### ISSUE TITLE
[BUG] Method 'GetMapStaticImageAsync' throws 'NullReferenceException' when pathes used.

### ISSUE THREAD

**Issue by melwynoo** [Azure/azure-sdk-for-net#38587]
### Library name and version

Azure.Maps.Rendering 1.0.0-beta.2

### Describe the bug

When I call the 'GetMapStaticImageAsync' method of the 'MapsRenderingClient' class specifying paths, the method throws a NullReferenceException.

A quick look at the code of the async method showed that when the list for the paths was created, the list for the pins was accidentally created a second time. 

The code part is identical to that of the non-async routine, except that the correct list is initialised there.

![grafik](https://github.com/Azure/azure-sdk-for-net/assets/20420971/7b4ab314-78e6-4b0d-a35b-f9e21ab1efe9)

### Expected behavior

The async method 'GetMapStaticImageAsync' does not throw a NullReferenceException if a list of paths is specified.

### Actual behavior

The async method 'GetMapStaticImageAsync' throws a NullReferenceException if a list of paths is specified.

### Reproduction Steps

- Create a valid 'GeoPosition'.
- Create an 'ImagePathStyle' with that position,
- Create a list of 'ImagePathStyle's with the given 'ImagePathStyle'
- Create a 'GetMapStaticImageOptions' with the given list of 'ImagePathStyle's
- Call the method 'GetMapStaticImageAsync' with the given options.

Code example:
```
var credentials = new AzureKeyCredential(key);
var client = new MapsRenderingClient(credentials);

var position = new GeoPosition(7, 51);

var path = new ImagePathStyle(new[] { position })
{
	CircleRadiusInMeters = 300,
	LineColor = Color.Gray,
	LineWidthInPixels = 3
};

var pathes = new List<ImagePathStyle> { path };

var imageOptions =new GetMapStaticImageOptions(position, 256, 256, null, pathes)
{
	ZoomLevel = 14,
	MapImageStyle = MapImageStyle.Main,
	Language = RenderingLanguage.German
};

var response = await client.GetMapStaticImageAsync(imageOptions);
```

### Environment

- Windows 11
- Microsoft Visual Studio Professional 2022 (64-bit) Version 17.6.4
- Microsoft.NETCore.App 7.0.7
- Microsoft.AspNetCore.App 7.0.7
- Azure.Maps.Rendering 1.0.0-beta.2

**Comment by dubiety** [comment]
Hi @melwynoo , thank you for reporting this issue. We'll fix this issue soon!
