### ISSUE TITLE
How to lock a resource with ARM client?

### ISSUE THREAD

**Issue by ChengleiYuan** [Azure/azure-sdk-for-net#38582]
How to lock a resource with ARM client?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ff19f954-5f7d-1060-d9e2-839144e6aed4
* Version Independent ID: d4801c03-6188-23e6-9e74-18214d994523
* Content: [ManagementLockResource Class (Azure.ResourceManager.Resources) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.resources.managementlockresource?view=azure-dotnet)
* Content Source: [xml/Azure.ResourceManager.Resources/ManagementLockResource.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.ResourceManager.Resources/ManagementLockResource.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ChengleiYuan** [comment]
Thank you @jsquire. I have found a way to created new locks:

```
ManagementLockCollection locks = resource.GetManagementLocks();

ManagementLockResource newlock = (await locks.CreateOrUpdateAsync(WaitUntil.Completed, lockkName, new ManagementLockData(ManagementLockLevel.ReadOnly))).Value;
```

**Comment by ChengleiYuan** [comment]
Close as the issues is resolved.
