### ISSUE TITLE
[FEATURE REQ] update Azure.ResourceManager.Avs to 2023-03-01 API

### ISSUE THREAD

**Issue by cataggar** [Azure/azure-sdk-for-net#38591]
### Library name

Azure.ResourceManager.Avs

### Please describe the feature.

The .NET team created and published several versions of [Azure.ResourceMager.Avs](https://www.nuget.org/packages/Azure.ResourceManager.Avs/). Thank you! Will you continue publishing updates? Or is my team expected to[ do the updates](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/78/Mgmt-.NET-SDK-release-process?anchor=sdk-generation-from-updated-spec)? We need the SDK updated to the 2023-03-01 API.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Yes @cataggar, please follow the guide to upgrade and release the new version by yourself.
