### ISSUE TITLE
[docs] Blob CreateOrReplace should better explain the blob-exists exception

### ISSUE THREAD

**Issue by MV10** [Azure/azure-sdk-for-net#3860]
Azure's Blob Storage classes have [CreateOrReplace](https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.blob.cloudappendblob.createorreplace?view=azure-dotnet) methods which include this same statement:

> To throw an exception if the blob exists, instead of overwriting, pass in an AccessCondition object generated using GenerateIfNotExistsCondition().

I suggest the word "exception" should reference [StorageException](https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.storageexception?view=azure-dotnet) and the statements should specifically explain that an HTTP 409 (Conflict) is returned when the object already exists.

There's no way for a developer to know what to expect based on the documentation alone.

**Comment by blueww** [comment]
@MV10 

The api in your issue is not from this repo, but from https://github.com/Azure/azure-storage-net
Please open a issue in https://github.com/Azure/azure-storage-net, and close this one.

Thanks!
