### ISSUE TITLE
[QUERY] Best practices for implementing `TokenCredential` class. 

### ISSUE THREAD

**Issue by pratyush-prateek** [Azure/azure-sdk-for-net#38601]
### Library name and version

Azure.Core 1.34.0

## Query

What are some best practices we need to adhere to while implementing the `TokenCredential` abstract class. We have our own logic of fetching tokens from AAD by calling a different RP. Do we have to include any sort of caching mechanism? Also, there are two methods `GetTokenAsync` and `GetToken`. What is the significance of implementing the non-async method here? Will it be just like calling the async method and waiting for completion?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @pratyush-prateek 

> What are some best practices we need to adhere to while implementing the TokenCredential abstract class.

Here is some [general guidance](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/samples/DefiningCustomCredentialTypes.md).


> Do we have to include any sort of caching mechanism? 

You don't have to implement caching, but depending on the use cases of your application, it may be good to do for performance reasons.

> Also, there are two methods GetTokenAsync and GetToken. What is the significance of implementing the non-async method here? Will it be just like calling the async method and waiting for completion?

If your code will not use the sync path, there is no need to fully implement it. But, generally, the sync implementation would be the same, just without any async depenencies.

**Comment by pratyush-prateek** [comment]
Thanks @christothes. The implementation of this class is used by various azure resource libraries, such as cosmos SDK. So, do we need to ask them
what they want us to implement in GetToken function, is it just actual logic without async or anything specific?

Another question I had is, let’s say my implementation of TokenCredential has some disposable object refererences. In that case, do we also need to implement IDisposable?

**Comment by christothes** [comment]
> Thanks @christothes. The implementation of this class is used by various azure resource libraries, such as cosmos SDK. So, do we need to ask them what they want us to implement in GetToken function, is it just actual logic without async or anything specific?

It should just be the same code but with sync paths where possible.

> Another question I had is, let’s say my implementation of TokenCredential has some disposable object refererences. In that case, do we also need to implement IDisposable?

Yes, that is considered a best practice, unless you are delegating ownership of the disposable object to the caller.
