### ISSUE TITLE
[BUG] Intermittent errors tagging resources: GetGenericResource(...) caching API versions not supported by all ARM request regions resulting in `No registered resource provider found for location`

### ISSUE THREAD

**Issue by bradleyjford** [Azure/azure-sdk-for-net#38615]
### Library name and version

Azure.ResourceManager 1.7

### Describe the bug

We are observing frequent intermittent errors when tagging resources (Generic Resources)

```
No registered resource provider found for location 'westus2' and API version '2023-06-01' for type 'publicIPAddresses'. The supported api-versions are '2014-12-01-preview, 2015-05-01-preview, 2015-06-15, 2016-03-30, 2016-06-01, 2016-07-01, 2016-08-01, 2016-09-01, 2016-10-01, 2016-11-01, 2016-12-01, 2017-03-01, 2017-04-01, 2017-06-01, 2017-08-01, 2017-09-01, 2017-10-01, 2017-11-01, 2018-01-01, 2018-02-01, 2018-03-01, 2018-04-01, 2018-05-01, 2018-06-01, 2018-07-01, 2018-08-01, 2018-10-01, 2018-11-01, 2018-12-01, 2019-02-01, 2019-04-01, 2019-06-01, 2019-07-01, 2019-08-01, 2019-09-01, 2019-11-01, 2019-12-01, 2020-01-01, 2020-03-01, 2020-04-01, 2020-05-01, 2020-06-01, 2020-07-01, 2020-08-01, 2020-11-01, 2021-01-01, 2021-02-01, 2021-03-01, 2021-04-01, 2021-05-01, 2021-06-01, 2021-08-01, 2021-12-01, 2022-01-01, 2022-05-01, 2022-07-01, 2022-09-01, 2022-11-01, 2023-02-01, 2023-04-01, 2023-05-01'. The supported locations are 'westus, eastus, northeurope, westeurope, eastasia, southeastasia, northcentralus, southcentralus, centralus, eastus2, japaneast, japanwest, brazilsouth, australiaeast, australiasoutheast, centralindia, southindia, westindia, canadacentral, canadaeast, westcentralus, westus2, ukwest, uksouth, koreacentral, koreasouth, francecentral, australiacentral, southafricanorth, uaenorth, switzerlandnorth, germanywestcentral, norwayeast, westus3, jioindiawest, swedencentral, qatarcentral, polandcentral, italynorth'.
Status: 400 (Bad Request)
ErrorCode: NoRegisteredProviderFound
```   

We retrieve resources using `var resource = await armClient.GetGenericResource(resourceIdentifier).GetAsync();` and then attempt to apply tags using `await resource.AddTagAsync("tagname", "value");`

I suspect these errors may be due to how API versions are retrieved and [cached for the resource type namespace](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/resourcemanager/Azure.ResourceManager/src/Resources/Custom/ResourceProviderCollection.cs#L70). Should all ARM request regions not support the cached version of the API, subsequent requests may result in the above error.

We are using the default ARM endpoint (`management.azure.com`) however during our investigation we observed that different ARM regions support different versions of APIs.

eg.
`westus.management.azure.com` supports API version `2023-06-01` for `Microsoft.Network/publicIPAddresses` (and others) whereas `westus2.management.azure.com` does not (the latest being `2023-05-01`). If the initial request (to `management.azure.com`) is served by the `westus` ARM Request Region, `2023-06-01` is cached for the resource type and all subsequent requests will attempt to use this version resulting in the following error.

To confirm that different versions were available in different request regions, the following Powershell commands were used.

```
Get-AzEnvironment -Name AzureCloud | Set-AzEnvironment -Name OverrideTest
Set-AzEnvironment -Name OverrideTest -ResourceManagerUrl https://westus.management.azure.com/
((Get-AzResourceProvider -Debug -ProviderNamespace Microsoft.Network).ResourceTypes | Where-Object ResourceTypeName -eq publicIPAddresses)
```

```
          'resourceType': 'publicIPAddresses',
          'locations': [
            'West US',
            'East US',
            'North Europe',
            'West Europe',
            'East Asia',
            'Southeast Asia',
            'North Central US',
            'South Central US',
            'Central US',
            'East US 2',
            'Japan East',
            'Japan West',
            'Brazil South',
            'Australia East',
            'Australia Southeast',
            'Central India',
            'South India',
            'West India',
            'Canada Central',
            'Canada East',
            'West Central US',
            'West US 2',
            'UK West',
            'UK South',
            'Korea Central',
            'Korea South',
            'France Central',
            'Australia Central',
            'South Africa North',
            'UAE North',
            'Switzerland North',
            'Germany West Central',
            'Norway East',
            'West US 3',
            'Sweden Central',
            'Qatar Central',
            'Poland Central'
          ],
          'apiVersions': [
            '2023-06-01',
            '2023-05-01',
            '2023-04-01',
            '2023-02-01',
            ... (truncated)
          ],
```

```
Set-AzEnvironment -Name OverrideTest -ResourceManagerUrl https://westus2.management.azure.com/
((Get-AzResourceProvider -Debug -ProviderNamespace Microsoft.Network).ResourceTypes | Where-Object ResourceTypeName -eq publicIPAddresses)
```

```    
      'resourceType': 'publicIPAddresses',
      'locations': [
        'West US',
        'East US',
        'North Europe',
        'West Europe',
        'East Asia',
        'Southeast Asia',
        'North Central US',
        'South Central US',
        'Central US',
        'East US 2',
        'Japan East',
        'Japan West',
        'Brazil South',
        'Australia East',
        'Australia Southeast',
        'Central India',
        'South India',
        'West India',
        'Canada Central',
        'Canada East',
        'West Central US',
        'West US 2',
        'UK West',
        'UK South',
        'Korea Central',
        'Korea South',
        'France Central',
        'Australia Central',
        'South Africa North',
        'UAE North',
        'Switzerland North',
        'Germany West Central',
        'Norway East',
        'West US 3',
        'Sweden Central',
        'Qatar Central',
        'Poland Central'
      ],
      'apiVersions': [
        '2023-05-01',
        '2023-04-01',
        '2023-02-01',
        ... (truncated)
      ],
```

### Expected behavior

Successful tagging of all resources

### Actual behavior

No registered resource provider found for location 'westus2' and API version '2023-06-01' for type 'publicIPAddresses'. The supported api-versions are '2014-12-01-preview, 2015-05-01-preview, 2015-06-15, 2016-03-30, 2016-06-01, 2016-07-01, 2016-08-01, 2016-09-01, 2016-10-01, 2016-11-01, 2016-12-01, 2017-03-01, 2017-04-01, 2017-06-01, 2017-08-01, 2017-09-01, 2017-10-01, 2017-11-01, 2018-01-01, 2018-02-01, 2018-03-01, 2018-04-01, 2018-05-01, 2018-06-01, 2018-07-01, 2018-08-01, 2018-10-01, 2018-11-01, 2018-12-01, 2019-02-01, 2019-04-01, 2019-06-01, 2019-07-01, 2019-08-01, 2019-09-01, 2019-11-01, 2019-12-01, 2020-01-01, 2020-03-01, 2020-04-01, 2020-05-01, 2020-06-01, 2020-07-01, 2020-08-01, 2020-11-01, 2021-01-01, 2021-02-01, 2021-03-01, 2021-04-01, 2021-05-01, 2021-06-01, 2021-08-01, 2021-12-01, 2022-01-01, 2022-05-01, 2022-07-01, 2022-09-01, 2022-11-01, 2023-02-01, 2023-04-01, 2023-05-01'. The supported locations are 'westus, eastus, northeurope, westeurope, eastasia, southeastasia, northcentralus, southcentralus, centralus, eastus2, japaneast, japanwest, brazilsouth, australiaeast, australiasoutheast, centralindia, southindia, westindia, canadacentral, canadaeast, westcentralus, westus2, ukwest, uksouth, koreacentral, koreasouth, francecentral, australiacentral, southafricanorth, uaenorth, switzerlandnorth, germanywestcentral, norwayeast, westus3, jioindiawest, swedencentral, qatarcentral, polandcentral, italynorth'.
Status: 400 (Bad Request)
ErrorCode: NoRegisteredProviderFound

### Reproduction Steps

This is difficult to reproduce as I suspect this is a result of the load balancing applied to `management.azure.com` and which ARM Request Region handles the initial Generic Resource query for a given resource type namespace and then another request region processing subsequent requests.

### Environment

Azure Functions app

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Hey @bradleyjford , thank you for reaching out to us about the Azure SDK for .NET. Unfortunately, this issue is related to the service side and not the SDK side, so we are not able to help you with it. Therefore, we are closing this issue for now. If you need more assistance, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). We apologize for any inconvenience this may cause you.

We value your feedback and we want to make sure that your problem is solved. If you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.
