### ISSUE TITLE
[BUG] Blob copy from StorageAccount (on Azure) and local Azurite

### ISSUE THREAD

**Issue by VincenzoCarlino** [Azure/azure-sdk-for-net#38659]
### Library name and version

Azure.Storage.Blobs 12.17.0

### Describe the bug

If a try to copy a Blob from a container on Azure to my local Azurite I get the following error:
![image](https://github.com/Azure/azure-sdk-for-net/assets/34278520/7d4ed022-053a-494b-a998-0ed9d612498c)

If I change the target container to a storage account on Azure, everything works.
Here is a snippet of my code:
```csharp
var sourceBlob = new BlobContainerClient("sourceconnectionstring", "sourcecontainername")
    .GetBlobClient("sourceblob");
var sourceBlobSasToken = sourceBlob.GenerateSasUri(BlobSasPermissions.All, DateTimeOffset.Now.AddHours(10));

var targetBlob = new BlobContainerClient("targetconnectionstring", "targetcontainername")
    .GetBlobClient("targetblob");

var copyOperation = await targetBlob.StartCopyFromUriAsync(sourceBlobSasToken,
    options: new BlobCopyFromUriOptions() { }, ct);
await copyOperation.WaitForCompletionAsync(ct);
```

If I go on my azurite docker container, I see a PUT request that fails with 404.

I've also enabled public access level to: "Public read access for container and blobs" on my container in Azurite.

### Expected behavior

Copy a blob from StorageAccount (on Azure) to my local Azurite.

### Actual behavior

I got an exception from the SDK saying that specified resource does not exist.

### Reproduction Steps

Just run the code pasted above using as target blob Azurite and source blob a StorageAccount on Azure.

**Comment by blueww** [comment]
@VincenzoCarlino 

This is a limitation in Azurite, you can see if from Azurite Readme. 
Azurite only support blob copy within same Azurite instance. https://github.com/Azure/azurite#:~:text=Snapshot%20Blob-,Copy%20Blob%20(Only%20supports%20copy%20within%20same%20Azurite%20instance,-)

**Comment by navba-MSFT** [comment]
@VincenzoCarlino Thanks for reaching out to us and reporting this issue. I hope you had a chance to see the [above comment ](https://github.com/Azure/azure-sdk-for-net/issues/38659#issuecomment-1717230085)and follow the suggestion shared above. If you have any follow-up questions, please do let us know.
