### ISSUE TITLE
[QUERY] Azure cli is throwing error when I use it to list the vms/disks

### ISSUE THREAD

**Issue by enuguris** [Azure/azure-sdk-for-net#38665]
### Library name and version

az cli version 2.38.0

### Query/Question

When I try to list vms or disks using the azure cli command it is throwing me the below error. These commands worked fine until yesterday and today we started observing these errors.  Your help to resolve this issue is greatly appreciated.

 az vm list -o table
(ProviderError) Resource provider 'Microsoft.Compute' failed to return collection response for type 'virtualMachines'.
Code: ProviderError
Message: Resource provider 'Microsoft.Compute' failed to return collection response for type 'virtualMachines'.

az disk list -o table
(ProviderError) Resource provider 'Microsoft.Compute' failed to return collection response for type 'disks'.
Code: ProviderError
Message: Resource provider 'Microsoft.Compute' failed to return collection response for type 'disks'.

### Environment

We are using the az cli on a RHEL 7  server

**Comment by jsquire** [comment]
This issue has been transferred to the Azure CLI repository as  [#27397](https://github.com/Azure/azure-cli/issues/27397).
