### ISSUE TITLE
[BUG] ExportDataset.Columns is read-only and has no setter

### ISSUE THREAD

**Issue by vexingpos** [Azure/azure-sdk-for-net#38679]
### Library name and version

Azure.ResourceManager.CostManagement 1.0.0

### Describe the bug

The `Columns` property in `Azure.ResourceManager.CostManagement.Models.ExportDataset` has a getter but **no setter**

This prevents a user from being able to define which columns they want when setting up a Cost Export.

### Expected behavior

It should be possible to set a value for `Columns`

### Actual behavior

Cannot define/set a list of columns for a cost export.

```
Error	CS0200	Property or indexer 'ExportDataset.Columns' cannot be assigned to -- it is read only
````

### Reproduction Steps

```csharp
IList<string> listOfColumns;
listOfColumns.Add("BillingAccountId");

var exportProperties = new CostManagementExportData
{
    Format = ExportFormatType.Csv,
    Definition = new ExportDefinition(ExportType.AmortizedCost, TimeframeType.Custom)
    {
        DataSet = new ExportDataset()
        {
            Columns = listOfColumns,  //<<<<<<<<<< fails here
            Granularity = GranularityType.Daily,
        },
        ExportType = ExportType.AmortizedCost,
        Timeframe = TimeframeType.Custom,
        TimePeriod = new ExportTimePeriod(DateTimeOffset.MinValue, DateTimeOffset.MaxValue),
    },
    Schedule = new ExportSchedule()
    {
        Status = ExportScheduleStatusType.Inactive
    },
    DeliveryInfoDestination = new ExportDeliveryDestination(container)
    {
        Container = container,
        ResourceId = storageId,
        RootFolderPath = exportType
    }
};
```

### Environment

Hosting platform
```
PS C:\Users\me> dotnet --info
.NET SDK:
 Version:   7.0.400
 Commit:    73bf45718d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.400\

Host:
  Version:      7.0.10
  Architecture: x64
  Commit:       a6dbb800a4

.NET SDKs installed:
  7.0.400 [C:\Program Files\dotnet\sdk]

```

IDE

```
Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.7.2
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Hey @vexingpos , thank you for reaching us.
The ExportDataset.Columns is a [IList<string> collection](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.ilist-1?view=net-7.0) which you can use its method for add / remove, not set a new collection.

**Comment by vexingpos** [comment]
Hi @ArthurMa1978 

So the correct syntax should be like this?

````c#
Columns = {  "AccountName" , "AccountOwnerId" , "ConsumedService" , ..... }
````

That works fine for me, but isn't ideal if you have a large number of columns. 

Is there no way to have a variable/method call assigned?
