### ISSUE TITLE
[BUG] DeserializeProcessThreadInfo failed

### ISSUE THREAD

**Issue by xieofxie** [Azure/azure-sdk-for-net#38690]
### Library name and version

appservice alpha version

### Describe the bug

when call SiteInstanceProcessResource.GetAsync, it throws

{
  "Message": "An error has occurred.",
  "ExceptionMessage": "The requested operation requires an element of type 'String', but the target element has type 'Number'.",
  "ExceptionType": "System.InvalidOperationException",
  "StackTrace": "   at System.Text.Json.JsonDocument.GetString(Int32 index, JsonTokenType expectedType)\r\n   at Azure.ResourceManager.AppService.Models.ProcessThreadInfo.DeserializeProcessThreadInfo(JsonElement element)\r\n   at Azure.ResourceManager.AppService.ProcessInfoData.DeserializeProcessInfoData(JsonElement element)\r\n   at Azure.ResourceManager.AppService.WebAppsRestOperations.<GetInstanceProcessAsync>d__327.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Azure.ResourceManager.AppService.SiteInstanceProcessResource.<GetAsync>d__17.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()\r\n   at Intercom.Actions.Shared.Controllers.ComputeControllerCore.<>c__DisplayClass6_1.<<GetProcessesAsync>b__1>d.MoveNext() in C:\\__w\\1\\s\\Intercom.Actions.Shared\\Controllers\\ComputeController.cs

I checked the code, doc and actual response, I think the definition for ProcessThreadInfo is wrong https://learn.microsoft.com/en-us/rest/api/appservice/web-apps/get-process#processthreadinfo

https://github.com/Azure/azure-sdk-for-net/blob/0a7502375061e1609ebda7f637151773d6a80a29/sdk/websites/Azure.ResourceManager.AppService/src/Generated/Models/ProcessThreadInfo.Serialization.cs#L86C41-L86C41

    "threads": [
      {
        "id": 4272,
        "href": "https://XX.scm.azurewebsites.net/api/processes/3284?api-version=2020-12-01/threads/4272",
        "state": "Wait"
      },

Note it is id is int instead of string and href and state are not in properties

### Expected behavior

work

### Actual behavior

not

### Reproduction Steps

call SiteInstanceProcessResource.GetAsync

**Comment by xieofxie** [comment]
The same issue exists for ProcessModuleInfo

https://learn.microsoft.com/en-us/rest/api/appservice/web-apps/get-process#processmoduleinfo

    "modules": [
      {
        "base_address": "67eb0000",
        "file_name": "Accessibility.ni.dll",
        "href": "https://XX.scm.azurewebsites.net/api/processes/3284?api-version=2020-12-01/modules/67eb0000",
        "file_version": "4.8.3761.0 built by: NET48REL1"
      },

**Comment by xieofxie** [comment]
In summary, they are different when you get it from process or process/thread
The doc is for getting directly from prcess/thread not for from process

**Comment by xieofxie** [comment]
spec https://github.com/Azure/azure-rest-api-specs/blob/main/specification/web/resource-manager/Microsoft.Web/stable/2022-09-01/WebApps.json#L27293C5-L27293C5 I think as a fast workaround, just ignore id when it is number

**Comment by xieofxie** [comment]
wait for App Service team to fix

**Comment by live1206** [comment]
There is nothing SDK team can do here, user already created ICM to the service team.
