### ISSUE TITLE
Default value is wrong

### ISSUE THREAD

**Issue by MartinDemberger** [Azure/azure-sdk-for-net#38740]
As you can see in https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/ConnectionPolicy.cs the default value is 6 second.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 17f88dfd-aa88-e817-8884-e2fd96c15110
* Version Independent ID: 7dba7648-4f99-e9a0-0c13-bf258ce92510
* Content: [CosmosClientOptions.RequestTimeout Property (Microsoft.Azure.Cosmos) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.cosmosclientoptions.requesttimeout?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Cosmos/CosmosClientOptions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/CosmosClientOptions.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.Azure.Cosmos` library is maintained as [#4084](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/4084).
