### ISSUE TITLE
[BUG] Azure.ResourceManager.Peering has a data model incompatible with IPv4-only peerings 

### ISSUE THREAD

**Issue by JonathanSaraco** [Azure/azure-sdk-for-net#38759]
### Library name and version

Azure.ResourceManager.Peering 1.1.0 and 1.2.0-beta.1

### Describe the bug

I am part of the team that owns Microsoft.Peering, and I am testing the SDK. There is an incompatibility with the data model in the SDK representing our resources. Within PeeringBgpSession, the IP address properties:

PeerSessionIPv4Address
PeerSessionIPv6Address
MicrosoftSessionIPv4Address
MicrosoftSessionIPv6Address

Are defined as IPAddress objects and not strings. In our service, we define these properties as strings. We do this because a valid case for a peering is to be IPv4 only. In which case, the IPv6 properties are null or an empty string. When I attempt to retrieve an IPv4-only peering using the SDK, a deserialization exception occurs when it tries to convert this string into an IPAddress object. The PeeringBgpSession model should have these properties as strings.

### Expected behavior

Peering resources that are IPv4 only should be properly deserialized into PeeringResource objects.

### Actual behavior

A deserialization error occurs when trying to get peering resources that are IPv4 only.

### Reproduction Steps

1. Create or obtain a peering resource with at least one null or empty IP address property
2. Use Azure.ResourceManager.Peering to GetPeering()
3. Observe the deserialization exception that occurs

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Hey @JonathanSaraco, thank you for reporting this issue to us, we will release a fix soon.
