### ISSUE TITLE
[FEATURE REQ] OTel Exporter: Report metrics for existing app

### ISSUE THREAD

**Issue by gopland-pinc** [Azure/azure-sdk-for-net#38750]
### Library name

Azure.Monitor.OpenTelemetry.Exporter

### Please describe the feature.

Am I missing something or is there no auto-instrumentation feature for feeding OpenTelemetry metrics to Azure Monitor ?

There is the Azure Monitor Application Insights Agent which seems to be an Application Insights-specific way of auto-instrumenting existing applications to send metrics (only for ASP.NET Core applications?) to Application Insights.

And there is the OpenTelemetry .NET Automatic Instrumentation which I think would do what I want if there were an Azure Monitor / Application Insights Exporter option I could enable in OTEL_TRACES_EXPORTER or OTEL_LOGS_EXPORTER environment variables.

The idea being that I want to send metrics from existing applications to Azure Monitor without having to modify the application's code.  If I have to run an agent I guess that's ok, but this should work for ASP.NET Core AND Console .NET Core applications.

Thank you

**Comment by cijothomas** [comment]
>  is there no auto-instrumentation feature for feeding OpenTelemetry metrics to Azure Monitor ?

Correct. Such feature do not exist today.
