### ISSUE TITLE
Repo-Tasks not functional

### ISSUE THREAD

**Issue by montgomp** [Azure/azure-sdk-for-net#3877]
### PowerShell Version
5.1.16299.64
### OS Version
10.0.16399.64
### Description
The Repo-Tasks.psd1 fails to load and therefore none of its commands are functional. 
### Script/Steps for Reproduction
Double-Click PS-VSPrompt
Type: Import-Module .\Repo-Tasks.psd1
Hit Enter. Receive error "Loading skipped. 'psuserpreferences' environment variable was not set to load user preferences.".
Type: Start-Build
Hit Enter. Receive error for missing msbuild "msbuild.exe : The term 'msbuild.exe' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At E:\Repos\azure-sdk-for-net\tools\Repo-Tasks.psm1:326 char:8"

**Comment by shahabhijeet** [comment]
@montgomp please do not use this module as it's not being actively fixed/supported.
Please use regular msbuild.exe to build the .NET SDK repo.
