### ISSUE TITLE
[BUG] Unnecessary options Configure call in Azure.Monitor.OpenTelemetry.AspNetCore

### ISSUE THREAD

**Issue by amis92** [Azure/azure-sdk-for-net#38787]
### Library name and version

Azure.Monitor.OpenTelemetry.AspNetCore 1.0.0-beta.6

### Describe the bug

There's an unnecessary/nonsense object instantiation in the following code: `builder.UseAzureMonitor(o => o = new AzureMonitorOptions())`. The assignment has no impact on actual configured options instance, as it is a local lambda variable/parameter being "overwritten". It's a nonsense code in general.

https://github.com/Azure/azure-sdk-for-net/blob/a35f47a9c74df644a3755e73ec5a8b82a32de105/sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/src/OpenTelemetryBuilderExtensions.cs#L55

### Expected behavior

A `null` lambda is passed, or an empty-bodied lambda is passed. Preferable a null lambda, because then it won't be registered in DI container and take up space in options-configuration-pipeline. However, the API contract is non-nullable and so it might be unwanted. Were it nullable, I'd happily open a PR, but in current situation a decision is necessary.

### Actual behavior

An essentially no-op lambda is passed (which creates a throw-away object instance in the process), and then gets registered into Options-configuration pipeline, which makes no sense.

### Reproduction Steps

It's a code nitpick, non-reproducible.

### Environment

Not applicable.

**Comment by rajkumar-rangaraj** [comment]
@amis92 Thanks for your feedback. Would you mind creating a PR with the proposed changes?

**Comment by amis92** [comment]
It probably deserves another issue/pr, but while in there, it confused me that the no-param method does additional calls in contrary to the configure-lambda call. It's not intuitive, especially given previous art in such extensions from runtime or aspnetcore. Commonly, a method without `configureOptions` does base job, while the method accepting `configureOptions` simply calls both the first method and adds the configureOptions to IOptions setup. Random example:

https://github.com/dotnet/aspnetcore/blob/d765d7ba4871a8c2cb38d4134553d3be9a7370d7/src/DataProtection/DataProtection/src/DataProtectionServiceCollectionExtensions.cs#L32-L57

What some may find confusing is that in case a person wants to customize say just `SamplingRatio`, and calls the overload with `configureAzureMonitor` parameter, the `DefaultAzureMonitorOptions` will not be added and executed, thus leaving the monitor not configured.
