### ISSUE TITLE
[BUG] TelemetryDetails.EscapeProductInformation throws FileNotFoundException (System.Net.Http)

### ISSUE THREAD

**Issue by TimLovellSmith** [Azure/azure-sdk-for-net#38803]
### Library name and version

Azure.Core 1.35.0

### Describe the bug

I'm trying to use Azure.Storage.Blobs 12.13.0, together with 12.12.0, and Azure.Core 1.35.0.

Unfortunately they seem to be blowing up while creating telemery for my HTTP pipeline that they're about to use to send requests to blob storage :-(.

Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
at Azure.Core.TelemetryDetails.EscapeProductInformation(System.String)
at Azure.Core.TelemetryDetails.GenerateUserAgentString(System.Reflection.Assembly, System.String, Azure.Core.RuntimeInformationWrapper)
at Azure.Core.TelemetryDetails..ctor(System.Reflection.Assembly, System.String, Azure.Core.RuntimeInformationWrapper)
at Azure.Core.Pipeline.HttpPipelineBuilder.CreateTelemetryPolicy(Azure.Core.ClientOptions)
at Azure.Core.Pipeline.HttpPipelineBuilder.BuildInternal(Azure.Core.Pipeline.HttpPipelineOptions, Azure.Core.Pipeline.HttpPipelineTransportOptions)
at Azure.Core.Pipeline.HttpPipelineBuilder.Build(Azure.Core.ClientOptions, Azure.Core.Pipeline.HttpPipelinePolicy[], Azure.Core.Pipeline.HttpPipelinePolicy[], Azure.Core.ResponseClassifier)
at Azure.Storage.StorageClientOptions.Build(Azure.Core.ClientOptions, Azure.Core.Pipeline.HttpPipelinePolicy, System.Uri)
at Azure.Storage.Blobs.Specialized.BlobBaseClient..ctor(System.Uri, Azure.Core.Pipeline.HttpPipelinePolicy, Azure.Storage.Blobs.BlobClientOptions, Azure.Storage.StorageSharedKeyCredential)

Based on the latest code I see for this, I have no idea how it could get a FileNotFoundException, so I suppose next logical thing to do is update to a newer version of Azure.Core.... except Azure.Core 1.35.0 *is* the latest one, isn't it?

### Expected behavior

No crash (I wish)

### Actual behavior

Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

### Reproduction Steps

Run in production, trying to authenticate with ManagedIdentity to storage, at startup time, to download a blob.

```
                    Uri blobServiceUri = new Uri(new Uri(blobUrl, UriKind.Absolute).GetLeftPart(UriPartial.Authority), UriKind.Absolute);
                    var tmpBlob = new BlobClient(new Uri(blobUrl));
                    var client = new BlobServiceClient(blobServiceUri, new DefaultAzureCredential());
                    var bsc = client.GetBlobContainerClient(tmpBlob.BlobContainerName).GetBlobClient(tmpBlob.Name);
                    var ms = new MemoryStream();
                    var response = bsc.DownloadTo(ms);
                    Logger.LogInfo($"download response is {response.Status}");
```

### Environment

Windows Server 2022's default install of .Net Framework.

**Comment by TimLovellSmith** [comment]
Although I still don't understand the error...
Seems like it could possibly have been introduced in this commit:

https://github.com/Azure/azure-sdk-for-net/commit/384607bdfb1739c3b8bdbdcc1cfbc6c839442abb#diff-30e1d17e7b7f1af528151f06fb3dd5f932b68367b54adc1c98bc6f33a0084c4d

if I am so lucky, then perhaps all I need to do is go back in time an earlier version of Azure.Core, from 8 months ago?

**Comment by TimLovellSmith** [comment]
Or... I could try to update the Storage libraries...

**Comment by TimLovellSmith** [comment]
When I load up Azure.Core with ildasm, it seems like the only non-dotnet-framework (built-in) assembly it could be trying to load here is

```
.assembly extern System.Diagnostics.DiagnosticSource
{
  .publickeytoken = (CC 7B 13 FF CD 2D DD 51 )                         // .{...-.Q
  .ver 6:0:0:1
}
```

**Comment by TimLovellSmith** [comment]
Isn't that a .Net Core assembly though?
HMm...

<html>
<body>


.NET | Core 1.0, Core 1.1, Core 2.0, Core 2.1, Core 2.2, Core 3.0, Core 3.1, 5, 6, 7, 8
-- | --



</body>
</html>

**Comment by TimLovellSmith** [comment]
No, there's nuget packages for it for .Net Framework too...

**Comment by TimLovellSmith** [comment]
Now I got symbols and line numbers...

Azure_Core!Azure.Core.TelemetryDetails.EscapeProductInformation+0x1
Azure_Core!Azure.Core.TelemetryDetails.GenerateUserAgentString+0x177 [/_/sdk/core/Azure.Core/src/TelemetryDetails.cs @ 91]
Azure_Core!Azure.Core.TelemetryDetails..ctor+0x4a [/_/sdk/core/Azure.Core/src/TelemetryDetails.cs @ 53]
Azure_Core!Azure.Core.Pipeline.HttpPipelineBuilder.CreateTelemetryPolicy+0x5c [/_/sdk/core/Azure.Core/src/Pipeline/HttpPipelineBuilder.cs @ 220]
Azure_Core!Azure.Core.Pipeline.HttpPipelineBuilder.BuildInternal+0x208 [/_/sdk/core/Azure.Core/src/Pipeline/HttpPipelineBuilder.cs @ 152]
Azure_Core!Azure.Core.Pipeline.HttpPipelineBuilder.Build+0xc5 [/_/sdk/core/Azure.Core/src/Pipeline/HttpPipelineBuilder.cs @ 46]
Azure_Storage_Blobs!Azure.Storage.StorageClientOptions.Build+0x135 [/_/sdk/storage/Azure.Storage.Common/src/Shared/StorageClientOptions.cs @ 120]
Azure_Storage_Blobs!Azure.Storage.Blobs.Specialized.BlobBaseClient..ctor+0x199 [/_/sdk/storage/Azure.Storage.Blobs/src/BlobBaseClient.cs @ 362]

**Comment by TimLovellSmith** [comment]
Sigh...

Could not load file or assembly &#39;System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&#39; or one of its dependencies. The system cannot find the file specified.

Is this the fault of my binding redirects? :(

**Comment by TimLovellSmith** [comment]
Wow, I wonder which one of these answers is the right one:

https://stackoverflow.com/questions/47149345/could-not-load-file-or-assembly-system-net-http

**Comment by TimLovellSmith** [comment]
Adding the System.Net.Http assembly reference to the project , and removing the binding redirect sounds fairly logical....

**Comment by TimLovellSmith** [comment]
Logical yes, correct...? unverified.
But apparently this one works.

```
<dependentAssembly>
    <assemblyIdentity name="System.Net.Http" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-4.2.0.0" newVersion="4.0.0.0" />
</dependentAssembly>
```
https://stackoverflow.com/a/57214989

**Comment by TimLovellSmith** [comment]
Looks like the blame for this is mainly https://github.com/dotnet/runtime/issues/24382 (combined with whatever I had in my old config file...?)

Can anything be done to mitigate the damage in the consuming packages like Azure.Core? I have no idea.

**Comment by jsquire** [comment]
Hi @TimLovellSmith.  Thank you for reaching out and we regret that you're experiencing difficulties.  Unfortunately, there's nothing that the library can do to mitigate, as the root cause of this is the binding behavior in the .NET desktop framework and how transitive dependencies are resolved.  In a case such as yours where the hierarchy of dependencies has conflicts, you'll normally want to add a direct reference to the application so that the version takes precedence and hoists it for all other references.  I'm glad to hear that you were able to resolve this for your scenario and are no longer blocked.

**Comment by TimLovellSmith** [comment]
TBH, I haven't quite *finished* resolving it in my scenario.... I just got past the first case where we throw that error.

In general this did feel like a total pit of failure... and I'm also not sure there is nothing you can do to fix the issue?

It seems to me that the problem is something to do with the **.net framework** version of Azure.Core assembly referencing the System.Net.Http version 4.2.0.0, instead of a later version, when targeting .net 4.7.2... but why would that happen?

It seems like there's a v472 specific Azure.Core assembly to target... so why doesn't it just work, when running on .Net 4.7.2?!

C:\Users\tilovell\.nuget\packages\azure.core\1.35.0\lib\net472

Well, its because you have an assembly reference to 4.2.0.0 version baked into your DLL there.

But isn't that the wrong version, if you are targetting .net framework v4.7.2?

Instead of 

```
.assembly extern System.Net.Http
{
  .publickeytoken = (B0 3F 5F 7F 11 D5 0A 3A )                        
  .ver 4:2:0:0
}
```

you should have

```
.assembly extern System.Net.Http
{
  .publickeytoken = (B0 3F 5F 7F 11 D5 0A 3A )
  .ver 4:0:0:0
}
```

right?

**Comment by jsquire** [comment]
@ViktorHofer :  Would you please share your thoughts on the above version question?

**Comment by jsquire** [comment]
Not my intent to seem dismissive, @TimLovellSmith, so please excuse me if I came off that way.   Unless I misunderstand, your scenario involves multiple libraries with Azure.Core of different versions, some of which are a year old.   This general scenario is something that we receive occasional inquiries about and which we've spent time investigating.  At present, we do not believe that the problem can be solved in the general case by a library.   

In the case of the `net472` target, this was a recent addition to Core to allow for binding directly to the type included as part of the framework, rather than the compatibility package.  This target does not appear in the older versions, so there are two different instances of `System.Net.Http` being pulled in from different sources.   As for why the specific version was chosen, Viktor, who I looped in above, would be best positioned to speak to that.

**Comment by TimLovellSmith** [comment]
My curent theory is that the issue is not caused by the whole set of libraries, but that its caused only by compiling with Azure.Core and targeting .Net Framework. I'll work on testing this theory further.

**Comment by TimLovellSmith** [comment]
Having played with it a little while, it seems like my theory is off: the above is **not** enough to reproduce the issue, and its probably also actually something to do with which other libraries the project references. :(
