### ISSUE TITLE
[QUERY] FormRecognizer - How Can I get an Output Like in the Studio? (paragraphs/tables in order per page)

### ISSUE THREAD

**Issue by adammpolak** [Azure/azure-sdk-for-net#38855]
### Library name and version

Azure.AI.FormRecognizer 4.1.0.0

### Query/Question

Currently results returns "pages" which has "lines"
There is also an output called "paragraphs"
There is also an output "tables"

The data in "tables" also shows up in "paragraphs".

I want a data structure that is:

- page
  -   paragraph
  -   table
  -   paragraph
   
As they show up on the page. Which is how the studio represents the data:
![image](https://github.com/Azure/azure-sdk-for-net/assets/12940507/65d7ac4c-16f1-4a5f-bb46-a04a25783729)

What can I do to make the data output appear like it does in studio? Where the paragraphs and tables are in the right order with no overlapping data?

This is my current request code:
```   
 // NOTE: Ensure the client variable for the Form Recognizer is instantiated elsewhere in the program
    AnalyzeDocumentOperation operation = await client.AnalyzeDocumentAsync(WaitUntil.Completed, "prebuilt-layout", stream);
    AnalyzeResult result = operation.Value;
```

### Environment

.NET 6.0 running on linux containers, and Visual Studio locally on Windows.

**Comment by adammpolak** [comment]
@ctstone  any luck?

**Comment by ctstone** [comment]
@adammpolak , I think you would have to compute merged ordering using the provided bounding box of each page element (paragraph, table, etc.). Sorry, we do not support this output structure from the service itself.

**Comment by adammpolak** [comment]
> @adammpolak , I think you would have to compute merged ordering using the provided bounding box of each page element (paragraph, table, etc.). Sorry, we do not support this output structure from the service itself.

I ended up writing the code to do merge ordering but would be great if msft at one point releases whatever computation is being done to support the UI of Form Recognizer Studio.

**Comment by jsquire** [comment]
Looks like this was answered:  the formatting is custom to Studio and not something provided by the service.   Marking as addressed.
