### ISSUE TITLE
[Key Vault] Raise useful error when `KeyReleasePolicy` is incorrectly created

### ISSUE THREAD

**Issue by pallavit** [Azure/azure-sdk-for-net#38859]
The `KeyReleasePolicy` model expects an `encoded_policy` parameter as bytes. If a string is passed instead, no error is raised -- but when the created policy is provided to a `create_key` request, the service returns an error suggesting that the policy was never provided (see https://github.com/Azure/azure-sdk-for-python/issues/29945):
```
azure.core.exceptions.HttpResponseError: (BadParameter) AKV.SKR.1004: Exportable keys must have release policy.
```

This doesn't make the cause of the failure obvious at all. Though input validation is generally avoided, we should raise an error when a string is provided to the `KeyReleasePolicy` constructor so that users have an easier way to identify the problem.

**Comment by heaths** [comment]
The `KeyReleasePolicy` already [takes a `BinaryData`](https://github.com/Azure/azure-sdk-for-net/blob/5807d8ecee4a0c5d5682562642173276c56170ee/sdk/keyvault/Azure.Security.KeyVault.Keys/src/KeyReleasePolicy.cs#L35). Some other languages took a string and required that customers base64-encode their policies. That's not the case here.

We cannot - and should not, [according to guidelines](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-params-service-validation) - validate that the policy is valid client-side. Who's to say based on the schema whether plain text is wrong? Even if it's always base64-encoded, given the policy format is intentionally undocumented, what if a future versioned format could be valid base64 encoding? Take RFC3339 durations: `P30D` (30 days) is valid base64.
