### ISSUE TITLE
[BUG] ServiceBus ExpiresAt is set incorrectly when sending a cloned message

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-sdk-for-net#38875]
### Library name and version

Azure.Messaging.ServiceBus 7.16.1

### Describe the bug

When **cloning** a message w/o TTL and sending the new message to ASB w/o specifying TTL, the `ExpiresAt` should be set to the `EnqueuedTime` + `TimeToLive` according to [docs](https://azuresdkdocs.blob.core.windows.net/$web/dotnet/Azure.Messaging.ServiceBus/7.1.0/api/Azure.Messaging.ServiceBus/Azure.Messaging.ServiceBus.ServiceBusReceivedMessage.html#Azure_Messaging_ServiceBus_ServiceBusReceivedMessage_ExpiresAt).

>The UTC instant at which the message is marked for removal and no longer available for retrieval from the entity due to expiration. Expiry is controlled by the TimeToLive property and this property is computed from EnqueuedTime+TimeToLive

But that's not the behaviour for a "cloned" message using Azure.Messaging.ServiceBus 7.16.1+5a3f6c0a6c047e8bfa26cdf29ae2f5771ab08b2b w/o TTL on the message.

### Expected behavior

`ExpireAt` should be set to 9999-12-31 23:59 for messages w/o TTL on entities with TTL set to `TimeSpan.MaxValue` and no TTL on the originally received messages.

### Actual behavior

Messages cloned using

```
var clone = new ServiceBusMessage(serviceBusReceiveMessage);
```

and sent w/o TTL to an entity with TTL set to `TimeSpan.MaxValue` 
![image](https://github.com/Azure/azure-service-bus/assets/1309622/15194505-4aa6-4ef6-80c3-12c680e4236e)

have their `ExpiresAt` value set to less than 2 months into the future (49.17:02:47.2950000), unless a workaround is applied (highlighted entries, see below)
![image](https://github.com/Azure/azure-service-bus/assets/1309622/afe23ef0-bc85-47f4-be0d-7edc1d458ab8)

## Workaround

The workaround is to set the TTL on the cloned message to `TimeSpan.MaxValue`

```
clone.TimeToLive = TimeSpan.MaxValue;
```

### Reproduction Steps

```
var clone = new ServiceBusMessage(serviceBusReceiveMessage);
```

### Environment

.NET 6/7

**Comment by SeanFeldman** [comment]
I've peeked into the `public ServiceBusMessage(ServiceBusReceivedMessage receivedMessage)` constructor code to debug what happened. For a message with ID `350db999-2efd-497e-b2fb-f9df81306f31`, the TTL reported by the broker was right.

![image](https://github.com/Azure/azure-service-bus/assets/1309622/069793b5-1feb-44cb-982a-69633038ed6a)

But when the message was received and used to construct a new `ServiceBusMessage`, the received message TTL was the arbitrary `49.17:02:47.2950000` value. 

![image](https://github.com/Azure/azure-service-bus/assets/1309622/12db7a19-5181-4be5-9f98-2270df43c62a)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
It looks like this is happening because the Microsoft.Azure.Amqp library defines Ttl as a `uint` which has a max value of 4294967295, which in milliseconds would be translated to approximately 49 days. The AMQP spec  similarly defines the TTL as millisecond represented using a uint. I'm not sure how Service Bus explorer was showing a larger value, but is it possibly using SBMP?

**Comment by SeanFeldman** [comment]
SBE is using SBMP but it's only reflecting what's coming from the broker. And in this case the cloned message is what's coming from the broker. It's not very obvious in most scenarios unless you need the message to live longer than 49 days. And that's more of a bug than an improvement. I'm not blocked as I can workaround it but a proper behavior would be good to have ootb. Thanks, Josh.

**Comment by SeanFeldman** [comment]
@JoshLove-msft any updates on this?

**Comment by rmeshksar** [comment]
I am not sure the issue I am facing is the same or not. 

Consider an Azure Service Bus queue called **main** with DeadLetteringOnMessageExpiration = true and ForwardDeadLetteredMessagesTo = "**main.dlq**".

When a message is published to the main queue with some delay (future scheduledEnqueueTimeUtc) and that message is expired and forwarded to the main.dlq queue, the new message in the main.dlq queue still has the original message ExpiresAt value which is already in past time.

I am using MassTransit and it ignores messages with ExpiresAt in the past, and this message is not processed.

**Comment by SeanFeldman** [comment]
@rmeshksar that would be a service side, not the client SDK IMO. Dead-lettering and auto-forwarding are done by the [service](https://github.com/Azure/azure-service-bus/issues).

**Comment by rmeshksar** [comment]
I think it is client SDK and the value of the ExpiresAt is caculated is here:
https://github.com/rickmark/azure-sdk-for-net/blob/16ac6c4a31cb012560e4ccfd324433365e009ab6/sdk/servicebus/Azure.Messaging.ServiceBus/src/Primitives/ServiceBusReceivedMessage.cs#L366

Let me explain with an example (Screenshots from Azure portal)

At **13:52:09** a message is published to main queue with the delay of 60 seconds
![image](https://github.com/Azure/azure-sdk-for-net/assets/5131689/aa21004b-6773-4771-aca7-7d35beaa2a17)

Then when it is queued:
![image](https://github.com/Azure/azure-sdk-for-net/assets/5131689/5f0b2148-3355-4088-844b-58042152be5a)

After 2 minutes it gets expired and forwarded to main.dlq
![image](https://github.com/Azure/azure-sdk-for-net/assets/5131689/4c913366-e197-472e-9d5b-970869fdfbce)

So far according to Azure portal information is good, but when the message is received in the ServiceBusProcessor it has this information:

EnqueuedTime: {2023-12-11 1:55:37 PM +00:00} <--- (Same as above)
ExpiresAt:	{2023-12-11 1:55:09 PM +00:00}  **<-- (NOT the same as above)**
TimeToLive:	{00:02:00} <-- (Same as above)

As you can see the value of ExpiresAt is NOT the same as what we see in portal as ExpitesAtUtc and the value is not EnqueuedTime + TimeToLive

**Comment by rmeshksar** [comment]
It seems when expired message is forwarded to the second queue, the AmqpMessage has the original AbsoluteExpiryTime which is in the past. It should be recalculated when message is forwarded. 
I am not sure how this issue should be reported though.

**Comment by JoshLove-msft** [comment]
So I dug into this some more and found something very interesting. The service behavior of what TTL is sent back appears to depend on how the queue is created. If the queue is created through the portal, and then the TTL is marked as Unbounded after creation (which appears to be the only way to make it unbounded), we see the behavior where the service sends back a TTL that gets transformed to 49 days. However, if I create the queue using the ServiceBusAdministrationClient and do not specify any TTL, then the service does not set a TTL and the client correctly translates this to the max TimeSpan value. I will need to follow up with the service team to see if this behavior is intended.

**Comment by JoshLove-msft** [comment]
Discussed with service team and filed https://github.com/Azure/azure-sdk-for-net/issues/40915
