### ISSUE TITLE
[BUG] InvalidSourceDatabaseId when trying to restore an azure database 

### ISSUE THREAD

**Issue by Musealali** [Azure/azure-sdk-for-net#38886]
### Library name and version

Azure.ResourceManager.Sql - 1.2.0

### Describe the bug

I am in the process of trying to restore a deleted database using the AZURE SDK in a NET CORE application:

```
Azure;
Azure.Core;
Azure.Identity;
Azure.ResourceManager;
Azure.ResourceManager.Resources;
Azure.ResourceManager.Sql;
Azure.ResourceManager.Sql.Models;
```

However when I get to the step of creating the database it keeps throwing me errors saying this:

```
Invalid source database identifier.
Status: 400 (Bad Request)
ErrorCode: InvalidSourceDatabaseId

Content:
{"error":{"code":"InvalidSourceDatabaseId","message":"Invalid source database identifier."}}

```

I have added the some sample code you can use beneath. I have of course removed the subscriptionID etc for security reasons..

Please do notice that when you debug the code it does find the restorable database which is great - everything works until you hit the CreateOrUpdateAsync method.

Ive also tried to use **SourceResourceId** instead of SourceDatabaseId and that just throws an internal server error 500

### Expected behavior

The operation of restoring the database should start and complete

### Actual behavior

I get a 400 Bad request

### Reproduction Steps

```
using Azure;
using Azure.Core;
using Azure.Identity;
using Azure.ResourceManager;
using Azure.ResourceManager.Resources;
using Azure.ResourceManager.Sql;
using Azure.ResourceManager.Sql.Models;

ArmClient client = new ArmClient(new DefaultAzureCredential());
SubscriptionResource subscription = await client.GetSubscriptions().GetAsync("");
ResourceGroupResource resourceGroupResource = await subscription.GetResourceGroupAsync("");

SqlServerResource sqlServerResource = await resourceGroupResource.GetSqlServerAsync("");


RestorableDroppedDatabaseCollection restorableDroppedDatabaseCollection =  sqlServerResource.GetRestorableDroppedDatabases();



await foreach (RestorableDroppedDatabaseResource restorableDroppedDatabaseResource in restorableDroppedDatabaseCollection)
{
    if (restorableDroppedDatabaseResource.Data.DatabaseName == "TestingRestore")
    {

        var backupData = new SqlDatabaseData(AzureLocation.WestEurope)
        {
            CreateMode = SqlDatabaseCreateMode.PointInTimeRestore,
            SourceDatabaseId = restorableDroppedDatabaseResource.Id,
            RestorePointInTime = restorableDroppedDatabaseResource.Data.EarliestRestoreOn
        };
        
        ArmOperation<SqlDatabaseResource> operation = await sqlServerResource.GetSqlDatabases()
            .CreateOrUpdateAsync(WaitUntil.Completed, restorableDroppedDatabaseResource.Data.Name, backupData);
        
        
        Console.WriteLine(operation.Value);
    }
}

```

### Environment

.NET SDK:
 Version:   7.0.201
 Commit:    68f2d7e7a3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.201\

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Musealali** [comment]
Any updates on this please?

**Comment by HarveyLink** [comment]
Hi @Musealali  , I think you should use `RestorableDroppedDatabaseId` property instead of `SourceDatabaseId`

**Comment by Musealali** [comment]
@HarveyLink still not working - can you also please try on your end?

 I am getting this error:


![image](https://github.com/Azure/azure-sdk-for-net/assets/20074364/85be0972-ffe3-496e-ad35-df525dd672ea)


![image](https://github.com/Azure/azure-sdk-for-net/assets/20074364/521d4b5e-cd01-4e97-b1b1-3414eb961e74)


This is how my code look like now:



```
using Azure;
using Azure.Core;
using Azure.Identity;
using Azure.ResourceManager;
using Azure.ResourceManager.Resources;
using Azure.ResourceManager.Sql;
using Azure.ResourceManager.Sql.Models;

ArmClient client = new ArmClient(new DefaultAzureCredential());
SubscriptionResource subscription = await client.GetSubscriptions().GetAsync("");
ResourceGroupResource resourceGroupResource = await subscription.GetResourceGroupAsync("");

SqlServerResource sqlServerResource = await resourceGroupResource.GetSqlServerAsync("");


RestorableDroppedDatabaseCollection restorableDroppedDatabaseCollection =  sqlServerResource.GetRestorableDroppedDatabases();



await foreach (RestorableDroppedDatabaseResource restorableDroppedDatabaseResource in restorableDroppedDatabaseCollection)
{
    if (restorableDroppedDatabaseResource.Data.DatabaseName == "TestingRestore")
    {

        var backupData = new SqlDatabaseData(AzureLocation.WestEurope)
        {
            CreateMode = SqlDatabaseCreateMode.PointInTimeRestore,
            RestorableDroppedDatabaseId= restorableDroppedDatabaseResource.Id,
            RestorePointInTime = restorableDroppedDatabaseResource.Data.EarliestRestoreOn
        };
        
        ArmOperation<SqlDatabaseResource> operation = await sqlServerResource.GetSqlDatabases()
            .CreateOrUpdateAsync(WaitUntil.Completed, restorableDroppedDatabaseResource.Data.Name, backupData);
        
        
        Console.WriteLine(operation.Value);
    }
}

```

**Comment by Musealali** [comment]
Any updates on this please?

**Comment by HarveyLink** [comment]
Hi @Musealali , sorry for the late reply, just back from vacation.
As the comments of creation mode, you could get:
```
Restore: Creates a database by restoring a backup of a deleted database. sourceDatabaseId must be specified.
If sourceDatabaseId is the database's original resource ID, then sourceDatabaseDeletionDate must be specified.
Otherwise sourceDatabaseId must be the restorable dropped database resource ID and sourceDatabaseDeletionDate is ignored.
restorePointInTime may also be specified to restore from an earlier point in time.
```
The key point here is Mode must be `Restore`, and if you use `RestorableDroppedDatabaseId` or original database id with deletion time. So the correct code here would be:
```
var server = (await resourceGroup.GetSqlServers().GetAsync("sdktest1107")).Value;
await foreach (var item in server.GetRestorableDroppedDatabases().GetAllAsync())
{
    var dbdata = new SqlDatabaseData(AzureLocation.EastUS)
    {
        Sku = new SqlSku("Basic") { Tier = "Basic" },
        CreateMode = SqlDatabaseCreateMode.Restore,
        RestorableDroppedDatabaseId = item.Id,
        RestorePointInTime = item.Data.EarliestRestoreOn,
    };
    var db = (await server.GetSqlDatabases().CreateOrUpdateAsync(WaitUntil.Completed, "newdb", dbdata)).Value;
}
```

**Comment by Musealali** [comment]
I'm sorry but this still doesn't work!

Alright so lets take it from the top.

I have an SQL Server and in my SQL Server I have a list of deleted databases:

![image](https://github.com/Azure/azure-sdk-for-net/assets/20074364/e9f3f00b-8774-400e-8bc0-f69fa49c0f1b)


Now in my code (And thanks Harvey for the suggestion) - I am able to find restorable databases and specifically that deleted one. It has all the right data when fetching from azure. 

However when I then try to create the database of that deleted database and its restore point time azure is giving me this error:

![image](https://github.com/Azure/azure-sdk-for-net/assets/20074364/d2b06c26-fe8b-42cf-b92a-29158714a29b)


Please try to reproduce this before getting back to me please.. You can do it by this.


1. Create an SQL server
2. Create an SQL database
3. Delete SQL Database
4. Go to "deleted databases" see if you can find your previous deleted database.
5. Implement this code (you can do it in a regular console app NET CORE) I have attached the code in this thread

Remember to fill in the empty strings (has been removed for security reasons)

Run the program and see what you get from the activity Logs in azure. 

[AzureSqlDatabase.zip](https://github.com/Azure/azure-sdk-for-net/files/13041442/AzureSqlDatabase.zip)

**Comment by Musealali** [comment]
Apologies for the above - I made it work - it seems like I was too fast with deleting the database so azure didn't have time to create a backup for it.

**Comment by HarveyLink** [comment]
@Musealali Never mind. Glad to hear that you have addressed your problem. I'm going to close this issue. 
If you have any further questions, feel free to reopen it.
