### ISSUE TITLE
DataMember attribute not considered when querying table storage entities.

### ISSUE THREAD

**Issue by WillooWisp** [Azure/azure-sdk-for-net#38884]
### Library name and version

Azure.Data.Tables 12.8.1

### Describe the bug

DataMember attribute, e.g. for mapping .NET property name to a serialized column name, PascalCase vs camelCase, is taken into account when UpsertEntityAsync with stronly typed ITableEntity using DataMember on a property, but not when querying data or generatic a filter using CreateQueryFilter.

### Expected behavior

Expected behavior is that it should be possible to use query expressions in queries or to generate a query filter.

### Actual behavior

The DataMember name is not used in queries or when generating the query filter string, so no match in result.

### Reproduction Steps

Create a strongly typed ITableEntity class.

 ```
public class SystemEventTableEntity : ITableEntity
{
  [DataMember(Name = "severity")]
  public long Severity { get; set; }
  [DataMember(Name = "text")]
  public string Text { get; set; }
  public string PartitionKey { get; set; }
  public string RowKey { get; set; }
  public DateTimeOffset? Timestamp { get; set; }
  public ETag ETag { get; set; }
}
```

Insert entities using table client UpsertEntityAsync.
Query the entity using Severity, above, in the query, using either CreateQueryFilter or QueryAsync directly with linq expression.
No match in results since query is generated with incorrect naming for the property, and not with the name from the DataMember.

### Environment

.NET 6, Windows 10.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
related to #35954 - I will work on getting this merged before the next release.
