### ISSUE TITLE
[QUERY] Why are some ResponseError fields internal?

### ISSUE THREAD

**Issue by kalbert312** [Azure/azure-sdk-for-net#38890]
### Library name and version

Azure.Core 1.34.0

### Query/Question

I'm migrating code that uses Track 1 SDKs to use Track 2 SDKs. The code captures all of the fields listed here in track 1's `ErrorResponse`:

```csharp
namespace Microsoft.Azure.Management.ResourceManager.Models
{
  /// <summary>Error Response</summary>
  /// <remarks>
  /// Common error response for all Azure Resource Manager APIs to return
  /// error details for failed operations. (This also follows the OData error
  /// response format.)
  /// </remarks>
  public class ErrorResponse
  {
    /// <summary>
    /// Initializes a new instance of the ErrorResponse class.
    /// </summary>
    public ErrorResponse()
    {
    }

    /// <summary>
    /// Initializes a new instance of the ErrorResponse class.
    /// </summary>
    /// <param name="code">The error code.</param>
    /// <param name="message">The error message.</param>
    /// <param name="target">The error target.</param>
    /// <param name="details">The error details.</param>
    /// <param name="additionalInfo">The error additional info.</param>
    public ErrorResponse(
      string code = null,
      string message = null,
      string target = null,
      IList<ErrorResponse> details = null,
      IList<ErrorAdditionalInfo> additionalInfo = null)
    {
      this.Code = code;
      this.Message = message;
      this.Target = target;
      this.Details = details;
      this.AdditionalInfo = additionalInfo;
    }

    /// <summary>Gets the error code.</summary>
    [JsonProperty(PropertyName = "code")]
    public string Code { get; private set; }

    /// <summary>Gets the error message.</summary>
    [JsonProperty(PropertyName = "message")]
    public string Message { get; private set; }

    /// <summary>Gets the error target.</summary>
    [JsonProperty(PropertyName = "target")]
    public string Target { get; private set; }

    /// <summary>Gets the error details.</summary>
    [JsonProperty(PropertyName = "details")]
    public IList<ErrorResponse> Details { get; private set; }

    /// <summary>Gets the error additional info.</summary>
    [JsonProperty(PropertyName = "additionalInfo")]
    public IList<ErrorAdditionalInfo> AdditionalInfo { get; private set; }
  }
}
```

Track 2's [`Azure.ResponseError`](https://github.com/Azure/azure-sdk-for-net/blob/bc5e855008db838982fc6f9dbd6cacb011bea3f1/sdk/core/Azure.Core/src/ResponseError.cs#L19) only exposes `Code` and `Message`, while other fields like `Details`, `Target`, and `InnerError` are internal.

I am wondering what's the reason behind keeping these internal and if there's any way these can be accessed directly? I see `ToString()` will print all of these fields to a string but there's no control over that output or ability to narrow down the data to distinct fields. The error handling code I'm working with captures all of these fields to distinct fields elsewhere.

**Comment by jsquire** [comment]
@tg-msft, @KrzysztofCwalina:  You folks would be best positioned to provide insight.   Would you please share your thoughts?

**Comment by tg-msft** [comment]
See https://github.com/Azure/azure-sdk-for-net/issues/25384#issuecomment-972597959, https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#rest-document-error-code-values, and https://github.com/microsoft/api-guidelines/blob/vNext/azure/ConsiderationsForServiceDesign.md#errors for the explanation.

**Comment by stuartko** [comment]
This feels like a bit of a feature regression, especially given those fields are output via the ErrorResponse .ToString() implementation (having the string representation include otherwise inaccessible/hidden data feels like a conflict with the design choice to use internal for the other properties). How firm are you on this design choice? It feels like creating something like ErrorResponseExtended  could have been an option here as well.

**Comment by kalbert312** [comment]
/unresolve

The code being migrated belongs to an Azure RP that depends on other RPs. We are capturing all of the error fields from the old response DTO into logs and also displaying select information to the user. The ToString() implementation to get these details doesn't work well in this case. We also lose the ability to traverse inner errors.

It would also be helpful to be able to access the `ResponseError` on a `RequestFailedException`. Similarly, a bunch of information is combined into a single string as the exception message including things like response headers which we cannot store or display in an organized way.

**Comment by tg-msft** [comment]
Per the links in my comment above, we consider it more harmful to customers to directly expose these for anything other than diagnostic purposes as they're subject to change without notice (i.e., the details/inner error/etc. can all change without even an api-version bump).

You can use [`RequestFailedException.GetRawResponse()`](https://learn.microsoft.com/en-us/dotnet/api/azure.requestfailedexception.getrawresponse?view=azure-dotnet#azure-requestfailedexception-getrawresponse) if you want to interrogate the headers, payload, etc.  That should be sufficient for passthrough scenarios.
