### ISSUE TITLE
[QUERY] [Schema Registry] Client credential overloads

### ISSUE THREAD

**Issue by danielmarbach** [Azure/azure-sdk-for-net#38896]
### Library name and version

Azure.Data.SchemaRegistry

### Query/Question

It seems quite common that HTTP based SDK client types provide constructor overloads of the following form

```csharp
SdkClient(Uri endpoint, AzureKeyCredential credential)
SdkClient(Uri endpoint, AzureKeyCredential credential, SdkClientOptions options)
SdkClient(Uri endpoint, TokenCredential credential, SdkClientOptions options = default)
SdkClient(Uri endpoint, AzureSasCredential credential, SdkClientOptions options = default)
```

is there a reason the `SchemaRegistryClient` does only provide overloads for
`TokenCredential` and `SchemaRegistryClientOptions` but not for key credential or SAS credential?

**Comment by jsquire** [comment]
Hi @danielmarbach.   The Schema Registry service itself supports only AAD authorization.  There are no shared keys or SAS tokens that would be usable with `AzureKeyCredential` nor `AzureSasCredential`.    The [REST API docs](https://learn.microsoft.com/rest/api/eventhub/controlplane-preview/schema-registry/get?tabs=HTTP#security) are minimal but allude to this.

**Comment by danielmarbach** [comment]
ok Thanks!
