### ISSUE TITLE
Azure functions Isolated V4 .net 7 

### ISSUE THREAD

**Issue by newportg** [Azure/azure-sdk-for-net#38954]
Is there any place on the roadmap to support the latest versions of Azure Functions ?

**Comment by jsquire** [comment]
Hi @newportg.  Can you help us understand what scenario you're inquiring about?

**Comment by newportg** [comment]
Hmmm, Not sure how my question got listed here, but never mind.

AUTOREST currently only supports the generation of Azure functions V3 with .Net 3.1 both of which are out of support.
My enquiry was simply to find out when the Azure Functions Generator would be brought up to date.

Thanks

**Comment by jsquire** [comment]
@newportg:  Thanks for clarifying.   I've transferred this over to the repository where the Azure Functions generator for C# is maintained as [#24](https://github.com/Azure/autorest.azure-functions-csharp/issues/24).   I do not have insight into that repository nor who maintains it, but based on activity history, it does not seem to be very active.
