### ISSUE TITLE
How can I use Azure App Configuration for QueueTrigger bindings?

### ISSUE THREAD

**Issue by gpuchtel** [Azure/azure-sdk-for-net#38965]
### Library name and version

Microsoft.Azure.Functions.Worker 1.19.0

### Query/Question

I've been searching for a way to use Azure 'App Configuration' to store the connection string of an Azure Storage Queue. After hours searching on the Web I'm even more confused--there seems to be conflicting opinions on how to do this. Maybe even using Managed Identity, but that makes debugging locally a nightmare.

What I want is something like this:

[Function("foo")
public void foo([QueueTrigger("bar", Connection = "FooConnection")] QueueMessage message)

Where "FooConnection" is the name of a 'key' in an Azure App Configuration from which the connection string is specified. adly, it seems that Azure only looks in the 'Configuration' of the function (or local settings if running locally).

So, is this even possible?

Note: I do 'AddAzureAppConfiguration(..) in my HostBuilder.

Thanks in advance,

I've tried to surround the name with '%' like "%FooConnection%", but I get an error saying the expression did not evaluate to a value.

I've seen posts that speak so an expression pattern, but there is not much guidance on it.

see: https://stackoverflow.com/q/77180419/8307483

**Comment by jsquire** [comment]
Hi @gpuchtel.  Thanks for reaching out and we regret that you're experiencing difficulties.   Unfortunately, this is a question related to the Functions host and how its bindings operate more so than the queue trigger.  As a result, there's not much insight that can be provided here.   I've transferred this to the repository where the Functions host is maintained as [#9568](https://github.com/Azure/azure-functions-host/issues/9568), which will ensure that the folks best positioned to assist see it.

In the meantime, it does look like the AppConfig extension can be used to bind to settings, though I'm not sure if that extends to the attribute syntax as well.   An end-to-end quickstart sample can be found [here](https://learn.microsoft.com/azure/azure-app-configuration/quickstart-azure-functions-csharp?tabs=in-process).
