### ISSUE TITLE
Issues with validation of the "data" property in EventGridEvent class

### ISSUE THREAD

**Issue by MilanMilic97** [Azure/azure-sdk-for-net#38962]
Hello,
I think there might be a problem with the validation of the "data" property in the EventGridEvent class.

Since I have changed the library from deprecated Microsoft.Azure.EventGrid to an Azure.Messaging.EventGrid I have stumbled upon an issue trying to adapt the validation of the message that is coming from the Azure message bus.

Whenever I try to send a message with an empty data parameter or null:
![image](https://github.com/Azure/azure-sdk-for-net/assets/82164825/aba73781-d1ea-424b-a3bd-ca0bf22cd9a7)
Validation always passes.

If I try to send anything else as null, validation will not pass and argumentNullException will be thrown which is expected.
In the picture below you can see the validation inside the constructor.
![image](https://github.com/Azure/azure-sdk-for-net/assets/82164825/ad685a8d-7358-462f-929f-982988dc6cc2)

The "data" property that is coming from the Azure message bus is in the raw JSON data and when parsing, if the value is null, it actually is not represented as null, but {null} instead.

Sent data: 
![image](https://github.com/Azure/azure-sdk-for-net/assets/82164825/3a778166-fd9f-4f74-bf69-eaf3f1450e69)

Parsed data: 
![image](https://github.com/Azure/azure-sdk-for-net/assets/82164825/f8867a77-91f6-4fec-be25-c795dde4a1c5)

The solution is quite simple with additional check in the logic, but I think that this has to be addressed and dealt with in the library itself since the expected behavior is that an exception will be thrown if no data is provided.

If I missed something, please let me know.
Thank you in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ce873d0e-3608-877c-99c0-a7cd281e8b89
* Version Independent ID: c04935be-26dc-8096-5ea6-939e4e12ca1d
* Content: [EventGridEvent.Parse(BinaryData) Method (Azure.Messaging.EventGrid) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.eventgrid.eventgridevent.parse?view=azure-dotnet)
* Content Source: [xml/Azure.Messaging.EventGrid/EventGridEvent.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Messaging.EventGrid/EventGridEvent.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @MilanMilic97,
Can you provide a code snippet that shows how the data is being sent to Service Bus?

**Comment by MilanMilic97** [comment]
Hi @JoshLove-msft,
Data is being sent to the Service Bus via IoTHub, and currently, I do not have access to the code that is sending the data from the instrument to IoTHub.

Anyhow, I was sending the data via Service Bus Explorer, following the schema shown in the issue. 
![image](https://github.com/Azure/azure-sdk-for-net/assets/82164825/6f82980f-703c-4bcd-8cb0-851d18555267)
I changed the values of properties to "string" because they are sensitive data.

The reason I was manually sending that payload via Service Bus is to check if the validation of the new library is working correctly.
As I mentioned, every other property validation (for example "event type") is working properly (throws exception with message).
To test other properties I was sending "null" as a value.

**Comment by JoshLove-msft** [comment]
Can you please provide a code snippet that reproduces the issue? The end to end scenario is not clear to me.

**Comment by MilanMilic97** [comment]
Repro steps:
1. Create this payload: 
{
    "id": "78e9158d-832a-4d66-b783-a512b64c2e92",
    "topic": "/subscriptions/{subscription-id}/resourceGroups/Storage/providers/Microsoft.Storage/storageAccounts/xstoretestaccount",
    "subject": "someSubject",
    "eventType": "Microsoft.Devices.DeviceDisconnected",
    "data": null,
    "dataVersion": "",
    "metadataVersion": "1",
    "eventTime": "2022-05-13T14:52:05.1616905Z"
}

Send with Service Bus Explorer to the Service Bus
Az Function trigger consumes the message
Code snippet of an Azure function endpoint that is receiving the message: 

```
[Function("ProcessDeviceConnectivity")]
[OpenApiIgnore]
[ServiceBusOutput("%MyQueueName%", Connection = "Connection")]
public async Task<string> UpdateStatus(
    [ServiceBusTrigger("%MyQueueName%", Connection = "Connection")]
    byte[] message,
    string messageId,
    FunctionContext context)
{
    DeviceConnection deviceConnection = null;
    var logger = context.GetLogger<Update>();
    var bodyMessage = new BinaryData(message);

    try
    {
        //Parsing is also a validation which whill throw exception if required parameters are not provided.
        var eventGridEvent = EventGridEvent.Parse(bodyMessage);
    }
    catch (ArgumentNullException e)
    {
        logger.Log(e);
        return await ServiceBusOutputResponse.PrepareOutputMessage(bodyMessage.ToString(), messageId, null, $"Error parsing ServiceBus message body. MessageId: {messageId}, Exception message: {e.Message}.").ConfigureAwait(false);
    }
    return await ServiceBusOutputResponse.Complete().ConfigureAwait(false);
}
```

I am expecting that the Parse() method is going to throw an exception because the "DATA" parameter has null value.
Why am I expecting an exception? Well because of this:
![image](https://github.com/Azure/azure-sdk-for-net/assets/82164825/828e1b1e-29cf-4291-b2f1-c601a8b56058)

And what actually happens:
EventGridEvent object is successfully made with all properties filled with the values that came from the Service Bus, and the "DATA" property has a value of a JSON with null inside. It looks like this: 
![image](https://github.com/Azure/azure-sdk-for-net/assets/82164825/e13813b9-cbe7-4e52-bf24-ae346c711557)

**Comment by JoshLove-msft** [comment]
The EventGridEvent.Parse method does not use the public constructor that you are referencing. It uses an internal constructor that is more lenient when it comes to validation in order to support deserialization scenarios involving different libraries.
