### ISSUE TITLE
Not able to create deployment using CognitiveServices SDK

### ISSUE THREAD

**Issue by fmabroukmsft** [Azure/azure-sdk-for-net#38973]
### Library name and version

Azure.ResourceManager.CognitiveServices 1.3.0

### Query/Question

Hello CognitiveServices, I'm attempting to create a simple deployment using the CognitiveServices sdk.
I first retrieve one of the default models from my AOAI account:
`var models = await GetModels(workspace, resourceId, maasAccountName).ConfigureAwait(false);`
`var curieModel = models.Find(model => model.Name == "text-curie-001");`

I then create a CognitiveServicesAccountDeploymentProperties object and set the Model field:
`var deploymentPropertiesPreloadedModel = new CognitiveServicesAccountDeploymentProperties
            {
                Model = curieModel
            };`

Next, I create a CognitiveServicesAccountDeploymentData object:
`ResourceIdentifier newResourceIdentifier = CognitiveServicesAccountDeploymentResource.CreateResourceIdentifier(workspace.SubscriptionId.ToString(), workspace.ResourceGroupName, maasAccountName, newDeploymentName);`
            `ResourceType cogServicesResourceType = new ResourceType("Microsoft.CognitiveServices/accounts/deployments");`
            `var selectedSku = new CognitiveServicesSku("S0");`
            `var modelFactoryDeploymentData = ArmCognitiveServicesModelFactory.CognitiveServicesAccountDeploymentData(
                id: newResourceIdentifier,
                name: newDeploymentName,
                resourceType: cogServicesResourceType,
                sku: selectedSku,
                properties: deploymentPropertiesPreloadedModel);`

Last, I create a deployment resource and then call UpdateAsync to create a deployment:
`CognitiveServicesAccountDeploymentResource deploymentResource = armClient.GetCognitiveServicesAccountDeploymentResource(newResourceIdentifier);`
`await deploymentResource.UpdateAsync(WaitUntil.Completed, modelFactoryDeploymentData).ConfigureAwait(false);`

Despite trying to tweak the request however possible, I keep running into the following error: `Azure.RequestFailedException : The request content was invalid and could not be deserialized.`

Is there an SDK example that shows creation of a new deployment from scratch (where the `CognitiveServicesAccountDeploymentResource` does not already exist)? What am I missing from my steps? Thanks in advance!

### Environment

.NET SDK:
 Version:   7.0.401
 Commit:    eb26aacfec

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.401\

Host:
  Version:      7.0.11
  Architecture: x64
  Commit:       ecb34f85ec

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi @fmabroukmsft ,
Here's a sample about how to create a depeloyment.
Note: The point here is: create method located at the collection class, like `CognitiveServicesAccountDeploymentCollection`, you could get the collection from it's parent resource
```
string clientId = Environment.GetEnvironmentVariable("CLIENT_ID");
string clientSecret = Environment.GetEnvironmentVariable("CLIENT_SECRET");
string tenantId = Environment.GetEnvironmentVariable("TENANT_ID");
string subscriptionId = Environment.GetEnvironmentVariable("SUBSCRIPTION_ID");
var client = new ArmClient(new ClientSecretCredential(tenantId, clientId, clientSecret), subscriptionId);
var subscription = await client.GetDefaultSubscriptionAsync();
var resourceGroupData = new ResourceGroupData(AzureLocation.EastUS);
var resourceGroupCollection = subscription.GetResourceGroups();
var resourceGroup = (await resourceGroupCollection.CreateOrUpdateAsync(WaitUntil.Completed, "rgName0718", resourceGroupData)).Value;

try
{
    var accountCollection = resourceGroup.GetCognitiveServicesAccounts();
    var accountData = new CognitiveServicesAccountData(AzureLocation.EastUS)
    {
        Sku = new CognitiveServicesSku("S0"),
        Kind = "OpenAI",
        Properties = new CognitiveServicesAccountProperties()
    };
    var account = (await accountCollection.CreateOrUpdateAsync(WaitUntil.Completed, "testaccount0927", accountData)).Value;

    var deploymentCollection = account.GetCognitiveServicesAccountDeployments();
    var deploymentData = new CognitiveServicesAccountDeploymentData()
    {
        Properties = new CognitiveServicesAccountDeploymentProperties
        {
            Model = new CognitiveServicesAccountDeploymentModel()
            {
                Name = "text-ada-001",
                Format = "OpenAI",
                Version = "1"
            },
            ScaleSettings = new CognitiveServicesAccountDeploymentScaleSettings()
            {
                ScaleType = CognitiveServicesAccountDeploymentScaleType.Standard,
            }
        }
    };
    var deployment = (await deploymentCollection.CreateOrUpdateAsync(WaitUntil.Completed, "testdeployment0927", deploymentData)).Value;
    Console.WriteLine(deployment.Data.Name);
}
catch (Exception e)
{
    Console.WriteLine(e.Message);
}
```
finally
{
    await resourceGroup.DeleteAsync(WaitUntil.Completed);
}
