### ISSUE TITLE
[FEATURE REQ] AddAzureMonitorLogExporter should support IOptions

### ISSUE THREAD

**Issue by scrocquesel-ml150** [Azure/azure-sdk-for-net#38991]
### Library name

Azure.Monitor.OpenTelemetry.Exporter

### Please describe the feature.

Is it possible to configure the Log exporter with traditional IOptions idioms, similar to Trace and Metric exporters? Currently, options are only provided through the configure delegate passed to the extension method. I have a use case where I want to separate AddAzureMonitorLogExporter from its configuration.

**Comment by vishweshbankwar** [comment]
@scrocquesel-ml150 Thanks for raising this. This is currently a limitation from OTel SDK side. Please follow 
https://github.com/open-telemetry/opentelemetry-dotnet/issues/4014
https://github.com/open-telemetry/opentelemetry-dotnet/issues/4433.
