### ISSUE TITLE
[FEATURE REQ] Ability to disable log export for monitor OpenTelemetry package

### ISSUE THREAD

**Issue by damienpontifex** [Azure/azure-sdk-for-net#39029]
### Library name

Azure.Monitor.OpenTelemetry.AspNetCore

### Please describe the feature.

An option/capability to not export logs to azure monitor via the OpenTelemetry package as can be seen configured https://github.com/Azure/azure-sdk-for-net/blob/239c373a260bdb45c0ff86e698418e7cdb8daa3f/sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/src/OpenTelemetryBuilderExtensions.cs#L127-L157

## Reasons
* We host our applications in AKS and use stdout logs to ContainerLogsV2 with basic logs capabilities to save on costs
* Exporting to app insights would duplicate these logs and negate the cost savings we're getting through basic logs
* Thus the ability to disable log output via OpenTelemetry so we just use our standard serilog json output via stdout as single logging destination, while still benefiting from the quick and simple setup the Azure.Monitor.OpenTelemetry.AspNetCore package provides for traces

**Comment by TimothyMothra** [comment]
Hi @damienpontifex, we currently don't have plans to add this customization to the Azure.Monitor.OpenTelemetry.AspNetCore package.
If you need this kind of flexibility now, I recommend using the Azure.Monitor.OpenTelemetry.Exporter. 
You can copy the configuration from OpenTelemetryBuilderExtensions.cs which you've already found.

**Comment by damienpontifex** [comment]
Thank you @cijothomas I hadn't thought of (or researched before) the different log levels per provider. I'll set the environment variable for `Logging__OpenTelemetry__LogLevel__Default=None` and as you've suggested should solve my request.
Thanks for the inputs/insights
