### ISSUE TITLE
[QUERY] How to access the search results from calling SearchClient.SearchAsync

### ISSUE THREAD

**Issue by MerjTek** [Azure/azure-sdk-for-net#39026]
### Library name and version

Azure.Search.Documents (11.4)

### Query/Question

Original Code (v10.):

var client = _serviceClient.Indexes.GetClient(indexName);
Task<DocumentSearchResult<Document>> results = await client.Documents.SearchAsync(azureQuery.SearchValueParam, searchParams);

New Replacement Code (v11):

var client = _searchIndexClient.GetSearchClient(indexName);
Response<SearchResults<SearchResult<Document>>> results = await client.SearchAsync<SearchResult<SearchDocument>>(azureQuery.SearchValueParam, (SearchOptions)searchParams);

I am trying to determine how to get the "SearchResult\<Document>" from results. Is there a way to do this? Which object inside Response class and also inside the SearchResults class do I need to reference to get down to this information?

I am asking here because of all of the name changes in the API.

### Environment

.Net 6.0
Visual Studio 2022

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ShivangiReja** [comment]
Hello @MerjTek, you can access your documents using `results.Value.GetResultsAsync()`:

```csharp
Response<SearchResults<MyDocument>> results = await client.SearchAsync<MyDocument>("*");
await foreach (SearchResult<MyDocument> result in results.Value.GetResultsAsync())
{
   ...
}
```

Alternatively, you can directly access your documents by using the `SearchResults<T>` type from the search call:

```csharp
SearchResults<MyDocument> results = await client.SearchAsync<MyDocument>("*");
await foreach (SearchResult<MyDocument> result in results.GetResultsAsync())
{
    ...
}
```

For more examples and details, please refer to the [official documentation](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/search/Azure.Search.Documents#async-apis).

**Comment by ShivangiReja** [comment]
The `Search` method returns a `Response<SearchResults<T>>`, so you should assign the results to `Response<SearchResults<T>>`, not `Response<SearchResults<SearchResult<SearchDocument>>>`. 

Here's an example of how to access `SearchResult` property values:

```c#
Response<SearchResults<SearchDocument>> response = await client.SearchAsync<SearchDocument>("*");

// Accessing SearchResults property values
SearchResults<SearchDocument> searchResults = response.Value;

// Accessing each SearchResult property values
await foreach (SearchResult<SearchDocument> result in searchResults.GetResultsAsync())
{
    // Accessing your Documents
    SearchDocument doc = result.Document;
    string id = (string)doc["Id"];
    Console.WriteLine($"{id}");
}
```

For more details please refer this [sample](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/search/Azure.Search.Documents#use-searchdocument-like-a-dictionary-for-search-results).

**Comment by ShivangiReja** [comment]
The `Search` method returns a `Response<SearchResults<T>>`, so you should assign the results to `Response<SearchResults<T>>`, not `Response<SearchResults<SearchResult<SearchDocument>>>`. 

Here's an example of how to access `SearchResult<T>`  from the response:

```c#
Response<SearchResults<SearchDocument>> response = await client.SearchAsync<SearchDocument>("*");

// Here's how you can access SearchResults<T> from the response
SearchResults<SearchDocument> searchResults = response.Value;

// Here's how you can access each SearchResult<T> from the response
await foreach (SearchResult<SearchDocument> searchResult in response.Value.GetResultsAsync())
{
    // Here's how you can access each document
    SearchDocument doc = searchResult.Document;
    string id = (string)doc["Id"];
    Console.WriteLine($"{id}");
}
```

For more details, please refer to this [sample](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/search/Azure.Search.Documents#use-searchdocument-like-a-dictionary-for-search-results).
