### ISSUE TITLE
[QUERY] Can I download the Blobs in Batch

### ISSUE THREAD

**Issue by vj-msft** [Azure/azure-sdk-for-net#39031]
### Library name and version

Azure.Storage.Blobs 12.16.0

### Query/Question

Is it possible to download the Blobs as batch? 
Scenario is , 
- There are 60 +(just example in this case) blobs in a container. 
- Azure Function App will be using the SDK to download the blobs one by one and merge it to create a single memory stream. 

So looking at the number of calls made to Azure storage in this case is 60+,  trying to figure out if there is an  options to reduce the number of calls to download the blobs.
 

### Environment

Hosting platform - Azure Function with Dedicated app service plan,  .net 6

**Comment by seanmcc-msft** [comment]
Hi @vj-msft, it is not possible to do a batch blob download.  The [Blob Batch REST API](https://learn.microsoft.com/en-us/rest/api/storageservices/blob-batch?tabs=microsoft-entra-id) only supports Batch Delete and Batch Set Tier.
