### ISSUE TITLE
Topic subscriptions pragmatically creation fail (.net core 2 / standard 2)

### ISSUE THREAD

**Issue by LilanMadusankaSilva** [Azure/azure-sdk-for-net#3904]
- I used Microsoft.Azure.Management.ServiceBus (https://github.com/Azure/azure-sdk-for-net/tree/AutoRest/src/ResourceManagement/ServiceBus)
- Token authentication work but subscription creation fail 

`var token = await GetToken();
var creds = new TokenCredentials(token);
var sbClient = new ServiceBusManagementClient(creds)
				{
					SubscriptionId = subscriptionId,
				};
var subscriptionParams = new SBSubscription
				{
                    MaxDeliveryCount = 10
				};

await sbClient.Subscriptions.CreateOrUpdateAsync(resourceGroupName, namespaceName, TopicName, SubscriptionName, subscriptionParams);`

**Comment by jfggdl** [comment]
@LilanMadusankaSilva if you are able o reproduce this problem, please get the tracking id and with that please create a support request on Azure Portal. We are going to be closing this issue, but feel free to open it again if you have any additional questions around creating your support request.
