### ISSUE TITLE
[FEATURE REQ] Allow Users to Configure Retry Policy for Credentials through ClientFactory

### ISSUE THREAD

**Issue by wsugarman** [Azure/azure-sdk-for-net#39049]
### Library name

Microsoft.Extensions.Azure

### Please describe the feature.

While `RetryOptions` may be configured for Azure service clients through the `AzureComponentFactoryImpl.CreateClientOptions`, they cannot be similarly configured for any of the `TokenCredential` objects generated through `ClientFactory.CreateCredential`. For my team, it is becoming more important to configure our `ManagedIdentityCredential` object's retry while federated identities are [still not available in all Azure regions](https://learn.microsoft.com/en-us/azure/active-directory/workload-identities/workload-identity-federation-considerations#unsupported-regions-user-assigned-managed-identities), and AAD pod identity may take some time to become ready for a given pod.

I think the existing API could be easily extended to allow a nested configuration section called `retry` with all of the value for `RetryOptions`. Eg.

```json
{
  "credential": "managedidentity",
  "retry": {
    "delay": "00:00:10",
    "maxRetries": 10
  }
}
```

**Comment by jsquire** [comment]
Hi @wsugarman.  Thank you for reaching out with your suggestion.  Retry policies for credentials can be configured today by registering credential that you've configured with the client builder:

```csharp
builder.Services.AddAzureClients(clientBuilder =>
{
    var options = new DefaultAzureCredentiailOptions();
    options.Retry.MaxRetries = 10;
    options.Retry.MaxDelay = TimeSpan.FromMinutes(5);

    var credential = new DefaultAzureCredential(options);
    clientBuilder.UseCredential(credential);
});
```

More discussion and examples can be found in [Dependency injection with the Azure SDK for .NET](https://learn.microsoft.com/dotnet/azure/sdk/dependency-injection?tabs=web-app-builder).    

With respect to the suggested configuration, we do not have plans to extend the configuration syntax in the short term, but we are we are looking at ways to improve the overall Azure SDK configuration story as a longer-term feature.
