### ISSUE TITLE
[BUG] delete directory on gen2 hierarchical namespace blob

### ISSUE THREAD

**Issue by deanmarcussen** [Azure/azure-sdk-for-net#39065]
### Library name and version

Azure.Storage.Blobs 12.18.0

### Describe the bug

When retrieving a `BlobClient` on a gen2 enabled hierarchical namespace storage account for a directory, and then trying to delete the directory the execution fails with the following error.

```
Azure.RequestFailedException: The requested operation is not supported on a directory.
RequestId:21eef5b4-201e-00a3-5ea5-f5c7e5000000
Time:2023-10-03T03:01:07.6936271Z
Status: 400 (The requested operation is not supported on a directory.)
ErrorCode: OperationNotSupportedOnDirectory
```

I can't find any documentation on how to deal with folders via the blobs sdk, so looking for some advise on how to delete folders.

### Expected behavior

Able to delete folders

### Actual behavior

Throws exception

### Reproduction Steps

```
var blob = _blobContainer.GetBlobClient(blobFolder);
await blob.DeleteAsync(); 
```

**Comment by seanmcc-msft** [comment]
This behavior is expected.  `BlobClient.Delete()` is calling the [Delete Blob](https://learn.microsoft.com/en-us/rest/api/storageservices/delete-blob?tabs=azure-ad) REST API, which is not compatible with deleting ADLS Gen 2 directories.  I recommend using [Azure.Storage.Files.DataLake](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/storage/Azure.Storage.Files.DataLake)'s `DataLakeDirectoryClient.DeleteAsync()` method instead.
