### ISSUE TITLE
[QUERY]not able use Deadletter and abandon in serviceBusreceived message class

### ISSUE THREAD

**Issue by venky0411** [Azure/azure-sdk-for-net#39073]
### Library name and version

serviceBustrigger

### Query/Question

not able use Deadletter and abandon in serviceBusreceived message class in azure function app v4

### Environment

.net FM v4.8

**Comment by jsquire** [comment]
Hi @venky0411.  Thanks for reaching out and we regret that you're experiencing difficulties.   You can manually settle messages by binding to the `ServiceBusMessageActions` type and invoking the desired settlement operation there.

```csharp
[FunctionName("BindingToMessageActions")]
public static async Task Run(
    [ServiceBusTrigger("<queue_name>", Connection = "<connection_name>")]
    ServiceBusReceivedMessage[] messages,
    ServiceBusMessageActions messageActions)
{
    foreach (ServiceBusReceivedMessage message in messages)
    {
        if (message.MessageId == "1")
        {
            await messageActions.DeadLetterMessageAsync(message);
        }
        else
        {
            await messageActions.CompleteMessageAsync(message);
        }
    }
}
```

More context and discussion can be found [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/README.md#message-settlement).
