### ISSUE TITLE
PartitionKey Options

### ISSUE THREAD

**Issue by mbaird628** [Azure/azure-sdk-for-net#39088]
Given the following statement, in what scenario would I need to provide the PartitionKey? If it is truly optional and has no impact then why require or even make optional?

Is this for backward compatibility?

PartitionKey for the item. If not specified will be populated by extracting from {T}[PartitionKey]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e207d56d-6858-2465-65c6-a123392c54e3
* Version Independent ID: c4dd3e1b-e99e-3ff6-5edd-88d65fe5233a
* Content: [Container.UpsertItemAsync&lt;T&gt; Method (Microsoft.Azure.Cosmos) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container.upsertitemasync?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Cosmos/Container.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/Container.xml)
* Service: **cosmos-db**
* GitHub Login: @azure-sdk
* Microsoft Alias: **azsdkdocs**

**Comment by jsquire** [comment]
This issue has been moved to the repository where the `Microsoft.Azure.Cosmos` library is maintained as [#4110](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/4110).
