### ISSUE TITLE
[BUG] Delay in Blob Availability vs CreatedOn Timestamp

### ISSUE THREAD

**Issue by abeker** [Azure/azure-sdk-for-net#39085]
### Library name and version

Azure.Storage.Blobs 12.17.0

### Describe the bug

In the Azure.Storage.Blobs SDK version 12.17.0, there's an observed discrepancy between the CreatedOn timestamp and the actual time the blob is available in the storage. Specifically, for larger blobs, the CreatedOn timestamp suggests that the blob has been created and is available several seconds before it actually appears and becomes accessible in the blob storage.

### Expected behavior

The CreatedOn timestamp should accurately reflect the time when the blob is fully uploaded and available in the blob storage.

### Actual behavior

The CreatedOn timestamp is set a few seconds (variable based on blob size) before the blob is actually accessible in the storage.

### Reproduction Steps

1. Use the Azure.Storage.Blobs SDK version 12.17.0
2. Upload a large blob (e.g., several gigabytes in size) to Azure Blob Storage
3. Immediately after receiving the upload confirmation, query the blob's metadata to obtain the CreatedOn timestamp
4. Repeatedly query the blob storage for the presence of the blob
5. Note the discrepancy between the CreatedOn timestamp and the actual time the blob becomes available.

### Environment

- OS: Windows 10.0.19045
- Azure Storage Explorer: 1.31.1
- .NET Runtime Version: 7.0.401

**Comment by seanmcc-msft** [comment]
This behavior is expected, as the backend storage service is a distributed service.
