### ISSUE TITLE
[FEATURE REQ] Annotate Azure.Identity for Nullable Reference Types 

### ISSUE THREAD

**Issue by burkenyo** [Azure/azure-sdk-for-net#39103]
### Library name

Azure.Identity

### Please describe the feature.

Nullable Reference Types were introduced in C# 8 and have now become a standard part of the framework and many other libraries. Please consider annotating Azure.Identity for NRTs to enable the library to work with this very helpful language feature.

**Comment by burkenyo** [comment]
Noting here that @heaths commented on this is a related issue:
https://github.com/Azure/azure-sdk-for-net/issues/32597#issuecomment-1402370390

**Comment by jsquire** [comment]
Hi @burkenyo.  Thank you for reaching out and we regret that you're experiencing difficulties.   Nullable reference annotations are something that we continue to evaluate for Azure SDK packages as the language and tooling evolves, but not something that we'll be enabling in the short term.   There are several reasons for this, the most important being:

- The Azure SDK strives to have a consistent set of patterns and feel across different libraries.   As such, nullable reference annotations are not something that would be applied to individual libraries; it would be a decision that we need to apply to all of our current generation packages.

- For most of our libraries, the service definitions do not adequately document which fields may be null.   We continue to work with our service partners to improve these definitions, but it's a large effort that we expect to continue for some time. 

- Tooling still doesn't provide a thorough understanding of what breaking changes would be introduced by enabling nullable reference annotations.  Avoiding breaking changes is one of the most important core tenants of the current Azure SDK generation; until we have confidence that we can prove that nullable reference annotations are safe for the public APIs that they were added to, the risk outweighs the reward.
