### ISSUE TITLE
[FEATURE REQ] Make library Azure.ResourceManager mockable 

### ISSUE THREAD

**Issue by grishaagit** [Azure/azure-sdk-for-net#39118]
### Library name

Azure.ResourceManager.Sql

### Please describe the feature.

This library is generally not very convenient to write unit tests against and though there are many places need attention, here I would like to give as an example several places in particular where I ended up resorting to reflection in order to have unit tests.

ElasticPoolData setting State property
ElasticPoolData setting Name property inherited from ResourceData
Obtaining instance of SqlServerUsage

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi @grishaagit , Model Factory for SQL resource manager is enable for all services.
You could refer to : https://github.com/Azure/azure-sdk-for-net/blob/9ac52a165101b727ff606dd50dd82f771ec7c710/sdk/core/Azure.Core/README.md#mocking
