### ISSUE TITLE
[FEATURE REQ] Allow Custom Authorization Scopes for Azure OpenAI 

### ISSUE THREAD

**Issue by AlexDKlein** [Azure/azure-sdk-for-net#39114]
### Library name

Azure.AI.OpenAI

### Please describe the feature.

Currently, the authorization scope is [hardcoded to "cognitiveservices.azure.com/.default"](https://github.com/Azure/azure-sdk-for-net/blob/e902ef5a2ed5db3d6104ccb2db29b97a02258634/sdk/openai/Azure.AI.OpenAI/src/Generated/OpenAIClient.cs#L23C9-L23C128). This disallows compatibility with proxies or custom authorization pipelines. I know my own team as well as several others that utilize proxies to distribute load on LLMs. 

Without this change, we would not be able to make use of this package.

Simply creating a method for the client to add additional authorization scopes would be sufficient and allow much greater flexibility for this package.

**Comment by jsquire** [comment]
Hi @AlexDKlein.  Thank you for reaching out and we regret that you're experiencing difficulties.  Proxy support for the Azure SDK libraries can be configured via the options passed to your client using the standard .NET proxy objects supported by `HttpClientHandler`.   For example:

```csharp
using HttpClientHandler handler = new HttpClientHandler()
{
    Proxy = new WebProxy(new Uri("http://example.com"))
};

var options = new OpenAIClientOptions
{
    Transport = new HttpClientTransport(handler)
};

var client = new OpenAIClient(<endpoint>, <credential>, options);
```

More discussion and examples can be found in [Configuring a proxy](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Configuration.md#configuring-a-proxy).

If configuring a proxy this way does not work for your scenario, we would appreciate if you could share some additional context to help us better understand your scenario.
