### ISSUE TITLE
[BUG] Application Insights Failure Due to Service Bus SDK fails to deserialize the error.

### ISSUE THREAD

**Issue by shreenayak** [Azure/azure-sdk-for-net#39115]
### Library name and version

Azure.Messaging.ServiceBus

### Describe the bug

Issue Description:
We have reports of discrepancy in Application Insights failures. Initially, it appeared to be a UI problem. However, after further investigation alongside our Ingestion team, we have confirmed that the customer is sending payload data from their application in a malformed way, causing it to be rejected by our ingestion service.

We requested SDK logs of .NET SDK installed on their application to send data to Application Insights, and we have identified the root cause:

Application Insights is failing to deserialize the error that occurs when a .NET service (using the Service Bus SDK Azure.Messaging.ServiceBus.dll) attempts to connect to a Service Bus topic or subscription that does not exist.

Upon analyzing the issue, we have determined that the problem lies within the Service Bus SDK (as indicated by the dll). When reviewing the code for the Service Bus message receive event, as observed in the  sample payload, we were unable to locate the code where the Service Bus sets the responseCode field for the context object:

(https://github.com/Azure/azure-sdk-for-net/blob/0cecccb564f603b5df7d7ba6f69be0ec7c0e2f2a/sdk/servicebus/Azure.Messaging.ServiceBus/src/Receiver/ServiceBusReceiver.cs#L335)

### Expected behavior

The Service Bus SDK should handle the error gracefully and provide the necessary information for Application Insights to properly log the failure.

### Actual behavior

Application Insights fails to deserialize the error when the .NET service using the Service Bus SDK attempts to connect to a non-existent Service Bus topic or subscription.

### Reproduction Steps

NA

### Environment

Environment Details:

Azure.Messaging.ServiceBus.dll version: Latest
Application Insights Version: Latest

**Comment by jsquire** [comment]
Hi @shreenayak.   Thank you for reaching out and we regret that you're experiencing difficulties.   I'm afraid that I do not understand the scenario that you're describing.  The Service Bus client library does not deserialize or interpret the payload of messages in any way; it is treated as an opaque blob of bytes.  Can you share some additional context about the scenario?

Please provide the exception that you're seeing as well as the associated stack trace.  It would also be quite helpful to see the logs that you are referring to, if you are able to share them.
