### ISSUE TITLE
[BUG] managedDiskData needs to be able to set the Zones

### ISSUE THREAD

**Issue by SavaNDragos** [Azure/azure-sdk-for-net#39112]
### Library name and version

Azure.ResourceManager.Compute 1.1.0

### Describe the bug

Premium v2/Ultra disk requires to be deployed on a Zone;

In ManagedDiskData we have:

        /// <summary> The Logical zone list for Disk. </summary>
        public IList<string> Zones { get; }

It also needs a set; else you will not be able to assign the disk to a vm/vmss that is on a zone.

### Expected behavior

Zones should have a set

### Actual behavior

Disks created have no zone and they fail to get attached to a vm/vmss that is on a zone.

### Reproduction Steps

create a disk from code;
attach it to a vm that is on a availability zone
It fails.

**Comment by SavaNDragos** [comment]
for premium SSD (v1) the zones can be left empty; but they might also need a zone set;

**Comment by SavaNDragos** [comment]
so In azure deployment template:
parameters:
..
        "zone": {
            "type": "String"
        },
..
"resources": [
...
            "zones": [
                "[parameters('zone')]"
            ],
...

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by SavaNDragos** [comment]
this should be a simple set
