### ISSUE TITLE
[BUG] Incomplete output in results

### ISSUE THREAD

**Issue by church365** [Azure/azure-sdk-for-net#39126]
### Library name and version

Azure.ResourceManager.AppService 1.0.2

### Describe the bug

I'm using this method to retrieve a list of processes from a given app service. There is a similar REST API here:
https://learn.microsoft.com/en-us/rest/api/appservice/web-apps/list-processes

GET https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Web/sites/{name}/processes?api-version=2022-03-01

That REST call retrieves useful information including the properties object, which includes the file name of the running process. I don't see the file name in the results of this SDK method; there is a "filename" property, but it's always null compared to the REST results against the same running processes. Please advise if something is missing from this output.

### Expected behavior

At least as much information available in the SDK method output call as is available in the REST output.

### Actual behavior

No actual information on the process itself, just a few populated properties of metadata like the process ID, resource ID, etc. Under the "Data" property, "Children" is empty, as is "EnvironmentVariables", FileName, HandleCount, Modules, OpenFileHandles, etc. In fact most of "Data" is empty. However, for the process I'm inspecting with all those null values, HasData=true.

### Reproduction Steps

        public async Task<List<SiteProcessResource>> GetProcesses(CancellationToken cancellationToken)
        {
            var id = WebSiteResource.CreateResourceIdentifier(
                subscriptionId: _tenant.AzureSubId,
                resourceGroupName: SiteUtils.AzureRGName,
                name: _webApp.ServiceName);
            var svcMgr = _armClient.GetWebSiteResource(id);
            var processList = svcMgr.GetSiteProcesses();
            var lst = processList.GetAllAsync(cancellationToken);
            var res = await lst.ToListAsync(cancellationToken);
            return res;
        }

### Environment

Azure Windows Function (on app hosting plan), runtime ~4, 32 bit, integrated pipeline, code is .net core 6.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi @church365 Thank you for using Azure SDK for .NET.
We can't repro your issue based on the information you provided. 
It would be helpful if you could provide some details of the function app you used or the actual payload for the issue operation(exclude the sensitive data).

**Comment by bretthacker** [comment]
I only just got an email notification of activity for this ancient bug. I worked around it so I can't tell you if it's been fixed. I filed it as a service to your PG. Do with it what you will. But it absolutely was returning null. No idea if the bug was a mapping issue in the SDK or missing output from the API.

**Comment by HarveyLink** [comment]
Reopen this bug.
Update:
- The `List` operation will not return process details, it's by service design.
- We could get the process details with its `Id` (int number), like: 
   ```await instance.GetSiteInstanceProcesses().GetAsync("3040")```

- Found a new issue in SDK while deserialize response content. Class: `ProcessThreadInfo` property `id` is actually `int` value, not `ResourceIdentifier`. Need to correct it and release a new version to fix it.
![image](https://github.com/user-attachments/assets/9d6c73db-3c95-4450-abe8-52959946dbe9)

**Comment by welovej** [comment]
#45091
