### ISSUE TITLE
Upgrade Microsoft.Azure.Search (Version 10.1.0) to Azure.Search.Documents(Verion 11.4.0), The geography points are serialized differently

### ISSUE THREAD

**Issue by baskialdensys** [Azure/azure-sdk-for-net#39127]
### Library name and version

Azure.Search.Documents 11.4.0

### Query/Question

Microsoft.Azure.Search (Version 10.1.0) Geography Point serialization output:

"location": {
     "latitude": 39.2428832397,
     "longitude": -75.8474861165,
     "isEmpty": false,
     "z": null,
     "m": null,
     "coordinateSystem": {
        "epsgId": 4326,
        "id": "4326",
        "name": "WGS84"
     }
}

Azure.Search.Documents(Verion 11.4.0) Geography point serialization output:

"location": {
    "type": "Point",
    "coordinates": [
       -75.5646879643,
       39.7093928328
     ],
    "crs": {
         "type": "name",
         "properties": {
         "name": "EPSG:4326"
    }
   }
  }
We are using NewtonsoftJsonMicrosoftSpatialGeoJsonConverter, how can we retain the Microsoft.Azure.Search (Version 10.1.0) serialization format? This would allow our clients to use our current API without making any changes in their end.

**Comment by pallavit** [comment]
Thank you for reporting the issue. Azure.Search.Documents maintains feature parity with Microsoft.Azure.Search however there are some breaking changes between the two versions. GeographyPoint was one such difference between the two libraries.

For Azure.Search.Documents library, we support [Microsoft.Azure.Core.Spatial](https://www.nuget.org/packages/Microsoft.Azure.Core.Spatial/1.2.0-beta.1) and it contains MicrosoftSpatialGeoJsonConverter  which converts between Microsoft.Spatial objects and Geo-JSON. Please see the [readme](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Microsoft.Azure.Core.Spatial/README.md) for more details.

You can find all the differences between the two libraries in our [migrationguide](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/MigrationGuide.md). 

/cc: @ShivangiReja for FYI. We should consider adding this information to our migration guide.

**Comment by baskialdensys** [comment]
Thank you. we tried to write a custom serializer to mimic the serialization of Microsoft.Azure.Search (Version 10.1.0) for GeographyPoint, but it never got called. Is it possible to just override the serialization of GeographyPoint? If so, please point us in the right direction.

**Comment by ShivangiReja** [comment]
@pallavit, we have already documented this information in our [migration guide](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/MigrationGuide.md#migration-guide), which is part of the attached [upgrade document](https://docs.microsoft.com/azure/search/search-dotnet-sdk-migration-version-11).

Specifically, you can find details about JSON serialization in the section titled [JSON Serialization](https://learn.microsoft.com/en-us/azure/search/search-dotnet-sdk-migration-version-11#json-serialization).

**Comment by baskialdensys** [comment]
In Azure.Search.Documents(Verion 11.4.0) we have two serialization options
1. JsonObjectSerializer
2. NewtonsoftJsonObjectSerializer

With JsonObjectSerializer GeographyPoint is serailized as below
```json
 "location": {
    "coordinates": {
         "altitude": null,
         "longitude": -92.60729599,
         "latitude": 40.18714009,
         "count": 2
    },
    "type": "Point",
    "boundingBox": null
 
```
with NewtonsoftJsonObjectSerializer GeoGraphyPoint is serialized as 

```json
"location": {
    "type": "Point",
    "coordinates": [
             -75.5646879643,
             39.7093928328
     ],
     "crs": {
            "type": "name",
            "properties": {
            "name": "EPSG:4326"
            }
     }
}

```
Default Geogrphypoint serialization with Microsoft.Azure.Search (Version 10.1.0) is below, and this is the format we are expecting the output to be
```json
"location": {
       "latitude": 39.2428832397,
       "longitude": -75.8474861165,
       "isEmpty": false,
       "z": null,
       "m": null,
       "coordinateSystem": {
            "epsgId": 4326,
            "id": "4326",
             "name": "WGS84"
       }
}
```

**Comment by ShivangiReja** [comment]
Hi @baskialdensys, I've been working with Azure.Search.Documents (Version 11.4.*) and created a test case based on your scenario using the `Microsoft.Spatial.GeographyPoint` type, `NewtonsoftJsonMicrosoftSpatialGeoJsonConverter`, and `NewtonsoftJsonObjectSerializer`. You can find the sample [here](https://github.com/ShivangiReja/azure-sdk-for-net/blob/Issue39127/sdk/search/Azure.Search.Documents/tests/DocumentOperations/GeographyPointTest.cs#L27-L93).

Here's the [GeographyPoint](https://github.com/ShivangiReja/azure-sdk-for-net/blob/Issue39127/sdk/search/Azure.Search.Documents/tests/DocumentOperations/GeographyPointTest.cs#L91) Json:

```json
"Summit": {
    "type": "Point",
    "coordinates": [
      -75.5646879643,
      39.7093928328
    ],
    "crs": {
      "type": "name",
      "properties": {
        "name": "EPSG:4326"
      }
    }
  }
```

We are following the GeoJSON format guidelines available [here](https://geojson.org/).

I noticed that in your JSON for GeographyPoint serialization with Microsoft.Azure.Search (Version 10.1.0), some required properties like "type" seem to be missing. According to [RFC7946](https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.2), "type" is required. If you pass JSON without "type," the service will throw an exception similar to this:

```c#
Azure.RequestFailedException: The request is invalid. Details: Invalid GeoJSON. The 'type' member is required, but was not found.
Status: 400 (Bad Request)
Content: {"error":{"code":"","message":"The request is invalid. Details: Invalid GeoJSON. The 'type' member is required, but was not found."}}
```

I also noticed that tests in Microsoft.Azure.Search (Version 10.1.0) seem to consider [this format](https://github.com/Azure/azure-sdk-for-net/blob/Microsoft.Azure.Search_10.1.0/sdk/search/Microsoft.Azure.Search/tests/Tests/Serialization/GeoJsonPointConverterTests.cs#L35) as a well-formed GeoJSON.

Hope this helps clarify the situation!

**Comment by ShivangiReja** [comment]
I'd also like to point out that if you need a different format for your JSON with `Azure.Search.Documents`, you can create a custom converter and include it in your code [here](https://github.com/ShivangiReja/azure-sdk-for-net/blob/Issue39127/sdk/search/Azure.Search.Documents/tests/DocumentOperations/GeographyPointTest.cs#L37-L40). This way, you can tailor the JSON based on your specific requirements.

**Comment by ShivangiReja** [comment]
@baskialdensys For your reference, the Microsoft.Azure.Search_10.1.0 library uses the following default JSON structure for the `GeographyPoint` type, as seen in [this test](https://github.com/Azure/azure-sdk-for-net/blob/Microsoft.Azure.Search_10.1.0/sdk/search/Microsoft.Azure.Search/tests/Tests/IndexingTests.cs#L44):

```json
{
  "location": {
    "type": "Point",
    "coordinates": [
      -73.975403,
      40.760586
    ]
  }
}
```

This JSON format is based on the recorded response for the same test, which can be found [here](https://github.com/Azure/azure-sdk-for-net/blob/Microsoft.Azure.Search_10.1.0/sdk/search/Microsoft.Azure.Search/tests/SessionRecords/IndexingTests/CanIndexDynamicDocuments.json#L418).

You can refer to the entire test case [here](https://github.com/Azure/azure-sdk-for-net/blob/Microsoft.Azure.Search_10.1.0/sdk/search/Microsoft.Azure.Search/tests/Tests/IndexingTests.cs#L23-L168) for more details.

**Comment by baskialdensys** [comment]
Thank you so much for your detailed explanations. However, we are still receiving the following format from Microsoft.Azure.Search_10.1.0:

```json
"location": {
    "latitude": 39.2428832397,
    "longitude": -75.8474861165,
    "isEmpty": false,
    "z": null,
    "m": null,
    "coordinateSystem": {
        "epsgId": 4326,
        "id": "4326",
        "name": "WGS84"
    }
}
```

Even though Microsoft.Azure.Search_10.1.0's GeoJSON documentation is very clear about the GeoJSON format, we are getting the above output.

A few differences I can think of are as follows:

1. Our old code uses .NET Framework 4.7.2.
2. It uses Microsoft.Spatial (version 7.9.0) targeting .NET Standard 1.1 with the OData specification.

Do you think this might be the reason we are seeing a different output?

We also tried a custom converter, but the converter call is only made for the SearchDocument object (root level) and not for the GeographyPoint inside the SearchDocument instance."

**Comment by ShivangiReja** [comment]
I've written code to mimic your scenario using both the `Microsoft.Azure.Search` and `Azure.Search.Documents` libraries. Here are my observations:

**Using Microsoft.Azure.Search:**

I created a [console app](https://github.com/ShivangiReja/MyTestConsoleApp/blob/main/MyConsoleApp/Program.cs#L18) based on your scenario using ["Microsoft.Azure.Search" Version="10.1.0"](https://github.com/ShivangiReja/MyTestConsoleApp/blob/main/MyConsoleApp/MyConsoleApp.csproj#L9C31-L9C72).

After creating an index and uploading the data, the JSON format in the portal appears as shown below:
![Portal JSON Format](https://github.com/Azure/azure-sdk-for-net/assets/45216704/f02e2dda-4e5d-44eb-8b28-ddfb699ef7f6)

When querying the data, the default deserialization of the "location" field results in the following [JSON structure](https://github.com/ShivangiReja/MyTestConsoleApp/blob/main/MyConsoleApp/Program.cs#L61-L73). @baskialdensys, I believe you mentioned about this json being different:

```json
{
    "Latitude": -75.5646879643,
    "Longitude": 39.7093928328,
    "IsEmpty": false,
    "Z": null,
    "M": null,
    "CoordinateSystem": {
        "EpsgId": 4326,
        "Id": "4326",
        "Name": "WGS84"
    }
}
```

**Using Azure.Search.Documents:**

I've also written similar code [here](https://github.com/ShivangiReja/azure-sdk-for-net/blob/aa8c50b2e5008d796d2a8ed929d6edf9bdc9aa81/sdk/search/Azure.Search.Documents/tests/DocumentOperations/GeographyPointTest.cs#L102-L168) using the `Azure.Search.Documents` library to mimic the behavior of `Microsoft.Azure.Search`.

When querying the data using the `Azure.Search.Documents` library, the "location" field gets deserialized in the format that matches the portal:

```json
{
  "type": "Point",
  "coordinates": [
    39.7093928328,
    -75.5646879643
  ],
  "crs": {
    "type": "name",
    "properties": {
      "name": "EPSG:4326"
    }
  }
}
```

**My observation:**

As @pallavit's suggested, that there might be some breaking changes between `Azure.Search.Documents` and `Microsoft.Azure.Search`, and this deserialization difference is likely one of those breaking changes.

**Comment by ShivangiReja** [comment]
If you prefer to have the same format as [Microsoft.Spatial.GeographyPoint](https://learn.microsoft.com/en-us/dotnet/api/microsoft.spatial.geographypoint?view=odata-spatial-7.0), you can utilize a strong C# type, as demonstrated [here](https://github.com/ShivangiReja/azure-sdk-for-net/blob/b21be5a7994593aa3fc27a4a283325a636e27f9f/sdk/search/Azure.Search.Documents/tests/DocumentOperations/GeographyPointTest.cs#L98). By doing this, when you receive the [result](https://github.com/ShivangiReja/azure-sdk-for-net/blob/b21be5a7994593aa3fc27a4a283325a636e27f9f/sdk/search/Azure.Search.Documents/tests/DocumentOperations/GeographyPointTest.cs#L75), the 'Location' property will deserialize in the format of [Microsoft.Spatial.GeographyPoint](https://learn.microsoft.com/en-us/dotnet/api/microsoft.spatial.geographypoint?view=odata-spatial-7.0), like this:

```json
{
    "Latitude": -75.5646879643,
    "Longitude": 39.7093928328,
    "Z": null,
    "M": null,
    "CoordinateSystem": {
        "EpsgId": 4326,
        "Id": "4326",
        "Name": "WGS84"
    },
    "IsEmpty": false
}
```

This approach ensures that the 'Location' property deserializes in the specified format.

**Comment by baskialdensys** [comment]
Unfortunately, we won't be able to use any strong C# types. Our search service supports various assets, and we use a very generic model based on the SearchDocument.

Any other work around for us?

**Comment by baskialdensys** [comment]
Unfortunately, we won't be able to use any strong C# types. Our search service supports various assets, and we use a very generic model based on the SearchDocument.

Any other work around for us ?

**Comment by baskialdensys** [comment]
> I've written code to mimic your scenario using both the `Microsoft.Azure.Search` and `Azure.Search.Documents` libraries. Here are my observations:
> 
> **Using Microsoft.Azure.Search:**
> 
> I created a [console app](https://github.com/ShivangiReja/MyTestConsoleApp/blob/main/MyConsoleApp/Program.cs#L18) based on your scenario using ["Microsoft.Azure.Search" Version="10.1.0"](https://github.com/ShivangiReja/MyTestConsoleApp/blob/main/MyConsoleApp/MyConsoleApp.csproj#L9C31-L9C72).
> 
> After creating an index and uploading the data, the JSON format in the portal appears as shown below: ![Portal JSON Format](https://user-images.githubusercontent.com/45216704/274080572-f02e2dda-4e5d-44eb-8b28-ddfb699ef7f6.png)
> 
> When querying the data, the default deserialization of the "location" field results in the following [JSON structure](https://github.com/ShivangiReja/MyTestConsoleApp/blob/main/MyConsoleApp/Program.cs#L61-L73). @baskialdensys, I believe you mentioned about this json being different:
> 
> ```json
> {
>     "Latitude": -75.5646879643,
>     "Longitude": 39.7093928328,
>     "IsEmpty": false,
>     "Z": null,
>     "M": null,
>     "CoordinateSystem": {
>         "EpsgId": 4326,
>         "Id": "4326",
>         "Name": "WGS84"
>     }
> }
> ```
> 
> **Using Azure.Search.Documents:**
> 
> I've also written similar code [here](https://github.com/ShivangiReja/azure-sdk-for-net/blob/aa8c50b2e5008d796d2a8ed929d6edf9bdc9aa81/sdk/search/Azure.Search.Documents/tests/DocumentOperations/GeographyPointTest.cs#L102-L168) using the `Azure.Search.Documents` library to mimic the behavior of `Microsoft.Azure.Search`.
> 
> When querying the data using the `Azure.Search.Documents` library, the "location" field gets deserialized in the format that matches the portal:
> 
> ```json
> {
>   "type": "Point",
>   "coordinates": [
>     39.7093928328,
>     -75.5646879643
>   ],
>   "crs": {
>     "type": "name",
>     "properties": {
>       "name": "EPSG:4326"
>     }
>   }
> }
> ```
> 
> **My observation:**
> 
> As @pallavit suggested, there might be some breaking changes between `Azure.Search.Documents` and `Microsoft.Azure.Search`, and this deserialization difference is likely one of those breaking changes.

Please make sure this is documented in breaking changes,

**Comment by pallavit** [comment]
Thanks @baskialdensys we will work on adding this to the breaking changes documentation. I will go ahead and mark this as issue_addressed given this is an intentional change between track1 and track2. Please let us know if can assist you with anything else.
