### ISSUE TITLE
[BUG] User delegation SAS token is not valid for file path with the specified number of directory segments

### ISSUE THREAD

**Issue by mmkowal-rel** [Azure/azure-sdk-for-net#39158]
### Library name and version

Azure.Storage.Files.DataLake 12.14.0

### Describe the bug

I'm trying to generate SAS token with read and list permission in order to download a single file from ADLS fileshare. 
For unknown reasons token generated for the file path containing no more than 8 directories (counting from the root of the container) works fine, given identity is able to download the file. 
However when the path contains 9 and more directories token generated in exactly the same way, for the same identity and for the same path is invalid. 

See the example code:

    public async Task<string> Abc(Uri storageAccountUri, string containerName, string requestedPath, CancellationToken cancellationToken)
		{
			var identity = new DefaultAzureCredential(new DefaultAzureCredentialOptions
			{
				ManagedIdentityClientId = "xxx-xxx-xxx-xxx",
			});

			var dataLakeServiceClient = new DataLakeServiceClient(storageAccountUri, identity);

			var delegationKey =
				await dataLakeServiceClient.GetUserDelegationKeyAsync(DateTimeOffset.UtcNow,
					DateTimeOffset.UtcNow.AddHours(2), cancellationToken).ConfigureAwait(false);

			var sasBuilder = new DataLakeSasBuilder
			{
				FileSystemName = containerName,
				Resource = "d",
				IsDirectory = true,
				Path = requestedPath,
				ExpiresOn = DateTimeOffset.UtcNow.AddHours(2),
				Protocol = SasProtocol.Https
			};

			sasBuilder.SetPermissions(DataLakeAccountSasPermissions.Read | DataLakeAccountSasPermissions.List);

			DataLakeSasQueryParameters dataLakeSasQueryParameters = sasBuilder.ToSasQueryParameters(delegationKey.Value, _ACCOUNT_NAME);

			var uriBuilder = new DataLakeUriBuilder(_STORAGE_ACCOUNT_URI)
			{
				Sas = dataLakeSasQueryParameters,
				DirectoryOrFilePath = requestedPath,
				FileSystemName = containerName
			};

			string token = uriBuilder.ToUri().Query;

			return token;
		}
,

### Expected behavior

it is expected that SAS token is valid regardless of the nested level and allows to download of the file when it is located in:

### Actual behavior

It looks like there is some kind of limit when it comes to the number of path segments. when the source file is under the 8th directory (counting from the root of the container)
\0\1\2\3\4\5\6\7 - this currently FAILS with exception:

> Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature

but when the exact same file is located under 7th nested directory or higher (6, 5, and so on) the SAS token is valid.  
\0\1\2\3\4\5\6 - this works WORKS

It seems that when SAS Token is generated the directory depth is automatically detected and set to proper value. 
For example, having 10 folders structure sets the property to 10, but the token turns out to be invalid.

### Reproduction Steps

See the example code above.

### Environment

console app, .net 6, windows10

**Comment by KlaudiuszBryjaRelativity** [comment]
This issue was resolved under this one:
https://github.com/Azure/azure-sdk-for-net/issues/40528

Because it was closed, this issue can also be closed.
