### ISSUE TITLE
How to create an error response for mocking error?

### ISSUE THREAD

**Issue by sadviramana** [Azure/azure-sdk-for-net#39157]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 376e2c70-c811-ecc8-2fa4-c5b12fbea1df
* Version Independent ID: 44106a9f-551c-c279-1f7d-d1d243882ba5
* Content: [Response Class (Azure) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.response?view=azure-dotnet)
* Content Source: [xml/Azure/Response.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure/Response.xml)
* Service: **azure**
* GitHub Login: @azure-sdk
* Microsoft Alias: **azsdkdocs**

**Comment by pallavit** [comment]
Thank you for reaching out. 

Azure.Core.TestFramework supports MockResponse class that can be used to create Mock responses including error scenarios. You can find samples here - https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/core/Azure.Core.TestFramework#unit-tests

Hope this helps.
