### ISSUE TITLE
Unable to read key vault secret with AzureKeyVault configbuilder without Get and List permission

### ISSUE THREAD

**Issue by jimt4593** [Azure/azure-sdk-for-net#3915]
I am using the AzureKeyVault configbuilder (Microsoft.Configuration.ConfigurationBuilders.Azure 1.0.0-preview) to retrieve an app setting from key vault.    The web.config contains:

```
 <add name="AzureKeyVault"
           vaultName="valid key vault name"
           clientId="valid client id"
           clientSecret="valid client secret"
           type="Microsoft.Configuration.ConfigurationBuilders.AzureKeyVaultConfigBuilder, Microsoft.Configuration.ConfigurationBuilders.Azure, Version=1.0.0.0, Culture=neutral" />
```
Unfortunately, I was unable to retrieve the secret when the principal (associated with the clientId) had only the Get Secret permission.

I had to give the prinicipal the List Secret permission.

**Comment by shahabhijeet** [comment]
@jimt4593 please open an issue over here
https://github.com/aspnet/MicrosoftConfigurationBuilders/issues
