### ISSUE TITLE
[BUG] OpenTelemetry - ServiceBus message spans are reported in Azure.Messaging.ServiceBus activity source (same for EH)

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-net#39166]
### Library name and version

Azure.Messaging.ServiceBus, Azure.Messaging.EventHubs, Azure.Core

### Describe the bug

The convention we have is to use `<root namespace>.<client name>` for ActivitySource names so that users can enable individual libraries using `AddSource("<root namespace>.*")` and can even enable tracing on individual clients if necessary.

Message spans are created in a different way than service method spans, and due to this logic 

https://github.com/Azure/azure-sdk-for-net/blob/aa5fe51801498a3d967b85caaeb3bd53c4d3a2ad/sdk/core/Azure.Core/src/Shared/DiagnosticScopeFactory.cs#L102-L107

end up with  `Azure.Messaging.ServiceBus|EventHubs` source name, not following the above convention (`<root namespace>.*`)

### Expected behavior

Message spans are special - they are coming from sender client, but we'd like to be able to enable them independently from sender spans, so ideally they should be reported by `Azure.Messaging.ServiceBus|EventHubs.Message` (or similar) sources.

### Actual behavior

ServiceBus and EventHubs report message spans from `Azure.Messaging.ServiceBus|EventHubs` sources.

### Reproduction Steps

1. Create simple ServiceBus producer app
2. Listen to all activity sources and print their names 
    ```csharp
    ActivitySource.AddActivityListener(new ActivityListener()     {
        ShouldListenTo = l => { Console.WriteLine(l.Name); return false; }});
    ```
3. Send some messages and check the sources:

```
Azure.Messaging.ServiceBus
Azure.Messaging.ServiceBus.ServiceBusSender
```

**Comment by JoshLove-msft** [comment]
We discussed offline and we will amend the logic used in creating the activity source name to always include the activity name even if it doesn't contain a `.`. Thus the name for the Message activity will be `Azure.Messaging.ServiceBus.Message`.
