### ISSUE TITLE
[BUG] Cannot create WebActivity headers

### ISSUE THREAD

**Issue by chinarosesz** [Azure/azure-sdk-for-net#39187]
### Library name and version

Azure.ResourceManager.DataFactory v1.0.0-beta.4

### Describe the bug

I'm having a lot of trouble creating a web activity headers. I've tried using literal string, secure string, and expression. And none of this worked for the basic scenario such as setting a basic key/value pair. 

The previous SDK worked because the headers takes in a dictionary, but the new SDK takes in a DataFactoryElement<string>. 

### Expected behavior

Generated key value pairs for headers

### Actual behavior

Generated value of 0, 1, 2, 3, and each character from the literal string as single item. 

### Reproduction Steps

// Create pipeline web activity
DataFactoryElement<string> uri = $"@concat('https://{functionAppName}.azurewebsites.net/api/SyncPermissionsFunction?organization={org.Url}&code=',pipeline().parameters.functionkey)";
WebActivity webActivity = new WebActivity("SyncPermissionsFunction", WebActivityMethod.Get, uri);

// This line does not work.
webActivity.Headers = DataFactoryElement<string>.FromLiteral("foo");

**Comment by pallavit** [comment]
Thank you for reporting the issue. Could you please share the name of the SDK you are trying to use?

**Comment by chinarosesz** [comment]
Yes. This is the package I am using.

        <PackageReference Include="Azure.ResourceManager.DataFactory" Version="1.0.0-beta.4" />

**Comment by Frey-Wang** [comment]
What's the error you see here? From my perspective, you are using expression, so you can try something like:
```csharp
var uri = DataFactoryElement<string>.FromExpression($"@concat($"@concat('https://{functionAppName}.azurewebsites.net/api/SyncPermissionsFunction?organization={org.Url}&code=',pipeline().parameters.functionkey)");
var webActivity = new WebActivity("SyncPermissionsFunction", WebActivityMethod.Get, uri);
```

**Comment by chinarosesz** [comment]
I’m trying to pass in the headers. And the headers should be treated like an object or a dictionary. As of now it only takes in a string, and there is no way for me to construct headers if it is of type string. I have tried the whole day to construct the headers from the SDK and have no luck. Can you try on your side to construct a webactivity with headers?

**Comment by DavidKarlas** [comment]
I'm facing same problem but from other side, I want to run GetDataFactoryPipelines method on DataFactoryResource class and it is throwing exception ```System.InvalidCastException: 'Unable to cast object of type 'System.Collections.Generic.Dictionary`2[System.String,System.Object]' to type 'System.String'.'```

Turns out [deserializing code](https://github.com/thomhurst/azure-sdk-for-net/blob/3bfd7ba3dc94af7e4d2aba8a6a4661c0b6729c66/sdk/datafactory/Azure.ResourceManager.DataFactory/src/Generated/Models/AzureFunctionActivity.Serialization.cs#L208) wants to read String, but JSON returned from API has `"headers": {}` hence exception...

**Comment by DavidKarlas** [comment]
This is weird, linked code is different than one I'm debugging:
![image](https://github.com/Azure/azure-sdk-for-net/assets/774791/3bf17e6f-c423-40cf-885d-44ba3fd78dfe)
Notice that debugged code is not decompiled, but came from source server...

**Comment by chinarosesz** [comment]
Correct, 

> I'm facing same problem but from other side, I want to run GetDataFactoryPipelines method on DataFactoryResource class and it is throwing exception `` System.InvalidCastException: 'Unable to cast object of type 'System.Collections.Generic.Dictionary`2[System.String,System.Object]' to type 'System.String'.' ``
> 
> Turns out [deserializing code](https://github.com/thomhurst/azure-sdk-for-net/blob/3bfd7ba3dc94af7e4d2aba8a6a4661c0b6729c66/sdk/datafactory/Azure.ResourceManager.DataFactory/src/Generated/Models/AzureFunctionActivity.Serialization.cs#L208) wants to read String, but JSON returned from API has `"headers": {}` hence exception...

That’s correct. I get the same error as well. It expects a json object but the SDK property requires headers to be passed in a string. A WebActivity without headers is not going to do much..we need this fixed. Or might have to revert back to the old SDK.

**Comment by chinarosesz** [comment]
Is there any update on this? I am happy to help and fix this issue as well so my team can leverage this feature. It's hard to use a webactivity without the ability to pass in headers.

**Comment by DavidKarlas** [comment]
I tested https://github.com/Azure/azure-rest-api-specs/pull/26334 and works perfect for me... Not sure how to raise priority on this, because even most basic stuff like fetching pipelines doesn't work, if they have this headers set....

**Comment by chinarosesz** [comment]
@ArthurMa1978 , still no traction on this issue, can we proceed with the above PR? We need headers to work for webactivity in Azure Data Factory.

**Comment by DavidKarlas** [comment]
Not sure if I should be angry or just sad... I even went as far as opening PR... This API is totally broken, I don't get it why is this not getting merged... Is ADF dead product? Should we start transitioning away from it?

**Comment by chinarosesz** [comment]
I’m wondering the same here as well. Let’s see if we can escalate this together to someone in Azure since no response from here much. Getting very frustrated because this is the core functionality of a webactivity.

**Comment by DavidKarlas** [comment]
It is not just about not being able to set WebActivity...
I literally can't fetch pipelines info, if there is any WebActivity in whole ADF factory, making whole API useless...

**Comment by ruowan** [comment]
I am from ADF team. Thanks for feedback we are taking look at this issue. And trying to fix it.

**Comment by DavidKarlas** [comment]
@ruowan  can this be closed, or waiting for NuGet to be published?
