### ISSUE TITLE
[BUG] Preview SearchModelFactory.SearchResults<T> does not allow mocking of Answers or Captions

### ISSUE THREAD

**Issue by kevnwang** [Azure/azure-sdk-for-net#39196]
### Library name and version

Azure.Search.Documents v11.5.0-beta.5

### Describe the bug

Preview version of SearchModelFactory.SearchResults<T> does not take in parameters for Answers, Captions, SemanticPartialResponseReason, and SemanticPartialResponseType

### Expected behavior

Answers, Captions, SemanticPartialResponseReason, and SemanticPartialResponseType should be passable as parameters to create SearchResults instances for mocking that include those properties

### Actual behavior

Answers, Captions, SemanticPartialResponseReason, and SemanticPartialResponseType are not passable as parameters, causing those properties to become unmockable when part of SearchResults

### Reproduction Steps

Attempt to mock SearchAsync like the following:

```
var clientMock = new Mock<SearchClient>();
var responseMock = new Mock<Response>();

var resultMock = SearchModelFactory.SearchResult(new SearchDocument() { { "metadata_storage_name", null } }, null, null);
var resultsMock = SearchModelFactory.SearchResults(new[] { resultMock }, 1, null, null, responseMock.Object);

clientMock.Setup(x => x.SearchAsync<SearchDocument>(It.IsAny<string>(), It.IsAny<SearchOptions>(), It.IsAny<CancellationToken>()))
    .ReturnsAsync(Response.FromValue(resultsMock, responseMock.Object));
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
