### ISSUE TITLE
[BUG] System.Net.Sockets.SocketException, unreachable network 169.254.169.254:80

### ISSUE THREAD

**Issue by ToddEvansHome** [Azure/azure-sdk-for-net#39199]
### Library name and version

Azure.Identity 1.10.2

### Describe the bug

Azure.Identity worked with version 1.10.0.  Version 1.10.1 introduced the following error 
_Request [e900b25d-5aa9-48b1-9e77-69c9da683360] exception Azure.RequestFailedException: Unable to connect to the remote server ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A socket operation was attempted to an unreachable network 169.254.169.254:80
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)_
   
  The error happens when calling AzureTable.TableClient.CreateIfNotExists(); 

### Expected behavior

No exception should occur.   169.254.169.254:80 is unreachable from a local machine

### Actual behavior

The following exception is thrown
Request [e900b25d-5aa9-48b1-9e77-69c9da683360] exception Azure.RequestFailedException: Unable to connect to the remote server ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A socket operation was attempted to an unreachable network 169.254.169.254:80
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)

### Reproduction Steps

Call the following method
```c#
using Azure.Core;
using Azure.Data.Tables;
private readonly string _connectionString;
public AzureTable(string connectionString, string tableName, bool createIfNotExist = true, int retryDelay = 1, int maxRetries = 4, RetryMode retryMode = RetryMode.Exponential)
{
    TableClientOptions clientOptions = new TableClientOptions(TableClientOptions.ServiceVersion.V2020_12_06)
    {
        Diagnostics = { IsLoggingContentEnabled = false, IsLoggingEnabled = true, IsDistributedTracingEnabled = false  }, 
    };


    clientOptions.Retry.Delay = TimeSpan.FromSeconds(retryDelay);
    clientOptions.Retry.Mode = retryMode;
    clientOptions.Retry.MaxRetries = maxRetries;
    clientOptions.Retry.NetworkTimeout = new TimeSpan(0, 2, 0);
    
    _connectionString = connectionString;
    TableClient = new TableClient(_connectionString, tableName, clientOptions);

    if (createIfNotExist)
    {
        TableClient.CreateIfNotExists();
    }
}
```

### Environment

Windows 11, .NET Framework 4.8 console application
Visual Studio 2022 v17.7.4

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ToddEvansHome** [comment]
Sorry, this is not the issue I was having.  I will close this issue.  Sorry for the inconvenience
