### ISSUE TITLE
[QUERY] Does C# Azure SDK allow us to get/set/reset Azure SQL Server Administrator Password?

### ISSUE THREAD

**Issue by alwynjohnlim** [Azure/azure-sdk-for-net#39193]
### Library name and version

Azure.ResourceManager.Sql

### Query/Question

Hi,

I am trying to get/set/reset a SQL Server Admin password using the Azure SDK. I am using a service principal as my credentials and have its Owner RBAC access to my SQL server.
I know, I can reset my SQL server admin password through the portal. But what I need is to do it via Azure SDK, is this possible?

Also, I tried to get the AdministratorLoginPassword below, but it is returning null.

            ArmClient armClient = new ArmClient(new DefaultAzureCredential());
            SubscriptionResource subscriptionResource = await armClient.GetDefaultSubscriptionAsync();
            ResourceGroupResource resourceGroupResource = subscriptionResource.GetResourceGroup("*****);
            SqlServerResource sqlServerResource = resourceGroupResource.GetSqlServer("*******");
            var password= sqlServerResource.Data.AdministratorLoginPassword;
            
Any thoughts on this?
The reason I need this is because I want to export my SQL databases using the REST API and I need to supply the AdministratorLoginPassword in the body. Is this possible, without me having the old AdministratorLoginPassword?

Thanks,
Alwyn

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by alwynjohnlim** [comment]
Hi,

Just found out that I can reset SQL server password using below. However, it would be better if I could just get the current password instead of resetting it. Any thoughts?

            SqlServerResource sqlServerResource = await resourceGroupResource.GetSqlServerAsync("********");
            var sqlServerPatch = new SqlServerPatch() { AdministratorLoginPassword = tempPassword };
            wait sqlServerResource.UpdateAsync(WaitUntil.Completed, sqlServerPatch);
            
Thanks,
Alwyn

**Comment by HarveyLink** [comment]
Hi @alwynjohnlim , Thank you for using Azure SDK for .NET.
As Azure SQL service design, it's impossible for us to get the admin password once we had the server create OR password reset.
These two scenario is the only window we could get the password value.
