### ISSUE TITLE
[QUERY] Register named ServiceBusClient with SAS credential

### ISSUE THREAD

**Issue by folbo** [Azure/azure-sdk-for-net#39218]
### Library name and version

Azure.Messaging.ServiceBus (7.16.1)

### Query/Question

Is it possible to register the AzureClient for ServiceBus with fully qualified namespace and SAS instead of full connectionString or TokenCredential using extensions methods from this lib?

I can't find an overload of AddServiceBusClientWithNamespace that accepts AzureSasToken object like this:
```csharp
serviceCollection.AddAzureClients(clientsBuilder =>
{
    clientsBuilder
        .AddServiceBusClientWithNamespace("fullyQualifiedNamespace", new AzureSasCredential("sas")) //error
        .WithName("serviceBus1");
}
```
However, `ServiceBusClient` has a constructor that accepts fullyQualifiedNamespace and a SasTokenCredential:
```csharp
var serviceBusClient = new ServiceBusClient("fullyQualifiedNamespace", new AzureSasCredential("sas"));
```
https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusclient.-ctor?view=azure-dotnet#azure-messaging-servicebus-servicebusclient-ctor(system-string-azure-azuresascredential-azure-messaging-servicebus-servicebusclientoptions)

I know I could register the client "manually" but the SDK has very convincing named registrations of clients and injectable factory which can resolve named dependencies. Is there a convenient way to do it?

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.413
 Commit:    10710f7d8e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @folbo,
You should be able to leverage the overload that takes an IConfiguration instance like this:
```c#
builder.Services.AddAzureClients(
    clients => clients.AddServiceBusClient(builder.Configuration.GetSection("ServiceBus")));
```

Where you have a config section like this:
```
  "ServiceBus": {
    "fullyQualifiedNamespace": "sb://<namespace>.servicebus.windows.net/",
    "credential" : {
      "signature": "<sas>"
      }
  }
```
