### ISSUE TITLE
[BUG] AKV10000: Request is missing a Bearer or PoP token. - Intermittent issue

### ISSUE THREAD

**Issue by danyltsiv** [Azure/azure-sdk-for-net#39216]
### Library name and version

Azure.Security.KeyVault.Secrets 4.0.1

### Describe the bug

From time to time we've got:
401 (Unauthorized)
{"error":{"code":"Unauthorized","message":"AKV10000: Request is missing a Bearer or PoP token."}}
throwing in:
```
async Azure.Security.KeyVault.KeyVaultPipeline.SendRequestAsync(??)
   
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   
async Azure.Security.KeyVault.KeyVaultPipeline.SendRequestAsync[TResult](??)
   
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   
async Azure.Security.KeyVault.Secrets.SecretClient.GetSecretAsync(String name,String version,CancellationToken cancellationToken)
   
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

It's happening at the beginning of the execution of activity within **Azure Durable Function**

Code that adds Secret Services looks as follows:
```
services.AddAzureClients(clientBuilder =>
{
    var clientId = configuration["ManagedIdentityClientId"];
    var credentials = string.IsNullOrWhiteSpace(clientId)
        ? (TokenCredential)new DefaultAzureCredential()
        : new ManagedIdentityCredential(clientId);
    clientBuilder
        .AddSecretClient(new Uri(configuration["VaultUri"]))
        .WithCredential(credentials);
});
```

Notice that it's an intermittent issue, occurring from time to time, like in 1 of 100 cases at a random moment, at this moment we didn't notice anything that might correlate with it.

### Expected behavior

Not throwing 401 at all.

### Actual behavior

Throws 401 at a random moment

### Reproduction Steps

Can't define the exact steps to reproduce as it is an intermittent issue

### Environment

**Operating System:** Windows 
**TargetFramework:**: net6.0
**AzureFunctionsVersion**: v4
**Runtime Version**: 4.25.2.21138

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
So a `RequestFailedException` is being thrown, given your stack, or you're just seeing 401s. The latter is expected, because Key Vault always sends an initial unauthenticated response to get a challenge to authenticate with Entra (formerly AAD), and it will subsequently when a token has or is about to expire.

/cc @schaabs, @christothes for Identity in case they have seen anything like this recently.

**Comment by danyltsiv** [comment]
> So a `RequestFailedException` is being thrown, given your stack, or you're just seeing 401s. The latter is expected, because Key Vault always sends an initial unauthenticated response to get a challenge to authenticate with Entra (formerly AAD), and it will subsequently when a token has or is about to expire.
> 
> /cc @schaabs, @christothes for Identity in case they have seen anything like this recently.

hey! thanks for looking into it
so, not just seeing 401, it's an unhandled exception from the package's service SecretClient, method GetSecretAsync

**Comment by heaths** [comment]
I haven't heard of this, but we made some changes over a year ago to authentication to improve reliability. Can you still reproduce this with the latest `Azure.Security.KeyVault.Secrets` and `Azure.Core`?

**Comment by danyltsiv** [comment]
that's what we have tried
looks like it is now moved from unhandled exception to warning exception, silently handled in the background not interrupting our process

so issue might be closed

thanks!
