### ISSUE TITLE
[BUG] Get System.InvalidOperationException when deserializing response

### ISSUE THREAD

**Issue by dw511214992** [Azure/azure-sdk-for-net#39249]
### Library name and version

Azure.ResourceManager.ContainerService (all versions)

### Describe the bug

There is `public IReadOnlyList<ManagedClusterPoolUpgradeProfile> AgentPoolProfiles { get; }` in [ManagedClusterUpgradeProfileData.cs](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/containerservice/Azure.ResourceManager.ContainerService/src/Generated/ManagedClusterUpgradeProfileData.cs#L52). In service's response, this value may be `null`. However, in deserialize code, it doesn't check whether it's null: https://github.com/Azure/azure-sdk-for-net/blob/3b2405aa66c348bbe333ca10d1bf234c47eb14dc/sdk/containerservice/Azure.ResourceManager.ContainerService/src/Generated/Models/ManagedClusterUpgradeProfileData.Serialization.cs#L73

### Expected behavior

Deserialize successfully.

### Actual behavior

Get exception:
```
System.InvalidOperationException: The requested operation requires an element of type 'Array', but the target element has type 'Null'.
   at System.Text.Json.ThrowHelper.ThrowJsonElementWrongTypeException(JsonTokenType expectedType, JsonTokenType actualType)
   at System.Text.Json.JsonElement.EnumerateArray()
   at Azure.ResourceManager.ContainerService.ManagedClusterUpgradeProfileData.DeserializeManagedClusterUpgradeProfileData(JsonElement element)
   at Azure.ResourceManager.ContainerService.ManagedClustersRestOperations.GetUpgradeProfileAsync(String subscriptionId, String resourceGroupName, String resourceName, CancellationToken cancellationToken)
   at Azure.ResourceManager.ContainerService.ManagedClusterUpgradeProfileResource.GetAsync(CancellationToken cancellationToken)
```

### Reproduction Steps

1. create a kubernetes cluster.
2. Get the `aksCluster` and continue with the following code:
```
var aksClusterUpgradeProfileResource = aksCluster.GetManagedClusterUpgradeProfile();
var aksClusterUpgradeProfile = await aksClusterUpgradeProfileResource.GetAsync(cancellationToken).ConfigureAwait(false);
```

**Comment by live1206** [comment]
This is not a bug in SDK generator.
[agentPoolProfiles ](https://github.com/Azure/azure-rest-api-specs/blob/9ec0fcc278aa2128c4fbb2b8a1aa93432d72cce0/specification/containerservice/resource-manager/Microsoft.ContainerService/aks/stable/2023-08-01/managedClusters.json#L4715C10-L4715C27) is defined as required in swagger, so SDK generator doesn't treat it as nullable during deserialization.
The actual service behavior doesn't align with the swagger definition. We can modify the swagger with directive in SDK as workaround to make `agentPoolProfiles` not required.
