### ISSUE TITLE
[QUERY] System.AccessViolationException makes App crash when getting the incoming Call on ACS UWP

### ISSUE THREAD

**Issue by SadevKalubowila** [Azure/azure-sdk-for-net#39257]
### Library name and version

Azure.Communication.Calling.WindowsClient 1.2.0

### Query/Question

We are developing Video Calling  UWP App based on (https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/get-started-with-video-calling?pivots=platform-windows) document targetting HoloLens 2 and PC. But we have encountered several app crashes in calling process. 

Often, app crashes at `"OnIncomingVideoStreamStateChanged"` method, line `RemoteVideo.Source = MediaSource.CreateFromUri(uri);` when receiving  incoming calls. 

This is the throwing exception;
`{"Attempted to read or write protected memory. This is often an indication that other memory is corrupt."}	System.AccessViolationException`

The call stack is  
`System.AccessViolationException
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>`

When issue occurs "uri" available as `skype://urlbinding_sink_1/`

### Environment

This occurs on Windows 11 Pro [Version 22H2, OS build 22621.2361] as well as on HoloLens 2.[OS Build 22621.1133] 
Tried with x64  and x86  and ARM64 architectures. 
Visual Studio Version 2022

```[tasklist]
### Tasks
```

**Comment by jowang-msft** [comment]
I believe this issue has been resolved during our call. The root cause is that the participant collection variable needs to have a longer lifecycle and should be declared external to the scope of the event handler.
