### ISSUE TITLE
How to use OpenTelemetry library with Azure Monitor without code?

### ISSUE THREAD

**Issue by joshmouch** [Azure/azure-sdk-for-net#39263]
### Library name and version

Azure.Monitor.OpenTelemetry.AspNetCore

### Query/Question

I went through the documentation, and I don't see any examples of using the Azure Monitor integration with the Open Telemetry "Automatic Instrumentation" scenarios that don't require any code changes.

See: https://opentelemetry.io/docs/instrumentation/net/automatic/

Is this supported?

**Comment by TimothyMothra** [comment]
Hi @joshmouch, the `Azure.Monitor.OpenTelemetry.AspNetCore` package from this repo is not a codeless automatic instrumentation. You can learn more about this package here: https://learn.microsoft.com/azure/azure-monitor/app/opentelemetry-enable?tabs=aspnetcore

@rajkumar-rangaraj do you have more information about the auto instrumentation for Azure Monitor?

**Comment by rajkumar-rangaraj** [comment]
As of now, there are no plans to provide Azure Monitor auto-instrumentation as a standalone package. This repo contains the Azure Monitor Exporter/Distro; this issue is being closed as it is not related to this repo.
