### ISSUE TITLE
[BUG] EventHubTrigger on EventData[] processing same event multiple times

### ISSUE THREAD

**Issue by NattyMojo** [Azure/azure-sdk-for-net#39267]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.EventHubs 5.3.0

### Describe the bug

Single message being handled many times over, like the Checkpoints aren't being saved after processing a batch of messages. Older image of an instance of this occurring, but continues to be a problem. Sometimes (as seen here) it's the exact same batch being handled over again.

![image](https://github.com/Azure/azure-sdk-for-net/assets/37313152/5b9272bc-bb16-4962-81d6-7c59f68c1b82)

### Expected behavior

After a batch is handled, checkpoint is written, and that batch is not handled again.

### Actual behavior

Batches being handled multiple times, or a single message making it into many unique batches.

### Reproduction Steps

1. Create function with EventHubTrigger for EventData[] for processing batches that logs message id's
2. host.json: "eventHubs": {
"maxEventBatchSize": 200,
"minEventBatchSize": 50,
"maxWaitTime": "00:02:00"
}
3. Send chunk of messages (>1k or so)
4. See logs for messages handled multiple times

### Environment

Azure Windows Function App version: 4.1.3
Consumer Function App plan
Region: West US 2
.NET 6

**Comment by NattyMojo** [comment]
originally opened this issue in https://github.com/Azure/azure-functions-host/issues/9543 which notes I have tried upgrading to Microsoft.Azure.WebJobs.Extensions.EventHubs 5.4.0 to no avail

**Comment by pallavit** [comment]
Thanks for reporting the issue.  Assigning it to the person best able to assist you.
//c: @jsquire

**Comment by jsquire** [comment]
Hi @NattyMojo.  Thank you for reaching out and we regret that you're experiencing difficulties.  There is a known issue with `minBatchSize` not recording checkpoints when there are not enough events available to meet the requested batch size in the wait time allowed.  This has been fixed with v6.0.0.    Would you please try to reproduce by either removing the `minBatchSize` configuration or upgrading to v6+?

**Comment by NattyMojo** [comment]
@jsquire thanks for the quick feedback! I have upgraded to v6.0.1 and have done some testing. Appears to be resolved in this version, I'm going to watch through the day and I'll come back if I see anything different

**Comment by jsquire** [comment]
Thanks for the confirmation, @NattyMojo.   I'm going to mark this as addressed.  If you need further assistance or would like to continue the discussion, please feel free to unresolve.

**Comment by drdamour** [comment]
> Hi @NattyMojo. Thank you for reaching out and we regret that you're experiencing difficulties. There is a known issue with `minBatchSize` not recording checkpoints when there are not enough events available to meet the requested batch size in the wait time allowed. This has been fixed with v6.0.0. Would you please try to reproduce by either removing the `minBatchSize` configuration or upgrading to v6+?

@jsquire how come this bugfix isnt mentioned in the 6.0.0 changelog?

**Comment by jsquire** [comment]
> @jsquire how come this bugfix isnt mentioned in the 6.0.0 changelog?

That is an excellent question.  I would assume that it was a mistake.   I'll see about getting it added.
