### ISSUE TITLE
Microsoft.Azure.Management.OperationalInsights new query language

### ISSUE THREAD

**Issue by OneCyrus** [Azure/azure-sdk-for-net#3927]
It looks like the currently published OperationalInsights package (0.18.0-preview) doesn't support the new log analytics query language. At least i can't use something like ```search * | where(Type == "Perf")``` with GetSearchResultsAsync.

is this correct and is the new query language on the near roadmap for this package?

**Comment by shareonline** [comment]
Please fix this.. We can't add saved searches because of this.. So now i have to write my own rest calls, which is working. But this is not really great when we are supposed to have an SDK for the job?

**Comment by jsquire** [comment]
Closing this out as this refers to a legacy version of the library there has been no recent engagement.  Please feel free to reopen or file a new issue if this remains a problem with the current version of the library.
