### ISSUE TITLE
[BUG]cannot configure SqlClientInstrumentationOptions because it is now an internal class

### ISSUE THREAD

**Issue by zyofeng** [Azure/azure-sdk-for-net#39273]
### Library name and version

Azure.Monitor.OpenTelemetry.AspNetCore 1.0.0-beta.8

### Describe the bug

previously we can use
`.Configure<SqlClientInstrumentationOptions>`
To overwrite the default sql instrumentation behaviour registered by Azure.Monitor.OpenTelemetry.AspNetCore

In beta 8, SqlClientInstrumentationOptions is now internal and no longer possible.

What's the recommended approach for configuration? 

### Expected behavior

Either do not register default sql instrumentation or allow options to be passed through UseAzureMonitor?

### Actual behavior

Can't configure sql instrumentation at all, compile error

### Reproduction Steps
```
.Configure<SqlClientInstrumentationOptions>(s =>
            {
                s.SetDbStatementForText = true;
                s.SetDbStatementForStoredProcedure = true;
            })
```

**Comment by TimothyMothra** [comment]
Hi @zyofeng, I'm sorry for the disruption. We can't release a stable version of our package with beta dependencies. Our new approach is to temporarily internalize these libraries. We're currently gauging user feedback on this change.

This change was called out in our changelog: 
https://github.com/Azure/azure-sdk-for-net/blob/033c57c169c52e09aec64c17f3eb7681a79e0ad1/sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/CHANGELOG.md?plain=1#L13-L22

To configure the sql instrumentation, you'll need to first manually take a dependency on the sql instrumentation library. When you do this, our instrumentation will back-off.

cc @rajkumar-rangaraj @mattmccleary
