### ISSUE TITLE
There is not a sample to show how to use CdnEndpointCollection.GetAllAsync

### ISSUE THREAD

**Issue by begood0513** [Azure/azure-sdk-for-net#39283]
I read the document below, but there are no samples to show how to use these methods. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bfb9ec09-0a5c-c96f-6fb6-949431f8c738
* Version Independent ID: 18e7c844-5e02-aef0-17a1-53d1152f1cda
* Content: [CdnEndpointCollection.GetAllAsync(CancellationToken) Method (Azure.ResourceManager.Cdn) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.cdn.cdnendpointcollection.getallasync?view=azure-dotnet)
* Content Source: [xml/Azure.ResourceManager.Cdn/CdnEndpointCollection.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.ResourceManager.Cdn/CdnEndpointCollection.xml)
* Service: **azure**
* GitHub Login: @azure-sdk
* Microsoft Alias: **azsdkdocs**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by begood0513** [comment]
Thanks!

**Comment by HarveyLink** [comment]
Hi @begood0513 , Thank you for using Azure SDK for .NET.
For the usage of CDN, please refer to this sample: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cdn/Azure.ResourceManager.Cdn/samples/Sample1_ManagingCdnOriginGroups.md
Or, for the `CdnEndpointCollection.GetAllAsync` method, you could refer to: https://github.com/Azure/azure-sdk-for-net/blob/02c37929386421c1c6d6693f67cbc5a7bde9fde3/sdk/cdn/Azure.ResourceManager.Cdn/samples/Generated/Samples/Sample_CdnEndpointCollection.cs#L23C6-L23C6
