### ISSUE TITLE
[FEATURE REQ] Able to change the endpoint of openai

### ISSUE THREAD

**Issue by feiyun0112** [Azure/azure-sdk-for-net#39284]
### Library name

Azure.AI.OpenAI

### Please describe the feature.

[https://github.com/microsoft/semantic-kernel/issues/3159](https://github.com/microsoft/semantic-kernel/issues/3159)

Instead of forcing the use of official endpoints, maybe change the endpoint

**Comment by jsquire** [comment]
Hi @feiyun0112.  Thank you for reaching out and we regret that you're experiencing difficulties.  This feature already exists.  When creating an [OpenAIClient](https://learn.microsoft.com/dotnet/api/azure.ai.openai.openaiclient?view=azure-dotnet-preview#constructors), the constructor requires you to pass the address of the endpoint that you'd like to connect to.  There is no validation that enforces this to be "an official endpoint."

Examples and more discussion can be found in the [Authenticate the client](https://learn.microsoft.com/dotnet/api/overview/azure/ai.openai-readme?view=azure-dotnet-preview#authenticate-the-client) section of the client documentation.

**Comment by qihangnet** [comment]
@jsquire In some cases, applications cannot directly access OpenAI’s official endpoints. Enterprises/organizations or individuals need to use an intermediary server to perform filtering (such as security auditing, internal token usage cost allocation, etc.), and then forward the request to OpenAI.

Therefore, the application should be allowed to specify the Endpoint.

**Comment by scottaddie** [comment]
This problem has been addressed in the v2.x release train. The endpoint can be set via the [OpenAIClientOptions.Endpoint property](https://github.com/openai/openai-dotnet/blob/0b97311f58dfb28bd883d990f68d548da040a807/src/Custom/OpenAIClientOptions.cs#L15). For example:

```csharp
OpenAIClient client = new(
    new OpenAIClientOptions
    {
        Endpoint = "<endpoint here>",
    });
```
