### ISSUE TITLE
The request is invalid. Details: An unexpected 'StartObject' node was found for property named 'JobID' when reading from the JSON reader. A 'PrimitiveValue' node was expected.

### ISSUE THREAD

**Issue by wist214** [Azure/azure-sdk-for-net#39294]
### Library name and version

Azure.Search 3.0.5

### Describe the bug

Hi, I am getting "The request is invalid. Details: An unexpected 'StartObject' node was found for property named 'JobID' when reading from the JSON reader. A 'PrimitiveValue' node was expected." error when trying to call the SearchIndexClient.Documents.Index(...) method. I'm getting this error because my type is not serialized correctly, **but** this problem only occurs when I run the code in an Azure Function.

JobID is an int wrapper, one of the properties of the type that I pass as a parameter to the Index method. I have overridden JsonConverter for this type and everything works fine when I call SearchIndexClient.Documents.Index(...) in any application except the Azure function.

Do you happen to know why the same code doesn't work in azure function? 

P.S. I am not sure if it is the right place for this issue, please let me know if it is not.

### Expected behavior

SearchIndexClient.Documents.Index(...) method sends a batch of upload, merge, and/or delete actions to the Azure Search index.

### Actual behavior

"The request is invalid. Details: An unexpected 'StartObject' node was found for property named 'JobID' when reading from the JSON reader. A 'PrimitiveValue' node was expected." error occures

### Reproduction Steps

1) Create an int/string wrapper with JsonConverter attribute to make it serialize correctly
2) Create a new type with an int/string wrapper property
3) Call the SearchIndexClient.Documents.Index() passing an array of the object with type from previous step.

### Environment

.NET Framework and Azure Function V1

**Comment by pallavit** [comment]
Thank you for reporting the issue. Tagging and routing to the team member best able to assist you.
@JoshLove-msft - could you please take a quick look and see if there is anything off on our side or loop in functions team for further assistance.

/cc: @ShivangiReja

**Comment by jsquire** [comment]
@wist214:  Would you please include the signature of your function and the relevant code that demonstrates how the Search library is being used?   I'd also like to understand what type is using the converter that you've mentioned.

**Comment by wist214** [comment]
Hi @jsquire, thanks for your feedback.
Here is an example of an Azure function that calls the SearchIndexClient.Documents.Index(...) method:
```
        [FunctionName("AzureFunctionExample")]
        public static void Run([TimerTrigger("%ScheduleExpression%")] TimerInfo myTimer, TraceWriter log)
        {
            PutBatch(new[] { _jobAzureSearchable });
        }

        private static void PutBatch(IEnumerable<JobAzureSearchable> items)
        {
            try
            {
                var batch = IndexBatch.Upload(items);
                var indexClient = new SearchIndexClient(SearchServiceName, IndexName, _searchCredentials, null, null);
                var result = indexClient.Documents.Index(batch, null);
            }
            catch (Exception ex)
            {
                Logger.Error(ex);
                throw;
            }
        } 
```

JobAzureSearchable class:
```
    [Serializable]
    public class JobAzureSearchable : IAzureSearchable<JobID>
    {
       
        #region Properties 

        [System.ComponentModel.DataAnnotations.Key, IsFilterable, IsSortable]
        public JobID JobID { get; set; }
        // other properties, etc.
     }
```

JobID int wrapper: [JobID.txt](https://github.com/Azure/azure-sdk-for-net/files/12929913/JobID.txt)

**Comment by jsquire** [comment]
Thank you for the additional context, @wist214.   Would you please also include the full error message and stack trace?

**Comment by jsquire** [comment]
Thanks, @wist214.   That's helpful.   One last request:  can you please share the list of packages that your app is referencing?   I want to be sure that we're able to use the same when investigating.

**Comment by wist214** [comment]
Sure @jsquire, here are the packages:

- EntityFramework 6.1.1
- Microsoft.AspNet.WebPages 3.2.7
- Microsoft.Azure.WebJobs.ServiceBus 2.3.0
- Microsoft.NET.Sdk.Functions 1.0.30
- Newtonsoft.Json 12.0.1
- NLog.Targets.ElasticSearch 4.0.0
- System.Diagnostics.DiagnosticSource 4.3.0
- System.Runtime.CompilerServices.Unsafe 4.7.0
- WindowsAzure.ServiceBus 3.4.5

**Comment by jsquire** [comment]
Hi @wist214.  I'm afraid that there is no assistance that we can provide for this library.

After looking through the dependencies, we noticed that you're using the legacy Search package, `Microsoft.Azure.Search` which has been formally retired and reached end-of-life in March 2023.  As a result, this package is no longer published nor supported by Microsoft.  We strongly recommended that you consider upgrading to its replacement, [Azure.Search.Documents](https://www.nuget.org/packages/Azure.Search.Documents/).

- [Azure Search Migration Guide](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/MigrationGuide.md)
- [Retirement announcement](https://azure.microsoft.com/en-us/updates/support-for-azure-sdk-libraries-that-do-not-conform-to-our-current-azure-sdk-guidelines-will-be-retired-as-of-31-march-2023/)

**Comment by wist214** [comment]
Thanks for your feedback @jsquire, I'll update the Microsoft.Azure.Search nuget package to the latest version and let you know if this issue still exists.

**Comment by wist214** [comment]
The latest Azure.Search.Documents nuget package solved the problem, thank you.
