### ISSUE TITLE
[BUG] NetworkSecurityGroup DesintationPortRange cannot support multiple ports anymore

### ISSUE THREAD

**Issue by pjohnst5** [Azure/azure-sdk-for-net#39303]
### Library name and version

Azure.ResourceManager.Network 1.5.0

### Describe the bug

It used to be that with Fluent, you could specify multiple ports to allow as the "`ToPortRanges()`" method in an NSG:
```
nsg.Update()
    .DefineRule(TestConstants.RuleName)
        .AllowInbound()
        .FromAnyAddress()
        .FromAnyPort()
        .ToAnyAddress()
        .ToPortRanges(new string[] { TestConstants.ServiceFabricClientPort.ToString(), TestConstants.ServiceFabricWebPort.ToString(), TestConstants.DNCPort.ToString(), TestConstants.CNSPort.ToString(), EnvironmentVariables[TestConstants.CustomerPortEnvVarName] })
        .WithProtocol(SecurityRuleProtocol.Tcp)
        .WithDescription(TestConstants.RuleDescription)
        .WithPriority(TestConstants.RulePriority)
        .Attach()
    .Apply();
```

Now however, this is not possible with ArmClient:

```
SecurityRuleData newRule = new SecurityRuleData();
newRule.Name = TestConstants.RuleName;
newRule.Description = TestConstants.RuleDescription;
newRule.Access = SecurityRuleAccess.Allow;
newRule.Direction = SecurityRuleDirection.Inbound;
newRule.SourceAddressPrefix = "*";
newRule.SourcePortRange = "*";
newRule.DestinationAddressPrefix = "*";
newRule.DestinationPortRange = TestConstants.ServiceFabricClientPort.ToString() + "," + TestConstants.ServiceFabricWebPort.ToString() + "," + TestConstants.DNCPort.ToString() + "," + TestConstants.CNSPort.ToString() + "," + EnvironmentVariables[TestConstants.CustomerPortEnvVarName];
newRule.Protocol = SecurityRuleProtocol.Tcp;
```

This now throws an error:
```
resourceGroup.GetNetworkSecurityGroups().CreateOrUpdate(WaitUntil.Completed, nsgResourceID.Name, nsg.Data);
```

```
Azure.RequestFailedException: 'Security rule has invalid Port range. Value provided: 19000,19080,9001,10090,8081. Value should be an integer OR integer range with '-' delimiter. Valid range 0-65535.
Status: 400 (Bad Request)
ErrorCode: SecurityRuleInvalidPortRange
```

Unless I am missing something on how to allow multiple, specified ports, I think this is a regression from Fluent to ArmClient

### Expected behavior

Would like to be able to set multiple specific ports on an NSG rule using ArmClient

### Actual behavior

Error saying:
"Azure.RequestFailedException: 'Security rule has invalid Port range. Value provided: 19000,19080,9001,10090,8081. Value should be an integer OR integer range with '-' delimiter. Valid range 0-65535.
Status: 400 (Bad Request)
ErrorCode: SecurityRuleInvalidPortRange"

### Reproduction Steps

See description

**Comment by pjohnst5** [comment]
Hello @ArthurMa1978 , lmk what you think, thanks

**Comment by mcgallan** [comment]
@pjohnst5 In [the latest version 1.7.0](https://www.nuget.org/packages/Azure.ResourceManager.Network), the DestinationPortRanges property has been changed to ChangeTrackingList<string>(). You can freely specify multiple ports to complete your work. Thank you for your feedback.
