### ISSUE TITLE
[BUG] Request fail when QueryType does not equal Semantic and answers requested

### ISSUE THREAD

**Issue by claremonahan** [Azure/azure-sdk-for-net#39306]
### Library name and version

Azure.Search.Documents 11.5.0-beta.5

### Describe the bug

The latest SDK throws the following exception
Azure.RequestFailedException: 'Parameter 'answers' is supported only when 'queryType' is set to 'semantic'.
Parameter name: answers
Status: 400 (Bad Request)
ErrorCode: MissingRequiredParameter

Content:
{"error":{"code":"MissingRequiredParameter","message":"Parameter 'answers' is supported only when 'queryType' is set to 'semantic'.\r\nParameter name: answers","details":[{"code":"MissingSemanticQueryType","message":"Parameter 'answers' is supported only when 'queryType' is set to 'semantic'."}]}}

Headers:
Cache-Control: no-cache,no-store
Pragma: no-cache
Server: Microsoft-IIS/10.0
client-request-id: 3658cf61-05dc-460e-ae43-682820fbd9f1
x-ms-client-request-id: 3658cf61-05dc-460e-ae43-682820fbd9f1
request-id: 3658cf61-05dc-460e-ae43-682820fbd9f1
elapsed-time: 48
Strict-Transport-Security: REDACTED
Date: Mon, 16 Oct 2023 20:59:22 GMT
Content-Length: 298
Content-Type: application/json; charset=utf-8
Content-Language: REDACTED
Expires: -1
'

### Example Input:

			SearchOptions options = new SearchOptions()
			{
				QueryType = SearchQueryType.Full,
				SemanticMaxWaitInMilliseconds = 1000,
				SemanticErrorHandling = "partial",
				QueryLanguage = "en-us",
				QueryAnswer = "extractive",
				QueryAnswerCount = 3,
				SemanticQuery = "new york apartmenets?"
			};

			var response = client.Search<Result>("new yo*", options);

### Expected behavior

So long as either SemanticQuery or QueryType=SearchQueryType.Semantic are provided, we should accept both QueryAnswer* and QueryCaption* parameters as part of the search request. 

### Actual behavior

Exception: 
Azure.RequestFailedException: 'Parameter 'answers' is supported only when 'queryType' is set to 'semantic'.

### Reproduction Steps

See above example input

### Environment

![image](https://github.com/Azure/azure-sdk-for-net/assets/144977813/94c2ff49-9a93-43c5-9887-0a4ff6fef6c7)

**Comment by pallavit** [comment]
Thank you for reporting the issue. Tagging and routing to the person best able to assist you.

**Comment by ShivangiReja** [comment]
Hello @claremonahan, In order to get a semantic answer, `QueryType` must be set to `Semantic`. For additional information on semantic search, please refer the search service documentation available [here](https://learn.microsoft.com/en-us/azure/search/semantic-answers#formulate-a-rest-query-for-answers).

**Comment by claremonahan** [comment]
hi @ShivangiReja, to clarify, I am an engineer on the Semantic Search team. This is an issue specifically with the newest preview SDK implementation, where we introduced the concept of `SemanticQuery` [link to preview docs](https://learn.microsoft.com/en-us/rest/api/searchservice/2023-10-01-preview/documents/search-post?tabs=HTTP)

The expectation is that if `SemanticQuery` is passed to the API, regardless of `QueryType`, both SemanticCaptions and SemanticAnswers will be valid. 
[link to answers validation](https://msdata.visualstudio.com/Azure%20Search/_git/AzureSearch?path=/Source/Search/Product/SearchCore/Services/QueryBuilder.cs&version=GBcurrent&line=932&lineEnd=933&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents). 
[link to isSemanticQuery setting](https://msdata.visualstudio.com/Azure%20Search/_git/AzureSearch?path=/Source/Search/Product/SearchCore/Models/ApiQueries/ApiSearchQuery.cs&version=GBcurrent&line=226&lineEnd=227&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents)

If I call the 2023-10-01-preview API directly, I am able to get an expected 200 response. However, when I try to use the version of the SDK using the example query above, I get the error state message shown above. This makes me think that there is some misformed logic in the newer SDK that is not properly passing SemanticQuery to the API, which would cause the error state I am seeing. 

Could you please take a look and the SDK implementation of SemanticQuery and ensure that it is being passed properly to the API?

**Comment by ShivangiReja** [comment]
Hi @claremonahan, the issue has been resolved and released in [Azure.Search.Documents@11.6.0-beta.1](https://www.nuget.org/packages/Azure.Search.Documents/11.6.0-beta.1) preview. Please check the [SemanticQuery](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/samples/Sample08_SemanticSearch.md#using-semanticquery) sample for your reference.
