### ISSUE TITLE
[FEATURE REQ] Add extension method to validate a secret name 

### ISSUE THREAD

**Issue by erikjanwestendorp** [Azure/azure-sdk-for-net#39321]
### Library name

Azure.Extensions.AspNetCore.Configuration.Secrets

### Please describe the feature.

As far as I know, there is currently no extension method to check if a secret name is valid. Often, I now create an extension method to check if the secret is valid. Is it an idea to add this to this package to make it easy to verify secret names?

```csharp
public static bool IsValidSecretName(this string secretName)
{
    const string pattern = @"^[a-zA-Z0-9\-]+$";

    return Regex.IsMatch(secretName, pattern);
}
```

**Comment by jsquire** [comment]
Hi @erikjanwestendorp.  Thank you for reaching out and for your suggestion.  Unfortunately, this isn't something that we'll be moving forward with.

When an Azure service owns the rules for validation, we intentionally do not perform client-side validation to ensure the behavior is correct across service changes.   In this case, the rules for a valid secret name are purview of the service so we want the client to pass the value through and allow the service to validate.  

Thank you, again, for your suggestion and your interest in improving the Azure developer experience.

**Comment by erikjanwestendorp** [comment]
@jsquire Thanks for your explanation!
