### ISSUE TITLE
[BUG] Find Blobs By Tags returning Deleted Blobs that return 404 occasionally

### ISSUE THREAD

**Issue by philip-young** [Azure/azure-sdk-for-net#39336]
### Library name and version

Azure.Storage.Blobs 12.17.0

### Describe the bug

I am experiencing some odd behaviour when using Blob Tags and the ```FindBlobsByTagsAsync``` functionality: it seems that occasionally, blob names are returned that no longer exist in the container. Later when I create a ```BlobClient``` and try to do an action of ```GetTagsAsync``` on it I'm getting back a 404. This isn't happening that often but often enough that is noticeable. I'm deleting the blob using ```DeleteIfExistsAsync``` which as far as I can see is working as expected and I do not have soft delete enabled nor any Blob snapshots enabled (that I know of). I'm not sure if this is an Azure SDK issue or just known behaviour of this Service or Endpoint but I can't seem to find anything about it.

### Expected behavior

The Find Blobs By Tags only returns Blobs that still exist in the container.

### Actual behavior

Find Blobs By Tags occasionally is returning Blob names that don't exist anymore in the container (that were deleted). This is discovered later when trying to perform actions through ```BlobClient``` with the name.

### Reproduction Steps

1. Upload Blob with Blob Index Tags (using ```UploadAsync``` with the tags in ```BlobUploadOptions```)
2. Read the Blob, then delete it using ```DeleteIfExists()```
3. Later call the ```FindBlobsByTagsAsync``` and notice occasionally the deleted blob name seems to be returned.

**Comment by seanmcc-msft** [comment]
This behavior is expected.  When you call `DeleteIfNotExist()` on a blob, it is marked for garage collection in the backend storage service, and may not be deleted immediately.  It also takes several seconds for Blob Tags to be indexed.
