### ISSUE TITLE
Missing attributes or no NuGet package

### ISSUE THREAD

**Issue by securigy** [Azure/azure-sdk-for-net#39346]
### Library name and version

Azure.Search.Documents

### Describe the bug

I am using 11.4.0 and the attributes VectorSearchDimensions and VectorSearchProfile of the SearchFiled are missing. 
This is the latest NuGet package!

### Expected behavior

Either provide the appropriate NuGet package or add the attributes.

### Actual behavior

Unable to build

### Reproduction Steps

Unable to build:

`        /// <summary>
        /// Embeddings Vector (array of floats)
        /// </summary>
        [SearchField(SearchField.VectorSearchDimensions = "1536", SearchField.VectorSearchProfile = "my-vector-profile")] public IReadOnlyList<float>? TextVector { get; set; }
        public IReadOnlyList<float>? SourceVector { get; set; }
`

**Comment by jsquire** [comment]
Hi @securigy.   You're not seeing these attributes in v11.4.0 because vector search is a beta feature that is not yet available in a GA package.   According to the [change log](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/CHANGELOG.md#1150-beta3-2023-07-11) it first was introduced in v11.5..0-beta.3 in July of 2023.   In order to make use of it, we'd advise using the latest beta.

**Comment by securigy** [comment]
I get it. The problem is that this new package is not available in NuGet, so how am I supposed to use it?

Sent from Yahoo Mail on Android 
 
  On Wed, Oct 18, 2023 at 7:13 AM, Jesse ***@***.***> wrote:   


Hi @securigy. You're not seeing these attributes in v11.4.0 because vector search is a beta feature that is not yet available in a GA package. According to the change log it first was introduced in v11.5..0-beta.3 in July of 2023. In order to make use of it, we'd advise using the latest beta.

**Comment by jsquire** [comment]
@securigy: It sounds like you've got your IDE or package manager configured to not allow pre-release packages.   All of our beta versions are available via NuGet.   In this case: [v11.5.0-beta.5](https://www.nuget.org/packages/Azure.Search.Documents/11.5.0-beta.5)

**Comment by securigy** [comment]
Many thanks. That was it!
