### ISSUE TITLE
[Event Hubs] Tracking GeoDR feature support

### ISSUE THREAD

**Issue by m-redding** [Azure/azure-sdk-for-net#39367]
## Adding support for Geo-DR in Event Hubs

Community discussion has a public timeline estimate [here](https://feedback.azure.com/d365community/idea/adcef9fb-7526-ec11-b6e6-000d3a4f032c). Adding support in phases.

Prototype:
- https://github.com/Azure/azure-sdk-for-net/pull/38351

### To do:
- [x] Initial set up:
    - https://github.com/Azure/azure-sdk-for-net/pull/39454
    - https://github.com/Azure/azure-sdk-for-net/pull/41829 from architect feedback
    - https://github.com/Azure/azure-sdk-for-net/pull/41911 bug fix for issue found in testing prior to release
    - https://github.com/Azure/azure-sdk-for-net/pull/41871 bug fix for issue found in testing prior to release
- [x] Prioritize sequence number over offset:
    - https://github.com/Azure/azure-sdk-for-net/pull/41360

After service deployment:
- [ ] Initial changes:
    - Hide Offset
    - read sequence number to populate offset
    - translate reading offset to sequence number
    - Change some various logic - 
- [ ] Next changes:
    - New string property that represents sequence number / replication segment & associated logic

**Comment by jsquire** [comment]
Initial preview and updated API surface complete.   Issues exist for tracking the remaining work.
