### ISSUE TITLE
Azure.ResourceManager.CosmosDB lacking useful examples

### ISSUE THREAD

**Issue by ChadNedzlek** [Azure/azure-sdk-for-net#39376]
There is absolutely no indication how to do anything with this library.  How do I, say, create a container?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cfe45b72-4171-565a-d259-d15368cb1657
* Version Independent ID: eccb7522-fc38-7198-5a2e-c34d44b82ed5
* Content: [Microsoft Azure Cosmos DB management client library for .NET - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/resourcemanager.cosmosdb-readme?view=azure-dotnet)
* Content Source: [api/overview/azure/latest/resourcemanager.cosmosdb-readme.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/latest/resourcemanager.cosmosdb-readme.md)
* Service: **cosmosdb**
* GitHub Login: @azure-sdk
* Microsoft Alias: **azsdkdocs**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ChadNedzlek** [comment]
In particular, I got sent to this package because the data plane SDK told me I had to use it to create containers using Entra ID. Except there is no documentation on how to do that.  I eventually figured it out after a few hours, I think, but it wasn't straightforward.

**Comment by dvbb** [comment]
Hi, @ChadNedzlek 

Thanks for using Azure SDK, the current SDK repository does not contain a `container` sample, but we will continue to improve the sample repo, here is a sample of creating a container in cosmosDB.

More samples you can ref [Test cases](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/cosmosdb/Azure.ResourceManager.CosmosDB/tests/ScenarioTests), [Auto-Generated samples](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/cosmosdb/Azure.ResourceManager.CosmosDB/samples/Generated/Samples), [Azure-Samples repo](https://github.com/orgs/Azure-Samples/repositories?language=&q=cosmosdb-dotnet&sort=&type=all)

```
// Create a resource group in the EastUS region
string rgName = "cosmosRG";
ArmOperation<ResourceGroupResource> rgLro = await subscription.GetResourceGroups().CreateOrUpdateAsync(WaitUntil.Completed, rgName, new ResourceGroupData(AzureLocation.EastUS));
ResourceGroupResource resourceGroup = rgLro.Value;

// 1. Create dbAccount
string dbAccountName = "dbaccount555666";
string iPAddressOrRange = "23.43.231.120";
var locations = new List<CosmosDBAccountLocation>()
{
    new CosmosDBAccountLocation(){ LocationName  = AzureLocation.EastUS, FailoverPriority = 0 },
};
var dbAccountInput = new CosmosDBAccountCreateOrUpdateContent(AzureLocation.WestUS2, locations)
{
    Kind = CosmosDBAccountKind.GlobalDocumentDB,
    ConsistencyPolicy = new Azure.ResourceManager.CosmosDB.Models.ConsistencyPolicy(DefaultConsistencyLevel.BoundedStaleness)
    {
        MaxStalenessPrefix = 100000,
        MaxIntervalInSeconds = 300
    },
    IPRules =
    {
        new CosmosDBIPAddressOrRange()
        {
            IPAddressOrRange = iPAddressOrRange
        }
    },
    IsVirtualNetworkFilterEnabled = true,
    EnableAutomaticFailover = false,
    ConnectorOffer = ConnectorOffer.Small,
    DisableKeyBasedMetadataWriteAccess = false,
    EnableMultipleWriteLocations = true,
};
var accountLro = await resourceGroup.GetCosmosDBAccounts().CreateOrUpdateAsync(WaitUntil.Completed, dbAccountName, dbAccountInput);
CosmosDBAccountResource dbAccount = accountLro.Value;

// 2. Create database
string databaseName = "database1";
var databaseCollection = dbAccount.GetCosmosDBSqlDatabases();
var sqlDatabaseCreateUpdateOptions = new CosmosDBSqlDatabaseCreateOrUpdateContent(AzureLocation.WestUS, new CosmosDBSqlDatabaseResourceInfo(databaseName)) { };
var databaseLro = await databaseCollection.CreateOrUpdateAsync(WaitUntil.Completed, databaseName, sqlDatabaseCreateUpdateOptions);
CosmosDBSqlDatabaseResource database = databaseLro.Value;

// 3. Create container
string containerName = "container1";
var containerCollection = database.GetCosmosDBSqlContainers();
var containerInfo = new CosmosDBSqlContainerResourceInfo(containerName)
{
    ContainerName = containerName,
    PartitionKey = new CosmosDBContainerPartitionKey()
    {
        Kind = new CosmosDBPartitionKind("Hash")
    },
    IndexingPolicy = new CosmosDBIndexingPolicy()
    {
        IsAutomatic = true,
        IndexingMode = CosmosDBIndexingMode.Consistent,
    }
};
containerInfo.PartitionKey.Paths.Add("/testscope");
var containerInput = new CosmosDBSqlContainerCreateOrUpdateContent(resourceGroup.Data.Location,containerInfo);
var containerLro = await containerCollection.CreateOrUpdateAsync(WaitUntil.Completed, containerName, containerInput);
CosmosDBSqlContainerResource container = containerLro.Value;

await Console.Out.WriteLineAsync(container.Data.Name);
```
