### ISSUE TITLE
[BUG] Cannot retrieve tags when using hierarchical storage

### ISSUE THREAD

**Issue by raghavendra-chandrashekhar** [Azure/azure-sdk-for-net#39388]
### Library name and version

Azure.Storage.Blobs 12.18.0

### Describe the bug

If I create a Azure blob storage without hierarchical name space below functionality works properly but, We have created azure blob storage with hierarchical name space. When we send a request using SDK to get the tags its showing the error.

### Expected behavior

Should return the tags of the particular blob.

### Actual behavior

Its throwing the below error when querying the tags using below method in SDK

BlobClient.GetTags();

https://learn.microsoft.com/en-us/rest/api/storageservices/get-blob-tags?tabs=azure-ad

Value for one of the query parameters specified in the request URI is invalid.
RequestId:<removed for security reasons>
Time:<removed for security reasons>
Status: 400 (Value for one of the query parameters specified in the request URI is invalid.)
ErrorCode: InvalidQueryParameterValue Additional Information: QueryParameterName: comp QueryParameterValue: tags
Reason: 

Content:
<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:<removed for security reasons>
Time:<removed for security reasons></Message><QueryParameterName>comp</QueryParameterName><QueryParameterValue>tags</QueryParameterValue><Reason /></Error>

Headers:
Server: Microsoft-HTTPAPI/2.0
x-ms-request-id: <removed for security reasons>
x-ms-client-request-id: <removed for security reasons>
x-ms-error-code: InvalidQueryParameterValue
Date: <removed for security reasons>
Content-Length: 375
Content-Type: application/xml

azure blob

### Reproduction Steps

1. Create a blob storage with hierarchical namespace
2. Create container
3. Upload a file in that container
4. Create c# .net 7 console application
5. Install nuget Azure.Storage.Blobs 12.18.0
6. Place below code in main method and run
```
var blobServiceClient = new BlobServiceClient("Replace connection string here");
var container = blobServiceClient.GetBlobContainerClient("replace with container name");
var blob = container.GetBlobClient("Replace with blob path");
var tags = blob.GetTags();
```

### Environment

.net 7 conosle application

**Comment by raghavendra-chandrashekhar** [comment]
Hi All,

Do you have any update on this issue? Many users are waiting for the solution on the same.

**Comment by dibabecs** [comment]
Hi, 

BlobTags is not yet supported for hierarchical namespace enabled account. So, the observed behavior is expected.
For further details, please refer:
https://learn.microsoft.com/en-us/azure/storage/blobs/storage-manage-find-blobs?tabs=azure-portal#:~:text=learn%20more.-,Feature%20support,-Support%20for%20this
https://learn.microsoft.com/en-us/azure/storage/blobs/storage-feature-support-in-storage-accounts
