### ISSUE TITLE
KeyVaultClient disposes HttpClient if it is passed through constructor

### ISSUE THREAD

**Issue by BohdanZhmud** [Azure/azure-sdk-for-net#3940]
KeyVaultClient should use protected ServiceClient(HttpClient httpClient, bool disposeHttpClient = true) ctor if pass HttpClient to not dispose HttpClient instance.

This issue prevents from sharing HttpClient instance between instances of ServiceClient

**Comment by deepumi** [comment]
I am having the same issue, trying to share the HttpClient Instance in keyvault and after the call is being made client is getting disposed. As @BohdanZhmud pointed above, the constructors are explicitly setting disposeHttpClient = true.

Should it be looking internal handler and make sure the dispose check? 

I am explicitly setting in HttpClientHandler not to dispose internal handlers like below.

```csharp

private static readonly HttpClient _httpClient = new HttpClient(new HttpClientHandler { AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate }, false);

private readonly KeyVaultClient _kvclient = new KeyVaultClient(new KeyVaultClient.AuthenticationCallback(new AzureServiceTokenProvider().KeyVaultTokenCallback), 
                                                                       _httpClient);
```
Finally call goes to here. 

```csharp
 protected ServiceClient(params DelegatingHandler[] handlers)
      : this((HttpClient) null, ServiceClient<T>.CreateRootHandler(), true, handlers)
{
}
```

**Comment by abatishchev** [comment]
The link issue says:

>Using the latest autorest utility 2.0.4283.

@shahabhijeet what version of it you're using?

**Comment by heaths** [comment]
You're right: we should be calling the base constructor taking an `HttpClient` and would also need to plumb through whether it should be disposed or not, mimicking that constructor (as an overload, to avoid breaking changes).

But have you taken a look at our new libraries like <https://docs.microsoft.com/en-us/dotnet/api/azure.security.keyvault.keys?view=azure-dotnet>? They have much improved performance, and have consistent tracing and diagnostics. If you have solutions using multiple languages, you'll find our cross-language libraries to be very consistent while idiomatic to the language. We even have a [sample](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Configuration.md#user-provided-httpclient-instance) of how to use and control the lifetime of your own `HttpClient` instance. There are a lot of great benefits to these new libraries on which we'll be focusing (we're working on a summary document highlighting improvements, but do have a [Channel9 video](https://channel9.msdn.com/Shows/On-NET/Understanding-the-AzureCore-library)).

**Comment by abatishchev** [comment]
Hi, please pickup the latest AutoRest and generate the client using it.

**Comment by heaths** [comment]
We've only making critical fixes to the older libraries at this time. Regenerating could also introducing breaking API changes. Are you able to move to the new libraries that do already support the behavior you want, e.g. Azure.Security.KeyVault.Secrets?

**Comment by abatishchev** [comment]
Great, I didn't know the new version already supports that. Thanks!

**Comment by heaths** [comment]
See https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Configuration.md#user-provided-httpclient-instance for an example.
