### ISSUE TITLE
Adding Dimension and Configuration to SearchIndex in Azure.Search.Documents

### ISSUE THREAD

**Issue by securigy** [Azure/azure-sdk-for-net#39414]
### Library name and version

Azure.Search.Documents 11.5.0-bet

### Query/Question

When I try to create SearchIndex I use this:

```csharp
             try
            {
                SearchIndex? searchIndex = null;
                try
                {
                    searchIndex = await mSearchIndexClient.GetIndexAsync(mIndexName);
                }
                catch (RequestFailedException ex) when (ex.Status == 404)
                {
                    Log.Verbose(ex);
                    // If the specified index not exist, 404 is thrown.

                    string vectorProfileFilePath = Path.Combine(InstallDir, mVectorProfileFileName);
                    string jsonStr = File.ReadAllText(vectorProfileFilePath);


                        VectorSearch? vectorSearch = new()
                        {
                            Profiles =
                            {
                                new VectorSearchProfile("my-default-vector-profile", "my-hnsw-config-2")
                            },
                            Algorithms =
                            {
                                new HnswVectorSearchAlgorithmConfiguration("my-hnsw-config-2")
                            }
                        };

                        **searchIndex = new SearchIndex(mIndexName)**
                        {
                            Fields = new FieldBuilder().Build(typeof(SegmentObj)),
                            
                            // Only available starting 2023-10-01 beta version
                            VectorSearch = vectorSearch
                        };
                    }

                    searchIndex = await mSearchIndexClient.CreateIndexAsync(searchIndex);
                }
                catch (Exception ex)
                {
                    Log.Verbose(ex);
                    return;
                }
```

At the line searchIndex = new SearchIndex(mIndexName) the exception is thrown as shown below, however, I cannot find the way to add 'dimentions' and 'vectorSearchConfiguration' to SegmentTextVector field despite I browsed many of your samples and documentation. So how do I do it?

**This field is defined as:**
```csharp         
          [SearchableField(IsFilterable = false, IsSortable = true)]
          public IReadOnlyList<float>? SegmentTextVector { get; set; }
```

**Exception thrown:**
```text
Azure.RequestFailedException: 'The request is invalid. Details: definition : The vector field 'SegmentTextVector' must have the properties 'dimensions' and 'vectorSearchConfiguration' set.
Status: 400 (Bad Request)
ErrorCode: InvalidRequestParameter
```

Content:
```json
{"error":{"code":"InvalidRequestParameter","message":"The request is invalid. Details: definition : The vector field 'SegmentTextVector' must have the properties 'dimensions' and 'vectorSearchConfiguration' set.","details":[{"code":"InvalidField","message":"The vector field 'SegmentTextVector' must have the properties 'dimensions' and 'vectorSearchConfiguration' set. Parameters: definition"}]}}
```

Headers:
```text
Cache-Control: no-cache
Pragma: no-cache
client-request-id: 3340b211-e406-4662-afcc-766c94da724a
x-ms-client-request-id: 3340b211-e406-4662-afcc-766c94da724a
request-id: 3340b211-e406-4662-afcc-766c94da724a
elapsed-time: 123
Preference-Applied: REDACTED
Strict-Transport-Security: REDACTED
Date: Fri, 20 Oct 2023 05:10:16 GMT
Content-Type: application/json; charset=utf-8
Content-Language: REDACTED
Expires: -1
Content-Length: 397
```

### Environment

Win11, .NET 7, VS2022

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by securigy** [comment]
I think I resolved the posted question, but it would be great to confirm.
After this block:

                       `searchIndex = new SearchIndex(mIndexName)
                        {
                            Fields = new FieldBuilder().Build(typeof(SegmentObj)),
                            
                            // Only available starting 2023-10-01 beta version
                            VectorSearch = vectorSearch
                        };`
 I added the following:

     `                        SearchField field = searchIndex.Fields[4];
                              field.VectorSearchDimensions = 1536;
                              field.VectorSearchProfile = "my-default-vector-profile";
    `
You may ask what is **_searchIndex.Fields[4]_**? 
Well, the vector field I am interested in is the fourth from the top in my class fields definition. Sounds like a hack, especially if my field definition changes later, but how else I can retrieve the field?

Anyway, that eliminated the exception I was referring in my previous post.  One more thing: remember to mark the vector field as non-Sortable and non-filterable.

**Comment by ShivangiReja** [comment]
Hi @securigy, We've recently released the GA version [Azure.Search.Documents@11.5.1](https://www.nuget.org/packages/Azure.Search.Documents/11.5.1), which includes support for Vector Search. To help you get started, please take a look at the sample [here](https://github.com/Azure/azure-sdk-for-net/blob/Azure.Search.Documents_11.5.1/sdk/search/Azure.Search.Documents/samples/Sample07_VectorSearch_UsingVectorizedQuery.md). It provides guidance on adding a vector field and performing vector searches.

**Comment by securigy** [comment]
Just a comment that all your search configuration stuff, both for VectorSearch and SemanticSearch is a mess - very poorly documented, piece here and piece there, in addition to constantly changing... just my 2 cents

**Comment by ShivangiReja** [comment]
Thank you for your feedback, @securigy. I understand that the search configuration for both VectorSearch and SemanticSearch may have seemed fragmented and frequently changing. When your issue was created, these features were in the preview stage and not yet generally available (GA). As per the [SDK preview  version guidelines](https://learn.microsoft.com/en-us/azure/developer/intro/azure-service-sdk-tool-versioning#preview-versions), we can introduce breaking changes based on the feedback we receive about proposed changes and new features introduced by the search service. This is why you may have noticed several updates.

Now that VectorSearch and SemanticSearch are GA, we won't be introducing any new breaking changes via the SDK. Regarding the documentation, we have made efforts to improve it alongside the GA release. Please refer to the service documentation for [VectorSearch](https://learn.microsoft.com/en-us/azure/search/vector-search-overview) and [SemanticSearch](https://learn.microsoft.com/en-us/azure/search/semantic-search-overview), as well as the SDK usage documentation for [VectorSearch](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/samples/Sample07_VectorSearch.md) and [SemanticSearch](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/samples/Sample08_SemanticSearch.md).

We value your feedback and would appreciate any specific suggestions you may have for further improvements.

**Comment by securigy** [comment]
Thank you for your response. Whom do I talk to with regards to the responses that I get from the vector search? It seems that when I get 6-8 responses from the vector search and feed them into Azure OpenAI Completion API as a context (RAG) I get quite generic response, instead of specific answer... So, I wonder how I can improve it. Honestly, I am confused by the options: 
- I realize I can do both Vector and Semantic Search 
- I am not sure how to use text search, especially when I also retrieve Named Entities using analytics. That is, where to feed those? As Keywords? as Text Search? As additional vector after creating embeddings from them?

**Comment by ShivangiReja** [comment]
Your best path for reporting the quality of results to the Search service team would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). Alternatively, you could consider posting to the [Azure Search forum](https://feedback.azure.com/d365community/forum/9325d19e-0225-ec11-b6e6-000d3a4f07b8) of the Azure Feedback site, as that forum is also monitored by the service team.

@mattmsft, @pallavit

**Comment by ShivangiReja** [comment]
@securigy Your best path for reporting the quality of results to the Search service team would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). Alternatively, you might consider posting on the [Azure Search forum](https://feedback.azure.com/d365community/forum/9325d19e-0225-ec11-b6e6-000d3a4f07b8) on the Azure Feedback site, as this forum is also monitored by the service team.

For RAG, please refer to the following documentation:
* [Retrieval-Augmented Generation Overview](https://learn.microsoft.com/en-us/azure/search/retrieval-augmented-generation-overview)
* [Getting Started with App Chat Template](https://learn.microsoft.com/en-us/dotnet/azure/ai/get-started-app-chat-template?tabs=github-codespaces)

Cc: @mattmsft, @pallavit
