### ISSUE TITLE
[QUERY] Is there a way to customize the behavior of the RedirectPolicy

### ISSUE THREAD

**Issue by xiaomi7732** [Azure/azure-sdk-for-net#39425]
### Library name and version

Azure.Core.1.33.0

### Query/Question

RedirectPolicy will clear the authorization header - https://github.com/Azure/azure-sdk-for-net/blob/2b941a2f3cb6ebefba2477effc741941f1883ac8/sdk/core/Azure.Core/src/Pipeline/RedirectPolicy.cs#L83C1-L84C1

1. Is there some way to keep it?
2. If not, what is the best way to supply an alternative to maybe replace the current RedirectPolicy?
    * We are considering disabling **allowAutoRedirect** and then supplying a similar policy that doesn't strip the header or resend the request, which feels a bit upside down. What would be the best approach?

======
If we understand correctly, the reason to strip the header is to avoid exposing the authorization header to an untrusted host. Is it possible to expose a delegate for the client code (our code) to determine whether the host is trusted and avoid stripping the header when it is?

We have a legitimate scenario where 302 Found is returned by a request, and we know the trusted host to go with.

### Environment

Windows; .NET 6;

**Comment by pallavit** [comment]
Thank you for reporting the issue. Tagging and routing it to the person best able to assist you.
FYI - /cc: @annelo-msft , @christothes

**Comment by JoshLove-msft** [comment]
Hi @xiaomi7732,
As of 1.33.0, redirects are actually disabled by default due to security concerns. If you choose to enable redirects, then the auth header is stripped for the reason that you mentioned. Does the URI that you are being redirected to require the auth header?

**Comment by JoshLove-msft** [comment]
Yes, we can use this issue to track that feature request.

**Comment by xiaomi7732** [comment]
@JoshLove-msft , Fantastic. Please keep us posted for the changes. We are looking forward to see the capability to be implemented.

**Comment by JoshLove-msft** [comment]
@xiaomi7732, can you clarify whether you are writing a client library that needs this functionality or if you are intending to use this feature as a user of a client library or Azure.Core?

**Comment by xiaomi7732** [comment]
@JoshLove-msft, we have code using **HttpPipeline** (instead of HttpClient) to leverage the policy/retryPolicy provided. So, we are the latter.

I am just curious, why does that matter? A client library would also be a user for `Azure.Core` too, right? :-)

**Comment by JoshLove-msft** [comment]
> I am just curious, why does that matter? A client library would also be a user for `Azure.Core` too, right? :-)

Yes, but the question is who would be configuring this policy - would it be the client library or the user of the client library? The answer to that question would help inform the API design. It sounds like for your scenario, it would be the client library itself that needs to configure the policy.

**Comment by xiaomi7732** [comment]
Okay. I am not sure I can see the difference without seeing the details. But if you'd like to share the API design, I'd be glad to verify whether that's gonna work for our scenario or not.

**Comment by JoshLove-msft** [comment]
@xiaomi7732, can you share your code for how you are constructing the `HttpPipeline`?

**Comment by xiaomi7732** [comment]
Yes. this is a simplified version of the factory method we used:

```csharp
return HttpPipelineBuilder.Build(
    clientOptions,
    perCallPolicies: new HttpPipelinePolicy[]
    {
        new ABCPolicy(clientOptions.Endpoint),
        new VersionPolicy(clientOptions.ApiVersion)
    },
    transportOptions: new HttpPipelineTransportOptions
    {
        IsClientRedirectEnabled = true
    },
    responseClassifier: null);
```

FWIW, I would imagine a delegate to allow checking for trusted endpoints. For example:

```csharp
return HttpPipelineBuilder.Build(
    clientOptions,
    transportOptions: new HttpPipelineTransportOptions
    {
        IsClientRedirectEnabled = true
        // Only forward the auth header for trusted host
        IsTrustedHost( url => {
            if(url.IsRelativeUri) // Relative url doesn't specify host, use base uri
            {
                  return true;
            }
            if(url.host) ...  // Check if the target is whitelisted.
            {
                  return true;
            }
            return false;
        })
    },
    responseClassifier: null);

```
Please let me know if there more info needed.

**Comment by JoshLove-msft** [comment]
So you do not use the [BearerTokenAuthenticationPolicy](https://learn.microsoft.com/en-us/dotnet/api/azure.core.pipeline.bearertokenauthenticationpolicy?view=azure-dotnet)? I ask because this policy, when applied in the `perRetryPolicies` will result in the Authorization header always being applied before sending the request.

**Comment by xiaomi7732** [comment]
@JoshLove-msft Yes, we use `BearerTokeAuthenticationPolicy`. Actually, we use that as a workaround. It allows us to re-attach the header on every call.

The problem is, that applying it to `perRetryPolicies` is at best a workaround. It defeats the purpose of removing the header for the redirect scenario.

Does that make sense?

**Comment by JoshLove-msft** [comment]
That makes sense. The issue in which BearerTokenAuthPolicy adds back the header unconditionally would need to be addressed as part of the feature to allow customizing whether the RedirectPolicy retains the header. Otherwise, it will just get added back if a library is adding the bearer token policy.

**Comment by xiaomi7732** [comment]
@JoshLove-msft Thanks for the communication. Just on the side, please consider backward compatibility carefully. I actually have a complaint about stopping auto-redirect by default. Here's our case:

I have 1 library A, that references the package `Azure.Core.1.31.0` with auto-redirect;
The user has some other library, B, that references the package `Azure.Core.1.33.0`, where auto-redirect is disabled;

The problem, at the runtime, the latest package will be used, and auto-redirect will be off by default, and the library A stopped working because of that.

**Comment by jsquire** [comment]
Hi @xiaomi7732 .  Thanks for reaching out and for opening this feature request.  The Azure.Core team has reviewed, and we have decided not to move forward with this feature.  This is a rather a unique scenario which can be satisfied by the current work around or by disabling the built-in redirect policy and injecting a custom policy.

Should we receive feedback from other developers asking for similar functionality in the future, we may reconsider.  For now, I'm going to close this out as unplanned.
