### ISSUE TITLE
[BUG] Nullable enum type on a ITableEntity class throws an exception if the value is null

### ISSUE THREAD

**Issue by jhariel8** [Azure/azure-sdk-for-net#39448]
### Library name and version

Azure.Data.Tables 12.8.1

### Describe the bug

I have a base class (EngageReaderStateDto) with some properties in it, some of which are nullable enum types. I extended the class with the properties needed for Table Storage (PartitionKey, RowKey, ETag, and Timestamp), and the extension of this class implements ITableEntity. The name of this class is ReadEngageReaderStateEntity. Sometimes the value of these nullable enums may not be known when the entity is initially created, meaning they are not written to table storage.

I then query entities from Table Storage using a method that accepts a parameter "serialNumber" of type string:

```c#
var result = table.Query<ReadEngageReaderStateEntity>(entity => entity.PartitionKey == serialNumber.ToLower());

if (result != null && result.Any())
    stateDto = JsonConvert.DeserializeObject<EngageReaderStateDto>(JsonConvert.SerializeObject(result.FirstOrDefault()));
```

### Expected behavior

All the method calls should succeed and an EngageReaderStateDto object should be returned, with any missing properties, including the enum types, set to null.

### Actual behavior

The call to result.Any() fails with the following exception:

System.ArgumentNullException:
   at System.Enum.TryParse (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Azure.Data.Tables.TablesTypeBinder.TryGet (Azure.Data.Tables, Version=12.8.1.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)
   at Azure.Core.TypeBinder`1+BoundMemberInfo`1.Deserialize (Azure.Data.Tables, Version=12.8.1.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)
   at Azure.Core.TypeBinder`1+BoundTypeInfo.Deserialize (Azure.Data.Tables, Version=12.8.1.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)
   at Azure.Data.Tables.DictionaryTableExtensions.ToTableEntityList (Azure.Data.Tables, Version=12.8.1.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)
   at Azure.Data.Tables.TableClient+<>c__DisplayClass56_0`1.<Query>b__0 (Azure.Data.Tables, Version=12.8.1.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)
   at Azure.Core.PageableHelpers+FuncPageable`1+<AsPages>d__4.MoveNext (Azure.Data.Tables, Version=12.8.1.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)
   at Azure.Pageable`1+<GetEnumerator>d__8.MoveNext (Azure.Core, Version=1.35.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)
   at System.Linq.Enumerable.Any (System.Linq, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)

Excluding the nullable columns by providing the "select" parameter to the query causes the call to succeed. Changing the nullable enums to nullable ints also causes it to succeed

### Reproduction Steps

* Create a class that extends ITableEntity with nullable enum properties.
* Write an entity to Table Storage with the enum properties set to null.
* Attempt to query the entity back from Table Storage.

### Environment

IDE Version: Visual Studio 17.7.4

The application is hosted in Azure Kubernetes Service but the error occurs locally as well.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @jhariel8 - 
I'm not able to reproduce this given the steps above. Here is what I did:

code
```c#
var client = service.GetTableClient("nullableenum");
client.CreateIfNotExists();
var userEntity = new UserEntity();
userEntity.NullableEnum = null;
client.UpsertEntity(userEntity);
var result = client.Query<UserEntity>();
var any = result.Any();
Console.WriteLine(any);
foreach (var item in result)
{
    Console.WriteLine($"RK:{item.RowKey} enum:{item.NullableEnum}");
}
/* output after a few runs including one setting the enum to a non-null value
True
RK:88e50656-f614-4468-bf01-1b9ab3cdd673 enum:
RK:c817648c-9e94-4111-9bb5-543ddb9c84b6 enum:
RK:ed6e60b7-aa31-40a3-975e-0042e75e5c8a enum:
RK:66f154ee-e39f-4ce2-aed3-003c9dba7668 enum:
RK:ba7dcdc7-fd08-4a53-83d7-2d8967ab6a6a enum:Foo
*/
```

model
```c#
public enum MyEnum
{
    Foo,
    Bar
}

public class UserEntity : ITableEntity
{
    public string PartitionKey { get; set; }
    public string RowKey { get; set; }
    public DateTimeOffset? Timestamp { get; set; }
    public ETag ETag { get; set; }
    public int Value { get; set; }
    public MyEnum? NullableEnum { get; set; }

    public UserEntity()
    {
        PartitionKey = Guid.NewGuid().ToString();
        RowKey = Guid.NewGuid().ToString();
        Value = new Random().Next();
    }
}
```

**Comment by jhariel8** [comment]
Hey @christothes,

Thanks for looking into this.

Your setup looks pretty similar to ours. The only differences I can really see are as follows:
1) All our enums start with a value = 1, whereas yours start (implicitly) with 0.
2) We use two different classes for writing to table storage and reading from it, whereas you are using the same one.

I have no idea if those particulars even make a difference. The one that I would think would potentially cause an issue is the fact that we use two different entity classes for writing and reading, but I would still think that as long as the properties are the same types that it would work? We do this because we have a class that dynamically constructs a TableEntity based on the properties that we pass into it, but this may not be necessary for this case (I can look into that tomorrow). For whatever reason, it does work when I change the nullable enums to nullable ints though, so I still feel like there's some kind of issue here.

If neither of those things raise alarms for you, is there any other reason you think we could potentially be running into this? We are using the latest package version (12.8.1).

**Comment by christothes** [comment]
> Your setup looks pretty similar to ours. The only differences I can really see are as follows:
> 
> 1. All our enums start with a value = 1, whereas yours start (implicitly) with 0.
> 2. We use two different classes for writing to table storage and reading from it, whereas you are using the same one.

Neither of these seem relevant to me. Are you able to reproduce using a simplified example like mine?

> If neither of those things raise alarms for you, is there any other reason you think we could potentially be running into this?

I can't think of a reason unless there is something different about your deserialization model. Perhaps a simplified repro would help uncover the difference?

**Comment by jhariel8** [comment]
Hi @christothes,

I created an entirely new project, only bringing over the relevant objects/enums, and tried it again and it is still occurring for me. I've stripped our object down to a bare minimum:

`using Azure;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NullableEnumTest
{
    public class StateEntity : StateDto, Azure.Data.Tables.ITableEntity
    {
        public string PartitionKey { get; set; }
        public string RowKey { get; set; }
        public DateTimeOffset? Timestamp { get; set; }
        public ETag ETag { get; set; }
    }

    public enum SecurityState
    {
        Locked = 1,
        Unlocked = 2,
        Forced = 3,
        Propped = 4,
        Unknown = 20
    }

    public enum BusyState
    {
        Ready = 1,
        ProcessingDb = 2,
        UpdatingFirmware = 3,
        Unknown = 20
    }

    public enum ConnectionState
    {
        Offline = 1,
        GettingCertificate = 2,
        InitialAuthSucceeded = 3,
        ConnectingToServer = 4,
        Connected = 5,
        AuthFailedInvalidTimestamp = 6,
        AuthFailedInvalidBasicCreds = 7,
        LookingUpSerialNumber = 8,
        NeverCommunicated = 9,
        NeedsRecommission = 10,

        InitialAuthFailed = 11,
        Unknown = 20,
    }

    public enum DatabaseState
    {
        Good = 1,
        Unknown = 2,
        Corrupt = 3,
        FDRNeeded = 4
    }

    public class StateSummaryDto
    {
        public string serialnumber { get; set; }
        public SecurityState? securitystate { get; set; }
        public string dooropen { get; set; }
        public ConnectionState? connectionstate { get; set; }
        public BusyState? busystate { get; set; }
        public string accountuid { get; set; }
        public string accountgid { get; set; }
    }

    public class StateDto : StateSummaryDto
    {
        public DatabaseState? databasestate { get; set; }
        //public string configurationparams { get; set; }
        //public long? configurationparamslast { get; set; }
    }
}
`

This code is throwing the same exception:

`var result = table.Query<StateEntity>(entity => entity.PartitionKey == "<serialnumber>".ToLower());

if (result != null && result.Any()) {}`

The offending record in table storage has a value for connectionstate and securitystate and busystate, but not for databasestate. Perhaps it's the combination of null and non-null values?

**Comment by christothes** [comment]
I tried this locally and still can't repro. If you have a consistently reproducible sample program, would you be willing to put it into a public github repo as a complete solution? There must be something different that we are missing here.

**Comment by jhariel8** [comment]
@christothes I've pretty much shared everything that I have, minus the actual connection to our table storage account which I can't provide.

We've made a workaround at this point using nullable int values instead of nullable enums, so I guess we'll just go with that for now. It isn't ideal, but it appears we've gone as far as we can to debug this.

I appreciate you looking into this! Maybe at some point I will have something additional that I can share that would help fix this issue, but I will close this for now.
