### ISSUE TITLE
Communication Messages Readme Issue

### ISSUE THREAD

**Issue by jianingwang123** [Azure/azure-sdk-for-net#39445]
1.
**Section** [link](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/communication/Azure.Communication.Messages/README.md):
![image](https://github.com/Azure/azure-sdk-for-net/assets/141212663/e75d64fe-eb7e-4383-b8c5-151bab267417)
![image](https://github.com/Azure/azure-sdk-for-net/assets/141212663/bd3714fd-9681-4e29-8e83-81cb9d692f1e)
![image](https://github.com/Azure/azure-sdk-for-net/assets/141212663/9c38838a-146d-4239-8acb-3c3e85fadbe0)

**Reason**:
The links are invalid.

**Suggestion**:
Add links for the following names:
[Source code]: [https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/communication/Azure.Communication.Messages/src](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/communication/Azure.Communication.Messages/src).
 [Package (NuGet)]: [https://www.nuget.org/packages/Azure.Communication.Messages](https://www.nuget.org/packages/Azure.Communication.Messages).
[Product documentation]: [https://learn.microsoft.com/zh-cn/azure/communication-services/overview](https://learn.microsoft.com/zh-cn/azure/communication-services/overview).
[NuGet]: [https://www.nuget.org](https://www.nuget.org).
[Azure subscription]: [https://azure.microsoft.com/zh-cn/free/dotnet/](https://azure.microsoft.com/zh-cn/free/dotnet/).
[Communication Service Resource]: [https://learn.microsoft.com/zh-cn/azure/communication-services/quickstarts/create-communication-resource?tabs=windows&pivots=platform-azp](https://learn.microsoft.com/zh-cn/azure/communication-services/quickstarts/create-communication-resource?tabs=windows&pivots=platform-azp).
[Azure Portal]: [https://learn.microsoft.com/zh-cn/azure/communication-services/quickstarts/create-communication-resource?tabs=windows&pivots=platform-azp](https://learn.microsoft.com/zh-cn/azure/communication-services/quickstarts/create-communication-resource?tabs=windows&pivots=platform-azp).
[Azure PowerShell]: [https://learn.microsoft.com/zh-cn/powershell/module/az.communication/new-azcommunicationservice](https://learn.microsoft.com/zh-cn/powershell/module/az.communication/new-azcommunicationservice).
[.NET management client library]: [https://learn.microsoft.com/zh-cn/azure/communication-services/quickstarts/create-communication-resource?tabs=windows&pivots=platform-net](https://learn.microsoft.com/zh-cn/azure/communication-services/quickstarts/create-communication-resource?tabs=windows&pivots=platform-net).
[Azure Portal]: [https://portal.azure.com](https://portal.azure.com).
[cla.microsoft.com]: [https://cla.microsoft.com](https://cla.microsoft.com).
[Microsoft Open Source Code of Conduct]: [https://opensource.microsoft.com/codeofconduct/](https://opensource.microsoft.com/codeofconduct/).
[Code of Conduct FAQ]: [https://opensource.microsoft.com/codeofconduct/faq/](https://opensource.microsoft.com/codeofconduct/faq/).

@jsquire , @scottaddie , @mayurid and @acsdevx-msft to notification.

**Comment by Shamkh** [comment]
Hi Team,
We have recently release new documentation for new Azure ACS service. Need to understand, how we can receive this feedback to team email.

Thanks
Shamsha

**Comment by glorialimicrosoft** [comment]
The Readme issue has been fixed by: https://github.com/Azure/azure-sdk-for-net/pull/39618

**Comment by jianingwang123** [comment]
@glorialimicrosoft Your PR https://github.com/Azure/azure-sdk-for-net/pull/39618 has two link issues. There is an extra ' . ' at the end of these two links, please update.
-> [nuget]: [https://www.nuget.org](https://www.nuget.org)
-> [azure_portal]: [https://portal.azure.com](https://portal.azure.com)
![image](https://github.com/Azure/azure-sdk-for-net/assets/141212663/56cc67e9-7bb8-4fd2-adf5-d82d6e267712)

**Comment by glorialimicrosoft** [comment]
@jianingwang123 Thanks for catching them, here is the PR to fix the two dots. https://github.com/Azure/azure-sdk-for-net/pull/39638

**Comment by jianingwang123** [comment]
@glorialimicrosoft  LGTM, we will close this issue after this PR [#39638](
https://github.com/Azure/azure-sdk-for-net/pull/39638) merge.

**Comment by v-xuto** [comment]
This issue has been fixed. We will close this issue.
