### ISSUE TITLE
[BUG] Table Fields for Neural/Template models are not returned correctly DocumentAnalysisClient.AnalyzeDocument (including other versions of this method)

### ISSUE THREAD

**Issue by IanBruwer** [Azure/azure-sdk-for-net#39469]
### Library name and version

Azure.AI.FormRecognizer 4.1.0

### Describe the bug

When calling the Document Intelligence SDK DocumentAnalysisClient.AnalyzeDocument or any of it's variants e.g. async or from url, I get a different response than if I call the rest api directly.  The first response with the white background is what I get back from the rest api. 
![image](https://github.com/Azure/azure-sdk-for-net/assets/6494527/a4e54fc8-7469-4f7c-9ab0-811091302857)

The second response in black is what I get back via the SDK.
![image](https://github.com/Azure/azure-sdk-for-net/assets/6494527/791381c0-18d2-4762-9591-b468e8e8d657)

In short Table Fields don't appear to be returning correctly via the SDK.

### Expected behavior

TableFields should contain appropriate data not just the Table Field Name e.g. 
![image](https://github.com/Azure/azure-sdk-for-net/assets/6494527/bcc2a5ac-a3c7-4137-b366-a6408a5e866a)

### Actual behavior

Table Fields are returned with only the Table Field Names and empty values e.g. 
![image](https://github.com/Azure/azure-sdk-for-net/assets/6494527/1317996b-94ed-47eb-b7e1-92ee68c622ce)

### Reproduction Steps

1. In Azure, Create a custom extraction model based in West Europe
2. define a model with a table field 
![image](https://github.com/Azure/azure-sdk-for-net/assets/6494527/13bbf0db-568d-416a-b4e4-93e3df2524fb)
3. train model
4. Call model as per the below
AnalyzeDocumentOperation operation = await azureClient.AnalyzeDocumentAsync(WaitUntil.Completed, "10DocNeural", fs);
AnalyzeResult result = operation.Value;

5. Inspect "Fields" element.

### Environment

.NET SDK:
 Version:   7.0.400
 Commit:    73bf45718d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.400\

Host:
  Version:      7.0.10
  Architecture: x64
  Commit:       a6dbb800a4

.NET SDKs installed:
  7.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  [Microsoft.AspNetCore.App](http://microsoft.aspnetcore.app/) 7.0.10 [C:\Program Files\dotnet\shared\[Microsoft.AspNetCore.App](http://microsoft.aspnetcore.app/)]
  [Microsoft.NETCore.App](http://microsoft.netcore.app/) 6.0.11 [C:\Program Files\dotnet\shared\[Microsoft.NETCore.App](http://microsoft.netcore.app/)]
  [Microsoft.NETCore.App](http://microsoft.netcore.app/) 7.0.10 [C:\Program Files\dotnet\shared\[Microsoft.NETCore.App](http://microsoft.netcore.app/)]
  [Microsoft.WindowsDesktop.App](http://microsoft.windowsdesktop.app/) 6.0.11 [C:\Program Files\dotnet\shared\[Microsoft.WindowsDesktop.App](http://microsoft.windowsdesktop.app/)]
  [Microsoft.WindowsDesktop.App](http://microsoft.windowsdesktop.app/) 7.0.10 [C:\Program Files\dotnet\shared\[Microsoft.WindowsDesktop.App](http://microsoft.windowsdesktop.app/)]

IDE = Visual Studio Code

Project
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.AI.FormRecognizer" Version="4.1.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
</Project>

**Comment by pallavit** [comment]
Thank you for reporting the issue. Tagging and routing to the member best able to assist you.

**Comment by kinelski** [comment]
Hello @IanBruwer.

Our models were not designed with serialization in mind, so it's expected to see inconsistencies with the REST API when trying to serialize them into JSON.

If you want to get the raw response as it was originally returned by the service, you can use the `GetRawResponse` method:
```cs
AnalyzeDocumentOperation operation = await azureClient.AnalyzeDocumentAsync(WaitUntil.Completed, "10DocNeural", fs);
string jsonResponse = operation.GetRawResponse().Content.ToString();
```
