### ISSUE TITLE
[QUERY] Which number format info should be used by exporter?

### ISSUE THREAD

**Issue by avereshchak** [Azure/azure-sdk-for-net#39470]
### Library name and version

Azure.Monitor.OpenTelemetry.Exporter 1.0.0

### Query/Question

Should the exporter use the ```NumberFormatInfo``` from ```CultureInfo.InvariantCulture``` for converting activity tags of double/float type?

Currently it is using the ```CultureInfo.CurrentCulture```. 

There are a couple consequences:
- Several tests such as  [TagObjects_DoubleArray](https://github.com/Azure/azure-sdk-for-net/blob/0641744a402e4a92387eda2e28fa75662f37397d/sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/tests/Azure.Monitor.OpenTelemetry.Exporter.Tests/TagsTests.cs#L209C31-L209C31) will fail on my PC because the "," character is used as a decimal symbol, not "." as expected by tests.
- Activity tag values of double type will be converted using different number formats depending on regional settings of a machine running the application being instrumented. If I try convert these values back to double in my Kusto query, I might have to consider all possible decimal symbols, thus making the query more complicated.

Is this an expected behavior of the exporter?

### Environment

I'm using the Azure.Monitor.OpenTelemetry.Exporter 1.0.0 in .NET 7.0 console application.

**Comment by cijothomas** [comment]
Looks like unintentional/bug.
