### ISSUE TITLE
no help at all for filter types

### ISSUE THREAD

**Issue by oren-shn** [Azure/azure-sdk-for-net#39508]
need some explanation about filter types

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 42a20203-9bd1-4c28-0ac1-d2b1214902e9
* Version Independent ID: 7e18fdc7-503c-6a13-72e8-fea167f7882a
* Content: [ResourceGroupResource.GetGenericResources Method (Azure.ResourceManager.Resources) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.resources.resourcegroupresource.getgenericresources?view=azure-dotnet&devlangs=csharp&f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Azure.ResourceManager.Resources.ResourceGroupResource.GetGenericResources)%3Bk(DevLang-csharp)%26rd%3Dtrue)
* Content Source: [xml/Azure.ResourceManager.Resources/ResourceGroupResource.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.ResourceManager.Resources/ResourceGroupResource.xml)
* Service: **azure**
* GitHub Login: @azure-sdk
* Microsoft Alias: **azsdkdocs**

**Comment by HarveyLink** [comment]
Hi @oren-shn , Thank you for using Azure SDK for .NET.
For the sample code, please check: https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/resourcemanager/Azure.ResourceManager#create-genericresource
