### ISSUE TITLE
[BUG] EnvironmentCredential changes behavior of DefaultAzureCredential even when it is excluded

### ISSUE THREAD

**Issue by nschuessler** [Azure/azure-sdk-for-net#39503]
### Library name and version

Azure.Identity 1.10.3

### Describe the bug

If you use DefaultAzureCredential in the following way:

 ```
 DefaultAzureCredentialOptions options = new DefaultAzureCredentialOptions()
     {
          ExcludeEnvironmentCredential = true,
          ExcludeInteractiveBrowserCredential = true,
          ExcludeManagedIdentityCredential = true,
          ExcludeWorkloadIdentityCredential = true,
          ExcludeAzureCliCredential = true,
          ExcludeAzurePowerShellCredential = true,
          ExcludeSharedTokenCacheCredential = false,
          ExcludeAzureDeveloperCliCredential = false,
          ExcludeVisualStudioCodeCredential = false,
          ExcludeVisualStudioCredential = false,
     };

     DefaultAzureCredential tokenCredential = new DefaultAzureCredential(options);
```

(note: `ExcludeEnvironmentCredential` is set to true). and the AZURE_TENANT_ID environment variable is set, the default tenant is reset by the the credential anyway for subsequent credential checks.

For development environment, we have a key vault in one local tenant for development with our startup secrets, after which it uses production services in the default (set by AZURE_TANANT_ID) for the rest of the azure blobs and data.

Because of this behavior, it is not possible to do development in the development environment unless you replicate all the azure environment items into the development environment.

I'm trying specifying the tenant id specifically in `TokenRequestContext()` to see if that helps.

### Expected behavior

If `TokenRequestContext` has a null `TenantId` setting, it should pick the local one, not the one from AZURE_TENANT_ID, since `ExcludeEnvironmentCredential` is set to `true`

### Actual behavior

It changes the tenant id to that set by AZURE_TENANT_ID environment variable w/o looking at the options.

### Reproduction Steps

Use the code above to get a token for the scope "https://vault.azure.net/.default" with and without AZURE_TENANT_ID set. You'll see the default tenant changes.

### Environment

dotnet 6.0
This is an ASP.NET web application. ASP.NetCore 6.0.24
Azure.Identity 1.10.3

**Comment by christothes** [comment]
Hi @nschuessler - 


> If `TokenRequestContext` has a null `TenantId` setting, it should pick the local one, not the one from AZURE_TENANT_ID, since `ExcludeEnvironmentCredential` is set to `true`

In your code, where is the "local" TenantId being configured? In the example above, there is no TenantId option set.

The current expected behavior for the AZURE_TENANT_ID environment variable is that if no explicit tenant Id is supplied in the options, the one from the environment is used (if set). This is unrelated to the EnvironmentCredential itself.

If you have some clients that need to use different TenantIds, you will need to configure those clients with distinct credential instances with the preferred TenantId configured in the options.

**Comment by nschuessler** [comment]
In my case, I used the default of 'null' for tenant. And it picked up the tenant where my user account/machine where I do my development are hosted for most simple projects.

```
AccessToken token = await tokenCredential.GetTokenAsync(
    requestContext: new TokenRequestContext(
        scopes: new string[] { "https://vault.azure.com/.default" }), // tenantId is null by default.
    cancellationToken: cancellationToken);
```
How does it make sense to pick up a user credential for the current logged in VSO development environment (this goes for CLI credential, powershell credential, shared cache credential ...),  and the honor AZURE_TENANT_ID which points elsewhere?  They will never match right?

If you can't find all the credentials you need to auth in the SAME place from the same method, then use none of them and try the next credential right?

**Comment by christothes** [comment]
Thanks for the feedback, @nschuessler. What I've described is the actual behavior, and changing it would be a breaking change. Do you have any additional questions about how to get the correct TenantId set for your scenario?

**Comment by nschuessler** [comment]
Thanks initial question is answered.
