### ISSUE TITLE
[BUG]ServiceFabricManagedNodeTypeResource.NodeTypesRestOperations Both Update and UpdateAsync throw Http 202 accepted message as error

### ISSUE THREAD

**Issue by shobanabanda** [Azure/azure-sdk-for-net#39509]
### Library name and version

Azure.ResourceManager.ServiceFabricManagedClusters 1.1.0 and up until1.1.0-beta.2

### Describe the bug

ServiceFabricManagedNodeTypeResource throw HTTP Status 202 as error which is resulting in exception.
Functions that needs correction - UpdateAsync and Update
Recommended fix at Line 581 at https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicefabricmanagedclusters/Azure.ResourceManager.ServiceFabricManagedClusters/src/Generated/RestOperations/NodeTypesRestOperations.cs 

Change existing switch to allow 202 
 switch (message.Response.Status)
            {
                case 200:
                case 202:
                    return message.Response;
                default:
                    throw new RequestFailedException(message.Response);
            }

### Expected behavior

Http status code 202 Accepted response should not be treated as error and no exception should occur.

### Actual behavior

Http status code 202 Accepted response is throwing RequestFailed Exception

### Reproduction Steps

Invoke UpdateAsync or Update to scale up capacity of servicefabric managed nodetype resource.

### Environment

Occurs even in 1.1.0-beta.2 latest prerelease of Azure SDK Azure.ResourceManager.ServiceFabricManagedClusters

**Comment by mcgallan** [comment]
Fixed
