### ISSUE TITLE
[QUERY] How can I gather all eventsubscriptions attached to a storage account?

### ISSUE THREAD

**Issue by Rajesh-Patel-SH** [Azure/azure-sdk-for-net#39501]
### Library name and version

Azure.ResourceManager.EventGrid 1.0.1

### Query/Question

Hi! 

I am wanting to get all eventsubscriptions that are attached to a storage account, how can i go about doing this? Here is a picture in the UI, which shows what I want to get.

<img width="821" alt="image" src="https://github.com/Azure/azure-sdk-for-net/assets/136853151/f8eea823-aeaa-4420-aabc-64803f938910">

I want the line at the very bottom that I covered in red

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by mcgallan** [comment]
@Rajesh-Patel-SH 
To view all event subscriptions that are attached to a storage account in the Azure portal, follow these steps:

1.Sign in to the Azure portal.
2.In the left navigation pane, select “Storage accounts”.
3.Select the storage account you want to check.
4.In the storage account’s left navigation pane, scroll down to the “Events” section and select “Events”.
5.On the “Events” page, you will see a list of all event subscriptions that are attached to the storage account.

**Comment by mcgallan** [comment]
Hi @Rajesh-Patel-SH According to my knowledge, in Microsoft.Azure.Management.EventGrid, you can use `eventGridManagementClient.EventSubscriptions.ListByResourceAsync(storageAccountId)` to get all the relevant event subscriptions. However, currently, there is no alternative method in Azure.ResourceManager.EventGrid to accomplish this task using the Azure SDK. Thank you for your feedback.

**Comment by melina5656** [comment]
Hi @Rajesh-Patel-SH. You can refer to this sample code to complete getting all eventsubscriptions.

 ```csharp
  var scope = new ResourceIdentifier($"{storageAccount.Id}");
  var eventSubscriptionCollection = armClient.GetEventSubscriptions(scope);
  int i = 0;
  await foreach(var events in eventSubscriptionCollection.GetAllAsync())
  {
      Console.WriteLine(events.Data.Name);
      i++;
  }
  Console.WriteLine("sum:" + i);
  ```
Thank you for your feedback.
