### ISSUE TITLE
[BUG] Mocking: ServiceBusProcessor protected ctor does not create sessionIds

### ISSUE THREAD

**Issue by slaneyrw** [Azure/azure-sdk-for-net#39520]
### Library name and version

Azure.Messaging.ServiceBus, 7.14.0

### Describe the bug

I'm trying to unit test ServiceBusSessionProcessor.

Whilst I can override InnerProcessor, the UpdateConcurrency on ServiceBusSessionProcessor invokes the Inner's internal UpdateConcurrency.

This method on ServiceBusProcessor relies on a local field _sessionIds.  This is not initialized in the protected constructor.
Calling this method from a mocked/substituted instance throws a NullReferenceException

### Expected behavior

Calling ServiceBusSessionProcessor.UpdateConcurrency on a mocked/substituted instance should not throw any exception

### Actual behavior

  Message: 
System.NullReferenceException : Object reference not set to an instance of an object.

  Stack Trace: 
ServiceBusProcessor.UpdateConcurrency(Int32 maxConcurrentSessions, Int32 maxConcurrentCallsPerSession)
ServiceBusSessionProcessor.UpdateConcurrency(Int32 maxConcurrentSessions, Int32 maxConcurrentCallsPerSession)

### Reproduction Steps

```csharp
public class ServiceBusSessionProcessorDouble : ServiceBusSessionProcessor
{
    protected ServiceBusSessionProcessorDouble()
    {
        // The session processor relies on an InnerProcessor for some parts... so make sure we have one
        this.innerProcessor = Substitute.ForPartsOf<ServiceBusProcessor>();
    }
    protected override ServiceBusProcessor InnerProcessor => this.innerProcessor;
}

var sessionProcessor = new ServiceBusSessionProcessorDouble();

sessionProcessor.UpdateConcurrency(1, 1);
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by slaneyrw** [comment]
Adding the following to the above constructor allows the code to not throw

``
            var field = typeof(ServiceBusProcessor).GetField("_sessionIds", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic);
            field.SetValue(this.innerProcessor, Array.Empty<string>());
``
