### ISSUE TITLE
Query as a stream only supports single partition queries

### ISSUE THREAD

**Issue by veselfil** [Azure/azure-sdk-for-net#39528]
Can you please clarify what "Query as a stream only supports single partition queries" means for the `GetItemQueryStreamIterator` method? 

I've noticed some overloads of `GetItemQueryIterator<T>` do not have this remark in the docs, however, internally the generic version calls the Stream version, at least from what I've been able to find. Moreover, calling `GetItemQueryStreamIterator` for `SELECT * FROM c` without specifying a partition key has returned an OK response, and appears to have actually iterated over all partitions. 

Am I misunderstanding what this means?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a566e19a-4602-3cb9-3984-b0872bc40287
* Version Independent ID: f4a0d818-5959-bfc2-2fee-071e2e14e60c
* Content: [Container.GetItemQueryStreamIterator Method (Microsoft.Azure.Cosmos) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container.getitemquerystreamiterator?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Cosmos/Container.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/Container.xml)
* Service: **cosmos-db**
* GitHub Login: @azure-sdk
* Microsoft Alias: **azsdkdocs**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.Azure.Cosmos` library is maintained as [#4159](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/4159).
