### ISSUE TITLE
How to update the connection string in TableServiceClient

### ISSUE THREAD

**Issue by Jimmy-Ahmed** [Azure/azure-sdk-for-net#39575]
### Library name and version

Azure.Data.Tables 12.8.1

### Query/Question

I am using this code

`TableServiceClient serviceClient = new TableServiceClient("ConnectionString");`

How can I update the connection string after the TableServiceClient creation?

**Comment by jsquire** [comment]
Hi @Jimmy-Ahmed.  It is not possible to update a connection string - the client is bound to that connection string at creation.  If you need to roll the connection string, you'll need to create a new client instance using the new connection string.

Assuming it is the key that you're looking to roll, that can be done if you create your client using the [TableSharedKeyCredential](https://learn.microsoft.com//dotnet/api/azure.data.tables.tablesharedkeycredential?view=azure-dotnet).  Calling it's [SetAccountKey](https://learn.microsoft.com/dotnet/api/azure.data.tables.tablesharedkeycredential.setaccountkey?view=azure-dotnet#azure-data-tables-tablesharedkeycredential-setaccountkey(system-string)) method allows the key to be rolled without creating a new client.  

For example:
```csharp
// Construct a new TableClient using a TableSharedKeyCredential.
var keyCredential = new TableSharedKeyCredential(
    accountName, 
    accountKey);

var client = new TableClient(
    new Uri(storageUri),
    tableName,
    keyCredential);

// Update the key.
keyCredential.SetAccountKey(updatedAccountKey);
```

More discussion and additional examples can be found in the [Tables authorization sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/tables/Azure.Data.Tables/samples/Sample0Auth.md#shared-key-credential).
