### ISSUE TITLE
[QUERY] Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.13.0 depending on Microsoft.AspNetCore.App framework

### ISSUE THREAD

**Issue by iamzhaoxu** [Azure/azure-sdk-for-net#39619]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.13.0

### Query/Question

I noticed that Microsoft.Azure.WebJobs.Extensions.ServiceBus library started depending on the GRPC.TOOLS package in version 5.13.0. Since GRPC.TOOLS depends on the following ASP.NET Core packages:

```
> Grpc.AspNetCore                          2.49.0
> Grpc.AspNetCore.Server                    2.49.0
> Grpc.AspNetCore.Server.ClientFactory         2.49.0
```
This means that Microsoft.Azure.WebJobs.Extensions.ServiceBus now also depends on ASP.NET Core, which requires consumers to install Microsoft.AspNetCore.App framework.

Do you think this is intentional? Should Microsoft.Azure.WebJobs.Extensions.ServiceBus depend on the ASP.NET Core framework? 

![image](https://github.com/Azure/azure-sdk-for-net/assets/1594894/d810fc45-357f-4783-944d-c8d3f958b6c8)
![image](https://github.com/Azure/azure-sdk-for-net/assets/1594894/3cb1ec3a-f9e5-4ddc-a733-fbe6f18ce4e1)
![image](https://github.com/Azure/azure-sdk-for-net/assets/1594894/faed7026-c109-45e2-a6e0-ebceae676ab8)

**Comment by JoshLove-msft** [comment]
Hi @iamzhaoxu,
This was an intentional update in order to support using the dotnet isolated worker with the service bus extension.

**Comment by iamzhaoxu** [comment]
[ServiceBusIssue.zip](https://github.com/Azure/azure-sdk-for-net/files/13210673/ServiceBusIssue.zip)
You can use this to reproduce the issue. Rebuild the solution and run the command below 
`dotnet list package --include-transitive | findstr AspNet` (working on window cmd but you can replace findstr with grep in linux and it still work)
Then you will see the dependencies 
![image](https://github.com/Azure/azure-sdk-for-net/assets/1594894/34c66e0e-28d9-4fce-82a1-03a97f74bb93)

**Comment by jviau** [comment]
This dependency is expected as it is to support the out-of-proc scenarios. While it looks like a new dependency to in-proc customers, it is not net-new. AspNetCore app framework was already brought in by the functions host. The only 'new' dependency would be the `Grpc.AspNetCore` and other `Grpc` packages.

**Comment by JoshLove-msft** [comment]
@iamzhaoxu, did you not have the dotnet SDK installed initially? That would include ASP .NET Core.

**Comment by iamzhaoxu** [comment]
Hi Josh,

We're hosting Azure web jobs in Kubernetes and expect the app to be a console application that depends only on the .NET runtime framework. However, after the recent update to Microsoft.Azure.WebJobs.Extensions.ServiceBus, the app requires the ASP.NET Core runtime, which doesn't make sense since we don't use any ASP.NET Core features.

Is it possible to make the Microsoft.Azure.WebJobs.Extensions.ServiceBus library independent of the ASP.NET Core runtime? If so, could you make the gRPC function a separate library that can be plugged into the Azure web job SDK?

This would allow us to continue using Azure web jobs with Kubernetes without having to depend on the ASP.NET Core runtime.

Thanks for your consideration.

**Comment by JoshLove-msft** [comment]
Thanks for the additional details. I will discuss this with the team and keep you updated.

**Comment by JoshLove-msft** [comment]
I discussed this with the team, and while we appreciate that it isn't a great situation for WebJobs, we are not able to invest the effort to maintain two separate libraries to avoid having the ASP .NET Core dependency pulled in. As a workaround, you can pin to the last version of the extension before the dependency was added.
