### ISSUE TITLE
[BUG] Exception when deserializing Azure.Search.Documents.SearchOptions

### ISSUE THREAD

**Issue by DavidVollmers** [Azure/azure-sdk-for-net#39630]
### Library name and version

Azure.Search.Documents 11.1.1

### Describe the bug

The bug occurs since the 24th of October. It only happens sporadically but consistently since then.

Stacktrace:
```
System.InvalidOperationException: The requested operation requires an element of type 'Number', but the target element has type 'Null'.
   at System.Text.Json.JsonDocument.TryGetValue(Int32 index, Int32& value)
   at System.Text.Json.JsonElement.GetInt32()
   at Azure.Search.Documents.SearchOptions.DeserializeSearchOptions(JsonElement element)
   at Azure.Search.Documents.Models.SearchResults`1.DeserializeAsync(Stream json, ObjectSerializer serializer, Boolean async, CancellationToken cancellationToken)
   at Azure.Search.Documents.SearchClient.SearchInternal[T](SearchOptions options, String operationName, Boolean async, CancellationToken cancellationToken)
```

As the stacktrace indicates there is a problem deserializing the `SearchOptions`. I have looked into it and the only properties which are trying to be deserialized as Number (`GetInt32`) are `skip` and `top`.

### Expected behavior

No exceptions should be thrown.

### Actual behavior

See description...

### Reproduction Steps

See description...

### Environment

- Azure hosted App Service using a Docker container based on `mcr.microsoft.com/dotnet/aspnet:6.0`

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by DavidVollmers** [comment]
A fix to this is to update to the latest version `11.4.0`. It seems to me that they were some codebreaking changes introduced on the API. I would expect older versions to still work with it or at least release a new major version and deprecate the old one...

**Comment by giulianob** [comment]
> A fix to this is to update to the latest version `11.4.0`. It seems to me that they were some codebreaking changes introduced on the API. I would expect older versions to still work with it or at least release a new major version and deprecate the old one...

Do you have a link to the PR that fixes this? I am investigating the changes on the API side to see what might have caused this.
