### ISSUE TITLE
CloudException is not deserializable via ISerializable

### ISSUE THREAD

**Issue by JohnSchmeichel** [Azure/azure-sdk-for-net#3965]
CloudException doesn't include ctor(SerializationInfo info, StreamingContext context) which prevents deserialization via ISerializable.

Newtonsoft.Json.JsonSerializationException: ISerializable type 'Microsoft.Rest.Azure.CloudException' does not have a valid constructor. To correctly implement ISerializable a constructor that takes SerializationInfo and StreamingContext parameters should be present. Path '', line 1, position 1009.

**Comment by shahabhijeet** [comment]
@dsgouda can you take this.
We need to make sure we have test coverage once you add the appropriate constructor for full desktop.

**Comment by dsgouda** [comment]
@shahabhijeet I have added a couple of test cases trying to deserialize the CloudException object on FullDesktop framework [here](https://github.com/Azure/azure-sdk-for-net/pull/4189/) but was not able to replicate this issue.
@JohnSchmeichel Could you please provide more details about your project so we can take a look.

**Comment by shahabhijeet** [comment]
Please open a new issue with repro code if you are still experiencing this issue.
