### ISSUE TITLE
ipv4

### ISSUE THREAD

**Issue by ABOOD-18** [Azure/azure-sdk-for-net#39657]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 790cbfad-547d-8120-c8a7-d50ef1ca42a3
* Version Independent ID: 32f35b21-1dc3-c036-3dec-587bafd12fa5
* Content: [AlternativeType Class (Microsoft.Azure.Management.Compute.Models) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.management.compute.models.alternativetype?view=azure-dotnet-legacy)
* Content Source: [xml/Microsoft.Azure.Management.Compute.Models/AlternativeType.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.Compute.Models/AlternativeType.xml)
* Service: **multiple**
* GitHub Login: @azure-sdk
* Microsoft Alias: **azsdkdocs**

**Comment by jsquire** [comment]
Hi @ABOOD-18.  Thank you for your feedback.   The `Microsoft.Azure.Management.Compute` package reached end-of-life on September 30, 2023 and is no longer published nor supported by Microsoft.  As a result, we're no longer considering feedback to its documentation.   Closing this out.
