### ISSUE TITLE
Does this also apply to the latest version or there might be some changes like support bacth messages Microsoft.Azure.WebJobs.Extensions.ServiceBus v5.13.3

### ISSUE THREAD

**Issue by XiaoYue2-22** [Azure/azure-sdk-for-net#39665]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a0203fd1-e905-1db5-8ec1-4a0a00d0ca4e
* Version Independent ID: 458d6304-e240-a5e9-d7cb-45573a279062
* Content: [ServiceBusOptions.MaxConcurrentSessions Property (Microsoft.Azure.WebJobs.ServiceBus) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.webjobs.servicebus.servicebusoptions.maxconcurrentsessions?view=azure-dotnet#applies-to)
* Content Source: [xml/Microsoft.Azure.WebJobs.ServiceBus/ServiceBusOptions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.WebJobs.ServiceBus/ServiceBusOptions.xml)
* Service: **azure-functions**
* GitHub Login: @azure-sdk
* Microsoft Alias: **azsdkdocs**

**Comment by jsquire** [comment]
Hi @XiaoYue2-22.  Thank you for reaching out and for your inquiry.  This option applies to v5.13.3 and any future versions of the `Microsoft.Azure.WebJobs.Extensions.ServiceBus` package, including the latest current release..
