### ISSUE TITLE
EventHubsClient handles connection string inconsistently; throws InvalidSignature exception

### ISSUE THREAD

**Issue by aggieben** [Azure/azure-sdk-for-net#3967]
While trying to diagnose an unrelated issue, I was setting up very a very simplistic sender and receiver in LinqPad.  Here's my sender:

```f#
let ehcs = "<string copied from eventhub namespace blade in azure portal>"
let entityPath = "path-name"
let connectionStringBuilder = EventHubsConnectionStringBuilder(ehcs, EntityPath = entityPath)
let connectionString = connectionStringBuilder.ToString()
connectionString.Dump("Connection String")
let client = EventHubClient.CreateFromConnectionString(connectionString)

type TestData = {
    label : string
    integer : int
    money : decimal
}   

let binarySerializer = FsPickler.CreateBinarySerializer()
let bytes = binarySerializer.Pickle { label = "new test data"; integer = 7; money = 3.44572734m }
bytes.Dump("serialized bytes")
let eventData = new EventData(bytes)
eventData.Dump("EventData")

client.SendAsync(eventData) |> Async.AwaitIAsyncResult |> Async.RunSynchronously
```

The connection string dumped by this LinqPad script is exactly what one might expect:
`Endpoint=sb://hostname/;EntityPath=path-name;SharedAccessKeyname=KEY_NAME;SharedAccessKey=KEY_VALUE;`

Note the semicolon at the end of the connection string.  This script works fine.  It serializes the test data and sends it.

Here's my receiver:

```F#
let ehcs = @"<same as above; copied from Azure portal blade>"
let entityPath = "path-name"
let connectionStringBuilder = EventHubsConnectionStringBuilder(ehcs, EntityPath = entityPath)
let connectionString = connectionStringBuilder.ToString()
connectionString.Dump("Connection String")
let generatedConnectionString = connectionStringBuilder.ToString()
generatedConnectionString.Dump("Generated Connection String")
let client = EventHubClient.CreateFromConnectionString(connectionString)
client.Dump("EventHubClient")

let runtimeInfo = client.GetRuntimeInformation()
runtimeInfo.Dump("Runtime Info")

type TestData = {
    label : string
    integer : int
    money : decimal
}

//let group = client.GetDefaultConsumerGroup()
//let partitionId = (client.GetRuntimeInformation()).PartitionIds.[0]
//let receiver = group.CreateReceiver(partitionId)
//
//while true do
//    printfn "doing"
```

The connection string dumped from this script is identical to the one dumped by the first.
In this case, you will see that I request runtime information with the client, but instead of working as expected, it throws an InvalidSignature exception:

![image](https://user-images.githubusercontent.com/1321/34280623-a8085c5e-e67e-11e7-9e80-77cd0ad6cac4.png)

For the google crawlers: the string is `MessagingException: Management operation failed. status-code: 401, status-description: InvalidSignature: The token has an invalid signature.`

When I manually set the connection string with a string literal that does not have a trailing semicolon, this works fine.

I suspect that the bug is actually in the client, not the connection string builder.

**Comment by bospoort** [comment]
I can't really tell from the code above which EventHubClient is used in either situation (there are two: one in Microsoft.Azure.EventHubs namespace, the other in Microsoft.ServiceBus.Messaging). The ConnectionString builders in those two assemblies result in a slightly different format, one containing a trailing semicolon. If you use the wrong ConnectionStringBuilder, you get the error. 

It would be good if the connection string builders handled the trailing ";" consistently for you.
