### ISSUE TITLE
Unable to use Moq to unit test the IOperationalInsightsDataClient

### ISSUE THREAD

**Issue by jeroenwo** [Azure/azure-sdk-for-net#3968]
I would like to use Moq as a mocking framework for unit testing code that uses the `IOperationalInsightsDataClient`. However, since the `QueryAsync` method on the `OperationalInsightsDataClient` implementation is not part of the interface but an extension method in `OperationalInsightsDataClientExtensions`, I cannot fake a certain result with which I can test my code.

How do you test code which implements the `QueryAsync` method?

**Comment by christothes** [comment]
Mocking `QueryWithHttpMessagesAsync` on `IOperationalInsightsDataClient` should effectively mock `QueryAsync`. Does that work for your scenario?

**Comment by shemers** [comment]
Closing this one as this is related to [#/3969](https://github.com/Azure/azure-sdk-for-net/issues/3969)
