### ISSUE TITLE
[BUG] DataFactoryResource.GetDataFactoryLinkedServices() JSON deserialization error

### ISSUE THREAD

**Issue by SuperNose** [Azure/azure-sdk-for-net#39707]
### Library name and version

Azure.ResourceManager.DataFactory 1.0.0-beta.4

### Describe the bug

Trying to get all the linked serivices from a DataFactoryResource. The foreach enumeration of the result (kind of) works for the first n-items, then a deserialization exception comes.

### Expected behavior

All the linked data-sources must be reachable in the foreach loop

### Actual behavior

At some index, the loop breaks, as the behind-the-scenes deserializer can't cast the result into a type-safe class (my guess).

ex.Message
`"Unable to cast object of type 'System.Boolean' to type 'System.String'."`

ex.StackTrace
```
"   at Azure.Core.Expressions.DataFactory.DataFactoryElementJsonConverter.Deserialize[T](JsonElement json)\r\n   at Azure.Core.Expressions.DataFactory.DataFactoryElementJsonConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)\r\n   at System.Text.Json.Serialization.Converters.CastingConverter`2.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)\r\n   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)\r\n   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)\r\n   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)\r\n   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)\r\n   at System.Text.Json.JsonSerializer.Deserialize[TV
alue](String json, JsonSerializerOptions options)\r\n   at Azure.ResourceManager.DataFactory.Models.GoogleBigQueryLinkedService.DeserializeGoogleBigQueryLinkedService(JsonElement element)\r\n   at Azure.ResourceManager.DataFactory.Models.DataFactoryLinkedServiceProperties.DeserializeDataFactoryLinkedServiceProperties(JsonElement element)\r\n   at Azure.ResourceManager.DataFactory.DataFactoryLinkedServiceData.DeserializeDataFactoryLinkedServiceData(JsonElement element)\r\n   at Azure.ResourceManager.DataFactory.DataFactoryLinkedServiceCollection.<GetAllAsync>b__9_2(JsonElement e)\r\n   at Azure.Core.PageableHelpers.PageableImplementation`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()\r\n   at Azure.Core.PageableHelpers.PageableImplementation`1.GetAsyncEnumerator(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()\r\n   at AzureReflector.AzureParsing.AzureEnumerator.EnumResourcesAsync(String resourceGroupName) in C:\\Projects\\swi
zzbits.sk\\dotnet\\AzureReflector\\AzureParsing\\AzureEnumerator.cs:line 70\r\n   at AzureReflector.AzureParsing.AzureEnumerator.EnumResourcesAsync(String resourceGroupName) in C:\\Projects\\swizzbits.sk\\dotnet\\AzureReflector\\AzureParsing\\AzureEnumerator.cs:line 70\r\n   at AzureReflector.AzureParsing.AzureEnumerator.EnumResourcesAsync(String resourceGroupName) in C:\\Projects\\swizzbits.sk\\dotnet\\AzureReflector\\AzureParsing\\AzureEnumerator.cs:line 52"

```

### Reproduction Steps

Try to get all the linked resources in a DataFactoryResource: there is somewhere a deserialization bug while iterating through the JSON internally - I can't tell where from your log message, as the actual JSON is not logged.

```
// here, the loop breaks at some index, trying interally to cast a Bool to String
await foreach (var resource in resourceGroup.GetGenericResourcesAsync())
{
  if (resource.Id.ResourceType.ToString() == "Microsoft.DataFactory/factories"
  {
    var dfRsrc = _armClient.GetDataFactoryResource(resource.Id);
    var r2 = await dfRsrc.GetAsync();
    var lsR = r2.Value.GetDataFactoryLinkedServices().GetAllAsync();

    // while looping, at some index the exception breaks the execution
    await foreach (var ls in lsR)
    {
```

### Environment

C:\Users\andy>dotnet --info

```
.NET SDK:
 Version:   7.0.402
 Commit:    791db8e2d8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.402\

Host:
  Version:      7.0.12
  Architecture: x64
  Commit:       4a824ef37c

.NET SDKs installed:
  7.0.402 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]
```

**Comment by JoshLove-msft** [comment]
This seems to indicate an issue with the definition of one of the properties in GoogleBigQueryLinkedService, or potentially with what the service is sending back for one of the properties. In particular, [RequestGoogleDriveScope](https://apiview.dev/Assemblies/Review/7c2450d1c7df4d9babdbd55f70e9ada1#) is defined as `DataFactoryElement<string>` but perhaps a bool is coming back. Does the error not occur for the first element? If it did that would indicate the type in the library is wrong. If it doesn't, it seems the service is sending back inconsistent results.
/cc @ArthurMa1978

**Comment by SuperNose** [comment]
It's happening not on the 1st element, but on the 8th or something like that => it seems like a problem of casting a bool into string. I didn't look into the sources nor decompiled them, but you should call a .ToString() on the deserialized result just to be on the safe-side ;-). TY

**Comment by JoshLove-msft** [comment]
This points to the API definition potentially being inaccurate for the property mentioned. @ArthurMa1978, are you able to confirm with the service team whether [RequestGoogleDriveScope](https://apiview.dev/Assemblies/Review/7c2450d1c7df4d9babdbd55f70e9ada1#) can contain both a bool or a string? If so, we may need to modify the swagger to represent this as `DataFactoryElement<BinaryData>`.

**Comment by JoshLove-msft** [comment]
@visingla-ms, @Frey-Wang any idea here on whether RequestGoogleDriveScope is defined correctly?

**Comment by ruowan** [comment]
@SuperNose could you please https://www.nuget.org/packages/Azure.ResourceManager.DataFactory/ 1.0.0 version. It should resolve that issue.

**Comment by ArthurMa1978** [comment]
Fixed in https://github.com/Azure/azure-rest-api-specs/pull/26507
