### ISSUE TITLE
src/SDKs/Resources/Generated  has classes for IDeploymentOperations and IDeploymentsOperations

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-sdk-for-net#3970]
The IDeploymentOperations looks like it returns operation info, while IDeploymentOperatiosn managemenes deployments.  Thezse should be either combined, or renamed so that the distinction is clear.

**Comment by dsgouda** [comment]
The `IDeploymentsOperations` and `IDeploymentOperations` are auto-generated by AutoRest based on the config file [here](https://github.com/Azure/azure-rest-api-specs/blob/e759c7386ca8c76cdbc5d4277ead9c17b006c7f9/specification/resources/resource-manager/readme.md) The REST spec must be updated to either modify the operationId [here](https://github.com/Azure/azure-rest-api-specs/blob/e759c7386ca8c76cdbc5d4277ead9c17b006c7f9/specification/resources/resource-manager/Microsoft.Resources/stable/2017-05-10/resources.json#L1875) or change the name of other operation ids from `Deployments_*` to something like `DeploymentsManagement_*`

@ravbhatnagar

**Comment by shahabhijeet** [comment]
@vivsriaus can you take a look at this as this needs update to the spec.

**Comment by hjhhh3000vitae** [comment]
The part of the code is auto-generated from Swagger definition.

In the swagger, there is two sets of operations one called `Deployments`, dealing with CRUD of Deployment, while the other is called `DeploymentOperations` dealing with CRUD of Deployment operation status.

It is not a good idea of combining two to one as they are referring to different things.

Either it is not good to rename `DeploymentsManagement` as it violates naming convention.

I am curious why the swagger definition of `DeploymentOperations` did not generate classes named like `IDeploymentOperationsOperations`.

Need attention from SDK maintainer.

**Comment by hjhhh3000vitae** [comment]
@bsiegel Please advise regarding the comment above. Code generator is generating similar class names from different definition in swagger.

**Comment by bsiegel** [comment]
Summoning @pakrym @MiYanni as maintainers of autorest.csharp generator.

**Comment by MiYanni** [comment]
Neither @pakrym and I work in the v2 autorest.csharp generator. However, from our work on v3 autorest.csharp, type names that have duplicate words are deduplicated. So, `DeploymentOperationsOperations` would become `DeploymentOperations` unless there is a naming conflict. Having duplicated words in 99% of cases doesn't add additional meaning. This was also done in autorest.powershell too. Unfortunately, I don't know how you modify type names in this generator to fix it by hand.

**Comment by alex-frankel** [comment]
@markcowl - we took a look at this issue. Is there something that is broken because of this or is it more of a style problem? We are thinking about closing it as it would mean a swagger change and could potentially be a breaking change.

cc @filizt

**Comment by alex-frankel** [comment]
closing. Let us know if this should be re-opened
