### ISSUE TITLE
[FEATURE REQ] A way to download an entire virtual folder as an archive without running down local system resourcse.

### ISSUE THREAD

**Issue by fahadash** [Azure/azure-sdk-for-net#39713]
### Library name

Azure.Storage.Blobs

### Please describe the feature.

I am writing an Azure Functions app in C# .NET 6. I have a few thousand files in an Azure Blob Folder (ok ok Virtual Folder) inside a Container. I need to download the entire Folder as a zip file. I would love for Microsoft Azure to have such a feature.

I have tried searching the internet and the only solution I found is to Download the individual blobs to a local disk or a stream and then archive it. This does not sound practical for the size of data I have and it does not work. If I download to local temp directory, One single Azure Functions run does not give me enough disk space or system resources to effectively download files simultaneously (there is also a limit of number of sockets you can open to download blobs in parallel).

If I download to a local stream and keep accumulating into an archive in the memory stream, it will eventually reach the memory capacity, not to mention you cannot add multiple blobs to a zip stream simultaneously which would increase the function run time.

What is the best way to download a Azure Blob virtual Folder as a Zip archive? with the following bases covered.

There are thousands of files, simultaneous operations should be used to make the process faster.
Working memory and disk space of an azure functions run is very limited.
Simultaneous operations adding to an archive may not work since you can only add one item at a time.
Thanks

**Comment by seanmcc-msft** [comment]
It is not possible to download blobs from Azure Storage as .zip archives, this would require substantial changes to the backend storage service itself.

A possible workaround would be to download the directory using [Azure.Storage.DataMovement.Blobs](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/storage/Azure.Storage.DataMovement.Blobs).
