### ISSUE TITLE
Policy assignment data not allowed to assign parameters

### ISSUE THREAD

**Issue by chenjeyok** [Azure/azure-sdk-for-net#39734]
To create an Policy Assignment by PolicyAssignmentCollection.CreateOrUpdateAsync, which needs an argument PolicyAssignmentData, but this class does not allow modifying it's Parameters properties, which makes it impossible to create an assignment.
``` json
 {"error":{"code":"MissingPolicyParameter","message":"The policy assignment '......' is missing the parameter(s) 'sourceOutboundIpsInKeyValue,targetName' as defined in the policy definition '........'."}}
```
here is my code snippet:
``` C#
          // prepare policy assignment data
          PolicyAssignmentData assignmentData = new PolicyAssignmentData
          {
              PolicyDefinitionId = definitionId,
              DisplayName = assignmentDisPlayName,
              Description = assignmentDesc,
              ManagedIdentity = new ManagedServiceIdentity(new ManagedServiceIdentityType("SystemAssigned")),
              Location = new AzureLocation("eastus2"),
              // Parameters = new Dictionary<string, ArmPolicyParameterValue>() // this doesn't allow assignment
          };

          var assignments = this._client.GetDefaultSubscription().GetPolicyAssignments();
          var ops = await assignments.CreateOrUpdateAsync(WaitUntil.Completed, assignmentName, assignmentData);
          var resp = ops.WaitForCompletionResponse();
```
This is the Decompiled code from Azure.ResourceManager.Resources.PolicyAssignmentData, the Parameters can't be assigned
``` c#
        /// <summary> The parameter values for the assigned policy rule. The keys are the parameter names. </summary>
        public IDictionary<string, ArmPolicyParameterValue> Parameters { get; }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1a63c7ec-62dc-b6ab-07c4-e12f9f1d8f6b
* Version Independent ID: b89290d5-1a5b-bf9a-5784-1b48debed02e
* Content: [PolicyDefinitionData Class (Azure.ResourceManager.Resources) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.resources.policydefinitiondata?view=azure-dotnet&source=docs)
* Content Source: [xml/Azure.ResourceManager.Resources/PolicyDefinitionData.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.ResourceManager.Resources/PolicyDefinitionData.xml)
* Service: **azure**
* GitHub Login: @azure-sdk
* Microsoft Alias: **azsdkdocs**

**Comment by m-redding** [comment]
Thank you for your feedback. Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
@chenjeyok thank you for reaching us, here the `Parameters` is a collection, which you can use add/remove parameter by using [methods of the collection](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.idictionary-2?view=net-7.0).

**Comment by chenjeyok** [comment]
Hi @ArthurMa1978 Thank you for the response, sorry I think it should be a bit more clear that it's not to modify this Parameters itself. The issue is that `Property or indexer 'PolicyAssignmentData.Parameters' cannot be assigned to -- it is read only`, so that I can't give an IDictory Objec to this property. It is supposed to be assignable.
