### ISSUE TITLE
Make ClientModel BinaryContent not implement IDisposable

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#39731]
Today, ClientModel's BinaryContent type implements IDisposable to support a private subtype used by the `BinaryContent .Create(IPersitableModel)` overload.  This means that every BinaryContent must be used in a `using` block in all of our docs and samples, and will complicate user code..

We should rework the `ModelMessageBody<T>` private subtype of BinaryContent so that it doesn't need to implement IDisposable, and then remove IDisposable from BinaryContent as well.

**Comment by annelo-msft** [comment]
@m-nash, the Dispose method we discussed earlier can be found here: https://github.com/Azure/azure-sdk-for-net/blob/feature/core-experiment/sdk/core/System.ClientModel/src/Message/BinaryContent.cs#L142-L150

**Comment by pallavit** [comment]
Closing this based on our past conversation.
