### ISSUE TITLE
Incorrect parameter name for exception

### ISSUE THREAD

**Issue by omon77** [Azure/azure-sdk-for-net#39745]
https://github.com/Azure/azure-sdk-for-net/blob/b39ac29dc9ae3bfcadca33c7eb12f995a5b151d7/sdk/extensions/Azure.Extensions.AspNetCore.Configuration.Secrets/src/AzureKeyVaultConfigurationExtensions.cs#L101C52-L101C72

Is:
`Argument.AssertNotNull(options, nameof(configurationBuilder));`

Should be:
`Argument.AssertNotNull(options, nameof(options));`

**Comment by JoshLove-msft** [comment]
Thanks for bringing this to our attention @omon77. We will get it fixed up and we also gratefully accept contributions!
