### ISSUE TITLE
Missing parameter scope in the PolicyAssignmentCollection.Get(String, CancellationToken) Method

### ISSUE THREAD

**Issue by chenjeyok** [Azure/azure-sdk-for-net#39751]
I'm using this `PolicyAssignmentCollection.Get(String, CancellationToken)` Method to get an assignment

 the document states ` Path /{scope}/providers/Microsoft.Authorization/policyAssignments/{policyAssignmentName}`, but this method accepts only one argument `policyAssignmentName`. Thus `Scope` is not assigned and I get this error promoting `missing parameter 'Scope'`

When I switched to REST API and feed with both argument, it works. so I think the SDK defintion is missing a parameter `Scope`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ebf8772a-b946-d248-c07e-52a6c324889b
* Version Independent ID: 5d810fbd-f147-1f5b-b3a7-e79ec483f2c9
* Content: [PolicyAssignmentCollection.Get(String, CancellationToken) Method (Azure.ResourceManager.Resources) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.resources.policyassignmentcollection.get?view=azure-dotnet#azure-resourcemanager-resources-policyassignmentcollection-get(system-string-system-threading-cancellationtoken))
* Content Source: [xml/Azure.ResourceManager.Resources/PolicyAssignmentCollection.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.ResourceManager.Resources/PolicyAssignmentCollection.xml)
* Service: **azure**
* GitHub Login: @azure-sdk
* Microsoft Alias: **azsdkdocs**

**Comment by HarveyLink** [comment]
Hi @chenjeyok , Thank you for using Azure SDK for .NET.
Not sure how you get `PolicyAssignmentCollection` class, but the scope is auto defined from where you get it.
Like when you get the collection from resource group, the scope is the resource group id.
Get it from a storage account, the scope is the storage account id.

**Comment by chenjeyok** [comment]
Thanks @HarveyLink this has solved the confusion, thank you very much!
