### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by houk-ms** [Azure/azure-sdk-for-net#39758]
### Library name and version

Azure.ResourceManager.ManagedServiceIdentities = 1.1.0

### Describe the bug

`Audiences` property in `FederatedIdentityCredentialData` is read only in the SDK, resulting in `FederatedIdentityCredentialResource` can not be created.

It should not be read-only, as it's a required parameter as shown in API.
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/msi/resource-manager/Microsoft.ManagedIdentity/stable/2023-01-31/ManagedIdentity.json#L705

### Expected behavior

the property it should be settable

### Actual behavior

it's read-only in the sdk, causing we are not able to create the resource

### Reproduction Steps

Just new a `FederatedIdentityCredentialData` to create a `FederatedIdentityCredentialResource`

```
var federatedIdentityCredential = new FederatedIdentityCredentialData
{
    IssuerUri = new Uri(issuer),
    Subject = subject,
    Audiences = new List<string>() { "api://AzureADTokenExchange" }
};
```

The sdk will tell you `Audiences` is read-only :(

### Environment

No relationship with environment

**Comment by archerzz** [comment]
@houk-ms List properties are read-only. It's by design. See https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/guidelines-for-collections#collection-properties-and-return-values

**Comment by houk-ms** [comment]
thank you @archerzz , it worked.
