### ISSUE TITLE
[BUG] ContainerAppJobExecutionCollection.GetAll or ContainerAppJobExecutionCollection.GetAllAsync returns an empty collection if insufficient permissions

### ISSUE THREAD

**Issue by githubnetworkplus** [Azure/azure-sdk-for-net#39768]
### Library name and version

Azure.ResourceManager.AppContainers 1.1.0

### Describe the bug

AppJobExecutions returns an empty collection if the client has `microsoft.app/jobs/execution/read` and not `microsoft.app/jobs/executions/read` (note the plural) permissions.

If `microsoft.app/jobs/executions/read` is granted along with `microsoft.app/jobs/execution/read` then collection returns results

If neither permission is granted then the call fails with a permissions exception as expected.

### Expected behavior

If the identify is not given `microsoft.app/jobs/executions/read` permissions then GetAllAsync() throws  a permissions error as expected 

```
ResourceIdentifier ri = new ResourceIdentifier("/subscriptions/....");
ContainerAppJobResource containerAppJobResource = _client.GetContainerAppJobResource(ri);
ContainerAppJobExecutionCollection collection = containerAppJobResource.GetContainerAppJobExecutions();
// invoke the operation and iterate over the result
await foreach (ContainerAppJobExecutionResource item in collection.GetAllAsync())
{
}
```

### Actual behavior

However if the identity is given  `microsoft.app/jobs/execution/read` (note the singular) then no permissions error is thrown, and collection.GetAllAsync() returns an empty collection rather than throwing an execption. We can see in the logging that the underlying HTTP response is 200.

```
Request [XXX] GET https://management.azure.com/subscriptions/.../resourceGroups/.../providers/Microsoft.App/jobs/c.../executions?api-version=2023-05-01
      Accept:application/json
      User-Agent:azsdk-net-ResourceManager.AppContainers/1.1.0 (.NET 7.0.13; Microsoft Windows 10.0.19045)
      client assembly: Azure.ResourceManager
info: Azure.Core[5]
      Response [ZZZ] 200 OK (00.8s)
```
This may be our understanding of the difference between read execution and read executions, but returning an empty collection based on missing permissions seems unexpected.       
      

### Reproduction Steps

To demonstrate the problem you will need a container job executing/completed at the time the code is run

```

ResourceIdentifier ri = new ResourceIdentifier("/subscriptions/....");
ContainerAppJobResource containerAppJobResource = _client.GetContainerAppJobResource(ri);
ContainerAppJobExecutionCollection collection = containerAppJobResource.GetContainerAppJobExecutions();
// invoke the operation and iterate over the result
await foreach (ContainerAppJobExecutionResource item in collection.GetAllAsync())
{
}

```

### Environment

Azure Mangement api-version=2023-05-01

dotnet --info   
.NET SDK:
 Version:   7.0.403
 Commit:    142776d834

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.403\

Host:
  Version:      7.0.13
  Architecture: x64
  Commit:       3f73a2f186

.NET SDKs installed:
  6.0.416 [C:\Program Files\dotnet\sdk]
  7.0.403 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

**Comment by m-redding** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Thank you for reaching out to us about the Azure SDK for .NET. Unfortunately, this issue is related to the service side and not the SDK side, so we are not able to help you with it. Therefore, we are closing this issue for now. If you need more assistance, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). We apologize for any inconvenience this may cause you.

We value your feedback and we want to make sure that your problem is solved. If you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.
