### ISSUE TITLE
DigitalTwins CI pipeline is broken by 39753

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-net#39787]
### Library name

Azure.ResourceManager

### Please describe the feature.

DigitalTwin CI pipeline is broken by #39753 - https://dev.azure.com/azure-sdk/public/_build/results?buildId=3239008&view=results

A couple of tests fails with following serialization issue
```
  Failed CreateDigitalTwinWithSystemAssignedIdentityAndEndpoint() [3 s]
  Error Message:
   System.Text.Json.JsonException : The object or value could not be serialized. Path: $.
  ----> System.InvalidOperationException : Cannot write a JSON value within an object without a property name. Current token type is 'StartObject'.
  Stack Trace:
```

Previous commit before #39753 passes - https://dev.azure.com/azure-sdk/public/_build/results?buildId=3239017&view=results

**Comment by lmolkova** [comment]
@archerzz @ArcturusZhang @ArthurMa1978 could someone please take a look?

**Comment by joseharriaga** [comment]
The "net - storage - ci" pipeline appears to be having the same issue:
🔗 https://dev.azure.com/azure-sdk/public/_build/results?buildId=3241642&view=results

**Comment by amnguye** [comment]
Thanks @joseharriaga !

Yeah this also started happening for the Azure.ResourceManager.Storage pipelines yesterday and we haven't made changes to this package for a while now.

This occurs for the tests that are Playback Only if that helps. It also does repo locally as well with the same error message.

**Comment by archerzz** [comment]
@lmolkova @joseharriaga @amnguye The issue should have been fixed. Could you please try again? Sorry for the breaking, we were in the middle of a fundamental library upgrade.

**Comment by joseharriaga** [comment]
Speaking for the storage CI pipeline, that one looks like it's fixed. Thank you, @archerzz !

**Comment by lmolkova** [comment]
all green  now https://dev.azure.com/azure-sdk/public/_build?definitionId=1729&_a=summary, thank you @archerzz !
