### ISSUE TITLE
Is it possible to use Newtonsoft.JsonConverterAttribute attribute for IndexDocumentsBatch types?

### ISSUE THREAD

**Issue by wist214** [Azure/azure-sdk-for-net#39792]
### Library name and version

Azure.Search.Documents

### Query/Question

I use SearchClient.IndexDocuments method to send a batch of some actions to the search index. 
I'd like to use Newtonsoft.JsonConverter<T> to serialize my int wrapper class (JobID) as a string

Class example:
```
[Serializable]
    public class JobAzureSearchable : IAzureSearchable<JobID>
    {
       
        #region Properties 

         [SimpleField(IsKey = true, IsFilterable = true)]
        public JobID JobID { get; set; }
        // other properties, etc.
     }

```

**JobID** is an int wrapper class with Newtonsoft.JsonConverter attribute.

[JobID.txt](https://github.com/Azure/azure-sdk-for-net/files/13277861/JobID.txt)

When I used Microsoft.Azure.Search nuget package it worked fine, but it doesn't with Azure.Search.Documents nuget package.
Is there a way I can override the serialization using Newtonsoft?

### Environment

.NET Framework

**Comment by m-redding** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ShivangiReja** [comment]
Yes, you can utilize Newtonsoft.JsonConverter in the Azure.Search.Documents package. For detailed information, please refer to the [documentation](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Microsoft.Azure.Core.NewtonsoftJson/README.md). Additionally, you can check out the [migration guide](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/MigrationGuide.md) for more comprehensive details.

**Comment by wist214** [comment]
Thank you for the information!
