### ISSUE TITLE
[A load balancing cycle has taken too long to complete.]

### ISSUE THREAD

**Issue by SaharnazRefaei** [Azure/azure-sdk-for-net#39802]
### Library name and version

Azure.Messaging.EventHubs.Processor 5.9.3

### Query/Question

The warning message below is frequently recieved by one of our services using Microsoft.Azure.AppConfiguration.AspNetCore V6.1.1 connected to Azure.Messaging.EventHubs.Processor 5.9.3 (Partition count:2):
{WARNING: A load balancing cycle has taken too long to complete. A slow cycle can cause stability issues with partition ownership. Consider investigating storage latency and thread pool health. Common causes are soft delete being enabled for storage and too many partitions owned. You may also want to consider increasing the 'PartitionOwnershipExpirationInterval' in the processor options. Cycle Duration: '100.92' seconds. Partition Ownership Interval '1:20' seconds. (commands). For troubleshooting information, see https://aka.ms/azsdk/net/eventhubs/exceptions/troubleshoot.}
It should be mentioned that soft delete on both blob and file service of storage account is set to **Disabled** and there are only **two** partitions.

**Comment by m-redding** [comment]
Hi @SaharnazRefaei - sorry to hear that you have been experiencing difficulties, I'm happy to try and help figure out what's going on.
I see that you're already following the recommendations on disabling soft delete and limiting the number of partitions assigned to a processor instance. Aside from that, this warning could also be an indicator of slow performance when processing events that may lead to some partitions stalling, since the runtime does not guarantee fairness for continuation scheduling. Does it take a long time for your application logic to process events?
Another thing to consider is your environment, and if it's possible there is any thread pool starvation going on, even though there are not a lot of partitions assigned to your processor. There are some additional details here and in the linked articles: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/TROUBLESHOOTING.md#too-many-partitions-are-owned

**Comment by SaharnazRefaei** [comment]
> Hi @SaharnazRefaei. Thank you for opening this issue and giving us the opportunity to assist. To help our team better understand your issue and the details of your scenario please provide a response to the question asked above or the information requested above. This will help us more accurately address your issue.
There are two more points that should be mentioned: 
1.Our service is on Azure Container App ([CPU core:1.0 , memory: 2Gi] for each partition). The maximum CPU usage for ACA during last 7 days is less than 0.66 cores. So 
![image](https://github.com/Azure/azure-sdk-for-net/assets/102354875/66805379-17e2-43da-8fba-3b008cdef6ab)
2. Does it take a long time for your application logic to process events? **Yes**. At some point the duration of processing events is too high(more than accepted time:  60,000 msec) as graph below shows:
![MicrosoftTeams-image (3)](https://github.com/Azure/azure-sdk-for-net/assets/102354875/55c413d9-2b93-406e-aa82-8ce1f4807617)
**SO** 
Apparently our service should not encounter to long load balancing time exception. I'm clueless why it happens?! Let me know if you need more information.

**Comment by IhorCo** [comment]
It looks like the first call to Storage account takes too long and s cancelled after 100 seconds. The next one is successful and takes 23 ms. Is not too long to wait 100 seconds just to update offset in Storage account?

**Comment by m-redding** [comment]
@SaharnazRefaei  I would guess that the storage account access is probably the issue. The load balancing cycle needs to access the checkpoint stored in the blob, so if accessing the storage account is taking a long time then that would lead to load balancing cycles taking a long time, which can cause frequent partition ownership changes which can really decrease performance. In terms of debugging why accessing the storage account is taking so long, one other thing you could try to check is if "Blob versioning" is turned on? https://learn.microsoft.com/en-us/azure/storage/blobs/versioning-overview

**Comment by SaharnazRefaei** [comment]
> Hi @SaharnazRefaei. Thank you for opening this issue and giving us the opportunity to assist. To help our team better understand your issue and the details of your scenario please provide a response to the question asked above or the information requested above. This will help us more accurately address your issue.
**Response:**
In our system configuration, both _blob storage_ and _blob versioning_ are currently set to `Disabled`. However, we are using a single container for two event hubs. It is recommended to **use a unique container for each Event Hub and consumer group combination**. Therefore, we plan to modify the system to follow a one container per event hub structure and will monitor the results. We will provide feedback soon.

**Comment by SaharnazRefaei** [comment]
> > Hi @SaharnazRefaei. Thank you for opening this issue and giving us the opportunity to assist. To help our team better understand your issue and the details of your scenario please provide a response to the question asked above or the information requested above. This will help us more accurately address your issue.

**Response:**
In our system configuration, both _blob storage_ and _blob versioning_ are currently set to `Disabled`. However, we are using a single container for two event hubs. It is recommended to **use a unique container for each Event Hub and consumer group combination**. Therefore, we plan to modify the system to follow a one container per event hub structure and will monitor the results. We will provide feedback soon.

**Comment by SaharnazRefaei** [comment]
we finally resolved the issue with access to the storage account by configuring both the event hub and the storage account to be in the same region. This ensured that the warning 'A load balancing cycle has taken too long to complete' did **not** occur in our system. Consequently, I am closing this issue.
