### ISSUE TITLE
Microsoft.Azure.Management.ApiManagement on NuGet has totally different class members.

### ISSUE THREAD

**Issue by leftler** [Azure/azure-sdk-for-net#3981]
Using https://www.nuget.org/packages/Microsoft.Azure.Management.ApiManagement/3.4.0-preview (which has a publish date earlier than the inititial check in of https://github.com/Azure/azure-sdk-for-net/tree/psSdkJson6/src/SDKs/ApiManagement) and looking in to `Microsoft.Azure.Management.ApiManagement.IUserOperations` I see methods like `CreateAsync` and `DeleteAsync`. 

If I look at https://github.com/Azure/azure-sdk-for-net/blob/3bd40fa47229b3a9163ffefc05cbc5f591c85f51/src/SDKs/ApiManagement/Management.ApiManagement/Generated/IUserOperations.cs I see methods like `CreateOrUpdateWithHttpMessagesAsync` or `DeleteWithHttpMessagesAsync`.

Is the 3.4.0-preview NuGet package very out of date or am I using the wrong package to get the .NET wrapper for these Api Management api's?

**Comment by dsgouda** [comment]
@leftler The package version published from the psSdkJson6 codebase ([here](https://github.com/Azure/azure-sdk-for-net/blob/3bd40fa47229b3a9163ffefc05cbc5f591c85f51/src/SDKs/ApiManagement/Management.ApiManagement/Generated/IUserOperations.cs)) is 4.0.0-preview which, as expected has the `CreateOrUpdateWithHttpMessagesAsync` or `DeleteWithHttpMessagesAsync` methods in `Microsoft.Azure.Management.ApiManagement.IUserOperations` interface.
The `3.4.0-preview` version was published from the codebase [here](https://github.com/Azure/azure-sdk-for-net/blob/master/src/ResourceManagement/ApiManagement/ApiManagementManagement/Generated/IUsersOperations.cs)

You could upgrade to `4.0.0-preview` version to see this code.

**Comment by dsgouda** [comment]
If you have any further issues while using the package, kindly reopen the issue and provide detailed repro steps.
