### ISSUE TITLE
[QUERY] How to Mock Azure.ResourceManager.ManagedServiceIdentities.UserAssignedIdentityData

### ISSUE THREAD

**Issue by baryoloraul** [Azure/azure-sdk-for-net#39812]
### Library name and version

Azure.ResourceManager.ManagedServiceIdentities 1.1.0

### Query/Question

I cannot find a way to mock this model type named **UserAssignedIdentityData** returned by the Azure.ResourceManager.ManagedServiceIdentities SDK. According to the [Mocking](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/core-readme?view=azure-dotnet#mocking) documentation there should be a **ModelFactory** type for this. The properties of this object are read only and not marked as virtual. Any suggestion?

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.416
 Commit:    db3bc4a6c6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.416\

Host:
  Version:      7.0.13
  Architecture: x64
  Commit:       3f73a2f186

**Comment by pallavit** [comment]
Thank you for reporting the issue. Tagging and routing it to the member best able to assist you.

@ArthurMa1978 looking at the source history I believe mocking behavior was added after the SDK release - https://github.com/Azure/azure-sdk-for-net/commit/124b8a2b79ba48ab144078bf446cc2086030330d but wanted to confirm with you.

**Comment by ArthurMa1978** [comment]
Hey @baryoloraul , for the MSI there only the [latest beta support model factory](https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.managedserviceidentities.models.armmanagedserviceidentitiesmodelfactory?view=azure-dotnet-preview&viewFallbackFrom=azure-dotnet), you can try this beta version and wait for the next stable release.
