### ISSUE TITLE
[FEATURE REQ] Update docs to clarify how/where/when AZURE_CLIENT_ID is needed for ManagedIdentityCredential

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#39832]
### Library name

Azure.Identity

### Please describe the feature.

Should https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/identity/Azure.Identity#environment-variables have an entry for MIC?

Can we clarify whether `AZURE_CLIENT_ID` is only needed for user-assigned managed identity and you can skip it if you're doing system-assigned managed identity?  Ditto for the ref docs at https://learn.microsoft.com/en-us/dotnet/api/azure.identity.managedidentitycredential.-ctor?view=azure-dotnet#azure-identity-managedidentitycredential-ctor(system-string-azure-identity-tokencredentialoptions).

**Comment by christothes** [comment]
`AZURE_CLIENT_ID` is never _needed_ but it is the baseline value used for the managed Identity client Id only in the case of `DefaultAzureCredential`. Setting the `ManagedIdentityClientId ` option overrides that though. 

https://github.com/Azure/azure-sdk-for-net/blob/bfaf0bcf093b79215257ef21d75f84a8fdfb58d5/sdk/identity/Azure.Identity/src/Credentials/DefaultAzureCredentialOptions.cs#L196

Regarding the stand alone `ManagedIdentityCredential`, there is no scenario in which AZURE_CLIENT_ID is used.
