### ISSUE TITLE
[BUG] Azure Maps Routing - SectionFilter in RouteDirectionOptions does not support multiple SectionTypes

### ISSUE THREAD

**Issue by goldsparksolutions** [Azure/azure-sdk-for-net#39869]
### Library name and version

Azure.Maps.Routing 1.0.0-beta.2

### Describe the bug

The documentation for the Get Route Directions API states that multiple `SectionType` can be provided. However, there is no way to provide multiple values to `SectionFilter` in the `RouteDirectionOptions`. I would expect this property to be a list.

### Expected behavior

Multiple `SectionType` can be assigned using a `List<SectionType>`:
```
var options = new RouteDirectionOptions {
    SectionFilter = new List<SectionType> {
        SectionType.Ferry,
        SectionType.TravelMode
    }
};
```

### Actual behavior

Only one `SectionType` can be assigned:
```
var options = new RouteDirectionOptions {
    SectionFilter = SectionType.TravelMode
};
```

### Reproduction Steps

1. Create a new `RouteDirectionOptions` object:
```
var options = new RouteDirectionOptions();
```
2. Look at the `SectionFilter` property in the object.

**Comment by dubiety** [comment]
Hi @goldsparksolutions,

Sorry for waiting so long. We've fixed this issue in our latest [Azure.Maps.Routing v1.0.0-beta.3](https://www.nuget.org/packages/Azure.Maps.Routing). I'll close this issue now. Welcome to try and give us feedback.
