### ISSUE TITLE
`initialVisibilityDelay` has undocumented limit of 7 days

### ISSUE THREAD

**Issue by papadeltasierra** [Azure/azure-sdk-for-net#39872]
As per summary, testing indicates that `initialVisibilityDelay` has a limit of 7 days.  Attempting to set a limit any greater results in this Exception:

```
System.ArgumentOutOfRangeException: The argument 'initialVisibilityDelay' is larger than maximum of '7.00:00:00' (Parameter 'initialVisibilityDelay')
   at Microsoft.WindowsAzure.Storage.Core.Util.CommonUtility.AssertInBounds[T](String paramName, T val, T min, T max)
   at Microsoft.WindowsAzure.Storage.Queue.CloudQueue.AddMessageImpl(CloudQueueMessage message, Nullable`1 timeToLive, Nullable`1 initialVisibilityDelay, QueueRequestOptions options)
   at Microsoft.WindowsAzure.Storage.Queue.CloudQueue.AddMessageAsync(CloudQueueMessage message, Nullable`1 timeToLive, Nullable`1 initialVisibilityDelay, QueueRequestOptions options, OperationContext operationContext, CancellationToken cancellationToken)
   at Microsoft.WindowsAzure.Storage.Queue.CloudQueue.AddMessageAsync(CloudQueueMessage message, Nullable`1 timeToLive, Nullable`1 initialVisibilityDelay, QueueRequestOptions options, OperationContext operationContext)
   ...
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a617559f-7492-8231-4ca9-26b770fe12d3
* Version Independent ID: 7deda058-fa45-0e73-2e6c-3a74e3527eb3
* Content: [CloudQueue.AddMessageAsync Method (Microsoft.Azure.Storage.Queue) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.queue.cloudqueue.addmessageasync?view=azure-dotnet-legacy#microsoft-azure-storage-queue-cloudqueue-addmessageasync(microsoft-azure-storage-queue-cloudqueuemessage-system-nullable((system-timespan))-system-nullable((system-timespan))-microsoft-azure-storage-queue-queuerequestoptions-microsoft-azure-storage-operationcontext))
* Content Source: [xml/Microsoft.Azure.Storage.Queue/CloudQueue.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Storage.Queue/CloudQueue.xml)
* Service: **storage**
* GitHub Login: @azure-sdk
* Microsoft Alias: **azsdkdocs**

**Comment by dimbleby** [comment]
related https://github.com/Azure/durabletask/issues/1006

**Comment by seanmcc-msft** [comment]
This issue is in the legacy .NET Queues SDK, which is deprecated and no longer supported.  We highly recommend upgrading to [Azure.Storage.Queues](https://www.nuget.org/packages/Azure.Storage.Queues), which is a different NuGet package.

Here is our [migration guide](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs/AzureStorageNetMigrationV12.md), which is for the Blobs package, but the sample principles apply.  Samples can be found [here](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/storage/Azure.Storage.Queues/samples).

**Comment by papadeltasierra** [comment]
Thanks for the info.  I should have said we didn't hit this directly, rather we were using another package that sat atop this and it took some debugging to confirm that we had not actually written a bug ourselves.  That package didn't handle this Exception nicely, resulting in a process that "span" continually attempting the request.  Can the documentation at least be updated to make clear that the API is deprecated and the limit documented to aid debugging for anyone else stumbling across this issue in future?
