### ISSUE TITLE
[QUERY] Not Seeing TraceId in LogAnalytics traces for outgoing http client calls when using  OpenTelemetry.Instrumentation.Http

### ISSUE THREAD

**Issue by joebeernink** [Azure/azure-sdk-for-net#39877]
### Library name and version

Azure.Monitor.OpenTelemetry.Exporter 1.0.0

### Query/Question

I'm using OpenTelemetry.Instrumentation.Http to instrument my calls to a web service. On the service side, I'm using OpenTelemetry.Instrumentation.AspNetCore to instrument the service. 

If I log the traces for the **outgoing calls** to the console using the OpenTelemetry.Exporter.Console, I see the TraceId.
But if I log the traces using "Azure.Monitor.OpenTelemetry.Exporter" Version="1.0.0", the trace id **does not appear in App Insights**.

If, however, I use the "OpenTelemetry.Instrumentation.AspNetCore" to log incoming calls to my service, I see the traceId in both the console and the AppInsights logs.

I previously opened this issue with the open telemetry group, thinking the issues were in the OpenTelemetry.Instrumentation.Http library, but since the console is showing the results, I'm thinking the issue is in the Azure.Monitor.OpenTelemetry.Exporter
https://github.com/open-telemetry/opentelemetry-dotnet/issues/5035

**Comment by vishweshbankwar** [comment]
@joebeernink Could you share the output from console where it shows the traceId?

**Comment by joebeernink** [comment]
Here's a sample output:

Activity.TraceId:            b0981bb642d7288fc00f0d71d6d9d9b5
Activity.SpanId:             fa9d385c68d8032b
Activity.TraceFlags:         Recorded
Activity.ActivitySourceName: System.Net.Http
Activity.DisplayName:        HTTP GET
Activity.Kind:               Client
Activity.StartTime:          2023-11-09T19:50:47.7067746Z
Activity.Duration:           00:00:00.0173765
Activity.Tags:
    http.scheme: http
    http.method: GET

**Comment by vishweshbankwar** [comment]
@joebeernink Thanks! - The screenshot you shared in https://github.com/open-telemetry/opentelemetry-dotnet/issues/5035 is from traces table which contains logs. For activity you need to check request(incoming) or dependency(outgoing) table. 

You should see OperationId(traceId) and ParentSpanId(SpanId) populated on logs for an outgoing call if they are within the same trace. The properties are not controlled by exporter, exporter simply exports what it gets from the LogRecord.

**Comment by joebeernink** [comment]
Ah, Thanks! I did not know that about those other tables. I'm sure it's for backwards compat or something...

**Comment by vishweshbankwar** [comment]
> Ah, Thanks! I did not know that about those other tables. I'm sure it's for backwards compat or something...

👍 Request and Dependency tables are not for backward compatibility. [Traces](https://opentelemetry.io/docs/concepts/signals/traces/) from OpenTelemetry (Activity in .NET) are exported to them. [Logs](https://opentelemetry.io/docs/concepts/signals/logs/) from OpenTelemetry (ILogger in .NET) are exported to `Trace`  table.
