### ISSUE TITLE
An unexpected error was encountered while trying to access Azure Storage

### ISSUE THREAD

**Issue by Manoj10decoder** [Azure/azure-sdk-for-net#39898]
### Library name and version

Azure.ResourceManager.Sql

### Query/Question

I using the Azure.ResourceManager.Sql package to export the SQL database to the Storage account. When I try to export the small size of the database it works perfectly but when I export the large size of the database I get the below error.

Note: I using Private link endpoints

**'The ImportExport operation with Request Id 'b88535fe-deed-483f-9e92-xxxxxx' failed due to 'An unexpected error was encountered while trying to access Azure Storage: An error occurred while sending the request. An error occurred while sending the request. Unable to connect to the remote server A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 10.0.0.0:443'.
Status: 200 (OK)
ErrorCode: ImportExportJobError

Content:
{"name":"b88535fe-deed-483f-9e92-045e31xxxxxx","status":"Failed","startTime":"2023-11-10T13:12:45Z","error":{"code":"ImportExportJobError","message":"The ImportExport operation with Request Id 'b88535fe-deed-483f-9e92-045e313433b4' failed due to 'An unexpected error was encountered while trying to access Azure Storage: An error occurred while sending the request. An error occurred while sending the request. Unable to connect to the remote server A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 10.0.0.0:443'."}}

Headers:
Cache-Control: no-cache
Pragma: no-cache
Retry-After: 15
x-ms-request-id: 0b652489-0b2a-42ef-8b7e-60bbac58b802
Server: Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-reads: REDACTED
x-ms-correlation-request-id: REDACTED
x-ms-routing-request-id: REDACTED
Strict-Transport-Security: REDACTED
X-Content-Type-Options: REDACTED
Date: Fri, 10 Nov 2023 13:12:50 GMT
Content-Length: 651
Content-Type: application/json; charset=utf-8
Expires: -1**

This is my code
`ArmOperation<ImportExportOperationResult> d = await s.ExportAsync(Azure.WaitUntil.Completed, databaseExportDefinition);`

Please anyone help me to solve this it is a pretty urgent task. 

### Environment

.NET 6

**Comment by m-redding** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Manoj10decoder** [comment]
> Thank you for your feedback. Tagging and routing to the team member best able to assist.

Thanks, A Quick solution will save my day ✌

**Comment by DreamCatcher13** [comment]
Today I encounter the same error, using the Private link. DB size is around 26 GB,  database and storage account are in different subscriptions.

**Comment by HarveyLink** [comment]
Since small DB operation was succeeded, this may be a service side issue.

**Comment by Manoj10decoder** [comment]
> Since small DB operation was succeeded, this may be a service side issue.

@HarveyLink I have tried today, I can successfully export my database for the first time using the Private endpoint connection and then I tried a second time export operation failed (My database size is 23MB). 

This is the error message I got.

An unexpected error was encountered while trying to access Azure Storage: An error occurred while sending the request. An error occurred while sending the request. Unable to connect to the remote server A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 10.8.0.24:443

**Comment by HarveyLink** [comment]
Hey @Manoj10decoder  , thank you for reaching out to us about the Azure SDK for .NET. Unfortunately, this issue is related to the service side and not the SDK side, so we are not able to help you with it. Therefore, we are closing this issue for now. If you need more assistance, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). We apologize for any inconvenience this may cause you.

We value your feedback and we want to make sure that your problem is solved. If you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.
