### ISSUE TITLE
[BUG] ADX Cluster principal fails to assign role.

### ISSUE THREAD

**Issue by songwillow** [Azure/azure-sdk-for-net#39891]
### Library name and version

Pulumi Azure Native

### Describe the bug

Whenever I do a kusto role assignment to an azure container app's identity, I randomly get this error

error: resource partially created but read failed autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The resource with identifier '/subscriptions/***/resourceGroups/***/providers/Microsoft.Kusto/Clusters/***//Databases/***//PrincipalAssignments/dedb-app-admin-<container-name>-role' is not found.": Code="ResourceNotFound" Message="[NotFound] Failed to run add principal assignment action for service Engine-***. AAD principal was not found."

Then after waiting a few minutes when I re-run my script it'll be able to assign it properly

What's weird is if I do a regular rbac assignment to any other azure resources (keyvault, cognitive search) the assignment on the same run as the first (when I get the error from kusto) it assigns it successfuly.

I suspect that it could be a race condition but doesn't explain how a regular rbac assignment work but not a kusto role assignment.

Log from azure

{
    "authorization": {
        "action": "Microsoft.Kusto/clusters/databases/principalAssignments/write",
        "scope": "/subscriptions/***/resourceGroups/***/providers/Microsoft.Kusto/clusters/***/databases/***/principalAssignments/***"
    },
    "caller": "aa21adab-abbe-4e3b-9589-0b74d8880676",
    "channels": "Operation",
    "claims": {
        "aud": "https://management.azure.com",
        "iss": "https://sts.windows.net/***/",
        "iat": "1699471603",
        "nbf": "1699471603",
        "exp": "1699475503",
        "aio": "E2VgYNh6VOL7lMLICvffn2dKegXoAgA=",
        "appid": "66758847-bffc-4ded-941f-14c688be7cc0",
        "appidacr": "1",
        "groups": "9efcdbbe-4c3e-4399-a6e1-c0405bc6a4fd,e39c6101-7c7b-4648-810d-e01d718da736,5cea7e0f-6be8-49c7-9ff2-18fe5545ce79,0d476f11-333f-4119-a352-0cd1ae5106d5,bea9fd13-526c-41ea-b150-b062d3d999d1,a00d3217-8b7b-4f02-a2d1-825712ccd870,9192801a-5fc8-44b5-b849-5061e983cbfd,0c51d71b-1d2b-4b17-96d1-055bb11434c4,88890d20-9aa7-4808-a810-2dc784ea83cf,48213020-aa71-4566-880e-203082bf53b7,b76fad27-2124-4d42-8251-80d2351ccfbd,67e4e728-1e2f-4966-ab79-6d8e79d06b70,b4b6162d-d142-40d1-bc87-f10a0d7e1e65,32a45e36-ccb8-4ade-97b3-2dd17bde701f,0ef15f40-e134-4438-8841-dcd8ed265234,12289f40-8e13-447b-98dc-3fca5b703a02,1976bc41-bef6-48a2-b6f1-5dc43dd5cbf1,36e9e541-09cc-41a8-bed6-3841ed1e6373,c9a39a44-850a-487c-9ba0-0c6baf9c65f0,b5d10a46-4acc-4a21-9cd5-ed873ca23dc8,3005ee47-7c03-4303-b350-5ecef7cc5c14,224df24e-8ca6-4dc3-bf4e-2b4d1d3f46e5,235d8b4f-86b7-435e-9763-4cf2d69771b5,d01bf756-fc7f-445c-8a4b-0b3699f82da0,c3f21058-334a-4c90-bb7b-7f4b413b3065,598ea05b-6c38-4353-b3a0-e87c37b880e6,ad07ec60-61ad-4cd8-912a-396df2b695c1,c9b8ac63-f8d2-40f4-883e-eedd9527bb2d,6bf63164-8534-49f6-b161-77f39fbf3bc0,c3087467-dcbf-414a-873b-d14782029a55,c08c426d-3f47-4efb-a8d0-31bad2cd3a63,0c8f2477-beb6-443c-86f7-b42835b1ac3f,362ced77-742f-4518-af01-b4796c1474ae,49006c7b-bf2a-4b62-96d3-ea67a7189acb,ad4ab87c-3c99-4d3b-98ea-0cd122319995,8365647d-0218-485d-b4f4-9b0907173558,a950c87d-81f3-44a4-91ce-e4b27e97805d,e639867e-26cf-402c-9810-7e882dcd6b16,22e27180-f484-49e6-8213-069e94d72d90,7a6c7182-846c-4b41-a461-a38dae1deeaf,eab5ea83-b405-4f7e-abcc-b52756cd37fd,edf23284-cbfb-4ca5-bf83-7c3beaa29c2c,88b3fe8d-9773-4f84-ae98-7afb8d9e861a,dddc008e-471a-491a-85ca-09903eadc94a,d992dc93-673c-4df2-a4f7-a3270e71db52,664c8296-805c-41de-acb3-b18aa16fb5c7,8d206599-4f35-4ca1-836e-bd8cb987e421,09f09d99-b1a1-4bff-a1c7-93df1bc09261,79bf849c-11db-45dd-9b2b-eb6bdc1120bb,027abfa0-cad3-45a2-8c6f-74e060d9bb38,ea2f00a5-2c21-47d9-9eef-f96f2f049401,71dd90ab-66f0-44f4-83ba-7d50ef567d37,cea409b4-a536-48d0-a026-f5eb1f5652e2,6f4d1db4-9b7f-49ad-bc31-7b8a8b9d7da5,1def3bb4-1bd5-4204-9ca8-0587a2b41ecb,adb6fab4-b351-4473-9363-2734868bfa47,4f2a18bb-d554-4f1e-8f1b-96b7010f4fcf,969b96bf-a5a3-4ca9-a8f4-b1d52a216ed2,218fa9bf-be5b-461a-87d2-5d10cecb3091,9b71a6c4-4796-4fa6-8b08-ba8bcc73e729,bbbe8bc5-7741-41db-8fc9-3b65ddab4265,cdda26c6-6648-4470-bb5e-473bd04d30ef,7edff7c7-88dd-4e55-a1f9-ca94266411cb,a90e6ec9-5cd0-45c7-966d-b2ef3580cf3c,0e9b72c9-4edb-4c7b-b4d3-395457a69be1,895a66cc-b18d-45c8-839c-ff4cd8e72bf2,b2aa77cc-713b-4ca3-a583-27c6abe46b9f,8a75ddce-8d15-4e21-be74-63b66b55d2dc,56c5cdd8-ddce-41e3-8a39-d6891421804b,ab1805e3-a9a2-436d-b5a6-12fbbb0baff8,da436ae6-f20a-4a7a-b33a-05a99e82806e,079852e8-9e9d-4d67-85ec-5a9896ee25fc,74a1c2e8-325e-481c-93dd-88bb61bee97b,66a9eaec-a847-4362-a697-bbc2a8679232,1526dbf2-06da-48ee-ab6c-359d310730cd,84af1ef3-1434-4196-b3d2-bdf381767e91,213c8bf3-3b72-49e3-a2cf-832f4e0206f3,e1d128f4-353f-495e-a5ff-2144570141cb,5dc56af5-0278-4499-98c0-9ef4bb668c89,eca158f6-6548-49c2-937d-e176f8dc94f7,99f21cfa-478e-44b6-8d7a-178233d3b832,fc6aeffa-18fc-44fc-8bc2-93e1a26aef21",
        "http://schemas.microsoft.com/identity/claims/identityprovider": "https://sts.windows.net/***/",
        "idtyp": "app",
        "http://schemas.microsoft.com/identity/claims/objectidentifier": "aa21adab-abbe-4e3b-9589-0b74d8880676",
        "rh": "0.AWYA0WYx1KHCJk-iE_Yg26E6uEZIf3kAutdPukPawfj2MBNmAAA.",
        "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier": "aa21adab-abbe-4e3b-9589-0b74d8880676",
        "http://schemas.microsoft.com/identity/claims/tenantid": "***",
        "uti": "6mmN-FZgMU64uOFswPKDAA",
        "ver": "1.0",
        "xms_cae": "1",
        "xms_tcdt": "1422596418"
    },
    "correlationId": "2d531a63-a1d1-4160-9daa-d38cba1266f9",
    "description": "",
    "eventDataId": "10fad8b6-5fe5-4bf3-a6cb-fa28e3c1b12e",
    "eventName": {
        "value": "EndRequest",
        "localizedValue": "End request"
    },
    "category": {
        "value": "Administrative",
        "localizedValue": "Administrative"
    },
    "eventTimestamp": "2023-11-08T19:32:00.5888299Z",
    "id": "/subscriptions/***/resourceGroups/***/providers/Microsoft.Kusto/clusters/***/databases/***/principalAssignments/***/events/10fad8b6-5fe5-4bf3-a6cb-fa28e3c1b12e/ticks/638350687205888299",
    "level": "Error",
    "operationId": "cac0a43c-8f7c-4266-b871-bdbb2cd3b904",
    "operationName": {
        "value": "Microsoft.Kusto/clusters/databases/principalAssignments/write",
        "localizedValue": "Write a database principal assignments resource"
    },
    "resourceGroupName": "***",
    "resourceProviderName": {
        "value": "Microsoft.Kusto",
        "localizedValue": "Microsoft.Kusto"
    },
    "resourceType": {
        "value": "Microsoft.Kusto/clusters/databases/principalAssignments",
        "localizedValue": "Microsoft.Kusto/clusters/databases/principalAssignments"
    },
    "resourceId": "/subscriptions/***/resourceGroups/***/providers/Microsoft.Kusto/clusters/***/databases/***/principalAssignments/***",
    "status": {
        "value": "Failed",
        "localizedValue": "Failed"
    },
    "subStatus": {
        "value": "",
        "localizedValue": ""
    },
    "submissionTimestamp": "2023-11-08T19:36:59Z",
    "subscriptionId": "***",
    "tenantId": "***",
    "properties": {
        "statusMessage": "{\"status\":\"Failed\",\"error\":{\"code\":\"ResourceOperationFailure\",\"message\":\"The resource operation completed with terminal provisioning state 'Failed'.\",\"details\":[{\"code\":\"ResourceNotFound\",\"message\":\"[NotFound] Failed to run add principal assignment action for service Engine-***. AAD principal was not found.\"}]}}",
        "eventCategory": "Administrative",
        "entity": "/subscriptions/***/resourceGroups/***/providers/Microsoft.Kusto/clusters/***/databases/***/principalAssignments/***",
        "message": "Microsoft.Kusto/clusters/databases/principalAssignments/write",
        "hierarchy": "***/***/***"
    },
    "relatedEvents": []
}

I saw this post which is very similar to what I'm experiencing
https://github.com/Azure/azure-sdk-for-net/issues/16416

### Expected behavior

Kusto role assignment should behave exactly like rbac role assigment.

### Actual behavior

Kusto role assignment is returning 404 on identity that exists since it was able to assign rbac assignment.

### Reproduction Steps

Create container app and assign kusto role assignment right after.

**Comment by m-redding** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi @songwillow , thank you for reaching out to us about the Azure SDK for .NET. Unfortunately, this issue is related to the service side and not the SDK side, so we are not able to help you with it. Therefore, we are closing this issue for now. If you need more assistance, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). We apologize for any inconvenience this may cause you.

We value your feedback and we want to make sure that your problem is solved. If you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.
