### ISSUE TITLE
[FEATURE REQ] GetGenericResourcesAsync for ManagementGroupResource

### ISSUE THREAD

**Issue by kalbert312** [Azure/azure-sdk-for-net#39982]
### Library name

Azure.ResourceManager.Resources 1.6.0

### Please describe the feature.

I'm working on code for ARM deployments and am trying to convert Track 1 SDK calls to Track 2. I need to convert a method that gets a resource listing under a scope. The scope can be either a resource group, subscription, or management group. `ResourceGroupResource` and `SubscriptionResource` both have an API method `GetGenericResourcesAsync` but this appears to be missing on `ManagementGroupResource`. It would be great to get this functionality on a `ManagementGroupResource`.

**Comment by HarveyLink** [comment]
Hi @kalbert312 .Thank you for using Azure SDK for .NET.
We will have a `ManagementGroupResource` onboard at next release, but there is not `GetGenericResourcesAsync` operatipon for this resource.
Our SDK is auto generated from the exsiting swagger, there isn't such API in the RESTApi.
