### ISSUE TITLE
Can't find "Create Azure Authentication Events Trigger Project" command from Quick Start for Visual Studio Code

### ISSUE THREAD

**Issue by adamsosinski** [Azure/azure-sdk-for-net#40013]
Hi,

I'm trying to check the usage of Authentication Events triggered functions for providing additional claims for access tokens. However, when trying to set up Azure Function from Quickstart I can't find the command "Create Azure Authentication Events Trigger Project" available from the command palette.

I have the Azure Functions and C# extension installed

Please let me know if I'm missing some step.

Thanks,

Adam

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6926ae0b-e5e2-ca64-4c09-e298431716d8
* Version Independent ID: cbf77984-6ad5-d1c0-40fb-5436caf5277a
* Content: [Authentication events trigger for Azure Functions client library for .NET - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/microsoft.azure.webjobs.extensions.authenticationevents-readme?view=azure-dotnet-preview)
* Content Source: [api/overview/azure/preview/microsoft.azure.webjobs.extensions.authenticationevents-readme.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/preview/microsoft.azure.webjobs.extensions.authenticationevents-readme.md)
* Service: **entra**
* GitHub Login: @azure-sdk
* Microsoft Alias: **azsdkdocs**

**Comment by jsquire** [comment]
//fyi:  @HarmanDhunna, @hakimms

**Comment by HarmanDhunna** [comment]
Hi @adamsosinski, 

Appreciate you checking out our Authentication Events Trigger NuGet!

At the moment we do not have a full support for QuickStart for Authentication Events Trigger. This is definitely something on our radar for the future, but not for our current goal of GA release.

Since we are still in beta and support for the QuickStart is a little far out, I am more than happy to help you set up the NuGet for your custom extension in the interim. 

~harman

**Comment by adamsosinski** [comment]
Hi @HarmanDhunna,

Great hearing that you can help me with setting it all up. What I have figured out for now is that I need to probably, register  AuthenticationEventWebJobsStartup on my Azure Function like this:

```C#
var host = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults()
    .ConfigureServices(services => {
        services.AddApplicationInsightsTelemetryWorkerService();
        services.ConfigureFunctionsApplicationInsights();
    })
    .ConfigureWebJobs(configure =>
    {
        configure.UseWebJobsStartup<AuthenticationEventWebJobsStartup>();
    })
    .Build();

host.Run();
```

But right now, I'm not sure how I can register a code that will be called when the Authentication Event happens. To give you an overview, I would like to add additional claims to the returned token.

My thinking is that I would need to derive from TokenIssuenceAction or use ProvideClaimsForToken class somehow.

I would appreciate any advises or step-by-step guide on what needs to be added to the code, so that I would be able to achieve my goal.

Thanks,

Adam

**Comment by adamsosinski** [comment]
Hi,

Can I expect any update on that one?

Thanks,

Adam

**Comment by HarmanDhunna** [comment]
Sorry for the delayed response. Most of us were out of the office due to Thanksgiving holidays. 

Which Azure Function Trigger are you trying to set up? Currently we are only supporting HTTP Trigger. 

Below is some sample code for setting up azure function app running .NET v6.0

```csharp

using System;
using System.Collections.Generic;
using System.Threading.Tasks;

using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.AuthenticationEvents;
using Microsoft.Azure.WebJobs.Extensions.AuthenticationEvents.Framework;
using Microsoft.Azure.WebJobs.Extensions.AuthenticationEvents.TokenIssuanceStart;
using Microsoft.Azure.WebJobs.Extensions.AuthenticationEvents.TokenIssuanceStart.Actions;
using Microsoft.Extensions.Logging;

namespace CustomExtensions.AuthenticationEvents.onTokenIssuanceStart
{
    public static class OnTokenIssuanceStartv2
    {
        /// <summary>The entry point for the Azure Function</summary>
        /// <param name="request">Strongly Typed request data for a token issuance start request</param>
        /// <param name="log">Logger</param>
        /// <returns>The augmented token response or error.</returns>
        [FunctionName("onTokenIssuanceStartv2")]
        public async static Task<AuthenticationEventResponse> Run([AuthenticationEventsTrigger] TokenIssuanceStartRequest request, ILogger log)
        {
            try
            {
                //Is the request successful and did the token validation pass.
                if (request.RequestStatus == RequestStatusType.Successful)
                {
                    var content = new Dictionary<string, string>()
                    {
                        {"SomeInfo", "SomeValue" }
                    };

                    List<ProvideClaimsForToken> claims = new();
                    foreach (KeyValuePair<string, string> kv in content)
                    {
                        claims.Add(new ProvideClaimsForToken(new TokenClaim(kv.Key, kv.Value)));
                        log.LogInformation($"Added claim {kv.Key} with value {kv.Value}");
                    }

                    request.Response.Actions.AddRange(claims);
                }
                else
                {
                    //If the request failed for any reason, i.e. Token validation, output the failed request status
                    log.LogInformation(request.StatusMessage);
                }
                return await request.Completed();
            }
            catch (Exception ex)
            {
                return await request.Failed(ex);
            }
        }
    }
}

```

**Comment by HarmanDhunna** [comment]
Hopefully you would not need to derive TokenIssuenceAction or ProvideClaimsForToken. You should be able to utilize them directly.

If you want, you can have a wrapper around them to make it easy to update your code as our library grows, but we'll be pretty bound to the current SDK library contract.

**Comment by adamsosinski** [comment]
Hi,

Thanks for the response, the setup looks promising, as we want to depend on HTTP triggers. Will let you know if I managed to set this up or if would need some additional help.

Thanks

**Comment by HarmanDhunna** [comment]
@adamsosinski let me know if you need anymore help, happy to reopen the item.
