### ISSUE TITLE
[QUERY] How to get the cloud information as Azure environment

### ISSUE THREAD

**Issue by fseldow** [Azure/azure-sdk-for-net#40011]
### Library name and version

Microsoft.Azure.Management.ResourceManager.Fluent

### Query/Question

Since `Microsoft.Azure.Management.ResourceManager.Fluent` is deprecated, do we have any alternative method to get the azure cloud information similar as the `AzureEnvironment.FromName()` ?
I know we have auth endpoint defined [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/src/AzureAuthorityHosts.cs). But where could i find the rest? e.g. Name, AuthenticationEndpoint, ResourceManagerEndpoint, ManagementEndpoint, GraphEndpoint,, StorageEndpointSuffix, KeyVaultSuffix

**Comment by jsquire** [comment]
Hi @fseldow.  There is no replacement for the legacy `AzureEnvironment` class.  Unfortunately, the information that you're looking for is not published by any supported Azure service in a way that is queryable by the Azure SDK packages.  As the data is very likely to change over time, it is not something that is appropriate for the client to hardcode - which is exactly what the legacy implementation did.

This is an area that we're still exploring and discussing with our Azure service partners, but there is no current plan for providing a replacement.
