### ISSUE TITLE
[QUERY] Add VM extension after pool created

### ISSUE THREAD

**Issue by mariealtin** [Azure/azure-sdk-for-net#40017]
### Library name and version

Azure.ResourceManager.Batch 1.1.1

### Query/Question

Using the BatchAccountPoolResource.UpdateAsync method for a pool that has already  been created. 
I need to add an extension to the DeploymentConfiguration.VmConfiguration.Extensions list, however seems UpdateAsync does not support this as the List of Extensions is Get only. How can this be achieved? Documentation on this subject seems non-existent.

### Environment

.NET framework 4.8

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Close as duplicated with issue: #40325
