### ISSUE TITLE
[BUG] Azure Monitor OTel Exporter - activities with duplicated tags are dropped

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-net#40023]
### Library name and version

Azure.Monitor.OpenTelemetry.Exporter

### Describe the bug

If an activity has duplicated tags, it's dropped by the exporter.

E.g. write
```csharp
  var s = new ActivitySource("foo");
  var act = s.StartActivity("bar");
  act?.AddTag("k", "v1")
      .AddTag("k", "v2");

  act?.Stop();

  var act2 = s.StartActivity("baz");
  act2?.AddTag("k1", "v1")
      .AddTag("k2", "v2");

  act2?.Stop();
```
Configure distro
```csharp
builder.Services.AddOpenTelemetry().UseAzureMonitor();
builder.Services.ConfigureOpenTelemetryTracerProvider((sp, builder) => builder
  .AddSource("foo")
  .AddConsoleExporter());
```

Result:

- both activities are exporter by console exporter
- but only `baz` appears in the portal:

```log
Activity.TraceId:            db8de9fe66c99061faf57cafb7e790e3
Activity.SpanId:             043588858b17c852
Activity.TraceFlags:         Recorded
Activity.ParentSpanId:       73b88f601db285c8
Activity.ActivitySourceName: foo
Activity.DisplayName:        bar
Activity.Kind:               Internal
Activity.StartTime:          2023-11-15T20:50:49.0703292Z
Activity.Duration:           00:00:00.0000062
Activity.Tags:
    k: v1
    k: v2
    _MS.ProcessedByMetricExtractors: (Name: X,Ver:'1.1')
Resource associated with Activity:
    telemetry.distro.name: Azure.Monitor.OpenTelemetry.AspNetCore
    telemetry.sdk.name: opentelemetry
    telemetry.sdk.language: dotnet
    telemetry.sdk.version: 1.6.0
    service.name: unknown_service:LineCounter

Activity.TraceId:            db8de9fe66c99061faf57cafb7e790e3
Activity.SpanId:             fedc9a9a144bd3a4
Activity.TraceFlags:         Recorded
Activity.ParentSpanId:       73b88f601db285c8
Activity.ActivitySourceName: foo
Activity.DisplayName:        baz
Activity.Kind:               Internal
Activity.StartTime:          2023-11-15T20:50:49.0710349Z
Activity.Duration:           00:00:00.0000036
Activity.Tags:
    k1: v1
    k2: v2
    _MS.ProcessedByMetricExtractors: (Name: X,Ver:'1.1')
Resource associated with Activity:
    telemetry.distro.name: Azure.Monitor.OpenTelemetry.AspNetCore
    telemetry.sdk.name: opentelemetry
    telemetry.sdk.language: dotnet
    telemetry.sdk.version: 1.6.0
    service.name: unknown_service:LineCounter
```

![image](https://github.com/Azure/azure-sdk-for-net/assets/2347409/a87a3f41-faa9-4b70-87f6-deff5bbb8424)

### Expected behavior

Activity is exported with one of the provided values.

### Actual behavior

Activity is not exported

### Reproduction Steps

See above

### Environment

// cc @vishweshbankwar @rajkumar-rangaraj

**Comment by vishweshbankwar** [comment]
@lmolkova `AddTag` is not recommended on Activity [ref](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Api#tracing-api:~:text=The%20recommended%20way%20to%20set%20span%20attributes%20in%20Activity%20class%20is%20by%20using%20SetTag().%20OpenTelemetry%20users%20should%20not%20use%20other%20methods%20like%20AddTag%2C%20SetCustomProperty%20on%20Activity). Is there a specific reason to use AddTag not recommended `SetTag`?

**Comment by lmolkova** [comment]
> @lmolkova `AddTag` is not recommended on Activity [ref](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Api#tracing-api:~:text=The%20recommended%20way%20to%20set%20span%20attributes%20in%20Activity%20class%20is%20by%20using%20SetTag().%20OpenTelemetry%20users%20should%20not%20use%20other%20methods%20like%20AddTag%2C%20SetCustomProperty%20on%20Activity). Is there a specific reason to use `AddTag` and not recommended method i.e. `SetTag`?

yes, I'm fixing it in Azure Core, but it does not mean that activities should be dropped :)

**Comment by vishweshbankwar** [comment]
> > @lmolkova `AddTag` is not recommended on Activity [ref](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Api#tracing-api:~:text=The%20recommended%20way%20to%20set%20span%20attributes%20in%20Activity%20class%20is%20by%20using%20SetTag().%20OpenTelemetry%20users%20should%20not%20use%20other%20methods%20like%20AddTag%2C%20SetCustomProperty%20on%20Activity). Is there a specific reason to use `AddTag` and not recommended method i.e. `SetTag`?
> 
> yes, I'm changing to `SetTag` Azure Core, but the fact that it's not recommended does not mean that activities should be dropped :)

Yes, We need proper error handling.

**Comment by source-studio** [comment]
May I ask when a fix for this will be released? It appears to affecting the [Sentry SDK](https://github.com/getsentry/sentry-dotnet/blob/main/src/Sentry.OpenTelemetry/SentrySpanProcessor.cs#L118), as they implicitly rely on tags being unique. From what I can tell, the `error.type` tag is being duplicated.

**Comment by lmolkova** [comment]
> May I ask when a fix for this will be released? It appears to affecting the [Sentry SDK](https://github.com/getsentry/sentry-dotnet/blob/main/src/Sentry.OpenTelemetry/SentrySpanProcessor.cs#L118), as they implicitly rely on tags being unique. From what I can tell, the `error.type` tag is being duplicated.

@source-studio  I believe you're asking about Azure SDK producing duplicated `error.type` attributes (https://github.com/Azure/azure-sdk-for-net/pull/40027) - that's been fixed but will be released in January 2024.
