### ISSUE TITLE
[FEATURE REQ] [Azure.Core] Implement "lazy BinaryData" to represent generic data from different sources

### ISSUE THREAD

**Issue by joseharriaga** [Azure/azure-sdk-for-net#40036]
### Library name

Azure.Core

### Please describe the feature.

We have seen a pattern in multiple REST APIs where some form of data (for example: an image or a document) is represented as either a Base64-encoded string or a URL to blob storage.

### Case 1: Content Safety
Used as an input to send images to the service for analysis. See the [🔗 ContentSafetyImageData class](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/contentsafety/Azure.AI.ContentSafety/src/Generated/ContentSafetyImageData.cs).

### Case 2: OpenAI
Used as an output to receive images that were generated using the DALL-E models. See the [🔗 ImageLocation model](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/OpenAI.Inference/models/images/images.tsp#L62). (Note that the TypeSpec currently only specifies the URL property because Azure OpenAI does not yet support the Base64-encoded string result, but our understanding is that support for it is coming soon. Regardless, non-Azure OpenAI does support both formats.)

### Case 3: Document Intelligence
Used as an input to send documents to the service for analysis. See the [🔗 AnalayzeDocumentRequest class](https://apiview.dev/Assemblies/Review/f0a5ec117a4542fda3a9e828d33ba630#Azure.AI.DocumentIntelligence.AnalyzeDocumentRequest) and [🔗 Ted's comment in this APIView](https://apiview.dev/Assemblies/Review/f0a5ec117a4542fda3a9e828d33ba630#1d1ebca02692467aa8afe9e5090fc6ae).

### Case 4: Data Movement
Used to move data around. Adds a potential third consideration (in addition to a URL or a Base64-string) where the data can be represented as a file location in local storage.
 
### Potential solution
We have talked about having something like a "lazy BinaryData" and drafted the concept below:

```csharp
public class BinaryDataSource {
    public BinaryDataSource(BinaryData value);
    public BinaryDataSource(Uri uri);
    public BinaryDataSource(string path);

    public BinaryData? Data { get; }
    public string? Path { get; }
    public Uri? Uri { get; }

    public BinaryData Get(CancellationToken cancellationToken = default);
    public ValueTask<BinaryData> GetAsync(CancellationToken cancellationToken = default);
}
```

**Comment by annelo-msft** [comment]
@joseharriaga, is this still needed now that OAI has shipped?
