### ISSUE TITLE
Incorrect LRO tests

### ISSUE THREAD

**Issue by dsgouda** [Azure/azure-sdk-for-net#4005]
The tests `TestLROAsynOperationFailureWith200()`, `TestLROWithLocationHeaderFailureWith200()` and `TestLROPUTWithCanceledState()` in `LongRunningOperationsTest` have catch statements that are never executed thereby falsely passing since no exception is thrown.
We need `Assert.Throws<>` as well as investigation to verify why exceptions are not being thrown.

P.S.: Also need to fix a minor typo: `LROOpertionTestResponses` to `LROOperationTestResponses`

**Comment by shahabhijeet** [comment]
Fixed with #4142
