### ISSUE TITLE
Package is deprecated, what to use instead?

### ISSUE THREAD

**Issue by PjotrB** [Azure/azure-sdk-for-net#40088]
NuGet Manager for VS tells me "This package has been deprecated as it is legacy and no longer maintained."
The packages that it suggest as replacements - `Azure.Storage.Blobs` + `Azure.Storage.Queues` + `Azure.Storage.Files.Shares` - do not seem to offer the **NameValidator** class, or at least I can't find it.

Is there still a **NameValidator** class in a non-deprecated package, which package would that be?
Or has the functionality moved to a different class, to be found in which non-deprecated package?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2af239f0-d535-23d4-16e9-347affb81dbd
* Version Independent ID: 117c9835-d9b7-ccbb-d4a3-4546733e40b2
* Content: [NameValidator Class (Microsoft.Azure.Storage) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.namevalidator?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Storage/NameValidator.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Storage/NameValidator.xml)
* Service: **storage**
* GitHub Login: @azure-sdk
* Microsoft Alias: **azsdkdocs**

**Comment by seanmcc-msft** [comment]
@PjotrB, the `NameValidator` class does not exist in the new packages.  Name validation is now being enforced by the storage service itself.
