### ISSUE TITLE
[FEATURE REQ] DALL-E 3 Model ImageGeneration

### ISSUE THREAD

**Issue by 0x59d** [Azure/azure-sdk-for-net#40080]
### Library name

Azure.AI.OpenAI

### Please describe the feature.

We currently don't have an option to select which model we want to use for ImageGeneration. It seems the default model is still DALL-E 2. 

The Javascript SDK has implemented the dall-e-3 model ImageGenerations (https://github.com/openai/openai-node/blob/049ce6fa66ebe9a6aa0d64dead1e5fd8c3da1083/tests/api-resources/images.test.ts#L77) but is not available for the Dotnet SDK. 

Do we have an ETA of when this will be available as many of us would prefer to have images generated on the server side (better validation, access to private data, etc.).

Thanks

**Comment by jzhouw** [comment]
please also add the quality,style parameters

**Comment by scottaddie** [comment]
DALL-E 3 is supported as of the v2.0.0-beta.1 release. See the changelog entry at https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/openai/Azure.AI.OpenAI/CHANGELOG.md#features-added-2.
