### ISSUE TITLE
Type in title's page

### ISSUE THREAD

**Issue by scoriani** [Azure/azure-sdk-for-net#40122]
Hey folks, there's a type in the title! Database Fleet Manager is (our) different product, this should be Kubernetes Fleet Manager :)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6350ce5d-eb15-0766-923d-f39116d6fcda
* Version Independent ID: 63e906d3-6fdf-6296-c9e4-b1fe397ab113
* Content: [Microsoft Azure Database Fleet Manager management client library for .NET - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/resourcemanager.containerservicefleet-readme?view=azure-dotnet-preview)
* Content Source: [api/overview/azure/preview/resourcemanager.containerservicefleet-readme.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/preview/resourcemanager.containerservicefleet-readme.md)
* Service: **fleet**
* GitHub Login: @azure-sdk
* Microsoft Alias: **azsdkdocs**

**Comment by HarveyLink** [comment]
Page updated: https://review.learn.microsoft.com/en-us/dotnet/api/overview/azure/resourcemanager.containerservicefleet-readme?view=azure-dotnet&branch=main
