### ISSUE TITLE
CodeGenerator generates "Operation returned an invalid status code 'XYZ'"

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-sdk-for-net#4012]
We've had a number of customers complain or get confused about the fact that the generated text in the exception is an _invalid_ status code (even though the status code is listed in string form afterwards).

I personally actually see where they are coming from - "Invalid" makes me thing of an HTTP status code which is not a valid status code (i.e. returning -1 or something).

It would be clearer if this text said something like: "Operation returned an unexpected status code 'XYZ'" or "Operation returned an HTTP status code 'XYZ' which does not represent a success" 

Is a change like this something you'd be open to?

**Comment by shahabhijeet** [comment]
@matthchr yes we are open to such changes.
Can you give me a precise repro so we know which code path is causing such error strings.

**Comment by dsgouda** [comment]
@matthchr Improving the messaging in auto generated exceptions is something we have worked on in the CSharp generator but it hasn't been released yet. We should probably be able to take this change in the generator repo. Will reopen this issue there.
