### ISSUE TITLE
[BUG] Azure AI Search SDK's paging seems to be broken in latest release

### ISSUE THREAD

**Issue by jelledruyts** [Azure/azure-sdk-for-net#40137]
### Library name and version

Azure.Search.Documents 11.5.0

### Describe the bug

I'm migrating some existing code using "Azure.Search.Documents" from the 11.5.0-beta5 to the final 11.5.0 version but I'm getting an error while paging through the results that "The parameter 'semanticConfiguration' must not be empty". Digging a bit deeper I've noticed that the first page of results is fine (it does set "semanticConfiguration=default" in my case), and the API response includes "@search.nextPageParameters", but the next request that the SDK performs doesn't actually include most of those parameters.

### Expected behavior

The SDK should request the next page of results with the same parameters as the initial request.

### Actual behavior

The SDK requests the next page of results without the required parameters from the initial call (or those coming back from the service in "@search.nextPageParameters".

### Reproduction Steps

Client code:

```
var serviceResponse = await requestedSearchClient.SearchAsync<SearchDocument>(searchText, searchOptions);
foreach (var result in serviceResponse.Value.GetResults()) { ... }
```
 
Initial request:

![image](https://github.com/Azure/azure-sdk-for-net/assets/11096066/8579563b-d8dc-4c68-8fd2-ac51e94a7e15)

Next page params from initial response:

![image](https://github.com/Azure/azure-sdk-for-net/assets/11096066/b21ffb93-872d-42b0-8939-091d0f0df838)
 
Second request (lacking those parameters but including "skip=50"):

![image](https://github.com/Azure/azure-sdk-for-net/assets/11096066/11434b88-8775-4b45-88b1-61fd9c7cba00)

Error on second request:
 
`{"error":{"code":"","message":"The parameter 'semanticConfiguration' must not be empty. Alternatively, set a default semantic configuration for this index.\r\nParameter name: semanticConfiguration"}}`

### Environment

.NET SDK:
 Version:   7.0.114
 Commit:    b2a71039cd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.114\

Host:
  Version:      7.0.14
  Architecture: x64
  Commit:       808851b07a

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ShivangiReja** [comment]
Thank you for bringing this issue to our attention. I can confirm that it is an issue, and I want to assure you that we are currently addressing it. I've submitted a PR [here](https://github.com/Azure/azure-sdk-for-net/pull/40185), and I'll keep you informed once we release the updated package with the fix. We apologize for any inconvenience caused by this issue and appreciate your understanding.

**Comment by jelledruyts** [comment]
That was quick - thank you so much for the quick turnaround!

**Comment by ShivangiReja** [comment]
Hi @jelledruyts , we've released https://www.nuget.org/packages/Azure.Search.Documents/11.5.1 package containing this fix. Please confirm if it resolves your issue. Thank you!

**Comment by jelledruyts** [comment]
Yes, I've retested and it works now - thanks again for the quick fix!
