### ISSUE TITLE
[FEATURE REQ] Add example of auth with TokenCredentials to Azure.Storage.Files.Shares samples

### ISSUE THREAD

**Issue by ArturAdam** [Azure/azure-sdk-for-net#40148]
### Library name

Azure.Storage.Files.Shares

### Please describe the feature.

I would like to request an update to the existing documentation and code samples related to Azure Storage File Shares. Recently, OAuth support was added for Azure file shares as detailed in the Microsoft documentation (https://learn.microsoft.com/en-us/azure/storage/files/authorize-oauth-rest?tabs=portal). However, the existing samples and documentation primarily showcase authentication methods that predate this addition.

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the linked article is maintained, so that the content authors are made aware.   Please see [#117313](https://github.com/MicrosoftDocs/azure-docs/issues/117313).

**Comment by ArturAdam** [comment]
@jsquire I meant samples in this repo here: https://github.com/Azure/azure-sdk-for-net/tree/c4f2dda276227af505ebabeabe233737b483e583/sdk/storage/Azure.Storage.Files.Shares/samples

**Comment by jsquire** [comment]
@ArturAdam: Thanks for the clarification.  We'll route this over to the folks that own the Storage library for consideration.
