### ISSUE TITLE
Get all Values for a Key in AzureAppConfiguration

### ISSUE THREAD

**Issue by shadowano** [Azure/azure-sdk-for-net#40150]
When reading the documentation it looks like Label has to be known by the app in order to get all Values for a Key which has labels. 

I'm following this [Microsoft learn Tutorial](https://learn.microsoft.com/en-us/azure/azure-app-configuration/enable-dynamic-configuration-aspnet-netfx) to get Keys from the App configuration. It works fine if I enter a label that exists, but I don't see how to fetch ALL Values with and without label set. Is this not possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9eb5ea19-ce46-f037-6963-689ca8f5ef2e
* Version Independent ID: 1b7c3195-9f7b-24c2-ff3f-cfcc56e94649
* Content: [AzureAppConfigurationOptions.Select(String, String) Method (Microsoft.Extensions.Configuration.AzureAppConfiguration) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.azureappconfiguration.azureappconfigurationoptions.select?view=azure-dotnet#microsoft-extensions-configuration-azureappconfiguration-azureappconfigurationoptions-select(system-string-system-string))
* Content Source: [xml/Microsoft.Extensions.Configuration.AzureAppConfiguration/AzureAppConfigurationOptions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Extensions.Configuration.AzureAppConfiguration/AzureAppConfigurationOptions.xml)
* Service: **azure-app-configuration**
* GitHub Login: @azure-sdk
* Microsoft Alias: **azsdkdocs**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.Extensions.Configuration.AzureAppConfiguration` package is maintained as [#500](https://github.com/Azure/AppConfiguration-DotnetProvider/issues/500).
