### ISSUE TITLE
Export an ARM template for a resource

### ISSUE THREAD

**Issue by ggoel** [Azure/azure-sdk-for-net#40156]
### Library name and version

Azure.ResourceManager 1.6.0

### Query/Question

How to export an ARM template for a resource using Azure.ResourceManager.ArmClient. Similar sample example for ARM template deployment provided [here]( https://github.com/Azure-Samples/azure-samples-net-management/blob/master/samples/resources/deploy-using-arm-template/Program.cs) seems outdated and uses _ResourcesManagementClient_ which is now not supported[AFAIK]. Please provide sample for Template export using latest lib

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ggoel** [comment]
@ArthurMa1978 please advise

**Comment by ggoel** [comment]
@jsquire @ArthurMa1978 please let me know if this functionality exists already OR I can work to contribute and build this in the lib

**Comment by HarveyLink** [comment]
Hi @ggoel Thank you for using Azure SDK for .NET.
For the question you asked, please refer to:
https://github.com/Azure/azure-sdk-for-net/blob/84c0361d53cc0cfa4c71f8267e28d5af34c6b889/sdk/resourcemanager/Azure.ResourceManager/samples/Generated/Samples/Sample_ResourceGroupResource.cs#L113
