### ISSUE TITLE
Deadlock getting authentication header from TokenProvider

### ISSUE THREAD

**Issue by dweggemans** [Azure/azure-sdk-for-net#4016]
Using Microsoft.Rest.ClientRuntime 2.3.10

We're experiencing deadlocks when using the `TokenCredentials`. We've tracked this down to

https://github.com/Azure/azure-sdk-for-net/blob/52c7902eb62391b7e37794bc8a491dbad73116a1/src/SdkCommon/ClientRuntime/ClientRuntime/TokenCredentials.cs#L115

Solution: add `.ConfigureAwait(false)` fixes the deadlock.

**Comment by shahabhijeet** [comment]
@dweggemans can you provide me a repro for the deadlock you are experiencing.
This helps in knowing the scenario and making sure such regression is never introduced in this code base.

**Comment by pakrym** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
