### ISSUE TITLE
Request for Public Constructors or Factory Methods for DTO Mocking in Azure.AI.OpenAI

### ISSUE THREAD

**Issue by BlackGad** [Azure/azure-sdk-for-net#40191]
### Library name

Azure.AI.OpenAI

#### Problem Statement
We are currently facing challenges in mocking response DTOs in our testing environment. The primary issue stems from the fact that all DTOs have internal constructors, limiting our ability to instantiate these objects externally for testing purposes.

#### Proposed Solution
To address this, I propose two potential solutions:
1. **Make Constructors Public**: Altering the access level of the constructors from internal to public would allow external instantiation, facilitating easier mocking of these DTOs.
2. **Implement Factory Methods**: As an alternative, introducing factory methods for DTO creation could provide a controlled way of instantiating DTOs while preserving encapsulation and internal constructor integrity.

### Impact
- **Testing Efficiency**: Implementing either of these changes would significantly streamline our testing process, allowing for more effective and efficient test case creation.
- **Flexibility in Mocking**: It would also provide greater flexibility in mocking different scenarios, leading to more robust testing.

**Comment by jsquire** [comment]
Hi @BlackGad.  Thank you for reaching out and we regret that you're experiencing difficulties.  The Azure SDK libraries, including OpenAI, provide a model factory to allow creation of read-only models for testing.  In this case, the class that you're looking for is [OpenAiModelFactory](https://learn.microsoft.com/dotnet/api/azure.ai.openai.azureopenaimodelfactory?view=azure-dotnet-preview).  More context and discussion of the strategy we use for testability of the Azure SDK can be found in [Unit testing and mocking with the Azure SDK for .NET](https://learn.microsoft.com/dotnet/azure/sdk/unit-testing-mocking?tabs=csharp).

**Comment by BlackGad** [comment]
Thank you for the quick response. Somehow I missed this factory class. This satisfies all my current needs.
