### ISSUE TITLE
[QUERY] Are KQL injection attacks a possibility via Azure.Monitor.Query?

### ISSUE THREAD

**Issue by furyd** [Azure/azure-sdk-for-net#40223]
### Library name and version

Azure.Monitor.Query

### Query/Question

I'm using Azure.Monitor.Query in a manner where third parties can query our logs against a key (string or GUID) supplied by them via a route value in a web api, and another key from their auth token so they can only query against actions they've done.

Now my concern is if they can craft the string key to circumvent those restrictions or the curated projection they get returned? I want to ensure that isn't a possibility.

**Comment by jsquire** [comment]
Hi @furyd.  Thank you for reaching out and we regret that you're experiencing difficulties.  What you're asking about relates to how the Monitor service generates and validates keys, which is opaque to the Azure SDK library and not something that it can influence or control. 

This repository is focused on the Azure SDK for .NET which means that, unfortunately, this isn't a question that we're able to assist with.  Your best path forward would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request).

I'm going to close this out;  if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.

**Comment by furyd** [comment]
/unresolve

Hi @jsquire I think you've misunderstood as it's to do with the queries.

I'm writing a query, e.g. $"traces | where customDimensions[""x""] = '{key}'" - now I want to ensure that the key string cannot be crafted such that it acts in a similar manner to a SQL injection attack as it originates from a REST request.

I want to know if my concern is unfounded, and, if not, what I need to do to ensure the string is cleansed before being part of the query.

**Comment by jsquire** [comment]
@furyd.  Thanks for clarifying.  I understand what you're attempting to do, but the client does not have insight or control over how the service processes queries nor what protections it offers.  The client passes the query and its elements to the service, which interprets and processes it.  As a result, we can't provide an authoritative response for your question, and given that it is security-related, you'll want to raise this with the service team.
