### ISSUE TITLE
[BUG] Json Mode is missing from completions API

### ISSUE THREAD

**Issue by kzu** [Azure/azure-sdk-for-net#40225]
### Library name and version

Azure.AI.OpenAI 1.0.0-beta.9

### Describe the bug

See https://platform.openai.com/docs/guides/text-generation/json-mode

### Expected behavior

ChatCompletionsOptions have a `bool? JsonMode` property to trigger the new behavior in OpenAI.

### Actual behavior

No such property exists, it's impossible to use that new feature.

### Reproduction Steps

Try to set Json Mode on a request.

**Comment by KSemenenko** [comment]
https://techcommunity.microsoft.com/t5/ai-azure-ai-services-blog/azure-openai-service-launches-gpt-4-turbo-and-gpt-3-5-turbo-1106/ba-p/3985962

Microsoft mentions this publicly and it would be great to have support for this feature.

**Comment by tl-ben** [comment]
They have help content for it, but not SDK support (it's there for Python):
https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/json-mode

It's a single property that needs adding to ChatCompletionsOptions, Python has response_format = { "type": "json_object" }.

**Comment by PooSham** [comment]
Seems to exist now on 1.0.0-beta.10 with `ResponseFormat = ChatCompletionsResponseFormat.JsonObject`

However, using model gpt-4 with model version 1106-preview, I get the following message:

> 'json_object' is not of type 'object' - 'response_format'

Not sure if the model name has to be gpt-4-turbo, but that's not available. I thought 1106 was turbo. 

I'll have to try with gpt-35-turbo and see if it works.

**Comment by PooSham** [comment]
I just tried with a gpt-35-turbo deployment and got the same result. I'll create a new issue for this.

**Comment by PooSham** [comment]
#40632

**Comment by kzu** [comment]
As a workaround for now @larserikfinholt you can use the package with the minimal changes in my PR: https://github.com/Azure/azure-sdk-for-net/pull/40226#issuecomment-1826343480

**Comment by kzu** [comment]
Fixed with https://github.com/Azure/azure-sdk-for-net/pull/40638 in latest beta. Thanks!
