### ISSUE TITLE
System.ClientModel: Add boilerplate links to README

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#40306]
The ClientModel README should have boilerplate doc links similar to the ones in Azure.Core: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/README.md?plain=true#L11

**Comment by pallavit** [comment]
@annelo-msft why is this a release-blocker? Can you please share what links are needed here?

**Comment by annelo-msft** [comment]
My understanding is that these are required for our team's READMEs.  Since we are bypassing engsys validations (given that the name doesn't start with Azure.*), we aren't being asked to do it, but it's best practice so I think it would be helpful to customers to provide those links.

The links in questions are the same ones the Azure.Core README has: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/README.md?plain=true#L11

We filed this during the beta release -- they weren't added then because there wasn't yet a landing page for the nuget package.  Now there is, so it should be a very small change to address.
