### ISSUE TITLE
[FEATURE REQ] Allow RBAC authorized BlobClient to generate sas uri 

### ISSUE THREAD

**Issue by samjpv** [Azure/azure-sdk-for-net#40307]
### Library name

Azure.Storage.Blobs

### Please describe the feature.

It seems like the BlobClient CanGenerateSasUri value will always be false unless the BlobClient is authorized using a shared key, which is expected behavior, based on docs [here](https://learn.microsoft.com/en-us/azure/storage/blobs/sas-service-create-dotnet#:~:text=is%20authorized%20with%20a%20shared%20key%20credential) and [here](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobclient?view=azure-dotnet#:~:text=If%20the%20client%20is%20authenticated%20with%20a%20StorageSharedKeyCredential.) and based on the BlobClient code. 

In my case, a service SAS needs to be generated by the BlobClient, but the BlobClient uses RBAC. Although the BlobClient has access to the shared access keys via roles, it cannot generate the service SAS because it is authenticated using RBAC and not a StorageSharedKeyCredential. Would it be possible to allow clients to generate SAS uri's without having to pass in a key, as long as they have access to the keys through roles?

Also let me know if there's a workaround or something else that I'm missing here, since I'm surprised that there didn't appear to be any issues open for this already. Thanks!

Edit: I know that I can also use [SasBuilder.ToSasQueryParameters](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.sas.blobsasbuilder.tosasqueryparameters?view=azure-dotnet) with a StorageSharedKeyCredential as well to get just the token instead of using [BlobContainerClient.GenerateSasUri](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobcontainerclient.generatesasuri?view=azure-dotnet), but it still means I need to get the shared access key to generate the token, which I would prefer not to do.

**Comment by seanmcc-msft** [comment]
@samjpv, here is an example of how to generate a [User Delegation SAS](https://learn.microsoft.com/en-us/rest/api/storageservices/create-user-delegation-sas) in the .NET SDK:

https://github.com/Azure/azure-sdk-for-net/blob/1152fecbc51dd11284c714a0a82cc93dff28deee/sdk/storage/Azure.Storage.Blobs/tests/BlobBaseClientTests.cs#L204
