### ISSUE TITLE
WebSiteManagementClient.WebApps.SyncFunctionTriggers method throws an Exception even if the StatusCode is 200 OK

### ISSUE THREAD

**Issue by yoshimasak** [Azure/azure-sdk-for-net#4030]
I’m using Microsoft.Azure.Management.Websites.WebSiteManagementClient class, WebApps.SyncFunctionTriggers method to sync triggers.
I understand that this method does a REST call internally, and it seems that the REST call is working well, receives HTTP 200 OK and the sync process completes successfully, but the method throws an exception.

It seems that this issue happens because SyncFuntionTriggers method is marked to return void (empty response body) but from the Function APIs called out at: https://github.com/projectkudu/kudu/wiki/Functions-API#syncing-the-function-apps-triggers, the response body is as below.

```
{
  "status":"success"
}
```

My function is like below and we can reproduce this easily.

```
public static async Task syncTrigger(string tenantId, string clientId, string clientSecret, string subscriptionId)
{
    try
    {
        var serviceCreds = await ApplicationTokenProvider.LoginSilentAsync(tenantId, clientId, clientSecret);
        var webClient = new WebSiteManagementClient(serviceCreds);
        webClient.SubscriptionId = subscriptionId;
 
        webClient.WebApps.SyncFunctionTriggers(resourceGroupName, resourceName);
        Console.WriteLine("Synced Triggers successfully.");
    }
    catch (Exception exp)
    {
        Console.WriteLine("Failed Syncing triggers.");
    }
}
```

**Comment by dsgouda** [comment]
@yoshimasak Could you please provide the call stack and exception details here.

**Comment by dsgouda** [comment]
Closing the issue, please open a new one if this persists
