### ISSUE TITLE
Azure function (Service Bus Trigger) - ReceiveMessageException No such host is known.

### ISSUE THREAD

**Issue by rahulsingii** [Azure/azure-sdk-for-net#40314]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.11.0

### Query/Question

I have two azure functions each triggered using service bus. The functions re working as expected but recently the system has started logging continous errors, all related to service bus. A few of them are:-

- Azure.Messaging.ServiceBus.ServiceBusException: No such host is known.

- Azure.Messaging.ServiceBus.ServiceBusException: The session lock was lost. Request a new session receiver. (SessionLockLost)

- ReceiveBatchAsync Exception: System.UnauthorizedAccessException: Unauthorized access. 'Listen' claim(s) are required to perform this operation.

These are few examples of what system is logging. It's causing no issue in the system but has already logged millions of exceptions. 

### Environment

Hosting Platform - Azure app Service
Service Bus Trigger Auth - Managed Identity 

```[tasklist]
### Tasks
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by m-redding** [comment]
Hi @rahulsingii would you mind collecting around 5 minutes of SDK logs using the instructions [here ](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/TROUBLESHOOTING.md#enable-logging)/ [here](https://learn.microsoft.com/en-us/dotnet/azure/sdk/logging#logging-with-client-registration)? It'd be helpful to get some additional information about what is happening with the SDK so that we can figure out why so many exceptions are being logged. At first look, it seems like it's possible there could be something like some network issues, or maybe the identity being used is not the exact one you're expecting.

**Comment by rahulsingii** [comment]
@m-redding - Thank you for your response. As I mentioned, I am not registring service bus by SDK rather only using the trigger in AZ function (which under the hood has service bus code). Here are few more detailed logs :

> Event Name

 - ReceiveMessageException

> Exception 

- sbq-xxxx-6a666a82-858b-2345-99fe-435455235-Receiver: ReceiveBatchAsync Exception: Azure.Messaging.ServiceBus.ServiceBusException: No such host is known. ErrorCode: HostNotFound (ServiceCommunicationProblem). For troubleshooting information, see https://aka.ms/azsdk/net/servicebus/exceptions/troubleshoot.   ---> System.Net.Sockets.SocketException (11001): No such host is known.     at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)     at Microsoft.Azure.Amqp.Transport.AmqpTransportInitiator.<>c.<ConnectAsync>b__17_1(IAsyncResult r)     at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)  --- End of stack trace from previous location ---     at Azure.Messaging.ServiceBus.Amqp.AmqpConnectionScope.CreateAndOpenConnectionAsync(Version amqpVersion, Uri serviceEndpoint, Uri connectionEndpoint, ServiceBusTransportType transportType, IWebProxy proxy, String scopeIdentifier, TimeSpan timeout)     at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)     at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)     at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)     at Azure.Messaging.ServiceBus.Amqp.AmqpConnectionScope.OpenReceiverLinkAsync(String identifier, String entityPath, TimeSpan timeout, UInt32 prefetchCount, ServiceBusReceiveMode receiveMode, String sessionId, Boolean isSessionReceiver, CancellationToken cancellationToken)     at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.OpenReceiverLinkAsync(TimeSpan timeout, UInt32 prefetchCount, ServiceBusReceiveMode receiveMode, String identifier, CancellationToken cancellationToken)     at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)     at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)     at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)     at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.ReceiveMessagesAsyncInternal(Int32 maxMessages, Nullable`1 maxWaitTime, TimeSpan timeout, CancellationToken cancellationToken)     --- End of inner exception stack trace ---     at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.ReceiveMessagesAsyncInternal(Int32 maxMessages, Nullable`1 maxWaitTime, TimeSpan timeout, CancellationToken cancellationToken)     at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<>c.<<ReceiveMessagesAsync>b__45_0>d.MoveNext()  --- End of stack trace from previous location ---     at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken, Boolean logTimeoutRetriesAsVerbose)     at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken, Boolean logTimeoutRetriesAsVerbose)     at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.ReceiveMessagesAsync(Int32 maxMessages, Nullable`1 maxWaitTime, CancellationToken cancellationToken)     at Azure.Messaging.ServiceBus.ServiceBusReceiver.ReceiveMessagesAsync(Int32 maxMessages, Nullable`1 maxWaitTime, Boolean isProcessor, CancellationToken cancellationToken).

> Event Name

ClientCreateExceptionCore

> Exception Message 

An exception occurred while creating a ServiceBusSessionReceiver (Namespace 'xyzsb.servicebus.windows.net', Entity path 'sbq-xxxx'). Error Message: 'Azure.Messaging.ServiceBus.ServiceBusException: No such host is known. ErrorCode: HostNotFound (ServiceCommunicationProblem). For troubleshooting information, see https://aka.ms/azsdk/net/servicebus/exceptions/troubleshoot.   ---> System.Net.Sockets.SocketException (11001): No such host is known.     at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)     at Microsoft.Azure.Amqp.Transport.AmqpTransportInitiator.<>c.<ConnectAsync>b__17_1(IAsyncResult r)     at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)  --- End of stack trace from previous location ---     at Azure.Messaging.ServiceBus.Amqp.AmqpConnectionScope.CreateAndOpenConnectionAsync(Version amqpVersion, Uri serviceEndpoint, Uri connectionEndpoint, ServiceBusTransportType transportType, IWebProxy proxy, String scopeIdentifier, TimeSpan timeout)     at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)     at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)     at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)     at Azure.Messaging.ServiceBus.Amqp.AmqpConnectionScope.OpenReceiverLinkAsync(String identifier, String entityPath, TimeSpan timeout, UInt32 prefetchCount, ServiceBusReceiveMode receiveMode, String sessionId, Boolean isSessionReceiver, CancellationToken cancellationToken)     at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.OpenReceiverLinkAsync(TimeSpan timeout, UInt32 prefetchCount, ServiceBusReceiveMode receiveMode, String identifier, CancellationToken cancellationToken)     at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)     at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)     at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)     at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<>c.<<OpenLinkAsync>b__78_0>d.MoveNext()  --- End of stack trace from previous location ---     at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken, Boolean logTimeoutRetriesAsVerbose)     --- End of inner exception stack trace ---     at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken, Boolean logTimeoutRetriesAsVerbose)     at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.OpenLinkAsync(CancellationToken cancellationToken)     at Azure.Messaging.ServiceBus.ServiceBusReceiver.OpenLinkAsync(CancellationToken cancellationToken)     at Azure.Messaging.ServiceBus.ServiceBusSessionReceiver.CreateSessionReceiverAsync(String entityPath, ServiceBusConnection connection, ServiceBusSessionReceiverOptions options, String sessionId, CancellationToken cancellationToken, Boolean isProcessor)'

**Comment by m-redding** [comment]
@rahulsingii one of the links I sent has some information about how to map Azure SDK logging to Functions logging - https://learn.microsoft.com/en-us/dotnet/azure/sdk/logging#map-to-aspnet-core-logging. Logs from Service Bus are also usually collected in App Insights [by default](https://learn.microsoft.com/en-us/azure/azure-functions/functions-monitoring#dependencies), so if you are using App insights you may already be able to get them there.

Looking at the logs you posted here, both exceptions have ErrorCodes related to [ServiceCommunicationProblem](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/TROUBLESHOOTING.md#find-information-about-a-servicebusexception), 

> This indicates that there was an error communicating with the service. The issue may stem from a transient network problem, or a service problem. These are transient errors that will be automatically retried.

From the bit of context here, it seems that these are transient errors that are being retried. Since the exceptions aren't being surfaced to the application, they are eventually succeeding within the bounds of the retry policy. It may be helpful to look into various potential network issues and try to see if making related adjustments stops these exceptions from being logged so frequently. One example could be if your resources have geographic locations far away from each other.

Some additional potentially helpful information:
- Socket exception [troubleshooting](https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-messaging-exceptions-latest#socketexception)
