### ISSUE TITLE
[BUG] Cannot Update/Remove VM Extension on Batch Account Pool

### ISSUE THREAD

**Issue by mjpitt** [Azure/azure-sdk-for-net#40325]
### Library name and version

Azure.ResourceManager.Batch 1.2.1

### Describe the bug

The new method of using certificates on Batch requires the KV extension be installed on pools instead of using Batch Certificates
See: [Migrate Batch account certificates to Azure Key Vault](https://learn.microsoft.com/en-us/azure/batch/batch-certificate-migration-guide)
We can create a pool with the VM extension, however  updating/removing the extension fails.

### Expected behavior

The VMExtension is added to the pool (new nodes created would then have the extension)

### Actual behavior

Fails with:
Status: 400 (A property that cannot be updated was specified as part of the request.)
ErrorCode: PropertyCannotBeUpdated

```json
[
   {"code":"Reason","message":"A property that cannot be updated was specified as part of the request."}, 
   {"code":"PropertyName","message":"deploymentConfiguration"}, 
   {"code":"PropertyPath","message":"properties.deploymentConfiguration"}
]
```

### Reproduction Steps

Create a pool, then attempt to update the pool using Management library to update/add/remove VMExtension

```csharp
var armPoolResponse = await _azureResourceManager.GetBatchPoolResourceAsync(account, poolId);
var config = armPoolResponse.Data.DeploymentConfiguration;

config.VmConfiguration.Extensions.Clear();

var extension = new BatchVmExtension(VmKeyVaultExtension.Name, VmKeyVaultExtension.Publisher, VmKeyVaultExtension.Type)
{
    AutoUpgradeMinorVersion = true,
    Settings = BinaryData.FromObjectAsJson(
        ImageReferenceExtensions.BuildKeyVaultCertificateExtensionSettings(account.ManagedIdentityClientId, account.KeyVaultUri, account.CertificateSecret))
};

config.VmConfiguration.Extensions.Add(extension);

var patch = new BatchAccountPoolData()
{
    Identity = identity,
    DeploymentConfiguration = armPoolResponse.Data.DeploymentConfiguration,
};

await armPoolResponse.UpdateAsync(patch);

```

### Environment

Windows 10 .NET Framework 4.8
Visual Studio 17.8.1

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by dpwatrous** [comment]
Thanks, @mjpitt - that's useful feedback. I'll make sure the right folks working on the service see this.

As far as the SDK itself goes, I believe it will already send the correct JSON, so if the service's REST API adds support for updating the extensions property it should work.

**Comment by ArthurMa1978** [comment]
Thank you @dpwatrous for your valuable support.

And appreciate @mjpitt for your feedback! Please feel free to contact us if you have any other questions, oryou can also [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) for service questions. We will be happy to assist you further.
