### ISSUE TITLE
[BUG] ImageGenerationOptions missing DeploymentName property

### ISSUE THREAD

**Issue by miika-prose** [Azure/azure-sdk-for-net#40330]
### Library name and version

Azure.AI.OpenAI 1.0.0-beta.9

### Describe the bug

GetImageGenerationsAsync function is now completely broken because of missing DeploymentName property in ImageGenerationOptions model. I can't produce Dalle request

### Expected behavior

ImageGenerationOptions has DeploymentName property like ChatCompletionsOptions

### Actual behavior

Only Prompt, ImageCount, Size and User are supported now.

### Reproduction Steps

```
var responseWithoutStream = await client.GetImageGenerationsAsync(
          new ImageGenerationOptions
           {
                    Prompt = text,
                    ImageCount = 1,
                    Size = ImageSize.Size1024x1024,
            }
     );
```
I this goes to 404 address.

**Comment by trrwilson** [comment]
Thanks for getting in touch! Prior to yesterday's beta.10 release, the Azure.AI.OpenAI library used the older "no-deployment" endpoint that only worked with legacy dall-e-2 image generation models. With yesterday's change, `GetImageGenerations()` is now fully aligned with OpenAI's dall-e-3 calls and should be able to use your dall-e-3 resources as expected.
