### ISSUE TITLE
Need access to status updates while awaiting the completion of a long running request

### ISSUE THREAD

**Issue by mdomashchenko** [Azure/azure-sdk-for-net#4034]
https://github.com/Azure/azure-sdk-for-net/blob/382f6a568d67f1995f4db1e998ed3dd1ab2d9eb0/src/SdkCommon/ClientRuntime.Azure/ClientRuntime.Azure/AzureClientExtensions.cs#L71

This method `GetLongRunningOperationResultAsync()` abstracts away all the gory details of handling long running requests. That's a great idea!

Unfortunately, it also abstracts away any possibility of watching the progress of those requests. According to [documentation](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-async-operations#azure-asyncoperation-request-and-response) `status` field of the response can contain arbitrary values for non-terminal statuses. For example, the operation of restoring a SQL Database from a dacpac provides the names of stages of the process.

The `GetLongRunningOperationResultAsync()` hides all those in-progess status messages from the caller and only returns once the poll request produces one of the terminal statuses of `Succeeded`, `Failed` or `Canceled`.

Would it be possible to pass some kind of callback as an additional parameter that would be called when the polling code gets a status update? Also, would you mind reporting `percentComplete` as well?

**Comment by Petermarcu** [comment]
@pakrym is this now exposed in Azure.Core based libraries?

**Comment by pakrym** [comment]
Yes, in Track 2 we have `Operation<T>.UpdateStatus` method and `HasComplete/HasValue` properties to be able to manually query the status.

**Comment by AlexGhiondea** [comment]
Closing this as this is supported in our Track 2 library.
