### ISSUE TITLE
[FEATURE REQ] Include OpenAI Assistant api and beta endpoints

### ISSUE THREAD

**Issue by BW-Kianda** [Azure/azure-sdk-for-net#40347]
### Library name

Azure.AI.OpenAI 1.0.0-beta.9

### Please describe the feature.

Hello, 
Just wondering if you could please include the Beta api endpoints from openAI in this library, if already included can you link me to some documentation or ways of using it.
See attached screenshot from openAI documentation
This feature is highly used and will be coming out of beta soon hopefully, it would be great to access using this azure sdk for dotnet
![image](https://github.com/Azure/azure-sdk-for-net/assets/113896693/f188727e-a0ba-4c16-bdcb-365d1ab9bfc2)

Thanks in advance

**Comment by ItayElgazar** [comment]
any news about this?

**Comment by kpsocal** [comment]
Still waiting

**Comment by scottaddie** [comment]
The Assistants v2 API is fully supported in the [official OpenAI library for .NET](https://devblogs.microsoft.com/dotnet/openai-dotnet-library/) and in its Azure.AI.OpenAI v2.0.0 Beta companion library.
