### ISSUE TITLE
[BUG] TenantResource.GetManagementGroups returns data from other tenant

### ISSUE THREAD

**Issue by Expecho** [Azure/azure-sdk-for-net#40369]
### Library name and version

Azure.ResourceManager 1.9.0

### Describe the bug

When I call `GetManagementGroups`  to list the management groups of a tenant, it lists management groups from another tenant.

### Expected behavior

It lists management groups from the tenant on which the method is called.

### Actual behavior

Consider the code below

```csharp
var tenantCollection = armClient.GetTenants();
var tenant = await tenantCollection.FirstAsync(t => t.Data.TenantId == Guid.Parse(selectedTenant.Id));

var mgs = tenant.GetManagementGroups();
await foreach (var mg in mgs.GetAllAsync())
{
    Console.WriteLine(mg.Data.DisplayName);
}
```

were `selectedTenant.Id` equals "a266655a-245b-4ab8-8d8f-6be387631120" the following happens when I inspect the values in a debug sessions:

**mg.Data.TenantId**
2250FCE3-5BC9-4AE7-A5E9-58C510A422EC
    _a: 575732963
    _b: 23497
    _c: 19175
    _d: 165
    _e: 233
    _f: 88
    _g: 197
    _h: 16
    _i: 164
    _j: 34
    _k: 236
**tenant.Data.Id**
'/tenants/a266655a-245b-4ab8-8d8f-6be387631120'
    Empty: ''
    Length: ƒ Length ()
**selectedTenant.Id**
'a266655a-245b-4ab8-8d8f-6be387631120'
    Empty: ''
    Length: ƒ Length ()

This clearly indicates that the call to `GetManagementGroups` of tenant with id a266655a-245b-4ab8-8d8f-6be387631120 lists managementgroups that belong to tenant with id 2250FCE3-5BC9-4AE7-A5E9-58C510A422EC

### Reproduction Steps

```csharp
var tenantCollection = armClient.GetTenants();
var tenant = await tenantCollection.FirstAsync(t => t.Data.TenantId == Guid.Parse(selectedTenant.Id));

var mgs = tenant.GetManagementGroups();
await foreach (var mg in mgs.GetAllAsync())
{
    Console.WriteLine(mg.Data.DisplayName);
}
```

### Environment

- Blazor Webassembly project running on localhost (Windows 11)
- Visual Studio 2022 17.8.0

**Comment by jsquire** [comment]
Hi @Expecho.  Thank you for reaching out and we regret that you're experiencing difficulties.   The behavior that you're seeing is not something that the SDK can influence or control, the service itself returns these results.  Unfortunately, this repository is focused on the Azure SDK for .NET and we're unable to assist with other Azure issues.  

Your best path forward would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) and report the service behavior.  As an alternative, if you're unable to open a support request, you may want to post on the [Azure Resource Manager forum](https://feedback.azure.com/d365community/forum/9a0ece70-ff24-ec11-b6e6-000d3a4f07b8) of the Azure Feedback site., which the service teams monitor.  

I'm going to close this out;  if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.

**Comment by jsquire** [comment]
Thanks for the clarification, @Expecho.   It seems I overlooked a client-side hook.   I'll triage this over to the folks who own the management libraries and will be best able to assist.

**Comment by ArthurMa1978** [comment]
Hey @Expecho , thank you for your message, investigating.

**Comment by HarveyLink** [comment]
Hi @Expecho , Thank you for using Azure SDK for .NET.
Since the tenant info is part of the credential, we are not able to change it within the same arm client.
And when query the management group, there is no tenant id in the request payload.
https://learn.microsoft.com/en-us/rest/api/managementgroups/operations/list?view=rest-managementgroups-2020-05-01&tabs=HTTP
