### ISSUE TITLE
Atomicity of sending a message batch to a queue

### ISSUE THREAD

**Issue by Aleksey-Kudryavtsev** [Azure/azure-sdk-for-net#40409]
Hello,

It would be helpful to clarify if sending a message batch is atomic or not. If it's possible for only a part of a batch to be sent in case of a failure on the client or server side.

Thanks,
Aleksey

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eb6fd36b-5867-fee8-adc4-97034c315899
* Version Independent ID: c7bfcaa6-c427-d56f-e154-38d3f3c60d46
* Content: [ServiceBusSender.SendMessagesAsync Method (Azure.Messaging.ServiceBus) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebussender.sendmessagesasync?view=azure-dotnet)
* Content Source: [xml/Azure.Messaging.ServiceBus/ServiceBusSender.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Messaging.ServiceBus/ServiceBusSender.xml)
* Service: **azure**
* GitHub Login: @azure-sdk
* Microsoft Alias: **azsdkdocs**

**Comment by jsquire** [comment]
Hi @Aleksey-Kudryavtsev.  Thank you for your feedback.   All publishing operations for Service Bus are atomic; there is no possibility for partial success.   We'll look at adding remarks to clarify in the docs.

**Comment by jsquire** [comment]
Addressed by #40521.
