### ISSUE TITLE
[BUG] DevContainer setup fails

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-sdk-for-net#40452]
### Library name and version

n/a - repo bug

### Describe the bug

When attempting to open the Dev Container via "Reopen in Container" in VS Code, I receive the following error in the log:

![image](https://github.com/Azure/azure-sdk-for-net/assets/20270743/64eedd39-a63b-4d62-8bfe-f78623ae270d)

### Expected behavior

devcontainer should open successfully

### Actual behavior

exceptions occur and devcontainer fails to open

### Reproduction Steps

follow steps in Contributing.md

### Environment

Windows
VS Code: 1.84.2
VS Code Insiders: 1.85.0-insider

**Comment by jsquire** [comment]
Thanks, @brandonh-msft.   We'll take a look at getting this fixed up.
