### ISSUE TITLE
[BUG] WebApiSkill is still missing the authResourceId property 

### ISSUE THREAD

**Issue by iulianmarius** [Azure/azure-sdk-for-net#40461]
### Library name and version

Azure.Search.Documents.Indexes.Models 11.5.1

### Describe the bug

I have the same problem as i described in https://github.com/Azure/azure-sdk-for-net/issues/35302 . It actualy never been fixed.
The authResourceId Property that is used with a managed identity is not available. I am not able to set the authResourceId when i create a WebApiSkill with the .Net SDK.

### Expected behavior

it should be possible to set the authResourceId

### Actual behavior

cannot set authResourceId

### Reproduction Steps

create a new WebApiSkill() and check for presence of the property

**Comment by jsquire** [comment]
@ShivangiReja:  Is there an alternative that could be used for the stable API?

**Comment by iulianmarius** [comment]
@jsquire thanks for the answear. I see the problem - this but this is a big impediment because we currently need to set the authResourceId manually in azure portal and we cannot automate the infrastructure as needed ... 
I hope this will get into stable soon...

Thanks,
Iulian

**Comment by ShivangiReja** [comment]
@iulianmarius, as I mentioned [here](https://github.com/Azure/azure-sdk-for-net/issues/35302#issuecomment-1631585766), the property [authResourceId](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/search/data-plane/Azure.Search/preview/2023-10-01-Preview/searchservice.json#L9390) has been introduced in the [Azure.Search.Documents@11.5.0-beta.3](https://www.nuget.org/packages/Azure.Search.Documents/11.5.0-beta.3) package and will be available in future preview versions. However, it is not supported in stable versions.

@mattmsft, does the "2023-11-01" API version support [WebApiSkill.authResourceId](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/search/data-plane/Azure.Search/stable/2023-11-01/searchservice.json#L8249)? Is it possible that it supports this property, but it's missing in the swagger, or is this property only supported in the  "2023-10-01-Preview" preview API version?

**Comment by ShivangiReja** [comment]
This request is specifically for the service team, and the SDK can only incorporate features that are supported by the service. If you have any questions related to the search service, please raise an issue at [Azure Search · Community](https://feedback.azure.com/d365community/forum/9325d19e-0225-ec11-b6e6-000d3a4f07b8). For any SDK-related questions, feel free to create issues on [Azure SDK for .NET Github](https://github.com/Azure/azure-sdk-for-net/issues).
