### ISSUE TITLE
[BUG] Change of Api version not being reflected when using SetApiVersion for configurationAssignment in Microsoft.Maintenance

### ISSUE THREAD

**Issue by akansha18rohilla** [Azure/azure-sdk-for-net#40511]
### Library name and version

Azure.ResourceManager.Maintenance 1.2.0-beta.4

### Describe the bug

Using SetApiVersion to override version using SDK libraries like so
```csharp
ArmClient Client { get; set; }
ArmClientOptions clientOptions = new ArmClientOptions(){Environment = environment };
clientOptions.SetApiVersion(new ResourceType("Microsoft.Maintenance/configurationAssignments"), "2021-05-01");
Client = new ArmClient(cred, subscriptionId, clientOptions);
```
Using the following code for creating the configuration assignment
```csharp
await resourceGroupResource.CreateOrUpdateConfigurationAssignmentAsync(ProviderName, ResourceType, VMSSResourceName, VMSSConfigurationAssignmentName, data);
```
Getting an exception while making the call which shows that the version was not overridden. The error is expected as the endpoint I'm calling does not support this version.

---------------

## Further Information

Upon debugging I saw that the ApiVersionOverrides property of the ArmClient is being populated correctly

The issue is that the ResourceGroupResourceExtensionClient is not initializing the ConfigurationAssignmentsRestClient object with the correct ApiVersion, instead the default constructor is being used [default _apiVersion](https://github.com/Azure/azure-sdk-for-net/blob/6bc542b5d1ec2e896a956a475be0c14c4927b466/sdk/maintenance/Azure.ResourceManager.Maintenance/src/Generated/RestOperations/MaintenanceConfigurationsRestOperations.cs#L36)

Code:
"`private ConfigurationAssignmentsRestOperations ConfigurationAssignmentsRestClient => _configurationAssignmentsRestClient ??= new ConfigurationAssignmentsRestOperations(Pipeline, Diagnostics.ApplicationId, Endpoint);`" 

![image](https://github.com/Azure/azure-sdk-for-net/assets/144460991/e2573b22-56d7-46a5-b259-139bf9d86bec)

Reference of the above code [ResourceGroupResourceExtensionClient.cs#L49](https://github.com/Azure/azure-sdk-for-net/blob/Azure.ResourceManager.Maintenance_1.2.0-beta.4/sdk/maintenance/Azure.ResourceManager.Maintenance/src/Generated/Extensions/ResourceGroupResourceExtensionClient.cs#L49)

ConfigurationAssignmentsRestClient is being used to call the CreateOrUpdateAsync of configurationAssignments

![image](https://github.com/Azure/azure-sdk-for-net/assets/144460991/36cf207f-7d8c-4841-9f5d-f5538acb5beb)

Reference of the above code [ResourceGroupResourceExtensionClient.cs#L554](https://github.com/Azure/azure-sdk-for-net/blob/6bc542b5d1ec2e896a956a475be0c14c4927b466/sdk/maintenance/Azure.ResourceManager.Maintenance/src/Generated/Extensions/ResourceGroupResourceExtensionClient.cs#L554C17-L554C21)

The autorest.md file indicates that the code is auto generated so this might not be the right place to look for such errors.

---------------

### Expected behavior

After calling SetApiVersion, The specified version should be sent in the request while making the call to configurationAssignments.

### Actual behavior

The default Api version ('2023-04-01' in this case) is being sent in the request. 

### Reproduction Steps

```csharp
ArmClient Client { get; set; }
ArmClientOptions clientOptions = new ArmClientOptions(){Environment = environment };
clientOptions.SetApiVersion(new ResourceType("Microsoft.Maintenance/configurationAssignments"), "2021-05-01");
Client = new ArmClient(cred, subscriptionId, clientOptions);
```
Using the following code for creating the configuration assignment
```csharp
await resourceGroupResource.CreateOrUpdateConfigurationAssignmentAsync(ProviderName, ResourceType, VMSSResourceName, VMSSConfigurationAssignmentName, data);
```

**Comment by akansha18rohilla** [comment]
## For the Reference
MaintenanceConfiguration in Microsoft.Maintenance working fine, it is using the specified Api version to request which I set using setApiVersion

`clientOptions.SetApiVersion(new ResourceType("Microsoft.Maintenance/maintenanceConfigurations"), "2021-05-01");`

 It is initializing the _maintenanceConfigurationRestClient object with the correct ApiVersion using that TryGetApiVersion

![image](https://github.com/Azure/azure-sdk-for-net/assets/144460991/8792118a-7f67-452f-b4dd-e6a97aa25d04)

Reference of the above code [MaintenanceConfigurationCollection.cs#L47](https://github.com/Azure/azure-sdk-for-net/blob/6bc542b5d1ec2e896a956a475be0c14c4927b466/sdk/maintenance/Azure.ResourceManager.Maintenance/src/Generated/MaintenanceConfigurationCollection.cs#L47C13-L47C49)

and then this client object is being used to create maintenanceConfiguration

![image](https://github.com/Azure/azure-sdk-for-net/assets/144460991/dd1b56ff-ea66-4bd3-b7a6-b72ef0ce7f23)

Reference of the above code [MaintenanceConfigurationCollection.cs#L90](https://github.com/Azure/azure-sdk-for-net/blob/6bc542b5d1ec2e896a956a475be0c14c4927b466/sdk/maintenance/Azure.ResourceManager.Maintenance/src/Generated/MaintenanceConfigurationCollection.cs#L90)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
New version released contains the fix: https://www.nuget.org/packages/Azure.ResourceManager.Maintenance/1.2.0-beta.7
