### ISSUE TITLE
Add a delegate to support resources without a trailing slash

### ISSUE THREAD

**Issue by jianghaolu** [Azure/azure-sdk-for-net#4051]
In https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SdkCommon/ClientRuntime.Azure.Authentication/ApplicationTokenProvider.cs, there are a few places we are calling `settings.TokenAudience.ToString()`.

In case of Key Vault, the resource must be "https://vault.azure.net" without a trailing slash. This doesn't work with Key Vault since `.ToString()` always adds a trailing slash.

**Comment by adrianhall** [comment]
Hello, my apologies for this taking so long.  Is this still an issue?
