### ISSUE TITLE
[FEATURE REQ] Azure Monitor Distro client library not logging RoleName properly for traces and exceptions

### ISSUE THREAD

**Issue by joshdanko** [Azure/azure-sdk-for-net#40558]
### Library name and version

Azure.Monitor.OpenTelemetry.AspNetCore 1.0.0

### Describe the bug

Requests, dependencies, customEvents and metrics all set the RoleName and RoleInstance properly when using the below code to set the resource values for service.name, servicenamespace and service.instance.id.  However, traces and exceptions do not use these values and instead use the detected values. 

```csharp
var resourceAttributes = new Dictionary<string, object> {
    { "service.name", "svc" },
    { "service.namespace", "ns" },
    { "service.instance.id", Dns.GetHostName() }};
builder.Services.ConfigureOpenTelemetryTracerProvider((sp, builder) =>
{
    builder.ConfigureResource(resourceBuilder =>
    {
        resourceBuilder.AddAttributes(resourceAttributes);
    });
});
```

I am able to override this by using the code below i found here in the source: [Extension Method](https://github.com/Azure/azure-sdk-for-net/blob/aeb79ef7c1d619da2e6fd6402a72b21c633f7a2d/sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/src/OpenTelemetryBuilderExtensions.cs#L108C25-L108C41)

```csharp
builder.Services.AddLogging(logging =>
{
    logging.AddOpenTelemetry(builderOptions =>
    {
        var resourceBuilder = ResourceBuilder.CreateDefault();
        resourceBuilder.AddAttributes(resourceAttributes);
        builderOptions.SetResourceBuilder(resourceBuilder);
        builderOptions.IncludeFormattedMessage = true;
        builderOptions.IncludeScopes = false;
    });
});
```

### Expected behavior

Expecting ILogger implementation to use configured resource values instead of the ones auto detected similar to the requests, dependencies, etc.

### Actual behavior

Without overriding OpenTelemetry logging the roleName does not show up correctly 

### Reproduction Steps

Simple application using the Azure Monitor Distro client library and attempt to use an ILogger to log traces or exceptions will result in missing rolename defined.

### Environment

Windows 10
.NET 8.0.100
Azure Application Insights
Azure.Monitor.OpenTelemetry.AspNetCore 1.0.0

**Comment by rajkumar-rangaraj** [comment]
`OpenTelemetry.Extensions.Hosting` marked `ConfigureOpenTelemetryLoggerProvider` as experimental as part of their GA release. Once this API is stabilized, it will be included in the distro to modify log resources.

https://github.com/open-telemetry/opentelemetry-dotnet/blob/65dd83b44eed8d24fa0f60f592192573dd2d0f6a/src/OpenTelemetry.Extensions.Hosting/OpenTelemetryBuilder.cs#L61

**Comment by ChristopherL-STCU** [comment]
@joshdanko this is off topic, but I noticed you mentioned "customEvents" in your issue report. Are you able to send data to the "customEvents" table using OTel? If so can you share an example?

**Comment by cijothomas** [comment]
> @joshdanko this is off topic, but I noticed you mentioned "customEvents" in your issue report. Are you able to send data to the "customEvents" table using OTel? If so can you share an example?

Not supported today.

**Comment by TimothyMothra** [comment]
> @joshdanko this is off topic, but I noticed you mentioned "customEvents" in your issue report. Are you able to send data to the "customEvents" table using OTel? If so can you share an example?

We're tracking CustomEvents in a separate issue. Please upvote here: https://github.com/Azure/azure-sdk-for-net/issues/42157#issuecomment-1967297360
