### ISSUE TITLE
[QUERY] Azure.AI.OpenAI_1.0.0-beta.10 no longer exposes message content on base ChatRequestMessage

### ISSUE THREAD

**Issue by chrisbardon** [Azure/azure-sdk-for-net#40634]
### Library name and version

Azure.AI.OpenAI_1.0.0-beta.10

### Query/Question

In the previous beta, ChatRequestMessage exposed a Content property that you could use to work with a collection.  In my case, I had something like this:

```
List<ChatMessage> _chatMessages = new();
int tokenCount = 0;
foreach (ChatMessage m in _chatMessages)
    tokenCount += TokenCounter.CountTokens(m.Content);
```
to estimate the size of the conversation history before sending a subsequent chat request.  With the new version, I have to cast the types, and there's the issue that ChatRequestUserMessage hides the content property.  I saw the note in ChatRequestUserMessage about multimedia content, which makes some degree of sense, however it makes operations like this, which is an experiment that attempts to reduce the size of text content, much more difficult:
```
foreach (ChatMessage m in _chatMessages.OrderByDescending(c => TokenCounter.CountTokens(c.Content)))
{
    List<ChatMessage> msgs = new();
    msgs.Add(new ChatMessage(ChatRole.System, $"reduce the number of tokens in this prompt by half without losing meaning:{m.Content}"));
    var comp = await _openAIClient.GetChatCompletionsAsync("chat", new ChatCompletionsOptions(msgs));
    int oldTokens = TokenCounter.CountTokens(m.Content);
    if (comp?.Value.Choices.Count > 0)
    {
        m.Content = comp.Value.Choices[0].Message.Content;
    }
    int newTokens = TokenCounter.CountTokens(m.Content);
    tokenCount -= (oldTokens - newTokens);
    if (tokenCount < tokenLimit)
    {
        AppendChatMessage("SYSTEM", $"reduced prompt from {originalTokenCount} to {tokenCount}");
        return tokenCount;
    }
}
```
I tried to write an extension method to deal with this, but it appears that ChatRequestUserMessage doesn't expose its content at all?  SerializeContent(Utf8JsonWriter writer) is marked as internal.  

Is there a suggested method to do this now?  

### Environment

VS Enterprise 17.8.2, .net 7

**Comment by trrwilson** [comment]
Thank you for getting in touch, and so soon after the latest beta release!

This is a painful but intended consequence of the expanded message hierarchy that the OpenAI APIs have introduced to support `gpt-4-vision-preview` and Tools features. You can see their API reference here: https://platform.openai.com/docs/api-reference/chat/create#chat-create-messages

As you'll see from the derived/discriminated message types, function and tool messages don't contain content (but do contain other required properties) while system, assistant, and user do contain content as a required property.

The extra "gotcha" for user messages comes from the new vision-enabled variant of the API:
https://platform.openai.com/docs/guides/vision/quick-start

In that schema, user messages can have "content" that's either the traditional string *or* an array of individual content objects that can be text or video. So there's no simple get/set of "content" as there used to be and we internalize the multiplexing into BinaryData for serialization.

Potential approaches I see that could make this easier (than needing to retain the content yourself when you just want to propagate it later) include:

- Forking `ChatRequestUserMessage` *another* layer, e.g. into `ChatRequestUserTextMessage` and `ChatRequestUserContentCollectionMessage`, to keep the responsibilities distinct
- Adding instance methods like `GetStringContent()` and `GetContentItems()` that could take the place of the previous property getters

Given that need to represent both content forms, would the above or another option seem like good improvements to you? Your feedback is very much appreciated!

**Comment by chrisbardon** [comment]
Hi @trrwilson -I saw the change you made, and that definitely helps, but a couple of suggestions:
-If the Content property is surfaced on the base ChatRequestMessage, then you wouldn't have to cast like this:
```
            StringBuilder sb = new StringBuilder();
            //serialize
            foreach (ChatRequestMessage msg in _messages)
            {
                if(msg is ChatRequestUserMessage)
                    sb.Append(((ChatRequestUserMessage)msg).Content);
                else if(msg is ChatRequestSystemMessage)
                    sb.Append(((ChatRequestSystemMessage)msg).Content);
                else if(msg is ChatRequestAssistantMessage)
                    sb.Append(((ChatRequestAssistantMessage)msg).Content);
                else if(msg is ChatRequestToolMessage)
                    sb.Append(((ChatRequestToolMessage)msg).Content);
            }
```
-Making Content read/write would be useful for modifying history
