### ISSUE TITLE
[BUG] Logging Exception with Outer Message shows Outermessage and inner message to be the same

### ISSUE THREAD

**Issue by joebeernink** [Azure/azure-sdk-for-net#40633]
### Library name and version

Azure.Monitor.OpenTelemetry.Exporter Version="1.0.0"

### Describe the bug

When logging an exception to Log Analytics using the Azure.Monitor.OpenTelemetry.Exporter, with an additional message, the additional message should appear in the outer message field, and the exception in the inner message, but the outer message is always set to the inner message.

``` csharp                   
                        try
                        {
                               throw new ArgumentNullException("Test");
                        }
                        catch (Exception ex)
                        {
                            Logger.LogError(ex, "This should be the outer message {MessageValue}", "test");
                        }

```

### Expected behavior

The additional message should appear in the outer message field, and the exception in the inner message

### Actual behavior

The outer message is always set to the exception message

A sample from out Azure Monitor logs. 
![image](https://github.com/Azure/azure-sdk-for-net/assets/3885965/eb2991c1-1f70-4ab7-9247-6c0a53c45996)

### Reproduction Steps

``` csharp                   
                        try
                        {
                               throw new ArgumentNullException("Test");
                        }
                        catch (Exception ex)
                        {
                            Logger.LogError(ex, "This should be the outer message {MessageValue}", "test");
                        }

```

**Comment by cijothomas** [comment]
>  Logger.LogError(ex, "This should be the outer message {MessageValue}", "test");

_"This should be the outer message {MessageValue}"_ text is not part of the Exception itself, so in the ExceptionTelemetry table, it gets stored in the customDimensions! The inner/outer is purely derived from the Exception instance itself. Not sure what is the right fix here.. One possibility is to send both TraceTelemetry and ExceptionTelemetry , and TraceTelemetry can store the "This should be the outer message {MessageValue}" as its Message, and ExceptionTelemetry can store its part as before. This incurs extra cost, so may not be a good default choice either :(

**Comment by joebeernink** [comment]
What we're doing now is to do a LogInformation with the message, and then do a LogException with the exception. Which means two calls for each exception (which isn't that big of a deal code or Azure cost wise), but correlating the two log lines is a huge deal when researching a problem. So extra cost from an Azure perspective is miniscule compared to the cost of the time it takes for a dev to identify the real cause of a problem and mitigate it.

When you talk about the TraceTelemetry and ExceptionTelemetry tables, I'm guessing those are in the backing store for the logs (Geneva?) and never surfaced to the Azure Monitor users? I don't see anything in the Properties column of the AppExceptions table in LogAnalytics either... 

Is there a way to add a traceId/span id to the two records to at least make it easy to query the matching tracelog with exception log to solve the correlation issue?

**Comment by cijothomas** [comment]
> Is there a way to add a traceId/span id to the two records to at least make it easy to query the matching tracelog with exception log to solve the correlation issue?

They all should already be automatically correlated!

**Comment by joebeernink** [comment]
I'm not sure how they already can be... since they are two separate logging statements. Or do you mean they are correlated from an inbound http request perspective? Unfortunately, that's not a valid assumption in this case, as the calling application is a batch application that is calling an http endpoint, and is the client, not the service, so there is no overall request context here to correlate with.

Or is there another way to mark two log statements with a common traceid that I am missing?

**Comment by cijothomas** [comment]
>  Or do you mean they are correlated from an inbound http request perspective?

Yes thats what I meant. It need not be an HttpRequest. Any `Activity` is good enough. Log statements made inside the context of same Activity, will get same traceid,spanid allowing it to be correlated. Looks like you have a custom scenario where there is no parent Activity itself?

**Comment by joebeernink** [comment]
We haven't used a lot of activities... usually a single log statement will do. But if we now need to surround every LogError with an activity and add a LogInfo into the code for every logerror... I guess that's what we'll do... though I'll probably extract that into a custom ILogger implementation to abstract that... but this is soooo ugly... Basically we're saying the LogError(ex, message) doesn't work with OpenTelemetry for Azure Monitor. Or am I still misunderstanding the issue? Let me know if it would be useful to chat in Teams.

**Comment by cijothomas** [comment]
> LogError(ex, message) doesn't work with OpenTelemetry for Azure Monitor

That is an incorrect statement. 
When you emit an exception *and* a message (different than the Exception.Message), with a single Log statement, there is now 2 messages competing for top spot - the one from Message itself, and the one from Exception.Message! Its unclear what would be the right solution here - some users might prefer the Exception.Message, other might prefer the log Message.

**Comment by joebeernink** [comment]
But there is currently no way in Azure Log Analytics (AppExceptions table) or App Insights (exceptions table) to view the message emitted via LogError, correct? Is there a table where I can see the message that I just haven't tried yet?

**Comment by cijothomas** [comment]
> But there is currently no way in Azure Log Analytics (AppExceptions table) or App Insights (exceptions table) to view the message emitted via LogError, correct?

If that is the case, then it could be treated as a bug. It should be exported! Only question is whether that message should take the top spot OR be put under custom_dimensions column. Have you confirmed it is not part of custom_dimensions as well ?

**Comment by joebeernink** [comment]
Assuming that the "custom_dimensions" field is mapped to the "properties" collection in the AppExceptions table, then I have verified that the message is not there. I see no other fields on the AppExceptions table.

I do see the ResourceAttributes added through the SetResourceBuilder call when instantiating the log provider, but the message from the logger call itself is not there.

![image](https://github.com/Azure/azure-sdk-for-net/assets/3885965/1249527f-7171-4a31-849b-48e37a7a11db)

**Comment by cijothomas** [comment]
^ This looks like a bug.  @rajkumar-rangaraj can you confirm if you see this behavior where the logger message is not even in the Properties?

**Comment by rajkumar-rangaraj** [comment]
I used the code snippet from the issue and was able to see the logger message in the properties of the AppExceptions table

![image](https://github.com/Azure/azure-sdk-for-net/assets/9479006/f85070e6-5dcf-4539-b9f5-5201aa7cbe71)

@joebeernink Could you please help me with a small repro of this issue?

**Comment by joebeernink** [comment]
As always happens, as soon as you get the professionals involved, you find the root cause of the issue...

We had a CustomLogEnrichmentProcessor hidden under the covers that was doing the following:

``` csharp
    public override void OnEnd(LogRecord data)
    {
        data.Attributes = _contextValues;
    }
```
Which was replacing all of the existing attributes with only the context attributes.

It should have been

``` csharp
    public override void OnEnd(LogRecord data)
    {
        var attributes = data.Attributes?.ToList() ?? [];
        attributes.AddRange(_contextValues!);

        data.Attributes = attributes!;
    }
```
    
Thank you for helping me with this one. I'll close this issue and consider it user error.
