### ISSUE TITLE
Unnecessary byte array is allocated when trying to decode a string

### ISSUE THREAD

**Issue by FeiboChen** [Azure/azure-sdk-for-net#4064]
Hi,

I noticed that when decoding a string, Avro always tries to read the data into a temp byte array, then decode from the byte array to the dest string. This is not efficient and may increase the working set of the process if too many deserialations happens in a short time. Can we try to remove the temp byte array to improve the perf?

Here's the source code:
        /// <summary>
        /// Decodes a byte array.
        /// </summary>
        /// <returns>
        /// Decoded value.
        /// </returns>
        public byte[] DecodeByteArray()
        {
            int arraySize = this.DecodeInt();
            **var array = new byte[arraySize];**
            this.ReadAllRequiredBytes(array);
            return array;
        }

        /// <summary>
        /// Decodes a string value.
        /// </summary>
        /// <returns>
        /// Decoded value.
        /// </returns>
        public string DecodeString()
        {
            **return Encoding.UTF8.GetString(this.DecodeByteArray());**
        }

https://msazure.visualstudio.com/DefaultCollection/One/_git/Rome-Detection-ColdPath?path=%2Fsrc%2FMicrosoft.Hadoop.Avro%2FEncoders%2FBinaryDecoder.cs&version=GBmaster&_a=contents&line=157&lineStyle=plain&lineEnd=180&lineStartColumn=1&lineEndColumn=10

**Comment by dsgouda** [comment]
Assigning it to @wawon-msft since they made the last commits to HDInsight SDK, feel free to reassign it to the appropriate personnel

**Comment by tylerfox** [comment]
The Avro SDK is no longer supported by Microsoft.
