### ISSUE TITLE
Convert to TSP for SpringAppDiscovery

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/azure-sdk-for-net#40689]
https://github.com/Azure/azure-rest-api-specs-pr/tree/RPSaaSMaster/specification/offazurespringboot/resource-manager

**Comment by HarveyLink** [comment]
https://github.com/Azure/azure-rest-api-specs-pr/pull/16410

**Comment by HarveyLink** [comment]
Closed as completed
