### ISSUE TITLE
Not able to migrate AbandonAsync of Microsoft.Azure.ServiceBus to AbandonMessageAsync of Azure.Messaging.ServiceBus

### ISSUE THREAD

**Issue by beingsangam** [Azure/azure-sdk-for-net#40690]
### Library name and version

Azure.Messaging.ServiceBus, 7.17.1

### Query/Question

private async Task AbondonMessagesFromAllQueuesAsync(
    IMessageReceiver messageReceiver,
    ConcurrentDictionary<string, T> lockTokenMessageMap)
{
    if (messageReceiver.IsClosedOrClosing)
    {
        return;
    }

    foreach (KeyValuePair<string, T> lockTokenMessagePair in lockTokenMessageMap)
    {
        try
        {
            await messageReceiver.AbandonAsync(lockTokenMessagePair.Key);
        }
        catch (Exception ex)
        {
            this.logger.LogException(ex, "Lock has expired ");
        }
    }
}
I have the above code that I am trying to migrate to Azure.Messaging.ServiceBus, now it has AbandonMessageAsync in place of AbandonAsync that accepts parameter of type ServiceBusReceivedMessage but previously it was being used as a string locktoken, so how can I solve the issue.

### Environment

.Net

**Comment by jsquire** [comment]
Hi @beingsangam.  Thank you for reaching out and we regret that you're experiencing difficulties.   The intent is that you'll pass in the `ServiceBusReceivedMessage` that your application is processing.   There's not enough context to understand your end-to-end scenario, but it seems that you're collecting lock tokens in bulk for some reason.

In that case, you'll want to use the approach discussed in [Storing only the lock token](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample16_CrossReceiverMessageSettlement.md#storing-only-the-lock-token):

```csharp
// Saving the lock token bytes
ServiceBusReceivedMessage receivedMessage = await receiver.ReceiveMessageAsync();
ReadOnlyMemory<byte> lockTokenBytes = Guid.Parse(receivedMessage.LockToken).ToByteArray();

// Creating an artificial message to settle for a given lock token
ServiceBusReceivedMessage rehydratedMessage = ServiceBusModelFactory.ServiceBusReceivedMessage(lockTokenGuid: new Guid(lockTokenBytes.ToArray()));
await receiver.AbandonMessageAsync (rehydratedMessage);
```
