### ISSUE TITLE
[QUERY] Is HttpPipeline supported for handwritten/custom requests?

### ISSUE THREAD

**Issue by kalbert312** [Azure/azure-sdk-for-net#40700]
### Library name and version

Azure.Core 1.35.0

### Query/Question

I am wondering if `HttpPipeline` is supported to be used for hand-written scenarios. I want to reuse all of the default policies and flow that SDK clients use for custom requests that the SDK does not support. Because all of the necessary APIs are public and after some brief issue searching, I assume yes, but I also have some worries:

- It's currently consumed by all SDK clients and feels like an internal implementation because of that.
- Will its public API be stable over time?
  - It's consumed by generated code which could increase the likelihood of breaking changes because altering the output of generated code is easier than migrating manually written code.
- There didn't seem to be support for a base URI feature so I added a custom policy to set this on my `HttpPipeline`, but changes to the implementation regarding the ordering of policies in `HttpPipelineBuilder` could break this. The generated code explicitly sets a base URI on requests.
- I didn't see any explicit mention in the places that I looked that this is supported for hand-written scenarios.

**Comment by jsquire** [comment]
Hi @kalbert312.   Thank you for reaching out.   To answer your question - the Azure SDK libraries, including Azure Core, have strict backwards compatibility guarantees as discussed in the [.NET Azure SDK Design Guidelines](https://azure.github.io/azure-sdk/dotnet_introduction.html).   While Azure Core is primarily intended to provide infrastructure for Azure SDK libraries and optimized for Azure patterns, using it for other scenarios is a valid and supported scenario.   More information around the built-in policies and requirements for Azure Core itself can be found in [General Guidelines: Azure Core](https://azure.github.io/azure-sdk/general_azurecore.html).

Looping in @KrzysztofCwalina and @tg-msft, in case either has additional perspective they'd like to share.
