### ISSUE TITLE
[FEATURE REQ] SchemaRegistryClient : Get Schema or SchemaId using GroupName and SchemaName

### ISSUE THREAD

**Issue by devsmart** [Azure/azure-sdk-for-net#40711]
### Library name

Microsoft.Azure.Data.SchemaRegistry.ApacheAvro

### Please describe the feature.

Current .Net SDK only supports getting `SchemaRegistryClient.GetSchemaPropertiesAsync`. Which required the schema definition. Can We expose getting the schema like using the REST API below?
```
https://{EventHubName}.servicebus.windows.net/$schemagroups/{groupName}/schemas/{schemaName}?api-version=2023-07-01
``` 

OR how we can extend the features on the SDK user/consumer side rather than changing SDK-related code?

**Comment by devsmart** [comment]
I was expecting something like this :)

```
using Azure;
using Azure.Core;
using Azure.Core.Pipeline;
using Azure.Data.SchemaRegistry;

namespace ApacheAveroDemo;

internal class SchemaRegistryClientExt : SchemaRegistryClient
{
    private const string CredentialScope = "https://eventhubs.azure.net/.default";
    private readonly HttpPipeline _pipeline;
    private const string ApiVersion = "2023-07-01";

    public SchemaRegistryClientExt(string fullyQualifiedNamespace, TokenCredential credential) : base(fullyQualifiedNamespace, credential)
    {
        _pipeline = HttpPipelineBuilder.Build(new SchemaRegistryClientOptions(), new BearerTokenAuthenticationPolicy(credential, CredentialScope));
    }

    internal HttpMessage CreateGetSchemaByGroupAndNameRequest(string group, string name)
    {
        var message = _pipeline.CreateMessage();
        var request = message.Request;
        request.Method = RequestMethod.Get;
        var uri = new RequestUriBuilder();
        uri.Reset(new Uri($"https://{FullyQualifiedNamespace}"));
        uri.AppendPath($"$schemaGroups/{group}/schemas/{name}", false);
        uri.AppendQuery("api-version", ApiVersion);
        request.Uri = uri;
        request.Headers.Add("Accept", "application/json; serialization=Avro, application/json; serialization=json, application/octet-stream");
        return message;
    }

    // Return string for now
    public async Task<string> GetSchemaByGroupAndNameAsync(string group, string name, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(group);
        ArgumentNullException.ThrowIfNull(name);

        using var message = CreateGetSchemaByGroupAndNameRequest(group, name);
        await _pipeline.SendAsync(message, cancellationToken).ConfigureAwait(false);

        switch (message.Response.Status)
        {
            case 200:
                {
                    var value = message.ExtractResponseContent() ?? throw new RequestFailedException("Cannot find the content.");
                    return BinaryData.FromStream(value).ToString();
                }
            default:
                throw new RequestFailedException(message.Response);
        }
    }
}


```

**Comment by jsquire** [comment]
Hi @devsmart.  Thank you for your feedback.  The Schema Registry service specification does not support issuing a GET against the path `/$schemaGroups/{groupName}/schemas/{schemaName}`.  By spec, that path is only to be used with PUT for the purposes of creating a new schema.  _([reference](https://github.com/Azure/azure-rest-api-specs/blob/c364b64a6b412ffd7507dea71ae53251d35748c1/specification/schemaregistry/data-plane/Microsoft.EventHub/stable/2023-07-01/schemaregistry.json#L395))_  

The Azure SDK clients only expose service operations which are officially supported by the service and which are documented as part of its public contract.  Should the Schema Registry service decide to support this operation as part of its specification, it will be added to the Schema Registry client library.   Your best path forward for requesting service support would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) or post on the [Event Hubs forum](https://feedback.azure.com/d365community/forum/86c37ae9-7526-ec11-b6e6-000d3a4f032c) of the Azure feedback site.

**Comment by devsmart** [comment]
@jsquire Thanks for the prompt response! I'll raise there :)
