### ISSUE TITLE
[FEATURE REQ] Provide a IFileProvider Implementation for Blob Store Access

### ISSUE THREAD

**Issue by drothmaler** [Azure/azure-sdk-for-net#40750]
### Library name

Azure.Storage.Blobs

### Please describe the feature.

ASP.NET Core had the concept of [file providers](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/file-providers) for quite some time now.

It would be nice, if the SDK would provide an implementation of the [IFileProvider interface](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.fileproviders.ifileprovider) out of the box. 

While there is a [3rd party implementation](https://www.nuget.org/packages/WaterTrans.AzureBlobFileProvider) of it, it's not very well maintained and seems pretty outdated...

**Comment by seanmcc-msft** [comment]
Related - https://github.com/Azure/azure-sdk-for-net/issues/40884

@drothmaler, thanks for the feature request. This would be a relatively larger undertaking, and .NET SDK Storage team is heads down on other work. This is something we could possible consider in the future if many customer are asking for this feature.
