### ISSUE TITLE
[FEATURE REQ] Support extra header in OpenAI LLM sdk like Python openai sdk did

### ISSUE THREAD

**Issue by zemaMSFT** [Azure/azure-sdk-for-net#40782]
### Library name

Azure.AI.OpenAI

### Please describe the feature.

hi, OpenAI .Net sdk developper, we know that in python sdk openai, there is a way to add extra header directly in chat/completion api, but seems in Azure.AI.OpenAI .net sdk, there is no such feature support, is there any plan to support it?

below is the python invocation sample:
`import openai

openai.api_key = "your-api-key"

response = openai.Completion.create(
  engine="text-davinci-002",
  prompt="Translate the following English text to French: '{\"role\": \"system\", \"content\": \"You are a helpful assistant.\"}'",
  max_tokens=60,
  **headers={"Extra-Header": "Extra-Value"}**
)`

**Comment by jsquire** [comment]
Hi @zemaMSFT.  Thank you for reaching out and for your question.  Manipulating the raw HTTP request shape, including adding arbitrary headers, is done by interacting with the Azure.Core HttpPipeline in .NET.  An example of injecting a custom header using a pipeline policy can be found in the [Implementing a synchronous policy sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Pipeline.md#implementing-a-synchronous-policy).

**Comment by zemaMSFT** [comment]
thanks @jsquire !
