### ISSUE TITLE
How to authenticate to Azure Container Instance use Service Principal and ManagedIdentity using Azure.ResourceManager.ContainerInstance [QUERY]

### ISSUE THREAD

**Issue by groogiam** [Azure/azure-sdk-for-net#40789]
### Library name and version

Azure.ResourceManager.ContainerInstance 1.2.0

### Query/Question

When creating an Azure Container Instance I am having trouble authentication to an ACR use a service principal or managed credential. I can get it to working using the ACR admin user, but that is not as secure. Ideally I would like to authenticate using the same service principal my ArmClient is using? Second best option would be a managed identity. Would it be possible to provide a sample showing how to do this.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi @groogiam , thank you for using Azure SDK for .NET.
If you would like to assign permission to some resource, you should use [Azure.ResourceManager.Authorization](https://www.nuget.org/packages/Azure.ResourceManager.Authorization)
Sample code would like:
```
    var roleId = new ResourceIdentifier("roleDefinitionId");
    var data = new RoleAssignmentCreateOrUpdateContent(roleId, Guid.Parse("principalId"));
    var assignment = (await acr.GetRoleAssignments().CreateOrUpdateAsync(WaitUntil.Completed, Guid.NewGuid().ToString(), data)).Value;
```

**Comment by groogiam** [comment]
> Hi @groogiam , thank you for using Azure SDK for .NET. If you would like to assign permission to some resource, you should use [Azure.ResourceManager.Authorization](https://www.nuget.org/packages/Azure.ResourceManager.Authorization) Sample code would like:
> 
> ```
>     var roleId = new ResourceIdentifier("roleDefinitionId");
>     var data = new RoleAssignmentCreateOrUpdateContent(roleId, Guid.Parse("principalId"));
>     var assignment = (await acr.GetRoleAssignments().CreateOrUpdateAsync(WaitUntil.Completed, Guid.NewGuid().ToString(), data)).Value;
> ```

This does not answer the question. When you create a container app you have to tell it how to authentic to the container repository. I am asking how this can be done in the API using a managed credentials or service principle. My question is not asking how to assign the identity or service principal to have read permissions to the acr via the API which is what your answer appears to be focused on. The answer I am looking for would be the 2 container app update calls with the specifics of setting the container repository credentials for a manged identity and service principal respectively. Thanks.

**Comment by HarveyLink** [comment]
> > Hi @groogiam , thank you for using Azure SDK for .NET. If you would like to assign permission to some resource, you should use [Azure.ResourceManager.Authorization](https://www.nuget.org/packages/Azure.ResourceManager.Authorization) Sample code would like:
> > ```
> >     var roleId = new ResourceIdentifier("roleDefinitionId");
> >     var data = new RoleAssignmentCreateOrUpdateContent(roleId, Guid.Parse("principalId"));
> >     var assignment = (await acr.GetRoleAssignments().CreateOrUpdateAsync(WaitUntil.Completed, Guid.NewGuid().ToString(), data)).Value;
> > ```
> 
> This does not answer the question. When you create a container app you have to tell it how to authentic to the container repository. I am asking how this can be done in the API using a managed credentials or service principle. My question is not asking how to assign the identity or service principal to have read permissions to the acr via the API which is what your answer appears to be focused on. The answer I am looking for would be the 2 container app update calls with the specifics of setting the container repository credentials for a manged identity and service principal respectively. Thanks.

Based on your description, if you already have the role assignment done, you could add following property while creating a container group:
```
var data = new ContainerGroupData(....)
{
    ImageRegistryCredentials = 
    {
        new ContainerGroupImageRegistryCredential("acrServer")
        {
            Username = "service-principal-ID",
            Password = "service-principal-password"
        }
    },
...
}
```

**Comment by groogiam** [comment]
@HarveyLink Have you tested this with a service principal and managed identity. I tried and it does not seem to work. First off a managed identity does not have a password. If you don't pass a password to the call you get an error.

What is the password supposed to be for a service principal? Using the secret does not seem to work.

**Comment by HarveyLink** [comment]
> Author

Since lack of domian knowledge, I haven't go through the container instance + acr scenarios, but the service principal could login into the acr.
This could be easily tested in docker command line(password is the credential):
![image](https://github.com/Azure/azure-sdk-for-net/assets/30464227/122f20f2-561f-4c3a-8706-c95e149360a2)
If you have still have concerns, I could work out a complete sample for you.

**Comment by groogiam** [comment]
I should be able to verify the service principal functionality from your example. I still would like an example on how to make this work with a managed identity. Thanks.

**Comment by HarveyLink** [comment]
> managed credential.

Please following this document to understand the limitations and prerequisites.
https://learn.microsoft.com/en-us/azure/container-instances/using-azure-container-registry-mi
As the doc suggest, we could assgin the identity both in `identity` property and `imageRegistryCredentials` property part, which would make the code look like:
```
    var containerGroup = new ContainerGroupData(
      location: "westus",
      containers: containers,
      osType: ContainerInstanceOperatingSystemType.Linux)
    {
        Identity = new ManagedServiceIdentity(ManagedServiceIdentityType.UserAssigned)
        {
            UserAssignedIdentities =
            {
                { new ResourceIdentifier("uid"), new UserAssignedIdentity() }
            }
        },
        ImageRegistryCredentials =
        {
            new ContainerGroupImageRegistryCredential("myacr.azurecr.io")
            {
                Identity = "uid"
            }
        },
....
}
```
