### ISSUE TITLE
How to update ApplicationGroupReferences for an AVD workspace object? there property is read only and no constructor.

### ISSUE THREAD

**Issue by keweyt** [Azure/azure-sdk-for-net#40798]
https://github.com/Azure/azure-sdk-for-net/blob/0519b4112821b063cf84ebea922d9fd78a713b1b/sdk/desktopvirtualization/Azure.ResourceManager.DesktopVirtualization/src/Generated/VirtualWorkspaceData.cs#L26

**Comment by jsquire** [comment]
Hi @keweyt.  Thank you for reaching out and we regret that you're experiencing difficulties.   The Azure SDK pattern for collection types is that they read-only and initialized with an empty collection that can be modified.  This is based on the [Framework Design Guidelines - Guidelines for Collections](https://docs.microsoft.com/dotnet/standard/design-guidelines/guidelines-for-collections#collection-properties-and-return-values).   

These properties can be set by either using the initializer syntax or adding items to the collection.   For example, something like:

```csharp
// Manipulating the collection after construction
var data = new VirtualWorkspaceData(AzureLocation.EastUs);
data.ApplicationGroupReferences.Add("someGroup");
data.ApplicationGroupReferences.Add("otherGroup");

// Using collection initializers
var data = new VirtualWorkspaceData(AzureLocation.EastUs)
{
    ApplicationGroupReferences = { "someGroup", "otherGroup" }
}
```
