### ISSUE TITLE
[Container App Job] How to mount the volume to the azure file storage?

### ISSUE THREAD

**Issue by LuoyeAn** [Azure/azure-sdk-for-net#40797]
### Library name

Azure.ResourceManager.AppContainers

### Please describe the feature.

I would like to mount the volume to the azure file storage. 
Want to do following with the C# Azure.ResourceManager.AppContainers:
```
az containerapp env storage set --access-mode ReadWrite 
--azure-file-account-name $STORAGE_ACCOUNT_NAME 
--azure-file-account-key $STORAGE_ACCOUNT_KEY 
--azure-file-share-name $STORAGE_SHARE_NAME 
--storage-name $STORAGE_MOUNT_NAME 
--name $ENVIRONMENT_NAME 
--resource-group $RESOURCE_GROUP 
--output table
```

Content: https://learn.microsoft.com/en-us/azure/container-apps/storage-mounts-azure-files?tabs=bash#create-the-storage-mount

**Comment by mjqin** [comment]
Here is sample that might help you to mount the storage

```csharp
// You need to create a managed environment first
ContainerAppManagedEnvironmentResource _managedEnvironmentResource;

// Mount the storage for the environment
var storageData = new ContainerAppManagedEnvironmentStorageData()
            {
                ManagedEnvironmentStorageAzureFile = new ContainerAppAzureFileProperties()
                {
                    AccountName = accountName,
                    ShareName = shareName,
                    AccessMode = accessMode,
                    AccountKey = accessKey,
                },
            };

await _managedEnvironmentResource
    .GetContainerAppManagedEnvironmentStorages()
    .CreateOrUpdateAsync(WaitUntil.Completed, "storage-name", storageData);

```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by LuoyeAn** [comment]
> Here is sample that might help you to mount the storage
> 
> ```cs
> // You need to create a managed environment first
> ContainerAppManagedEnvironmentResource _managedEnvironmentResource;
> 
> // Mount the storage for the environment
> var storageData = new ContainerAppManagedEnvironmentStorageData()
>             {
>                 ManagedEnvironmentStorageAzureFile = new ContainerAppAzureFileProperties()
>                 {
>                     AccountName = accountName,
>                     ShareName = shareName,
>                     AccessMode = accessMode,
>                     AccountKey = accessKey,
>                 },
>             };
> 
> await _managedEnvironmentResource
>     .GetContainerAppManagedEnvironmentStorages()
>     .CreateOrUpdateAsync(WaitUntil.Completed, "storage-name", storageData);
> ```

It works well. Thank you very mach
