### ISSUE TITLE
[Poor Results from the Hybrid Vector/Semantic Search]

### ISSUE THREAD

**Issue by securigy** [Azure/azure-sdk-for-net#40796]
### Library name and version

Azure.SearchDocument 11.5.1

### Query/Question

I implemented something similar to Vector/Semantic search, as described [here](https://github.com/Azure/azure-sdk-for-net/blob/Azure.Search.Documents_11.5.1/sdk/search/Azure.Search.Documents/samples/Sample07_VectorSearch_UsingSemanticHybridQuery.md):

The code of configuring both vector and semantic searches is based on the flags passed to the API, and look like that:

    `    public SearchIndex? GetOrCreateSearchIndex(int searchTypeInt,
                                           SearchIndexClient searchIndexClient,
                                           string searchIndexName)
    {
        SearchIndex? searchIndex = null;

        SearchType searchType = (SearchType)searchTypeInt;

    try
    {
        // Get index if exists
        searchIndex = searchIndexClient.GetIndex(searchIndexName);
    }
    catch (RequestFailedException ex) when (ex.Status == 404)
    {
        try
        {
            // The search index schema (local definition of index) does not exist - create one
            FieldBuilder builder = new FieldBuilder();
            searchIndex = new SearchIndex(searchIndexName, builder.Build(typeof(SegmentObj)));

            // VECTOR OPTION
            if ((searchType & SearchType.Vector) == SearchType.Vector)
            {
                //string vectorProfileFilePath = Path.Combine(InstallDir, mVectorProfileFileName);
                string jsonStr = File.ReadAllText("VectorProfile.json");

                searchIndex.VectorSearch = new VectorSearch
                {
                    Profiles =
                    {
                        // using 11.5.0-beta5 of Azure.Search.Documents, in 11.5.0 it will be different ???
                        //new VectorSearchProfile("my-default-vector-profile", "my-hnsw-config-2")
                        new VectorSearchProfile("my-vector-profile", "my-hnsw-config")
                        {
                             Name = "my-vector-profile",
                             AlgorithmConfigurationName ="my-hnsw-config"
                        }
                    },
                    Algorithms =
                    {
                        // using 11.5.0-beta5 of Azure.Search.Documents, in 11.5.0 it will be different ???
                        //new HnswAlgorithmConfiguration("my-hnsw-config-2") // using 11.5.0-beta5 of Azure.Search.Documents
                        new HnswAlgorithmConfiguration("my-hnsw-config")
                        {
                             Name = "my-hnsw-config",
                             Parameters = new HnswParameters()
                             {
                                  Metric = "cosine",
                                   EfSearch = 800,
                                    EfConstruction = 800,
                                     M = 8
                             }
                        },
                    }
                };

            }

            // SEMANTIC OPTION
            if ((searchType & SearchType.Semantic) == SearchType.Semantic)
            {
                SemanticSearch semanticSearch = new SemanticSearch
                {
                    Configurations =
                    {
                        // Looks line "my-semantic-config" is not a file name by a name I give
                        // to new semantic configuration I am creating...Not sure about it...
                        // https://learn.microsoft.com/en-us/azure/search/semantic-how-to-query-request?tabs=rest%2Crest-query
                        // The above documentation says: Set "semanticConfiguration" to a
                        // predefined semantic configuration that's embedded in your index.
                        //
                        new SemanticConfiguration("my-semantic-config", new()
                        {
                            //TitleField = new SemanticField("HotelName"),
                            ContentFields =
                            {
                                new SemanticField("SegmentText"),
                                new SemanticField("NamedEntities")
                            },
                            KeywordsFields =
                            {
                                new SemanticField("NamedEntities")
                            }
                        })
                    }
                };

                searchIndex.SemanticSearch = semanticSearch;
            }

            // Create SearchIndex in Azure
            if (searchIndex != null)
                searchIndex = searchIndexClient.CreateIndex(searchIndex);
        }
        catch (Exception ex2)
        {
            _logger.LogError(ex2, ex2.Message);
            return null;
        }
    }

    return searchIndex;
    }`

and here is the calling function:

    `public async Task<List<SegmentObj>?> HybridSearch(SearchClient searchClient, 
                               SearchIndexClient searchIndexClient, 
                               string searchIndexName,
                               int searchTypeInt, 
                               ReadOnlyMemory<float> embeddings, // Embeddings of prompt
                               string searchText = "",  // Additional Text to search
                               string filterNamedEntities = "",
                               int k = 10)
    {
        _logger.LogTrace("HybridSearch entered");

        SearchIndex? searchIndex = null;
    SearchOptions? searchOptions = null;
    List<SegmentObj>? segList = null;

        SearchType searchType = (SearchType)searchTypeInt;
        _logger.LogTrace($"SearchType: {searchType.ToString()}");

    try
    {
        // Get Index if exists, otherwise create it
        searchIndex = GetOrCreateSearchIndex(searchTypeInt,
                                             searchIndexClient,
                                             searchIndexName);

        searchOptions = CreateSearchOptions(searchTypeInt, k, embeddings);

        if (!String.IsNullOrWhiteSpace(filterNamedEntities.Trim()))
            searchOptions.Filter = filterNamedEntities; 

        //if (searchIndex != null)
        //    searchIndex = await searchIndexClient.CreateIndexAsync(searchIndex);

        SearchResults<SegmentObj>? response = null;
        if (searchOptions != null)
            response = await searchClient.SearchAsync<SegmentObj>(searchOptions);
        //response = await searchClient.SearchAsync<SegmentObj>("", searchOptions);

        int count = 0;
        _logger.LogTrace($"Single Vector Search Results:");

        segList = new List<SegmentObj>();

        //foreach (SearchResult<SegmentObj> result in response.GetResults())
        if (response != null)
        {
            await foreach (SearchResult<SegmentObj> result in response.GetResultsAsync())
            {
                count++;
                SegmentObj seg = result.Document;
                segList.Add(seg);
                _logger.LogTrace($"ID: {seg.segmentId}: Text:{seg.SegmentText}: NE:{seg.NamedEntities} ");
            }
        }

        _logger.LogTrace($"Total number of search results:{count}");
    }
    catch (Exception ex)
    {
        _logger.LogError(ex, ex.Message);
        return null;
    }

    _logger.LogTrace("HybridSearch exiting");
    return segList;
    }
`
So, everything works - no exceptions. Obviously, you need to take my word that all other entities associated with this configuration were created correctly.

Now, previously I ingested a document using the same configuration as far I know (just my resume). Now that I do the search, I ask something like: When did [Person's Name] work at [Company Name]? - and I get back only a single result instead of 10 that I asked, and this result is TOTALLY incorrect - just a last paragraph of the document. (Something to clarify: I segmented this document into segments, which are paragraphs, before I fed them to Azure OpenAI Embeddings API, so each paragraph is represented by a vector).

Do you see anything evident in the code that results in my misfortunes? So far, I ran 'Vector' mode and 'Vector | Semantic', but the results are bad for both...

### Environment

Windows 11,
Visual Studio 2022
Azure.Search.Documents 11.5.1

**Comment by jsquire** [comment]
Hi @securigy.  Thank you for reaching out and we regret that you're experiencing difficulties.  The results that are returned are generated by the service, the client library has no influence or insight into them.  

Unfortunately, this repository is focused on the Azure SDK for .NET - we're unable to assist with other Azure issues.  Your best path for reporting the quality of results to the Search service team would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request).  Alternatively, you could consider posting to the [Azure Search forum](https://feedback.azure.com/d365community/forum/9325d19e-0225-ec11-b6e6-000d3a4f07b8) of the Azure Feedback site, as that forum is also monitored by the service team.

I'm going to close this out;  if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.

**Comment by securigy** [comment]
I believe that the results I am getting is a problem with the code that I wrote and therefore I wanted opinion of people that wrote the search examples.

**Comment by jsquire** [comment]
> I believe that the results I am getting is a problem with the code that I wrote and therefore I wanted opinion of people that wrote the search examples.

Thank you for the clarification; I misunderstood your intent.   Reopening and routing to the team member best able to assist.

**Comment by jsquire** [comment]
@ShivangiReja:  Would you please offer thoughts on the code snippet that was shared?

**Comment by securigy** [comment]
I tried to do everything by the book, that is, the example code in the link and surrounding examples that I shared in the link in my original question. At the same time I needed to make it modular so, the code is structured to satisfy my architectural demands.
Eventually, the main piece was creating the SearchIndex from the parts I've created before, like SearchIndexClient, etc. This function is called from 2 APIs right now: the Ingest API that ingests the 167 segments of the document (the Segment is a paragraph of the document, but I belie you call it 'Document') and the Search API. After that I call for CreateSearchOptions and eventually the Azure Search API.

The ingestion works and I believe I ingest all the 167 segments - I am not sure how to verify this... but that's another issue.
The rest is layed out in the code. It looks like it is all in the configuration items...

**Comment by securigy** [comment]
Looking at Azure - it shows me that the number of Documents is 1.
Does it mean that I ingested a single segment?

**Comment by ShivangiReja** [comment]
You can check the document count in your index through the portal, or alternatively, you can utilize [searchClient.GetDocumentCount();](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/samples/Sample01a_HelloWorld.md#handle-errors) to retrieve the number of documents in your index.

As an example, in my 'btchjuud' index, there are 350 documents.
<img width="1097" alt="image" src="https://github.com/Azure/azure-sdk-for-net/assets/45216704/7b1e4b0a-3a21-4341-b892-61e9533d3727">

@securigy If you have only 1 document, maybe that's why you are not getting the result you're expecting.

**Comment by securigy** [comment]
Is there any way I can see metadata in the index?
When I search 'project' word, I get:
{
  "@odata.context": "https://semantictrainer.search.windows.net/indexes('my-text-index1')/$metadata#docs(*)",
  "value": []
}

and if I click on the link I get 403.

**Comment by ShivangiReja** [comment]
In the Azure portal, first navigate to the specific index for which you want to view the metadata. Here, you'll find detailed information such as fields, scoring profiles, CORS options, among other settings. 

Alternatively, you can leverage the Azure Search `SearchIndexClient.GetIndex` API to fetch the metadata of an index programmatically. Here's a sample code snippet in C# demonstrating how to use the `GetIndex` method:

```csharp
// Instantiate a new SearchIndexClient
SearchIndexClient indexClient = new SearchIndexClient(new Uri("<Your-Search-Service-Endpoint>"), new AzureKeyCredential("<Your-Search-Service-Key>"));

// Call the GetIndexAsync method to fetch the index
SearchIndex index = await indexClient.GetIndexAsync("<Your-Index-Name>");
```

Please remember to replace `<Your-Search-Service-Endpoint>`, `<Your-Search-Service-Key>`, and `<Your-Index-Name>` with your actual values.
