### ISSUE TITLE
Management Certificate support for WebSiteManagementClient

### ISSUE THREAD

**Issue by MarkSiedle** [Azure/azure-sdk-for-net#4080]
Hi,

At Octopus, we currently support both Azure Management Certificates and Service Principals as connection options for querying and deploying Azure web apps.

We're trying to upgrade our libraries to use your latest Azure SDK, but can't find a way to connect with a Management Certificate.

If we use the older SDK @ `Microsoft.WindowsAzure.Management.WebSites`, we can create a [WebSiteManagementClient](https://msdn.microsoft.com/en-us/library/microsoft.windowsazure.management.websites.websitemanagementclient.aspx) using a Management Certificate (via [CertificateCloudCredentials](https://msdn.microsoft.com/en-us/library/microsoft.windowsazure.certificatecloudcredentials.aspx)) and query the subscription's web apps just fine. But we believe this library is deprecated and quite limited in the data that it returns (especially since we want to start querying Azure Functions as well as Web Apps).

If we use this SDK @ `Microsoft.Azure.Management.WebSites`, is there anyway to establish a `WebSiteManagementClient` login non-interactively if all you have is a subscription's Management Certificate (X509) and the SubscriptionId, like you used to be able to do with the older SDK?

If not, as a workaround, is there a way we could obtain an AccessToken using just a Management Certificate + SubscriptionId? Are there any code examples of this?

Any advice appreciated

Thanks
Mark

**Comment by Petermarcu** [comment]
@schaabs will this be solved when the management libraries are released on top of Azure.Identity?

**Comment by schaabs** [comment]
I believe the `ClientCloudCredentials` class mentioned here is for authenticating "classic" deployment requests. Currently our management plane libraries only support ARM, not the "classic" ASM/RDFE deployments which are in the process of being deprecated. So there are no plans to support this authentication mechanism in Azure.Identity or Azure.Core.

The closest analog to this in Azure.Identity would be the [ClientCertificateCredential](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.clientcertificatecredential?view=azure-dotnet). This is also certificate based authentication, however it authenticates a specific service principal. To authenticate in this manner you need to create a service principal and assign that service principal the desired roles within your subscription to grant it access.

**Comment by schaabs** [comment]
I'm closing this issue as we are not planning support. @MarkSiedle If you disagree please feel free to reopen.
