### ISSUE TITLE
[QUERY] Dependency injection of all azure clients, use stale HttpClient instances?

### ISSUE THREAD

**Issue by kikaragyozov** [Azure/azure-sdk-for-net#40807]
### Library name and version

Microsoft.Extensions.Azure 1.8.0-beta.1

### Query/Question

After inspecting the source code, the underlying `HttpClientTransport` uses an `HttpClient`, which as far as my understanding goes, needs to be refreshed from an `IHttpClientFactory` as keeping a single long-lived instance of it, might cause issues relating to DNS.

The `AzureClientFactory` coupled with `ClientRegistration<TClient>` cache the whole client that's built from DI, which also includes any dependencies it might have, such as `HttpClientTransport`.

My question is - is this intended? If so, why?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by AlexanderSher** [comment]
Hi @kikaragyozov,

DNS TTL expiration problem is addressed by setting `SocketsHttpHandler.PooledConnectionLifetime` to 5 minutes. See https://github.com/Azure/azure-sdk-for-net/blob/db6673e128cb5f9dd239ac2ccfdbd98fa4693566/sdk/core/Azure.Core/src/Pipeline/ServicePointHelpers.cs#L61-L106
