### ISSUE TITLE
[QUERY] Is setting blob metadata an atomic operation when blob is uploaded?

### ISSUE THREAD

**Issue by asgoe** [Azure/azure-sdk-for-net#40816]
### Library name and version

Azure.Storage.Blobs:12.1.0, WindowsAzure.Storage: 8.7.0

### Query/Question

We recently noticed that few blobs which were created in 2020/2021 do not have the relevant metadata stored on them. There are other 1000's of other blobs in the container which have the correct metadata. The blob has not been modified since it was created. These blobs are backups, so we upload them and they are then deleted after a certain retention period (through a separate flow that runs periodically). There is no workflow which modifies these blobs after they are uploaded. Not having this metadata is resulting in blobs not being cleaned up.

The way we create the blob is:
1. Set the blob metadata on the blob object (eg: blob.Metadata[key] = value)
2. Upload the blob using blob.UploadFromStreamAsync

Question:
- Is setting the blob metadata and upload atomic operations on the backend? Is it possible that the blob got uploaded, but the operation to set the metadata ran into issues on the server side?
- Is there any other reason why the metadata will not exist on the blob?

Blob without metadata:
![image](https://github.com/Azure/azure-sdk-for-net/assets/58997343/a21cbd51-8d9f-4f98-9cf8-17e7c451d3c5)

Blob with metadata:
![image](https://github.com/Azure/azure-sdk-for-net/assets/58997343/47e987e4-1f99-4eb9-ab3c-49aec90c43af)

### Environment

We are running services hosted in Service Fabric on Azure VMSS Scale sets using .NET Framework

**Comment by asgoe** [comment]
Can I get some traction on this issue? Thanks

**Comment by KevinKitts** [comment]
> Is setting the blob metadata and upload atomic operations on the backend?

I could also like an answer to this in terms of Azure Storage V12 SDK.
We upload a blob and later set the metadata to indicate its upload is complete. 

```
// Upload the blob without the metadata
BlobUploadOptions uploadOptions = new() { HttpHeaders = new BlobHttpHeaders() { ContentEncoding = contentEncoding }, };
BlobContentInfo uploadContentInfo = await blobClient.UploadAsync(contentStream, uploadOptions, cancellationToken: ct);

// Blob upload succeeded and we can mark it complete for other client applications.
IDictionary<string, string> metadata = new();
metadata["Complete"] = "True";
await blobClient.SetMetadataAsync(metadata, cancellationToken: ct);
```

Is this unecessary and we could safely have 1 fewer network calls?
```
// Upload the blob WITH the metadata expecting atomic operation
IDictionary<string, string> metadata = new();
metadata["Complete"] = "True";
BlobUploadOptions uploadOptions = new() { HttpHeaders = new BlobHttpHeaders() { ContentEncoding = contentEncoding }, Metadata = metadata, };
BlobContentInfo uploadContentInfo = await blobClient.UploadAsync(contentStream, uploadOptions, cancellationToken: ct);
```

**Comment by seanmcc-msft** [comment]
@asgoe, it depends on the SDK API you use for the upload, and the size of the content.  Most our upload APIs will do a single-shot (1 API call) upload for uploads < 256 MB, including setting metadata.  (This is assuming you are using the default settings, instead of setting BlobUploadOptions.TransferOptions).  Uploads >= 256 MB will be preformed via multiple Put Block calls, followed by a Commit Block List call.  The call to Commit Block List should be the one setting the blob metadata.
