### ISSUE TITLE
[BUG] Null Reference Exception in OpenAIClient.GetChatCompletionsAsync

### ISSUE THREAD

**Issue by mcDevnagh** [Azure/azure-sdk-for-net#40810]
### Library name and version

Azure.AI.OpenAI 1.0.0-beta.11

### Describe the bug

```
Exception thrown: 'System.NullReferenceException' in System.Private.CoreLib.dll: 'Object reference not set to an instance of an object.'
   at Azure.AI.OpenAI.ChatCompletionsOptions.Azure.Core.IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
   at Azure.Core.Utf8JsonWriterExtensions.WriteObjectValue(Utf8JsonWriter writer, Object value)
   at Azure.AI.OpenAI.ChatCompletionsOptions.ToRequestContent()
   at Azure.AI.OpenAI.OpenAIClient.<GetChatCompletionsAsync>d__14.MoveNext()
   at MyNamespace.MyType.<MyFunction>d__13.MoveNext() in /home/myname/.local/src/repo/MyNamespace/MyType.cs:line #
```

### Expected behavior

No exception is thrown

### Actual behavior

Exception not thrown

### Reproduction Steps

1. Use this constructor (other constructors don't repro): https://github.com/Azure/azure-sdk-for-net/blob/899b608fc56f65dba4f75335936115b047bdf74a/sdk/openai/Azure.AI.OpenAI/src/Generated/ChatCompletionsOptions.cs#L30
2. Pass `ChatCompletionsOptions` to `OpenAIClient.GetChatCompletionsAsync`

```cs

List<ChatRequestMessage> messages = new List<ChatRequestMessage>
{
    new ChatRequestSystemMessage("test"),
    new ChatRequestUserMessage("test"),
};

var options = new ChatCompletionsOptions(messages)
{
    DeploymentName = deploymentName,
    ChoiceCount = 1,
};

Response<ChatCompletions> response = await this.Client.GetChatCompletionsAsync(
    chatCompletionsOptions: options,
    cancellationToken: cancellationToken);


```

### Environment

.NET SDK:
 Version:   7.0.404
 Commit:    22f221a24c

Runtime Environment:
 OS Name:     debian
 OS Version:  11
 OS Platform: Linux
 RID:         debian.11-x64
 Base Path:   /usr/share/dotnet/sdk/7.0.404/

Host:
  Version:      7.0.14
  Architecture: x64
  Commit:       808851b07a

.NET SDKs installed:
  5.0.408 [/usr/share/dotnet/sdk]
  6.0.417 [/usr/share/dotnet/sdk]
  7.0.404 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.17 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.25 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.14 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.17 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.25 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.14 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by trrwilson** [comment]
Thank you for getting in touch and for the great detail! This problem reflected an oversight in the code generation specification and was just corrected with #40697 .

**Comment by HiltonGiesenow** [comment]
I'm seeing this also, in beta 1.12. In my case, I'm doing a recursive call into the same method the 2nd time, which is calling OpenAI. It's also in `IUtf8JsonSerializable.Write(Utf8JsonWriter writer)`.

Is the fix in [40697](https://github.com/Azure/azure-sdk-for-net/pull/40697) released in 1.12?

**Comment by HiltonGiesenow** [comment]
Never mind, it applies even if I new up a fresh instance inside the method.

**Comment by HiltonGiesenow** [comment]
I found the problem - the serialization was failing because I'd passed a `null` value for one of the collections (the Functions list), which it wasn't expecting. I'll try work on a PR, but in the meantime posting this here in case it helps others.
