### ISSUE TITLE
[BUG] EventGridClient got 401 when acknowledging messages from Event Grid namespace topic

### ISSUE THREAD

**Issue by fazho** [Azure/azure-sdk-for-net#40812]
### Library name and version

Azure.Messaging.EventGrid 4.22.0-beta.1

### Describe the bug

I created an Azure service principal under my Azure Subscription. For simplicity I am using password as the secret for authentication, not certificate.

Then under the same Azure subscription I created an Event Grid Namespace, enabled MQTT for it, and created a namespace topic and a subscription. The following roles are assigned to my service principal at the namespace topic level (not at the EG namespace level): EventGrid Contributor and EventGrid Data Contributor.

I then use this service principal's credential to read messages from the namespace topic:
```
var clientSecretCredential = new ClientSecretCredential(
    "<a valid tenant id>",
    "<a valid app id>",
    "<app password>");
var egClient = new EventGridClient(new Uri("<a valid eg endpoint>"), clientSecretCredential);
int egListenerCount = 1;
var topicName = "<a valid topic name>";
var subscriptionName = "<a valid subscription name>";
var listenerTasks = new List<Task>();

for (int count = 0; count < egListenerCount; count++)
{
    listenerTasks.Add(
        Task.Run(async () =>
        {
            while (Interlocked.Read(ref flag) == 0)
            {
                ReceiveResult result = await egClient.ReceiveCloudEventsAsync(topicName, subscriptionName, 5, TimeSpan.FromSeconds(30));

                if (result?.Value != null)
                {
                    var toAcknowledge = new List<string>();

                    foreach (ReceiveDetails detail in result.Value)
                    {
                        CloudEvent cloudEvent = detail.Event;
                        BrokerProperties brokerProperties = detail.BrokerProperties;
                        Console.WriteLine($"[EGNS Topic Testing]Data: {cloudEvent?.Data?.ToString()}");

                        toAcknowledge.Add(brokerProperties.LockToken);
                    }

                    if (toAcknowledge.Any())
                    {
                        AcknowledgeResult acknowledgeResult = await egClient.AcknowledgeCloudEventsAsync(topicName, subscriptionName, new AcknowledgeOptions(toAcknowledge));

                        if (acknowledgeResult.FailedLockTokens.Any())
                        {
                            Console.WriteLine($"[EGNS Topic Testing]Failed count for Acknowledge: {acknowledgeResult.FailedLockTokens.Count}");
                            foreach (FailedLockToken failedLockToken in acknowledgeResult.FailedLockTokens)
                            {
                                Console.WriteLine($"Lock Token: {failedLockToken.LockToken}; Error Code: {failedLockToken.Error}; Error Description: {failedLockToken.ToString}");
                            }
                        }

                        if (acknowledgeResult.SucceededLockTokens.Any())
                        {
                            Console.WriteLine($"[EGNS Topic Testing]Success count for Acknowledge: {acknowledgeResult.SucceededLockTokens.Count}");
                            foreach (string lockToken in acknowledgeResult.SucceededLockTokens)
                            {
                                Console.WriteLine($"Lock Token: {lockToken}");
                            }
                        }
                    }
                }
            }
        }));
}
```

The **ReceiveCloudEventsAsync() method returned some messages** from the namespace topic, but when the code tried to **acknowledge them** by calling AcknowledgeCloudEventsAsync(), the following error occurred:

Provided JWT token is not allowed to perform following operation
Status: 401 (Unauthorized)
ErrorCode: Unauthenticated

Content:
{"error":{"code":"Unauthenticated","message":"Provided JWT token is not allowed to perform following operation","timestamp_utc":"2023-12-15T19:34:32.914700543+00:00","tracking_id":"319A8767-930D-45DA-9955-F8D1EEBB89F5"}}

Headers:
broker-errorcode: REDACTED
Date: Fri, 15 Dec 2023 19:34:32 GMT
Content-Length: 220
Content-Type: application/json; charset=utf-8

### Expected behavior

Both read and ack should succeed or fail together, using the same service principal.

### Actual behavior

read succeeded but ack failed.

### Reproduction Steps

All repro steps are mentioned in the summary.

**Comment by jsquire** [comment]
Hi @fazho.   Thank you for reaching out and we regret that you're experiencing difficulties.  The client library does not have insight nor influence over authorization, it only surfaces the response from the Event Grid service.  To understand why the principal is being rejected, we'll need perspective from the service.  Unfortunately, this repository is focused on the Azure SDK for .NET - we're unable to assist with other Azure issues.  Your best path forward would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request).
