### ISSUE TITLE
[QUERY] Possible reasons why Azure IoT Hub built-in endpoint closes the receiver link

### ISSUE THREAD

**Issue by minghuaw** [Azure/azure-sdk-for-net#40828]
### Library name and version

Azure.Messaging.EventHubs

### Query/Question

I have been working on an unofficial Event Hub SDK for rust, and recently one user found that their Event Hub consumer client kept getting closed by Azure after working fine for a random period of time. They are using the Event Hub consumer client to read events from an IoT Hub built-in endpoint, and they are working with a North Europe instance. What they have been observed in the log is the follows:

1. The consumer client works fine for some hours
2. The AMQP receiver link gets disconnected by Azure with a closing detach frame with no error message
3. The underlying AMQP connection, however, is kept open, and the AMQP management link on that connection is also kept active
4. During the retrying process, disconnecting and reconnect the management link works, but trying to receive from the receiving link (this is actually indeed my problem, should not have tried resuming a closed link) yields the same error mentioned above in (2)

There are roughly 6 or 7 messages per minute coming from the IoT Hub, so we could rule out connection closure due to inactiveness. I have been trying to reproduce this on a test instance in the Canada Central region, but I have not been able to reproduce this yet. I was just wondering if you have any insights of what could be causing the initial closing `Detach` from Azure?

**Comment by minghuaw** [comment]
The original issue can be found here minghuaw/azeventhubs#4

**Comment by jsquire** [comment]
Hi @minghuaw.  Thanks for reaching out and we regret that you're experiencing difficulties.  Unfortunately, the behavior that you're asking about is service-side and not something that the Azure SDK clients have insight into nor influence over.   This isn't something that we're able to assist with from this repository.

Your best path forward would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request).  Alternately, you could consider posting to the [Event Hubs forum](https://feedback.azure.com/d365community/forum/86c37ae9-7526-ec11-b6e6-000d3a4f032c) of the Azure Feedback site, which is monitored by the service team.

**Comment by minghuaw** [comment]
Thanks a lot. I will close this issue then.
