### ISSUE TITLE
[FEATURE REQ] Add TableCheckpointStore

### ISSUE THREAD

**Issue by Arithmomaniac** [Azure/azure-sdk-for-net#40830]
### Library name

Azure.Messaging.EventHubs.Processor

### Please describe the feature.

Currently, the only built-in CheckpointStore in the Azure SDK, [BlobCheckpointStore](https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.eventhubs.primitives.blobcheckpointstore?view=azure-dotnet) uses Azure Blob Storage as its backing.

As the Durable Functions team [shared recently](https://techcommunity.microsoft.com/t5/apps-on-azure-blog/preview-of-durable-functions-extension-v3-0-0/ba-p/4000452), using Azure Storage Tables is cheaper and easier to debug than using stub blobs, and they are changing their default partition manager accordingly.

There's an [@azure/eventhubs-checkpoint-table](url) package in beta in the [JS SDK](https://github.com/Azure/azure-sdk-for-js/tree/main/sdk/eventhub/eventhubs-checkpointstore-table) that we could port and finalize.

**Comment by jsquire** [comment]
Hi @Arithmomaniac.  Thank you for reaching out and for your suggestion.  This is not something that is currently planned.  To date, we have not seen enough customer feedback asking for a Tables checkpoint store to justify the investment needed to build and maintain the feature across languages.   We'll continue to monitor and are open to considering this in the future if there is enough demand for it.

**Comment by Arithmomaniac** [comment]
/unresolve

given that you accepted a JS version (albeit in its own package), would you accept a PR with a .NET version?

**Comment by jsquire** [comment]
@Arithmomaniac : Thank you for your kind offer to contribute.  Unfortunately, this is not a feature that we would be open to taking ownership of nor supporting at present.  

Our JS package is an internal prototype that has never been formally released.  Were we to move forward with official support for a Tables checkpoint store, we would need to do so as a coordinated effort across the Azure SDK languages.
