### ISSUE TITLE
OcrResult variable Language of the wrong type.

### ISSUE THREAD

**Issue by dumonjorne** [Azure/azure-sdk-for-net#4083]
Hi,

In `Microsoft.Azure.CognitiveServices.Vision.ComputerVision.Models.OcrResult,` variable Language  is of the wrong type, resulting in a failing json deserialization. It should be of type OcrLanguage instead of OcrResult.

**Comment by brminnick** [comment]
Here's my workaround for anyone else who is struggling with this error.

I created my own OcrResultModel that uses the correct type, `OcrLanguages`. I then create a new `OcrResult`, assigning `Language = default(OcrResult)`


```
public static async Task<OcrResult> GetOcrResultsFromMediaFile(MediaFile mediaFile)
{
	try
	{
		return await ComputerVisionApiClient.RecognizePrintedTextInStreamAsync(true, ConverterHelpers.ConvertMediaFileToStream(mediaFile, false)).ConfigureAwait(false);
	}
	catch (ComputerVisionErrorException e) when (e.Response.StatusCode.Equals(HttpStatusCode.Unauthorized))
	{
		DebugHelpers.PrintException(e);

		OnInvalidComputerVisionAPIKey();

		throw;
	}
        catch (Microsoft.Rest.SerializationException e)
	{
		var xamSpeakOcrResult = JsonConvert.DeserializeObject<XamSpeakOcrResult>(e.Content);

		return new OcrResult
		{
			Language = default(OcrResult),
			Orientation = xamSpeakOcrResult.Orientation,
			Regions = xamSpeakOcrResult.Regions,
                        TextAngle = xamSpeakOcrResult.TextAngle
		};
	}
}

	public class XamSpeakOcrResult
	{
		[JsonProperty("language")]
		public OcrLanguages Language { get; set; }

		[JsonProperty("orientation")]
		public string Orientation { get; set; }

		[JsonProperty("textAngle")]
		public double TextAngle { get; set; }

		[JsonProperty("regions")]
		public List<OcrRegion> Regions { get; set; }
	}
```

**Comment by brminnick** [comment]
To fix this bug, change this line of code in the SDK: https://github.com/Azure/azure-sdk-for-net/blob/c95d9ea0f880886c185dd1f9d1d6b2ccb1f7383e/src/SDKs/CognitiveServices/dataPlane/Vision/ComputerVision/ComputerVision/Generated/Models/OcrResult.cs#L66

Change
`public OcrResult Language { get; set; }`
To
`public OcrLanguages Language { get; set; }`
