### ISSUE TITLE
[BUG] WebSiteResource.Stop method does not work on Staging slot

### ISSUE THREAD

**Issue by VladimirKhvostov** [Azure/azure-sdk-for-net#40840]
### Library name and version

Azure.ResourceManager.AppService v1.1.0-beta4

### Describe the bug

Consider the following example:
```
            WebSiteResource[] sites = resourceGroup.GetWebSites().GetAll(includeSlots: isStaging).ToArray();

            string siteName = isStaging ? functionAppName + "/Staging" : functionAppName;

            WebSiteResource site = sites.SingleOrDefault(s => string.Equals(s.Data.Name, siteName, StringComparison.OrdinalIgnoreCase));

            if (site is not null)
            {
                site.Stop();
           }
```
Stop method fails reporting the following error:

```
{"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.Web/sites/Staging' under resource group 'statusppecus1' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"}}
```

Notice that the resource is Microsoft.Web/sites/Staging instead of  Microsoft.Web/sites/{siteName}/slot/Staging
Rest API reference: https://learn.microsoft.com/en-us/rest/api/appservice/web-apps/stop-slot?view=rest-appservice-2022-03-01

After some digging, I think I need to do the following:
```
            WebSiteSlotResource webSiteSlot;
            try
            {
                WebSiteResource site = resourceGroup.GetWebSites().Get(functionAppName);
                webSiteSlot = site.GetWebSiteSlot(stepData.SlotName);
            }
            catch (RequestFailedException ex) when (ex.Status == (int)HttpStatusCode.NotFound)
            {
                return;
            }

            webSiteSlot.StopSlot();
```
I am logging this issue to raise awareness that the API is not user friendly.

### Expected behavior

WebSiteResource.Stop method should stop staging slot.

### Actual behavior

RequestFailedException with status 404 is thrown.

### Reproduction Steps

See description

### Environment

.NET Framework 4.8

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi @VladimirKhvostov ,Thank you for using Azure SDK for .NET.
Thank you for the suggestion, unfortunately, our sdk is auto generated.
We'll log it and see if there is any improvement we could make in the future.
