### ISSUE TITLE
Banned from OpenAI after issuing a request with Azure.AI.OpenAI

### ISSUE THREAD

**Issue by viktoreinars** [Azure/azure-sdk-for-net#40847]
### Library name and version

Azure.AI.OpenAI 1.0.0-beta.12

### Query/Question

Not sure if this related at all but yesterday I added some credits to my OpenAI account, created an API key and sent a single chat requests asking for PR summary for user stories titles. Using your package.

During the night it seems my OpenAI account has been banned. 

Is it possible that my API key was leaked somehow or that the package is abusing the OpenAI platform in some way?

### Environment

Visual Studio 2022

**Comment by jsquire** [comment]
Hi @viktoreinars.  Thank you for reaching out and we regret that you're experiencing difficulties.  The Azure SDK package just wraps the REST API for the Open AI service, invoking service operations only when your application interacts with the client API.  All telemetry and logging generated by the client is emitted only in the scope of your application.  We're sorry to hear that your account has been banned, but this is not something that we can assist with.

Your best path forward would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) or an [OpenAI support request](https://help.openai.com/en/articles/6614161-how-can-i-contact-support).

I'm going to close this out; if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.

**Comment by viktoreinars** [comment]
Hi @jsquire,

I figured as much. Thanks for the response!

Best regards,
Viktor Einarsson
