### ISSUE TITLE
[QUERY] Index code for internal build process

### ISSUE THREAD

**Issue by noellelc** [Azure/azure-sdk-for-net#40853]
### Library name and version

all

### Query/Question

We would like to use this repository to dogfood some internal build processes, if you could follow the steps outlined in [these docs](https://dev.azure.com/DevDiv/DevDiv/_wiki/wikis/DevDiv.wiki/28554/Index-Your-Repo)

@weshaggard

**Comment by ericstj** [comment]
@weshaggard this was the functionality we discussed that we'd like to try to enable in the build pipeline.

**Comment by huangmin-ms** [comment]
Hi All, As we also planned to support `typescript`, can we also onboard https://github.com/Azure/azure-sdk-for-js to code index？
