### ISSUE TITLE
[BUG] Cannot send images with a file size of more than about 64KB

### ISSUE THREAD

**Issue by shibayan** [Azure/azure-sdk-for-net#40855]
### Library name and version

Azure.AI.OpenAI 1.0.0-beta.12

### Describe the bug

Due to the fact that `ChatMessageImageUrl` and `ChatMessageImageContentItem` use the `Uri` class to handle images, only about 64KB or less is available for uploading images using Data URL.

OpenAI endpoints can handle images larger than 64KB, but the SDK's use of `Uri` is a major limitation.

### Expected behavior

Images with a file size of 64KB or larger can be uploaded to generate a response.

### Actual behavior

The constraints of the `Uri` class throw the following exceptions.

>System.UriFormatException: 'Invalid URI: The Uri string is too long.'

### Reproduction Steps

```csharp
var filePath = @"largesize.png";

var imageContent = new ChatMessageImageContentItem(
    new Uri($"data:image/png;base64,{Convert.ToBase64String(File.ReadAllBytes(filePath))}"),
    ChatMessageImageDetailLevel.Auto);
```

**Comment by arafattehsin** [comment]
I figured out the similar issue today and received the below error:

`{System.UriFormatException: Invalid URI: The Uri string is too long.`

**Comment by joakimriedel** [comment]
https://github.com/Azure/azure-sdk-for-net/issues/40744

**Comment by vandana2015** [comment]
Hi, when can this be available? any ETA?

**Comment by vandana2015** [comment]
Still an issue in Azure.AI.OpenAI 1.0.0-beta.14
