### ISSUE TITLE
[BUG] StaticSitePatch missing Identity property to update managed identity

### ISSUE THREAD

**Issue by NickSevens** [Azure/azure-sdk-for-net#40859]
### Library name and version

Azure.ResourceManager.AppService 1.0.2

### Describe the bug

The `StaticSitePatch` object is missing the `Identity` property, which makes it unable to update the resource's managed identity.

### Expected behavior

`StaticSitePatch` should include the `Identity` property to enable updating of managed identity.

### Actual behavior

The `StaticSitePatch` object is missing the `Identity` property, which makes it unable to update the resource's managed identity.

### Reproduction Steps

-

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Hey @NickSevens, thank you for reaching out to us about the Azure SDK for .NET.
Here the [Patch operation](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/web/resource-manager/Microsoft.Web/stable/2021-02-01/StaticSites.json#L307) doesn't support change the `Identity` of the static site, please refer the definition [here](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/web/resource-manager/Microsoft.Web/stable/2021-02-01/StaticSites.json#L3234).
