### ISSUE TITLE
Invalid link in document

### ISSUE THREAD

**Issue by DannyArr** [Azure/azure-sdk-for-net#40860]
### Type of issue

Outdated article

### Description

This link to 'https://www.siteextensions.net/packages/TiPCallback/' in the doc doesn't work.

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.management.websites.models.rampuprule.-ctor?view=azure-dotnet-legacy#microsoft-azure-management-websites-models-rampuprule-ctor

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.WebSites.Models/RampUpRule.xml

### Document Version Independent Id

7f40c919-ceef-f3ad-c984-901f3552695a

### Article author

@azure-sdk

### Metadata

* ID: 274dd2d0-3a01-d673-c78c-7dc341f1b3e9 
* Service: **app-service**
* Sub-service: **web-apps**

**Comment by jsquire** [comment]
Hi @DannyArr.  Thank you for your feedback.   The `Microsoft.Management.Websites` package reached end-of-life in December 2022 and is no longer published nor maintained by Microsoft.  The linked document is a point-in-time capture of documentation for the package at the time that it was retired, and the content is also no longer maintained.
