### ISSUE TITLE
ServiceClient UserAgent and ProductInfoHeaderValue issues

### ISSUE THREAD

**Issue by EricDahlvang** [Azure/azure-sdk-for-net#4086]
Allowing consumers to provide an HttpClient was a great addition to the ServiceClient library.  Thanks for that!

1)
While using the ServiceClient and providing a static HttpClient, I noticed https://github.com/Azure/azure-sdk-for-net/blob/81d6e36f25213143cf4b509ffb4926b610f7e946/src/SdkCommon/ClientRuntime/ClientRuntime/ServiceClient.cs#L476 adds the ProductInfoHeaderValue even if it is already present.  I made some changes to fix this: https://github.com/Azure/azure-sdk-for-net/compare/psSdkJson6...EricDahlvang:psSdkJson6  but, your checklist is somewhat extensive so I haven't submitted a PR.  

2)
The MergeUserAgentInfo method assumes every ProductInfoHeaderValue has a Product.  However, if a ProductInfoHeaderValue was created using the comment constructor, it will not have a Product and MergeUserAgentInfo will throw a null reference exception.

![image](https://user-images.githubusercontent.com/11055362/36513579-26befb08-1725-11e8-9af5-d7d2f97f0e62.png)

Thank you for your assistance with these two issues.

**Comment by EricDahlvang** [comment]
Thanks for fixing the first issue mentioned.

Note:

https://github.com/Azure/azure-sdk-for-net/blob/master/src/SdkCommon/ClientRuntime/ClientRuntime/ServiceClient.cs#L568

Will still potentially throw a null reference exception if the existing ProductInfoHeaderValues were created using the comment constructor (no product): https://docs.microsoft.com/en-us/dotnet/api/system.net.http.headers.productinfoheadervalue.-ctor?view=netframework-4.7.2#System_Net_Http_Headers_ProductInfoHeaderValue__ctor_System_String_

Unit Test:
```cs
        /// <summary>
        /// This is to verify if a HttpClient is passed that contains ProductInfoHeaderValues with comments in
        /// userAgent information, no exception occurs while merging
        /// </summary>
        [Fact]
        public void IgnoreProductInfoHeaderValueCommentsDuringMerge()
        {
            const string comment = "(comment)";
            HttpClient hc = new HttpClient(new ContosoMessageHandler());
            hc.DefaultRequestHeaders.UserAgent.Add(new ProductInfoHeaderValue(comment));
            ContosoServiceClient contosoClient = new ContosoServiceClient(hc, false);
            HttpResponseMessage response = contosoClient.DoSyncWork();

            HttpHeaderValueCollection<ProductInfoHeaderValue> userAgentValueCollection = contosoClient.HttpClient.DefaultRequestHeaders.UserAgent;
            contosoClient.Dispose();
            var productInfos = userAgentValueCollection.Where<ProductInfoHeaderValue>((p) => p.Product == null && p.Comment.Equals(comment, StringComparison.OrdinalIgnoreCase));
            Assert.Single(productInfos);
        }
```

Maybe if the above is addressed, this catch all can be removed:
https://github.com/Azure/azure-sdk-for-net/blob/master/src/SdkCommon/ClientRuntime/ClientRuntime/ServiceClient.cs#L540

**Comment by Thorarin** [comment]
An attempt was made to prevent UserAgent headers from being added to the default headers of an HttpClient in https://github.com/Azure/azure-sdk-for-net/pull/5009, but it doesn't look right to me.

A lock object is created on the fly, for each instance of `ServiceClient`, so that in no way prevents two instances from updating a `HttpClient` at the same time. Perhaps the issue will appear slightly less often because a memory barrier was added, but I've actually seen `IndexOutOfRangeException`s because of this issue in version 2.3.18 (and newer) of Microsoft.Rest.ClientRuntime.

**Comment by EricDahlvang** [comment]
This has been open for over three years now.  I find this odd, considering the fix is relatively minor.

Is there anything anyone can do to help resolve this?

**Comment by AlexGhiondea** [comment]
@EricDahlvang thank you for filing this issue. We are working on new versions of our libraries that are based on Azure.Core. Because of that, we are de-prioritizing changes to the ClientRuntime. Could you see if the features that Azure.Core provides work for your scenario?

**Comment by EricDahlvang** [comment]
@AlexGhiondea thank you for the update! 

I'll close this issue, and review Azure.Core for our needs separately.
