### ISSUE TITLE
Replacement for IsVersioningEnabled 

### ISSUE THREAD

**Issue by vamanoch** [Azure/azure-sdk-for-net#40868]
### Library name

Azure.ResourceManager.Storage 

### Please describe the feature.

Hello, BlobServiceProperties used to have a property to check if versioning was enabled on the blob service for storage account

https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.management.storage.models.blobserviceproperties.isversioningenabled?view=azure-dotnet-legacy.

This could be fetched using BlobServiceCLient.

However it seems with the new SDK, the property has shifted to BlobServiceData()

https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.storage.blobservicedata.isversioningenabled?view=azure-dotnet#azure-resourcemanager-storage-blobservicedata-isversioningenabled

How do I fetch BlobServiceData? Thanks

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi @vamanoch , Thank you for using Azure SDK for .Net.
You could get the data class like:
```
    var account = (await resourceGroup.GetStorageAccounts().GetAsync("name")).Value;
    var blob = (await account.GetBlobService().GetAsync()).Value;
    Console.WriteLine(blob.Data.IsVersioningEnabled);
```
