### ISSUE TITLE
[BUG] ExistsAsync, WaitForCompletionAsync and/or DeleteIfExistsAsync terminate unexpectedly

### ISSUE THREAD

**Issue by Loppor** [Azure/azure-sdk-for-net#40873]
### Library name and version

Azure.Storage.Blobs v12.19.1

### Describe the bug

Debugger fully terminates after either:

1. Checking if Blob exists via async method "ExistsAsync"
2. After calling WaitForCompletionAsync when copy of Blob has started
3. After Deleting Blob from container with "DeleteIfExistsAsync"

### Expected behavior

Debugger doesn't terminate and continues with the copy of the rest of the files which are present in the container with the given prefix

### Actual behavior

Debugger terminates fully after calling ExistsAsync on BlobClient:
Application Insights Telemetry: {"name":"AppDependencies","time":"2023-12-22T08:26:17.3481331Z","iKey":"f1315be9-97ed-4882-bafb-7eadc677640a","tags":{"ai.application.ver":"15.0.0.0","ai.cloud.roleInstance":"JeroenDesmetWr","ai.operation.id":"b2db59fbfec45194a418138e391fb14a","ai.operation.parentId":"624ab8e0508c8321","ai.internal.sdkVersion":"dotnetc:2.21.0-429","ai.internal.nodeName":"JeroenDesmetWr"},"data":{"baseType":"RemoteDependencyData","baseData":{"ver":2,"name":"HEAD /devstoreaccount1/handleidingen/nl/Handleiding%20Accountancy%20Dashboard/HTML/images/Anlisa_Handleiding___Accountancy_Dashboard_%28%3DBerekeningsmodellen%29_11.png","id":"6fe8656fe17f70a6","data":"
[http://127.0.0.1:10000/devstoreaccount1/handleidingen/nl/Handleiding%20Accountancy%20Dashboard/HTML/images/Anlisa_Handleiding___Accountancy_Dashboard_%28%3DBerekeningsmodellen%29_11.png","duration":"00:00:00.0041505","resultCode":"200","success":true,"type":"Http","target":"127.0.0.1:10000","properties":{"AspNetCoreEnvironment":"Development","_MS.ProcessedByMetricExtractors":"(Name:'Dependencies'](http://127.0.0.1:10000/devstoreaccount1/handleidingen/nl/Handleiding%20Accountancy%20Dashboard/HTML/images/Anlisa_Handleiding___Accountancy_Dashboard_%28%3DBerekeningsmodellen%29_11.png%22,%22duration%22:%2200:00:00.0041505%22,%22resultCode%22:%22200%22,%22success%22:true,%22type%22:%22Http%22,%22target%22:%22127.0.0.1:10000%22,%22properties%22:%7B%22AspNetCoreEnvironment%22:%22Development%22,%22_MS.ProcessedByMetricExtractors%22:%22(Name:%27Dependencies%27)
, Ver:'1.1')","ServerRequestId":"bf99ccc3-e462-43d6-b0b6-c6526f8d067b","DeveloperMode":"true","ClientRequestId":"337988ce-ff02-4d31-b6ca-a4ced1a84708"}}}}
The thread 0x7704 has exited with code 0 (0x0).
Application Insights Telemetry: {"name":"AppDependencies","time":"2023-12-22T08:26:17.3446061Z","iKey":"f1315be9-97ed-4882-bafb-7eadc677640a","tags":{"ai.application.ver":"15.0.0.0","ai.cloud.roleInstance":"JeroenDesmetWr","ai.operation.id":"b2db59fbfec45194a418138e391fb14a","ai.operation.parentId":"e9f3ca6465d26453","ai.internal.sdkVersion":"dotnetc:2.21.0-429","ai.internal.nodeName":"JeroenDesmetWr"},"data":{"baseType":"RemoteDependencyData","baseData":{"ver":2,"name":"BlobBaseClient.Exists","id":"624ab8e0508c8321","duration":"00:00:00.0359072","success":true,"type":"InProc | Microsoft.Storage","properties":{"AspNetCoreEnvironment":"Development","_MS.ProcessedByMetricExtractors":"(Name:'Dependencies', Ver:'1.1')","DeveloperMode":"true"}}}}
The program '[26616] testhost.exe' has exited with code 4294967295 (0xffffffff).

Debugger fully terminates after calling WaitForCompletionAsync on CopyFromUriOperation:
Application Insights Telemetry: {"name":"AppDependencies","time":"2023-12-22T09:42:21.0521313Z","iKey":"f1315be9-97ed-4882-bafb-7eadc677640a","tags":{"ai.application.ver":"15.0.0.0","ai.cloud.roleInstance":"JeroenDesmetWr","ai.operation.id":"d4a9d9ae3d4c5a65db1ebd5e90be27f7","ai.operation.parentId":"3eaf322e6f91d1c4","ai.internal.sdkVersion":"dotnetc:2.21.0-429","ai.internal.nodeName":"JeroenDesmetWr"},"data":{"baseType":"RemoteDependencyData","baseData":{"ver":2,"name":"PUT /devstoreaccount1/handleidingen/old/nl/Handleiding%20Accountancy%20Dashboard/HTML/images/Anlisa_Handleiding___Accountancy_Dashboard_%28%3DBerekeningsmodellen%29_16.png","id":"01d75ce76a0c5ddc","data":"http://127.0.0.1:10000/devstoreaccount1/handleidingen/old/nl/Handleiding%20Accountancy%20Dashboard/HTML/images/Anlisa_Handleiding___Accountancy_Dashboard_%28%3DBerekeningsmodellen%29_16.png","duration":"00:00:00.0028789","resultCode":"202","success":true,"type":"Http","target":"127.0.0.1:10000","properties":{"ServerRequestId":"03dcd1e1-8daa-4540-a0a7-1b7eeef34c16","AspNetCoreEnvironment":"Development","_MS.ProcessedByMetricExtractors":"(Name:'Dependencies', Ver:'1.1')","DeveloperMode":"true","ClientRequestId":"f1fe1791-b726-452d-92e5-ddfe7332e127"}}}}
Application Insights Telemetry: {"name":"AppDependencies","time":"2023-12-22T09:42:21.0503918Z","iKey":"f1315be9-97ed-4882-bafb-7eadc677640a","tags":{"ai.application.ver":"15.0.0.0","ai.cloud.roleInstance":"JeroenDesmetWr","ai.operation.id":"d4a9d9ae3d4c5a65db1ebd5e90be27f7","ai.operation.parentId":"82cd73ebfe5c02d8","ai.internal.sdkVersion":"dotnetc:2.21.0-429","ai.internal.nodeName":"JeroenDesmetWr"},"data":{"baseType":"RemoteDependencyData","baseData":{"ver":2,"name":"BlobBaseClient.StartCopyFromUri","id":"3eaf322e6f91d1c4","duration":"00:00:00.0270861","success":true,"type":"InProc | Microsoft.Storage","properties":{"AspNetCoreEnvironment":"Development","_MS.ProcessedByMetricExtractors":"(Name:'Dependencies', Ver:'1.1')","DeveloperMode":"true"}}}}
The thread 0x5664 has exited with code 0 (0x0).
Application Insights Telemetry: {"name":"AppDependencies","time":"2023-12-22T09:42:22.0078869Z","iKey":"f1315be9-97ed-4882-bafb-7eadc677640a","tags":{"ai.application.ver":"15.0.0.0","ai.cloud.roleInstance":"JeroenDesmetWr","ai.operation.id":"d4a9d9ae3d4c5a65db1ebd5e90be27f7","ai.operation.parentId":"e7e80bf1e5700f5d","ai.internal.sdkVersion":"dotnetc:2.21.0-429","ai.internal.nodeName":"JeroenDesmetWr"},"data":{"baseType":"RemoteDependencyData","baseData":{"ver":2,"name":"HEAD /devstoreaccount1/handleidingen/old/nl/Handleiding%20Accountancy%20Dashboard/HTML/images/Anlisa_Handleiding___Accountancy_Dashboard_%28%3DBerekeningsmodellen%29_16.png","id":"5fce3302ca54e18a","data":"http://127.0.0.1:10000/devstoreaccount1/handleidingen/old/nl/Handleiding%20Accountancy%20Dashboard/HTML/images/Anlisa_Handleiding___Accountancy_Dashboard_%28%3DBerekeningsmodellen%29_16.png","duration":"00:00:00.0041548","resultCode":"200","success":true,"type":"Http","target":"127.0.0.1:10000","properties":{"ServerRequestId":"4abffa89-3366-4304-8749-b3d29129ba29","AspNetCoreEnvironment":"Development","_MS.ProcessedByMetricExtractors":"(Name:'Dependencies', Ver:'1.1')","DeveloperMode":"true","ClientRequestId":"ac8a5eed-2959-4d42-aa9e-80ecb18bce2c"}}}}
Application Insights Telemetry: {"name":"AppDependencies","time":"2023-12-22T09:42:22.0077577Z","iKey":"f1315be9-97ed-4882-bafb-7eadc677640a","tags":{"ai.application.ver":"15.0.0.0","ai.cloud.roleInstance":"JeroenDesmetWr","ai.operation.id":"d4a9d9ae3d4c5a65db1ebd5e90be27f7","ai.operation.parentId":"82cd73ebfe5c02d8","ai.internal.sdkVersion":"dotnetc:2.21.0-429","ai.internal.nodeName":"JeroenDesmetWr"},"data":{"baseType":"RemoteDependencyData","baseData":{"ver":2,"name":"BlobBaseClient.GetProperties","id":"e7e80bf1e5700f5d","duration":"00:00:00.0069656","success":true,"type":"InProc | Microsoft.Storage","properties":{"AspNetCoreEnvironment":"Development","_MS.ProcessedByMetricExtractors":"(Name:'Dependencies', Ver:'1.1')","DeveloperMode":"true"}}}}
The program '[19768] testhost.exe' has exited with code 4294967295 (0xffffffff).

Debugger fully terminates after calling DeleteIfExists on BlobClient:
The thread 0x68e8 has exited with code 0 (0x0).
Application Insights Telemetry: {"name":"AppDependencies","time":"2023-12-22T09:30:48.1242649Z","iKey":"f1315be9-97ed-4882-bafb-7eadc677640a","tags":{"ai.application.ver":"15.0.0.0","ai.cloud.roleInstance":"JeroenDesmetWr","ai.operation.id":"d85530bc4a3b10875a3f268ad5990f71","ai.operation.parentId":"e26cdb896c2bb0f6","ai.internal.sdkVersion":"dotnetc:2.21.0-429","ai.internal.nodeName":"JeroenDesmetWr"},"data":{"baseType":"RemoteDependencyData","baseData":{"ver":2,"name":"HEAD /devstoreaccount1/handleidingen/nl/Handleiding%20Accountancy%20Dashboard/HTML/images/Anlisa_Handleiding___Accountancy_Dashboard_%28%3DBerekeningsmodellen%29_14.png","id":"b0d03387aeacfa6f","data":"http://127.0.0.1:10000/devstoreaccount1/handleidingen/nl/Handleiding%20Accountancy%20Dashboard/HTML/images/Anlisa_Handleiding___Accountancy_Dashboard_%28%3DBerekeningsmodellen%29_14.png","duration":"00:00:00.0081296","resultCode":"200","success":true,"type":"Http","target":"127.0.0.1:10000","properties":{"AspNetCoreEnvironment":"Development","_MS.ProcessedByMetricExtractors":"(Name:'Dependencies', Ver:'1.1')","DeveloperMode":"true","ClientRequestId":"5b18189b-cf40-4156-bb5d-854d1f06639f","ServerRequestId":"ce8885b2-1f61-4126-af00-e19c3645db54"}}}}
Application Insights Telemetry: {"name":"AppDependencies","time":"2023-12-22T09:30:48.1241440Z","iKey":"f1315be9-97ed-4882-bafb-7eadc677640a","tags":{"ai.application.ver":"15.0.0.0","ai.cloud.roleInstance":"JeroenDesmetWr","ai.operation.id":"d85530bc4a3b10875a3f268ad5990f71","ai.operation.parentId":"46cd031e7c44b040","ai.internal.sdkVersion":"dotnetc:2.21.0-429","ai.internal.nodeName":"JeroenDesmetWr"},"data":{"baseType":"RemoteDependencyData","baseData":{"ver":2,"name":"BlobBaseClient.Exists","id":"e26cdb896c2bb0f6","duration":"00:00:00.0133180","success":true,"type":"InProc | Microsoft.Storage","properties":{"AspNetCoreEnvironment":"Development","_MS.ProcessedByMetricExtractors":"(Name:'Dependencies', Ver:'1.1')","DeveloperMode":"true"}}}}
Application Insights Telemetry: {"name":"AppDependencies","time":"2023-12-22T09:30:48.1414945Z","iKey":"f1315be9-97ed-4882-bafb-7eadc677640a","tags":{"ai.application.ver":"15.0.0.0","ai.cloud.roleInstance":"JeroenDesmetWr","ai.operation.id":"d85530bc4a3b10875a3f268ad5990f71","ai.operation.parentId":"a4ea859bb9708dfa","ai.internal.sdkVersion":"dotnetc:2.21.0-429","ai.internal.nodeName":"JeroenDesmetWr"},"data":{"baseType":"RemoteDependencyData","baseData":{"ver":2,"name":"HEAD /devstoreaccount1/handleidingen/nl/Handleiding%20Accountancy%20Dashboard/HTML/images/Anlisa_Handleiding___Accountancy_Dashboard_%28%3DBerekeningsmodellen%29_14.png","id":"0f6cfd96a9aa7561","data":"http://127.0.0.1:10000/devstoreaccount1/handleidingen/nl/Handleiding%20Accountancy%20Dashboard/HTML/images/Anlisa_Handleiding___Accountancy_Dashboard_%28%3DBerekeningsmodellen%29_14.png","duration":"00:00:00.0014581","resultCode":"200","success":true,"type":"Http","target":"127.0.0.1:10000","properties":{"AspNetCoreEnvironment":"Development","_MS.ProcessedByMetricExtractors":"(Name:'Dependencies', Ver:'1.1')","DeveloperMode":"true","ClientRequestId":"bda3b41a-b0dc-4fd5-b6f3-10b7d2eb1159","ServerRequestId":"9871f3a5-048d-4969-9e43-cab8dc7628a2"}}}}
Application Insights Telemetry: {"name":"AppDependencies","time":"2023-12-22T09:30:48.1413875Z","iKey":"f1315be9-97ed-4882-bafb-7eadc677640a","tags":{"ai.application.ver":"15.0.0.0","ai.cloud.roleInstance":"JeroenDesmetWr","ai.operation.id":"d85530bc4a3b10875a3f268ad5990f71","ai.operation.parentId":"46cd031e7c44b040","ai.internal.sdkVersion":"dotnetc:2.21.0-429","ai.internal.nodeName":"JeroenDesmetWr"},"data":{"baseType":"RemoteDependencyData","baseData":{"ver":2,"name":"BlobBaseClient.GetProperties","id":"a4ea859bb9708dfa","duration":"00:00:00.0039784","success":true,"type":"InProc | Microsoft.Storage","properties":{"AspNetCoreEnvironment":"Development","_MS.ProcessedByMetricExtractors":"(Name:'Dependencies', Ver:'1.1')","DeveloperMode":"true"}}}}
Application Insights Telemetry: {"name":"AppDependencies","time":"2023-12-22T09:30:48.1517064Z","iKey":"f1315be9-97ed-4882-bafb-7eadc677640a","tags":{"ai.application.ver":"15.0.0.0","ai.cloud.roleInstance":"JeroenDesmetWr","ai.operation.id":"d85530bc4a3b10875a3f268ad5990f71","ai.operation.parentId":"b109a059f689819c","ai.internal.sdkVersion":"dotnetc:2.21.0-429","ai.internal.nodeName":"JeroenDesmetWr"},"data":{"baseType":"RemoteDependencyData","baseData":{"ver":2,"name":"DELETE /devstoreaccount1/handleidingen/nl/Handleiding%20Accountancy%20Dashboard/HTML/images/Anlisa_Handleiding___Accountancy_Dashboard_%28%3DBerekeningsmodellen%29_14.png","id":"53bf429c6dc1bcb1","data":"http://127.0.0.1:10000/devstoreaccount1/handleidingen/nl/Handleiding%20Accountancy%20Dashboard/HTML/images/Anlisa_Handleiding___Accountancy_Dashboard_%28%3DBerekeningsmodellen%29_14.png","duration":"00:00:00.0446928","resultCode":"202","success":true,"type":"Http","target":"127.0.0.1:10000","properties":{"AspNetCoreEnvironment":"Development","_MS.ProcessedByMetricExtractors":"(Name:'Dependencies', Ver:'1.1')","DeveloperMode":"true","ClientRequestId":"5dff996f-f3b3-452d-afbd-5e674360a954","ServerRequestId":"da97349b-c4c2-4589-8610-8dc0dc0464ba"}}}}
Application Insights Telemetry: {"name":"AppDependencies","time":"2023-12-22T09:30:48.1500018Z","iKey":"f1315be9-97ed-4882-bafb-7eadc677640a","tags":{"ai.application.ver":"15.0.0.0","ai.cloud.roleInstance":"JeroenDesmetWr","ai.operation.id":"d85530bc4a3b10875a3f268ad5990f71","ai.operation.parentId":"46cd031e7c44b040","ai.internal.sdkVersion":"dotnetc:2.21.0-429","ai.internal.nodeName":"JeroenDesmetWr"},"data":{"baseType":"RemoteDependencyData","baseData":{"ver":2,"name":"BlobBaseClient.DeleteIfExists","id":"b109a059f689819c","duration":"00:00:00.0514180","success":true,"type":"InProc | Microsoft.Storage","properties":{"AspNetCoreEnvironment":"Development","_MS.ProcessedByMetricExtractors":"(Name:'Dependencies', Ver:'1.1')","DeveloperMode":"true"}}}}
The program '[21652] testhost.exe' has exited with code 4294967295 (0xffffffff).

### Reproduction Steps

This is the code I used to produce the bug, bear in mind that I replaced the containernames and filenames with dummy data:
`try
{
    var containerClient = await GetBlobContainerClient("xyz", cancellationToken);
    var blobs = containerClient.GetBlobsAsync(BlobTraits.All, BlobStates.All, "prefix", cancellationToken);
    await foreach (var blob in blobs)
    {
        var sourceBlob = containerClient.GetBlobClient("prefix/filename");
        if (await sourceBlob.ExistsAsync(cancellationToken))
        {
            var destinationBlob = containerClient.GetBlobClient("newPrefix/Filename");
            var operation = await destinationBlob.StartCopyFromUriAsync(sourceBlob.Uri, cancellationToken: cancellationToken);
            await operation.WaitForCompletionAsync(cancellationToken);
            if (await IsBlobLocked(sourceBlob, cancellationToken))
                throw new AzureStorageException(AzureStorageExceptionReason.FileLocked);
            await sourceBlob.DeleteIfExistsAsync(DeleteSnapshotsOption.IncludeSnapshots, cancellationToken: cancellationToken);
        }
        else
        {
            _logger.LogWarning("Copy file async, source file does not exist");
        }
    }
}
catch (Exception)
{

    throw;
}`

### Environment

.NET SDK:
 Version:   7.0.403
 Commit:    142776d834

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.403\

Host:
  Version:      7.0.13
  Architecture: x64
  Commit:       3f73a2f186

.NET SDKs installed:
  7.0.403 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

**Comment by jsquire** [comment]
Hi @Loppor.  Thank you for reaching out and we regret that you're experiencing difficulties.  Unfortunately, this is not something that the maintainers of the Azure SDK are able to assist with.  

The behavior that you're asking about is part of the debugger that you're using and is not something that the Azure client has insight into nor can influence.  You don't mention what debugger you're using.  For Visual Studio, discussion of how to report problems can be found [here](https://learn.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022).

I'm going to close this out; if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.
