### ISSUE TITLE
[QUERY] How to migrate WindowsAzure.ServiceBus to Azure.Messaging.ServiceBus in given condition? 

### ISSUE THREAD

**Issue by maomaomqiu** [Azure/azure-sdk-for-net#40880]
### Library name and version

Azure.Messaging.ServiceBus (7.15.0); WindowsAzure.ServiceBus (4.1.1)

### Query/Question

Hi, this is maomaomqiu! I am a newcomer, don't know this question is too stupid **: )** ..
I am now working on deprecating codes of WindowsAzure.ServiceBus to Azure.Messaging.ServiceBus of existing codebase.
# Here is previous mainly code logic
(1) initial queue client ```queueClient```
(2) call ```queueClient.AcceptMessageSessionAsync()``` to get session in loop, until new session acquired is null, then get group of session -> ```sessions (List<MessageSession>)```
(3) for each session (let's call it session0) in sessions, according to it's ```sessionId```, get the session (let's call it session1) by ```queueClient.AcceptMessageSessionAsync(sessionId)``` 
**(4)** use ```session.ReceiveBatchAsync(int messageCount, TimeSpan serverWaitTime)``` to batch receive messages (session here use session1)
... later logic

# Here I want to do after
Here for our codebase, we now have moved part of code to Azure.Messaging.ServiceBus, and wrap ServiceBusSessionProcessor and ServiceBusProcessor, I want to know whether processor can achieve (1) to (4) ? (**my concern is (4)**)

PS: I see part of source code, for processor, it actually will call 
ServiceBusProcessor.cs#StartProcessingAsync -> RunReceiveTaskAsync -> ReceiveAndProcessMessagesAsync -> ReceiveAndProcessMessagesAsync -> ReceiverManager.cs#ReceiveAndProcessMessagesAsync, **maxMessages is assigned as 1**,
![image](https://github.com/Azure/azure-sdk-for-net/assets/154726587/42a2d27d-4164-4497-9afb-8ea557e88de7)

Based on my limit knowledge, 1 solution is introducing **Receiver**?

**Comment by jsquire** [comment]
Hi @maomaomqiu.  Thank you for reaching out.  There are several ways to accomplish what you're looking to do, including using the `ServiceBusSessionProcessor`.  The processor allows you to specify the maximum number of concurrent sessions that you would like to process as part of its configuration.   Setting this value will allow your processor to work with multiple sessions at the same time, similar to what your original code was doing.   

For example:

```csharp
var options = new ServiceBusSessionProcessorOptions
{
    // This tells the processor to work with up to 5 sessions concurrently.
    MaxConcurrentSessions = 5,

    // This tells the processor how many messages can be processed concurrently for each session.
    MaxConcurrentCallsPerSession = 2,

    // If you'd like to limit to a set of well-known sessions rather than accepting the next available
    // this is how you would do that.
    SessionIds = { "my-session", "your-session" },
};

await using ServiceBusSessionProcessor processor = client.CreateSessionProcessor(queueName, options);
```

More discussion and examples can be found in the [Session Processor sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample05_SessionProcessor.md#processing-messages-from-a-session-enabled-queue).

**Comment by maomaomqiu** [comment]
Thanks @jsquire 's promptly reply 👍 👍 
Let me add more details about it.. Before see you answer I just ask one of my colleague, and get reply 
- If messages are **independent**, param like `MaxConcurrentCallsPerSession` can take similar effect like what I want to do in **(4)**
- dependent -> can process multiple messages as a whole

Unluckily, in previous code logic, messages are processed as a whole
(5) Process messages

(3), (4), (5)
```
var messagesA = new List<MessageA>();
var messagesB = new List<MessageB>();


for session in sessions
{
    // session(session0), newSession(session1)
    // step (3)
    var newSession = queueClient.AcceptMessageSessionAsync(session.SessionId);

    // step (4)
    var result = newSession.ReceiveBatchAsync(50, TimeSpan);
    
    // check result not null and count > 0
    // step (5)
    if (session.SessionId == IdA)
    {
        
    }
}
```

**Comment by maomaomqiu** [comment]
PS: I will add more details to this issue

**Comment by maomaomqiu** [comment]
```
step (1) initial queue client queueClient

step (2) call queueClient.AcceptMessageSessionAsync() to get session in loop, until new session acquired is null, then get group of session -> sessions (List<MessageSession>)

sessions = new List<MessageSession>();

sessionNew = queueClient.AcceptMessageSessionAsync();
Timer timer = null;

while (sessionNew != null)
{
    sessions.add(sessionNew);

    if (timer == null)
    {
        timer = new Timer (RenewSessionLocks, sessions, dueTime, period);
    }

   sessionNew = queueClient.AcceptMessageSessionAsync();
   
    
}

// RenewSessionLocks
// tasks ← all session in sessions will call session.RenewLockAsync()
// Task.WhenAll(tasks)

var messagesA = new List<MessageA>();
var messagesB = new List<MessageB>();


for session in sessions
{
    // session(session0), newSession(session1)
    // step (3)
    var newSession = queueClient.AcceptMessageSessionAsync(session.SessionId);

    // step (4)
    var result = newSession.ReceiveBatchAsync(50, TimeSpan);
    
    // check result not null and count > 0
    // step (5)
    if (session.SessionId == IdA)
    {
        messagesA.addRange(result.OfType<MessageA>());
    }
    else
    {
        messagesB.addRange(result.OfType<MessageB>());
    }
}
```

**Comment by maomaomqiu** [comment]
I plan to do below change -
# Before WindowsAzure.ServiceBus (4.1.1)
// the type of sessionNew is MessageSession
sessionNew = queueClient.AcceptMessageSessionAsync()
sessionNew / newSession / session can do operation 
- newSession.ReceiveBatchAsync(50, TimeSpan)
- session.RenewLockAsync()


# After Azure.Messaging.ServiceBus (7.15.0)
// the type of sessionNew is ServiceBusSessionReceiver
sessionNew = ServiceBusClient.AcceptNextSessionAsync(queueName)
- sessionNew, as ServiceBusSessionReceiver, can do
    - sessionNew.ReceiveMessagesAsync(int maxMessages, TimeSpan maxWaitTime)
    - sessionNew.RenewSessionLockAsync()

I see 
- in WindowsAzure.ServiceBus  and ```MessageSession : MessageReceiver```
![image](https://github.com/Azure/azure-sdk-for-net/assets/154726587/e4e26dd4-7757-48c9-b6b7-6318c096e035)

- in Azure.Messaging.ServiceBus and ```ServiceBusSessionReceiver : ServiceBusReceiver```
![image](https://github.com/Azure/azure-sdk-for-net/assets/154726587/f283f066-0649-4c1a-8d2c-713d4f406a8a)

**Comment by jsquire** [comment]
I think there's some confusion around the configuration options available:

- `MaxConcurrentSessions` - This asks the question how many sessions should I process concurrently?   Each message in a given session is processed in order.   This one is the direct translation of your previous pattern of "collect all the sessions, use a separate receiver for each."

- `MaxConcurrentCallsPerSession`- This asks the question how many messages should I process concurrently for a given session?   If you have ordering needs for messages in a session, you'll want to leave this as 1.

You could also follow your existing pattern more closely by using `ServiceBusClient::AcceptNextSession`, which returns a receiver that can be used exclusively with that session.   Call that for as many sessions as you'd like to process concurrently and call `ReceiveMessagesAsync` until you're done with the session.  

The only difference is how much work your application has to do.  The processor handles resilience and error conditions for you, as well as optionally handling lock renewal and message completion.  The client/receiver path requires that your application handle those concerns.

**Comment by maomaomqiu** [comment]
Thanks @jsquire 's detail explanation!   : ) 
Sorry for not detailly go through the source code of processor, and greatly thank you point out key points for me to dig into.

My team member has migrated most of code to **Processor**, but some legacy usage, like use ReceiveBatchAsync(), can not equally move to **Processor** with `MaxConcurrentSessions` as messages are **dependent** handled.

This issue can be closed for now, thank you!
