### ISSUE TITLE
Microsoft.Azure.Management.DataFactory : ctor method not found

### ISSUE THREAD

**Issue by savioz** [Azure/azure-sdk-for-net#4089]
I have this error using VS 2017 and the package Microsoft.Azure.Management.DataFactory  v 0.5.0 Preview

Void Microsoft.Azure.Management.DataFactory.DataFactoryManagementClient..ctor(Microsoft.Rest.ServiceClientCredentials, System.Net.Http.DelegatingHandler[]

**Comment by dsgouda** [comment]
@savioz are you still running into this issue? Please provide a detailed stack trace if possible.

**Comment by savioz** [comment]
no i solved that a few weeks ago

**Comment by dsgouda** [comment]
Thanks @savioz closing the issue.

**Comment by biashka** [comment]
savioz, how did you fix this error? I have the same problem when I promote my solution to a different server.
Locally in VS the web site works as expected.
