### ISSUE TITLE
[BUG] Singular peek and receive message operations on a receiver should return a nullable message.

### ISSUE THREAD

**Issue by craigb** [Azure/azure-sdk-for-net#40901]
### Library name and version

Azure.Messaging.ServiceBus 7.16.2

### Describe the bug

Nullability hints incorrect for singular Peek and Receive methods.

### Expected behavior

If the API is expected to return `null`, the return value should be nullable.

### Actual behavior

Both singular Peek and Receive methods on the receiver return non-nullable messages, but the return value is `null` when there are no messages in the message container.

### Reproduction Steps

create a servicebus namespace
create a queue
connect a receiver to the queue
peek the empty queue

**Comment by jsquire** [comment]
Hi @craigb.  Thank you for reaching out and we regret that you're experiencing difficulties.  This is by design.  The Azure client libraries are intentionally not annotated for nullable reference types, other than `Azure.Core`.    Rationale and discussion can be found in #8880.
