### ISSUE TITLE
clarification on documentation about "Stream chat messages"

### ISSUE THREAD

**Issue by sabbadino** [Azure/azure-sdk-for-net#40906]
### Library name and version

Azure.AI.OpenAI 1.0.0-beta.12

### Query/Question

in the docs 

https://github.com/Azure/azure-sdk-for-net/blob/Azure.AI.OpenAI_1.0.0-beta.12/sdk/openai/Azure.AI.OpenAI/README.md

there is a section named "Stream chat messages with non-Azure OpenAI".
Does it mean that Azure OpenAI does not support chat-completion streaming , or does not this SDK ? 
I have been using chat streaming against a an azure open ai instance and it looks like working.
thanks 
Enrico

**Comment by raeesgillani** [comment]
I think this can be closed, as the provided link now includes a clearer definition:

> "It can connect to Azure OpenAI resources or to the non-Azure OpenAI inference endpoint, making it a great choice for even non-Azure OpenAI development."

@sabbadino, it means you are not isolated to using just the endpoints available via Azure OpenAI.

**Comment by sabbadino** [comment]
Fine for me :)

**Comment by sabbadino** [comment]
Ok
