### ISSUE TITLE
[FEATURE REQ] DI builders should have a `Services` property

### ISSUE THREAD

**Issue by aelij** [Azure/azure-sdk-for-net#40910]
### Library name

Azure.Core

### Please describe the feature.

Builders like `IAzureClientBuilder` should have a `IServiceCollection Services { get; }` property, so that fluent calls could return to the original context. This is a standard in .NET builders, see for example [OptionsBuilder<TOptions>.Services](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.options.optionsbuilder-1.services).

**Comment by jsquire** [comment]
Hi @aelij.  Thank you for your feedback.  We'll take this into consideration.

**Comment by jsquire** [comment]
@AlexanderSher:  Would you please take point for understanding the end-to-end scenario and making a recommendation on whether we should make this change?

**Comment by AlexanderSher** [comment]
@aelij Unfortunately, `IAzureClientBuilder` is defined in `Azure.Core` library which doesn't reference `Microsoft.Extensions.DependencyInjection.Abstractions` assembly that contains `IServiceCollection` interface.

What is the scenario where you need this property?

**Comment by aelij** [comment]
@AlexanderSher I see. That does complicate things.

One specific example where it would've helped is implementing a `WithKey` method for using the new keyed DI in .NET 8. Of course there's a workaround, to add it as an additional param: 

   ```cs
    public static IAzureClientBuilder<TClient, TOptions> WithKey<TClient, TOptions>(this IAzureClientBuilder<TClient, TOptions> builder, IServiceCollection services, string name) where TClient : class where TOptions : class
    {
        services.AddKeyedSingleton(name, (sp, key) => sp.GetRequiredService<IAzureClientFactory<TClient>>().CreateClient((key as string)));
        return builder.WithName(name);
    }
   ```

I'll close this issue, as it probably can't be fixed easily.
