### ISSUE TITLE
return SelectionMarkState

### ISSUE THREAD

**Issue by nczimmerman** [Azure/azure-sdk-for-net#40913]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/azure.ai.formrecognizer.models.selectionmarkstate?view=azure-dotnet

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.AI.FormRecognizer.Models/SelectionMarkState.xml

### Document Version Independent Id

f809162b-827b-face-4313-31e27d70fcf8

### Article author

@azure-sdk

### Metadata

* ID: 8e1743ba-6e1e-22d7-bbbf-7373ed18af5d 
* Service: **azure**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by kinelski** [comment]
Hello @nczimmerman,

Could you tell us exactly where the typo is and what would be the expected text?

**Comment by nczimmerman** [comment]
Thank you for your response. Please close the issue.
