### ISSUE TITLE
[QUERY] Clean Up Session State with ServiceBusSessionProcessor

### ISSUE THREAD

**Issue by ben-page** [Azure/azure-sdk-for-net#40927]
### Library name and version

Azure.Messaging.ServiceBus 7.17.1

### Query/Question

How are users intended to clean up session state when using a ServiceBusSessionProcessor?

When there are no messages in a session ServiceBusSessionProcessor simply stop raising events. The session state will persist indefinitely. There's no chance to check the state for an expiration and clean it up. 

On the other hand ServiceBusSessionReceiver still accepts the session even if there are no active messages, affording an opportunity to clean up the session state.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.  Please expect and forgive slow responses during the US holiday season.

**Comment by JoshLove-msft** [comment]
Hi @ben-page, you can subscribe to the [SessionClosingAsync event](https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebussessionprocessor.sessionclosingasync?view=azure-dotnet) so that you can execute code when the processor is done with a session. Note that this doesn't mean there will never be more messages for that session (this is entirely dependent on your application), but it does mean that the processor timed out based on the [SessionIdleTimeout](https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebussessionprocessoroptions.sessionidletimeout?view=azure-dotnet) setting without receiving any more messages for that session.

**Comment by ben-page** [comment]
@JoshLove-msft thank you for a the prompt response, but that doesn't quite address my question.

I'll elaborate. Cleaning up session state when the processor closes it isn't particularly useful. If the session state doesn't need to outlive the current receiver's lock on the session, why even use session state? You could just hold the state in the application.

I think the most common use case for session state is when you have some kind of pattern, such as a saga, where related messages will arrive at somewhat random intervals. But if something were to fail and the final message was never sent, then the session state would persist indefinitely.

At least that's the case for ServiceBusSessionProcessor, which appears to have no way to access a session that does not have active messages. Alternatively if you are using a ServiceBusSessionReceiver, you would still end up with a lock on the session though there are no messages. So if your session state stored an expiration, the application would have a chance to clean it up.

**Comment by JoshLove-msft** [comment]
> I think the most common use case for session state is when you have some kind of pattern, such as a saga, where related messages will arrive at somewhat random intervals. But if something were to fail and the final message was never sent, then the session state would persist indefinitely.

If this is the pattern you are using, could you clean up the session state when the final message arrives? Are you able to detect such a final message? Or is the cleanup based on some expiration time?

> At least that's the case for ServiceBusSessionProcessor, which appears to have no way to access a session that does not have active messages. Alternatively if you are using a ServiceBusSessionReceiver, you would still end up with a lock on the session though there are no messages. So if your session state stored an expiration, the application would have a chance to clean it up.

You can still specify specific [SessionIds](https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebussessionprocessoroptions.sessionids?view=azure-dotnet#azure-messaging-servicebus-servicebussessionprocessoroptions-sessionids) to process, in which case those sessions will be opened even if there are no messages available.
