### ISSUE TITLE
[Form Recognizer] The environment has not become ready in UsGov cloud.

### ISSUE THREAD

**Issue by zedy-wj** [Azure/azure-sdk-for-net#40923]
We are running live Tests against other clouds like US Gov and Azure China Cloud. The goal is to check whether new azure sdk package work with other clouds or not.

**Error Description:**
Some test cases using `TestEnvironment` failed to run on UsGov cloud. For details, please click [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3366128&view=logs&j=f85fd28d-9b31-57cb-532c-c4f6fd03bb12&t=a85abebb-09f0-5e98-08e3-a8d6823bd2df&l=435).

**Error Message:**
`OneTimeSetUp: System.InvalidOperationException : The environment has not become ready, check your TestEnvironment.IsEnvironmentReady scenario.`

**Expected Behavior:**
These test cases can run normally.

@scottaddie , @AlexGhiondea, @benbp , @maririos, @meeraharidasa , @mayurid for notification.

**Comment by jsquire** [comment]
This is a transient issue with the ARM plane.  No action is needed nor can be taken from the client library.   Closing.
