### ISSUE TITLE
[Question] Dose the Service bus processor support pick derral message

### ISSUE THREAD

**Issue by AbeGeMS** [Azure/azure-sdk-for-net#40928]
### Library name and version

Azure.Messaging.ServiceBus

### Query/Question

I used ServiceBusSessionProcessor to handle my session queue's message.
while I deferred a message like below:
`  
await args.DeferMessageAsync(args.Message, new Dictionary<string, object>(1) { { "ScheduledEnqueueTime", DateTime.UtcNow.AddMinutes(1) } });
`
 Then I would like to pick this message 1 minutes later. However, I wait for a long time(30minutes+) but this message has never been picked by the processor.
So,  I would like to know whether the service bus processor support "deferred message"? If so how should I set the processor?
If not, would you please recommend a best practice about My case: my app respossible for upload the messages to a website. However as to the volume of the message is very large. So, the website sometime throttle my request. that means I need to wait 20minutes to upload then again. So, I would like to reschedule the message and pick then 20 minute again.
my app haven't storage. So, I couldn't maintain the sequence number and I don't want maintain a timer for this cause the message is too large. I need to handle other message immediately.

the best solution is I could use DeferMessageAsync method to reschedule the message. but it looks like the server bus processor doesn't work.
My workaround ugly solution is that remove the current message and create a new one with schedule time and send them to service bus again.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.  Please expect and forgive slow responses during the US holiday season.

**Comment by JoshLove-msft** [comment]
Deferred messages won't be automatically picked up by the processor because you need to receive them using the sequence number of the message. You can receive deferred messages within your handler for the `ProcessMessageAsync` event doing the following:
```c#
async Task ProcessMessage(ProcessMessageEventArgs args)
{
  ProcessorReceiveActions receiveActions = args.GetReceiveActions();
  IReadOnlyList<ServiceBusReceivedMessage> receivedMessages = await receiveActions.ReceiveDeferredMessagesAsync( new [] { << sequence number 1>>, << sequence number 2 >> });
}
```

You could also just use a regular `ServiceBusReceiver` to accomplish the same thing - which is more flexible as you can receive the deferred messages whenever you want, not just when a "regular" message has been received by the processor.

**Comment by AbeGeMS** [comment]
> Deferred messages won't be automatically picked up by the processor because you need to receive them using the sequence number of the message. You can receive deferred messages within your handler for the `ProcessMessageAsync` event doing the following:
> 
> ```cs
> async Task ProcessMessage(ProcessMessageEventArgs args)
> {
>   ProcessorReceiveActions receiveActions = args.GetReceiveActions();
>   IReadOnlyList<ServiceBusReceivedMessage> receivedMessages = await receiveActions.ReceiveDeferredMessagesAsync( new [] { << sequence number 1>>, << sequence number 2 >> });
> }
> ```
> 
> You could also just use a regular `ServiceBusReceiver` to accomplish the same thing - which is more flexible as you can receive the deferred messages whenever you want, not just when a "regular" message has been received by the processor.

Thank you, @JoshLove-msft. This is exactly what we needed. However, we have encountered the same requirement of deferring a specific time to pick up a message multiple times in our industry. It would be much more convenient if the service bus allowed for rescheduling of messages, rather than requiring the use of sequence numbers. Although the 'Defer Message' feature exists, it seems that very few people use it and instead opt for a workaround of copying and scheduling a new message. We are interested in learning more about the use cases for the current 'Defer Message' feature.
And we believe that it would be beneficial if the service bus SDK to support message deferral specific time:
e.g.
`        public async Task MessageHandler(ProcessMessageEventArgs args, IMessageSender sender)
        {
            args.DeferMessageAsync(args.Message,System.TimeSpan.FromMinutes(20));
}
`
Then I could pick it as "regular" message in 20 minutes later, instead of using a sequence number and maintain a timer(....It's too uxxxx :))

**Comment by JoshLove-msft** [comment]
The rescheduling feature is essentially the concept of abandoning a message with delay. The feature request can be found in the Service Bus repo - https://github.com/Azure/azure-service-bus/issues/454. Closing this issue out as a duplicate. Let us know if you have further questions.
