### ISSUE TITLE
[BUG] BlobClient cannot read blobs with # characters in name

### ISSUE THREAD

**Issue by jkdmyrs** [Azure/azure-sdk-for-net#40925]
### Library name and version

Azure.Storage.Blobs 12.19.1

### Describe the bug

The `BlobClient` incorrectly truncates blob file names if the name contains a `#` character.

### Expected behavior

The following code should output: 

`example#test.json` 
`example.json`

Code:

```c#
using Azure.Identity;
using Azure.Storage.Blobs;

BlobClient blobClient1 = new(new Uri("https://example.blob.core.windows.net/example/exmple#test.json"), new DefaultAzureCredential());
Console.WriteLine(blobClient1.Name);

BlobClient blobClient2 = new(new Uri("https://example.blob.core.windows.net/example/exmple.json"), new DefaultAzureCredential());
Console.WriteLine(blobClient2.Name);
``` 

### Actual behavior

The code outputs:
`example`
`example.json`

`example#test.json` is truncated at the `#` character.

### Reproduction Steps

- create a .net 8 console app
- install `Azure.Storage.Blobs` (and `Azure.Identity`)
- run this code:
```c#
using Azure.Identity;
using Azure.Storage.Blobs;

BlobClient blobClient1 = new(new Uri("https://example.blob.core.windows.net/example/example#test.json"), new DefaultAzureCredential());
Console.WriteLine(blobClient1.Name);

BlobClient blobClient2 = new(new Uri("https://example.blob.core.windows.net/example/example.json"), new DefaultAzureCredential());
Console.WriteLine(blobClient2.Name);
```

**Comment by jkdmyrs** [comment]
Seems like this was fixed previously... is this a regression?
https://github.com/Azure/azure-sdk-for-net/issues/11602

**Comment by amnguye** [comment]
Will be resolved by https://github.com/Azure/azure-sdk-for-net/pull/44941

after it releases with v12.21.0 of Azure.Storage.Blobs

**Comment by jkdmyrs** [comment]
@amnguye thanks!
