### ISSUE TITLE
[QUERY] Is MessagingCommunicationException(WindowsAzure.ServiceBus (4.1.1)) equal to ServiceBusFailureReason.ServiceCommunicationProblem (Azure.Messaging.ServiceBus (7.15.0)))

### ISSUE THREAD

**Issue by maomaomqiu** [Azure/azure-sdk-for-net#40934]
### Library name and version

Azure.Messaging.ServiceBus (7.15.0);WindowsAzure.ServiceBus (4.1.1)

### Query/Question

Hi, this is maomaomqiu, thanks for your previous timely and kind help : ) !

I am still doing migration work from WindowsAzure.ServiceBus (4.1.1) to Azure.Messaging.ServiceBus (7.15.0)
# Before WindowsAzure.ServiceBus (4.1.1)
```
if (exception is MessagingCommunicationException) { do something } 
```

PS: I search latest versin of WindowsAzure.ServiceBus, MessagingCommunicationException seems renamed

# After
I search source code of Azure.Messaging.ServiceBus (7.15.0), find the possible proper override way is 
```
if (exception is ServiceBusException sbEx && (sbEx.Reason == ServiceBusFailureReason.ServiceCommunicationProblem)) {do something}
```

Could you tell me is my understanding right?

**Comment by jsquire** [comment]
Hi @maomaomqiu.  Thank you for reaching out and we regret that you're experiencing difficulties.  Yes, I believe the `ServiceCommunicationProblem` reason code is equivalent to the `MessagingCommunicationException` from the legacy package.

That said, these represent the most generic "something went wrong when talking to the service, but the client wasn't informed of exactly what".   Generally, these indicate a network-level error whose details you would want to retrieve from the inner exception.
