### ISSUE TITLE
Feature Request: deploy application refers netstandard2.0 - e.g. deploying Durable Functions

### ISSUE THREAD

**Issue by SayusiAndo** [Azure/azure-sdk-for-net#4093]
Hi all,

I wanted to deploy my Durable Function Application with Deployment Project using Visual Studio. When I try to build Deployment project which has a reference to my Durable Function project (it uses netstandard2.0 as class library) throws the following error:

> Project '..\AzureDurableFunctions\AzureDurableFunctions.csproj' targets 'netstandard2.0'. It cannot be referenced by a project that targets 'Deployment,Version=1.0'.

Did I make an error here or it is not possible to use Deployment project to deploy Durable Function project?

Thanks for any help in advance!

**Comment by shahabhijeet** [comment]
@SayusiAndo please send this as a feedback at this location.
This issues seems likely for VS Tools for Azure.
This repo is for Azure .NET SDKs
 https://developercommunity.visualstudio.com/
