### ISSUE TITLE
BLOB Snapshot

### ISSUE THREAD

**Issue by kishordaGit** [Azure/azure-sdk-for-net#40946]
### Type of issue

Typo

### Description

Is SDK creates themselves do automatically create blob snapshots without explicit user instructions. OR Snapshot Creation by Default:

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/overview/azure/support?view=azure-dotnet

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/latest/support.md

### Document Version Independent Id

bdc99a6f-9827-9165-f626-a54f7c308d7d

### Article author

@azure-sdk

### Metadata

* ID: 5f9a6c35-5bf2-249f-b622-92e5db93e421 
* Service: **support**

**Comment by kishordaGit** [comment]
we are using azure sdk, however, but found the blob snapshot automatically. We have not used any API to create them. we guess it creates snapshots by chance of the manner we implemented. for example we upload and copy blobs. We found the snapshots created with current version for few blobs and not for all.

**Comment by jsquire** [comment]
> we are using azure sdk, however, but found the blob snapshot automatically. We have not used any API to create them. we guess it creates snapshots by chance of the manner we implemented. for example we upload and copy blobs. We found the snapshots created with current version for few blobs and not for all.

Thank you for the additional context.  However, there are many packages that fall under the Azure SDK umbrella, so this does not help us understand what you're inquiring about.   Would you please provide the name of the package and which version you're using?   A snippet that demonstrates how you're using the package would also be helpful.

**Comment by jsquire** [comment]
As this is still unable to be triaged or acted on due to lack of information, I'm going to close this out.  If you still require assistance, please open a new issue with the name of the package and which version you're using, along with the description of your scenario.  A snippet that demonstrates how you're using the package would also be helpful.
