### ISSUE TITLE
> how would I detect the dependency or even installation of the Azure Identity sdk ?

### ISSUE THREAD

**Issue by mezzofix** [Azure/azure-sdk-for-net#40945]
> how would I detect the dependency or even installation of the Azure Identity sdk ?

Hi @mezzofix.  Unfortunately, this is not something that we're able to assist with.  The answer will be specific to your organization, environment, tooling preferences, and budget and is not related to the Azure SDK package itself.  If your organization has a security or ops team, you may want to ask there.  Otherwise, you may want to start by looking into the [dotnet CLI list package --vulnerable](https://devblogs.microsoft.com/nuget/how-to-scan-nuget-packages-for-security-vulnerabilities/).   There are also a number of third-party tools that could be found via web search.

_Originally posted by @jsquire in https://github.com/Azure/azure-sdk-for-net/issues/40693#issuecomment-1852658581_

**Comment by jsquire** [comment]
Hi @mezzofix.  The answer to this has not changed; this is not an issue that we're able to assist with.  Was there a specific follow-up that you wanted to ask?

**Comment by jsquire** [comment]
Closing this as a duplicate of #40693, as that has been reopened and has the original context.
