### ISSUE TITLE
[MQ] Test cases in `Azure.ResourceManager.DataFactory` are not properly using the base type in a discriminated set

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/azure-sdk-for-net#40940]
### Information

The generator will generate the base type in a discriminated set as abstract classes because the base type does not have a discriminator value and the discriminator property is always required in the schema.

We should always instantiate a derived type of the base in our test cases, but the test cases in `Azure.ResourceManager.DataFactory` are using base types of discriminated sets quite a lot

The impacted test cases are tagged with the `Ignore` attributes.

**Comment by pallavit** [comment]
@ArcturusZhang I see you assigned this to me, were you looking for any particular action from me?

**Comment by ArcturusZhang** [comment]
> @ArcturusZhang I see you assigned this to me, were you looking for any particular action from me?

not really. The assignment comes from the template. I will remove.

**Comment by ArcturusZhang** [comment]
@ruowan for your reference, you could pay attention to the comments in this PR: https://github.com/Azure/azure-sdk-for-net/pull/40965

**Comment by ruowan** [comment]
Thanks. @ArcturusZhang We have created a PR to fix it. And that PR has been merged.  So you could close this issue
