### ISSUE TITLE
[BUG] Uploading large item can cause smaller items to be dropped

### ISSUE THREAD

**Issue by Arithmomaniac** [Azure/azure-sdk-for-net#40941]
### Library name and version

Azure.Monitor.Ingestion

### Describe the bug

Someone calling `LogsIngestionClient.UploadAsync(ruleId, streamName, logs)` can, if the last item in `logs` is extremely large, end up having some previous items not written to Log Analytics, 

### Expected behavior

Suppose `logs` is `[itemOfSizeKib(20, id: "A"), itemOfSizeKib(20, id: "B"), itemOfSizeKib(1025, id: "C")]`.

`C` should be uploaded first by itself, then `A` and `B` together as a batch.

### Actual behavior

Only `C` will be uploaded; `A` and `B` will be dropped.

### Reproduction Steps

Haven't actually run, but see how there is no flushing here if the oversize item is the last item:

https://github.com/Azure/azure-sdk-for-net/blob/eca420c8d9b08c059cc4609a9e2ac8ee501b9491/sdk/monitor/Azure.Monitor.Ingestion/src/LogsIngestionClient.cs#L128-L139

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.  Please expect and forgive delays during the US holiday season.

**Comment by nisha-bhatia** [comment]
A new Nuget package has been released fixing this!
