### ISSUE TITLE
AppAuthentication 1.1.0-preview: Could not load file or assembly (ActiveDirectory)

### ISSUE THREAD

**Issue by tyjen** [Azure/azure-sdk-for-net#4094]
I'm trying to acquire a token from the new AppAuthentication package. Ideally the AzureServiceTokenProvider would use the Windows Integrated Identity, however it's throwing an exception in GetAccessTokenAsync:

`{"Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory.Platform, Version=3.19.1.3001, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)":"Microsoft.IdentityModel.Clients.ActiveDirectory.Platform, Version=3.19.1.3001, Culture=neutral, PublicKeyToken=31bf3856ad364e35"}`

The inner exception complains about a different version of ActiveDirectory:

`{"Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory.Platform, Version=3.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)":"Microsoft.IdentityModel.Clients.ActiveDirectory.Platform, Version=3.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"}`

I've also tried this on the latest stable version (0.5.0.5) and get the same problem.

**Comment by nonik0** [comment]
It's been a while, are you still having this issue? Let us know if you were able to use assembly redirect to fix it.

**Comment by varunsh-msft** [comment]
@shahabhijeet , can you please close this issue? Thanks!
