### ISSUE TITLE
[BUG] LazyLoadingReadOnlyStream ReadAsync returns less bytes when we read 4MB chunks.

### ISSUE THREAD

**Issue by bcarthic** [Azure/azure-sdk-for-net#40955]
### Library name and version

Azure.Storage.Blobs 12.19.1

### Describe the bug

LazyLoadingReadOnlyStream ReadAsync returns less bytes if the first few iteration reads less than 4MB. For example, if my file size is 12000000 bytes and I read 1837 as first iteration then if I read 4MB for second chunk, I expect to read the whole 4MB is the file length is more than 4MB. But the stream reads fewer bytes.

 

### Expected behavior

This is a theoretical expected behavior for file size of 12000000 bytes.

```
BlockIteration: 1, Requested size: 1837 bytes, Read blocks: 1837 bytes
BlockIteration: 2, Requested size: 4194304 bytes, Read blocks: 4196141 bytes
BlockIteration: 3, Requested size: 4194304 bytes, Read blocks: 8390445 bytes
BlockIteration: 4, Requested size: 3609555 bytes, Read blocks: 12000000 bytes
```

### Actual behavior

This is an actual behavior for file size of 12000000 bytes.  We can see from below, the second iteration reads less than 4MB but we requested to read 4MB.

BlockIteration: 1, Requested size: 1837 bytes, Read blocks: 1837 bytes, TotalBytesRead: 1837 bytes
_BlockIteration: 2, Requested size: 4194304 bytes, **Read blocks: 4192467 bytes**, TotalBytesRead: 4194304 bytes_
BlockIteration: 3, Requested size: 4194304 bytes, Read blocks: 4194304 bytes, TotalBytesRead: 8388608 bytes
BlockIteration: 4, Requested size: 3609555 bytes, Read blocks: 3609555 bytes, TotalBytesRead: 11998163 bytes
BlockIteration: 5, Requested size: 1837 bytes, Read blocks: 1837 bytes, TotalBytesRead: 12000000 bytes

### Reproduction Steps

Below is a sample program to repro this issue. Use a file greater than 12MB. 

LinqPad share link - https://share.linqpad.net/6fber6ac.linq

```csharp
public class Program
{
	public static async Task Main(string[] args)
	{
		var lazyLoadTest = new LazyLoadTest();
		await lazyLoadTest.UploadAndRetrieveInBlocks();
	}
}

public class LazyLoadTest
{
	private BlobContainerClient container;
	private string sourceFilePath = @"C:\Temp\randomtxtFile.txt";
	private BlockBlobClient blobClient;
	public LazyLoadTest()
	{
		string storageConnectionString = "UseDevelopmentStorage=true";
		container = new BlobContainerClient(storageConnectionString, "test");
		blobClient = container.GetBlockBlobClient("blockblob.dcm");
	}

	public async Task UploadAndRetrieveInBlocks()
	{
		const int stagedBlockSize = 4 * 1024 * 1024;
		
		using FileStream uploadFileStream = File.OpenRead(sourceFilePath);
		await blobClient.UploadAsync(uploadFileStream);
		uploadFileStream.Close();
		
		using (var stream = await blobClient.OpenReadAsync())
		{
			byte[] buffer = ArrayPool<byte>.Shared.Rent(Math.Min(stagedBlockSize, (int)stream.Length));
			long totalBytesRead = 0;
			int blockIteration = 0;

			var blocks = GetBlockLengths((int)stream.Length, 1837, stagedBlockSize);
			Console.Error.WriteLine("-------------------------------------------------------------------------------------------");
			try
			{
				while (totalBytesRead < stream.Length)
				{
					var bytesToRead = blockIteration >= blocks.Count ? Math.Min(stagedBlockSize, stream.Length - totalBytesRead) : blocks[blockIteration];
					long bytesRead = await stream.ReadAsync(buffer, 0, (int)bytesToRead);
					blockIteration++;
					totalBytesRead += bytesRead;
					var msg = $"BlockIteration: {blockIteration}, Requested size: {bytesToRead}, Read blocks: {bytesRead}, TotalBytesRead: {totalBytesRead}";
					Console.Error.WriteLine(msg);
				}
			}
			finally
			{
				ArrayPool<byte>.Shared.Return(buffer);
			}
		}
	}

	private List<int> GetBlockLengths(int streamLength, int initialBlockLength, int stageBlockSizeInBytes)
	{
		var blockLengths = new List<int>();
		int fileSizeWithoutFirstBlock = streamLength - initialBlockLength;
		int numStagesWithoutFirstBlock = (int)Math.Ceiling((double)fileSizeWithoutFirstBlock / stageBlockSizeInBytes) + 1;

		int bytesRead = 0;
		for (int i = 0; i < numStagesWithoutFirstBlock; i++)
		{
			int blockSize = i == 0 ? initialBlockLength : Math.Min(stageBlockSizeInBytes, streamLength - bytesRead);
			blockLengths.Add(blockSize);
			bytesRead += blockSize;

			Console.WriteLine($"BlockIteration: {i + 1}, Requested size: {blockSize}, Read blocks: {bytesRead}");
		}

		return blockLengths;
	}
}
```

**Output**

BlockIteration: 1, Requested size: 1837 bytes, Read blocks: 1837 bytes
BlockIteration: 2, Requested size: 4194304 bytes, Read blocks: 4196141 bytes
BlockIteration: 3, Requested size: 4194304 bytes, Read blocks: 8390445 bytes
BlockIteration: 4, Requested size: 3609555 bytes, Read blocks: 12000000 bytes

-------------------------------------------------------------------------------------------

BlockIteration: 1, Requested size: 1837 bytes, Read blocks: 1837 bytes, TotalBytesRead: 1837 bytes
BlockIteration: 2, Requested size: 4194304 bytes, Read blocks: 4192467 bytes, TotalBytesRead: 4194304 bytes
BlockIteration: 3, Requested size: 4194304 bytes, Read blocks: 4194304 bytes, TotalBytesRead: 8388608 bytes
BlockIteration: 4, Requested size: 3609555 bytes, Read blocks: 3609555 bytes, TotalBytesRead: 11998163 bytes
BlockIteration: 5, Requested size: 1837 bytes, Read blocks: 1837 bytes, TotalBytesRead: 12000000 bytes

**Comment by seanmcc-msft** [comment]
This behavior is by-design.  The LazyLoadingReadOnlySteam implements the [Stream](https://learn.microsoft.com/en-us/dotnet/api/system.io.stream?view=net-8.0) interface.  According to the spec, the [.ReadAsync()](https://learn.microsoft.com/en-us/dotnet/api/system.io.stream.readasync?view=net-8.0#system-io-stream-readasync(system-byte()-system-int32-system-int32)) method can return less that the specified number of requested bytes:

> A task that represents the asynchronous read operation. The value of the TResult parameter contains the total number of bytes read into the buffer. The result value can be less than the number of bytes requested if the number of bytes currently available is less than the requested number, or it can be 0 (zero) if count is 0 or if the end of the stream has been reached.
