### ISSUE TITLE
[Doc] Add an example how to update a resource - Migrating from old to new management SDK

### ISSUE THREAD

**Issue by PFYasu** [Azure/azure-sdk-for-net#40959]
Hello,

Our internal project uses `Microsoft.Azure.Management._.Fluent` packages. We are planning the migration to `Azure.ResourceManager._` packages to be up to date. 

We're using your migration [docs](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/resourcemanager/Azure.ResourceManager/docs/MigrationGuide.md#migrating-from-track-1-fluent-sdk-to-track-2-sdk) which explain how to migrate between the packages. Unfortunatelly we haven't seen any information on how to update a resource in the new way, using the _ResourceManager_.

For example, let's say I have a _virtual machine resource_. I want to change its network profile by setting first network interface as primary. I don't want to change other properties of the virtual machine.

Which way to handle it is correct?
**a)** Get the vm resorce by name, modify its _Data_ property and then call `VirtualMachineCollection.CreateOrUpdate(WaitUntil.Completed, "myVmName", myVm.Data)` 
- _myVm_ is a VirtualMachineResource variable for which I've set network interface as primary.

**b)** Create a new object of `VirtualMachineData`, set there a properties which I want to modify, and then call `VirtualMachineCollection.CreateOrUpdate(WaitUntil.Completed, "myVmName", virtualMachineDataToModify)` 
- _virtualMachineDataToModify_ is a new VirtualMachineData variable which only contains the prop to set first nic as primary.

Your documentation only contains examples how to create and delete resources. Can you add there a small example regarding to resource updates?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Hey @PFYasu , thank you for reaching out to us about the Azure SDK for .NET migration, @HarveyLink  will assist on the migration.

**Comment by melina5656** [comment]
Hi, @PFYasu, these are three sample codes for functions that update resources.

1.  Create a new object of VirtualMachineData
```
var virtualMachineDataToModify = new VirtualMachineData(AzureLocation.EastUS)
{
    NetworkProfile = new VirtualMachineNetworkProfile()
    {
        NetworkInterfaces =
        {
            new VirtualMachineNetworkInterfaceReference()
            {
                Id = nic.Id,
                Primary = true,
            }
        }
    },
};
var vmModify = (await virtualMachineCollection.CreateOrUpdateAsync(WaitUntil.Completed, vmName, virtualMachineDataToModify)).Value;
```

2. Using the UpdateAsync method
```
 var patch = new VirtualMachinePatch()
 {
     NetworkProfile = new VirtualMachineNetworkProfile()
     {
         NetworkInterfaces =
         {
             new VirtualMachineNetworkInterfaceReference()
             {
                 Id = nic.Id,
                 Primary = true,
             }
         }
     },
 };
 var vmModify = (await vm.UpdateAsync(WaitUntil.Completed, patch)).Value;
```

3.  Get the vm resource by name and modify its Data property

```
//update3 - Get the vm resource by name
 var vmGet = (await virtualMachineCollection.GetAsync(linuxVmName)).Value;
 vmGet.Data.NetworkProfile = new VirtualMachineNetworkProfile()
 {
     NetworkInterfaces =
     {
             new VirtualMachineNetworkInterfaceReference()
             {
                 Id = nic.Id,
                 Primary = true,
             }
     },
 };
 var vmModify = (await virtualMachineCollection.CreateOrUpdateAsync(WaitUntil.Completed, vmName, vmGet.Data)).Value;
```

**Comment by PFYasu** [comment]
Hello,

Thanks for your response. I will test your code in our project. 

It would be great to see these examples in your migration tutorial.

https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/resourcemanager/Azure.ResourceManager/docs/MigrationGuide.md#migrating-from-track-1-fluent-sdk-to-track-2-sdk

**Comment by melina5656** [comment]
Hi @PFYasu，sample code for update operation has been added in the migration tutorial.

https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/resourcemanager/Azure.ResourceManager/docs/MigrationGuide.md#update-a-virtual-machine
