### ISSUE TITLE
[FEATURE REQ] OpenTelemetry logging not passing Resource attributes

### ISSUE THREAD

**Issue by ladeak** [Azure/azure-sdk-for-net#40951]
### Library name and version

Azure.Monitor.OpenTelemetry.AspNetCore 1.0.0

### Describe the bug

Set attributes to ResourceBuilder. These attributes are not appearing as custom properties in AppInsights

```csharp
var loggerFactory = LoggerFactory.Create(builder =>
{
    builder.AddOpenTelemetry(options =>
    {
       options.SetResourceBuilder(ResourceBuilder.CreateDefault()
          .AddService(serviceName: "MyService", serviceVersion: "1.0.0")
          .AddAttributes(new Dictionary<string, object>() { { "prop1", "value" }}));
        options.AddAzureMonitorLogExporter();
    });
});
```

I am not sure if this is a missing feature or a bug.

### Expected behavior

`prop1` with value `value` is expected to appear as a custom property in AppInsights on the log message (similar to ILogger scopes).

Ref: [AddAttributes](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/docs/trace/customizing-the-sdk/README.md#resource)

### Actual behavior

Attributes do not appear.

### Reproduction Steps

Set up OpenTelemtry logging with Azure App Insights.
Customize the "resource" with ResourceBuilder.CreateDefault() and an attributes collection.

### Environment

.NET 8

### Workaround

My workaround for now: Creating a LogProcessor and manually extending the log message's Attributes collection.

**Comment by PureKrome** [comment]
@ladeak does this code sample from the MS docs, help? ref: https://learn.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-configuration?tabs=aspnetcore#set-the-cloud-role-name-and-the-cloud-role-instance

**Comment by ladeak** [comment]
@PureKrome yes it is the same problem.

**Comment by TimothyMothra** [comment]
I'm consolidating all issues regarding exporting custom Resource Attributes into another issue to help with tracking. https://github.com/Azure/azure-sdk-for-net/issues/46020
