### ISSUE TITLE
[QUERY] Marketplace.SaaS.Client vs Azure.ResourceManager.Marketplace

### ISSUE THREAD

**Issue by PFYasu** [Azure/azure-sdk-for-net#40956]
### Library name and version

Marketplace.SaaS.Client 1.2.0 / Azure.ResourceManager.Marketplace 1.1.1

### Query/Question

Hello there,

I'm introducing an Azure Marketplace SaaS offer for my organization. We have implemented a test offer including an integration with the `Marketplace.SaaS.Client` v1.2.0 package in our solution. 

Yesterday I found another nuget package - `Azure.ResourceManager.Marketplace`. I tried to get a bit more information about the package - mainly related to its capabilities. 

And here is my questions:

Does `Azure.ResourceManager.Marketplace` have the same features and responsibility as `Marketplace.SaaS.Client`? 
If so, do I need migrate?

Currently used package: https://www.nuget.org/packages/Marketplace.SaaS.Client
The package I want to use: https://www.nuget.org/packages/Azure.ResourceManager.Marketplace

**Comment by jsquire** [comment]
Hi @PFYasu.   Thank you for reaching out.  These packages are intended for different purposes and cannot be used interchangeably.  

The `Azure.ResourceManager.Marketplace` package is a replacement for [Microsoft.Azure.Management.Marketplace](https://www.nuget.org/packages/Microsoft.Azure.Management.Marketplace).   These packages are used to manage Azure resources  via ARM in the same way that the Azure portal, Azure CLI, or Azure PowerShell do.  They are not used to interact with the Marketplace data services, which `Marketplace.SaaS.Client` appears to do.

**Comment by PFYasu** [comment]
Ok, thanks for the clarification. 

Regards!
