### ISSUE TITLE
[BUG] Dev feed is returning 403 Forbidden

### ISSUE THREAD

**Issue by jamesemann** [Azure/azure-sdk-for-net#40961]
### Library name and version

Azure sdk dev feed

### Describe the bug

403 Forbidden when trying to download packages from https://pkgs.dev.azure.com/azure-sdk

### Expected behavior

It should download packages successfully

### Actual behavior

It does not download packages successfully. Fails with a 403 forbidden

### Reproduction Steps

This is happening in our own build but also noted in your public build https://github.com/Azure/azure-sdk-for-net/runs/20105715782

### Environment

Azure DevOps

**Comment by jsquire** [comment]
Hi @jamesemann.  Thank you for reaching out and we regret that you're experiencing difficulties.    This is the result of an active issue with one of our downstream dependencies.  Unfortunately, it does not look like they publish a public status but it is being worked on.

**Comment by jsquire** [comment]
This is now confirmed to be fully resolved.
