### ISSUE TITLE
TableInput for single entity returns array with all entities in that partition

### ISSUE THREAD

**Issue by patrick11994** [Azure/azure-sdk-for-net#40960]
I am using the TableInput binding with a partionkey and a rowkey to retrieve a single entity in the table. 

```cs
[Function("SomeFunction")]
public HttpResponseData Run(
    [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "somefunction/{paramname}")] HttpRequestData req,
    [TableInput("someTable", "somePartition", "{paramname}")] SomeEntity someEntity)
{
    // Removed to keep it on-topic 😊
}
```

This results in the error:
> Cannot convert input parameter 'someEntity' to type 'Namespace.For.Entity.SomeEntity' from type 'System.String'

Now using an IEnumerable as input parameter type for the TableInput, like this:
```cs
[Function("SomeFunction")]
public HttpResponseData Run(
    [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "somefunction/{paramname}")] HttpRequestData req,
    [TableInput("someTable", "somePartition", "{paramname}")] IEnumerable<SomeEntity> someEntities)
{
    // Removed to keep it on-topic 😊
}
```

Results in no error, and gives me all rows back from `somePartition`, ignoring the row key

Even when hardcoding a row key inside the TableInput, this is still happening:
```cs
[Function("SomeFunction")]
public HttpResponseData Run(
    [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "somefunction")] HttpRequestData req,
    [TableInput("someTable", "somePartition", "someRowKey")] IEnumerable<SomeEntity> someEntities)
{
    // Removed to keep it on-topic 😊
}
```

This returns all rows inside `somePartition`, ignoring the row key.

Issue Azure/azure-functions-dotnet-worker#1233 is about the same and tells me that this should be resolved, but it is not.

Using NuGet packages: 
- Microsoft.Azure.Functions.Worker v1.19.0
- Microsoft.Azure.Functions.Worker.Extensions.Http v3.1.0
- Microsoft.Azure.Functions.Worker.Extensions.Tables v1.2.1
- Microsoft.Azure.Functions.Worker.Sdk v1.15.1

And Azurite

**Comment by surgupta-msft** [comment]
The issue seems to have existed since the start of worker extension package -

`"Microsoft.Azure.Functions.Worker.Extensions.Tables, Version=1.0.0"`

Refer to the comment - [link](https://github.com/Azure/azure-functions-dotnet-worker/issues/1233#issuecomment-1365580821). Transferred it to sdk team for further investigation.

**Comment by jsquire** [comment]
@JoshLove-msft : Would you please take a look?

**Comment by JoshLove-msft** [comment]
This issue is about the isolated worker extension packages which do not live in this repo. @surgupta-msft, can you let us know why this issue was transferred from the dotnet worker repo (where the tables isolated extension lives) to the azure-sdk-for-net repo (where the host extension lives)?
