### ISSUE TITLE
Logic App Standard - Run Http Trigger 

### ISSUE THREAD

**Issue by andreatosato** [Azure/azure-sdk-for-net#40976]
### Library name and version

Azure.ResourceManager.AppService 1.0.2

### Query/Question

I want to run HttpTrigger in Logic App (Standard) but I don't find correct way.

I want to get Workflow URL and than trigger my HTTP Trigger
![image](https://github.com/Azure/azure-sdk-for-net/assets/24985956/35acbb5c-7760-4553-ba83-eb8acc27e2bc)

### Environment

dotnet 8

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi @andreatosato , Thank you for using Azure SDK for .NET.
Since we don't have much domain on a single resource, I can only assume that your senario is:
```
    var app = (await resourceGroup.GetLogicWorkflows().GetAsync("name")).Value;
    var trigger = (await app.GetLogicWorkflowTriggerAsync("name")).Value;
    var url = (await trigger.GetCallbackUrlAsync()).Value;
    await trigger.RunAsync();
```
You could have a try on this.

**Comment by andreatosato** [comment]
@HarveyLink work for LogicApp Consumptions, not for LogicApp Standard.

**Comment by HarveyLink** [comment]
Hi @andreatosato , thank you for the clarification, the [API](https://github.com/Azure/azure-rest-api-specs/blob/154b11de26012fb7a67544ec3d26937154d43a35/specification/web/resource-manager/Microsoft.Web/stable/2022-03-01/WebApps.json#L22503) is available from `2022-03-01` version, our current AppService SDK is `2021-02-01` version. You could help to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) to push WebSite team bump their SDK version.
