### ISSUE TITLE
[BUG] Unable to query BlobCount, BlobCapacity, ContainerCount

### ISSUE THREAD

**Issue by Isaac-Lee-msft** [Azure/azure-sdk-for-net#40979]
### Library name and version

Azure.Monitor.Query 1.2.0

### Describe the bug

I'm unable to query specific blob metrics from my storage account when this was supported in the classic metrics. Will these metrics be supported?
```
Azure.RequestFailedException: 'Failed to find metric configuration for provider: Microsoft.Storage, resource Type: storageAccounts, metric: BlobCount, Valid metrics: UsedCapacity,Transactions,Ingress,Egress,SuccessServerLatency,SuccessE2ELatency,Availability
Status: 400 (Bad Request)
ErrorCode: BadRequest

Content:
{"code":"BadRequest","message":"Failed to find metric configuration for provider: Microsoft.Storage, resource Type: storageAccounts, metric: BlobCount, Valid metrics: UsedCapacity,Transactions,Ingress,Egress,SuccessServerLatency,SuccessE2ELatency,Availability"}
```

### Expected behavior

I expected all metrics listed here to be supported: https://learn.microsoft.com/en-us/azure/storage/blobs/monitor-blob-storage-reference#metrics for the metric configuration for provider Microsoft.Storage.

### Actual behavior

The specific blob metrics are not supported for querying

### Reproduction Steps

Run the query client with 'BlobCount' specified as the metric:
```csharp
var results = await metricsQueryClient.QueryResourceAsync(
    resourceId: resourceId2,
    metrics: new[] { "BlobCount" },
    options: new MetricsQueryOptions()
    {
        TimeRange = new QueryTimeRange(TimeSpan.FromHours(1)),
    }
);
```

### Environment

.net 6

**Comment by jsquire** [comment]
Hi @Isaac-Lee-msft.   Thank you for reaching out and we regret that you're experiencing difficulties.  The failure that you're seeing is service behavior; the client library has no insight nor influence over what providers the service makes available or whether/when they'll be supported.  

Unfortunately, this repository is focused on the Azure SDK packages - we're unable to assist with other Azure issues.   As a Microsoft employee, your best path forward would be to open an internal support request for the Monitor service team.

I'm going to close this out; if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.
