### ISSUE TITLE
validation hostnames

### ISSUE THREAD

**Issue by bankzitter01** [Azure/azure-sdk-for-net#4099]
I am trying to add a hostname from a non azure created domain using this code:
```
 webapp.Update()
                .DefineHostnameBinding()
                    .WithThirdPartyDomain(domain)
                    .WithSubDomain("www")
                    .WithDnsRecordType(CustomHostNameDnsRecordType.CName)
                    .Attach()
                .Apply();
```
The command executes without error and the hostname is not created. In the azure activity log I see a succesfull update. When trying to add the hostname via the blade in azure it gives me an error vith the validation. 

I could not find functionallity to validate if a hostname can be added, 

Next I changed the domain to a valid domain. Executed the same code and that did not add a hostname either. What is it I am doing wrong?

**Comment by bankzitter01** [comment]
Is there documentation I have missed discussing how to attach a Third Party domain?

**Comment by hovsepm** [comment]
@bankzitter01 please reopen this issue in https://github.com/Azure/azure-libraries-for-net/ repo since Fluent SDK has been moved to a different place.
