### ISSUE TITLE
[QUERY] How to migrate WindowsAzure.ServiceBus to Azure.Messaging.ServiceBus in given condition? 

### ISSUE THREAD

**Issue by maomaomqiu** [Azure/azure-sdk-for-net#41000]
### Library name and version

Azure.Messaging.ServiceBus (7.15.0); WindowsAzure.ServiceBus (4.1.1)

### Query/Question

Hi, this is maomaomqiu! 
I am now working on deprecating codes of WindowsAzure.ServiceBus to Azure.Messaging.ServiceBus of existing codebase.

for WindowsAzure.ServiceBus (4.1.1), we have below operation before
that parts' logic is to handle received msg
```
class WrappedMessage
{
  private BrokeredMessage msg;
  
  ...
  // if we have it, return it
  if (msg != null)
  {
      // TimeStamp should be scheduled time i.e. when this 
      // message should become visible in service bus queue
       msg.ScheduledEnqueueTimeUtc = (t0.HasValue) ? t0.Value : CreationTime;
  
      return  msg;
  }
  
  // otherwsie create it
   msg = new BrokeredMessage(SerializeToJsonString())
  {
      ContentType = typeof(string).FullName,
      ScheduledEnqueueTimeUtc = (t0.HasValue) ? t0.Value : CreationTime,
      CorrelationId = CorrelationIdValue
  };
  
  // Add Type information to Properties
  Type type = this.GetType();
   msg.Properties[MessageTypeName] = type.FullName + TypeSeparator + type.Assembly.FullName.Split(TypeSeparator)[0];
  
  if (!string.IsNullOrEmpty(SessionId))
  {
       msg.SessionId = SessionId;
       msg.MessageId = Id;
  }
  
  return msg;
  ...
  /// <summary>
  /// Serialized JSON string of WrappedMessage
  /// </summary>
  public string SerializeToJsonString()
  {
      return JsonConvert.SerializeObject(this, this.GetType(), DefaultJsonSerializerSettings);
  }

  private static JsonSerializerSettings DefaultJsonSerializerSettings { get; } = new JsonSerializerSettings() { TypeNameHandling = TypeNameHandling.None };
```
I notice, in  Azure.Messaging.ServiceBus, the ```ServiceBusReceivedMessage``` should be proper migration candidate for ```BrokeredMessage```,
but for  ```ServiceBusReceivedMessage```, it has ```ScheduledEnqueueTime``` for ```ScheduledEnqueueTimeUtc``` (WindowsAzure.ServiceBus (4.1.1)), but can not set directly, so I think up this way to migrate

```
var propertyInfo = typeof(ServiceBusReceivedMessage).GetProperty("ScheduledEnqueueTime");
propertyInfo.SetValue(msg, (t0.HasValue) ? t0 : CreationTime);
```

Do you have any suggestions on migrating this part (all in **WrappedMessage**) code? Greatly thanks in advance : )

**Comment by jsquire** [comment]
Hi @maomaomqiu.   It would be helpful to understand what you're trying to accomplish.   I believe the root question is "how do I schedule a message for delivery in the future", which is done using the `ServiceBusSender`'s [ScheduleMessageAsync](https://learn.microsoft.com/dotnet/api/azure.messaging.servicebus.servicebussender.schedulemessageasync?view=azure-dotnet#azure-messaging-servicebus-servicebussender-schedulemessageasync(azure-messaging-servicebus-servicebusmessage-system-datetimeoffset-system-threading-cancellationtoken)) method.  An example can be found [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample01_SendReceive.md#schedule-a-message).

The `ScheduledEnqueueTimeUtc ` field on the message is broker-owned and should not be set by the client.  The same concept applies to `ServiceBusReceivedMessage`, which is intended to represent data sent by the broker.  The client will only allow you to send messages of type `ServiceBusMessage`.
