### ISSUE TITLE
[BUG] ServiceBusReceiver.CompleteMessage taking ~100ms to complete

### ISSUE THREAD

**Issue by Tak1za** [Azure/azure-sdk-for-net#41007]
### Library name and version

Azure.Messaging.ServiceBus 7.12.0

### Describe the bug

I've noticed from our logs that completing a message in Service Bus takes ~100ms.
I'm not saying it always takes ~100ms, but around 60% of the time it takes ~100ms, and other times it takes <50ms.
![image](https://github.com/Azure/azure-sdk-for-net/assets/18700114/68776dcc-a313-49b5-b4d0-64e89110f7a3)
![image](https://github.com/Azure/azure-sdk-for-net/assets/18700114/6b3561a7-8571-4990-b01f-9b3f24ccb269)
![image](https://github.com/Azure/azure-sdk-for-net/assets/18700114/2b2b0c42-82d5-474f-9469-3146bce2e0a0)

### Expected behavior

The time taken to complete messages ideally should remain consistent for completing same type of messages and >100ms seems too much to me.

### Actual behavior

Completing same type of messages takes inconsistent times and majority of the times takes ~100ms.

### Reproduction Steps

Try completing a few service bus messages:

`await messageActions.CompleteMessageAsync(message);`

### Environment

Azure Functions are being used to receive a trigger for Service Bus Message and then mark messages as completed.

**Comment by jsquire** [comment]
Hi @Tak1za.  Thank you for reaching out and we regret that you're experiencing difficulties.  The behavior that you're inquiring about is not something that the client library has any insight into nor influence over.  
 Completing a message is a network operation and, as such, should be expected to have variance based on network factors, the time that it takes the service to perform the operation, and any potential error recovery.  The SKU of your Service Bus namespace also plays a role, as levels other than premium and dedicated are shared instances.

If you'd like additional insight, your best path forward would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) for the Service Bus service team and ask that they take a look at service-side logs for your resource.
