### ISSUE TITLE
[QUERY] Network Interface Batch Deletion Support

### ISSUE THREAD

**Issue by shenshenwums** [Azure/azure-sdk-for-net#41002]
### Library name and version

Azure.Management.Network

### Query/Question

We're migrating from Fluent SDK to new Azure SDK and wonder whether NIC batch deletion, like `IAzure.NetworkInterfaces.DeleteByIdsAsync(listOfIds, cancellationToken)`, from Fluent SDK is supported in new SDK? If yes, is there an example of it? If no, what will be the best practice to perform batch deletion with new SDK? Thank you.

### Environment

.netcore 6.0 with VS 2022

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi @shenshenwums , there is no such method in current SDK.
As a work around, you could try:
```
    var ids = new List<ResourceIdentifier>();
    foreach (var item in ids)
    {
        await client.GetNetworkInterfaceResource(item).DeleteAsync(WaitUntil.Started);
    }
```
```
    var list = new List<NetworkInterfaceResource>;
    await foreach (var item in resourceGroup.GetNetworkInterfaces().GetAllAsync())
    {
        list.Add(item);
    }
    foreach (var item in list)
    {
        await item.DeleteAsync(WaitUntil.Started);
    }
```
