### ISSUE TITLE
Add a way to get a TenantResource without having to list all the tenants

### ISSUE THREAD

**Issue by Luaancz** [Azure/azure-sdk-for-net#41023]
### Library name

Azure.ResourceManager.Resources

### Please describe the feature.

To make a ResourceGraph request with ArmClient, a TenantResource is required. However, there is currently no way to create a TenantResource without making a request to Azure, which means we have to list tenants every time we get a new ArmClient.

In contrast, if I need e.g. a SubscriptionResource, I can do

`armClient.GetSubscriptionResource(SubscriptionResource.CreateResourceIdentifier(subscriptionId))`

to get a resource to call further methods with. But for tenants, the only available method is ArmClient.GetTenants; there is no TenantResource.CreateResourceIdentifier or armClient.GetTenantResource.

Alternatively, since ArmClient only really allows accessing one tenant at a time anyway, it would be enough to expose the private TenantResource. Or as probably a better option, expose TenantResource.GetResourcesAsync through ArmClient, just like with e.g. ArmClient.GetManagementGroups.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi @Luaancz , Thank you for using Azure SDK for .NET.
Since our SDK is auto generated based on Rest API, current API doesn't have operation to get one single Tenant,  SDK will not support that either.

**Comment by Luaancz** [comment]
> Hi @Luaancz , Thank you for using Azure SDK for .NET. Since our SDK is auto generated based on Rest API, current API doesn't have operation to get one single Tenant, SDK will not support that either.

Can you expose the TenantResource on the ArmClient then?

**Comment by ArthurMa1978** [comment]
> > Hi @Luaancz , Thank you for using Azure SDK for .NET. Since our SDK is auto generated based on Rest API, current API doesn't have operation to get one single Tenant, SDK will not support that either.
> 
> Can you expose the TenantResource on the ArmClient then?

Unfortunately, we can't do that as this functionality is not exposed by the service. You may try to contact the ARM service team through an [Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) and ask them if they can enable it.
