### ISSUE TITLE
What is the replacement of the the NamespaceManager class from Microsoft.ServiceBus?

### ISSUE THREAD

**Issue by That-Rationalist** [Azure/azure-sdk-for-net#41020]
### Library name and version

Azure.Messaging.ServiceBus latest version

### Query/Question

I need to get the active message count from a topic subscription, and so far I have only found this class can do the job: https://learn.microsoft.com/en-us/dotnet/api/microsoft.servicebus.namespacemanager?view=azure-dotnet-legacy

What's the equivalent in the recommended SDK? 

Thanks.

### Environment

Azure Function App, .NET Core 6 or 7
Visual Studio 2022

**Comment by jsquire** [comment]
Hi @That-Rationalist.  Thank you for reaching out and we regret that you're experiencing difficulties.  The closest equivalent would be the [ServiceBusAdministrationClient](https://learn.microsoft.com/dotnet/api/azure.messaging.servicebus.administration.servicebusadministrationclient?view=azure-dotnet).  It's [GetSubscriptionRuntimePropertiesAsync](https://learn.microsoft.com/dotnet/api/azure.messaging.servicebus.administration.servicebusadministrationclient.getsubscriptionruntimepropertiesasync?view=azure-dotnet#azure-messaging-servicebus-administration-servicebusadministrationclient-getsubscriptionruntimepropertiesasync(system-string-system-string-system-threading-cancellationtoken)) method provides information about a topic subscription, including the message count.
