### ISSUE TITLE
ClientModel: Use BinaryData.Empty instead of bespoke solution

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#41034]
See PR comment: https://github.com/Azure/azure-sdk-for-net/pull/41016#discussion_r1442382912

This will involve:
- Upgrading to System.Memory.Data [6.0.0 or higher](https://learn.microsoft.com/en-us/dotnet/api/system.binarydata.empty?view=dotnet-plat-ext-8.0#applies-to)
- Upgrading to System.Text.Json 6.0.0, which System.Memory.Data brings as a dependency
- Checking with PowerShell and Functions to ensure we don't upgrade above a version that they're using

**Comment by m-redding** [comment]
This should be unblocked by https://github.com/Azure/azure-sdk-for-net/pull/46134
