### ISSUE TITLE
[BUG] AppServicePlanData.IsZoneRedundant returns null values when zone redundancy is enabled

### ISSUE THREAD

**Issue by EmilDamsbo** [Azure/azure-sdk-for-net#41031]
### Library name and version

Azure.ResourceManager.AppService v1.0.2

### Describe the bug

`AppServicePlan.IsZoneRedundant` returns null despite resource in Azure being defined with zone redundancy.
My organization has a utility for aggregating various information about our subscriptions, among other being zone redundancy.
The code I've written is getting all AppServicePlans from a subscription, and checking the `IsZoneRedundant` values. However, those values are always null regardless of the value in the Azure Portal. Example of an App Service Plan which is zone redundant:
![image](https://github.com/Azure/azure-sdk-for-net/assets/67266681/1af5a67e-2983-48f7-a908-0c842f1382ac)

### Expected behavior

If the Azure Portal reports that the AppServicePlan resource has Zone Redundant enabled, then `AppServicePlanData.IsZoneRedundant` should return true.

### Actual behavior

`AppServicePlanData.IsZoneRedundant` returns a null value regardless of what Azure Portal reports.

### Reproduction Steps

1. In Azure Portal, create a new Linux app service plan in the Azure portal with a premium SKU and zone redundancy enabled - Deploy it without attaching any apps
2. Write a small utility to get the data of your Azure subscription, for example like this:

```
ArmClient armClient = [in my case gotten by managed identity];
var subscription = (await armClient.GetSubscriptions().GetAsync("[subscription id]")).Value;
IEnumerable<AppServicePlanData> plans = subscription.GetAppServicePlans();
foreach (var plan in plans)
{
    // every single plan.Data has IsZoneRedundant == null
}
```
3. Set a breakpoint somewhere in the loop and inspect the plans. Here's the entry corresponding to my other screenshot:
![image](https://github.com/Azure/azure-sdk-for-net/assets/67266681/62c4ec0f-4cac-42f2-97cb-0a8aef1249e1)

### Environment

Test app being run locally as C# .NET 6 in-process Azure Function ( built and run via VS2022 17.8.3 64-bit)
Linux-based App Service Plan in Azure Portal.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by EmilDamsbo** [comment]
Just to add some more info:
I cloned the SDK repo and added a reference to the AppService project instead of the NuGet, so I could debug what was really going on.

I stepped into [the deserialization logic of the app service plan data](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/websites/Azure.ResourceManager.AppService/src/Generated/Models/AppServicePlanData.Serialization.cs) and there the JSON entries also just had `"zoneRedundant": null`. I'm considering if this is actually a fault in the Azure API instead? If so could you log a bug internally or tell me the support area path to route?

**Comment by HarveyLink** [comment]
Hi @EmilDamsbo , Thank you for using Azure SDK for .NET.
We can't repro this issue on our side, the `IsZoneRedundant` returns `true` as we expected.
![image](https://github.com/Azure/azure-sdk-for-net/assets/30464227/5c60df87-e0c0-4168-8ab9-d14c63647eba)
Both approaches seem working good on out side, code attached
```
    var plan = (await resourceGroup.GetAppServicePlans().GetAsync("name")).Value;
    Console.WriteLine(plan.Data.IsZoneRedundant);
    var list = resourceGroup.GetAppServicePlans().GetAllAsync();
    await foreach (var item in list)
    {
        Console.WriteLine(item.Data.IsZoneRedundant);
    }
```
You could use any capture tools to check your actual payload, see if the response value is correct.

**Comment by EmilDamsbo** [comment]
@HarveyLink The value is not present in the payload. Could you comment on my previous assertion:

> Is this merely a question of the managed identity running my function app lacking sufficient privileges in my subscription?

If that could be the case, could you guide me towards which access my MI is lacking?

**Comment by HarveyLink** [comment]
> @HarveyLink The value is not present in the payload. Could you comment on my previous assertion:
> 
> > Is this merely a question of the managed identity running my function app lacking sufficient privileges in my subscription?
> 
> If that could be the case, could you guide me towards which access my MI is lacking?

Hi, We don't have much domain knowledge on a single service. If there is a sufficient privileges lacking here, you may need to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request)

**Comment by EmilDamsbo** [comment]
If anyone runs into this in the future: Use `GetAppServicePlans(detailed: true)`, Zone redundancy property is apparently not returned by default.
