### ISSUE TITLE
[FEATURE REQ] Include sdk models for easier unit testing

### ISSUE THREAD

**Issue by Isaac-Lee-msft** [Azure/azure-sdk-for-net#41048]
### Library name

Azure.Monitor.Query

### Please describe the feature.

Requesting for easier unit testing with the Azure.Monitor.Query sdk along the lines of a models factory so that mocking the expected MetricsQueryResult etc be simpler. i.e. https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.models.blobsmodelfactory?view=azure-dotnet

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Isaac-Lee-msft** [comment]
Actually, I just saw this changelog: https://github.com/Azure/azure-sdk-for-net/blob/Azure.Monitor.Query_1.3.0-beta.2/sdk/monitor/Azure.Monitor.Query/CHANGELOG.md#110-2022-01-25

This should be sufficient. Sorry for the noise.
