### ISSUE TITLE
Codgo se inicia sesion 

### ISSUE THREAD

**Issue by F6a3jywi** [Azure/azure-sdk-for-net#41052]
### Type of issue

Typo

### Description

[Escriba sus comentarios aquí]

### Page URL

https://learn.microsoft.com/es-es/dotnet/api/microsoft.azure.management.websites.models.facebook.enabled?view=azure-dotnet-legacy#microsoft-azure-management-websites-models-facebook-enabled

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.WebSites.Models/Facebook.xml

### Document Version Independent Id

aa2dc48c-4085-7e05-274b-b59ba92978f1

### Article author

@azure-sdk

### Metadata

* ID: eeb0b5f2-243d-796f-cf9e-63ef557ab842 
* Service: **app-service**
* Sub-service: **web-apps**

**Comment by jsquire** [comment]
Hi @F6a3jywi.  Thank you for your feedback.  The `Microsoft.Azure.Management.Websites` library has reached end-of-life and is no longer published nor supported by Microsoft.   This documentation is no longer maintained.
