### ISSUE TITLE
[FEATURE REQ] Support Activity.StatusDescription in Exporter

### ISSUE THREAD

**Issue by yizhoumo** [Azure/azure-sdk-for-net#41057]
### Library name

 Azure.Monitor.OpenTelemetry.Exporter

### Please describe the feature.

Support exporting `Activity.StatusDescription` as a custom property `otel.status_description` in telemetry.

OpenTelemetry suggest using `Activity.SetStatus()` to set status of trace. (https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Api/README.md#setting-status)
Currently the Exporter can use `Activity.Status` to determine the `Success` field, but the `Activity.StatusDescription` is totally ignored. The information of status description is missing in Azure telemetry. One possible way to keep this information would be adding custom property `otel.status_description` which matches the sematic convention of OpenTelemetry.

**Comment by TimothyMothra** [comment]
I'm consolidating all issues regarding overriding specific fields in the Application Insights schema into another issue to help with tracking. https://github.com/Azure/azure-sdk-for-net/issues/46021
