### ISSUE TITLE
[BUG] UpdateAsync execution failed with Exception: System.ArgumentNullException: Value cannot be null

### ISSUE THREAD

**Issue by weizhang1233** [Azure/azure-sdk-for-net#41063]
### Library name and version

Azure.ResourceManager version 1.9.0

### Describe the bug

I am observing an ArgumentNullException when attempting to UpdateAsync (remove tags) to an existing azure resources (data disk or os disk, azure resource type is "Disk") . I check the tags on this specific resource has been removed successfully but actually there is an exception like "System.ArgumentNullException: Value cannot be null" returned while deserialized the response json. 

Please see the following exception details:
Exception caught in DeletexxxxxxResourceTagsxxx, Value cannot be null.
Parameter name: id
   at Azure.ResourceManager.ArmResource..ctor(ArmClient client, ResourceIdentifier id)
   at Azure.ResourceManager.Resources.TagResource..ctor(ArmClient client, ResourceIdentifier id)
   **_at Azure.ResourceManager.Resources.TagResourceOperationSource.<Azure-Core-IOperationSource<Azure-ResourceManager-Resources-TagResource>-CreateResultAsync>d__3.MoveNext()_**
— End of stack trace from previous location where exception was thrown —
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.Core.NextLinkOperationImplementation.OperationToOperationOfT`1.<UpdateStateAsync>d__3.MoveNext()
— End of stack trace from previous location where exception was thrown —
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.Core.OperationInternal`1.<UpdateStatusAsync>d__20.MoveNext()
— End of stack trace from previous location where exception was thrown —
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Core.OperationInternalBase.<UpdateStatusAsync>d__13.MoveNext()
— End of stack trace from previous location where exception was thrown —
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Azure.Core.OperationPoller.<WaitForCompletionAsync>d__11.MoveNext()
— End of stack trace from previous location where exception was thrown —
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Core.OperationInternalBase.<WaitForCompletionResponseAsync>d__19.MoveNext()
— End of stack trace from previous location where exception was thrown —
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Core.OperationInternal`1.<WaitForCompletionAsync>d__19.MoveNext()
— End of stack trace from previous location where exception was thrown —
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.Core.OperationInternal`1.<WaitForCompletionAsync>d__15.MoveNext()
— End of stack trace from previous location where exception was thrown —
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.ResourceManager.Resources.TagResource.<UpdateAsync>d__20.MoveNext()
— End of stack trace from previous location where exception was thrown —
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Citrix.AzureFacade.AzureResourceManager.ClientWrappers.AzureRmClientWrapper.<>c_DisplayClass108_0.<<DeleteGenericResourceTagsAsync>b_0>d.MoveNext()
— End of stack trace from previous location where exception was thrown —
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Citrix.AzureCommon.Logging.MethodLogger.<ExecuteAsync>d__17`1.MoveNext() identifier.ResourceType.Namespace: 
  
Check backend source code, looks like issue happened here: 
namespace Azure.ResourceManager.Resources 
`public virtual async Task<ArmOperation<TagResource>> UpdateAsync(WaitUntil waitUntil, TagResourcePatch patch, CancellationToken cancellationToken = default)
{
    Argument.AssertNotNull(patch, nameof(patch));

    using var scope = _tagResourceTagsClientDiagnostics.CreateScope("TagResource.Update");
    scope.Start();
    try
    {
        var response = await _tagResourceTagsRestClient.UpdateAtScopeAsync(Id.Parent, patch, cancellationToken).ConfigureAwait(false);
        var operation = new ResourcesArmOperation<TagResource>(new **_TagResourceOperationSource(Client)_**, _tagResourceTagsClientDiagnostics, Pipeline, _tagResourceTagsRestClient.CreateUpdateAtScopeRequest(Id.Parent, patch).Request, response, OperationFinalStateVia.Location, skipApiVersionOverride: true);
        if (waitUntil == WaitUntil.Completed)
            await operation.WaitForCompletionAsync(cancellationToken).ConfigureAwait(false);
        return operation;
    }
    catch (Exception e)
    {
        scope.Failed(e);
        throw;
    }
}`

When wait and call DeserializeTagResourceData in create result async, 

`        async ValueTask<TagResource> IOperationSource<TagResource>.CreateResultAsync(Response response, CancellationToken cancellationToken)
        {
            using var document = await JsonDocument.ParseAsync(response.ContentStream, default, cancellationToken).ConfigureAwait(false);
            var data = TagResourceData.DeserializeTagResourceData(document.RootElement);
            return new TagResource(_client, data);
        }

Looks like the the id is not found in response data, and then go to new TagResource constructor
        internal TagResource(ArmClient client, ResourceIdentifier id) : base(client, id)
        {
            _tagResourceTagsClientDiagnostics = new ClientDiagnostics("Azure.ResourceManager.Resources", ResourceType.Namespace, Diagnostics);
            TryGetApiVersion(ResourceType, out string tagResourceTagsApiVersion);
            _tagResourceTagsRestClient = new TagsRestOperations(Pipeline, Diagnostics.ApplicationId, Endpoint, tagResourceTagsApiVersion);
#if DEBUG
			ValidateResourceId(Id);
#endif
        }`

` protected internal ArmResource(ArmClient client, ResourceIdentifier id)
        {
            Argument.AssertNotNull(id, nameof(id));
            Argument.AssertNotNull(client, nameof(client));

            Client = client;
            Id = id;
        }`
       

### Expected behavior

Tags removed successfully and no ArgumentNullException thrown.

### Actual behavior

Tags removed but ArgumentNullException returned to break continuous processing. 

### Reproduction Steps

Create a disk resources with a few tags in azure hypervisor, 
then try to remove those tags with UpdateAsync

identitifer is a ResourceIdentifier instance with resource id, name, resource group. 
var tagResource = ArmClient.GetGenericResource(identifier).GetTagResource();
var patch= new TagResourcePatch()
{
PatchMode = TagPatchModel.Delete, 
}

patch.TagValues.Add() --> add a key value from a key-value dictionary as tags. 
something like { resource: a, ad: , vmname: , vid:  }
then await tagResource.UpdateAsync(WaitUntil.Completed, patch).ConfigureAwait(false)).Value.Data;

Tried resource Disk, issue has been reproduced, but to virtual machine, no error feedback and tags removed successfully. 

### Environment

.NET SDK:
 Version:           8.0.100

Runtime Environment:
 OS Name:     Windows

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by weizhang1233** [comment]
It's only happening in specific tenant(directory). Looks like azure could is in a continuous upgrading processing.

**Comment by weizhang1233** [comment]
@jsquire Any updating? Thanks

**Comment by jsquire** [comment]
@weizhang1233 - I do not have insight into the current status.  We'll need an update from the assigned engineer, @ArthurMa1978.

**Comment by weizhang1233** [comment]
@jsquire Thanks for your feedback.
@ArthurMa1978 Is there any updating on this issue?

**Comment by ArthurMa1978** [comment]
Thank you @weizhang1233  for reaching us, @HarveyLink  will follow up your question.

**Comment by AlBaal** [comment]
We are experiencing same issue setting disk tags

`await _context.CreateArmClient().GetGenericResource(existingDisk.Value.Id).SetTagsAsync(tags, cancellationToken);`
                    
Stack:
`System.ArgumentNullException: Value cannot be null. (Parameter 'id')
   at Azure.Core.Argument.AssertNotNull[T](T value, String name)
   at Azure.ResourceManager.ArmResource..ctor(ArmClient client, ResourceIdentifier id)
   at Azure.ResourceManager.Resources.TagResource..ctor(ArmClient client, ResourceIdentifier id)
   at Azure.ResourceManager.Resources.TagResource..ctor(ArmClient client, TagResourceData data)
   at Azure.ResourceManager.Resources.TagResourceOperationSource.Azure.Core.IOperationSource<Azure.ResourceManager.Resources.TagResource>.CreateResultAsync(Response response, CancellationToken cancellationToken)
   at Azure.Core.NextLinkOperationImplementation.OperationToOperationOfT1.UpdateStateAsync(Boolean async, CancellationToken cancellationToken)
   at Azure.Core.OperationInternal1.UpdateStatusAsync(Boolean async, CancellationToken cancellationToken)
   at Azure.Core.OperationInternalBase.UpdateStatusAsync(CancellationToken cancellationToken)
   at Azure.Core.OperationPoller.WaitForCompletionAsync(Boolean async, OperationInternalBase operation, Nullable1 delayHint, CancellationToken cancellationToken)
   at Azure.Core.OperationInternalBase.WaitForCompletionResponseAsync(Boolean async, Nullable1 pollingInterval, String scopeName, CancellationToken cancellationToken)
   at Azure.Core.OperationInternal1.WaitForCompletionAsync(Boolean async, Nullable1 pollingInterval, CancellationToken cancellationToken)
   at Azure.Core.OperationInternal1.WaitForCompletionAsync(CancellationToken cancellationToken)
   at Azure.ResourceManager.Resources.TagResource.CreateOrUpdateAsync(WaitUntil waitUntil, TagResourceData data, CancellationToken cancellationToken)
   at Azure.ResourceManager.Resources.GenericResource.SetTagsAsync(IDictionary2 tags, CancellationToken cancellationToken)`

**Comment by HarveyLink** [comment]
Hi @weizhang1233 , We can't repro your issue with following code:
```
async Task<TagResourceData> RemoveTagResourceAsync(ArmClient client, ResourceIdentifier id)
{
    var tags = client.GetGenericResource(id).GetTagResource();
    var patchReq = new TagResourcePatch()
    {
        PatchMode = TagPatchMode.Delete,
        TagValues =
        {
            {"key1", "value1"},
            {"key2", "value2"},
        }
    };
    return (await tags.UpdateAsync(WaitUntil.Completed, patchReq)).Value.Data;
}
```
OR
```
            var tags = new Dictionary<string, string>()
            {
                {"new1", "value1"},
                {"new2", "value2"},
            };
            var issue = (await client.GetGenericResource(item).SetTagsAsync(tags)).Value;
            Console.WriteLine(issue.Data.Tags.Count);
```

If possible, please capture and attach the request/response payload, it could help us to identify the issue.

**Comment by weizhang1233** [comment]
@HarveyLink I will try. Is there any configuration change to make request/reponse payload printed?

**Comment by HarveyLink** [comment]
> @HarveyLink Minghao Chen (WICRESOFT NORTH AMERICA LTD) Vendor I will try. Is there any configuration change to make request/reponse payload printed?

Any tools that could capture HTTPS traffic will do the job, like Fiddler or other wed debug tools.

**Comment by AlBaal** [comment]
@HarveyLink I have tested failing request using Fiddler. Below are the results.

First PUT request+response:
```
PUT https://management.azure.com/subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.Compute/disks/managed1/providers/Microsoft.Resources/tags/default?api-version=2022-09-01 HTTP/1.1
Host: management.azure.com
Accept: application/json
x-ms-client-request-id: 42a39737-81a9-401b-9c7f-c2c7ca95c810
x-ms-return-client-request-id: true
User-Agent: azsdk-net-ResourceManager/1.8.1 (.NET 6.0.26; Microsoft Windows 10.0.22631)
Authorization: Bearer REDACTED
Content-Type: application/json
Content-Length: 35

{"properties":{"tags":{"testKey":"testValue"}}}


>>>>>>>>>>>>>>>


HTTP/1.1 202 Accepted
Cache-Control: no-cache
Pragma: no-cache
Expires: -1
Location: https://management.azure.com//subscriptions/REDACTED/tagsoperationresults?api-version=2022-09-01&$ol=REDACTED
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-request-id: 3fe740b4-5213-4c65-b8b0-7af14243bf29
x-ms-correlation-request-id: 3fe740b4-5213-4c65-b8b0-7af14243bf29
x-ms-routing-request-id: GERMANYWESTCENTRAL:20240124T145448Z:3fe740b4-5213-4c65-b8b0-7af14243bf29
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
Date: Wed, 24 Jan 2024 14:54:47 GMT
Content-Length: 0
```


Second GET request+response (probably async operation check)
```
GET https://management.azure.com//subscriptions/REDACTED/tagsoperationresults?api-version=2022-09-01&$ol=REDACTED HTTP/1.1
Host: management.azure.com
x-ms-client-request-id: f095302c-daec-424d-8575-47392dccb197
x-ms-return-client-request-id: true
User-Agent: azsdk-net-ResourceManager/1.8.1 (.NET 6.0.26; Microsoft Windows 10.0.22631)
Authorization: Bearer REDACTED


>>>>>>>>>>>>>>>


HTTP/1.1 202 Accepted
Cache-Control: no-cache
Pragma: no-cache
Content-Type: application/json; charset=utf-8
Expires: -1
x-ms-request-id: 035c4384-209d-4e9a-960d-084aef8eb049
x-ms-correlation-request-id: 035c4384-209d-4e9a-960d-084aef8eb049
x-ms-routing-request-id: GERMANYWESTCENTRAL:20240124T145448Z:035c4384-209d-4e9a-960d-084aef8eb049
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
Date: Wed, 24 Jan 2024 14:54:47 GMT
Content-Length: 4

null
```


Third GET request+response
```
GET https://management.azure.com//subscriptions/REDACTED/tagsoperationresults?api-version=2022-09-01&$ol=REDACTED HTTP/1.1
Host: management.azure.com
x-ms-client-request-id: 6111fbc4-1b0c-4d8f-bf3a-8958cf43dceb
x-ms-return-client-request-id: true
User-Agent: azsdk-net-ResourceManager/1.8.1 (.NET 6.0.26; Microsoft Windows 10.0.22631)
Authorization: Bearer REDACTED


>>>>>>>>>>>>>>>


HTTP/1.1 200 OK
Cache-Control: no-cache
Pragma: no-cache
Content-Type: application/json; charset=utf-8
Expires: -1
x-ms-request-id: 991e22ae-3274-47e6-94b9-c2bfc2f3f823
x-ms-correlation-request-id: 991e22ae-3274-47e6-94b9-c2bfc2f3f823
x-ms-routing-request-id: GERMANYWESTCENTRAL:20240124T145449Z:991e22ae-3274-47e6-94b9-c2bfc2f3f823
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
Date: Wed, 24 Jan 2024 14:54:48 GMT
Content-Length: 12

{"value":[]}
```

Worth mentioning is double slash in URL of get requests, _null_ in response of second request and empty value in response of third request.

**Comment by HarveyLink** [comment]
> @HarveyLink Minghao Chen (WICRESOFT NORTH AMERICA LTD) Vendor I have tested failing request using Fiddler. Below are the results.
> 
> First PUT request+response:
> 
> ```
> PUT https://management.azure.com/subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.Compute/disks/managed1/providers/Microsoft.Resources/tags/default?api-version=2022-09-01 HTTP/1.1
> Host: management.azure.com
> Accept: application/json
> x-ms-client-request-id: 42a39737-81a9-401b-9c7f-c2c7ca95c810
> x-ms-return-client-request-id: true
> User-Agent: azsdk-net-ResourceManager/1.8.1 (.NET 6.0.26; Microsoft Windows 10.0.22631)
> Authorization: Bearer REDACTED
> Content-Type: application/json
> Content-Length: 35
> 
> {"properties":{"tags":{"testKey":"testValue"}}}
> 
> 
> >>>>>>>>>>>>>>>
> 
> 
> HTTP/1.1 202 Accepted
> Cache-Control: no-cache
> Pragma: no-cache
> Expires: -1
> Location: https://management.azure.com//subscriptions/REDACTED/tagsoperationresults?api-version=2022-09-01&$ol=REDACTED
> x-ms-ratelimit-remaining-subscription-writes: 1199
> x-ms-request-id: 3fe740b4-5213-4c65-b8b0-7af14243bf29
> x-ms-correlation-request-id: 3fe740b4-5213-4c65-b8b0-7af14243bf29
> x-ms-routing-request-id: GERMANYWESTCENTRAL:20240124T145448Z:3fe740b4-5213-4c65-b8b0-7af14243bf29
> Strict-Transport-Security: max-age=31536000; includeSubDomains
> X-Content-Type-Options: nosniff
> Date: Wed, 24 Jan 2024 14:54:47 GMT
> Content-Length: 0
> ```
> 
> Second GET request+response (probably async operation check)
> 
> ```
> GET https://management.azure.com//subscriptions/REDACTED/tagsoperationresults?api-version=2022-09-01&$ol=REDACTED HTTP/1.1
> Host: management.azure.com
> x-ms-client-request-id: f095302c-daec-424d-8575-47392dccb197
> x-ms-return-client-request-id: true
> User-Agent: azsdk-net-ResourceManager/1.8.1 (.NET 6.0.26; Microsoft Windows 10.0.22631)
> Authorization: Bearer REDACTED
> 
> 
> >>>>>>>>>>>>>>>
> 
> 
> HTTP/1.1 202 Accepted
> Cache-Control: no-cache
> Pragma: no-cache
> Content-Type: application/json; charset=utf-8
> Expires: -1
> x-ms-request-id: 035c4384-209d-4e9a-960d-084aef8eb049
> x-ms-correlation-request-id: 035c4384-209d-4e9a-960d-084aef8eb049
> x-ms-routing-request-id: GERMANYWESTCENTRAL:20240124T145448Z:035c4384-209d-4e9a-960d-084aef8eb049
> Strict-Transport-Security: max-age=31536000; includeSubDomains
> X-Content-Type-Options: nosniff
> Date: Wed, 24 Jan 2024 14:54:47 GMT
> Content-Length: 4
> 
> null
> ```
> 
> Third GET request+response
> 
> ```
> GET https://management.azure.com//subscriptions/REDACTED/tagsoperationresults?api-version=2022-09-01&$ol=REDACTED HTTP/1.1
> Host: management.azure.com
> x-ms-client-request-id: 6111fbc4-1b0c-4d8f-bf3a-8958cf43dceb
> x-ms-return-client-request-id: true
> User-Agent: azsdk-net-ResourceManager/1.8.1 (.NET 6.0.26; Microsoft Windows 10.0.22631)
> Authorization: Bearer REDACTED
> 
> 
> >>>>>>>>>>>>>>>
> 
> 
> HTTP/1.1 200 OK
> Cache-Control: no-cache
> Pragma: no-cache
> Content-Type: application/json; charset=utf-8
> Expires: -1
> x-ms-request-id: 991e22ae-3274-47e6-94b9-c2bfc2f3f823
> x-ms-correlation-request-id: 991e22ae-3274-47e6-94b9-c2bfc2f3f823
> x-ms-routing-request-id: GERMANYWESTCENTRAL:20240124T145449Z:991e22ae-3274-47e6-94b9-c2bfc2f3f823
> Strict-Transport-Security: max-age=31536000; includeSubDomains
> X-Content-Type-Options: nosniff
> Date: Wed, 24 Jan 2024 14:54:48 GMT
> Content-Length: 12
> 
> {"value":[]}
> ```
> 
> Worth mentioning is double slash in URL of get requests, _null_ in response of second request and empty value in response of third request.

Thans you for the update. The `SetTags()` method operate on a `GenericResource` contains 3 steps:
1. Delete all the tags.
2. Put the tags.
3. Get the resource overall properties. 

Looks like you have the Put tags request return blank result.(The double slash before subscription is expected)
This is what I got on my own machine:
```
{
  "id": "/providers//subscriptions/<>/resourceGroups/<>/providers/Microsoft.Compute/disks/<>/providers/Microsoft.Resources/tags/default",
  "name": "default",
  "type": "Microsoft.Resources/tags",
  "properties": {
      "tags": {
          "testkey": "testvalue"
      }
  }
}
```
It seems to be a service issue, you could [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) for the further help.
