### ISSUE TITLE
[BUG] Dispose of ServiceBusClient is not marking its ServiceBusSenders as Closed

### ISSUE THREAD

**Issue by pabermod** [Azure/azure-sdk-for-net#41072]
### Library name and version

Azure.Messaging.ServiceBus 7.17.1

### Describe the bug

From the documentation:

> It is important to note that when a ServiceBusClient instance is disposed, it will automatically close and cleanup any senders, receivers, and processors that were created using it.

When disposing a ServiceBusClient, the property IsClosed of its ServiceBusSenders is not being set to true.

### Expected behavior

When a ServiceBusClient instance is disposed, as all its ServiceBusSenders are closed and cleaned up, so their property **IsClosed** should be set to true

### Actual behavior

The property **IsClosed** of the senders is not set to true

### Reproduction Steps

- Create a ServiceBusClient
- Create a ServiceBusSender
- Dispose the ServiceBusClient
- Check the property **IsClosed** of the sender

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
> When a ServiceBusClient instance is disposed, as all its ServiceBusSenders are closed and cleaned up, so their property IsClosed should be set to true

This isn't exactly true - when the ServiceBusClient is disposed, the AMQP connection with the service is closed, but the individual AMQP links are not closed by the client. When you dispose/close the ServiceBusSender, the AMQP links are closed by the client and hence the sender is marked as closed. This is why the best practice is to first close the ServiceBusSender instances, and then close the ServiceBusClient when shutting down.

**Comment by pabermod** [comment]
/unresolve

@JoshLove-msft  So maybe the documentation: 

https://learn.microsoft.com/en-us/dotnet/api/overview/azure/messaging.servicebus-readme?view=azure-dotnet#client-lifetime

should be updated because it can be misunderstood

**Comment by JoshLove-msft** [comment]
> /unresolve
> 
> @JoshLove-msft So maybe the documentation:
> 
> https://learn.microsoft.com/en-us/dotnet/api/overview/azure/messaging.servicebus-readme?view=azure-dotnet#client-lifetime
> 
> should be updated because it can be misunderstood

Indeed it should, thanks for pointing that out.

**Comment by JoshLove-msft** [comment]
@pabermod, this has been fixed in https://github.com/Azure/azure-sdk-for-net/pull/41082. The learn page will be updated after our next release of the library.
