### ISSUE TITLE
<br> tag is not being rendered properly in the learn.microsoft.com page

### ISSUE THREAD

**Issue by MichaelPico** [Azure/azure-sdk-for-net#41079]
### Type of issue

Typo

### Description

The documentation on the learn.microsoft.com page is confusing because the line breaks are not being rendered as HTML.

![image](https://github.com/Azure/azure-sdk-for-net/assets/70300075/1b775405-7959-4f9f-8611-4f4bc2b5bb3e)

Browsers 

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.resources.resourcegroupresource.getgenericresources?view=azure-dotnet

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.ResourceManager.Resources/ResourceGroupResource.xml

### Document Version Independent Id

7e18fdc7-503c-6a13-72e8-fea167f7882a

### Article author

@azure-sdk

### Metadata

* ID: 42a20203-9bd1-4c28-0ac1-d2b1214902e9 
* Service: **azure**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Hey @MichaelPico , thank you for reaching out to us, the error originates from https://github.com/Azure/azure-rest-api-specs/blob/main/specification/resources/resource-manager/Microsoft.Resources/stable/2023-07-01/resources.json#L2432, so please file an issue in this repo.
