### ISSUE TITLE
FileNotFoundException when creating SecretClient in ASPNETCore 3.1 site

### ISSUE THREAD

**Issue by munkii** [Azure/azure-sdk-for-net#41073]
### Library name and version

Azure.Identity

### Describe the bug

In our ASPNETCore 3.1 site we were using Azure.Identity version 1.3.0 without any issues but we started to get a Warning saying that version had vulnerabilities so we should upgrade it.

The first version without any known vulnerabilities is 1.10.2. Any attempt to move past version 1.9.0 results in us getting 

> System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.'

when calling the following code

`var secretClient = new SecretClient(new Uri("https://name-of-our-kv.vault.azure.net"), new DefaultAzureCredential());`

I have tried enabling AutoGenerateBindingRedirects but that did not help. The only thing that has helped but is a dreadful solution is to explicitly add a reference to the System.Diagnostics.DiagnosticSource into the csproj. 

`<PackageReference Include="System.Diagnostics.DiagnosticSource" Version="6.0.0" />`

I also tried all the available versions after 10.10.2, same issue.

I have attached a small repro
[WebApplication3.zip](https://github.com/Azure/azure-sdk-for-net/files/13860033/WebApplication3.zip)

### Expected behavior

Should be able create a SecretClient and call SecretClient.GetSecret on it without any error

### Actual behavior

Code throws FileNotFoundException

### Reproduction Steps

Try creating a SecretClient. I have attached a repro project that will show the error on execution of the root controller

**Comment by jsquire** [comment]
Hi @munkii.  Thank you for reaching out and we regret that you're experiencing difficulties.  The .NET Core 3.1 runtime reached end-of-life in December of 2022 and is no longer supported by Microsoft.   The Azure SDK packages offer support for versions of the .NET runtime which are themselves supported.   For more context, please see the [Azure SDK lifecycle and support policy](https://azure.github.io/azure-sdk/policies_support.html#azure-sdk-dependencies).

Unfortunately, unless you are able to reproduce this behavior on one of the supported platforms, we're unable to assist.

**Comment by munkii** [comment]
> Hi @munkii. Thank you for reaching out and we regret that you're experiencing difficulties. The .NET Core 3.1 runtime reached end-of-life in December of 2022 and is no longer supported by Microsoft. The Azure SDK packages offer support for versions of the .NET runtime which are themselves supported. For more context, please see the [Azure SDK lifecycle and support policy](https://azure.github.io/azure-sdk/policies_support.html#azure-sdk-dependencies).
> 
> Unfortunately, unless you are able to reproduce this behavior on one of the supported platforms, we're unable to assist.

I thought the .NetCore 3.1 support might have been an issue. No worries and thanks for your speedy reply
