### ISSUE TITLE
[BUG] Azure.ResourceManager.Logic EDI Maps Creation

### ISSUE THREAD

**Issue by Silener** [Azure/azure-sdk-for-net#41076]
### Library name and version

Azure.ResourceManager.Logic 1.1.0

### Describe the bug

Hi there! While dabbling in the Sample_IntegrationAccountMapResource.cs for EDI Map creation I found out that the method Update_CreateOrUpdateAMap is not working for creating a new Map. Using the map resource with the data provided in the example gives an error (System.Exception: '1' is invalid after a single JSON value. Expected end of data. LineNumber: 0 | BytePositionInLine: 16.) for the "Content" property of the "IntegrationAccountMapData" class. Looking deeper into the library I saw that the Content is expected to be JSON, but the provided example is in XML with the comments being:
To assign an object to this property use <see cref="BinaryData.FromObjectAsJson{T}(T, System.Text.Json.JsonSerializerOptions?)".
and
To assign an already formatted json string to this property use <see cref="BinaryData.FromString(string)".
, which leads me to believe that maybe some changes have been made that do not accept XML anymore.

### Expected behavior

Being able to pass XML into the "Content" property as we are expected to pass an Xslt.

### Actual behavior

Passing an XML into the Content property gives the following error:
System.Exception: '1' is invalid after a single JSON value. Expected end of data. LineNumber: 0 | BytePositionInLine: 16.

### Reproduction Steps

Run the sample mentioned in the "Describe the bug" section

### Environment
Visual Studio 2022 - 17.4
OS Name: Windows
OS Version: 10.0.22621
.NET SDK: Version: 8.0.100
.NET runtimes installed:
Microsoft.AspNetCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi @Silener Thank you for using Azure SDK for .NET.
For the issue you mentioned, you could use `BinaryData.FromObjectAsJson` to pass the xml content.
