### ISSUE TITLE
Do continuation tokens expire?

### ISSUE THREAD

**Issue by msft-personal-acct** [Azure/azure-sdk-for-net#41086]
### Library name and version

Azure.Storage.Blobs 12.19.1

### Query/Question

When enumerating an `IAsyncEnumerable<Page<BlobItem>>` retrieved by calling `GetBlobsAsync().AsPages()` each item has a ContinuationToken property.

When the property is not null and not empty: How long is the continuation token good for? Can I use it a day after it was first retrieved? Or does it exist forever?

### Environment

Windows 11 console app: C# using the dotnet 8.0.100 SDK

**Comment by seanmcc-msft** [comment]
@msft-personal-acct, continuation tokens do not expire at a specific time, but may become invalid over time as blobs are added or removed from the container in question.
