### ISSUE TITLE
how to set the content type of the files correctly when uploading a local directory to a container?

### ISSUE THREAD

**Issue by lgong-rms** [Azure/azure-sdk-for-net#41087]
### Library name and version

Azure Storage Data Movement Blobs client library for .NET - version 12.0.0-beta.4

### Query/Question

I am using container.StartUploadDirectoryAsync to upload a local directory to a container following the examples here:
https://learn.microsoft.com/en-us/dotnet/api/overview/azure/storage.datamovement.blobs-readme?view=azure-dotnet-preview
it works but the content type of all blobs/files is set to application/octet-stream.  is it possible to set the content type correctly, e.g., based on the file extension?

### Environment

Microsoft Visual Studio Enterprise 2022 (64-bit) - Current Version 17.8.3 on Windows 10 Enterprise

**Comment by ncoussemacq** [comment]
I'm facing the same case where I need to set a content-type on some of the files I'm uploading using StartUploadDirectoryAsync API.

**Comment by seanmcc-msft** [comment]
@amnguye please post a sample of how to set blob content type on uploads.

**Comment by amnguye** [comment]
Here's a code snippet of how to set the content type:
```
BlobsStorageResourceProvider blobProvider = new BlobsStorageResourceProvider(<authentication, token credential etc>);
StorageResource destinationResource = blobProvider.FromUri(_uri, new BlobStorageResourceContainerOptions()
{
    BlobOptions = new BlobStorageResourceOptions()
    {
         ContentType = new(<content type here>)
    }
}
await transferManager.StartTransferAsync(sourceResource, destinationResource);
```

**Comment by nickliu-msft** [comment]
Does the above code snippet address your question?
