### ISSUE TITLE
Tag published nuget modules with the api-version supported

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-sdk-for-net#4112]
Also add the api-versions part of the release notes if  possible.

This would be  helpful for azurestack and other sovereign clouds

**Comment by shahabhijeet** [comment]
@bganapa release notes is something that is currently manually added.
We have no plans to add API version in the release notes.
Can you suggest why API version needs to be in release notes, primarily when there can be composite nuget packages that might have multiple API versions, this will also mess up the format for the release notes, hence we do not want to auto update release notes with API version.
