### ISSUE TITLE
[QUERY] Content accessing for Schemas/Maps directly instead of from content url

### ISSUE THREAD

**Issue by Silener** [Azure/azure-sdk-for-net#41141]
### Library name and version

Azure.ResourceManager.Logic 1.1.0

### Query/Question

Hi!

When using the SDK to get a Map resource I noticed that there is a content link in the response body and not the content( XSD ), which link must be followed in order to get the content itself. I imagine this is done as to not pass whole XSDs into the requests, but is there a way to add it to the response without making an additional request to the content link and if not is there an idea to add it in the future ?

Thank you!

**Comment by jsquire** [comment]
Hi @Silener.  Thank you for reaching out and we regret that you're experiencing difficulties.  The content of the response is defined by the service and is not something that the Azure SDK library has insight into nor influence over.  

Unfortunately, this repository is focused on the Azure SDK packages and we are unable to assist with other Azure issues.  Your best path forward would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) or to make a feature request through the [Azure Feedback site](https://feedback.azure.com/d365community/).

I'm going to close this out; if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.
