### ISSUE TITLE
[BUG] BackupShortTermRetentionPolicyCollection.CreateOrUpdateAsync() causes exception: client does not have authorization to perform action 'Microsoft.Sql/locations/shortTermRetentionPolicyAzureAsyncOperation/read'

### ISSUE THREAD

**Issue by fhurta** [Azure/azure-sdk-for-net#41151]
### Library name and version

Azure.ResourceManager.Sql 1.2.0

### Describe the bug

I'm programmatically setting BackupShortTermRetentionPolicyData and getting error

```
The client 'xxx' with object id 'yyy' does not have authorization to perform action 'Microsoft.Sql/locations/shortTermRetentionPolicyAzureAsyncOperation/read' over scope '/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Sql/locations/westeurope/shortTermRetentionPolicyAzureAsyncOperation/590cb35f-59f6-4803-92c4-6fceffbf3d4e' or the scope is invalid. If access was recently granted, please refresh your credentials.
```

Looking into the Azure Portal, the PIT is set but the exception breaks my flow.

The code used:

```
var armClient = new ArmClient(new DefaultAzureCredential());

var dbId = new ResourceIdentifier($"{_azureEnvironmentSettings.SqlServerId}/databases/{createDbNotification.DbName}");
var db = armClient.GetSqlDatabaseResource(dbId);
db = await db.GetAsync();

var strPolicies = db.GetBackupShortTermRetentionPolicies();
var strData = new BackupShortTermRetentionPolicyData
{
	RetentionDays = 35,
};
var strPolicyOperation = await strPolicies.CreateOrUpdateAsync(WaitUntil.Completed, "Default", strData);
```

It is performed from within Azure FunctionApp. It has managed identity, which in turn has Sql Server Contributor role.

(The full code creates a new Azure Sql Database in the Elastic Pool, sets its LongTermRetentionPolicies and as a last step it sets also the ShortTermRetentionPolicies - this last steps throws the exception and is shown above.)

### Expected behavior

The code succeeds without the exception. As written above the short term retention policies is set (verified in Azure Portal) so perhaps just the re-reading the value to return it fails?

I tried to remove and add back the managed identity into Sql Server Contributor role, even removing managed identity and generating a new one but none of that helped.

### Actual behavior

I'm programmatically setting BackupShortTermRetentionPolicyData and getting error

```
The client 'xxx' with object id 'yyy' does not have authorization to perform action 'Microsoft.Sql/locations/shortTermRetentionPolicyAzureAsyncOperation/read' over scope '/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Sql/locations/westeurope/shortTermRetentionPolicyAzureAsyncOperation/590cb35f-59f6-4803-92c4-6fceffbf3d4e' or the scope is invalid. If access was recently granted, please refresh your credentials.
```

Looking into the Azure Portal, the PIT is set but the exception breaks my flow.

The code used:

```
var armClient = new ArmClient(new DefaultAzureCredential());

var dbId = new ResourceIdentifier($"{_azureEnvironmentSettings.SqlServerId}/databases/{createDbNotification.DbName}");
var db = armClient.GetSqlDatabaseResource(dbId);
db = await db.GetAsync();

var strPolicies = db.GetBackupShortTermRetentionPolicies();
var strData = new BackupShortTermRetentionPolicyData
{
	RetentionDays = 35,
};
var strPolicyOperation = await strPolicies.CreateOrUpdateAsync(WaitUntil.Completed, "Default", strData);
```

It is performed from within Azure FunctionApp. It has managed identity, which in turn has Sql Server Contributor role.

(The full code creates a new Azure Sql Database in the Elastic Pool, sets its LongTermRetentionPolicies and as a last step it sets also the ShortTermRetentionPolicies - this last steps throws the exception and is shown above.)

### Reproduction Steps

The code and description is provided

### Environment

Azure Function dotnet-isolated .Net8
referenced packages:
- Azure.Identity 1.10.4
- Azure.ResourceManager 1.9.0
- Azure.ResourceManager.Sql 1.2.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi @fhurta , Thank you for using Azure SDK for .NET.
We can't repro your issue based on the infos you provided.
Please make sure the credential you are using has the right permission. You could check the error message's id permission.
Note, any operation send/received by our SDK is based on the credential token retrieved in `ArmClient`.
