### ISSUE TITLE
[BUG] Empty Folder in Blob path is stripped when accessing BlobClient.Uri

### ISSUE THREAD

**Issue by willyt150** [Azure/azure-sdk-for-net#41153]
### Library name and version

Azure.Storage.Blobs 12.19.1

### Describe the bug

The sdk does not properly include "empty folder" in blob paths. For example `<container_name>//file.txt` ends up as `<container_name>/file.txt` using this SDK and then any interactions with the blob fail with 404 as it doesn't exist.

We have consumers of our system, who we provide with a Container SAS token url, successfully uploading files to blob storage with an "empty folder" in the blob's path. While we're working on trying to get them to remove it, there's no way for us to prevent consumers from doing something like this in the future.

Versions prior to 12.9.0 of the SDK as well as the deprecated Microsoft.Azure.Storage.Blob nuget package used to handle this correctly and provide the correct blob path/url.

### Expected behavior

We expect a `BlobClient.Uri` for a blob with an empty folder in its path (e.g. `<container_name>//file.txt`) to have its url include that empty folder.

`https://<storage_account>.blob.core.windows.net/<container_name>//file.txt`

### Actual behavior

The `BlobClient.Uri` has the empty folder stripped

`https://<storage_account>.blob.core.windows.net/<container_name>/file.txt`

### Reproduction Steps

EDIT: Sorry missed that I could attach. Here's a .Net console app to show the reproduction of the issue.
You should only need to replace the `[CONNECTION_STRING]` value on line 11 of `Program.cs` to a Storage Account you have access to and it will to everything.
[EmtpyNameFolderTest.zip](https://github.com/Azure/azure-sdk-for-net/files/13894108/EmtpyNameFolderTest.zip)

High Level steps
1. Upload a blob to azure storage with an empty folder in its virtual path
    - Easily accomplished using `Microsoft.Azure.Storage.Blob 11.2.3`. We do not know what the consumer is using to upload 
2. Using `Azure.Storage.Blobs 12.19.1` Create `BlobServiceClient` from connection string
3. Then create `BlobContainerClient` using the service client for the container the blob was uploaded to
4. loop over `blobContainerClient.GetBlobsAsync()` results (type `BlobItem`)
5. Create `BlobClient` from the `BlobItem` using the containerclient's `GetBlobClient` method using the blob item's name (will look something like `/file.txt`
6. Look at the blob client's `Uri` property, it is missing the empty folder and therefore will result in a 404 for any interaction with it.

### Environment

.Net 6, Azure Functions, but reproducible in a .Net 6 Console application
Visual Studio 17.8.3

**Comment by Pathak-Akshat** [comment]
While creating the blob client , I think you can use BlobClientOptions to pass this TrimBlobNameSlashes as false.

![image](https://github.com/Azure/azure-sdk-for-net/assets/28618614/bc532850-79aa-4667-ad66-4fb498c897aa)

https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs/src/BlobClientOptions.cs#L16

**Comment by willyt150** [comment]
@Pathak-Akshat thank you, the `BlobClientOptions.TrimBlobNameSlashes` set to `false` gets it working like it did before.

In that case, I'd contend that defaulting it to `true` for "backwards compatibility" is incorrect. Older versions did NOT trim blob name slashes so for backwards compatibility it should be `false`

**Comment by seanmcc-msft** [comment]
Workaround was provided.
