### ISSUE TITLE
Format of databasename property in WorkloadSqlRestoreContent

### ISSUE THREAD

**Issue by bzuidgeest** [Azure/azure-sdk-for-net#41190]
### Library name and version

Azure.ResourceManager.RecoveryServicesBackup

### Query/Question

I'm trying to restore a database using the graph api. 

At some point to trigger the restore I need to provide a WorkloadSqlRestoreContent. I'm not restoring to the original server so I need to provide a new database name and instance name.

from the link below I believe I can set the new instance name and database name in one go using the databasename property.
This property is string and the correct format is not documented. So what should it be?

server\instance.database or server\instance/database or or or.....

Unfortunately these things are very poorly documented. Its very hard to use.

https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.management.recoveryservices.backup.models.targetrestoreinfo.databasename?view=azure-dotnet-legacy&viewFallbackFrom=azure-dotnet-preview

### Environment

vs2022 latest

**Comment by mcgallan** [comment]
Hi @bzuidgeest , thank you for your feedback. Regarding your question, I believe that in TargetRestoreInfo, DatabaseName actually refers to the name of the database, not the ResourceID. Therefore, it doesn't really have a specific format. The format of ContainerID, which also belongs to TargetRestoreInfo, should be similar to "/subscriptions/yoursubscription/../..". It works together with DatabaseName to locate the database for the restore operation.
