### ISSUE TITLE
[BUG] SiteFunctionResource.GetFunctionKeysAsync always returns an empty dictionary

### ISSUE THREAD

**Issue by HardToChoose** [Azure/azure-sdk-for-net#41218]
### Library name and version

Azure.ResourceManager.AppService 1.0.0.0

### Describe the bug

`SiteFunctionResource.GetFunctionKeysAsync` returns an object of type `AppServiceConfigurationDictionary` which is always empty.
The HTTP response returned by Azure API is a JSON object like `{ "default": "XXXX" }`, but `AppServiceConfigurationDictionary.Properties` is not populated with this data during deserialization.

### Expected behavior

`AppServiceConfigurationDictionary.Properties` must be populated with function keys

### Actual behavior

`AppServiceConfigurationDictionary.Properties` is empty

### Reproduction Steps

```
ResourceGroupResource resourceGroup;
// ...
WebSiteResource functionApp = await resourceGroup
    .GetWebSites()
    .GetAsync("someAzureFunctionApp");

AppServiceConfigurationDictionary functionKeys = await functionApp
    .GetSiteFunction("httpTriggerFunc").Value
    .GetFunctionKeysAsync();

int keyCount = functionKeys.Properties.Count; // == 0
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by welovej** [comment]
Issue fixed, will ship in the next release.
