### ISSUE TITLE
Authentication library 2.3.2 isn't really compatible with ADAL up to 4.0

### ISSUE THREAD

**Issue by TimLovellSmith** [Azure/azure-sdk-for-net#4124]
We just tried out Microsoft.Rest.ClientRuntime.Azure.Authentication 2.3.2 with ADAL 3.19.2 on desktop .net and we get MissingMethodException

**Comment by shahabhijeet** [comment]
@TimLovellSmith can you please provide me the details.
How can I repro this issue.

**Comment by TimLovellSmith** [comment]
I think basically what I wanted out of this issue was the ability to use latest and greatest ADAL library with latest Microsoft.Rest.ClientRuntime.Azure.Authentcation, as a way out of compatibility issues.

At the time of filing, I think 2.3.2 was the most recent version?
If this also affects 2.3.3, then probably just by updating your nuget dependency from the Microsoft.Rest.ClientRuntime.Azure.Authentication project to being upon ADAL 4.0, you would see the issue as a compile error.

**Comment by TimLovellSmith** [comment]
So I hit this again.
Here is the repro:

use 
```  <package id="Microsoft.Rest.ClientRuntime.Azure.Authentication" version="2.3.2" targetFramework="net461" />```


```  <package id="Microsoft.IdentityModel.Clients.ActiveDirectory" version="3.19.6" targetFramework="net461" />```

And 

```
IAuthenticated azure = Azure.Authenticate(new AzureCredentials(
                new UserLoginInformation { UserName = Console.ReadLine(), Password = Console.ReadLine(), ClientId = clientId },
                tenantId,
                AzureEnvironment.AzureGlobalCloud));
            Console.Clear();
            var cacheTeamSub = azure.WithSubscription("yoursubid");
            var region = Region.Create("Central US EUAP");
            var vnet = cacheTeamSub.Networks.Define("vnet1").WithRegion(region).WithNewResourceGroup("rg1").Create();
```

And it blows up with

"Method not found: 'System.Threading.Tasks.Task`1<Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationResult> Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireTokenAsync(System.String, System.String, Microsoft.IdentityModel.Clients.ActiveDirectory.UserCredential)'."

on the last line.

```
   at Microsoft.Rest.Azure.Authentication.UserTokenProvider.<LoginSilentAsync>d__24.MoveNext()\r\n   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)\r\n   at Microsoft.Rest.Azure.Authentication.UserTokenProvider.LoginSilentAsync(String clientId, String domain, String username, String password, ActiveDirectoryServiceSettings serviceSettings, TokenCache cache)\r\n   at Microsoft.Azure.Management.ResourceManager.Fluent.Authentication.AzureCredentials.<ProcessHttpRequestAsync>d__24.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at Microsoft.Azure.Management.ResourceManager.Fluent.ResourceGroupsOperations.<CreateOrUpdateWithHttpMessagesAsync>d__6
.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.Management.ResourceManager.Fluent.ResourceGroupImpl.<CreateResourceAsync>d__26.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.Creatable`4.<Microsoft-Azure-Management-ResourceManager-Fluent-Core-ResourceActions-IResourceCreator<IResourceT>-CreateResourceAsync>d__15.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.T
hrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.CreatorTaskItem`1.<ExecuteAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.TaskGroupBase`1.<ExecuteNodeTaskAsync>d__14.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.Extensions.Synchronize[TResult](Func`1 function)\r\n   
at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.Creatable`4.Create()
```

**Comment by shahabhijeet** [comment]
@TimLovellSmith if you want to use username/password, you will have to use .NET 4.5.2 version of this library and use the one that it is bound to and you cannot upgrade to latest.
Because latest ADAL has breaking changes and you cannot use username/password with latest ADAL.

**Comment by zh454771942** [comment]
@shahabhijeet We have a similar issue here. I am trying to call 
`public static Task<ServiceClientCredentials> LoginSilentWithCertificateAsync(string domain, ClientAssertionCertificate certificate, ActiveDirectoryServiceSettings settings);`, using the latest ADAL, but got the error 

System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationResult> Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireTokenAsync(System.String, Microsoft.IdentityModel.Clients.ActiveDirectory.ClientAssertionCertificate)'.

I need to move to new version of ADAL as other nuget packages are using it. Can you instruct me on how to solve this problem?

**Comment by TimLovellSmith** [comment]
>Because latest ADAL has breaking changes and you cannot use username/password with latest ADAL.
Really cannot use username and password at all? Or just have to use it a different way, as some suggest?
https://stackoverflow.com/questions/37465949/adal-net-v3-does-not-support-acquiretoken-with-usercredential
