### ISSUE TITLE
How do I update specific properties on a ContainerApp?

### ISSUE THREAD

**Issue by groogiam** [Azure/azure-sdk-for-net#41244]
### Library name and version

Azure.ResourceManager.AppContainers 1.1.1

### Query/Question

I'm trying to pull down an existing container app definition, update a couple properties (custom domains) and then save the changes. This does not seem to work as the Get does not seem to populate secrets or container registry passwords, so when I try to save the object i get
```
Invalid Request: Container app secret(s) with name(s) 'container-registry-password' are invalid: value or keyVaultUrl and identity should be provided
```

My code does not directly have access to these secrets and I don't want to risk resetting these properties. How do I do a patch operations on just the properties I need to update as Update seems to do a put?

**Comment by groogiam** [comment]
This looks related to https://github.com/Azure/azure-sdk-for-net/issues/35004

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Duplicate with #35004
