### ISSUE TITLE
[FEATURE REQ][Cosmos DB] Provide CreateCreateOrUpdateIfNotExist

### ISSUE THREAD

**Issue by Danieladu** [Azure/azure-sdk-for-net#41251]
### Library name

Azure.ResourceManager.CosmosDB

### Please describe the feature.

Now we are using such code to create new  colection if the container does not exist:
```
var databases = _cosmosClient.GetCosmosDBSqlDatabases();
if (await databases.ExistsAsync(databaseName, cancellationToken: cancellationToken))
{
    databaseResource = await databases.GetAsync(databaseName, cancellationToken: cancellationToken);
}
else
{
    var addResponse = await databases.CreateOrUpdateAsync(WaitUntil.Completed, databaseName, xxx, xxx);
    databaseResource  = aadResponse.Value;
}
```

There exists a race condition where two instances/Threads tried to create the same new container? If the condition check is passed and prepare to add a new container, another thread just added one, this one would cover the other one?

Maybe need  a new method `CreateOrUpdateIfNotExistAsync()`

or provide some method like `GetOrAdd()` in `ConcurrentDictionary`, [reference](https://learn.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentdictionary-2.getoradd?view=net-8.0#system-collections-concurrent-concurrentdictionary-2-getoradd(-0-system-func((-0-1))))
Thanks

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi @Danieladu ,Thank you for using Azure SDK for .NET.
For question you mentioned, `Exists` only calls the get operation and return bool value, it will not try to create a new one.
`CreateOrUpdate` is the method used to create a resource, so there will not be any conflict or race here.
Since you add the await there, it should be safe while runnning the async method.
