### ISSUE TITLE
[BUG]  Azure Functions App returns Status 200 when endpoint called in short sequence

### ISSUE THREAD

**Issue by janschreieradac** [Azure/azure-sdk-for-net#41264]
### Library name and version

Microsoft.Azure.Functions.Worker.Extensions.Http 3.1

### Describe the bug

When hitting the following endpoint multiple times, it ocassanlly happens that in between expected  responses
`Status: 400 Bad Request, Response: {   "Data": null,  "Success": false }`
I get 
`Status: 200 OK: Response: `

```csharp
[Function("bugtest")]
public IActionResult BugTest(
	[HttpTrigger(AuthorizationLevel.Function, "get", Route = "endpoints/bugtest")] HttpRequest req)
{
	return new ContentResult()
	{
		Content = "{\"Data\":null,\"Success\":false}",
		ContentType = "application/json; charset=utf-8",
		StatusCode = (int)HttpStatusCode.BadRequest,
	};
}
```

Thanks for looking into this!

### Expected behavior

I would expect to always receive the first result. when running the function locally it works as expected.

### Actual behavior

![the issue is also show in the Azure Portal Monitor for that function](https://github.com/Azure/azure-sdk-for-net/assets/138873071/8d965e5f-d9de-483c-8fc1-fcf6e4c9c9f8)

### Reproduction Steps

take the above example and run it as a dotnet-isolated function in Azure

### Environment

az functions version: 4
Environment: dotnet-isolated 8.0
Server: Linux

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.Azure.Functions.Worker.Extensions.Http`package is maintained as [#2215](https://github.com/Azure/azure-functions-dotnet-worker/issues/2215).
