### ISSUE TITLE
[QUERY] Is there support for OpenAI Assistants API?

### ISSUE THREAD

**Issue by nrhoffmann** [Azure/azure-sdk-for-net#41293]
### Library name and version

Azure.AI.OpenAI 1.0.0-beta.12

### Query/Question

Are assistants supported? If not, when can we expect support?

**Comment by nrhoffmann** [comment]
I have found this: https://github.com/Azure/azure-sdk-for-net/pull/40817

**Comment by scottaddie** [comment]
The Assistants v2 API is supported in the 2.x release train. I encourage you to upgrade and try it out.
