### ISSUE TITLE
Consider exposing static singleton instance for HttpClientPipelineTransport

### ISSUE THREAD

**Issue by pallavit** [Azure/azure-sdk-for-net#41309]
```c#
System.ClientModel.Primitives.HttpClientPipelineTransport.HttpClientPipelineTransport()
```
#
Should we expose a static singleton instance?

https://apiview.dev/Assemblies/Review/1b123e7a51d44ebe945f0212ee039c65/57e9a3d0f27542d7be602db4b320eaee#System.ClientModel.Primitives.HttpClientPipelineTransport.HttpClientPipelineTransport%28%29

**Comment by annelo-msft** [comment]
Completed.
