### ISSUE TITLE
How to use this HighlightFields property

### ISSUE THREAD

**Issue by itarunkumar08** [Azure/azure-sdk-for-net#41321]
### Type of issue

Missing information

### Description

How it is set? When it is set? Why is Highlight property is missing in this Class but it is available when searching through REST API? 
Kindly help in understanding how this field works? 

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/azure.search.documents.searchoptions.highlightfields?view=azure-dotnet

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Search.Documents/SearchOptions.xml

### Document Version Independent Id

d00fdd93-4e86-4044-6642-dff568d46af9

### Article author

@azure-sdk

### Metadata

* ID: 0127c4fe-2b05-7b59-37f6-6f92e672c538 
* Service: **azure**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ShivangiReja** [comment]
Hi @itarunkumar08, the `SearchOptions.HighlightFields` property, documented [here](https://learn.microsoft.com/en-us/dotnet/api/azure.search.documents.searchoptions.highlightfields?view=azure-dotnet), corresponds to the `Highlight` property in the [REST API](https://learn.microsoft.com/en-us/rest/api/searchservice/search-documents#request-body). It is used for hit highlighting, applying text formatting (e.g., bold or yellow highlights) to matching terms in a result, making it easier to identify the match. This feature is particularly useful for longer content fields like a description field, where the match may not be immediately apparent.

You can provide a list of field names for hit highlights, but keep in mind that only searchable fields can be used for this purpose. The search results are accessible through the `Highlights` property of the [`SearchResult<T>`](https://learn.microsoft.com/en-us/dotnet/api/azure.search.documents.models.searchresult-1.highlights?view=azure-dotnet#azure-search-documents-models-searchresult-1-highlights) class.

Here's an example of how to use it in C#:

```csharp
Response<SearchResults<Hotel>> response = await searchClient.SearchAsync<Hotel>("luxury hotel",
        new SearchOptions
        {
            Filter = "rating eq 5",
            HighlightPreTag = "<b>",
            HighlightPostTag = "</b>",
            HighlightFields = new[] { Description, Category }
        });
SearchResult<Hotel> doc = await response.Value.GetResultsAsync().FirstAsync();
var highlights = doc.Highlights;
var highlightCount = doc.Highlights.Count;
CollectionAssert.Contains(highlights.Keys, Description);
CollectionAssert.Contains(highlights.Keys, Category);
CollectionAssert.AreEqual(
    new[]
    {
        "Best <b>hotel</b> in town if you like <b>luxury</b> <b>hotels</b>.",
        "We highly recommend this <b>hotel</b>."
    },
    highlights[Description]);
```

I hope this helps. For more details, please refer to the [Hit Highlighting documentation](https://learn.microsoft.com/en-us/azure/search/search-pagination-page-layout#hit-highlighting).
