### ISSUE TITLE
[BUG] Azure.ResourceManager.KeyVault.KeyVaultCollection.CreateOrUpdateAsync does not update network rule sets as expected.

### ISSUE THREAD

**Issue by felixarise** [Azure/azure-sdk-for-net#41355]
### Library name and version

Azure.ResourceManager.KeyVault 1.2.0

### Describe the bug

I would like to able to disable a virtual network protection for a key vault. On keyvault creation I enabled a virtual network protection by specifying a few subnet resource ids. But when I try to disable a vnet protection, nothing happens. A keyvault still has the same virtual network subnets ids.

### Expected behavior

Network Acls can be disabled for a key vault.

### Actual behavior

Network Acls are still the same

### Reproduction Steps

Here a code snipped how I configure network acls for a key vault.
```
public virtual void ConfigureNetworkAcls(
    KeyVaultProperties properties,
    KeyVaultNetworkAcls networkRules)
{
    if (networkRules.NetworkAcls is null) return;

    var networkRuleSet = new KeyVaultNetworkRuleSet()
    {
        DefaultAction = !string.IsNullOrWhiteSpace(networkRules.NetworkAcls.DefaultAction) ?
            new(networkRules.NetworkAcls.DefaultAction) : null,
        Bypass = !string.IsNullOrWhiteSpace(networkRules.NetworkAcls.Bypass) ?
            new KeyVaultNetworkRuleBypassOption(networkRules.NetworkAcls.Bypass) : new()
    };

    foreach (var subnet in networkRules.NetworkAcls.SubnetResourceIds)
    {
        networkRuleSet.VirtualNetworkRules.Add(new(subnet));
    }

    properties.NetworkRuleSet = networkRuleSet;
} 
```

And then I pass created KeyVaultCreateOrUpdateContent object to method for create or update key vault.

```
internal virtual async Task<string> CreateOrUpdateKeyVaultAsync(
    string vaultName, 
    string resourceGroupName,
    KeyVaultCreateOrUpdateContent content)
{
    try
    {
        ResourceGroupResource resourceGroupResource = await GetResourceGroupResourceAsync(resourceGroupName);
        KeyVaultResource vault = (await resourceGroupResource.GetKeyVaults()
            .CreateOrUpdateAsync(WaitUntil.Completed, vaultName, content)).Value;

        logger.Success($"Successfully created key vault - {vaultName}.");

        return vault.Id.ToString();
    }
    catch (RequestFailedException ex)
    {
        logger.Error($"Unable to create environment key vault. Details: {ex.Message}");
        throw;
    }
}
```

### Environment

.NET SDK:
 Version:           8.0.101
 Commit:            6eceda187b
 Workload version:  8.0.100-manifests.825c015e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.101\

.NET workloads installed:
 Workload version: 8.0.100-manifests.825c015e
 [wasm-tools-net6]
   Installation Source: VS 17.8.34408.163
   Manifest Version:    8.0.1/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.workload.mono.toolchain.net6\8.0.1\WorkloadManifest.json
   Install Type:              Msi

 [wasm-tools-net7]
   Installation Source: VS 17.8.34408.163
   Manifest Version:    8.0.1/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.workload.mono.toolchain.net7\8.0.1\WorkloadManifest.json
   Install Type:              Msi

 [wasm-tools]
   Installation Source: VS 17.8.34408.163
   Manifest Version:    8.0.1/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.workload.mono.toolchain.current\8.0.1\WorkloadManifest.json
   Install Type:              Msi

 [maui-windows]
   Installation Source: VS 17.8.34408.163
   Manifest Version:    8.0.3/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.3\WorkloadManifest.json
   Install Type:              Msi

 [maccatalyst]
   Installation Source: VS 17.8.34408.163
   Manifest Version:    17.0.8478/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maccatalyst\17.0.8478\WorkloadManifest.json
   Install Type:              Msi

 [ios]
   Installation Source: VS 17.8.34408.163
   Manifest Version:    17.0.8478/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.ios\17.0.8478\WorkloadManifest.json
   Install Type:              Msi

 [android]
   Installation Source: VS 17.8.34408.163
   Manifest Version:    34.0.43/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.android\34.0.43\WorkloadManifest.json
   Install Type:              Msi

Host:
  Version:      8.0.1
  Architecture: x64
  Commit:       bf5e279d92

.NET SDKs installed:
  8.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

VS version: 17.8.4

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by felixarise** [comment]
Closed as not reproducible anymore.
