### ISSUE TITLE
[Service Bus] Add NamespaceProperties to ServiceBusModelFactory

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#41356]
# Summary

The `NamespaceProperties` type used by the `ServiceBusAdministrationClient` has a public constructor, but all properties have internal setters.  This makes it impossible to create a populated instance for mocking purposes.  

## Success criteria

- The `ServiceBusModelFactory` allows creation of a populated `NamespaceProperties` instance.
- We have made a decision on whether we should hide the public constructor and have made any needed implementation corrections.

**Comment by azad1612** [comment]
HI @jsquire Thanks for quick help, I am trying mock for GetRulesAsync() and GetQueuesAsync() object reference errors. can u please share sample code snippet for above methods.
