### ISSUE TITLE
Consider making CancellationToken optional in BinaryContent.WriteTo method.

### ISSUE THREAD

**Issue by pallavit** [Azure/azure-sdk-for-net#41362]
```c#
System.ClientModel.BinaryContent.WriteTo(System.IO.Stream, System.Threading.CancellationToken)
```
#
should CT be optional?

**Comment by annelo-msft** [comment]
This is not a breaking change per Framework Design Guidelines

>  D.11.16 Changing a Parameter from Required to Optional (✔️)
> 
> Optional parameters, also known as default parameters or default arguments, are a compile-time feature, not a runtime feature. Therefore, there is no runtime impact when you change a parameter from required to optional.
> 
> When making parameters optional, be careful not to introduce ambiguity between member overloads when only some parameters are specified. The Framework Design Guidelines encourage you to have optional parameters on only one overload to avoid ambiguous member invocations.
> 
> The .NET BCL team considers this an acceptable change, provided the change does not require parameter reordering and does not introduce the possibility of an ambiguous member invocation.
