### ISSUE TITLE
[FEATURE REQ] Enable AzureSdkLogForwarder in Azure Monitor OTel distro

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-net#41373]
### Library name

Azure.Monitor.OpenTelemetry.AspNetCore

### Please describe the feature.

Azure SDKs emit logs using EventSources. EventSources can be forwarded to ILogger using [AzureEventSourceLogForwarder ](https://learn.microsoft.com/en-us/dotnet/azure/sdk/logging#logging-with-client-registration)  

Some SDKs like CosmosDB leverage this to emit essential diagnostic information and currently have to ask users to enable it explicitly:

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/8af055c68e01af1df9d530d3b716437c68ee5579/Microsoft.Azure.Cosmos.Samples/Usage/OpenTelemetry/Program.cs#L67-L68

AzMon distro should support Azure SDK logs by default.

**Comment by TimothyMothra** [comment]
Should this be an opt-in feature? 
I'm imagining users would only want this enabled if there's an issue.
Currently we're not sending the Exporter's internal logs to the AI Resource.

**Comment by TimothyMothra** [comment]
Cijo commented that this sounds like the same feature that was added to the AI SDK:

- "Report internal dependencies from Cosmos SDK as InProc and align with Cosmos SDK EventSource changes"
  https://github.com/microsoft/ApplicationInsights-dotnet/pull/2712


Long term, is there a plan for Azure SDKs to migrate to ILogger natively?

**Comment by lmolkova** [comment]
> Long term, is there a plan for Azure SDKs to migrate to ILogger natively?

No, we won't add a dependency on ILogger and we use EventSource to write our logs.

> I'm imagining users would only want this enabled if there's an issue.
Users enable error/warn SDK logs by default because these logs provide observability. Some users enable info logs, some use them instead of traces - these logs are for users. 
Verbose logs are for us to consumer and users opt in by configuring ILogger levels.

So opt-in mechanism is already part of  ILogger, but the distro should allow opt-in to happen.

**Comment by jcocchi** [comment]
+1, the user should still be able to control their own log level/ sampling. The ask is for the capability for logging to wired up by default
