### ISSUE TITLE
[BUG] Unknown MonitorConditionOperator value. (Parameter 'value') Actual value was Equal.

### ISSUE THREAD

**Issue by geolawton** [Azure/azure-sdk-for-net#41377]
### Library name and version

Azure.ResourceManager.Monitor 1.3.0

### Describe the bug

It's possible for alert rules to have the Operator of "Equal" when created in the Azure Portal. The enum `MointorConditionOperator` Does not have a value for this to map to and will crash when it attempts to do so. 

### Expected behavior

Should be able to query for alerts that have a "Equal to" operator

### Actual behavior

Will crash with an `ArgumentOutOfRangeException` when attempting to get an alert rule that has "table rows = 0"

### Reproduction Steps

Create a log search alert rule using Application Insights.
- Set the Alert Logic condition to be as such:
![image](https://github.com/Azure/azure-sdk-for-net/assets/90012201/7597b01f-fb20-4ccf-ae2b-a7f57605b40d)
- Confirm that the operator is set to Equal on "Review + Create"
![image](https://github.com/Azure/azure-sdk-for-net/assets/90012201/e44400fb-e3d8-41cb-ba79-6f4ba6a5cf88)
- Run the following code to get all alert rules. It will crash on `GetAllAsync()` when trying to get the alert with the Equal operator
```csharp
var client = new ArmClient(new DefaultAzureCredential());
var subscription = client.GetDefaultSubscription();
var allRgs = subscription.GetResourceGroups();

var scheduledQueryRules = new List<ScheduledQueryRuleResource>();
foreach(var rg in allRgs)
{
     await foreach(var scheduledQueryRule in rg.GetScheduledQueryRules().GetAllAsync())
     {
         currentScheduledQueryRule = scheduledQueryRule;
         scheduledQueryRules.Add(scheduledQueryRule);
     }
}
```

### Environment

IDE: Rider
Version: Build #RD-233.13135.100

`dotnet --info` output
```
.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.8d38d0cc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100\

.NET workloads installed:
 Workload version: 8.0.100-manifests.8d38d0cc
There are no installed workloads to display.

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

.NET SDKs installed:
  8.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by geolawton** [comment]
There is a workaround where changing the alert in the Azure Portal to use GreaterThen and LessThan will circumnavigate the issue. E.g. `table rows = 0` becomes `table rows < 1`

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
This is a service issue. The defined value is: `Equals`, but the actual response is `Equal`.
https://github.com/Azure/azure-rest-api-specs/blob/2491b616cde43277fae339604f03f59412e016aa/specification/monitor/resource-manager/Microsoft.Insights/stable/2022-06-15/scheduledQueryRule_API.json#L607
We had a quick fix on the SDK, waiting for review & merge.

**Comment by HarveyLink** [comment]
Issue fixed, will ship in the next release.
