### ISSUE TITLE
[QUERY] Is it possible to serialze a ManagedDiskData to json?

### ISSUE THREAD

**Issue by krizex** [Azure/azure-sdk-for-net#41419]
### Library name and version

Azure.ResourceManager.Computer 1.3.0

### Query/Question

I noticed the class `ManagedDiskData` implements `IUtf8JsonSerializable`. However, the interface `IUtf8JsonSerializable` is internal so I am not able to call `IUtf8JsonSerializable.Write` on this class to serialize it to json.

Is there a possible approach or workaround that I can utilize to accomplish my objective?

Thanks!

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by krizex** [comment]
Thanks @dvbb !
