### ISSUE TITLE
Add full support for search Oct preview release

### ISSUE THREAD

**Issue by pallavit** [Azure/azure-sdk-for-net#41410]
Given the preview SDK supporting Oct preview was done to unblock GA. We are aiming to have an SDK preview release targeting Oct preview with the following
1. Full convenience API
2. Samples
3. Full testing. 

This is expected to be RC which we expect to GA in March end.

**Comment by ShivangiReja** [comment]
We have already added full support for the Oct preview, incorporating all the GA changes, convenience APIs, samples, and test cases. A preview version has been released and can be found at https://www.nuget.org/packages/Azure.Search.Documents/11.6.0-beta.1.
