### ISSUE TITLE
[QUERY] Help cannot get Azure.Identity working as a replacement for old code.

### ISSUE THREAD

**Issue by nschuessler** [Azure/azure-sdk-for-net#41422]
### Library name and version

Azure.Identity 1.10.4

### Query/Question

I have a scope configured for my web api as `api://<guid>/access_as_service`. Previous code I could just specify `api://<guid>` to the `AcquireTokenAsync` api and I got an appropriate token.

I now have the following code:

```
 IConfidentialClientApplication confidentialClient = ConfidentialClientApplicationBuilder.Create(clientId)
               .WithClientSecret(clientSecret)
               .WithAuthority(AADInstance)
               .Build();

   string[] scopes = new[] { "api://<guid>"+ "/access_as_service" };   // *** What does this have to be?

  AuthenticationResult authResult = await confidentialClient.AcquireTokenForClient(scopes).ExecuteAsync();
  string accessToken = authResult?.AccessToken ?? string.Empty;

```

I get the following results:
1) api://&lt;guid&gt;/.default   -- successfully gets token, but I get 403 when accessing the service using the token.
2) api://&lt;guid&gt;/access_as_service -- API complains that scope doesn't end with "/.default"
3) api://&lt;guid&gt;/access_as_service/.default  -- MSALException "Resource principal "api://&lt;guid&gt;/access_as_service" does not exist.

This is the code I'm trying to replace:
```
ClientCredential clientCred = new ClientCredential(clientId, clientSecret);
AuthenticationContext authContext = new AuthenticationContext(AADInstance);

AuthenticationResult authResult = await authContext.AcquireTokenAsync("api://<guid>", clientCred);
string accessToken = authResult?.AccessToken;
```

### Environment

This repros in a .Net 8 console application with Azure.Identity 1.10.4.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @nschuessler - 
I think the correct scope to pass is `api://<guid>/.default`.  There is some documentation [here](https://learn.microsoft.com/en-us/entra/identity-platform/scenario-daemon-acquire-token?tabs=idweb#scopes-to-request) that discusses scopes. 

The code in your example is using MSAL directly, rather than Azure.Identity. Here is an example similar to yours [here](https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2?tab=readme-ov-file).

The equivalent for Azure.Identity would be to use the [ClientSecretCredential](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.clientsecretcredential?view=azure-dotnet)

**Comment by nschuessler** [comment]
So I tried with client credential as well, and I get the same result as with IConfidentialClientApplication. A 403 Forbidden:

```
    ClientSecretCredential secretCredential = new ClientSecretCredential(
         TenantId,
         clientId,
         clientSecret);

     string[] scopes = new[] { "api://<guid>" + "/.default" };
     TokenRequestContext context = new TokenRequestContext(scopes, null, null, TenantId);
     AccessToken token = await secretCredential.GetTokenAsync(context, CancellationToken.None);
     string accessToken = token.Token;
```

**Comment by nschuessler** [comment]
So my scenario is I have a console application that runs on a VM scale set.  I starts up using a managed identity to access a key vault to pull client id and secret. In production is the app managed identity, in development environment it is my user identity.  It then uses the client secret, client id to access a production web service. The second step is what is giving me a 403 forbidden (the code above).

**Comment by nschuessler** [comment]
Ok. Sorry folks I found the problem. Nothing to do with azure identity /MSAL of course.  I updated the azure identity library and changed APIs I called between the services. I forgot to add `[Authorize(Roles=xxxx)]` for my service to the new APIs which were exclusive to a different app previously.  Problem solved.

**Comment by nschuessler** [comment]
Problem solved
