### ISSUE TITLE
[FEATURE REQ] - QueryFields for the C# SDK

### ISSUE THREAD

**Issue by VladDerptastic** [Azure/azure-sdk-for-net#41434]
### Library name

Azure.AI.FormRecognizer

### Please describe the feature.

[QueryFields](https://learn.microsoft.com/en-us/azure/ai-services/document-intelligence/concept-add-on-capabilities?view=doc-intel-4.0.0#query-fields) have been added to the Document Intelligence API and Studio starting with the `2023-10-31-preview` version. The current latest (preview & stable) .NET/C# SDK release - 4.1.0 - is still using `2022_07_31` inside, and does not allow for using a higher version than `2022_08_31`:
![image](https://github.com/Azure/azure-sdk-for-net/assets/17119930/54b265bf-82e6-42e1-8365-4182e9a48f35)

When will this functionality be released to the C# SDK package (even as a preview)? Is there a plan for this even? The [repo](https://github.com/Azure/azure-sdk-for-net/tree/Azure.AI.FormRecognizer_4.1.0/sdk/formrecognizer/Azure.AI.FormRecognizer) has last been updated 5 months ago.

**Comment by kinelski** [comment]
Hello @VladDerptastic.

Going forward we don't intend to update the `Azure.AI.FormRecognizer` package anymore. Instead, development has shifted to the new `Azure.AI.DocumentIntelligence` library, which currently does support service version `2023-10-31-preview` and query fields.

You can check our README for more details: [README](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/documentintelligence/Azure.AI.DocumentIntelligence/MigrationGuide.md)
We also have a migration guide for those coming from the FormRecognizer package: [Migration Guide](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/documentintelligence/Azure.AI.DocumentIntelligence/MigrationGuide.md)

Please note that the new package is not backward compatible with the old one.

**Comment by VladDerptastic** [comment]
@kinelski Thank you for the answer and the migration guide, that's exactly what I needed. Perhaps a line in the old [README](https://github.com/Azure/azure-sdk-for-net/tree/Azure.AI.FormRecognizer_4.1.0/sdk/formrecognizer/Azure.AI.FormRecognizer) redirecting to the new package (and new documentation) might be useful to other lost souls like me?

It did cross my mind, that maybe development would be done under the new name, but when I was looking it up, I forgot to also search for preview packages, and since that one is in `1.0.0-beta.1` it sneaked under my radar.

As a side question, the analyze document from stream is missing (but has a workaround), but is it planned to bring it back or take it in a new direction entirely?
