### ISSUE TITLE
Unable to set includePending=true for GetCertificatesAsync in KeyVaultClient

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/azure-sdk-for-net#4144]
Is there any good reason I am unable to pass includePending=true fot GetCertificatesAsync? How am I supposed to query for pending certificate?

I am trying to implement a utility that scans for pending (or expiring) certificate requests and fullfill them using the Let's Encrypt CA.

**Comment by jsquire** [comment]
Closing this out as this references a legacy version of the KeyVault library and there has been no recent engagement.  Please feel free to reopen or file a new issue if this remains a problem with the current version of the library.
