### ISSUE TITLE
Is .Net6 not supported by Azure.ResourceMabager.DataFactory ?

### ISSUE THREAD

**Issue by ons-cherif** [Azure/azure-sdk-for-net#41492]
### Library name and version

Azure.ResourceMabager.DataFactory 1.0.0-beta.5

### Query/Question

Hello,

Currently, we are using Microsoft.Azure.Management.DataFactory version 9.3.0. However, this version has been marked as deprecated, and therefore, we need to switch to Azure.ResourceManager.DataFactory instead. The issue we are facing is that our projects are based on .NET6, and according to the new NuGet documentation, this version is not yet supported.

My question is, when will Azure.ResourceManager.DataFactory be supported for .NET6? Additionally, what are the downsides of continuing to use the old NuGet package?

Thank you for your support.

Kind Regards,
Ons.Ch

### Environment

Hosting platform : Windows
SDK .NET Version:   8.0.100
IDE: Visual Studio 17.8.3 for Devolopement mode, but not that all our projects are on production mode

**Comment by ons-cherif** [comment]
Noted, thank you for the fast response. 
One last question, I saw that there have been many releases of this new package but still it's a beta version, is it safe enough ti use for production projects? 
Thank you.

**Comment by jsquire** [comment]
We do not recommend using beta versions in production scenarios.  

 @ArthurMa1978: Is there a timeline for the DataFactory stable release that you can share?  It seems we have a scenario here with a retired package but no GA replacement.  That seems wrong.
