### ISSUE TITLE
[QUERY]500 error when Managed Identities credential  get token

### ISSUE THREAD

**Issue by Timothy945** [Azure/azure-sdk-for-net#41521]
### Library name and version

Azure.Identity

### Query/Question

Hello
I am using Managed Identities to get token in **app service web job.** Azure cloud is China. But I got 500 error 
Does my TokenRequestContext has lost some fields for different Azure cloud?

[01/24/2024 07:44:21 > 19a5ac: INFO] ManagedIdentityCredential authentication failed: Service request failed.
[01/24/2024 07:44:21 > 19a5ac: INFO] Status: 500 (Internal Server Error)
[01/24/2024 07:44:21 > 19a5ac: INFO] 
[01/24/2024 07:44:21 > 19a5ac: INFO] Content:
[01/24/2024 07:44:21 > 19a5ac: INFO] {"statusCode":500,"message":"An unexpected error occured while fetching the AAD Token.","correlationId":"3c7c5ead-d553-4b59-a2d9-f98553ec9f4c"}

`var credential = new DefaultAzureCredential(new DefaultAzureCredentialOptions { 
    ManagedIdentityClientId = clientId,
    AuthorityHost = AzureAuthorityHosts.AzureChina
}) ;`
`AccessToken accessToken = credential.GetToken(new TokenRequestContext(new[] { "https://sts.chinacloudapi.cn"}));`

### Environment

App Services Web App ->web job 
ASP.NET 4.8

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @Timothy945 - it looks like you are passing `https://sts.chinacloudapi.cn` as the scope. Is that intentional?

**Comment by Timothy945** [comment]
> Hi @Timothy945 - it looks like you are passing `https://sts.chinacloudapi.cn` as the scope. Is that intentional?

Hi @christothes 
I am not sure. I used scope "https://sts.windows.net" in global , and it works.
I followed the China developer guide  and change the scope to that.
https://learn.microsoft.com/zh-cn/azure/china/resources-developer-guide#next-steps

**Comment by Timothy945** [comment]
change scope to api://***
