### ISSUE TITLE
Missing the scale of the MaxSize

### ISSUE THREAD

**Issue by cfelstead** [Azure/azure-sdk-for-net#41532]
### Type of issue

Missing information

### Description

The page reads "Specifies the size of the new Page Blob." but does not clarify the scale.
Bytes? Megabytes? etc ....

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/azure.storage.files.shares.models.sharefileopenwriteoptions.maxsize?view=azure-dotnet

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Files.Shares.Models/ShareFileOpenWriteOptions.xml

### Document Version Independent Id

e94826a5-c77d-1775-373b-3166cfae6a64

### Article author

@azure-sdk

### Metadata

* ID: 5446a5b3-dc6e-da0d-6d74-ddbf37274845 
* Service: **azure**

**Comment by seanmcc-msft** [comment]
Hi @cfelstead, thanks for reporting this, I have created a PR to address - https://github.com/Azure/azure-sdk-for-net/pull/41686
