### ISSUE TITLE
[QUERY] Migrating to Azure.ResourceManager.Automation from Microsoft.Azure.Management.Automation

### ISSUE THREAD

**Issue by Shubhrmcf-07** [Azure/azure-sdk-for-net#41572]
### Library name and version

Azure.ResourceManager.Automation

### Query/Question

We have a GA product which has been using the Azure Automation library for process automation for customers. However, the existing library was deprecated (Microsoft.Azure.Management.Automation) and we are in process of migrating to the new one and facing breaking changes which would be not ideal for our scenario.

A couple of changes to be addressed : 

1. The default identifier in this case has switched to job name from job id, which we are currently using and would like to keep it that way and not add any additional input parameters.
2. The runbook properties is set to readonly in the ARM library, which would be required to be set by the customer on their particular runbook job.
3. The client connection properties have changed (although we have a workaround for that without breaking any changes, so that is not much of an issue)

Need assistance with further steps and how we can have a seamless migration in such a scenario.

**Comment by Shubhrmcf-07** [comment]
Currently working with Logic Apps team using the Microsoft.Azure.Management.Automation library for customer communication to process automation feature.

**Comment by Shubhrmcf-07** [comment]
We are using the previous library for almost 2 years and were not made aware of the changes/deprecation

**Comment by jsquire** [comment]
Hi @Shubhrmcf-07.  Thank you for reaching out and we regret that you're experiencing difficulties.   I've answered some of your initial questions and have routed this to the team member best able to assist with those remaining.   In addition, a migration guide for moving from the legacy management packages to the current generation can be found [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/resourcemanager/Azure.ResourceManager/docs/MigrationGuide.md).

> We are using the previous library for almost 2 years and were not made aware of the changes/deprecation

Retirements were announced in [March of 2022](https://azure.microsoft.com/updates/support-for-azure-sdk-libraries-that-do-not-conform-to-our-current-azure-sdk-guidelines-will-be-retired-as-of-31-march-2023/) following the standard Azure lifecycle process.   The lifecycle of individual packages can be tracked on the [Azure SDK Deprecated Releases page](https://azure.github.io/azure-sdk/releases/deprecated/index.html).

> The runbook properties is set to readonly in the ARM library, which would be required to be set by the customer on their particular runbook job.

As a convention across libraries in the Azure SDK, collection types for models are intentionally read-only.   Their value can be set by mutating the existing collection.  This can be done by either adding members after the object has been constructed or using C#'s initializer syntax as part of construction.   

For example:

```csharp
// Accessing the set
var example = new SomeModel();

foreach (var thing in myThings)
{
    example.Things.Add(thing);
}

// Using list initializers
var example = new SomeModel
{
    Things = { thing1, thing2 }
}
```

**Comment by Shubhrmcf-07** [comment]
Hey Jesse, 

Thanks a ton for the response. This was super helpful. Would you be able to redirect me to the team member assigned for assistance who I can discuss with? As we would need the help with some specific scenarios as well.

**Comment by ArthurMa1978** [comment]
Hey @Shubhrmcf-07 for migration we can chat more details in teams.
