### ISSUE TITLE
[Logic App + Analyze Document for PreBuilt] Timeout

### ISSUE THREAD

**Issue by mehmetaltuntas** [Azure/azure-sdk-for-net#41576]
### Library name and version

Logic App Connector - Analyzer Document (v3.x API) 1

### Query/Question

I am having a logic app workflow that communicates with Form Recognizer via Analyze Document for Prebuilt connector. It basically reads from a blob and uses an existing prebuilt-read model and supposedly generates a analyze result to a blob. The file is about 80MB. Assuming that the analyze process takes some time. The connector is waiting for the completion. This causes a time out. 
What is the best way to implement Form Recognizer connector which handles the async call which requires the completion on the other side so that the result gets inserted into an output blob?
Thanks

**Comment by jsquire** [comment]
Hi @mehmetaltuntas.  Thank you for reaching out and we regret that you're experiencing difficulties.  Unfortunately, this is not an issue the maintainers of the Azure SDK can assist with.  Logic app connectors are part of the Logic Apps service offering and are not Azure SDK packages.  Your best path forward would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request).

I'm going to close this out;  if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.
