### ISSUE TITLE
[QUERY] How to use AddServiceBusAdministrationClientWithNamespace()

### ISSUE THREAD

**Issue by That-Rationalist** [Azure/azure-sdk-for-net#41585]
### Library name and version

Azure.Messaging.ServiceBus v7.17.2

### Query/Question

I have an Azure Function, and all I want is just to register an instance of ServiceBusAdministrationClient in the DI container so that my class can access it as a Singleton. In its Startup.cs, I have the following block:

```
public class Startup : FunctionStartup
{
  public override void Configure(IFunctionsHostBuilder builder)
  {
    RegisterDep(builder.Services);
  }

  private static void RegisterDep(IServiceCollection services)
  {
    services.AddServiceBusAdministrationClientWithNamespace()
  }
  
}
```

I thought it would be like this but it does not work. I also tried calling in on builder. There is zero document on how to use it.

Thank you.

### Environment

Windows 10, Visual Studio 17.7.7

**Comment by That-Rationalist** [comment]
Please note that I am aware that I can achieve it by coding like below:

services.AddSingleton(sp => { return new ServiceBusAdministrationClient("namespace", new DefaultAzureCredential()) });

But I am curious about the purpose of AddServiceBusAdministrationClientWithNamespace.

**Comment by jsquire** [comment]
Hi @That-Rationalist.  Thank you for reaching out and we regret that you're experiencing difficulties.   The extension `AddServiceBusAdministrationClientWithNamespace` is used to register a `ServiceBusAdministrationClient` with the `AzureClientFactory` that will pair it with the default credential configured globally for Azure clients.   For example:

```csharp
public void ConfigureServices(IServiceCollection services)
 {
     services.AddAzureClients(builder =>
     {
         // This will register the ServiceBusAdministrationClient using an Azure Identity credential.
         builder.AddServiceBusAdministrationClientWithNamespace("<< YOUR NAMESPACE >>.servicebus.windows.net");

         // By default, DefaultAzureCredential is used, which is likely desired for most
         // scenarios. If you need to restrict to a specific credential instance, you could
         // register that instance as the default credential instead.
         builder.UseCredential(new ManagedIdentityCredential());
     });

     // Register other services, controllers, and other infrastructure.
 }
```

The article [Dependency injection with the Azure SDK for .NET](https://learn.microsoft.com/dotnet/azure/sdk/dependency-injection?tabs=web-app-builder) goes into detail, with examples for a number of scenarios.   The [Service Bus client library overview](https://learn.microsoft.com/dotnet/azure/sdk/dependency-injection?tabs=web-app-builder provides additional examples specifically for Service Bus clients and is the source for the example that I included above.
