### ISSUE TITLE
[QUERY] How to setup User Managed Identity on SMB File Share  (getting 403 ATM)

### ISSUE THREAD

**Issue by giobb** [Azure/azure-sdk-for-net#41580]
### Library name and version

Azure.Identity 1.10.4, Azure.Storage.Files.Share 12.17.1

### Query/Question

Hi. We have an Azure function that writes to a File Share on SMB mounted in a VM.  We get 403 on **ShareDirectoryClient.Create(string directory)** when using User Managed Identity. 

We instantiate **ShareClient** object using boilerplate codes

![image](https://github.com/Azure/azure-sdk-for-net/assets/15137038/c360bb71-1603-43a1-8c32-30134d944ace)

Ultimately, we want to write to the file share and it's in our call to ShareDirectory.Client where we get the 403.

![image](https://github.com/Azure/azure-sdk-for-net/assets/15137038/65abdd85-1ec3-4403-ad67-4cb53ab65a93)

![image](https://github.com/Azure/azure-sdk-for-net/assets/15137038/039a6bed-0246-4ac6-935c-188e4d13350e)

We have verified that the correct managed identity id is used (we use same for our Key Vault and that works). It has the following permissions 

![image](https://github.com/Azure/azure-sdk-for-net/assets/15137038/bffb7ff4-d65a-4553-a859-0366add80e0a)

What did we miss?

### Environment

PROD

**Comment by seanmcc-msft** [comment]
@giobb, unfortunately OAuth does not work with Service-level and most Share-level operations in the Files service today - https://learn.microsoft.com/en-us/rest/api/storageservices/authorize-with-azure-active-directory#permissions-for-file-service-operations

The good news is full OAuth support (i.e. all operations will be supported) is coming to the Files service, and should become available later this year.
