### ISSUE TITLE
How to remote debug Azure Web app running more than one instance

### ISSUE THREAD

**Issue by DebolaA** [Azure/azure-sdk-for-net#4158]
i need help to remote debugging my azure web application. i also read this article

https://azure.microsoft.com/en-us/blog/introduction-to-remote-debugging-on-azure-web-sites-part-3-multi-instance-environment-and-git/

but it has not helped.

i need to debug my code to confirm that redis-cache scale out implementation works. i tried to debug with one instance and it worked fine but when i scaled up my application to 10 instances and tried to remote debug...it fails to attach debugger and i get this error message

![2](https://user-images.githubusercontent.com/35138680/37833050-411bfcd2-2ea2-11e8-88f6-036d21db498b.png)

any new article link? thank you

**Comment by shahabhijeet** [comment]
@DebolaA this is a repo for reporting issue for Azure .NET SDKs.
You can report this issue for VS/Azure VS tools over at this location
https://developercommunity.visualstudio.com/
