### ISSUE TITLE
How am i supposed to moq response that return DocumentTable?

### ISSUE THREAD

**Issue by b93rn** [Azure/azure-sdk-for-net#41617]
### Library name and version

azure.ai.formrecognizer: 4.1.0

### Query/Question

How are we supposed to moq responses form the client when there are no public constructors for objects like DocumentTable and DocumentTableCell?

**Comment by jsquire** [comment]
Hi @b93rn .  Thank you for your feedback.   Support for mocking and unit testing is one of the core goals of the new Azure SDKs, and the details of the approach that we use are discussed in the [Azure SDK Design Guidelines](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-mocking).   More in-depth discussion and examples can be found in [Unit testing and mocking with the Azure SDK for .NET](https://learn.microsoft.com/dotnet/azure/sdk/unit-testing-mocking?tabs=csharp).

For model types that are returned by service operations, a factory class exists to enable creating them for testing.  In the case of FormRecognizer, the [DocumentAnalysisModelFactory](https://learn.microsoft.com/dotnet/api/azure.ai.formrecognizer.documentanalysis.documentanalysismodelfactory?view=azure-dotnet) would be the place to look.   For example, the `DocumentTableCell` model that you've asked about can be created using [this method](https://learn.microsoft.com/dotnet/api/azure.ai.formrecognizer.documentanalysis.documentanalysismodelfactory.documenttablecell?view=azure-dotnet#azure-ai-formrecognizer-documentanalysis-documentanalysismodelfactory-documenttablecell(azure-ai-formrecognizer-documentanalysis-documenttablecellkind-system-int32-system-int32-system-int32-system-int32-system-string-system-collections-generic-ienumerable((azure-ai-formrecognizer-documentanalysis-boundingregion))-system-collections-generic-ienumerable((azure-ai-formrecognizer-documentanalysis-documentspan)))).   There are also additional methods available to create the result types returned, such as [AnalyzeResult](https://learn.microsoft.com/dotnet/api/azure.ai.formrecognizer.documentanalysis.documentanalysismodelfactory.analyzeresult?view=azure-dotnet#azure-ai-formrecognizer-documentanalysis-documentanalysismodelfactory-analyzeresult(system-string-system-string-system-collections-generic-ienumerable((azure-ai-formrecognizer-documentanalysis-documentpage))-system-collections-generic-ienumerable((azure-ai-formrecognizer-documentanalysis-documenttable))-system-collections-generic-ienumerable((azure-ai-formrecognizer-documentanalysis-documentkeyvaluepair))-system-collections-generic-ienumerable((azure-ai-formrecognizer-documentanalysis-documentstyle))-system-collections-generic-ienumerable((azure-ai-formrecognizer-documentanalysis-documentlanguage))-system-collections-generic-ienumerable((azure-ai-formrecognizer-documentanalysis-analyzeddocument))-system-collections-generic-ienumerable((azure-ai-formrecognizer-documentanalysis-documentparagraph))-system-string)).

**Comment by b93rn** [comment]
Thanks for the quick and clear response! My bad, i completely missed those factory methods!
