### ISSUE TITLE
Container Registry Readme Issue

### ISSUE THREAD

**Issue by zhangjiale-64** [Azure/azure-sdk-for-net#41639]
1.
**Section** [link](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/containerregistry/Azure.Containers.ContainerRegistry/README.md#registry-operations):

![image](https://github.com/Azure/azure-sdk-for-net/assets/141405558/2d3d182f-862f-4252-8fe7-4701ebe89701)

**Reason**:
Misspelled word.

**Suggestion**:
Change 'secion ' to 'section'.

2.
**Section** [link](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/containerregistry/Azure.Containers.ContainerRegistry/README.md#list-repositories-asynchronously):
![image](https://github.com/Azure/azure-sdk-for-net/assets/141405558/da08bf61-88be-47ed-a7e2-2febc84d7f1f)
**Reason**:
Case issue.

**Suggestion**:
Change 'Task' to 'task'.

@scottaddie , @jsquire , @sandeep-sen , @Mohit-Chakraborty and @annelo-msft to notification.

**Comment by pallavit** [comment]
This has been fixed as part of https://github.com/Azure/azure-sdk-for-net/pull/41689
