### ISSUE TITLE
Can't use "await blobBatchClient.SetBlobsAccessTierAsync(blobUris: uris, accessTier: AccessTier.Cool)" to set million of files in one task

### ISSUE THREAD

**Issue by huanghaiqing1** [Azure/azure-sdk-for-net#41634]
### Type of issue

Code doesn't work

### Description

Hello, I'm follwoing KB: https://docs.azure.cn/zh-cn/storage/blobs/archive-blob?tabs=azure-cli#use-lifecycle-management-policies-to-archive-blobs to set a folders with more than 2000 files in Azure one storage account's one container from hot tier to cool tier.  The main Task[Task BulkArchiveContainerContents] is as belwo shows like KB provided. I found the function code is ok for small numbers of files. But throw "Invalid response/Invalid response/Invalid response" when I adjust operation files numbers to thounds level.  Below is the error detail from VSC during debug. And I'm sure the error is thrown when execute code: "await blobBatchClient.SetBlobsAccessTierAsync(blobUris: uris, accessTier: AccessTier.Cool);". Please guide me any additional codes should be added, when handle mass data. Thanks.

###################################################################
Exception thrown: 'Azure.RequestFailedException' in System.Private.CoreLib.dll
Invalid response
Status: 202 (Accepted)

Headers:
Transfer-Encoding: chunked
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 6231fbf8-201e-002a-805b-523b7a000000
x-ms-version: 2023-11-03
x-ms-client-request-id: b1f2b32e-a61b-4c85-bcc0-5b159b135f63
Date: Mon, 29 Jan 2024 02:31:12 GMT
Content-Type: multipart/mixed; boundary=batchresponse_e33efffd-71c3-48b7-ae85-ab45e07db368
###################################################################

static async Task BulkArchiveContainerContents(string accountName, string containerName)
{
    string containerUri = string.Format("https://{0}.blob.core.chinacloudapi.cn/{1}",
                                    accountName,
                                    containerName);

    // Get container client, using Azure AD credentials.
    BlobUriBuilder containerUriBuilder = new BlobUriBuilder(new Uri(containerUri));
    BlobContainerClient blobContainerClient = new BlobContainerClient(containerUriBuilder.ToUri(), 
                                                                      new DefaultAzureCredential());

    // Get URIs for blobs in this container and add to stack.
    var uris = new Stack<Uri>();
    await foreach (var item in blobContainerClient.GetBlobsAsync())
    {
        uris.Push(blobContainerClient.GetBlobClient(item.Name).Uri);
    }

    // Get the blob batch client.
    BlobBatchClient blobBatchClient = blobContainerClient.GetBlobBatchClient();

    try
    {
        // Perform the bulk operation to archive blobs.
        await blobBatchClient.SetBlobsAccessTierAsync(blobUris: uris, accessTier: AccessTier.Archive);
    }
    catch (RequestFailedException e)
    {
        Console.WriteLine(e.Message);
    }
}

[在此处输入反馈]

### Page URL

https://learn.microsoft.com/zh-cn/dotnet/api/azure.storage.blobs.specialized.blobbatchclient.setblobsaccesstierasync?view=azure-dotnet

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Blobs.Specialized/BlobBatchClient.xml

### Document Version Independent Id

92778d92-755e-fb19-d471-181de585eef5

### Article author

@azure-sdk

### Metadata

* ID: 9a0817cd-3691-3e1d-b1e9-a9403aa77e7b 
* Service: **azure**

**Comment by huanghaiqing1** [comment]
I read related KBs and says  it's possiblely triggered by "Each batch request supports a maximum of 256 subrequests". I'm not good at .net. So in my above source code, how should I setup a loop to handly those blobs more than 256 in URLs ?

**Comment by seanmcc-msft** [comment]
Blob Batch requests are limited to 256 sub-requests per batch request - https://learn.microsoft.com/en-us/rest/api/storageservices/blob-batch?tabs=microsoft-entra-id#request-body

Here is our code sample for list blobs - https://github.com/Azure/azure-sdk-for-net/blob/0260e01269caebd492527aaba2b3a3bde2d60b62/sdk/storage/Azure.Storage.Blobs/samples/Sample01b_HelloWorldAsync.cs#L124

As a workaround, you could list the blobs in question with a running counter.  When you reach 256 blobs, you can form a blob batch request and send it to the service.
