### ISSUE TITLE
[BUG] Additional tags recorded by `OpenTelemetry.Trace.ActivityExtensions.RecordException` are discarded by Application Insights

### ISSUE THREAD

**Issue by KennethHoff** [Azure/azure-sdk-for-net#41643]
### Library name and version

Azure.Monitor.OpenTelemetry.AspNetCore 1.0.0

### Describe the bug

Using the [RecordException](https://github.com/open-telemetry/opentelemetry-dotnet/blob/0b9cf42e9af668fe6d3af86254f9758c7c821f5e/src/OpenTelemetry.Api/Trace/ActivityExtensions.cs#L81) extension method in the [OpenTelemetry](https://www.nuget.org/packages/OpenTelemetry) NuGet package, I manually add a few custom tags, like the following:

```c#
activity?.RecordException(ex, new TagList
{
	{ "attachment.name", attachment.FileName },
	{ "attachment.size", attachment.Length },
	{ "attachment.contentType", attachment.ContentType },
});
```

I can see these tags in the [Console Exporter](https://www.nuget.org/packages/OpenTelemetry.Exporter.Console):

```
Activity.Events:
    Exception [29/01/2024 14:56:46 +00:00]
        attachment.name: balloon.jpg
        attachment.size: 16836
        attachment.contentType: image/jpeg
    exception [29/01/2024 14:56:46 +00:00]
        exception.type: Microsoft.Kiota.Abstractions.ApiException
        exception.stacktrace: Microsoft.Kiota.Abstractions.ApiException: Exception of type 'Microsoft.Kiota.Abstractions.ApiException' was thrown.
   at [[REDACTED]]
        exception.message: Exception of type 'Microsoft.Kiota.Abstractions.ApiException' was thrown.
    Exception [29/01/2024 14:56:46 +00:00]
        attachment.name: Avtale.pdf
        attachment.size: 3028
        attachment.contentType: application/pdf
    exception [29/01/2024 14:56:46 +00:00]
        exception.type: Microsoft.Kiota.Abstractions.ApiException
        exception.stacktrace: Microsoft.Kiota.Abstractions.ApiException: Exception of type 'Microsoft.Kiota.Abstractions.ApiException' was thrown.
   at [[REDACTED]]
        exception.message: Exception of type 'Microsoft.Kiota.Abstractions.ApiException' was thrown.
    Exception [29/01/2024 14:56:47 +00:00]
        attachment.name: file-sample_1MB.docx
        attachment.size: 1026736
        attachment.contentType: application/vnd.openxmlformats-officedocument.wordprocessingml.document
    exception [29/01/2024 14:56:47 +00:00]
        exception.type: Microsoft.Kiota.Abstractions.ApiException
        exception.stacktrace: Microsoft.Kiota.Abstractions.ApiException: Exception of type 'Microsoft.Kiota.Abstractions.ApiException' was thrown.
   at [[REDACTED]]
        exception.message: Exception of type 'Microsoft.Kiota.Abstractions.ApiException' was thrown.
Resource associated with Activity:
    telemetry.distro.name: Azure.Monitor.OpenTelemetry.AspNetCore
    telemetry.sdk.name: opentelemetry
    telemetry.sdk.language: dotnet
    telemetry.sdk.version: 1.7.0
    service.name: [[REDACTED]]
```

However, they do not show up in the Application Insights UI:

![image](https://github.com/Azure/azure-sdk-for-net/assets/17124533/bee05d17-e2d5-4b5a-803a-0f71d80c45fa)

Currently I've resorted to simply creating my own wrapper methods like this, and hiding the 1st party ones, which is not a sustainable solution.

```c#
public static void RecordException(this Activity activity, Exception ex)
{
	OpenTelemetry.Trace.ActivityExtensions.RecordException(activity, ex);
}
public static void RecordException(this Activity activity, Exception ex, in ActivityTagsCollection tags)
{
	if (tags.Count > 0)
	{
		activity.AddEvent(new ActivityEvent("Exception", tags: tags));
	}

	RecordException(activity, ex);
}
```

### Expected behavior

Custom tags should show similar to how they do for any other event (as Exceptions are defined to be a subset of `Event`):

https://opentelemetry.io/docs/specs/otel/trace/exceptions/

>An exception SHOULD be recorded as an Event on the span during which it occurred. The name of the event MUST be "exception".

https://opentelemetry.io/docs/specs/otel/trace/api/#record-exception

> Note: RecordException may be seen as a variant of AddEvent with additional exception-specific parameters and all other parameters being optional (because they have defaults from the exception semantic convention).

```c#
activity?.AddEvent(new ActivityEvent("Exception", tags: new ActivityTagsCollection
{
	["attachment.name"] = attachment.FileName,
	["attachment.size"] = attachment.Length,
	["attachment.contentType"] = attachment.ContentType,
}));
```

![image](https://github.com/Azure/azure-sdk-for-net/assets/17124533/e8056a6b-8dc3-48e8-a379-195d16663c41)

### Actual behavior

There is no `Custom Properties` section on an Exception in Azure Application Insights, despite the OpenTelemetry standard saying it should be like any other event.

### Reproduction Steps

1. Set up `Azure.Monitor.OpenTelemetry.AspNetCore 1.0.0` as normal; ConnectionString, etc..
2. Install the `OpenTelemetry` and some other non-Azure exporter (for example the Console Exporter)
3. Use the `RecordException` extension method with the TagList overload.

Notice how it shows up in the Console, but nowhere to be seen on Application Insights.

**Comment by TimothyMothra** [comment]
Hi @KennethHoff, we're planning to ship a beta tomorrow. 
Don't have an ETA on our next stable release yet.
