### ISSUE TITLE
[BUG] function.json, error 500 on "filter": "RowKey eq '{Request.Query.Name}'",

### ISSUE THREAD

**Issue by slashd** [Azure/azure-sdk-for-net#41640]
### Library name and version

Azure Functions Core Tools 4.0.5455

### Describe the bug

VSCode > Azure Functions > PowerShell 7.2 > httpTrigger
In function.json add a table binding:

this works:

```json
{
  "bindings": [
    {
      "authLevel": "anonymous",
      "type": "httpTrigger",
      "direction": "in",
      "name": "Request",
      "methods": [
        "get",
        "post"
      ]
    },
    {
      "type": "http",
      "direction": "out",
      "name": "Response"
    },
    {
      "name": "HeroEntity",
      "type": "table",
      "tableName": "Hots",
      "partitionKey": "Hots",
      "filter": "RowKey eq 'Raynor'",
      "direction": "in"
    }
  ]
}
```
Error 500 when i change the filter to get the parameter from the querystring:
```json
"filter": "RowKey eq '{Request.Query.Name}'",
```

I tried it with both:
http://localhost:7071/api/GetHots?Name=Raynor
http://localhost:7071/api/GetHots

### Expected behavior

Not getting an error 500...

### Actual behavior

Error 500

### Reproduction Steps

See 'Describe the bug'

### Environment

W11, VSCode, Azure Functions, PowerShell 7.2, Azure Functions Core Tools 4.0.5455

**Comment by jsquire** [comment]
Hi @slashd.  Thank you for reaching out and we regret that you're experiencing difficulties.  Since your inquiry appears related to how the Azure Functions host processes settings, I've transferred this over to the repository where the host is maintained as [#9838](https://github.com/Azure/azure-functions-host/issues/9838).
