### ISSUE TITLE
Azure Search Service - Facing an error while creating an Azure search indexer using Active directory password authentication connection string

### ISSUE THREAD

**Issue by arunkathroju** [Azure/azure-sdk-for-net#4164]
I was trying to create an azure search indexer using active directory password authentication connection string but i was not able to create as there was an error saying "unable to load adalsql.dll (below screenshot)". Am I missing any thing here? Below is the connection string i was using.

Server=tcp:.database.windows.net,;Database=;Authentication=Active Directory Password;User ID=;Password=;Trusted_Connection=False;Encrypt=True;Connection Timeout=30;

Error : Unable to load adalsql.dll (Authentication=ActiveDirectoryPassword). Error code: 0x2. For more information, see http://go.microsoft.com/fwlink/?LinkID=513072

**Comment by brjohnstmsft** [comment]
@arunkathroju We don't support Active Directory authentication for SQL indexer at this time. Please vote on this [User Voice](https://feedback.azure.com/forums/263029-azure-search/suggestions/33595465-support-azure-active-directory-password-authentica) item to help us prioritize.

The error message is misleading and we are improving it to make the true cause of the error clear.

Closing this issue as it is not related to the Azure Search .NET SDK.
