### ISSUE TITLE
[BUG] Cannot initialize TargetTags in ContainerRegistryImportImageContent class

### ISSUE THREAD

**Issue by lbussell** [Azure/azure-sdk-for-net#41654]
### Library name and version

Azure.ResourceManager.ContainerRegistry 1.2.0

### Describe the bug

I'm trying to initialize ⁠[ContainerRegistryImportImageContent](https://github.com/Azure/azure-sdk-for-net/blob/e88d7dc05388f26c5d3b7d89bdb478c9f34e77f1/sdk/containerregistry/Azure.ResourceManager.ContainerRegistry/src/Generated/Models/ContainerRegistryImportImageContent.cs#L15) in a similar way to ⁠[the sample](https://github.com/Azure/azure-sdk-for-net/blob/e88d7dc05388f26c5d3b7d89bdb478c9f34e77f1/sdk/containerregistry/Azure.ResourceManager.ContainerRegistry/samples/Generated/Samples/Sample_ContainerRegistryResource.cs#L44-L58):

```
ContainerRegistryImportImageContent content = new(...) { TargetTags = myList }
```

Because the `TargetTags` property has no setter or init-only setter, I can't set it to anything besides an array initializer. I want to set it to my own List<string>. Am I missing something or is setting `TargetTags` to my own list not possible?

### Expected behavior

I should be able to set TargetTags to my own list of tags to import as.

### Actual behavior

```
Property or indexer 'ContainerRegistryImportImageContent.TargetTags' cannot be assigned to -- it is read only (CS0200)
```

### Reproduction Steps

Install the Azure.ResourceManager.ContainerRegistry package.

Write the following code in your IDE:

```
using System.Collections.Generic;
using Azure.ResourceManager.ContainerRegistry;

...

List<string> myList = new() { "foo", "bar" };
ContainerRegistryImportImageContent content = new(new ContainerRegistryImportSource("baz"))
{
    TargetTags = myList,
};
```

### Environment

OS: Windows 11
SDK: .NET 8.0.101
Runtime: .NET 8.0.1
IDE: VS Code with C# Dev Kit

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by lbussell** [comment]
I was able to work around this with by just adding directly to the list - not sure why I didn't think of it earlier.

```
ContainerRegistryImportImageContent content = new(new ContainerRegistryImportSource(sourceImage));
myList.ForEach(content.TargetTags.Add);
```

Please close the issue if there's no further action.
