### ISSUE TITLE
[QUERY] How to use az netappfiles account ad update in dotnet

### ISSUE THREAD

**Issue by ras-relativity** [Azure/azure-sdk-for-net#41661]
### Library name and version

Azure.ResourceManager.NetApp 1.4.2

### Query/Question

We are using azure cli to provide this functionality but would like to use the dotnet sdk. 

Running into this error: 'Property or indexer 'NetAppAccountPatch.ActiveDirectories' cannot be assigned to -- it is read only'

az cli reference:
https://learn.microsoft.com/en-us/cli/azure/netappfiles/account/ad?view=azure-cli-latest#az-netappfiles-account-ad-update

**Comment by ras-relativity** [comment]
Also I noticed NetAppAccountResource in the docs is 404
https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.netapp.netappaccountresource?view=azure-dotnet
compare to 
https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.netapp.netappaccountdata?view=azure-dotnet

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by dvbb** [comment]
Hi @ras-relativity 

Here is a complete sample of using the dotnet SDK to implement adding an active directory to the netapp account

#### Get resource group
 ```
// get your azure access token, for more details of how Azure SDK get your access token, please refer to https://learn.microsoft.com/en-us/dotnet/azure/sdk/authentication?tabs=command-line
TokenCredential cred = new DefaultAzureCredential();
// authenticate your client
ArmClient client = new ArmClient(cred);

// this example assumes you already have this ResourceGroupResource created on azure
// for more information of creating ResourceGroupResource, please refer to the document of ResourceGroupResource
string subscriptionId = "D633CC2E-722B-4AE1-B636-BBD9E4C60ED9";
string resourceGroupName = "myRG";
ResourceIdentifier resourceGroupResourceId = ResourceGroupResource.CreateResourceIdentifier(subscriptionId, resourceGroupName);
ResourceGroupResource resourceGroupResource = client.GetResourceGroupResource(resourceGroupResourceId);
```

#### Update netappAccount to connect AAD
```
// Get NetApp account(Azure NetApp Files)
var accountLro = await resourceGroupResource.GetNetAppAccounts().GetAsync("netappfiles0000");
NetAppAccountResource account = accountLro.Value;

// Update netappAccount to connect AAD
NetAppAccountPatch patch = new NetAppAccountPatch(AzureLocation.EastUS2);
foreach (var item in account.Data.ActiveDirectories)
{
    patch.ActiveDirectories.Add(item);
};
patch.ActiveDirectories.Add(new NetAppAccountActiveDirectory()
{
    Username = "user",
    Password = "Password123!",
    Domain = "testdomain",
    Dns = "192.0.2.2",
    SmbServerName = "SDKSMBSeNa"
});
await account.UpdateAsync(WaitUntil.Completed, patch);
```
