### ISSUE TITLE
[FEATURE REQ] [TestFramework] Support multipart content matching

### ISSUE THREAD

**Issue by archerzz** [Azure/azure-sdk-for-net#41674]
### Library name

Azure.Core.TestFramework

### Please describe the feature.

For HTTP multipart requests, a random boundary value will be determined for each request. That boundary is used in both `Content-Type` header and each part in the request content. See below for an example.
```
POST /upload HTTP/1.1
Content-Length: 428
Content-Type: multipart/form-data; boundary=abcde12345
--abcde12345
Content-Disposition: form-data; name="id"
Content-Type: text/plain
123e4567-e89b-12d3-a456-426655440000
--abcde12345
Content-Disposition: form-data; name="address"
Content-Type: application/json
{
  "street": "3, Garden St",
  "city": "Hillsbery, UT"
}
--abcde12345
Content-Disposition: form-data; name="profileImage "; filename="image1.png"
Content-Type: application/octet-stream
{…file content…}
--abcde12345--
```

Right now
- `Content-Type` is in the `ExcludedHeaders` list, so the boundary value won't fail matching.
- But test framework will still do exact matching for request content, which will fail for multipart requests, like below:
```
Azure.Core.TestFramework.TestRecordingMismatchException
  HResult=0x80131500
  Message=Unable to find a record for the request POST
https://xxxx-document-translator.cognitiveservices.azure.com/translator/document:translate?targetLanguage=hi&api-version=2023-11-01-preview
Header differences:
Body differences:
Request and record bodies do not match at index 2:
     request: "--eba93f1c-f9dc-4082-8"
     record:  "--38fa6b03-6458-4459-8"
```
We need to figure out a way to ignore multipart boundary in the request content.

**Comment by jsquire** [comment]
This is an issue with the Test Proxy, not the test framework.   Tracking is here:  https://github.com/Azure/azure-sdk-tools/issues/2900
