### ISSUE TITLE
[BUG] Missing AzureLocation values: ItalyNorth, PolandCentral, IsraelCentral (possibly others)

### ISSUE THREAD

**Issue by ohads-MSFT** [Azure/azure-sdk-for-net#41683]
### Library name and version

Azure.Core (latest / main branch)

### Describe the bug

Per the title, some missing locations (there might be others, might be worth a full alignment)

### Expected behavior

All Azure regions are available as an `AzureLocation`

### Actual behavior

`AzureLocation` is missing some regions

### Reproduction Steps

This won't compile: `AzureLocation.ItalyNorth` (same for the other missing locations)

**Comment by jsquire** [comment]
Hi @ohads-MSFT.  Thanks for reaching out and letting us know.  We'll take a look at the missing regions and see about getting them added.   In the meantime, `AzureLocation` is an extensible type and can used with the missing regions by creating an instance with the associated region code.   For example:

```csharp
var italyNorthLocation = new AzureLocation("italynorth");
```

**Comment by ArthurMa1978** [comment]
@jsquire, Are there any plans to include these new locations in `Azure.Core` in the future?

**Comment by jsquire** [comment]
> @jsquire, Are there any plans to include these new locations in `Azure.Core` in the future?

@ArthurMa1978:  They should be added, yes.   There's no formal plan nor scheduling; it's something that will need to be addressed as time allows.   Feel free to make the changes, if you'd like.  Otherwise, when the folks working on Core have capacity, we'll pick it up.

**Comment by jsquire** [comment]
These were added by #41835.
