### ISSUE TITLE
Azure.Messaging.EventGrid 4.22.0 stable?

### ISSUE THREAD

**Issue by axelaceax** [Azure/azure-sdk-for-net#41682]
### Library name and version

Azure.Messaging.EventGrid 4.22.0-beta.1

### Query/Question

Hi,
Inside my company we have a restriction of using beta nuget packages.
We need to make a decision based on what is the expected date of delivering a stable version after 4.22.0-beta.1 for Azure.Messaging.EventGrid.
Can you help us with some predictions of this work that you are doing?

### Environment

4.22.0-beta.1

**Comment by jsquire** [comment]
Hi @axelaceax.  Thank you for reaching out and we regret that you're experiencing difficulties.   The Event Grid service with the namespace feature set is still in beta.  Once the service promotes the feature set to stable, we will release a stable version of the `Azure.Messaging.EventGrid` package soon after.   To my knowledge, there has not yet been a public announcement of the service timeline to share.

**Comment by axelaceax** [comment]
thank you, @jsquire!
