### ISSUE TITLE
external chat that sends and receives messages from Teams channel with Azure Communication Services

### ISSUE THREAD

**Issue by snecro** [Azure/azure-sdk-for-net#41703]
### Library name and version

Azure communication chat

### Query/Question

Hello,
I have an external application that tries to communicate through a Teams channel. I am using Azure Communication Services.
I know that we can connect to a Teams meeting as an external user and my question is that are we able to connect (send and write messages) as an external app via Teams chat? I generated a token for a Teams user and I tried to use that token when I created chatClient. My message when trying to send a message from an external app is:

RestError: {

  "CommunicationError": {

    "Code": "Forbidden",

    "Details": []

  } 
if someone can give me some advice on how I should procced I would appreciate it. Thank you in advance!

**Comment by jpeng-ms** [comment]
Hi @snecro we currently do not support send and receive messages from Teams channels. We welcome you to raise a feature request here:  https://feedback.azure.com/d365community/forum/81ff6d2b-0c25-ec11-b6e6-000d3a4f0858


I will be closing off this issue for now, but please reopen it if you have more questions.
