### ISSUE TITLE
Microsoft.Azure.Management.AppService - ListHybridConnection methods in WebAppsOperations return single object but should return Page<> for the list

### ISSUE THREAD

**Issue by nboettcher** [Azure/azure-sdk-for-net#4170]
I am attempting to use the ListHybridConnectionsWithHttpMessagesAsync in the WebAppsOperations class in Microsoft.Azure.Management.AppService.Fluent library. The method returns a single HybridConnectionInner object, however since this is a List method, the REST API call returns a list of objects that should be returned in a Page<HybridConnectionInner> object.

**Comment by shahabhijeet** [comment]
@nboettcher can you open an issue in the below repo
https://github.com/Azure/azure-libraries-for-net for fluent related issues.
