### ISSUE TITLE
Support pagination for CostManagement Query Usage

### ISSUE THREAD

**Issue by GitHubAre** [Azure/azure-sdk-for-net#41710]
### Library name

Azure.ResourceManager.CostManagement

### Please describe the feature.

RestApi [link](https://learn.microsoft.com/en-us/rest/api/cost-management/query/usage?view=rest-cost-management-2023-11-01) supports Skip Token, sdk UsageQueryAsync method is not using it.

Could you please add support for it?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi @GitHubAre , As the docuemnt shows, only the response nextLink contains skip token, the request self doesn't have that.

**Comment by GitHubAre** [comment]
Hello @HarveyLink , its not documented, but it supports it.
I have already implemented it locally weeks ago and it works fine.
<img width="766" alt="image" src="https://github.com/Azure/azure-sdk-for-net/assets/17234860/b375de1e-6afb-4f80-bba3-3514b089b3c0">

Please re-open this ticket.

**Comment by NickCraver** [comment]
@HarveyLink Shouldn't the result in the API be pageable here? I was migrating our team over to `Azure.ResourceManager.CostManagement` and I don't see proper paging support like other Azure .NET SDKs would have. I recommend re-opening as there's still a gap here. We shouldn't expect people to manually query across `.NextLink` and constructing requests.

I would expect the normal https://learn.microsoft.com/en-us/dotnet/azure/sdk/pagination behavior to be involved here.
