### ISSUE TITLE
[FEATURE REQ] Support SDK generation in CI pipeline for the services migrated from Swagger to TypeSpec

### ISSUE THREAD

**Issue by raych1** [Azure/azure-sdk-for-net#41746]
### Library name

Automation scripts

## Problem
If an existing service converts the Swagger specs to TypeSpec and creates a spec PR in Azure/azure-rest-api-specs repository, the SDK automation pipeline for DotNet will end up with the following error.
```
08:49:42.149 cmdout 	[Invoke-GenerateAndBuildV2.ps1] /home/cloudtest/.nuget/packages/microsoft.azure.autorest.csharp/3.0.0-beta.20240129.1/buildMultiTargeting/Microsoft.Azure.AutoRest.CSharp.targets(56,5): error : Cannot define both /mnt/vss/_work/1/s/azure-sdk-for-net/sdk/schemaregistry/Azure.Data.SchemaRegistry/src/autorest.md and /mnt/vss/_work/1/s/azure-sdk-for-net/sdk/schemaregistry/Azure.Data.SchemaRegistry/src/../tsp-location.yaml in the same project [/mnt/vss/_work/1/s/azure-sdk-for-net/sdk/schemaregistry/Azure.Data.SchemaRegistry/src/Azure.Data.SchemaRegistry.csproj]
08:49:42.151 cmdout 	[Invoke-GenerateAndBuildV2.ps1] Build FAILED.
08:49:42.152 cmdout 	[Invoke-GenerateAndBuildV2.ps1] /home/cloudtest/.nuget/packages/microsoft.azure.autorest.csharp/3.0.0-beta.20240129.1/buildMultiTargeting/Microsoft.Azure.AutoRest.CSharp.targets(56,5): `error : Cannot define both /mnt/vss/_work/1/s/azure-sdk-for-net/sdk/schemaregistry/Azure.Data.SchemaRegistry/src/autorest.md and /mnt/vss/_work/1/s/azure-sdk-for-net/sdk/schemaregistry/Azure.Data.SchemaRegistry/src/../tsp-location.yaml in the same project` [/mnt/vss/_work/1/s/azure-sdk-for-net/sdk/schemaregistry/Azure.Data.SchemaRegistry/src/Azure.Data.SchemaRegistry.csproj]
08:49:42.152 cmdout 	[Invoke-GenerateAndBuildV2.ps1]     0 Warning(s)
08:49:42.152 cmdout 	[Invoke-GenerateAndBuildV2.ps1]     1 Error(s)
```
## Feature Request
SDK automation pipeline should support this scenario in the spec PR pipeline.

As this issue only happens for DotNet repository, we propose adding support for it in DotNet automation side rather than the SDK automation framework side.

## Proposed Solutions: 

1. Add a call back function, such as `Delete-{Language}-SwaggerConfig`, to delete the `autorest.md`. Call this function in [TypeSpec-Project-Process.ps1](https://github.com/Azure/azure-sdk-for-net/blob/main/eng/common/scripts/TypeSpec-Project-Process.ps1) before creating/modifying the `tsp-location.yaml` file. 
Pros: it is reasonable to have this support in the `Process` script and `Language-Settings.ps1`
**Cons:** this effort will be abandoned when adopting `tsp-client`.

2. Add support in [Invoke-GenerateAndBuildV2.ps1](https://github.com/Azure/azure-sdk-for-net/blob/main/eng/scripts/Invoke-GenerateAndBuildV2.ps1) to delete `autorest.md` before calling `TypeSpec-Project-Process.ps1`. 
Pros: it doesn't depend on the `TypeSpec-Project-Process.ps1` script, and it will be easy to adopt the `tsp-client` in the future.
**Cons:** it needs to parse `tsp-config.yaml` to understand the SDK project folder.

3. add support in `tsp-client`. I haven't looked into the implementation detail.

Here're some spec PRs which have this problem.
- https://github.com/Azure/azure-rest-api-specs/pull/25168
- https://github.com/Azure/azure-rest-api-specs/pull/27405

@weshaggard @m-nash
@chunyu3 @lirenhe

**Comment by weshaggard** [comment]
Given we want to move away from the PS1 scripts and use tsp-client can you please look at options to fix it there?

If this is only .NET issue then another thought is to remove the autorest.md and tsp-location.yaml check and always prefer the tsp-location if it is present. Maybe just make it a warning so someone knows to clean-up the autorest.md.
