### ISSUE TITLE
[QUERY] Asynchronous operations failing unexpectedly

### ISSUE THREAD

**Issue by vthiebaut10** [Azure/azure-sdk-for-net#41759]
### Library name and version

Azure.ResourceManager.Cdn

### Query/Question

I have been working with Azure.ResourceManager.Cdn library to manage my CDN resources. Until now, all the operations were working with no issues. Now asynchronous operations are failing with no exception being thrown.

For example:
```
        static public async Task CreateCustomDomainAsync(ProfileResource profile, string hostname)
        {
            FrontDoorCustomDomainCollection customDomains = profile.GetFrontDoorCustomDomains();
            FrontDoorCustomDomainData data = new FrontDoorCustomDomainData();
            data.HostName = hostname;

            var lro = await customDomains.CreateOrUpdateAsync(Azure.WaitUntil.Started, hostname.Replace('.', '-'), data);

            FrontDoorCustomDomainResource result = lro.Value;
            FrontDoorCustomDomainData resourceData = result.Data;
            Console.WriteLine($"Succeeded on id: {resourceData.Id}");
        }
```

This code used to work, but now the process exits immediately once the "CreateOrUpdateAsync" method gets called. However, when I switch it to the non-async version of the method "CreateOrUpdate" the operation succeeds, so it can't be an issue with the configured identity. 
It's weird that the process exits with code 0 and no exceptions are thrown. I tested that the same thing happens with other methods in the same library.

Is this a known behavior? Is there any additional info that I can provide for debugging?

### Environment

OS: Windows 11
IDE: Visual Studio 2022 version 17.8.6
dotnet --info:
```
.NET SDK:
 Version:           8.0.101
 Commit:            6eceda187b
 Workload version:  8.0.100-manifests.825c015e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.101\

.NET workloads installed:
 Workload version: 8.0.100-manifests.825c015e
There are no installed workloads to display.

Host:
  Version:      8.0.1
  Architecture: x64
  Commit:       bf5e279d92

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  6.0.321 [C:\Program Files\dotnet\sdk]
  8.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found
```

**Comment by vthiebaut10** [comment]
Just a note, this also happens with other async operations from other packages, like Azure.ResourceManager.Compute", so I think it might be something that got changed in my own system that is causing this. But I have no idea what could be.

**Comment by jsquire** [comment]
Hi @vthiebaut10.  Thank you for reaching out and we regret that you're experiencing difficulties.  We're not seeing failures in our test suite related to async calls nor was I able to reproduce the behavior that you're describing in stand-alone attempt.  As you've noted this behavior with other packages, I don't believe that this is related to the Azure SDK packages.  If you feel otherwise, please share a small, self-contained repro that we can use to investigate and unresolve this issue.
