### ISSUE TITLE
[BUG] Azure.Storage.Blobs SDK considers &spr=http,https as invalid SasProtocol

### ISSUE THREAD

**Issue by puneetg1983** [Azure/azure-sdk-for-net#41789]
### Library name and version

Azure.Storage.Blobs `12.19.1`

### Describe the bug

We recently migrated from from “WindowsAzure.Storage” to Azure.Storage.Blobs and we noticed that our preconfigured Connection strings that had spr parameter set to `http,https` failed to be recognized as an invalid string.

The exception that we receive is 

```
Invalid SasProtocol value
Parameter name: s

   at Azure.Storage.Sas.Azure.Storage.Common1377.SasExtensions.ParseProtocol(String s)
   at Azure.Storage.Sas.SasQueryParameters..ctor(IDictionary`2 values)
   at Azure.Storage.Blobs.BlobUriBuilder..ctor(Uri uri, Boolean trimBlobNameSlashes)
   at Azure.Storage.Blobs.BlobContainerClient.GetBlobClient(String blobName)
```

Issue doesn't happen if we use `https,http` 

### Expected behavior

spr=http,https is a valid protocol so the library should handle it

### Actual behavior

System.ArgumentOutOfRangeException 
Invalid SasProtocol value Parameter name: s

### Reproduction Steps

Create a SAS URI with spr=http,https and try to use it with the below code and you should see 
**System.ArgumentOutOfRangeException - Invalid SasProtocol value Parameter name: s**
```
var newContainerClient = new BlobContainerClient(new Uri(accountSasUri));
BlobClient blobClient = containerClient.GetBlobClient(destinationFilePath);

// Open the file and upload it to Azure Storage
using (FileStream fs = File.OpenRead(sourceFilePath))
{
    await blobClient.UploadAsync(fs, true, cancellationToken);
    fs.Close();
}
```

The bug is happening at https://github.com/Azure/azure-sdk-for-net/blob/ca54f4adf87f8c8cefc004ef9f7071c1c009fe8f/sdk/storage/Azure.Storage.Common/src/Shared/SasExtensions.cs#L114 where it is checking for existence of HttpsAndHttpName (which is "https,http")

### Environment

Azure AppService

**Comment by seanmcc-msft** [comment]
@puneetg1983, this was fixed by https://github.com/Azure/azure-sdk-for-net/pull/42471 and will be included in our next release.
