### ISSUE TITLE
[BUG] Azure.Messaging.ServiceBus Version 7.17.x Causing High Request Rates, Performance Issues, and Escalating Billing Costs

### ISSUE THREAD

**Issue by stani0502** [Azure/azure-sdk-for-net#41807]
### Library name and version

Azure.Messaging.ServicesBus 7.17.x

### Describe the bug

we have encountered critical issue with Azure.Messaging.ServiceBus version 7.17.x, specifically related to significantly elevated request rates and performance degradation when the required session feature is enabled. The number of requests sent to Azure Service Bus has experienced a significant surge, exceeding normal levels.

Notably, we have verified that this issue does not occur with version 7.16.2.

![image](https://github.com/Azure/azure-sdk-for-net/assets/6171313/d4f8847d-0be6-4161-ad8f-454c83e6269d)

### Expected behavior

Enabling required sessions in Azure.Messaging.ServiceBus version 7.17.x should not lead to a disproportionate increase in request rates or negatively impact the overall performance of the application. The expected behavior aligns with the stable performance observed in version 7.16.2.

### Actual behavior

-

### Reproduction Steps

-

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
@stani0502, can you clarify whether you are using the session processor or receiver?

**Comment by stani0502** [comment]
Thank you for the clarification. We are using the session processor in our application.
