### ISSUE TITLE
[BUG] `Messaging.System` attribute value is not following OTel spec

### ISSUE THREAD

**Issue by joegoldman2** [Azure/azure-sdk-for-net#41853]
### Library name and version

Azure.Messaging.ServiceBus 7.17.2 / Azure.Messaging.EventHubs 5.10.0

### Describe the bug

The value of the attribute `messaging.system` is not following the OTel [spec](https://opentelemetry.io/docs/specs/semconv/attributes-registry/messaging/) for both Azure Service Bus and Azure Event Hubs.

### Expected behavior

The value for the attribute `messaging.system` should be `azure_servicebus` for Azure Service Bus and `azure_eventhubs` for Azure Event Hubs.

### Actual behavior

The value for the attribute `messaging.system` is `servicebus` for Azure Service Bus and `eventhubs` for Azure Event Hubs.

https://github.com/Azure/azure-sdk-for-net/blob/efd289388f37be4961d069947efd7a6a30a49b7c/sdk/servicebus/Azure.Messaging.ServiceBus/src/Diagnostics/DiagnosticProperty.cs#L21

https://github.com/Azure/azure-sdk-for-net/blob/efd289388f37be4961d069947efd7a6a30a49b7c/sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Diagnostics/DiagnosticProperty.cs#L22

We may not be able to change these values directly and may have to introduce new constants, as these values are used when ActivitySource is not enabled (and we probably want to keep the retro compatibility with the old values).

https://github.com/Azure/azure-sdk-for-net/blob/efd289388f37be4961d069947efd7a6a30a49b7c/sdk/core/Azure.Core/src/Shared/MessagingClientDiagnostics.cs#L67-L83

### Reproduction Steps

1. Set the switch `Azure.Experimental.EnableActivitySource` or the env variable `AZURE_EXPERIMENTAL_ENABLE_ACTIVITY_SOURCE` to `true`.
2. Send a message to a Service Bus or Event Hubs
3. Use a `ActivityListener` or the OpenTelemetry SDK to monitor the activity.

### Environment

.NET 8

**Comment by jsquire** [comment]
//cc: @lmolkova

**Comment by jsquire** [comment]
Hi @joegoldman2.  Thanks for reaching out and letting us know.   Based on what seems to be the [latest version of the page](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/attributes-registry/messaging.md), it looks like those values were updated to match what we're using.    We'll consult with our OTel experts and, if needed, make the adjustment.

**Comment by joegoldman2** [comment]
According to this recent PR open-telemetry/semantic-conventions#572 (not yet published in the [doc](https://opentelemetry.io/docs/specs/semconv/messaging/messaging-spans/)), well-known values for `messaging.system` has been updated to remove `azure_` prefix. This issue can probably be closed. Thank you!
