### ISSUE TITLE
client.Resources.UpdateByIdAsync Exception

### ISSUE THREAD

**Issue by taroyutao** [Azure/azure-sdk-for-net#4185]
when i use method to update tag on notification hub：
client.Resources.UpdateByIdAsync("/subscriptions/e0fbea86-6cf2-4b2d-81e2-9c59f4f96bcb/resourceGroups/yuvmtest/providers/Microsoft.NotificationHubs/namespaces/yueast/notificationHubs/yueast", "2016-03-01", para).GetAwaiter().GetResult();

**it works well and no exception throw out.**

but when i use method to update tag on notification hub's namespace:

client.Resources.UpdateByIdAsync("/subscriptions/e0fbea86-6cf2-4b2d-81e2-9c59f4f96bcb/resourceGroups/yuvmtest/providers/Microsoft.NotificationHubs/namespaces/yueast", "2016-03-01", para).GetAwaiter().GetResult();

**tags can been updated  which confirmed on the portal but an exception was threw out.**

**exception information:**

An unhandled exception of type 'Microsoft.Rest.Azure.CloudException' occurred in System.Private.CoreLib.ni.dll

Additional information: Provisioning state is missing from long running operation.

**Environment:**
SDK Version:Microsoft.Azure.Management.ResourceManager.Fluent   1.8.0
Test on China Azure

**Comment by shahabhijeet** [comment]
@taroyutao can you open an issue in
https://github.com/Azure/azure-libraries-for-net for fluent related issues.
