### ISSUE TITLE
[QUERY] When adding a MicrosoftTeamsUserIdentifier with AddParticipant, is a 403 response expected? Can you add teams members to chat threads?

### ISSUE THREAD

**Issue by Pieeer1** [Azure/azure-sdk-for-net#41885]
### Library name and version

Azure.Communication.Chat 1.2.0 Azure.Communication.Identity 1.3.0

### Query/Question

When adding a MicrosoftTeamsUserIdentifier to a chat thread, I am continuously getting the following error:
`      
 "message": "Service request failed.\r\nStatus: 201 (Created)\r\n\r\nContent:\r\n{\"invalidParticipants\":[{\"code\":\"403\",\"message\":\"Permissions check failed ...
`
This implies that the participant is invalid? But the 201 -> 403 pipeline makes me think it is not allowed?

Additionally, When creating a chat thread with the teams user identifier, the thread gets created successfully with the CommunicationUserIdentifier's, but not the MicrosoftTeamsUserIdentifier.

I guess my main questions are as follows:

A. Can you add MicrosoftTeamsUserIdentifier to Chat Threads with CommunicationUserIdentifier's as members?
B. If yes, what permissions/scopes am I missing on my requesting user? (I have scoured the documentation for this information and was unable to find any information regarding this)

Here is an example of the code snippet used:

```CSharp
        if(user.ChatUserType == Domain.Enums.ChatUserType.Default) // this works
        {
            ChatThreadClient chatThreadClient = GetChatClient(userEmail, out _).GetChatThreadClient(chatThreadId);
            var resp = await chatThreadClient.AddParticipantAsync(new ChatParticipant(GetUserIdentifierFromEmail(user.Identity)));
        }
        else if(user.ChatUserType == Domain.Enums.ChatUserType.Teams) // this does not, 201 into 403 as shown above
        {
            ChatThreadClient chatThreadClient = GetChatClient(userEmail, out _).GetChatThreadClient(chatThreadId);
            var resp = await chatThreadClient.AddParticipantAsync(new ChatParticipant(GetTeamsIdentifierFromEmail(user.Identity)));
        }
        return user;
```

Extension methods used above:

```CSharp
    private ChatClient GetChatClient(string userEmail, out NotificationUser? notificationUser)
    {
        notificationUser = _notificationUserRepository.GetSingle(x => x.B2CEmail == userEmail);
        CommunicationUserIdentifier userIdentifier = GetUserIdentifierFromEmail(userEmail);

        AccessToken token = _communicationIdentityClient.GetToken(userIdentifier, [CommunicationTokenScope.Chat, CommunicationTokenScope.VoIP]);

        return new ChatClient(new Uri(_azureCommunicationOptions.AzureCommunicationEndpoint), new CommunicationTokenCredential(token.Token));
    }
    private CommunicationUserIdentifier GetUserIdentifierFromEmail(string userEmail)
    {
        NotificationUser? notificationUser = _notificationUserRepository.GetSingle(x => x.B2CEmail == userEmail);
        CommunicationUserIdentifier userIdentifier;
        if (notificationUser == null)
        {
            userIdentifier = _communicationIdentityClient.CreateUser().Value;
            _notificationUserRepository.AddAndSave(new NotificationUser(userEmail, userIdentifier.Id));
        }
        else
        {
            userIdentifier = new CommunicationUserIdentifier(notificationUser.AzureCommunicationIdentity);
        }
        return userIdentifier;
    }
    private CommunicationUserIdentifier GetUserIdentifierFromEmail(string userEmail)
    {
        NotificationUser? notificationUser = _notificationUserRepository.GetSingle(x => x.B2CEmail == userEmail);
        CommunicationUserIdentifier userIdentifier;
        if (notificationUser == null)
        {
            //if you get an exception here you have to have the azure environment credentials (client id | client tenant | client secret) in your env vars. run az login locally
            userIdentifier = _communicationIdentityClient.CreateUser().Value;
            _notificationUserRepository.AddAndSave(new NotificationUser(userEmail, userIdentifier.Id));
        }
        else
        {
            userIdentifier = new CommunicationUserIdentifier(notificationUser.AzureCommunicationIdentity);
        }
        return userIdentifier;
    }
    private MicrosoftTeamsUserIdentifier GetTeamsIdentifierFromEmail(string teamsEmail)
    {
        //todo - get the user object id dynamically using graph
        return new MicrosoftTeamsUserIdentifier("THIS WAS THE OBJECT ID OF THE TEAMS USER I WANT TO ADD", cloud: CommunicationCloudEnvironment.Public);
    }

```

### Environment

.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.8d38d0cc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64

**Comment by jpeng-ms** [comment]
Hi @jsquire thank you so much for your detailed message. We are enabling support for Teams anonymous user in the upcoming release and will share more about it when I have an update.

**Comment by jpeng-ms** [comment]
Hi @jsquire can you clarify the type of chat type you are trying to add Teams user to? Also what's the type of user that created this chat thread? Was it a communication user?

**Comment by jsquire** [comment]
> Hi @jsquire can you clarify the type of chat type you are trying to add Teams user to? Also what's the type of user that created this chat thread? Was it a communication user?

@jpeng-ms : Please be aware that I am not the issue author, just triage for the repository.   You'll want to address your question to @Pieeer1.

**Comment by jpeng-ms** [comment]
Sorry!

**Comment by Pieeer1** [comment]
> Hi @Pieeer1 can you clarify the type of chat thread you are trying to add Teams user to? Also what's the type of user that created this chat thread? Was it a communication user?

1. A Chat Thread created from the CreateChatThreadAsync request in the Azure.Communication.Chat Library.
2. A communication user created the thread.

**Comment by jpeng-ms** [comment]
Hi @Pieeer1, 

Thanks for clarifying. Unfortunately we currently do not support users with MicrosoftTeamsUserIdentifier when chat thread is created by a Communication User. We welcome you to raise a feature request here: https://feedback.azure.com/d365community/forum/81ff6d2b-0c25-ec11-b6e6-000d3a4f0858


For Teams interoperability, we currently only support the Communication Users to join a Teams meeting chat thread. That is:
1. Teams User needs to create a Teams meeting first
2. The Communication User needs to join the call using our Calling SDK
3. Teams User admits the Communication User to the call
4. The Communication User joins this meeting chat thread using our Chat SDK

Please note, the Communication users cannot add/remove participants and they cannot update any thread properties neither. To see the list of supported capabilities, please refer to: https://learn.microsoft.com/en-us/azure/communication-services/concepts/interop/guest/capabilities

For more information about the teams interoperability support with a Teams meeting chat, please refer to our QuickStart: https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/chat/meeting-interop?pivots=platform-windows

I hope that answers your questions and I am going to go ahead and close this issue for now. But please reopen this issue anytime if you have more questions.

Thanks
