### ISSUE TITLE
Links routes to page: content not found (404)

### ISSUE THREAD

**Issue by jd-create** [Azure/azure-sdk-for-net#41926]
### Type of issue

Typo

### Description

On this article https://learn.microsoft.com/en-us/dotnet/api/overview/azure/notification-hubs?view=azure-dotnet

2 Links give a missing page (error 404).

link title: explore the client api's (https://learn.microsoft.com/en-us/dotnet/api/overview/azure/notificationhubs/client)
link title: explore the management api's (https://learn.microsoft.com/en-us/dotnet/api/overview/azure/notificationhubs/management)

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/overview/azure/notification-hubs?view=azure-dotnet

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/latest/notification-hubs.md

### Document Version Independent Id

a02b13f4-8a6d-0505-2166-0a5959ed3e5f

### Article author

@azure-sdk

### Metadata

* ID: abe90788-b411-6601-68ef-ddeecdcc6628 
* Service: **notificationhubs**

**Comment by jsquire** [comment]
Hi @jd-create.  Thank you for reaching out and we regret that you're experiencing difficulties.  This issue has been transferred to the repository where the `Microsoft.Azure.NotificationHubs` libraries are maintained as [#303](https://github.com/Azure/azure-notificationhubs-dotnet/issues/303).
