### ISSUE TITLE
Unable to authenticate Compute SM SDK using AAD Token

### ISSUE THREAD

**Issue by dragonfly91** [Azure/azure-sdk-for-net#4193]
Hi,

I’m trying to authenticate the Compute Service Management SDK (to access Classic Cloud Services) using AAD token but this fails with forbidden error. I’m able to authenticate the Compute Service Management SDK successfully with certificate. Also, when I tried to authenticate Compute Resource Manager SDK with the same AAD token, it work fine again. 

  | AAD Token | Cert
-- | -- | --
Compute Service Management SDK | Forbidden error – need help here | Works fine
Compute Resource Manager SDK | Works fine | Didn’t try

Can you please point out what’s the issue? Code is attached.

[Program.txt](https://github.com/Azure/azure-sdk-for-net/files/1883252/Program.txt)

**Comment by shahabhijeet** [comment]
@hyonholee can you confirm if Service Management SDK supports AAD token auth.

**Comment by shahabhijeet** [comment]
@dragonfly91 the link below suggested by @hyonholee  if the below link helps let us know and we can close the issue
https://msdn.microsoft.com/en-us/library/azure/ee460782.aspx

**Comment by dragonfly91** [comment]
Hi, I've tried this and it didn't work. I've sent the details in mail.

**Comment by huangpf** [comment]
@hyonholee FYI.

**Comment by huangpf** [comment]
@huangpf

**Comment by huangpf** [comment]
Service API ask/issue.

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
