### ISSUE TITLE
SqlServer

### ISSUE THREAD

**Issue by m-nash** [Azure/azure-sdk-for-net#41985]
Add / update SqlServer to support all of the customization shown here

- https://github.com/dotnet/aspire/blob/main/src/Aspire.Hosting.Azure/Bicep/AzureBicepSqlServerResource.cs
- https://github.com/dotnet/aspire/blob/main/src/Aspire.Hosting.Azure/Bicep/sql.bicep

**Comment by mitchdenny** [comment]
Will we be getting an API here like `AddStorageAccount` (e.g. `AddSqlServer`?).

**Comment by JoshLove-msft** [comment]
> Will we be getting an API here like `AddStorageAccount` (e.g. `AddSqlServer`?).

Yeah we should go through all of the resources and add these helpers.
