### ISSUE TITLE
Description link goes to an image

### ISSUE THREAD

**Issue by MisinformedDNA** [Azure/azure-sdk-for-net#4200]
The repo description links to https://www.visualstudio.com/features/azure-tools-vs, which redirects to https://www.visualstudio.com/wp-content/uploads/2016/06/azure.png.

It doesn't make any sense so I assume there was a copy/paste error somewhere.

**Comment by shahabhijeet** [comment]
this has been fixed.

**Comment by MisinformedDNA** [comment]
You're welcome.
