### ISSUE TITLE
testwinrest

### ISSUE THREAD

**Issue by nawfelgi** [Azure/azure-sdk-for-net#42007]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.management.fluent.azure.activitylogs?view=azure-dotnet-legacy#microsoft-azure-management-fluent-azure-activitylogs

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.Fluent/Azure.xml

### Document Version Independent Id

348004b2-18cc-9db8-adf9-d111e86a3113

### Article author

@azure-sdk

### Metadata

* ID: ab969d6b-e5a0-cb0c-0a40-882c58828a0c 
* Service: **multiple**

**Comment by jsquire** [comment]
Hi @nawfelgi.  Thank you for reaching out and we regret that you're experiencing difficulties.  The Fluent management packages reached end-of-life in September, 2023 and are no longer published nor supported by Microsoft.  As updating this documentation would require an update and release of those libraries, this is not something that we'll be able to fix.
