### ISSUE TITLE
[BUG] After Upgrading AzureAppConfiguration AppInsights receives suddenly status 302 for refresh key checks

### ISSUE THREAD

**Issue by mpodonyi** [Azure/azure-sdk-for-net#42025]
### Library name and version

Microsoft.Azure.AppConfiguration.AspNetCore 7.0.0

### Describe the bug

After upgrading from Microsoft.Azure.AppConfiguration.AspNetCore V5.1.0 to V7.0.0
and Microsoft.Extensions.Configuration.AzureAppConfiguration V5.1.0 to V7.0.0

I am receiving suddenly Refresh Key Check Warnings of status 304 every 5 seconds (my refresh intervall) inAzure App Insights.

This is flooding my loggings and should not be so.

### Expected behavior

No 304 Warnings should be shown in AzureAppInsights for Refresh Key Checks where the when the Sentinel Values hasn't changed

### Actual behavior

The 304 Warning for Refreshkey Changes is suddenly appearing in my logs.

<img width="835" alt="Screenshot 2024-02-16 at 09 12 59" src="https://github.com/Azure/azure-sdk-for-net/assets/110200/d01417ec-5620-454d-bb8c-64837a7572a7">

### Reproduction Steps

The internal call to AppConfiguration Refresh Key is causing returning 304 which is logged.
https://[hidden].azconfig.io/kv/%21Trigger?api-version=2023-10-01

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.Azure.AppConfiguration.AspNetCore` package is maintained as [#519](https://github.com/Azure/AppConfiguration-DotnetProvider/issues/519)
