### ISSUE TITLE
[FEATURE REQ] GetPropertiesOfCertificatesAsync should support includeSubjectNameAndSan

### ISSUE THREAD

**Issue by henriblMSFT** [Azure/azure-sdk-for-net#42021]
### Library name

Azure.Security.KeyVault.Certificates

### Please describe the feature.

The certificate API supports the inclusion of subject name and SAN:
certificates?api-version=7.0&maxresults=25&includePending=true&includeSubjectNameAndSan=true

The azure SDK library does not. In order to retrieve the subject, one request per certificate has to be made.
When trying to identify a certificate by subject name this significantly increase the number of calls to keyvault.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
That parameter is not documented (https://learn.microsoft.com/rest/api/keyvault/certificates/get-certificates/get-certificates?view=rest-keyvault-certificates-7.4) nor included in swagger (https://github.com/Azure/azure-rest-api-specs/blob/7c1d25a89e495568fbecad030bdd8727613902f8/specification/keyvault/data-plane/Microsoft.KeyVault/stable/7.5/certificates.json#L38, from which our docs are generated). Can I ask where you learned of this parameter?

/cc @jlichwa

**Comment by jlichwa** [comment]
It is correct it is not supported in any of rest api versions https://github.com/Azure/azure-rest-api-specs/blob/master/specification/keyvault/data-plane/Microsoft.KeyVault/stable/7.0/keyvault.json#L1527

**Comment by jlichwa** [comment]
For feature requests to Key Vault service we recommend to share Idea here :https://feedback.azure.com/d365community/forum/285c5ae0-f524-ec11-b6e6-000d3a4f0da0

Once there is significant number customers asking for that feature, it can be considered in future releases

Key Vault Team
