### ISSUE TITLE
[QUERY] Documentation for Azure.Messaging.ServiceBus Claim Check Methods

### ISSUE THREAD

**Issue by MarkParsonsOS** [Azure/azure-sdk-for-net#42026]
### Library name and version

Azure.Messaging.ServiceBus 7.17.3

### Query/Question

Hi
I have found two methods in namespace Azure.Messaging.ServiceBus that deal with claims check.
ClaimCheckOnSend is in class ServiceBusMessage
ClaimCheckOnReceive is in class ServiceBusReceivedMessage
I cannot see any mention on them in the documentation
https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusmessage?view=azure-dotnet
https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusreceivedmessage?view=azure-dotnet
Are they released for general use?
Regards
Mark

### Environment

TargetFramework net8.0
AzureFunctionsVersion v4
 isolated worker model

Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.8.4

**Comment by jsquire** [comment]
Hi @MarkParsonsOS.  Thank you for reaching out and we regret that you're experiencing difficulties.   There is no claims check functionality in the Service Bus client library, just a [sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample10_ClaimCheck.md) that demonstrates how an application may choose to implement it.  

The methods that you've mentioned do not exist on [ServiceBusMessage](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/src/Primitives/ServiceBusMessage.cs) or [ServiceBusReceivedMessage](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/src/Primitives/ServiceBusReceivedMessage.cs).   If you are seeing them appear in your environment, then you most likely are referencing a third-party library that defines them as extension methods.  I do not know of a third-party library that does this, but if you're using an abstraction such as MassTransit or NServiceBus, those would be the first place that I'd suggest checking.
