### ISSUE TITLE
[BUG] Any Management SDK call stuck sometimes when using WaitUntil.Completed and never returns back.

### ISSUE THREAD

**Issue by vikramdadwal** [Azure/azure-sdk-for-net#42040]
### Library name and version

Azure.ResourceManager.ServiceBus, Azure.ResourceManager.Compute

### Describe the bug

We are observing that sometimes the call to Azure with CreateUpdate methods using the WaitUntil enum as WaitUntil.Completed hangs and never returns back with the result, this is causing our services to block the resources for the infinite time. 

Following is just one example when SDK with WaitUntil.Completed:

`ServiceBusTopicResource serviceBusTopic = serviceBusTopicCollection.CreateOrUpdate(WaitUntil.Completed, dynamicTopicName, topicData).Value;`

### Expected behavior

The SDK call should return with either a Success or a Failure response.

### Actual behavior

SDK call hangs and never returns.

### Reproduction Steps
Following is just one example when SDK with WaitUntil.Completed:

`ServiceBusTopicResource serviceBusTopic = serviceBusTopicCollection.CreateOrUpdate(WaitUntil.Completed, dynamicTopicName, topicData).Value;`

### Environment

.NET runtime running on Azure Container Instances

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by mcgallan** [comment]
Hi @vikramdadwal , regarding the issue you mentioned, I did not encounter the problem you mentioned during the reproduction process. Obviously, such a situation is not a necessary event, so if you can provide more information, such as error messages, specific implementation code, etc., it will help us better understand the situation and solve the problem better.

**Comment by melina5656** [comment]
Hi @vikramdadwal , you should use `asynchronous methods` and the `await` keyword. 

`await` is a mechanism for asynchronously waiting for a task to complete, while `WaitUntil.Completed` is a parameter that indicates the level of completion to wait for in an asynchronous method. `Used together`, they allow for waiting for time-consuming operations to complete without blocking the thread.

The specific format is as follows : 
```csharp
 //Create a serviceBus
 var serviceBusCollection = resourceGroup.GetServiceBusNamespaces();
 var namespaceName = "serviceBus";
 var serviceBusData = new ServiceBusNamespaceData(AzureLocation.EastUS)
 {
     Sku = new ServiceBusSku(ServiceBusSkuName.Premium)
     {
         Tier = ServiceBusSkuTier.Premium
     }
 };
 var serviceBus = (await serviceBusCollection.CreateOrUpdateAsync(WaitUntil.Completed, namespaceName, serviceBusData)).Value;

 //Create a serviceBusTopic
 var serviceBusTopicCollection = serviceBus.GetServiceBusTopics();
 var topicName = "topic";
 var topicData = new ServiceBusTopicData();
 var serviceBusTopic = (await serviceBusTopicCollection.CreateOrUpdateAsync(WaitUntil.Completed, topicName, topicData)).Value;
```
Thank you for your feedback.
