### ISSUE TITLE
Should GetParameters be exposed on Construct?

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#42050]
```C#
public IEnumerable<Parameter> GetParameters(bool recursive = true);
```
#
Should this have the recursive parameter or even be on Construct? I think the return will always be empty if recursive is false.

**Comment by m-nash** [comment]
Yes it should.  A parameter belongs to a construct NOT a resource therefore it is what needs the list and the ability to query.

**Comment by JoshLove-msft** [comment]
The scope that the parameter is added to by the user doesn't translate anymore to how parameter will be represented in the bicep. This is because the bicep is constructed into modules based on https://github.com/Azure/azure-sdk-for-net/issues/42017. For that reason, I wonder what value there is in letting a user add/query parameters with constructs.

**Comment by JoshLove-msft** [comment]
Based on the changes to always expose parameters added via AddConstruct even if they are not assigned to a resource, we should still have the GetParameters method. However, there is a bug in that it doesn't dedup parameters currently.
