### ISSUE TITLE
[QUERY] Why is `SearchAadAuthDataPlaneAuthOptions.AadOrApiKey` internal?

### ISSUE THREAD

**Issue by levimatheri** [Azure/azure-sdk-for-net#42051]
### Library name and version

Azure.ResourceManager.Search 1.1.0

### Query/Question

I'm trying to set auth option to 'Both' i.e. api key and RBAC for Azure AI Search. As per [the documentation](https://learn.microsoft.com/en-us/azure/search/search-security-rbac?tabs=config-svc-rest%2Croles-portal%2Ctest-portal%2Ccustom-role-portal%2Cdisable-keys-portal#configure-role-based-access-for-data-plane), this is possible via the REST API. However, in C#, the `AadOrApiKey` property is internal. What is the right way to set auth option to 'both' in .NET?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by levimatheri** [comment]
Looking at the [implementation](https://github.com/Azure/azure-sdk-for-net/blob/412e07874912c23a853b13a8beaba6acaa5d75b4/sdk/search/Azure.ResourceManager.Search/src/Generated/Models/SearchAadAuthDataPlaneAuthOptions.cs#L104) the property is set if the `AadAuthFailureMode` is set, which works, but seems unnatural... 🫤

**Comment by HarveyLink** [comment]
Hi @levimatheri , Thank you for using Azure SDK for .NET.
The question you mentioned is by design.
If the properfy has only one child property, we'll expose the child property to public and set the parent propery to internal.
