### ISSUE TITLE
Page Provides no help

### ISSUE THREAD

**Issue by jeremy-schaab** [Azure/azure-sdk-for-net#42065]
### Type of issue

Typo

### Description

[Enter feedback here]
I am trying to migrate from Microsoft.Azure.SqlManagement to Azure.ResourceManager.Sql and there are no examples (the link provides none) and there is nothing that I can find on migrating.  I tried ChatGPT paid version and it keeps spitting out code using the old package.

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/overview/azure/ResourceManager.Sql-readme?view=azure-dotnet

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/latest/resourcemanager.sql-readme.md

### Document Version Independent Id

f0728b44-4120-8630-adcf-7fc4f1ad78fe

### Article author

@azure-sdk

### Metadata

* ID: b2d3c115-8d8d-1626-0299-bb301b6ccdc5 
* Service: **sqlmanagement**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by mcgallan** [comment]
Hi @jeremy-schaab , thank you for your feedback. The page that your provided Page URL leads to was updated on March 26th. I'm not sure what the page looked like when you posted this issue, but now it may meet your needs. Also, about the examples you mentioned, they are also displayed on the page. I hope it can help you: https://github.com/Azure-Samples/azure-samples-net-management
