### ISSUE TITLE
How to set values for event grid advanced filters such for  StringContainsAdvancedFilter

### ISSUE THREAD

**Issue by waynebsx** [Azure/azure-sdk-for-net#42087]
### Library name and version

Azure.ResourceManager.EventGrid 1.0.1

### Query/Question

Creating an event grid subscription using Azure.ResourceManager.EventGrid - confused how to set values for advanced filters using SDK. Specifically for StringContainsAdvancedFilter. There's only a default parameterless constructor and the values list is read only. Ideally I'd like to do data.Filter.AdvancedFilters.Add(new StringContainsAdvancedFilter { Key = "subject", Values = new List<string>() { "somevalue" } }); but Values is readonly - so how to set values?

### Environment

Visual Studio 17.8.3

 dotnet --info
.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.8d38d0cc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100\

.NET workloads installed:
 Workload version: 8.0.100-manifests.8d38d0cc
There are no installed workloads to display.

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

.NET SDKs installed:
  8.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by melina5656** [comment]
Hi @waynebsx .You can refer to the following sample code to implement the required functions.

```csharp
 var data = new EventGridSubscriptionData()
 {
     Destination = new StorageQueueEventSubscriptionDestination()
     {
         ResourceId = storageAccount.Id,
         QueueName = storageQueue.Data.Name,

     },
     Filter = new EventSubscriptionFilter()
     {
         AdvancedFilters =
         {
             new StringContainsAdvancedFilter()
             {
                 Key = "subject",
                 Values =
                 {
                     "somevalue"
                 }
             }
         }
     }
 };
 var eventSubscription = (await eventSubscriptionCollection.CreateOrUpdateAsync(WaitUntil.Completed, eventSubscriptionName, data)).Value;
 ```
 Thank you for your feedback.
