### ISSUE TITLE
[FEATURE REQ] Set Private Execution environment for the SearchIndexerClient for Azure AI Search

### ISSUE THREAD

**Issue by willvelida** [Azure/azure-sdk-for-net#42092]
### Library name

Azure.Search.Documents.Indexes

### Please describe the feature.

We are integrating Azure AI Search inside a VNet, and we need to run our indexers within the Private execution environment. We'd like to be able to set this within our SearchIndexerClient: https://learn.microsoft.com/en-us/azure/search/search-indexer-securing-resources

Currently there is no way to do this via the .NET SDK: https://learn.microsoft.com/en-us/dotnet/api/azure.search.documents.indexes.searchindexerclient?view=azure-dotnet-preview

Would it be possible to introduce a property within the SearchIndexerClient to explicitly set the execution environment?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ShivangiReja** [comment]
Hi @willvelida, According to [this documentation](https://learn.microsoft.com/en-us/azure/search/search-indexer-securing-resources#step-3-force-indexers-to-run-in-the-private-environment), you can set the `executionEnvironment` to `private` within the indexer. Similarly, in the SDK, you can achieve this functionality by setting the [ExecutionEnvironment](https://learn.microsoft.com/en-us/dotnet/api/azure.search.documents.indexes.models.indexingparametersconfiguration.executionenvironment?view=azure-dotnet-preview#azure-search-documents-indexes-models-indexingparametersconfiguration-executionenvironment) property within the [IndexingParametersConfiguration](https://learn.microsoft.com/en-us/dotnet/api/azure.search.documents.indexes.models.indexingparametersconfiguration?view=azure-dotnet-preview) inside the indexer. Below is an example of how you can use this:

```csharp
SearchIndexer indexer = new SearchIndexer("indexerName", "dataSourceConnectionName", "indexName")
{
    Parameters = new IndexingParameters
    {
        IndexingParametersConfiguration = new IndexingParametersConfiguration
        {
            ExecutionEnvironment = IndexerExecutionEnvironment.Private
        }
    }
    // Add any other necessary properties here
};

SearchIndexerClient indexerClient = new SearchIndexerClient(endpoint, credential);
await indexerClient.CreateIndexerAsync(indexer);
```

This code snippet demonstrates setting the execution environment to "Private" within the `IndexingParametersConfiguration` of the `SearchIndexer` object. Feel free to adjust it according to your specific requirements!

**Comment by willvelida** [comment]
> Hi @willvelida, According to [this documentation](https://learn.microsoft.com/en-us/azure/search/search-indexer-securing-resources#step-3-force-indexers-to-run-in-the-private-environment), you can set the `executionEnvironment` to `private` within the indexer. Similarly, in the SDK, you can achieve this functionality by setting the [ExecutionEnvironment](https://learn.microsoft.com/en-us/dotnet/api/azure.search.documents.indexes.models.indexingparametersconfiguration.executionenvironment?view=azure-dotnet-preview#azure-search-documents-indexes-models-indexingparametersconfiguration-executionenvironment) property within the [IndexingParametersConfiguration](https://learn.microsoft.com/en-us/dotnet/api/azure.search.documents.indexes.models.indexingparametersconfiguration?view=azure-dotnet-preview) inside the indexer. Below is an example of how you can use this:
> 
> ```cs
> SearchIndexer indexer = new SearchIndexer("indexerName", "dataSourceConnectionName", "indexName")
> {
>     Parameters = new IndexingParameters
>     {
>         IndexingParametersConfiguration = new IndexingParametersConfiguration
>         {
>             ExecutionEnvironment = IndexerExecutionEnvironment.Private
>         }
>     }
>     // Add any other necessary properties here
> };
> 
> SearchIndexerClient indexerClient = new SearchIndexerClient(endpoint, credential);
> await indexerClient.CreateIndexerAsync(indexer);
> ```
> 
> This code snippet demonstrates setting the execution environment to "Private" within the `IndexingParametersConfiguration` of the `SearchIndexer` object. Feel free to adjust it according to your specific requirements!

Hey @ShivangiReja, thanks for getting back to me! Where can I raise an issue to update the documentation that shows this code snippet? I think that would be helpful for other developers :)

**Comment by ShivangiReja** [comment]
@willvelida - API documentation already includes the [IndexerExecutionEnvironment.Private](https://learn.microsoft.com/en-us/dotnet/api/azure.search.documents.indexes.models.indexerexecutionenvironment.private?view=azure-dotnet-preview#azure-search-documents-indexes-models-indexerexecutionenvironment-private) Property. If you are referring to the sample documentation, we do have a sample that demonstrates how to configure the `IndexingParametersConfiguration` properties [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/samples/Sample02_Service.md#create-an-indexer).

**Comment by willvelida** [comment]
@ShivangiReja - that doc isn't in the most accessible place. Could we not add to tab in this [document](https://learn.microsoft.com/en-us/azure/search/search-indexer-securing-resources#step-3-force-indexers-to-run-in-the-private-environment) to show the C# example alongside the JSON?

**Comment by ShivangiReja** [comment]
@willvelida - [This](https://learn.microsoft.com/en-us/azure/search/search-indexer-securing-resources#step-3-force-indexers-to-run-in-the-private-environment) documentation is for Azure Search service and it contains the code snippets demonstrating the usage of REST API with JSON payloads. While the focus of the documentation is on showcasing the usage of REST API with JSON bodies, it doesn't include specific samples for .NET SDK or other languages like Python, Java, etc. Due to the support for multiple languages through SDKs in the Azure Search service, it's not feasible to include samples for every language within the documentation. However, if you're looking for samples in a particular language such as .NET, a separate link is provided ([here](https://learn.microsoft.com/en-us/azure/search/samples-dotnet#sdk-samples)) where you can find relevant examples.
