### ISSUE TITLE
[BUG] MonitorExtensions.GetActivityLogsAsync throws The requested operation requires an element of type 'String', but the target element has type 'Number'.

### ISSUE THREAD

**Issue by minarde** [Azure/azure-sdk-for-net#42100]
### Library name and version

Azure.ResourceManager.Monitor 1.3.0

### Describe the bug

The code throws InvalidOperationException. It calls [MonitorExtensions.GetActivityLogsAsync](https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.monitor.monitorextensions.getactivitylogsasync?view=azure-dotnet)
```
    var eventsPages = subscription.GetActivityLogsAsync(filter, propertiesSelect, cancellationToken).AsPages();
    await foreach (var page in eventsPages)
    {
    }
```

Stacktrace
```
System.InvalidOperationException: The requested operation requires an element of type 'String', but the target element has type 'Number'.
   at System.Text.Json.ThrowHelper.ThrowJsonElementWrongTypeException(JsonTokenType expectedType, JsonTokenType actualType)
   at System.Text.Json.JsonDocument.GetString(Int32 index, JsonTokenType expectedType)
   at Azure.ResourceManager.Monitor.Models.EventDataInfo.DeserializeEventDataInfo(JsonElement element)
   at Azure.Core.PageableHelpers.PageableImplementation`1.CreatePage(Response response, String& nextLink)
   at Azure.Core.PageableHelpers.PageableImplementation`1.AsPagesAsync(String continuationToken, Nullable`1 pageSizeHint, CancellationToken cancellationToken)+MoveNext()
   at Azure.Core.PageableHelpers.PageableImplementation`1.AsPagesAsync(String continuationToken, Nullable`1 pageSizeHint, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
```

JSON
```
{
	"authorization": null,
	"caller": null,
	"channels": 0,
	"claims": null,
	"correlationId": null,
	"description": null,
	"eventDataId": null,
	"eventName": null,
	"category": {
		"value": "ResourceHealth",
		"localizedValue": "Resource Health"
	},
	"httpRequest": null,
	"id": "[CORRECT_RESOURCE_ID]",
	"level": 0,
	"resourceGroupName": null,
	"resourceProviderName": null,
	"resourceId": null,
	"resourceType": null,
	"operationId": null,
	"operationName": null,
	"properties": null,
	"status": null,
	"subStatus": null,
	"eventTimestamp": "0001-01-01T00:00:00",
	"submissionTimestamp": "0001-01-01T00:00:00",
	"subscriptionId": null,
	"tenantId": null
}
```

### Expected behavior

The JSON should be deserialized correctly.

### Actual behavior

System.InvalidOperationException: The requested operation requires an element of type 'String', but the target element has type 'Number'. is thrown

### Reproduction Steps

    var armClient = new ArmClient(tokenCredential, subscriptionId, options);
    var subscription = armClient.GetSubscriptionResource(SubscriptionResource.CreateResourceIdentifier(subscriptionId));
    var eventsPages = subscription.GetActivityLogsAsync(filter, "", cancellationToken).AsPages();
    await foreach (var page in eventsPages)
    {
    }

### Environment

Windows .NET 8

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by minarde** [comment]
Yesterday this issue appears to be fixed. There is difference in JSON, before it was `"level": 0`, now `"level": null`
