### ISSUE TITLE
[Automation Script Bug] Use 'service.csproj' to build generated SDK projects rather than using '*.sln' file

### ISSUE THREAD

**Issue by raych1** [Azure/azure-sdk-for-net#42159]
### Library name and version

The automation script in DotNet repository

### Describe the bug

The current build step in the automation script relies on the `*.sln` file under the SDK project folder. However, in some cases, the service may have a `*.sln` file under the root folder of the service folder, which can cause issues with SDK generation. 

To address this, the proposal is to change the script to use the [eng/service.proj](https://github.com/Azure/azure-sdk-for-net/blob/main/eng/service.proj) file and remove the dependency on the `*.sln` file.  An example of this usage can be found in the [CI pipeline](https://github.com/Azure/azure-sdk-for-net/blob/main/eng/pipelines/templates/jobs/ci.yml#L217).

Additionally, we suggest updating the [build command](https://github.com/Azure/azure-sdk-for-net/blob/main/eng/scripts/automation/GenerateAndBuildLib.ps1#L758) to only scope to the 'src' project.

Finally, we recommend exploring the possibility of excluding the test project build and test run from the spec PR CI to prevent similar errors from breaking the SDK generation step.

### Expected behavior

The SDK generation should succeed in the spec PR pipeline.

### Actual behavior

This is an [example PR](https://github.com/Azure/azure-rest-api-specs/pull/27405#issuecomment-1951559617) with this issue. The SDK generation failed with the following error.
```
Start to build sdk: /mnt/vss/_work/1/s/azure-sdk-for-net/sdk/communication/Azure.Communication.Messages
05:03:40.690 cmdout 	[Invoke-GenerateAndBuildV2.ps1] MSBuild version 17.4.0+18d5aef85 for .NET
05:03:40.694 cmdout 	[Invoke-GenerateAndBuildV2.ps1] MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
05:03:40.799 cmderr W 	[Invoke-GenerateAndBuildV2.ps1] GeneratePackage: /mnt/vss/_work/1/s/azure-sdk-for-net/eng/scripts/Invoke-GenerateAndBuildV2.ps1:131
05:03:40.799 cmderr W 	[Invoke-GenerateAndBuildV2.ps1] Line |
05:03:40.799 cmderr W 	[Invoke-GenerateAndBuildV2.ps1]  131 |                GeneratePackage `
05:03:40.799 cmderr W 	[Invoke-GenerateAndBuildV2.ps1]      |                ~~~~~~~~~~~~~~~~~
05:03:40.800 cmderr W 	[Invoke-GenerateAndBuildV2.ps1]      | Failed to build sdk. exit code: False

```

### Reproduction Steps

Please try running the SDK generation at this project folder [sdk/communication/Azure.Communication.Messages](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/communication/Azure.Communication.Messages/)

@chunyu3

**Comment by jsquire** [comment]
@raych1: When opening issues outside of your project area, please do not add tags.   This interferes with the triage process and increases the chances that this will end up being overlooked.

**Comment by weshaggard** [comment]
If we can scope to just building the src project directly then we don't need to use the service.proj. However if we do need to build more then just the src project you should use service.proj and not rely on sln files.
