### ISSUE TITLE
Add overview and samples to CM similar to Azure.Core

### ISSUE THREAD

**Issue by pallavit** [Azure/azure-sdk-for-net#42153]
All the samples similar to - https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/readme.md

**Comment by pallavit** [comment]
@KrzysztofCwalina will know more about it, since he asked me to create this work-item :)

**Comment by KrzysztofCwalina** [comment]
mainly for users of client libraries. We want them to understand that they can change retires (just the number of retries first), that there is a pluggable pipeline, that there are protocol methods, ClientResponse<T>, etc.

**Comment by annelo-msft** [comment]
For end-user, I would suggest following a structure something like:

- Configuring the client/[Configuration](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/[Configuration](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Configuration.md).md)
  - Passing credentials
  - Using client options
    - NetworkTimeout
    - Add a custom policy
    - Configuring retries
    - Customizing the transport
      - custom HttpClient
      - proxies
    - Freezing
- Calling client methods
  - Convenience methods/Response
    - Client method return values
      - `ClientResult<T>`
      - `ClientResult<T?>`
    - HTTP thru Response
      -  Status
      - Headers
      - Content/ContentStream
    - Exception handling
  - Protocol methods
    - How to use
      - Creating BinaryContent input
      - Using ClientResult return value
    - Configuring a request/RequestContext
      - CancellationToken
      - ErrorOptions
      - Headers: add vs. set
      - Add a custom policy
      - Freezing
- Model Reader Writer samples
  - TBD per @m-nash
- Mocking
  - Punt for now?
