### ISSUE TITLE
[BUG] WrapKeyInternal in Azure.Storage.Blobs calls wrong method

### ISSUE THREAD

**Issue by yuopolev** [Azure/azure-sdk-for-net#42160]
### Library name and version

Azure.Storage.Blobs 

### Describe the bug

![image](https://github.com/Azure/azure-sdk-for-net/assets/91480786/d70187e5-4138-46e3-9b8e-ff379f55319c)

'WrapKeyInternal' in SpecializedBlobExtensions in Azure.Storage.Blobs calls 'UnwrapKey' in case of non-async call.

### Expected behavior

'WrapKeyInternal' should wrap key independently of being called as async or sync.

If 'sync' branch part is not used at all and not covered in tests, hten it should be removed, otherwise this needs to be fixed and do wrap.

### Actual behavior

'WrapKeyInternal' wraps key in case it is called as async, and unwraps (?) key in case it is called as sync.

### Reproduction Steps

This is obvious code defect, can be seem in sources.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
//cc: @xgithubtriage

**Comment by nickliu-msft** [comment]
Hi we're working on a fix in our next coming release
