### ISSUE TITLE
analyzing multiple pages with my custom models not working

### ISSUE THREAD

**Issue by yonatanma** [Azure/azure-sdk-for-net#42176]
### Type of issue

Code doesn't work

### Description

hello All, I am using the Azure.AI.DocumentIntelligence SDK for .NET to analyze a document on my custom model with multiple pages. However, I am encountering an issue where the resulting AnalyzeResult object only contains a single page result, even though the documentation states that the SDK supports analyzing multiple pages

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/overview/azure/ai.documentintelligence-readme?view=azure-dotnet-preview

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/preview/ai.documentintelligence-readme.md

### Document Version Independent Id

df73dd02-1b97-86c0-f092-60080e3f179a

### Article author

@azure-sdk

### Metadata

* ID: c0b346e0-23d2-d1c3-8606-31917875b562 
* Service: **documentintelligence**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by kinelski** [comment]
Hello @yonatanma,

Could you share the request ID of your `AnalyzeDocument` call? This will help us to understand whether this is an issue in the SDK or in the Document Intelligence service.

To get the request ID:
```cs
var operation = client.AnalyzeDocument(WaitUntil.Completed, ...);
string requestId = operation.GetRawResponse().RequestId;
```
