### ISSUE TITLE
[QUERY] How to query Azure API Management information

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/azure-sdk-for-net#42183]
### Library name and version

Azure.ResourceManager.ApiManagement" v1.1.0

### Query/Question

I am trying to query Azure API Management as following but it alays returns that there is no information:

```csharp
var clientOptions = new ArmClientOptions()
{
    Diagnostics = { IsLoggingEnabled = true, IsLoggingContentEnabled = true}
};
var armClient = new ArmClient(auth, subscriptionId, clientOptions);
var apimResourceId = ApiManagementServiceResource.CreateResourceIdentifier("<subscription-id>", "<resource-group>", "<apim-resource-id>");
var x = armClient.GetApiManagementServiceResource(apimResourceId);
var z = armClient.GetGenericResource(apimResourceId);
```

Am I doing something wrong?

The app has contributor permissions which should be more than required:
<img width="1014" alt="image" src="https://github.com/Azure/azure-sdk-for-net/assets/4345663/9417a7ab-cf8d-4c76-8317-e701614973f3">

### Environment

Sources are available on https://github.com/tomkerkhove/api-management-chaos-monkey/blob/sandbox/src/GatewaySimulation.Sandbox/Worker.cs#L49-L59

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by tomkerkhove** [comment]
Any comment on this @ArthurMa1978?

**Comment by tomkerkhove** [comment]
This is very counter intuitive to me as I was expecting the service info to receive here:
```csharp
var serviceResource = armClient.GetApiManagementServiceResource(apimResourceId);
```

However, this is just a placeholder resource and you need to request to get the info:
```csharp
var serviceInfoResponse = await serviceResource.GetAsync();
```

Once that completes, you need to parse the data: (note that there is a `HasData` which should be `true`)
```csharp
var serviceInfo = serviceInfoResponse.Value.Data;
```
