### ISSUE TITLE
[QUERY] Get the Url of a Search Service

### ISSUE THREAD

**Issue by sebastienros** [Azure/azure-sdk-for-net#42202]
### Library name and version

Azure.Search.Documents

### Query/Question

Is there a way to get the service url of a Search Service without having to compute it like this:

```
https://${searchServiceName}.search.windows.net
```

I couldn't find the property from this doc:

https://learn.microsoft.com/en-us/rest/api/searchmanagement/services/get?view=rest-searchmanagement-2023-11-01&tabs=HTTP

But can see it in the portal:

![image](https://github.com/Azure/azure-sdk-for-net/assets/1165805/68a6ebb6-f83c-477d-ba22-921380e97483)

**Comment by jsquire** [comment]
Hi @sebastienros.  Thank you for reaching out and we regret that you're experiencing difficulties.  There is no API that we are aware of to read this from, neither from the management plane nor data plane services.  This would be a topic that we'd suggest discussing with the Search service team, as any changes would need to be service-side.

**Comment by jsquire** [comment]
> > This would be a topic that we'd suggest discussing with the Search service team
> 
> Do you know of any public repository where this could be suggested, or any other public discussion medium? The only public forum I can see on the documentation site is a link to StackOverflow...
> 
> In parallel I'll try to find some internal contacts.

There's no repository for the services; they're not open-source products.  The search team does not seem to have a page on the [Azure Feedback site](https://feedback.azure.com/d365community/forum/86c37ae9-7526-ec11-b6e6-000d3a4f032c) to use.

**Comment by sebastienros** [comment]
The Azure AI Search team said they would add this property.
