### ISSUE TITLE
Decide whether or not env vars should be supported for subscriptionId

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#42203]
Currently we fall back to the AZURE_SUBSCRIPTION_ID env var if no subscription is specified when constructing an Infrastructure. For subscription scoped deployments using az cli, the subscription bicep function would resolve based on the default subscription. When using azd, the env var is already respected, so the question is whether it needs to also be respected in the CDK.

**Comment by tg-msft** [comment]
This is now customizable in `ProvisioningContext`: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/provisioning/Azure.Provisioning/src/ProvisioningContext.cs
