### ISSUE TITLE
[FEATURE REQ] Support GetMessageSessions

### ISSUE THREAD

**Issue by miqm** [Azure/azure-sdk-for-net#42215]
### Library name

Azure.Messaging.ServiceBus

### Please describe the feature.

Hello,

Please reopen #20569. This is fully doable with Azure Service Bus AMQP transport. As per discussion here: https://github.com/MicrosoftDocs/azure-docs/issues/119766 and implementation in Java SDK: https://github.com/Azure/azure-sdk-for-java/blob/6c697512988fbd96a9d8a9bfe84eb96566f4681b/sdk/servicebus/microsoft-azure-servicebus/src/main/java/com/microsoft/azure/servicebus/SessionBrowser.java#L37 setting maximum value for the `last-updated-time` field returns all sessions in the response.

**Comment by jsquire** [comment]
Hi @miqm.  Thank you for reaching out and we regret that you're experiencing difficulties.  This is not a feature that we can consider at the present time, as the service API does not behave in an intuitive and consistent way that would address common developer scenarios.   The example that you're referencing works only when a developer has explicitly created state for a session, which is a seldom used feature.  It also does not filter sessions that have no active messages, making it misleading for the commonly requested use case.

For this to be something that we can add to the client, service changes are needed to correct the behavior.  The Service Bus team has indicated that this is not on their roadmap currently.   I'm going to close this issue out; should the service offer an API with the expected behaviors, the client will support it.   

If you would like to advocate for service support, consider opening a feature request in the [Service Bus forum](https://feedback.azure.com/d365community/forum/7c0a897d-2125-ec11-b6e6-000d3a4f0f84) of the Azure feedback site.

**Comment by miqm** [comment]
> The example that you're referencing works only when a developer has explicitly created state for a session, which is a seldom used feature.

@jsquire I raised that concern in https://github.com/MicrosoftDocs/azure-docs/issues/119766 and @yvgopal (Microsoft employee) corrected that providing DateTime.MaxValue returns ALL sessions - with sessions state set and not set. This is a consistent way I think and fits scaling scenarios.

I think that there's some misunderstanding and that feature does exist in Service Bus. Basing on the Java SDK - since quite a long time...

/unresolve

**Comment by miqm** [comment]
> It also does not filter sessions that have no active messages, making it misleading for the commonly requested use case.

I wouldn't consider this as a blocker. This is a case-specific scenario and as you said - it's used seldom.

**Comment by jsquire** [comment]
Thank you for your thoughts but, ss mentioned, this is not something that we'll consider adding without changes to the service API.

**Comment by miqm** [comment]
Limitation with filtering or not getting all sessions?

**Comment by jsquire** [comment]
At a minimum, the service API would need to return all sessions regardless of whether or not state was set.  It should allow callers to filter by whether or not there are messages in the session.

**Comment by miqm** [comment]
> At a minimum, the service API would need to return all sessions regardless of whether or not state was set.

This is working today, correct?

**Comment by jsquire** [comment]
No, it is not.  Vijaya's statements are incorrect with respect to the current service behavior.  The Azure SDK team has discussed this internally with him and the other members of the Service Bus service team.   They have confirmed that it requires session state to have been set in order to return the session and stated that adjusting the behavior is not currently on their roadmap.

**Comment by miqm** [comment]
@yvgopal could you comment on this please? I'm a bit confused...

**Comment by jsquire** [comment]
//cc: @EldertGrootenboer 

This request is coming up again.  

For historical context:

- https://github.com/Azure/azure-service-bus/issues/275
- https://github.com/Azure/azure-sdk-for-net/issues/11439
- https://github.com/Azure/azure-sdk-for-net/issues/20569

**Comment by miqm** [comment]
Also some context: https://github.com/kedacore/keda/issues/1479
Cc: @TomKerkhove

**Comment by miqm** [comment]
> No, it is not. Vijaya's statements are incorrect with respect to the current service behavior.

@jsquire I tested this on my Service Bus instance and when I provided timestamp value as @yvgopal suggested - in the AMQP response I received list of sessions with both state set (and no messages) and those that exist only due to existence of a message in the queue. So unless there's something non-deterministic going on, it seems to be working.

**Comment by jsquire** [comment]
I'm going to close this out in favor of [#275](https://github.com/Azure/azure-service-bus/issues/275).   While we appreciate the discussion and the anecdotal evidence, the fact remains that the Service Bus team has not signed off on the feature providing the necessary behavior and committed to supporting it as such.   Until that takes place, this will not be added to the Azure SDK packages.    

@EldertGrootenboer:  As the product owner for Service Bus, I'll ask that you reactivate 275 if the service is reconsidering the request or that you reach out if the status has changed since our last conversation.

**Comment by miqm** [comment]
This is very odd. One team says it does not exist, second is updating official documentation. Please get it straighten.

**Comment by miqm** [comment]
Will the #275 be re-opened?

**Comment by jsquire** [comment]
> Will the [#275](https://github.com/Azure/azure-service-bus/issues/275) be re-opened?

The fate of 275 depends on the decisions made by @EldertGrootenboer and the Service Bus team.
