### ISSUE TITLE
[BUG] async Task<T> is not defined in QueryAsync method in TableClient class

### ISSUE THREAD

**Issue by JicoDotNet** [Azure/azure-sdk-for-net#42222]
### Library name and version

Azure.Data.Tables 12.8.3

### Describe the bug

In the class 'TableClient' line number 1056 & 1132 for two methods are below inappropriate. 

1. public virtual AsyncPageable<T> QueryAsync<T>(Expression<Func<T, bool>> filter, int? maxPerPage = null, IEnumerable<string> select = null, CancellationToken cancellationToken = default)
2. public virtual AsyncPageable<T> QueryAsync<T>(string filter = null, int? maxPerPage = null, IEnumerable<string> select = null, CancellationToken cancellationToken = default)

methods are used for **Async but** these are **not 'Task'.** 

Ref: https://github.com/Azure/azure-sdk-for-net/blob/Azure.Data.Tables_12.8.3/sdk/tables/Azure.Data.Tables/src/TableClient.cs

### Expected behavior

11. public virtual **async Task<AsyncPageable<T>>** QueryAsync<T>(Expression<Func<T, bool>> filter, int? maxPerPage = null, IEnumerable<string> select = null, CancellationToken cancellationToken = default)
2. public virtual **async Task<AsyncPageable<T>>** QueryAsync<T>(string filter = null, int? maxPerPage = null, IEnumerable<string> select = null, CancellationToken cancellationToken = default)

### Actual behavior

Method is not async Task

### Reproduction Steps

// Define the query you want to execute
string filter = TableClient.CreateQueryFilter($"");
AsyncPageable<PersonEntity> entities = await tableClient.QueryAsync<PersonEntity>(filter);

**Comment by jsquire** [comment]
Hi @JicoDotNet.  Thank you for reaching out and we regret that you're experiencing difficulties.  The method signatures are correct.  They are intended to represent an `IAsyncEnumerable<T>` that you can iterate through rather than a `Task<T>`.   Your application would consume this in the same way as the [Query Tables example](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/tables/Azure.Data.Tables/samples/Sample3QueryTables.md#query-tables-1) demonstrates, but using the asynchronous form:

```csharp
AsyncPageable<TableItem> queryTableResults = serviceClient.QueryAsync(filter: $"TableName eq '{tableName}'");
Console.WriteLine("The following are the names of the tables in the query results:");

// Iterate the <see cref="Pageable"> in order to access queried tables.

await foreach (TableItem table in queryTableResults)
{
    Console.WriteLine(table.Name);
}
```

More information can be found in [Iterating with Async Enumerables in C# 8](https://learn.microsoft.com/en-us/archive/msdn-magazine/2019/november/csharp-iterating-with-async-enumerables-in-csharp-8).

**Comment by JicoDotNet** [comment]
Hi @jsquire Thanks for your support. Can you please support for my below code. 

```
public async Task<List<Person>> GetPersons(string Query)
{
    try
    {
        TableServiceClient tableServiceClient = new AzureHandler("my_storage_account_connection_string").Connection;
        TableClient myTableClient = tableServiceClient.GetTableClient("my_table_name");
        return await myTableClient.QueryAsync<Person>(Query).ToBlockingEnumerable().ToList();
    }
    catch (Exception)
    {
        throw;
    }
}
```
**Receiving below error.** 

> Error CS1061 'List<Person>' does not contain a definition for 'GetAwaiter' and no accessible extension method 'GetAwaiter' accepting a first argument of type 'List<Person>' could be found (are you missing a using directive or an assembly reference?)

**Comment by JicoDotNet** [comment]
Hi @jsquire, Thanks for your support. Can you please help me on the code below. I'm getting an error for this code block.

```
public async Task<List<Person>> GetPersons(string Query)
{
    try
    {
        TableServiceClient tableServiceClient = new TableServiceClient("my_storage_account_connection_string");
        TableClient myTableClient = tableServiceClient.GetTableClient("my_table_name");
        return await myTableClient.QueryAsync<Person>(Query).ToBlockingEnumerable().ToList();
    }
    catch (Exception)
    {
        throw;
    }
}
```
**Receiving below ERROR.**

> Error CS1061 'List<Person>' does not contain a definition for 'GetAwaiter' and no accessible extension method 'GetAwaiter' accepting a first argument of type 'List<Person>' could be found (are you missing a using directive or an assembly reference?)

**Comment by jsquire** [comment]
The standard `ToList` only works with `IEnumerable<T>`, not with `IAsyncEnumerable<T>`.   Your options would be to consider using a package like [System.Linq.Async](https://www.nuget.org/packages/System.Linq.Async/) to give you assess to `ToListAsync()` or you would need to write your own loop to do the conversion:

```csharp
var results = new List<TableItem>();
var queryTableResults = serviceClient.QueryAsync(filter: $"TableName eq '{tableName}'");

await foreach (TableItem table in queryTableResults)
{
    results.Add(table);
}
```
