### ISSUE TITLE
[BUG] Error when upgrading Azure.Extensions.AspNetCore.DataProtection.Keys

### ISSUE THREAD

**Issue by khellang** [Azure/azure-sdk-for-net#42223]
### Library name and version

Azure.Extensions.AspNetCore.DataProtection.Keys 1.2.3

### Describe the bug

This is the exact same error as #14761, which seems to be fixed back in 2020, but this is the second time we're seeing issues when upgrading to newer versions of Azure.Extensions.AspNetCore.DataProtection.Keys since then, so I think something might still be wonky.

### Expected behavior

I expect to be able to update the package to a newer version and my existing keys continue to work.

### Actual behavior

When attempting to decrypt something using a key from an older version (1.2.2), we're getting the following error:

> Could not load file or assembly 'Azure.Extensions.AspNetCore.DataProtection.Keys, Version=1.2.2.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

We store our keys in the database and both times this has happened, I've ran something along the lines of the following SQL statement:

```sql
UPDATE [dbo].[DataProtectionKey] SET [Xml] = REPLACE([Xml], 'Azure.Extensions.AspNetCore.DataProtection.Keys.AzureKeyVaultXmlDecryptor, Azure.Extensions.AspNetCore.DataProtection.Keys, Version=1.2.2.0', 'Azure.Extensions.AspNetCore.DataProtection.Keys.AzureKeyVaultXmlDecryptor, Azure.Extensions.AspNetCore.DataProtection.Keys, Version=1.2.3.0')
```

Which changes the following XML

```diff
-<encryptedSecret decryptorType="Azure.Extensions.AspNetCore.DataProtection.Keys.AzureKeyVaultXmlDecryptor, Azure.Extensions.AspNetCore.DataProtection.Keys, Version=1.2.2.0, Culture=neutral, PublicKeyToken=92742159e12e44c8" xmlns="http://schemas.asp.net/2015/03/dataProtection">
+<encryptedSecret decryptorType="Azure.Extensions.AspNetCore.DataProtection.Keys.AzureKeyVaultXmlDecryptor, Azure.Extensions.AspNetCore.DataProtection.Keys, Version=1.2.3.0, Culture=neutral, PublicKeyToken=92742159e12e44c8" xmlns="http://schemas.asp.net/2015/03/dataProtection">
```

Then recycled the app, and it works again.

### Reproduction Steps

- Install `Azure.Extensions.AspNetCore.DataProtection.Keys` v1.2.2
- Set up DataProtection with `ProtectKeysWithAzureKeyVault`
- Protect something so key is stored
- Update to `Azure.Extensions.AspNetCore.DataProtection.Keys` v1.2.3
- Attempt to unprotect the same thing that was just protected with the previous version

### Environment

- Azure App Service
- .NET Framework 4.8.4645.0
- Microsoft.AspNetCore.DataProtection 8.0.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
