### ISSUE TITLE
[QUERY] How to authenticate as a specific user assigned managed identity with a client secret.

### ISSUE THREAD

**Issue by nschuessler** [Azure/azure-sdk-for-net#42225]
### Library name and version

Azure.Identity 1.10.4

### Query/Question

I have an app service it uses two user assigned managed identities:
configurationidentity => access key vault for configuration
dataidentity => access production data

When it starts up in production, I of course use:

`new ManagedIdentityCredential(clientId: "configurationidentity")` to get to the key vault.
`new ManagedIdentityCredential(clientId: "dataidentity")` to get to the production data.

Because there is > 1 user assigned managed identity (I presume) that is the cause of the exception when you don't explicitly specify `clientId`.

When running in the debugger on a developer box, I authenticate under my user account `VisualStudioCredential`.

If I can load app id and app secret from somewhere using `VisualStudioCredential` on my devbox. 

What credentials can I use to authenticate to make the code run locally?
`ManagedIdentityCredential` - doesn't take app ids or secrets, but you can specify the identity id
`ClientSecretCredential` - takes the app id and secret, but the identity to use is ambiguous (because you don't have an id field that I can see).

I need something like `new ManagedIdentityCredential(clientId: "configurationidentity", new ClientSecretCredential(appid, appsecret));

How is it done?

Thanks

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @nschuessler - Your choice of credential is dependent on which identity you want to authenticate with. If, for example, you wanted to authenticate with some registered app, you could use `ClientSecretCredential`. In that case the app ID (ClientID) is what defines that registered app as the service principal. You'd need to grant RBAC access to the resource for that client ID. [See this](https://learn.microsoft.com/en-us/entra/identity-platform/howto-create-service-principal-portal) for more information.

`ManagedIdentityCredential` is only available when running on the deployed host environment.

**Comment by nschuessler** [comment]
Basically, my scenario is I cannot attach debugger to a running production server because of network configuration. But by having resources available and pressing F5 in visual studio I would still like to manually inspect that code is working.

**Comment by christothes** [comment]
You'll need to change the code to use a different credential type when running locally and the identity represented by that credential would need to have RBAC permissions to the resource. If your requirement is that it must be two different identities for accessing configuration and data, then you'll need two different identities for dev scenarios as well.
