### ISSUE TITLE
[QUERY] Missing documentation and sample use of GetUsagesCollections

### ISSUE THREAD

**Issue by alexvelicu** [Azure/azure-sdk-for-net#42253]
### Library name and version

Azure.ResourceManager.CosmosDB 1.3.0

### Query/Question

Hello, while trying to call the method GetUsagesCollections, or the async version, i found there is no documentation and / or samples of this method being called. Is there any way to get some documentation on it and also some sample code of using it?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Hey @alexvelicu, here is one [sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cosmosdb/Azure.ResourceManager.CosmosDB/samples/Generated/Samples/Sample_CosmosDBAccountResource.cs#L693) for this method.
Please let me know if this is good for you.

**Comment by alexvelicu** [comment]
Hello, the sample helps, seems to work (I need more testing to confirm). 
Thank you.
