### ISSUE TITLE
[FEATURE REQ] Add option to opt out of Check Pointing

### ISSUE THREAD

**Issue by amnguye** [Azure/azure-sdk-for-net#42264]
### Library name

Azure.Storage.DataMovement

### Please describe the feature.

Add opt out feature to disable / opt out of check pointing the state of transfers when using the DataMovement Library.

This would disable the ability to pause and resume as the state of the transfers are not stored anywhere.

This would disable the creation of the ".azstoragedml" folder created when using the DataMovement library.

**Comment by austindonnelly** [comment]
This was completed in PR #46286 which released in 12.0.0-beta.6
https://github.com/Azure/azure-sdk-for-net/releases/tag/Azure.Storage.DataMovement.Blobs_12.0.0-beta.6

I think this feature request could be closed now.
