### ISSUE TITLE
[Core] SSE: Analysis and design

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#42284]
# Overview

You down with SSE?  Well, Krzysztof is - so we should go ask him what we need and get his thoughts on a design.

## Scope of work

- Capture requirements from Krzysztof, covering OpenAI and the general form.
- Determine whether this feature lands in Core or ClientModel after discussing with Krzysztof and Anne.
- Determine code generation needs for this feature after discussing with Michael.
- Create issue(s) to describe the needed implementation scope and the design for both code gen and client library work.

## Out of scope

- The implementation; that will be covered by a separate issue

## Success criteria

- The requirements for SSE are understood and captured in an issue.
- A high-level design for SSE was created and details are captured in an issue.
- Work to implement client library scope is understood and captured in an issue.
- Work to implement code generation scope is understood and captured in an issue.
- Estimation to complete implementation, end-to-end, is known

**Comment by pallavit** [comment]
What does runtime feature mean? BTW I love the project grooming @annelo-msft

**Comment by annelo-msft** [comment]
> What does runtime feature mean?

That is @jsquire's categorization - I didn't change anything he'd already categorized.  @jsquire can you unpack this one for us?

**Comment by jsquire** [comment]
OpenAI has a built-in SSE implementation.   We know that we want to move this to ClientModel at some point in the future so that other libraries can also make use.  We do not yet understand the scope of what is needed.   This issue is about gathering the requirements from our SME (Krzysztof) and capturing the work in issues.

**Comment by jsquire** [comment]
>What does runtime feature mean?

Not a clue.  That predates me and I'd like to see the field die because I don't understand it.

**Comment by annelo-msft** [comment]
Related to https://github.com/Azure/azure-sdk-for-net/issues/43032

@joseharriaga FYI

**Comment by annelo-msft** [comment]
Closed by https://github.com/Azure/azure-sdk-for-net/pull/43840, modulo SCM GA-release activities.
