### ISSUE TITLE
[FEATURE REQ] Make it possible to pass correlation id through ClientCertificateCredential to MsalConfidentialClient/AcquireTokenForClientParameterBuilder

### ISSUE THREAD

**Issue by austvik** [Azure/azure-sdk-for-net#42283]
### Library name

Azure.Identity

### Please describe the feature.

For tracability I want to add the correlation id to authentication calls which are done through the ClientCertificateCredential (I guess this is an issue for all the different credential classes).

The call is done through the MsalConfidentialClient, which internally uses the client to create a AcquireTokenForClientParameterBuilder.

This builder has a WithCorrelationId, but there is no way to signal to the MsalConfidentialClient through the ClientCertificateCredential that we want to add more parameters to the builder.

Please make it possible to add more parameters (like correlation id) to the authentication calls.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @austvik - Would wrapping your `GetToken` calls in [HttpPipeline.CreateClientRequestIdScope](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Diagnostics.md#setting-x-ms-client-request-id-value-sent-with-requests) address your issue?
