### ISSUE TITLE
[FEATURE REQ] Add CacheControl as a configurable option for new blobs in BlobCheckpointStore

### ISSUE THREAD

**Issue by ddouglas-msft** [Azure/azure-sdk-for-net#42304]
### Library name

Azure.Messaging.EventHub

### Please describe the feature.

I've also been running into the issue described here: https://github.com/Azure/azure-sdk-for-net/issues/33635

I was wondering if the BlobCheckpointStore could be updated so CacheControl could be an option that's set when new blobs are created.

**Comment by jsquire** [comment]
@ddouglas-msft:  Please don't add labels when opening issues outside of your product area.  It interferes with triage and makes it more likely something will be overlooked.

**Comment by ddouglas-msft** [comment]
> @ddouglas-msft: Please don't add labels when opening issues outside of your product area. It interferes with triage and makes it more likely something will be overlooked.

Thank you. I was unaware.

**Comment by jsquire** [comment]
I'm not sure that I understand what is being asked for.  We intentionally do not cache in the checkpoint store and cannot do so safely for any ownership operations.  We could, in theory, cache checkpoint data, but those are expected to be written frequently and read only when ownership changes or a partition crashes.

Can you provide additional context about the end-to-end scenario that you've got in mind?

**Comment by ddouglas-msft** [comment]
We've been seeing a lot of "multiple condition headers are not supported" errors in our logs. I believe it's related to the issue in the linked bug. The issue appears to be caching in Azure Blobs. We want to set CacheControl to "max-age=0" which fixed it for the customer in that issue. I'm hoping this could be either added automatically for us, or for there to be a way for us to set it. I wrote something to go through the blobs created and set the value. I'm currently testing it to see if it fixes the issue. As we deploy to new areas, I'm worried this could keep popping up so I'm hoping it can just be set when the blob is created so we won't have to worry about it. Thank you

**Comment by ddouglas-msft** [comment]
Here's the exception:
`Unexpected error in EventHub EventProcessor. partition:'', operationDescription:'Executing a load balancing cycle.', Exception = Azure.Messaging.EventHubs.EventHubsException(GeneralError): Attempting to renew all of the processor's partition ownership in the storage service..  For troubleshooting information, see https://aka.ms/azsdk/net/eventhubs/exceptions/troubleshoot
   at Azure.Messaging.EventHubs.Primitives.PartitionLoadBalancer.RenewOwnershipAsync(CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Primitives.PartitionLoadBalancer.RunLoadBalancingAsync(String[] partitionIds, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Primitives.EventProcessor`1.PerformLoadBalancingAsync(ValueStopwatch cycleDuration, String[] partitionIds, CancellationToken cancellationToken)
Azure.RequestFailedException: Multiple condition headers are not supported.
RequestId:ea50083f-001e-001e-17ae-6a2241000000
Time:2024-02-29T01:29:56.0342331Z
Status: 400 (Multiple condition headers are not supported.)
ErrorCode: MultipleConditionHeadersNotSupported

Content:
﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>MultipleConditionHeadersNotSupported</Code><Message>Multiple condition headers are not supported.
RequestId:ea50083f-001e-001e-17ae-6a2241000000
Time:2024-02-29T01:29:56.0342331Z</Message></Error>

Headers:
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: ea50083f-001e-001e-17ae-6a2241000000
x-ms-client-request-id: e58122ff-3166-40de-83b1-7040f0e155c9
x-ms-version: 2023-01-03
x-ms-error-code: MultipleConditionHeadersNotSupported
Date: Thu, 29 Feb 2024 01:29:55 GMT
Content-Length: 250
Content-Type: application/xml

   at Azure.Storage.Blobs.BlockBlobRestClient.UploadAsync(Int64 contentLength, Stream body, Nullable`1 timeout, Byte[] transactionalContentMD5, String blobContentType, String blobContentEncoding, String blobContentLanguage, Byte[] blobContentMD5, String blobCacheControl, IDictionary`2 metadata, String leaseId, String blobContentDisposition, String encryptionKey, String encryptionKeySha256, Nullable`1 encryptionAlgorithm, String encryptionScope, Nullable`1 tier, Nullable`1 ifModifiedSince, Nullable`1 ifUnmodifiedSince, String ifMatch, String ifNoneMatch, String ifTags, String blobTagsString, Nullable`1 immutabilityPolicyExpiry, Nullable`1 immutabilityPolicyMode, Nullable`1 legalHold, Byte[] transactionalContentCrc64, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlockBlobClient.UploadInternal(Stream content, BlobHttpHeaders blobHttpHeaders, IDictionary`2 metadata, IDictionary`2 tags, BlobRequestConditions conditions, Nullable`1 accessTier, BlobImmutabilityPolicy immutabilityPolicy, Nullable`1 legalHold, IProgress`1 progressHandler, UploadTransferValidationOptions transferValidationOverride, String operationName, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlockBlobClient.<>c__DisplayClass64_0.<<GetPartitionedUploaderBehaviors>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Azure.Storage.PartitionedUploader`2.UploadInternal(Stream content, Nullable`1 expectedContentLength, TServiceSpecificData args, IProgress`1 progressHandler, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobClient.StagedUploadInternal(Stream content, BlobUploadOptions options, Boolean async, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Primitives.BlobCheckpointStoreInternal.ClaimOwnershipAsync(IEnumerable`1 desiredOwnership, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Primitives.EventProcessor`1.DelegatingCheckpointStore.ClaimOwnershipAsync(IEnumerable`1 desiredOwnership, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Primitives.PartitionLoadBalancer.RenewOwnershipAsync(CancellationToken cancellationToken)`

**Comment by jsquire** [comment]
Thanks for the context, @ddouglas-msft.   Now I get what you're trying to do.   You're not looking to add caching, but to explicitly forbid it.  I don't think we'd want to toggle that as an option, if we think it's the right approach, it should be emitted for all scenarios.

I'd like to ask our friends in the Azure Storage team to offer thoughts on whether this is something they would recommend.  @xgithubtriage:  I'd appreciate your thoughts.

//cc: @amnguye, as they were point person on the linked issue.

**Comment by amnguye** [comment]
Ideally any proxy that is forcing the cache on these properties should be disabled. As altering HTTP request can cause more issues than just this error popping up.

However I do understand that sometimes you can't control who's using your application in the environment given.

If you're fine with setting this property when the blob is created. Dependent on the blob type you can set the `CacheControl` value when you create the blob (e.g. Page / Append Blobs accept this header on Create call, same with single Put Blob requests, and Commit Block List requests). This should save the Cache Control on the blob itself and persist the property.

https://learn.microsoft.com/en-us/rest/api/storageservices/put-blob?tabs=microsoft-entra-id#blob-custom-properties

The risk I see doing this something like "no-cache" or "max-age=0" is that the client tells the service that it has to revalidate every single time. (see https://www.rfc-editor.org/rfc/rfc7234 ). Which may not be a huge risk to certain applications.

**Comment by jsquire** [comment]
Thanks, @amnguye.   Just to be sure that I'm not overlooking something, the revalidation risk that you're referring to is a performance/reliability concern, right?

**Comment by amnguye** [comment]
@jsquire Correct. So with this header, you would lose the benefits of caching. Which means when the request is hitting the service, it can cause an increase in server load.

Which dependent on how much server load there is to the respective storage account can cause more reliability concerns (e.g. receiving more 500's, causing the request to retry).

This should definitely be an optional thing that the client should do, only if they're willing to take on the risk of slower performance when there's higher traffic. However if there's not much traffic hitting the storage account in the first place, there might be no risk at all.

**Comment by jsquire** [comment]
@ddouglas-msft:  We're going to poke at this a bit and discuss before making decisions.   In the meantime, since your application creates Blob Storage client used by the checkpoint store, you can extend via [synchronous policy](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Pipeline.md#implementing-a-synchronous-policy) to force non-cache headers to be emitted.

**Comment by ddouglas-msft** [comment]
Hello @jsquire . Thanks for your help. I've been doing some experimenting and I know what's happening that's causing the problem. 

The problem is we had a TTL policy because the blobs in one container needs to be deleted after 48 hours for regulatory reasons. This seems to be the core issue so I'm updating the policy in Azure Storage. I've been able to replicate this by deleting all of the blobs in or dev environment to see if this is the issue. I've noticed though that even after setting CacheControl to max-age=0, after an hour, it still never mitigates. So I can't say for sure that updating the cache actually works. I'm going to look into how I can get the SDK to be able to recover. So far the only thing that has worked is restarting the service.

**Comment by jsquire** [comment]
Hi @ddouglas-msft:  We've explored this idea internally and we don't feel that it's appropriate for the general use case, nor even as an option given the side-effects.  If you need to emit cache-control headers directly for your scenario, you can do so by adding a synchonous policy to the options that you pass when creating your blob client, as demonstrated in [this sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Pipeline.md#implementing-a-synchronous-policy). 

If you wanted to change the approach used to create blobs, you could also do that by implementing your own [CheckpointStore](https://learn.microsoft.com/dotnet/api/azure.messaging.eventhubs.primitives.checkpointstore?view=azure-dotnet) _([src](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/src/Primitives/CheckpointStore.cs))_ using our implementation as a reference _([src](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/BlobCheckpointStore/BlobCheckpointStoreInternal.cs))_ and then passing that to your processor.
