### ISSUE TITLE
Generate SDK script improvements

### ISSUE THREAD

**Issue by shahabhijeet** [Azure/azure-sdk-for-net#4231]
- Allow a way to get rid of relative path to master generate.ps1
- Allow to generate meta data into .cs file into the sdk directory rather inside _metadata directory
- For incorrect meta data, it should fail build.

Fields needed in SDK_*.cs
AutoRestVersion =
AutoRestbootStrapversion
AutoRestCmdUsed
GithubForkname
GithubBranchName
GithubCommidId
GenerationErrorDetected

Cost: 3

**Comment by dsgouda** [comment]
1. Is already implemented
2. Inject metadata into class members
3. Incorrect metadata failure is for a future step

If code generation fails, push the data to cs file and fail the build.

**Comment by dsgouda** [comment]
Will be merged here https://github.com/Azure/azure-sdk-for-net/pull/4648
