### ISSUE TITLE
Generate SDK and compare with generated SDK

### ISSUE THREAD

**Issue by shahabhijeet** [Azure/azure-sdk-for-net#4233]
Currently there is no easy way to make sure the generated SDK in PR is actually generated from the spec repo.
Have a way to generate SDK as part of the CI and compare it with the PR generated SDK.
Work for breaking change tool

**Comment by dsgouda** [comment]
Breaking down this tasks into some deliverables I can think of:

- Figure out APIs including Auth methods to query github for metadata related to an open PR
  - Also to make commits on behalf of a user or azuresdkci in automated workflow moving forward
- Once we figure out the files modified in a PR, we need to scope the builds, This should be our iteration 1
- Next step would be figuring out affected SDKs (and corresponding generate.ps1s) so we can execute them and compare files for those SDKs. 
  -This might involve rewriting the generate.ps1 scripts as an msbuild task instead
  - This should also include ability to fail a build if there are issues generating the code or if there are unexpected changes involved in the generated SDK vs SDK PR


@shahabhijeet PTAL and add points I may have missed

**Comment by pakrym** [comment]
This is done for Track 2 SDKs. I don't think we are going to back port it into track 1.
