### ISSUE TITLE
Ref docs /// issue: KeyVaultClientExtensions.GetSecretAsync Method (Microsoft.Azure.KeyVault) Does not document exceptions thrown

### ISSUE THREAD

**Issue by CamSoper** [Azure/azure-sdk-for-net#4235]
@paulhickman-a365 commented on [Fri Apr 06 2018](https://github.com/Azure/azure-docs-sdk-dotnet/issues/573)

Can you add documentation on the exceptions thrown by extension methods. This is present for the normal methods of the KeyVaultClient but not the extensions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac49d6d8-a550-3da9-0cdb-a70aea52eb3a
* Version Independent ID: 6cab7777-3293-3262-b87d-3dcde5e0e528
* Content: [KeyVaultClientExtensions.GetSecretAsync Method (Microsoft.Azure.KeyVault)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.keyvault.keyvaultclientextensions.getsecretasync?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.KeyVault/KeyVaultClientExtensions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.KeyVault/KeyVaultClientExtensions.xml)
* Service: **key-vault**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by heaths** [comment]
Microsoft.Azure.KeyVault has been deprecated. We recommend using any of:

* https://www.nuget.org/packages/Azure.Security.KeyVault.Certificates
* https://www.nuget.org/packages/Azure.Security.KeyVault.Keys
* https://www.nuget.org/packages/Azure.Security.KeyVault.Secrets

These should document any expected exceptions (e.g. `RequestFailedException` or `ArgumentNullException`) appropriately.
