### ISSUE TITLE
Ref docs /// issue: DeploymentPropertiesExtended.ProvisioningState Property (Microsoft.Azure.Management.ResourceManager.Models) ProvisioningState  Documentation Needs Improvement

### ISSUE THREAD

**Issue by CamSoper** [Azure/azure-sdk-for-net#4236]
@thepenguinmaster commented on [Wed Apr 04 2018](https://github.com/Azure/azure-docs-sdk-dotnet/issues/568)

Because provisioning state is a string which is ambiguous, it would be important to list the possible values, or provide an enumeration for this field. At the very least, possible values for deployment states should be listed. 
"Provisioning State (Get) - Gets the state of provisioning" is not proper documentation IMO. Typically when writing documentation it is bad practice to simply add spaces to the name of the item being described with small changes in word order. Some elaboration here would be beneficial. I assume this documentation is auto generated and simply needs to be filled in. 

**Reasoning**: 
There are many times when in an application you may want to make decisions based on the state of a deployment. Having a list of know values would be helpful for this, since it is difficult/impossible to know what will come from Azure in this case. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8cd038f-7db0-6ab1-bc3a-b4d509f35947
* Version Independent ID: 39120ec7-7010-6a56-c17c-a9e00d598fd0
* Content: [DeploymentPropertiesExtended.ProvisioningState Property (Microsoft.Azure.Management.ResourceManager.Models)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.resourcemanager.models.deploymentpropertiesextended.provisioningstate?view=azure-dotnet#Microsoft_Azure_Management_ResourceManager_Models_DeploymentPropertiesExtended_ProvisioningState)
* Content Source: [xml/Microsoft.Azure.Management.ResourceManager.Models/DeploymentPropertiesExtended.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.ResourceManager.Models/DeploymentPropertiesExtended.xml)
* Service: **azure-resource-manager**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by Technolink** [comment]
👍 it would be nice when writing my code if I could know what to expect here, rather than just trial and error. Just now I found out that when I create an AADDS, the state is "Succeeded", but a few minutes later the state returns "Creating". This caused some automation to fail.

**Comment by rsimac** [comment]
I would also like to see the list of 'provisioning states', needed for proper and dependable automation design and implementation. For example, the resource groups fail to delete when having deployments in certain states, and no way to design the code other than tedious and time consuming trial and error - with no guarantee the expected 'strings' will remain unchanged in future (or same) sdk releases. Thanks.

**Comment by jsquire** [comment]
The `Microsoft.Azure.Management.ResourceManager` library has since been deprecated and is slated for retirement.  It is currently receiving only critical security fixes.  Closing this out.
