### ISSUE TITLE
[FEATURE REQ] Azure.Monitor.OpenTelemetry - synchronize TargetFramework across packages

### ISSUE THREAD

**Issue by christophwille** [Azure/azure-sdk-for-net#42360]
### Library name and version

1.0.0-beta.2

### Describe the bug

https://www.nuget.org/packages/Azure.Monitor.OpenTelemetry.LiveMetrics#dependencies-body-tab

vs

https://www.nuget.org/packages/Azure.Monitor.OpenTelemetry.Exporter

What has gotten us into trouble is that the former package has only a netstandard2.0 target whereas the older .Exporter also has a net6.0 target. The problematic bit was the Microsoft.Bcl.AsyncInterfaces dependency that implicity was expected as 8.0.0 from another library (FastEndpoints).

### Expected behavior

Can we please have identical targets for all Azure.Monitor.OpenTelemetry packages including net8.0?

### Actual behavior

n/a

### Reproduction Steps

n/a

**Comment by TimothyMothra** [comment]
- Related to Microsoft.Bcl.AsyncInterfaces https://github.com/Azure/azure-sdk-for-net/issues/41747
- Related to .NET 8 https://github.com/Azure/azure-sdk-for-net/issues/40026

**Comment by christophwille** [comment]
I read the other issues - I should have noted that F5 on Windows and integration tests on Ubuntu worked, where it started to fail was a dotnet publish as a container (the first two run with packages, the published app with copy-local assemblies). Which was nasty to diagnose if basically "everything" works and only a deployment shows this behavior.

**Comment by TimothyMothra** [comment]
Hi @christophwille Thanks for reporting the issue. We've had a handful of reports of the Bcl.AsyncInterfaces dependency but haven't had a repro yet. When I get some time, i'll take a look at FastEndpoints. If you're able to share a small repro, that would help speed up our investigation.


Regarding our target frameworks, I can summarize the current state:
All packages in this repo are required to target `netstandard2.0` (Exporter, AspNetCore, LiveMetrics). Any additional TFMs are optional. The Exporter package has a requirement to support AOT, so this package includes `net6`. This repo doesn't yet support `net8`

**Comment by TimothyMothra** [comment]
I can confirm that this reproduces with FastEndpoints. Investigating a fix.

**Comment by TimothyMothra** [comment]
We released a new version of Azure.Monitor.OpenTelemetry.LiveMetrics that we believe addresses this issue.
https://www.nuget.org/packages/Azure.Monitor.OpenTelemetry.LiveMetrics/1.0.0-beta.3

If you have any more issues, please respond.
