### ISSUE TITLE
Inline ref-doc (///) issue: VirtualMachineExtension.ForceUpdateTag Property (Microsoft.Azure.Management.Compute.Models) Valid Values for ForceUpdateTag

### ISSUE THREAD

**Issue by CamSoper** [Azure/azure-sdk-for-net#4238]
@timomta commented on [Mon Apr 02 2018](https://github.com/Azure/azure-docs-sdk-dotnet/issues/563)

The property says it is a string, but it is not clear what the valid values for it are? What do you set it do? How do you use the property?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d21c75a-6859-0f6b-d1e6-670474faa61e
* Version Independent ID: cc2bd435-0df1-8fd2-b8d9-3ab31d8ed838
* Content: [VirtualMachineExtension.ForceUpdateTag Property (Microsoft.Azure.Management.Compute.Models)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.compute.models.virtualmachineextension.forceupdatetag?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Management.Compute.Models/VirtualMachineExtension.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.Compute.Models/VirtualMachineExtension.xml)
* Service: **big-compute**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by huangpf** [comment]
@hyonholee @huangpf

As triaged, it's likely a doc issue, and Swagger spec issue.

**Comment by CamSoper** [comment]
@huangpf - Correct, it's probably propagated all the way from the Swagger spec.  I'm sorry, I should have put more in the description.  I'm the maintainer of the Azure SDK docs, and customer @timomta created this issue on my repo, so I cloned it over here.

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
