### ISSUE TITLE
Inline ref doc /// issue: Microsoft.Azure.Management.DataFactory Better error handling and documentation for deleting elements of an ADF

### ISSUE THREAD

**Issue by CamSoper** [Azure/azure-sdk-for-net#4239]
@Goldensunboy commented on [Mon Apr 02 2018](https://github.com/Azure/azure-docs-sdk-dotnet/issues/561)

When using Microsoft.Azure.Management.DataFactory operations extensions functions from TriggersOperationsExtensions, PipelinesOperationsExtensions, DatasetsOperationsExtensions or LinkedServicesOperationsExtensions to respectively delete elements of an ADF (using the Delete function), if there is a failure of any kind then the function throws:

> Microsoft.Azure.Management.DataFactory.Models.ErrorResponseException: Operation returned an invalid status code 'BadRequest'

It would be very helpful if the exceptions thrown by these functions were more descriptive of the underlying problem (for example, "attempt to delete LinkedService \<Lname\> which Dataset \<Dname\> depends on"), and if the following pages would describe the possible failure scenarios:

[TriggersOperationsExtensions](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.datafactory.triggersoperationsextensions?view=azure-dotnet)
[PipelinesOperationsExtensions](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.datalake.analytics.pipelineoperationsextensions?view=azure-dotnet)
[DatasetsOperationsExtensions](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.datafactory.datasetsoperationsextensions?view=azure-dotnet)
[LinkedServicesOperationsExtensions](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.datafactory.linkedservicesoperationsextensions?view=azure-dotnet)

**Comment by hvermis** [comment]
We have improved most of our error handling and are returning better messages.
We  continue to improve this as an ongoing effort.
The documentation however is autogenerated, and it doesn't include the exceptions. The message shown to the user will be clear enough and we are adding troubleshooting docs for ADF that will cover these scenarios.
