### ISSUE TITLE
[IoT] 404 on "Explore the client Apis" button link

### ISSUE THREAD

**Issue by ingie** [Azure/azure-sdk-for-net#42403]
### Type of issue

Other (describe below)

### Description

On Page : https://learn.microsoft.com/en-us/dotnet/api/overview/azure/iot?view=azure-dotnet#client-library

Button link at bottom, labelled "Explore the client Apis" 

leads to https://learn.microsoft.com/en-us/dotnet/api/overview/azure/iot/client - which is a dead link / 404

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/overview/azure/iot?view=azure-dotnet#client-library

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/latest/iot.md

### Document Version Independent Id

4973d389-cf56-a951-e3f8-859089d7bd23

### Article author

@azure-sdk

### Metadata

* ID: 0124d728-3cb7-13a2-ff42-864d9ac59b71 
* Service: **iot**

**Comment by timtay-microsoft** [comment]
Since this is a problem with the [azure-docs-sdk-dotnet repo](https://github.com/Azure/azure-docs-sdk-dotnet/) and not an issue with this repo, I've [opened an issue over there](https://github.com/Azure/azure-docs-sdk-dotnet/issues/2429) instead and will close this thread.
