### ISSUE TITLE
[QUERY] Number of sessions in Azure Service Bus

### ISSUE THREAD

**Issue by MykolaKushnarenko** [Azure/azure-sdk-for-net#42404]
### Library name and version

Azure.Messaging.ServiceBus

### Query/Question

How to fetch the number of sessions from the queue/topic? In the documentation, there is no such functionality described. 
Would it be at all possible for you to provide any useful information concerning this query?

**Comment by jsquire** [comment]
Hi @MykolaKushnarenko.  The Service Bus service does not currently provide an API to query the sessions for an entity.   As a result, the client cannot support the feature.  To request the feature for the service, your best path forward would be to open an issue in the [Azure Service Bus repository](https://www.github.com/Azure/azure-service-bus/issues) or consider posting to the [Azure Feedback site](https://feedback.azure.com/d365community).

I'm going to close this out; if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.

**Comment by MykolaKushnarenko** [comment]
@jsquire thanks for your replay! 
What about some other approaches to how we could get this info? Maybe there are some workarounds to use. 
I would appreciate any into on this.

Thanks in advance!

**Comment by jsquire** [comment]
To our knowledge, the service does not expose this information.  There are no work-arounds that I can offer.

**Comment by bastyuchenko** [comment]
@jsquire but [ServiceBusExplorer](https://github.com/paolosalvatori/ServiceBusExplorer) somehow returns number of sessions. It seems there was possibility to retrive the number of sessions in .NET Framework. Any reason why it was declined in new versions of .NET? Can we use direct call to some AMQP endpoints of Azure Service Bus as a workaround?

We want to scale number of instances of our Azure Service Bus queue consumer based on the number of sessions in a queue.

**Comment by jsquire** [comment]
To my knowledge, Service Bus Explorer uses the legacy Service Bus library which uses SBMP as well as AMQP.  I do not know if there was an SBMP call that would provide this information nor what it is using.  However, the version that exists for AMQP does not work as a caller would expect.  In a nutshell, it only enumerates sessions that have session state associated with it, does not limit to sessions with active messages, and does not return data consistently.  

Further details and discussion can be found in:

- [[FEATURE REQ] Get Session Information for a Queue/Subscription - Azure.Messaging.ServiceBus](https://github.com/Azure/azure-sdk-for-net/issues/20569)
- [GetMessageSessions in a queue](https://github.com/Azure/azure-service-bus/issues/275)
