### ISSUE TITLE
Application Insights shows 400-499 response codes even though failed requests have been filtered in a processor

### ISSUE THREAD

**Issue by MikhailIvanou** [Azure/azure-sdk-for-net#42411]
### Library name and version

Azure.Monitor.OpenTelemetry.Exporter 1.2.0

### Describe the bug

We ran into a weird problem, in our code we have a processor that filters requests with status code 499,
like that:

```
public class OurVeryGoodProcessor : BaseProcessor<Activity>
{
    public override void OnEnd(Activity activity)
    {
        var statusCode = activity.GetTagItem("http.response.status_code")?.ToString() ?? string.Empty;

        if (statusCode == "499")
        {
            activity.IsAllDataRequested = false;
            activity.ActivityTraceFlags &= ~ActivityTraceFlags.Recorded;
        }
    }
}
```
it works perfectly fine (here is a query from our AI instance):
![image](https://github.com/Azure/azure-sdk-for-net/assets/9464479/f39fa97e-fcf9-49dc-8e7c-11abfb67a542)
there are no signs of any telemetry item with status code 499 in corresponding Log Analytics Workspace at all

but if we take a look at "Failures" tab (the same AI instance) we see:
![image](https://github.com/Azure/azure-sdk-for-net/assets/9464479/c37cb12e-74c2-4a24-aa14-0f0cc0d5f7fc)

It is worth mentioning that we see the stats with 499 response codes only for last 24h interval, if you increase it to e.g. 3 days those requests magically disappear
![image](https://github.com/Azure/azure-sdk-for-net/assets/9464479/ecb82172-5e6d-48e0-9755-9ab001d0f403)

So, AppIns gathers 400-499 statistics for unknown for us reasons and it is quite misleading.
We would like to disable it. Do you have any idea how to do it?

### Expected behavior

there is no 499 response codes in "Failures" tab 

### Actual behavior

there is 499 response codes in "Failures" tab

### Reproduction Steps

1. ASP.NET Core app + OTel + AI Exporter + Processor like described above
2. Craft a request with 400-499 response code
3. Check "Top 3 response codes" on AI Failure tab

### Environment

.net 8.0, asp.net core
Azure.Monitor.OpenTelemetry.AspNetCore 1.1.0
Azure.Monitor.OpenTelemetry.Exporter 1.2.0

**Comment by TimothyMothra** [comment]
Hi. Sorry for the delay, thanks for opening this issue.

In short, the current behavior is working as intended.
There is an internal feature we call "standard metrics" which summarizes all requests received by your application.
This is designed to supplement sampling. If for example a user was sampling only 10% of their total requests, our sdk would still report 100% of the observed response codes.


I fully understand your confusion here. 
We're having discussions with the product team to determine if we should handle this differently.
If you have any other comments feel free to leave them here and I'll make sure it's included in the conversation.
