### ISSUE TITLE
I prefer `isExisting` not be on the parameter list and is just set in the ctor with `init`

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#42422]
I prefer `isExisting` not be on the parameter list and is just set in the ctor with `init`

_Originally posted by @m-nash in https://github.com/Azure/azure-sdk-for-net/pull/42416#discussion_r1513404033_

**Comment by tg-msft** [comment]
This has been changed to a static `FromExisting` like https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/provisioning/Azure.Provisioning.Storage/src/Generated/StorageAccount.cs#L551
