### ISSUE TITLE
[OpenAI] Implement preview `ChatClient`'s convenience methods

### ISSUE THREAD

**Issue by joseharriaga** [Azure/azure-sdk-for-net#42438]
```[tasklist]
- [ ] Convenience methods
- [ ] Models and model factory methods
- [ ] Architecture review
```

Complete the tasks above for each of the following features:
1. Create chat completion

**Comment by pallavit** [comment]
Curious why we call this ChatClient and not ChatCompletionClient? We do have ChatCompletetion* names in the APIView?

**Comment by joseharriaga** [comment]
> Curious why we call this ChatClient and not ChatCompletionClient? We do have ChatCompletetion* names in the APIView?

This is to align with OpenAI's documentation, where they refer to it as the Chat APIs.
