### ISSUE TITLE
[OpenAI] Implement preview `CompletionClient`'s protocol methods

### ISSUE THREAD

**Issue by joseharriaga** [Azure/azure-sdk-for-net#42448]
```[tasklist]
- [x] Create completion
```

**Comment by pallavit** [comment]
Given CompletionAPI is now legacy - why do we still want to add support for this? Should the support here be minimal?

**Comment by joseharriaga** [comment]
> Given CompletionAPI is now legacy - why do we still want to add support for this? Should the support here be minimal?

Yes, we're only doing protocol methods for this one.
