### ISSUE TITLE
[OpenAI] Implement preview `ModelManagementClient`'s convenience methods

### ISSUE THREAD

**Issue by joseharriaga** [Azure/azure-sdk-for-net#42445]
```[tasklist]
- [x] Convenience methods
- [x] Models and model factory methods
- [x] Architecture review
```

Complete the tasks above for each of the following features:
1. List models
2. Retrieve model
3. Delete a fine-tuned model

**Comment by pallavit** [comment]
My initial thought here is that this is among the least used feature of the OpenAI client? Should this be a p1 from that perspective? That is we may choose to do it post our current release?
