### ISSUE TITLE
[OpenAI] Implement preview `AssistantClient`'s convenience methods

### ISSUE THREAD

**Issue by joseharriaga** [Azure/azure-sdk-for-net#42447]
```[tasklist]
- [x] Convenience methods
- [x] Models and model factory methods
- [x] Architecture review
```

Complete the tasks above for each of the following features:
1. Create assistant
2. Create assistant file
3. List assistants
4. List assistant files
5. Retrieve assistant
6. Retrieve assistant file
7. Modify assistant
8. Delete assistant
9. Delete assistant file
10. Create thread
11. Retrieve thread
12. Modify thread
13. Delete thread
14. Create message
15. List messages
16. List message files
17. Retrieve message
18. Retrieve message file
19. Modify message
20. Create run
21. Create thread and run
22. List runs
23. List run steps
24. Retrieve run
25. Retrieve run step
26. Modify run
27. Submit tool outputs to run
28. Cancel run

**Comment by pallavit** [comment]
Given all CRUD operations and object hierarchies here, do you have a sense of whether some should be at protocol only for now? Or do you see us being able to support basic convenience for every one of them?
