### ISSUE TITLE
[QUERY] Why is TableEntity sealed in the latest azure .net sdk?

### ISSUE THREAD

**Issue by omatrot** [Azure/azure-sdk-for-net#42454]
### Library name and version

Azure.Data.Tables 12.8.3

### Query/Question

I'm in the process of porting a .NET 4.7.1 Azure Worker project to multiple azure functions using the latest version of the Azure Sdk.
The old code, is using **TableEntity** and inherit from this class.
Unfortunately, this class is sealed now in the **Azure.Data.Tables** nugget.

I may be wrong but the migration guide does not talk about this breaking change. I do not know how to migrate the following code:

```
using Microsoft.WindowsAzure.Storage.Table;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SC.TM.Core.TableStorage
{
    public abstract class TableStorageItem : TableEntity
    {
        public TableStorageItem() { }

        public TableStorageItem(string partitionKey, string rowKey): base(partitionKey, rowKey) { }
      
    }
}
```

Any help appreciated.

For the record, Bing Conversation, when asked to convert the code to the latest version of the Sdk, pretends that the class is not sealed ;)

### Environment

.NET SDK:
 Version:           8.0.201
 Commit:            4c2d78f037
 Workload version:  8.0.200-manifests.3097af8b

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.3
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.201/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.2
  Architecture: arm64
  Commit:       1381d5ebd2

.NET SDKs installed:
  6.0.202 [/usr/local/share/dotnet/sdk]
  6.0.203 [/usr/local/share/dotnet/sdk]
  6.0.300 [/usr/local/share/dotnet/sdk]
  6.0.401 [/usr/local/share/dotnet/sdk]
  6.0.402 [/usr/local/share/dotnet/sdk]
  6.0.403 [/usr/local/share/dotnet/sdk]
  6.0.404 [/usr/local/share/dotnet/sdk]
  6.0.405 [/usr/local/share/dotnet/sdk]
  6.0.406 [/usr/local/share/dotnet/sdk]
  6.0.407 [/usr/local/share/dotnet/sdk]
  6.0.408 [/usr/local/share/dotnet/sdk]
  6.0.410 [/usr/local/share/dotnet/sdk]
  7.0.100 [/usr/local/share/dotnet/sdk]
  7.0.101 [/usr/local/share/dotnet/sdk]
  7.0.200 [/usr/local/share/dotnet/sdk]
  7.0.202 [/usr/local/share/dotnet/sdk]
  7.0.203 [/usr/local/share/dotnet/sdk]
  7.0.302 [/usr/local/share/dotnet/sdk]
  7.0.304 [/usr/local/share/dotnet/sdk]
  8.0.201 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.12 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.14 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.15 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.16 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.18 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.18 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet/x64]
    registered at [/etc/dotnet/install_location_x64]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
HI @omatrot - 
Could you clarify what you are trying to accomplish with your child class of TableEntity? As an alternative you can create a custom class that implements `ITableEntity`.

**Comment by omatrot** [comment]
Sure, here is the code:

```
using Microsoft.WindowsAzure.Storage.Table;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SC.TM.Core.TableStorage
{
    public abstract class TableStorageItem : TableEntity
    {
        public TableStorageItem() { }

        public TableStorageItem(string partitionKey, string rowKey): base(partitionKey, rowKey) { }
      
    }
}
```

```
using Microsoft.WindowsAzure.Storage.Table;
using SC.TM.Core.Cloud.TableStorage;
using SC.TM.Core.Service.NotificationService;
using System;

namespace SC.TM.Core.TableStorage
{
    public class NotificationItem : TableStorageItem
    {
        public NotificationItem() { }

        /// <summary>
        /// constuctor: partitionKey is the recipient, RowKey is build with chronologicalkey system to be able to take only last notifs.
        /// </summary>
        /// <param name="recipientAppLoginId">The unique identifier (AppLoginId) of the recipient of this notification</param>
        /// <param name="type">type of the notification</param>
        public NotificationItem(int recipientAppLoginId, NotificationType type) : 
            base(recipientAppLoginId.ToString(), TableStorageChronologicalKeyGenerator.CreateChronologicalKey(TableStorageChronologicalKeyGeneratorDirection.Descending))
        {
            this.Type = type.ToString();
            this.AlreadyRead = false;
        }

        [IgnoreProperty]
        public int RecipientAppLoginId
        {
            get { return Int32.Parse(this.PartitionKey); }
        }

        public int? TenantId { get; set; }

        public string NotificationTitle { get; set; }

        public string Type { get; set; } //type of the notification 

        [IgnoreProperty]
        public NotificationType NotificationType
        {
            get { return NotificationTypeHelper.ParseNotificationType(this.Type); }
        }

        public bool AlreadyRead { get; set; }

        public string ProjectName { get; set; }
        public int? ProjectId { get; set; }

        public string LeadName { get; set; }
        public int? LeadId { get; set; }

        public string CandidateFullName { get; set; }

        public int? CandidateId { get; set; }

        public string CompanyName { get; set; }

        public int? InitiatorId { get; set; }
        public string InitiatorFullName { get; set; }

        #region Properties used by Search Alert Notification

        public int? NbNewContact { get; set; }

        public string SavedSearchName { get; set; }

        #endregion

        #region Properties used by Current Day Interview Notification

        public DateTime? InterviewDate { get; set; }

        #endregion

        #region Properties used by Presentation to Stakeholder Notification & Presentation Acknowledgment Notification


        public string PresentationIds { get; set; }
        public string PresentedCandidates { get; set; }


        #endregion

        //#region Properties used Mention Notification

        //public string Mention { get; set; }

        //#endregion

        public string ExtraInfo { get; set; }

        [IgnoreProperty]
        public int? MinuteSinceTimeStamp
        {
            get
            {
                return (int)Math.Ceiling((DateTime.UtcNow - this.Timestamp.UtcDateTime).TotalMinutes);
            }
        }
    }
}
```


```
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Table;
using SC.TM.Core.TableStorage;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SC.TM.Core.Cloud.TableStorage
{
    public sealed class NotificationTableStorage : TableStorage<NotificationItem>
    {
        public const string TABLE_NAME = "Notification";

        public NotificationTableStorage() : base(TABLE_NAME)
        { }

     

        /// <summary>
        /// Checks if a particular row already exists into the table or not.
        /// </summary>
        /// <param name="notifRowKey">bound to the table row key.</param>
        /// <param name="ownerId">bound to the table partition key.</param>
        /// <returns>Returns true if the row already exists, false otherwise.</returns>
        public bool RowExists(string notifRowKey, int ownerId)
        {
            if (!this.TableExist())
                return false;

            TableOperation retrieveOperation = TableOperation.Retrieve<NotificationItem>(notifRowKey, ownerId.ToString());
            TableResult retrievedResult = table.Execute(retrieveOperation);
            return (retrievedResult.Result != null);
        }
    }
}
```

As you can see the existing code relies on the ability to inherit from TableIdentity to use Azure table storage. I have many many classes like **NotificationItem**.

**Comment by omatrot** [comment]
Sometimes I need to override ReadEntity & Write Entity:

```
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Table;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SCTM.Core.TableStorage
{
    public class AnalyticsDataTableItem<AnalyticsDataBag> : TableStorageItem
    {
        //public AnalyticsDataTableItem(int tenantId, DateTime date, int userId) : base()
        //{
        //    this.PartitionKey = BuildPartitionKey(tenantId, userId);
        //    this.RowKey = BuilRowKey(date);
        //}

        public AnalyticsDataTableItem() : base()
        { }


        //public string BuildPartitionKey(int tenantId, int userId)
        //{
        //    return $"{tenantId}-{userId}";
        //}

        //public abstract string BuilRowKey(DateTime date);

        public AnalyticsDataBag DataBag { get; set; }

        public override IDictionary<string, EntityProperty> WriteEntity(OperationContext operationContext)
        {
            var results = base.WriteEntity(operationContext);
            var extentedProp = EntityPropertyConverter.Flatten(this.DataBag, operationContext);
            foreach (var kvp in extentedProp)
                results.Add(kvp.Key, kvp.Value);

            return results;
        }

        public override void ReadEntity(IDictionary<string, EntityProperty> properties, OperationContext operationContext)
        {
            base.ReadEntity(properties, operationContext);

            this.DataBag = EntityPropertyConverter.ConvertBack<AnalyticsDataBag>(properties, operationContext);
        }
    }
}
```

**Comment by christothes** [comment]
In your `NotificationItem` example, that seems like it would work implementing `ITableEntity` rather than extending `TableEntity`.

The Azure.Data.Tables SDK doesn't expose full control over serialization, so overriding `ReadEntity` and `WriteEntity` is not possible. There is an outstanding [feature request](https://github.com/Azure/azure-sdk/issues/5760) to add such support, however.
