### ISSUE TITLE
[BUG] EventGridEvent requires optional Data property

### ISSUE THREAD

**Issue by cbotos** [Azure/azure-sdk-for-net#42453]
### Library name and version

Azure.Messaging.EventGrid 4.22.0

### Describe the bug

According to the documentation at https://learn.microsoft.com/en-us/azure/event-grid/event-schema#event-properties, the "Data" property for EventGridEvent is not required. However, when receiving and deserializing EventGridEvent JSON from a webhook without this property, the deserialization process will crash.

### Expected behavior

It should be capable of parsing the data even without this optional property.

### Actual behavior

![image_2024-03-06_092549156](https://github.com/Azure/azure-sdk-for-net/assets/36774019/bf4cde4c-efc5-4254-bc6f-94192c2530b6)

### Reproduction Steps

```c#       
        var data = BinaryData.FromString("""
            [
              {
                "id": "123e4567-e89b-12d3-a456-426614174000",
                "eventType": "Generic.Event.Type.Example",
                "subject": "category/123e4567-e89b-12d3-a456-426614174000",
                "dataVersion": "1.0",
                "metadataVersion": "1",
                "eventTime": "2024-02-15T14:30:00+00:00",
                "topic": "/subscriptions/123e4567-e89b-12d3-a456-426614174000/resourceGroups/example-rg/providers/Microsoft.EventGrid/domains/example-domain/topics/example-topic"
              }
            ]
            """);

        var events = EventGridEvent.ParseMany(data);
```

**Comment by jsquire** [comment]
Hi @cbotos.  Thank you for reaching out and we regret that you're experiencing difficulties.  The behavior of `EventGridEvent` is correct; the `data` element is defined as a required field by the [Event Grid REST API specification](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/eventgrid/data-plane/Microsoft.EventGrid/stable/2018-01-01/EventGrid.json#L162).   

As this appears to be an error in the docs, I've opened [#120505](https://github.com/MicrosoftDocs/azure-docs/issues/120505) in the MS Learn repository for the doc owners to correct the content.
