### ISSUE TITLE
AzureRegions enumeration in TextAnalytics is missing at least one value

### ISSUE THREAD

**Issue by rewilson** [Azure/azure-sdk-for-net#4248]
In `Microsoft.Azure.CognitiveServices.Language.TextAnalytics.Models`, there are five enum values:

```
Westus = 0,
Westeurope = 1,
Southeastasia = 2,
Eastus2 = 3,
Westcentralus = 4
```

However, `australiaeast` is also a supported endpoint for the TextAnalytics API, and so should be included in this enum.

**Comment by daggmano** [comment]
While I am particularly after AustraliaEast as well, it looks like TextAnalytics is available across a large swathe of regions now: https://westus.dev.cognitive.microsoft.com/docs/services/TextAnalytics.V2.0/operations/56f30ceeeda5650db055a3c7

**Comment by ChrisHMSFT** [comment]
Closing since we have updated the SDK to now take in the endpoint parameter instead of the region.

Thanks,
Chris
