### ISSUE TITLE
[OpenAI] [Scenario] Add conveniences to associate `BinaryData` with a file format

### ISSUE THREAD

**Issue by joseharriaga** [Azure/azure-sdk-for-net#42489]
For outputs: For example, when you generate an image and get it back as `BinaryData`, there should be an indication somewhere that this is a PNG (as opposed to this information only being available in the documentation).

For inputs: For example, when you pass an audio file as `BinaryData` to the `AudioClient`'s `TranscribeAudio` method, there should be a way to specify the file format to confirm that it corresponds to one of the supported types.

**Comment by pallavit** [comment]
Is it always expected to be PNG? Looking at the documentation here - https://platform.openai.com/docs/api-reference/images/object I did not see it mention that? Can this change any time in the future?
