### ISSUE TITLE
Swagger validation fails for a parameter already defined in the endpoint definition

### ISSUE THREAD

**Issue by dipinbehl** [Azure/azure-sdk-for-net#4249]
While updating an already existing API in the APIM via a powershell script, an error was thrown as '_Parsing error(s): All parameters in path template MUST be defined in path parameters collection. Not matched parameters names: Par1._'. 

The scenario being that there exists two endpoints in my swagger definition as
```
"/api/foo1/{bar}/{par1}":{  
         "get":{  
            "tags":[ ],
            "operationId":"ApiFoo1Get",
            "consumes":[  ],
            "produces":[  ],
            "parameters":[  
               {  
                  "name":"bar",
                  "in":"path",
                  "required":true,
                  "type":"string"
               },
               {  
                  "name":"par1",
                  "in":"path",
                  "required":false,
                  "type":"integer",
                  "format":"int32"
               }
            ],
            "responses":{  
               "200":{  
                  "description":"Success"
               }
            }
         }
```

 and

```
"/api/foo2/{par1}":{  
         "get":{  
            "tags":[  ],
            "operationId":"ApiFoo2Get",
            "consumes":[  ],
            "produces":[  ],
            "parameters":[  
               {  
                  "name":"Par1",
                  "in":"path",
                  "required":false,
                  "type":"integer",
                  "format":"int32"
               }
            ],
            "responses":{  
               "200":{  
                  "description":"Success"
               }
            }
         }
```

The swagger definition was generated with the help of swashbuckle and seems legit with the parameters defined in each endpoint that consumes it.

**Comment by shahabhijeet** [comment]
@dipinbehl I am not sure I understand what the issue is here.
Is this related to Azure .NET SDK? If yes I will need more information than what you have mentioned above.
Also a repro code snippet

**Comment by dipinbehl** [comment]
@shahabhijeet The above stated are the two snippets from a swagger definition for an API defined in an instance of APIM. While updating the same on the APIM instance, an error message was thrown as '_Parsing error(s): All parameters in path template MUST be defined in path parameters collection. Not matched parameters names: par1._'
Now, the swagger definition defines the 'par1' parameter but the APIM instance still fails to update the API definition stating that it was not found.

We have used a powershell script to update the API definition which does not show an error but the APIM deployment logs does. So I would rather say that this is an issue with the APIM's parser for swagger definition that Power SDK for Azure or .NET SDK for Azure

**Comment by jwettstrom** [comment]
I see the exact same issue, but going through the Azure Portal APIM site (not using PowerShell). The error shows up right away and you can't import the Open API (swagger) file. The format of the file looks perfectly right according to Open API spec and still complains about 'Not matched parameters names: xxx'.
 I am also using swashbuckle to generate the file.

**Comment by adrianhall** [comment]
Hello, My apologies for this being dropped.  Is this still an issue?
