### ISSUE TITLE
[FEATURE REQ] Support Session Consistency for CosmosDB Tables API accounts.

### ISSUE THREAD

**Issue by cplacemsft** [Azure/azure-sdk-for-net#42490]
### Library name

Azure.Data.Tables

### Please describe the feature.

Support session consistency for CosmosDB Tables API accounts.

While migrating from Microsoft.Azure.Cosmos.Table to Azure.Data.Tables, we discovered that Azure.Data.Tables does not support session consistency.  Our application is a few years old and the logic is such that it depends on the "read your own writes" guarantees provided by session consistency.  We are now in a position where we must:
1. Use strong consistency in our CosmosDB Tables API accounts.
2. Make significant changes to our application (that we would much rather not have to make).

Are there any other avenues available to us?  Or is session consistency supported and we're reading things wrong?  It was quite surprising to come to this realization since session consistency is the default behavior.  But I can also understand if the goal of the Azure.Data.Tables SDK is more for compatibility with applications migrating from table storage, and implementing the caching of session tokens was not in scope.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @cplacemsft - 
The consistency level is configurable in the portal. I just tried it with a Cosmos table API instance to confirm:

![image](https://github.com/Azure/azure-sdk-for-net/assets/1279263/bc4ed4a9-8524-4878-a4ac-849d1644eafd)

**Comment by cplacemsft** [comment]
> Hi @cplacemsft - The consistency level is configurable in the portal. I just tried it with a Cosmos table API instance to confirm:
> 
> ![image](https://private-user-images.githubusercontent.com/1279263/310936314-bc4ed4a9-8524-4878-a4ac-849d1644eafd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MjU3NjksIm5iZiI6MTcwOTgyNTQ2OSwicGF0aCI6Ii8xMjc5MjYzLzMxMDkzNjMxNC1iYzRlZDRhOS04NTI0LTQ4NzgtYTRhYy04NDlkMTY0NGVhZmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDdUMTUzMTA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2EwOGY1YjUwYTg1YmQyNjU0NDRhMWYzZWQ3NzE0ZmU5N2Y4NGRiYTc2OWVkNjZhMTQ2NTQxM2RiY2NhMDhiNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.O-HpSHzBahtMBKAqX4iX3LwjBWWkm_j86jG4cC2Iqe0)

The account(s) have been configured for Session consistency, and we know that the accounts support this because we've been using Microsoft.Azure.Cosmos.Table to this point, and the behavior we see is consistent with "read your own writes" consistency guarantees.

However, we no longer see this behavior after migrating our application to Azure.Data.Tables.  Instead, we see what looks like eventual consistency behavior.

Can you confirm if Azure.Data.Tables supports session consistency, and if so, how do we achieve that with this particular SDK?

**Comment by cplacemsft** [comment]
/unresolve

Re-opening issue.

**Comment by christothes** [comment]
Hi @cplacemsft 
Sorry, you are correct. This is not supported by the newer SDK.

Some context here - the older SDK used what is called the "direct mode API" which is similar to the interface used by the full Cosmos document DB API. The new Azure.Data.Tables SDK uses the REST API interface, which is shared with Azure Storage tables. The request level session management is not supported in the REST mode APIs. 

The only way to get the full cosmos functionality is to migrate to the full Cosmos nosql API/SDK.

**Comment by cplacemsft** [comment]
Thanks for the confirmation, that seems reasonable.  There are a few places in the documentation that should probably be updated so that's clearer for customers.  I have a PR for the migration guide.  Also the table in this page in particular is misleading:  https://learn.microsoft.com/en-us/azure/cosmos-db/table/introduction.

Thanks again for the quick response.
