### ISSUE TITLE
Azure Key Vault libraries for .NET broken GitHub links for version 3.x.x

### ISSUE THREAD

**Issue by paulomorgado** [Azure/azure-sdk-for-net#42506]
### Type of issue

Other (describe below)

### Description

The links point to inexistent resources:

### Version 3.x.x

The source code for the Azure Key Vault libraries for .NET is available on GitHub.

Use the following version 3.x.x libraries to work with certificates, keys, and secrets:

| Library | Reference | Package | Source |
|--------------------------------------|---------------------------------------------------------------|-------------------------------------------------------------------------------|-------------------------------------------------------------------------------|
|    Microsoft.Azure.KeyVault.Core    |    Reference   |    NuGet    |    [GitHub](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/keyvault/Microsoft.Azure.KeyVault.Core)    |
|    Microsoft.Azure.KeyVault.Cryptography    |    Reference    |    NuGet    |    [GitHub](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/keyvault/Microsoft.Azure.KeyVault.Cryptography)    |
|    Microsoft.Azure.KeyVault.Extensions    |      |    NuGet    |    [GitHub](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/keyvault/Microsoft.Azure.KeyVault.Extensions)    |
|    Microsoft.Azure.KeyVault.WebKey    |    Reference    |    NuGet    |    [GitHub](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/keyvault/Microsoft.Azure.KeyVault.WebKey)    |
|    Microsoft.Azure.KeyVault    |    Reference    |    NuGet    |    [GitHub](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/keyvault/Microsoft.Azure.KeyVault)    |

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/overview/azure/key-vault?view=azure-dotnet&source=docs

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/latest/key-vault.md

### Document Version Independent Id

a3e86a24-3caa-c378-90ac-3e7bcea62828

### Article author

@azure-sdk

### Metadata

* ID: c3f44732-15c3-8ed7-d153-6d67ec8425cb 
* Service: **keyvault**

**Comment by jsquire** [comment]
Hi @paulomorgado.  Thanks for reaching out and we regret that you're experiencing difficulties.  The v3.x line of Key Vault libraries has reached end-of-life and are no longer published nor supported by Microsoft.  The content on that page is quite outdated; I've opened [#2430](https://github.com/Azure/azure-docs-sdk-dotnet/pull/2430) to bring it up to the current state.
