### ISSUE TITLE
[QUERY] Consumers from the same consumer group listen to the same messages twice

### ISSUE THREAD

**Issue by bastyuchenko** [Azure/azure-sdk-for-net#42511]
### Library name and version

Azure.Messaging.EventHubs.Processor 5.11.0 Azure.Messaging.EventHubs 5.11.1

### Query/Question

I have my EventHub instance with 4 partitions. And I sent 10 events with the following PartitionKey: #pk5, #pk3, #pk4, #pk1, #pk4, #pk3, #pk2, #pk1, #pk5, #pk2.
Using ServiceBusExplorer I see the following picture how events were distriburted in partitions:

**PartitionId 0:** 
PartitionKey=[#pk3] SequenceNumber=[0]
PartitionKey=[#pk4] SequenceNumber=[1]
PartitionKey=[#pk4] SequenceNumber=[2]
PartitionKey=[#pk3] SequenceNumber=[3]

**PartitionId 1:** 
PartitionKey=[#pk1] SequenceNumber=[0]
PartitionKey=[#pk2] SequenceNumber=[1]
PartitionKey=[#pk1] SequenceNumber=[2]
PartitionKey=[#pk2] SequenceNumber=[3]

**PartitionId 2:** 
PartitionKey=[#pk5] SequenceNumber=[0]
PartitionKey=[#pk5] SequenceNumber=[1]

**PartitionId 3:** 
- no events

I launch 5 consumers in parrallel (5 instances of the EventProcessorClient) in the same $Default consumer group.

- ConsumerId: 66f03b54-e395-498a-8e69-5c37036e499d
- ConsumerId: 801c942f-fde2-4350-9dc0-906b1fa61df1
- ConsumerId: 92158784-abc6-40a0-929e-2f5f3482c9e3
- ConsumerId: 2fb3e34e-7bb4-444c-bcea-ec50ee503506
- ConsumerId: ff9ef0c3-8051-4ade-9bfc-4a0bc953a75d

I expected that all consumers will coordinate to balance work between them and if Consumer: 92158784-abc6-40a0-929e-2f5f3482c9e3 started listening to PartitionKey: #pk2 (PartitionId: 1), then ConsumerId: 2fb3e34e-7bb4-444c-bcea-ec50ee503506 won't listen to the same messages from PartitionKey: #pk2. However based on the log of my application below I see that sometimes different consumers in the same consumer group listen to the same messages

**ConsumerId: 92158784-abc6-40a0-929e-2f5f3482c9e3;** 
- _**PartitionKey: #pk2; SequenceNumbers that was listened by the consumer within PartitionKey: [1,3];**_
- PartitionKey: #pk1; SequenceNumbers that was listened by the consumer within PartitionKey: [0,2];

**ConsumerId: 801c942f-fde2-4350-9dc0-906b1fa61df1**
- PartitionKey: #pk3; SequenceNumbers that was listened by the consumer within PartitionKey: [0,3];
- PartitionKey: #pk4; SequenceNumbers that was listened by the consumer within PartitionKey: [1,2];

**ConsumerId: ff9ef0c3-8051-4ade-9bfc-4a0bc953a75d**
- PartitionKey: #pk5; SequenceNumbers that was listened by the consumer within PartitionKey: [0,1];

**ConsumerId: 2fb3e34e-7bb4-444c-bcea-ec50ee503506;**
- _**PartitionKey: #pk2; SequenceNumbers that was listened by the consumer within PartitionKey: [1,3];**_
- PartitionKey: #pk5; SequenceNumbers that was listened by the consumer within PartitionKey: [0,1];
- PartitionKey: #pk1; SequenceNumbers that was listened by the consumer within PartitionKey: [0,2];

Is it possible to tune EventProcessorClient in my consumer application to avoid listening the same messages twince from different consumers? 

See my consumer application code below
```csharp
using Azure.Messaging.EventHubs;
using Azure.Messaging.EventHubs.Processor;
using Azure.Storage.Blobs;
using System.Collections.Concurrent;

internal class Program
{
    const string storageConnectionString = "......";
    const string blobContainerName = ".....";

    const string eventHubsConnectionString = ".....";
    const string eventHubName = ".......";
    const string consumerGroup = "$Default";

    static object lockResult = new object();

    private static async Task Main(string[] args)
    {
        CancellationTokenSource source = new CancellationTokenSource();
        source.CancelAfter(TimeSpan.FromMinutes(1));

        var threads = Enumerable.Range(0, 5)
                    .Select(_ => new ThreadStart(async () =>
                    {
                        await Launch(source.Token);
                    }))
                    .Select(x => new Thread(x))
                    .ToList();

        foreach (var t in threads) t.Start();

        await Task.Delay(Timeout.Infinite);
    }

    static async Task Launch(CancellationToken token)
    {
        var consumerId = Guid.NewGuid().ToString();

        await Console.Out.WriteLineAsync($"ConsumerId: {consumerId}");
        var partitionKeyToSequenceNumbers = new ConcurrentDictionary<string, List<long>>();

        var storageClient = new BlobContainerClient(
        storageConnectionString,
        blobContainerName);

        var processor = new EventProcessorClient(
            storageClient,
            consumerGroup,
            eventHubsConnectionString,
            eventHubName,
             new EventProcessorClientOptions
             {
                 LoadBalancingStrategy = LoadBalancingStrategy.Greedy
             });

        try
        {
            processor.ProcessEventAsync += processEventHandlerPartitionKeyinDict;
            processor.ProcessErrorAsync += (ProcessErrorEventArgs args) => { Console.WriteLine($"Exception: {args.Exception}"); return Task.CompletedTask; };

            await processor.StartProcessingAsync(token);
            await Task.Delay(Timeout.Infinite, token);

            async Task processEventHandlerPartitionKeyinDict(ProcessEventArgs args)
            {
                var partitionKey = $"{args.Data.PartitionKey}";
                partitionKeyToSequenceNumbers.AddOrUpdate(
                    partitionKey,
                    new List<long> { args.Data.SequenceNumber },
                    (key, oldValue) =>
                    {
                        oldValue.Add(args.Data.SequenceNumber);
                        return oldValue;
                    });

                await args.UpdateCheckpointAsync();
            }
        }
        catch (Exception ex)
        {
            lock (lockResult)
            {
                Console.WriteLine();
                foreach (var partitionKey in partitionKeyToSequenceNumbers.Keys)
                {
                    Console.WriteLine($"ConsumerId: {consumerId}; PartitionKey: {partitionKey}; SequenceNumbers that was listened by the consumer within PartitionKey: [{string.Join(',', partitionKeyToSequenceNumbers[partitionKey])}];");
                }
            }
        }
    }
}
```

### Environment

OS: Windows
net7.0
Azure.Messaging.EventHubs.Processor 5.11.0 
Azure.Messaging.EventHubs 5.11.1

**Comment by jsquire** [comment]
Hi @bastyuchenko.  Thank you for reaching out and we regret that you're experiencing difficulties.  A small amount of overlap (1-2 batch sizes worth) is normal and expected behavior when partition ownership changes as there is no ordered hand-off between processors.   When a new owner assumes control, the old owner of a partition may have events held in memory that are being dispatched and is not aware that ownership has changed until the next attempt to read from the service.  At the same time, the new owner has rewound to the last recorded checkpoint for that partition and will re-read any events processed since that checkpoint was written.

More discussion and context can be found in the [Duplicate events are being processed](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/TROUBLESHOOTING.md#duplicate-events-are-being-processed) section of the Event Hubs Troubleshooting Guide.

**Comment by bastyuchenko** [comment]
Hi @jsquire ,
Thanks for the prompt answer.
I reviewed the the recommendations that you referenced to above. Could you help me to understand the following recommendation from "_[Too many partitions are owned](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/TROUBLESHOOTING.md#too-many-partitions-are-owned)_" part:

`Generally, it is recommended that an event processor own no more than 3 partitions for every 1 CPU core of the host. Since the ratio will vary for each application, it is often helpful to start with 1.5 partitions for each CPU core and increase the number of owned partitions gradually to determine what works best for your application.`

I have 4 CPU Cores and 32 pre-created patitions in my EventHub. I sent 40 000 events to EventHub that were destributed evenly throught the all partitions.

How should I consume the events from this EventHub now? :

- Should I scale to 4 processors in the same consumer group? - in this case I afraid that each processor will own 8 partitions.
- Should I scale to 10 processors in the same consumer group? - in this case I afraid that will experience ThreadPool starvation.
- Maybe I shouldn't create EventHub with more than `4 CPU Cores x 3 partions = 12 partitions` in it.

**Comment by jsquire** [comment]
@bastyuchenko :

To clarify one thing:  You absolutely DO NOT want to add more processors to a single machine.  That is going to cause more resource use and exacerbate and problems, not help alleviate them.  When we talk about scaling processors, it means "adding another host machine with another instance" NOT "adding another processor to the same host."


> Should I scale to 4 processors in the same consumer group? - in this case I afraid that each processor will own 8 partitions.
The number of processors isn't the concern, its resource use on the host.  Based on your statement that each VM has 4 cores, if you were to scale out to 4 processors, then you are correct that each would have a "fair share" of 8 partitions.   That would result in the processor launching 9 dedicated background tasks (1 per partition, 1 for load balancing + health monitoring).   

Assuming that each processor is on a host with 4 cores, then you'd end up with a 2:1 ratio of processors-to-cores, which would be fine for most workloads.  For many workloads, you'd be able to increase that and maybe scale to 3 processors, giving each responsibility for ~10 partitions or right around a 3:1 ratio.  Either way would be a good starting point for testing under load and measuring stability/performance.

> Should I scale to 10 processors in the same consumer group? - in this case I afraid that will experience ThreadPool starvation.

In this case, assuming your 4 core host, you'd end up with each processor seeing 3-4 partitions as its fair share.   Each core would have a 1:1 ration with a dedicated background thread.  For most workloads, this is overkill, but if you've got processing that is heavily CPU-bound, it may be worth considering.   Here again, you'd want to test thoroughly to be sure that you're not spending money to be overprovisioned.

> Maybe I shouldn't create EventHub with more than 4 CPU Cores x 3 partitions = 12 partitions in it.

That would allow you to more comfortably fit on a single host and would avoid waiting resources time-slicing between a large number of background threads.  However, that does limit your throughput, as partitions are the Event Hubs unit of concurrency and you would not be able to scale out to handle higher loads without adding partitions later (possible for premium+ SKUs)
