### ISSUE TITLE
Azure OpenAI API version 2023-12-01-preview to be deprecated 2024-04-02

### ISSUE THREAD

**Issue by AaronCTech** [Azure/azure-sdk-for-net#42512]
### Library name and version

Azure.AI.OpenAI 1.0.0-beta.14

### Query/Question

My team received an email stating that this deprecation would occur, and according to the release notes, the last time the API version was mentioned it was still on 2023-12-01-preview, which is one of the legacy versions slated to be retired.

Is there a timeframe to expect a release that uses a supported API version?

Thank you in advance!

### Environment

Azure

**Comment by scottaddie** [comment]
This issue has been addressed with the v2.x package release train. For a list of supported versions, see: https://github.com/Azure/azure-sdk-for-net/blob/96559f513a328182511b1f5408951302fcd30a20/sdk/openai/Azure.AI.OpenAI/src/Custom/AzureOpenAIClientOptions.cs#L26-L28
