### ISSUE TITLE
Why BlockBlobClient can support ClientSideEncryption 

### ISSUE THREAD

**Issue by CallMeCJ** [Azure/azure-sdk-for-net#42544]
https://github.com/Azure/azure-sdk-for-net/blob/5178b1d1d8129ffe803988671e4244776fbf27c7/sdk/storage/Azure.Storage.Blobs/src/BlockBlobClient.cs#L373

There is scenario where we need to encrypt block block, we are using BlockBlobClient due to file size is large. Is there any suggestion for big file encryption supported.

**Comment by seanmcc-msft** [comment]
@CallMeCJ, we highly recommending using one of our server-side encryption implementations instead, such as [Encryption Scopes](https://learn.microsoft.com/en-us/azure/storage/blobs/encryption-scope-manage?tabs=portal) or [Customer Managed Keys](https://learn.microsoft.com/en-us/azure/storage/common/customer-managed-keys-overview).  Our client-side encryption implementation is only present so customers of the legacy .NET SDK were able to upgrade.

If you absolutely must use client-side encryption, larger files are supported by the BlockBlobClient.
