### ISSUE TITLE
Timezone Client

### ISSUE THREAD

**Issue by FelixKahle** [Azure/azure-sdk-for-net#42558]
### Library name

Azure.Maps

### Please describe the feature.

A client for the Timezone REST API, similar to the one found in the Java SDK. As of my understandings, this REST client can be generated using the autorest tools.

**Comment by FelixKahle** [comment]
Hello, just to checkout, are there any updates concerning this issue? 

Thank you in advance

**Comment by dubiety** [comment]
Hi @FelixKahle , we still need some time to implement Time Zone SDK. Will notify you once it's done. Thank you for your understanding.

**Comment by dubiety** [comment]
Hi @FelixKahle ,

I'm glad to share the great news that we've release `Azure.Maps.TimeZones` package `v1.0.0-beta.1`. Welcome to try it out and let us know if that fits your needs. Thank you again for your patience!
