### ISSUE TITLE
[QUERY] Adding ServiceBusClients and creating ServiceBusSender clients for multiple Service Bus Namespaces

### ISSUE THREAD

**Issue by J0nKn1ght** [Azure/azure-sdk-for-net#42550]
### Library name and version

Azure.Messaging.ServiceBus 7.17.3

### Query/Question

I can't work out how I can instantiate ServiceBusSender clients for multiple Service Bus namespaces.  Some of the senders are for queues, and some are for topics.

I wanted to iterate through a number of SB namespaces held in config, so create a helper function to create the factories:

``` csharp
private static void AddNamedServiceBusSender(IServiceCollection services, IConfiguration configuration, string configSectionName, string senderName)
{
    var config = configuration.GetSection(configSectionName);
    string? serviceBusConnectionString = config.GetValue<string?>("ConnectionString"));
    string? serviceBusNamespace = config.GetValue<string?>("Namespace"));
    string? queueName = config.GetValue<string?>("QueueName"));
    string? topicName = config.GetValue<string?>("TopicName"));

    services.AddAzureClients(builder =>
    {
        if (!string.IsNullOrEmpty(serviceBusNamespace))
        {
            builder.AddServiceBusClientWithNamespace(serviceBusNamespace);
        }
        else
        {
            builder.AddServiceBusClient(serviceBusConnectionString);
        }

        builder.AddClient<ServiceBusSender, ServiceBusSenderOptions>((_, _, provider) => provider
            .GetService<ServiceBusClient>()!
            .CreateSender(queueName ?? topicName))
        .WithName(senderName);
    });
}
```

I then injected a `IAzureClientFactory<ServiceBusSender>` instance into the consuming class, and used `.CreateClient(namedClient)` to create the ServiceBusSender instances as needed.

However, the problem with this is that the call to `provider.GetService<ServiceBusClient>()` is not keyed, so when called, all senders get whatever client was added to the services collection last.

I think what I need is the ability to have an `AddKeyedServiceBusClient`/`AddKeyedServiceBusClientWithNamespace`, and then be able to use `GetKeyedService<ServiceBusClient>(senderName)` in the AddClient lambda, but neither of these extension methods exist.

I've ended up using `AddKeyedSingleton<ServiceBusClient>` to add the service bus clients, and then using `AddKeyedScoped` to add the ServiceBusSender instances, which use `GetKeyedRequiredService<ServiceBusClient>(serviceKey)`, but I don't know whether this is best practice, or not.  My consuming class now has `IServiceProvider` injected.

Is there a way to achieve this with the current AddAzureClients implementation?

### Environment

.Net 8
dotnet-isolated function app

**Comment by jsquire** [comment]
Hi @J0nKn1ght.  Thanks for reaching out and we regret that you're experiencing difficulties.   Because the Azure Extensions package still targets an older version of the DI abstractions, we can't yet take advantage of keyed registrations.  As a result, you'd need to use the `WithName` approach to register factories for `ServiceBusClient` similar to how you're doing the sender.   This would look something like:

```csharp
services.AddAzureClients(builder =>
{
    builder
        .AddServiceBusClient("<< CONNECTION STRING >>")
        .WithName("primary");

    builder
        .AddServiceBusClient("<< CONNECTION STRING >>")
        .WithName("secondary");

    // Register a sender for the "primary" client.
    builder.AddClient<ServiceBusSender, ServiceBusClientOptions>((_, _, provider) =>
        provider
            .GetService<IAzureClientFactory<ServiceBusClient>>()
            .CreateClient("primary")
            .CreateSender("someQueue")
    )    
    .WithName("primary-someQueue");

    // Register a sender for the "secondary" client.
    builder.AddClient<ServiceBusSender, ServiceBusClientOptions>((_, _, provider) =>
        provider
            .GetService<IAzureClientFactory<ServiceBusClient>>()
            .CreateClient("secondary")
            .CreateSender("someTopic")
    )    
    .WithName("secondary-someTopic");
});
```

**Comment by J0nKn1ght** [comment]
@jsquire - Thanks for your reply. That makes sense. I'll refactor as you've suggested.
