### ISSUE TITLE
Wrong sample code for ReadItemAsync

### ISSUE THREAD

**Issue by filipgoris** [Azure/azure-sdk-for-net#42563]
### Type of issue

Code doesn't work

### Description

The sample on this page is wrong.

`await this.container.ReadItemAsync<ToDoActivity>` does not return `ToDoActivity` but `ItemResponse<ToDoActivity>`.
Documented correctly, but not used correctly in the Examples on this page.

Microsoft.Azure.Cosmos 3.38.1

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container.readitemasync?view=azure-dotnet

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/Container.xml

### Document Version Independent Id

e7668b21-8894-5f28-8fbf-a029dfd82079

### Article author

@azure-sdk

### Metadata

* ID: 78c49c42-9f71-8275-4d4c-b5c38175cf5d 
* Service: **cosmos-db**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.Azure.Cosmos` library is maintained as [#4343](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/4343).
