### ISSUE TITLE
Azure OpenAI for CDK

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#42574]

**Comment by mitchdenny** [comment]
Looks like the name on cog services account isn't following the naming regime. It is coming out as `nameichose-temp` insead of the expression `toLower(take(concat('nameichose', uniqueString(resourceGroup().id)), 24))`

**Comment by JoshLove-msft** [comment]
According to the docs, the name is scoped to the resource group so it does not need to be globally unique - https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftcognitiveservices
