### ISSUE TITLE
Tokens  for chats 

### ISSUE THREAD

**Issue by Lacy420** [Azure/azure-sdk-for-net#42583]
### Type of issue

Missing information

### Description

My husband d3l
[Enter feedback here] deleted them 

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/azure.core.tokencredential?view=azure-dotnet

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Core/TokenCredential.xml

### Document Version Independent Id

dcb2f919-1fda-9ff8-8cfb-10e7fda808cf

### Article author

@azure-sdk

### Metadata

* ID: 4f9f4f97-9cd9-a295-69b6-a44016481d67 
* Service: **azure**

**Comment by jsquire** [comment]
Closing and locking as spam.
