### ISSUE TITLE
[QUERY] Update BlobCopyFromUriOptions documentation

### ISSUE THREAD

**Issue by ir-dev** [Azure/azure-sdk-for-net#42589]
### Library name and version

Azure.Storage.Blobs 12.19.1

### Query/Question

I stumbled upon the same problem that another user in #32684 already had, namely that StartCopyFromUriAsync with "copy tags from source" option set has no effect, i.e. does not copy any tags:
```
blob.StartCopyFromUriAsync(uri, new BlobCopyFromUriOptions
{
    CopySourceTagsMode = BlobCopySourceTagsMode.Copy
})
```

It has already been clarified in the linked issue that copying tags only works with `SyncCopyFromUri` and it was suggested to update the documentation for CopySourceTagsMode & BlobCopyFromUriOptions. Since this has not happened, it is still very misleading and should please be made up for.

**Comment by seanmcc-msft** [comment]
Hi @ir-dev, thanks for reporting this.  I have created a PR to clarify the documentation.
