### ISSUE TITLE
Cuenta 

### ISSUE THREAD

**Issue by 890700** [Azure/azure-sdk-for-net#42580]
### Type of issue

Code doesn't work

### Description

[Escriba sus comentarios aquí]

### Page URL

https://learn.microsoft.com/es-es/dotnet/api/microsoft.azure.management.appservice.fluent.models.backuprestoreoperationtype?view=azure-dotnet-legacy

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.AppService.Fluent.Models/BackupRestoreOperationType.xml

### Document Version Independent Id

547aff65-100f-3235-7b6b-1dc7536dfc0e

### Article author

@azure-sdk

### Metadata

* ID: e118b84d-8659-55fc-732c-2a87aeeb2075 
* Service: **app-service**

**Comment by jsquire** [comment]
Hi @890700.  Thank you for reaching out and we regret that you're experiencing difficulties.  The `Microsoft.Azure.Management.AppService.Fluent` package reached end-of-life in September 2023 and is no longer published nor maintained by Microsoft.  Likewise, the documentation for it is no longer maintained.
