### ISSUE TITLE
OpenAi

### ISSUE THREAD

**Issue by dtiplaman** [Azure/azure-sdk-for-net#42586]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/azure.ai.openai.embeddings?view=azure-dotnet-preview

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.AI.OpenAI/Embeddings.xml

### Document Version Independent Id

f13bd901-f32a-0c60-c0e6-d8bfe1fd9a7f

### Article author

@azure-sdk

### Metadata

* ID: dcb4ce23-c3f2-ac57-50a4-5883b033fa09 
* Service: **azure**

**Comment by jsquire** [comment]
Hi @dtiplaman.  Thank you for reaching out to let us know about a typo that you found.  Unfortunately, there's not enough context in this issue to understand where the typo exists.  Would you please provide additional context to help us understand where you're seeing a mistake?

**Comment by jsquire** [comment]
Seeing as we've had a wave of issues come in with this same pattern, closing and locking as spam.
