### ISSUE TITLE
[FEATURE REQ] Support for blob image url when using GPT-4 Turbo with Vision

### ISSUE THREAD

**Issue by vandana2015** [Azure/azure-sdk-for-net#42591]
### Library name

Azure.AI.OpenAI 1.0.0-beta.14

### Please describe the feature.

When using GPT-4 Turbo with Vision model, I want to have the ability to pass blob url to the image in the `image_url` field.

```
                {
	                "type": "image_url",
	                "image_url": {
                               "url": "<URL of image blob>"
                    }
                } 
```

Right now I get 403 forbidden error.
"The provided image url can not be accessed. status code: 403.\r\nStatus: 400 (Bad Request)"

What I have tried - 
The base64 image passed in `image_url `has a size restriction of 64 KB. 
My service is within VPN, so accessing image from web is a security issue. 

Please provide ability to pass a blob image url on which the API has Service account access to be used in the `image_url `field, OR please share any other way to pass the url so that the openai model can access it.

**Comment by scottaddie** [comment]
This support exists in versions 1.0.0-beta.17 and later. See the changelog entry at https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/openai/Azure.AI.OpenAI/CHANGELOG.md#features-added-3.
