### ISSUE TITLE
[BUG] Azure.ResourceManager.TestFramework fails for an ResourceManagerUrl that does not match the 4 predefined environments AzurePublicCloud, AzureChina, AzureGen

### ISSUE THREAD

**Issue by jasonurban1** [Azure/azure-sdk-for-net#42612]
### Library name and version

azure-sdk-for-net\common\ManagementTestShared\Redesign\ManagementRecordedTestBase.cs

### Describe the bug

I have been using an AzEnvironment that has a ResourceManagerUrl aimed at canary https://centraluseuap.management.azure.com/.  Everything else in the environment shows same as AzureCloud.  This work for my powershell session with Az powershell commands.  

When I run my tests "EDGEZONES_RESOURCE_MANAGER_URL" is set for "https://centraluseuap.management.azure.com/".  This environment.ResourceManagerUrl does not match any of the predefined environments the ResourceManagerUrl is checked against  in https://github.com/Azure/azure-sdk-for-net/blob/4b6f51cbcab665daab4c7df083b6dfe18f2e7e03/common/ManagementTestShared/Redesign/ManagementRecordedTestBase.cs#L150.  Tries to create an ArmEnvironment at line 172 and fails with InvalidOperationException even when attribute OneTimeSetUp is set on a method in my test 's ManagementTestBase class.

Testing against Canary is fairly common.  I am surprised this does not work.  At present I will have to wait for my resource provider changes to go word wide before I can write and record testcases for it.

### Expected behavior

Using a ResourceManagerUrl https://centraluseuap.management.com for EDGEZONES_RESOURCE_MANAGER_URL should work.

### Actual behavior

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Failed TestGetAzureExtendedZone() [294 ms]
  Error Message:
   System.InvalidOperationException : Recorded value should not be set outside the test method invocation
  Stack Trace:
     at Azure.Core.TestFramework.TestEnvironment.GetRecordedOptionalVariable(String name, Action`1 options) in c:\git\repos\azure-sdk-for-net\azure-sdk-for-net\sdk\core\Azure.Core.TestFramework\src\TestEnvironment.cs:line 417
   at Azure.Core.TestFramework.TestEnvironment.GetRecordedOptionalVariable(String name) in c:\git\repos\azure-sdk-for-net\azure-sdk-for-net\sdk\core\Azure.Core.TestFramework\src\TestEnvironment.cs:line 395
   at Azure.Core.TestFramework.TestEnvironment.get_ServiceManagementUrl() in c:\git\repos\azure-sdk-for-net\azure-sdk-for-net\sdk\core\Azure.Core.TestFramework\src\TestEnvironment.cs:line 172
   at Azure.ResourceManager.TestFramework.ManagementRecordedTestBase`1.GetArmEnvironment(TestEnvironment environment) in c:\git\repos\azure-sdk-for-net\azure-sdk-for-net\common\ManagementTestShared\Redesign\ManagementRecordedTestBase.cs:line 172
   at Azure.ResourceManager.TestFramework.ManagementRecordedTestBase`1.GetCleanupClient() in c:\git\repos\azure-sdk-for-net\azure-sdk-for-net\common\ManagementTestShared\Redesign\ManagementRecordedTestBase.cs:line 119
   at Azure.ResourceManager.TestFramework.ManagementRecordedTestBase`1.CreateCleanupClient() in c:\git\repos\azure-sdk-for-net\azure-sdk-for-net\common\ManagementTestShared\Redesign\ManagementRecordedTestBase.cs:line 178
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

### Reproduction Steps

Run a test case with mode Recording and have your AzContext.Environment ResourceManagerUrl set to https://centraluseuap.management.microsoft.com/

### Environment

>dotnet --info
.NET SDK:
 Version:           8.0.200
 Commit:            438cab6a9d
 Workload version:  8.0.200-manifests.e575128c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.200\

.NET workloads installed:
 [maui-windows]
   Installation Source: VS 17.9.34607.119
   Manifest Version:    8.0.6/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.6\WorkloadManifest.json
   Install Type:        FileBased

 [maccatalyst]
   Installation Source: VS 17.9.34607.119
   Manifest Version:    17.2.8004/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maccatalyst\17.2.8004\WorkloadManifest.json
   Install Type:        FileBased

 [ios]
   Installation Source: VS 17.9.34607.119
   Manifest Version:    17.2.8004/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.ios\17.2.8004\WorkloadManifest.json
   Install Type:        FileBased

 [android]
   Installation Source: VS 17.9.34607.119
   Manifest Version:    34.0.52/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.android\34.0.52\WorkloadManifest.json
   Install Type:        FileBased

Host:
  Version:      8.0.2
  Architecture: x64
  Commit:       1381d5ebd2

.NET SDKs installed:
  6.0.419 [C:\Program Files\dotnet\sdk]
  7.0.406 [C:\Program Files\dotnet\sdk]
  8.0.200 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by HarveyLink** [comment]
Duplicated with #39383

**Comment by HarveyLink** [comment]
Hi @jasonurban1 , for the `ServiceManagementUrl`, it's a known issue, our engineer still working on it.
If you need to test the canary environment, you could try to modify the `ManagementRecordedTestBase` class as a work around:
[Line 172](https://github.com/Azure/azure-sdk-for-net/blob/a2ff5e6bbccd62fc5d82a5aaacec826e856bdd74/common/ManagementTestShared/Redesign/ManagementRecordedTestBase.cs#L172), change to
```
return new ArmEnvironment(new Uri(endpoint), TestEnvironment.ServiceManagementUrl ?? $"{endpoint}/.default");
```

Since we don't have a canary SPN for us to test, you could try it your self. And the endpoint you mentioned has 3 different versions, make sure you are using the correct one:
https://centraluseuap.management.microsoft.com/
https://centraluseuap.management.com/
https://centraluseuap.management.azure.com/

Note:
-----
It's not recommended to test/record on canary and release the SDK, if it only works on canary region, then it's not ready for the common users.
