### ISSUE TITLE
ROOMID

### ISSUE THREAD

**Issue by shivanisingh-10** [Azure/azure-sdk-for-net#42625]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/azure.communication.rooms.roomsclient.addorupdateparticipants?view=azure-dotnet

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Communication.Rooms/RoomsClient.xml

### Document Version Independent Id

176d1f70-e9d6-bdd4-0c36-1b3c9b9d8d46

### Article author

@azure-sdk

### Metadata

* ID: eaa04f65-d618-75f4-3dd2-327fb225911d 
* Service: **azure**

**Comment by jsquire** [comment]
Not enough detail to understand what is being reported as a typo, but using the `RoomId` from the title as a context clue, I've confirmed that the parameters in code match the docs.   Closing.
