### ISSUE TITLE
IfDef FullDesktop directive to work on non-windows

### ISSUE THREAD

**Issue by shahabhijeet** [Azure/azure-sdk-for-net#4263]
Find a proper way to IfDeg FullDesktop so that it works on non-windows environment.
Currently FullDesktop assumes two things:
1. That it is full desktop .net
2. That it is running on Windows

#2 should not be assumed and if needed guard with appropriate ifDef if required.

The code in question is the following code block
https://github.com/Azure/azure-sdk-for-net/blob/d6c9636ef100346afee80619beb191d31c5cba07/src/SdkCommon/ClientRuntime/ClientRuntime/ServiceClient.cs#L53

Required:
1) Add tests that can be run on non-windows environment

**Comment by dsgouda** [comment]
@shahabhijeet investigated a little here and looks like the only way we can detect the operating system is in the csproj files, which means we can compile code in only 2 modes, one is for the current operating system on which the code is being compiled on or cross plat (AnyCPU)

**Comment by dsgouda** [comment]
Fix merged, some testing is pending on non windows machine, tracked here https://github.com/Azure/azure-sdk-for-net/issues/4403
