### ISSUE TITLE
[BUG] AddAzureMonitorTraceExporter clobbers the trace sampler

### ISSUE THREAD

**Issue by mol-pensiondk** [Azure/azure-sdk-for-net#42668]
### Library name and version

Azure.Monitor.OpenTelemetry.Exporter 1.2.0

### Describe the bug

AddAzureMonitorTraceExporter calls TracerProviderBuilderExtensions.SetSampler to set a ApplicationInsightsSampler as the trace sampler. This clobbers any sampler that has already been set up. Adding an exporter should not affect the sampling policy!

We unexpextedly found that when we changed to using the Azure.Monitor.OpenTelemetry.Exporter, our sampling policy was no longer respected (every request was suddenly sampled). We were using the OTLP sampler and OpenTelemetry collector to export trace metrics to Azure Monitor, but decided to shorten the telemetry chain by exporting directly to Azure Monitor from some of our dotnet components. We replaced the AddOtlpExporter call with AddAzureMonitorTraceExporter in the chained calls setting up the TracerProviderBuilder. Suddenly we were flooded with trace telemetry, because each and every call originating from the changed components would have their recorded flag set in the traceparent and downstream requests would all be recorded.

Our workaround is to call SetSampler after AddAzureMonitorTraceExporter instead of before.

This is the offending line of code:
https://github.com/Azure/azure-sdk-for-net/blob/a2f6ba0cfd188bfae3c3a264e8d1c819513585db/sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/src/AzureMonitorExporterExtensions.cs#L75

### Expected behavior

The method should not set the sampler.

### Actual behavior

The method sets the sampler, clobbing the sampler already set earlier in the chain of builder calls.

### Reproduction Steps

Call AddAzureMonitorTraceExporter and inspect the Sampler afterwards.

**Comment by cijothomas** [comment]
This is unfortunate, but since the library is already stable, the behavior cannot be changed. All we can do is to ensure the doc is pretty clear on what are the effects of  calling AddAzMonExporter, so users can take precaution and workarounds.

**Comment by mol-pensiondk** [comment]
Maybe the more usual path is to replace Application Insights libraries with OT and use the Azure Monitor exporter from the outset rather than going with the OT Collector first, and that is why the issue has not been discovered/reported before. Or maybe it is because the default OT sampler samples all root activities, so replacing it with a sampler that samples **all** activities (ignoring parent context) will generate the same telemetry in many applications. It's only when you actually care about not setting the W3C recorded flag too often (and respecting the flag if set in the context) that you will really notice.

It's a shame that the clobbering behaviour cannot be changed. But at least with updated documentation, the next team trying to figure out why sampling policy is not respected will have a chance of doing so more quickly.
