### ISSUE TITLE
Azure.ResourceManager.Sql uses preview API Version in latest GA

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#42670]
https://github.com/Azure/azure-sdk-for-net/blob/Azure.ResourceManager.Sql_1.2.0/sdk/sqlmanagement/Azure.ResourceManager.Sql/src/Generated/RestOperations/ServersRestOperations.cs#L36 references a preview API version, but this is a GA library.

**Comment by ArthurMa1978** [comment]
https://www.nuget.org/packages/Azure.ResourceManager.Sql/1.2.1 released.
