### ISSUE TITLE
[QUERY] Dependency Biding issue with libraries depending on different versions of Azure.Core

### ISSUE THREAD

**Issue by gupta-sk** [Azure/azure-sdk-for-net#42685]
### Library name and version

Azure.Identity (1.10.4), Azure.Security.KeyVault.Secrets (4.6.0),  Azure.Core (1.38.0)

### Query/Question

Currently, one of the solutions is using Azure.Identity (1.10.4), Azure.Security.KeyVault.Secrets (4.6.0).

Now, Azure.Identity depends on Azure.Core (1.36.0) while Azure.Security.KeyVault.Secrets depends on Azure.Core (1.37.0).
Having 1.37.0 version, gives runtime binding failure for Azure,Identity package.

I tried getting the fusion logs and found out it's indeed a runtime dependency binding issue, which is throwing MissingMethodException.

Even the assembly binding redirects are not working (maybe because this is indirect dependency).

Any suggestions on how to resolve this?

I am an internal customer who works in AzNet on RNM service, where we are facing this issue.

**Comment by jsquire** [comment]
Hi @gupta-sk.  Thanks for reaching out and we regret that you're experiencing difficulties.  You can mitigate this by taking a direct reference to the latest Azure.Core in your application, as that will hoist the version used by dependencies.

**Comment by gupta-sk** [comment]
/unresolve

I did try adding direct dependency on latest version of Azure.Core i.e., 1.38.0 and the solution builds without any errors. However, I still got MissingMethodException while running UTs as shown below:

<img width="653" alt="image" src="https://github.com/Azure/azure-sdk-for-net/assets/156887893/e1dd05a1-23ab-42db-b212-93df70d3adbd">


Upon getting the fusion logs, can see that assembly loading is failing because of Azure.Core:

<img width="829" alt="image" src="https://github.com/Azure/azure-sdk-for-net/assets/156887893/fb4bdf60-325c-4b3a-a56a-5f364653adc7">

We facing this issue even with Azure.Storage.Blobs while creating BlobServiceClient which is dependent on Azure.Core (1.36.0)
