### ISSUE TITLE
[OpenAI] Instructions on how to consume local NuGet packages

### ISSUE THREAD

**Issue by pallavit** [Azure/azure-sdk-for-net#42698]
Given OpenAI is not familiar with .NET we need to share with them instructions on how to consume a nuget package.
We also may want to consider generating a package from our dev feed instead for the time being.

**Comment by joseharriaga** [comment]
Found here: 🔗 https://gist.github.com/joseharriaga/5d1f18c361fa294aa300d78fd59d35a5
