### ISSUE TITLE
ContinuousWebJobStatus does not have Disabled status

### ISSUE THREAD

**Issue by FirePho** [Azure/azure-sdk-for-net#4269]
Microsoft.Rest.SerializationException: Unable to deserialize the response. ---> Newtonsoft.Json.JsonSerializationException: Error converting value "Disabling" to type 'System.Nullable`1[Microsoft.Azure.Management.WebSites.Models.ContinuousWebJobStatus]'. Path 'properties.status', line 1, position 389. ---> System.ArgumentException: Requested value 'Disabling' was not found.

**Comment by shahabhijeet** [comment]
@FirePho can you describe in detail what you are trying to do what is the issue here.
can you also provide code snippet that allows us to reproduce this error that you are trying to report.

**Comment by FirePho** [comment]
I just stop web job (IWebSiteManagementClient.WebApps.StartContinuousWebJob)
and get it status (IWebSiteManagementClient.WebApps.GetContinuousWebJob)

After a request to stop, the web job for a few seconds is in the status of Disabling

![image](https://user-images.githubusercontent.com/1927599/41190822-1fecf6d6-6bee-11e8-9780-42f2fcafda9a.png)

**Comment by FirePho** [comment]
There is also no 'Stopping' status, although web jobs can be in it

Microsoft.Rest.SerializationException: Unable to deserialize the response. ---> Newtonsoft.Json.JsonSerializationException: Error converting value "Stopping" to type 'System.Nullable`1[Microsoft.Azure.Management.WebSites.Models.ContinuousWebJobStatus]'. Path 'properties.status', line 1, position 388. ---> System.ArgumentException: Requested value 'Stopping' was not found.
    at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnumName(String enumText, Boolean isNullable, Type t)
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)

**Comment by adrianhall** [comment]
Hi @FirePho - my apologies for this being dropped for so long.  Is this still an issue?

**Comment by FirePho** [comment]
Hi @adrianhall
Yes, it is still an issue, reproduced as follows:
```
var client = new WebSiteManagementClient(credentials);
client.SubscriptionId = _subscriptionId;
client.WebApps.StartContinuousWebJob(_resourceGroupName, _siteName, _jobName);
while (true)
{
    if (client.WebApps.GetContinuousWebJob(_resourceGroupName, _siteName, _jobName).Status 
== Microsoft.Azure.Management.WebSites.Models.ContinuousWebJobStatus.Running)
    {
        break;
    }
}
```

**Comment by adrianhall** [comment]
Can you confirm the name and version of the DLL you are using, please?
