### ISSUE TITLE
[BUG] Add missing streaming support to the Assistants API

### ISSUE THREAD

**Issue by kzu** [Azure/azure-sdk-for-net#42716]
### Library name and version

Azure.AI.OpenAI.Assistants_1.0.0-beta.3

### Describe the bug

OpenAI added streaming support to the assistant API: https://platform.openai.com/docs/assistants/overview?context=with-streaming.

Granted, this shipped *today*, so I understand if you don't have same-day shipping (we used to have that in Xamarin, heh). But it's a critically important API to support. See changelog at https://platform.openai.com/docs/changelog

### Expected behavior

Support the streaming API

### Actual behavior

No streaming in Assistant API

### Reproduction Steps

Try to invoke the assistant API using streaming

**Comment by scottaddie** [comment]
[Streaming is fully supported](https://github.com/openai/openai-dotnet?tab=readme-ov-file#how-to-use-streaming-and-gpt-4o-vision-with-assistants), but you'll need to migrate to the Azure.AI.OpenAI package. For more context on the package migration, see [this note](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/openai/Azure.AI.OpenAI.Assistants#important-note-assistants-is-converging).
