### ISSUE TITLE
Implement unbranded `ToDynamicFromJson`

### ISSUE THREAD

**Issue by joseharriaga** [Azure/azure-sdk-for-net#42722]
We need `ToDynamicFromJson` in unbranded libraries so that users can leverage it when they use protocol methods (instead of them having to use `JsonDocument` or similar).

**Comment by pallavit** [comment]
Is this something we will add as part of convenience or do you expect this to be something that ideally unbranded toolchain generates?

**Comment by joseharriaga** [comment]
> Is this something we will add as part of convenience or do you expect this to be something that ideally unbranded toolchain generates?

We will want it as part of the unbranded toolchain to facilitate working with protocol methods everywhere.

/cc: @KrzysztofCwalina, who started a thread with Stephen Toub to explore how we can expose this functionality outside of Azure.Core.

**Comment by annelo-msft** [comment]
Duplicate of https://github.com/Azure/azure-sdk-for-net/issues/42654
