### ISSUE TITLE
[QUERY] Must use Azure SignalR management SDK with Azure Functions, but no documentation exists.

### ISSUE THREAD

**Issue by michaeldaw** [Azure/azure-sdk-for-net#42752]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.SignalRService 1.13.0

### Query/Question

According to information in #30218, "serverless hub is not supported in isolated-process model. If you want the similar coding experience in isolated-process, please use [Azure SignalR management SDK](https://github.com/Azure/azure-signalr/blob/dev/docs/management-sdk-guide.md) directly."

The documentation for the SignalRService package still uses the serverless hub model and does not mention it can't be used in isolated-process model.

#30218 also mentions that the documentation will be updated to reflect this change. Where is this documentation?

**Comment by Y-Sindo** [comment]
Now serverless hub is supported in isolated-process model. See https://github.com/aspnet/AzureSignalR-samples/tree/main/samples/DotnetIsolated-ClassBased for a sample. We are updating the docs.

**Comment by michaeldaw** [comment]
Thank you for the reply. I've switched to the class-based approach in the sample and it seems to be working.

One thing I wanted to mention:
If you add an HTTP trigger to your function using Visual Studio, a reference to `Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore` will be added to the project. It doesn't seem to be needed, but from what I can tell in my testing, if this package is present, the following error occurs when attempting to call "ConfigureFunctionWorkerDefaults":
```
The registration for method 'ConfigureFunctionsWebApplication' is expected for ASP.NET Core Integration.
```
The error goes away if `ConfigureFunctionsWebApplication` is added to the application, but if this is done, the Function App seems to no longer expose the endpoint `/runtime/webhooks/signalr`, which is needed for the connection to the Azure SignalR server.
`Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore` isn't actually needed to run HTTP triggers, so removing it is fine and everything seems to work. I'm just concerned that others may run into this and have a difficult time figuring it out.

This explanation probably sounds a little convoluted. If I can provide more information, please let me know.

Thanks again for the reply.

**Comment by Y-Sindo** [comment]
@jsquire Could you help route the question about HTTP trigger in dotnet isolated process to related team?
> Thank you for the reply. I've switched to the class-based approach in the sample and it seems to be working.
> 
> One thing I wanted to mention: If you add an HTTP trigger to your function using Visual Studio, a reference to `Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore` will be added to the project. It doesn't seem to be needed, but from what I can tell in my testing, if this package is present, the following error occurs when attempting to call "ConfigureFunctionWorkerDefaults":
> 
> ```
> The registration for method 'ConfigureFunctionsWebApplication' is expected for ASP.NET Core Integration.
> ```
> 
> The error goes away if `ConfigureFunctionsWebApplication` is added to the application, but if this is done, the Function App seems to no longer expose the endpoint `/runtime/webhooks/signalr`, which is needed for the connection to the Azure SignalR server. `Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore` isn't actually needed to run HTTP triggers, so removing it is fine and everything seems to work. I'm just concerned that others may run into this and have a difficult time figuring it out.
> 
> This explanation probably sounds a little convoluted. If I can provide more information, please let me know.
> 
> Thanks again for the reply.

**Comment by jsquire** [comment]
> @jsquire Could you help route the question about HTTP trigger in dotnet isolated process to related team?

@michaeldaw:  For discussion of the HTTP trigger in an isolated process, you'd want to open an issue with your inquiry in the [azure-functions-dotnet-worker repository](https://github.com/Azure/azure-functions-dotnet-worker) or [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request).
