### ISSUE TITLE
[FEATURE REQ] Please add an option to set the application properties inside the ServiceBusModelFactory class

### ISSUE THREAD

**Issue by jhueppauff** [Azure/azure-sdk-for-net#42772]
### Library name

Azure.Messaging.ServiceBus

### Please describe the feature.

Hi, 

for (unit) testing purpose it would be great to set the applicationProperties inside the model factory. 

Currently there is no option to set it, which causes us some issues as we are not able to write unit tests which are depended on application properties to be there. 

https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusmodelfactory?view=azure-dotnet

**Comment by jsquire** [comment]
Hi @jhueppauff.  Thanks for reaching out and we regret that you're experiencing difficulties.  Can you help us understand what model you're looking to set application properties for?   The one that seems applicable to me is [ServiceBusReceivedMessage](https://learn.microsoft.com/dotnet/api/azure.messaging.servicebus.servicebusmodelfactory.servicebusreceivedmessage?view=azure-dotnet#parameters) where the `ApplicationProperties` dictionary can be passed using the `properties` parameter.   _(I don't know why the name of the parameter differs from the name of the property it matches, but I'll look into getting that updated, likewise with the missing parameter documentation.)_

**Comment by jhueppauff** [comment]
sorry for the late response, yes you are right. Properties = ApplicationProperties.
![image](https://github.com/Azure/azure-sdk-for-net/assets/20532954/8b78f205-77b2-4b14-9fcd-8612b49ad65f)

The naming is indeed a bit confusing as it is kind of different at every place. Looking at Azure it is not even consistent there:

![image](https://github.com/Azure/azure-sdk-for-net/assets/20532954/483ed4a3-85e1-4e6f-8635-36308982c885)

![image](https://github.com/Azure/azure-sdk-for-net/assets/20532954/5eebba56-e893-482d-a415-cbe8736269db)

But from the SDK perspective I think it would really help to have it named application properties. As I kind was assuming that properties are the system properties like CorrelationId, etc

Thank you for your help :)

**Comment by jsquire** [comment]
Renaming the parameters for the model factory method is a breaking change, which this doesn't meet the bar for.   I've added the missing doc comments for the parameters, highlighting which property of the associated model they populate as part of #43276.   This will be available as part of our April release this week.
