### ISSUE TITLE
[OpenAI] Implement GitHub release workflow

### ISSUE THREAD

**Issue by hallipr** [Azure/azure-sdk-for-net#42774]
The workflow should
- [x] Trigger on publish of a release
- [x] Build, test and publish the client nuget package
  - [x] The generated package should reference the release tag in its source metadata
  - [ ] If using SourceLink, that too should point to the repo at the release tag
- [x] Append the nuget package to the triggering release
- [ ] Ensure the version of the package matches the release tag
  - The package version is determined by the version properties in Directory.Build.props.  Rather than arbitrarily name the package after the release tag, we should fail the run if the tag doesn't match the generated version.

**Comment by jsquire** [comment]
Closing, per state in the EngSys project
