### ISSUE TITLE
Rearrange all admin project and management projects for AzureStack

### ISSUE THREAD

**Issue by shahabhijeet** [Azure/azure-sdk-for-net#4279]
Currently AzureStack Admin projects are all under src\AzureStack directory.
Since management projects are beginning to light up under AzureStack, it's time to rearrange all projects like below
- src\AzureStack\Admin\AzureBridgeAdmin, BackupAdmin etc
- src\AzureStack\Management\Subscription etc

**Comment by shahabhijeet** [comment]
@deathly809 can you finish this by EO month?

**Comment by deathly809** [comment]
@shahabhijeet Yeah.

**Comment by shahabhijeet** [comment]
@deathly809 thank you for doing this.
