### ISSUE TITLE
Http 2.0 support for Azure Blob Storage

### ISSUE THREAD

**Issue by ilabsllc** [Azure/azure-sdk-for-net#42828]
### Library name and version

Latest

### Query/Question

My understanding is that Azure Blob Storage still doesn't support Http 2.0. Is there any reason why ?. When can we expect support for http 2.0

### Environment

NA.

**Comment by seanmcc-msft** [comment]
Azure Storage Blob currently only supports HTTP 1.1 - https://learn.microsoft.com/en-us/rest/api/storageservices/http-version-support

My understanding is that there are no current plans to add HTTP 2 support in the service.

**Comment by ilabsllc** [comment]
I was expecting a technical explanation of why HTTP 2 support is not a priority for azure blob storage.
