### ISSUE TITLE
[QUERY] Is it possible to enable outbounding internet application routing ?

### ISSUE THREAD

**Issue by sebasviot** [Azure/azure-sdk-for-net#42867]
### Library name and version

Azure.ResourceManager 1.10.2; Azure.ResourceManager.Network 1.7.0; Azure.ResourceManager.AppService 1.0.2

### Query/Question

Using Azure Resource Manager, I have created a web application, a virtual network and a nat gateway. 

I would like to know if it is possible to enable application routing so that outbound traffic passes through my nat gateway. 

In my Azure Portal screenshot, I would like this box to be ticked when using ArmClient. 

Is this possible?

Thanks
![Capture d'écran 2024-03-21 104827](https://github.com/Azure/azure-sdk-for-net/assets/55495132/e6dbe44d-6429-4775-a939-34060a2645e2)

**Comment by sebasviot** [comment]
I found a workaround by querying GenericResources :


`var genericData = new GenericResourceData(AzureLocation.WestEurope)
        {
            Properties = BinaryData.FromObjectAsJson(new Dictionary<string, object>()
            {
                { "vnetRouteAllEnabled", true }
            })
        };`

`await _armClient.GetGenericResources().CreateOrUpdateAsync(
            WaitUntil.Completed, myResourceId, genericData, cancellationToken);`

**Comment by mcgallan** [comment]
Hi @sebasviot, thank you for your feedback! You can achieve the functionality you need by setting WebSiteData.SiteConfig.IsVnetRouteAllEnabled to True. Here’s a simple example:
```
var data = new WebSiteData(location)
{
    IsReserved = false,
    IsXenon = false,
    IsHyperV = false,
    SiteConfig = new SiteConfigProperties
    {
        NetFrameworkVersion = "v4.6",
        AppSettings =
        {
            new AppServiceNameValuePair
            {
                Name = "WEBSITE_NODE_DEFAULT_VERSION",
                Value = "10.14"
            }
        },
        IsLocalMySqlEnabled = false,
        IsHttp20Enabled = true,
        IsVnetRouteAllEnabled = true,
    },
    IsScmSiteAlsoStopped = false,
    IsHttpsOnly = false
};
```

**Comment by sebasviot** [comment]
Hi @mcgallan. Thanks for your reply, it works fine for me !
