### ISSUE TITLE
[BUG] Azure.ResourceManager.ApiManagement, ApiManagementServiceResource.GetApis() throws exception

### ISSUE THREAD

**Issue by cokosharp** [Azure/azure-sdk-for-net#42865]
### Library name and version

Azure.ResourceManager.ApiManagement 1.1.0

### Describe the bug

An exception is thrown when listing the apis in apim using ApiManagementServiceResource.GetApis() if any of the apis has an invalid URI for the property "termsOfService".

Exception detail:
at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
at System.Uri..ctor(String uriString)
at Azure.ResourceManager.ApiManagement.ApiData.DeserializeApiData(JsonElement element)
at Azure.ResourceManager.ApiManagement.ApiCollection.<>c__DisplayClass9_0.b__2(JsonElement e)
at Azure.Core.PageableHelpers.PageableImplementation1.<GetAsyncEnumerator>d__15.MoveNext() at Azure.Core.PageableHelpers.PageableImplementation1.d__15.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
at ...d__14.MoveNext()

### Expected behavior

All apis should be listed regardless of what value the property termsOfService has for each api.

### Actual behavior

An exception is thrown if any of the apis has an invalid URI for the property termsOfService, so not all apis will be listed.

### Reproduction Steps

In our case, one of the apis had the property "termsOfService": "n/a", which is not a valid URI, and an exception is thrown.

```
ResourceIdentifier id = ApiManagementServiceResource.CreateResourceIdentifier(_subscriptionId, _resourceGroupName, _serviceName);
ClientSecretCredential credentials = new(_tenantId, _clientId, _clientSecret);

ArmClient client = new(credentials);
ApiManagementServiceResource apimService = await client.GetApiManagementServiceResource(id).GetAsync();

ApiCollection apiList = apimService.GetApis();

try
{
    foreach (var api in apiList)
    {
        try
        {
            Console.WriteLine(api.Id);
        }
        catch (Exception ex)
        {
            // Not catched here
            Console.WriteLine(ex.Message);
        }
    }
}
catch (Exception ex)
{
    // Catched here
    Console.WriteLine(ex.Message);
}
```

The bug is in function Azure.ResourceManager.ApiManagement.ApiData.DeserializeApiData, where there is no check if property0.Value is a valid URI:
termsOfServiceUri = new Uri(property0.Value.GetString());

### Environment

Azure AppService .NET 8
Visual Studio 17.9.4

**Comment by melina5656** [comment]
Hi @cokosharp , this issue has been fixed. 
Thank you for your feedback.

**Comment by schmallaria** [comment]
Hi @melina5656, are there any plans when this fix gets released?

**Comment by melina5656** [comment]
> Hi @melina5656, are there any plans when this fix gets released?

Hi @schmallaria , Do you urgently need a fixed version now? We have other bugs that have not been fixed yet. If your plan is not very urgent, we will release it after fixing all the bugs.

**Comment by schmallaria** [comment]
Hi @melina5656 would be nice to have an updated version asap. We use this package within an Azure Function. This function would not be running until it's fixed.

**Comment by melina5656** [comment]
> Hi @melina5656 would be nice to have an updated version asap. We use this package within an Azure Function. This function would not be running until it's fixed.

Hi @schmallaria , we will release it as soon as possible.

**Comment by schmallaria** [comment]
@melina5656, awesome. Thank you!

**Comment by melina5656** [comment]
> @melina5656, awesome. Thank you!

Hi @schmallaria, the new version has been released, you can try using it.
