### ISSUE TITLE
Operation returned an invalid status code 'InternalServerError' while getting IoT hub list using Microsoft.Azure.Management.DeviceProvisioningServices

### ISSUE THREAD

**Issue by vithal-wadje** [Azure/azure-sdk-for-net#4287]
I am using **Microsoft.Azure.Management.DeviceProvisioningServices** and **Microsoft.Azure.Management.ResourceManager.Fluent** to get the list of linked IoT hubs to the DPS , but while calling the IotDpsClient GetAsync & Get method its throwing **Operation returned an invalid status code 'InternalServerError'** after 20 to 30 seconds of wait . I have increased task timeout and all but still has the same issue, following is the stackTrace of exception

> at Microsoft.Azure.Management.DeviceProvisioningServices.IotDpsResourceOperations.<GetWithHttpMessagesAsync>d__5.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Azure.Management.DeviceProvisioningServices.IotDpsResourceOperationsExtensions.<GetAsync>d__1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at sampleweb.Api.Controllers.OperationsController.<GetIoTHubListByDpsName>d__3.MoveNext() in C:\Working Folder\sampleweb\Controllers\OperationsController.cs:line 85

Following the response coming from package after evaluating expression ((Microsoft.Azure.Management.DeviceProvisioningServices.Models.ErrorDetailsException)e).Response.Content

**{"code":500019,"httpStatusCode":"InternalServerError","message":"Internal Error. If you contact a support representative please include this correlation identifier: d2e56c0b-bb32-4a2d-a906-a9c9f6c36981, timestamp: 2018-05-04 14:56:31Z, errorcode: IH500019."}**

Following is the code snippet I am using 

`AzureCredentials credentials = SdkContext.AzureCredentialsFactory.FromServicePrincipal(
                   "clientId", "clientSecret",
                   "tenantId", AzureEnvironment.AzureGlobalCloud);
                IotDpsClient client = new IotDpsClient(credentials);
                  client.SubscriptionId = "SubscriptionId ";
                ProvisioningServiceDescription iotdpsservicedescription
              = await client.IotDpsResource.GetAsync(dpsInstanceName, resourceGroupName).ConfigureAwait(false);`

Note : The lastest version 2.3.3  of  **Microsoft.Rest.ClientRuntime.Azure.Authentication** is won't work we have downgrade it to less than **2.3.3** then its only works , This package is get added when we install **Microsoft.Azure.Management.ResourceManager.Fluent** nuget package

This is very strange issue , we are stuck in major implementation due this , Please look into this and let me know if requires any other details.

**Comment by deathly809** [comment]
```
Note : The lastest version 2.3.3 of Microsoft.Rest.ClientRuntime.Azure.Authentication is won't work we have downgrade it to less than 2.3.3 then its only works , This package is get added when we install Microsoft.Azure.Management.ResourceManager.Fluent nuget package
```

So you are saying that for an older version you don't get this error?

So it looks like you are getting an error from the Resource Provider.  Have you contacted support with the error above?  Without knowing exactly what is happening on the RP side makes it hard to determine if it is because the SDK is wrong or the RP is wrong.

**Comment by vithal-wadje** [comment]
Thanks @deathly809  for your response , yes when downgrade Microsoft.Rest.ClientRuntime.Azure.Authentication its work but if Newtonsoft.Json & System.Net.Http  are already installed in solution which requires to run other module of projects & later on we install Microsoft.Azure.Management.DeviceProvisioningServices and Microsoft.Azure.Management.ResourceManager.Fluent its give error . one thing I observed that when you install Microsoft.Azure.Management.ResourceManager.Fluent its add own Newtonsoft.Json & System.Net.Http as wrapper , might be that causing problem .  We haven't contacted yet to support team but we will. Thanks for your valuable time.

**Comment by deathly809** [comment]
@vithal-wadje The only thing I can think of is that the new NewtonSoft library serializes differently than what is expected on the other end.  Good luck!

**Comment by vithal-wadje** [comment]
@deathly809 thanks you so much for your response , after some trouble shooting I removed application insight packages from my solution then issue is resolved . Its surprise what is the relation between application insight &  Microsoft.Azure.Management.DeviceProvisioningServices , Please reproduce this issue & check , if need any details , Please let me know .
