### ISSUE TITLE
Azure Search: MaxAgeInSeconds not set in code causes "null" value in portal

### ISSUE THREAD

**Issue by christian-vorhemus** [Azure/azure-sdk-for-net#4291]
I create an index with the Azure Search .NET SDK like so

```c#
var articlesDefinition = new Microsoft.Azure.Search.Models.Index()
{
    Name = "articles-index",
    Fields = FieldBuilder.BuildForType<ArticlesIndex>(),
    CorsOptions = new CorsOptions() { AllowedOrigins = new List<string> { "*" } }
};
```
Everything runs fine. When I open the Azure Portal and go to the Azure Search Index CORS settings, I see this:

<img src="https://user-images.githubusercontent.com/3229424/39705922-13829d4e-5210-11e8-811e-d350c05f8025.png" width="340" />

On the one hand, this makes sense because I didn't set "MaxAgeInSeconds" in the code, on the other hand: Should this value really be "null"? I expected it to be the default value (5 minutes)

**Comment by brjohnstmsft** [comment]
@christian-vorhemus Thanks for reporting this. Without having investigated further, I speculate that the REST API does not return the `maxAgeInSeconds` property if it has never been set, and the Azure portal interprets the missing property as "null". This doesn't make for a smooth portal experience. I'll discuss with the team what the best solution is and get back to you.

**Comment by jj09** [comment]
In REST API we treat null as default value. In this case default value is 300.
We do not handle this use case in Portal correctly. We do not convert null to 300.
We are going to fix this on the Portal side.

**Comment by brjohnstmsft** [comment]
@christian-vorhemus Since this is an issue with our Azure portal extension and not with the SDK per se, I'm going to close this issue.

**Comment by christian-vorhemus** [comment]
Alright, thanks for your help!
