### ISSUE TITLE
What is read from a blob if it's modified while being read with `allowModifications=false`?

### ISSUE THREAD

**Issue by Regenhardt** [Azure/azure-sdk-for-net#42927]
### Type of issue

Missing information

### Description

The docs only state that if set to true, an exception will be thrown. 

What happens otherwise though?  

Will the stream continue seamlessly but at some point will receive bytes containing modified data, so potentially byte 0-99 are old data and byte 100-199 are new data?

Or will it just stop? 

Or will it start over?

Or will it still receive the rest of the unmodified data?

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.models.blobopenreadoptions.-ctor?view=azure-dotnet

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Blobs.Models/BlobOpenReadOptions.xml

### Document Version Independent Id

d91bcc83-e7eb-26c4-9f81-4dd753fa0b08

### Article author

@azure-sdk

### Metadata

* ID: ab56d1cc-91db-e36c-69d9-a2ec371de0f9 
* Service: **azure**

**Comment by seanmcc-msft** [comment]
@Regenhardt, the OpenRead API will stop reading and throw an exception.
