### ISSUE TITLE
PipelineMessage should check for null on arguments that it uses

### ISSUE THREAD

**Issue by m-nash** [Azure/azure-sdk-for-net#42964]
### Library name

System.ClientModel

### Please describe the feature.

In [this method](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/System.ClientModel/src/Message/PipelineMessage.cs#L116) we blindly use options without first checking if it is null.  If the client library has nullable disabled this is possible to make this call.

An alternative here would be to perform a no op if it is null with this implementation

```c#
    public void Apply(RequestOptions options)
    {
        options?.Apply(this);
    }

```

**Comment by annelo-msft** [comment]
Thanks, @m-nash.  We will throw ArgumentNullException here instead.

I'll also do a pass over the library to see if there are other places we're not validating arguments that we expect not to be null.

Thanks for catching this!
