### ISSUE TITLE
[OpenAI] `StreamingClientResult` should implement `IAsyncDisposable`

### ISSUE THREAD

**Issue by joseharriaga** [Azure/azure-sdk-for-net#43032]
https://apiview.dev/Assemblies/Review/abf39c5b6bd9459f81706dfc751197b5#10a2bddb8bfa4b1b9b961f9452856837

[annelo-msft](https://apiview.dev/Assemblies/Profile/annelo-msft) [6 days ago](https://apiview.dev/Assemblies/Review/abf39c5b6bd9459f81706dfc751197b5#10a2bddb8bfa4b1b9b961f9452856837)
Moving the old comment - should this implement IAsyncDisposable? Or, should it move the resources that need to be disposed into the enumerator implementation, since that implements IAsyncDisposable already?

If we decide to keep this one as IDisposable for whatever reason, we might want to consider updating the usage samples to use it in a using statement?

**Comment by annelo-msft** [comment]
I believe we can actually remove IDispose from the StreamingClientResult implementation and handle disposing the pieces that need to be disposed from the async enumerator, which implements IAsyncDisposable already.  Let me know if you'd like me to share further details.

**Comment by annelo-msft** [comment]
Addressed by https://github.com/Azure/azure-sdk-for-net/issues/42284
