### ISSUE TITLE
[FEATURE REQ] Add support for streaming responses from assistants (Azure.AI.OpenAI.Assistants)

### ISSUE THREAD

**Issue by ips-jm** [Azure/azure-sdk-for-net#43033]
### Library name

Azure.AI.OpenAI.Assistants

### Please describe the feature.

OpenAI added streaming support for agents two weeks ago. Would be nice to see this implemented here.

**Comment by regenthor** [comment]
Any news or roadmap?

**Comment by regenthor** [comment]
Any news ?

**Comment by oyvhvi** [comment]
Need!

**Comment by scottaddie** [comment]
[Streaming is fully supported](https://github.com/openai/openai-dotnet?tab=readme-ov-file#how-to-use-streaming-and-gpt-4o-vision-with-assistants), but you'll need to migrate to the Azure.AI.OpenAI package.
