### ISSUE TITLE
[FEATURE REQ] `ContainerAppData` should provide a field for app URL

### ISSUE THREAD

**Issue by kaibocai** [Azure/azure-sdk-for-net#43047]
### Library name

Azure.ResourceManager.AppContainers

### Please describe the feature.

The class `ContainerAppData` should provide a field for the app URL, currently it only provides 
```csharp
  /// <summary> Fully Qualified Domain Name of the latest revision of the Container App. </summary>
  public string LatestRevisionFqdn { get; }
```
but app URL is also commonly used and it should be provided.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
@Juliehzl can you help on this question?

**Comment by Juliehzl** [comment]
@kaibocai  why do you want to provide it? If you want to add custom domain for the app, please configure custom domain part in  `Configuration.Ingress.CustomDomains`

**Comment by kaibocai** [comment]
@Juliehzl Thanks for the response. I will check out the custom domain. Just curious, will using a custom domain add any performance/bill overhead? Does it configure a private Azure DNS zone under the hood? Thanks.
