### ISSUE TITLE
[Spike] Consider evaluating HLC extensions on top of generator extension plugin to migrate HLC to Typespec

### ISSUE THREAD

**Issue by pallavit** [Azure/azure-sdk-for-net#43042]
In order to move HLCs to Typespec one option would be to write extensions for each HLC on top of our generator extension plugin and have the codegen generate the correct convenience layer for our SDKs.

**Comment by jsquire** [comment]
Given that HLCs are a small portion of our libraries and support exists in AutoRest to generate these from TypeSpec today, the current plan is to not move these to MGC.    Closing this out for now.
