### ISSUE TITLE
[FEATURE REQ] Support for cross-tenant requests and OBO token per request.

### ISSUE THREAD

**Issue by kalbert312** [Azure/azure-sdk-for-net#43068]
### Library name

Azure.ResourceManager.Resources 1.7.0

### Please describe the feature.

My team has adopted the .NET Track 2 SDK in the `Microsoft.Resources/deploymentStacks` RP. Our usages are currently within our jobs that run for a single tenant and we create a client on the fly with a custom `TokenCredential` implementation that accepts a tenant id from the job metadata.

At some point, we may need to pull in the SDK into our web service which receives a tenant id header and OBO token from ARM. I was looking into how to set a tenant id per SDK request rather than for all requests but I'm having trouble seeing how it could be done.

`TokenRequestContext` has a `TenantId` field, but it looks like it's not set by `BearerTokenAuthenticationPolicy`: https://github.com/Azure/azure-sdk-for-net/blob/900e673b392bca242a1429e70dc2025f5407d680/sdk/core/Azure.Core/src/Pipeline/BearerTokenAuthenticationPolicy.cs#L74
I see the method is `protected virtual`, so I thought I could potentially make a custom implementation to grab the tenant id from a `HttpMessage` request header, but there's a couple issues:
1. The `BearerTokenAuthenticationPolicy` implementation is not customizable in a generated(?) SDK client like `ArmClient` as it's added within the constructor: https://github.com/Azure/azure-sdk-for-net/blob/900e673b392bca242a1429e70dc2025f5407d680/sdk/resourcemanager/Azure.ResourceManager/src/ArmClient.cs#L79
2. There's no way to pass a tenant id from an SDK request like `armClient.GetGenericResource(ResourceIdentifier).GetAsync()`, modify the `HttpMessage` for the request, or pass in a `RequestContext`. I don't see this for pretty much all `ArmClient` methods either.

2 is the same situation for when an OBO-token request header needs to be a set for a single request.

It would be great to get support for setting a tenant id for authentication per request, as well as setting an OBO token per request.

**Comment by mcgallan** [comment]
Hi @kalbert312 Thank you for your feedback. Regarding the functionality you need to implement, as far as I know in the SDK, if you want to change the tenantid and OBO token, you may need to create a new service client for each request. Currently, the SDK does not provide a method to directly set the OBO token and tenantid at each request level. As for how to get the tenantid from the HttpMessage request header, you can try the following method after obtaining the HttpMessage:
```
HttpRequestMessage request
if (request.Headers.TryGetValues("tenantID", out var values))
{
    string tenantID = values.FirstOrDefault();
}
```

**Comment by kalbert312** [comment]
@mcgallan That is the only workaround that I could find, however it seems inefficient to instantiate a new client for each request. The web service could be receiving a high number of requests per second, causing many more instantiations of the client and internals, increasing the load on the web server (how much I'm not certain, I have not done any measurements). We'd also lose out on OOB caching mechanisms offered by the client such as auth token caching (although only the auth token from the latest TokenAuthContext is cached, so if tenant id changes, it will not use a cached version per tenant id).

Ideally, we'd want to instantiate a single instance of the SDK client at service startup and inject that instance to all request threads so it's ready to go. Per tenant auth token caching auth token would further reduce the number of outgoing requests required.

**Comment by HarveyLink** [comment]
Hi @kalbert312 ,
We could only operate on one single tenant in one ArmClient. If you need to operate other tenant, you may have to create different ArmClient with that tenant Id. This is by desgin for now. We may consider to add cross tenant support in the future.
