### ISSUE TITLE
Correct IMDS resource ID query parameter

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-net#43076]
### Library name

Azure.Identity

### Please describe the feature.

Specifying an identity by resource ID doesn't work on Azure Container Instances (and maybe some other platforms) because we specify the resource ID with query parameter "mi_res_id". ACI observes only "m**s**i_res_id", which we should prefer anyway because although IMDS observes both parameters, it [documents only msi_res_id](https://github.com/Azure/azure-rest-api-specs/blob/dba6ed1f03bda88ac6884c0a883246446cc72495/specification/imds/data-plane/Microsoft.InstanceMetadataService/stable/2018-10-01/imds.json#L233-L239). Related: Azure/azure-sdk-for-go#22650

**Comment by tasnef** [comment]
stop ⛔️⛔️⛔️⛔️⛔️

**Comment by christothes** [comment]
created an MSAL issue [here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4911)
