### ISSUE TITLE
[BUG] Visual Studio Credential looking for tokenprovider.json file at wrong file path

### ISSUE THREAD

**Issue by funkel1989** [Azure/azure-sdk-for-net#43101]
### Library name and version

Azure.Identity 1.10.4

### Describe the bug

running a dotnet 8 Native AOT application configured to build for docker support on linux x64 systems. When running locally in Windows 11 Visual Studio 2022 an exception is throw by the visual studio authentication provider with the below message:
```
IO_PathNotFound_Path, /home/app/.IdentityService/AzureServiceAuth/tokenprovider.json
```

I found this PR: https://github.com/Azure/azure-sdk-for-net/pull/33556/files which seems to address this issue but i'm assuming there is a bug with how RuntimeInformation.IsOSPlatform works with set configurations for Native AOT applications.

Here is my csproj file configuration for native aot: 
```
<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<InvariantGlobalization>true</InvariantGlobalization>
		<PublishAot>true</PublishAot>
		<RuntimeIdentifier>linux-x64</RuntimeIdentifier>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<OutputType>exe</OutputType>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<EventSourceSupport>false</EventSourceSupport>
		<UseSystemResourceKeys>true</UseSystemResourceKeys>
		<StripSymbols>true</StripSymbols>
		<OptimizationPreference>Speed</OptimizationPreference>
		<Platforms>x64</Platforms>
	</PropertyGroup>
```

### Expected behavior

Expect it to correctly detect that i'm running on a windows system even when the contain is being executing inside of a docker desktop app to find the file it requires.

### Actual behavior

It is looking for the token provider on a linux file path and not a windows file path and will never work like this.

### Reproduction Steps

create a new Dotnet 8 native aot application building for linux with linux docker support running on docker desktop on a windows 11 machine.

```
builder.Configuration.AddAzureKeyVault(
    new Uri(settings.AzureKeyVaultUrl),
    new DefaultAzureCredential(
        new DefaultAzureCredentialOptions { TenantId = settings.AzureTenantId, VisualStudioTenantId = settings.AzureTenantId, IsUnsafeSupportLoggingEnabled = true}),
    new KeyVaultSecretReplacer(builder.Configuration));
```

### Environment

dotnet --info
.NET SDK:
 Version:           8.0.200
 Commit:            438cab6a9d
 Workload version:  8.0.200-manifests.e575128c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.200\

.NET workloads installed:
 [maui-windows]
   Installation Source: VS 17.9.34622.214
   Manifest Version:    8.0.6/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.6\WorkloadManifest.json
   Install Type:        FileBased

 [maccatalyst]
   Installation Source: VS 17.9.34622.214
   Manifest Version:    17.2.8004/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maccatalyst\17.2.8004\WorkloadManifest.json
   Install Type:        FileBased

 [android]
   Installation Source: VS 17.9.34622.214
   Manifest Version:    34.0.52/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.android\34.0.52\WorkloadManifest.json
   Install Type:        FileBased

 [ios]
   Installation Source: VS 17.9.34622.214
   Manifest Version:    17.2.8004/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.ios\17.2.8004\WorkloadManifest.json
   Install Type:        FileBased

Host:
  Version:      8.0.2
  Architecture: x64
  Commit:       1381d5ebd2

.NET SDKs installed:
  8.0.200 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
//cc @NCarlsonMSFT

**Comment by NCarlsonMSFT** [comment]
@funkel1989 If I understand you're repro correctly, you're running an app published using AOT in a linux container through the Visual Studio container tools. Is that correct?
If so, it's an expected shortcoming of the way the token proxying from VS works that it doesn't support containers that don't have the .NET runtime installed (for instance the runtime-deps base image used by an AOT project). I have posted an example with a work-around that swaps out the base image when debugging in VS to add the needed .NET runtime and the GDB debugger: https://github.com/NCarlsonMSFT/VisualStudioCredentialExample/commit/b36d0fe216622dbec3049e3f9da8686759a5c8de. Does that unblock you?

**Comment by funkel1989** [comment]
@NCarlsonMSFT I made the changes shown in your commit and didn't seem to get any further in this process. For clarity I'm trying to solve this as another potential solution to handling secrets locally for a team of developers where I've built a secret replacer and they can access an azure keyvault with permissions granted via the account they have used to log into visual studio with. 

You are correct that I am running a AOT app published to a Linux container through Video Studio Container Tools. My local workstation running visual studio is a windows 11 machine. When the DefaultCredential attempts to authenticate I get 7 internal exceptions. The third one is always regarding the Visual Studio token provider and always has a message of:

```
Visual Studio Token provider can't be accessed at /home/app/.IdentityService/AzureServiceAuth/tokenprovider.json

Inner Exception Message: IO_PathNotFound_Path, /home/app/.IdentityService/AzureServiceAuth/tokenprovider.json
```

Its looking for this file (which does exist on my local machine) in a directory inside of the container in which it is running instead of the host machine. Thinking about this more... this is probably intended and the way I'm attempting to go about this may not be supported now or ever. It doesn't seem like the runtime dep container is missing anything as adding the aotdebug container made no changes in the way it operated.

**Comment by NCarlsonMSFT** [comment]
@funkel1989 looking for the file in the container is the expected behavior, when debugging from Visual Studio it starts a service that generates the config file in the container and orchestrates proxying communication with the launching visual studio for authentication ([docs](https://learn.microsoft.com/en-us/visualstudio/containers/container-tools-configure?view=vs-2022#configure-azure-authentication)).  

Some more clarifying questions:  
* Are you running your container from VS (F5 or Ctrl+F5) or publishing and then running the image? The token proxy is only inserted when run from VS (17.6+).
* Are you running your container in Fast mode or Regular mode? If you haven't set [`ContainerDevelopmentMode`](https://learn.microsoft.com/en-us/visualstudio/containers/container-msbuild-properties) the default is Fast for the Debug Configuration, Regular for all other Configurations.
* If you set the environment variable `MS_VS_CONTAINERS_TOOLS_LOGGING_ENABLED` to `1` before launching VS and check the logs in  `%tmp%\Microsoft.VisualStudio.Containers.Tools`, do you see any errors from the token proxy?
* If you `docker exec` into your container, what is the output from `dotnet --info` ?
