### ISSUE TITLE
Package "Microsoft.Rest.ClientRuntime" fails to install from nuget.org

### ISSUE THREAD

**Issue by gppanayotov** [Azure/azure-sdk-for-net#4310]
When you try to install "Microsoft.Rest.ClientRuntime" from nuget.org it fails with error that it can't find one or more of the dependent packages "System.Reflection.Emit.Lightweight"

Looking at https://www.nuget.org/packages/System.Reflection.Emit.Lightweight/4.0.0 , this package has been unlisted. 

in order to reproduce run "install-Package -Source "http://www.nuget.org/api/v2/"  Microsoft.Rest.ClientRuntime"

PS C:\> install-Package -Source "http://www.nuget.org/api/v2/"  Microsoft.Rest.ClientRuntime

The package(s) come from a package source that is not marked as trusted.
Are you sure you want to install software from 'nuget'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): a
install-Package : **Unable to find dependent package(s) (System.Reflection.Emit.Lightweight)**
At line:1 char:1
+ install-Package -Source "http://www.nuget.org/api/v2/"  Microsoft.Res ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (System.Reflection.Emit.Lightweight:String) [Install-Package], Exception
    + FullyQualifiedErrorId : UnableToFindDependencyPackage,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

**Comment by shahabhijeet** [comment]
@gppanayotov what OS and what versoin of VS (if any) installed on your machine.
Also list .NET Core version installed on your machine.
I tried reproducing this error but could not.
Below is the output from
1) Console App targeting 4.6.1


Attempting to gather dependency information for package 'Microsoft.Rest.ClientRuntime.2.3.11' with respect to project 'ConsoleApp5', targeting '.NETFramework,Version=v4.6.1'
Gathering dependency information took 711.63 ms
Attempting to resolve dependencies for package 'Microsoft.Rest.ClientRuntime.2.3.11' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Microsoft.Rest.ClientRuntime.2.3.11'
Resolved actions to install package 'Microsoft.Rest.ClientRuntime.2.3.11'
Retrieving package 'Microsoft.Rest.ClientRuntime 2.3.11' from 'nuget.org'.
Retrieving package 'Newtonsoft.Json 6.0.8' from 'nuget.org'.
  GET https://api.nuget.org/v3-flatcontainer/microsoft.rest.clientruntime/2.3.11/microsoft.rest.clientruntime.2.3.11.nupkg
Adding package 'Newtonsoft.Json.6.0.8' to folder 'c:\users\labuser\documents\visual studio 2017\Projects\ConsoleApp5\packages'
  OK https://api.nuget.org/v3-flatcontainer/microsoft.rest.clientruntime/2.3.11/microsoft.rest.clientruntime.2.3.11.nupkg 259ms
Installing Microsoft.Rest.ClientRuntime 2.3.11.
Added package 'Newtonsoft.Json.6.0.8' to folder 'c:\users\labuser\documents\visual studio 2017\Projects\ConsoleApp5\packages'
Added package 'Newtonsoft.Json.6.0.8' to 'packages.config'
Executing script file 'c:\users\labuser\documents\visual studio 2017\Projects\ConsoleApp5\packages\Newtonsoft.Json.6.0.8\tools\install.ps1'...
Successfully installed 'Newtonsoft.Json 6.0.8' to ConsoleApp5
Adding package 'Microsoft.Rest.ClientRuntime.2.3.11' to folder 'c:\users\labuser\documents\visual studio 2017\Projects\ConsoleApp5\packages'
Added package 'Microsoft.Rest.ClientRuntime.2.3.11' to folder 'c:\users\labuser\documents\visual studio 2017\Projects\ConsoleApp5\packages'
Added package 'Microsoft.Rest.ClientRuntime.2.3.11' to 'packages.config'
Successfully installed 'Microsoft.Rest.ClientRuntime 2.3.11' to ConsoleApp5
Executing nuget actions took 4.26 sec
Time Elapsed: 00:00:05.2615597
========== Finished ==========

2) .NET Core app targeting .Net CoreApp 1.1

Package Manager Console Host Version 4.2.0.2457

Type 'get-help NuGet' to see all available NuGet commands.

PM> Install-Package Microsoft.Rest.ClientRuntime
Restoring packages for c:\users\labuser\documents\visual studio 2017\Projects\ClassLibrary1\ClassLibrary1\ClassLibrary1.csproj...
Installing NuGet package Microsoft.Rest.ClientRuntime 2.3.11.
Committing restore...
Writing lock file to disk. Path: c:\users\labuser\documents\visual studio 2017\Projects\ClassLibrary1\ClassLibrary1\obj\project.assets.json
Restore completed in 905.47 ms for c:\users\labuser\documents\visual studio 2017\Projects\ClassLibrary1\ClassLibrary1\ClassLibrary1.csproj.
Successfully installed 'Microsoft.Rest.ClientRuntime 2.3.11' to ClassLibrary1
Successfully installed 'Newtonsoft.Json 9.0.1' to ClassLibrary1
Successfully installed 'System.Runtime.Serialization.Primitives 4.1.1' to ClassLibrary1
Executing nuget actions took 967.44 ms
Time Elapsed: 00:00:02.4129338

**Comment by gppanayotov** [comment]
@shahabhijeet

I tried this on both win7 and win 10. 
I don't have VS installed and not using the VSs Package Manager Console just the Powershell's Package Management module. 

My use case is to get PSSwagger module up ( https://github.com/PowerShell/PSSwagger) 
which has a dependency on Microsoft.Rest.ClientRuntime. 

PS H:\> dotnet --info
.NET Command Line Tools (2.1.200)

Product Information:
 Version:            2.1.200
 Commit SHA-1 hash:  2edba8d7f1

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.200\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11

**Comment by shahabhijeet** [comment]
@gppanayotov at this point please provide clear repro steps.
I will need exact steps to reproduce this issue.
The issue you have reported (unbale to restore a nuget package) is so fundamental that I would like to reproduce it but I am unable to.

**Comment by sassov** [comment]
I have a project with the MS.Rest.ClientRuntime version of 2.3.8 with .net v4.7.2. I'm trying to upgrade the clientruntime to v2.3.20 and it fails. Newtonsoft.Json version installed is v12.0.2.

**Comment by adrianhall** [comment]
@sassov - this feels like a new issue.  Can you please move to a new issue and define what "fails" means for you - is there an exception?  if so, what?  Does it fail to build?  If so, what does the trace look like?

This needs to be entered in a new issue, rather than a stale one as we don't review stale issues as often.
