### ISSUE TITLE
LUIS sdk nugets missing

### ISSUE THREAD

**Issue by abishekreddy** [Azure/azure-sdk-for-net#4311]
The RuntimeAPI nuget `Microsoft.Azure.CognitiveServices.Language.LUIS (2.0.0) `and the ProgrammaticAPI nuget `Microsoft.Azure.CognitiveServices.Language.LUIS.Programmatic (2.0.0)` are missing from the public nuget repository.

**Comment by ronak25** [comment]
I added Kirthi and David Li to the thread. My team doesn't own Luis.

Ronak.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by cahann** [comment]
we are working on exposing this in the coming couple of months
