### ISSUE TITLE
[BUG] Recent commit introduced NullReferenceException in LogsQueryClient constructor

### ISSUE THREAD

**Issue by kirk-marple** [Azure/azure-sdk-for-net#43115]
### Library name and version

Azure.Monitor.Query 1.3.0.0

### Describe the bug

In commit 7ebbbd0 by @nisha-bhatia, there was a recent change which can cause a NullReferenceException if the LogsQueryClient constructor is called with just the credential.

If the second parameter is null, then options.Audience?.ToString() will throw an exception since options is null.

```
        /// <summary>
        /// Creates an instance of <see cref="LogsQueryClient"/> for Azure Public Cloud usage. Uses the default 'https://api.loganalytics.io' endpoint.
        /// <code snippet="Snippet:CreateLogsClient" language="csharp">
        /// var client = new LogsQueryClient(new DefaultAzureCredential());
        /// </code>
        /// </summary>
        /// <param name="credential">The <see cref="TokenCredential"/> instance to use for authentication.</param>
        public LogsQueryClient(TokenCredential credential) : this(credential, null)
        {
        }

        /// <summary>
        /// Creates an instance of <see cref="LogsQueryClient"/> for Azure Public Cloud usage. Uses the default 'https://api.loganalytics.io' endpoint, unless <see cref="LogsQueryClientOptions.Audience"/> is set to an Azure sovereign cloud.
        /// </summary>
        /// <param name="credential">The <see cref="TokenCredential"/> instance to use for authentication.</param>
        /// <param name="options">The <see cref="LogsQueryClientOptions"/> instance to use as client configuration.</param>
        public LogsQueryClient(TokenCredential credential, LogsQueryClientOptions options) : this(string.IsNullOrEmpty(options.Audience?.ToString()) ? _defaultEndpoint : new Uri(options.Audience.ToString()), credential, options)
        {
        }
```

### Expected behavior

No exception, constructor should work as before.

### Actual behavior

Null reference exception when using this constructor.

new LogsQueryClient(credential)

### Reproduction Steps

Instantiate a LogsQueryClient with:

var credential = new ClientSecretCredential(settings.TenantId, settings.ClientId, settings.ClientSecret);
var client = new LogsQueryClient(credential)

### Environment

.NET 6, C#

**Comment by kirk-marple** [comment]
![image](https://github.com/Azure/azure-sdk-for-net/assets/13594550/f7e3884d-6134-425c-aa03-9671b7c1afb7)

**Comment by pallavit** [comment]
@nisha-bhatia do you want to patch the GA SDK for this fix? Should we consider adding more test coverage here?

**Comment by m33p** [comment]
I just came across the same error "NullReferenceException" after updating to 1.3.0.

**Comment by nisha-bhatia** [comment]
A new Nuget package has been released fixing this!
