### ISSUE TITLE
What does MaxConcurrentCallsPerSession do?

### ISSUE THREAD

**Issue by agiordimaina** [Azure/azure-sdk-for-net#43124]
### Library name and version

Azure.Messaging.ServiceBus 7.17.4

### Query/Question

I am currently using a queue without sessions and with MaxConcurrentCalls set to 5 in order to process multiple messages in parallel, which works fine. I am now considering extending our system and we may need to enable sessions.

So for testing I am trying to use MaxConcurrentCallsPerSession. The issue is that I am only able to process 1 message at a time.

I am aware that queues with sessions enabled are designed to enforce FIFO but even when setting the ReceiveMode to ReceiveAndDelete I am still unable to process messages in parallel.

This is a sample code that I wrote:

    static void Main()
    {
        MainAsync().Wait();
    }

    static async Task MainAsync()
    {
        //create the queue
        await CreateQueue();

        //initialize queue client
        ServiceBusClient queueClient = new ServiceBusClient(_serviceBusConnectionString, new ServiceBusClientOptions
        {
            TransportType = ServiceBusTransportType.AmqpWebSockets,
        });

        //initialize the sender
        ServiceBusSender sender = queueClient.CreateSender(_queueName);

        //queue 3 messages
        await sender.SendMessageAsync(new ServiceBusMessage() { SessionId = _sessionId, MessageId = "1" });
        await sender.SendMessageAsync(new ServiceBusMessage() { SessionId = _sessionId, MessageId = "2" });
        await sender.SendMessageAsync(new ServiceBusMessage() { SessionId = _sessionId, MessageId = "3" });

        //initialize processor
        ServiceBusSessionProcessor processor = queueClient.CreateSessionProcessor(_queueName, new ServiceBusSessionProcessorOptions()
        {
            AutoCompleteMessages = false,
            ReceiveMode = ServiceBusReceiveMode.PeekLock,
            SessionIds = { _sessionId },
            PrefetchCount = 5,
            MaxConcurrentCallsPerSession = 5
        });

        //add message handler
        processor.ProcessMessageAsync += HandleReceivedMessage;

        //add error handler
        processor.ProcessErrorAsync += ErrorHandler;

        //start the processor
        await processor.StartProcessingAsync();

        Console.ReadLine();
    }

    static async Task CreateQueue()
    {
        ServiceBusAdministrationClient client = new ServiceBusAdministrationClient(_serviceBusConnectionString);

        bool doesQueueExist = await client.QueueExistsAsync(_queueName);

        //check if the queue exists, if not then create one
        if (!doesQueueExist)
        {
            _ = await client.CreateQueueAsync(new CreateQueueOptions(_queueName)
            {
                RequiresSession = true,
                DeadLetteringOnMessageExpiration = true,
                MaxDeliveryCount = 3,
                EnableBatchedOperations = true,
            });
        }
    }

    static async Task HandleReceivedMessage(ProcessSessionMessageEventArgs sessionMessage)
    {
        Console.WriteLine("Received message: " + sessionMessage.Message.MessageId);

        await Task.Delay(5000).ConfigureAwait(false);

        await sessionMessage.CompleteMessageAsync(sessionMessage.Message);

        Console.WriteLine("Completed message: " + sessionMessage.Message.MessageId);
    }

    static Task ErrorHandler(ProcessErrorEventArgs e)
    {
        Console.WriteLine("Error received");

        return Task.CompletedTask;
    }

When executing the program, what I expect to receive is:

> Received message: 1
> Received message: 2
> Received message: 3
> Completed message: 1
> Completed message: 2
> Completed message: 3

But what I am getting is:

> Received message: 1
> Completed message: 1
> Received message: 2
> Completed message: 2
> Received message: 3
> Completed message: 3

So my question is, if this is by design that you are unable to process multiple messages in parallel because the queue is enforcing FIFO, then what does MaxConcurrentCallsPerSession actually do?

### Environment

.NetFramework 4.7.2

**Comment by m-redding** [comment]
Hi @agiordimaina! Thank you for reaching out and providing such a helpful description of the issue. I was able to reproduce this locally and found this is a bug with the `SessionIds` setting. Session processors that specify session ids weren't factoring in the max concurrent calls per session. Fix is in https://github.com/Azure/azure-sdk-for-net/pull/43157 but pending on some unrelated pipeline issues.

**Comment by agiordimaina** [comment]
Hi @m-redding, that is great to know thanks! I'll keep an eye out for the fix.
