### ISSUE TITLE
[QUERY] How to force to delete a CosmosDBSqlDatabaseResource?

### ISSUE THREAD

**Issue by abiisnn** [Azure/azure-sdk-for-net#43139]
### Library name and version

Azure.ResourceManager 1.4.0

### Query/Question

Hi, I have the following code that deletes a Database:

```
try
{
     CosmosDBAccountResource accountResource = await GetCosmosDBAccount(subscriptionId, resourceGroupName, databaseAccountName, cancellationToken);
     CosmosDBSqlDatabaseResource databaseResource = await accountResource.GetCosmosDBSqlDatabaseAsync(databaseName, cancellationToken);

      await databaseResource.**DeleteAsync**(WaitUntil.Completed, cancellationToken);
}
```

which is returning the following error in some cases:

`"exceptionDetails": "System.AggregateException: One or more errors occurred. (Message: {\"code\":\"Forbidden\",\"message\":\"Message: {\\\"Errors\\\":[\\\"The requested operation cannot be performed at this region\\\"]}`

We figured out that this error is happening because the user deleted the Key vault, but **we would like "force to delete" the database**, is there a way we can do that?

Thanks

**Comment by HarveyLink** [comment]
Hi @abiisnn , Thank you for using Azure SDK for .NET.
Our SDK is auto generated from the REST API, we don't have much domain knowledge on a specific service.
You could [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) to get the help you need.
