### ISSUE TITLE
When Are you going to fix the Method not found exception 

### ISSUE THREAD

**Issue by qamessenger** [Azure/azure-sdk-for-net#4316]
This issue has not been resolved 

System.MissingMethodException : Method not found: 'System.Threading.Tasks.Task`1 Microsoft.Rest.Azure.Authentication.UserTokenProvider.LoginSilentAsync(System.String, System.String, System.String, System.String, Microsoft.Rest.Azure.Authentication.ActiveDirectoryServiceSettings, Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache)'.

This occurs when using library Microsoft.Rest.ClientRuntime.Azure.Authentication version 2.3.3 if you downgrade to version 2.3.2 works fine.

**Comment by shahabhijeet** [comment]
@qamessenger with 2.3.3 we made few fundamental changes
1) User Token provider is no longer supported beyond 2.28.x of ADAL. We decided to support User token provider for .NET 4.5.2 ONLY
2) If you want to target .NET > 4.5.2 and beyond (e.g. .NET 4.6.1) we will support ADAL >= 3.14.x and anything >= ADAL 3.14.x does not support user token provider.

So in your case if you would like to use UserToken provider, you best bet is to use .NET 4.5.2 version and that will work without any issues.

If you still see any issue, either reopen this issue or open a new one with repro steps.

**Comment by lbsong** [comment]
@shahabhijeet I am using Microsoft.Azure.Management.Fluent to create VM, which apparently relies on this method UserTokenProvider.LoginSilentAsync. If User Token Provider is no longer supported, which NuGet package of Microsoft.Azure.Management.Fluent is updated for this change?
