### ISSUE TITLE
Getting AzureServicesAuthConnectionString to work with CertificateThumbprint

### ISSUE THREAD

**Issue by adwhiteMS** [Azure/azure-sdk-for-net#4317]
I'm trying to get access to my Keyvault in an Azure Functon using Managed Service Identity's when debugging locally.  I followed the instructions found here:

https://docs.microsoft.com/en-us/azure/app-service/app-service-managed-service-identity

and here

https://github.com/Azure-Samples/app-service-msi-keyvault-dotnet

 I have configured AzureServicesAuthConnectionString in my functions local.settings.json:

AzureServicesAuthConnectionString= RunAs=App;AppId={MyApp Id} ;TenantId={My tenantID} ;CertificateThumbprint={My Service Prin Cert Thumb print};CertificateStoreLocation=CurrentUser

When I run my functions locally and it tries to fetch a secret from my keyvault I get this error:

[5/14/2018 8:06:50 PM] A ScriptHost error has occurred
[5/14/2018 8:06:50 PM] Unhandled exception trying to load the tenant configuration from key vault: Parameters: Connectionstring: RunAs=App;AppId={Removed value};TenantId={Removed Value};CertificateThumbprint={My Cert's thumbprint};CertificateStoreLocation=CurrentUser, Resource: https://vault.azure.net, Authority: https://login.windows.net/... Exception Message: Tried 1 certificate(s). Access token could not be acquired.
[5/14/2018 8:06:50 PM] Exception for cert #1 with thumbprint {Cert Thumbprint}: Object reference not set to an instance of an object.

I know the application can find my cert, because when I enter an invalid value, it tells me that the cert thumbprint I provided cannot be found. 

If I configure AzureServicesAuthConnectionString to use the client secret (AppKey) everything works.  Unfortunately using the AppKey is a temporary fix, because I don't want to checkin code with my client secret.

**Comment by adwhiteMS** [comment]
Hello Varun,


I’m using Microsoft.Azure.Services.AppAuthentication 1.1.0-preview.  Is that the latest version?  Or are you asking about a different library?



I don’t have a good reason why my team went down the service principal route.  I agree managing the cert is a pain, but before I start reworking stuff I would like to try and get this working.



On a side note, I have another nuget package that leverages the Microsoft.IdentityModel.Clients.ActiveDirectory, but that package uses version 3.19.  If I include that project in my function project and try to run my function I get this error:


Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.14.2.11, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.



I had to downgrade my nugets packages to use Microsoft.IdentityModel.Clients.ActiveDirectory version 3.14.2 so I won’t get that error.



Thanks,

Adam

**Comment by adwhiteMS** [comment]
@varunsh-msft,   We are already targeting .NET 4.6.2, due to an issue we are having.  What is interesting after reading issue [752](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/752), the cert we are trying to use has its private key marked as not exportable, but according to issue 752 this problem should only be in 4.7.X   Any other ideas?

Right now I'm using version 1 of Azure Functions.  Based on the wiki link you mentioned the Azure Function team tried to implement some major changes to fix runtime assembly issues in version 2.  When I created my Azure function I only choose version 1 because version 2 was in preview.  I will try switching to version 2 to see if that solves any problems.

**Comment by nonik0** [comment]
Hi Adam, were you able to resolve this issue?

**Comment by dft616** [comment]
I was having this issue on a console app running locally that we run as a webjob in Azure. I was only getting the error running locally authenticating to keyvault with a cert. Switching my app back to 4.6.2 fixed the problem. My package config looked like this:

  <package id="Microsoft.Azure.KeyVault" version="3.0.2" targetFramework="net472" />
  <package id="Microsoft.Azure.KeyVault.Core" version="3.0.1" targetFramework="net472" />
  <package id="Microsoft.Azure.KeyVault.WebKey" version="3.0.2" targetFramework="net472" />
  <package id="Microsoft.Azure.Services.AppAuthentication" version="1.0.0" targetFramework="net472" />

**Comment by dft616** [comment]
Updating Microsoft.Azure.Services.AppAuthentication to 1.2.0-preview fixed my issue.

**Comment by mliesmons** [comment]
The preview is buit against 3.19.4 also.
What a mess, clean this up please!

BTW, this hard-coding of version upper limits in MS packages of common nuget dependencies (e.g. Newtonsoft.Json) is getting really on my nerves lately.

**Comment by varunsh-msft** [comment]
@mliesmons, can you please clarify the issue? Preview is built against 3.19.4, but there is no upper limit set in the ADAL dependency. You should be able to use any ADAL version above 3.19.4. Can you please try to upgrade the ADAL version after you install App Auth package?

**Comment by mliesmons** [comment]
Hi Varun,
Seems to work now. Thanks for your advise.
Kr,
Michel.

**Comment by varunsh-msft** [comment]
Welcome! In fact, I tried to update ADAL to 4.3 and that worked too. I tried to get token using an app secret and it worked fine. So, one should be able to use 3.19.4 and future versions (at least until there is no breaking change in the future version of ADAL).

**Comment by varunsh-msft** [comment]
@shahabhijeet , can you please close this issue? Thanks!

**Comment by jitendriyag2** [comment]
anyone has the issiue of connectionstring null, he can use  the below solution:


AzureServiceTokenProvider azureServiceTokenProvider = new AzureServiceTokenProvider($"RunAs=App;AppId={AppID};TenantId={TenantID};AppKey={AppKey}");

We should registered an app in  AAD Registered App -> then get the Client ID  also Create a Access Key for that and then in Key vault section give the access to the registered app as per the access strategy

AppID: Client ID 
TenantID: Directory ID
AppKey : Secret Key Generated for the registered app

**Comment by varunsh-msft** [comment]
@jitendriyag2 , this is NOT recommended guidance as it will lead to credentials in source code (AppKey is a credential), that leads to them being compromised, and hard to rotate. 

What scenario is not working for you? What is the connection string null issue?
