### ISSUE TITLE
[FEATURE REQ] Support extensions in Postgres flexible

### ISSUE THREAD

**Issue by aaronpowell** [Azure/azure-sdk-for-net#43175]
### Library name

Azure.Provisioning

### Please describe the feature.

When it comes to deploying Postgres to be used as a vector database we need to enable the pgvector extension on the Postgres resource as deployed.

This is done using the following bicep:

```bicep
resource postgresConfig 'Microsoft.DBforPostgreSQL/flexibleServers/configurations@2022-12-01' = {
  dependsOn: [
    myPostgresResource
  ]
  name: '${name}/azure.extensions'
  properties: {
    value: 'PGVECTOR'
    source: 'user-override'
  }
}
```

There seems to be no way to add these extensions at present using the `Azure.Provisioning` package.

**Comment by mitchdenny** [comment]
@tg-msft and @JoshLove-msft this is important for Aspire because being able to use this resource type is what enables people to use pgvector features. Without it they've got no managed option and need to use a container image directly.

**Comment by aaronpowell** [comment]
Looks like this is possible using the `PostgreSqlConfiguration` type, so I'll close this.
