### ISSUE TITLE
Updating a function app deletes all the functions

### ISSUE THREAD

**Issue by seanoflynn-tie** [Azure/azure-sdk-for-net#4319]
I'm trying to update the application settings for a function app. I can't seem to do any updates to a function app without it wiping all the functions and then I have to redeploy to the function app again. It seems to update the WEBSITE_CONTENTSHARE setting of the function app on every update - I can't seem to overwrite this using the sdk. 

Is that the intended behavior or is there another way to accomplish this? I notice there is no Create or Update Function App api endpoint in the REST API just Delete and Create so maybe this isn't supported yet?

    var func = await _azure.AppServices.FunctionApps.GetByIdAsync(app.Id);
    await func.Update().WithExistingStorageAccount(_existingStorageAccount).ApplyAsync();

Thanks,
Sean

**Comment by hovsepm** [comment]
@seanoflynn-tie please reopen the issue in the Fluent SDK repo - https://github.com/Azure/azure-libraries-for-net/
