### ISSUE TITLE
[FEATURE REQ] Add policy fragment handling in Azure.ResourceManager.ApiManagement sdk

### ISSUE THREAD

**Issue by ericfitskieolyslager** [Azure/azure-sdk-for-net#43200]
### Library name

Azure.ResourceManager.ApiManagement

### Please describe the feature.

I'd like to manage my API Management Policy fragments in c# with the Azure.ResourceManager.ApiManagement SDK. At this moment I'm able to manage a lot about my API management, but the Policy Fragments seems missing.

In the Management REST API [API Management Policy Fragment](https://learn.microsoft.com/en-us/rest/api/apimanagement/policy-fragment?view=rest-apimanagement-2022-08-01) this is available.

Please add this functionality to the Azure.ResourceManager.ApiManagement SDK nuget package.

**Comment by ArthurMa1978** [comment]
Asking service team to upgrade the sdk to support his new feature

**Comment by solankisamir** [comment]
We have the feature merged in track1 SDK https://github.com/Azure/azure-sdk-for-net/pull/34639.

If customer asks for it, can we release it?

Track 2 SDK is still WIP

**Comment by ericfitskieolyslager** [comment]
Hi @ArthurMa1978 and @solankisamir 

Thank you for the update.

This saves me manually communicating with the Management REST API, only for the policy fragment part of the APIM.

**Comment by ericfitskieolyslager** [comment]
@ArthurMa1978 or @solankisamir,

Is there any update on this issue?

**Comment by ArthurMa1978** [comment]
@ericfitskieolyslager , here are the classes [PolicyFragmentContractCollection](https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.apimanagement.policyfragmentcontractcollection?view=azure-dotnet) and [PolicyFragmentContractResource](https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.apimanagement.policyfragmentcontractresource?view=azure-dotnet) for the policy fragment handling.
