### ISSUE TITLE
[BUG] CS0121: The call is ambiguous between the following methods or properties

### ISSUE THREAD

**Issue by TaoChenOSU** [Azure/azure-sdk-for-net#43206]
### Library name and version

Azure.Monitor.OpenTelemetry.AspNetCore 1.2.0-beta.2

### Describe the bug

Error message:
`error CS0121: The call is ambiguous betwe
en the following methods or properties: 'Microsoft.Extensions.DependencyInjection.OptionsBuilderExtensions.ValidateOnStart<TOptions>(Micr
osoft.Extensions.Options.OptionsBuilder<TOptions>)' and 'Microsoft.Extensions.DependencyInjection.OptionsBuilderExtensions.ValidateOnStar
t<TOptions>(Microsoft.Extensions.Options.OptionsBuilder<TOptions>)'`

### Expected behavior

Code can be successfully compiled.

### Actual behavior

Code failed to compile due to the above error.

### Reproduction Steps

With a basic ASP.Net core application, parse configurations into `Options` and called `ValidateOnStart()`
```
internal static void AddOptions<TOptions>(this IServiceCollection services, IConfigurationSection section)
    where TOptions : class
{
    services.AddOptions<TOptions>()
        .Bind(section)
        .ValidateDataAnnotations()
        .ValidateOnStart();
}
```

### Environment

OS: Windows
.NET: 8.0.202

**Comment by TimothyMothra** [comment]
Hi @TaoChenOSU, we (Azure.Monitor.OpenTelemetry.AspNetCore) don't own the `ValidateOnStart` method.
I did a quick search and found this issue: https://github.com/dotnet/runtime/issues/95524
Can you please check if this solution helps you?

**Comment by TaoChenOSU** [comment]
Hi @TimothyMothra, thanks for your quick reply!

I am sure `Azure.Monitor.OpenTelemetry.AspNetCore` doesn't own the `ValidateOnStart` method. The weird thing is once I install the package, it creates the error. 

I have tried to manually install the latest version of the `Microsoft.Extensions.DependencyInjection` package. Unfortunately, it didn't help.

**Comment by CodeBlanch** [comment]
@TaoChenOSU 

Here is the PR which introduced the issues: https://github.com/dotnet/runtime/pull/88546

`OptionsBuilderExtensions` was moved from `Microsoft.Extensions.Hosting` into `Microsoft.Extensions.Options`. If you have a newer `Microsoft.Extensions.Options` and an older `Microsoft.Extensions.Hosting` you will run into this issue. Try doing this...

```xml
<PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
<PackageReference Include="Microsoft.Extensions.Options" Version="8.0.0" />
```

Does that make the issue go away?

**Comment by TaoChenOSU** [comment]
Hi @CodeBlanch, 

That worked! Thank you so much!
