### ISSUE TITLE
[BUG] Azure OpenAI SDK, Chat Completions, Streaming, Unable To Get Citations, 

### ISSUE THREAD

**Issue by raeesgillani** [Azure/azure-sdk-for-net#43226]
### Library name and version

Azure.AI.OpenAI 1.0.0-beta.15

### Describe the bug

I am making a Chat Completions Streaming request via the Azure OpenAPI SDK using:

`await openAIClient!.GetChatCompletionsStreamingAsync(chatCompletionsOptions);`

It uses my own data.

When receiving the response, it is able to stream the content.

However, it returns no citation objects when using:

`response.AzureExtensionsContext.Citations`

Please advise.

### Expected behavior

I imagine any '[docx]' ContentUpdate in the AzureExtensionsContext.Citations would have a value:

{"Id":"19bec74a-f436-41a6-827d-6cf739cffe8e","Created":"2024-04-05T00:18:42+00:00","Role":null,"ContentUpdate":" East","FunctionName":null,"FunctionArgumentsUpdate":null,"ToolCallUpdate":null,"AuthorName":null,"FinishReason":null,"ChoiceIndex":0,"SystemFingerprint":null,"AzureExtensionsContext":null}

> {"Id":"19bec74a-f436-41a6-827d-6cf739cffe8e","Created":"2024-04-05T00:18:42+00:00","Role":null,"ContentUpdate":" **[doc2]**.\n\n","FunctionName":null,"FunctionArgumentsUpdate":null,"ToolCallUpdate":null,"AuthorName":null,"FinishReason":null,"ChoiceIndex":0,"SystemFingerprint":null,"AzureExtensionsContext": <span style="color:red">**[some citation object]**</span> }

{"Id":"19bec74a-f436-41a6-827d-6cf739cffe8e","Created":"2024-04-05T00:18:42+00:00","Role":null,"ContentUpdate":"These","FunctionName":null,"FunctionArgumentsUpdate":null,"ToolCallUpdate":null,"AuthorName":null,"FinishReason":null,"ChoiceIndex":0,"SystemFingerprint":null,"AzureExtensionsContext":null}

### Actual behavior

Currently there is a null AzureExtensionsContext.Citations object:

{"Id":"19bec74a-f436-41a6-827d-6cf739cffe8e","Created":"2024-04-05T00:18:42+00:00","Role":null,"ContentUpdate":" East","FunctionName":null,"FunctionArgumentsUpdate":null,"ToolCallUpdate":null,"AuthorName":null,"FinishReason":null,"ChoiceIndex":0,"SystemFingerprint":null,"AzureExtensionsContext":null}

> {"Id":"19bec74a-f436-41a6-827d-6cf739cffe8e","Created":"2024-04-05T00:18:42+00:00","Role":null,"ContentUpdate":" **[doc2]**.\n\n","FunctionName":null,"FunctionArgumentsUpdate":null,"ToolCallUpdate":null,"AuthorName":null,"FinishReason":null,"ChoiceIndex":0,"SystemFingerprint":null,"AzureExtensionsContext":**null**}

{"Id":"19bec74a-f436-41a6-827d-6cf739cffe8e","Created":"2024-04-05T00:18:42+00:00","Role":null,"ContentUpdate":"These","FunctionName":null,"FunctionArgumentsUpdate":null,"ToolCallUpdate":null,"AuthorName":null,"FinishReason":null,"ChoiceIndex":0,"SystemFingerprint":null,"AzureExtensionsContext":null}

### Reproduction Steps

1. Create a chat completion request (GetChatCompletionsStreamingAsync) via the Azure OpenAI SDK and pass in an Azure AI Search config.
2. Review response, specifically those AzureExtensionsContext.Citations objects where a placeholder citation [doc..] is retrieved in the ContentUpdate object.

### Environment

dotnet 8.0

**Comment by raeesgillani** [comment]
> Thanks for the feedback! We are routing this to the appropriate team for follow-up. cc @jpalvarezl @trrwilson.

Any update on this please?

**Comment by sathismanick** [comment]
Hi
First response you get all Citations in  response.AzureExtensionsContext.Citations then you start get chatUpdate.ContentUpdate text 

```
 await foreach (StreamingChatCompletionsUpdate chatUpdate in client.GetChatCompletionsStreaming(chatCompletionsOptions))
 {
     if (!string.IsNullOrEmpty(chatUpdate.ContentUpdate))
     {
         StreamMessage(aiIntegratorRequest.StreamConnectionId, chatUpdate.ContentUpdate, index++);
         aiResponse += chatUpdate.ContentUpdate;
     }
     if (chatUpdate.AzureExtensionsContext != null)
     {
         messageContext = chatUpdate.AzureExtensionsContext;
     }
 }
```

**Comment by raeesgillani** [comment]
> Hi First response you get all Citations in response.AzureExtensionsContext.Citations then you start get chatUpdate.ContentUpdate text
> 
> ```
>  await foreach (StreamingChatCompletionsUpdate chatUpdate in client.GetChatCompletionsStreaming(chatCompletionsOptions))
>  {
>      if (!string.IsNullOrEmpty(chatUpdate.ContentUpdate))
>      {
>          StreamMessage(chatUpdate.ContentUpdate);
>          aiResponse += chatUpdate.ContentUpdate;
>      }
>      if (chatUpdate.AzureExtensionsContext != null)
>      {
>          messageContext = chatUpdate.AzureExtensionsContext;
>      }
>  }
> ```

Thank you! - that worked :)
