### ISSUE TITLE
[BUG] DefaultAzureCredential causes unnessary processes

### ISSUE THREAD

**Issue by dldldlepl** [Azure/azure-sdk-for-net#43234]
### Library name and version

Azure.Identity

### Describe the bug

When Azure Cli authentication is tried to be used through DefaultAzureCredentials unnecessary processes can remain due to the auto-upgrade setting.

### Expected behavior

No additional processes after left after dotnet application stopped.

### Actual behavior

Additional Python processes are left after the dotnet application closes:

Command Line for first process:
```
"C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin\\..\python.exe"  -IBm azure.cli account get-access-token --output json --resource https://vault.azure.net --tenant ....
```

Command Line of second process:
```
C:\WINDOWS\system32\cmd.exe /c "az upgrade --all True"
```

Command Line of third process:
```
"C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin\\..\python.exe"  -IBm azure.cli upgrade --all True
```

![image](https://github.com/Azure/azure-sdk-for-net/assets/53822569/2f04a087-69d8-4c8f-b3f2-4268ff98a5be)

### Reproduction Steps

Enable auto upgrade of Azure Cli and wait until an update is available.
```
az config set auto-upgrade.enable=yes
```

Then use DefaultAzureCredential with allowing Azure CLI and you will notice the additional processes.

**Comment by christothes** [comment]
Hi @dldldlepl - 
This sounds like an issue for the Azure Cli. Could you open this issue over there? https://github.com/Azure/azure-cli/issues

**Comment by dldldlepl** [comment]
Hi @christothes, 

I have linked this issue in an existing issue of the Azure Cli about broken automation workflows, which seems to me to search also for a solution, which could this fix.

**Comment by christothes** [comment]
Thanks - I'm going to go ahead and close this issue then.
