### ISSUE TITLE
DefaultAzureCredentials not proceeding with next credentials if there is a proxy authentication error

### ISSUE THREAD

**Issue by ganiths** [Azure/azure-sdk-for-net#43232]
### Library name and version

Azure.Identity 1.10.4

### Describe the bug

My local machine is currently sitting behind a corporate proxy that requires authentcaition. When i try to connect Azure service from Visual studio use DefaultAzureCredentials, it looks for credentials in below order
EnvironmentVariables
ManagedIdentity
VisualStudio

As managedidentity authentication request  is sent to http://169.254.169.254/metadata/identity/oauth2/token, my proxy server is blocking the request and it is throwing me 407 authentication required error.

### Expected behavior

As of version 1.10.1, DefaultAzureCredential will attempt to authenticate with all developer credentials until one succeeds, regardless of any errors previous developer credentials experienced.

### Actual behavior

DefaultAzureCredentails stops at the ManagedIdentityCredentials error and not proceeding further

### Reproduction Steps

1. Create a service bus triggered function app
2. Run from Visual studio on a machine that is behind a corporate proxy that requires authentication.

### Environment

Visual Studio 17.8.7

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @ganiths - 
The response from the proxy should result in a `CredentialUnavailableException` which will let the next credential inline attempt to acquire a token. Can you reproduce this with the latest version of Azure.Identity? If so, please provide logging output from your repro.

https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/README.md#logging
