### ISSUE TITLE
Add AddSearchIndexerClient Extension Method for Azure AI Search

### ISSUE THREAD

**Issue by xantari** [Azure/azure-sdk-for-net#43233]
### Library name

Azure.Core.Extensions

### Please describe the feature.

Currently you only have registration methods for AddSearchIndexClient and AddSearchClient.

It would be helpful to also add AddSearchIndexerClient to this: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/src/SearchClientBuilderExtensions.cs

```cs
builder.AddClient<SearchIndexerClient, SearchClientOptions>((opts) =>
{
    return new SearchIndexerClient(new Uri(config.SearchServiceUrl), new AzureKeyCredential(config.SearchServiceQueryApiKey));
});
```

The above is the current work around (not the end of the world, but you had extension methods for the other client registrations so I wouldn't see why you wouldn't add this one as well.

**Comment by pallavit** [comment]
@jsquire do we have a criteria on deciding when to add extensions for clients across our SDKs?

**Comment by jsquire** [comment]
> @jsquire do we have a criteria on deciding when to add extensions for clients across our SDKs?

@pallavit:  General guidance has been that we should have an extension to register every top-level client exposed by a library, unless they have special needs for use/lifetime management where passing them around doesn't make sense.

**Comment by pallavit** [comment]
It may be worth having a static analyzer for this then - we may have a few gaps in our SDKs.
/cc: @m-nash do we have this added to the DPG generator i.e. we create an extension for each builder?

**Comment by ShivangiReja** [comment]
@xantari - We have added an extension to register the `SearchIndexerClient` and released it in the GA library: [Azure.Search.Documents@11.6.0](https://www.nuget.org/packages/Azure.Search.Documents/11.6.0).
