### ISSUE TITLE
Support for IMDS (AppAuthentication)

### ISSUE THREAD

**Issue by aaronla-ms** [Azure/azure-sdk-for-net#4323]
Could you add support for IMDS to AzureServiceTokenProvider (AppAuthentication)? The MSI extension on localhost:50342 is slated for deprecation, and we can't get it running on some of our VMs anyway. Would prefer to use the IMDS service as described [here](https://docs.microsoft.com/en-us/azure/active-directory/managed-service-identity/overview) instead.

Pardon if this is already supported through some sort of extension -- in which case, a reference in the documentation would be appreciated.

(Note: filed the issue here as 'azure-sdk-for-net' is listed as the project page for the [AppAuthentication nuget package](https://www.nuget.org/packages/Microsoft.Azure.Services.AppAuthentication). I'd draft a pull request save that I can't find AppAuthentication in this repo)

**Comment by danwkennedy** [comment]
Will the update also include support for passing the new client id parameter as well?

**Comment by varunsh-msft** [comment]
Not in this update. We are considering adding a new connection string option for user assigned identity. That way you use a connection string to use the explicit identity. The current connection string options are [here](https://docs.microsoft.com/en-us/azure/key-vault/service-to-service-authentication#connection-string-support). You can pass the connection string in the constructor. Do you have feedback on this design?

**Comment by CrazyTuna** [comment]
Do you have an estimated release date for this feature please ?

**Comment by varunsh-msft** [comment]
By 6/15 for IMDS.

**Comment by nonik0** [comment]
Version 1.0.3 of the AppAuthentication library has just been published to NuGet. This release includes support for calling the new IDMS endpoint for MSI authentication.

**Comment by cwe1ss** [comment]
Any update on passing a specific user assigned identity? Should we create a separate issue for this?

**Comment by varunsh-msft** [comment]
We have been working on some updates to the library for SQL Azure and Storage, and after that will take up the work to pick a user assigned identity. It would be better to track it as separate issue though. thanks!

**Comment by cwe1ss** [comment]
> @varunsh-msft It would be better to track it as separate issue though. thanks! 

https://github.com/Azure/azure-sdk-for-net/issues/4791 covers that, right?!
