### ISSUE TITLE
Investigate and Restrict projects/jobs running on signing machines

### ISSUE THREAD

**Issue by dsgouda** [Azure/azure-sdk-for-net#4325]
Looks like a bunch of jobs are running on our CI signing machines (like nightly builds and other jobs not related to signing or publishing) we need to figure out a way to secure the CI machines so they run jobs only related to signing and publishing

**Comment by shahabhijeet** [comment]
We will revisit this if we see these issue happening again. Right now pushing it to next milestone.

**Comment by shahabhijeet** [comment]
We do not see any value in pursuing this option at this stage as the effort is not worth the reward, plus we will be soon moving to VSTS.
