### ISSUE TITLE
VideoAnalyzerPreset - Error while using video without Audio 

### ISSUE THREAD

**Issue by yaprigal** [Azure/azure-sdk-for-net#4326]
Hi,
I was successfully executed this tutorial for the new v3 api
https://github.com/Azure-Samples/media-services-v3-dotnet-tutorials
but when I am trying to upload a video without an audio the Media Services job is failing with exception saying "No audio stream can be extracted from the source.
Is there a preset that need to be pass in order to avoid this failure?

Thanks

**Comment by akucer** [comment]
Closing out as not able to repro issue and also have feedback from yaprigal that issue isn't repro from their side any longer.
