### ISSUE TITLE
[FEATURE REQ] Make `GetUserDelegationKey` fail on insufficient permissions

### ISSUE THREAD

**Issue by BuildItBusk** [Azure/azure-sdk-for-net#43272]
### Library name

Azure.Storage.Blobs

### Please describe the feature.

If you are trying to use [GetUserDelegationKey](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobserviceclient.getuserdelegationkey?view=azure-dotnet) without Role Based Access Control (RBAC) enabled, it is able to return a key. The key will be invalid though. 

I would like to suggest that instead some variant of a permission exception is thrown, if the user attempts to call `GetUserDelegationKey` in a setting where it is not possible.

Tested by trying the following code on two different accounts, one where RBAC is disabled and one where it's enabled:

```cs
// Construct the blob endpoint from the account name.
string endpoint = $"https://{_accountName}.blob.core.windows.net";

// Added to control which tenant is used. May be possible to omit in most cases
DefaultAzureCredentialOptions defaultAzureCredentialOptions = new DefaultAzureCredentialOptions()
{
    VisualStudioTenantId = "fe8e182f-8278-4947-af21-750e26d5321f"
};

DefaultAzureCredential credential = new(defaultAzureCredentialOptions);

// Create a blob service client object using DefaultAzureCredential
BlobServiceClient blobServiceClient = new(
    new Uri(endpoint),
    credential);

// Get a user delegation key for the Blob service that's valid for 1 day
UserDelegationKey userDelegationKey;   
userDelegationKey = await blobServiceClient.GetUserDelegationKeyAsync(
    DateTimeOffset.UtcNow.AddMinutes(-15),
    DateTimeOffset.UtcNow.AddDays(1));
       

// Create a SAS token for the container resource that's also valid for 1 day
BlobSasBuilder sasBuilder = new()
{
    BlobContainerName = containerClient.Name,
    Resource = "c",
    StartsOn = DateTimeOffset.UtcNow,
    ExpiresOn = DateTimeOffset.UtcNow.AddDays(1)
};

// Specify the necessary permissions
sasBuilder.SetPermissions(
    BlobSasPermissions.List | BlobSasPermissions.Read | BlobSasPermissions.Write);


// Add the SAS token to the blob URI
BlobUriBuilder uriBuilder = new(containerClient.Uri)
{
    // Specify the user delegation key
    Sas = sasBuilder.ToSasQueryParameters(
        userDelegationKey,
        containerClient.AccountName)
};
```

**Comment by amnguye** [comment]
This is a feature request for the storage service itself and not the SDK. Since the SDK can only send the REST request and return the response to the user, it cannot validate the permissions from a client perspective.

Please submit your support request via
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

as these github issues are designated for SDK issues.
