### ISSUE TITLE
[BUG] Unknown TriggeredWebJobStatus value. Parameter name: value Actual value was Aborted / Running.

### ISSUE THREAD

**Issue by ahmedHashwa** [Azure/azure-sdk-for-net#43295]
### Library name and version

Azure.ResourceManager.AppService 1.0.2

### Describe the bug

When using Azure.ResourceManager.AppService library to request the status of Triggered Webjobs in Azure, an exception occurs as it doesn't recognize the status of Aborted and Running.

### Expected behavior

To be able to get the current status of the TriggeredWebJob, which may include Pending, Running, Success, Failed, and Aborted

### Actual behavior

Exception is thrown.

### Reproduction Steps

1- Install the aforementioned Library.
2- Make sure you have an Azure Subscription along with a Triggered WebJob aborted/running.
3- Run the following code replacing items in <> with proper values.

            var client = new ArmClient(new DefaultAzureCredential()); 
            var subscription = await client.GetDefaultSubscriptionAsync();  
            var resourceGroups = subscription.GetResourceGroups();  
            ResourceGroupResource resourceGroup = await resourceGroups.GetAsync(<resourceGroupName>);  
            var website = await resourceGroup.GetWebSiteAsync(<webAppName>);  
            await website.Value.GetWebSiteSlotTriggeredWebJobAsync(<webJobName>);

### Environment

Azure AppService

**Comment by HarveyLink** [comment]
Hi @ahmedHashwa ,Thank you for using Azure SDK for .NET.
As the [service swagger definition](https://learn.microsoft.com/en-us/rest/api/appservice/web-apps/get-triggered-web-job?view=rest-appservice-2023-01-01#triggeredwebjobstatus),  we only have 3 status value, which are: `Error/Failed/Success`.
If there are other available values, then the service team need to update the definition. You could [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) to get help on that.
Also, if you could provide us the correct values, we could fix it at SDK side as work around.

**Comment by ahmedHashwa** [comment]
@HarveyLink 
Thank you for your response.
I got the exception for the aforementioned values in TriggeredWebJobStatus:

Aborted
Running

It is also expected to get exceptions if another value is returned, such as:
Initializing: according to Kudu [TriggeredJobRunLogger.cs](https://github.com/projectkudu/kudu/blob/20239baf6d482861e238505e487b84dc7c4bdc9e/Kudu.Core/Jobs/TriggeredJobRunLogger.cs#L49) 


As mentioned, when I try to get an object representing the job, I get that exception, which prevents me from running it through the API if it is in Aborted Status, for example.

**Comment by HarveyLink** [comment]
Issue fixed, new package released, please have a try on that.
