### ISSUE TITLE
Key Vault credentials object not using supplied client or handlers to obtain challenge

### ISSUE THREAD

**Issue by msfcolombo** [Azure/azure-sdk-for-net#4331]
When I create a `KeyVaultClient` using one of the constructors that accept a `KeyVaultClient.AuthenticationCallback` parameter and either an array of `DelegatingHandler` or an explicit `HttpClient`, I can see that my handlers/client are used in every request, **except** in the pre-authorization code. This prevents customization of certain requests.

It's particularly bad for logging, because if we want to add a `DelegatingHandler` that logs which URI is failing, the very first request to Key Vault (the pre-authentication) may fail without calling the logger. It's also bad if we want to use an `HttpClient` instance with different settings, such as a proxy or different timeout values.

It seems that the root cause is the fact that `KeyVaultCredential` object always instantiate a new `HttpClient`:

https://github.com/Azure/azure-sdk-for-net/blob/f4e242a32f30bf78fd190bc2675862a2366e08cf/src/SDKs/KeyVault/dataPlane/Microsoft.Azure.KeyVault/Customized/Authentication/KeyVaultCredential.cs#L94

We can work around this issue by supplying a custom instance of `ServiceClientCredentials`. However this is hacky and may require duplication of the logic at `KeyVauldCredential`.

**Comment by dimitertodorov** [comment]
Just ran into this too. 
This is especially tricky when using Managed Service Identity.
I should be able to pass in a Root Handler and have that handler respect it.

Would like a suggestion on how to handle this. 
```
AzureServiceTokenProvider azureServiceTokenProvider = new AzureServiceTokenProvider();
            var kvCallback = new KeyVaultClient.AuthenticationCallback(azureServiceTokenProvider.KeyVaultTokenCallback);
            var kvCreds = new KeyVaultCredential(kvCallback);
            var kvClient = new KeyVaultClient(kvCreds, GetBackChannelHttpHandler(config["BackChannelHttpProxy"]));
```

If I just copy the KeyVaultCredential Implementation will that be sufficient?

**Comment by msfcolombo** [comment]
@dimitertodorov, Yes you can copy `KeyVaultCredential` implementation and change to use your own `HttpClient`. I did that for now.
