### ISSUE TITLE
ServiceBusManagementClient CreateIfNotExists

### ISSUE THREAD

**Issue by deckertron9000** [Azure/azure-sdk-for-net#4334]
In the Microsoft.ServiceBus.Messaging library there used to be a method to create a queue or topic if it did not already exist. In the Microsoft.Azure.Management.ServiceBus library there is only a CreateOrUpdate method. 

Does this new CreateOrUpdate overwrite all existing settings of a queue or topic if it already exists? If so, are there any plans to add in the old CreateIfNotExists functionality to the newer library?

**Comment by axisc** [comment]
@deckertron9000

querying and then creating a new queue/topic is a management operation which is more expensive than executing send/receives.

As the product has matured we've made more improvements on the data operations, so I would recommend not using a CreateIfNotExists call for improved performance.

I recommend that you create queues/topics at the start of a process, or in an independent process
 
Then, when you send to a queue/topic.
- If the queue/topic exists, you will be able to send without any problems.
- If the queue/topic doesn't exist, then you will receive an error/exception from Service Bus. When handling this exception you can create the entity and try resending.

Hope this helps. I'm closing this issue, please feel free to reopen if you face an issue.
