### ISSUE TITLE
[BUG] AzureMonitor doesn't capture activities/spans/dependencies

### ISSUE THREAD

**Issue by TaoChenOSU** [Azure/azure-sdk-for-net#43342]
### Library name and version

Azure.Monitor.OpenTelemetry.AspNetCore 1.1.0

### Describe the bug

I am using `AzureMonitor` and `OpenTelemetry`. I'd like to create custom spans/activities/internal dependencies within my app. I am following the guide here: https://learn.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-add-modify?tabs=aspnetcore#add-custom-spans. However, when I run my app, I don't see my custom span in my ApplicationInsights instance's transaction records nor the `dependencies` table.

Here is a minimal repro based on the example: https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/tests/Azure.Monitor.OpenTelemetry.AspNetCore.Demo

```
using System.Diagnostics;
using System.Net.Http;
using Azure.Monitor.OpenTelemetry.AspNetCore;
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

ActivitySource activitySource = new("test");

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddOpenTelemetry().UseAzureMonitor();

var app = builder.Build();
app.MapGet("/", () =>
{
  using (var activity = activitySource.StartActivity("CustomActivity"));
  app.Logger.LogInformation("Hello World!");

  using var client = new HttpClient();
  var response = client.GetAsync("https://www.bing.com/").Result;

  return $"Hello World! OpenTelemetry Trace: {Activity.Current?.Id}";
});

app.Run();
```

### Expected behavior

Expect to see an `internal dependency` with the name `test` in ApplicationInsights' transaction search results, or an entry in the `dependencies` table.

### Actual behavior

I only observed the following.

End-to-end transaction:
![image](https://github.com/Azure/azure-sdk-for-net/assets/12570346/97d18b6b-4eee-4d69-80f8-d198cc9cd1b5)
![image](https://github.com/Azure/azure-sdk-for-net/assets/12570346/352b4ab0-3515-4c18-b68b-43f197834fb1)

In the `dependencies` table:
![image](https://github.com/Azure/azure-sdk-for-net/assets/12570346/c2eacb1d-6f4d-48f4-a121-3a1f04d0944b)

### Reproduction Steps

See above for the minimal repro.

### Environment

OS: Windows
.Net: 8.0.4

**Comment by cijothomas** [comment]
The repro shared is not adding `builder.Services.ConfigureOpenTelemetryTracerProvider((sp, builder) => builder.AddSource("test"));
`
Could you add that and try again?

**Comment by TaoChenOSU** [comment]
> The repro shared is not adding `builder.Services.ConfigureOpenTelemetryTracerProvider((sp, builder) => builder.AddSource("test")); ` Could you add that and try again?

You're right! Thanks!

However, when I did that, my custom activity did showed up but the activity duration seemed to be off.
![image](https://github.com/Azure/azure-sdk-for-net/assets/12570346/6bd32a80-e9e6-4903-b5d2-e257e2ea40ce)
![image](https://github.com/Azure/azure-sdk-for-net/assets/12570346/c7ed7443-b75d-4e16-a7f1-05897c996d3e)

I'd expect it to include the duration of the request to `https://www.bing.com/`.

**Comment by TimothyMothra** [comment]
There's three ways to use the `using` keyword:
1. using with a block 
    ```
    using (new SomeClass())
    {
        // do some work
    }
    ```

2. using with a block (shorthand)
    ```
    using (new SomeClass());
    // do some work
    ```

3. using with a declared variable.
    ```
    using var someClass = new SomeClass();
    // do some work
    ```

In your code sample, you're using option 2. 
So your activity is disposed after the LogInformation.
Your activity does not encompass the dependency call to bing.

**Comment by TaoChenOSU** [comment]
Thank you so much!

I figured it out why my traces were not showing up in ApplicationInsights. It's because I had the `SamplingRatio` set to 0.05. I'd recommend anyone who is testing their telemetry pipeline end-to-end to not set the `SamplingRatio`.
