### ISSUE TITLE
[BUG] AddEventGridClient ambiguous method

### ISSUE THREAD

**Issue by danielmarbach** [Azure/azure-sdk-for-net#43351]
### Library name and version

Azure.Messaging.EventGrid 4.22.0-beta.1

### Describe the bug

I'm using a beta version that contains the EventGridClient for pull delivery. Unfortunately when upgrading from 4.18.0-beta.1 to 4.22.0-beta.1 the following line creates a compiler error

```csharp
var builder = Host.CreateApplicationBuilder(args);
builder.Services.AddAzureClients(azureClientBuilder =>
{   
    azureClientBuilder.AddEventGridClient(new Uri(builder.Configuration.GetSection("EventGridOptions")["Endpoint"]), new AzureKeyCredential(builder.Configuration.GetSection("EventGridOptions")["AccessKey"]));
});
```

with the following error

```text
  Program.cs(8, 24): [CS0121] The call is ambiguous between the following methods or properties: 'EventGridClientBuilderExtensions.AddEventGridClient<TBuilder>(TBuilder, Uri, AzureKeyCredential)' and 'MessagingEventGridNamespacesClientBuilderExtensions.AddEventGridClient<TBuilder>(TBuilder, Uri, AzureKeyCredential)'
```

it is possible to get the code compiling again with the following workaround

```csharp
var builder = Host.CreateApplicationBuilder(args);
builder.Services.AddAzureClients(azureClientBuilder =>
{
    // This is a bit of a quirk in the beta builds :(
    EventGridClientBuilderExtensions.AddEventGridClient(azureClientBuilder, new Uri(builder.Configuration.GetSection("EventGridOptions")["Endpoint"]), new AzureKeyCredential(builder.Configuration.GetSection("EventGridOptions")["AccessKey"]));
});
```

### Expected behavior

No compile error

### Actual behavior

Already described in the bug description

### Reproduction Steps

Already described in the bug description

**Comment by JoshLove-msft** [comment]
The Namespace functionality has been moved into a separate library Azure.Messaging.EventGrid.Namespaces. The duplicate methods have been removed.
