### ISSUE TITLE
[BUG] prebuilt-layout model not responding anymore

### ISSUE THREAD

**Issue by hellcoderGIT** [Azure/azure-sdk-for-net#43367]
### Library name and version

Azure.AI.DocumentIntelligence 1.0.0-beta.2

### Describe the bug

since about 16hours the prebuilt-layout model V2024_02_29_Preview (the only version usable by this lib) is not giving answers anymore, it just runs forever. The same is true for using it directly on https://documentintelligence.ai.azure.com/studio/layout

It might be an azure problem but i could not find any status dashboards or a way to notify the right people.
My instance is running in East-US and everything else, older versions of the model and other models are working fine.
This is on a paid S0 plan.

### Expected behavior

AnalyzeDocumentAsync giving a response after a few seconds (WaitUntil.Completed)

### Actual behavior

AnalyzeDocumentAsync  running forever without response

### Reproduction Steps

https://documentintelligence.ai.azure.com/studio/layout
choose the newest preview model and any document, click analyze.

**Comment by jsquire** [comment]
Hi @hellcoderGIT.  Thank you for reaching out and we regret that you're experiencing difficulties.  As you've noted, the behavior that you're seeing is related to the Document Intelligence service and not the Azure SDK client.  The client has no insight nor influence over the performance and responsiveness of the service.  Unfortunately, the maintainers of the Azure SDK libraries are unable to assist with service issues.

To ensure that the right team has visibility and can help, your best path forward for would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) or inquire on the [Microsoft Q&A site](https://learn.microsoft.com/answers/questions/).  

I'm going to close this out; if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.
