### ISSUE TITLE
Re-record SqlManagement tests

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#43386]
These tests were marked as LiveOnly as part of the sanitization initiative in https://github.com/Azure/azure-sdk-for-net/pull/43356. Sanitization of the "password" JSON property caused the tests to start failing playback. Attempting to re-record resulted in the following error:
 
The [RecordedTest] attribute attempted to re-record, but failed:

Azure.RequestFailedException : Resource group 'Sql-RG-5445' could not be found.
Status: 404 (Not Found)
ErrorCode: ResourceGroupNotFound

Content:
{
  "error": {
    "code": "ResourceGroupNotFound",
    "message": "Resource group \u0027Sql-RG-5445\u0027 could not be found."
  }
}

To find the associated tests, you can look at the PR referenced above or do a code search for this issue number.

**Comment by welovej** [comment]
#43675
