### ISSUE TITLE
Marquitos 

### ISSUE THREAD

**Issue by Marquitos1997** [Azure/azure-sdk-for-net#43405]
### Type of issue

Typo

### Description

[Escriba sus comentarios aquí]

### Page URL

https://learn.microsoft.com/es-es/dotnet/api/azure.ai.formrecognizer.documentanalysis.documentbarcodekind.microqrcode?view=azure-dotnet#azure-ai-formrecognizer-documentanalysis-documentbarcodekind-microqrcode

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.AI.FormRecognizer.DocumentAnalysis/DocumentBarcodeKind.xml

### Document Version Independent Id

86541ab6-4fa2-c67d-7e73-334297382f0e

### Article author

@azure-sdk

### Metadata

* ID: 1dbd9333-d621-333f-d84a-9e9339d29dec 
* Service: **azure**

**Comment by kinelski** [comment]
Hello @Marquitos1997,

Could you clarify where exactly in the documentation the typo is located and what you expected the corrected text to be?
