### ISSUE TITLE
AutoCorrect not working as detailed: TextModeration

### ISSUE THREAD

**Issue by greenallparagonuk** [Azure/azure-sdk-for-net#4344]
TextModeration: ScreenText

I was running some testing to find out if this service could help my project, but found that the examples are not what really happens. I used the text from "https://docs.microsoft.com/en-gb/azure/cognitive-services/content-moderator/text-moderation-api#auto-correction" which is "The qu!ck brown f0x jumps over the lzay dog."

and when I test the auto-correct with this text I get: "The Qu! cu brown f0x jumps over the lazy dog." and not "The quick brown fox jumps over the lazy dog.", so it's not looked at "fox" at all and "quick" has been split. To me it looks like it can't detect "!" as an "i" and "0" (zero) as an "o"!

I also tried "lzaydog" which corrects to "lapdog", but if I put lzaydog into Bing it puts websites that refer to "lazy dog" in the top results.

Please fix the documentation or the auto-correct.

The problem I'm trying to solve in my project is based on email addresses and physical addresses having explicit words embedded/hidden in them. It appears this service is not going to help.

**Comment by jsquire** [comment]
Closing this out as there has been no recent engagement.  Please feel free to reopen or file a new issue if this remains a problem with the current version of the library.
