### ISSUE TITLE
[QUERY] How to deserialize ARM restful API response to new ARM models?

### ISSUE THREAD

**Issue by lissdy** [Azure/azure-sdk-for-net#43459]
### Library name and version

Azure.ResourceManager.Resources.Models

### Query/Question

To get a more detailed response, our .net service interacts with ARM via restful API instead of ARM SDK.
We deserialize the JSON response to old Azure management SDK-defined models as the sample code shown

```
// provider docs https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/listall
var virtualMachines = await armClient.GetResourceListAsync<VirtualMachine>("Microsoft.Compute/virtualMachines");

public async Task<List<T>> GetResourceListAsync<T>(string provider, string apiVersion = "")
{
    var resourceList = new List<T>();

    // Get https://management.azure.com/subscriptions/{subscriptionId}/providers/{provider}/?api-version={apiVersion}
    var nextLink = BuildURI($"/subscriptions/{this.credentialHolder.SubscriptionId}/providers/{provider}", apiVersion);
    var httpHolder = new HttpHolder()
    {
        HttpMethod = HttpMethod.Get,
        RequestBody = string.Empty,
        RequestUri = nextLink,
        EventName = nameof(GetResourceListAsync),
    };
    do
    {
        var responseMessage = await this.GetResponseMessageAsync(httpHolder).ConfigureAwait(false);

        if (responseMessage.IsSuccessStatusCode)
        {
            var content = responseMessage.Content.ReadAsStringAsync().GetAwaiter().GetResult();

            PagedListResult<T> page = JsonConvert.DeserializeObject<PagedListResult<T>>(content);
            resourceList.AddRange(page.Value);
            httpHolder.RequestUri = page.NextLink;
        }
        else
        {
            throw this.BuildExceptionFromResponse(responseMessage);
        }
    }
    while (!string.IsNullOrEmpty(httpHolder.RequestUri));

    return resourceList;
}
```

As we migrate to Track 2 Azure management SDK, we noticed we can't build resource object via JSON deserialize directly.

```
// replace Microsoft.Azure.Management.Compute.Models.VirtualMachine with Azure.ResourceManager.Compute.VirtualMachineData
var virtualMachines = await armClient.GetResourceListAsync<VirtualMachineData>("Microsoft.Compute/virtualMachines");
```
Hit JsonSerializationException

```
"ClassName": "Newtonsoft.Json.JsonSerializationException",
  "Message": "Error converting value \"/subscriptions/XXX/resourceGroups/XXX/providers/Microsoft.Compute/virtualMachines/XXX\" to type 'Azure.Core.ResourceIdentifier'. Path 'value[0].id', line 1, position 222.",
  "Data": null,
  "InnerException": {
    "ClassName": "System.ArgumentException",
    "Message": "Could not cast or convert from System.String to Azure.Core.ResourceIdentifier.",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)\r\n   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": null,
    "HResult": -2147024809,
    "Source": "Newtonsoft.Json",
    "WatsonBuckets": null,
    "ParamName": null
  },
```

May I know the migration guidance here?

**Comment by jsquire** [comment]
Hi @lissdy.  Thank you for reaching out and we regret that you're experiencing difficulties.  Please be aware that the models in the Azure SDK package are intended to be instantiated only by the Azure SDK client and we do not support the direct deserialization scenario that you're attempting to use them for.   Unfortunately, this means that we cannot offer assistance for converting your previous code.

The Azure SDK clients and models conform to the REST API specification of the service that they interact with and support the full set of data returned by those services.  Our guidance would be that you use the Azure client to query the service and obtain your results.

**Comment by lissdy** [comment]
Thanks @jsquire , looks the guidance is to replace the ARM REST API calls with SDK? 
May I know any cases that REST API is recommended?

**Comment by jsquire** [comment]
> Thanks @jsquire , looks the guidance is to replace the ARM REST API calls with SDK? May I know any cases that REST API is recommended?

I can only speak on behalf of the Azure SDK packages.  Given that the management libraries offer the same functionality as the REST API, I don't know of any scenarios where you would need to call the REST API directly.   Doing so is a matter of preference.
