### ISSUE TITLE
[QUERY] How to dis associate subnet from NATGateway using Azure SDK

### ISSUE THREAD

**Issue by ShijunLu** [Azure/azure-sdk-for-net#43499]
### Library name and version

Azure.ResourceManager.Network, Version="1.6.0"

### Query/Question

I am using this method to associate NATGateway to a subnet.

            ArmClient azure = this.azureProvider.GetAzureClient(resourceTenantId, subscriptionId);

            var subnetId = SubnetResource.CreateResourceIdentifier(subscriptionId, resourceGroupName, vNetName, subnetName);

            SubnetResource subnetResource = await azure.GetSubnetResource(subnetId).GetAsync();

            subnetResource.Data.NatGatewayId = ResourceIdentifier.Parse(natGatewayId);

            await subnetResource.UpdateAsync(waitUntil: WaitUntil.Completed, data: subnetResource.Data);
# But I do not know how to disassociate it.

To disassociate it, if I use

            SubnetResource subnetResource = await azure.GetSubnetResource(subnetId).GetAsync();

            subnetResource.Data.NatGatewayId = null;

            await subnetResource.UpdateAsync(waitUntil: WaitUntil.Completed, data: subnetResource.Data);
Azure will throw exception "error":{"code":"InvalidRequestFormat","message":"Cannot parse the request.","details":[{"code":"MissingJsonReferenceId","message":"Value for reference id is missing. Path properties.natGateway."}] since the resourceId cannot be null.

# May I know how to use this SDK to disassociate the Subnet From NATGateway?

### Environment

Visual Studio. 
.Net 6

**Comment by mcgallan** [comment]
Hi @ShijunLu , thank you for your feedback. Regarding the issue you mentioned, I'm sorry to inform you that the SDK currently cannot implement the functionality you need. We sincerely apologize for this. In subsequent version updates, we will continue to monitor this issue in the hope that it can be properly resolved in the future.
