### ISSUE TITLE
[FEATURE REQ] Align ProcessSessionMessageEventArgs.DeadLetterMessageAsync overload parameter types

### ISSUE THREAD

**Issue by kimsey0** [Azure/azure-sdk-for-net#43498]
### Library name

Azure.Messaging.ServiceBus

### Please describe the feature.

`ProcessSessionMessageEventArgs` has three methods which take `IDictionary<string, object> propertiesToModify` parameters: `AbandonMessageAsync`, `DeferMessageAsync`, and `DeadLetterMessageAsync`.

https://github.com/Azure/azure-sdk-for-net/blob/ff649380ce9e4bf5d46ddcc72cac1f8b3bfe2960/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ProcessSessionMessageEventArgs.cs#L199-L202

However, it also has one `DeadLetterMessageAsync` overload which takes a `Dictionary<string, object>`.

https://github.com/Azure/azure-sdk-for-net/blob/ff649380ce9e4bf5d46ddcc72cac1f8b3bfe2960/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ProcessSessionMessageEventArgs.cs#L213-L218

Can this one be changed to take an `IDictionary<string, object>`, aligning it with the other three?

**Comment by JoshLove-msft** [comment]
Thank you for bringing this issue to our attention @kimsey0. Unfortunately changing the type from Dictionary to IDictionary would be a binary break. I think we may have to live with this inconsistency.
