### ISSUE TITLE
[BUG] ServiceBus - ReceiveDeferredMessageAsync does not check for existing subscription

### ISSUE THREAD

**Issue by matthewpavia99** [Azure/azure-sdk-for-net#43492]
### Library name and version

Azure.Messaging.ServiceBus 7.15.0

### Describe the bug

If a ServiceBusReceiver is created using a non-existing `subscriptionName`, then using the `ReceiveDeferredMessageAsync` method should return a `ServiceBusException` with the reason set to `MessagingEntityNotFound`. Instead the method times out.

### Expected behavior

Using the `ReceiveDeferredMessageAsync` method with a non-existing subscription shoukd throw a `ServiceBusException` with the reason set to `MessagingEntityNotFound`.

### Actual behavior

`ReceiveDeferredMessageAsync` method timesout with `ServiceTimeout` reason.

### Reproduction Steps

Create a new ServiceBusReceiver instance using a random/non-existing subscription name, then use the receiver's `ReceiveDeferredMessageAsync` method.

**Comment by jsquire** [comment]
Hi @matthewpavia99.  Thank you for reaching out and we regret that you're experiencing difficulties.   The client has no direct insight into whether a subscription exists or not and can only react to an error response from the Service Bus service.   The behavior that you're reporting sounds like the service is not returning an error and is instead just hanging until timeout.  

Unfortunately, the maintainers of the Azure SDK are unable to assist with service issues, and the service teams do not monitor this repository.  To ensure that the Service Bus service team has visibility and can help, your best path forward for would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) or inquire on the [Microsoft Q&A site](https://learn.microsoft.com/answers/questions/).   

I'm going to close this out; if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.
