### ISSUE TITLE
[BUG] Azure Data Factory Default Value Expression not valid

### ISSUE THREAD

**Issue by leekennett** [Azure/azure-sdk-for-net#43532]
### Library name and version

Azure.ResourceManager.DataFactory 1.0.0

### Describe the bug

Using the .net SDK defining a should result in an expression in Azure Data Factory.

`["fileName"] = new(EntityParameterType.String)
{
    DefaultValue = BinaryData.FromObjectAsJson(new Dictionary<string, object>()
    {
        ["value"] = "@coalesce(null)",
        ["type"] = "Expression"
    })
},`

but Azure Data Factory is not reflecting this accurately. Apparently order matters in ADF.
When observing the deployed dataset
![image](https://github.com/Azure/azure-sdk-for-net/assets/167556617/1afd205c-0d42-4f13-85f4-3837c1b2f494)
![image](https://github.com/Azure/azure-sdk-for-net/assets/167556617/951d2214-db26-4339-aa0b-5795d8e2bcde)

There doesn't appear any way to ensure the order. The following is what ADF is expecting to represent an expression.
`"fileName": {
                                "value": "@coalesce(null)",
                                "type": "Expression"
                            }`

### Expected behavior

Passing an object as json with those values should get parsed as valid expression in ADF.

Output to ADF should be
`"fileName": {
                                "value": "@coalesce(null)",
                                "type": "Expression"
                            }`

### Actual behavior

Value is not getting parsed as an expression.
`"fileName": {
                                "type": "Expression",
                                "value": "@coalesce(null)"
                            }`

### Reproduction Steps

Write an ADF .net project.
Define a Dataset with a parameter, set the default value to an expression like:
`["fileName"] = new(EntityParameterType.String)
{
    DefaultValue = BinaryData.FromObjectAsJson(new Dictionary<string, object>()
    {
        ["value"] = "@coalesce(null)",
        ["type"] = "Expression"
    })
},`
Write that dataset to an ADF instance, anything that references that's dataset you should be able to observe that that parameter is not getting parsed as an expression.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by HarveyLink** [comment]
Hi @leekennett , could you provide more detailed code about how you create the dataset.
It would help us to repro the issue and investigate further.

**Comment by leekennett** [comment]
The issue appears to be resolved in the latest package - re-tested on 1.6
Default values for a parameter can be defined simple strings.

```
["fileName"] = new(EntityParameterType.String)
{
    DefaultValue = BinaryData.FromObjectAsJson("@coalesce(null)")
},
```

previously that was being interpreted in activity references as a string instead of an expression which led to issues.

**Comment by leekennett** [comment]
Sorry, I spoke too soon.

Defining a dataset with a default value expression like
```
["fileName"] = new(EntityParameterType.String)
{
    DefaultValue = BinaryData.FromObjectAsJson("@coalesce(null)")
},
```
results in a deployment with an empty default which is desired.

**Comment by HAKIMBIBI67A** [comment]
appleid_usen@apple.com<=1

**Comment by HAKIMBIBI67A** [comment]
![image](https://github.com/user-attachments/assets/b3fd9b08-8d08-4088-975e-81777f896e36)

**Comment by HAKIMBIBI67A** [comment]
![image](https://github.com/user-attachments/assets/cc34a0c3-3aa9-4892-aafd-6f49e247b11a)
