### ISSUE TITLE
[QUERY] Proper Way to Handle Exceptions in ServiceBusProcessor.ProcessMessageAsync Handler

### ISSUE THREAD

**Issue by cjablonski76** [Azure/azure-sdk-for-net#43544]
### Library name and version

Azure.Messaging.ServiceBus 7.17.4

### Query/Question

I'm testing out trace ids from the publisher through to the consumer. I saw [this issue](https://github.com/Azure/azure-sdk-for-net/issues/33338), but I have some follow up to that. 

In my `ServiceBusProcessor.ProcessMessageAsync` handler method, I grab the `Diagnostic-Id` and start a new `Activity`:
```
    private async Task OnProcessMessageAsync(ProcessMessageEventArgs args)
    {
        var diagnosticId = string.Empty;
        if (args.Message.ApplicationProperties.TryGetValue("Diagnostic-Id", out var objectId))
        {
            diagnosticId = objectId as string ?? string.Empty;
        }

        using var activitySource = new ActivitySource("processActivitySource");
        using var activity = activitySource.StartActivity("ProcessMessage", default, parentId: diagnosticId);
     
        // process message and log data to activity        

        // force exception
        throw new ArgumentException("hello");
    }

    private Task OnProcessErrorAsync(ProcessErrorEventArgs args)
    {
         /// how can we get the traceid from the ArgumentException("hello");
    }
```

Mostly I'm trying to just bubble my exceptions from `OnProcessMessageAsync` to `OnProcessErrorAsync`, but I don't see a way to trace the exceptions back to the `traceid` I have coming all the way from the original publisher logic.

What is the recommendation here, do I need to add explicit `try/catch` inside of my `OnProcessMessageAsync`, or is there a way to trace in the `OnProcessErrorAsync`?

### Environment

Macbook M1 chip, using Rider for local testing.
```
.NET SDK:
 Version:           8.0.101
 Commit:            6eceda187b
 Workload version:  8.0.100-manifests.69afb982

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.4
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.101/

.NET workloads installed:
 Workload version: 8.0.100-manifests.69afb982
There are no installed workloads to display.

Host:
  Version:      8.0.1
  Architecture: arm64
  Commit:       bf5e279d92

.NET SDKs installed:
  6.0.418 [/usr/local/share/dotnet/sdk]
  8.0.101 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.26 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.26 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
  ```

**Comment by JoshLove-msft** [comment]
I don't think you'd be able to trace back to the activity that you are creating in your message handler, because the error handler is executed outside the scope of your message handler. However, the entire call of message/error handler is already within a diagnostic scope with activity name "ServiceBusProcessor.ProcessMessage" as mentioned [here](https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-end-to-end-tracing?tabs=net-standard-sdk-2#service-bus-net-client-autotracing).

**Comment by cjablonski76** [comment]
@JoshLove-msft, so how can I trace my message from the publisher all the way down to when an error is thrown?

**Comment by JoshLove-msft** [comment]
> @JoshLove-msft, so how can I trace my message from the publisher all the way down to when an error is thrown?

The ProcessMessage span will be linked to the publishing span via the DiagnosticId. Essentially what you are doing in your message handler is already done by the SDK.

**Comment by cjablonski76** [comment]
> > @JoshLove-msft, so how can I trace my message from the publisher all the way down to when an error is thrown?
> 
> The ProcessMessage span will be linked to the publishing span via the DiagnosticId. Essentially what you are doing in your message handler is already done by the SDK.

Ok, I need to get my monitoring setup locally and see what things look like. Will all of my published messages end up having a child span that points to my long running processor spans, do you happen to know?

**Comment by JoshLove-msft** [comment]
The process and send spans should both be children of the Message span, if I'm not mistaken.
