### ISSUE TITLE
[BUG] App Service Can Not Access Key Vault with Manage Identity until Restarting

### ISSUE THREAD

**Issue by izanami00** [Azure/azure-sdk-for-net#43556]
### Library name and version

Azure.Identity 1.4.0

### Describe the bug

An Azure App Service was deployed 2 years ago, it can accessed Azure Key Vault with Managed Identity Authentication and Access Policy Configuration, it worked well in these years, but this year the functionality failed several times, and once failed, the App Service will not able to access the Key Vault, even if there is an internal retry mechanism, until the App Service is restarted. 

### Expected behavior

The Managed Identity Authentication should always work.

### Actual behavior

The Managed Identity Authentication failed sometimes and cannot work even after trying again, until the App Service is restarted.

**Error**:
Exception:ManagedIdentityCredential authentication failed: Retry failed after 4 tries. Retry settings can be adjusted in ClientOptions.Retry. (An error occurred while sending the request.) (No connection could be made because the target machine actively refused it.) (No connection could be made because the target machine actively refused it.) (No connection could be made because the target machine actively refused it.)
Retry failed after 4 tries. Retry settings can be adjusted in ClientOptions.Retry. (An error occurred while sending the request.) (No connection could be made because the target machine actively refused it.) (No connection could be made because the target machine actively refused it.) (No connection could be made because the target machine actively refused it.)
An error occurred while sending the request.
An error occurred while sending the request.
Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
An existing connection was forcibly closed by the remote host.

### Reproduction Steps

The problem occurs randomly in Azure Cloud Environment and cannot be replicated.

### Environment

Azure App Service (Net Core 3.1)
Azure Key Vault with Access Policy Configured

**Comment by christothes** [comment]
Hi @izanami00 
Unfortunately, I don't see enough information to determine what the problem is here. My guess, based on the exception, would be some problem with the App Service itself. I would recommend enabling logging for the SDK so that you can get request Id details for the failing requests and opening a support case for the App Service to see if they can determine why the service connection is failing.

As a side note, the version of Azure.Identity you are using should be upgraded to the latest due to various security issues and improvements.

**Comment by izanami00** [comment]
OK, thanks for your recommendation, the issue could be closed.
