### ISSUE TITLE
[BUG]Service Bus Listener Not Stopping After Stopping Route in Latest Camel Version(4.4.0)

### ISSUE THREAD

**Issue by HarshithaReddyEega** [Azure/azure-sdk-for-net#43561]
### Library name and version

camel-azure-servicebus:4.4.1

### Describe the bug

I am using version 4.4.1 of azure-servicebus. In this version, due to a recent fix, the Service Bus listener does not stop even after killing the route. However, in version 4.3.0, the listener stops as expected.

How can I stop the listener in the latest Camel version?

This appears to be an issue.

I have a Service Bus route configured and running as shown below:

```
public class AzureServiceBusRoute extends RouteBuilder {

@Override
public void configure() throws Exception {
    from("azure-servicebus:test-queue?connectionString=RAW(" + connectionString + ")")
        .to("log:receivedMessage")
        .routeId("azureServiceBusRoute");
}
}
```

```
public class Main {
public static void main(String[] args) {
try {
CamelContext camelContext = new DefaultCamelContext();
// Add route to Camel context
camelContext.addRoutes(new AzureServiceBusRoute());
// Start the Camel context
camelContext.start();
// Retrieve RouteController
RouteController routeController = camelContext.getRouteController();
// Start the route
routeController.startRoute("azureServiceBusRoute");
// Wait for some time to keep the context running
Thread.sleep(6000);
camelContext.removeRoute("azureServiceBusRoute");
// Wait for some time after stopping the route
Thread.sleep(10000);
// Stop the Camel context
camelContext.stop();
} catch (Exception e) {
System.out.println(e.getMessage());
}
}
}
```

### Expected behavior

After stopping the Camel route, the Service Bus listener should also stop receiving messages, as observed in version 4.3.0.

### Actual behavior

Even after stopping the Camel route, the Service Bus listener continues to receive messages, indicating that it's still active.

### Reproduction Steps

1. Run the Main.java
2. Let it run for a while to ensure connection is active after starting the route
3. After killing the route connection is lost and reconnecting again
4. Observe that the listener still continues to receive messages despite the route being stopped.
5. Compare this behavior with version 4.3.0(azure-messaging-servicebus:7.14.7), where the listener stops as expected after killing the route.

**Comment by jsquire** [comment]
Hi @HarshithaReddyEega.   Thanks for reaching out and we regret that you're experiencing difficulties.   Can you please help me understand what Azure SDK package and version you're using?   You seem to be referring to `azure-servicebus`  v4.4.1, which does not exist.    The `azure-servicebus` package is a deprecated Java library, but there is no v4.4.1.   

Please be aware that Camel is a third-party product that is not published nor supported by Microsoft.  If this inquiry is about the [Camel Service Bus component](https://camel.apache.org/components/4.4.x/azure-servicebus-component.html), we are unable to assist.

**Comment by HarshithaReddyEega** [comment]
Hi @jsquire Yes, the issue with camel service bus component

**Comment by jsquire** [comment]
> Hi @jsquire Yes, the issue with camel service bus component

@HarshithaReddyEega:  As mentioned, Camel and its component are third-party products not owned or supported by Microsoft.  We're unable to assist with this inquiry.  I'd suggest reaching out to the Camel project for support.
