### ISSUE TITLE
DefaultAzureCredential Fails Azure Identity 1.11.2

### ISSUE THREAD

**Issue by tichyb** [Azure/azure-sdk-for-net#43618]
### Library name and version

Azure.Identity 1.11.2

### Describe the bug

After updating from V 1.10.4 to any 1.11.x version the attached error.
[startupError.txt](https://github.com/Azure/azure-sdk-for-net/files/15095128/startupError.txt)

`	var cred = new DefaultAzureCredential();
	var token = cred.GetToken(new Azure.Core.TokenRequestContext(new[] { "https://vault.azure.net/.default" }));`

I am using a Managed Identity ClientId and have no issues with the previous versions of Azure.Identity. (1.10.4)

### Expected behavior

Authentication passed via ManagedIdentityCredential and application startup continues.
Application works locally using Visual Studio Token Provider

### Actual behavior

application fails to start

### Reproduction Steps

update to any Azure Identity 1.11.x version, deploy to server and start web application.

### Environment

Hosting platform : Azure Infrastructure as a service (IaaS)
.NET SDK:
 Version:           8.0.204

IDE: Visual Studio 17.9.6

**Comment by christothes** [comment]
hi @tichyb, Could you enable logging to reproduce the issue? This should provide more information about what is happening.  https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/README.md#logging

**Comment by bilby91** [comment]
We are having the same problem after migrating from 1.10 to 1.11. Only breaks with managed identity.

**Comment by tichyb** [comment]
@christothes I am seeing the following in my logs, we are using a ManagedIdentityCredential:

An error occurred: DefaultAzureCredential failed to retrieve a token from the included credentials. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/defaultazurecredential/troubleshoot
- EnvironmentCredential authentication unavailable. Environment variables are not fully configured. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/environmentcredential/troubleshoot
- WorkloadIdentityCredential authentication unavailable. The workload options are not fully configured. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/workloadidentitycredential/troubleshoot
- ManagedIdentityCredential authentication unavailable. No response received from the managed identity endpoint.
- Visual Studio Token provider can't be accessed at C:\windows\system32\config\systemprofile\AppData\Local\.IdentityService\AzureServiceAuth\tokenprovider.json
- Azure CLI not installed
- Az.Accounts module >= 2.2.0 is not installed.
- Azure Developer CLI could not be found.

**Comment by christothes** [comment]
Hi @tichyb - 
Could you share the details of the logs when we attempt the `ManagedIdentityCredential` authentication?

Also, are you able to reproduce this by using `ManagedIdentityCredential` directly instead of `DefaultAzureCredential`?

**Comment by tichyb** [comment]
@christothes additional logging below:
ManagedIdentityCredential.GetToken was unable to retrieve an access token. Scopes: [ https://vault.azure.net/.default ] ParentRequestId:  Exception: Azure.Identity.CredentialUnavailableException (0x80131500): ManagedIdentityCredential authentication unavailable. No response received from the managed identity endpoint.
 ---> System.Threading.Tasks.TaskCanceledException (0x8013153b): The operation was cancelled because it exceeded the configured timeout of 0:00:01. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.
 ---> System.Threading.Tasks.TaskCanceledException (0x8013153b): A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException (0x8013153b): A task was canceled.

----------------------------------------------------------------------------------------------------
ManagedIdentityCredential.GetToken was unable to retrieve an access token. Scopes: [ https://vault.azure.net/.default ] ParentRequestId:  Exception: Azure.Identity.CredentialUnavailableException (0x80131500): ManagedIdentityCredential authentication unavailable. No response received from the managed identity endpoint.
 ---> System.Threading.Tasks.TaskCanceledException (0x8013153b): The operation was cancelled because it exceeded the configured timeout of 0:00:01. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.
 ---> System.Threading.Tasks.TaskCanceledException (0x8013153b): A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException (0x8013153b): A task was canceled.

=== End of inner exception stack trace ===
To see full exception details, enable PII Logging. See https://aka.ms/msal-net-logging
   at Azure.Identity.ImdsManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityClient.AuthenticateCoreAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityClient.AppTokenProviderImpl(AppTokenProviderParameters parameters)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.SendTokenRequestToAppTokenProviderAsync(ILoggerAdapter logger, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.GetAccessTokenAsync(CancellationToken cancellationToken, ILoggerAdapter logger)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<>c__DisplayClass11_1.<<RunAsync>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Identity.Client.Utils.StopwatchService.MeasureCodeBlockAsync(Func`1 codeBlock)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)


------------------------------------------------------------------------------------------------------------------------
Request [97c3493e-8c5e-4041-972f-5908d1454fc9] exception System.Threading.Tasks.TaskCanceledException: The operation was cancelled because it exceeded the configured timeout of 0:00:01. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message, Boolean async)
   at Azure.Core.Pipeline.HttpPipelineTransportPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   --- End of inner exception stack trace ---
   at Azure.Core.Pipeline.ResponseBodyPolicy.ThrowIfCancellationRequestedOrTimeout(CancellationToken originalToken, CancellationToken timeoutToken, Exception inner, TimeSpan timeout)
   at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.LoggingPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)


---------------------------------------------------------------------------------------------------------------------------------

Request [97c3493e-8c5e-4041-972f-5908d1454fc9] GET http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=REDACTED
x-ms-client-request-id:97c3493e-8c5e-4041-972f-5908d1454fc9
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.11.2 (.NET 8.0.3; Microsoft Windows 10.0.14393)
client assembly: Azure.Identity


----------------------------------------------------------------------------------------------------------------------

False MSAL 4.60.3.0 MSAL.NetCore .NET 8.0.3 Microsoft Windows 10.0.14393 [2024-05-01 19:42:51Z - dcc3dd32-4e41-43f3-97d5-f4925b286b7b] [Instance Discovery] Skipping Instance discovery because it is disabled. 

-------------------------------------------------------------------------------------------------------------

False MSAL 4.60.3.0 MSAL.NetCore .NET 8.0.3 Microsoft Windows 10.0.14393 [2024-05-01 19:42:51Z - dcc3dd32-4e41-43f3-97d5-f4925b286b7b] === Token Acquisition (ClientCredentialRequest) started:
	 Scopes: https://vault.azure.net/.default
	Authority Host: login.microsoftonline.com

--------------------------------------------------------------------------------------------------------------

False MSAL 4.60.3.0 MSAL.NetCore .NET 8.0.3 Microsoft Windows 10.0.14393 [2024-05-01 19:42:51Z - dcc3dd32-4e41-43f3-97d5-f4925b286b7b] 
=== Request Data ===
Authority Provided? - True
Scopes - https://vault.azure.net/.default
Extra Query Params Keys (space separated) - 
ApiId - AcquireTokenForClient
IsConfidentialClient - True
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - dcc3dd32-4e41-43f3-97d5-f4925b286b7b
UserAssertion set: False
LongRunningOboCacheKey set: False
Region configured: 

-----------------------------------------------------------------------------------------------------------------------

False MSAL 4.60.3.0 MSAL.NetCore .NET 8.0.3 Microsoft Windows 10.0.14393 [2024-05-01 19:42:51Z - dcc3dd32-4e41-43f3-97d5-f4925b286b7b] === AcquireTokenForClientParameters ===
SendX5C: False
ForceRefresh: False


---------------------------------------------------------------------------------------------------------------------------

ManagedIdentityCredential.GetToken invoked. Scopes: [ https://vault.azure.net/.default ] ParentRequestId: 

---------------------------------------------------------------------------------------------------------------------------

DefaultAzureCredential.GetToken invoked. Scopes: [ https://vault.azure.net/.default ] ParentRequestId:

**Comment by tichyb** [comment]
@christothes 
I noticed with the older 1.10.x versions I see this:
Request [7ad40b7c-48a1-4915-ad6f-83b9748f65cf] attempt number 1 took 01.1s

-------------------------------------------------------------------------------
Request [7ad40b7c-48a1-4915-ad6f-83b9748f65cf] GET http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=REDACTED
Metadata:REDACTED
x-ms-client-request-id:7ad40b7c-48a1-4915-ad6f-83b9748f65cf
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.10.4 (.NET 8.0.3; Microsoft Windows 10.0.14393)
client assembly: Azure.Identity

---------------------------------------------------------------------------

Response [7ad40b7c-48a1-4915-ad6f-83b9748f65cf] 200 OK (00.2s)
Server:IMDS/150.870.65.1253
x-ms-request-id:53405744-4414-409f-b038-c89cf1d9963b
Date:Wed, 01 May 2024 20:39:30 GMT
Content-Type:application/json; charset=utf-8
Content-Length:1906

---------------------------------------------------------------------

False MSAL 4.59.0.0 MSAL.NetCore .NET 8.0.3 Microsoft Windows 10.0.14393 [2024-05-01 20:39:30Z - 8a26d259-6f2a-4dc3-b943-b9e703126bda] Checking client info returned from the server..

------------------------------------------------------------------------------------
False MSAL 4.59.0.0 MSAL.NetCore .NET 8.0.3 Microsoft Windows 10.0.14393 [2024-05-01 20:39:30Z - 8a26d259-6f2a-4dc3-b943-b9e703126bda] Saving token response to cache..

---------------------------------------------------------------------------------------------------------

**Comment by christothes** [comment]
Thanks - it seems that we are not receiving a response from IMDS within the timeout. 

> Also, are you able to reproduce this by using `ManagedIdentityCredential` directly instead of `DefaultAzureCredential`?

Were you able to try this? It would help determine whether this is related to the timeout being too aggressive or if the endpoint is just not responding for some reason.

**Comment by tichyb** [comment]
> Thanks - it seems that we are not receiving a response from IMDS within the timeout.
> 
> > Also, are you able to reproduce this by using `ManagedIdentityCredential` directly instead of `DefaultAzureCredential`?
> 
> Were you able to try this? It would help determine whether this is related to the timeout being too aggressive or if the endpoint is just not responding for some reason.

When I use 'ManagedIdentityCredential' directly I am able to successfully retrieve a token.

--------------------------------------
DefaultAzureCredential credential selected: Azure.Identity.ManagedIdentityCredential

--------------------------------------
DefaultAzureCredential.GetToken succeeded. Scopes: [ https://vault.azure.net/.default ] ParentRequestId: 106677f1-35f1-4e7c-b28f-0eb0bf0abf66 ExpiresOn: 2024-05-03T19:09:47.4232930+00:00

**Comment by christothes** [comment]
Thanks for confirming - If you enable logging for the `ManagedIdentityCredential`, how long did it take to receive a response from the IMDS endpoint?

**Comment by tichyb** [comment]
> Thanks for confirming - If you enable logging for the `ManagedIdentityCredential`, how long did it take to receive a response from the IMDS endpoint?

If this is correct then only couple milliseconds, I included logs for reference

2024-05-02T19:25:22.277407800Z
2024-05-02T19:25:22.293025400Z 


--- Request ---- 2024-05-02T19:25:22.277407800Z

Request [c920440b-ec12-44ba-9674-1de57c887fb0] GET http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=REDACTED
Metadata:REDACTED
x-ms-client-request-id:c920440b-ec12-44ba-9674-1de57c887fb0
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.11.2 (.NET 8.0.3; Microsoft Windows 10.0.14393)
client assembly: Azure.Identity


-- IMDS response ------ 2024-05-02T19:25:22.293025400Z 

Response [c920440b-ec12-44ba-9674-1de57c887fb0] 200 OK (00.0s)
Server:IMDS/150.870.65.1253
x-ms-request-id:b56f2cb6-ac77-4ed5-9b1e-6c245d515933
Date:Thu, 02 May 2024 19:25:21 GMT
Content-Type:application/json; charset=utf-8
Content-Length:1906

**Comment by christothes** [comment]
Hi @tichyb - could you share the resource id for the VM that you are reproducing this so that we can look up the telemetry on the service side?

**Comment by tichyb** [comment]
> Hi @tichyb - could you share the resource id for the VM that you are reproducing this so that we can look up the telemetry on the service side?

/subscriptions/0d0a1d06-eee4-4a41-9a26-e97d50fc8639/resourceGroups/rg-spoke-app-dev-eastus-0/providers/Microsoft.Compute/virtualMachines/vm-app-d-e1-0

**Comment by christothes** [comment]
Thanks @tichyb - 
Could you try issuing a curl command directly from within the VM to the IMDS endpoint without the `Metadata` header to see if ever responds?

**Comment by tichyb** [comment]
@christothes 
without the metadata - "error":"invalid_request","error_description":"Required metadata header not specified"

**Comment by christothes** [comment]
So it does respond, and gives you a status 400?

**Comment by tichyb** [comment]
> So it does respond, and gives you a status 400?

That is correct

**Comment by christothes** [comment]
Hi @tichyb - 
Would you mind issuing a set of new requests and providing the exact timestamps (should be available via logging)? This will help the service team locate them and compare the failing one. Ideally, please try the following:

DefaultAzureCredential
ManagedIdentityCredential
curl with and without `Metadata` header.

thanks for your patience as we try to narrow this down.

**Comment by tichyb** [comment]
> Hi @tichyb - Would you mind issuing a set of new requests and providing the exact timestamps (should be available via logging)? This will help the service team locate them and compare the failing one. Ideally, please try the following:
> 
> DefaultAzureCredential ManagedIdentityCredential curl with and without `Metadata` header.
> 
> thanks for your patience as we try to narrow this down.
ManagedIdentityCredential :

2024-05-06 18:47:25Z (with header)
 
2024-05-06 18:48:23Z (without header) "Invoke-WebRequest : {"error":"invalid_request","error_description":"Required metadata header not specified"}"

--------------------------------------------------
l am not sure how to invoke the request for a DefaultAzureCredential in powershell

**Comment by christothes** [comment]
Thanks @tichyb  - Could you confirm this is from the same resource mentioned earlier? (`/subscriptions/0d0a1d06-eee4-4a41-9a26-e97d50fc8639/resourceGroups/rg-spoke-app-dev-eastus-0/providers/Microsoft.Compute/virtualMachines/vm-app-d-e1-0`)?

For the `ManagedIdentityCredential` and `DefaultAzureCredential` tests, using your application code should be sufficient. Alternatively, you could create a simple console application that fetches a token for a scope like "https://graph.microsoft.com/.default"

**Comment by stas-sultanov** [comment]
I have faced exactly the same issue.
had to downgrade "Azure.Identity" to Version="1.10.4"
