### ISSUE TITLE
[BUG] Azure.ResourceManager.Orbital SDK Issues

### ISSUE THREAD

**Issue by thisisdevanshu** [Azure/azure-sdk-for-net#43626]
### Library name and version

Azure.ResourceManager.Orbital

### Describe the bug

We recently discovered 2 issues with the .NET SDK https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/orbital/Azure.ResourceManager.Orbital 

1. EventHubUri is a misnomer, we expected a resource id, but the SDK expects a URI
2. EndPoint.ipAddress: - ip-address is not nullable in .NET TSDK

### Expected behavior

1. EventHubUri accepts a resource id in the .NET SDK
2. Endpoint.ipAddress allows null for ip address

### Actual behavior

1. EventHubUri does not accept a resource id in the .NET SDK
2. Endpoint.ipAddress does not allow null for ip address

### Reproduction Steps

1. Create a contact profile resource with a eventhub resource id
2. Create a contact profile with null value for Endpoint.ipAddress

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Workaround this from sdk side:
1. Rename it to eventHubId and add attribute "format": "arm-id".
2. Remove ipAddress out of required [azure-rest-api-specs/specification/orbital/resource-manager/Microsoft.Orbital/stable/2022-11-01/orbital.json at main · Azure/azure-rest-api-specs (github.com)](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/orbital/resource-manager/Microsoft.Orbital/stable/2022-11-01/orbital.json#L1268)

**Comment by melina5656** [comment]
Hi @thisisdevanshu ,  We have conducted multiple tests on `PUT/subscriptions/<>/resourceGroups/<>/providers/Microsoft. Organizational/contactprofiles/<>? API version=2022-03-01` and found that the current API version does not support null values for the `ipAddress` property. If the value passed in is null, a RequestFailedException error will be thrown. May I ask if the version you are using is `2022-03-01`? And how did you determine that the `ipAddress` property can be null? Look forward to your reply.
