### ISSUE TITLE
[QUERY] How to use a custom log processor

### ISSUE THREAD

**Issue by AlexGlassman** [Azure/azure-sdk-for-net#43623]
### Library name and version

Azure.Monitor.OpenTelemetry.AspNetCore v1.1

### Query/Question

I have implemented a custom log processor to obfuscate sensitive log data. As per the OpenTelemetry docs [here](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/docs/logs/extending-the-sdk/README.md), it looks something like this:
```c#
public class OTelSensitiveDataEnricher : BaseProcessor<LogRecord>
{
    private readonly IEnumerable<ISensitiveDataFilter> _sensitiveDataFilters;

    public OTelSensitiveDataEnricher(IEnumerable<ISensitiveDataFilter> sensitiveDataFilters)
    {
        _sensitiveDataFilters = sensitiveDataFilters;
    }

    public override void OnEnd(LogRecord logRecord)
    { 
       //use _sensitiveDataFilters to obfuscate data in logRecord 
    }
}
```

My issue is understanding how I can register this processor in my `Program/StartUp.cs` in conjunction with the Azure Monitor Distro, as the `UseAzureMonitor()` extension method handles log configuration behind the scenes, and it doesn't seem like there is a way to add a Log Processor in the same way as you can add a Trace Processor or Metrics Processor as shown in [the docs](https://learn.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-add-modify?tabs=aspnetcore#filter-telemetry).

Any help would be greatly appreciated. Thanks!

 

### Environment

.NET 8

**Comment by TimothyMothra** [comment]
Hi @AlexGlassman, I've got some options for you.
Note that for either option you should add your Processor BEFORE calling `UseAzureMonitor` to place your custom Processor earlier in the chain.

### Option 1. Call `AddLogging` and `AddOpenTelemetry`


```csharp
builder.Services.AddLogging(logging =>
{
    logging.AddOpenTelemetry(builderOptions =>
    {
        builderOptions.AddProcessor(new MyCustomProcessor());
    });
});

builder.Services.AddOpenTelemetry().UseAzureMonitor();
```

### Option 2. Experimental Api: `ConfigureOpenTelemetryLoggerProvider`
As of today, this API is currently only available in beta versions of [OpenTelemetry](https://www.nuget.org/packages/OpenTelemetry).

You can watch the OpenTelemetry dotnet repo to see when this API is stablized: https://github.com/open-telemetry/opentelemetry-dotnet/issues/5442


```csharp
builder.Services.ConfigureOpenTelemetryLoggerProvider(builder => builder.AddProcessor<MyCustomProcessor>());
builder.Services.AddOpenTelemetry().UseAzureMonitor();
```

**Comment by AlexGlassman** [comment]
Thanks @TimothyMothra! Option 1 worked a treat; I did initially think about this approach but erroneously assumed calling `UseAzureMonitor()` would override whatever custom processors were configured before it. This is a production workload so went with the more stable option, but will keep my eyes peeled for `ConfigureOpenTelemetryLoggerProvider` coming out of beta. 

Thanks again!
