### ISSUE TITLE
[BUG] checkpoint format now sets Offset=null 

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-sdk-for-net#43649]
### Library name and version

Azure.Messaging.EventHubs 5.10.0

### Describe the bug

https://github.com/Azure/azure-functions-extension-bundles/issues/389

### Expected behavior

offset should not be null as it impacts scaling for Azure Functions Apps

### Actual behavior

offset should not be null as it impacts scaling for Azure Functions Apps

### Reproduction Steps

Unexpected scaling behavior

### Environment

Azure Functions Apps

**Comment by pragnagopa** [comment]
@alrod @sidkri @chiangvincent @jsquire

**Comment by jsquire** [comment]
Your expected behavior is incorrect.  The offset is intentionally set to null.
