### ISSUE TITLE
[QUERY] Using Logic App SDK to provide Trigger parameter values

### ISSUE THREAD

**Issue by KhushaalKurswaniAnicca** [Azure/azure-sdk-for-net#43654]
### Library name and version

Azure.ResourceManager.Logic 1.0.1

### Query/Question

Hi,

I have a Logic App Workflow to send email messages. The Logic App has a HTTP Request Trigger and accepts request parameters relevant to the email (to, subject, message body).

I know that I can use the HTTP trigger's URL to pass in the email parameters and trigger the workflow. **However, I am looking for a way to pass parameters to the trigger using the Logic APP SDK instead of making a direct REST API call.**

I previously asked a similar question ([Providing parameter values when triggering Logic App Workflow](https://learn.microsoft.com/en-us/answers/questions/1656787/providing-parameter-values-when-triggering-logic-a)). The answer to that question led me to the SDK's [LogicWorkflowResource.UpdateAsync](https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.logic.logicworkflowresource.updateasync?view=azure-dotnet) method.

The [LogicWorkflowResource.UpdateAsync](https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.logic.logicworkflowresource.updateasync?view=azure-dotnet) method can be used to update workflow parameters. Although this method works as intended, it does not meet all my requirements. **Storing and modifying the email details as workflow parameters is clunky since the workflow parameters are not designed to be changed for every time the Logic App Workflow is triggered.**

**Instead, I am looking for a way to use the Logic App SDK to set the HTTP Trigger's request parameters. Is such a functionality supported by the Logic App SDK?**

**Comment by mcgallan** [comment]
Hi @KhushaalKurswaniAnicca ，thank you for your feedback. I'm sorry, but the Logic App SDK currently does not support directly setting the request parameters of the HTTP trigger, so your requirement cannot be met at this time. You can see from the content of LogicWorkflowTriggerResource that the operations we can perform on the Trigger in the SDK cannot pass parameters in the call, so we cannot use the SDK to set the parameters of the Http trigger.
