### ISSUE TITLE
[QUERY] - Register custom HttpClient

### ISSUE THREAD

**Issue by schmallaria** [Azure/azure-sdk-for-net#43680]
### Library name and version

Microsoft.Extensions.Azure

### Query/Question

I'm trying to figure out if it's possible to add a custom HttpClient (typed or untyped) via AddAzureClients configuration method.

Something like:
```
 services.AddAzureClients(builder =>
 {
     builder.AddClient<HttpClient, HttpClientOptions>();
     builder.UseCredential(new DefaultAzureCredential());
 });
```

Is that possible or are only the Azure SDK clients allowed here?

**Background**: My application uses Azure.ResourceManager.ApiManagement package to access API Management Gateway. Via that package we're trying to figure out which APIs have an health endpoint. This health endpoint is then called via a custom HttpClient. For both, the API Management client and for the HttpClient we want to use the same configuartion method and the same credentials.

**Comment by jsquire** [comment]
Hi @schmallaria.  Thanks for reaching out and for your inquiry.  While you could create a client factory that would allow you to register an `HttpClient` via the `AddAzureClients` extension, there's no benefit over using the standard DI registration path, as it will not achieve your goal.   

The Azure clients use a well-known pattern for authentication via Azure.Identity credentials and Azure.Core's configuration options which the `AddAzureClients` uses to configure and inject credentials.  The `HttpClient` type does not support those constructs nor the Azure SDK patterns.  You would be better off configuring/registering your `HttpClient` with the standard DI path and injecting a `TokenCredential` into wherever you're using `HttpClient` and then manually requesting the token from it.

Something like:

```csharp

// Assumption "MyClass" is created by DI, which injects the registered client and credential.
public class MyClass
{
    private HttpClient _httpClient;
    priivate TokenCredential _credential;

    public MyClass(HttpClient httpClient, TokenCredential credential) => (_ httpClient, _credential) = (httpClient, credential)

    public async Task DoTheThing()
    {
        var bearerToken = await _credential.GetTokenAsync(
            new TokenRequestContext(new[] { "http://some.service.com/.default" }), CancellationToken.None);    
    
        var message = new HttpRequestMessage(HttpMethod.Get, new Uri("https://www.google.com"));
        message.Headers.Authorization = new AuthenticationHeaderValue("Bearer", bearerToken.Token);
    
        await _httpClient.SendAsync(message);
    }
}

```
