### ISSUE TITLE
[FEATURE REQ] ServiceBusReceivedMessage: include QueueProperties

### ISSUE THREAD

**Issue by marthijn** [Azure/azure-sdk-for-net#43694]
### Library name

Azure.Messaging.ServiceBus

### Please describe the feature.

It would be nice to include some information about the origin of a `ServiceBusReceivedMessage`. For example the information listed in the class `QueueProperties`. With this information many more things are possible in middleware (e.g. logging, scheduled retries, audit trails, etc.)

**Comment by jsquire** [comment]
Hi @marthijn.  Thank you for reaching out and we regret that you're experiencing difficulties.  The information that you're asking for is not part of the contract for messages returned by Service Bus, so it cannot be included in `ServiceBusMessage`.   Should the service choose to include additional information in the messages they return, the client will surface them.

If you would like to suggest this feature to the Service Bus service team, your best path forward would be to open an issue in the [Azure Service Bus service repository](http://www.github.com/Azure/azure-service-bus/issues) or  on the [Azure Feedback site](https://feedback.azure.com/d365community).

I'm going to close this out; if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.
