### ISSUE TITLE
LUIS nuget

### ISSUE THREAD

**Issue by vovanb** [Azure/azure-sdk-for-net#4373]
What nuget I should use for LUIS c# API?
Below path does not added to any nuget:
azure-sdk-for-net/src/SDKs/CognitiveServices/dataPlane/Language/LUIS/Runtime/Generated/

**Comment by shahabhijeet** [comment]
@DavidLiCIG is this the right package?
https://www.nuget.org/packages/Microsoft.Azure.CognitiveServices.Language.LUIS.Runtime/0.9.0-preview

@vovanb you don't have to add any paths, simply search for LUIS package in the Visual Studio
1. Right click on your project in VS where you want to consume the package
2. Search for LUIS
3. Install the pakcage (after selecting the version you want)

**Comment by DavidLiCIG** [comment]
Yes, this is the right package that was just published last week.

Thanks!

**Comment by ChrisHMSFT** [comment]
Closing the ticket since David provided the answer. 

Thanks,
Chris
