### ISSUE TITLE
Incomplete information. 

### ISSUE THREAD

**Issue by bigtfromaz** [Azure/azure-sdk-for-net#43787]
### Type of issue

Typo

### Description

[Enter feedback here]
A reference to the ArmDnsModelFactory.DnsARecordData factory would be helpful on the DnsARecordData Constructor page.  

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.dns.dnsarecorddata.-ctor?view=azure-dotnet

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.ResourceManager.Dns/DnsARecordData.xml

### Document Version Independent Id

b1f6f435-ef70-0544-45dc-4ad04b5e0b1f

### Article author

@azure-sdk

### Metadata

* ID: b12e77f5-7325-38f6-db72-8bed77364c60 
* Service: **azure**

**Comment by cxznmhdcxz** [comment]
Hi @bigtfromaz , the navigation on the top of the article shows and could reach the parent pages. Hope this could help.


![image](https://github.com/Azure/azure-sdk-for-net/assets/47708215/68510718-313b-49d1-af79-6477e44fc3af)

**Comment by HarveyLink** [comment]
Hi @bigtfromaz , The document is auto generated from our SDK source.
Regarding the usage question, you could check our usage sample: https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/dns/Azure.ResourceManager.Dns/samples or test code: https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/dns/Azure.ResourceManager.Dns/tests/Scenario.
