### ISSUE TITLE
House or house?

### ISSUE THREAD

**Issue by mikeblakeuk** [Azure/azure-sdk-for-net#43786]
https://github.com/Azure/azure-sdk-for-net/blob/92c30eb92baf8373206834fca1eb996458c32917/sdk/datafactory/Azure.ResourceManager.DataFactory/src/Generated/Models/LakeHouseTableDataset.cs#L20

Should it be LakeHouse or Lakehouse?

as per 
https://github.com/MicrosoftDocs/azure-docs/issues/122106

**Comment by ArthurMa1978** [comment]
Add @ruowan , it's `LakeHouse` defined in swagger spec, so might be fixed from swagger spec if it should be `Lakehouse`.

**Comment by JaylenZ8** [comment]
We're preparing a PR to fix the naming from `LakeHouse` to `Lakehouse`, thanks.

**Comment by ruowan** [comment]
According to the Azure breaking change policy, changing the name is breaking change for customer. So close this issue. If any other concern, pls reopen this.

**Comment by mikeblakeuk** [comment]
But the bot broke the name why it fixed the spelling.
What does the server side expect?
Why is there a mix of Lakehouse and LakeHouse?

**Comment by mikeblakeuk** [comment]
Can this be reopened?
That would help this PR https://github.com/Azure/azure-sdk-for-net/pull/44121
