### ISSUE TITLE
[BUG] When working with Semantic Kernel, while invoking ChatCompletion API, unable to specify data sources

### ISSUE THREAD

**Issue by chetan-d-mahajan** [Azure/azure-sdk-for-net#43783]
### Library name and version

Microsoft.SemanticKernel, Microsoft.SemanticKernel.ChatCompletion

### Describe the bug

When calling the OpenAI's chat completion API, the SDK doesn't provide an option to specify extra field such as "data_sources"

https://learn.microsoft.com/en-us/azure/ai-services/openai/references/on-your-data?tabs=rest#context

### Expected behavior

the SKD should support additional parameter to chat completions API

### Actual behavior

the SKD doesn't support additional parameter to chat completions API

### Reproduction Steps

Microsoft.SemanticKernel.ChatCompletion.IChatCompletionService.GetStreamingChatMessageContentsAsync()

This method doesn't accept additional parameters to query data on custom data sources

### Environment

VS 2022
.NET 6.0
Windows

**Comment by chetan-d-mahajan** [comment]
@Rtoribiog

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.SemanticKernel` packages are maintained as [#6061](https://github.com/microsoft/semantic-kernel/issues/6061).
