### ISSUE TITLE
Async SdkContext.AzureCredentialsFactory.FromServicePrincipal()

### ISSUE THREAD

**Issue by ImageQC** [Azure/azure-sdk-for-net#4379]
A call to SdkContext.AzureCredentialsFactory.FromServicePrincipal() can take 5 seconds or more to return. Is there an async version or other way to invoke it that would free the thread whilst it waits for the Azure service to do its stuff?

**Comment by shahabhijeet** [comment]
@ImageQC can you please help us understand this scenario better.
Please provide the name of the sdk nuget package that you are using.
Also any code that will help us to repro this issues helps.

**Comment by ImageQC** [comment]
<ItemGroup>
    <PackageReference Include="Microsoft.Azure.Management.Fluent" Version="1.11.1" />
    <PackageReference Include="Microsoft.Azure.WebJobs" Version="3.0.0-beta5" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="3.0.0-beta5" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="1.4.1" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.EventGrid" Version="2.0.0-beta1" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.13" />
    <PackageReference Include="System.Data.SqlClient" Version="4.4.0-preview1-25305-02" />
  </ItemGroup>


                            var azure = Azure
                                .Configure()
                                .WithLogLevel(HttpLoggingDelegatingHandler.Level.Basic)
                                .Authenticate(credentials)
                                .WithDefaultSubscription();


                                                var containerGroup = await azure.GetResult().ContainerGroups
                                                    .Define(containerName)
                                                    .WithRegion(Region.EuropeWest)
                                                    .WithExistingResourceGroup(resourceGroupName)
                                                    .WithLinux()
                                                    .WithPublicImageRegistryOnly()
                                                    .WithoutVolume()
                                                        .DefineContainerInstance(containerName)
                                                        .WithImage(classifierImage)
                                                        .WithExternalTcpPort(80)
                                                        .WithCpuCoreCount(cpuCount)
                                                        .WithMemorySizeInGB(memoryGb)
                                                        .Attach()
                                                        .WithDnsPrefix(dnsPrefix)
                                                        .WithRestartPolicy(ContainerGroupRestartPolicy.OnFailure)
                                                    .CreateAsync();

The delay is in the second call. Please let me know if you need anything more.

**Comment by shahabhijeet** [comment]
@ImageQC this seems like a .NET Fluent SDK issue.
Can you open an issue in this repo for all .NET Fluent related stuff
https://github.com/Azure/azure-libraries-for-net/issues
Closing this issue. Let me know if you think otherwise.
