### ISSUE TITLE
[Codegen] Model hierarchy to support OpenAI package from Azure OpenAI package

### ISSUE THREAD

**Issue by pallavit** [Azure/azure-sdk-for-net#43805]
In order to support model hierarchy which is the way we want to enable Azure OpenAI SDK usage from the OpenAI SDK we need the following features from the codegen.

Constructors
1. Add a protected Client(string model, ClientPipeline pipeline, ApiKeyCredential keyCredential, Uri endpoint) (current existing internal constructor, just with model added)

Methods
1. Do not make convenience methods virtual; do ensure all convenience methods are ultimately calls into their protocol counterparts
2. Do make protocol methods virtual
3. What about PipelineMessage creation? If not that, then RequestContent?

Fields
1. Everything but constants seemingly become protected: _endpoint, _keyCredential, _pipeline
2. We also introduce a new protected string Model since our clients stash that

Pipeline
1. How should pipeline creation be overriden? Right now, the base library has its creation [hard-coded in the factory client](https://github.com/joseharriaga/openai-in-typespec/blob/main/.dotnet/src/Generated/OpenAIClient.cs#L49). 2. Should we replace that constructor with one that has a protected virtual CreatePipeline() used? And then, should directly instantiable scenario clients duplicate that logic, have a lazy-initialized back-ref to the parent factory client to generate their pipelines, or do something else?
3. We should have CreatePipeline virtual method, just like we have CreateRequest.

**Comment by jsquire** [comment]
This is no longer the current plan for extension.  The current plan involves using extension members and an AdditionalProperties bag covered by other tracking.   Closing this out as unplanned.
