### ISSUE TITLE
Pulling image from public docker registry.

### ISSUE THREAD

**Issue by tmp505** [Azure/azure-sdk-for-net#43829]
### Library name and version

Azure.ResourceManager.ContainerRegistry

### Query/Question

I'm failing to retrieve images from public docker.io registry using nuget below:
using Azure.Containers.ContainerRegistry;
ContainerRegistryClient registryClient = new ContainerRegistryClient(new Uri("https://registry.docker.io"));
RegistryArtifact? artifact = registryClient.GetArtifact("registry", "latest");
if (artifact is not null)
{ 
    var artifactManifest = artifact.GetManifestProperties();
    // https://registry.docker.io => 503 Service Unavailable
    // https://registry-1.docker.io => 404 Not Found
}

Is this is just a mishap over the v1/v2 registry standards or hopefully just my code, please let me know.
To test that I can get manifest manually I had to use registry v2 on this base url: registry-1.docker.io
Before that a bearer token from auth.docker.io/token?service=registry.docker.io&scope=repository:library/registry:pull

### Environment

.NET8, Win10 Visual Studio

**Comment by jsquire** [comment]
@tmp505:  Thank you for reaching out and we regret that you're experiencing difficulties.   Based on the code snippet that you've included, I'm going to assume that your inquiry is about the `Azure.Containers.ContainerRegistry` and not the resource manager library that you referenced.

If I understand correctly, you're attempting to use the Azure Container Registry client to access the Docker registry.  This is not a supported scenario; the Azure SDK package is intended to be used with the [Azure Container Registry service](https://learn.microsoft.com/azure/container-registry/container-registry-intro).  While we do not actively prevent you from using the client with other registries, we do not guarantee compatibility, nor do we support doing so.
