### ISSUE TITLE
MSI return the entire token

### ISSUE THREAD

**Issue by danwkennedy** [Azure/azure-sdk-for-net#4383]
Our service would like to use the expiration metadata from the MSI endpoint so that we can know when to retrieve a new access token instead of pinging the endpoint repeatedly. Right now, the SDK assumes that all we want is the access token and short circuits that. The use case for us is we're using the access token to authenticate with SQL Azure so the extra request latency for MSI adds up over time.

Thanks for all your work on this!

**Comment by varunsh-msft** [comment]
Is this request for AzureServiceTokenProvider? What code are you using right now?

**Comment by nonik0** [comment]
Hi Dan, in the next release of AppAuth which we are working on releasing now, there will be a new method for AzureServiceTokenProvider called GetAuthenticationResultAsync that will return the new AppAuthenticationResult object. This object will contain both the raw access token string as well as the expiration time of the access token. 

I believe this will cover your ask, but let me know if you have any more questions.

**Comment by nonik0** [comment]
@danwkennedy 

We have receently released AppAuth 1.2.0-preview, which contains the changes I detailed about just above. You can find the new release here:
https://www.nuget.org/packages/Microsoft.Azure.Services.AppAuthentication/1.2.0-preview

Let us know if you have any feedback!

**Comment by varunsh-msft** [comment]
@shahabhijeet , can you please close this issue? Thanks!
