### ISSUE TITLE
[QUERY] Storage Blob Data Contributor at Storage Account Container Level

### ISSUE THREAD

**Issue by Qualizorg** [Azure/azure-sdk-for-net#43833]
### Library name and version

Azure.Storage.Blobs 12.19.1

### Query/Question

Should the Storage Blob Data Contributor Role be sufficient at container level from Storage Account to allow .NET BlobClient to be able to persist blobs without having roles at Storage Account level?

**Comment by seanmcc-msft** [comment]
Please see the public documentation - https://learn.microsoft.com/en-us/rest/api/storageservices/authorize-with-azure-active-directory#manage-access-rights-with-rbac
