### ISSUE TITLE
[BUG]  Accessing KeyVault with ManagedIdentityCredential (using DefaultAzureCredential) for local development taking several minutes

### ISSUE THREAD

**Issue by erlingto** [Azure/azure-sdk-for-net#43905]
### Library name and version

Azure Identity 1.11.2

### Describe the bug

When launching my ASP.NET API locally I'm accessing a KeyVault to fetch some configuration parameters. This is done using a plain (no options) DefaultAzureCredential instance. This has always been time consuming (around 40 sec to get the API up and running), but last week i started getting timeout errors on the request to the KeyVault. I am suspecting that the problem is related to ManagedIdentityCredentials being extremely slow. 

Spinning up the API (with some workarounds to prevent timeouts) takes about 2 minutes and 50 seconds now. Additionally some other processes running in the background of the API relying on managed identity for authorization against other APIs have problems with requests timing out.  

This seems like a problem that only affects a few of the developers, as most of the developers can still access the KeyVault in under a minute, it seems only me and a handful others are affected by this issue. Issues started last Thursday 2.5.2024.

Interestingly, sending the request through a proxy (Fiddler) makes the request go back to taking about 40 seconds again (but leads to different complications down the line that i consider unrelated to this issue)

### Expected behavior

Accessing a keyvault using DefaultAzureCredential (ManagedIdentityCredentials) takes a reasonable amount of time and does not timeout without workarounds. 

### Actual behavior

Accessing a keyvault using DefaultAzureCredential takes up to 3 minutes and times out unless work arounds are present. 

### Reproduction Steps

Instantiating a DefaultAzureCredential to fetch API configuration from a KeyVault.

`TokenCredential credential =  new DefaultAzureCredential()
config.AddAzureAppConfiguration(options =>
{
    options.Connect(new Uri(endpoint), credential)
        .ConfigureKeyVault(kv =>
        {
            kv.SetCredential(new DefaultAzureCredential());
        });
});`

**Comment by christothes** [comment]
Hi @erlingto - This should be fixed in https://www.nuget.org/packages/Azure.Identity/1.11.3

**Comment by christothes** [comment]
related #43825
