### ISSUE TITLE
[BUG] BlobContainerClient.CreateIfNotExistsAsync throws exception if container exists

### ISSUE THREAD

**Issue by rekhamoturislx** [Azure/azure-sdk-for-net#43911]
### Library name and version

Azure.Storage.Blobs [latest]

### Describe the bug

BlobContainerClient.CreateIfNotExistsAsync still throws a 409 when the container exists logging 1000s of unnecessary events in AppInsights
This issue was reported by many users and was closed without resolution

BlobContainerClient.CreateIfNotExistsAsync throws exception if container exists #28549

### Expected behavior

Do not return an exception when the container exists

### Actual behavior

returns a 409

### Reproduction Steps

Use CreateifNotExists() on a blob container that already exists

**Comment by nickliu-msft** [comment]
Hi @rekhamoturislx, thanks for bringing this to our attention. I have attempted to replicate your scenario with the below test:


>         
        public async Task CreateIfNotExistsAsync_ContainerExists()
        {
            BlobServiceClient service = GetServiceClient_SharedKey();
            BlobContainerClient container = InstrumentClient(service.GetBlobContainerClient(GetNewContainerName()));
            // First time, creates the container
            Assert.DoesNotThrowAsync(async () => {
                await container.CreateIfNotExistsAsync();
            });

            Response<BlobContainerProperties> response0 = await container.GetPropertiesAsync();
            Assert.IsNotNull(response0.Value.ETag);

            // Second time, should not create container
            Assert.DoesNotThrowAsync(async () => {
                await container.CreateIfNotExistsAsync();
            });

            Response<BlobContainerProperties> response1 = await container.GetPropertiesAsync();
            Assert.IsNotNull(response1.Value.ETag);
            // validate new container not created
            Assert.AreEqual(response0.Value.ETag, response1.Value.ETag);

            // Cleanup
            await container.DeleteIfExistsAsync();
        }


and this is able to pass and not throw an exception when BlobContainerClient.CreateIfNotExistsAsync is called for a container that exists. I am not seeing the issue you are describing.

I know that you mentioned that you have upgraded Azure Storage blobs to the latest version but can you verify again? Also can you send a code snippet of your issue?

**Comment by nickliu-msft** [comment]
In fact looking at the implementation, no exception is thrown if ContainerAlreadyExist
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs/src/BlobContainerClient.cs#L1113

**Comment by nickliu-msft** [comment]
Closing due to no response. Please create another issue if it still persists
