### ISSUE TITLE
EventData Data property is null

### ISSUE THREAD

**Issue by ewancoder** [Azure/azure-sdk-for-net#43927]
### Library name and version

Azure.Messaging.EventHubs 5.10.0.0

### Query/Question

Hi, we have the following piece of code throwing NullReferenceExceptions suddenly in large amounts:

```
if (eventArgs.Data.Properties.ContainsKey(CommonConstants.EventType))
```

Judging from the code, the only thing that can be null there is Data property. I can see that in the XML documentation on that property there's a note:

```
Expected to be null if the receive call has timed out.
```

Could you please elaborate on this, what this means and what is `receive timeout` and how we can try to reproduce it? Or if you have any ideas why this might be happening it would be helpful.

**Comment by jsquire** [comment]
Hi @ewancoder.  This is known and intentional behavior when you set [EventProcessorOptions.MaximumWaitTime](https://learn.microsoft.com/dotnet/api/azure.messaging.eventhubs.eventprocessorclientoptions.maximumwaittime?view=azure-dotnet#azure-messaging-eventhubs-eventprocessorclientoptions-maximumwaittime).   This tells the processor to wait for that interval and when no events are available from that partition, emit an empty call to your handler.   This is often used by applications as a heartbeat mechanism to help detect when events are not flowing through the system.   

More discussion and context can be found in the [Event Processor Handlers sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs.Processor/samples/Sample03_EventProcessorHandlers.md#process-event).

**Comment by ewancoder** [comment]
Oh thanks, this seems to be the root cause indeed. Let me investigate a bit more in that direction and I'll get back to you.

**Comment by ewancoder** [comment]
So, in regards to the issue above, if we ignore all events that have null args.Data property, but are still processing the ones that have Data set, we aren't actually losing any data. The large amount of them just means that we have a short timeout set up and a lack of events in the hub, so a lot of empty "fake" events are being generated by the library but no real data is at risk. Right?

**Comment by jsquire** [comment]
> So, in regards to the issue above, if we ignore all events that have null args.Data property, but are still processing the ones that have Data set, we aren't actually losing any data. The large amount of them just means that we have a short timeout set up and a lack of events in the hub, so a lot of empty "fake" events are being generated by the library but no real data is at risk. Right?

Correct.   If you are not interested in receiving empty pings, I'd suggest setting the MaximumWaitTIme on the options to `null`.

**Comment by ewancoder** [comment]
Is there a possibility that after reading EventArgs.Data.Body.Span, the Data property becomes null and HasEvent becomes false? We encounter a very strange error that the Data property that was previously not null might be becoming null, after upgrading to .NET 8 (5.6.2.0 -> 5.10.0.0 version of EventHub library)

**Comment by jsquire** [comment]
The [ProcessEventArgs](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/src/Processor/ProcessEventArgs.cs) structure is not mutable; there's no way that the value of `Data` can change under normal circumstances.   For it to do so, you'd have to drop down to reflection and alter the private backing field.

**Comment by ewancoder** [comment]
Yeah I see, thanks. I'll keep digging then.

**Comment by ewancoder** [comment]
btw if we do use `MaximumWaitTime`, the empty event will come to **every** Partition, right? even if one instance of a service is handling multiple partitions, it will get called multiple times with different partitions

**Comment by jsquire** [comment]
> btw if we do use `MaximumWaitTime`, the empty event will come to **every** Partition, right? even if one instance of a service is handling multiple partitions, it will get called multiple times with different partitions

This is correct.   It applies to the processor itself and will impact any partitions owned by that processor instance.

**Comment by ewancoder** [comment]
Thanks for the help. I think we can close this as I think the issue was on our side after all.
