### ISSUE TITLE
Why is the AuthenticationEvents trigger not supported in the .NET Isolated Worker Process? 

### ISSUE THREAD

**Issue by SWarnberg** [Azure/azure-sdk-for-net#43924]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.AuthenticationEvents 1.0.0-beta.8

### Query/Question

Creating an Azure Function in isolated worker process is often preferred to have more control over .NET versions and other dependencies. What's the reason for this library not supporting it?

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the Azure Functions team maintains the worker packages needed for extensions to be used with the isolated model.   see: [#2449](https://github.com/Azure/azure-functions-dotnet-worker/issues/2449).
