### ISSUE TITLE
[BUG] NullReferenceException in Microsoft.Azure.Amqp 2.6.5

### ISSUE THREAD

**Issue by Chocanto** [Azure/azure-sdk-for-net#43929]
### Library name and version

Azure.Messaging.ServiceBus

### Describe the bug

Hi,

`Microsoft.Azure.Amqp` version 2.6.5 contains a bug that could throw an uncatched `NullReferenceException` in some circonstances.
This library was recently fixed and a new version was released: 2.6.6 (see https://github.com/Azure/azure-amqp/issues/258).

`Azure.Messaging.ServiceBus` is still using `Microsoft.Azure.Amqp` version 2.6.5. Would it be possible to use the latest, fixed, version of `Microsoft.Azure.Amqp` please?

Thank you,
Anthony

### Expected behavior

`Azure.Messaging.ServiceBus` does not crash with a `NullReferenceException`

### Actual behavior

`Azure.Messaging.ServiceBus` could crash with a `NullReferenceException` 

### Reproduction Steps

Normal useage of `Azure.Messaging.ServiceBus`

**Comment by jsquire** [comment]
Hi @Chocanto.  Thanks for the heads-up.  We'll bump the central version of the AMQP library and include v2.6.6 in our next release.  In the meantime, if you're impacted by the AMQP bug, I'd recommend taking a direct reference to `Microsoft.Azure.Amqp` v2.6.6 in your application, which will hoist the version used by the Service Bus package.

**Comment by Chocanto** [comment]
Perfect, thank you very much for your quick reply!

**Comment by jsquire** [comment]
Addressed by #43930.
