### ISSUE TITLE
ClientModel: Make RequestOptions.BufferResponse non-nullable

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#43932]
See discussion at https://github.com/Azure/azure-sdk-for-net/pull/43909#discussion_r1592995251

**Comment by m-nash** [comment]
@annelo-msft  based on the discussion you linked it sounds like the generator will by default let buffering be true for protocol.

What property in tsp will indicate that we should go against this default?

It also mentions that conveniences can "set the option however they want" which property in tsp will indicate which direction they want to go?

**Comment by KrzysztofCwalina** [comment]
@m-nash, there is no default for protocol methods that the generator needs to know about. Protocol methods take RequestOptions parameter, the parameter has a property called BufferResponse, and the value of this property will control whether buffering happens or not. This will happen insode the RequestOptions.Apply method, and so the generator does not need to do anything as it already calls Apply.
