### ISSUE TITLE
[FEATURE REQ] clientCertificateCredential to support x5c for Azure AD 

### ISSUE THREAD

**Issue by gaoyp830** [Azure/azure-sdk-for-net#43945]
### Library name

Microsoft.Extensions.Azure

### Please describe the feature.

In order for Azure function service bus trigger to support connection using Azure AD, the code snippet [here ](https://github.com/Azure/azure-sdk-for-net/blob/e20bf7380b9bf035d1a04270e39b0f660dc1e74e/sdk/extensions/Microsoft.Extensions.Azure/src/Internal/ClientFactory.cs#L200-L209)(which is used to generate token to be used in the creation of service bus client) needs to set `SendX5C ` to be `true` in the `options`. (https://learn.microsoft.com/en-us/dotnet/api/microsoft.identity.web.microsoftidentityoptions.sendx5c?view=msal-model-dotnet-latest)

**Comment by jsquire** [comment]
Hi @gaoyp830.  Thank you for reaching out and we regret that you are experiencing difficulties.   For your scenario, you'll need to override the default options by calling [UseCredential](https://learn.microsoft.com/dotnet/api/microsoft.extensions.azure.azureclientfactorybuilder.usecredential?view=azure-dotnet) as part of your DI registration.  This allows you to control credential creation and set the options desired for your specific needs.   

In this case, I believe you'll want to look at setting [ClientCertificateCredentialOptions.SendCertificateChain](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.clientcertificatecredentialoptions.sendcertificatechain?view=azure-dotnet#azure-identity-clientcertificatecredentialoptions-sendcertificatechain) and using that with a new instance of [ClientCertificateCredential](https://learn.microsoft.com/dotnet/api/azure.identity.clientcertificatecredential?view=azure-dotnet).   For example:

```csharp
services.AddAzureClients(clientBuilder =>
{
    var options = new ClientCertificateCredentialOptions { SendCertificateChain = true };
    var credential = new ClientCertificateCredential(options);
            
    // This will set the credential used by all Azure clients.
    clientBuilder.UseCredential(credential);
});
```

More context and discussion can be found in:

- [Dependency injection with the Azure SDK for .NET](https://learn.microsoft.com/dotnet/azure/sdk/dependency-injection?tabs=web-app-builder)
- [Azure.Identity Credentials overview](https://learn.microsoft.com/dotnet/api/overview/azure/identity-readme?view=azure-dotnet#key-concepts)

**Comment by gaoyp830** [comment]
Hi @jsquire, thanks for the information! from [Dependency injection with the Azure SDK for .NET](https://learn.microsoft.com/dotnet/azure/sdk/dependency-injection?tabs=web-app-builder), I see that in the example the client is passed in after registration using dependency injection:

` public MyApiController(BlobServiceClient blobServiceClient)
    {
        _blobServiceClient = blobServiceClient;
    }`
...however this example is the client code. I wonder in the case of using [service bus trigger](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-trigger?tabs=python-v2%2Cisolated-process%2Cnodejs-v4%2Cextensionv5&pivots=programming-language-csharp), registering the service bus client like you have mentioned above will also result in service bus trigger using the same client?

Thanks again for any help!

**Comment by jsquire** [comment]
The trigger uses the registered DI credential implicitly for the clients that perform its operations.  There's no difference for what you'd need to do.
