### ISSUE TITLE
DefaultAzureCredential VisualStudioCredential Requires Administrator Permissions on Developer Machine?

### ISSUE THREAD

**Issue by sguidos** [Azure/azure-sdk-for-net#43954]
### Library name and version

Azure Identity 1.11.2

### Query/Question

When using DefaultAzureCredential, the VisualStudioCredential failed when the user was not an Administrator on their development machine.  One of the developers was getting the error:
```
[Informational] Azure-Identity: VisualStudioCredential.GetToken invoked. Scopes: [ https://vault.azure.net/.default ] ParentRequestId: e5e1c1cc-8cc2-456b-b0cb-5d79754338e0
[Informational] Azure-Identity: VisualStudioCredential.GetToken was unable to retrieve an access token. Scopes: [ https://vault.azure.net/.default ] ParentRequestId: e5e1c1cc-8cc2-456b-b0cb-5d79754338e0 Exception: Azure.Identity.CredentialUnavailableException (0x80131500): Process "C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\CommonExtensions\Microsoft\Asal\TokenService\Microsoft.Asal.TokenService.exe" has failed to get access token in 30 seconds.

```
which was resolved when they were made a Local Admin on their machine (Visual Studio was apparently installed by the IT department and not the developer).  Or was the issue that they did not have permissions to the folder where ```Microsoft.Asal.TokenService.exe``` was located?  The requirement should be noted somewhere, to assist others in future troubleshooting, thanks.

### Environment

Windows 11, Visual Studio Pro 2022, .NET 6.0

**Comment by christothes** [comment]
Hi @sguidos - 
I'm not aware of any requirement by the `Microsoft.Asal.TokenService.exe` process for the user to be an admin. If you are able to reproduce this, what happens if you attempt to run the Microsoft.Asal.TokenService.exe directly, using the path from the error? 

Also, could you provide the version of Visual Studio you are running (from Help->About)?
