### ISSUE TITLE
Make all credential types mockable

### ISSUE THREAD

**Issue by scottaddie** [Azure/azure-sdk-for-net#43959]
While reading through https://github.com/Azure/azure-sdk-for-net/issues/20911, I noticed that only some credential types in the Azure Identity library expose protected, parameterless constructors and are therefore mockable. This is a tracking issue to update the affected credential types accordingly, to adhere to [Azure SDK for .NET mocking guidelines](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-mocking).

**Comment by jsquire** [comment]
@scottaddie:  Can you help us understand for what the scenarios are where mocking `TokenCredential` is not sufficient?   There's no API in any Azure SDK package that is credential based but does not take `TokenCredential`.

**Comment by scottaddie** [comment]
@jsquire We have customers who want to test code that didn't accept/use the `TokenCredential` abstraction and instead accepted the derived type. I linked to an issue in my original comment that shows an example.

My bigger concern is that we're inconsistent across credential types.

**Comment by jsquire** [comment]
To be clear, I'm not opposed to the requested change, just trying to understand the scenario.
