### ISSUE TITLE
[QUERY] How to create a SubscriptionProperties in unit tests?

### ISSUE THREAD

**Issue by wbuck** [Azure/azure-sdk-for-net#43998]
### Library name and version

Azure.Messaging.ServiceBus

### Query/Question

I was mocking the `ServiceBusAdministrationClient` and realized I'm not table to create/initialize the `SubscriptionProperties` `class`.
Both constructors defined for the `SubscriptionProperties` `class` are `internal`... 

Is there a factory function I can use in my unit tests?
Or could someone make the constructors `public` for the `SubscriptionProperties` `class`?

**Comment by JoshLove-msft** [comment]
Hi @wbuck,
You can use the [ServiceBusModelFactory](https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusmodelfactory.subscriptionproperties?view=azure-dotnet) to create an instance of SubscriptionProperties.
