### ISSUE TITLE
How to retrieve runbook job

### ISSUE THREAD

**Issue by MortenMeisler** [Azure/azure-sdk-for-net#4399]
Should be as simple as this right?

```
//Get job by jobname (which is the jobId)
var job = client.Job.Get("my resource group name", "my automation account name", "38ff75c2-d4ca-471f-b4a5-2a98da4d252b");
```

I'm getting error: 
1/2:
JsonSerializationException: Error converting value "Succeeded" to type 'Microsoft.Azure.Management.Automation.Models.JobProvisioningStateProperty'. Path 'properties.provisioningState', line 1, position 427

2/2:
ArgumentException: Could not cast or convert from System.String to Microsoft.Azure.Management.Automation.Models.JobProvisioningStateProperty.

This one works fine:
`var jobs = client.Job.ListByAutomationAccount(resourceGroup, automationAccount);`

And from that list of jobs I can check the names

What is the syntax here? any examples?

Thanks

Using preview version 3.0.3 (which was the least painfull to get authenticated with :)).

**Comment by drizzlelabs** [comment]
I'm getting the same error when using Job.Create and Job.CreateAsync:

Newtonsoft.Json.JsonSerializationException: Error converting value "Processing" to type 'Microsoft.Azure.Management.Automation.Models.JobProvisioningStateProperty'. Path 'properties.provisioningState', line 1, position 431.

Looking through the code, I see that those status' are missing in 'Models/ProvisioningState.cs'. I'll clone the repo, make the changes, and see if it works.

**Comment by dsgouda** [comment]
Closing this in favor of https://github.com/Azure/azure-rest-api-specs/issues/3181
