### ISSUE TITLE
Deployment failed; but get RequestFailedException with bad response message

### ISSUE THREAD

**Issue by xula2018** [Azure/azure-sdk-for-net#44008]
### Library name and version

Azure.Core 1.39.0
Azure.ResourceManager 1.11.1
Azure.ResourceManager.Resources 1.7.2

### Describe the bug

Try to create a spot VM using template deployment, it failed due to low spot price. In Azure activity log, it shows the reason as "
Unable to perform operation 'Create VM' since the provided max price '0.001 USD' is lower than the current spot price '0.0113 USD' for Azure Spot VM size 'Standard_D2ds_v5'.".

However in the exception message from SDK, it says:
"Azure.RequestFailedException: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.
Status: 200 (OK)
ErrorCode: DeploymentFailed

Service request succeeded. Response content and headers are not included to avoid logging sensitive data."

Why doesn't it include the actual failure message?

### Expected behavior

Previously we get exception with message like:

Azure.RequestFailedException: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.
Status: 200 (OK)
ErrorCode: DeploymentFailed

Content:
{"status":"Failed","error":{"code":"DeploymentFailed","target":"/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Resources/deployments/xxx","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"OperationNotAllowed","message":"Unable to perform operation 'Create VM' since the provided max price '0.001 USD' is lower than the current spot price '0.0113 USD' for Azure Spot VM size 'Standard_D2ds_v5'. For more information, see http://aka.ms/AzureSpot/errormessages."}]}}

### Actual behavior

With Azure.Core 1.39.0, we get:

Azure.RequestFailedException: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.
Status: 200 (OK)
ErrorCode: DeploymentFailed

Service request succeeded. Response content and headers are not included to avoid logging sensitive data.

### Reproduction Steps

at Azure.Core.OperationInternal`1.GetResponseFromState(OperationState`1 state)
   at Azure.Core.OperationInternal`1.<UpdateStatusAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Core.OperationInternalBase.<UpdateStatusAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Azure.Core.OperationPoller.<WaitForCompletionAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Operation.<WaitForCompletionResponseAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Citrix.AzureFacade.AzureResourceManager.ClientWrappers.LongRunningOperationExtensions.<LroWaitForCompletionResponseAsync>d__0.MoveNext()

**Comment by jsquire** [comment]
Hi @xula2018.  Thanks for reaching out and we regret that you're experiencing difficulties.   In order to triage this to the right folks to assist, I'll need you to tell me the Azure SDK package and version that you're using.   Azure.Core is an infrastructure library that provides network operations for the Azure SDK, not something that you would use directly in your application.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by xula2018** [comment]
> Hi @xula2018. Thanks for reaching out and we regret that you're experiencing difficulties. In order to triage this to the right folks to assist, I'll need you to tell me the Azure SDK package and version that you're using. Azure.Core is an infrastructure library that provides network operations for the Azure SDK, not something that you would use directly in your application.

FYI, I added the SDK package and version to the ticket. 

- Azure.ResourceManager 1.11.1

- Azure.ResourceManager.Resources 1.7.2

**Comment by HarveyLink** [comment]
Hi @xula2018 , the error message change is by design, please check: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/CHANGELOG.md#other-changes-2

**Comment by xula2018** [comment]
Hi HerveyLink, Thank you for looking into this issue.  In this case, the deployment failed, shouldn't response.IsError be false? 

https://github.com/Azure/azure-sdk-for-net/blob/e6ce9f34d2927bb34aa459c9df542d88817ad890/sdk/core/Azure.Core/src/RequestFailedException.cs#L175

> Hi @xula2018 , the error message change is by design, please check: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/CHANGELOG.md#other-changes-2

**Comment by HarveyLink** [comment]
> > Hi @xula2018 , the error message change is by design, please check: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/CHANGELOG.md#other-changes-2
> 
> Hi HerveyLink, Thank you for looking into this issue. In this case, the deployment failed, shouldn't response.IsError be false?
> 
> https://github.com/Azure/azure-sdk-for-net/blob/e6ce9f34d2927bb34aa459c9df542d88817ad890/sdk/core/Azure.Core/src/RequestFailedException.cs#L175

Well, in that case, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) to get further help.

**Comment by wsugarman** [comment]
@HarveyLink - To reiterate an earlier question: should this behavior be the one observed? I understand not wanting to perhaps expose sensitive information in logs from successful requests, but it looks like a bug that ARM is returning 200s for unsuccessful requests such that the client throws `RequestFailedException`.

I am seeing this behavior as well. For example, I received a `200 (OK)` from ARM but with this (redacted) body that complained about a missing delegated resource.
```json
{
  "status": "Failed",
  "error": {
    "code": "DeploymentFailed",
    "target": "***",
    "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.",
    "details": [
      {
        "code": "FailedIdentityOperation",
        "message": "Identity operation for resource '***' failed with error 'Failed to perform resource identity operation. Status: 'BadRequest'. Response: '{\"error\":{\"code\":\"AzureResourceNotFound\",\"message\":\"Delegated resource with internal id '***' was not found.\"}}'.'."
      }
    ]
  }
}
```

I had to write custom code in order to see this message in the logs because `Response.IsError` returned `false`.

**Comment by wsugarman** [comment]
I think I better understand that the fetching of the status was successful, but the operation whose status was fetched failed. I'll create a separate issue to discuss this.
