### ISSUE TITLE
[BUG] Update status changes to "In Progress" sometime after "Succeeded".

### ISSUE THREAD

**Issue by mahdighorbanpourptw** [Azure/azure-sdk-for-net#44002]
### Library name and version

Azure.IoT.DeviceUpdate 1.0.0

### Describe the bug

I have an update script which is a copy of the sample scripts and some changes to adapt it to our needs. The update works perfectly fine. The state changes from not running, in progress, succeeded. Then after a while, it changes back to In Progress. I looked at the update agent logs and there, the condition check works perfectly fine, and the update is not triggered twice! Note that, when I restart the agent, it immediately shows "Succeeded". Then the same issue, after some time, goes back to in progress. 
having said, the IotHub portal, updates, update-group overview, showing inconsistent data. The first two devices, are already updated successfully, which on the upper side info box, shows correctly. But in the lower side, all of them are shown "In Progress". The third device in the list is even turned off! 
![image](https://github.com/Azure/azure-sdk-for-net/assets/97948692/c3913de5-ccca-4ff1-858a-cd9d7add4faa)

You could also see that, in the twin, it says applied.

![image](https://github.com/Azure/azure-sdk-for-net/assets/97948692/e5f70aa6-f017-40b5-af72-47affed26546)

### Expected behavior

The first two devices should keep showing the state "Succeeded". And the last one, should be "Not Running"

### Actual behavior

All the devices are shown "In Progress". 

### Reproduction Steps

Use the example scripts to create an update. Assign it to the devices.

### Environment

Ubuntu 22.04
IotEdge 1.4.39
DeviceIpdate-Agent 1.1.0

**Comment by jsquire** [comment]
Hi @mahdighorbanpourptw.  Thank you for reaching out and we regret that you're experiencing difficulties.  If I understand correctly, the behavior that you're inquiring about is the status displated in the IoT Hub portal.  Unfortunately, this is not an area that the maintainers of the Azure SDK packages can assist with.  

To ensure that the right team has visibility and can help, your best path forward for would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) or inquire on the [Microsoft Q&A site](https://learn.microsoft.com/answers/questions/).   For feature suggestions, you may also want to consider the [Azure Feedback site](https://feedback.azure.com/d365community).

I'm going to close this out; if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.
