### ISSUE TITLE
Improve message for TaskCanceled exception

### ISSUE THREAD

**Issue by shahabhijeet** [Azure/azure-sdk-for-net#4402]
- Handle retries for timeout.
- explore the possibility to add default retry policy across clients.
- Improve TaskCanceled exception that results due to timeout

Cost: 4 days (stretch)

**Comment by mikeblakeuk** [comment]
+1

**Comment by shahabhijeet** [comment]
Unable to accomodate this feature in this sprint. Pushing to next sprint

**Comment by hales8181** [comment]
+1

**Comment by jsquire** [comment]
Management pipelines have changed since this issue was filed.   Closing.   

//fyi: @ArthurMa1978 - please feel free to reopen if this is still needed.
