### ISSUE TITLE
Azure.Monitor.OpenTelemetry.AspNetCore.Internals.AzureSdkCompat.AzureEventSourceLogForwarder double formats event messages

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#44028]
https://github.com/Azure/azure-sdk-for-net/blob/c4418cd3e85f2e01a92b702414244647ff3695df/sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/src/Internals/AzureSdkCompat/AzureEventSourceLogForwarder.cs#L70

calls `LogEvent`, but ignores the formatted string coming from the `s` parameter.

`LogEvent` then calls _formatMessage here:
https://github.com/Azure/azure-sdk-for-net/blob/c4418cd3e85f2e01a92b702414244647ff3695df/sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/src/Internals/AzureSdkCompat/AzureEventSourceLogForwarder.cs#L34

which is defined as:
https://github.com/Azure/azure-sdk-for-net/blob/c4418cd3e85f2e01a92b702414244647ff3695df/sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/src/Internals/AzureSdkCompat/AzureEventSourceLogForwarder.cs#L64

Then `EventSource.Format()` calls:
https://github.com/Azure/azure-sdk-for-net/blob/2a0e020ae9348cb31af769027efd6b1491595a9d/sdk/core/Azure.Core/src/Shared/EventSourceEvent.cs#L58

This seems to effectively calls `EventSourceEventFormatting.Format` twice.

(related to https://github.com/Azure/azure-sdk-for-net/pull/43947#issuecomment-2111253949)

**Comment by TimothyMothra** [comment]
@christothes can this be closed? I see the PR was abandoned.
