### ISSUE TITLE
Microsoft.Asal.TokenService.exe has failed with unexpected error

### ISSUE THREAD

**Issue by linhu2020** [Azure/azure-sdk-for-net#44034]
### Library name and version

Microsoft.Azure.Cosmos

### Query/Question

I am using Managed Identity to access cosmosDB. Here is the sample code: ```
var credential = new DefaultAzureCredential();
var client = new CosmosClient("https://docdb-rc-int.documents.azure.com:443/", credential);
var database = client.GetDatabase("feeds");
var container = database.GetContainer("botuser");

QueryDefinition queryDefinition = new QueryDefinition("SELECT * from C");
await container.CreateItemAsync(new BotUser
{
	TenantId = new Guid("266b4b2e-33d0-48f5-a39a-63846c927ae2"),
	BotId = "dac4b741-9444-489a-a3a6-8f72aae621e2",
	ConversationId = "11adf10b-9c12-437b-ad97-0a740947d773",
	EncryptedConversationId = "a:14NsKXq4HZO_ZxwfffYUhdWrDt2XVcljtaaz-Ys9ZYNoGy2ZsBj7zVuMlSDMCh5PDDyfS31sb_1gPt6WUnJHGV3Vq1IK0wTXrqRYnHVlcr696yaVeZ10mNiOnkrJbdkol",
	ServiceUrl = "https://smba.trafficmanager.net/amer/",
	Email = "lihu1@microsoft.com",
	CreateAt = DateTime.UtcNow.Microsecond,
	UpdateAt = DateTime.UtcNow.Microsecond,
});```

I already assigned the write role to my AAD user and already login in the Azure Authentication Service of Visual Studio. But I still got the below error: Process "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\Extensions\ecawnuz4.qsn\TokenService\Microsoft.Asal.TokenService.exe" has failed with unexpected error: TS003: Error, TS005: No accounts found. Please go to Tools->Options->Azure Services Authentication, and add an account to be to authenticate to Azure services during development..  How can I resolve this issue?
![image](https://github.com/Azure/azure-sdk-for-net/assets/132728542/dbf7f470-b2f0-405d-a967-fe3bd7d7dcbd)

**Comment by christothes** [comment]
Hi @linhu2020 - 
`Microsoft.Asal.TokenService.exe` is owned by Visual Studio, so you may need to report this error via the [reporting link](https://developercommunity.visualstudio.com/VisualStudio/report). 

However, in the meantime I would suggest trying the following:
- Sign out and sign back in your account
- Update your version of Visual Studio (it appears you are on 2019)

**Comment by christothes** [comment]
I'm afraid I don't have any additional suggestions.
