### ISSUE TITLE
[QUERY] How to create a blob client using EntraAppIds with Federated credentials?

### ISSUE THREAD

**Issue by eddynaka** [Azure/azure-sdk-for-net#44063]
### Library name and version

Azure.Storage.Blob

### Query/Question

Hello!

Given an Azure Entra App Id with federated credentials, how do I properly create it and use it to connect into AzureStorage accounts to successfully create a blobclient?

I tried to use the DefaultAzureCredentials with the ClientId from my app, but I'm not sure if my issuer was right, since I didn't find any documentation.

**Comment by eddynaka** [comment]
Hello @christothes ,

Since there is not much documentation available, here is what I did:
1. Created an Entra App
2. Created a federated credential with the following options: `Other`, `Issuer=https://[Instance]/[Domain]/{TenantId}/v2.0/`, `Subject=AppId`
3. Gave Blob Owner permission to the entra app
4. Tried to create using DefaultAzureCredentials with the ClientId to authenticate to the blob

Given those steps, it fails with either issuer not found or unauthorized.
I also tried to use MSAL but didn't work as well.

**Comment by christothes** [comment]
What is the issuer you are using for the federated credential? That issuer should have the details for you to fill in. 

Regarding documentation - here are the general docs for configuring this - https://learn.microsoft.com/en-us/entra/workload-id/workload-identity-federation
