### ISSUE TITLE
Cloud Service project uses incorrect .Net Standard package references

### ISSUE THREAD

**Issue by cvellan** [Azure/azure-sdk-for-net#4408]
I have been attempting to implement a cloud service project with dependencies targeting .Net Standard. At the moment, the project only contains a .Net Standard library and a worker role, which has been configured to use the PackageReference style of Nuget package restoration as described [here](https://www.hanselman.com/blog/ReferencingNETStandardAssembliesFromBothNETCoreAndNETFramework.aspx) in order to automatically copy the library's dependencies.

Upon running the project locally, a BadImageFormatException exception is thrown from the .Net Standard library when attempting to instantiate an object from a specific Nuget package. The error is as follows:

```System.BadImageFormatException: Could not load file or assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)```

System.Memory is a dependency of the Nuget package being referenced, and is being copied to the cloud project's debug folder as a "reference" assembly. The same .dll present in the worker role's binary folder appears to be the correct copy of the full assembly.

The problem also occurs if the .Net Standard library is replaced by one targeting the .Net Framework, if the worker role still uses the PackageReference style. Changing back to the packages.config system corrects the issue. A minimal reproduction is possible by adding System.Memory from Nuget directly to the worker role and attempting to reference anything from it (again, using PackageReference).

Is there anything that needs to be done to tell the Cloud Service project how to resolve .Net Standard dependencies using PackageReference?

**Comment by shahabhijeet** [comment]
@cvellan this is azure .NET SDK repo.
Before I redirect you to file this issue with different team, I just want to make sure I understand your scenario.
So can you describe your scenario that I repo.
Please provide with your repro steps.

**Comment by DarthVella** [comment]
Hi, and thanks in advance! I couldn't find a more appropriate Github repository for this issue, but I'd much appreciate being redirected if there is one.

The steps for a minimal reproduction are as follows; and a project created following these steps is attached to this comment. I am using Visual Studio 2017 Enterprise Edition and the .Net Framework 4.6.1.

1. Create a new Azure Cloud Service Project, under Templates > Visual C# > Cloud.
2. When prompted to add roles to the solution, add a single worker role.
3. Unload the worker role project from the solution and open the project file for editing.
4. In the first PropertyGroup tag, add the tag
```xml
<RestoreProjectStyle>PackageReference</RestoreProjectStyle>
```
5. Save the project file, and re-load the project into the solution.
6. Using the Nuget Package Manager, add a dependency on System.Memory to the worker role.
7. Debug the cloud project locally to confirm that there are no issues.
8. At the end of the worker role's Run method, insert the line
```csharp
 Span<int> memorySpan = new Span<int>();
```
9. Debug the cloud project locally and confirm that an unhandled exception of type System.BadImageFormatException is thrown.
[AzureCloudService1.zip](https://github.com/Azure/azure-sdk-for-net/files/2121993/AzureCloudService1.zip)

**Comment by shahabhijeet** [comment]
@cvellan thanks for the repro steps. I just wanted to make sure this is related to VS tools for Azure, which it is from your repro steps.

Can you send this via VS feedback.
VS --> Help --> Send Feedback -->Report a problem
Please provide the similar repro. This will get routed to Visual Tools for Azure team.

Closing this issue.

**Comment by tullo-x86** [comment]
...and so, the trail went cold.

**Comment by cvellan** [comment]
Ah, sorry mate. The issue was posted [here](https://developercommunity.visualstudio.com/content/problem/280697/cloud-service-project-uses-incorrect-net-standard.html), which directed me to post a UserVoice issue [here](https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/34742794-support-the-packagereference-nuget-restoration-opt). Nothing has come of it so far, unfortunately.

**Comment by tullo-x86** [comment]
It's not your fault. Azure Cloud Services are now a "classic" offering, which appears to be the Microsoft terminology for "we aren't deprecating this, but we aren't maintaining it either; have fun".

I got around this by simply removing the binding redirect for the assembly it was complaining about (`System.Runtime` in my case), then repeating this for each new assembly the error popped up for, until the application finally started.

**Comment by dmytro-gokun** [comment]
Ideally, I'd also like to run it on .NET Core 2.2 :)
I know i can have a VM etc., but i'd like to have something more like PaaS-y :)
