### ISSUE TITLE
ApplicationPublishObject missing subscription-key

### ISSUE THREAD

**Issue by venkatesh-bhupathi** [Azure/azure-sdk-for-net#4409]
Hi,
We are able to associate the Subscription Key from Azure Portal with LUIS app through Publish Settings in Luis.ai portal,

We see that API is accepting the following JSON, {
  "endpointUrl": "DummyUrl",
  "subscription-key": "DummyEndpointKey",
  "endpointRegion": "westus",
  "isStaging": false
}

However programmatic client code does not have the subscription-key property. Can you please let us know the ETA for adding this missing property in the client?

**Comment by rozele** [comment]
+1

**Comment by kayousef** [comment]
@venkatesh-bhupathi 

LUIS does not store the subscription keys for security and compliance reasons. It's the responsibilty of the user to maintain the subscription key.
Can you describe the scenario you need to retrieve the subscription key for?

**Comment by cahann** [comment]
#please-close

**Comment by jsquire** [comment]
Closing this out as there has been no recent engagement.  Please feel free to reopen or file a new issue if this remains a problem with the current version of the library.
