### ISSUE TITLE
[FEATURE REQ] Assistant V2

### ISSUE THREAD

**Issue by FrontFelix** [Azure/azure-sdk-for-net#44104]
### Library name

AssistantsClient.cs

### Please describe the feature.

I am currently trying to use the Assistant v2 API. However, in the code, there is a line:
`request.Headers.Add("OpenAI-Beta", "assistants=v1");`

I couldn't find any documentation or option to change this to v2. For my use case, I need to use Assistant v2. It would be great if you could implement this feature!

-     Add support for specifying the version of the Assistant API in the request headers.
-     Allow changing the version from v1 to v2 as needed.

**Comment by samuelnygaard** [comment]
This feature would be really useful, I can create a PR if that is helpful @jsquire ?

**Comment by jsquire** [comment]
@samuelnygaard :  We appreciate your kind offer to contribute, but I'm not the owner of this package, so I'm unable to say whether or not the OpenAI team would be amenable.   We'd need @trrwilson and team to offer their thoughts.

**Comment by FrontFelix** [comment]
Any update on this ?

**Comment by scottaddie** [comment]
The Assistants v2 API is fully supported in the [official OpenAI library for .NET](https://devblogs.microsoft.com/dotnet/openai-dotnet-library/) and in its Azure.AI.OpenAI v2.0.0 Beta companion library.
