### ISSUE TITLE
[Storage] Mismatch in docs and code behaviour

### ISSUE THREAD

**Issue by WynieCronje** [Azure/azure-sdk-for-net#44150]
Hi @orhanmaden 

I believe I found the issue:
```
  var credential = new DefaultAzureCredential();
  var containerUri = new Uri($"https://{accountName}.blob.core.windows.net/{containerName}/");
  var blobServiceClient = new BlobServiceClient(containerUri, credential);
  var containerClient = blobServiceClient.GetBlobContainerClient(containerName);
```
It looks like you are trying to use the containerUri as the Uri for the Blob Service.

I'd recommend trying this instead:
```
  var credential = new DefaultAzureCredential();
  var serviceUri = new Uri($"https://{accountName}.blob.core.windows.net");
  var blobServiceClient = new BlobServiceClient(serviceUri, credential);
  var containerClient = blobServiceClient.GetBlobContainerClient(containerName);
```

-Sean

_Originally posted by @seanmcc-msft in https://github.com/Azure/azure-sdk-for-net/issues/13411#issuecomment-657707295_

**Comment by WynieCronje** [comment]
From the above comment in another issue. 

There is a mismatch between the code behavior and documentation.

The [documentation](https://learn.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.blobserviceclient?view=azure-python#parameters) states that any reference to a container or blob will be ignored:
![image](https://github.com/Azure/azure-sdk-for-net/assets/4537265/2f87dc0e-d55e-4feb-82f7-2bb8d283ab66)

But the code throws an exception: `InvalidUri -> The requested URI does not represent any resource on the server`

**Comment by nickliu-msft** [comment]
Hi thanks for bringing this to our attention. The documentation that you provided seems to be for the Python SDK. As such, please submit an issue in the Python GitHub: https://github.com/Azure/azure-sdk-for-python
