### ISSUE TITLE
[BUG] Fails to find existing Host resource in a Resource Group

### ISSUE THREAD

**Issue by AlexLsh** [Azure/azure-sdk-for-net#44157]
### Library name and version

Azure.ResourceManager.Maintenance v1.1.2

### Describe the bug

It appears that the call to `CreateOrUpdateConfigurationAssignmentAsync()` behaves differently based on whether the resource type (as passed to that call) has parent/child resource types, like: 
"hostGroups/hosts" or when there's just a resource type name, like:
"virtualMachines" 

For the virtual machine resource, when there's a resource missing (like a virtual machine not present in a RG), the error message would be:
```The Resource 'Microsoft.Compute/virtualMachines/maintenanceconfigurationtest' under resource group 'fsavs3wcus-rupatro-mgmt' was not found.```
Note the resource name looks like expected: **Provider/Type/name**.

For the host resource, in the scenario when the required resource was actually present in an RG, the error message was:
```The Resource 'Microsoft.Compute/hostGroups/hosts' under resource group 'fsavs3wcus-vis-proto-mgmt' was not found.```
Note that the resource name (**esx-1**) is _not_ present in the error message. 

It looks like `CreateOrUpdateConfigurationAssignmentAsync()` fails to understand, that 'Microsoft.Compute/hostGroups/hosts' is not a full resource name. And, when it tries to lookup with 'Microsoft.Compute/hostGroups/hosts' the resoource whose name is actually 'Microsoft.Compute/hostGroups/hosts/esx-1', it of course fails.  

### Expected behavior

When called to add an existing Host resource the function should add it to the MC, just as `New-AzConfigurationAssignment` does.
I was able to verify that the `New-AzConfigurationAssignment`  would add the Hosts to the MCs in the resource groups, where `CreateOrUpdateConfigurationAssignmentAsync()` as describe above.

### Actual behavior

As describe above, `CreateOrUpdateConfigurationAssignmentAsync()` fails to add exisring Host to existing Maintenance Configuration (MC).

### Reproduction Steps

1. In a Resource Group, create a Host group, with at least one Host.
2. Create Maintenance Configuration in the Resource Group.
3. Try to add the host (from the above Host Group), to the MC from step 2.4
4. It will succeed from Portal web UI, it would succeed with `New-AzConfigurationAssignment`, and  `CreateOrUpdateConfigurationAssignmentAsync()` would fail as described in the Bug Description Section.

### Environment

An Azure Subscription.

**Comment by HarveyLink** [comment]
Hi @AlexLsh , Thank you for using Azure SDK for .Net.
I can't 100% go through your scenaro since we don' have much domain knowledge on a specific service. However, the usage of this method should looks like:
```await resourceGroup.CreateOrUpdateConfigurationAssignmentAsync("Microsoft.Compute", "hostGroups/hostGroupName/hosts", "hostName", "resultName", data)```
I can't get further beacuse the service returns region not supported error, but there should avoid the Not Found error thrown.
