### ISSUE TITLE
ARM Question RE: Channel Registration via Microsoft.Azure.Management.BotService SDK

### ISSUE THREAD

**Issue by MickH3** [Azure/azure-sdk-for-net#4415]
I’m using the 0.9.1 preview to add the Teams Channel programmatically and while I get a 500 error, it still technically adds the channel.  Unfortunately, I get the same error when trying to add DirectLine but it does not add the Direct Line channel.  I have tried both using the NuGet package classes and the direct PATCH call to …/providers/Microsoft.BotService/botServices/…

The error I get is always the following…

An unexpected error occurred. Exception: 'System.NullReferenceException: Object reference not set to an instance of an object.
   at Intercom.ResourceProvider.DataProviders.ChannelResourceDataProvider.<ReplaceResourceAsync>d__5.MoveNext()'.

Maybe there is an optional parameter I am not providing that I need to provide?  Or maybe a bug in the underlying API for channel management?

Thanks!

**Comment by adrianhall** [comment]
Hi Mick,
My apologies for this sitting for so long.  Is this still a problem for you?

**Comment by MickH3** [comment]
Hi Adrian, I was able to work around it but it's been a while.  Something to the effect of DirectLine being a channel that already exists in a new Azure Bot Registration and not needing to be added like the Teams channel.  I think once I queried for the default key it would 'enable' it.  We aren't using this anymore, so I cannot remember the specifics.  

Thanks again for getting back to me!

Mick

**Comment by adrianhall** [comment]
I appreciate the confirmation.  We're trying to get better at responding.  Unfortunately, there is a large backlog of "old issues" that fell through the cracks.  Let us know (by opening a new issue) if you bump into anything new.
