### ISSUE TITLE
[BUG] ArmAppServiceModelFactory is not contained in the Azure.ResourceManager.AppService nuget package

### ISSUE THREAD

**Issue by skylog** [Azure/azure-sdk-for-net#44152]
### Library name and version

Azure.ResourceManager.AppService 1.0.2

### Describe the bug

ArmAppServiceModelFactory extension methods cannot be used

### Expected behavior

I expected to see the ArmAppServiceModelFactory class in the Azure.ResourceManager.AppService 1.0.2 nuget package to take advantage of the extension methods.

I hope that ArmAppServiceModelFactory extension methods will be available in the Azure.ResourceManager.AppService nuget package.

### Actual behavior

I can not use ArmAppServiceModelFactory in the Azure.ResourceManager.AppService 1.0.2, file is not included in the assembly and the required dll is missing 

### Reproduction Steps

Install nuget package  Azure.ResourceManager.AppService 1.0.2, and try to use any extension method from [ArmAppServiceModelFactory](https://github.com/Azure/azure-sdk-for-net/blob/17cf6490b983b169f9ee1a550faa9eb96c93d87e/sdk/websites/Azure.ResourceManager.AppService/src/Generated/ArmAppServiceModelFactory.cs#L1378C13-L1412C52) (sdk/websites/Azure.ResourceManager.AppService/src/Generated/ArmAppServiceModelFactory.cs)

**Comment by HarveyLink** [comment]
Hi @skylog , thank you for using Azure SDK for .NET.
The mock for extension only available from 1.1.0-beta.4 , please try this version or any later ones.
