### ISSUE TITLE
[FEATURE REQ] Add keys operation to Azure.ResourceManager.KeyVault

### ISSUE THREAD

**Issue by Muszkal** [Azure/azure-sdk-for-net#44151]
### Library name

Azure.ResourceManager.KeyVault

### Please describe the feature.

In version 1.0.0-beta.8 of the library, there were keys operations such as GetKeyVaultKeys and GetVaultKeyAsync on the vault resource.

They disappeared in version 1.0.0 and after.

Why is that and is there timeline to bring them back?

**Comment by HarveyLink** [comment]
Hi @Muszkal We'll release a new version contians those APIs. Will comment this issue once we have the PR ready

**Comment by ArthurMa1978** [comment]
The KeyVaultKey operations are part of [Azure.Security.KeyVault.Keys](https://www.nuget.org/packages/Azure.Security.KeyVault.Keys) lib, not in this management plane SDK.
