### ISSUE TITLE
[BUG] Activity.Tags not exported to customDimensions 

### ISSUE THREAD

**Issue by cataggar** [Azure/azure-sdk-for-net#44163]
### Library name and version

Azure.Monitor.OpenTelemetry.Exporter 1.1.0

### Describe the bug

I set Activity tags and they do not show up in `customDimensions` as expected.

May be related issues:
- #40951
- #35487

### Expected behavior

If the dimensions are not mapped to specific columns, they are added to `customDimensions`.

### Actual behavior

A `_MS.ProcessedByMetricExtractors` dimension is being set.

### Reproduction Steps

This console exporter shows this trace:
```
Activity.TraceId:            bc9e1a52fee636e944a3a95712baa577
Activity.SpanId:             a6e5d5e3f87f185b
Activity.TraceFlags:         Recorded
Activity.ActivitySourceName: Conveyor
Activity.DisplayName:        GET /v1/skus/privateClouds
Activity.Kind:               Server
Activity.StartTime:          2024-05-20T23:30:17.7765957Z
Activity.Duration:           00:00:00.5667895
Activity.Tags:
    url.full: http://0.0.0.0:8080/v1/skus/privateClouds
    http.response.status_code: 200
StatusCode: Ok
Resource associated with Activity:
    telemetry.sdk.name: opentelemetry
    telemetry.sdk.language: dotnet
    telemetry.sdk.version: 1.6.0
    service.name: unknown_service:ConveyorHost
```

I can query with KQL:
```
let traceId = 'bc9e1a52fee636e944a3a95712baa577';
let spanId = 'a6e5d5e3f87f185b';
requests
| where operation_Id == traceId
| where id == spanId
| project name, customDimensions, resultCode
```

Output:
- name: GET /v1/skus/privateClouds
- customDimensions: {"_MS.ProcessedByMetricExtractors":"(Name: X,Ver:'1.1')"}
- resultCode: 0

![image](https://github.com/Azure/azure-sdk-for-net/assets/87583576/da676e69-9fe2-401d-874a-14305562a21b)

**Comment by cataggar** [comment]
A related question is how do I set these two values using OpenTelemetry?

![image](https://github.com/Azure/azure-sdk-for-net/assets/87583576/3c2e3f75-42b7-403d-8152-6a5ae33ea708)

**Comment by cijothomas** [comment]
> May be related issues:
> 
> https://github.com/Azure/azure-sdk-for-net/issues/40951
> https://github.com/Azure/azure-sdk-for-net/issues/35487

They are specifically about Resource attributes not being stored into Telemetry tables' customDimensions. 

In your case, you are referring to Activity.Tags, right? The following?
```
Activity.Tags:
    url.full: http://0.0.0.0:8080/v1/skus/privateClouds
    http.response.status_code: 200
```

url.full could be mapped into RequestTelemetry.url - can you check there?
http.response.status_code could be mapped into RequestTelemetry.responseCode. can you check?

Can you share a minimal repro app?

**Comment by cataggar** [comment]
It looks like custom properties are indeed set. I was able to set the response code by making sure the value was an int. I did not have luck with `url.full`, but the older `http.url` worked only when I set `http.method`. What still confuses me is why doesn't `http.user_agent` show up? Here is the minimal repo: https://github.com/cataggar/net44163/blob/365f16210827e7b3edf093d7a0fae8d9338f63de/Program.cs

```
Activity.TraceId:            4d66de24e6e9c1df6de90727b00423fa
Activity.SpanId:             f44710ae4a38ae80
Activity.TraceFlags:         Recorded
Activity.ActivitySourceName: bug44163
Activity.DisplayName:        main
Activity.Kind:               Server
Activity.StartTime:          2024-05-21T15:27:05.9271900Z
Activity.Duration:           00:00:00.0006631
Activity.Tags:
    customTag: customValue
    abc: def
    http.user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0
    http.newconvetiontag: special value
    http.method: GET
    http.url: http://0.0.0.0:8080/v1/skus/privateClouds
    http.status_code: 202
Resource associated with Activity:
    telemetry.sdk.name: opentelemetry
    telemetry.sdk.language: dotnet
    telemetry.sdk.version: 1.8.1
    service.name: unknown_service:net44163
```    

![image](https://github.com/Azure/azure-sdk-for-net/assets/87583576/bb88a8a5-b817-473f-ab5f-946b2db3399c)

**Comment by cataggar** [comment]
I see. In the case of `http.user_agent`, I see `client_Browser` `Firefox 72.0`. Is there no way to get the original value. May be just create a custom attirbute?

**Comment by cijothomas** [comment]
```csharp
using Activity? activity = activitySource.CreateActivity("main", ActivityKind.Server);
activity?.Start();
activity?.SetTag("customTag", "customValue");  // should land in custom properties, and is working as expected.
activity?.SetTag("abc", "def"); // should land in custom properties, and is working as expected.
activity?.SetTag("http.user_agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0");  // original value is lost, but a derived value is used to populate client_browser.
activity?.SetTag("http.newconvetiontag", "special value"); // should land in custom properties, and is working as expected.

// older tag conventions
activity?.SetTag("http.method", "GET");  // See below
activity?.SetTag("http.url", "http://0.0.0.0:8080/v1/skus/privateClouds"); // method and url are forming the name
activity?.SetTag("http.status_code", 202); // must be an int, not a string - @rajkumar-rangaraj - is this by design to ignore non-int??
```

Left comments in above. It looks like some doc improvements are required to explain how the exporter maps tags to AppInsights concepts.
