### ISSUE TITLE
Create an interface `IJsonModel` in `System.ClientModel` library

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/azure-sdk-for-net#44168]
The interface should look like:
```csharp
public interface IJsonModel
{
    // when the model explicitly defines additional properties in the spec, this method should be implemented normally
	// when the model does not define additional properties in the spec, this method should be explicitly implemented
	IDictionary<string, BinaryData> AdditionalProperties {get;}
	// always explicitly implemented, or we do not have this and we always customize it
    IEnumerable<KeyValuePair<string, T>> GetProperties<T>(); // try cast the value to T and return
}
```

**Comment by annelo-msft** [comment]
This is one possible approach to solving this problem, but it is unclear that these are the public APIs we would want to provide in SCM to enable this scenario.

@ArcturusZhang, if the scenario you are looking to enable is the same as https://github.com/Azure/azure-sdk-for-net/issues/43771, let's add requirements to that issue so we can move forward on building the right SCM APIs to enable user needs here.  If the scenarios are different from those, let's file a new issue to track designing the right APIs to enable those scenarios.  Many thanks!
