### ISSUE TITLE
[FEATURE REQ] Get rid of hardcoded OpenAI-endpoint in OpenAIClient

### ISSUE THREAD

**Issue by Matti-Koopa** [Azure/azure-sdk-for-net#44173]
### Library name

Azure.AI.OpenAI

### Please describe the feature.

In `OpenAIClient.cs` the OpenAI-API-Uri is hardcoded and cannot be changed. The constructor for specifying a custom endpoint will always expect an Azure Uri. The private, unchangeable variable called `_isConfiguredForAzureOpenAI` cannot be changed.
This is related to issue #37794, which was closed because it was recommended to use a proxy server instead.

This should not be considered a serious solution these days. The OpenAI-API has become the de-factor standard for all LLM APIs. Many solutions such as "Local AI" or "Oobabooga Web UI" ship an OpenAI-compatible API. We should be able to consume those with `OpenAIClient`. Setting up a proxy isn't a feasible option for something as simple as that. Also it would make it impossible to use multiple different `OpenAIClient` instances with different endpoints.

Suggested solution:
Add another constructor or an optional boolean parameter like `useAzureOpenAI` to the existing constructor that, if set, disables `_isConfiguredForAzureOpenAI` and does not initialize `_pipeline` using Azure-stuff while also allowing you to set a custom `endpoint`.

**Comment by abahjat-d** [comment]
I agree, this would be a huge help

**Comment by acarver-d** [comment]
We also need this feature

**Comment by scottaddie** [comment]
This problem has been addressed in the v2.x release train. The endpoint can be set via the `OpenAIClientOptions.Endpoint` property:

https://github.com/openai/openai-dotnet/blob/0b97311f58dfb28bd883d990f68d548da040a807/src/Custom/OpenAIClientOptions.cs#L15
