### ISSUE TITLE
[BUG] Equality failures due to implicit cast on RequestFailedException.ErrorCode

### ISSUE THREAD

**Issue by Arithmomaniac** [Azure/azure-sdk-for-net#44213]
### Library name and version

Azure.Storage.Blobs 12.19.1.0

### Describe the bug

In [several places in the SDK](https://github.com/search?q=repo%3AAzure%2Fazure-sdk-for-net+%22public+static+implicit+operator%22+%22string+value%29+%3D%3E%22+%22throw+new+ArgumentNullException%28nameof%28value%29%29%22+path%3A**%2F*ErrorCode.cs&type=code), comparing `RequestFailedException.ErrorCode` to a strongly typed `*ErrorCode` type (e.g. `BlobErrorCode)` can throw an exception. 

This is because:
- `RequestFailedException.ErrorCode` is nullable
- strings can be implicitly converted in `==` comparisons to `*ErrorCode` 
- The constructor of `*ErrorCode` throws if a null is received

This goes against the [guideline](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/user-defined-conversion-operators) of
> Predefined C# implicit conversions always succeed and never throw an exception. User-defined implicit conversions should behave in that way as well.

### Expected behavior

No exception is thrown; in the Reproduction Steps case below, `isContainerError` is `false` if inspected.

### Actual behavior

An `ArgumentNullException` is thrown.

### Reproduction Steps
```csharp
try
{
    throw new RequestFailedException(status: 404, message: "Some error.", errorCode: null, innerException: null);
}
catch (RequestFailedException ex)
{
    var isContainerError = ex.ErrorCode == BlobErrorCode.ContainerNotFound;
}
```

**Comment by Arithmomaniac** [comment]
Thanks!
What about the non storage APIs? Should I open separate bugs?

**Comment by nickliu-msft** [comment]
Hi @Arithmomaniac for non-storage APIs, yes please open another GitHub issue without the "Storage" tag and the appropriate team will assist you

**Comment by Arithmomaniac** [comment]
@nickliu-msft Thanks. I kicked the issue up to the AutoTest repo, which I should have done originally (but thanks for providing the recommended solution 😉)
