### ISSUE TITLE
[FEATURE REQ] Upgrade Azure.AI.OpenAI.Assistants to support latest API

### ISSUE THREAD

**Issue by BlackGad** [Azure/azure-sdk-for-net#44225]
### Library name

Azure.AI.OpenAI.Assistants

### Please describe the feature.

Hi!

Are there are any plans for [**Azure.AI.OpenAI.Assistants**](https://www.nuget.org/packages/Azure.AI.OpenAI.Assistants/1.0.0-beta.4) API update to support:
1. Assistant streaming [API](https://platform.openai.com/docs/assistants/overview?context=with-streaming)
2. Assistant token usage [API](https://platform.openai.com/docs/api-reference/runs/object)
3. Latest models support like **gpt-4o**

**Comment by jonchicoine** [comment]
I have the exact same questions, especially: Assistant streaming, It is supported for chatcompletions ... all we have currently is GetRunAsync()...

**Comment by douglasware** [comment]
It's really hard to understand why anyone should use the MS bits if they can't keep them up to date with the published Open API specs.

**Comment by exsitec-felfro** [comment]
Do we have any time plan on this? Ability to use the latest models would be appreciated.

**Comment by scottaddie** [comment]
We're encouraging customers to move to the feature-complete Azure.AI.OpenAI package to take advantage of these things. The desire is to eventually deprecate Azure.AI.OpenAI.Assistants in favor of the package I mentioned. See the note at https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/openai/Azure.AI.OpenAI.Assistants#important-note-assistants-is-converging for more context.
