### ISSUE TITLE
Invalid URI: The format of the URI could not be determined

### ISSUE THREAD

**Issue by elvischau** [Azure/azure-sdk-for-net#44230]
https://github.com/Azure/azure-sdk-for-net/blob/9f55143935b61a2dfdca6bf6d6f37e7b4a786397/sdk/storage/Azure.Storage.Blobs/src/BlobExtensions.cs#L773

Hi, 

It looks like the URL in x-ms-copy-source header might have changed, when it hit this part of the code, it will report "Invalid URI: The format of the URI could not be determined" error.

It appears that the code is expected an absolute URL, but now the URL is just a relative URL

**Comment by seanmcc-msft** [comment]
@elvischau, which version are you on?  Can you provide a code snippet that we can use to reproduce?

**Comment by nickliu-msft** [comment]
Closing this issue due to no response. If you have further questions/concerns please create another issue. Thanks
