### ISSUE TITLE
Getting IVirtualMachine public IP address

### ISSUE THREAD

**Issue by jbpoulsen** [Azure/azure-sdk-for-net#4423]
Hello.

Im having lots of issues with getting the public IP Address of an already created Azure Virtual Machine.

I can request everything i want about the VM (Power state, power off, power on), but getting the public ip address of the machine seems to never work.

To get the IP Address i simply call: vm.GetPrimaryPublicIPAddress(), but that method keeps returning null for me. I've tried using many different VM's but they all return null.
If i look them up in the Azure Portal, i can clearly see that they have an accessible public IP address that i can use without issues.

Am i querying the IP address wrong? What other options do i have to try and look for the IP address?

Thanks.

**Comment by huangpf** [comment]
It's about the usage of VM-Network cross-RP APIs. Not just a Compute bounded problem. Also related to NRP somehow.

But it belongs to the service API ask boundary. @hyonholee @huangpf

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
