### ISSUE TITLE
OpenTelemetry Resource Attributes are not exported to Azure Monitor

### ISSUE THREAD

**Issue by tskardal** [Azure/azure-sdk-for-net#44257]
### Library name and version

Azure.Monitor.OpenTelemetry.Exporter

### Query/Question

When I run my application I manage to get data from OpenTelemetry into Azure Monitor, but I have some trouble with the resource attributes that I provide in my setup.

This [guide] only adds the serivce.name attribute but my understanding is that you can add any custom attribute here, and that it 
 is not required to be one of the attributes defined in the [semconv].

[guide]: https://learn.microsoft.com/en-us/dotnet/core/diagnostics/observability-with-otel
[semconv]: https://opentelemetry.io/docs/specs/semconv/resource/

I've found another [issue] mentioning this, but I'm not sure if it is directly related, as this is in the contrib repository. I can also confirm that the resource attributes are added and logged by using the console exporter.

[issue]: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18525

Is this a limitation in Azure Monitor or maybe a misconfiguration or misunderstanding on my side? I struggle to find any documentation on this, so creating this issue is kind of is my last idea of how to get any further with this problem. :)

Thanks in advance!

**Comment by TimothyMothra** [comment]
I'm consolidating all issues regarding exporting custom Resource Attributes into another issue to help with tracking. https://github.com/Azure/azure-sdk-for-net/issues/46020
