### ISSUE TITLE
[BUG] BuildDocumentModelContent.BuildMode is not getting serialized

### ISSUE THREAD

**Issue by jaliyaudagedara** [Azure/azure-sdk-for-net#44266]
### Library name and version

Azure.AI.DocumentIntelligence 1.0.0-beta.2 (preview)

### Describe the bug

Consider the following example code to build a `BuildDocumentModelContent`.

```csharp
using Azure.AI.DocumentIntelligence;
using System.Text.Json;

BuildDocumentModelContent content = new("some-model-id", DocumentBuildMode.Neural)
{
    AzureBlobSource = new AzureBlobContentSource(new Uri("https://someSasUri"))
    {
        Prefix = "/somefolder"
    },
    Description = "Some Description"
};

string serializedContent = JsonSerializer.Serialize(content, new JsonSerializerOptions
{
    WriteIndented = true
});

Console.WriteLine(serializedContent);
```

Output:
```
{
  "ModelId": "some-model-id",
  "Description": "Some Description",
  "BuildMode": {},
  "AzureBlobSource": {
    "ContainerUrl": "https://someSasUri",
    "Prefix": "/somefolder"
  },
  "AzureBlobFileListSource": null,
  "Tags": {}
}
```

Note the `BuildMode` is empty.

### Expected behavior

`BuildDocumentModelContent.BuildMode` should get serialized.

### Actual behavior

`BuildDocumentModelContent.BuildMode` is not getting serialized.

### Reproduction Steps

Provided above under the description.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by jaliyaudagedara** [comment]
@kinelski,

Thanks for the response.

I see. My scenario is, that I am publishing a message with the content of `BuildDocumentModelContent` to a ServiceBus and there is an Azure Function that picks it up and calls the  Document Intelligence API.

While I can work around it, I'd personally think since `BuildDocumentModelContent` is getting sent over the wire through `documentIntelligenceAdministrationClient.BuildDocumentModelAsync(...)`, it's properties should be serializable and be consistent.
