### ISSUE TITLE
Avro Scheme "default" and "doc" are missing

### ISSUE THREAD

**Issue by ahilis** [Azure/azure-sdk-for-net#4429]
I've spent a lot of time trying to figure out how to add "default" or "doc" properties for any field from C# class into scheme. I do it like that:

`AvroSerializer.Create<Class>().WriterSchema.ToString()`

I found that it's impossible. And that's why:
ReflectionSchemaBuilder always pass null inside the RecordField instead of default value (line 466)
Doc property is always sets to empty string inside MemberSerializationInfo constructor
Is there any chance that it will be fixed?

**Comment by tylerfox** [comment]
The Avro SDK is no longer supported by Microsoft.
