### ISSUE TITLE
Setting ACL for a Blob with .NET SDK?

### ISSUE THREAD

**Issue by digiofficerobin** [Azure/azure-sdk-for-net#44298]
Hi,

Through the REST API there is not a way to add ACLs per blob.
https://docs.microsoft.com/en-us/rest/api/storageservices/operations-on-blobs

_Originally posted by @amnguye in https://github.com/Azure/azure-sdk-for-net/issues/11714#issuecomment-623587472_

We are a few years later, I still don't see a possibility to set the ACL of a Blob file. We want to store our DMS documents in Blob containers and need to set the ACL. I've noticed that the Web UI and the Storageexplorer tool can read/write the ACLs.

I think the ACL should also be read/write with the .NET SDK for Blob containers, folders and files.

**Comment by digiofficerobin** [comment]
I'm confused about the relation between Azure Blob Storage and Data Lake Storage Gen2. It seems that Data Lake is built on top of Azure Blob storage and enhances capabilities such as Finer grained security model. source: https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-introduction 

Does, for example, the Storageexplorer uses the Data Lake Storage Gen2 API instead of the Blob storage API?

**Comment by seanmcc-msft** [comment]
@digiofficerobin, if you are using a ADLS Gen 2 account, please switch to the Azure.Storage.Files.DataLake package, it will allow you to set ACLs on a file.

**Comment by digiofficerobin** [comment]
@seanmcc-msft Thanks for directing me to the Azure.Storage.Files.DataLake package.
