### ISSUE TITLE
[BUG] Missing HTTP header sanitization when reading values from `/etc/{os,lsb}-release`

### ISSUE THREAD

**Issue by nazarewk** [Azure/azure-sdk-for-net#44300]
### Library name and version

User-Agent:azsdk-net-Identity/1.10.4 (.NET 8.0.5; NixOS 24.11 (Vicuña))

### Describe the bug

I have already spent enough time trying to report it, so please just read already existing references (don't want to infinitely cross-post the same text)  in this order until you think you have enough context to understand it:
1. https://github.com/dotnet/runtime/issues/102819#issuecomment-2138014009
2. https://github.com/dotnet/runtime/issues/102819#issue-2323461673
3. https://github.com/microsoftgraph/msgraph-cli/issues/477#issue-2322875661
4. https://github.com/NixOS/nixpkgs/issues/315574

### Expected behavior

whatever is involved in the issue should either:
1. not read `/etc/os-release`/`/etc/lsb-release` at all
2. make sure it properly escapes unexpected content (such as UTF-8/Unicode characters), by for example urlencoding it

### Actual behavior

please just read https://github.com/dotnet/runtime/issues/102819#issue-2323461673

### Reproduction Steps

please read `To Reproduce` part of https://github.com/dotnet/runtime/issues/102819#issue-2323461673

### Environment

`User-Agent:azsdk-net-Identity/1.10.4 (.NET 8.0.5; NixOS 24.11 (Vicuña))`

**Comment by wfurt** [comment]
[Azure/azure-sdk-for-net@5004a5c/sdk/eventhub/Azure.Messaging.EventHubs/src/Core/ClientLibraryInformation.cs#L56-L82](https://github.com/Azure/azure-sdk-for-net/blob/5004a5cb6202dab381d5a7a452da8ee775db3a0e/sdk/eventhub/Azure.Messaging.EventHubs/src/Core/ClientLibraryInformation.cs#L56-L82)

the RuntimeInformation.OSDescription makes no guarantee about HTTP safety -> "An opaque string that describes the operating system on which the app is running."

**Comment by jsquire** [comment]
> [Azure/azure-sdk-for-net@5004a5c/sdk/eventhub/Azure.Messaging.EventHubs/src/Core/ClientLibraryInformation.cs#L56-L82](https://github.com/Azure/azure-sdk-for-net/blob/5004a5cb6202dab381d5a7a452da8ee775db3a0e/sdk/eventhub/Azure.Messaging.EventHubs/src/Core/ClientLibraryInformation.cs#L56-L82)
> 
> the `RuntimeInformation.OSDescription` makes no guarantee about HTTP safety -> "An opaque string that describes the operating system on which the app is running."

@wfurt:  Event Hubs an AMQP-based library and does not send HTTP requests.   The class that you're referencing sets link properties of AMQP type [string](https://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-types-v1.0-os.html#type-string), which is Unicode-based.

**Comment by jsquire** [comment]
@m-redding:  Would you take a look at the Core logic for User Agent strings?


//cc: @annelo-msft, @KrzysztofCwalina for awareness.

**Comment by m-redding** [comment]
@nazarewk  I'm working on investigating a fix for this, but if you don't want the user agent string to be added to the request at all, you can set the environment variable "AZURE_TELEMETRY_DISABLED" to true. There's also [a setting for this in the SDK](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/DiagnosticsOptions.cs#L93) but it doesn't sound like you're using the identity SDK directly so I'm assuming you can't take advantage of that.

**Comment by Mr-MooMoo** [comment]
As a hacky workaround (and totally un-nix-y way, i know - just to be able to work):
```
sudo ushare -m bash
mount -o remount,rw /nix/store
sed -i 's/ñ/n/g' /etc/os-release
sed -i 's/ñ/n/g' /etc/lsb-release
exit
```
(replaces all ñ with n) in given files, so nuget can pull packages, and dotnet restore keeps working
Will be overwritten on every update of your nix-config files!

**Comment by wfurt** [comment]
that works only if you are admin/root -> not scalable IMHO.
