### ISSUE TITLE
EventGrid Management SDK Samples

### ISSUE THREAD

**Issue by tobiasb** [Azure/azure-sdk-for-net#4432]
Are there samples somewhere on how to properly use the EventGrid Management SDK? Especially the authentication doesn't seem to be as straight forward as the EventGrid data plane SDK.

**Comment by ahamad-MS** [comment]
We have multiple samples for both control and data planes. Here is list:

1. .NET SDK Samples: https://github.com/Azure-Samples/event-grid-dotnet-publish-consume-events
and here is a list of all .NET Sample for Event Grid: https://github.com/Azure-Samples?utf8=%E2%9C%93&q=event-grid&type=&language=c%23

2. Here is a full list of all languages:
https://github.com/Azure-Samples?utf8=%E2%9C%93&q=event-grid&type=&language=

**Comment by jfggdl** [comment]
@tobiasb, We are closing this issue, but feel free to reopen it if you feel that the documentation provided does not address all of your concerns.

**Comment by SeanFeldman** [comment]
@ahamad-MS, I've looked into the https://github.com/Azure-Samples/event-grid-dotnet-publish-consume-events and it appears to be outdated (both the client and the management packages). Is it no longer maintained?

Raised an issue about it, https://github.com/Azure/azure-sdk-for-net/issues/12246
