### ISSUE TITLE
Letting you know I published a sample that I think you can use.

### ISSUE THREAD

**Issue by bigtfromaz** [Azure/azure-sdk-for-net#44327]
### Type of issue

Other (describe below)

### Description

[Enter feedback here]
I was unable to locate a useful sample for this API, so I created one to test my assumptions before starting an in-house project. It's published at this link:
[https://github.com/bigtfromaz/AzureDnsApiSample]
Let me know if you decide to use it.

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.dns?view=azure-dotnet

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/ns-Azure.ResourceManager.Dns.xml

### Document Version Independent Id

1fcdd705-3a40-b9df-e3fa-64da508a09d5

### Article author

@azure-sdk

### Metadata

* ID: 5885ecf6-2e21-ce6a-12bd-e2cc9a6a6e3f 
* Service: **azure**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Hey @bigtfromaz , thank you for your contribution, @HarveyLink please help on adding this sample into the sample folder https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/dns/Azure.ResourceManager.Dns/samples

**Comment by HarveyLink** [comment]
Our samples already contains most of the scenarios, other resources/tag api samples located at https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/resourcemanager/Azure.ResourceManager/samples

**Comment by bigtfromaz** [comment]
Where are you DNS samples?

This message was sent from my mobile phone. Please forgive me if it seems terse or pithy.

On Jun 18, 2024, at 2:24 AM, Minghao Chen ***@***.***> wrote:

﻿

Our samples already contains most of the scenarios, other resources/tag api samples located at https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/resourcemanager/Azure.ResourceManager/samples
