### ISSUE TITLE
[FEATURE REQ] Microsoft Entra ID (aka AAD2) authentication support for `ImageAnalysisClient`

### ISSUE THREAD

**Issue by Wei-YB** [Azure/azure-sdk-for-net#44320]
### Library name

Azure.AI.Vision.ImageAnalysis

### Please describe the feature.

Currently the `Azure.AI.Vision.ImageAnalysis.ImageAnalysisClient` only supports authentication with an access key, which has no integrate with AAD and Azure RBAC. I strongly recommend the dev team could support `Azure.Core.TokenCredential` as authentication method so we can remove the dependency of local auth.

**Comment by rhurey** [comment]
PR #44509

**Comment by rahulkhanna1605** [comment]
What role needs to be assigned to an app service for it to call computer vision resource using managed identity?

**Comment by rhurey** [comment]
@rahulkhanna1605 "Cognitive Services User"

@Wei-YB  Since Beta-3 released with this support, I'll close this.
