### ISSUE TITLE
[FEATURE REQ]Need to support pass HttpMessageHandler when construct client

### ISSUE THREAD

**Issue by cherryzh** [Azure/azure-sdk-for-net#44334]
### Library name

All

### Please describe the feature.

When using client library, I need to trace all service calls to Azure services with service call details such as API name, elapsed time, success or fail. Usually this is implemented in HttpMessageHandler. Without this functionality, every service call client code needs to copy the same code logic.

**Comment by xboxeer** [comment]
Add @ArthurMa1978 for awarness

**Comment by jsquire** [comment]
Hi @cherryzh.  The Azure SDK libraries all provide this level of tracing for all service operations via both our Open Telemetry diagnostics as well as our ETW-based logs.   For custom needs, you can create an `HttpClient` instance configured to your specifications and pass it via the `ClientOptions` used to construct your client.

An example of doing so can be found [in this sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Configuration.md#user-provided-httpclient-instance).
