### ISSUE TITLE
Vulnerable libraries in some track2 data plane SDKs

### ISSUE THREAD

**Issue by archerzz** [Azure/azure-sdk-for-net#44343]
## Problem

See the build log: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3834974&view=logs&j=2c0ea462-7216-57d4-bec6-0d2de9c81498&t=f2c23f9c-1933-5fad-99c8-bfaae8933e5e

There are two security warnings:
- > D:\a\_work\1\s\azure-sdk\sdk\digitaltwins\Azure.DigitalTwins.Core\samples\DigitalTwinsClientSample\DigitalTwinsClientSample.csproj : warning NU1902: Package 'Azure.Identity' 1.10.3 has a known moderate severity vulnerability, https://github.com/advisories/GHSA-wvxc-855f-jvrv [D:\a\_work\1\s\azure-sdk\eng\service.proj]
- > D:\a\_work\1\s\azure-sdk\sdk\eventgrid\Azure.Messaging.EventGrid\EventGridSourceGenerator\src\EventGridSourceGenerator.csproj : warning NU1903: Package 'Newtonsoft.Json' 10.0.3 has a known high severity vulnerability, https://github.com/advisories/GHSA-5crp-9r3c-p9vr [D:\a\_work\1\s\azure-sdk\eng\service.proj]

Those two warnings are treated as error so that they break some CI pipelines.

**Comment by archerzz** [comment]
I tried to bump the versions to the latest, and the warnings are gone. I'll let the owner to decide the versions.

**Comment by jsquire** [comment]
Thanks for calling this out, @archerzz.   I'll take a look at these today and get them updated.
