### ISSUE TITLE
[QUERY]: Is OpenTelemetry Baggage supported

### ISSUE THREAD

**Issue by MarcusKohnert** [Azure/azure-sdk-for-net#44348]
### Library name and version

Azure.Messaging.ServiceBus 7.17.5

### Query/Question

@lmolkova wrote [here](https://github.com/Azure/azure-sdk-for-net/issues/18002#issuecomment-1007602042) that OpenTelemetry Baggage will be gradually adopted once it is approved.

I couldn't find any information if that adoption took place already.
[Here](https://github.com/Azure/azure-sdk-for-net/issues/41543#issue-2099169376) it sounds like it should work.

I couldn't get Baggage propagation over process boundaries working in my local development setup.

### This is my scenario:
Process A, populates Baggage items via Activity.Current?.SetBaggage("", "")
Process A, sends message to Azure Service Bus
Process B, receives message from Azure Service Bus

### Expected result:
Process B, Activity.Current has Baggage items

### Actual result:
Process B, Activity.Current has no baggage

Is Baggage propagation already supposed to work?
If yes, do I need to turn on specific things (Flags or similar)?
Is maybe the transport mechanism to ServiceBus relevant?

Thanks for any hints or pointers?

### Environment

> dotnet --info
.NET SDK:
 Version:           8.0.204
 Commit:            c338c7548c
 Workload version:  8.0.200-manifests.7d36c14f
Runtime:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.204\

**Comment by jsquire** [comment]
@lmolkova :  Would you mind offering your insight?

**Comment by lmolkova** [comment]
Thanks @MarcusKohnert !

The short answer is no, unfortunately Baggage is not supported - https://github.com/Azure/azure-sdk/issues/6959
The long answer - we don't have a good way to support it in OTel-compatible way - https://github.com/open-telemetry/opentelemetry-dotnet/issues/5667.

**Comment by MarcusKohnert** [comment]
@lmolkova Thank you very much for the explanation.
