### ISSUE TITLE
Examples section has wrong example. Uses non existing API. 

### ISSUE THREAD

**Issue by vizistaha** [Azure/azure-sdk-for-net#44341]
### Type of issue

Code doesn't work

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.linq.cosmoslinqextensions.toquerydefinition?view=azure-dotnet

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos.Linq/CosmosLinqExtensions.xml

### Document Version Independent Id

a6ff6b3d-528b-31f5-66cc-63f492306a88

### Article author

@azure-sdk

### Metadata

* ID: 3b65e983-6096-b372-355c-c18f33a57629 
* Service: **cosmos-db**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.Azure.Cosmos` library is maintained as [#20507](https://github.com/cosmos/cosmos-sdk/issues/20507).
