### ISSUE TITLE
[QUERY] Can ProcessMessageEventArgs.CompleteMessageAsync be throttled?

### ISSUE THREAD

**Issue by pabermod** [Azure/azure-sdk-for-net#44344]
### Library name and version

Azure.Messaging.ServiceBus 7.17.1

### Query/Question

I'm testing  my application in an Azure ServiceBus Standard and while processing a message in a ServiceBusProcessor.

I'm getting a throttling error:

The request was terminated because the namespace MYNAMESPACE is being throttled

At also it seems the message is being duplicated (The sender of the message only sends it once)

I'm completing manually the messages. After processing my message i'm calling **CompleteMessageAsync**

Could this method not finalize due to the ASB namespace being throttled, generating a message duplication due to it being abandoned after the message lock is expired?

### Environment

.Net 461

**Comment by jsquire** [comment]
Hi @pabermod.   Yes, all operations in Service Bus are subject to service quotas and may be throttled - including message completion calls.   Please see [Throttling operations on Azure Service Bus](https://learn.microsoft.com/azure/service-bus-messaging/service-bus-throttling) for more context and discussion.   

In the case that your attempt to complete a message was throttled, then the message was unsettled and once the lock expires, it will be made available to be read again, resulting in duplicate processing.
