### ISSUE TITLE
[FEATURE REQ]  export CategoryName to Application Insights

### ISSUE THREAD

**Issue by cataggar** [Azure/azure-sdk-for-net#44353]
### Library name

Azure.Monitor.OpenTelemetry.Exporter

### Please describe the feature.

It would be nice if there was an easy way to export `LogRecord.CategoryName`. The `OpenTelemetry.Exporter.Geneva` sets `name` with this value [here](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/47b667acf8cde47aa73fc6d28b609ebb3aeca8d3/src/OpenTelemetry.Exporter.Geneva/MsgPackExporter/MsgPackLogExporter.cs#L315-L318). We use both exporters. It would be great if there was an easy or standard way to export it to Application Insights.

**Comment by TimothyMothra** [comment]
This is fixed in https://github.com/Azure/azure-sdk-for-net/pull/44754
I'm working on releasing a new beta of our libraries, which should be available Tuesday (7/16).
