### ISSUE TITLE
invalid syntax for GetDatabase  - closing paren is shown as closing square bracket

### ISSUE THREAD

**Issue by zachz-microsoft** [Azure/azure-sdk-for-net#44375]
### Type of issue

Typo

### Description

Code snippet in article shows the following.

Database db = cosmosClient.GetDatabase("myDatabaseId"];
DatabaseResponse response = await db.ReadAsync();

the closing square bracket on the first line should be a closing paren

Database db = cosmosClient.GetDatabase("myDatabaseId");
DatabaseResponse response = await db.ReadAsync();

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/azure.cosmos.cosmosclient.getdatabase?view=azure-dotnet-preview

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Cosmos/CosmosClient.xml

### Document Version Independent Id

937ff655-3950-fa5c-4b13-866185f4ba5e

### Article author

@azure-sdk

### Metadata

* ID: 1254ef33-f7a0-9971-5833-8fbae7e645b8 
* Service: **azure**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.Azure.Cosmos` package is maintained as [#4526](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/4526).

**Comment by zfoster** [comment]
please remove zfoster from the actions cc
