### ISSUE TITLE
[FEATURE REQ] Support assigning Entra ID to PostgreSQL Flexible Server instances

### ISSUE THREAD

**Issue by aaronpowell** [Azure/azure-sdk-for-net#44376]
### Library name

Azure.Provisioning

### Please describe the feature.

While Azure.Provisioning has support for configuring the resource to use Entra as the auth model (set via the properties of `Microsoft.DBforPostgreSQL/flexibleServers`), it lacks the ability to create an admin using, which requires using `Microsoft.DBforPostgreSQL/flexibleServers/administrators` (`PostgreSqlFlexibleServerActiveDirectoryAdministratorResource` is the type in the RM package).

Including this will mean that we can configure deployed resources to use managed identity with no SQL auth account.

**Comment by jsquire** [comment]
//cc: @JoshLove-msft

**Comment by tg-msft** [comment]
That's supported in the latest updates at https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/provisioning/Azure.Provisioning.PostgreSql/tests/BasicPostgreSqlTests.cs#L89
