### ISSUE TITLE
[FEATURE REQ] Azure.ResourceManager.Sql does not provide a mechanism to enable/disable "Microsoft Entra authentication only" property

### ISSUE THREAD

**Issue by VladimirKhvostov** [Azure/azure-sdk-for-net#44385]
### Please describe the feature.

I had to write the following to code to enable "Microsoft Entra authentication only" authentication.
Please provide a mechanism to do this with reflection.

```csharp
SqlServerResource sqlServer = armClient.GetSqlServerResource(SqlServerResource.CreateResourceIdentifier(c_subscriptionId, c_resourceGroupName, c_sqlServerName)).Get();
SqlServerAzureADAdministratorResource admin = sqlServer.GetSqlServerAzureADAdministrator(SqlAdministratorName.ActiveDirectory);
    admin.Data.GetType().GetField("<IsAzureADOnlyAuthenticationEnabled>k__BackingField",
    System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance).SetValue(admin.Data, true);
    
admin.Update(WaitUntil.Completed, admin.Data);

```

**Comment by VladimirKhvostov** [comment]
I found out that I can do this:
```csharp

SqlServerAzureADOnlyAuthenticationResource authentication = sqlServer.GetSqlServerAzureADOnlyAuthentication(AuthenticationName.Default);
authentication.Update(WaitUntil.Completed, new SqlServerAzureADOnlyAuthenticationData() { IsAzureADOnlyAuthenticationEnabled = true });
```

**Comment by VladimirKhvostov** [comment]
It is not clear why SqlServerAzureADAdministratorResource has IsAzureADOnlyAuthenticationEnabled. It is readonly and always null.

**Comment by HarveyLink** [comment]
> I found out that I can do this:
> 
> ```cs
> SqlServerAzureADOnlyAuthenticationResource authentication = sqlServer.GetSqlServerAzureADOnlyAuthentication(AuthenticationName.Default);
> authentication.Update(WaitUntil.Completed, new SqlServerAzureADOnlyAuthenticationData() { IsAzureADOnlyAuthenticationEnabled = true });
> ```

Hi @VladimirKhvostov , looks like you have resolved your issue by yourself. The property's read only is defined by the service swagger, please check: https://github.com/Azure/azure-rest-api-specs/blob/125223f5737a5082e02bc7ef7981e5c819c7330c/specification/sql/resource-manager/Microsoft.Sql/preview/2023-02-01-preview/ServerAzureADAdministrators.json#L294
We'll close the issue for now, if you have further question, feel free to reopen it. Thanks~
