### ISSUE TITLE
[BUG] autorest.md Gen error

### ISSUE THREAD

**Issue by welovej** [Azure/azure-sdk-for-net#44396]
### Library name and version

Azure.ResourceManager.ApiManagement

### Describe the bug

if we change the autorest.md to the simplied version like the attach
[autorest.md](https://github.com/user-attachments/files/15574129/autorest.md), then run :dotnet build /t:GenerateCode,
it would show the error like the   attach:
[error.txt](https://github.com/user-attachments/files/15574152/error.txt)

### Expected behavior

no error

### Actual behavior

see Describe the bug

### Reproduction Steps

see Describe the bug

**Comment by jsquire** [comment]
GitHub is not the place to seek support for internal issues with code generation.  Please refer to the [Azure SDK onboarding guide](https://eng.ms/docs/products/azure-developer-experience/onboard/requirements) and use the [Azure SDK onboarding Teams channel](https://teams.microsoft.com/l/channel/19%3ade3fce22c2994be18cac50502c55f717%40thread.skype/Azure%2520SDK%2520Onboarding?groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47) for assistance.
