### ISSUE TITLE
[BUG] Test BearerTokenAuthenticationPolicy_TokenNotAlmostExpiredWithRefreshOnNow is failing randomly

### ISSUE THREAD

**Issue by live1206** [Azure/azure-sdk-for-net#44417]
### Library name and version

Azure.Core

### Describe the bug

![image](https://github.com/Azure/azure-sdk-for-net/assets/5196139/20685587-1c9e-4f15-b3b5-0a1fc94a9136)
https://dev.azure.com/azure-sdk/public/_build/results?buildId=3851287&view=ms.vss-test-web.build-test-results-tab&runId=48129193&resultId=103040&paneView=debug
[BearerTokenAuthenticationPolicy_TokenNotAlmostExpiredWithRefreshOnNow](https://github.com/Azure/azure-sdk-for-net/blob/3d7d02efe339b7d2effbeb982d0f6839233dec98/sdk/core/Azure.Core/tests/BearerTokenAuthenticationPolicyTests.cs#L269) is failing constantly, and rerun will usually pass.

### Expected behavior

Tests should always pass

### Actual behavior

BearerTokenAuthenticationPolicy_TokenNotAlmostExpiredWithRefreshOnNow is failing randomly

### Reproduction Steps

PR CI is failing from time to time.
https://dev.azure.com/azure-sdk/public/_build/results?buildId=3851287&view=ms.vss-test-web.build-test-results-tab&runId=48129193&resultId=103040&paneView=debug

**Comment by jsquire** [comment]
@christothes:  Would you please take a look?
