### ISSUE TITLE
[FEATURE REQ] Add a GenerateUserDelegation...SasUri extension to storage clients.

### ISSUE THREAD

**Issue by MitchBodmer** [Azure/azure-sdk-for-net#44426]
### Library name

Azure.Storage.*

### Please describe the feature.

My organization is trying to move away from service SAS tokens and I'm ending up writing extension methods like this...
```csharp
using System;
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Models;
using Azure.Storage.Blobs.Specialized;
using Azure.Storage.Sas;

namespace My.Service;

internal static class BlobClientExtensions
{
    public static Uri GenerateUserDelegationSasUri(
        this BlobClient blobClient,
        UserDelegationKey userDelegationKey,
        BlobSasPermissions blobSasPermissions,
        DateTimeOffset expiresOn)
    {
        BlobSasBuilder blobSasBuilder = new(blobSasPermissions, expiresOn)
        {
            BlobContainerName = blobClient.GetParentBlobContainerClient().Name,
            BlobName = blobClient.Name,
            Resource = "b"
        };

        BlobUriBuilder blobUriBuilder = new(blobClient.Uri)
        {
            Sas = blobSasBuilder.ToSasQueryParameters(
                userDelegationKey,
                blobClient
                    .GetParentBlobContainerClient()
                    .GetParentBlobServiceClient().AccountName)
        };

        return blobUriBuilder.ToUri();
    }
}
```
...to emulate the convenient `BlobClient.GenerateSasUri` method.

Since user delegation SAS tokens are the recommended path for most situations now, it seems like adding similar helper methods might make sense.

This should probably be considered for all storage clients that currently expose any `GenerateSasUri` method, not just blobs.

**Comment by DrEsteban** [comment]
+1! 

It's always fun when you go to file a piece of feedback and find not only the exact idea already logged, but the exact same proposed solution! 🤣 (My impl differs only in variable names but is otherwise identical 😄) 

Great 🧠s... @MitchBodmer

**Comment by seanmcc-msft** [comment]
@MitchBodmer this is a reasonable feature request, we will scheduled this for an upcoming release.

**Comment by nickliu-msft** [comment]
Closing this as the feature has been implemented and will be released soon

**Comment by MitchBodmer** [comment]
Excellent! Thank you for doing this. I really appreciate it. Looking forward to using it.
