### ISSUE TITLE
When reposting a service bus message after a failure, the Diagnostic-Id field is not reset/clear. 

### ISSUE THREAD

**Issue by EmilDamian** [Azure/azure-sdk-for-net#44432]
### Library name and version

Azure.Messaging.ServiceBus 7.17.5

### Describe the bug

When reposting a service bus message after a failure, the Diagnostic-Id field is not reset/clear. 

### Expected behavior

Diagnostic-Id field should be cleared.

### Actual behavior

The same Diagnostic-Id values is kept for unrelated messages.

### Reproduction Steps

await using var serviceBusSender = serviceBusClient.CreateSender(topicName);
 await serviceBusSender.SendMessageAsync(
    new ServiceBusMessage(message)
  {
    ApplicationProperties =
    {
        [configuration.ReviveForProperty] = subscriptionName,
      [configuration.RetryCounterProperty] = retryCounter + 1
    },
    ScheduledEnqueueTime = DateTimeOffset.UtcNow.Add(TimeSpan.FromSeconds(retryDelay))
  });

### Environment

Azure Function App

.NET SDK:
 Version:           8.0.300
 Commit:            326f6e68b2
 Workload version:  8.0.300-manifests.4e5ea2d8
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.300\

.NET workloads installed:
 [aspire]
   Installation Source: VS 17.10.34928.147
   Manifest Version:    8.0.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.0.0\WorkloadManifest.json
   Install Type:        FileBased

Host:
  Version:      8.0.5
  Architecture: x64
  Commit:       087e15321b

**Comment by jsquire** [comment]
@EmilDamian:  Thank you for reaching out and we regret that you're experiencing difficulties.   I'm not sure that I understand the end-to-end scenario that you're describing.   Can you please provide more context for what a "failure" is in this scenario and what you believe the expected behavior should be?
