### ISSUE TITLE
UpdateSubscriptionAsync method does not update AutoDeleteOnIdle properties

### ISSUE THREAD

**Issue by liangdaxian** [Azure/azure-sdk-for-net#44458]
# Description

i am trying to using the admin api to update some subscription AutDeleteOnIdel time span, code snip as:

var subs = admin.GetSubscriptionsAsync(topicName).GetAsyncEnumerator();
while (subs.MoveNextAsync().AsTask().Result)
{
   var subdetails = admin.GetSubscriptionAsync(topicName, subs.Current.SubscriptionName).Result.Value;
    
    subdetails.AutoDeleteOnIdle = TimeSpan.FromDays(90);

    var updated = admin.UpdateSubscriptionAsync(subdetails).Result.Value;

    Console.Out.WriteLine($"Sub {subdetails.SubscriptionName} in {subdetails.TopicName} updated autodelete on idle");
}

however the code runs fine but AutoDeleteOnIdle was not actually updated

using  <package id="Azure.Messaging.ServiceBus" version="7.17.5" targetFramework="net48" />

**Comment by ArthurMa1978** [comment]
Hey @liangdaxian , are you inquiring about the Azure.Messaging.ServiceBus library?
[GetSubscriptionsAsync](https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.administration.servicebusadministrationclient.getsubscriptionsasync?view=azure-dotnet)
[UpdateSubscriptionAsync](https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.administration.servicebusadministrationclient.updatesubscriptionasync?view=azure-dotnet)

**Comment by jsquire** [comment]
@liangdaxian:  Please clarify which package and version you're using.

**Comment by liangdaxian** [comment]
hi i think i put it under desc but get trunked:

using  <package id="Azure.Messaging.ServiceBus" version="7.17.5" targetFramework="net48" />

**Comment by jsquire** [comment]
I've confirmed that the autoDeleteOnIdle property is defined in the [service spec](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/servicebus/data-plane/Microsoft.ServiceBus/stable/2021-05/servicebus.json#L1460) and that the payload is being [formatted correctly](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/src/Administration/QueuePropertiesExtensions.cs#L152) by the client.    This looks to be an issue with the Service Bus ATOM service.    

@EldertGrootenboer:  Not sure why this was transferred over to the client repository, but I'm going to send it back, as it requires service investigation.

**Comment by jsquire** [comment]
This issue has been transferred to the Azure Service Bus repository for service team investigation as [#711](https://github.com/Azure/azure-service-bus/issues/711).
