### ISSUE TITLE
[QUERY] how can I see http payload sent to azure ai search ?

### ISSUE THREAD

**Issue by sabbadino** [Azure/azure-sdk-for-net#44450]
### Library name and version

Latest net azure ai search nuget package

### Query/Question

how can I see http payload sent to azure ai search ?

### Environment

Windows ,  net 8

**Comment by sabbadino** [comment]
1)   in startup : var opt = new SearchClientOptions
  {
      Diagnostics =
      {
          IsLoggingContentEnabled = true
      }
  };
  return new SearchIndexClient(new Uri(azureSearchServiceEndpoint), new AzureKeyCredential(azureSearchAdminKey), opt);
  

2) in startup : services.TryAddSingleton<AzureEventSourceLogForwarder>();

3) have  AzureEventSourceLogForwarder injected somewhere and call  .Start(); on it

**Comment by ShivangiReja** [comment]
You can find more information about logging here: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Diagnostics.md.
