### ISSUE TITLE
incomplete doc

### ISSUE THREAD

**Issue by nareshh74** [Azure/azure-sdk-for-net#44468]
### Type of issue

Missing information

### Description

[Enter feedback here]
Looks like this doc - https://learn.microsoft.com/en-us/dotnet/api/system.fabric.health.healthevent.lastwarningtransitionat?view=azure-dotnet#remarks is not complete

![image](https://github.com/Azure/azure-sdk-for-net/assets/13416664/16170229-dcb3-4e0e-9722-c4f9e98db968)

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.fabric.health.healthevent.lastwarningtransitionat?view=azure-dotnet

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/System.Fabric.Health/HealthEvent.xml

### Document Version Independent Id

56779673-4225-88e5-558b-2971b39e9baa

### Article author

@azure-sdk

### Metadata

* ID: 9efca9cc-e3e1-6650-35c0-f027b2f5d1dd 
* Service: **service-fabric**

**Comment by jsquire** [comment]
@ronniegeraghty:  This report is for the `Microsoft.ServiceFabric` package, which is not open source nor maintained in this repository.  Likewise, the service team responsible for the library does not monitor issues here.   Since all docs issues get forwarded to our repo and we have no path to redirect to the team responsible, I'm not sure what the right approach here should be.

//cc: @scottaddie, @danieljurek  for thoughts

**Comment by ronniegeraghty** [comment]
@jsquire,
Looking at the content source for the page I can't find any lists that have three blank items. This might be an issue with how the content source is being rendered on learn. I reached out to the learn team to see.

**Comment by scottaddie** [comment]
This problem can occur when the XML docs are invalid. Example PRs I've opened to fix this problem:
- https://github.com/Azure/azure-sdk-for-net/pull/43628
- https://github.com/dotnet/orleans/pull/8959

**Comment by ronniegeraghty** [comment]
@jsquire & @scottaddie, 
Looks like the docs are related to code in this [repo](https://github.com/microsoft/service-fabric)
Specifically, this [file](https://github.com/microsoft/service-fabric/blob/master/src/prod/src/managed/Api/src/System/Fabric/health/HealthEvent.cs#L74)
Should we try and transfer this issue to that repo?

**Comment by jsquire** [comment]
@ronniegeraghty:  Nice find!   I wasn't aware that it was an open source repo.    This one, we can transfer over.   There are others which are not open source, but the docs issues will still appear here.   We don't have a plan for those today.

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the Service Fabric libraries are maintained as [#1500](https://github.com/microsoft/service-fabric/issues/1500).
