### ISSUE TITLE
APIScan failure on DefaultAzureCredentialOptions several properties

### ISSUE THREAD

**Issue by JRahnama** [Azure/azure-sdk-for-net#44482]
### Library name and version

Azure.Identity v1.11.3

### Describe the bug

APIScan is not able to find documentation for below properties on DefaultAzureCredentialOptions

SharedTokenCacheTenantId, VisualStudioCodeTenantId, VisualStudioTenantId.

We have received several bug reports similar to below

```
Tool: ApiScan: Rule: documentationnotfound (Documentation Not Found). https://aka.ms/apiscan/learnmore?page=protocol%2fdocumentationnotfound.htm
azure.identity!Azure.Identity.DefaultAzureCredentialOptions.set_SharedTokenCacheTenantId is either an undocumented HVP API or the documentation is not discoverable.
```

We were not able to find related source for these properties in published documentation.

### Expected behavior

We would except to find documentation publicly for these properties.
APIScan should be able to find the documentation.

### Actual behavior

```
Tool: ApiScan: Rule: documentationnotfound (Documentation Not Found). https://aka.ms/apiscan/learnmore?page=protocol%2fdocumentationnotfound.htm
azure.identity!Azure.Identity.DefaultAzureCredentialOptions.set_SharedTokenCacheTenantId is either an undocumented HVP API or the documentation is not discoverable.
```

### Reproduction Steps

There is no specific repro steps. You can try finding public documentation for those properties which leads to nowhere.

**Comment by christothes** [comment]
hi @JRahnama - 
These properties are intentionally hidden

**Comment by JRahnama** [comment]
We were able to replace those properties with TenantId. Thank you.
