### ISSUE TITLE
[BUG] Unable to remove linked domain

### ISSUE THREAD

**Issue by yogeshmo** [Azure/azure-sdk-for-net#44489]
### Library name and version

Azure.Communication.Email 1.0.1

### Describe the bug

I'm running into an issue with the Communication .NET Management SDK where I'm not able to unlink a domain from a communication services resource.

### Expected behavior

"LinkedDomains" is a property under the communication resource, and sending out a patch request with an empty LinkedDomains list should remove any existing linked domains from the resource.

### Actual behavior

When using the .NET SDK, It seems like the response from the patch request still contains the linked domain (this should be an empty list).

The response I get back should have an empty list in "LinkedDomains", but it's still contains an item.

![image](https://github.com/Azure/azure-sdk-for-net/assets/46582228/512d389a-a351-44be-84b3-13fef71aa9e7)

Adding a LinkedDomain to the list is working fine. I was also able to remove the linked domain with the JS SDK and by directly making an http request, so it seems like the issue is specifically with the .NET SDK.  I've also tried setting "LinkedDomains" to null, but that gives me a compilation error.

### Reproduction Steps

This is how I'm making the request with the SDK.

```csharp
CommunicationServiceResourcePatch patch = new CommunicationServiceResourcePatch
{
    LinkedDomains = { }
};
CommunicationServiceResource result = await communicationServiceResource.UpdateAsync(patch);
```

**Comment by ArthurMa1978** [comment]
Hey @yogeshmo , as we discussed in teams, please confirm with logging / fiddler that the payload contains
 ```
"linkedDomains": []
```
If so then the client is doing the right thing and I would start to look at the service side. 
if not then I would break on this line here
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/communication/Azure.ResourceManager.Communication/src/Generated/Models/CommunicationServiceResourcePatch.Serialization.cs#L49 .  
The first part of that check is whether or not the underlying instance of LinkedDomains is a ChangeTrackingList which with the way you are constructing it in issue linked in this thread it should not be as you are instantiating it with
{ }
.
