### ISSUE TITLE
[BUG] property "Identity" misses principalId and tenantId

### ISSUE THREAD

**Issue by dw511214992** [Azure/azure-sdk-for-net#44503]
### Library name and version

Azure.ResourceManager.ContainerService 1.2.1

### Describe the bug

The property `Identity` misses principalId and tenantId when get it.
[Code](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/containerservice/Azure.ResourceManager.ContainerService/src/Custom/ContainerServiceManagedClusterData.cs#L63-L79):
```
        [EditorBrowsable(EditorBrowsableState.Never)]
        public ManagedServiceIdentity Identity
        {
            //get; set;
            // Update get once Azure.ResourceManager provide model factory method for ManagedServiceIdentity
            get => ClusterIdentity is null ? default : new ManagedServiceIdentity(ClusterIdentity.ResourceIdentityType);
            set
            {
                if (value is null)
                    ClusterIdentity = null;
                else
                {
                    IDictionary<ResourceIdentifier, UserAssignedIdentity> userAssignedIdentities = new ChangeTrackingDictionary<ResourceIdentifier, UserAssignedIdentity>();
                    if (value.ManagedServiceIdentityType == ManagedServiceIdentityType.UserAssigned || value.ManagedServiceIdentityType == ManagedServiceIdentityType.SystemAssignedUserAssigned)
                        userAssignedIdentities = value.UserAssignedIdentities;
                    ClusterIdentity = new ManagedClusterIdentity(value.PrincipalId, value.TenantId, value.ManagedServiceIdentityType, new ChangeTrackingDictionary<string, ManagedClusterDelegatedIdentity>(), userAssignedIdentities, null);
                }
            }
        }
```

If the ClusterIdentity is set and then I get the Identity, it will returns `new ManagedServiceIdentity(ClusterIdentity.ResourceIdentityType)`, which only contains the ResourceIdentityType, and the principalId and tenantId are missed.

### Expected behavior

When I read the `Identity`, we should get all data from the identity, including principalId and tenantId.

### Actual behavior

When I read the `Identity`, we only get the ResourceIdentityType in it.

### Reproduction Steps

none

**Comment by live1206** [comment]
As offline clarified, `ContainerServiceManagedClusterData.Identity` property has been renamed to [ContainerServiceManagedClusterData.ClusterIdentity](https://github.com/Azure/azure-sdk-for-net/blob/5b8580a95be01bea9f6a33dd6532a9c4a9483c20/sdk/containerservice/Azure.ResourceManager.ContainerService/src/Generated/ContainerServiceManagedClusterData.cs#L172), the user can get everything needed from that instead.
