### ISSUE TITLE
[BUG]: Upgrade Azure.Identity Microsoft.Identity.Client to latest version to resolve security vulnerability

### ISSUE THREAD

**Issue by srini3793** [Azure/azure-sdk-for-net#44548]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.Storage 5.3.0

### Describe the bug

Merlin bot is reporting security incident in azure devops pipeline during PR build run.

Pls upgrade the following packages for immediate resolution

Azure.Identity
Microsoft.Identity.Client

### Expected behavior

Upgrade Azure.Identity Microsoft.Identity.Client to latest version to resolve security vulnerability

### Actual behavior

Azure.Identity Microsoft.Identity.Client is not latest

### Reproduction Steps

Check the dependent package versions

**Comment by seanmcc-msft** [comment]
@srini3793, this issue has been resolved with the release of [Microsoft.Azure.WebJobs.Extensions.Storage 5.3.1](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.Storage/5.3.1)
