### ISSUE TITLE
How can we Enable/Disable APIs and Operations in Azure API Management Using .NET SDK and or in Portal

### ISSUE THREAD

**Issue by fogwildflower** [Azure/azure-sdk-for-net#44554]
### Library name and version

Azure.ResourceManager.ApiManagement 1.1.0

### Query/Question

I'm currently working on a project that involves managing APIs within Azure API Management programmatically using the .NET SDK. However, I couldn't find explicit documentation or examples on how to enable or disable APIs and their operations or individual operations specifically.

Could you please provide guidance or code snippets on how to achieve this functionality using the .NET SDK for Azure API Management? It would be immensely helpful to have clear instructions or references to ensure seamless integration with our existing .NET applications.

**Comment by welovej** [comment]
Hi  @fogwildflower  , this similar question has been asked at this [link](https://learn.microsoft.com/en-us/answers/questions/1351023/how-to-stop-azure-apim-service). 
It does make sense, since the Azure web portal does not provide a clear feature or status indicator for enabling or disabling.

**Comment by fogwildflower** [comment]
> Hi @fogwildflower , this similar question has been asked at this [link](https://learn.microsoft.com/en-us/answers/questions/1351023/how-to-stop-azure-apim-service). It does make sense, since the Azure web portal does not provide a clear feature or status indicator for enabling or disabling.

That mean currently, Azure API Management does not provide a feature to enable or disable APIs or their operations. The available actions are limited to adding, updating, or deleting APIs and operations.

Is there any plan to introduce this feature in the future?

**Comment by welovej** [comment]
@fogwildflower   Sorry for the inconvenience caused. Since we are the SDK team, if you want the new feature, it's better to open an Azure ticket to get support from the service team. Then it will be feasible to introduce this feature into the SDK.
