### ISSUE TITLE
[QUERY] What is happening with EventGridClient class?

### ISSUE THREAD

**Issue by ine8181** [Azure/azure-sdk-for-net#44552]
### Library name and version

Azure.Messaging.EventGrid 4.22.0-beta.1

### Query/Question

In this page:
https://learn.microsoft.com/en-us/answers/questions/1695419/pull-delivery-model-support-in-c-sdk

The documentation is clear that I can use .Net SDK to poll ('pull') from the EventGrid. But the class EventGridClient _only_ exists in the package version 4.22.0-beta.1, and does not seem to have made it into 4.22 or any subsequent versions of the package. 

4.22.0-beta.1 was published 7 months ago, so I'm wondering whether this is going to be a supported feature at all.

Is the feature going to be available in the future? Can you give an indication of when it would be?

If not, the documentation above needs to be revised (or removed) so that it doesn't mislead developers.

**Comment by JoshLove-msft** [comment]
The EventGridClient class split into two separate classes, EventGridSenderClient and EventGridReceiverClient, and was moved into a new library [Azure.Messaging.EventGrid.Namespaces](https://www.nuget.org/packages/Azure.Messaging.EventGrid.Namespaces). Here are some usage samples - https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventgrid/Azure.Messaging.EventGrid.Namespaces/samples/Sample1_Namespaces.md
