### ISSUE TITLE
When will the LUIS Authoring API be released on nuget

### ISSUE THREAD

**Issue by Molotch** [Azure/azure-sdk-for-net#4457]
The LUIS Authoring (and Runtime) API (Microsoft.Azure.CognitiveServices.Language.LUIS.Authoring) isn't published on nuget for some reason. Is there an ETA for when this will be done?

1 day

**Comment by yangyuan** [comment]
Both have been published :)

https://www.nuget.org/packages/Microsoft.Azure.CognitiveServices.Language.LUIS.Runtime
https://www.nuget.org/packages/Microsoft.Azure.CognitiveServices.Language.LUIS.Authoring

**Comment by dsgouda** [comment]
Thanks @yangyuan
