### ISSUE TITLE
infinite lease via break?

### ISSUE THREAD

**Issue by infobrixGit** [Azure/azure-sdk-for-net#44578]
### Type of issue

Other (describe below)

### Description

Please confirm - is 0 means infinite lease ? means will it hold lease forever?? Please confirm
Parameters

breakPeriod
    [Nullable](https://learn.microsoft.com/en-us/dotnet/api/system.nullable-1)<[TimeSpan](https://learn.microsoft.com/en-us/dotnet/api/system.timespan)> 

A [TimeSpan](https://learn.microsoft.com/en-us/dotnet/api/system.timespan) representing the amount of time to allow the lease to remain, which will be rounded down to seconds. If null, the break period is the remainder of the current lease, or zero for infinite leases.

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.blob.cloudblobcontainer.breakleaseasync?view=azure-dotnet-legacy

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Storage.Blob/CloudBlobContainer.xml

### Document Version Independent Id

261b3be9-d35f-98e5-7b7c-5a11ecde3e94

### Article author

@azure-sdk

### Metadata

* ID: abcbaf13-6fd3-2ac2-c388-c2ef28ed2704 
* Service: **azure-storage**

**Comment by jsquire** [comment]
Hi @infobrixGit.  Thanks for reaching out and for your question.  Please be aware that the `Microsoft.Azure.Storage.Blob` package reached end-of-life in March of 2023 and is no longer published nor supported by Microsoft.    We would strongly advise not using this package in your applications and upgrading to the `Azure.Storage.Blobs` package.

Unfortunately, we cannot assist with questions for unsupported packages.
