### ISSUE TITLE
ApiManagement - Adding Api to Product fails, if the product has space

### ISSUE THREAD

**Issue by solankisamir** [Azure/azure-sdk-for-net#4458]
Customer is using Add-AzureRmApiManagementApiToProduct. 

When their ProductId has a space, this command will failed at this error: 
[error]Unable to configure Azure ApiManagement. 'productId' does not match expected pattern '(^[\\w]+$)|(^[\\w][\\w\\-]+[\\w]$)'.

This is a bug in the Swagger spec. The service side does not have any such limitation.

**Comment by dsgouda** [comment]
@solankisamir Please open this issue against the REST spec repo
