### ISSUE TITLE
[FEATURE REQ] Open Telemetry Sample Request

### ISSUE THREAD

**Issue by rapatank** [Azure/azure-sdk-for-net#44587]
### Information

https://learn.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-configuration?tabs=net#connection-string to provide example to support logging all columns in traces table. Currently, it allows only severityLevel, message, EventName and customdimensions.

**Comment by rapatank** [comment]
Would it be possible to share an example of how to log operation_Name and some of the other fields present in the traces table in AppInsights? The example sdk seems to use Microsoft.Extensions.Logging that only supports a few fields like message and customDimensions. Was wondering if it is possible to overwrite the _ResourceId as well.

**Comment by cijothomas** [comment]
> operation_Name and overwrite _ResourceId (which currently is pre-populated)?

These are special fields. There won't be ability to populate them with custom values using `ILogger` API. 

Can you elaborate your end goals, so we can suggest alternates?

**Comment by TimothyMothra** [comment]
I'm consolidating all issues regarding overriding specific fields in the Application Insights schema into another issue to help with tracking. https://github.com/Azure/azure-sdk-for-net/issues/46021

**Comment by rapatank** [comment]
[heart]         Rashmi Patankar reacted to your message:
________________________________
