### ISSUE TITLE
[FEATURE REQ] Support IsStored for any string field in Azure AI Search

### ISSUE THREAD

**Issue by Tornhoof** [Azure/azure-sdk-for-net#44595]
### Library name

Azure.Search.Documents

### Please describe the feature.

In a recent API change (preview), support for not storing vector fields was added.
Please add the same capabilities for any string field. A full text search query should still work if the content is not available, as it's properly indexed.

Why?
I recently tried out Azure AI Search with Vector Embeddings with a sufficiently large amount of documents (40GB of pdfs) and the index size is huge (larger than the actual source documents, it's still indexing). If I query the index content, I see that the chunks are also stored as plain text. I'm aware that for the full RAG experience, the content needs to be supplied to a LLM for further processing.

While it is recommended, e.g. in Elasticsearch to store the source documents in _source, this can be deactivated via stored=true/false in Apache Solr and Elasticsearch to reduce the size of the index. Given that the chunks are actually overlapping segments from the source, the greater-than-source from above makes sense and makes the problem even more annoying, as customers easily have single digits TB of documents.

So I'm looking at options to reduces the size, even though it might reduce functionality.

**Comment by ShivangiReja** [comment]
Currently search service supports `IsStored` property only for vector fields in preview releases. This feature request is specifically for the service team, and the SDK can only incorporate features that are supported by the service. If you have any questions related to the search service, please raise an issue at [Azure Search · Community](https://feedback.azure.com/d365community/forum/9325d19e-0225-ec11-b6e6-000d3a4f07b8). For any SDK-related questions, feel free to create issues on [Azure SDK for .NET Github](https://github.com/Azure/azure-sdk-for-net/issues).
