### ISSUE TITLE
Can I rely on AzureWebJobs:extensions:ServiceBus options?

### ISSUE THREAD

**Issue by Aleksey-Kudryavtsev** [Azure/azure-sdk-for-net#44606]
### Library name and version

Microsoft.Azure.Webjobs.Extensions.Servicebus 5.16.1

### Query/Question

Hello,

I couldn't find any documentation for setting ServiceBusOptions in app configuration, but looking at the code and debugging it I found that I can place the options under AzureWebJobs:extensions:ServiceBus e.g. AzureWebJobs:extensions:ServiceBus:MessageHandlerOptions:MaxConcurrentCalls.

Can I rely on these settings to stay the same and not change in future versions?

Thanks,
Aleksey

### Environment

Azure AppService, .net 8

**Comment by jsquire** [comment]
Hi @Aleksey-Kudryavtsev.   Thanks for reaching out.   The documentation for configuration of the Service Bus extensions will correlate to the `host.json` settings for Azure Functions, which are documented [here](https://learn.microsoft.com//azure/azure-functions/functions-bindings-service-bus?tabs=isolated-process%2Cextensionv5%2Cextensionv3&pivots=programming-language-csharp#hostjson-settings).   

These options will continue to evolve in an additive way over time.  Unless there are extreme circumstances, we do not make breaking changes, so you can depend on these being stable.
