### ISSUE TITLE
[QUERY] How can we use configuration when registering an Azure client

### ISSUE THREAD

**Issue by cjablonski76** [Azure/azure-sdk-for-net#44625]
### Library name and version

Azure.Messaging.ServiceBus 7.17.5

### Query/Question

Is there a way to register a new `ServiceBusClient` while depending on `IServiceProvider` when calling the `builder.AddServiceBusClient*()` methods?
I am trying to utilize the `AddServiceBus*` methods to register my client objects, but it does not appear there is an overload that will allow us to access `IServiceProvider`, am I missing something?

I am currently just doing:
```csharp
serviceCollection.AddAzureClients(builder =>
{
    builder.AddClient<ServiceBusClient, ServiceBusClientOptions>((options, provider) =>
    {
        var config = provider.GetRequiredService<IOptions<MyConfigClass>>();
        ...
        return new ServiceBusClient(...);
    }
}
```

I would prefer to be able to use the `builder.AddServiceBusClient*` methods though, except there is no overload that will give me access to the `provider` object.
If I stick to the example above, will my instances still be cleaned up and managed properly for me?

**Comment by jsquire** [comment]
Hi @cjablonski76.   You are correct in that there is no overload that injects an `IServiceProvider` and the factory approach that you're using is the recommended way to do so.   The resulting factory is invoked on-demand and the resulting client instance is cached and cleaned up.  

If your goal is to provide configuration to the client or overload its options, there are other more direct ways to do so.

For example, to create a client based on configuration, the recommended approach is:

```csharp
var appBuilder = WebApplication.CreateBuilder(args);
var serviceCollection = appBuilder.Services;

serviceCollection.AddAzureClients(builder =>
{
    builder.AddServiceBusClient(appBuilder.Configuration.GetSection("ServiceBus");
}
```

Overriding client options can be done in the following way, if you'd like to avoid the factory:

```csharp
var appBuilder = WebApplication.CreateBuilder(args);
var serviceCollection = appBuilder.Services;

serviceCollection.AddAzureClients(builder =>
{
    builder
        .AddServiceBusClientWithNamespace("<your_namespace>.servicebus.windows.net");
        .ConfigureOptions(options =>
        {
            var myOptions = new MyOptions();
            appBuilder.Configuration["MyOptions"].Bind(myOptions);

            options.TransportType = myOptions.ServiceBusTransportType;
        });
}
```

More discussion and examples can be found in [Dependency injection with the Azure SDK for .NET](https://learn.microsoft.com/dotnet/azure/sdk/dependency-injection?tabs=web-app-builder).

**Comment by jsquire** [comment]
@cjablonski76:

> You're saying there's nothing wrong with the way I'm currently doing it though (i.e. with builder.AddClient<ServiceBusClient, ServiceBusClientOptions>)?

Correct.  There's nothing wrong with what you're currently doing, and it seems like the best approach for your specific scenario of not knowing the configuration that you want upfront.   What you're doing will register the client and ensure proper cleanup.

**Comment by cjablonski76** [comment]
Awesome, thanks for the help!
