### ISSUE TITLE
ManagedIdentityCredential authentication failed: Response from Managed Identity was successful, but the operation timed out prior to completion[QUERY]

### ISSUE THREAD

**Issue by VigneashSelvaraj** [Azure/azure-sdk-for-net#44622]
### Library name and version

Azure.Identity.1.11.4

### Query/Question

I run below code from Azure App service to connect Azure key vault and read few information, though the managed Identity is properly set in both App service and key vault having proper access policy.

I still see below error “**ManagedIdentityCredential authentication failed: Response from Managed Identity was successful, but the operation timed out prior to completion. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/managedidentitycredential/troubleshoot at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage, Boolean isCredentialUnavailable) at Azure.Identity.ManagedIdentityCredential.<GetTokenImplAsync>d__16.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Azure.Identity.ManagedIdentityCredential.<GetTokenAsync>d__14.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at Azure.Identity.DefaultAzureCredential.<GetTokenFromSourcesAsync>d__14.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Threading.Tasks.ValueTask`1.get_Result() at Azure.Identity.DefaultAzureCredential.<GetTokenImplAsync>d__12.MoveNext() --- End of stack trace from previous location where exception was thrown --- at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage, Boolean isCredentialUnavailable) at Azure.Identity.DefaultAzureCredential.<GetTokenImplAsync>d__12.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Azure.Identity.DefaultAzureCredential.<GetTokenAsync>d__11.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Identity.Web.ManagedIdentityClientAssertion.<GetClientAssertion>d__2.MoveNext() --- End of stack t”race from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Identi”**

```
private async Task<string> GetTokenAsync(string authority, string resource, string scope)
{
    string authToken = string.Empty;
    string[] scopes = new string[] { $"{resource}/.default" };
    AuthenticationResult result = null;
    try
    {


            Func<string> msiTokenGetter = () => new ManagedIdentityClientAssertion(MsiClientId).GetSignedAssertion(CancellationToken.None).GetAwaiter().GetResult();
            IConfidentialClientApplication clientApp = ConfidentialClientApplicationBuilder
                            .Create(ClientId) 
                            .WithClientAssertion(msiTokenGetter)
                            .WithAuthority(authority)
                            .Build();
        

            result = await clientApp.AcquireTokenForClient(scopes)
                                        .WithSendX5C(true) //this is crucial!
                                        .ExecuteAsync();

            authToken =  result.AccessToken;
        return authToken;
    }
    catch (Exception exp)
    {
        var ex = new Exception(string.Format("Authentication failed for {0}", ClientId), exp);
        throw ex;
    }
}
```

**Comment by christothes** [comment]
Hi @VigneashSelvaraj - 
Your application is using Microsoft.Identity.Web (which happens to use Azure.Identity internally for some scenarios). Please open this issue in their repo for assistance https://github.com/AzureAD/microsoft-identity-web/issues
