### ISSUE TITLE
Scopes not being included by default in the OpenTelemetry distro may be insufficiently documented

### ISSUE THREAD

**Issue by NetherGranite** [Azure/azure-sdk-for-net#44621]
Looking at [this comment](https://github.com/Azure/azure-sdk-for-net/issues/42177#issuecomment-1996055961_), it sounds like there was intent to document the fact that using the OpenTelemetry distro for Azure Monitor doesn't include scopes by default was going to be documented more clearly, but on both [the intro page for the distro](https://learn.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-enable?tabs=aspnetcore) and the [OpenTelemetry configuration guide](https://learn.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-configuration?tabs=aspnetcore), scopes aren't mentioned at all.

Not being sure why scopes aren't included in the OpenTelemetry method is currently a very easy trap to fall into and very hard to find information on, especially since there's no formal part of the fluent API for configuring `OpenTelemetryLoggerOptions`. On that last note, it may be very helpful to add an overload of `.AddOpenTelemetry()` that takes an `Action<OpenTelemetryLoggerOptions>`.

**Comment by TimothyMothra** [comment]
Hello @NetherGranite ,
I just wanted to chime in and share that the following setting works with our Distro.

```csharp
builder.Services.Configure<OpenTelemetryLoggerOptions>(options =>
{
    options.IncludeScopes = true;
});
```

I'm following up with our docs team to get this tracked.
