### ISSUE TITLE
https://www.facebook.com/nickryanpedralba?mibextid=LQQJ4d

### ISSUE THREAD

**Issue by JovRyan1968** [Azure/azure-sdk-for-net#44646]
### Type of issue

Other (describe below)

### Description

My old facebook account was hacked i dont have the access please can you remove the gmail was link in my old facebook account thanks

[Enter feedback here]

### Page URL

https://www.facebook.com/nickryanpedralba?mibextid=LQQJ4d

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/ns-Microsoft.AspNetCore.Builder.xml

### Document Version Independent Id

0004d424-fe13-43ee-87c5-e3e5133a4390

### Article author

@azure-sdk

### Metadata

* ID: 8b9df84f-f19c-4e58-6899-75d86d5d465a

**Comment by jsquire** [comment]
Spam
