### ISSUE TITLE
Using MSI in Service Fabric

### ISSUE THREAD

**Issue by mrashid-sci** [Azure/azure-sdk-for-net#4465]
Is there a guide on how to use the MSI in a Service Fabric Application?

**Comment by varunsh-msft** [comment]
What sample are you following now? It will help to know so we can modify that sample to use MSI.

**Comment by mrashid-sci** [comment]
Initially I followed the document provided here.

https://docs.microsoft.com/en-us/azure/app-service/app-service-managed-service-identity

I couldn't find anything specific to Service Fabric, so I tried using the same Microsoft.Azure.Services.AppAuthentication. When I tried to run it, I get the following error on my development machine.

Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/047b7906-bd8a-49e1-a494-731805d5c289. Exception Message: Tried the following 3 methods to get an access token, but none of them worked.\r\nParameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/047b7906-bd8a-49e1-a494-731805d5c289. Exception Message: Tried to get token using Managed Service Identity. Unable to connect to the Managed Service Identity (MSI) endpoint. Please check that you are running on an Azure resource that has MSI setup.\r\nParameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/047b7906-bd8a-49e1-a494-731805d5c289. Exception Message: Tried to get token using Visual Studio. Access token could not be acquired. Visual Studio Token provider file not found at \"C:\\Windows\\system32\\config\\systemprofile\\AppData\\Local\\.IdentityService\\AzureServiceAuth\\tokenprovider.json\"\r\nParameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/047b7906-bd8a-49e1-a494-731805d5c289. Exception Message: Tried to get token using Azure CLI. Access token could not be acquired. Traceback (most recent call last):\r\n  File \"runpy.py\", line 193, in _run_module_as_main\r\n  File \"runpy.py\", line 85, in _run_code\r\n  File \"C:\\Users\\trdai\\AppData\\Local\\Temp\\pip-install-972ovukd\\azure-cli\\azure\\cli\\__main__.py\", line 32, in <module>\r\n  File \"C:\\Users\\trdai\\AppData\\Local\\Temp\\pip-install-972ovukd\\azure-cli-core\\azure\\cli\\core\\__init__.py\", line 492, in get_default_cli\r\n  File \"C:\\Users\\trdai\\AppData\\Local\\Temp\\pip-install-972ovukd\\azure-cli-core\\azure\\cli\\core\\__init__.py\", line 49, in __init__\r\n  File \"C:\\Users\\trdai\\AppData\\Local\\Temp\\pip-install-972ovukd\\knack\\knack\\util.py\", line 38, in ensure_dir\r\n  File \"os.py\", line 220, in makedirs\r\nPermissionError: [WinError 5] Access is denied: 'C:\\\\Windows\\\\system32\\\\config\\\\systemprofile\\\\.azure'\r\n\r\n"

So I am assuming there is some more configuration that needs to be done here for MSI to work under local service fabric cluster?

**Comment by MaxWilson** [comment]
I followed the directions at varun's link, and enabled MSI on the scale set for my cluster's node types, but I get an error about "MSI ResponseCode: BadRequest" and "Identity not found".

```
Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderException: Parameters: Connection String: [No connection string specified], Resource: http
s://management.azure.com/, Authority: . Exception Message: Tried the following 4 methods to get an access token, but none of them worked.
Parameters: Connection String: [No connection string specified], Resource: https://management.azure.com/, Authority: . Exception Message: Tried to get token usi
ng Managed Service Identity. Access token could not be acquired. MSI ResponseCode: BadRequest, Response: {"error":"invalid_request","error_description":"Identit
y not found"}
Parameters: Connection String: [No connection string specified], Resource: https://management.azure.com/, Authority: . Exception Message: Tried to get token usi
ng Visual Studio. Access token could not be acquired. Visual Studio Token provider file not found at "C:\Users\poservice\AppData\Local\.IdentityService\AzureSer
viceAuth\tokenprovider.json"
Parameters: Connection String: [No connection string specified], Resource: https://management.azure.com/, Authority: . Exception Message: Tried to get token usi
ng Azure CLI. Access token could not be acquired. 'az' is not recognized as an internal or external command, operable program or batch file.
```

**Comment by varunsh-msft** [comment]
@shahabhijeet , can you please close this issue?
