### ISSUE TITLE
[BUG] Azure.Monitor.OpenTelemetry.Exporter EventId duplicate key exception causes LogRecord to be dropped

### ISSUE THREAD

**Issue by DaanWasscher** [Azure/azure-sdk-for-net#44653]
### Library name and version

Azure.Monitor.OpenTelemetry.Exporter 1.3.0

### Describe the bug

When a LogRecord has an EventId specified and the LogRecord AttributeData dictionary already contains a key EventId then the LogsHelper.GetMessageAndSetProperties method causes a DuplicateKey exception. Which eventually leads to the whole LogRecord getting dropped.

This problem also occurs with attribute key "EventName".

In my project I am using Serilog. Serilog adds (if set on the log entry) EventId and EventName to the log state which causes it to end up in the LogRecord AttributeData dictionary. The LogsHelper then without checking whether it exists adds EventId again to the AttributeData dictionary causing an exception.

https://github.com/Azure/azure-sdk-for-net/blob/Azure.Monitor.OpenTelemetry.Exporter_1.3.0/sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/src/Internals/LogsHelper.cs

### Expected behavior

When the attribute dictionary of the LogRecord already contains EventId or EventName then the LogsHelper doesnt try add it again.

### Actual behavior

LogsHelper causes a duplicate key exception and the LogRecord is dropped never gets exported.

### Reproduction Steps

-

**Comment by cijothomas** [comment]
https://github.com/Azure/azure-sdk-for-net/blob/Azure.Monitor.OpenTelemetry.Exporter_1.3.0/sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/src/Internals/LogsHelper.cs#L112 There are places where we de-dup, but eventid/name are not in that path :(
