### ISSUE TITLE
[BUG] Synonym Maps >> Index, "modelName" Error

### ISSUE THREAD

**Issue by richchapler** [Azure/azure-sdk-for-net#44675]
### Library name and version

Azure.Search.Documents 11.6.0-beta.4

### Describe the bug

When attempting to programmatically create a synonym map on Azure AI Search Index, configured with a vectorizer, an error indicates that the 'modelName' parameter is required in API version '2024-05-01-preview'.

### Expected behavior

The synonym map should be created and added to the specified column.

### Actual behavior

The following error is encountered:

Azure.RequestFailedException
  HResult=0x80131500
  Message=The request is invalid. Details: definition : Error in Vectorizer 'myVectorizer' : 'modelName' parameter is required in API version '2024-05-01-preview'.
Status: 400 (Bad Request)

Content:
{"error":{"code":"","message":"The request is invalid. Details: definition : Error in Vectorizer 'myVectorizer' : 'modelName' parameter is required in API version '2024-05-01-preview'."}}

Headers:
Cache-Control: no-cache,no-store
Pragma: no-cache
Server: Microsoft-IIS/10.0
client-request-id: a637f2e1-0fb7-4012-916c-1c193f2020a3
x-ms-client-request-id: a637f2e1-0fb7-4012-916c-1c193f2020a3
request-id: a637f2e1-0fb7-4012-916c-1c193f2020a3
elapsed-time: 78
Strict-Transport-Security: REDACTED
Date: Wed, 19 Jun 2024 18:10:15 GMT
Content-Length: 187
Content-Type: application/json; charset=utf-8
Content-Language: REDACTED
Expires: -1

  Source=Azure.Search.Documents
  StackTrace:
   at Azure.Search.Documents.IndexesRestClient.<CreateOrUpdateAsync>d__15.MoveNext()
   at Azure.Search.Documents.Indexes.SearchIndexClient.<CreateOrUpdateIndexAsync>d__48.MoveNext()
   at AzureSolutions.Helpers.AISearch.SynonymMap.<Create>d__0.MoveNext() in C:\Users\rchapler\OneDrive - Microsoft\repos\AzureSolutions_Helpers\AzureSolutions\Helpers\AISearch\SynonymMap.cs:line 36
   at Program.<AISearch_Create_SynonymMap>d__9.MoveNext() in C:\Users\rchapler\OneDrive - Microsoft\repos\AzureSolutions_Helpers\Tester\Program.cs:line 201
   at Program.<Main>d__0.MoveNext() in C:\Users\rchapler\OneDrive - Microsoft\repos\AzureSolutions_Helpers\Tester\Program.cs:line 12
...specifically at line:

await Index.Client(AISearch_Name,AISearch_Key).CreateOrUpdateIndexAsync(index.Value);

### Reproduction Steps

I have a Helper Class named SynonymMap.cs which includes Create:

public static async Task Create(
   string AISearch_Name,
   string AISearch_Key,
   string AISearch_Index_Name,
   string AISearch_SynonymMap_Name,
   string SynonymsJson_Path
   )
{
   string j = File.ReadAllText(Path.GetFullPath(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, SynonymsJson_Path)));
   var d = JsonSerializer.Deserialize<List<List<string>>>(json: j, options: new() { PropertyNameCaseInsensitive = true });
   string synonyms = d == null ? "" : string.Join("\n", d.Select(synonymGroup => string.Join(", ", synonymGroup)));
   var sm = new Azure.Search.Documents.Indexes.Models.SynonymMap(AISearch_SynonymMap_Name, synonyms);

   await Index.Client(AISearch_Name,AISearch_Key).CreateOrUpdateSynonymMapAsync(sm);

   /* ************************* Add to Column in AI Search Index */

   var index = Index.Client(AISearch_Name,AISearch_Key).GetIndex(AISearch_Index_Name);
   var field = index.Value.Fields.FirstOrDefault(f => f.Name == "merged_content");
   if (field != null)
   {
       field.SynonymMapNames.Add(sm.Name);
       await Index.Client(AISearch_Name,AISearch_Key).CreateOrUpdateIndexAsync(index.Value);
   }
}

### Environment

Azure.Search.Documents 11.6.0-beta.4

**Comment by ShivangiReja** [comment]
Thanks for reaching out, and we regret that you're experiencing difficulties. Based on the error, it seems like you are missing the "ModelName" in your vectorizer, which is required by the service. This omission is likely causing the service to throw the error. Please refer to the samples on how to create an index with a vectorizer [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/samples/Sample07_VectorSearch_UsingVectorizableTextQuery.md#create-a-vector-index).

**Comment by richchapler** [comment]
Shivangi, please don't close out the bug without confirmation. Model Number cannot be applied programmatically without throwing an error; from my chat on this topic with Gia:

[5:16 AM] Rich Chapler
This is the error

Error details: {"error":{"code":"","message":"The request is invalid. Details: The property 'modelName' does not exist on type 'Microsoft.Azure.Search.V2023_10_01_Preview.AzureOpenAIParameters'. Make sure to only use property names that are defined by the type."}}
[5:17 AM] Rich Chapler
this is the part of the object used to create the definition that includes modelName

                    vectorizers = new[] {
                                new {
                                    name = "myVectorizer",
                                    kind = "azureOpenAI",
                                    azureOpenAIParameters = new {
                                        resourceUri = $"https://{oaic.OpenAI_Name}.openai.azure.com",
                                        apiKey = oaic.OpenAI_Key,
                                        modelName = "experimental",
                                        deploymentId = oaic.OpenAI_Deployment_Embedding
                                    }
                                }
                            },

**Comment by mattgotteiner** [comment]
Hi @richchapler ,

Unfortunately I can't reproduce the issue. Can you please try the following code snippet and see if it works for you?

```csharp
using Azure.Search.Documents.Indexes;
using Azure.Identity;
using Azure.Search.Documents.Indexes.Models;

Environment.SetEnvironmentVariable("AZURE_SEARCH_ENDPOINT", "your-search-service-endpoint");
Environment.SetEnvironmentVariable("AZURE_OPENAI_ENDPOINT", "your-openai-endpoint");

var client = new SearchIndexClient(
    endpoint: new Uri(Environment.GetEnvironmentVariable("AZURE_SEARCH_ENDPOINT")),
    tokenCredential: new DefaultAzureCredential());

await client.CreateOrUpdateSynonymMapAsync(new SynonymMap("mysynonymmap", "USA, United States, United States of America"));

await client.CreateOrUpdateIndexAsync(
    index: new SearchIndex(name: "myindex")
    {
        Fields = {
            new SearchField("id", SearchFieldDataType.String) { IsKey = true },
            new SearchableField("content") { SynonymMapNames = { "mysynonymmap" } },
            new VectorSearchField("vector", vectorSearchDimensions: 3072, vectorSearchProfileName: "myprofile")
        },
        VectorSearch = new VectorSearch
        {
            Profiles = {
                new VectorSearchProfile(name: "myprofile", algorithmConfigurationName: "hnsw")
                {
                    Vectorizer = "myvectorizer"
                }
            },
            Algorithms = { new HnswAlgorithmConfiguration(name: "hnsw") },
            Vectorizers = {
                new AzureOpenAIVectorizer(name: "myvectorizer")
                {
                    AzureOpenAIParameters = new AzureOpenAIParameters
                    {
                        ResourceUri = new Uri(Environment.GetEnvironmentVariable("AZURE_OPENAI_ENDPOINT")),
                        DeploymentId = "text-embedding-3-large",
                        // Removing the following line results in the error
                        // {"error":{"code":"","message":"The request is invalid. Details: definition : Error in Vectorizer 'myvectorizer' : 'modelName' parameter is required in API version '2024-05-01-preview'."}}
                        ModelName = "text-embedding-3-large"
                    }
                }
            },
        }
    });
```

**Comment by mattgotteiner** [comment]
Update: Worked with Rich offline, the project is not using the SDK, it's using a custom REST API adapter which needs to be manually updated.
