### ISSUE TITLE
ARM IntelliSense Bug: Use of deployment().name in uniqueString occures Error

### ISSUE THREAD

**Issue by abeckDev** [Azure/azure-sdk-for-net#4468]
Hi there, 

I discovered some strange behaviour while I wrote an Azure Resource Manager (ARM) Template with a uniqueString.

The [Documentation](https://docs.microsoft.com/de-de/azure/azure-resource-manager/resource-group-template-functions-string?toc=%2fazure%2ftemplates%2ftoc.json&bc=%2Fazure%2Ftemplates%2Fbreadcrumb%2Ftoc.json#remarks-2) said that I can create a unique string with calling the uniqueString ARM function and giving them the ResourceGroupId and the DeploymentName like this:

```json
"variables": {
    "mcosDeploymentId": "[uniqueString(resourceGroup().id, deployment().name)]"
  },
```

But when I wrote that code Visual Studio will mark the ".name" as an error with the following Error Message: 
> A property of 'deployment' must be one of the following: templateLink, template, parameters, mode, provisioningState

This is some strange behaviour because I use the deployment().name as an parameter. So I tried to deploy the template via Azure Portal and everything worked as expected. 

So there might be an Issue within the IntelliSense of the Azure SDK for Visual Studio.

### Visual Studio 
Visual Studio Enterprise 2017
Version 15.7.4

### Microsoft Azure Tools
Version 2.9

**Comment by StephenWeatherford** [comment]
This has been fixed in Visual Studio.  If you have an Internet connection, you should see the fix after one or possibly two restarts of Visual Studio.

**Comment by abeckDev** [comment]
Thank you @StephenWeatherford for taking care of this one!
