### ISSUE TITLE
[BUG] EntityRecognitionSkill is deprecated, but EntityRecognitionSkillV3 is not public

### ISSUE THREAD

**Issue by Volkmire** [Azure/azure-sdk-for-net#44725]
### Library name and version

Azure.Search.Documents 11.6.0-beta.4

### Describe the bug

I'm trying to check out document indexers and though it would be cool to try EntityRecognitionSkill. I've defined a skillset configuration, but when I tried to push it configuration, I got the following error:
```
Azure.RequestFailedException: Skillset 'docs-v1-skillset' contains a skill of type 'Microsoft.Skills.Text.EntityRecognitionSkill' which is not supported in this API version. Refer https://go.microsoft.com/fwlink/?linkid=2036733 for details and recommendations

Status: 400 (Bad Request)

Content:
{"error":{"code":"","message":"Skillset 'docs-v1-skillset' contains a skill of type 'Microsoft.Skills.Text.EntityRecognitionSkill' which is not supported in this API version. Refer https://go.microsoft.com/fwlink/?linkid=2036733 for details and recommendations"}}
```

Reading the linked article diagonally, I found that EntityRecognitionSkill is deprecated, but there is EntityRecognitionSkillV3. Unfortunately, I'm unable to reference the type from the library, because it is marked as internal.

I'm also unable to recreate v3 skill, since SearchIndexerSkill has no public constructors exposed.

Here's a workaround I'm currently using which allows me to create a skillset:
``` csharp
typeof(EntityRecognitionSkill)
            .GetProperty("ODataType", BindingFlags.Instance | BindingFlags.NonPublic)!
            .SetValue(skill, "#Microsoft.Skills.Text.V3.EntityRecognitionSkill");
```

### Expected behavior

EntityRecognitionSkillV3 is public and able to be referenced from client code.

### Actual behavior

EntityRecognitionSkillV3 is internal and blocked from referencing by client code.

### Reproduction Steps

``` csharp
private static EntityRecognitionSkillV3 CreatePersonsRecognitionSkill() =>
        new(
            new List<InputFieldMappingEntry>
            {
                new("text")
                {
                    Source = "/document/pages/*"
                }
            },
            new List<OutputFieldMappingEntry>
            {
                new("persons")
            })
        {
            Categories =
            {
                "Person"
            }
        };
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ShivangiReja** [comment]
Hi @Volkmire, V1 is deprecated. In the `EntityRecognitionSkill` constructor, you can pass version V3 as a third parameter:

```csharp
var entityRecognitionSkill = new EntityRecognitionSkill(inputs, outputs, EntityRecognitionSkill.SkillVersion.V3);
```

**Comment by Volkmire** [comment]
> Hi @Volkmire, V1 is deprecated. In the `EntityRecognitionSkill` constructor, you can pass version V3 as a third parameter:
> 
> ```cs
> var entityRecognitionSkill = new EntityRecognitionSkill(inputs, outputs, EntityRecognitionSkill.SkillVersion.V3);
> ```

Hah. Completely missed that one, thanks. 
Although I do wonder why have v3 typed in the first place then? Didn't even try to check for it once I saw that type was there.

**Comment by Volkmire** [comment]
> Hi @Volkmire, V1 is deprecated. In the `EntityRecognitionSkill` constructor, you can pass version V3 as a third parameter:
> 
> ```cs
> var entityRecognitionSkill = new EntityRecognitionSkill(inputs, outputs, EntityRecognitionSkill.SkillVersion.V3);
> ```

Hah. Completely missed that one, thanks. 
Although I do wonder why have v3 typed in the first place then? Didn't even try to check for it once I saw that type was there.

**Comment by ShivangiReja** [comment]
The `EntityRecognitionSkillV3` type is auto-generated from the search service specification. Since we have `SkillVersion.V3`, the specific type was not needed for public use. Therefore, we made it internal within the SDK.
