### ISSUE TITLE
The pagesize parameter is not taken effect during the pageable operation

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/azure-sdk-for-net#44735]
This issue was found in this [PR](https://github.com/Azure/azure-sdk-for-net/pull/44571/commits/97b6a43bfc7f986e618b435aa5e6f814f64eaeae#diff-8e7ca83dfffe40890d0e92dd38c5c655b96bee301eb747c34975ac5ade44b577) when correcting the format of `maxpagesize` parameter of the pageable operations from `string` to `int`. 
From the code, the parameter `maxpagesize` isn't passed correctly to the delegate func:
![image](https://github.com/Azure/azure-sdk-for-net/assets/20514459/b835936e-4653-4ac8-af34-2d8bbeafc58e)
Then the test failed, as the maxpagesize is missing in the query parameter:
![image](https://github.com/Azure/azure-sdk-for-net/assets/20514459/34fbf117-f7d1-40af-9ea2-d4b6166c685a)

After digging into the code, the problem is not caused by the delegate func, but the `GeneratorPageableHelpers.CreatePageable`, which doesn't have a `pagesize` parameter:
![image](https://github.com/Azure/azure-sdk-for-net/assets/20514459/eae5b115-fb7d-4268-ac24-f2a102cc9dfc)
However, the `PageableHelpers.PageableImplementation` has  a `pagesize` parameter:
![image](https://github.com/Azure/azure-sdk-for-net/assets/20514459/9f33f4d6-5da6-4937-8165-26ab6dd643dc)

So the fixing should take 2 steps:
1. Add a overloading function which exposes the `pagesize` parameter, and pass it to `PageableHelpers.PageableImplementation`.
2. Fix the CodeGen to support it.

**Comment by welovej** [comment]
regen PR: https://github.com/Azure/azure-sdk-for-net/pull/47669
