### ISSUE TITLE
KeyVault: Reference documentation for SecretBundle.Id Property unclear

### ISSUE THREAD

**Issue by CamSoper** [Azure/azure-sdk-for-net#4474]
Hi there! I'm the docs author at the [Azure .NET SDK docs site](https://docs.microsoft.com/dotnet/azure), and a customer submitted the following issue with documentation generated from the `///` comments in your API. Please be sure to @ them in your response. Thanks! 

@lukos commented on [Thu Jun 07 2018](https://github.com/Azure/azure-docs-sdk-dotnet/issues/669)

Is this referring to the "version" as displayed on the portal or the entire URL that is displayed as the "Secret Identifier" in the portal when you click on a secret?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2452c2e7-52f7-592d-2752-054c6e31c817
* Version Independent ID: c81ed9e3-5d8e-6fcf-7655-3cefa0cfd592
* Content: [SecretBundle.Id Property (Microsoft.Azure.KeyVault.Models)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.keyvault.models.secretbundle.id?view=azure-dotnet#Microsoft_Azure_KeyVault_Models_SecretBundle_Id)
* Content Source: [xml/Microsoft.Azure.KeyVault.Models/SecretBundle.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.KeyVault.Models/SecretBundle.xml)
* Service: **key-vault**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by heaths** [comment]
These packages are deprecated. Please update to Azure.Security.KeyVault.* packages, which have migration guides available next to our README.md files as MigrationGuide.md.
