### ISSUE TITLE
Batch: CloudServiceConfiguration.OsFamily property ref doc remarks needs formatting

### ISSUE THREAD

**Issue by CamSoper** [Azure/azure-sdk-for-net#4475]
Hi there! I'm the docs author at the [Azure .NET SDK docs site](https://docs.microsoft.com/dotnet/azure), and a customer submitted the following issue with documentation generated from the `///` comments in your API. Please be sure to @ them in your response. Thanks! 

@Mikhail-Pranovich commented on [Thu Jun 07 2018](https://github.com/Azure/azure-docs-sdk-dotnet/issues/673)

It's great that in Remarks there is a list of values and corresponding names. However it would be easier if it was formatted properly with newlines in between different OS entries.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efc66629-0be3-ad72-843c-1aa87cdeabe7
* Version Independent ID: 08524449-919b-6f0a-512b-ee65add3545f
* Content: [CloudServiceConfiguration.OsFamily Property (Microsoft.Azure.Batch.Protocol.Models)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.batch.protocol.models.cloudserviceconfiguration.osfamily?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Batch.Protocol.Models/CloudServiceConfiguration.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Batch.Protocol.Models/CloudServiceConfiguration.xml)
* Service: **batch**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by matthchr** [comment]
@shahabhijeet - This is fixed now

**Comment by CamSoper** [comment]
Thanks for the assist, @matthchr, and thanks for logging the issue, @Mikhail-Pranovich !
