### ISSUE TITLE
[FEATURE REQ] SqlDatabaseResource.ExportAsync() / DatabaseExportDefinition to allow Managed Identity

### ISSUE THREAD

**Issue by johnburgato** [Azure/azure-sdk-for-net#44763]
### Library name

Azure.ResourceManager.Sql

### Please describe the feature.

Currently, the DatabaseExportDefinition class constructor will only accept an Azure Storage access key and SQL Server username and password.

Two of the recommendations from Microsoft Defender for Cloud are: "Storage accounts should prevent shared key access" and "Azure SQL Database should have Azure Active Directory Only Authentication enabled". Both of these are considered "critical" recommendations.

We have a WebJob that triggers a database export each night, which I don't think is an un-common scenario. With the export functionality as it is, we could not possibly achieve the two recommendations of Microsoft Defender for Cloud. This seems especially important on the destination storage account, because it contains customer data in .bacpac files not protected in any other way.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi @johnburgato , .NET SDK is auto-generated from service swagger, if you need service to support the Export operation with ManagedIdentity, you could [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) to get further help.
