### ISSUE TITLE
Data Factory: PipelineResource.Annotations property reference documentation unclear

### ISSUE THREAD

**Issue by CamSoper** [Azure/azure-sdk-for-net#4476]
Hi there! I'm the docs author at the [Azure .NET SDK docs site](https://docs.microsoft.com/dotnet/azure), and a customer submitted the following issue with documentation generated from the `///` comments in your API. Please be sure to @ them in your response. Thanks! 

@don4of4 commented on [Tue Jun 05 2018](https://github.com/Azure/azure-docs-sdk-dotnet/issues/665)

Is this a list of strings?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7eab420-829e-48c7-fdf1-1363e7c5f385
* Version Independent ID: 5356973b-bdac-4b16-7bb4-3fafcc5efcc6
* Content: [PipelineResource.Annotations Property (Microsoft.Azure.Management.DataFactory.Models)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.datafactory.models.pipelineresource.annotations?view=azure-dotnet#Microsoft_Azure_Management_DataFactory_Models_PipelineResource_Annotations)
* Content Source: [xml/Microsoft.Azure.Management.DataFactory.Models/PipelineResource.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.DataFactory.Models/PipelineResource.xml)
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by garethjensen** [comment]
Sooo.... what is this a list of?

**Comment by aamalvea** [comment]
Per the documentation this is an IList<Object>
