### ISSUE TITLE
Azure AI Translation Text Samples Issue

### ISSUE THREAD

**Issue by zhangjiale-64** [Azure/azure-sdk-for-net#44779]
1.
**Section** [link](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/translation/Azure.AI.Translation.Text/tests/Samples/Sample0_CreateClient.cs#L23):
![image](https://github.com/Azure/azure-sdk-for-net/assets/141405558/77514015-5761-4ab6-8c31-42adcb5c0e9e)

**Reason**: 
When running unit tests, an error "Method has non-void return value, but no result is expected" occurs.

**Suggestion**:
Change the return type from "TextTranslationClient" to "void".

2.
**Section** [link](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/translation/Azure.AI.Translation.Text/tests/Samples/Sample0_CreateClient.cs#L145):
![image](https://github.com/Azure/azure-sdk-for-net/assets/141405558/70570b17-c2e0-4a55-9038-1827a74b0d2f)

**Reason**: 
When running unit tests, an error "Async test methods must have a non-void return type" occurs.

**Suggestion**:
Change the return type of the `HandleBadRequestAsync` method from "void" to "Task".

@scottaddie , @jsquire , @mayurid and @cpoulain for notification.

**Comment by v-xuto** [comment]
This issue has been fixed by https://github.com/Azure/azure-sdk-for-net/pull/45153. Close it.
