### ISSUE TITLE
Automation: Reference documentation unclear

### ISSUE THREAD

**Issue by CamSoper** [Azure/azure-sdk-for-net#4478]
Hi there! I'm the docs author at the [Azure .NET SDK docs site](https://docs.microsoft.com/dotnet/azure), and a customer submitted the following issue with documentation generated from the `///` comments in your API. Please be sure to @ them in your response. Thanks! 

@MortenMeisler commented on [Thu May 31 2018](https://github.com/Azure/azure-docs-sdk-dotnet/issues/659)

Should be as simple as this right?

```
//Get job by jobname (which is the jobId)
var job = client.Job.Get("my resource group name", "my automation account name", "38ff75c2-d4ca-471f-b4a5-2a98da4d252b");
```

I'm getting error: 
1/2:
JsonSerializationException: Error converting value "Succeeded" to type 'Microsoft.Azure.Management.Automation.Models.JobProvisioningStateProperty'. Path 'properties.provisioningState', line 1, position 427

2/2:
ArgumentException: Could not cast or convert from System.String to Microsoft.Azure.Management.Automation.Models.JobProvisioningStateProperty.

This one works fine:
`var jobs = client.Job.ListByAutomationAccount(resourceGroup, automationAccount);`

And from that list of jobs I can check the names

What is the syntax here? any examples?

Thanks

Using preview version 3.0.3 (which was the least painfull to get authenticated with :)).

---

@CamSoper commented on [Wed Jun 20 2018](https://github.com/Azure/azure-docs-sdk-dotnet/issues/659#issuecomment-398943644)

I recently had reason to wrestle with the 3.0.3 version of the automation library. I agree, it's rough. Let's see what they say.

**Comment by jsquire** [comment]
The `Microsoft.Azure.Management.Automation` library has since been deprecated and is slated for retirement.  It is currently receiving only critical security fixes.  Closing this out.
