### ISSUE TITLE
[QUERY] How to reproduce the dependency behavior from the app insights SDK?

### ISSUE THREAD

**Issue by DaveLHX** [Azure/azure-sdk-for-net#44789]
### Library name and version

Azure.Monitor.OpenTelemetry.Exporter 1.3.0

### Query/Question

With the app insights sdk I can easily manually set all my external api calls as grouped dependencies like so.
```csharp
       private IDisposable GetTelemetryOperation(string dependencyName, string data)
        {
            DependencyTelemetry dependencyTelemetry =
                new DependencyTelemetry("HTTP", "MSGraphAPI", dependencyName, data);
            TelemetryClient telemetryClient = new TelemetryClient();
            return telemetryClient.StartOperation(dependencyTelemetry);
        }
```
To get this result, all calls to graph api are under the graph api dependency.
![image](https://github.com/Azure/azure-sdk-for-net/assets/12000766/af6c5c47-ac59-41f0-b752-df0f8b22f122)

I'm not sure I'm doing it right but I am trying to get the same result  but all the calls are seen as different dependencies, I cant get a single "GraphAPI" dependency, are there tags I can set or an other way to create dependencies? 
```csharp  
var graphApiActivitySource = new ActivitySource("GraphApi");
 using (var activity = graphApiActivitySource.StartActivity("GraphApi.SomeCall", ActivityKind.Client))
 {
     activity?.SetTag("http.method", "GET");
     activity?.SetTag("foo123", 1);
     activity?.SetTag("baz123", new int[] { 1, 2, 3 });
     activity?.SetStatus(ActivityStatusCode.Ok);
 }
 using (var activity = graphApiActivitySource.StartActivity("GraphApi.SomeOhterCall", ActivityKind.Client))
 {
     activity?.SetTag("http.method", "POST");
     activity?.SetStatus(ActivityStatusCode.Ok);
 }
```

![image](https://github.com/Azure/azure-sdk-for-net/assets/12000766/fc84ab0d-d50d-49b4-a7b2-46e0b7f69be8)

### Environment

The app is a web api in .net 4.8

**Comment by TimothyMothra** [comment]
Hi @DaveLHX, can you please share a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) using the Application Insights SDK showing what you're trying to accomplish?

We're in the process of writing a migration guide and we would like to fully understand your scenario.

**Comment by DaveLHX** [comment]
> Hi @DaveLHX, can you please share a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) using the Application Insights SDK showing what you're trying to accomplish?
> 
> We're in the process of writing a migration guide and we would like to fully understand your scenario.
This is how it would look.   When creating a new DependencyTelemetry the second parameter (target) is what allows me to do what I need.  In the open telemetry version I have no control over the target it always ends up the the same as the DependencyName,   We need to create multiple dependencies like, MSGraphAPI, ActiveDirectoryOnPrem, ExchangeOnline, App1Api, etc... and have all their calls under them.

```csharp
 public IList<string> GetGroupNames(string userPrincipalName)
 {
     var queryParam = new GraphGroupRequestBuilder.GraphGroupRequestBuilderGetQueryParameters();
     queryParam.Select = new[] { "DisplayName" };
     queryParam.Top = 200;
     DependencyTelemetry dependencyTelemetry =
         new DependencyTelemetry("HTTP", "MSGraphAPI", "GetAllGroupsForUser",
             "UserPrincipalName: {userPrincipalName}");
     TelemetryClient telemetryClient = new TelemetryClient();
     using (telemetryClient.StartOperation(dependencyTelemetry))
     {
         List<Group> groups = Task.Run(async () => await m_GraphServiceClient
             .Users[userPrincipalName].TransitiveMemberOf.GraphGroup.GetAsync(o =>
             {
                 o.QueryParameters = queryParam;
                 o.Options.WithAppOnly();
             })).Result.Value;
         IList<string> groupList = groups.Select(o => o.DisplayName).ToList();
         return groupList;
     }
 }
```
From the SDK:   public DependencyTelemetry(string dependencyTypeName, string target, string dependencyName, string data)

Working with multipleCustomDepenencies 

 new DependencyTelemetry("HTTP", "MSGraphAPI", "GetUser", "UserPrincipalName: {userPrincipalName}");
![image](https://github.com/Azure/azure-sdk-for-net/assets/12000766/13de2b87-b765-4eca-9df0-91b1f2ba4aba)
 new DependencyTelemetry("HTTP", "MSGraphAPI", "GetAllGroupsForUser", "UserPrincipalName: {userPrincipalName}"); 
![image](https://github.com/Azure/azure-sdk-for-net/assets/12000766/070cd6b5-70a2-4896-9e97-cf0ef36a630f)

and so on...
 new DependencyTelemetry("HTTP", "EXO", "GetMail", "UserPrincipalName: {userPrincipalName}");
 new DependencyTelemetry("HTTP", "EXO", "SearchSharedMailbox", "SearchString: {searchString}");

 new DependencyTelemetry("ActiveDirectory", "AD", "GetUser",  "UserPrincipalName: {userPrincipalName}");

**Comment by TimothyMothra** [comment]
Hi @DaveLHX ,

I believe this is what you want:
```csharp
using (var activity = activitySource.StartActivity("DependencyName", ActivityKind.Client))
{
    activity?.SetTag("http.request.method", "GET"); // The presence of this attribute will set the dependency Type to HTTP
    activity?.SetTag("url.full", "Data");
    activity?.SetTag("server.address", "TargetName");
}
```

compared to ApplicationInsights's Dependency Telemetry:
```csharp
public DependencyTelemetry(string dependencyTypeName, string target, string dependencyName, string data)
```

**Comment by TimothyMothra** [comment]
Our migration guide was just published. We have examples of the Application Insights api and how to use the new OpenTelemetry api.
https://learn.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-dotnet-migrate?tabs=aspnetcore#dependencytelemetry

Please take a look and let us know if this helps

**Comment by DaveLHX** [comment]
> Hi @DaveLHX ,
> 
> I believe this is what you want:
> 
> ```cs
> using (var activity = activitySource.StartActivity("DependencyName", ActivityKind.Client))
> {
>     activity?.SetTag("http.request.method", "GET"); // The presence of this attribute will set the dependency Type to HTTP
>     activity?.SetTag("url.full", "Data");
>     activity?.SetTag("server.address", "TargetName");
> }
> ```
> 
> compared to ApplicationInsights's Dependency Telemetry:
> 
> ```cs
> public DependencyTelemetry(string dependencyTypeName, string target, string dependencyName, string data)
> ```
Sorry for the late response, Yes this seems to do the trick thank you.
I do have to set both of the following for it to work.  If I dont put the http.request.method it ignores the TargetName 
     activity?.SetTag("http.request.method", "GET");
     activity?.SetTag("server.address", "TargetName");
     
Is there a list of the possible tags somewhere ?  Did you get that from looking in the insights repo/code?

**Comment by DaveLHX** [comment]
> Our migration guide was just published. We have examples of the Application Insights api and how to use the new OpenTelemetry api. https://learn.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-dotnet-migrate?tabs=aspnetcore#dependencytelemetry
> 
> Please take a look and let us know if this helps

Yes this seems like it would have helped quite a bit thanks.

**Comment by TimothyMothra** [comment]
> Is there a list of the possible tags somewhere? Did you get that from looking in the insights repo/code?

Right now I'm pulling the info from the code. We're currently exploring how to communicate the full list of available tags. Until then, please feel free to ask about specific fields here. We use the feedback here to prioritize our backlog.

**Comment by TimothyMothra** [comment]
I'm closing this issue. If you have additional questions, feel free to comment here or open a new issue.
