### ISSUE TITLE
Using LogExporter to connect to AppInsights and set message and Custom Dimensions field

### ISSUE THREAD

**Issue by srivadiMicrosoft** [Azure/azure-sdk-for-net#44791]
### Library name and version

Azure.Monitor.OpenTelemetry.Exporter" Version="1.3.0"

### Query/Question

Hey folks, we are looking to connect to AppInsights using .NET and OpenTelemetry. We have connected properly with Azure Monitor Log Exporter and can log to AppInsights. My query is in AppInsights we have 2 columns which are Message and CustomDimensions. I am using logger.log method to log data. This is the function used 

void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception? exception, Func<TState, Exception?, string> formatter)

1 : On passing String as the 3rd param in Tstate state, it is setting the text as Message field in AppInsights.
2 : On passing Key-Value pair as 3rd param in Tstate state, it is setting as Custom Dimensions field in AppInsights.

Adding screenshot for both scenarios.
![image](https://github.com/Azure/azure-sdk-for-net/assets/174135543/320d9c11-6193-4631-9cd5-91161c8358f0)

My question is how to set both fields, message and customDimensions?

**Comment by rajkumar-rangaraj** [comment]
@srivadiMicrosoft Could you please provide us [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) which explains this issue? Once we have the repro will check to identify why one of the column was not set.

**Comment by srivadiMicrosoft** [comment]
using Microsoft.Extensions.Logging;
using OpenTelemetry.Logs;
using Azure.Monitor.OpenTelemetry.Exporter;
using System.Text.Json;

//Setup code
var loggerFactory = LoggerFactory.Create(builder =>
{
    builder.AddOpenTelemetry(options =>
    {
        options
            .AddAzureMonitorLogExporter(options =>
            {
                options.ConnectionString = "InstrumentationKey=1e514254-12d0-495b-88c5-9bd7cb2e66db;IngestionEndpoint=https://eastus-8.in.applicationinsights.azure.com/;LiveEndpoint=https://eastus.livediagnostics.monitor.azure.com/;ApplicationId=d4eee155-8817-4465-8a45-19cda9d1d18e";
            })
            .AddConsoleExporter();
    });
});

var logger = loggerFactory.CreateLogger<Program>();

string demo = "{Name : \"Pest \",\nAge  : 21,\nCountry : \"Nepal\"}";

var person = new Dictionary<string, object?>()
{
    ["Name"] = "Test",
    ["Age"] = 26,
    ["Country"] = "India"
};

// This part sets Message field in AppInsights
logger.Log(
    LogLevel.Information,
    0,
    "BodyBody",
    null,
    null);

// This part sets CustomDimension field in AppInsights
logger.Log(
    LogLevel.Information,
    0,
    person,
    null,
    null);

// Dispose logger factory before the application ends.
// This will flush the remaining logs and shutdown the logging pipeline.
loggerFactory.Dispose();

**Comment by srivadiMicrosoft** [comment]
@rajkumar-rangaraj The issue is based on type of Input I am able to set either "Message" or "CustomDimensions" field. I want a way to set both. Please see screenshot attachted in original question for output of above code

**Comment by rajkumar-rangaraj** [comment]
Looks like you are incorrectly using log string interpolation. Again interpolation is not recommended. Please follow the recommendation documented here that should solve the issue - https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/logs#structured-logging

**Comment by srivadiMicrosoft** [comment]
using Microsoft.Extensions.Logging;
using OpenTelemetry.Logs;
using Azure.Monitor.OpenTelemetry.Exporter;
using System.Text.Json;

ILoggerFactory loggerFactory = LoggerFactory.Create(builder =>
{
    builder.AddOpenTelemetry(options =>
    {
        options
            .AddAzureMonitorLogExporter(options =>
            {
                options.ConnectionString = ;
            })
            .AddConsoleExporter();
    });
});

 ILogger logger = loggerFactory.CreateLogger<Program>();

var person = new Dictionary<string, object?>()
{
    ["Name"] = "Test",
    ["Age"] = 26,
    ["Country"] = "India"
};

logger.Log(
    LogLevel.Information,
    0,
    "BodyBody",
    null,
   null);

logger.Log(
    LogLevel.Information,
    0,
   person,
   null,
   null);


// Dispose logger factory before the application ends.
// This will flush the remaining logs and shutdown the logging pipeline.
loggerFactory.Dispose();

**Comment by srivadiMicrosoft** [comment]
Not sure this answers my question.  As you can see that we have 2 different fields in AppInsights, namely message and Custom Dimensions. I want to set both the fields.

In the above code using the 2 ways, I able to set either of the fields and not both. What is the way to set both fields? I have highlighted in above code on what does what

![image](https://github.com/Azure/azure-sdk-for-net/assets/174135543/6c5051d9-ffee-4198-ad40-1c8fd53cf456)

**Comment by rajkumar-rangaraj** [comment]
@srivadiMicrosoft My earlier recommendation was to follow the samples from https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/logs#structured-logging. The action plan has not changed yet; please follow the samples in that article. Those samples update both the Message and custom dimensions.
