### ISSUE TITLE
Valid values for the ImageReference Properties

### ISSUE THREAD

**Issue by rob011235** [Azure/azure-sdk-for-net#44808]
### Type of issue

Missing information

### Description

Please provide information on where to get valid values for the ImageReference Properties

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.management.compute.models.imagereference?view=azure-dotnet-legacy

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.Compute.Models/ImageReference.xml

### Document Version Independent Id

bb85bf89-ec54-1272-e3c6-164eccce857d

### Article author

@azure-sdk

### Metadata

* ID: 8bced382-3170-ff05-b5c0-0cb91e38e986 
* Service: **multiple**

**Comment by jsquire** [comment]
Hi @rob011235.  The `Microsoft.Azure..Management.Compute` package reached end-of-life in September 2023 and is no longer published nor supported by Microsoft.  The currently supported package for compute management operations is `Azure.ResourceManager.Compute`.

As this your inquiry is regarding an unsupported package, regrettably, there is no assistance that we can provide.  I'm going to close this out.
