### ISSUE TITLE
[QUERY] Integrating Azure AD Token Authorization in .NET by passing authorization token

### ISSUE THREAD

**Issue by shouryashashank** [Azure/azure-sdk-for-net#44805]
### Library name and version

Azure.AI.OpenAI --version 2.0.0-beta.2

### Query/Question

Hello,

I am currently using Azure AD token to authorize the client in Python and it's working fine with the Python library. Here is the relevant code snippet from the Python library:

![image](https://github.com/Azure/azure-sdk-for-net/assets/25346465/4e0fa445-a109-4cc1-a953-624d73f5e803)

https://github.com/openai/openai-python/blob/6316b7c0f182877e578a3dbed2fd129b63538af5/src/openai/lib/azure.py#L291

However, I am facing difficulties when trying to implement the same in .NET. Currently, my only option is to create my own HTTP client and make REST calls and passing request header 
```
Authorization :  Bearer ****

```

It would be great if you could provide some guidance or point me to the relevant documentation or examples. Any help would be greatly appreciated.

Thank you.

### Environment

Windows 11
dotnet 6

**Comment by jsquire** [comment]
@shouryashashank :  The Azure SDK clients make use of the Azure.Identity library to integrate with Entra ID and other token-based sources.  Each client, including the `AzureOpenAIClient`, have constructor overloads that accept a `TokenCredential` instance.

For example:

```csharp
AzureOpenAIClient azureClient = new(
    new Uri("https://your-azure-openai-resource.com"),
    new DefaultAzureCredential());
```

More discussion and links to further examples can be found in the [Azure OpenAI README](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/openai/Azure.AI.OpenAI#create-client-with-a-microsoft-entra-credential)
