### ISSUE TITLE
My version is not in this enum

### ISSUE THREAD

**Issue by pjirsa** [Azure/azure-sdk-for-net#44811]
https://github.com/Azure/azure-sdk-for-net/blob/6adc0dc4ac7ffc94a91f3c5463e05672cde5ee1a/sdk/openai/Azure.AI.OpenAI/src/Custom/AzureOpenAIClientOptions.cs#L24

I have access to a private preview version that is not listed. How can I set the version number being sent by the AzureOpenAIClient?

**Comment by jsquire** [comment]
Hi @pjirsa.  Thanks for reaching out and we regret that you're experiencing difficulties.  Each Azure SDK client supports only the known service versions that were known at the time of its release, all of which are defined its service version enumeration.   Other service versions are not supported by that build of the client and cannot be used with it.

**Comment by pjirsa** [comment]
Hey @jsquire. Thanks for the response. In this case, the SDK *DOES* contain the client support for the preview endpoint I'm working with. But the enum does not contain the version for that preview.

**Comment by pjirsa** [comment]
I'm looking for `2024-04-15-preview` option.
