### ISSUE TITLE
[FEATURE REQ] PublicNetworkAccess.SecuredByPerimeterValue does not exist but is supported by the Storage API

### ISSUE THREAD

**Issue by pwoosam** [Azure/azure-sdk-for-net#44828]
### Library name

Microsoft.Azure.Management.Storage.Models

### Please describe the feature.

`Azure.ResourceManager.Storage.Models` supports `StoragePublicNetworkAccess.SecuredByPerimeterValue`, but `Microsoft.Azure.Management.Storage.Models` does not have a `PublicNetworkAccess.SecuredByPerimeterValue` field. 

Can `Microsoft.Azure.Management.Storage.Models` be caught up to speed with `Azure.ResourceManager.Storage.Models`? #44571

**Comment by pwoosam** [comment]
cc: @blueww @ArthurMa1978

**Comment by jsquire** [comment]
Hi @pwoosam.  Thanks for reaching out and we regret that you're experiencing difficulties.   The `Microsoft.Azure.Management.Storage` package reached end-of-life in September 2023 and is no longer published nor supported by Microsoft.  We strongly recommend that you not use it in production applications and upgrade to `Azure.ResourceManager.Storage`.    

As there is no support available for the package, I'm going to close this out.

**Comment by pwoosam** [comment]
Ah that makes sense 🙂 Thank you!
