### ISSUE TITLE
ResourceManager doesn't have SDK for latest version viz 2018-02-01, 2018-05-01

### ISSUE THREAD

**Issue by DheerendraRathor** [Azure/azure-sdk-for-net#4482]
ResourceManager has swagger spec present for both API versions (https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Resources/stable) but current version of SDK and nuget package doesn't contain methods for these API versions.

**Comment by ifeoluwaokunoren** [comment]
Hello, 
[Latest Nuget Package available here](https://www.nuget.org/packages/Microsoft.Azure.Management.ResourceManager/3.5.0-preview
We're also working on a process to ensure that the latest API versions also have their SDKs generated and released.
