### ISSUE TITLE
[BUG] Storage operations are hanging

### ISSUE THREAD

**Issue by shaibs3** [Azure/azure-sdk-for-net#44833]
### Library name and version

Azure.Identity 1.12.0

### Describe the bug

Azure.Identity version 1.12.0 causes the services to hang upon storage operations
Recently i upgraded the Azure.Identity NuGet from version 1.1.14 to 1.12.0 and started to experience problems when performing io operations vs the storage account (mostly reading and writing blobs). the services depending in this NuGet just hanged and didn't complete their read, write operations. i had to downgrade the NuGet back to 1.1.14 where things work as expected.

### Expected behavior

IO operations (read and writing blobs form a storage account) don't hang. i.e calling to [BlobClient.OpenWriteAsync](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobclient.openwriteasync?view=azure-dotnet) will result in a response

### Actual behavior

IO operations (read and writing blobs form a storage account) hang. i.e calling to [BlobClient.OpenWriteAsync](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobclient.openwriteasync?view=azure-dotnet) hangs and no response recieved

### Reproduction Steps

use azure,identity  1.12.0 and try to read io operations on storage blobs such as [BlobClient.OpenWriteAsync](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobclient.openwriteasync?view=azure-dotnet), the operation hangs (not all the time)

**Comment by PixelByProxy** [comment]
I experienced this also, the exception appeared to happen in Azure.Core as described in this issue https://github.com/Azure/azure-sdk-for-net/issues/44817

**Comment by jsquire** [comment]
This was traced back to a bug in Azure.Core which has been fixed in v1.41.0.    Until the Storage packages are released with an updated Core reference, mitigation is to take a direct reference to Core in your application.
