### ISSUE TITLE
TextAnalytics SDK v1.0.1-preview Missing ServiceClientCredentials Implementations

### ISSUE THREAD

**Issue by brminnick** [Azure/azure-sdk-for-net#4483]
The [TextAnalytics SDK v1.0.1-preview](https://www.nuget.org/packages/Microsoft.Azure.CognitiveServices.Language.TextAnalytics) is missing `ServiceClientCredentials` implementations.

The constructor for `TextAnalyticsAPI` requires a `ServiceClientCredentials` object, but `ServiceClientCredentials` is `abstract`.

Below is the work-around I added to my project. I am using `ApiKeyServiceClientCredentials` [found in the Vision library](https://github.com/Azure/azure-sdk-for-net/blob/528d88795f298a394290a5730186ff58b973a2b1/src/SDKs/CognitiveServices/dataPlane/Vision/ContentModerator/ContentModerator/ApiKeyServiceClientCredentials.cs).

```csharp
TextAnalyticsAPI apiClient = new TextAnalyticsAPI(new ApiKeyServiceClientCredentials(TextAnalysisConstants.SentimentKey));

public class ApiKeyServiceClientCredentials : ServiceClientCredentials
{
    private readonly string subscriptionKey;

    /// <summary>
    /// Creates a new instance of the ApiKeyServiceClientCredentails class
    /// </summary>
    /// <param name="subscriptionKey">The subscription key to authenticate and authorize as</param>
    public ApiKeyServiceClientCredentials(string subscriptionKey)
    {
        this.subscriptionKey = subscriptionKey;
    }

    /// <summary>
    /// Add the Basic Authentication Header to each outgoing request
    /// </summary>
    /// <param name="request">The outgoing request</param>
    /// <param name="cancellationToken">A token to cancel the operation</param>
    public override Task ProcessHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        if (request == null)
            throw new ArgumentNullException("request");

        request.Headers.Add("Ocp-Apim-Subscription-Key", this.subscriptionKey);

        return Task.FromResult<object>(null);
    }
}
```

**Comment by brminnick** [comment]
v2.0.0-preview is also missing `ApiKeyServiceClientCredentials`

**Comment by ChrisHMSFT** [comment]
This issue has been addressed in the newest version of the Text Analytics SDK. You can find documentation here: https://www.nuget.org/packages/Azure.AI.TextAnalytics/1.0.0-preview.1

Thanks,
Chris
