### ISSUE TITLE
[FEATURE REQ] How to set UserAccountId in AppInsights with Azure.Monitor.OpenTelemetry.Exporter

### ISSUE THREAD

**Issue by SteMcLellan** [Azure/azure-sdk-for-net#44837]
### Library name and version

Azure.Monitor.OpenTelemetry.Exporter" Version="1.3.0"

### Query/Question

Hello,

I am attempting to convert some applications from using the Application Insights SDK to OpenTelemetry, and am running into some confusion about how to make sure that certain properties on AppRequests are set as expected. We have historically used `UserAccountId` (or `user_AccountId`) to store the tenant in our application, and I'd like to continue doing so.

I have been unable to find a "map" between OpenTelemetry fields and those supported by Azure Monitor, does one exist? In absence of map, is there a way to set this field, or will I need to utilize custom dimensions?

**Comment by olegd-superoffice** [comment]
This is a "must have" for multi-tenant applications. I also tried to do it but couldn't find a way. I hope that mapping of OTEL attributes to [Application Insights Data Model](https://learn.microsoft.com/en-us/azure/azure-monitor/app/data-model-complete) is going to be documented. So far I see that only mapping for [cloud role name and cloud role instance is documented](https://learn.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-configuration?tabs=aspnetcore#set-the-cloud-role-name-and-the-cloud-role-instance) and I see that `service.version` attribute is getting mapped to [Application version](https://learn.microsoft.com/en-us/azure/azure-monitor/app/data-model-complete#application-version).

**Comment by TimothyMothra** [comment]
Unfortunately this field is not mapped today. I changed this title to a Feature Req, we're tracking which outstanding fields users are asking for. As of today I can't give an estimate on when this will be available.

**Comment by TimothyMothra** [comment]
I'm consolidating all issues regarding overriding specific fields in the Application Insights schema into another issue to help with tracking. https://github.com/Azure/azure-sdk-for-net/issues/46021
