### ISSUE TITLE
[FEATURE REQ] RunCommandInput.CommandId Property should support a type in addition to/instead of a string

### ISSUE THREAD

**Issue by kekivelez** [Azure/azure-sdk-for-net#44846]
### Library name

Azure.ResourceManager.Compute.Models

### Please describe the feature.

the CommandId property of RunCommand can only be a limited set of values found [here](https://learn.microsoft.com/en-us/azure/virtual-machines/windows/run-command#available-commands) and [here](https://learn.microsoft.com/en-us/azure/virtual-machines/linux/run-command#available-commands). The property name or the sdk reference don't even hint at them being limited. At the very least the sdk reference should indicate as such

**Comment by jsquire** [comment]
@kekivelez:  Thanks for reaching out and we regret that you're experiencing difficulties.   The documentation for the client members is generated directly from the service REST API specification and would need to be adjusted there by the service team who owns that spec.  To ensure that the right team has visibility and can help, your best path forward for would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) or inquire on the [Microsoft Q&A site](https://learn.microsoft.com/answers/questions/).   

I'm going to close this out; if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.

**Comment by kekivelez** [comment]
Well the request was around changing the type of this field from a string
to something more strict. The documentation change suggestion was meant to
be treated as a stop gap or an alternative suggestion.

 As I mentioned originally this field can only accept one of a
limited/countable set of values. A string that can accept an arbitrary
value leads to confusion/misunderstanding on the field.

Why depend on customers to know that they need to put in
"RunPowerShellScript" when it would be much more declarative and less error
prone to have to use something like "WindowsVmCommand.RunPowerShellScript".

So you can imagine having a "VmCommand" type/interface/class and then have
a WindowsVmCommand version/member of that type and a LinuxVmCommand
version/member of that type. The property would accept either of them which
would be up to the customer and the platform of their system

**Comment by jsquire** [comment]
@kekivelez:  Thanks for the clarifications and apologies for the confusion.   Unfortunately, that doesn't change the outcome.  As the management clients are generated, the choice of `string` for this member is based on the REST API spec defining it as `string` rather than the spec defining it as a constrained set of values.    A change to that representation would need to take place in the API spec and flow into the Azure SDK package from there.
