### ISSUE TITLE
[BUG] Azure OpenAI Assistants (C#) do not work as expected (mixing up roles etc)

### ISSUE THREAD

**Issue by k2tomasz** [Azure/azure-sdk-for-net#44849]
### Library name and version

Azure.AI.OpenAI.Assistants 1.0.0-beta.4

### Describe the bug

Assistants created with the SDK do not handle responses as expected. For example, when instructed to act as a customer and user to be the salesperson, it acts as a salesperson and expects the user to be a customer. It other times it returns a paragraph from the instruction prompt (paragraph that contains the examples of interactions). 

I have tested the same prompt on the same model deployment with Assistants playground and it works as expected.

### Expected behavior

Assistants created with the SDK should respond in the same way assistants created in the playground do.

### Actual behavior

Mixing up roles, replaying back with big parts of the system prompt.

### Reproduction Steps

Can give you the exact prompt but would like to keep it private. So, DM me please.

### Environment

.NET 8.0

**Comment by k2tomasz** [comment]
any idea when the Assistants SDK would be fixed? Not sure if I should wait or maybe use OpenAI SDK for time now.

**Comment by scottaddie** [comment]
@k2tomasz We recommend that customers migrate to the Azure.AI.OpenAI package. Azure.AI.OpenAI supports the latest features, including the Assistants v2 API. See the note at https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/openai/Azure.AI.OpenAI.Assistants#important-note-assistants-is-converging.
