### ISSUE TITLE
[BUG] Cannot remove WAF policy association from App Gateway HttpListener

### ISSUE THREAD

**Issue by AFAde** [Azure/azure-sdk-for-net#44854]
### Library name and version

Azure.ResourceManager.Network 1.8.0

### Describe the bug

When trying to remove the association of a waf policy from an App Gateway http listener, an exception is thrown

### Expected behavior

The WAF Policy association is removed from HttpListener

### Actual behavior

The WAF Policy association is not removed from HttpListener. Error message:

> System.AggregateException: One or more errors occurred. (The activity function 'WafInstancePolicyActivity' failed: "Cannot parse the request.
> Status: 400 (Bad Request)
> ErrorCode: InvalidRequestFormat
> 
> Content:
> {
>   "error": {
>     "code": "InvalidRequestFormat",
>     "message": "Cannot parse the request.",
>     "details": [
>       {
>         "code": "MissingJsonReferenceId",
>         "message": "Value for reference id is missing. Path properties.httpListeners[7].properties.firewallPolicy."
>       }
>     ]
>   }
> }
> 
> at Azure.ResourceManager.Network.ApplicationGatewaysRestOperations.CreateOrUpdateAsync(String subscriptionId, String resourceGroupName, String applicationGatewayName, ApplicationGatewayData data, CancellationToken cancellationToken)
>    at Azure.ResourceManager.Network.ApplicationGatewayCollection.CreateOrUpdateAsync(WaitUntil waitUntil, String applicationGatewayName, ApplicationGatewayData data, CancellationToken cancellationToken)

### Reproduction Steps

Here is the code snippet
```
var appGatewayGroup = "<Gateway_Resource_Group_Name>";
var subscriptionId = "<SUBSCRIPTION_ID>";
var listenerName = "<LISTENER_NAME>";
var appGateWayName = "<APP_GATEWAY_NAME>";

var credential = new ChainedTokenCredential(new ManagedIdentityCredential(),
    new DefaultAzureCredential());

var client = new ArmClient(credential, subscriptionId);
	
var subscription = await client.GetDefaultSubscriptionAsync().ConfigureAwait(false);
 
var rg = await subscription.GetResourceGroupAsync(appGatewayGroup).ConfigureAwait(false);

var appGateway = (await rg.Value.GetApplicationGatewayAsync(appGateWayName)
                .ConfigureAwait(false)).Value;
				
 var listener = appGateway.Data.HttpListeners.SingleOrDefault(l => string.Equals( l.Name ,listenerName, StringComparison.OrdinalIgnoreCase));
 if (listener != null)
 {
	listener.FirewallPolicyId = null;
	var updateCollection = rg.Value.GetApplicationGateways();
	var operation = await updateCollection.CreateOrUpdateAsync(WaitUntil.Completed, appGateWayName, appGateway.Data) .ConfigureAwait(false);            
 }
```

### Environment

.net 6 in-process Azure Function

**Comment by HarveyLink** [comment]
Hi @AFAde , thank you for using Azure SDK for .NET.
Due to the SDK design, it will be slight complex on achieve your requirement.
Please check:
```
    var gateway = (await resourceGroup.GetApplicationGateways().GetAsync("<PlaceHolder>")).Value;
    var data = gateway.Data;
    var listenerList = new List<ApplicationGatewayHttpListener>();
    foreach (var item in gateway.Data.HttpListeners)
    {
        if (item.Name.Equals("<PlaceHolder>"))
        {
            var target = new ApplicationGatewayHttpListener()
            {
                 HostName = item.HostName,
                 Id = item.Id,
                 Name = item.Name,
                 Protocol = item.Protocol,
                 RequireServerNameIndication = item.RequireServerNameIndication,
                 FrontendIPConfigurationId = item.FrontendIPConfigurationId,
                 FrontendPortId = item.FrontendPortId,
                 // Not set if they are empty
                 //SslCertificateId = item.SslCertificateId,
                 //SslProfileId = item.SslProfileId
            };
            foreach (var config in item.CustomErrorConfigurations)
            {
                target.CustomErrorConfigurations.Add(config);
            }
            foreach (var host in item.HostNames)
            {
                target.HostNames.Add(host);
            }
            listenerList.Add(target);
        }
        else
        {
            listenerList.Add(item);
        }
    }
    data.HttpListeners.Clear();
    foreach (var item in listenerList)
    {
        data.HttpListeners.Add(item);
    }
    gateway = (await resourceGroup.GetApplicationGateways().CreateOrUpdateAsync(WaitUntil.Completed, "<PlaceHolder>", data)).Value;
```
The trick here is not to set the `WAF Id` in a new object, similar to `SslCertificateId`, `SslProfileId`.
Then modify the list.
