### ISSUE TITLE
Please specify whether ImportImageAsync Updates an existing image if used same tag with newer version or not

### ISSUE THREAD

**Issue by saikrishnav** [Azure/azure-sdk-for-net#44861]
### Type of issue

Missing information

### Description

ImportImageAsync does NOT specify the behavior for existing tags. 
For example, if the target ACR already has image:1.0 and we try to import image:1.0 with a new image but same tag, does the import method update the image on ACR or does it NOT? 

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.management.containerregistry.registriesoperationsextensions.importimageasync?view=azure-dotnet-legacy

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.ContainerRegistry/RegistriesOperationsExtensions.xml

### Document Version Independent Id

b4635777-5110-6090-7930-2fd40ce8543f

### Article author

@azure-sdk

### Metadata

* ID: 84dc31bd-f7ad-c81a-56e7-69d58d851081 
* Service: **container-registry**

**Comment by jsquire** [comment]
Hi @saikrishnav.  Thanks for reaching out and we regret that you're experiencing difficulties.   The `Microsoft.Azure.Management.ContainerRegistry` package reached end-of-life in September 2023 and is no longer published nor supported by Microsoft.   We strongly recommend not using this package and migrating to `Azure.ResourceManager.ContainerRegistry."

As this package is unsupported, we're unable to assist with your inquiry.  I'm going to close this out.
