### ISSUE TITLE
The registration for method 'ConfigureFunctionsWebApplication' is expected for ASP.NET Core Integration.AZFW0014

### ISSUE THREAD

**Issue by sivakarthick169** [Azure/azure-sdk-for-net#44883]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.functions.worker.invocation?view=azure-dotnet

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/ns-Microsoft.Azure.Functions.Worker.Invocation.xml

### Document Version Independent Id

691ab652-227b-0805-78fb-65933f19dd73

### Article author

@azure-sdk

### Metadata

* ID: 6d2612d8-4cb0-623b-e973-4d1b0b88d7b3

**Comment by jsquire** [comment]
This issue has been trasferred to the repository where the Azure Functions worker pacakges are maintained as [#2578](https://github.com/Azure/azure-functions-dotnet-worker/issues/2578).
