### ISSUE TITLE
[BUG] Start an internal activity raise a Dependency Call Failure in Live metrics

### ISSUE THREAD

**Issue by luox78** [Azure/azure-sdk-for-net#44889]
### Library name and version

Azure.Monitor.OpenTelemetry.AspNetCore 1.2.0

### Describe the bug

when I start an internal activity, a dependency failure was raised without specifying a status
![image](https://github.com/Azure/azure-sdk-for-net/assets/29404988/d3bc0f5c-d77e-4af8-ae89-80c1964ef9d2)

### Expected behavior

Shouldn't show failure

### Actual behavior

show failure

### Reproduction Steps

```csharp
  public static readonly ActivitySource TaskActivitySource  = new("task");

var activity = TaskActivitySource.StartActivity($"BackgroundTask test",
    ActivityKind.Internal, parentContext: default);

activity?.SetStatus(ActivityStatusCode.Ok);
activity?.Stop();
```
addservice
```csharp
services.AddOpenTelemetry().WithTracing(t => t.AddSource("task")).UseAzureMonitor();
```

### Environment

.NET 8.0.4

**Comment by TimothyMothra** [comment]
I found the bug. working on a fix.
