### ISSUE TITLE
Unable to run any powershell command/script

### ISSUE THREAD

**Issue by Ravikumar-1709** [Azure/azure-sdk-for-net#44893]
### Library name and version

Azure Powershell

### Describe the bug

I am unable to run any PS script in my machine and tried all the ways but didnt help
![Untitled](https://github.com/Azure/azure-sdk-for-net/assets/175024562/1a5f216c-5d91-4e49-a10d-826a626f9552)

### Expected behavior

I didnt all the possibilities 

### Actual behavior

Need to execute all the Script

### Reproduction Steps

Still same issue

**Comment by jsquire** [comment]
@Ravikumar-1709:  This repository is for issues related to the Azure SDK for .NET packages; we have no association with Azure PowerShell.   You'll want to file your issue in the [azure-powershell repository](https://github.com/Azure/azure-powershell/issues/new/choose).   They have strict templates that must be followed when filing an issue which require context that is not available here.   As a result, I'm unable to transfer on your behalf.
