### ISSUE TITLE
[QUERY] trace-id in Cosmos DB refresh every 5 minutes is reused

### ISSUE THREAD

**Issue by andrasg** [Azure/azure-sdk-for-net#44897]
### Library name and version

Microsoft.Azure.Cosmos v3.41.0

### Query/Question

My WebAPI code uses Azure.Monitor.OpenTelemetry.AspNetCore v1.2.0 instrumentation and the Microsoft.Azure.Cosmos v3.41.0 SDK.
I am seeing periodic GET request to Cosmos DB every 5 minutes. I am suspecting this is the SDK refreshing some Cosmos region information.

<img width="740" alt="image" src="https://github.com/Azure/azure-sdk-for-net/assets/10730249/f0ead1bf-2c51-4884-a3cd-ec305f64c75e">

All operations seem to be reusing a correlation id (trace-id) of an initial API request to my API. 

Is it expected that the trace-id is reused for these periodic background calls? Is there a way to influence (reset?) the trace context used for these operations?

### Environment

.net 8.0 code deployed to a Azure Website
Azure.Monitor.OpenTelemetry.AspNetCore v1.2.0
Microsoft.Azure.Cosmos v3.41.0

**Comment by jsquire** [comment]
Gi @andrasg.  Thanks for reaching out and we regret that you're experiencing difficulties.   I've transferred this to the repository where the `Microsoft.Azure.Cosmos` package is maintained as [#4581](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/4581).  This will ensure that the folks best able to assist have visibility.
