### ISSUE TITLE
[BUG] Cost Management Query usage - include Tags column

### ISSUE THREAD

**Issue by VaclavK** [Azure/azure-sdk-for-net#44894]
### Library name and version

Azure.ResourceManager.CostManagement, 1.0.1

### Describe the bug

I can generate usage query IF I do not include Tags column via the SDK
e.g.

 query.Dataset.Columns.Add("Tags");

this can be done via raw JSON/http client and receives 200, c# code as above with the line included gets 400, 200 without this include column

looking at the code for this collection of columns and request serialization, there seems to be mismatch in the expected name

include (expected) vs configuration (sdk code)

### Expected behavior

http 200 received

### Actual behavior

http 400 received

### Reproduction Steps

full sample code
```
 QueryDefinition query = new(ExportType.ActualCost, TimeframeType.Custom, new QueryDataset()) 
 {
     TimePeriod = new QueryTimePeriod(request.ReportRequest.CostFrom, request.ReportRequest.CostTo),                    
 };

 query.Dataset.Granularity = new GranularityType("None");
 query.Dataset.Columns.Add("Tags");
 query.Dataset.Aggregation.Add("totalCost", new QueryAggregation("Cost", "Sum"));
 query.Dataset.Grouping.Add(new QueryGrouping(QueryColumnType.Dimension, request.GroupingMode == GroupingMode.Resource ? "ResourceId" : "SubscriptionId"));

 var sdkresponse = await armClient.UsageQueryAsync(new ResourceIdentifier(subId), query);
``` 

### Environment

.net core 8 under dapr app

.NET SDK:
 Version:           8.0.302
 Commit:            ef14e02af8
 Workload version:  8.0.300-manifests.5273bb1c
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.302\

.NET workloads installed:
 [aspire]
   Installation Source: VS 17.10.35013.160
   Manifest Version:    8.0.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.0.0\WorkloadManifest.json
   Install Type:        FileBased

Host:
  Version:      8.0.6
  Architecture: x64
  Commit:       3b8b000a0e

.NET SDKs installed:
  8.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.31 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.31 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by welovej** [comment]
I reproduced that:
> Azure.RequestFailedException:** 'Invalid query definition: Invalid dataset configuration columns: 'Tags'; valid values: 'SubscriptionGuid','ResourceGroup','ResourceLocation','UsageDateTime','MeterCategory','MeterSubcategory','MeterId','MeterName','MeterRegion','UsageQuantity','ResourceRate','PreTaxCost','ConsumedService','ResourceType','InstanceId','TagsDy','OfferId','AdditionalInfo','ServiceInfo1','ServiceInfo2','ServiceName','ServiceTier','Currency','UnitOfMeasure'.


The column "Tags" is invalid in the query definition, and grouping or aggregation must not be specified if the configuration is used. Here's how to resolve this:

- Use Valid Columns: Use valid column names in the dataset configuration. For example, use "**TagsDy**" instead of "Tags".
- Remove Grouping or Aggregation: If you are using configuration columns, you cannot specify grouping or aggregation.

```
QueryDefinition query = new(ExportType.ActualCost, TimeframeType.Custom, new QueryDataset()) 
{
    TimePeriod = new QueryTimePeriod(request.ReportRequest.CostFrom, request.ReportRequest.CostTo),                    
};

// Use a valid column name, for example, "TagsDy"
query.Dataset.Granularity = new GranularityType("None");
query.Dataset.Columns.Add("TagsDy");

// Remove aggregation and grouping
// query.Dataset.Aggregation.Add("totalCost", new QueryAggregation("Cost", "Sum"));
// query.Dataset.Grouping.Add(new QueryGrouping(QueryColumnType.Dimension, request.GroupingMode == GroupingMode.Resource ? "ResourceId" : "SubscriptionId"));

var sdkresponse = await armClient.UsageQueryAsync(new ResourceIdentifier(subId), query);
```

**Comment by VaclavK** [comment]
@welovej  will try... out of curiosity.. where are these column names defined? I use Tags column when sending JSON directly so I simply transferred that - and it works there (albeit separate issue of tags beings incorrectly serialized at times), the response itself contains such tag name so it makes sense - so for my future reference I would like to understand mapping between SDK names and direct JSON names

e.g. this absolutely works for JSON
```
{
    "type": "ActualCost",
    "dataSet": {
        "granularity": "None",
        "aggregation": {
            "totalCost": {
                "name": "Cost",
                "function": "Sum"
            }
        },
        "include":[
                "Tags"
            ],
        "grouping": [
            {
                "type": "Dimension",
                "name": "SubscriptionId"
            }
        ]       
    },
    "timeframe": "Custom",
    "timePeriod": {
        "from": "2024-07-01T13:00:00+00:00",
        "to": "2024-07-10T23:59:59+00:00"
    }
}
```

**grouping wise**  - I want to see the cost per resource or per subscription (depends on flow).. without grouping, I will have to deal with considerably larger response - again, this works with JSON request, what am I missing?

**Comment by welovej** [comment]
@VaclavK  can you reproduct how to use this json in a c# snippet  or like postman ?

**Comment by VaclavK** [comment]
> @VaclavK can you reproduct how to use this json in a c# snippet or like postman ?

postman

I then wanted to convert it into c# and that triggered this ticket

**Comment by welovej** [comment]
> > @VaclavK can you reproduct how to use this json in a c# snippet or like postman ?
> 
> postman
> 
> I then wanted to convert it into c# and that triggered this ticket

can you post the screenshot?

**Comment by VaclavK** [comment]
> > > @VaclavK can you reproduct how to use this json in a c# snippet or like postman ?
> > 
> > 
> > postman
> > I then wanted to convert it into c# and that triggered this ticket
> 
> can you post the screenshot?

apologies, screenshot of what? the postman? Please let me know.

 I provided the  JSON payload earlier and c# as well

**Comment by welovej** [comment]
> > > > @VaclavK can you reproduct how to use this json in a c# snippet or like postman ?
> > > 
> > > 
> > > postman
> > > I then wanted to convert it into c# and that triggered this ticket
> > 
> > 
> > can you post the screenshot?
> 
> apologies, screenshot of what? the postman? Please let me know.
> 
> I provided the JSON payload earlier and c# as well

screentshot of postman

**Comment by VaclavK** [comment]
@welovej 
<img width="881" alt="image" src="https://github.com/user-attachments/assets/811697a0-c7d9-4ab4-a496-4d80b7e8f20e">

getting 200 response - grouped by sub id (some details redacted) with e.g.

```
{
    "id": "subscriptions/********************/providers/Microsoft.CostManagement/query/4629b39d-1389-4b58-8e6d-f8f8209745c4",
    "name": "4629b39d-1389-4b58-8e6d-f8f8209745c4",
    "type": "Microsoft.CostManagement/query",
    "location": null,
    "sku": null,
    "eTag": null,
    "properties": {
        "nextLink": null,
        "columns": [
            {
                "name": "Cost",
                "type": "Number"
            },
            {
                "name": "SubscriptionId",
                "type": "String"
            },
            {
                "name": "Tags",
                "type": "Array"
            },
            {
                "name": "Currency",
                "type": "String"
            }
        ],
        "rows": [
            [
                4749.37610325131,
                "*******************",
                [
                    "\"environment\":\"dev\"",
                    "\"environment\":\"production\"",
                    "\"defendervmscanner\":\"exclude\"",
                    "\"ms-resource-usage\":\"azure-cloud-shell\"",
                    "\"createdby\":\"azurebackup\"",
                    "\"createdby\":\"********\"",
                    "\"_organizationname_\":\"********\"",
                    "\"environment\":\"platform\"",
                    "\"logtype\":\"main\""
                ],
                "EUR"
            ]
        ]
    }
}
```

also 200 when grouping per resource id

![image](https://github.com/user-attachments/assets/c2ce25bc-e84d-4fd5-af44-2a30dc9fab28)

**Comment by welovej** [comment]
> hi @VaclavK
> 
> I reproduced that:
> 
> > Azure.RequestFailedException:** 'Invalid query definition: Invalid dataset configuration columns: 'Tags'; valid values: 'SubscriptionGuid','ResourceGroup','ResourceLocation','UsageDateTime','MeterCategory','MeterSubcategory','MeterId','MeterName','MeterRegion','UsageQuantity','ResourceRate','PreTaxCost','ConsumedService','ResourceType','InstanceId','TagsDy','OfferId','AdditionalInfo','ServiceInfo1','ServiceInfo2','ServiceName','ServiceTier','Currency','UnitOfMeasure'.
> 
> The column "Tags" is invalid in the query definition, and grouping or aggregation must not be specified if the configuration is used. Here's how to resolve this:
> 
> * Use Valid Columns: Use valid column names in the dataset configuration. For example, use "**TagsDy**" instead of "Tags".
> * Remove Grouping or Aggregation: If you are using configuration columns, you cannot specify grouping or aggregation.
> 
> ```
> QueryDefinition query = new(ExportType.ActualCost, TimeframeType.Custom, new QueryDataset()) 
> {
>     TimePeriod = new QueryTimePeriod(request.ReportRequest.CostFrom, request.ReportRequest.CostTo),                    
> };
> 
> // Use a valid column name, for example, "TagsDy"
> query.Dataset.Granularity = new GranularityType("None");
> query.Dataset.Columns.Add("TagsDy");
> 
> // Remove aggregation and grouping
> // query.Dataset.Aggregation.Add("totalCost", new QueryAggregation("Cost", "Sum"));
> // query.Dataset.Grouping.Add(new QueryGrouping(QueryColumnType.Dimension, request.GroupingMode == GroupingMode.Resource ? "ResourceId" : "SubscriptionId"));
> 
> var sdkresponse = await armClient.UsageQueryAsync(new ResourceIdentifier(subId), query);
> ```

---
hi @VaclavK 
- I tried all the SDK supported name,but it only responsed Currency as the screenshot of postman shows. It might have some problems with this requested service.
- And your way   ```"include":[
                "Tags"
            ]```  works, but it's not the part of the data post of   ```query.Dataset.Columns.Add("Tags"); 
  await armClient.UsageQueryAsync(subid, query); ```

thank you for reaching out to us about the Azure SDK for .NET. Unfortunately, this issue is related to the service side and not the SDK side, so we are not able to help you with it. Therefore, we are closing this issue for now. If you need more assistance, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). We apologize for any inconvenience this may cause you.
We value your feedback and we want to make sure that your problem is solved. If you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.

![image](https://github.com/user-attachments/assets/71cd080d-1323-43de-a959-a4004f479077)
