### ISSUE TITLE
[FEATURE REQ] OpenTelemetry tags for RPC are not associated with the correct OperationType

### ISSUE THREAD

**Issue by rvanheest** [Azure/azure-sdk-for-net#44905]
### Library name and version

Azure.Monitor.OpenTelemetry.Exporter

### Describe the bug

When adding tags such as `"rpc.system"` or `"rpc.service"` to an `Activity`, it is supposed to be recognized as an RPC operation. The `Azure.Monitor.OpenTelemetry.Exporter.Internals.OperationType` already contains this type, but in `Azure.Monitor.OpenTelemetry.Exporter.Internals.ActivityTagsProcessor` this type is not selected if the appropriate tags occur.

### Expected behavior

The `ActivityTagsProcessor` should register the correct `activityType` in `CategorizeTags` if a tag like `"rpc.system"` occurs. This will then correctly trigger `SetRpcDependencyProperties` in the constructor of `Azure.Monitor.OpenTelemetry.Exporter.Models.RemoteDependencyData`, writing the correct values to ApplicationInsights.

### Actual behavior

Currently the `activityType` is not set to `OperationType.Rpc`, causing the properties `"rpc.service"`, `"rpc.system"` and `"rpc.grpc.status_code"` not to be exported to ApplicationInsights.

### Reproduction Steps

```cs
var activity = Source.StartActivity(kind: ActivityKind.Client, name: "my name", tags: new []
{
    new KeyValuePair<string, object>("rpc.system", "mysystem"),
    new KeyValuePair<string, object>("rpc.service", "my service"),
    new KeyValuePair<string, object>("rpc.method", "some operation")
});
```

Currently only tag `"rpc.method"` is exported to ApplicationInsights.

**Comment by TimothyMothra** [comment]
Hi @rvanheest, the reason these attributes aren't mapped is because the RPC spec is still Experimental.
https://github.com/open-telemetry/semantic-conventions/blob/main/docs/rpc/rpc-spans.md

We're not planning any changes in this Exporter until these are stabilized.
