### ISSUE TITLE
[QUERY] Sending and filtering logs to 2 application insights from same ASP.Net core application

### ISSUE THREAD

**Issue by hemantkathuria** [Azure/azure-sdk-for-net#44911]
### Library name

Azure.Monitor.OpenTelemetry

### Please describe the feature.

I have to send logs to 2 application insights from same Asp.Net core application. Also, I want to filter logs for one destination.

 I can send to multiple destinations but not able to filter.  I have tried couple of syntaxes please see below

Tried to filter by custom Processor but no way to differentiate based on exporter.

Tried adding filter also but no way to distinguish between exporters //builder.Logging.AddFilter<OpenTelemetryLoggerProvider>((abc, lvl) =>

Option 1

```
builder.Logging.AddOpenTelemetry(options =>
{
   
    options.AddAzureMonitorLogExporter(options =>
    {
        options.ConnectionString = "InstrumentationKey=ApplicationInsights 1";
        
    });

    options.AddAzureMonitorLogExporter(options =>
    {
        options.ConnectionString = " InstrumentationKey=ApplicationInsights 2”
    });

});
```
Option 2

```
builder.Logging.AddOpenTelemetry(options =>
{
    options.AddProcessor(new LogFilteringProcessor());
    

    options.AddAzureMonitorLogExporter(options =>
    {
        options.ConnectionString = "InstrumentationKey=Application Insights 1";
        
    });

});

builder.Logging.AddOpenTelemetry(options =>
{
    options.AddAzureMonitorLogExporter(options =>
    {
        options.ConnectionString = "InstrumentationKey= Application Insights 2";
    });

});
```

**Comment by TimothyMothra** [comment]
We currently don't have a mechanism to filter logs based on their content. This is on our backlog and being discussed with the community. 

One workaround that might work for you, you could create a second LoggerFactory and use this instance for the subset of your logs. 
```csharp
LoggerFactory.Create(builder =>
{
    builder.AddOpenTelemetry(options =>
    {
        options.AddAzureMonitorLogExporter(o => o.ConnectionString = "2nd Application Insights Resource");
    });
});
var logger2 = loggerFactory.CreateLogger(logCategoryName);
```

**Comment by cijothomas** [comment]
same as https://github.com/Azure/azure-sdk-for-net/issues/32276

**Comment by vishweshbankwar** [comment]
@hemantkathuria - Please take a look at this https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/logs/dedicated-pipeline. Would this work for you?
