### ISSUE TITLE
Create Profile Packages for Azure Stack

### ISSUE THREAD

**Issue by shahabhijeet** [Azure/azure-sdk-for-net#4493]
- Create SDK Profile packages for Azure Stack
- This task will create individual packages for each RP with the right namespace

Cost: 3 days

**Comment by dsgouda** [comment]
Created and successfully compiled a solution for Compute hybrid profile.
Some issues with getting the solution to compile via msbuild using a scope parameter. Once that is fixed, a nuget package can be generated for the same.
