### ISSUE TITLE
[QUERY] Isolated model support for WebJobsAuthenticationEventsTrigger

### ISSUE THREAD

**Issue by tomkecy** [Azure/azure-sdk-for-net#44950]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.AuthenticationEvents 1.0.0

### Query/Question

Hello,
I've been looking into a custom claims provider and utilizing the WebJobsAuthenticationEventsTrigger instead of HttpTrigger.
I followed this tutorial https://learn.microsoft.com/en-us/entra/identity-platform/custom-extension-tokenissuancestart-setup?tabs=visual-studio%2Cazure-portal&pivots=nuget-library and noticed that the new Microsoft.Azure.WebJobs.Extensions.AuthenticationEvents supports only in-process model and I could not find anything about isolated model support planned.
As the in-process model is planned to be retired in the future, are there any plans and timelines for the AuthEvents support for the isolated worker model?

**Comment by jsquire** [comment]
//cc: @hakimms, @HarmanDhunna

**Comment by HarmanDhunna** [comment]
Hi @tomkecy,

Yes there is a plan to have support for isolated worker process but I can not share the timeline. What I can share is that Isolated worker process is currently under design and implementation.
