### ISSUE TITLE
[Docs] [DataMovement] Support Block type Blobs as destination during Blob Copy

### ISSUE THREAD

**Issue by ShaneCourtrille** [Azure/azure-sdk-for-net#44962]
### Library name

Azure.Storage.DataMovement

### Please describe the feature.

The [documentation](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/storage.datamovement.blobs-readme?view=azure-dotnet-preview) states that Blob Copy will always create an Append type blob which is a huge impediment to us using this library as we use Block Blobs due to the read heavy nature of our application.  Is this something that is planned to change in the near future?

**Comment by amnguye** [comment]
In the documentation are you asking about this portion talking about an example?

![image](https://github.com/user-attachments/assets/118bbd2b-61d7-48d8-afda-8866bcc9059c)

The statement "Note the destination blob is an append blob, regardless of the first blob's type" is referencing the code snippet below and is not an indication that all destination blobs will be Append blobs.
