### ISSUE TITLE
[QUERY] How can I write a test against AnalyzeResult which is a result of DocumentIntelligenceClient.AnalyzeDocument

### ISSUE THREAD

**Issue by yooontheearth** [Azure/azure-sdk-for-net#44975]
### Library name and version

AzureAI.DocumentIntelligence 1.0.0-beta.2

### Query/Question

I want to write a unit test against a result of DocumentIntelligenceClient.AnalyzeDocument, I mean AnalyzeResult.

```
var client = new DocumentIntelligenceClient(new Uri(endpoint), new AzureKeyCredential(apiKey));
var content = new AnalyzeDocumentContent()
{
    Base64Source = BinaryData.FromBytes(File.ReadAllBytes("table.pdf"))
};
Operation<AnalyzeResult> operation = client.AnalyzeDocument(WaitUntil.Completed, "prebuilt-layout", content);
AnalyzeResult result = operation.Value;   // <<< I want to write a test against this result.
```

Please note that I don't need to verify AnalyzeDocument or such, instead I want a test with the AnalyzeResult which contains paragraphs, or tables, or so on.

A problem is that I couldn't figure out how to create an instance of AnalyzeResult or mock it since its constructor is internal.
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/documentintelligence/Azure.AI.DocumentIntelligence/src/Generated/AnalyzeResult.cs

**Comment by jsquire** [comment]
Hi @yooontheearth.  Thanks for reaching out and we regret that you're experiencing difficulties.   The class that you're looking for is [DocumentIntelligenceModelFactory](https://learn.microsoft.com//dotnet/api/azure.ai.documentintelligence.documentintelligencemodelfactory?view=azure-dotnet-preview) which allows for creation of output types for unit testing purposes.  In this scenario, you'll want to use the [AnalyzeResult](https://learn.microsoft.com/dotnet/api/azure.ai.documentintelligence.documentintelligencemodelfactory.analyzeresult?view=azure-dotnet-preview#azure-ai-documentintelligence-documentintelligencemodelfactory-analyzeresult(system-string-system-string-azure-ai-documentintelligence-stringindextype-system-nullable((azure-ai-documentintelligence-contentformat))-system-string-system-collections-generic-ienumerable((azure-ai-documentintelligence-documentpage))-system-collections-generic-ienumerable((azure-ai-documentintelligence-documentparagraph))-system-collections-generic-ienumerable((azure-ai-documentintelligence-documenttable))-system-collections-generic-ienumerable((azure-ai-documentintelligence-documentfigure))-system-collections-generic-ienumerable((azure-ai-documentintelligence-documentlist))-system-collections-generic-ienumerable((azure-ai-documentintelligence-documentsection))-system-collections-generic-ienumerable((azure-ai-documentintelligence-documentkeyvaluepair))-system-collections-generic-ienumerable((azure-ai-documentintelligence-documentstyle))-system-collections-generic-ienumerable((azure-ai-documentintelligence-documentlanguage))-system-collections-generic-ienumerable((azure-ai-documentintelligence-analyzeddocument)))) method on the factory to build your test data.

More details and discussion of the design that we've used for testability can be found in [Unit testing and mocking with the Azure SDK for .NET](https://learn.microsoft.com/dotnet/azure/sdk/unit-testing-mocking?tabs=csharp).
