### ISSUE TITLE
[QUERY] SyncuploadFromuriasync uploads the blob with external URL, 403

### ISSUE THREAD

**Issue by jaelys** [Azure/azure-sdk-for-net#44976]
### Library name and version

Azure.Storage.Blobs 12.20.0

### Query/Question

The official document describes SyncuploadFromuriasync to support external URLs. As long as the source of HTTP get can be accessed, I have an external URL that can be opened in the browser and can be accessed with postman. Report 403, Azure.requestFaileDexception: 'This Request is not authorized to perform this operation.

Excuse me, does SyncuploadFromuriasync not support the access to the external URL with Query Parameters?

ex : https://abc.oss.com/output/8293e409e83e4d559f24fbe50/8293e409e83e4d55_20240710114350.json?Expires=1723175147&AccessKey=LTA4o1drkJN1TfCr&Signature=tiyBwLWZZ8yZubWGy6pT0%3D

### Environment

azure function and Azure AppService 
linux
.net 8

**Comment by nickliu-msft** [comment]
From my understanding, the SyncUploadFromUriAsync method does support accessing external URLs, including URLs with query parameters, as long as

The URL points to a publicly accessible resource or provides proper authorization credentials, and
The Azure Storage account and Blob service have the required permissions to access and retrieve content from that URL.
A 403 error typically means that the request lacks the necessary authorization to access the specified resource.
