### ISSUE TITLE
[FEATURE REQ] Update template and documentation for .NET SDK generation from TypeSpec

### ISSUE THREAD

**Issue by live1206** [Azure/azure-sdk-for-net#44998]
### Library name

Azure.ResourceManager

### Please describe the feature.

For new onboarding services, we should generate .NET SDK from TypeSpec input instead of swagger.

- We need to update `Azure.ResourceManager.Template` to take consideration of TypeSpec instead of swagger.
- Also, update the user guide in https://eng.ms/docs/products/azure-developer-experience/develop/sdk-generate-mgmt-dotnet to reflect the change.
- Update docker image to apply the TypeSpec input for new services @welovej

**Comment by welovej** [comment]
#45596
