### ISSUE TITLE
[QUERY] [Service Bus] Guidance for retrying with transactions

### ISSUE THREAD

**Issue by keir-nellyer** [Azure/azure-sdk-for-net#45008]
### Library name and version

Azure.Messaging.ServiceBus 7.17.1

### Query/Question

I am aware that retrying individual operations when in the context of a wider transaction is not possible [due to this](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/TROUBLESHOOTING.md#operations-in-a-transaction-are-not-retried).

My question is, how should we handle transient errors whilst in a transaction?

Would the recommended way be to retry the whole transaction? Something like:
```C#
var retryAttempts = 0;

while (retryAttempts < 3)
{
    try
    {
        using var ts = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled);

        await Task.WhenAll(
            args.SetSessionStateAsync(...),
            args.CompleteMessageAsync(...)
        );

        ts.Complete();
        return;
    }
    catch (ServiceBusException e)
    {
        if (!e.IsTransient)
        {
            throw;
        }
    }

    retryAttempts++;
    var retryDelay = Math.Min(Math.Pow(0.8, retryAttempts), 60);
    await Task.Delay(TimeSpan.FromSeconds(retryDelay));
}

// TODO Should probably throw the ServiceBusException if max retries has been exceeded
```

If not, what would be the recommended way?

In any case, could the documentation be updated to cover this, maybe an example added [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample06_Transactions.md)?

**Comment by JoshLove-msft** [comment]
Whether or not to retry the transaction would be highly dependent on the application scenario, but if you do want to retry then yes, you would need to retry the whole transaction since it will either succeed or fail as one atomic unit.
