### ISSUE TITLE
Nugget System.Text.Json has a vulnerability before 8.0.4

### ISSUE THREAD

**Issue by chaparo** [Azure/azure-sdk-for-net#45025]
https://github.com/Azure/azure-sdk-for-net/blob/442f867b186146a0fa292888d8a7b80a9dfd9db0/sdk/core/Azure.Core/src/Azure.Core.csproj#L28

**Comment by jsquire** [comment]
@chaparo:  [CVE 2024-30105](https://github.com/advisories/GHSA-hh2w-p6rv-4g7w) was updated to amend the STJ versions flagged as vulnerable to include only 7.0.0 - 8.0.3.   The Azure SDK packages, including Core, are using v4.7.2, which is not marked vulnerable.
