### ISSUE TITLE
Insufficient documentation on this API

### ISSUE THREAD

**Issue by jeremy-holovacs-sp** [Azure/azure-sdk-for-net#45034]
### Type of issue

Missing information

### Description

[Enter feedback here]
There is no description on what this does, how it works, or under what circumstances on how you would use it. We're looking at how we can dynamically update the connection string when using Power BI embedded for a customer-centric connection, and we think this might be the answer, but... there's literally no information on this.

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/microsoft.powerbi.api.datasetsoperations.updatedatasourcesingroupwithhttpmessagesasync?view=azure-dotnet#microsoft-powerbi-api-datasetsoperations-updatedatasourcesingroupwithhttpmessagesasync(system-guid-system-string-microsoft-powerbi-api-models-updatedatasourcesrequest-system-collections-generic-dictionary((system-string-system-collections-generic-list((system-string))))-system-threading-cancellationtoken)

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.PowerBI.Api/DatasetsOperations.xml

### Document Version Independent Id

1582c48b-ef59-41d7-4e36-ebc490edb491

### Article author

@azure-sdk

### Metadata

* ID: 11d33961-5ff3-9456-9d78-ff14e1757b88 
* Service: **powerbi**

**Comment by jsquire** [comment]
Hi @jeremy-holovacs-sp.  Thanks for reaching out and we regret that you're experiencing difficulties.   Unfortunately, the [repository](https://github.com/Microsoft/PowerBI-CSharp) where the `Microsoft.PowerBI.Api` library is maintained does not accept issues, so I'm unable to transfer this to the PowerBI team on your behalf.  To ensure that the right team has visibility and can help, your best path forward for would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) or inquire on the [Microsoft Q&A site](https://learn.microsoft.com/answers/questions/).   

I'm going to close this out; if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.
