### ISSUE TITLE
Microsoft Azure.WebJobs.Extensions.Durable Task: Could not load type 'Microsoft.Azure.WebJobs.Host.Scale.ITargetScalerProvider' from assembly 'Microsoft.Azure.WebJobs.Host, Version=3.0.34.0

### ISSUE THREAD

**Issue by bhaskarmbs** [Azure/azure-sdk-for-net#45036]
Please assist provide fix this error, it’s blocking my function execution locally
### Library name and version

Microsoft Azure.WebJobs.Extensions.Durable Task: Could not load type 'Microsoft.Azure.WebJobs.Host.Scale.ITargetScalerProvider' from assembly 'Microsoft.Azure.WebJobs.Host, Version=3.0.34.0

### Query/Question

Microsoft Azure.WebJobs.Extensions.Durable Task: Could not load type 'Microsoft.Azure.WebJobs.Host.Scale.ITargetScalerProvider' from assembly 'Microsoft.Azure.WebJobs.Host, Version=3.0.34.0

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the Microsoft.Azure.WebJobs.Extensions.Durable library is maintained as [#2877](https://github.com/Azure/azure-functions-durable-extension/issues/2877).

**Comment by lilyjma** [comment]
@bhaskarmbs - could you reply to this [issue](https://github.com/Azure/azure-functions-durable-extension/issues/2877) with a repro if you're still experiencing this?
