### ISSUE TITLE
Reopen this bug.

### ISSUE THREAD

**Issue by church365** [Azure/azure-sdk-for-net#45059]
Reopen this bug.
Update:
- The `List` operation will not return process details, it's by service design.
- We could get the process details with its `Id` (int number), like: 
   ```await instance.GetSiteInstanceProcesses().GetAsync("3040")```

- Found a new issue in SDK while deserialize response content. Class: `ProcessThreadInfo` property `id` is actually `int` value, not `ResourceIdentifier`. Need to correct it and release a new version to fix it.
![image](https://github.com/user-attachments/assets/9d6c73db-3c95-4450-abe8-52959946dbe9)

_Originally posted by @HarveyLink in https://github.com/Azure/azure-sdk-for-net/issues/39126#issuecomment-2232654686_

**Comment by jsquire** [comment]
Spam
