### ISSUE TITLE
Set cloud role name in App Insights using Open Telemetry[QUERY]

### ISSUE THREAD

**Issue by da-ms-22** [Azure/azure-sdk-for-net#45069]
### Library name and version

azure.monitor.opentelemetry.aspnetcore 1.1.1

### Query/Question

I'm using azure.monitor.opentelemetry.aspnetcore 1.1.1 to export Open Telemetry logs to App Insights in my .net 8 project. Cloud role name is set via service.name resource attribute. However, in App Insights, only requests and dependencies tables have cloud role name. All other tables, eg. traces and exceptions, have the default unknown_service:dotnet.

Thanks for your help.

```
var resourceAttributes = new Dictionary<string, object>
  {
      { "service.name", "MyCloudRoleName" },
  };

  services.ConfigureOpenTelemetryTracerProvider((sp, builder) =>
  {
      builder.SetResourceBuilder(ResourceBuilder.CreateDefault().AddAttributes(resourceAttributes));
  });
```

**Comment by TimothyMothra** [comment]
Hi @da-ms-22 , 
Looks like our doc page doesn't have a complete example. I'll work on getting this updated.

Please try this example:
```csharp
Dictionary<string, object> _testResourceAttributes = new()
{
    { "service.name", TestServiceName },
    { "service.namespace", TestServiceNamespace },
    { "service.instance.id", TestServiceInstance },
    { "service.version", TestServiceVersion }
};

builder.Services.AddOpenTelemetry()
    .UseAzureMonitor(options =>
    {
        options.ConnectionString = "YOUR CONNECTION STRING"
    })
    // Custom resources should be added AFTER AzureMonitor to override the default ResourceDetectors.
    .ConfigureResource(x => x.AddAttributes(_testResourceAttributes));

```

**Comment by TimothyMothra** [comment]
I submitted a doc fix for here: https://learn.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-configuration?tabs=aspnetcore#set-the-cloud-role-name-and-the-cloud-role-instance
It should be published by tomorrow morning.

Please let us know if this fully addresses your issue.

**Comment by da-ms-22** [comment]
Thank you, @TimothyMothra! This solution fixes my issue completely. All tables have the correct cloud role name.
