### ISSUE TITLE
[QUERY] How can I exclude table content from Paragraphs in PDF analysis to prevent duplication?

### ISSUE THREAD

**Issue by yooontheearth** [Azure/azure-sdk-for-net#45068]
### Library name and version

AzureAI.DocumentIntelligence 1.0.0-beta.2

### Query/Question

There is a PDF that contains a table and some text. When I analyze it using DocumentIntelligenceClient.AnalyzeDocument, I get AnalyzeResult.Tables and AnalyzeResult.Paragraphs as a result. The problem I am facing is that the paragraphs also include the table content. Is there any way to exclude the table content from the paragraphs? I want to use them as a source for RAG, so duplicate content is not desirable.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by yooontheearth** [comment]
Oh I finally figured out how to achieve to exclude table content from AnalyzeResult.Paragraphs. I just need to refer AnalyzeResult.Sections and retrieve a reference from that array recursively.
