### ISSUE TITLE
[QUERY] When will a new release of Azure.AI.OpenAI occur?

### ISSUE THREAD

**Issue by crickman** [Azure/azure-sdk-for-net#45060]
### Library name and version

Azure.AI.OpenAI 2.0.0-beta2

### Query/Question

Quite a few bug-fixes and imrovements have been made to the OpenAI dependency:

https://www.nuget.org/packages/OpenAI/2.0.0-beta.7

What is the timeline for bringing parity to `Azure.AI.OpenAI` via a new release?

**Comment by crickman** [comment]
@trrwilson - Any insight on next release for https://www.nuget.org/packages/Azure.AI.OpenAI/2.0.0-beta.2?

**Comment by gerrit-amagno** [comment]
Any news? And will the next version include support for GPT 4o mini?

**Comment by crickman** [comment]
@trrwilson - OpenAI beta9 will contains support for structured-output - be a nice release on which to snap:

https://github.com/openai/openai-dotnet/pull/164

**Comment by crickman** [comment]
https://www.nuget.org/packages/Azure.AI.OpenAI/2.0.0-beta.3
