### ISSUE TITLE
[FEATURE REQ] Allow defining export interval on PeriodicExportingMetricReader when using AddAzureMonitorMetricExporter extension

### ISSUE THREAD

**Issue by EdwinVanVliet** [Azure/azure-sdk-for-net#45074]
### Library name

Azure.Monitor.Opentelemetry.Exporter

### Please describe the feature.

The metric exporter only allows exporting every minute by default, while we would like to be able to define this to our own needs. We are burning a lot of data, while we are totally fine with less frequent metrics 99% of the time. The class `PeriodicExportingMetricReader.cs` already has an argument for this in the constructor, only the `MeterProviderBuilder.cs` class does not support setting this.

    public static IServiceCollection AddOpenTelemetryWithApplicationInsights(this IServiceCollection services, string? connectionString, string version)
    {
        services.AddOpenTelemetry()
            .ConfigureResource(r => {
                r.AddService(serviceName: "ServiceName", serviceInstanceId: "ServiceInstanceId", serviceVersion: version);
            })
            .WithMetrics(builder =>
            {
                builder.AddMeter("MeterName");
                builder.AddAzureMonitorMetricExporter(config =>
                {
                    config.ConnectionString = connectionString;
                });
            });

        return services;
    }

Would be great if the `AddAzureMonitorMetricExporter` function supports setting the `exportIntervalMilliseconds` on the constructor of `PeriodicExportingMetricReader` class.

**Comment by cijothomas** [comment]
This is a backend restriction. AzureMonitor only allows 1 minute intervals.
(It _may_ change in the future)
