### ISSUE TITLE
[FEATURE REQ] Set, or support setting, App Insights session ID and user ID via otel exporter

### ISSUE THREAD

**Issue by johncrim** [Azure/azure-sdk-for-net#45089]
### Library name

Azure.Monitor.OpenTelemetry.Exporter 1.3.0

### Please describe the feature.

The `Microsoft.ApplicationInsights.AspNetCore` library automatically writes `session_Id` and `user_Id` and `authUserId` values for requests, dependencies, and traces/logging based on the `ai_session` and `ai_user` cookies. These values are completely missing from the `Azure.Monitor.OpenTelemetry.Exporter` output, even though there are placeholder keys in `ContextTagKeys`. This could be considered a bug, or just a missing feature.

This is pretty critical functionality because it allows one to correlate all activity with a user session and a unique user (well, at least all telemetry in the async context, but not cross-process telemetry). Since the Exporter logic is internal and there are no extension points to modify the telemetry, there is no way to set this property.

The corresponding telemetry initializer in app insights classic are:
* [Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/WebSessionTelemetryInitializer.cs](https://github.com/microsoft/ApplicationInsights-dotnet/blob/main/NETCORE/src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/WebSessionTelemetryInitializer.cs)
* [Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/WebUserTelemetryInitializer.cs](https://github.com/microsoft/ApplicationInsights-dotnet/blob/main/NETCORE/src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/WebUserTelemetryInitializer.cs)

The workaround I have right now sets these Activity tags and LogRecord attributes using the cookie value, but I have to use custom properties because there's no way to set the root properties; which means the app insights web UI to show all telemetry for a user or user session doesn't work.

One opportunity we have here is to use the Baggage API to flow the userId and sessionId to downstream + out of process activities, which is a significant improvement from app insights classic.

**Comment by johncrim** [comment]
Here's what I have now - it gets me most of the way to the functionality that I want, but I would like to be able to populate the "standard" fields so the app insights web UI works as expected.

I'm using request enrichment to set values based on the request; and then Baggage and Processors to add the values to downstream activities and log records.

```cs
/// <summary>
/// Initializes request telemetry, and sets baggage, to log and propagate the app insights sessionId
/// and userId values to downstream operations.
/// </summary>
internal sealed class AppInsightsIdsRequestTelemetryInitializer : IEnrichRequestTelemetry
{

    private const string c_aiSessionCookieKey = "ai_session";

    private const string c_aiUserCookieKey = "ai_user";

    public void Enrich(Activity activity, HttpRequest request)
    {
        if (TryGetAppInsightsIdFromCookie(request, c_aiSessionCookieKey, out var sessionId))
        {
            activity.AddTag(OtelKey.AiSessionIdValue, sessionId);

            // Use otel Baggage to the AI sessionID propagates to downstream processes
            Baggage.SetBaggage(OtelKey.AiSessionIdValue, sessionId);
        }

        // AI user ID is _not_ our user id
        if (TryGetAppInsightsIdFromCookie(request, c_aiUserCookieKey, out var aiUserId))
        {
            activity.AddTag(OtelKey.AiUserIdValue, aiUserId);

            // Propagate downstream
            Baggage.SetBaggage(OtelKey.AiUserIdValue, aiUserId);
        }
    }

    private static bool TryGetAppInsightsIdFromCookie(HttpRequest request, string cookieKey, [NotNullWhen(true)] out string? value)
    {
        if (request.Cookies.TryGetValue(cookieKey, out var cookieValue))
        {
            if (! string.IsNullOrEmpty(cookieValue))
            {
                var cookieParts = ((string) cookieValue).Split('|');
                if (cookieParts.Length >= 1)
                {
                    value = cookieParts[0];
                    return true;
                }
            }
        }

        value = null;
        return false;
    }

}

/// <summary>
/// Adds tags to activity that are stored in request baggage.
/// </summary>
/// <remarks>
/// The objective here is to duplicate key tags in all downstream activities, eg
/// app insights session.id and user.id are useful in the whole downstream tree.
/// </remarks>
internal sealed class AddRequestBaggageActivityProcessor : BaseProcessor<Activity>
{

    public override void OnStart(Activity activity)
    {
        if (activity.IsAllDataRequested)
        {
            foreach (var kvp in Baggage.GetBaggage())
            {
                // We only expect "ai.*" telemetry in Baggage, so only copy those into tags
                if (kvp.Key.StartsWith("ai."))
                {
                    activity.SetTag(kvp.Key, kvp.Value);
                }
            }
        }
    }

}

/// <summary>
/// Adds tags to log records that are stored in request activity baggage.
/// </summary>
internal sealed class AddRequestBaggageLogRecordProcessor : BaseProcessor<LogRecord>
{

    public override void OnStart(LogRecord logRecord)
    {
        foreach (var kvp in Baggage.GetBaggage())
        {
            // We only expect "ai.*" telemetry in Baggage, so only copy those into tags
            if (kvp.Key.StartsWith("ai."))
            {
                logRecord.Attributes.Append(new(kvp.Key, kvp.Value));
            }
        }
    }

}
```

**Comment by johncrim** [comment]
Related to the above; slight correction in my bug report/feature request: `user_AuthenticatedId` does work as expected, at least for Activity logging. When I add a tag to an activity with key `"enduser.id"`, the `user_AuthenticatedId` is populated as expected on the request row.

As of right now I cannot confirm whether `user_AuthenticatedId` can be populated on dependencies or traces.

**Comment by TimothyMothra** [comment]
I'm consolidating all issues regarding overriding specific fields in the Application Insights schema into another issue to help with tracking. https://github.com/Azure/azure-sdk-for-net/issues/46021

**Comment by johncrim** [comment]
I think this should be re-opened. #46021 is related, but this issue is mainly about making it work automatically, for consistency with AI classic. Or having configuration to turn it on.

**Comment by hansmbakker** [comment]
@TimothyMothra can you please reopen this?

It looks like setting the opentelemetry tag `enduser.id` indeed sets the top-level `user_AuthenticatedId`, but it does not fully work as expected:
- it does not set `user_Id` resulting in the `All users` bar chart to be filled with the value `1`. The below chart should have a higher value at the end of the timeline:
  ![Image](https://github.com/user-attachments/assets/d0180cc2-b011-4a04-8eb5-f684b1b37fef)
- **only when manually choosing `Authenticated users` from the dropdown**, it works:
  ![Image](https://github.com/user-attachments/assets/b138e712-6cbc-4b10-afbd-bfdc4f52ee8c)
- [`enduser.id` is deprecated and is recommended to be replaced by `user.id`](https://github.com/open-telemetry/opentelemetry-js/blob/5e1736130e76561b59f289a313b26b9abc88dfd0/semantic-conventions/src/experimental_attributes.ts#L2387-L2396)
