### ISSUE TITLE
Facebook

### ISSUE THREAD

**Issue by Kelvinturcios** [Azure/azure-sdk-for-net#45111]
### Type of issue

Typo

### Description

[Escriba sus comentarios aquí]

### Page URL

https://learn.microsoft.com/es-es/dotnet/api/azure.resourcemanager.appcontainers.models.containerappfacebookconfiguration.isenabled?view=azure-dotnet#azure-resourcemanager-appcontainers-models-containerappfacebookconfiguration-isenabled

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.ResourceManager.AppContainers.Models/ContainerAppFacebookConfiguration.xml

### Document Version Independent Id

d1ddc19e-7527-7890-d910-ab70658c1c96

### Article author

@azure-sdk

### Metadata

* ID: eeae57e1-223f-2a24-0d21-50cad7bd5322 
* Service: **azure**

**Comment by ArthurMa1978** [comment]
Hey @Kelvinturcios , thank you for your feedback, please provide more information about the 'typo'? And this page is auto-translated from English.
