### ISSUE TITLE
.Net Runtime crashes with Azure.Messaging.ServiceBus 7.17.5

### ISSUE THREAD

**Issue by DLackmeyer** [Azure/azure-sdk-for-net#45128]
### Library name and version

Azure.Messaging.ServiceBus 7.17.5

### Describe the bug

We recently updated our service from Azure.Messaging.ServiceBus 7.17.1 to 7.17.5. After doing so, our service began crashing due to the framework being terminated:
> The process was terminated due to an internal error in the .NET Runtime at IP 791F9AAA (79140000) with exit code 80131506.

This was a non-deterministic crash that would occur approximately ever 2-15 minutes. Documentation indicates that this error tends to occur when the heap is determined to be corrupt during GC.

Rolling back to 7.17.1 resolved the problem. 7.18.0 was not available at the time we experienced this, so I don't currently know if the behavior still repros.

### Expected behavior

No app crashes due to memory corruption

### Actual behavior

Intermittent crashes

### Reproduction Steps

We have only reproduced this in the context of our own live service environments. I am internal to MS and am happy to provide an environment for investigation if needed.

### Environment

Win Server 2019
.NET Framework 4.8

**Comment by jsquire** [comment]
@DLackmeyer.  Thanks for reaching out and we regret that you're experiencing difficulties.  Our nightly test runs as well as prolonged stress test runs have not seen this behavior when running on the .NET Framework, nor have we seen other reports of this.   To assist, it would be quite helpful to have a stand-alone minimal reproduction that we could use for testing in different environments.  If you have a process dump available in the crashed state, that would also be helpful.

Within the Service Bus library, the most likely cause would be the bump to the AMQP dependency done in 7.13.3.   It may also be helpful to see if using 7.17.1 and taking a direct reference to `Microsoft.Azure.Amqp` v2.6.5 in your application manifests the behavior in the same way.

**Comment by DLackmeyer** [comment]
Excellent, thank you. We appear to be on a pretty ancient version of Microsoft.Azure.Amqp (1.3.0). I'll try pushing to something much more recent and see if that helps.
