### ISSUE TITLE
[QUERY] Document Permanent Delete Blob behavior using SDK

### ISSUE THREAD

**Issue by KyleMit** [Azure/azure-sdk-for-net#45131]
### Library name and version

Azure.Storage.Blobs 12.19.1

### Query/Question

This feature has been requested in

[[FEATURE REQ] Need Azure Blob Storage Permanent Delete #18983](https://github.com/Azure/azure-sdk-for-net/issues/18983)
[[FEATURE REQ] Pemanent delete Blob (include blob version) #29213](https://github.com/Azure/azure-sdk-for-net/issues/29213)

A possible solution was worked on in [Feature/storage/blob permanent delete #16229](https://github.com/Azure/azure-sdk-for-net/pull/16229), but reverted a day later.

We have hard requirements when CSAM images are deleted, they they not be allowed to exist as Soft Deletes for any period of time after removal.  If it's not going to be worked on, it would be helpful to share the reasoning proposed by the Azure Arch board.  Are there API designs that could prevent accidental deletion, like requiring `DeleteAsync` to be called a second time (one for soft delete, one for hard delete) or extending surface area with something like `DeletePermanantAsync` to avoid ambiguity?

It would also be good to add a note to [Delete and restore a blob with .NET](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blob-delete) with caveats on hard deletion.

**Comment by seanmcc-msft** [comment]
@KyleMit, the Azure SDK Arch Board made the decision to not include this feature in the SDKs several years ago.  The reasoning is that one of the main reasons customers contract customer support is because they accidently deleted their blobs or containers.  If a blob is permanently deleted, it is not possible to restore, which could result in a very negative customer experience.

**Comment by KyleMit** [comment]
Thanks @seanmcc-msft, is it also possible to add that info to the SDK help page on how to [delete and restore a blob with .NET](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blob-delete) with caveats on hard deletion?
