### ISSUE TITLE
System.ObjectDisposedException at Azure.Messaging.ServiceBus.ServiceBusReceiver

### ISSUE THREAD

**Issue by verdysh** [Azure/azure-sdk-for-net#45143]
### Library name and version

Azure.Messaging.ServiceBus 7.17.4

### Query/Question

Today I found in logs about 3k items within a minute with the following issues:

> ServiceBusReceiver has already been closed and cannot perform the requested operation. Object name: 'ServiceBusReceiver'.

It threw the exceptions at the line:
`var messages = await _receiver.ReceiveMessagesAsync(_config.MaxMessages, _config.MaxWaitTimeout);`

Despite the above, the app looks healthy and ServiceBus's queues are being processed.

My questions are the following:
1. Why might this happen?
2. Can ServiceBusReceiver recover from the problem on its own? Should I handle this manually?

**Comment by jsquire** [comment]
Hi @verdysh.  If you're seeing that message, it indicates that your application has either closed/disposed the `ServiceBusClient` instance that spawned the receiver or closed the receiver itself.  As a result, the connection and other network resources associated with the receiver have been reclaimed and the receiver instance is no longer usable.

The recommended mitigation is not to close/dispose the client or receiver until your application is done using them.

**Comment by verdysh** [comment]
My code calls DisposeAsync for the Receiver and then for the Client from the StopAsync method of the HostedService that runs the consumer. This can happen only in case of app's grateful shootdown. There is no way in the app to run new consumer besides run of the HostedService (which can happen only when app starts).

The app is run in the Azure. Looks like something happened and the app was turned off and turn on back.

Thanks for the answer!
