### ISSUE TITLE
[QUERY] Logic App Standard - List Workflow Run Actions

### ISSUE THREAD

**Issue by matthewpavia99** [Azure/azure-sdk-for-net#45147]
### Library name and version

Azure.ResourceManager.AppService 1.0.2

### Query/Question

Is it possible to list the workflow run actions of a Logic App (Standard)? I cannot find anything related in the Azure.ResourceManager.AppService SDK. The `GetLogicWorkflowRunActions` in the Azure.ResourceManager.Logic SDK works for Logic App Consumption but doesn't seem to work for Standard LA's.

Thanks!

### Environment

Windows
.Net 8

**Comment by welovej** [comment]
hi @matthewpavia99   

As of my last update, the Azure SDK for .NET (Azure.ResourceManager) provides different classes and methods for interacting with Logic App Standard. Specifically, you should use the Azure.ResourceManager.Logic namespace for Logic App Consumption, and for Logic App Standard, you'll need to use the Azure.ResourceManager.AppService namespace.

As of now, direct support for listing workflow run actions in Logic App Standard using Azure.ResourceManager.AppService SDK might not be available. Using the Azure REST API with an authenticated HttpClient is a viable alternative. Keep an eye on the official Azure SDK documentation for any updates or new releases that might include direct support for this functionality.

---

 try this sample code below, hope to solve your problem.

```
            var credential = new DefaultAzureCredential();
            var token = await credential.GetTokenAsync(new TokenRequestContext(new[] { "https://management.azure.com/.default" }));
            var subscriptionId = "your subscriptionId ";
            var resourceGroupName = "your resourceGroupName ";
            var workflowName = "your workflowName ";
            var siteName = "your siteName(standard logic app name)";
            var client = new HttpClient();
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token.Token);
            var url = $"https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Web/sites/{siteName}/workflows/{workflowName}/?api-version=2020-12-01";
            var response = await client.GetAsync(url);
            var content = await response.Content.ReadAsStringAsync();

```
