### ISSUE TITLE
[FEATURE REQ] SignalR Scaleout with Azure Service Bus

### ISSUE THREAD

**Issue by kajusknoras** [Azure/azure-sdk-for-net#45140]
### Library name

Azure.Messaging.ServiceBus

### Please describe the feature.

With the previous Azure SDK (WindowsAzure.ServiceBus) it was possible to do so. In a .NET Framework (4.8) application, whilst migrating to Azure.Messaging.ServiceBus, we've realized that support for scaling out for SignalR, that was originally achievable with `GlobalHost.DependencyResolver.UseServiceBus(connectionString, topicPrefix)` does not exist.

 This is now missing or is not documented. Perhaps one of the alternatives could be that support for Microsoft.AspNet.SignalR.ServiceBus3 or Microsoft.AspNet.SignalR.ServiceBus is added with Azure.Messaging.ServiceBus?

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.AspNet.SignalR.ServiceBus` package is maintained as [#](https://github.com/SignalR/SignalR/issues/4715).

**Comment by kajusknoras** [comment]
Thanks for the update, but from what I understand there will be no updates from the other project's side, as it is the first thing that is mentioned on the README.md there:

`IMPORTANT: There will be no new features added to this product`

**Comment by jsquire** [comment]
@kajusknoras:  Then there is no path forward.   The functionality that you're looking for was not part of the Service Bus library directly and was enabled via the bridge packages that you mentioned.  If they've chosen not to move that to a later version of the Azure SDK package, then there's nothing that the Service Bus client library can do.
