### ISSUE TITLE
Is it possible to limit or control the exception message logs when service bus queue is disabled?

### ISSUE THREAD

**Issue by anandank04** [Azure/azure-sdk-for-net#45146]
### Library name and version

Azure.Messaging.ServiceBus 7.17.5

### Query/Question

When the Azure Service bus 's queue status is disabled, the SDK logs the below exception message for every second till becomes active.

```
[2024-07-22 15.13.54.154 fail: Azure.Messaging.ServiceBus]  [QUEUE-NAME]-8d0c9cd6-b856-4cec-95ce-1ad57b4d3bf8-Receiver: ReceiveBatchAsync Exception: Azure.Messaging.ServiceBus.ServiceBusException: Messaging entity 'sb://[QUEUE_URL]' is currently disabled. For more information please see
https://aka.ms/ServiceBusExceptions
. TrackingId:3b2425f25e794b098f5973269b1826f9_G4, SystemTracker:gateway7, Timestamp:2024-07-22T09:43:54 (MessagingEntityDisabled). For troubleshooting information, see
https://aka.ms/azsdk/net/servicebus/exceptions/troubleshoot.
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.ReceiveMessagesAsyncInternal(Int32 maxMessages, Nullable`1 maxWaitTime, TimeSpan timeout, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<>c.<<ReceiveMessagesAsync>b__44_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken, Boolean logTimeoutRetriesAsVerbose)
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken, Boolean logTimeoutRetriesAsVerbose)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.ReceiveMessagesAsync(Int32 maxMessages, Nullable`1 maxWaitTime, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ServiceBusReceiver.ReceiveMessagesAsync(Int32 maxMessages, Nullable`1 maxWaitTime, Boolean isProcessor, CancellationToken cancellationToken)
```

Since it logs every second, we don't want to populate the logs and tried to stop the `ServiceBusProcessor` using `StopProcessingAsync(CancellationToken)`, `CloseAsync(CancellationToken)` and `DisposeAsync` methods but it's not returning or timing out when the service bus's queue status is disabled.

Do you guys have any workaround to limit or control the time gap between each log?

**Comment by jsquire** [comment]
Hi @anandank04.  Thanks for reaching out and we regret that you're experiencing difficulties.  We do not recommend disabling an entity while you have clients actively using it.    Guidance would be to stop the clients before disabling an entity.    

Errors are logged each time a service operation fails.  Because you left your processor running, it will continue to try and make forward progress after a read fails.  Because the error itself is non-transient, there is no retry policy/delay applied.  The processor raises the failure to your error handler and will attempt to recover.  Calling `StopProcesingAsync` is the right mitigation if you find yourself in this situation, but it will wait for a graceful shutdown of all processing tasks and may take time depending on how many degrees of concurrency you've set, how long your TryTimeout, and will wait for any outstanding calls to your processing handler to complete.

**Comment by anandank04** [comment]
Hi @jsquire, Yes, we tried calling `StopProcesingAsync`but that doesn't return anything for long and we didn't set `TryTimeout` and I see its default value is 60 seconds.

**Comment by jsquire** [comment]
> Hi @jsquire, Yes, we tried calling `StopProcesingAsync`but that doesn't return anything for long and we didn't set `TryTimeout` and I see its default value is 60 seconds.

@anandank04:  This is not a scenario that we're able to reproduce.  To assist, we'll need to ask that you grab a 5-minute slice of verbose SDK logs around the behavior.  It would also be helpful if you could provide a small self-contained app that demonstrates how to reproduce the behavior.     Guidance for capturing logs can be found in:  [Logging with the Azure SDK for .NET](https://learn.microsoft.com/dotnet/azure/sdk/logging).

**Comment by anandank04** [comment]
@jsquire, I have attached the logs and also created a self-contained app. Please have a look. And below are the steps to reproduce the issue:
1. Set the status of Service bus queue to "Active"
2. Run the Self-contained app.
3. Once, the app connects to service bus, set the status of Service bus queue to "Disabled"

Due to disable, for every second, SDK calls `ErrorHandler` method, but we don't wanna populate the logs rather tried to stop the ServiceBusProcessor using StopProcessingAsync(CancellationToken), CloseAsync(CancellationToken) and DisposeAsync methods in `ErrorHandler` method but it's not returning or timing out when the service bus's queue status is disabled.

We wanna know if there is any workaround to stop the ServiceBusProcessor when its disabled or control the time gap between each log?

[Logs.txt](https://github.com/user-attachments/files/17055490/Logs.txt)
[ServiceBusQueueQuickStart.zip](https://github.com/user-attachments/files/17055521/ServiceBusQueueQuickStart.zip)

**Comment by jsquire** [comment]
Hi @anandank04.  Your logs indicate that `StopProcessingAsync` was never called before the program terminates.  Your program is structured such that there's a `Console.ReadKey` blocking the main thread and it does not look as if you pressed a key to exit but rather terminated in another way.

Running your code, I'm unable to reproduce the behavior that you're reporting.  When I launch the code and run, the log messages stream to the console despite it waiting for input.  When I press a key to terminate, I see the expected logs that indicate the processor is stopping and I see an ordered shutdown:

```text
[Informational] Azure-Messaging-ServiceBus: test-f111956c-d19c-4376-a69d-8551c3dd8703: StopProcessingAsync start.
...
<< SNIP: additional errors while stop is attempted >>
...
[Informational] Azure-Messaging-ServiceBus: test-f111956c-d19c-4376-a69d-8551c3dd8703: StopProcessingAsync done.
[Verbose] Azure-Messaging-ServiceBus: Closing a ServiceBusReceiver (Identifier 'test-f111956c-d19c-4376-a69d-8551c3dd8703-Receiver').
[Verbose] Azure-Messaging-ServiceBus: A ServiceBusReceiver has been closed (Identifier 'test-f111956c-d19c-4376-a69d-8551c3dd8703-Receiver').
13:36:38 info: Program[0] Stopped receiving messages
[Verbose] Azure-Messaging-ServiceBus: Closing a ServiceBusClient (Identifier 'squire-test.servicebus.windows.net-307de418-dfcd-4ab6-8ce4-44d3b8ddc4ce').
[Verbose] Azure-Messaging-ServiceBus: A ServiceBusClient has been closed (Identifier 'squire-test.servicebus.windows.net-307de418-dfcd-4ab6-8ce4-44d3b8ddc4ce').
```

As previously mentioned, the processor is intended to be robust and continue to try and make forward progress in the face of errors.  The responsibility of the application is to use the error handler to observe error pattens over time, make the decision as to whether these should be considered terminal for the application and, if so, terminate the processor.

**Comment by jsquire** [comment]
@anandank04: You cannot invoke `StopProcessingAsync` from within the error handler.  This will deadlock your application, as detailed in the [documentation for the error handler](https://learn.microsoft.com/dotnet/api/azure.messaging.servicebus.servicebusprocessor.processerrorasync?view=azure-dotnet#remarks).

**Comment by anandank04** [comment]
@jsquire, if the status of Service bus queue to `Disabled`, then how can we stop the processor. Is there any other way?

**Comment by jsquire** [comment]
@anandank04:

We generally recommend that you use a cancellation token as an intermediary.   For example:

```csharp
        public async static Task Main()
	{
		using var cancellationSource = new CancellationTokenSource();
		
		var processor = new ServiceBusProcessor();
		
                 // NOTE:  
                 //    This is a basic example for illustration.  We do not
                 //     recommend stopping the processor on every error.
                 //
		processor.HandleErrorAsync += args =>
		{
			cancellationSource.Cancel();
			return Task.CompletedTask;
		};
		
                 // Start the processor
		await processor.StartProcessingAsync();		
		
                 // Wait forever until something cancels the token.  That may be a disabled
                 // error or may be your application wanting to exit.
                 //
		try
		{
		    await Task.Delay(Timeout.Infinite, cancellationSource.Token);
		}
		catch (OperationCanceledException)
		{
			// Expected on cancellation.
		}
		
                 // At this point, we know the application is expecting to exit.  Stop
                 // the processor.
                 //
		await processor.StopProcessingAsync();				
	        Console.WriteLine("Done");
    }
```
