### ISSUE TITLE
[QUERY] Unexpected query results

### ISSUE THREAD

**Issue by civbaron** [Azure/azure-sdk-for-net#45166]
### Library name and version

Azure.ResourceManager.CosmosDB

### Query/Question

When pulling the cosmosdbaccounts for a subscription I am getting a phantom account showing up. It does not appear in the UI but it does return in the call to GetCosmosDBAccounts(). 

This is an old account that has been deleted for at least a year.

### Environment

Azure Function using latest release package of the Azure.ResourceManager.CosmosDB

**Comment by HarveyLink** [comment]
Hi @civbaron ,
Thank you for using Azure SDK for .NET.
The SDK only returns what service give us. In this case, you could [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) to get further help.
