### ISSUE TITLE
[BUG] ResourceManager.AppService error

### ISSUE THREAD

**Issue by chenryIDSTC** [Azure/azure-sdk-for-net#45177]
### Library name and version

Azure.ResourceManager.AppService 1.0.2

### Describe the bug

Method - GetAppServiceCertificateOrdersAsync - failing

public static AsyncPageable<AppServiceCertificateOrderResource> GetAppServiceCertificateOrdersAsync(this SubscriptionResource subscriptionResource, CancellationToken cancellationToken = default)

The failure occurs seemingly after the certificate order data is returned. About 7 seconds after initiating the request.

Full exception:

{"data":"System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'resourceType')\r\n   at Azure.Core.ResourceType..ctor(String resourceType)\r\n   at Azure.ResourceManager.AppService.AppServiceCertificateOrderData.DeserializeAppServiceCertificateOrderData(JsonElement element)\r\n   at Azure.ResourceManager.AppService.SubscriptionResourceExtensionClient.<GetAppServiceCertificateOrdersAsync>b__103_2(JsonElement e)\r\n   at Azure.Core.PageableHelpers.PageableImplementation`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()\r\n   at Azure.Core.PageableHelpers.PageableImplementation`1.GetAsyncEnumerator(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()\r\n   at IdstcAdmin.Controllers.ReportsController.GetAppServiceCertificates() in C:\\git_idstc\\IdstcAdmin\\IdstcAdmin\\Controllers\\ReportsController.cs:line 901\r\n   at IdstcAdmin.Controllers.ReportsController.GetAppServiceCertificates() in 

### Expected behavior

Return app service certificate orders

### Actual behavior

Exception:

specified argument was out of the range of valid values. (parameter 'resourcetype')

### Reproduction Steps

  var subscriptionId = Environment.GetEnvironmentVariable("SubscriptionID");
  var credential = new DefaultAzureCredential();
   var armClient = new ArmClient(credential, subscriptionId);
    var resourceId = SubscriptionResource.CreateResourceIdentifier(subscriptionId);
    var subscription = armClient.GetSubscriptionResource(resourceId);                        
    var certOrders = subscription.GetAppServiceCertificateOrdersAsync();

    if (certOrders != null) {
        await foreach (var certOrder in certOrders) {
            var blah = certOrder;
            }
    }

### Environment

Windows 11 
dotnet 8.0.303

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by welovej** [comment]
PR: #45343
