### ISSUE TITLE
[QUERY] How to properly mock extensions methods for ArmClient

### ISSUE THREAD

**Issue by mbaranovych** [Azure/azure-sdk-for-net#45179]
### Library name and version

Azure.ResourceManager.ServiceFabricManagedClusters 1.2.0

### Query/Question

Hi team.
We are trying to write some UTs, in which we need to mock SFMC extension methods (`ServiceFabricManagedClustersExtensions` class) on `ArmClient` (e.g. `GetServiceFabricManagedClusterResource`).

We can see description of the method that mentions: "_To mock this method, please mock MockableServiceFabricManagedClustersArmClient.GetServiceFabricManagedApplicationTypeResource(ResourceIdentifier) instead._", however we can't find a way how to do it properly. **Do you have any docs or examples we could follow to get an idea about proper mocking**?

We can see that `MockableServiceFabricManagedClustersArmClient` is used on top of ArmClient in the extension methods, but all constructors either protected or internal, are we supposed to create derived class and override method there? If so, how do we "connect" that class with extension methods class?

We checked this PR: #37927, but it didn't help with ideas on actual usage, and it seems that official docs are also non-existent.

Will appreciate any input, thanks!

**Comment by scottaddie** [comment]
@mbaranovych We have guidance available at https://learn.microsoft.com/dotnet/azure/sdk/unit-testing-mocking?tabs=csharp#understand-azure-resource-manager-arm-clients. Please read through it, and let us know what questions you have.

**Comment by mbaranovych** [comment]
@scottaddie thanks a lot for sharing a link, weird we didn't find it ourselves..
I reviewed the docs, it is helpful. However, we noticed that for some classes it's not possible to create an object with needed values or mock it. E.g. `ServiceFabricManagedClusterData`, there is no way for us to create a mock or an object with specified `ClusterId`, while with an old SDK library (`Microsoft.Azure.Management.ServiceFabricManagedClusters`) it was possible.
Are we missing something?

**Comment by scottaddie** [comment]
@jsquire What would you recommend for [ServiceFabricManagedClusterData](https://github.com/Azure/azure-sdk-for-net/blob/e5b40918cfd3d32518914d97109158399d7eef3c/sdk/servicefabricmanagedclusters/Azure.ResourceManager.ServiceFabricManagedClusters/src/Customization/ServiceFabricManagedClusterData.cs#L24C74-L36C10)?

**Comment by jsquire** [comment]
@mbaranovych, @scottaddie:  Creation of `ServiceFabricManagedClusterData` would be done using the model factory, as described in the article when discussing output only types.   In this case, you'd be looking for [ArmServiceFabricManagedClustersModelFactory.ServiceFabricManagedClusterData](https://learn.microsoft.com/dotnet/api/azure.resourcemanager.servicefabricmanagedclusters.models.armservicefabricmanagedclustersmodelfactory.servicefabricmanagedclusterdata?view=azure-dotnet-preview
