### ISSUE TITLE
Support for Manager Identity modification

### ISSUE THREAD

**Issue by William-HCX** [Azure/azure-sdk-for-net#45175]
### Type of issue

Other (describe below)

### Description

Is there a plan for DocumentClient to support Manager Identity modification?

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.client.documentclient?view=azure-dotnet

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Client/DocumentClient.xml

### Document Version Independent Id

fe52c0b4-01af-f215-45f0-74940289becf

### Article author

@azure-sdk

### Metadata

* ID: 76704596-4890-d949-e4bb-e98345cb3258 
* Service: **cosmos-db**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the Cosmos libraries are maintained as [#4608](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/4608).
