### ISSUE TITLE
[Question] SASUrl compatibility

### ISSUE THREAD

**Issue by harshalsc** [Azure/azure-sdk-for-net#45172]
### Library name and version

Azure.Storage.Blobs 12.20.0

### Query/Question

I’ve recently transitioned from the **Microsoft.Azure.Storage.Blob** package to **Azure.Storage.Blobs**. However, I’ve encountered a compatibility issue with the SAS URLs generated by the new package. Specifically, when I attempt to use these SAS URLs with the APIs from the old Microsoft.Azure.Storage.Blob package, I encounter an error during blob uploads. The error message is as follows: **“Microsoft.WindowsAzure.Storage.StorageException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.”** This occurs despite the SAS URL being correctly formed.

Additionally, I’ve noticed that the SAS URL version (**sv**) change. Is there a method to specify a particular version when generating a SAS URL using the Azure.Storage.Blobs package?

**Comment by seanmcc-msft** [comment]
@harshalsc, this is not an issue with the modern SDK.  That error message indicates that your SAS URL is invalid, and was rejected by the storage service.  It's possible the SAS URL was expired, or does not have the proper permissions for the resource and operation in question.
