### ISSUE TITLE
Microsoft.Azure.ServiceBus MessageHandlerOptions max retry

### ISSUE THREAD

**Issue by ruonan0509** [Azure/azure-sdk-for-net#45182]
while using MessageHandlerOptions, 
var _options = new MessageHandlerOptions(ExceptionReceivedHandler)
what is the max retry when error occurs and trigger ExceptionReceivedHandler? is that defaut as 10 times? is that somegthing can be configured inside of code, or the queue itseft?

thanks

**Comment by jsquire** [comment]
//cc: @EldertGrootenboer

**Comment by EldertGrootenboer** [comment]
By default 5 retries are done, using the [RetryExponential](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.retryexponential?view=azure-dotnet-legacy) policy. Please note that the used SDK will be [retired](https://azure.microsoft.com/en-us/updates/retirement-notice-update-your-azure-service-bus-sdk-libraries-by-30-september-2026/) on 30 October 2026, and you should upgrade to the Azure.Messaging.ServiceBus SDK.
