### ISSUE TITLE
Create VSTS workers for CI

### ISSUE THREAD

**Issue by shahabhijeet** [Azure/azure-sdk-for-net#4519]
Create workers/jobs to start using VSTS for .NET SDK CI needs
- Investigation
- Need to make sure we use minimum VS 15.7 image for our workers

Investigate Cost: 4
Task Cost: 4

**Comment by dsgouda** [comment]
Steps:
1. Can we get a dry run to build and test on a VSTS machine
2. Hook up the github repo with VSTS and test the following PR scenarios
    - PR opened from user fork to the repo
    - PR opened by a user outside the org

**Comment by dsgouda** [comment]
Results of investigation
- VSTS does not support running CI builds against PRs opened from user forks
- VSTS also does not expose build logs to anonymous users and requires a bunch of authentications

This is a blocker to migrate to VSTS
