### ISSUE TITLE
[FEATURE REQ] Azure Monitor Distro - Metrics like CPU and available memory

### ISSUE THREAD

**Issue by FM1973** [Azure/azure-sdk-for-net#45199]
### Library name and version

Azure.Monitor.OpenTelemetry.AspNetCore 1.2.0

### Query/Question

Hello.
We are hosting a Blazor Server app on Azure (app service).
We are included OpenTelemetry with Application Insights using Azure.Monitor.OpenTelemetry.AspNetCore.

We followed the migration instructions for open telemetry and integrated the following code in program.cs

`builder.Services.AddOpenTelemetry().UseAzureMonitor();`

The instrumentation key is set using appsettings.json.

Having a look at our Application insights dashboard, we can see data like failed requests, server response time and server exceptions. What we don´t see are metrics like CPU, available memory etc. 
Using live metrics we can see CPU total and committed memory - but not on the dashboard.

Is there anything we have to configure to get these metrics?

Thanks for your help.

### Environment

Hosting platform: Azure App service (.net 8, 32 bit)
IDE: Visua Studio Pro 17.9.6

**Comment by TimothyMothra** [comment]
Hi @FM1973, I think I understand your confusion.

Our `Azure.Monitor.OpenTelemetry.AspNetCore` SDK has an internal implementation to collect CPU and Memory metrics exclusively for the LiveMetrics charts.
We don't include any mechanism to include these metrics for your full telemetry. 

OpenTelemetry does have an instrumentation library that you could explore:
 - https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Instrumentation.Process

This library is still in beta, so we don't have any plans to include it in our SDK. We may reconsider after they have a stable release, but I don't have any ETA of when that might be.

**Comment by FM1973** [comment]
Thanks for the info!
