### ISSUE TITLE
[QUERY] Is it possible to register different ServiceBus clients in DI with different authentication type

### ISSUE THREAD

**Issue by gaoyp830** [Azure/azure-sdk-for-net#45190]
### Library name and version

Azure.Messaging.ServiceBus 7.15.0

### Query/Question

Hello, we have a scenario that we have several service bus triggers in our Azure function. Some of them need to connect to a service bus using `ClientCertificateCredential` while one needs to use managed identity. I have this following setup during DI:
```

services.AddAzureClients(clientBuilder =>
            {
                clientBuilder
                    .AddServiceBusClientWithNamespace("namespace 1")
                    .WithCredential(new ManagedIdentityCredential("managed identity app id"))
                    .WithName("Queue1");

                clientBuilder.AddClient<ServiceBusReceiver, ServiceBusClientOptions>((_, _, provider) => 
                    provider.GetService<IAzureClientFactory<ServiceBusClient>>()
                            .CreateClient("Queue1")
                            .CreateReceiver("queue 1")
                );

                clientBuilder
                    .AddServiceBusClientWithNamespace("namespace 2")
                    .WithCredential(
                        new ClientCertificateCredential(
                                    tenantId: "tenantId",
                                    clientId: "first party app id",
                                    clientCertificate: certificate,
                                    new ClientCertificateCredentialOptions()
                                    {
                                        SendCertificateChain = true,
                                        AuthorityHost = new Uri("https://login.microsoftonline.com/")
                                    })
                        )
                    .WithName("Queue2");
                
                clientBuilder.AddClient<ServiceBusReceiver, ServiceBusClientOptions>((_, _, provider) => 
                    provider.GetService<IAzureClientFactory<ServiceBusClient>>()
                            .CreateClient("Queue2")
                            .CreateReceiver("queue 2")
                );
            });
```

However this setup doesnt seem working as the service bus triggers are not able to start. Could someone one provide me with some guidance?

Exception I am seeing in function:

```
Microsoft.Azure.WebJobs.Host.Listeners.FunctionListenerException : The listener for function {name of the Service bus trigger function} was unable to start. 
---> System.InvalidOperationException : Service Bus account connection string 'ScheduleJobServiceBusPrimaryConnection' does not exist. Make sure that it is a defined App Setting.
   at Microsoft.Azure.WebJobs.Extensions.ServiceBus.Config.ServiceBusClientFactory.ResolveConnectionInformation(String connection)
   at Microsoft.Azure.WebJobs.Extensions.ServiceBus.Config.ServiceBusClientFactory.CreateClientFromSetting(String connection)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication,Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.Azure.WebJobs.ServiceBus.Listeners.ServiceBusListener.<>c__DisplayClass21_0.<.ctor>b__2()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.CreateValue()
   at async Microsoft.Azure.WebJobs.ServiceBus.Listeners.ServiceBusListener.StartAsync(CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Listeners.FunctionListener.StartAsync(??) at D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Listeners\FunctionListener.cs : 68
   End of inner exception
```

**Comment by jsquire** [comment]
@gaoyp830 :  The answer to the question that you're asking is "yes."   You can register multiple clients with different auth types via `WithName` as you're already doing.   More context and examples for DI scenarios can be found in [Dependency Injection with the Azure SDK for .NET](https://learn.microsoft.com/dotnet/azure/sdk/dependency-injection?tabs=web-app-builder).

That's not the cause of the error that you shared.  The Event Hubs trigger does not use the clients that you register with DI - it creates its own based on your trigger configuration.  You didn't show your trigger signature, but the error message is clear: 
 
> Service Bus account connection string 'ScheduleJobServiceBusPrimaryConnection' does not exist. Make sure that it is a defined App Setting.

When you configure the trigger, the "Connection" parameter that you supply should be the name of an app setting that holds either your connection string or fully qualified namespace name.   The Functions runtime did not find the one that you registered.  Examples can be found in the [product docs](https://learn.microsoft.com/azure/azure-functions/functions-bindings-event-hubs-trigger?tabs=python-v2%2Cisolated-process%2Cnodejs-v4%2Cfunctionsv2%2Cextensionv5&pivots=programming-language-csharp#example)  and the [README examples](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Microsoft.Azure.WebJobs.Extensions.EventHubs/README.md#examples).   More discussion about how Functions manages connections can be found in the  [Connections](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-hubs-trigger?tabs=python-v2%2Cisolated-process%2Cnodejs-v4%2Cfunctionsv2%2Cextensionv5&pivots=programming-language-csharp#connections) section of the docs.
