### ISSUE TITLE
[BUG] Azure Storage client experiencing culture issues

### ISSUE THREAD

**Issue by andrew-lis** [Azure/azure-sdk-for-net#45207]
### Library name and version

Azure.Messaging.EventHubs.Processor 5.11.4

### Describe the bug

Version 5.11.3 works fine, but upgrading to 5.11.4 produces a lot of errors when it tries to connect to Event Hub.

Exceptions: 
System.Globalization.CultureNotFoundException at Azure.Storage.StorageSharedKeyPipelinePolicy..cctor on Azure.Storage.StorageSharedKeyPipelinePolicy..cctor. 
One or more errors occurred. (Failed to compare two elements in the array.)
Error Message: **"Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')
en-US is an invalid culture identifier."**
The type initializer for 'Azure.Storage.StorageSharedKeyPipelinePolicy' threw an exception.
Failed to compare two elements in the array.

It happens only when csproj contains:    \<InvariantGlobalization>true\</InvariantGlobalization>

### Expected behavior

Azure.Messaging.EventHubs.Processor 5.11.4 should work when .NET Core Globalization Invariant Mode is used (    csproj contains   \<InvariantGlobalization>true\</InvariantGlobalization>).

### Actual behavior

Azure.Messaging.EventHubs.Processor 5.11.4 works only when .NET Core Globalization Invariant Mode is turned off ( csproj contains   \<InvariantGlobalization>false\</InvariantGlobalization> or the entry is missing).

### Reproduction Steps

1. Setup .net 8 to use .NET Core Globalization Invariant Mode 
2. Install Azure.Messaging.EventHubs.Processor 5.11.3
3. Check if works fine.
4. Install Azure.Messaging.EventHubs.Processor 5.11.4
5. Observe the error

### Environment

Checked on: Windows 10, and on Linux Debian.

**Comment by jsquire** [comment]
Hi @andrew-lis.   This looks to be related to a bug in the Azure Storage Blobs package that was recently fixed and included with the v12.21.1 release.    The Event Hubs package that you're using references v12.21.0, which does not have the fix.   The next time that the Event Hubs processor is released, it will pull in the latest Storage package with the fix.   In the meantime, you can mitigate the error by taking a direct reference to Azure.Storage.Blobs v12.21.1 or above in your application.

see: [Storage changelog](https://github.com/Azure/azure-sdk-for-net/blob/Azure.Storage.Blobs_12.21.1/sdk/storage/Azure.Storage.Blobs/CHANGELOG.md#12211-2024-07-25)
