### ISSUE TITLE
[BUG] EventHub trigger cannot receive Kafka produced events when function parameter is of type EventData or EventData[]

### ISSUE THREAD

**Issue by jponcedeleon-kr** [Azure/azure-sdk-for-net#45210]
### Library name and version

Azure.Messaging.EventHubs, Microsoft.Azure.WebJobs.Extensions.EventHubs

### Describe the bug

This issue affects the EventHubTrigger in Isolated mode, when receiving events sent by a Kafka producer (the Kafka output binding for example). 

The EventHub trigger fails to invoke functions that have EventData (or EventData[]) in the signature and throws a Serialization Exception because the underlying AMQP message of EventData contains properties that are of type byte[].

Events sent by Kafka producers will have headers that are of type byte[], and the Amqp converter fails to convert.

This could be a blocker when moving EventHub trigger functions from in-process to isolated mode, and the producers are Kafka based.

The issue seem to be in `Azure.Core.Amqp`, `AmqpAnnotatedMessageConverter` class.

A possible solution could be for the `ToAmqpMessage` method where it calls `TryCreateAmqpPropertyValueFromNetProperty` to pass in the additional parameter `allowBodyTypes` set to true, but I'm not sure what else this change might affect.

This might also affect the ServiceBus since it uses the same underlaying `Azure.Core.Amqp` codebase.

This has been reported before and moved to the `azure-functions-dotnet-worker` repository but the root cause seem to be here, here's a link of the previous report: [https://github.com/Azure/azure-sdk-for-net/issues/44199](url)

### Expected behavior

An EventHub triggered function, in isolated mode, with EventData or EventData[] in the function signature should trigger when the event was sent by a Kafka producer through the EventHub

```
public async Task Receive(
            [EventHubTrigger("%TopicName%", Connection = "EventHubConnectionString",
                ConsumerGroup = "%ConsumerGroup%")]
            EventData[] events)
...
```

### Actual behavior

Function invocation fails with the following Exception:

```
System.Runtime.Serialization.SerializationException: Serialization failed due to an unsupported type, System.Byte[].

         at Azure.Core.Amqp.Shared.AmqpAnnotatedMessageConverter.TryCreateAmqpPropertyValueFromNetProperty(Object propertyValue, Object& amqpPropertyValue, Boolean allowBodyTypes)

         at Azure.Core.Amqp.Shared.AmqpAnnotatedMessageConverter.ToAmqpMessage(AmqpAnnotatedMessage sourceMessage)

         at Azure.Core.Amqp.AmqpAnnotatedMessage.ToBytes()

         at Microsoft.Azure.WebJobs.EventHubs.EventHubExtensionConfigProvider.ConvertEventDataToBindingData(EventData input)
```

### Reproduction Steps

Although the issue is manifested in the EventHub trigger for isolated functions, here's a unit test that demonstrates it, which fails with Serialization Exception. 
This same method is called by the EventHub trigger's `EventHubExtensionConfigProvider` class when in isolated mode.

```
using Azure.Core.Amqp;
using Azure.Messaging.EventHubs;

namespace Kafka2EventHub;

public class UnitTest1
{
    [Fact]
    public void ShouldConvertHeadersFromKafkaToEventHub()
    {
        var amqpAnnotatedMessage = new AmqpAnnotatedMessage(AmqpMessageBody.FromValue("message"));
        var eventData = new EventData(amqpAnnotatedMessage)
        {
            Properties =
            {
                ["test_header"] = "test_value"u8.ToArray()
            }
        };

        var result = eventData.GetRawAmqpMessage().ToBytes();
        
        Assert.NotNull(result);
    }
}
```

### Environment

.NET SDK:
 Version:           8.0.303
 Commit:            29ab8e3268
 Workload version:  8.0.300-manifests.c915c39d
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.4
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.303/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.7
  Architecture: arm64
  Commit:       2aade6beb0

.NET SDKs installed:
  6.0.406 [/usr/local/share/dotnet/sdk]
  8.0.303 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.14 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet/x64]
    registered at [/etc/dotnet/install_location_x64]

Environment variables:
  Not set

global.json file:
  Not found

**Comment by jsquire** [comment]
Hi @jponcedeleon-kr.  Thank you for reaching out and we regret that you're experiencing difficulty.   The error that you're seeing indicates that there's a field somewhere in your AMQP message that does not conform to the AMQP specification - or that there's a bug in our deserialization.   

There was a change made it [5.11.2](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/CHANGELOG.md#other-changes-3) regarding the use of `byte[]` use in application properties that would manifest with the behavior that you're seeing with older packages.  Unfortunately, we're missing context to understand the structure of your AMQP message, so I cannot say whether or not that's the case that you're hitting.

For next steps:
- Please provide the version numbers of the packages that you're using.
- Please provide a code snippet that shows creation of an `EventData` instance or AMQP message that can be used to reproduce the behavior.

**Comment by jponcedeleon-kr** [comment]
@jsquire, 

- We are using version `5.11.4` of Azure.Messaging.EventHubs

- I'll prepare a full working example, that would involve an instance of an EventHub so that the function can be triggered. Creation of EventData instance can be seen in the Reproduction Steps.

In the meantime, the unit test provided in **"Reproduction Steps"** should be sufficient to reproduce the issue because `EventHubExtensionConfigProvider` class for the EventHub trigger (Microsoft.Azure.WebJobs.Extensions.EventHub) calls `input.GetRawAmqpMessage().ToBytes()` when in isolated mode. The version we are using does support `byte[]` in the `Properties` property for `EventData`. The `AmqpAnnotatedMessageConverter` in `Azure.Core.Amqp` doesn't seem to take into account that `EventData.Properties` could have `byte[]` as type. 

The test is made so that we have a simpler way to repro and not have to use an EventHub instance to run messages through.

The unit test fails with EventData and the associated byte[] property. It can be run with the following project file:

```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <RootNamespace>Kafta2EventHub</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Azure.Messaging.EventHubs" Version="5.11.4" />
        <PackageReference Include="coverlet.collector" Version="6.0.0"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0"/>
        <PackageReference Include="xunit" Version="2.5.3"/>
        <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

</Project>

```

**Comment by jsquire** [comment]
@jponcedeleon-kr:  Thank you for your reply.  I'm unable to reproduce your error with the available context, and we have [tests](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/tests/Amqp/AmqpMessageConverterTests.cs#L1108) covering the use of `byte[]` and `ArraySegment<byte>` use for application properties, which are consistently passing.

The Event Hubs library follows v1.0 of the AMQP spec and will support `byte[]` in the application properties, so long as it is encoded as AMQP type [binary](https://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-types-v1.0-os.html#type-binary).   Encoding as `array`, `map`, or `list` are disallowed, as they are invalid according to the [Application Properties](https://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-messaging-v1.0-os.html#type-application-properties) section of the spec.   

The error path in the stack trace points to the message being encoded with an incorrect type, causing it to fail the `is byte[]` and `is ArraySegment<byte>` checks [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core.Amqp/src/Shared/AmqpAnnotatedMessageConverter.cs#L29) and fall into the Unknown path [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core.Amqp/src/Shared/AmqpAnnotatedMessageConverter.cs#L545).   That seems to contradict the error message which indicates `System.Byte[]` as the type.

There's a detail in your scenario that we're missing to repro.  Unfortunately, I don't have access to Kafka to send a message and will need a code snippet that demonstrates creating a message that can reproduce the behavior that you're seeing in order to assist further.

**Comment by jponcedeleon-kr** [comment]
@jsquire, Thanks for taking the time to look into this we really appreciate it. 

I think I have a clue about what could be the issue, could be conflicts with the current nuget packages released, this is what I've found so far.

The current `Azure.Messaging.EventHubs` version `5.11.4`, has an open reference to `Azure.Core.Amqp`, which currently resolves to `1.3.0` which is the latest nuget release. 

Version `1.3.0` for Azure.Core.Amqp was released 3/2023 and doesn't contain the features to support `byte[]` which were introduced in 4/2024 in this commit `5f2822703c80538e406f21ece5bc3284683fd840`, but `Azure.Messaging.EventHub` supports it since `5.11.2` four months ago. Seems there's no release of `Azure.Core.Amqp` that supports it.

I have created a repository with a simple test case, [https://github.com/jponcedeleon-kr/azure-sdk-for-net-issues-45210](url). The test creates an `EventData` instance with a `byte[]` property, then calls `GetRawAmqpMessage().ToBytes()` which is what's called by the EventHub trigger, this simulates a payload generated by a Kafka producer without actually having to send messages to the EventHub.

Please take a look and let me know if the test passes for you. 

I've done a quick test and pulled the latest for `azure/azure-sdk-for-net` repo,  switched the reference to `Azure.Core.Amqp` in `Azure.Messaging.EventHubs`, from "nuget" reference to "project" reference in `sdk/Core/Azure.Core.Amqp` in the repo, and the test passed as expected. Seem like the issue might be that the changes needed in Azure.Core.Amqp have not being released yet?

**Comment by jsquire** [comment]
@jponcedeleon-kr : Thanks for the additional context and analysis.   I think that you've solved the mystery.   The TLDR is that we didn't account for the Function bindings and do need to make some additional releases for this to work as intended.

**Details**

The `AmqpAnnotatedMessageConverter` is a shared source file pulled into the Event Hubs and Service Bus libraries directly and compiled as part of them.  For operations within the client library, the local copy of the converter is invoked, which allows for sending/receiving events/messages with binary properties.    This is the test coverage that I was referring to.

The Function bindings pass data to the isolated worker via RPC channel where they call `ToBytes` on `AmqpAnnotatedMessage`.   The message is not shared source and is a public type in the `Azure.Core.Amqp` library - which is, in turn, calling its own local copy of the converter.   Since, as you pointed out, the `Azure.Core.Amqp` library did not get a release with the converter changes (since they were assumed to be all scoped to shared source) it is calling an outdated version without the binary property support.

**Comment by jsquire** [comment]
Passing this over to @JoshLove-msft who will be facilitating the releases to get this fixed up.

**Comment by jponcedeleon-kr** [comment]
Thank you for all the support I'm glad we have a resolution path.

One thing, would you have an estimate when `Azure.Core.Amqp` could be released next? We are currently blocked from converting EventHub triggered functions from in-process to isolated.

From what I see, the only thing we need to resolve this issue is releasing `Azure.Core.Amqp`, since the dependency in `Azure.Messaging.EventHubs` is open with no specific version, and should resolve to the latest released on nuget at restore time, even though `Microsoft.Azure.WebJobs.Extensions.EventHubs` and its isolated counterpart `Microsoft.Azure.Functions.Worker.Extensions.EventHub` use specific versions.

Again, thanks for all the help on this, appreciated.

**Comment by jponcedeleon-kr** [comment]
I see `Azure.Core.Amqp` version `1.3.1` have being released with does fixes the underlaying issue. To be able to use it, one have to add an explicit nuget reference to that version in the project, since `Azure.Messaging.EventHubs` defaults to the earlier `1.3.0`.

I would think that to fully resolve it, we will need new releases for `Azure.Messaging.EventHubs`, `Microsoft.Azure.WebJobs.Extensions.EventHub` and `Microsoft.Azure.Functions.Worker.Extensions.EventHub` would need also need to be updated (hardcoded in source file) and released as well.

Right now we have a workaround which is to reference `Azure.Core.Amqp` `1.3.1` in the isolated functions project file, and an after build step that copies that specific version into the host's build output (.azurefunctions) directory, so that it can be used by the trigger.

Thank you for all the progress done on this issue.

**Comment by JoshLove-msft** [comment]
Yes, confirming we will need new releases of the libraries you mentioned.

**Comment by JoshLove-msft** [comment]
An updated version of [Microsoft.Azure.WebJobs.Extensions.EventHubs](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.EventHubs/6.3.5) has been shipped. At this point, we would need an updated version of the worker package that points to this updated version. @liliankasem can you please help with that?

**Comment by mitalshah30** [comment]
@JoshLove-msft , Can you please help to update [Microsoft.Azure.Functions.Worker.Extensions.EventHub](https://github.com/Azure/azure-functions-dotnet-worker) as well? We are having similar issue in dotnet 8 isolated function app. and this seems to be still referencing old version.

**Comment by JoshLove-msft** [comment]
A new version of the extension has been published  - https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.EventHubs/6.3.5
