### ISSUE TITLE
[BUG] ARM Client Confusingly Redacts Logs for Failed Deployment Operations

### ISSUE THREAD

**Issue by wsugarman** [Azure/azure-sdk-for-net#45220]
### Library name and version

Azure.ResourceManager.Resources 1.8.0

### Describe the bug

When I submit a series of deployments using `ArmDeploymentCollection.CreateOrUpdateAsync`, if there are failures within the deployment a `RequestFailedException` is thrown. However, the thrown `RequestFailedException` object has an inner response whose property `Response.IsError` is `false`. Therefore, the detailed error details concerning the deployment is not displayed in the logs, leaving me with only:

```
Error Message:
   Azure.RequestFailedException : At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.
Status: 200 (OK)
ErrorCode: DeploymentFailed

Service request succeeded. Response content and headers are not included to avoid logging sensitive data.
```
Instead, I had to write custom code to print the content body:
```json
{
  "status": "Failed",
  "error": {
    "code": "DeploymentFailed",
    "target": "***",
    "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.",
    "details": [
      {
        "code": "FailedIdentityOperation",
        "message": "Identity operation for resource '***' failed with error '***'."
      }
    ]
  }
}
```
I am guessing that a 200 is returned because the "Get Operation Status" API successfully returned a response, but the operation inside failed. However, the end result is a bad experience that hides helpful information from users. I would say that either:
- The operation failure should be manifested in the returned data structure without throwing an exception, and users can inspect its status OR
- The method continues to throw an exception, but the client correctly updates `IsError` to be `true` as even the client is treating it like an error

Here is the shortened stack trace for more info:
```
Stack Trace:
     at Azure.Core.OperationInternal`1.GetResponseFromState(OperationState`1 state)
   at Azure.Core.OperationInternal`1.UpdateStatusAsync(Boolean async, CancellationToken cancellationToken)
   at Azure.Core.OperationInternalBase.UpdateStatusAsync(CancellationToken cancellationToken)
   at Azure.Core.OperationPoller.WaitForCompletionAsync(Boolean async, OperationInternalBase operation, Nullable`1 delayHint, CancellationToken cancellationToken)
   at Azure.Core.OperationInternalBase.WaitForCompletionResponseAsync(Boolean async, Nullable`1 pollingInterval, String scopeName, CancellationToken cancellationToken)
   at Azure.Core.OperationInternal`1.WaitForCompletionAsync(Boolean async, Nullable`1 pollingInterval, CancellationToken cancellationToken)
   at Azure.Core.OperationInternal`1.WaitForCompletionAsync(CancellationToken cancellationToken)
   at Azure.ResourceManager.Resources.ArmDeploymentCollection.CreateOrUpdateAsync(WaitUntil waitUntil, String deploymentName, ArmDeploymentContent content, CancellationToken cancellationToken)

```

### Expected behavior

I would expect the error details to be available in my telemetry when logging `RequestFailedException` objects thrown by `ResourcesArmOperation.WaitForCompletionAsync`.

### Actual behavior

Instead, a placeholder value is left in the logs.

### Reproduction Steps

I do not have a repro yet. I found this scenario within my team's testing, but I'll try to create one.

**Comment by wsugarman** [comment]
This is related to https://github.com/Azure/azure-sdk-for-net/issues/44008

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Add @christothes who made this change to explain the details.

**Comment by christothes** [comment]
This error is intended to prevent the SDK from inadvertently printing sensitive information to the exception message. If the specific code in question expects this behavior (a failed request with a successful status code), then a custom `RequestFailedDetailsParser` should be specified when constructing the [RequestFailedException](https://learn.microsoft.com/en-us/dotnet/api/azure.requestfailedexception.-ctor?view=azure-dotnet#azure-requestfailedexception-ctor(azure-response-system-exception-azure-core-requestfaileddetailsparser))

**Comment by wsugarman** [comment]
@HarveyLink - I think it's reasonable to possibly redact sensitive information from `RequestFailedException` when the response is not an error. But in this case for the ARM SDK, it seems like an oversight to redact the deployment errors from the exception.

**Comment by HarveyLink** [comment]
Hi @wsugarman @christothes , after internal discussions, since this operation is LRO, which means it's inside the shared code. Change it to support custom Parser and pass custom RequestFailedDetailsParser all the way down from the beginning is kind of difficult. Therefore we will not make any changes to this service for now. This issue will be documented and circle back once we could add this feature supported.
