### ISSUE TITLE
[BUG] Incorrect documentation/incorrect operation when querying tables.

### ISSUE THREAD

**Issue by NeilMacMullen** [Azure/azure-sdk-for-net#45227]
### Library name and version

Azure.Data.Tables 12.9.0

### Describe the bug

This [documentation page](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/tables/Azure.Data.Tables/samples/Sample4QueryEntities.md) includes this code sample...

```CSharp
IReadOnlyList<TableEntity> pageResults = page.Values;
moreResultsAvailable = pageResults.Any() && continuationToken != null;
```

I'm not sure whether the documentation is incorrect or whether there is a bug in the library but in our testing it's definitely possible to receive pages without any results prior to results being returned.

For example....

```
Running query '(PartitionKey eq 'singlepartition') and (Timestamp gt datetime'2024-07-29T08:51:00Z') and (Timestamp le datetime'2024-07-29T08:52:00Z')'

got page results:0 tok:1!20!c2luZ2xlcGFydGl0aW9u 1!24!NUU6NTE6NEE6MDA6RkU6OEI-
got page results:0 tok:1!20!c2luZ2xlcGFydGl0aW9u 1!24!NUU6NTE6NEE6MDU6Qjg6MTY-
got page results:1000 tok:1!20!c2luZ2xlcGFydGl0aW9u 1!24!NUU6NTE6NEI6MDE6OEE6MUQ-
got page results:1000 tok:1!20!c2luZ2xlcGFydGl0aW9u 1!24!NUU6NTE6NEI6MDE6OTQ6OTE-
got page results:1000 tok:1!20!c2luZ2xlcGFydGl0aW9u 1!24!NUU6NTE6NEI6MDE6OUU6MUU-
got page results:0 tok:1!20!c2luZ2xlcGFydGl0aW9u 1!24!RTQ6NjU6Qjg6QUQ6RkY6MTI-
got page results:0 tok:
```
If the documentation is incorrect, the fix is to remove the check for the result count.

### Expected behavior

Sample code returns correct results.

### Actual behavior

Sample code does not correctly work for all queries.

### Reproduction Steps

Run a simple query using a populated table using the sample code.  Possibly the behaviour only occurs on non-index properties.

### Environment

.NET SDK:
 Version:           8.0.400-preview.0.24324.5
 Commit:            736a2616db
 Workload version:  8.0.400-manifests.ae9c2ef0
 MSBuild version:   17.11.0+1192b22fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.400-preview.0.24324.5\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [android]
   Installation Source: VS 17.11.35118.90, VS 17.10.35122.118
   Manifest Version:    34.0.113/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.android\34.0.113\WorkloadManifest.json
   Install Type:              Msi

 [maccatalyst]
   Installation Source: VS 17.11.35118.90, VS 17.10.35122.118
   Manifest Version:    17.2.8053/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maccatalyst\17.2.8053\WorkloadManifest.json
   Install Type:              Msi

 [ios]
   Installation Source: VS 17.11.35118.90, VS 17.10.35122.118
   Manifest Version:    17.2.8053/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.ios\17.2.8053\WorkloadManifest.json
   Install Type:              Msi

 [maui-windows]
   Installation Source: VS 17.11.35118.90, VS 17.10.35122.118
   Manifest Version:    8.0.61/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.61\WorkloadManifest.json
   Install Type:              Msi

 [aspire]
   Installation Source: VS 17.10.35122.118
   Manifest Version:    8.0.1/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.0.1\WorkloadManifest.json
   Install Type:              Msi

Host:
  Version:      8.0.7
  Architecture: x64
  Commit:       2aade6beb0

.NET SDKs installed:
  8.0.107 [C:\Program Files\dotnet\sdk]
  8.0.206 [C:\Program Files\dotnet\sdk]
  8.0.303 [C:\Program Files\dotnet\sdk]
  8.0.400-preview.0.24324.5 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
