### ISSUE TITLE
[BUG] update Microsoft.Azure.WebJobs.Extensions.ServiceBus use Azure.Messaging.ServiceBus v7.18.0 to fix Azure.Core vulnerability

### ISSUE THREAD

**Issue by briandunnington** [Azure/azure-sdk-for-net#45238]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.ServiceBus v5.16.2

### Describe the bug

Microsoft.Azure.WebJobs.Extensions.ServiceBus v5.16.2 references Azure.Messaging.ServiceBus v7.17.5 which references Azure.Core v1.38.0 which has a vulnerability.

Azure.Messaging.ServiceBus v7.18.0 references Azure.Core v1.41.0 which is the fixed version.

<img width="669" alt="image" src="https://github.com/user-attachments/assets/8309c6f9-e230-4b1f-8ea1-e613d5d18178">

<img width="653" alt="image" src="https://github.com/user-attachments/assets/57667118-5c6a-455b-8b42-54dd63070713">

<img width="659" alt="image" src="https://github.com/user-attachments/assets/08d522fc-c34c-443c-926d-1a326f65d309">

### Expected behavior

using Microsoft.Azure.WebJobs.Extensions.ServiceBus does not result in any security vulnerabilities flagged

### Actual behavior

transitive dependency Azure.Core 1.38.0 is flagging for security vulnerability

### Reproduction Steps

any reference to this version results in the vulnerable dependency being used

**Comment by jsquire** [comment]
@briandunnington : Can you offer some additional detail on what is flagging Azure.Core and for what reason?  To our knowledge, there is no known vulnerability in Azure.Core.

**Comment by briandunnington** [comment]
Since this issue was filed, a new version of the Nuget package has been released with the updated dependency references so this can be considered closed.
