### ISSUE TITLE
Create Jenkins workders after upgrading

### ISSUE THREAD

**Issue by shahabhijeet** [Azure/azure-sdk-for-net#4523]
Create 3 Jenkins worker for CI
Create 2 Jenkins worker for sign/publish
Make sure we install latest VS on all the workers.

Cost: 5

**Comment by dsgouda** [comment]
Based on investigation here https://github.com/Azure/azure-sdk-for-net/issues/4519
This needs has a higher priority now

**Comment by shahabhijeet** [comment]
Closing
