### ISSUE TITLE
[BUG] breaking change: AppInsights connection string now required in local.settings.json

### ISSUE THREAD

**Issue by af4jm** [Azure/azure-sdk-for-net#45231]
### Library name and version

Azure.Monitor.OpenTelemetry.AspNetCore 1.2.0

### Describe the bug

while updating NuGet packages, we were forced to add `Azure.Monitor.OpenTelemetry.AspNetCore` in order to disable live metrics

old code:

``` cs
logBuilder.AddApplicationInsightsWebJobs(options => {
    options.EnableLiveMetrics = false;
});
```

new code:

``` cs
appBuilder.Services.AddOpenTelemetry().UseAzureMonitor(options => {
    options.EnableLiveMetrics = false;
});
```

note: in both cases, the `EnableLiveMetrics` line is inside `#if !(DEBUG || LOCAL)` because we do run live metrics in Azure 

### Expected behavior

this has always worked with `APPLICATIONINSIGHTS_CONNECTION_STRING` as an empty string in `local.settings.json`

### Actual behavior

it now throws [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/src/Internals/AzureMonitorTransmitter.cs#L77)

### Reproduction Steps

old code:

``` cs
new HostBuilder()
    .ConfigureAppConfiguration((hostContext, configurationBuilder) =>
    {
        if (hostContext.HostingEnvironment.IsDevelopment())
        {
            configurationBuilder.AddUserSecrets<Program>(optional: true);
        }
    })
    .ConfigureFunctionsWorkerDefaults(appBuilder =>
    {
        appBuilder.AddApplicationInsights(options =>
        {
            options.EnableDependencyTrackingTelemetryModule = false;
        });

        appBuilder.AddApplicationInsightsLogger();
    })
    .ConfigureLogging((hostContext, logBuilder) =>
    {
#if DEBUG || LOCAL
        logBuilder.SetMinimumLevel(LogLevel.Debug);
        logBuilder.AddFilter("Azure", LogLevel.Error);
#else
        logBuilder.AddFilter("default", LogLevel.Error);
        logBuilder.AddFilter("Function", LogLevel.Warning);
        logBuilder.AddFilter("Azure.Core", LogLevel.Error);
        logBuilder.AddFilter("Azure", LogLevel.Error);
        logBuilder.SetMinimumLevel(LogLevel.Warning);
#endif
        logBuilder.AddApplicationInsightsWebJobs(options =>
        {
#if !(DEBUG || LOCAL)
            options.EnableLiveMetrics = false;
            options.SamplingExcludedTypes = "Exception";
            options.SamplingSettings = new Microsoft.ApplicationInsights.WindowsServer.Channel.Implementation.SamplingPercentageEstimatorSettings
            {
                MaxSamplingPercentage = 0,
                MinSamplingPercentage = 0
            };
            options.HttpAutoCollectionOptions = new Microsoft.Azure.WebJobs.Logging.ApplicationInsights.HttpAutoCollectionOptions
            {
                EnableHttpTriggerExtendedInfoCollection = false,
                EnableW3CDistributedTracing = false,
                EnableResponseHeaderInjection = false
            };
#endif
        });
    })
    .ConfigureServices((hostContext, services) =>
    {
        // snip
    })
    .Build().RunAsync();
```

new code:

``` cs
new HostBuilder()
    .ConfigureAppConfiguration((hostContext, configurationBuilder) =>
    {
        if (hostContext.HostingEnvironment.IsDevelopment())
        {
            configurationBuilder.AddUserSecrets<Program>(optional: true);
        }
    })
    .ConfigureFunctionsWorkerDefaults(appBuilder =>
    {
#if !(DEBUG || LOCAL)
        appBuilder.Services.Configure<TelemetryConfiguration>(telemetryConfiguration =>
        {
            var telemetryProcessorChainBuilder = telemetryConfiguration.DefaultTelemetrySink.TelemetryProcessorChainBuilder;

            telemetryProcessorChainBuilder.UseAdaptiveSampling(new SamplingPercentageEstimatorSettings
            { // defaults https://github.com/microsoft/ApplicationInsights-dotnet/blob/main/BASE/src/ServerTelemetryChannel/Implementation/SamplingPercentageEstimatorSettings.cs#L21
                MinSamplingPercentage = 0.1,
                MaxSamplingPercentage = 5,
                InitialSamplingPercentage = 1
            }, null, excludedTypes: "Exception");

            telemetryProcessorChainBuilder.Build();
        });
#endif

        appBuilder.Services.AddOpenTelemetry().UseAzureMonitor(options => {
#if !(DEBUG || LOCAL)
            options.EnableLiveMetrics = false;
#endif
        });
    })
    .ConfigureServices((hostContext, services) =>
    {
        services.AddApplicationInsightsTelemetryWorkerService(options =>
        {
            options.EnableDependencyTrackingTelemetryModule = false;
        });
        services.ConfigureFunctionsApplicationInsights();

        services.Configure<LoggerFilterOptions>(options =>
        {
#if DEBUG || LOCAL
            options.MinLevel = LogLevel.Debug;
            options.AddFilter("Azure", LogLevel.Error);
#else
            options.AddFilter("default", LogLevel.Error);
            options.AddFilter("Function", LogLevel.Warning);
            options.AddFilter("Azure.Core", LogLevel.Error);
            options.AddFilter("Azure", LogLevel.Error);
            options.MinLevel = LogLevel.Warning;
#endif
        });

#if !(DEBUG || LOCAL)
        services.Configure<Microsoft.Azure.WebJobs.Logging.ApplicationInsights.HttpAutoCollectionOptions>(options =>
        {
            options.EnableHttpTriggerExtendedInfoCollection = false;
            options.EnableW3CDistributedTracing = false;
            options.EnableResponseHeaderInjection = false;
        });
#endif

        // snip
    })
    .Build().RunAsync();
```

**Comment by TimothyMothra** [comment]
1. `AddApplicationInsightsWebJobs`
   This isn't an API that we publish. What package were you using in the old sample?


2. https://github.com/Azure/azure-sdk-for-net/blob/de77bfc02f7bdea836f2b67535bf09161cfe3a47/sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/src/Internals/AzureMonitorTransmitter.cs#L77
This exception is valid. If a connection string is not provided to our Exporter/Distro then the SDK can't send telemetry. We consider that a fatal error and throw during startup.

**Comment by af4jm** [comment]
we're doing the middle of those 3 options when we deploy to Azure, the last for local debugging... what caught us by surprise is that in the old way (where we didn't need to load Azure monitor to turn off live metrics) we could leave it blank locally, now we have to put some nonsense in there... or use preprocessor directives to bypass loading AppInsights

The root question from us is... "Hey, this looks broken, if it's not then what are we doing wrong & where do we find how to do it right?" AppInsights in out-of-proc/isolated Azure Functions has changed a LOT... we've got 3 different projects that we can't copy-paste from because each was done a few months apart with big changes in between

diff of the NuGet versions between old & new codes in the original post:
![image](https://github.com/user-attachments/assets/f50ac6bb-6bf2-4a58-8711-6444dedf0935)

**Comment by af4jm** [comment]
edited "new" code in original to correct initializing `SamplingPercentageEstimatorSettings`, because we discovered it was just nonsensically wrong (while searching for how to do `options.SamplingExcludedTypes = "Exception";` which was missing from the "new" code)

**Comment by TimothyMothra** [comment]
Hi @af4jm, 
It seems you're describing a few different issues. I'm sorry, but I'm not sure how to best help. 
I'm going to try to respond, but if I've missed something please ask again.


1. > what caught us by surprise is that in the old way (where we didn't need to load Azure monitor to turn off live metrics)

    In the old code you shared, my team doesn't own any of these APIs. It seems like this is someone else's SDK that is wrapping ours. I can only speculate what settings they've turned on or off. If your intention is to continue using their SDK you should reach out to their team and provide the feedback about needing to disable Live Metrics.

    To add some context here, when my team shipped https://www.nuget.org/packages/Azure.Monitor.OpenTelemetry.AspNetCore/1.2.0, we added the Live Metrics feature and this is on-by-default by design. Our API allows users to disable Live Metrics. I can only speculate that this other SDK took the update but didn't expose an option to disable Live Metrics.


2. > diff of the NuGet versions between old & new codes in the original post:

    Each the packages you included in your screenshot are not published from this repo. You'll need to find the owning repo and report an issue about the change in behavior between versions. Your complaint is valid, but my team doesn't own those packages and we can't help you.


3. regarding your new code

   It seems like you're mixing two different SDKs here, I can't tell exactly what you're trying to accomplish.
   

    ### Classic Application Insights SDK

   - `Services.Configure<TelemetryConfiguration>`
   - `services.AddApplicationInsightsTelemetryWorkerService()`

   These APIs are from the classic Application Insights SDK:
       - Nuget: https://www.nuget.org/packages/Microsoft.ApplicationInsights.workerservice
       - Repo: https://github.com/microsoft/ApplicationInsights-dotnet
       
    My team owns this, but this project is in a different repo. This is a fully supported and feature rich SDK.
    If you want to onboard to this SDK, please review this doc:
    https://learn.microsoft.com/en-us/azure/azure-monitor/app/worker-service
    
    ### Azure Monitor OpenTelemetry

    - `Services.AddOpenTelemetry().UseAzureMonitor()`

   This API is from the newer OpenTelemetry based Azure Monitor SDK.
   - Nuget: https://www.nuget.org/packages/Azure.Monitor.OpenTelemetry.AspNetCore
   - Repo: https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore

    My team owns this, and this conversation is in the owning repo.
    OpenTelemetry is a new tech stack and this will eventually replace the former classic SDK.
    If you want to onboard to this SDK, please review this doc:
    https://learn.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-enable?tabs=aspnetcore

**Comment by af4jm** [comment]
thanks... this project is inventory tracking & syndication (to ad partners), with millions of update events daily, so our goal is to get what we need for alerts when something is wrong, but not so much that our AppInsights spend is out of control... currently we're hitting our daily cap in just a few hours when back in the .NET 5 days we'd get at least 18 hours with the same cap

ironically the rest of this week is our annual internal hackathon, so I think I'm going to make OpenTelemetry my focus... knowing we have a mix of SDKs means we've probably got a lot of duplication, so starting over with the new SDK as a baseline is probably a good idea... then we can dig into what settings are needed to turn down the data we don't need (as opposed to trying to retrofit prior settings into the new model)

**Comment by af4jm** [comment]
follow up question in issue #45373
