### ISSUE TITLE
[FEATURE REQ] Azure Monitor to export resource attributes for logs

### ISSUE THREAD

**Issue by BenWRare** [Azure/azure-sdk-for-net#45251]
### Library name

Azure.Monitor.OpenTelemetry.Exporter

### Please describe the feature.

Similar to https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18909 , when adding a resource onto a log message the console exporter can fetch and display associated information file but the azure monitor does not add it to the `customDimensions` section. 
![image](https://github.com/user-attachments/assets/c6962977-d4ff-4f55-b89f-72cdd1bb0971)

![rider64_2JzDkR9QzN](https://github.com/user-attachments/assets/24ec1138-cfb6-48e0-80fe-81536d3627f4)

Here is a small snippet of code I used to confirm this was the case:

```cs
var connectionString = "";
var resource =  ResourceBuilder.CreateDefault().AddService("AnyService").AddAttributes(new Dictionary<string, object>
{
	{"AnyKey", "AnyValue"}
});

var loggerFactory = LoggerFactory.Create(builder =>
	builder.AddOpenTelemetry(
		options => options
			.SetResourceBuilder(resource)
			.AddConsoleExporter()
			.AddAzureMonitorLogExporter(
			ctx => ctx.ConnectionString = connectionString)));

var logger = loggerFactory.CreateLogger("AnyLogger");

logger.LogError("Ahh I hit an error!");
```

Was there a specific reason it was not added or just accidentally left out?

**Comment by TimothyMothra** [comment]
I'm consolidating all issues regarding exporting custom Resource Attributes into another issue to help with tracking. https://github.com/Azure/azure-sdk-for-net/issues/46020
