### ISSUE TITLE
[FEATURE REQ] Cannot set ImmutableStorageWithVersioning on a new container

### ISSUE THREAD

**Issue by ms92ita** [Azure/azure-sdk-for-net#45253]
### Library name

Azure.Storage.Blobs

### Please describe the feature.

Hello,
from the function CreateBlobContainer, a property for set immutable storage with versioning is not enabled. Since that the property is available from the portal and PowerShell, I need to use it programmatically from my .net application.

**Comment by seanmcc-msft** [comment]
@ms92ita, this is a management plane function.  You can programmatically create a container with immutability with version with [Azure.ResourceManager.Storage](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/storage/Azure.ResourceManager.Storage).

**Comment by blueww** [comment]
@ms92ita 
You can find how to create a container with ImmutableStorageWithVersioning with [Azure.ResourceManager.Storage](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/storage/Azure.ResourceManager.Storage) from test case: https://github.com/Azure/azure-sdk-for-net/blob/1809f3bf2e6ae97cc63f4a3474ffe3c89c9966f6/sdk/storage/Azure.ResourceManager.Storage/tests/Tests/BlobContainerTests.cs#L711
