### ISSUE TITLE
[BUG] Azure.Messaging.EventHubs messes up global telemetry sampling

### ISSUE THREAD

**Issue by andrew-lis** [Azure/azure-sdk-for-net#45275]
### Library name and version

Azure.Messaging.EventHubs.Processor 5.11.2

### Describe the bug

When Azure.Messaging.EventHubs.Processor got upgraded from 5.11.1 to 5.11.2 our telemetry for http requests (served by our service and not related to EventHubs) got affected. It looks like a global sampling on Application Insights SDK was changed. After investigation it turned out the the telemetry calls to appinsights from our service are affected (please see image 1).

As a result the log with http requests that our service is serving via asp.net (to be found in appinsights `requests` table) doesn't contain all the request, even though sampling in our service is not turned on.

Image 1:
![image](https://github.com/user-attachments/assets/f6a931fd-f637-403a-b2eb-a8cd6813a8e3)

### Expected behavior

Azure.Messaging.EventHubs.Processor doesn't change global telemetry sampling setting for the whole .net service (e.g. http requests served by ASP component).

### Actual behavior

Azure.Messaging.EventHubs.Processor when upgraded to 5.11.2 changes global telemetry sampling setting for the whole .net service. ASP Api component that reports http calls to our service is affected.

### Reproduction Steps

1. Setup .Net 8 api service that serves HTTP requests and uses EventHubs sdk
2. Use Azure.Messaging.EventHubs.Processor 5.11.1
3. Observe app insights telemetry 
4. Upgrade to Azure.Messaging.EventHubs.Processor 5.11.2
5. Observe that app insights telemetry for http requests is broken (sampling(?) is enabled)

### Environment

Azure, Debian, Event Hubs

**Comment by jsquire** [comment]
Hi @andrew-lis.  Thanks for reaching out and we regret that you're experiencing difficulties.  The Event Hubs client library has no awareness of AppInsights nor influence over its settings or behavior.   Event Hubs simply emits telemetry that follows the OTel specification, which can be collected by any OTel-aware aggregator.

If something changed related to AppInsights, it would be due to how either the AppInsights client library or the Azure Monitor service are capturing and reporting.   If you can tell me what client library you're using for AppInsights, I can either transfer to the appropriate team or advise on recommended next steps.

**Comment by andrew-lis** [comment]
The problem described above persists with 5.11.4. It consistently goes away when the Nuget is reverted to 5.11.1. It's an isolated change (I make no other changes in our codebase).

I just spotted in changelog of [Azure.Messaging.EventHubs 5.11.2](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/CHANGELOG.md#5112-2024-04-10) that there were some changes related to "batch-level tracing" (the EnableBatchTracing flag). Could it have influenced application-wide telemetry settings?

Our setup looks like this:
Serilog is used for logs, OpenTelemetry for metrics.

```
        var loggerConfiguration = new LoggerConfiguration()
            .Enrich.WithProperty("Application", "MyName")
            .Enrich.FromLogContext()
            .Enrich.WithMachineName()
            .ReadFrom.Configuration(builder.Configuration);

        TelemetryConfiguration telemetryConfiguration = TelemetryConfiguration.CreateDefault();
        telemetryConfiguration.ConnectionString = configuration.ApplicationInsights.ConnectionString;
        _telemetryClient =  new TelemetryClient(telemetryConfiguration);
		
        loggerConfiguration.WriteTo.ApplicationInsights(_telemetryClient, new ApplicationInsightsConverter());

        builder.Services.AddApplicationInsightsTelemetry();
	builder.Services
			.AddOpenTelemetry()
			.ConfigureResource(resourceBuilder => resourceBuilder
				.AddService(serviceName: "MyName", serviceInstanceId: Environment.MachineName))
			.WithMetrics(meterProviderBuilder => meterProviderBuilder
				.AddAzureMonitorMetricExporter(x => x.ConnectionString = configuration.ApplicationInsights.ConnectionString)
				.AddProcessInstrumentation()
				.AddRuntimeInstrumentation()
				.AddMeter(
					"Microsoft.AspNetCore.Server.Kestrel",
					"MyName"));

        Log.Logger = loggerConfiguration.CreateLogger();

        builder.Logging.ClearProviders();
        builder.Logging.AddSerilog(Log.Logger);
```

Remarks:
* the problem we have doesn't impact our custom metrics. It only affects ASP built-in `requests` metric that is affected. So after upgrade this starts to lie:
```
requests
| where cloud_RoleName == "MyName"
| where name == "GET MyPath"
```

* Libs used:

    \<PackageReference Include="Azure.Monitor.OpenTelemetry.AspNetCore" Version="1.1.0" />
    \<PackageReference Include="Microsoft.ApplicationInsights" Version="2.22.0" />
    \<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.22.0" />
    \<PackageReference Include="Microsoft.ApplicationInsights.Kubernetes" Version="6.1.2" />
    \<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.7.0" />
    \<PackageReference Include="OpenTelemetry.Instrumentation.Process" Version="0.5.0-beta.4" />
    \<PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.7.0" />
    \<PackageReference Include="Serilog" Version="3.1.1" />
    \<PackageReference Include="Serilog.AspNetCore" Version="8.0.1" />
    \<PackageReference Include="Serilog.Enrichers.Environment" Version="2.3.0" />
    \<PackageReference Include="Serilog.Sinks.ApplicationInsights" Version="4.0.0" />
	
* I've tried to switch off the `EnableBatchTracing` flag like on the example below, but it didn't help.

```
class MyEventProcessorClient : EventProcessorClient
{
    public MyEventProcessorClient(BlobContainerClient checkpointStore, string consumerGroup, string connectionString, EventProcessorClientOptions clientOptions)
        : base(checkpointStore, consumerGroup, connectionString, clientOptions)
    {
        base.EnableBatchTracing = true;
    }
}
```

**Comment by jsquire** [comment]
Thanks, @andrew-lis.   I've moved this over to the Monitor folks for AppInsights thoughts and will continue to work with them as Event Hubs knowledge is needed.

**Comment by TimothyMothra** [comment]
Hello @andrew-lis,
My team owns the Azure Monitor and Application Insights SDKs. 
Looking at your code sample, it appears that you're combining SEVERAL different logging libraries. 
This is not recommended, and this alone is likely to have conflicts.
With this approach, it's going to be very difficult to isolate what exactly is conflicting with EventHub.



### 1. Classic Application Insights SDK

- Nuget: https://www.nuget.org/packages/Microsoft.ApplicationInsights.aspnetcore
- Repo: https://github.com/microsoft/ApplicationInsights-dotnet

`builder.Services.AddApplicationInsightsTelemetry();`

This is the extension method that configures the classic Application Insights SDK for ASP.NET Core applications.
https://learn.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core?tabs=netcorenew


### 2. Classic Application Insights SDK again

```
TelemetryConfiguration telemetryConfiguration = TelemetryConfiguration.CreateDefault();
telemetryConfiguration.ConnectionString = configuration.ApplicationInsights.ConnectionString;
_telemetryClient =  new TelemetryClient(telemetryConfiguration);
```

It is not recommended to create multiple instances of `TelemetryConfiguration` and `TelemetryClient`.
The ASP.NET Core extension method creates it's own instance of `TelemetryConfiguration` and `TelemetryClient`. These classes access static objects, and creating multiple has been known to cause unpredictable side effects.

### 3. Something Custom?

`loggerConfiguration.WriteTo.ApplicationInsights(_telemetryClient, new ApplicationInsightsConverter());`

`Log.Logger = loggerConfiguration.CreateLogger();`

This appears to be something custom and I cannot comment.

### 4. Azure Monitor OpenTelemetry

- Nuget: https://www.nuget.org/packages/Azure.Monitor.OpenTelemetry.AspNetCore
- Repo: https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore

`AddAzureMonitorMetricExporter`

This is the Azure Monitor OpenTelemetry Exporter. 



### 5. Serilog 

`<PackageReference Include="Serilog.Sinks.ApplicationInsights" Version="4.0.0" />`

This appears to be a 3rd party logging adapter to support Application Insights. 


## Next Steps

I recommended that you instrument your application with ONE telemetry library and follow the best practices.

- Application Insights is a fully supported and feature rich SDK.
You can review the getting started guide here: https://learn.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core?tabs=netcorenew

- OpenTelemetry is a new tech stack and this will eventually replace the former classic SDK.
You can review the getting started guide here: https://learn.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-enable?tabs=net

**Comment by andrew-lis** [comment]
Altering our code fixed the issue. Now we use OpenTelemetry instead of AppInsights SDK for logs as well (we had to remove Serilog).

The ticket can be closed as resolved.
