### ISSUE TITLE
Remove-AzureRmApiManagementUser does not work after updating AzureRM.ApiManagement from 4.3.1

### ISSUE THREAD

**Issue by KK911** [Azure/azure-sdk-for-net#4528]
We use Azure Automation Runbook to clean up Azure resources on certain actions from our product. The cleanup script recently stopped working with the message `'uid' does not match expected pattern '(^[\w]+$)|(^[\w][\w\-]+[\w]$)'.` This happens when API management user is being deleted.

The command we use is
`Remove-AzureRmApiManagementUser -Context $ApiMgmtContext -UserId $apiUser.UserId -DeleteSubscriptions`

Upon investigation, I found that the module versions were recently updated in Automation Account in order to include AzureRM.KeyVault module and as part of that, the version of AzureRM.ApiManagement module was upgraded from 4.3.1 to 6.1.0. Looking at the diff of the source code, I found that [new validations have been added](https://github.com/Azure/azure-sdk-for-net/commit/270ea2d079e659dd4ba11dce2b3450f23789963e#diff-d5519adeb1aff12731d5e677b398e19aR1343) that prevents us from passing Emails as UserId values. 

I see this as a breaking change and haven't seen it documented. In our product, we create users in API management using the REST API [documented here](https://docs.microsoft.com/en-us/rest/api/apimanagement/apimanagementrest/azure-api-management-rest-api-user-entity#CreateUser) and it still says uid's length can be up to 256 chars and does allow EmailId to be used as uid.

**Comment by shahabhijeet** [comment]
@KK911 please open the issue in the Azure PS repo, this is a repo for tracking Azure .NET SDK issues and not Azure Powershell.
https://github.com/Azure/azure-powershell/issues/new
