### ISSUE TITLE
[QUERY] Why can't I set a UniqueKeyPolicy in CosmosDBSqlContainerResourceInfo?

### ISSUE THREAD

**Issue by dbeyda** [Azure/azure-sdk-for-net#45293]
### Library name and version

Azure.ResourceManager.CosmosDB 1.3.2.0

### Query/Question

Hello!
I'm at a codebase where we use [ContainerCollection.CreateOrUpdateAsync](https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.cosmosdb.cosmosdbsqlcontainercollection.createorupdateasync?view=azure-dotnet) to create or update our containers.

Notice this method receives a [CosmosDBSqlContainerCreateOrUpdateContent ](https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.cosmosdb.models.cosmosdbsqlcontainercreateorupdatecontent?view=azure-dotnet), which contains a [CosmosDBSqlContainerResourceInfo](https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.cosmosdb.models.cosmosdbsqlcontainerresourceinfo?view=azure-dotnet). ContainerResourceInfo class allows me to set some updatable properties (index, TTL), and also some properties that are only set during container creation (partition key for ex.).

However, I cannot set the UniqueKeys / UniqueKeyPolicy. If you look at [code](https://github.com/Azure/azure-sdk-for-net/blob/f03114b97bea85b9028e1a4850270a2e7de2bf3d/sdk/cosmosdb/Azure.ResourceManager.CosmosDB/src/Generated/Models/CosmosDBSqlContainerResourceInfo.cs#L99), UniqueKeyPolicy is `internal`.

Is there any way I can set this field?
If no, is there any particular reason to forbidding outside devs from setting this field?

Thanks a lot!

### Environment

Windows 11 / .NET 8.0.303

**Comment by dbeyda** [comment]
Found [the factory method](https://github.com/Azure/azure-sdk-for-net/blob/9e7f50e6fd833751c2489937b683c862a1955801/sdk/cosmosdb/Azure.ResourceManager.CosmosDB/src/Generated/ArmCosmosDBModelFactory.cs#L1094C9-L1094C104) I can use to set UniqueKey field!
Thanks!
@ArthurMa1978 Feel free to mark as resolved.

**Comment by HarveyLink** [comment]
@dbeyda Thank you for using Azure SDK for .NET.
Looks like you have work around this issue using Mock.
Actually, you could use this property:
https://github.com/Azure/azure-sdk-for-net/blob/f03114b97bea85b9028e1a4850270a2e7de2bf3d/sdk/cosmosdb/Azure.ResourceManager.CosmosDB/src/Generated/Models/CosmosDBSqlContainerResourceInfo.cs#L102
This will set the internal property `UniqueKeyPolicy` you would like to use. It's by design.
