### ISSUE TITLE
[BUG] The value for one of the HTTP headers is not in the correct format.

### ISSUE THREAD

**Issue by larcai** [Azure/azure-sdk-for-net#45302]
### Library name and version

Azure.Storage.Blobs 12.21.0

### Describe the bug

Since we upgraded from 12.20.0 to 12.21.0 we get the following when we try to call BlobContainerClient.Upload

```
The value for one of the HTTP headers is not in the correct format.
RequestId:0cc4fe84-d01e-0009-4108-e4e15f000000
Time:2024-08-01T11:49:06.8703261Z
Status: 400 (The value for one of the HTTP headers is not in the correct format.)
ErrorCode: InvalidHeaderValue
 
Additional Information:
HeaderName: x-ms-version
HeaderValue: 2024-08-04
 
Content:
﻿<?xml version="1.0" encoding="utf-8"?>
<Error><Code>InvalidHeaderValue</Code><Message>The value for one of the HTTP headers is not in the correct format.
RequestId:0cc4fe84-d01e-0009-4108-e4e15f000000
Time:2024-08-01T11:49:06.8703261Z</Message><HeaderName>x-ms-version</HeaderName><HeaderValue>2024-08-04</HeaderValue></Error>
 
Headers:
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 0cc4fe84-d01e-0009-4108-e4e15f000000
Date: Thu, 01 Aug 2024 11:49:06 GMT
Content-Length: 329
Content-Type: application/xml

```

### Expected behavior

Http 200 ... uploaded file

### Actual behavior

Http Status: 400 (The value for one of the HTTP headers is not in the correct format.)

### Reproduction Steps

Reference Azure.Storage.Blobs 12.21.0
Call Upload
This worked with 12.20.0

### Environment

Windows Server 
dotnet SDK 8.0.303 and Microsoft.AspNetCore.App 8.0.7

**Comment by larcai** [comment]
Seems like the SDK jumped the gun...  API version in the SDK seems to be in the future...

**Comment by seanmcc-msft** [comment]
@larcai, your storage account is on a tenant that does not have x-ms-version 2024-08-04 enabled yet.  There are two workarounds:
- Downgrade to 12.20.0
- Manually pin to the 2024-05-04 service version with `BlobClientOptions.Version = BlobClientOptions.ServiceVersion.V2024_05_04`.
