### ISSUE TITLE
Usage calculation change cause breaking changes when migrate to TypeSpec

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/azure-sdk-for-net#45319]
The TypeSpec TCGC offers a more accurate usage calculation compared to the .Net CodeGen. However, this improvement will result in breaking changes when an RP migrates to TypeSpec, like below:
![image](https://github.com/user-attachments/assets/e9f64e98-7a16-40db-b768-f7262610cb97)

Should we accept these breaking changes, or maintain the old, incorrect results to keep backward compatible?

**Comment by live1206** [comment]
After discussion with @m-nash, we will update the usage for brown-fields services with usage decorator to avoid the breaking change. And with the benefit of propagation of usage decorator, we might be able to reduce the size of usage decorators to be added.
