### ISSUE TITLE
[BUG] Duplicate Logs Azure Function

### ISSUE THREAD

**Issue by king-11** [Azure/azure-sdk-for-net#45320]
### Library name and version

Azure.Monitor.OpenTelemetry.AspNetCore 1.2.0

### Describe the bug

I am running a `dotnet-isolated` azure function app with `net8.0` and using opentelemetry azure distro to export telemetry data to app insights.

In app insights transaction search am seeing duplicate logging for each emitted log.

Only configuration I have added for opentelemetry is as below
```csharp
services
    .AddOpenTelemetry()
    .UseFunctionsWorkerDefaults()
    .UseAzureMonitor();
```

Changes made to `host.json` is
```json
{
  "version": "2.0",
  "logging": {
    "default": "Information",
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      },
      "enableLiveMetricsFilters": true
    }
  },
  "telemetryMode": "openTelemetry"
}
```

Docker Image being used `mcr.microsoft.com/azure-functions/dotnet-isolated:4-dotnet-isolated8.0`

### Expected behavior

Only logs from one source should be emitted

### Actual behavior

Seeing duplicate logs

### Reproduction Steps

Create a function app with net8.0 in isolated worker model and attach opentelemetry distro to emit. Create a event hub trigger function and add logs to it.

### Environment

Azure App Service
net8.0
dotnet-isolated
docker image

**Comment by king-11** [comment]
the duplicate logs are differing in the sdk used
- dotnetiso:1.0.0.0_dotnet8.0.7:otel1.9.0:ext1.3.0-d
- azurefunctions: 4.34.2.2

**Comment by TimothyMothra** [comment]
Hi @king-11,
Can you please also report your issue in the [Azure Function repo](https://github.com/Azure/azure-functions-dotnet-worker/issues)?

Your config matches what's in the Functions documentation: https://learn.microsoft.com/en-us/azure/azure-functions/opentelemetry-howto?tabs=app-insights&pivots=programming-language-csharp#3-enable-opentelemetry-in-your-app

I also see in their repo documentation that they have a "capability to avoid duplicate telemetry".
https://github.com/Azure/azure-functions-dotnet-worker/blob/f92cb254a5a777459ef881fe9b6c5b6ba9b977b1/src/DotNetWorker.OpenTelemetry/README.md

Seems that their `Microsoft.Azure.Functions.Worker.OpenTelemetry` package is in prerelease and you may have encountered a bug.

**Comment by king-11** [comment]
@TimothyMothra there is already an existing issue in functions app repo thanks for pointing that I will link this issue there as well in case you wanna close it here.

**Comment by king-11** [comment]
@RohitRanjanMS don't have issues with being beta tester and reporting issue so that it can be improved and released faster :)
