### ISSUE TITLE
KeyVaultClient - Threadsafe

### ISSUE THREAD

**Issue by alexmaie** [Azure/azure-sdk-for-net#4532]
Hello Azure team,

can somebody confirm me that the KeyVaultClient's Get,Set ... async methods are thread safe?

Thanks

**Comment by BadgerCode** [comment]
Seems to be
https://msdn.microsoft.com/en-us/library/microsoft.azure.keyvault.keyvaultclient.aspx#Anchor_5
https://stackoverflow.com/questions/6675905/which-features-make-a-class-to-be-thread-safe

**Comment by alexmaie** [comment]
would be nice to also add it here :) 
https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.keyvault.keyvaultclient?view=azure-dotnet
