### ISSUE TITLE
Permanent Delete does not work

### ISSUE THREAD

**Issue by well0549** [Azure/azure-sdk-for-net#45348]
### Library name and version

packages\azure.storage.blobs\12.21.1

### Describe the bug

From the documentation I get the impression that it should be possible to PERMANENTLY delete a SOFT deleted blob from blob storage.

In my situation I have a blob with several **versions** and **no snapshots**.. The properties of the storage account are:

![image](https://github.com/user-attachments/assets/5824dbd8-b22f-4bbf-98d6-997419ba8f1a)

However when i try to delete a blob with a version I alweays get an error code 400.

I tried several methods but I cannot seem to delete the blob permanently. 

### Expected behavior

From the documentation (https://learn.microsoft.com/en-us/rest/api/storageservices/delete-blob?tabs=microsoft-entra-id) I understand the following : (from permanent delete)

_Storage accounts with permanent delete enabled can use the deletetype=permanent query parameter to permanently delete a soft-deleted snapshot or deleted blob version._

So this means first delete the blob, and the call the rest api with deletetype=permanent

### Actual behavior

I tried several things. I have the following Method

```
        private static async Task DestroyBlob(string accountName,string containerName, string sasToken, string blobName,   string blobVersion = "", bool permanentDelete = false)
        {
            Dictionary<string, string> headers = new Dictionary<string, string>();
            headers.Add("x-ms-version", "2024-08-04");
            headers.Add("x-ms-date", DateTime.UtcNow.ToString("R"));
            headers.Add("x-ms-delete-snapshots", "include");

            string url;
            if (string.IsNullOrEmpty(blobVersion))
            {
                if (permanentDelete)
                    url = $"https://{accountName}.blob.core.windows.net/{containerName}/{blobName}?{sasToken}&deletetype=permanent";
                else
                    url = $"https://{accountName}.blob.core.windows.net/{containerName}/{blobName}?{sasToken}";
            }
            else
            {
                if (permanentDelete)
                    url = $"https://{accountName}.blob.core.windows.net/{containerName}/{blobName}?{sasToken}&versionId={blobVersion}&deletetype=permanent";
                else
                    url = $"https://{accountName}.blob.core.windows.net/{containerName}/{blobName}?{sasToken}&versionId={blobVersion}";
            }

            // Create the default HTTP Client and request
            var httpAdapterClient = EIPConfiguration.httpClientFactory.CreateClient(url);
            HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Delete, url);
            foreach (var header in headers)
            {
                request.Headers.Add(header.Key, header.Value);
            }

            // Send the request
            HttpResponseMessage response = await httpAdapterClient.SendAsync(request);
            // Check if the response is successful
            if (!response.IsSuccessStatusCode)
            {
                throw new Exception($"Permanent delete of {blobName} failed: {response.StatusCode}/{response.ReasonPhrase}, Uri: {url}");
            }
```

Now when i Run:
```
await DestroyBlob(accountName, containerName, sasToken,claimPointer.Claim.PayloadId,"",false);
```
I get a 202 Accepted.

But wwhen i run it for a second time but now with permanent delete enable I get.

```
 await DestroyBlob(accountName, containerName, sasToken, claimPointer.Claim.PayloadId, "", **true**);
```

```
StatusCode: 409, ReasonPhrase: 'Permanent delete is not support on root blob.', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
  x-ms-request-id: d3351778-701e-0035-5f24-e7010c000000
  x-ms-version: 2024-08-04
  x-ms-error-code: PermanentDeleteNotSupportedOnRootBlob
  Date: Mon, 05 Aug 2024 10:41:16 GMT
  Content-Length: 251
  Content-Type: application/xml
}
```

Because I could not get it to work, I tried deleting it with a version ID.

```
            await DestroyBlob(accountName, containerName, sasToken,claimPointer.Claim.PayloadId,""**,false**);
            await DestroyBlob(accountName, containerName, sasToken, claimPointer.Claim.PayloadId, **versions[3], true)**;

StatusCode: 400, ReasonPhrase: 'Value for one of the query parameters specified in the request URI is invalid.', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
  x-ms-request-id: 505b973b-201e-0040-5a24-e786b7000000
  x-ms-version: 2024-08-04
  x-ms-error-code: InvalidQueryParameterValue
  Date: Mon, 05 Aug 2024 10:45:50 GMT
  Content-Length: 494
  Content-Type: application/xml
}
```
The URL is the following: https://XXXXXXXXorageaccount.blob.core.windows.net/eiclaimpointers/8063e0f7-f3b5-4141-aad0-7c535105e932.ClaimPointer?sv=<SA>&versionId=2024-08-05T10:48:45.1334742Z&deletetype=permanent

However the versionid is documented. And should Work ?

### Reproduction Steps

Create a blob
add a few versions (no snapshots)
Try to permananetly delete the blob

### Environment

On azure.

**Comment by seanmcc-msft** [comment]
This is not an issue with the .NET Storage SDK itself, this is a question about the REST endpoint functionality.  The error message explains the functionality of the service "Permanent delete is not support on root blob."
