### ISSUE TITLE
[QUERY] DefaultAzureCredential.GetToken() cache logic

### ISSUE THREAD

**Issue by HanCKPu** [Azure/azure-sdk-for-net#45362]
### Library name and version

Azure.Identity 1.12.0

### Query/Question

Hi folks, could you help me understand how the cache logic works when using DefaultAzureCredential to get an access token for an Azure resource?

For example, we have a storage account that associates with a user-managed identity and we want to auth our app to it using MSI.
```
string userAssignedClientId = "<your managed identity client ID>";
var credential = new DefaultAzureCredential(
    new DefaultAzureCredentialOptions
    {
        ManagedIdentityClientId = userAssignedClientId
    });

var token = credential .GetToken(context, cancellationToken);
```

After searching across different threads, it looks like this `credential` instance will cache the credential type, and MSAL will cache the auth token on their side (is that true?) while each `.GetToken()` call will refresh the token in the `credential` instance.

Questions,
1. What's the difference between with or without `ManagedIdentityClientId = userAssignedClientId`
2. We have **hundreds** of nodes across different vmss deployed in different regions and all of them will refresh the access token by calling `.GetToken()` every 1 min. Is that a good behavior? Or should we implement some cache logic in the app?

Thanks in advance

### Environment

.NET 7

**Comment by HanCKPu** [comment]
@christothes would you mind take a look at the question at ur leisure?

**Comment by christothes** [comment]
> 1. What's the difference between with or without ManagedIdentityClientId = userAssignedClientId

Without specifying the client Id, the credential will default to a system-assigned identity. 

> 2. We have hundreds of nodes across different vmss deployed in different regions and all of them will refresh the access token by calling .GetToken() every 1 min. Is that a good behavior? Or should we implement some cache logic in the app?

You shouldn't need to implement your own cache for this scenario. The calls to `GetToken` will be satisfied via the cache until the token is past its half-life of expiration. After that, a new token will be fetched.
