### ISSUE TITLE
Is there any documentation about the option allowUnsafeKeys when using Azure Search?

### ISSUE THREAD

**Issue by Rookian** [Azure/azure-sdk-for-net#45371]
### Library name and version

Azure.Search.Documents 11.5.1

### Query/Question

I am using `searchClient.MergeOrUploadDocumentsAsync` and have some issues to provide valid Ids.

First Azure search complained about that I should use a base64 string, so I used `Convert.ToBase64String`.
Then it still complained about invalid characters, so I used 'WebEncoders.Base64UrlEncode'.
Then it complained that the Id is not allowed to start with a slash `'/'`.

I then discovered an answer on [Stackoverflow](https://stackoverflow.com/a/75620934/175399).
If anyone interested in custom policy with sdk:

1. **Register your index client with DI**

```c#

 builder.AddSearchIndexClient(configuration.GetSection("IndexClient"))
            .WithName("IndexName").ConfigureOptions(client =>
            {
                client.AddPolicy(new AllowUnsafeKeyPolicy(), HttpPipelinePosition.PerCall);
            });
```

2. **Create AllowUnsafeKeyPolicy class like below**

```c#
    public class AllowUnsafeKeyPolicy : HttpPipelinePolicy
    {
        public override void Process(HttpMessage message, ReadOnlyMemory<HttpPipelinePolicy> pipeline)
        {
            message.Request?.Uri.AppendQuery("allowUnsafeKeys", "true");
            ProcessNext(message, pipeline);
        }

        public override async ValueTask ProcessAsync(HttpMessage message, ReadOnlyMemory<HttpPipelinePolicy> pipeline)
        {
            await ProcessNextAsync(message, pipeline);
        }
    }
```

Is there any documentation about this option and its consequences?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ShivangiReja** [comment]
@Rookian - Thank you for reaching out, and we apologize for the challenges you're facing. The `allowUnsafeKeys` option is not available in the REST API specification or the official Search documentation. As the SDK team, we can only support features that are officially part of the search service, so we're unable to provide guidance on the potential consequences of adding this as a query parameter. This feature request would be more appropriately directed to the Azure Search service team.

If you have any specific needs or questions regarding the search service, we recommend raising an issue on the [Azure Search · Community](https://feedback.azure.com/d365community/forum/9325d19e-0225-ec11-b6e6-000d3a4f07b8) or [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request).

CC: @mattgotteiner
