### ISSUE TITLE
Propagate Meaningful Network Related Exceptions

### ISSUE THREAD

**Issue by zacg** [Azure/azure-sdk-for-net#4538]
Recently the "management.azure.com" API endpoint experienced degradation in service for an extended period of time which resulted in TCP connections being closed/reset at random.

This resulted in the SDK throwing generic "Task Was Canceled" exceptions on the async API calls. 

It would be helpful if the SDK library could emit a "Network Error" exception so business logic can attempt to recover from these errors.

**Comment by shahabhijeet** [comment]
Similar to https://github.com/Azure/azure-sdk-for-net/issues/4402

**Comment by allenjzhang** [comment]
This is not mgmt specific.  HttpClient will raise a TaskCanceledException if the send times out. If this needs to be addressed, should be addressed in Azure.Core.

**Comment by pakrym** [comment]
We've recently improved the timeout exception message.
