### ISSUE TITLE
Properties doesn't have Setter method. How to set its value

### ISSUE THREAD

**Issue by dotcom-gosahi** [Azure/azure-sdk-for-net#45391]
### Type of issue

Missing information

### Description

Namespace:
[Azure.AI.OpenAI.Chat](https://learn.microsoft.com/en-us/dotnet/api/azure.ai.openai.chat?view=azure-dotnet-preview)
Assembly:
Azure.AI.OpenAI.dll
Package:
Azure.AI.OpenAI v2.0.0-beta.2

Here 
public System.Collections.Generic.IList<string> ContentFieldNames { get; }
public System.Collections.Generic.IList<string> VectorFieldNames { get; }

both the properties doesn't have a setter method.
How to set them?

I am using azure search index. There I have defined couple of fields as vector data. I want to perform search only on those fields. How can that be acheived if I am not able to set above properties?

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/azure.ai.openai.chat.datasourcefieldmappings.vectorfieldnames?view=azure-dotnet-preview

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.AI.OpenAI.Chat/DataSourceFieldMappings.xml

### Document Version Independent Id

c605ffd8-8757-7f6d-42fe-52be0da558d7

### Article author

@azure-sdk

### Metadata

* ID: d289e390-7853-83c2-2f4d-5df7b536d110 
* Service: **azure**

**Comment by dotcom-gosahi** [comment]
I want to use my custom data and here is the code

options.AddDataSource(new AzureSearchChatDataSource()
{
    Endpoint = new Uri(searchEndpoint),
    IndexName = searchIndex,
    Authentication = DataSourceAuthentication.FromSystemManagedIdentity(),
    TopNDocuments = 3,
    Strictness = 3,
    InScope = false,
    QueryType = DataSourceQueryType.VectorSimpleHybrid,
    AllowPartialResult = false,
    RoleInformation = "You are an AI assistant that helps people find information.",
    VectorizationSource = DataSourceVectorizer.FromDeploymentName("name of the deployment"),
    FieldMappings = new DataSourceFieldMappings()
    {
        TitleFieldName = "ItemLegalShortName",
        FilepathFieldName = "ItemLegalShortName",
        //VectorFieldNames = new List<string> { "ItemLegalShortName", "ItemLegalShortName" }.AsReadOnly()
        //ContentFieldNames
        //= new List<string> { "ItemLegalShortName", "ItemLegalShortName" }.AsReadOnly()
    }
});

**Comment by jsquire** [comment]
Hi @dotcom-gosahi.  Thank you for reaching out and we regret that you're experiencing difficulties.  As a convention across libraries in the Azure SDK, collection types for models are intentionally read-only.   Their value can be set by mutating the existing collection.  This can be done by either adding members after the object has been constructed or using C#'s initializer syntax as part of construction.   

```csharp
// Example: adding items after construction.
var mappings =  new DataSourceFieldMappings();
mappings.VectorFieldNames.Add("ItemLegalShortName");
mappings.VectorFieldNames.Add("ItemLegalShortName");
mappings.VectorFieldNames.Add("ItemLegalShortName");

// Example: initializer syntax
var mappings =  new DataSourceFieldMappings()
{
    VectorFieldNames = { "ItemLegalShortName", "ItemLegalShortName", "ItemLegalShortName" }
};
```

**Comment by dotcom-gosahi** [comment]
It worked. Thank you so much!
