### ISSUE TITLE
Make Managment Endpoint Host Configurable

### ISSUE THREAD

**Issue by zacg** [Azure/azure-sdk-for-net#4539]
Recently the "management.azure.com" API endpoint experienced degradation in service for an extended period of time which resulted in TCP connections being closed/reset at random.

This resulted in the Azure critical response team to advise us to redirect our traffic from "management.azure.com" to an alternate unaffected region (e.g.  westus.mangement.azure.com).

If the "management.azure.com" endpoint was configurable in the SDK library we would have avoided the need to setup temporary networking routes on our servers to redirect traffic to the required regions.

**Comment by shahabhijeet** [comment]
@zacg we have created extensibility into every management SDKs.
If you have a need to overwrite any of the public properties, in this case BaseUri, you can do that by implementing CustomInitialize and overriding BaseUri property.
Does that answer your question?

**Comment by adrianhall** [comment]
We will assume this has answered your question on September 7th, 2019.  If you feel this issue is answered, feel free to close it.  If not, please let us know how we can be of assistance.
