### ISSUE TITLE
AZURE_REGIONAL_AUTHORITY_NAME not working for AAD regional endPOINT work (ESTS-R)

### ISSUE THREAD

**Issue by shivamverma-ms** [Azure/azure-sdk-for-net#45411]
### Library name and version

Azure.Identity

### Query/Question

Hi, for ESTS-R 

I added the Environment variable "AZURE_REGIONAL_AUTHORITY_NAME" to an incorrect random name, but it's not working as aad calls are still taking place but instead they should be failing with Unknown host error. Meanwhile for other services under the tenant i am using are able to make it work with below changes only.

Package References:
    "Azure.Identity" -> Version="1.11.4" 
    "Microsoft.Identity.ServiceEssentials.AspNetCore" -> Version="1.26.0"
    "Microsoft.IdentityModel.S2S.Extensions.AspNetCore" -> Version="4.5.0" 

Something Like this:

```
Environment.GetEnvironmentVariable("AZURE_REGIONAL_AUTHORITY_NAME"); // this returns "xyz" which is an incorrect endpoint.
// even with incorrect endpoint the below call is passing through.
var creds = new ClientCertificateCredential(
    clientApp.TenantId,
    clientApp.ClientId,
    cert,
    new ClientCertificateCredentialOptions
    {
        SendCertificateChain = true,
        AuthorityHost = new Uri(aadSettings.AadAuthority),
    });
```

**Comment by christothes** [comment]
Hi @shivamverma-ms - 
Could you clarify what you are trying to do in the successful case? 

`AZURE_REGIONAL_AUTHORITY_NAME` is meant to control the azure region selection for 1st party applications only. 

The `AuthorityHost` option sets the specific host to use for the authority. 

Which are you trying to use and what problem do you encounter when you attempt to use them?
