### ISSUE TITLE
[QUERY][DNS]Mock DnsRecordData and Expose DnsRecordType.cs in DnsRecordData.cs

### ISSUE THREAD

**Issue by yunheMsft** [Azure/azure-sdk-for-net#45423]
### Library name and version

Azure.ResourceManager.Dns 1.1.1

### Query/Question

1. There is no public constructor in [DnsRecordData.cs](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/dns/Azure.ResourceManager.Dns/src/Customization/DnsRecordData.cs). There is no way to mock the entity for GetAllRecordDataAsync() calls. Can it be included in [ArmDnsModelFactory.cs](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/dns/Azure.ResourceManager.Dns/src/Customization/ArmDnsModelFactory.cs)? 
2. [DnsRecordType.cs](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/dns/Azure.ResourceManager.Dns/src/Generated/Models/DnsRecordType.cs) is not publicly accessible and is not included in DnsRecordData.cs. When I make a call to fetch all DNS records from a zone via GetAllRecordDataAsync(), there is no easy way to determine the DNS record type for each result. Currently I have to parse the ResourceType value "Microsoft.Network/dnszone/CName" then extract the record type segment. Could you make the DnsRecordType.cs enum public then expose it in the DnsRecordData.cs, and potentially expose it in concrete type as well?

**Comment by live1206** [comment]
@HarveyLink Could you help on this? Thanks!

**Comment by live1206** [comment]
Changed merged, will be fixed in the next release of `Azure.ResourceManager.Dns`
