### ISSUE TITLE
EventGrid events sent to storage queue subscriptions have TTL of 7 days

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-sdk-for-net#4544]
With storage queues supporting infinite TTL, messages should be sent with infinite TTL rather than limited to 7 days.

**Comment by ahamad-MS** [comment]
Kindly switch this to a feature request rather than service attention.

The support of setting the TTL to infinity was recently added by storage and we need to evaluate the impact on the users storage queue capacity to prevent any delivery failure due to exceeding such capacity.

**Comment by SeanFeldman** [comment]
I'm actually considering to retract this issue as it's not a client issue, but the service side as @bsiegel has labelled it.

**Comment by jfggdl** [comment]
Sean,

Thanks for bringing this up. 
Regarding labeling the issue as Service Attention is a way for the service teams to be aware that an issue that originated as a client-side concern is actually an item that needs to be reviewed by the team that takes care of the service implementation. Hence, the team that fronts the client issues labeled this issue correctly as "Service Attention". That would help us tracking this issue correctly.

**Comment by SeanFeldman** [comment]
Thank you @jfggdl.
In that case, I'll keep the issue opened until service team has a chance to comment.

Side note: looks like this problem of categorizing issues will repeat itself with other clients as well in this and other repositories (.NET, Java, Go, or whatever the language SDK will be provided in). I've definitely have seen that with Azure Service Bus client/SDK [repo](https://github.com/Azure/azure-service-bus-dotnet/) and the service [repo](https://github.com/Azure/azure-service-bus/). Wonder if the [issue templates](https://github.com/Azure/azure-sdk-for-net/tree/master/.github/ISSUE_TEMPLATE) should contain a link to a document that maps client SDKs to the issue tracker(s) in a separate repository.

| Client | Service issue tracker|
|--------|----------------------|
|ServiceBus  | [link](url)                         |
|EventGrid| [link](url) |
| etc | ...|

Just a thought.

**Comment by ahamad-MS** [comment]
Feature request was added to our backlog for future consideration if needed. Please close this issue for now (as I don't have the right access rights here).

**Comment by SeanFeldman** [comment]
@ahamad-MS is there a public issue tracker for the service to be able to track that? Thank you.

**Comment by jfggdl** [comment]
@SeanFeldman, No, we do not have a public issue tracker. Rest assured that we have added this to our backlog.  This is Javier Fernandez, by the way.

I will be closing this issue. Please feel free to reopen it if you have any additional questions.

**Comment by SeanFeldman** [comment]
`jfggdl` w/o a picture - would never guess it's you, Javier 😄

As a side note, I know that you folks track it. For customers, it's still much better to have an issue tracker.

**Comment by SeanFeldman** [comment]
@jfggdl please reopen the issue. Storage Queue subscriber still exhibits this problem where TTL is set to 7 days only.

**Comment by SeanFeldman** [comment]
@ahamad-MS it's been a year since the issue was raised. Any updates?

**Comment by SeanFeldman** [comment]
@ahamad-MS any updates?

**Comment by ahamad-MS** [comment]
@SeanFeldman No new update. This is made into our priority list as a feature request and it is going through internal prioritization process by our management. We don't have an ETA if this will make it to the top of the list and unless we made the final decision on supporting this request or not, we cannot provide a different response.

However, we strongly encourage customer to have feature request through user voice and open IcM ticket.

**Comment by SeanFeldman** [comment]
> However, we strongly encourage customer to have feature request through user voice and open IcM ticket.

I'm the customer 🙂.
Arguable, UserVoice is not a developer-friendly medium to subscribe to updates to receive notifications.

What's IcM? I intentionally want to stay away from opening tickets as that allows no visibility into the progress for others interested in this issue. BTW, this is a bug, not a feature.

**Comment by jfggdl** [comment]
We have estimated already the effort to implement this feature/bug and we have prioritized it as high. However, there are other very-high priority features that are in the backlog to which we have committed for the next 6 months. Given that, this feature will not be able to be implemented in the next 6 months.  It will be reviewed again in early December or so and at that point we will decide if given the priorities at the time, we can commit to implement this feature. 

In addition to having this Github issue, please use the following link to vote on this feature request:
https://feedback.azure.com/forums/909934-azure-event-grid/suggestions/40810879-messages-events-support-for-infinite-greater-ttl

With your vote we can have additional insights into the interest for this feature and can drive its prioritization higher.

Thanks for your understanding.

**Comment by jfggdl** [comment]
So far, there are just 2 votes for this feature in https://feedback.azure.com/forums/909934-azure-event-grid/suggestions/40810879-messages-events-support-for-infinite-greater-ttl. I will be start doing in plans in mid-to-late November and I will check again the count to decide prioritization.

**Comment by SeanFeldman** [comment]
@jfggdl this is a bug rather than a feature 🙂

**Comment by SeanFeldman** [comment]
Regarding UserVoice and how misleading it is - Microsoft partially gets it. And partially not. UserVoice is a horrible experience for interacting. Developers prefer GitHub. Here’s a [testimonial](https://twitter.com/dotdestroyer/status/1314811620510625797) that is accurately summarizing this discussion of UserVoice vs GitHub.

**Comment by jsquire** [comment]
Moving to the backlog milestone, as the current assignment is no longer valid.   Please update accordingly when scheduled.

//cc: @jfggdl

**Comment by SeanFeldman** [comment]
> So far, there are just 2 votes for this feature

@jfggdl, there are 5 votes now. That's a whipping 250% increase in the demand 😀

**Comment by jfggdl** [comment]
We are going to release a feature that will allow the user to set a TTL for a storage queue destination. It will be released by June 2021.

**Comment by jfggdl** [comment]
We have implemented this feature: https://docs.microsoft.com/en-us/azure/event-grid/delivery-properties#configure-time-to-live-on-outgoing-events-to-azure-storage-queues. Closing issue. Thanks!

**Comment by SeanFeldman** [comment]
Thank you.
