### ISSUE TITLE
AddCryptographyClient documentation states incorrectly that it adds a `KeyClient`

### ISSUE THREAD

**Issue by ChristophHornung** [Azure/azure-sdk-for-net#45442]
### Type of issue

Typo

### Description

The docs state:

> Registers a [KeyClient](https://learn.microsoft.com/en-us/dotnet/api/azure.security.keyvault.keys.keyclient?view=azure-dotnet) instance with connection options loaded from the provided configuration instance.

But the method adds a CryptographyClient (like the name suggests).

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.azure.keyclientbuilderextensions.addcryptographyclient?view=azure-dotnet&devlangs=csharp&f1url=%3FappId%3DDev17IDEF1%26l%3DEN-US%26k%3Dk(Microsoft.Extensions.Azure.KeyClientBuilderExtensions.AddCryptographyClient%2560%25601)%3Bk(DevLang-csharp)%26rd%3Dtrue

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Extensions.Azure/KeyClientBuilderExtensions.xml

### Document Version Independent Id

1053cb0e-b8b1-1800-b133-1364f0f5257b

### Article author

@azure-sdk

### Metadata

* ID: 0914cdec-6fdf-9e88-7f46-d76782c0b08d

**Comment by jsquire** [comment]
Hi @ChristophHornung.   Thank you for bringing this to our attention.   We'll get the docs updated to reflect the correct type.

**Comment by jsquire** [comment]
fixed by #45500

**Comment by jsquire** [comment]
Fix has been merged and will publish to MS Learn with the next Key Vault release in early September.
