### ISSUE TITLE
Incomplete example documentation

### ISSUE THREAD

**Issue by hesperanca** [Azure/azure-sdk-for-net#45449]
### Type of issue

Missing information

### Description

[Enter feedback here]
In the code example, where does the "containerReadResponse" come from? 

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container.replacecontainerasync?view=azure-dotnet&devlangs=csharp&f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Microsoft.Azure.Cosmos.Container.ReplaceContainerAsync)%3Bk(SolutionItemsProject)%3Bk(SolutionItemsProject)%3Bk(SolutionItemsProject)%3Bk(DevLang-csharp)%26rd%3Dtrue

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/Container.xml

### Document Version Independent Id

3d112314-0fb8-6c7d-795c-fb76f38338da

### Article author

@azure-sdk

### Metadata

* ID: aa0a97c0-92fe-212b-b232-4860a3cb2ee3 
* Service: **cosmos-db**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.Azure.Cosmos` package is maintained as [#4635](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/4635).
