### ISSUE TITLE
How to invoke CreateOrUpdate operation on a resource with non-public properties?

### ISSUE THREAD

**Issue by ItalyPaleAle** [Azure/azure-sdk-for-net#45443]
### Library name and version

Azure.ResourceManager.AppContainers 1.2.0

### Query/Question

We need to create an Azure Container App Managed Environment resource (`Microsoft.App/managedEnvironments`) using the .NET SDK, but we need to add properties that are not part of the public ARM manifest and so are not available in the SDK. What is the recommended approach for this? I was not able to find any existing documentation or sample.

**Comment by jsquire** [comment]
Hi @ItalyPaleAle.  Thanks for reaching out and for your inquiry.  The Azure SDK packages expose an API surface that conforms to the public REST API specification for the service.  We do not offer support for undocumented constructs.

Our recommendation would be for you to invoke the service REST API directly and not use the Azure SDK packages.  If you choose to continue with the Azure SDK, you'll need to implement a custom HTTP policy for the pipeline that rewrites the request body with your undocumented members and that reacts to any undocumented response properties.   A sample discussing policies and how to write them can be found [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Pipeline.md).

**Comment by ItalyPaleAle** [comment]
Thank you! We ended up making direct REST calls using the regular HTTP client.
