### ISSUE TITLE
[QUERY] Create listener at runtime?

### ISSUE THREAD

**Issue by peterbergman** [Azure/azure-sdk-for-net#45457]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.ServiceBus

### Query/Question

Hi,
I've been using the `Microsoft.Azure.WebJobs.Extensions.ServiceBus`-package to setup methods that act as triggers for ServiceBus subscriptions and it works great. However, the current setup only seem to allow for defining your triggers using the `ServiceBusTrigger`-attribute where queue/topic name are defined using compile time constants. I saw that you can also implement your own name resolver to get some more flexibility. But I wonder, is it possible to also register triggers through the DI somehow to avoid befing forced to use the attribute?

For example, it would be nice if I could do something like this (assuming that `ITrigger` is an interface from the package)

```csharp
services.AddSingleton<ITrigger, MyCustomTrigger>();
```

**Comment by jsquire** [comment]
Hi @peterbergman.  Thank you for reaching out and your suggestion.  It is not required that you use constant values with the trigger.  Azure Functions provides additional binding syntax options which allow for you to bind to dynamic configuration values or perform the binding at runtime.   Please see [Azure Functions binding expression patterns](https://learn.microsoft.com/azure/azure-functions/functions-bindings-expressions-patterns) and [Binding at runtime](https://learn.microsoft.com/azure/azure-functions/functions-dotnet-class-library?tabs=v4%2Ccmd#binding-at-runtime).

**Comment by peterbergman** [comment]
Thanks for the suggestion @jsquire! Most of the documentation I've found focuses on runtime binding for output bindings. However, I'm interested in achieving the same for input bindings. Could you please provide examples of how this can be done or point me to any documentation that covers this topic?

**Comment by jsquire** [comment]
@peterbergman:  Unfortunately, I have only those that I shared.  These are concepts from the Azure Functions runtime and outside the insight or influence of the Azure SDK extension package.    If you're looking for additional documentation that isn't accessible from the Functions docs on Learn, you may want to consider opening an issue in the [Azure Functions runtime repository](https://github.com/Azure/azure-functions-host/issues) or inquiring on the [Microsoft Q&A site](https://learn.microsoft.com/answers/questions/).  

The Azure Functions team monitors both and would be best able to offer additional guidance and doc pointers.

**Comment by peterbergman** [comment]
@jsquire thanks, I'll try that out!
