### ISSUE TITLE
What permissions does DPAPI PersistKeysToAzureBlobStorage need, and how to handle expiry?

### ISSUE THREAD

**Issue by saasen** [Azure/azure-sdk-for-net#45451]
### Library name and version

Azure.Extensions.AspNetCore.DataProtection.Blobs 1.3.4

### Query/Question

I have tried looking for information around what permissions the SAS token for this API needs, but I can't find it anywhere. 

From what I can see, the available permissions are:
- Read
- Add
- Create
- Write
- Delete
- List
- Immutable storage

It looks like SAS tokens also must have an expiry. Even though you can set it far in the future, does that mean we need to rotate the SAS tokens?

What method for storing DPAPI keys do you recommend?

### Environment

N/A

**Comment by jsquire** [comment]
Hi @saasen.  Thanks for reaching out and for your inquiry.   The package requires read, write, and list access to the container.  We recommend using an Entra ID with the "Storage Blob Data Contributor" RBAC role assigned.   More information can be found in the [README](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/extensions/Azure.Extensions.AspNetCore.DataProtection.Blobs/README.md).

With respect to storing and managing keys, we would recommend reading through the data protection documentation for guidance:

- [ASP.NET Core Data Protection Overview](https://learn.microsoft.com/aspnet/core/security/data-protection/introduction?view=aspnetcore-8.0)
- [Configure ASP.NET Core Data Protection](https://learn.microsoft.com/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-8.0)
- [Safe storage of app secrets in development in ASP.NET Core](https://learn.microsoft.com/aspnet/core/security/app-secrets?view=aspnetcore-8.0&tabs=windows)

**Comment by saasen** [comment]
Thanks, @jsquire! I'll read through the material. I'm closing this, and re-opening it if I have any more questions.
