### ISSUE TITLE
[QUERY] Release an Azure.Identity version with an updated Azure.Core dependency

### ISSUE THREAD

**Issue by MarcWils** [Azure/azure-sdk-for-net#45453]
### Library name and version

Azure.Identity 1.12.0

### Query/Question

Azure.Core 1.40.0 had an issue (#44817) which was fixed in 1.41.0 (#44882). This causes tasks/applications to intermittently get stuck.

The latest Azure.Identity release (1.12.0) still has a dependency on this "broken" version. There's a workaround by adding a direct reference to Azure.Core. But it's easy often not the case. And this issue only comes up sporadically.

When will a version of Azure.Identity be released containing the new dependency? Azure.Identity 1.13.0-beta.1 has a newer dependency version. When is it scheduled to be released?

**Comment by scottaddie** [comment]
@MarcWils The 1.13.0 GA release will ship in the 2nd week of October.
