### ISSUE TITLE
How to create Bot Service using dynamic MSA App Id/Password

### ISSUE THREAD

**Issue by mehtanilay10** [Azure/azure-sdk-for-net#4546]
I want to create a new Bot Service dynamically.
For this, I am using Microsoft.Azure.Management.BotService
Here I need to pass MSA App Id & Password when using Create() of BotsOperationsExtensions.
How can I create dynamically MSA app id/pass?

When trying to use BotsOperationsExtensions.CreateWebAppBot() It gives an error of 

> For Device code authentication, a handler for device code needs to be provided to create an Msa app id. Alternatively, provide your own Msa app id to avoid creating a new one.
> Parameter name: deviceCodeAuthHandler

```
// Create Bot client
AzureBotServiceClient botServiceClient = new AzureBotServiceClient(credentials);
botServiceClient.TenantId = credentials.TenantId;
botServiceClient.SubscriptionId = credentials.DefaultSubscriptionId;

// Create Bot 
Bot bot = new Bot
{
    Location = "global",
    Kind = Kind.Sdk,
    Properties = new BotProperties
    {
        Description = "Description of New Bot",
        DisplayName = "MyNewBotCreatedFromConsole",
        Endpoint = "https://superbot10-superbot10dev.azurewebsites.net/api/Values",
        Kind = Kind.Sdk,
        Sku = new Sku(SkuName.F0, SkuTier.Free),
        MsaAppId = Guid.NewGuid().ToString(),
        MsaAppPassword = Guid.NewGuid().ToString(),
        Location = "global",
    },
};
BotDeploymentInfo deploymentInfo = new BotDeploymentInfo
{
    CreateAppInsights = false,
};
//Microsoft.Azure.Management.BotService.Customizations.BotsOperationsExtensions.CreateWebAppBot(botServiceClient.Bots, resourceName, resourceName, bot, deploymentInfo);
botServiceClient.Bots.Create(resourceName, resourceName, bot);
```

**Comment by jsquire** [comment]
Closing this out as this refers to a legacy version of the library and there has been no recent engagement.  Please feel free to reopen or file a new issue if this remains a problem with the current version of the library.
