### ISSUE TITLE
[QUERY] Getting Delivery Properties of Event subscription From Azure Function

### ISSUE THREAD

**Issue by Baxom** [Azure/azure-sdk-for-net#45471]
### Library name and version

Microsoft.Azure.Functions.Worker.Extensions.EventGrid 3.4.1

### Query/Question

Hello,

I'm trying to deliver only one Azure Function to listen multiple Blobs. For this I choose to publish events when something happens on my storage to an event grid.

Then I have a function (isolated) which is triggered by the [EventGridTrigger].

All works well, nevertheless, I am not able to retrieve the headers I've added in the "delivery properties" of my event subscription.

![image](https://github.com/user-attachments/assets/dc008bbc-1ef7-4ad0-bd4a-659ec1524908)

I am only able to inject a CloudEvent, and the FunctionContext which doesn't carries anything interesting.

Is it possible ?

Thanks

**Comment by JoshLove-msft** [comment]
Hi @Baxom,
The isolated worker extension is shipped out of a different repo. I've created a new issue with your question in that repo - https://github.com/Azure/azure-functions-dotnet-worker/issues/2677
