### ISSUE TITLE
[QUERY] Connecting to ACR using Managed Identity to create ACI

### ISSUE THREAD

**Issue by shankarvrp** [Azure/azure-sdk-for-net#45492]
### Library name and version

Azure.ResourceManager.ContainerInstance 1.2.1

### Query/Question

Hi All,

I am using the samples to create ACI, while all samples appear to cover the public images to use in ACR, I don't see a way to connect to ACR using Managed Identity. Is there a way to achieve this when creating ACI instance programmatically today or is coming in the near term? Thanks much

On another note, also tried using Microsoft.Azure.Management.ContainerInstance.Fluent, there is the WithPrivateImageRegistry option that takes username and password but that also doesn't support managed identity.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Please following this document to understand the limitations and prerequisites.
https://learn.microsoft.com/en-us/azure/container-instances/using-azure-container-registry-mi
As the doc suggest, we could assgin the identity both in identity property and imageRegistryCredentials property part, which would make the code look like:

    var containerGroup = new ContainerGroupData(
      location: "westus",
      containers: containers,
      osType: ContainerInstanceOperatingSystemType.Linux)
    {
        Identity = new ManagedServiceIdentity(ManagedServiceIdentityType.UserAssigned)
        {
            UserAssignedIdentities =
            {
                { new ResourceIdentifier("uid"), new UserAssignedIdentity() }
            }
        },
        ImageRegistryCredentials =
        {
            new ContainerGroupImageRegistryCredential("myacr.azurecr.io")
            {
                Identity = "uid"
            }
        },
....
}
