### ISSUE TITLE
[QUERY][DNS]Retry policy for GetAllRecordDataAyns()

### ISSUE THREAD

**Issue by yunheMsft** [Azure/azure-sdk-for-net#45524]
### Library name and version

Azure.ResourceManager.Dns 1.1.1

### Query/Question

I have a process to fetch all Dns records from a zone using [GetAllRecordDataAsync()](https://github.com/Azure/azure-sdk-for-net/blob/0a7a585f2f40d09813e4f51b93a8a7dd69854380/sdk/dns/Azure.ResourceManager.Dns/src/Customization/DnsZoneResource.cs#L981). 
```
public async IAsyncEnumerable<DnsRecordData> GetAllDnsRecordDataAsync(int limit = DnsConfigurationFactory.DefaultGetAllDnsRecordsPerPageLimit)
    {
        AsyncPageable<DnsRecordData> asyncRecordSetsPages = _dnsZoneResource.GetAllRecordDataAsync(top: limit);

        await foreach(DnsRecordData record in asyncRecordSetsPages)
        {
            yield return record;
        }
    }
```
When iterating through the result AsyncPageable<DnsRecordData>, I see 429 error returned by DNS server side. Based on the logs from ARM, the SDK client initiated 3-4 retries for the call to fetch a particular page. However, the delay between each retry was only 10 seconds. This aligns with the "Retry-After: 10" header returned by DNS service. 
My questions:
1. Why is the default retry policy not using exponential backoff for throttling error?
2. Is it possible to attach a custom retry policy for the fetch page call?

**Comment by HarveyLink** [comment]
Hi @yunheMsft ,
For the questions you asked.
1. Default retry policy will prioritize Error response's RetryAfter header. So if the returned error contains service defined retry, SDK will follow it. Check https://github.com/Azure/azure-sdk-for-net/blob/150082bd7ac135540c5e3ec145ca596cc7e20716/sdk/core/Azure.Core/src/Pipeline/RetryPolicy.cs#L122 
```
                if (shouldRetry)
                {
                    var retryAfter = message.HasResponse ? message.Response.Headers.RetryAfter : default;
                    TimeSpan delay = async ? await GetNextDelayAsync(message, retryAfter).ConfigureAwait(false) : GetNextDelay(message, retryAfter);
                    if (delay > TimeSpan.Zero)
                    {
                        if (async)
                        {
                            await WaitAsync(delay, message.CancellationToken).ConfigureAwait(false);
                        }
                        else
                        {
                            Wait(delay, message.CancellationToken);
                        }
                    }
```
2. Yes, SDK support customized RetryPolicy, you could add it like
```
var option = new ArmClientOptions()
{
    RetryPolicy = new YourPolicy()
};
var client = new ArmClient(new DefaultAzureCredential(), subscription, option);
```
Your customized policy should inherit from `HttpPipelinePolicy` just like [RetryPolicy](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Pipeline/RetryPolicy.cs)

**Comment by yunheMsft** [comment]
Thanks @HarveyLink for the explanation.
