### ISSUE TITLE
CustomVision.Prediction SDK gives NotFound when no default iteration is set

### ISSUE THREAD

**Issue by jimbobbennett** [Azure/azure-sdk-for-net#4556]
**To reproduce**
Create and train a custom vision project through the portal.
Access the project to perform a prediction from a C# app using the Microsoft.Azure.CognitiveServices.Vision.CustomVision.Prediction NuGet package.

*Expected*
The prediction results should come back successfully.

*Actual*
A 404 error is returned.

**Details**

The reason for the error is that one iteration needs to be set as the default. If this step is not done, the 404 error is found. This is very unintuitive for new users, especially as the docs don't make this clear.

Ideally we should do one of the following:

* Make the first iteration the default
* Throw a better exception that a 404 giving the user an explanation

**Comment by tburns10** [comment]
Since this issue was raised, we've changed the behavior and require an iteration to be published to be utilized so its a new paradigm altogether and this issue no longer exists.

**Comment by ChrisHMSFT** [comment]
Closing the ticket per the above comment that the issue has been resolved. Please re-open if you are still experiencing an issue.
