### ISSUE TITLE
Generate Profile SDK

### ISSUE THREAD

**Issue by shahabhijeet** [Azure/azure-sdk-for-net#4557]
- Finish investigating website generation issue
- add second profile and generate multi profile SDK for each RP
- Make sure these can be build/signed.

Cost: 2 days

**Comment by dsgouda** [comment]
Breaking this down into 2 different pieces
- Getting the Websites profile SDK to build. Initial investigation suggests that `WebsitesManagementClient` must have some operations that then get referenced in `WebsitesManagementClientExtension`, looks like there might be some overlap which is rewriting the `WebsitesManagementClient`. Need to discuss with AutoRest owners regarding this

Add a second profile
- This needs adding a new profile section to each of the config files, adding code generation scripts and generating the code themselves
- Finally need to create csproj/sln files and build the projects

**Comment by dsgouda** [comment]
SDK generated, awaiting feedback to be addressed in future tasks
