### ISSUE TITLE
Broken image link for azure sdk for .net

### ISSUE THREAD

**Issue by tlunsfordCXP** [Azure/azure-sdk-for-net#45591]
### Type of issue

Typo

### Description

The image in the following documentation is dead:

https://learn.microsoft.com/en-us/dotnet/api/overview/azure/identity-readme?view=azure-dotnet#:~:text=The%20DefaultAzureCredential%20attempts%20to%20authenticate%20via%20the%20following%20mechanisms%2C%20in%20this%20order%2C%20stopping%20when%20one%20succeeds%3A

It appears that the link should be pointing to a .png file instead of a .svg file. This image link works:

https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/images/DefaultAzureCredentialAuthenticationFlow.png

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/overview/azure/identity-readme?view=azure-dotnet

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/latest/identity-readme.md

### Document Version Independent Id

c6232a65-a004-428e-1ddf-84f6049ce875

### Article author

@azure-sdk

### Metadata

* ID: 91f437c5-363b-f98a-f595-5fcb9bf39d2a 
* Service: **identity**

**Comment by scottaddie** [comment]
@tlunsfordCXP Thank you for reporting this issue. It has been resolved. As an FYI, we're in the process of moving this content to https://learn.microsoft.com/dotnet/azure/sdk/authentication/credential-chains.
