### ISSUE TITLE
Get Key and Secret Metadata that is not attached to Certificates

### ISSUE THREAD

**Issue by spruhanayak** [Azure/azure-sdk-for-net#45592]
### Type of issue

Other (describe below)

### Description

How can I retrieve metadata for keys and secrets from Azure Key Vault using the .NET SDK while ensuring that I exclude any keys and secrets associated with certificates? I know that the `managed` property can indicate whether an item is related to a certificate, but is it reliable to use this property exclusively to filter out such items?
https://learn.microsoft.com/en-us/dotnet/api/azure.security.keyvault.keys.keyclient.getpropertiesofkeys?view=azure-dotnet

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/azure.security.keyvault.keys.keyproperties.managed?view=azure-dotnet

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Security.KeyVault.Keys/KeyProperties.xml

### Document Version Independent Id

5b1997b2-68c9-acb4-2a7d-f05a594c1343

### Article author

@azure-sdk

### Metadata

* ID: 4f4d100d-c76c-ee92-b419-2c1abe6f0a4f 
* Service: **azure**

**Comment by heaths** [comment]
Yes, "managed" means it's managed by a certificate. From <https://learn.microsoft.com/rest/api/keyvault/secrets/get-secrets/get-secrets?view=rest-keyvault-secrets-7.4&tabs=HTTP#secretitem>,

Name | Type | Description
--- | --- | ---
managed | boolean | True if the secret's lifetime is managed by key vault. If this is a key backing a certificate, then managed will be true.

**Comment by spruhanayak** [comment]
/unresolve could manage be set true for any other reasons besides being backed by a cert?

**Comment by heaths** [comment]
No. The documentation is correct.

Please also note, if you have general questions, you can also ask on https://stackoverflow.com with the tag `azure-keyvault`.
