### ISSUE TITLE
Unclear what SubscriptionRuntimeProperties.AccessedAt really means

### ISSUE THREAD

**Issue by gliljas** [Azure/azure-sdk-for-net#45641]
### Library name and version

Azure.Messaging.ServiceBus

### Query/Question

The property SubscriptionRuntimeProperties.AccessedAt is supposed to return "when the entity was last accessed", but what does that mean? What constitutes access? I think it would be nice with a bit of clarification in the docs.

More specifically, is this the value that is used when calculating idle time for the  "auto-delete on idle" mechanism? We want to implement a warning notification system, which can alert us on pending deletions.

**Comment by jsquire** [comment]
Hi @gliljas.  Thank you for reaching out and for your inquiry.  Unfortunately there is no official Service Bus service documentation that details what "access" indicates, but it looks from the [legacy package docs](https://learn.microsoft.com/dotnet/api/microsoft.servicebus.messaging.subscriptiondescription?view=azure-dotnet-legacy) that "access" for a subscription means that there was a receive request for it.

**Comment by gliljas** [comment]
Thanks for the link to the legacy docs, @jsquire! Since it's a service side property I should be the same in the new library, and it's quite likely exactly what we wanted.
