### ISSUE TITLE
Redundant ToArray() call in GetBlobsAsyncCollection class

### ISSUE THREAD

**Issue by rameel** [Azure/azure-sdk-for-net#45653]
### Library name

Azure.Storage.Blobs

In the `GetBlobsAsyncCollection` class, there is an unnecessary call to `ToArray()` in the following code snippet:
[GetBlobsAsyncCollection.cs](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs/src/Models/GetBlobsAsyncCollection.cs#L68C63-L68C73)
```csharp
            return Page<BlobItem>.FromValues(
                response.Value.Segment.BlobItems.ToBlobItems().ToArray(),
                response.Value.NextMarker,
                response.GetRawResponse());
```
The `ToArray()` method call is redundant because the `ToBlobItems()` method already returns an array.

**Comment by nickliu-msft** [comment]
This issue has been resolved from this PR: https://github.com/Azure/azure-sdk-for-net/pull/45654
