### ISSUE TITLE
[QUERY] InteractiveBrowserCredential from .NET 8 WebApp

### ISSUE THREAD

**Issue by timthedevguy** [Azure/azure-sdk-for-net#45658]
### Library name and version

Azure.Identity 1.12.0

### Query/Question

Reference Issue #28076 

I am experiencing the same issue, I see in the response that this is by design as this method was intended for client side apps.  What is the suggested method if you are doing this: My app will start with bare bones settings, walking the user through an initial setup, part of that initial setup uses InteractiveBrowserCredential to allow the user to authenticate and then my app will create the App Registration, Roles, Client Secrets, setup Graph perms, etc and then store the ClientID/ClientSecret/etc details.  When app restarts the setup is complete and it then uses the clientsecret credentials.  Haven't really seen a good method other than the Interactive one, I can do it in PowerShell but that kind of ruins the setup experience for those not familiar with PoSh.

### Environment

Host:
  Version:      8.0.7
  Architecture: x64
  Commit:       2aade6beb0
  RID:          win-x64

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.31 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.31 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

IIS 10 + Server 2019

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by timthedevguy** [comment]
Will close, will switch to DeviceCode flow
