### ISSUE TITLE
[FEATURE REQ] Support object ID for ManagedIdentityCredential in AzureComponentFactory

### ISSUE THREAD

**Issue by scottaddie** [Azure/azure-sdk-for-net#45661]
### Library name

Microsoft.Extensions.Azure

### Please describe the feature.

The Azure Identity library's `ManagedIdentityCredential` is being enhanced to support object ID for user-assigned managed identity. See https://github.com/Azure/azure-sdk-for-net/pull/45605. Object ID is an alternative to using client ID or resource ID. With regards to `ManagedIdentityCredential`, we should have feature parity between Azure.Identity and Microsoft.Extensions.Azure. It would involve updating this code: https://github.com/Azure/azure-sdk-for-net/blob/91dc3f14f2d219c61ec7cdb715764becfce8fc73/sdk/extensions/Microsoft.Extensions.Azure/src/Internal/ClientFactory.cs#L115-L128

From a customer's perspective, they should be able to provide configuration like the following:

```json
{
    "credential": "managedidentity",
    "managedIdentityObjectId":  "<managedIdentityObjectId>"
}
```

Since we don't support object ID via `DefaultAzureCredential`, the following code flow is unaffected: https://github.com/Azure/azure-sdk-for-net/blob/91dc3f14f2d219c61ec7cdb715764becfce8fc73/sdk/extensions/Microsoft.Extensions.Azure/src/Internal/ClientFactory.cs#L218-L249

**Comment by christothes** [comment]
This change can be made after we ship the October release of Azure.Identity.

**Comment by scottaddie** [comment]
That sounds like a fine plan to me
