### ISSUE TITLE
Update ClientResult to Azure.Core.Response for Azure plugin

### ISSUE THREAD

**Issue by live1206** [Azure/azure-sdk-for-net#45705]
### Library name

N/A

### Please describe the feature.

Update operation return type from `ClientResult` to `Azure.Core.Response`

**Comment by annelo-msft** [comment]
@live1206, would you please add more context to this feature request?   It looks like a generator plugin feature, but it isn't marked as such.

**Comment by live1206** [comment]
> @live1206, would you please add more context to this feature request? It looks like a generator plugin feature, but it isn't marked as such.

Yes, sorry about the confusion, this is about the generator plugin, think we need a new tag for that  @ArthurMa1978

**Comment by live1206** [comment]
pending on https://github.com/microsoft/typespec/issues/3693
