### ISSUE TITLE
Returning an Exception "Container Not Found"

### ISSUE THREAD

**Issue by dotcom-gosahi** [Azure/azure-sdk-for-net#45708]
### Type of issue

Missing information

### Description

var uploadContainerEndpoint = string.Format("https://{0}.blob.core.windows.net/{1}", storageName, containerName);

var credential = new VisualStudioCredential();
var blobServiceClientOptions = new BlobClientOptions()
{
    Retry = {
        // Adjusting the Network Timeout to 5 minutes
        NetworkTimeout = TimeSpan.FromMinutes(15)
    }
};
var blobUploadContainerClient = new BlobContainerClient(new Uri(uploadContainerEndpoint), credential, blobServiceClientOptions);
bool isExists = blobUploadContainerClient.Exists();

It is returning "true" when container exists (expected behaviour).
But when container doesn't exist, instead of returning "false", it is throwing exception "Container Not Found".
![exception](https://github.com/user-attachments/assets/27cb6aa2-7a8a-45d8-8faf-107564518c97)
Please help me understanf if this is an expected behaviour or I need to make some changes.

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobcontainerclient.exists?view=azure-dotnet

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Blobs/BlobContainerClient.xml

### Document Version Independent Id

86e0dc6a-aea6-5baa-c6a2-d016ffd7445a

### Article author

@azure-sdk

### Metadata

* ID: ddcbc767-2ed7-b376-51fe-34c13fe7b391 
* Service: **azure**

**Comment by dotcom-gosahi** [comment]
Hey Team.
Any update on this?

**Comment by dotcom-gosahi** [comment]
Hello Team.
Following up on the above issue

**Comment by nickliu-msft** [comment]
Hi @dotcom-gosahi, based on how the code is written, it seems that if the container does not exist it will just return false with no exceptions thrown

https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs/src/BlobContainerClient.cs#L1656

I have also tried replicating your above code as a sample test and did not run into your issue (container did not exist and just returned false). Here is my code that replicated the code you provided

`        [Test]
        public async Task SampleTestForContainerExists()
        {
            await using DisposingContainer test = await GetTestContainerAsync();
            var uploadContainerEndpoint = string.Format("https://{0}.blob.core.windows.net/{1}", test.Container.AccountName, GetNewContainerName());
            var credential = new VisualStudioCredential();
            var blobServiceClientOptions = new BlobClientOptions()
            {
                Retry = {
                // Adjusting the Network Timeout to 5 minutes
                NetworkTimeout = TimeSpan.FromMinutes(15)
                }
            };
            var blobUploadContainerClient = new BlobContainerClient(new Uri(uploadContainerEndpoint), credential, blobServiceClientOptions);
            bool isExists = blobUploadContainerClient.Exists();
        }`
        
Have you made sure your account name and credentials are set correctly?

cc: @amnguye
