### ISSUE TITLE
[BUG] Azure.AI.OpenAI (2.0.0-beta.3) not compatible with OpenAI (2.0.0-beta.10), AudioClient fails with 404

### ISSUE THREAD

**Issue by grankko** [Azure/azure-sdk-for-net#45706]
### Library name and version

Azure.AI.OpenAI (2.0.0-beta.3) and OpenAI (2.0.0-beta.10)

### Describe the bug

OpenAI 2.0.0 beta 10 package breaks the latest version of the Azure.AI.OpenAI package. When setting up a AudioClient to do text to speech the network call fails with 404. Probably related to changes in the OpenAI how endpoint URLs are generated internally.

The following code fails with 404:
```
            var client = new AzureOpenAIClient(new Uri("<azure endpoint>"), new System.ClientModel.ApiKeyCredential("<key>"));
            var ttsClient = client.GetAudioClient("<model deployment name>");
            var response = await ttsClient.GenerateSpeechAsync("Say hi!", OpenAI.Audio.GeneratedSpeechVoice.Nova);
```

### Expected behavior

I expect the service call to succeed.

### Actual behavior

The request is sent to a bad URL and results in a 404.

### Reproduction Steps

Setup a TTS model in Azure OpenAI, use the latest version of the packages and run something like this:
```
            var client = new AzureOpenAIClient(new Uri("<azure endpoint>"), new System.ClientModel.ApiKeyCredential("<key>"));
            var ttsClient = client.GetAudioClient("<model deployment name>");
            var response = await ttsClient.GenerateSpeechAsync("Say hi!", OpenAI.Audio.GeneratedSpeechVoice.Nova);
```

### Environment

VS 17.10.6
dotnet 8

**Comment by RogerBarret0** [comment]
That's correct, I'm having the same issue as well.

Seems that the `AudioClient` is not appending the `Azure` endpoint correctly, defaulting to the OpenAI V1 endpoint approach.

![image](https://github.com/user-attachments/assets/c2d6421d-d499-46a7-a5a8-d841da9ec695)
