### ISSUE TITLE
[QUERY] Best practices regarding sharing `DefaultAzureCredential` instances across calls

### ISSUE THREAD

**Issue by julealgon** [Azure/azure-sdk-for-net#45713]
### Library name and version

Azure.Identity 1.12.0

### Query/Question

We have a project setup that has 2 connections to Azure AppConfig, both with Azure Vault support, a connection to cosmos, and another connection to Service Bus. The connections to Cosmos and ServiceBus are handled using `Microsoft.Extension.Azure`'s `AddAzureClients`, which naturally has a centralized means of providing the credential object (it uses `DefaultAzureCredential` by default behind the scenes). But the AppConfig configuration does not have such "high-level" API and requires us to pass the credential for both app configuration _and_ vault integration using the `Connect` and `ConfigureKeyVault` methods.

Currently, we are relying on the `DefaultAzureCredential` class for all of those, but we specify `new DefaultAzureCredential()` on every single place where it is needed.

My question is in regards to reusing instances of this class: is it safe and advisable to reuse a single instance of the `DefaultAzureCredential` class in scenarios such as ours? Would it be ok, for instance, if we had a `static` field defined somewhere where we declared a `DefaultAzureCredential` object only once, and reused that same field throughout the entire application, or if we registered?

I've seen this other issue but it wasn't super conclusive to me. It gives the impression that sharing should be ok, but I wanted to confirm it 100% before applying it to our projects and recommending it as a best practice in all of our code.
- https://github.com/Azure/azure-sdk-for-net/issues/36969

### Environment

N/A

**Comment by christothes** [comment]
Hi @julealgon - 
Yes, it is recommended to use a singleton instance of a credential across multiple service clients, assuming they will all be successful with the same credential type. Using a distinct instance per service client won't cause any problems. However, constructing a new instance each time a credential is used to fetch a token will cause problems such as not utilizing the token cache properly.

**Comment by julealgon** [comment]
Perfect. Thank you for confirming this @christothes . I'll proceed to share it when we can then.

My suggestion would be to document this fact somewhere in the basic documentation for the library so other devs can benefit from it. But will leave it up to you on that.

**Comment by christothes** [comment]
https://github.com/dotnet/docs/issues/42290
