### ISSUE TITLE
Unable to get list of reservationOrder or reservationOrder details

### ISSUE THREAD

**Issue by thegreatdane6** [Azure/azure-sdk-for-net#4571]
Hello all,

- On requesting a list containing all my reservation orders, i get an empty list. 
- On requesting details about a specific reservation order, the sdk throws an forbidden exception.
- But on requesting a list containing all the reservations in the specific reservation order the expected data is returned. 

At first i thought this is a problem with the SDK, so i tried to call the Api without the SDK (https://docs.microsoft.com/en-us/rest/api/reserved-vm-instances/reservationorder), but it shows the same behavior.
I am accessing the tenant with a service principal with has read rights to the subscription containing the reservation order and of course has granted access to the management Api. I also counterchecked in the portal, the service principal has read permission on the reservations.

Here's a sample of the code i am executing: 
![errorreservationorder](https://user-images.githubusercontent.com/12907164/42990804-0c84daec-8c04-11e8-8a48-9819ae24e061.PNG)

And here is the response i got from calling the Api (removed the Id's):
![error_response](https://user-images.githubusercontent.com/12907164/42990450-f2d3bcf4-8c02-11e8-8097-3c3401eaa8d0.PNG)

I again counterchecked in the portal and found the default reader role's permission. The permission includes the Microsoft.Capacity/reservationOrders/read action. So I cannot explain this behavior to myself anymore.

Do I need to assign more than '*/read' rights to the service principal, or am I missing out on something different?

Thanks in advance
Dane Dahlem

**Comment by thegreatdane6** [comment]
Anyone?

**Comment by shahabhijeet** [comment]
@thegreatdane6 seems like an issue with Fluent library. If yes I have opened an issue in the right repo
https://github.com/Azure/azure-libraries-for-net/issues/454

**Comment by jsquire** [comment]
Closing this out as there has been no recent engagement.  Please feel free to reopen or file a new issue if this remains a problem with the current version of the library.

**Comment by thegreatdane6** [comment]
I am unable to check whether the issue still exists.
