### ISSUE TITLE
[QUERY] Azure SQL Database 2014-04-01 APIs will be retired on 31 October 2025

### ISSUE THREAD

**Issue by Tim-2020** [Azure/azure-sdk-for-net#45727]
### Library name and version

Microsoft.Azure.Management.Sql

### Query/Question

Hello,
Recently we've received a e-mail from Microsoft that "Azure SQL Database 2014-04-01 APIs will be retired on 31 October 2025". 
We are not using this API directly, but we use Microsoft.Azure.Management.Sql library. 

I've found that the latest version of your library uses API that will be retired.
https://github.com/Azure/azure-sdk-for-net/blob/Azure.ResourceManager.Sql_1.3.0-beta.6/sdk/sqlmanagement/Microsoft.Azure.Management.Sql/src/Generated/DatabasesOperations.cs

So the questions:
Is there any work to change api version? 
When should I expect the release of the library which supports newer API?

Thanks in advance!

### Environment

.net 8.0

**Comment by jsquire** [comment]
Hi @Tim-2020.  Thanks for reaching out and we regret that you're experiencing difficulties.  As indicated on its [NuGet page](https://www.nuget.org/packages/Microsoft.Azure.Management.Sql/3.1.0-preview), the `Microsoft.Azure.Management.Sql` reached end-of-life in September 2023 and is no longer published nor supported by Microsoft.

We strongly urge updating to the current generation package, [Azure.ResourceManager.Sql](https://www.nuget.org/packages/Azure.ResourceManager.Sql/).

**Comment by Tim-2020** [comment]
Hello @jsquire 
Thanks for your answer!

And what about Azure.ResourceManager.Sql package? Does it contain correct API version? If no, when it is planned to use correct one?

Thanks in advance!
