### ISSUE TITLE
AppAuthentication for Azure B2C

### ISSUE THREAD

**Issue by phatcher** [Azure/azure-sdk-for-net#4572]
As Azure B2C now supports client credential flow, is using AppAuthentication a supported scenario for obtaining a token.

Also, I'd like to use KeyVault to rotate client secrets for Azure B2C applications, should I roll my own or is this on your roadmap?

**Comment by phatcher** [comment]
@varunsh-msft Looks like the second one has already been asked on SO - https://stackoverflow.com/questions/44822092/how-to-secure-azure-client-id-and-secret-without-using-app-settings-of-app-servi

**Comment by jsquire** [comment]
Closing this out as there has been no recent engagement.  Please feel free to reopen or file a new issue if this remains a problem with the current version of the library.
