### ISSUE TITLE
System.MissingMethodException: Method not found: 'Void Microsoft.Azure.KeyVault.KeyVaultClient..ctor(AuthenticationCallback, System.Net.Http.HttpClient)'.

### ISSUE THREAD

**Issue by samsil** [Azure/azure-sdk-for-net#4573]
**Context**
-I am trying to create KeyVaultClient instance from my "Web performance and Load Test project"
-.NET Framework 4.7
-using the latest KeyVault and KeyVault.WebKey (tried with 2.3.2 keyvault and 2.07 webkey as well)

The interesting thing is the same code with exactly the same dependencies works from other application.  The test project uses an old format csproj though, not sure whether it is related to the problem. Please let me know if any other information is required.

**Repro**
Create a simple Web performance and Load Test project. Instantiate KeyVaultClient from code (I just called from a webtest). You need to add packages for Azure.KeyVault and System.Net.Http and their dependencies.

**Comment by samsil** [comment]
I Just found out, If I downgrade the System.Net.Http to 4.0.0.0 from 4.3.3 Then this issue seems resolved for the repro project. But I need to use 4.3.3 for some of my other libraries. So I think not working with 4.3.3 should still be considered as an issue?

**Comment by sribs** [comment]
Do we have any update with regards to this ? The issue is still in 4.3.4 as well.

**Comment by Trycoder** [comment]
I have the same issue. It was working fine for a long time.
But lately, it has stopped working. I cannot downgrade the System.Net.Http  dll.

Does anyone know the solution

**Comment by heaths** [comment]
These packages are deprecated. Please update to Azure.Security.KeyVault.* packages, which have migration guides available next to our README.md files as MigrationGuide.md.
