### ISSUE TITLE
Nuget Package requires 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version>=3.14.2.11, but fails if a higher version is there

### ISSUE THREAD

**Issue by healthycola** [Azure/azure-sdk-for-net#4574]
In the nuget package requirements, it says it requires Microsoft.IdentityModel.Clients.ActiveDirectory **>=** 3.14.2, and we have 3.19.8 (current latest), and it fails to use that (and looks for 3.14.2 instead).

We're seeing this exception:
Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.14.2.11, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

**Comment by shahabhijeet** [comment]
@healthycola can you provide a detailed repro steps that I can use to reproduce this error.
Give me the exact version you are using and also the target framework your app is targeting.

**Comment by ksauce** [comment]
This is a repro for me as well.  The visual studio build environment locally is using the latest version.  Will there be an update for this nuget otherwise I can't use this with a certificate authentication?

**Comment by mattleibow** [comment]
There is also another issue here. The same one, but manifests in another way.

The version of AD (3.14.2.11) is broken on iOS - there is a type missing in the platform dll. The fix appears to be to upgrade AD to 4.3.0. But, then this issue rears it's ugly head.

**Comment by samuthrakumar** [comment]
I am hitting the same problem if I use >3.14.2.11.. I am getting below exception when I build Azure Key vault using certificate authentication. It is trying to load Microsoft.IdentityModel.Clients.ActiveDirectory.Platform.dll which is missing in the package > 3.14

   Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory.Platform, Version=3.14.2.11, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.

Below is the code I am using.

                keyVaultConfigBuilder.AddAzureKeyVault(
                    vault: vault,
                    clientId: client,
                    certificate: certificate);

                var keyVaultConfig = keyVaultConfigBuilder.Build();

**Comment by Muthukumar230195** [comment]
@samuthrakumar that exactly what I need.
Did you found any solution for your issue

**Comment by anilkumar1998** [comment]
> @samuthrakumar that exactly what I need.
> Did you found any solution for your issue

I was using 5.04 version of Microsoft.IdentityModel.Clients.ActiveDirectory and faced the same issue. I downgraded to 3.19.8 and packages depending on Microsoft.IdentityModel.Clients.ActiveDirectory to appropriate version and it worked for me.

**Comment by Muthukumar230195** [comment]
@anilkumar1998  thanks for the  reply. i have fixed this bug
