### ISSUE TITLE
Why, just why?

### ISSUE THREAD

**Issue by vinceweeks-69** [Azure/azure-sdk-for-net#45774]
### Type of issue

Missing information

### Description

[Enter feedback here]
please define the use of the parameter refreshToken - Why would you ever call a function called GetAccessToken that would not ever return a valid token? Why would there ever be a need for a parameter that asks for a refresh? Doesn't it make way more sense for this function to ALWAYS return something useable? Why would you ever need a parameter called refreshToken? Don't you think that if you're going to do something like that, you ought to explain yourself? I do. Better yet, change the function so that it does what it says without any ambiguity.

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.services.appauthentication.azureservicetokenprovider.getaccesstokenasync?view=azure-dotnet-legacy

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Services.AppAuthentication/AzureServiceTokenProvider.xml

### Document Version Independent Id

ada30632-2508-a4ef-17a8-7a44bc820930

### Article author

@azure-sdk

### Metadata

* ID: 40552281-44f9-b086-61f5-423b2bfcf0b2

**Comment by jsquire** [comment]
Hi @vinceweeks-69.  Thanks for reaching out and we regret that you're experiencing difficulties.  The `Microsoft.Azure.Services.AppAuthentication` package reached end-of-life in March 2023 and is no longer published nor supported by Microsoft.  It is strongly advised that you not use this package, as it has known vulnerabilities that will not be patched.

As the library is unsupported, the Azure SDK team is unable to assist with this inquiry.
