### ISSUE TITLE
[BUG] Delegation SAS lifetime exceeds 7 days exception message needs improvement

### ISSUE THREAD

**Issue by erdembayar** [Azure/azure-sdk-for-net#45789]
### Library name and version

Azure.Storage.Blobs

### Describe the bug

If I pass `endofAccess` more than 7 days in the future then it fails.

But error message is too vague, it took me a while to understand it was related to delegation SAS token lifetime. Why couldn't just explicitly say SAS lifetime is not valid. 
It was not really XML related issue, maybe XML schema is just complaining.

```
<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidXmlNodeValue</Code><Message>The value for one of the XML nodes is not in the correct format.
RequestId:ffffffff-ffff-ffff-ffff-fffff0000000
Time:2024-08-31T21:08:58.0021883Z</Message><XmlNodeName>2024-09-07T21:08:59Z</XmlNodeName><XmlNodeValue>2024-09-07T21:08:59Z</XmlNodeValue></Error>
```

        private BlobSasBuilder CreateSasBuilderWithPermission(FileUriPermissions permissions, DateTimeOffset endOfAccess)
        {
            var sasBuilder = new BlobSasBuilder
            {
                BlobContainerName = _blob.BlobContainerName,
                BlobName = _blob.Name,
                Resource = "b",
                StartsOn = DateTimeOffset.UtcNow.AddMinutes(-5),
                ExpiresOn = endOfAccess,
            };
            sasBuilder.SetPermissions(CloudWrapperHelpers.GetSdkSharedAccessPermissions(permissions));

            return sasBuilder;
        }

        private async Task<string> GenerateDelegationSasAsync(BlobSasBuilder sasBuilder)
        {
            UserDelegationKey userDelegationKey = (await _client.GetUserDelegationKeyAsync(sasBuilder.StartsOn, sasBuilder.ExpiresOn)).Value;
            BlobUriBuilder blobUriBuilder = new BlobUriBuilder(_blob.Uri)
            {
                Sas = sasBuilder.ToSasQueryParameters(userDelegationKey, _blob.AccountName),
            };
            return blobUriBuilder.ToUri().Query;
        }

### Expected behavior

Explicitly say SAS lifetime is valid, it have to be within 7 days since start.

### Actual behavior

But error message is too vague, it took me a while to understand it was related to delegation SAS token lifetime. Why couldn't just explicitly say SAS lifetime is not valid.

```
<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidXmlNodeValue</Code><Message>The value for one of the XML nodes is not in the correct format.
RequestId:ffffffff-ffff-ffff-ffff-fffff0000000
Time:2024-08-31T21:08:58.0021883Z</Message><XmlNodeName>2024-09-07T21:08:59Z</XmlNodeName><XmlNodeValue>2024-09-07T21:08:59Z</XmlNodeValue></Error>
```

### Reproduction Steps

See above C# code

### Environment

Azure sdk C#

**Comment by nickliu-msft** [comment]
Hi @erdembayar, I have a few clarifying questions for you:

1. So this error only occurs when BlobSasBuilder.ExpiresOn field is populated to be more than 7 days in the future?
2. What are you doing with this BlobSasBuilder that you are setting the ExpiresOn field for? Are you just using it to simply retrieve the uri containing the user delegation sas?

**Comment by nickliu-msft** [comment]
Hi @erdembayar, it seems like the 7-day expiration time for User Delegation SAS is intended due to [this](https://learn.microsoft.com/en-us/azure/storage/common/sas-expiration-policy?tabs=azure-portal#configure-a-sas-expiration-policy)

As for the unhelpful error message, as the Azure Storage SDK we have no control over this since we just return whatever the service returns. We actually aren't allowed to modify the error output on our end.

If you still have concerns, please reach out to the Azure Storage service team. Let me know if this answers your question.

**Comment by erdembayar** [comment]
> Hi @erdembayar, it seems like the 7-day expiration time limit for User Delegation SAS is intended due to [this](https://learn.microsoft.com/en-us/azure/storage/common/sas-expiration-policy?tabs=azure-portal#configure-a-sas-expiration-policy)

I'm already aware of it, I'm from internal team.

> If you still have concerns, please reach out to the Azure Storage service team. Let me know if this answers your question.

How to contact them?

**Comment by nickliu-msft** [comment]
@erdembayar I believe you have to file a Azure Support Request

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
