### ISSUE TITLE
No HostNameSslStates returned

### ISSUE THREAD

**Issue by rogerskk** [Azure/azure-sdk-for-net#458]
I am using the following code to retrieve my Azure WebSite information:
  WebSiteManagementClient client = new WebSiteManagementClient(cred);
                var website = client.WebSites.Get(WebSpaceName, SiteName, new WebSiteGetParameters());
                var hostnamesssl = website.WebSite.HostNameSslStates;

The hostnamesssl variable returns 0 records, even though I have several Ssl bindings for the website I'm getting the info for.  website.WebSite.HostNames returns all of my domains, but I am not getting the Ssl bindings.<p><a href="https://github.com/Azure/azure-sdk-for-net/issues/458">https://github.com/Azure/azure-sdk-for-net/issues/458</a></p>

**Comment by shahabhijeet** [comment]
@rogerskk please reopen if this is an issue.
