### ISSUE TITLE
Method not found: 'System.String[] System.String.Split(Char, System.StringSplitOptions)' after upgrading to v1.12. Is Azure.Identity no longer compatible with .Net Framework 4.x?

### ISSUE THREAD

**Issue by pseudosma** [Azure/azure-sdk-for-net#45827]
### Library name and version

Azure.Identity 1.12

### Query/Question

Hello,
I have an app running on .Net Framework 4.8. It had Azure.Identity 1.7, and I just upgraded to the latest version - 1.12.
When calling this block of code that previously worked, I am now seeing an error when hitting UsernamePasswordCredential.GetToken:

```vb
         Dim username As String = mConnection.AuthLogin.Value
         Dim password As String = mConnection.AuthSecret.Value
         Dim tenant As String = mConnection.CustomField1.Value
         Dim clientId As String = mConnection.AuthSecurityToken.Value
         Dim scopes As String() = {"https://analysis.windows.net/powerbi/api/.default"}

         ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12

         Dim credential As New UsernamePasswordCredential(username, password, tenant, clientId)
         Dim context As New TokenRequestContext(scopes)
         Dim authResult As AccessToken = credential.GetToken(context)
```
         
The error I see is `Method not found: 'System.String[] System.String.Split(Char, System.StringSplitOptions)`
Stack Trace:

>    at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage, Boolean isCredentialUnavailable)
>    at Azure.Identity.UsernamePasswordCredential.<AuthenticateImplAsync>d__31.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Azure.Identity.UsernamePasswordCredential.<GetTokenImplAsync>d__32.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage, Boolean isCredentialUnavailable)
>    at Azure.Identity.UsernamePasswordCredential.<GetTokenImplAsync>d__32.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Azure.Identity.UsernamePasswordCredential.GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken)

I did need to update some of the binding redirects to get the latest version to run (System.Runtime.CompilerServices.Unsafe updated to v6.0.0 along with the update to Azure.Identity 1.12, so I needed to redirect it to use System.Runtime 4.0.0).

According to the docs, that overload of String.Split isn't supported in the legacy .Net Framework https://learn.microsoft.com/en-us/dotnet/api/system.string.split?view=net-8.0#system-string-split(system-char-system-stringsplitoptions) .

So the question I have, is Azure.Identity still compatible with .Net Framework 4.x? The official nuget page still shows net48 as a valid framework: https://www.nuget.org/packages/Azure.Identity#supportedframeworks-body-tab.
If so, is there a viable work-around?

Thanks!

### Environment

.Net Framework 4.8

**Comment by christothes** [comment]
Hi @pseudosma - 
This is strange considering that Azure.Identity has used this method since version 1.2.0. Could there be something else about your application that changed that is causing this? I'm curious why you needed to update assembly binding redirects also - perhaps that is related?

**Comment by pseudosma** [comment]
> Hi @pseudosma - This is strange considering that Azure.Identity has used this method since version 1.2.0. Could there be something else about your application that changed that is causing this? I'm curious why you needed to update assembly binding redirects also - perhaps that is related?

Perhaps, but I have yet to find it.

The binding redirects were related to another upgrade I did on the same project. I use Flurl, and I upgraded that to version 4.0.0 first. That updates System.Text.Json >= 8.0.0.
Azure.Identity depends on version , so the binding redirects were to tell the app to use version 8 instead (couldn't bind automatically cause the major version jump).

```
      <dependentAssembly>
        <assemblyIdentity name="System.Text.Json" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-32767.32767.32767.32767" newVersion="8.0.0.4" />
      </dependentAssembly>
```

One or both of these has a dependency to System.Runtime.CompilerServices.Unsafe.6.0.0, which attempts to map to System.Runtime 6, which it can't use since it's net48, so there's one to redirect anything looking for System.Runtime 6 to get 4 instead:

```
      <dependentAssembly xmlns="urn:schemas-microsoft-com:asm.v1">
        <assemblyIdentity name="System.Runtime" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="6.0.0.0" newVersion="4.0.0.0" />
      </dependentAssembly>
```

**Comment by pseudosma** [comment]
Interestingly, when I try this code in a different environment ([dotNetFiddle running under net472](http://dotnetfiddle.net/bb3HdX)) I get this message from the linter:

`Reference required to assembly 'netstandard, version=2.0.0.0'.... containing the type 'CancellationToken'`

I don't see this in Visual Studio, just errors during runtime. Of course this works out of the box for higher versions such as .Net6 and .Net8 in dotNetFiddle.

 I'm curious if adding this to my web.config would do the trick.

```
<system.web>
  <compilation debug="true" targetFramework="4.8" >
    <assemblies>
      <add assembly="netstandard, Version=2.0.0.0, Culture=neutral, 
            PublicKeyToken=cc7b13ffcd2ddd51"/>
    </assemblies>
  </compilation>
  <httpRuntime targetFramework="4.8" />
```

**Comment by pseudosma** [comment]
Ok, including that extra assembly did fix my problem.

I never had this directly reference before in the web.config until now, so I imagine that the reason it worked on 1.7 was either because something else that I've since upgraded included that assembly but dropped it in their later versions, or the particular code path that it hit in the older version of UsernamePasswordCredential.GetToken didn't touch an instance of that method.

This requirement could be mentioned in the [trouble shooting guide](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/TROUBLESHOOTING.md).
