### ISSUE TITLE
Enable use-write-core for all the projects

### ISSUE THREAD

**Issue by pshao25** [Azure/azure-sdk-for-net#45828]
We need to enable `use-write-core` for all the projects in azure-sdk-for-net. Let's start from MPG first. Steps are:
1. Go to `autorest.md` and add `use-write-core: true`.
2. Run `dotnet build /t:GenerateCode` to regenerated. All the serialization file of model should have a new method called `JsonModelWriteCore`.
3. Fix test recording:
3.1 Restore test recording by https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/resourcemanager/Azure.ResourceManager/docs/TestGuide.md#test-proxy
3.2 Fix recording. Currently known issue is we should remove empty tags, i.e.,  `tags: {}`, unless it is touched by some call like `tags.clear()`, for this touch case, we still need a `tags: {}`.
3.3 Run test by Playback mode.
3.4 If everything OK, push the recording. Otherwise reach to me.
4. Run `exportAPI.ps1`
5. Send out PR with all these changes. An example PR will be like https://github.com/Azure/azure-sdk-for-net/pull/45829

**Comment by live1206** [comment]
> 3.2 Fix recording. Currently known issue is we should remove tags: []

@pshao25 Is there a pattern how we should remove this or a script to execute?
