### ISSUE TITLE
[BUG] ResourceManager.MachineLearning parameter validation error

### ISSUE THREAD

**Issue by mike-menaker** [Azure/azure-sdk-for-net#45884]
### Library name and version

Azure.ResourceManager.MachineLearning 1.2.0

### Describe the bug

A number of the *Collection, GetAll calls doesn't deserialize the response correctly.

After fetching the registry:
```
var machineLearningRegistryResourceId = MachineLearningRegistryResource.CreateResourceIdentifier(subscriptionId, resourceGroupName, registryName);
var machineLearningRegistry = client.GetMachineLearningRegistryResource(machineLearningRegistryResourceId);
```

I have tried:
```
var environmentCollection = machineLearningRegistry.GetMachineLearningRegistryEnvironmentContainers();
var environments = await environmentCollection.GetAllAsync().ToListAsync();
```
and
```
var dataCollection = machineLearningRegistry.GetMachineLearningRegistryDataContainers();
var dataResources = await dataCollection.GetAllAsync().ToListAsync();
```

However, I'm running into exceptions nested into the library when it deserializes the response. For some reason the returned type is not namespaced, for instance, its just "environments" instead of something like "Microsoft.MachineLearningServices/registries/environments".

The exception pops up in the ResourceType constructor:
![image](https://github.com/user-attachments/assets/fe11591d-cc16-4780-a940-06c5aa935639)

### Expected behavior

I'm able to get a list of resources from a collection object.

### Actual behavior

Exceptions.

### Reproduction Steps

Get collection and try to get resource:
```
var environmentCollection = machineLearningRegistry.GetMachineLearningRegistryEnvironmentContainers();
var environments = await environmentCollection.GetAllAsync().ToListAsync();
```
and
```
var dataCollection = machineLearningRegistry.GetMachineLearningRegistryDataContainers();
var dataResources = await dataCollection.GetAllAsync().ToListAsync();
```

### Environment

.NET SDK:
 Version:           8.0.304
 Commit:            352dc5a01f
 Workload version:  8.0.300-manifests.113cb230
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.304\

.NET workloads installed:
 [aspire]
   Installation Source: VS 17.10.35201.131
   Manifest Version:    8.1.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.1.0\WorkloadManifest.json
   Install Type:        FileBased

Host:
  Version:      8.0.8
  Architecture: x64
  Commit:       08338fcaa5

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  6.0.321 [C:\Program Files\dotnet\sdk]
  6.0.425 [C:\Program Files\dotnet\sdk]
  8.0.304 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi @mike-menaker , we are applying a fix to this issue, will relase a new version once the PR is merged.

**Comment by mike-menaker** [comment]
Thank you! I have verified that the API is working as expected.
