### ISSUE TITLE
mrsam

### ISSUE THREAD

**Issue by ruby4406** [Azure/azure-sdk-for-net#45897]
### Type of issue

Code doesn't work

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.datafactory.models.amazonmwslinkedservice?view=azure-dotnet&wt.mc_id=searchAPI_azureportal_inproduct_rmskilling&sessionId=c5f81fd8cdc64aa684a3ed9338016f96

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.ResourceManager.DataFactory.Models/AmazonMwsLinkedService.xml

### Document Version Independent Id

fbe8e8ac-a000-061d-dbb0-313861e76a66

### Article author

@azure-sdk

### Metadata

* ID: 94a13746-57f3-16a3-5791-e13d7f20095e 
* Service: **azure**

**Comment by jsquire** [comment]
Hi @ruby4406.  Thanks for reaching out and we regret that you're experiencing difficulties.  Unfortunately, there's not enough context in this issue to understand what code you're referring to nor in what way it doesn't work.

Please provide a code snippet with an example that demonstrates repro and the exact error message + stack trace that you're seeing.

**Comment by jsquire** [comment]
Closing this as not actionable.  If you still require assistance, please provide the requested information in a new issue.
