### ISSUE TITLE
`ResourceType` should not throw exception in its ctor

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/azure-sdk-for-net#45900]
Currently now the implementation of `ResourceIdentifier` has been changed and this type takes any input without throwing an exception.
I think `ResourceType` should follow the same pattern to make it accept anything as an input, and we could throw exceptions when some one trying to access its properties.

**Comment by ArcturusZhang** [comment]
First reported in https://github.com/Azure/azure-sdk-for-net/issues/45884

**Comment by ArthurMa1978** [comment]
#47260
