### ISSUE TITLE
problem display datetime of Azure cosmosDB SQL

### ISSUE THREAD

**Issue by loongdefect** [Azure/azure-sdk-for-net#4591]
Hi all,
I have problem display format of datetime.
View in portal is format "2018-07-01T15:19:10.0000000Z". When I using asp.net core get document, date time format is "07/01/2018 15:19:10".
How to date time format like when view in portal.

![azure](https://user-images.githubusercontent.com/8251888/43309235-6b417e0a-91ae-11e8-9e31-c07a45c6a80f.PNG)
![code](https://user-images.githubusercontent.com/8251888/43309236-6b78081c-91ae-11e8-9145-81254bdf56ad.PNG)

**Comment by shahabhijeet** [comment]
@loongdefect this repo is for reporting issue related to .NET SDK.
Are you having this issue with the cosmosDB sdk, if yes can you provide the name/version of the SDK that you are using.

**Comment by loongdefect** [comment]
Hi @shahabhijeet 
I think this problem of  .NET SDK.
On Portal is view correct.
This issue is close, because I don't working with CosmosDB.

Thank,
