### ISSUE TITLE
Cognitive Services Face API - FaceList Create Method Signature

### ISSUE THREAD

**Issue by lordcheeto** [Azure/azure-sdk-for-net#4594]
Using the Microsoft.Azure.CognitiveServices.Vision.Face 2.0.0-preview nuget package, there is an error in the `FaceListOperationsExtensions.CreateAsync` and corresponding `IFaceListOperations.CreateWithHttpMessagesAsync` method signatures:

```csharp
public static Task CreateAsync(this IFaceListOperations operations, string faceListId, string name = null, string userData = null, CancellationToken cancellationToken = default(CancellationToken));

Task<HttpOperationResponse> CreateWithHttpMessagesAsync(string faceListId, string name = null, string userData = null, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
```

In both cases, the method signature indicates that `name` is optional, when [the API specification indicates it's required](https://westus.dev.cognitive.microsoft.com/docs/services/563879b61984550e40cbbe8d/operations/563879b61984550f3039524b). As such, an `APIErrorException` is raised with a bad request status code if called without specifying the name.

JSON response:

```json
{"error":{"code":"BadArgument","message":"Request body is invalid."}}
```

I'm unable to pinpoint the issue in this repo to submit a pull request, and can't find any recent changes that would explain this behavior in the 2.0.0-preview nuget package, which is relatively new (2018-07-09T23:17:20Z).

**Comment by lebronJ** [comment]
Thanks @lordcheeto for your feedback, yes this is an error since name is actually required. Let me track this and fix it ASAP.

**Comment by jsquire** [comment]
Closing, as the related issue has been closed.  Please feel free to reopen if you feel that further discussion is needed.
