### ISSUE TITLE
Unauthorized access when trying to connect to cognitive services

### ISSUE THREAD

**Issue by MisinformedDNA** [Azure/azure-sdk-for-net#4595]
This is the code I was using and getting an "Unauthorized" response:

```csharp
var vision = new ComputerVisionAPI(new ApiKeyServiceClientCredentials(key));
var response = await vision.GenerateThumbnailWithHttpMessagesAsync(50, 50, imageUrl, smartCropping: true);
```

Per https://github.com/Microsoft/vs-tools-for-ai/issues/15#issuecomment-391549075, I need to set the `AzureRegion`. 

This code works:

```csharp
var vision = new ComputerVisionAPI(new ApiKeyServiceClientCredentials(key));
vision.AzureRegion = AzureRegions.Westcentralus;
var response = await vision.GenerateThumbnailWithHttpMessagesAsync(50, 50, imageUrl, smartCropping: true);
```

It seems like `AzureRegion` is required to make a successful call, so why is it not in the `ComputerVisionAPI` constructors?

**Comment by ChrisHMSFT** [comment]
Closing this ticket since this has been fixed with the new SDK which will use the endpoint parameter

Thanks,
Chris
