### ISSUE TITLE
[BUG] DesktopVirtualization SessionHost PATCH (Update) Calls Fail with Empty Resource ID

### ISSUE THREAD

**Issue by alec-baird** [Azure/azure-sdk-for-net#45976]
### Library name and version

Azure.DesktopVirtualization (Latest Version)

### Describe the bug

We recently had an RCA on an issue that happened in our service involving the .NET SDK, We had an issue with the .NET SDK Patch Session Host call trying to parse an Arm Path into a resource identifier, but our service allows this field to be null/empty. Notes are below:

When using the dot Net sdk to call patch on Session Hosts after they were created without an ArmPath, the dot Net sdk then tried to parse the Arm Path into a Resource Identifier. From my understanding the Resource identifier type does some validation to ensure that it is a valid Arm Path, which we were not returning.
 
This resulted in patch calls throwing the following exception from the dot Net SDK: 'Value cannot be an empty string. (Parameter 'resourceId').'

Our service uses IMDS (https://learn.microsoft.com/en-us/azure/virtual-machines/instance-metadata-service?tabs=windows) to populate these values, which customers can block, disable, or if they are on-prem/hybrid they won't have them at all. Whem making identical calls in Powershell and Portal, the calls succeed because there is no attempt to cast to a resource identifier.

### Expected behavior

Successful calls without requiring arm path/resource identifier

### Actual behavior

Failed calls: This resulted in patch calls throwing the following exception from the dot Net SDK: 'Value cannot be an empty string. (Parameter 'resourceId').'

### Reproduction Steps

Call Update on a SessionHost without a resource identifier present.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
