### ISSUE TITLE
[BUG] Creation of ImageReference results in NullReferenceException

### ISSUE THREAD

**Issue by DavidStorey** [Azure/azure-sdk-for-net#45989]
### Library name and version

Microsoft.Azure.Batch (v 16.3.0)

### Describe the bug

Creation of an Azure Batch Pool programmatically fails when the setup of VirtualMachineConfiguration is created.

Calling this line fails in v 16.3.0 and is successful in v 16.2.0

return new ImageReference(
            "0001-com-ubuntu-server-jammy",
            "canonical",
            "22_04-lts",
            "latest");

Confirmed the image is available.

### Expected behavior

ImageReference successfully created

### Actual behavior

NullReferenceException raised here

Microsoft.Azure.Batch.dll!Microsoft.Azure.Batch.ImageReference.Offer.set(string value)
Microsoft.Azure.Batch.dll!Microsoft.Azure.Batch.ImageReference.ImageReference(string offer, string publisher, string sku, string version)

### Reproduction Steps

Creation of an Azure Batch Pool programmatically fails when the setup of VirtualMachineConfiguration is created.

Calling this line fails in v 16.3.0 and is successful in v 16.2.0

return new ImageReference(
            "0001-com-ubuntu-server-jammy",
            "canonical",
            "22_04-lts",
            "latest");

Confirmed the image is available.

### Environment

Azure Batch pool created via a C# Azure Function

**Comment by TovTyvold** [comment]
Having the same issue on a .net6.0 project, breaking change.

**Comment by wiboris** [comment]
Fix should be in shortly

**Comment by wiboris** [comment]
16.3.1 uploaded with fix  https://www.nuget.org/packages/Microsoft.Azure.Batch

**Comment by wiboris** [comment]
fixed with 16.3.1
