### ISSUE TITLE
CognitiveService-Vision-Face test project failed to build for missing XUnit

### ISSUE THREAD

**Issue by lebronJ** [Azure/azure-sdk-for-net#4600]
I am using the latest VS 2017 (Microsoft VS Enterprise 2017 Version 15.7.5) but failed to build [`psSdkJson6/src/SDKs/CognitiveServices/dataPlane/Vision/Face/Face.Tests`](https://github.com/Azure/azure-sdk-for-net/tree/psSdkJson6/src/SDKs/CognitiveServices/dataPlane/Vision/Face/Face.Tests) with below error message:

`
2>FaceVerificationTests.cs(7,7,7,12): error CS0246: The type or namespace name 'Xunit' could not be found (are you missing a using directive or an assembly reference?)
2>FaceDetectionTests.cs(13,10,13,14): error CS0246: The type or namespace name 'FactAttribute' could not be found (are you missing a using directive or an assembly reference?)
2>FaceDetectionTests.cs(13,10,13,14): error CS0246: The type or namespace name 'Fact' could not be found (are you missing a using directive or an assembly reference?)
...`

I used to be able to build this test project when I updated Face SDK 6 month ago. But for now, I have to build this project by installing `xunit` and `xunit.runner.visualstudio` manually.

`<PackageReference Include="xunit" Version="2.4.0" />`
`<PackageReference Include="xunit.runner.visualstudio" Version="2.4.0" />`

**Comment by ChrisHMSFT** [comment]
Closing since this issue has been fixed.

Thanks,
Chris
