### ISSUE TITLE
[BUG] Inconsistent types between creating virtualMachineConfig with .Protocol.Models and BatchClient.PoolOperations.CreatePool

### ISSUE THREAD

**Issue by TovTyvold** [Azure/azure-sdk-for-net#46001]
### Library name and version

Microsoft.Azure.Batch 16.3.0

### Describe the bug

Using the Microsoft.Azure.Batch.Protocols.Models namespace instead of Microsoft.Azure.Batch. 
Creating the imagereference and the virtualMachineConfig is ok, but there is no CreatePool in Microsoft.Azure.Batch.PoolOperations that take in a virtualMachineConfig from the new namespace. 

### Expected behavior

Expected there to be a Microsoft.Azure.Batch.PoolOperations.CreatePool that could take in a virtualMachineConfig from the Microsoft.Azure.Batch.Protocols.Models namespace.

### Actual behavior

No overload to use. 

### Reproduction Steps

using Microsoft.Azure.Batch.Protocols.Models;
Initialize a new ImageReference() with either sharedImageGalleryId or virtualMachineImageId and a ContainerConfiguration
Add the imageReference and ContainerConfiguration to a new initialization of a VirtualMachineConfiguration.

Initialize a Microsoft.Azure.Batch.BatchClient using BatchClient.Open(BatchTokenCredentials credentials), lets call the symbol "client"

With this setup, there is no way to create a new pool.

 

### Environment

Azure Batch pool created via a .NET 6.0 Sdk.Web project.

**Comment by wiboris** [comment]
I believe the root of your issues came from the fact there was a bug with ImageReference which got fixed with the latest release 16.3.1.
