### ISSUE TITLE
[BUG] CreateReceiveLinkException (Unauthorized access) - even though RBAC on topic subscription was configured

### ISSUE THREAD

**Issue by MarcusKohnert** [Azure/azure-sdk-for-net#46002]
### Library name and version

Azure.Messaging.ServiceBus 7.18.0

### Describe the bug

I want to use RBAC to enable clients to listen to a ServiceBus Topic Subscription.
I've assigned the `Azure Service Bus Data Receiver` (and Sender) role to an Entra ID Group on the scope of the ServiceBus Topic Subscription. ("Development Team" is the name of the Entra ID Group - see picture)
I'm myself member of the Entra ID Group.

![image](https://github.com/user-attachments/assets/4a4aabcb-8d97-48c6-8d71-9d4c3b3da242)

I'm registering the clients via Microsoft.Extensions.Azure 1.7.5.

```csharp
services.AddAzureClients(clientsBuilder =>
{
    var subscriptionOptions = this.Configuration.GetSection("ServiceBus").Get<SubscriptionOptions>()!;

    clientsBuilder
        .AddServiceBusClientWithNamespace($"{subscriptionOptions.Name}.servicebus.windows.net")
        .ConfigureOptions(options =>
        {
            options.TransportType = ServiceBusTransportType.AmqpTcp;
        });

    clientsBuilder
        .AddClient<ServiceBusProcessor, ServiceBusProcessorOptions>((options, _, provider) =>
        {
            options.MaxConcurrentCalls = subscriptionOptions.MaxConcurrency;
            options.AutoCompleteMessages = false;
            options.PrefetchCount = subscriptionOptions.PrefetchCount;
            options.ReceiveMode = ServiceBusReceiveMode.PeekLock;

            return provider
                .GetRequiredService<ServiceBusClient>()
                .CreateProcessor(
                    subscriptionOptions.TopicName,
                    subscriptionOptions.SubscriptionName,
                    options);
        });

            clientsBuilder.UseCredential(
                new DefaultAzureCredential(
                    new DefaultAzureCredentialOptions
                    {
                        VisualStudioTenantId = "[redacted]",
                        Diagnostics =
                        {
                            IsAccountIdentifierLoggingEnabled = true,
                            IsLoggingEnabled = true
                        }
                    }));
});
```

### Expected behavior

A local develpoment client aka "Visual Studio started process", is able to receive messages via DefaultAzureCredentials via VisualStudioCredentials.

### Actual behavior

A token is successfully received:
`DefaultAzureCredential.GetToken succeeded. Scopes: [ https://servicebus.azure.net/.default ] ParentRequestId: ExpiresOn: 2024-09-17T12:01:25.1849635+00:00`

⚠️ But right afterwards a CreateReceiveLinkException is thrown and message processing does not happen.

```
Microsoft.Azure.Amqp.AmqpException: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'sb://[redacted].servicebus.windows.net/[redacted]topic/subscriptions/[redacted]subscription'. TrackingId:70fbf78f5915496fba85866a3500aeb1_G28, SystemTracker:gateway10, Timestamp:2024-09-17T11:03:56
   at Microsoft.Azure.Amqp.ExceptionDispatcher.Throw(Exception exception)
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.OpenAsyncResult.End(IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.EndOpen(IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.<>c.<OpenAsync>b__53_1(IAsyncResult r)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Azure.Messaging.ServiceBus.Amqp.AmqpConnectionScope.OpenAmqpObjectCoreAsync(AmqpObject target, String entityPath, Nullable`1 timeout, Nullable`1 cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpConnectionScope.OpenAmqpLinkAsync(AmqpLink link, String entityPath, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpConnectionScope.OpenReceiverLinkAsync(String identifier, String entityPath, TimeSpan timeout, UInt32 prefetchCount, ServiceBusReceiveMode receiveMode, String sessionId, Boolean isSessionReceiver, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.OpenReceiverLinkAsync(TimeSpan timeout, UInt32 prefetchCount, ServiceBusReceiveMode receiveMode, String identifier, CancellationToken cancellationToken)
```

### Reproduction Steps

See section "Describe the bug".

### Environment

Visual Studio 17.11.0

```
λ dotnet --info
.NET SDK:
 Version:           8.0.400
 Commit:            36fe6dda56
 Workload version:  8.0.400-manifests.56cd0383
 MSBuild version:   17.11.3+0c8610977

Runtime environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.400\
```

**Comment by jsquire** [comment]
Hi @MarcusKohnert.  Thanks for reaching out and we regret that you're experiencing difficulties.  Unfortunately, the client has no insight nor influence over authorization; that is controlled entirely by the Service Bus service.  The maintainers of the Azure SDK are unable to assist with this issue.  We can only confirm that the link that you're opening is a receiving link for a subscription and the service is rejecting the auth.

To ensure that the Service Bus service team has visibility and can assist, your best path forward for would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request).  If you'd prefer not to do so, the next best path would be to inquire on the [Microsoft Q&A site](https://learn.microsoft.com/answers/questions/), which is monitored by the service teams. 

I'm going to close this out; if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.

**Comment by jsquire** [comment]
Thanks very much for the update, @MarcusKohnert.   Hopefully, this will prove helpful for others who run into a similar issue in the future.
