### ISSUE TITLE
[BUG] Soft deleted blobs get returned as part of Find Blobs by Tags API results. 

### ISSUE THREAD

**Issue by VigneshB-Microsoft** [Azure/azure-sdk-for-net#46081]
### Library name and version

2024-11-04

### Describe the bug

There is a known condition that makes (soft) deleted blobs to be returned as part of Find Blobs by Tags API results. Fix is already in progress. Just a bug report for awareness and any comments to be added. 

### Expected behavior

Soft deleted blobs not appearing as part of Find Blobs by Tags API results. 

### Actual behavior

Soft deleted blobs appearing as part of Find Blobs by Tags API results. 

### Reproduction Steps

https://learn.microsoft.com/en-us/rest/api/storageservices/find-blobs-by-tags?tabs=microsoft-entra-id

**Comment by jsquire** [comment]
@VigneshB-Microsoft:  Thanks for reaching out and raising awareness.  The Azure SDK repositories do not track service errors nor service fixes in progress.  I'm going to close this out.
