### ISSUE TITLE
Validate mult-profile sdks

### ISSUE THREAD

**Issue by shahabhijeet** [Azure/azure-sdk-for-net#4608]
- make sure we can build, sign the new multi-profile SDKs
- convert multi-api SDK test to multi-profile test

Cost: 3

**Comment by dsgouda** [comment]
Bumping cost by 2.
We needed to add tests per RP

**Comment by dsgouda** [comment]
Added working tests for:
- Compute
- Resource
- Storage
- Websites
Need connection strings to record tests for:
- KeyVault
- Authorization
Need specific tests to record:
- Subscription
Will fix the tests in a new task
