### ISSUE TITLE
[BUG] System.InvalidOperationException Thrown When Retrieving Schema of JSON Dataset Using Azure Data Factory SDK

### ISSUE THREAD

**Issue by wangbwn** [Azure/azure-sdk-for-net#46111]
### Library name and version

Azure.ResourceManager.DataFactory 1.4.0

### Describe the bug

While using the Azure Data Factory .NET SDK (with .NET 6.0 on Windows 11) to retrieve the schema of a JSON dataset, an exception is thrown:
An exception of type 'System.InvalidOperationException' was thrown: 'dataset.Data.Properties.Schema.Literal'

### Expected behavior

The schema of the JSON dataset "JsonTest1" should be successfully retrieved without any exceptions.

### Actual behavior

An exception of type System.InvalidOperationException is thrown with the message:
An exception of type 'System.InvalidOperationException' was thrown: 'dataset.Data.Properties.Schema.Literal'

### Reproduction Steps

var credential = new DefaultAzureCredential();
var armClient = new ArmClient(credential);
_datafactory = armClient.GetDataFactoryResource(new ResourceIdentifier($"/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataFactory/factories/{dataFactoryName}")).Get();
var dataset = _datafactory.GetDataFactoryDatasets().Get("JsonTest1").Value;
var schema = dataset.Data.Properties.Schema;

This issue occurs consistently when attempting to retrieve the schema.

### Environment

Azure Data Factory SDK Version: 1.4.0
.NET Version: .NET 6.0
Operating System: Windows 11

**Comment by HarveyLink** [comment]
Hi @wangbwn , We can't repro this issue on our side, please check the latest version see if it still exists.

**Comment by HarveyLink** [comment]
Close as not reproduced.
