### ISSUE TITLE
 TrafficManagerProfile.WithoutEndpoint removes the incorrect endpoints

### ISSUE THREAD

**Issue by seahawksq** [Azure/azure-sdk-for-net#4620]
With package version 1.13.0, the TrafficManagerProfile.WithoutEndpoint only "keeps" the endpoint from input parameter other than "removes" it, for example:
In the profile there are three endpoints - endpoint1, endpoint2 and endpoint3.
profile.Update().WithoutEndpoint("endpoint2").Apply() removes endpoint1 and endpoint3 but the expected behavior should remove endpoint2 only.
When debugging into the IUpdate object of profile, I saw the endpoint2 is marked as "ToBeRemoved" in the "PendingOperation" field and Fiddler API confirms the deletion is for endpoint2.
But when calling to Apply() method, the "Put" request does NOT pass the correct traffic manager profile model (which contains the endpoint to be deleted in the profile), I think that's the cause of this issue.

**Comment by YalinLi0312** [comment]
@allenjzhang  Assigning Fluent bug related to you

**Comment by jsquire** [comment]
Given the age of this issue and the pending deprecation of the Fluent management packages, I'm going to close this out as stale.   Please feel free to reopen if further discussion is needed.
