### ISSUE TITLE
[FEATURE REQ] Azure AI Document Intelligence AnalyzeDocumentContent Include Auth Headers

### ISSUE THREAD

**Issue by apla1297** [Azure/azure-sdk-for-net#46269]
### Library name

Azure.AI.DocumentIntelligence

### Please describe the feature.

When passing a URI to Azure document intelligence it would be helpful to also be able to add an Auth header to allow the SDK to pull documents behind protected endpoints. 

In this case I'm trying to grab docs from SharePoint using the Graph API. I can get the doc and then sent it base64 encoded, but that's an extra hop that can be meaningful with large docs. Id rather have forms req get it directly from SharePoint, but would need to be able to add a token to the request headers to do so.

**Comment by jsquire** [comment]
Hi @apla1297.  Thank you for reaching out and for your suggestion.  What you're asking for requires a change to the Document Intelligence service before the Azure SDK client would be able to include this feature.  Unfortunately, service feature requests are not something that the maintainers of the Azure SDK can assist with.

To ensure that the right team has visibility and can help, your best path forward for would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) or you may also want to consider the [Azure Feedback site](https://feedback.azure.com/d365community).   Should the service add this feature, the Azure SDK clients will also support it.

I'm going to close this out; if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.
