### ISSUE TITLE
Missing UKSouth

### ISSUE THREAD

**Issue by xclayl** [Azure/azure-sdk-for-net#4626]
AzureRegions enum is missing UKSouth. 

We'd like to use "KeyPhrasesAsync()" with our Cognitive Service located in UK South.

**Comment by xclayl** [comment]
enum is:
Microsoft.Azure.CognitiveServices.Language.TextAnalytics.Models.AzureRegions

**Comment by ChrisHMSFT** [comment]
This problem has been fixed in the new SDK. 

Thanks,
Chris
