### ISSUE TITLE
[QUERY] Is Azure.Maps.TimeZone supposed to be on nuget.org?

### ISSUE THREAD

**Issue by jonathanpotts** [Azure/azure-sdk-for-net#46316]
### Library name and version

Azure.Maps.TimeZone 1.0.0-beta.1

### Query/Question

According to https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/maps/Azure.Maps.TimeZone/CHANGELOG.md, Azure.Maps.TimeZone 1.0.0-beta.1 was released on 2024-08-06 but it is not available on nuget.org.

When I run the following command: `dotnet add package Azure.Maps.TimeZone --prerelease` as specified in https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/maps/Azure.Maps.TimeZone/README.md, I get the following output:
```
...
info : Adding PackageReference for package 'Azure.Maps.TimeZone' into project 'REDACTED'.
info :   GET https://api.nuget.org/v3/registration5-gz-semver2/azure.maps.timezone/index.json
info :   NotFound https://api.nuget.org/v3/registration5-gz-semver2/azure.maps.timezone/index.json 206ms
error: There are no versions available for the package 'Azure.Maps.TimeZone'.
```

### Environment

Windows 11
.NET SDK 8.0.400
.NET Runtime 8.0.8
ASP.NET Core Runtime 8.0.8
.NET Desktop Runtime 8.0.8
Visual Studio 17.11.4

**Comment by dubiety** [comment]
Hi @jonathanpotts ,

This is a mistake. This package is not released yet. We'll remove the release date and our targeted release date is beginning of Nov. Sorry for the inconvenience and thanks for the understanding.

**Comment by dubiety** [comment]
We've updated the changelog. Sorry for the confusion. I'll close this issue now.

**Comment by jonathanpotts** [comment]
> Hi [@jonathanpotts](https://github.com/jonathanpotts) ,
> 
> This is a mistake. This package is not released yet. We'll remove the release date and our targeted release date is beginning of Nov. Sorry for the inconvenience and thanks for the understanding.

Is the package still going to be released this month?

**Comment by dubiety** [comment]
Hi @jonathanpotts ,

I'm glad to share we've release `Azure.Maps.TimeZones` SDK `v1.0.0-beta.1`. Welcome to try it out. Thank you for your patience.
