### ISSUE TITLE
 ComputerVision 3.2.0 gives ComputerVisionErrorException

### ISSUE THREAD

**Issue by easyj2j** [Azure/azure-sdk-for-net#4632]
Every method using ComputerVision 3.2.0 gives: "ComputerVisionErrorException: Operation returned an invalid status code 'NotFound'".

**Comment by easyj2j** [comment]
This is due to the change in setting the endpoint:

3.2: computerVision.Endpoint = "https://westcentralus.api.cognitive.microsoft.com";
2.1: computerVision.AzureRegion = AzureRegions.Westcentralus;
ProjectOxford: computerVision.ServiceHost = "https://westcentralus.api.cognitive.microsoft.com/vision/v1.0";

Would like to see:
 - On the NuGet page: an emphasis on the change in specifying the URL
 - A more illuminating exception message

**Comment by ChrisHMSFT** [comment]
Hi @easyj2j ,

Please try again with the latest version of the SDK. Here is a link to the Nuget: https://www.nuget.org/packages/Microsoft.Azure.CognitiveServices.Vision.ComputerVision

Thanks,
Chris
