### ISSUE TITLE
[QUERY] Details on IJsonModel<ManagedDiskData>.Create

### ISSUE THREAD

**Issue by everest146** [Azure/azure-sdk-for-net#46328]
### Library name and version

Azure.ResourceManager.Compute 1.4.0

### Query/Question

I'm working on unit tests for a C# script that operates on managed disks, so I need to create some dummy disks and fill them with fake data for testing. The documentation for how to do this has been sparse. The way I have been trying to do this is by creating mock ManagedDiskResource objects, and using the IJsonModel<ManagedDiskData>.Create method to turn a json string of the fake data into a ManagedDiskData object that I can add to the mock ManagedDiskResource object. However, when I run the tests, IJsonModel<ManagedDiskData>.Create successfully executes, and I can retrieve the data with IJsonModel<ManagedDiskData>.Write, but when I try to retrieve the data through normal getter methods, it's not there! The data must be stored in the ManagedDiskData object somewhere, but Create() isn't filling out the object's fields with the data as I need it to. I may be formatting the json object incorrectly, but I could not know since I can't find any guidelines for how to format it; I also couldn't find the implementation for the Create method. I've attached the mock class file for reference with what I've described above included. I would like some guidelines for how to correctly format the json (assuming I'm formating incorrectly) and some advice on the intended what to create dummy ManagedDisksResource objects (assuming I'm overcomplicating it). One last note -- I did look for a factory class to create the ManagedDiskResource objects, but there didn't appear to be one. Thanks.
[MockManagedDiskResource.txt](https://github.com/user-attachments/files/17156387/MockManagedDiskResource.txt)

### Environment

Windows 10, .NET v8, Visual Studio 2022 17.10.6

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi @everest146 , sorry for the late reply.
If you would like to mock a resource for your testing, you could check this factory class: https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.compute.models.armcomputemodelfactory?view=azure-dotnet

**Comment by everest146** [comment]
@HarveyLink I haven't seen this class before. I'll make sure to give it a try
