### ISSUE TITLE
Inconsistent Nomenclature Between Azure Portal and SDKs: Endpoint 

### ISSUE THREAD

**Issue by brminnick** [Azure/azure-sdk-for-net#4633]
# Issue
The Azure Portal uses the term `Endpoint` to refer to the API Endpoint:
![picture1](https://user-images.githubusercontent.com/13558917/43671124-35bcc654-9749-11e8-85ef-1c5e169c9e8a.png)

[Microsoft.Azure.CognitiveServices.Vision.Face v2.2.0-preview](https://www.nuget.org/packages/Microsoft.Azure.CognitiveServices.Vision.Face/2.2.0-preview) also also uses the term `Endpoint`, but is referring to the Base URI:
<img width="1033" alt="screen shot 2018-08-03 at 6 16 39 pm" src="https://user-images.githubusercontent.com/13558917/43671150-777c85b6-9749-11e8-97e4-95b8ead6ad4a.png">

Because the same term is used in the Azure Portal and the SDK, Developers are likely to copy/paste the full API `Endpoint` from the Azure Portal and paste it into their code. If the full API Endpoint Url (e.g. https://westus.api.cognitive.microsoft.com/face/v1.0) is used, the SDK throws the following exception at runtime:
> Microsoft.Azure.CognitiveServices.Vision.Face.Models.APIErrorException: Operation returned an invalid status code 'NotFound'  

# Recommendations

Although the .NET tooltip gives an example (as seen in the screenshot above), it would be better to use either of these options instead:
1. Name the property `BaseUri` instead of `Endpoint`
   - [Microsoft.Azure.CognitiveServices.Vision.Face v2.0.0-preview](https://www.nuget.org/packages/Microsoft.Azure.CognitiveServices.Vision.Face/2.0.0-preview) used the property name `BaseUri`
2. Add logic to trim the full API endpoint
   - If a developer passes in the full API endpoint, e.g. `https://westus.api.cognitive.microsoft.com/face/v1.0`, trim the `string` to `https://westus.api.cognitive.microsoft.com`, removing `/face/v1.0`

**Comment by brminnick** [comment]
Adding @noellelacharite for visibility

**Comment by ChrisHMSFT** [comment]
Hi All, 

Closing this ticket since the Azure portal now displays the same structure that is required for the SDKs

Thanks,
Chris
