### ISSUE TITLE
Microsoft.Azure.WebJobs.Extensions.WebPubSubForSocketIO README Issue

### ISSUE THREAD

**Issue by Kevin-Zhong19** [Azure/azure-sdk-for-net#46364]
1.
**Section** [link](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/webpubsub/Microsoft.Azure.WebJobs.Extensions.WebPubSubForSocketIO/README.md):

![image](https://github.com/user-attachments/assets/3a9391b2-c853-413b-a3b6-196002ce62a6)

**Reason**:
Link error.

**Suggestion**:
Change `Source code` link to "https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/webpubsub/Microsoft.Azure.WebJobs.Extensions.WebPubSubForSocketIO/src “.

@scottaddie , @jsquire and @iscai-msft for notification.

**Comment by v-xuto** [comment]
This issue has been fixed by PR https://github.com/Azure/azure-sdk-for-net/pull/46876, close it.
