### ISSUE TITLE
DeviceAuthentication should work with .NET Core

### ISSUE THREAD

**Issue by shahabhijeet** [Azure/azure-sdk-for-net#4636]
fix for https://github.com/Azure/azure-libraries-for-net/issues/282

**Comment by shahabhijeet** [comment]
https://github.com/Azure/azure-sdk-for-net/pull/4677

**Comment by hovsepm** [comment]
@shahabhijeet the library looks good. .NetCore and .Net 461 has DeviceAuthentication now. Please publish the new versions of both Auth 2.3.4 and TestFramework 1.7.3 packages.
