### ISSUE TITLE
Microsoft.Azure.WebJobs.Extensions.WebPubSub Samples Issue

### ISSUE THREAD

**Issue by Kevin-Zhong19** [Azure/azure-sdk-for-net#46365]
1.
**Section** [link](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/webpubsub/Microsoft.Azure.WebJobs.Extensions.WebPubSub/samples/WebPubSubTriggerFunction.cs#L18):

![image](https://github.com/user-attachments/assets/7107f1b5-7198-43e5-86d6-2d77de930d4a)

**Reason**:
Type error. Can't bind parameter 'data' to type 'System.String'.

**Suggestion**:
Please change to the correct data type.

@scottaddie , @jsquire and @vicancy for notification.

**Comment by JialinXin** [comment]
Which SDK version are you using? And what original data type are you using? We'll try to convert reserved parameters to possible data type, best choice is `BinaryData` and accepts `string`, `Stream`, `byte[]` for data and convert if possible.

See here for some reference: https://learn.microsoft.com/en-us/azure/azure-web-pubsub/reference-functions-bindings?tabs=csharp#usages

**Comment by Kevin-Zhong19** [comment]
> Which SDK version are you using? And what original data type are you using? We'll try to convert reserved parameters to possible data type, best choice is `BinaryData` and accepts `string`, `Stream`, `byte[]` and convert if possible.
> 
> See here for some reference: https://learn.microsoft.com/en-us/azure/azure-web-pubsub/reference-functions-bindings?tabs=csharp#usages

Thank you, we define the string type, it can be received normally.

**Comment by v-xuto** [comment]
This issue has been resolved and we will close this issue.
