### ISSUE TITLE
ASP NET Core MVC to Azure functions without changing any code

### ISSUE THREAD

**Issue by sjuarezgx** [Azure/azure-sdk-for-net#46382]
### Library name and version

Microsoft.Azure.Functions.Worker.Sdk 1.17.4

### Query/Question

Is there a tool or framework in the ASP.NET Core ecosystem that works identically to Spring's Cloud Function, allowing you to directly convert Controllers into Azure Functions without the need to re-program them?

I have an API in ASP NET Core, with code like this:

[HttpGet]
[Route("ListAirlines")]
public async Task gxep_listairlines( )
{
//here my code
}

I need to execute all my API as Azure functions without changing that code.
I saw that now there is support for [ASP NET Core integration with Azure functions](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide?tabs=windows#aspnet-core-integration). However, I do not see how to re-use my controllers code.

I tried creating a function "proxy" for all my controllers, by inyecting the ApplicationBuilder. I use that "ApplicationBuilder" to invoke the service controller registered.
So, I'm integrating the ASP Net core MVC with Azure functions, which I'm not sure if it will result in a performant solution (if it worked..)

Program.cs:

    var host = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults()
    .ConfigureServices(services =>
    {
	services.AddControllers();
	IMvcBuilder builder = services.AddMvc(option => option.EnableEndpointRouting = false);
	
	services.AddSingleton<IApplicationBuilder>(sp =>
	{
		var appBuilder = new ApplicationBuilder(sp);
                   appBuilder.UseRouting();
		appBuilder.UseEndpoints(endpoints =>
		{
			endpoints.MapControllers();
		});
		return appBuilder;
	});
	AzureFunctionsStartup.ConfigureServices(services);
})

Azure function code:

          public class HttpTriggerHandler
          {
           private ICacheService2 _redis;
           private IApplicationBuilder _applicationBuilder;

           public HttpTriggerHandler(IApplicationBuilder applicationBuilder, ICacheService2 redis)
           {
       _applicationBuilder = applicationBuilder;
       if (redis != null && redis.GetType() == typeof(Redis))
	  _redis = redis;
            }

        public async Task<HttpResponseData> Run(
	[HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", "put", "delete", Route = "{*route}")] HttpRequestData 
         req,
	string route, FunctionContext executionContext)
     {
	
	var httpResponseData = req.CreateResponse();
	HttpContext httpAzureContextAccessor = new GXHttpAzureContextAccessor(req, httpResponseData, _redis);
	await _applicationBuilder.Build().Invoke(httpAzureContextAccessor);

	return httpResponseData;

	
       }
           }
           }
But it doesn't work. It seems to be executing the service twice.. I have the following runtime error.

An attempt was made to transition a task to a final state when it had already completed

### Environment

Azure Functions v4
NET 8
Isolated model

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.Azure.Functions.Worker.Sdk` package is maintained as [#2744](https://github.com/Azure/azure-functions-dotnet-worker/issues/2744).
