### ISSUE TITLE
Configuring Managed Identity

### ISSUE THREAD

**Issue by madanjayaprakasam** [Azure/azure-sdk-for-net#46394]
### Type of issue

Missing information

### Description

We see option to configure access key for the EventGrid using KeySettingName but how do we configure EventGrid that use Managed Identity based auth.

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.webjobs.extensions.durabletask.eventgridnotificationoptions?view=azure-dotnet

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.WebJobs.Extensions.DurableTask/EventGridNotificationOptions.xml

### Document Version Independent Id

ec66102e-568e-9087-b442-6c9399e23ff1

### Article author

@azure-sdk

### Metadata

* ID: e7b049c9-bbe7-d26d-6e98-a026d93a6610 
* Service: **azure-functions**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.Azure.WebJobs.Exentions.DurableTask` library is maintained as [#2924](https://github.com/Azure/azure-functions-durable-extension/issues/2924).
