### ISSUE TITLE
[QUERY] Create Front Door Standard instance with management packages

### ISSUE THREAD

**Issue by ysuniltechovarya** [Azure/azure-sdk-for-net#46406]
### Library name and version

azure-sdk-for-net 

### Query/Question

Is there any sdk for .net core for create **standard** front door?
I'm currently working on a project using .NET Core, and I need to create an Azure Front Door Standard instance programmatically. I've explored various Azure SDKs, but I'm unsure which one to use for this specific task. Or is there any way to achieve it?

### Environment

.NET CORE

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi @ysuniltechovarya , The package you should use: 
[Azure.ResourceManager.Cdn](https://www.nuget.org/packages/Azure.ResourceManager.Cdn)
OR
[Azure.ResourceManager.FrontDoor](https://www.nuget.org/packages/Azure.ResourceManager.FrontDoor)
Depends on what kind of service you would like to use, you could refer to https://learn.microsoft.com/en-us/azure/frontdoor/front-door-cdn-comparison
