### ISSUE TITLE
[BUG] LiveMetrics showing incorrect values

### ISSUE THREAD

**Issue by TimothyMothra** [Azure/azure-sdk-for-net#46417]
### Library name and version

Azure.Monitor.OpenTelemetry.AspNetCore

### Describe the bug

LiveMetrics is showing incorrect values.
Specifically investigating Requests per second.

### Expected behavior

N/A

### Actual behavior

N/A

### Reproduction Steps

Here I've written a console app that starts a web application.
The default endpoint is invoked in a loop, and every second we print out the number of requests.

```csharp
    internal class Program
    {
        public static async Task Main(string[] args)
        {
            var builder = WebApplication.CreateBuilder(args);
            builder.Logging.ClearProviders();
            string connectionString = "...";
            builder.Services.AddOpenTelemetry().UseAzureMonitor(x => x.ConnectionString = connectionString);
            var app = builder.Build();

            app.MapGet("/", () => "Hello World!");

            var hostTask = app.RunAsync();

            using var httpClient = new HttpClient();
            var stopwatch = Stopwatch.StartNew();
            int callCount = 0;

            while (true)
            {
                var response = await httpClient.GetStringAsync("http://localhost:5000");
                callCount++;

                if (stopwatch.ElapsedMilliseconds >= 1000)
                {
                    Console.WriteLine($"{DateTime.Now:HH:mm:ss}: {callCount} calls");
                    callCount = 0;
                    stopwatch.Restart();
                }
            }
        }
    }
```

Console output shows between 30-50 requests per second.
![image](https://github.com/user-attachments/assets/2ab6c622-7393-472c-89b8-cb2187cd2c13)

The Metrics blade is showing an average of 45 requests per second.
![image](https://github.com/user-attachments/assets/fbf30c48-f0ad-4b0f-923b-71cbc934cf5b)

LiveMetrics dashboard is showing 3 requests per second
![image](https://github.com/user-attachments/assets/b7c9ea2e-d440-4f22-bc4f-269ebe95f42c)

A fiddler trace is also showing that the SDK is sending 3 requests per second
![image](https://github.com/user-attachments/assets/1ae02ea9-360d-4e4d-8d61-f3a0ec9af4a2)

**Comment by TimothyMothra** [comment]
Seems like our internal buffer had a hard cap of 20. 

https://github.com/Azure/azure-sdk-for-net/blob/43fc021007689ca13bb372293103ca985af2b0c9/sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/src/LiveMetrics/DataCollection/DocumentBuffer.cs#L15

When i changed this to an arbitrary high value, Live Metrics shows the correct value

![image](https://github.com/user-attachments/assets/2815b22e-294e-43c1-830d-9497a800c7b1)

**Comment by TimothyMothra** [comment]
FYI; The bug is related to the capacity limit on our internal buffer. The capacity was set too low.
We're discussing either increasing the capacity or removing it altogether. 
We need to take some more time to review the performance implications of either change.

**Comment by vRune4** [comment]
Live metrics:
![Image](https://github.com/user-attachments/assets/d2724713-1caf-44fb-97ff-d76630f8d94d)

Meanwhile, what was running during this time was a load test that averaged almost 1500 requests per second.

![Image](https://github.com/user-attachments/assets/386cbe41-01ef-4346-b246-5791ff49e920)

This is a .net 9 asp.net project that benchmarks a single query running against the northwind database.

```csharp
builder.Services.AddOpenTelemetry().UseAzureMonitor(opt => { opt.Credential = credential; opt.ConnectionString = appInsightsConnectionString; });
```
