### ISSUE TITLE
[BUG]Latest .net SDK version for azure redis enterprise attempts to use API version(2024-09-01-preview) which is not available yet.

### ISSUE THREAD

**Issue by priyankarking** [Azure/azure-sdk-for-net#46428]
### Library name and version

Azure.ResourceManager.RedisEnterprise 1.2.0-beta.1

### Describe the bug

The latest .NET SDK version for Redis Enterprise is attempting to use an API version (2024-09-01-preview) that is not yet available.

We are actively working on a fix, which will be released soon. In the meantime, please avoid using this SDK version.

### Expected behavior

library API call should work.

### Actual behavior

library API call not working as it uses API version which is not deployed yet.

### Reproduction Steps

upgrade nuget package for Azure.ResourceManager.RedisEnterprise  to 1.2.0-beta.1 and try to use the updated nuget library.

**Comment by priyankarking** [comment]
Please avoid using version 1.2.0-beta.1 and instead use the latest stable version(1.1.0) until we resolve the issue. We are actively working on a fix, which will be available soon.
![image](https://github.com/user-attachments/assets/a28e44ca-03e1-43a9-a675-89ebbcde6240)

**Comment by jsquire** [comment]
Thank you for the heads-up, @priyankarking.   As a beta version comes with no guarantees and the service intends to make this version available, I don't see any action for remediation needed for the SDK.   As we do not track service issues in this repository nor use issues for general announcements, I'm going to close this out.
