### ISSUE TITLE
[FEATURE REQ] Make the RetryCount of the PipelineMessage protected

### ISSUE THREAD

**Issue by fhmgonzaga** [Azure/azure-sdk-for-net#46426]
### Library name

System.ClientModel

### Please describe the feature.

I need to override the ShouldRetry method on System.ClientModel.Primitives.ClientRetryPolicy. One of my tasks is to control the number of retries, but I don't have access to the RetryCount property of System.ClientModel.Primitives.PipelineMessage.
Can we make this property protected?
Thanks.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by annelo-msft** [comment]
Thanks for the suggestion, @fhmgonzaga!  Would you be willing to share a few more specifics around what scenarios you're looking to implement by having access to the retry count in ClientRetryPolicy?  Having this information will help our team figure out the best way to expose those APIs to enable your scenarios as well as scenarios for other use cases as well.  Many thanks in advance for your help on this!

**Comment by fhmgonzaga** [comment]
Hi. I need to change the behavior of the ClientRetryPolicy. I want to treat one HttpStatusCode differently. For that, I overridden the ShouldRetry method. I will make my custom httpStatus logic, but I need to keep doing the retryCount logic. I can't do that if I don't have access to the message's RetryCount. For now, I'm using reflection to get it, but I would like to simply use the property.

**Comment by annelo-msft** [comment]
Got it!  Thank you, that is very helpful context.

I have a few suggestions for ways you might be able to solve this today -- I am interested in whether they will work for your specific case, or if API additions might still be needed.

1. If you're interested in modifying the retry behavior based on the status code, you might be able to override ClientRetryPolicy.OnRequestSent and modify the message.ResponseClassifier property.  You could create a custom PipelineMessageClassifier that modifies the TryClassify( ... out bool IsRetriable) method and set it on the message.  Then, the base retry policy's implementation of ShouldRetry would use this classifier and maintain the retry count logic for you -- the only thing that would change is which status codes were considered "retriable".
2. If you have more complex logic that motivates fully overriding ShouldRetry, you might consider implementing your logic in your method override and then calling base.ShouldRetry.  I would be interested to know if this didn't work.
3. If none of the above are viable options for you, you could consider setting a custom property on the message by using the PipelineMessage.SetProperty method.  Your policy would provide an internal/private type as the key for the property value, and then it would use this to look up the retry count value via PipelineMessage.TryGetProperty.  That would let you take full ownership of the ShouldRetry logic, while maintaining your own retry count.  You could increment this count in an overload of OnRequestSent, or I believe even just in ShouldRetry itself should work.

If none of these approaches will work for you, please let me know.  I would be interested to understand further specifics around your scenario if they are insufficient for your purposes.

Thanks!

**Comment by fhmgonzaga** [comment]
Hi @annelo-msft ,

I can't do 1 because if I create a custom PipelineMessageClassifier, I'll lose the original logic. I want to keep it and only add a new status on it.
I can't do 2 because I don't want to return true to any request of my new status. I need to check the RetryCount before.
I guess I could do 3, but I don't want to duplicate the RetryCount logic.

I'm using reflection to get the value I need:

PropertyInfo propertyInfo = type.GetProperty("RetryCount", BindingFlags.NonPublic | BindingFlags.Instance);
object? retryCountObj = propertyInfo.GetValue(message);
int retryCount = (int)retryCountObj;

Thanks!

**Comment by annelo-msft** [comment]
Thanks, @fhmgonzaga -- if I could provide you with a sample you could use to implement option 1, would you be willing to use it?  My concern is that if you use reflection to access an internal (undocumented) property and we later change the implementation, your application code might start behaving in unpredictable ways.  My sense is that the first option is likely the best match for your scenario, but we haven't made these APIs super usable in the first release of SCM.  If this becomes a common request, we can add better convenience APIs there.  And in the meantime, I'm happy to help provide a sample so that you can use a solution today that will make your application more robust.

**Comment by fhmgonzaga** [comment]
@annelo-msft , sure. I can try your sample. Thanks!

**Comment by annelo-msft** [comment]
Great!

I am hoping something like the following might work for your scenario:

```csharp
public class CustomRetryClassifier : PipelineMessageClassifier
{
    private readonly PipelineMessageClassifier _defaultClassifier;
    private readonly int _specialRetriableStatusCode;

    public CustomRetryClassifier(PipelineMessageClassifier defaultClassifier, int specialRetriableStatusCode)
    {
        _defaultClassifier = defaultClassifier;
        _specialRetriableStatusCode = specialRetriableStatusCode;
    }

    public override bool TryClassify(PipelineMessage message, out bool isError)
        => _defaultClassifier.TryClassify(message, out isError);

    public override bool TryClassify(PipelineMessage message, Exception? exception, out bool isRetriable)
    {
        // if it's a special HTTP code, classify it;
        // otherwise, let the default classifier classify it.
        if (message.Response!.Status == _specialRetriableStatusCode)
        {
            isRetriable = true;
            return true;
        }

        return _defaultClassifier.TryClassify(message, exception, out isRetriable);
    }
}

public class CustomRetryPolicy : ClientRetryPolicy
{
    private readonly int _retryStatusCode;

    public CustomRetryPolicy(int customRetryStatusCode)
    {
        _retryStatusCode = customRetryStatusCode;
    }

    protected override void OnSendingRequest(PipelineMessage message)
    {
        if (message.ResponseClassifier is not CustomRetryClassifier)
        {
            message.ResponseClassifier = new CustomRetryClassifier(message.ResponseClassifier, _retryStatusCode);
        }
    }
}
```

In this sample, you could create a custom retry policy that will retry a response with a 418 status code as follows:

```csharp
CustomRetryPolicy policy = new(customRetryStatusCode: 418);
```

If the response doesn't have the special code, it should preserve the default behavior.


Let me know if you have any questions about any of this, and/or if this doesn't address your scenario.

**Comment by fhmgonzaga** [comment]
Hi @annelo-msft .

Your code worked. I just had to use the async version of OnSendingRequest:

```
protected override ValueTask OnSendingRequestAsync(PipelineMessage message)
{
    if (message.ResponseClassifier is not CustomRetryClassifier)
    {
        message.ResponseClassifier = new CustomRetryClassifier(message.ResponseClassifier, _retryStatusCode);
    }

    return base.OnSendingRequestAsync(message);
}
```

Thanks!

**Comment by annelo-msft** [comment]
Great, glad to hear!

Yes, it is a best practice to implement both sync and async variants of Process when implementing any SCM pipeline policy.  If you look at example implementations in our repo, you'll see that we typically have [outer sync and async methods call into a common method](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/System.ClientModel/src/Pipeline/ClientRetryPolicy.cs#L42-L49) so we don't have to copy implementation logic in multiple places.

I'll go ahead and close this issue because it feels like you have a solution that suits your needs now, but if you feel there are more pieces to work through, let me know and we can reopen the issue to address them.


Thanks!
