### ISSUE TITLE
[BUG] Not all TableEntities are returned after inserting them.

### ISSUE THREAD

**Issue by well0549** [Azure/azure-sdk-for-net#46434]
### Library name and version

azure.data.tables\12.9.1

### Describe the bug

After inserting a 1000 table entities, the first read gives Less entities.
I have a very simple program
```
        public static async Task RunTest(TableClient client)
        {
            List<TableEntity> tableEntities = new List<TableEntity>();

            // Create 1000 table entities 
            for (int i = 0; i < 1000; i++)
            {
                TableEntity entity = new TableEntity();
                entity.PartitionKey = $"{new Random().Next(1, 10)}";
                entity.RowKey = $"{Guid.NewGuid()}";
                tableEntities.Add(entity);
            }

            Parallel.ForEach(tableEntities, async entity =>
            {
                await client.UpsertEntityAsync(entity);
            });

            for (int i = 0; i < 10; i++)
            {
                List<TableEntity> results = new();
                var asyncdata = client.QueryAsync<TableEntity>(maxPerPage: 200).ConfigureAwait(false);
                await foreach (TableEntity page in asyncdata)
                {
                    results.Add(page);
                }
                Console.WriteLine($"Read entities :{results.Count}");    
            }
        }
```

I would expect 1000 table entities when reading them. But i get less entioties than i inserted.
Below is some output from the program.

```
Read entities :999
Read entities :1000
Read entities :1000
Read entities :1000
Read entities :1000
Read entities :1000
Read entities :1000
Read entities :1000
Read entities :1000
Read entities :1000
```

The behaviour is pretty consistent, when i run it for a second time:
```
Read entities :1999
Read entities :2000
Read entities :2000
Read entities :2000
Read entities :2000
Read entities :2000
Read entities :2000
Read entities :2000
Read entities :2000
Read entities :2000
```
This time there are 1000 new entities added but again not all are read. Sometimes i miss 1 record, or 4, the number differs from time to time.

### Expected behavior

Since all records are inserted, I would expect 1000 records each time.

### Actual behavior

Not all records are read.

Even if i put `System.Threading.Thread.Sleep(1000); ` Just after the insert i still get less records

### Reproduction Steps

        public static async Task RunTest(TableClient client)
        {
            List<TableEntity> tableEntities = new List<TableEntity>();

            // Create 1000 table entities 
            for (int i = 0; i < 1000; i++)
            {
                TableEntity entity = new TableEntity();
                entity.PartitionKey = $"{new Random().Next(1, 10)}";
                entity.RowKey = $"{Guid.NewGuid()}";
                tableEntities.Add(entity);
            }

            Parallel.ForEach(tableEntities, async entity =>
            {
                await client.UpsertEntityAsync(entity);
            });

            for (int i = 0; i < 10; i++)
            {
                List<TableEntity> results = new();
                var asyncdata = client.QueryAsync<TableEntity>(maxPerPage: 200).ConfigureAwait(false);
                await foreach (TableEntity page in asyncdata)
                {
                    results.Add(page);
                }
                Console.WriteLine($"Read entities :{results.Count}");    
            }
        }
```

### Environment

On azuree running inside  visual  studio

**Comment by jsquire** [comment]
Hi @well0549.  Thanks for reaching out and we regret that you're experiencing difficulties.   The Azure SDK client has no insight nor influence over the set of results that the service returns for an operation.   The count of results and the content are generated by the service; the client simply deserializes and returns the service response.   As a result, the maintainers of the Azure SDK are unable to assist with this inquiry.

Unfortunately, the Azure service teams do not monitor our repository.  To ensure that the right team has visibility and can help, your best path forward for would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) or inquire on the [Microsoft Q&A site](https://learn.microsoft.com/answers/questions/).   

I'm going to close this out; if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.
