### ISSUE TITLE
[BUG] LogsIngestionClient.UploadAsync fails when running in Azure Function: "The api version is invalid. Allowed Api versions: 2021-11-01-preview,2023-04-24."

### ISSUE THREAD

**Issue by jcoliz** [Azure/azure-sdk-for-net#46439]
### Library name and version

Azure.Monitor.Ingestion 1.1.2

### Describe the bug

ONLY when running as an Azure Function, does the following occur. See "Environment" section below for more detail.

Uploading logs to Data Collection Endpoint using `LogsIngestionClient.UploadAsync` returns the following result content from the server:

```json
{"Error":{"Code":"InvalidApiVersion","Message":"The api version is invalid. Allowed Api versions: 2021-11-01-preview,2023-04-24."}}
```

The endpoint used in this case is:

```
2024-10-04T23:27:00.021 [Information] Request [7807f23d-d72b-409b-8117-0922bcb1feb4] POST https://dcep-redacted.westus2-1.metrics.ingest.monitor.azure.com/dataCollectionRules/dcr-a4810d9531954c18b88be2864764320b/streams/Custom-Forecasts_CL?api-version=2023-01-01
```

I would gladly change the API version. However, the only option in the client for version is in-fact 2023-01-01

```c#
//
// Summary:
//     Client options for LogsIngestionClient.
public class LogsIngestionClientOptions : ClientOptions
{
    //
    // Summary:
    //     The version of the service to use.
    public enum ServiceVersion
    {
        //
        // Summary:
        //     Service version "2023-01-01".
        V2023_01_01 = 1
    }
```

### Expected behavior

Should upload properly! Note that this works fine running locally using either the Azure Functions core tools, OR running the same code as a .NET worker. One other difference of note.... In the case of a local app, I am using an app registration. For the Azure Function, I'm using managed identity. However, we're not getting an IDENTITY error. And, yes, both the app and the app function managed identity have the correct role.

### Actual behavior

```json
{"Error":{"Code":"InvalidApiVersion","Message":"The api version is invalid. Allowed Api versions: 2021-11-01-preview,2023-04-24."}}
```

Some logs:

```
2024-10-04T23:27:50.024 [Information] Request [55a29747-2458-44c9-9ec1-fed2e8cbd966] POST https://dcep-REDACTED-pue7.westus2-1.metrics.ingest.monitor.azure.com/dataCollectionRules/dcr-a4810d9531954c18b88be2864764320b/streams/Custom-Forecasts_CL?api-version=2023-01-01
Accept:application/json
Content-Type:application/json
Content-Encoding:REDACTED
x-ms-client-request-id:55a29747-2458-44c9-9ec1-fed2e8cbd966
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Monitor.Ingestion/1.1.2 (.NET 8.0.8; Microsoft Windows 10.0.20348)
Authorization:REDACTED
client assembly: Azure.Monitor.Ingestion

2024-10-04T23:27:50.066 [Warning] Error response [55a29747-2458-44c9-9ec1-fed2e8cbd966] 400 Bad Request (00.0s)
Transfer-Encoding:chunked
Server:Microsoft-HTTPAPI/2.0
__HandlingServerId__:REDACTED
Strict-Transport-Security:REDACTED
X-Request-ID:REDACTED
Date:Fri, 04 Oct 2024 23:27:49 GMT
Content-Type:application/json

2024-10-04T23:27:50.066 [Error] UploadToLogsAsync: Failed
Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException : Result: UploadToLogsAsync: Failed
Exception: System.AggregateException: 1 out of the 1 logs failed to upload. Please check the InnerExceptions for more details. (Service request failed.
Status: 400 (Bad Request)

Content:
{"Error":{"Code":"InvalidApiVersion","Message":"The api version is invalid. Allowed Api versions: 2021-11-01-preview,2023-04-24."}}
```

### Reproduction Steps

Please let me know if you need a repro or more logs. I can polish a repro. However, a "minimal" 'repro will still have a LOT of setup.

### Environment

This only reproduces when running in an Azure Function service. Running the same code locally, either using the Azure Functions Core Tools, or by running as a regular .NET Worker, this works fine.

**Comment by jcoliz** [comment]
Hi, folks. As promised here is a complete repro. https://github.com/jcoliz/AzLogs.Ingestion/tree/topic/azfn-2 . 

If anyone tries this, please do feel free to provide feedback!

**Comment by IngerMathilde** [comment]
I had something similar but it turned out I had the wrong endpoint url. Might be worth looking into that.

**Comment by jcoliz** [comment]
@IngerMathilde oh crap, you're right!! Thanks!!

I was using `properties.metricsIngestion.endpoint` instead of `properties.logsIngestion.endpoint`. Doh!
