### ISSUE TITLE
[QUERY] How to retrive data from Semantic Kernel vector store?

### ISSUE THREAD

**Issue by dotcom-gosahi** [Azure/azure-sdk-for-net#46443]
### Library name and version

Microsoft.SemanticKernel.Core

### Query/Question

I am able to ingest the data in the semantic kernel vector store.
But I am exactly not sure how to retrive it. I am builing a web application using .net 8. I am injecting kernel in dependency injection.
Referring to this document
https://learn.microsoft.com/en-us/semantic-kernel/concepts/vector-store-connectors/out-of-the-box-connectors/volatile-connector?pivots=programming-language-csharp

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.SemanticKernal.Core` library is maintained as [#9141](https://github.com/microsoft/semantic-kernel/issues/9141).
