### ISSUE TITLE
[BUG] Azure.ResourceManager.RecoveryServicesBackup methods missing

### ISSUE THREAD

**Issue by i-love-dnb** [Azure/azure-sdk-for-net#46474]
### Library name and version

Azure.ResourceManager.RecoveryServicesBackup 1.2.0

### Describe the bug

`RecoveryServiceBackupExtensions.RefreshProtectionContainersAsync()` method triggers LRO. In method description it is mentioned to use `RecoveryServiceBackupExtensions.GetRefreshOperationResul()` method to get LRO result. But this method does not exist in the library as well as `RecoveryServiceBackupExtensions.GetProtectionContainerRefreshOperationResult()` method.

### Expected behavior

The following methods added to `RecoveryServiceBackupExtensions`:
- `GetRefreshOperationResul()` or `GetProtectionContainerRefreshOperationResult()`
- `GetRefreshOperationResulAsync()` or `GetProtectionContainerRefreshOperationResultAsync()`

### Actual behavior

the following methods do not exist in `RecoveryServiceBackupExtensions`:
- `GetRefreshOperationResul()`
- `GetRefreshOperationResulAsync()`
- `GetProtectionContainerRefreshOperationResult()`
- `GetProtectionContainerRefreshOperationResultAsync()`

### Reproduction Steps

- install Azure.ResourceManager.RecoveryServicesBackup 1.2.0 nuget package
- invoke `RecoveryServiceBackupExtensions.RefreshProtectionContainersAsync()` method
- try to get refresh operation result

**Comment by HarveyLink** [comment]
Hi @i-love-dnb , as the service spec suggested, the [ProtectionContainerRefreshOperationResults_Get](https://github.com/Azure/azure-rest-api-specs/blob/fa6c6015b1633a701edb629c1a759433aa1fdaf2/specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/stable/2024-04-01/bms.json#L2928) operation returns nothing but 202/204. [The example](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/stable/2024-04-01/examples/Common/RefreshContainers_OperationResults.json) have the same result.
Based on your description, you are looking for the actually result, but this operation may not help you on this. You could [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) to reach out to the service team for the further help.
