### ISSUE TITLE
[BUG] TenantResource.GetSubscriptions returning subscriptions for the wrong tenant

### ISSUE THREAD

**Issue by cjmcgee** [Azure/azure-sdk-for-net#46473]
### Library name and version

Azure.ResourceManager 1.13.0

### Describe the bug

TenantResource.GetSubscriptions() returns subscription for a different tenant than the tenant specified by the TenantResource object.  Example project included.  

- [GetSubscriptionsBug.zip](https://github.com/user-attachments/files/17293551/GetSubscriptionsBug.zip)

### Expected behavior

SubscriptionResource objects returned are for the tenant on which they were requested.  

### Actual behavior

SubscriptionResource objects returned are for a different tenant than the one they were requested on.

### Reproduction Steps

See included sample project. 

Summary:
```
var cred = new InteractiveBrowserCredential();
cred.Authenticate();
var client = new ArmClient( cred );
var tenants = client.GetTenants();
// The Id field at the top level is just "/" for all three TenantResource objects here, which I think is the cause of this problem.
var selectedTenant = tenants.Where( r => r.Data.DisplayName == "My Tenant" ).Single();
var subscriptions = selectedTenant.GetSubscriptions();
// subscriptions returned here are for the wrong tenant
```

### Environment

.net 8.0 desktop, W11 Enterprise, VS 2022 (17.11.4)

**Comment by HarveyLink** [comment]
Hi @cjmcgee , this is by design. The sdk could only query in one single tenant that you used to setup the ArmClient, no matter which TenantResource you are using. The TenantResource returned by the list operation are just for the information, we can't actually operate on them.
