### ISSUE TITLE
[BUG] Azure database status is 'Online' when its 'Paused'

### ISSUE THREAD

**Issue by stashut** [Azure/azure-sdk-for-net#46478]
### Library name and version

Microsoft.Azure.Management.Sql v3.1.0-preview

### Describe the bug

The core problem appears to be related to Azure Status handling. I have a database 'TestDB' set with an auto-pause delay for testing different statuses. In the SQL Databases section, the status is shown as 'Paused'

![testDB](https://github.com/user-attachments/assets/e5b799ef-f640-450d-ba18-5be7a2e545da)

However, when querying the same database in Azure Resource Graph Explorer, the status is returned as 'Online', which is also the status reflected in my application. This discrepancy indicates some inconsistencies in how the status is being reported.

![ql](https://github.com/user-attachments/assets/0ebc47c1-57bc-415e-aeaa-402f2b8847df)

UPD: after a while (like 6-8 hours) status polled as paused
 

### Expected behavior

Database status reflecting correctly with auto-pause delay

### Actual behavior

Database status does not reflect correctly with auto-pause delay, Azure Resource Graph Explorer returns status as 'Online' for a few hours when on database UI its 'Paused' 

### Reproduction Steps

1.Create sql DB
2. Set auto-pause delay for 1 hour
3. wait for status to be 'Paused' on UI
4. Go to Azure Resource Graph Explorer and query for DB
5. Find properties of DB
6. Status is 'Online' instead of 'Paused'

**Comment by jsquire** [comment]
Hi @stashut.  Thanks for reaching out and we regret that you're experiencing difficulties.   The `Microsoft.Azure.Management.Sql` package that you're inquiring about reached end of life in September 2023 and is no longer published nor supported by Microsoft.   As such, we are unable to assist with your inquiry.

We would recommend migrating to [Azure.ResourceManager.Sql](https://www.nuget.org/packages/Azure.ResourceManager.Sql/), which is the current generation management package for SQL Server.
