### ISSUE TITLE
[BUG] CostManagment: Deserialization error "ResourceType is null"

### ISSUE THREAD

**Issue by jeremysimmons** [Azure/azure-sdk-for-net#46510]
### Library name and version

Azure.ResourceManager.CostManagement 1.0.1

### Describe the bug

When retrieving exports, the runHistory objects specifies null values for "name", "type", and "eTag".

This causes the deserializer to fail, bceause the ResourceType is null.

   at Azure.Core.Argument.AssertNotNullOrWhiteSpace(String value, String name)
   at Azure.Core.ResourceType..ctor(String resourceType)
   at Azure.ResourceManager.CostManagement.Models.ExportRun.DeserializeExportRun(JsonElement element)
   at Azure.ResourceManager.CostManagement.Models.ExportExecutionListResult.DeserializeExportExecutionListResult(JsonElement element)
   at Azure.ResourceManager.CostManagement.CostManagementExportData.DeserializeCostManagementExportData(JsonElement element)
   at Azure.ResourceManager.CostManagement.CostManagementExportCollection.<>c__DisplayClass8_0.<GetAllAsync>b__1(JsonElement e)
   at Azure.Core.PageableHelpers.PageableImplementation`1.<GetAsyncEnumerator>d__15.MoveNext()
   at Azure.Core.PageableHelpers.PageableImplementation`1.<GetAsyncEnumerator>d__15.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at System.Linq.AsyncEnumerable.<<ToListAsync>g__Core|424_0>d`1.MoveNext() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToList.cs:line 36
   at System.Linq.AsyncEnumerable.<<ToListAsync>g__Core|424_0>d`1.MoveNext() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToList.cs:line 36
   at System.Threading.Tasks.ValueTask`1.get_Result() in System.Threading.Tasks\ValueTask.cs:line 484
   at Company.Azure.Utilities.Azure.BillingManagementClient.<GetCostManagementExportsAsync>d__15.MoveNext()

Example payload from the portal, also has nulls for runHistory entries
![Image](https://github.com/user-attachments/assets/f9c29653-d351-420f-a8c3-e424e73e0c7f)

### Expected behavior

The payload should not contain null for type. I should be able to use sdk to retrieve data and deserialize without exceptions.

### Actual behavior

`GET https://management.azure.com/providers/Microsoft.Billing/billingAccounts/:accountId/billingProfiles/:profile-id/providers/Microsoft.CostManagement/exports/:export-name/runHistory?api-version=2023-07-01-preview`
 is returning a payload where the name, type and etag for the runHistory object is null. type must not be null, and be a valid ResourceType so that https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/costmanagement/Azure.ResourceManager.CostManagement/src/Generated/Models/ExportRun.Serialization.cs#L153 does not throw an exception.

```json
{
  "value": [
    {
      "id": "/providers/Microsoft.Billing/billingAccounts/billing-account-id/billingProfiles/billing-profile-id/providers/Microsoft.CostManagement/exports/companyName-pricing/Run/964686a1-e832-4170-8899-0191e50559f2",
      "name": null,
      "type": null,
      "eTag": null,
      "properties": {
        "runSettings": {
          "format": "Parquet",
          "deliveryInfo": {
            "destination": {
              "resourceId": "/subscriptions/b5ac0f6f-7a51-4461-a2e5-53add7ed0d3d/resourceGroups/companyName/providers/Microsoft.Storage/storageAccounts/companyNameb5ac0f6f",
              "container": "companyName",
              "rootFolderPath": "exports/billing-account-id/billing-profile-id"
            }
          },
          "definition": {
            "type": "PriceSheet",
            "timeframe": "TheCurrentMonth",
            "dataSet": {
              "configuration": {
                "columns": [],
                "dataVersion": "2023-05-01",
                "filters": []
              },
              "granularity": null
            }
          },
          "partitionData": true,
          "dataOverwriteBehavior": "OverwritePreviousReport",
          "compressionMode": "snappy",
          "exportDescription": ""
        },
        "executionType": "OnDemand",
        "status": "Completed",
        "submittedBy": "",
        "submittedTime": "2024-10-09T12:01:19.2523149Z",
        "processingStartTime": "2024-10-09T12:11:22.2227377Z",
        "processingEndTime": "2024-10-09T13:03:33.0343405Z",
        "fileName": null,
        "manifestFile": "exports/billing-account-id/billing-profile-id/companyName-pricing/20241001-20241031/964686a1-e832-4170-8899-0191e50559f2",
        "startDate": "2024-10-01T00:00:00",
        "endDate": "2024-10-31T23:59:59.999"
      }
    }
   ]
}
```

### Reproduction Steps

```csharp
var armClientOptions = new ArmClientOptions();
armClientOptions.SetApiVersion(CostManagementExportResource.ResourceType, "2023-07-01-preview"); // same version used by portal...
var armclient = new ArmClient(credential, defaultSubscriptionId: null, options: armClientOptions);
var scope = ResourceIdentifier.Parse("/providers/Microsoft.Billing/billingAccounts/accountid/billingProfiles/profileid")
var export = await armclient.GetCostManagementExportAsync(scope, "my-export-name", "runHistory"); // exception!
```

### Environment

Microsoft Windows [Version 10.0.22631.4169]

`dotnet --info`
.NET SDK:
 Version:           8.0.306
 Commit:            7f060a8005
 Workload version:  8.0.300-manifests.86714225
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.306\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.10
  Architecture: x64
  Commit:       81cabf2857

.NET SDKs installed:
  6.0.321 [C:\Program Files\dotnet\sdk]
  7.0.317 [C:\Program Files\dotnet\sdk]
  8.0.204 [C:\Program Files\dotnet\sdk]
  8.0.206 [C:\Program Files\dotnet\sdk]
  8.0.306 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.35 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.29 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.35 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

`visual studio`
Microsoft Visual Studio Professional 2022
Version 17.9.6
VisualStudio.17.Release/17.9.6+34728.123
Microsoft .NET Framework
Version 4.8.09032

Installed Version: Professional

ASP.NET and Web Tools   17.9.199.22661
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.9.199.22661
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.9.199.22661
Azure Functions and Web Jobs Tools

C# Tools   4.9.0-3.24121.1+a98c90d56455379836dd5c845b35fa932b00cfa3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Git Web Links   2.10.0
Copy links to files in their online Git repositories.

GitHub Copilot   1.147.0.0 (v1.147.0.0@218a5ecac)
GitHub Copilot is an AI pair programmer that helps you write code faster and with less work.

GitHub Copilot Agent   1.147.0

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

NuGet Package Manager   6.9.2
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.9.2.2412004+684740676513b3b208d5bd5b7f8786dab8d287b7
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.9.56.1
Microsoft SQL Server Data Tools

TypeScript Tools   17.0.30103.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.9.0-3.24121.1+a98c90d56455379836dd5c845b35fa932b00cfa3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.9.0-beta.23614.3+a521e1cd420beb56c15faf6836184fadd2b7937a
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

**Comment by jeremysimmons** [comment]
@jsquire thx for the quick triage. It's pretty surprising to see the API return nulls for the name and type. Those are pretty fundamental fields in the ArmResource model.

**Comment by jeremysimmons** [comment]
@jsquire 

I wanted to share a work-around I made. I was able to use the HttpPipeline to add a rewriting mechanism to fix the type. It's pretty great this capability exists in the SDK, but obviously the issue is the payload is invalid with regards to the SDK's validation rules.

```csharp
var armClientOptions = new ArmClientOptions();
var policy = new ModifyResponseBodyPolicy();
policy.Modifications.Add(new GetExportListWithRunHistory());
policy.Modifications.Add(new GetExportWithRunHistory());
armClientOptions.AddPolicy(policy, HttpPipelinePosition.PerCall);
armClientOptions.SetApiVersion(CostManagementExportResource.ResourceType, _costManagementExportsApiVersion); // would have used "2023-03-01"
var armclient = new ArmClient(credential, defaultSubscriptionId: null, options: armClientOptions);
```

```csharp
public class ModifyResponseBodyPolicy : HttpPipelinePolicy
{
    public List<ResponseBodyModification> Modifications { get; init; } = new List<ResponseBodyModification>();

    public override void Process(HttpMessage message, ReadOnlyMemory<HttpPipelinePolicy> pipeline)
    {
        // Call the next policy in the pipeline.
        ProcessNext(message, pipeline);

        // Modify the response body here.
        foreach (var modification in Modifications)
        {
            if (modification.IsMatch(message))
            {
                ModifyResponseBody(message, modification);
            }
        }
    }

    public override async ValueTask ProcessAsync(HttpMessage message, ReadOnlyMemory<HttpPipelinePolicy> pipeline)
    {
        // Call the next policy in the pipeline.
        await ProcessNextAsync(message, pipeline);

        // Modify the response body here.
        foreach (var modification in Modifications)
        {
            if (modification.IsMatch(message))
            {
                ModifyResponseBody(message, modification);
            }
        }
    }

    private void ModifyResponseBody(HttpMessage message, ResponseBodyModification modification)
    {
        // Check if the response content is not null.
        if (message.Response.ContentStream != null)
        {
            // Read the response content stream.
            using var reader = new StreamReader(message.Response.ContentStream);
            var content = reader.ReadToEnd();

            var modifiedContent = modification.RewriteResponseBody(content);

            // Update the response content stream with the modified content.
            var modifiedStream = new MemoryStream(Encoding.UTF8.GetBytes(modifiedContent));
            message.Response.ContentStream = modifiedStream;
        }
    }
}
```

```csharp
public static class RequestExtensions
{
    public static bool QueryStringHasKeyValue(this Request request, string key, string value)
    {
        var queryCollection = AzureHttpUtility.ParseQueryString(request.Uri.Query);
        return queryCollection.TryGetValue(key, out string? queryValue) && queryValue == value;
    }
}
```

```csharp
public abstract class ResponseBodyModification
{
    public abstract bool IsMatch(HttpMessage message);
    public abstract string RewriteResponseBody(string responseBody);
}
```

```csharp
public class GetExportListWithRunHistory : ResponseBodyModificationRule
{
    public override bool IsMatch(HttpMessage message)
    {
        var request = message.Request;

        return request.Method == RequestMethod.Get
               && Regex.IsMatch(request.Uri.Path, "/providers/Microsoft.CostManagement/exports$")
               && message.Request.QueryStringHasKeyValue("$expand", "runHistory")
               && message.Request.QueryStringHasKeyValue("api-version", "2023-07-01-preview");
    }

    public override string RewriteResponseBody(string json)
    {
        // Parse the JSON into a JObject
        var jObject = JObject.Parse(json);
        var tokens = jObject.SelectTokens("$..value[*].properties.runHistory.value[?(@.type == null)]");
        foreach (var t in tokens)
        {
            t["type"] = "Microsoft.CostManagement/run";
        }
        // Convert the modified JObject back to a JSON string
        return jObject.ToString(Formatting.Indented);
    }
}
```

```csharp
public class GetExportWithRunHistory : ResponseBodyModificationRule
{
    public override bool IsMatch(HttpMessage message)
    {
        var request = message.Request;

        return request.Method == RequestMethod.Get
               && Regex.IsMatch(request.Uri.Path, "^.+/providers/Microsoft\\.CostManagement/exports/[a-z0-9-]+$")
               && message.Request.QueryStringHasKeyValue("$expand", "runHistory")
               && message.Request.QueryStringHasKeyValue("api-version", "2023-07-01-preview");
    }

    public override string RewriteResponseBody(string json)
    {
        // Parse the JSON object
        var jsonObject = JObject.Parse(json);

        var tokens = jsonObject.SelectTokens("$..properties.runHistory.value.[?(@.type == null)]");
        foreach (var t in tokens)
        {
            t["type"] = "Microsoft.CostManagement/run";
        }

        // Serialize the modified JSON object back to a string
        return jsonObject.ToString(Formatting.Indented);
    }
}
```

**Comment by annelo-msft** [comment]
@jeremysimmons, kudos on the great use of pipeline policies to work around this issue! 🎉

@jsquire, I'd love to look at some point at how we handle nulls in deserialization routines ... when I was looking at generating clients will nullable reference types annotations, I spotted some of these.  I'm not sure it would solve the issue of services sending invalid payloads, but it would be easier to understand where some of these issues are and communicate optionality of field values to client users via public APIs ... might be worth spending some cycles on if we can get to it.

**Comment by jeremysimmons** [comment]
@annelo-msft thanks! that's high praise coming from you... 

Please let me know if I can provide more details / context of what's going on.

**Comment by ArthurMa1978** [comment]
Hey @jeremysimmons, as you mentioned, this issue is a service side problem that the return value of a ArmResource doesn't follow the ARM definition. You can [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) to ask service team fix it. 
In the meantime, we can attempt a workaround using customization code. @HarveyLink , could you please assist with this?

**Comment by ArthurMa1978** [comment]
> [@jeremysimmons](https://github.com/jeremysimmons), kudos on the great use of pipeline policies to work around this issue! 🎉
> 
> [@jsquire](https://github.com/jsquire), I'd love to look at some point at how we handle nulls in deserialization routines ... when I was looking at generating clients with nullable reference type annotations, I spotted some things we might be able to address there. I'm not sure it would solve the issue of services sending invalid payloads, but it would be easier to understand where some of these issues are and communicate optionality of field values to client users via public APIs ... might be worth spending some cycles on if we can get to it.

Hey @annelo-msft , we don't need to handle this issue since `type` and `name` are required properties of a ArmResource model, and their values should never be null.

**Comment by jeremysimmons** [comment]
@ArthurMa1978 do you mean some other "customization code" different than what I suggested?
@HarveyLink do you have suggestions?

**Comment by jeremysimmons** [comment]
@annelo-msft Can you confirm that @ArthurMa1978 's suggestion to open [an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) is going to actually route to the team that owns the API service. My initial response from them seems to be someone supporting the Azure Portal (UI), and not the actual CostManagement API Service that the Azure.ResourceManager.CostManagement sdk package is acting as a client for. As a developer, it's frustrating to find a specific bug with the API response, and not be able to get in touch with the team that owns the API quickly...

**Comment by jsquire** [comment]
@jeremysimmons :  Unfortunately, that's not something that the maintainers of the Azure SDK have insight into nor influence over.   Support tickets generally start with the Microsoft support team.  I'd let them know that you're looking for the team that owns the ARM Resource Provider for Cost Management and that there's an error in their REST API.   You're welcome to tell them to reach out to me internally if they need additional context.

**Comment by jeremysimmons** [comment]
@jsquire THANK YOU! Knowing the "magic words" to speak in the support ticket is the first step. I really appreciate having people to engage via github. Thanks for everything and the rest of the team do.

> Unfortunately, that's not something that the maintainers of the Azure SDK have insight into nor influence over.

I wouldn't have expected that the teams would be so dramatically separated. It's big company though.

I think at this point, ya'll on the sdk team have done as much as possible, so I'll close the ticket.

**Comment by jsquire** [comment]
> I wouldn't have expected that the teams would be so dramatically separated. It's big company though.

Yeah, I understand how that would be confusing and frustrating.  Unfortunately, that gets accentuated for open-source products like the Azure SDK, where we're able to talk directly with you while service teams are required to go through the support channel.

**Comment by ArthurMa1978** [comment]
> [@ArthurMa1978](https://github.com/ArthurMa1978) do you mean some other "customization code" different than what I suggested? [@HarveyLink](https://github.com/HarveyLink) do you have suggestions?

It’s different. Your code provides an excellent workaround from a usage perspective. The customization code within the Azure SDK serves as a mechanism to handle some unexpected behaviors.

**Comment by jeremysimmons** [comment]
@ArthurMa1978 is the "customization code" something I'm expected to write? Do you have an example of the code?

**Comment by ArthurMa1978** [comment]
> [@ArthurMa1978](https://github.com/ArthurMa1978) is the "customization code" something I'm expected to write? Do you have an example of the code?

@HarveyLink will give a sample pr

**Comment by jeremysimmons** [comment]
@jsquire @ArthurMa1978 sorry to keep pinging you on a closed ticket. I got a reply from the azure service provider team, ticket #2410100040012460, but this makes no sense to me.

> Kindly note that the Engineering Team has reached indicating that our API always returns these properties as null which is being made by design. In this case, the Engineering Team suggested to please adjust the script to ignore these properties completely.

Can you please provide me some advice on how to tell them that these properties are Required by the Azure Resource model?

From what I can tell looking at the rest api specs, they should be included. They're not explicitly marked required, only "readonly". The Export entity uses the same base as ExportRun which is CostManagementProxyResource. It doesn't make sense that Export includes the properties but ExportRun does not...

runHistory is a property of CommonExportProperties
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2023-08-01/costmanagement.exports.json#L476

ExportExecutionListResult has items that are ExportRun
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2023-08-01/costmanagement.exports.json#L695

ExportRun includes allOf CostManagementProxyResource
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2023-08-01/costmanagement.exports.json#L714

CostManagementProxyResource defines 4 properties, id, name and type. They are all defined as "readonly". 
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2023-08-01/common-types.json#L165

The Export entities is also defined as having allOf CostManagementProxyResource
https://github.com/Azure/azure-rest-api-specs/blob/6e95d1f68657c6b1abfae889b6a12fe12ce67eaa/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2023-08-01/costmanagement.exports.json#L415

**Comment by jsquire** [comment]
Hi @jeremysimmons.   No worries at all.   I'm sorry this has been such a frustrating experience.  The friction in support process for these areas is certainly regrettable.  

@ArthurMa1978:  If I understand correctly, it looks like we've got an input-output type where the output is not returning data, but it is required for input so it would have to be artificially populated.   Is that a mismatch in the spec or in the generation?   It seems these should be symmetrical - either they're round-trip and always returned or they're not required for updates (which would require PATCH support, I believe.).     

I don't have a good feel for ARM contracts and would appreciate your thoughts.  Likewise, do we have an escalation path or contact that we can pursue?  I'd like to get our PM team following up if we've got an issue with the spec that blocks client scenarios.

**Comment by jeremysimmons** [comment]
Thank you Jesse. I think the annotation of "readonly" is correct. I don't expect to be able to change either the `name` or the `type`. 
I think the service team is mistaken in saying that the values are "null by design". I don't see how that could be valid.

**Comment by ArthurMa1978** [comment]
They should define 2 models for input and output instead of use one model.
