### ISSUE TITLE
[FEATURE REQ] support more values in CostManagementExportData for Export CreateOrUpdate

### ISSUE THREAD

**Issue by jeremysimmons** [Azure/azure-sdk-for-net#46536]
### Library name

Azure.ResourceManager.CostManagement

### Please describe the feature.

Support all parameters in Azure Portal in CreateOrUpdate operation
https://learn.microsoft.com/en-us/rest/api/cost-management/exports/create-or-update?view=rest-cost-management-2023-11-01&tabs=HTTP that are used/available in the Azure Portal

Currently, azure portal supports creating exports using newer formats like Parquet, but the Object Model in the SDK does not support many of these options.

```json
 {
     "properties": {
         "definition": {
             "dataSet": {
                 "configuration": {
                     "dataVersion": "2023-05-01",
                     "filters": []
                 }
             },
             "timeframe": "TheCurrentMonth",
             "type": "PriceSheet"
         },
         "deliveryInfo": {
             "destination": {
                 "container": "{{storageContainerName}}",
                 "rootFolderPath": "{{rootFolderPath}}",
                 "type": "AzureBlob",
                 "resourceId": "{{storageAccountResourceId}}"
             }
         },
         "schedule": {
             "recurrence": "Daily",
             "recurrencePeriod": {
                 "from": "{{recurrencePeriodFrom}}",
                 "to": "{{recurrencePeriodTo}}"
             },
             "status": "Active"
         },
         "format": "Parquet",
         "partitionData": true,
         "dataOverwriteBehavior": "OverwritePreviousReport",
         "compressionMode": "Snappy",
         "exportDescription": ""
     },
     "id": "{{exportResourceId}}",
     "name": "{{exportName}}",
     "type": "Microsoft.CostManagement/reports",
     "identity": {
         "type": "systemAssigned"
     },
     "location": "global"
 }
```

ExportFormatType only contains `Csv`, but is missing `Parquet`
TimeframeType is missing `TheCurrentMonth`

(arguable that's something I can just create a new ExportFormatType instance of)

The following don't have any representation

```json
         "partitionData": true,
         "dataOverwriteBehavior": "OverwritePreviousReport",
         "compressionMode": "Snappy",
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Hey @jeremysimmons , thank you for reporting this to us, unfortunately this issue is related to service side, so we are not able to help you with it, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) to ask service to update the spec and release a new SDK. 

Therefore, we are closing this issue for now. If you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.

**Comment by jeremysimmons** [comment]
@ArthurMa1978 I'm so confused. I thought this repository IS the azure SDK, so I'm confused why the service team needs to release something else called an sdk. Are you saying that the team that makes the CostManagement Service Provider has to release a new version of their API, including some artifacts (sdk), I think you're referring to the typespec files, that this repository/team consumes via code generation process? Is all that right?

**Comment by jeremysimmons** [comment]
@jsquire you previously helped me https://github.com/Azure/azure-sdk-for-net/issues/46510 with the right words to get the ticket routed to the correct team members with the azure support request. Can you help me with phrasing this so that I can get my ticket routed internally/correctly when opening the azure support request?

**Comment by jsquire** [comment]
@jeremysimmons :  Happy to help as I'm able.   In this case, I'm going to need a bit of help from Arthur to understand what needs to happen, as the management packages have a different development lifecycle.

@ArthurMa1978 : Can you help me understand what is needed from the service for this one?   Looking over the [REST API specs](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/cost-management/resource-manager/Microsoft.CostManagement/stable) for it, I'm seeing the latest stable as `2023-11-01`, which seems to have been added after the management package was released.

The latest `Azure.ResourceManager.CostManagement` package is [v1.0.1](),

**Comment by ArthurMa1978** [comment]
Hey @jeremysimmons, sorry I didn't explain it clearly. Here please file a ticket to ask service team update the swagger spec by adding: 'Parquet' to ExportFormatType and 'TheCurrentMonth' to TimeframeType. After these updates, they can release a new version of sdk.

**Comment by ArthurMa1978** [comment]
Oh, for this case, the `TimeframeType` and `ExportFormatType` are extensible enum, so it accept pass in a string value for any undefined enum value.
So you can give `TheCurrentMonth` and `Parquet` a try to see if it works well.

**Comment by jeremysimmons** [comment]
>Oh, for this case, the TimeframeType and ExportFormatType are extensible enum, so it accept pass in a string value for any undefined enum value.

Yes, specifying the value of the extensible enum method works... but doesn't address the issue that the current SDK version doesn't match what's being used in Azure Portal.

Do you have any other suggested work-around for the other values that are missing from the Request object model?
