### ISSUE TITLE
Debugging is misspelled

### ISSUE THREAD

**Issue by brandonavant** [Azure/azure-sdk-for-net#46532]
### Type of issue

Typo

### Description

The word "debugging" is misspelled as "debuging".

![Image](https://github.com/user-attachments/assets/dedd5145-91a7-4676-9ef8-19824735a2a7)

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.client.feedoptions.populateindexmetrics?view=azure-dotnet

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Client/FeedOptions.xml

### Document Version Independent Id

e8cc925f-1ade-1426-909b-75999db0b108

### Article author

@azure-sdk

### Metadata

* ID: 0ea0435a-66b6-48b0-e701-e1f1ffea5876 
* Service: **azure-cosmos-db**

**Comment by jsquire** [comment]
Hi @brandonavant.  Thank you for reaching out and for catching the spelling mistake.  

Unfortunately, the documentation for API listings is controlled by the source code of the library itself and requires release of a new package version to correct.  In this case, the `Microsoft.Azure.Documents.Client` package reached end of life and is no longer published nor supported by Microsoft, so we won't be able to fix the spelling error in the deprecated documentation.
