### ISSUE TITLE
Can you download a figure similar to the functionality in Document Intelligence Studio?

### ISSUE THREAD

**Issue by dccrain** [Azure/azure-sdk-for-net#46552]
### Library name and version

Azure.AI.DocumentIntelligence 1.0.0-beta.3

### Query/Question

Currently in Document Intelligence Studio, once a document is analyzed you can download figures from the document as .png files
 ![Image](https://github.com/user-attachments/assets/1c16cfaa-e57d-4688-9a9a-b80d4b39f5e0)

Is this functionality supported by the latest version of this package? If not is this something that is planned for future support? I would like to be able to send a document and extract the images from it for direct handling and use.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by kinelski** [comment]
Hello @dccrain,

This feature is currently supported by the SDK version you're using. The following snippet illustrates how to use it:
```cs
// Specify the output options to enable figure extraction.
IEnumerable<AnalyzeOutputOption> outputOptions = new[] { AnalyzeOutputOption.Figures };
Operation<AnalyzeResult> analyzeOperation = client.AnalyzeDocument(WaitUntil.Completed, <model-id>, <content>, output: outputOptions);
AnalyzeResult result = analyzeOperation.Value;

// All extracted figures should be listed in 'result.Figures'. Suppose we want to download the figure at index 1:
string figureId = result.Figures[1].Id;

// Get a BinaryData instance with the bytes of the figure.
Response<BinaryData> response = client.GetAnalyzeResultFigure(<model-id>, new Guid(analyzeOperation.Id), figureId);
BinaryData data = response.Value;
```
