### ISSUE TITLE
Azure.Provisioning: Remove `BicepValue<T>` for models

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#46557]
### Library name

Azure.Provisioning

### Please describe the feature.

Using `BicepValue<T>` for model types results in a lot of unnatural `foo.Value!.Bar.Value!.Baz`.  Models deriving from `ProvisioningConstruct` should encapsulate the `T | Expression` concept so we only have to write `foo.Bar.Baz`.

**Comment by ArcturusZhang** [comment]
:( it turns out that, despite we removed this pattern for normal properties, but this pattern remains for collection types.
For instance, in `BicepList<Model>`, we still have `BicepValue<Model> item = list[0];` which also leads to some unnecessary `item.Value!.Property` expressions.
