### ISSUE TITLE
[BUG] Azure Functions - Azure.Core: Could not load file or assembly 'System.Memory.Data, Version=6.0.0.0

### ISSUE THREAD

**Issue by fhtino** [Azure/azure-sdk-for-net#46577]
### Library name and version

 Azure.Data.Tables 12.9.1 and Azure.Storage.Blobs 12.22.2

### Describe the bug

Cannot use Azure.Data.Tables and Azure.Storage.Blobs in the same Azure Functions project in VS 2022. When I use the TableClient I get 

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Memory.Data, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'System.Memory.Data, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at Azure.Core.RequestContent.Create(Object serializable, ObjectSerializer serializer)
   at Azure.Core.RequestContent.Create(Object serializable)
   at Azure.Data.Tables.TableClient.CreateIfNotExistsAsync(CancellationToken cancellationToken)
   at azfunct1.HelloWorld.Run(HttpRequest req, ILogger log) in xxxxxxx\az-func-cannot-load-assembly\azfunct1\HelloWorld.cs:line 29
```

```
var tsc = new TableServiceClient("UseDevelopmentStorage=true");
var tabc = tsc.GetTableClient("zzztest1");
await tabc.CreateIfNotExistsAsync();
```

Sample project with the issue:
https://github.com/fhtino/publicissues/tree/main/az-func-cannot-load-assembly

Workaround: place _FunctionsSkipCleanOutput in the project file:

```
<PropertyGroup>
	<_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
```

### Expected behavior

no errors

### Actual behavior

Exception: System.Memory.Data, Version=6.0.0.0  not found

### Reproduction Steps

sample here:  https://github.com/fhtino/publicissues/tree/main/az-func-cannot-load-assembly

### Environment

 - Visual Studio 2022 17.11.5
 - Azure Functions Core Tools / Core Tools Version: 4.0.6518 (64-bit) / Function Runtime Version: 4.35.4.23179

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the Azure Functions worker for .NET is maintained as [#2776](https://github.com/Azure/azure-functions-dotnet-worker/issues/2776).
