### ISSUE TITLE
Does Azure OpenAI has auto-retry policy for certain error codes?

### ISSUE THREAD

**Issue by OfirD1** [Azure/azure-sdk-for-net#46612]
### Library name and version

Azure OpenAI

### Query/Question

The openai-dotnet library has an [auto-retry policy](https://github.com/openai/openai-dotnet?tab=readme-ov-file#automatically-retrying-errors) for several error codes.

Does Azure OpenAI has the same policy? If not, is there a standard way to set up such policy?

**Comment by AngelosP** [comment]
Yes, you can expect the same behavior from the AzureOpenAI client as well (the client is told how long to wait for through HTTP headers).

/cc @trrwilson in case there are any interesting differences worth pointing out.

**Comment by trrwilson** [comment]
@AngelosP is correct -- `Azure.AI.OpenAI` uses the same underlying logic to control its retry behavior as the `OpenAI` library, and each of them use the default `IsRetriableResponse()` implementation of `ResponseClassifier`, as viewable here:

https://github.com/Azure/azure-sdk-for-net/blob/14d976613655cbf181c50215ffc04b7ab0031ca5/sdk/core/Azure.Core/src/ResponseClassifier.cs#L22

That code link is the original source for that documented list:

```csharp
            switch (message.Response.Status)
            {
                case 408: // Request Timeout
                case 429: // Too Many Requests
                case 500: // Internal Server Error
                case 502: // Bad Gateway
                case 503: // Service Unavailable
                case 504: // Gateway Timeout
                    return true;
                default:
                    return false;
            }
```

The only notable addition to retry behavior for `Azure.AI.OpenAI` is that it extends the default retry behavior to retrieve and honor the values in the `retry-after-ms`, `x-ms-retry-after-ms`, or `Retry-After` response headers; source for that here:

https://github.com/Azure/azure-sdk-for-net/blob/14d976613655cbf181c50215ffc04b7ab0031ca5/sdk/openai/Azure.AI.OpenAI/src/Custom/AzureOpenAIClientOptions.cs#L101

**Comment by OfirD1** [comment]
Great to know, thanks!
