### ISSUE TITLE
Able to create service bus with the same name with the Fluent SDK

### ISSUE THREAD

**Issue by KeishaW** [Azure/azure-sdk-for-net#4661]
I'm using this to create a service bus using the Fluent SDK:

```
var serviceBusNamespace = azure.ServiceBusNamespaces
                            .Define(serviceBusName)
                            .WithRegion(Region)
                            .WithExistingResourceGroup(resourceGroup)
                            .WithSku(NamespaceSku.Standard)
                            .Create();
```
If I run this code for two different resource groups using the same serviceBusName, I get a service bus created in both resources groups without error. However when I go to the Azure portal the first service bus opens fine, but I get an error saying 'Not Found' when trying to open the second.

I understand that servicebus names must be unique across all of Azure, but why is the Fluent SDK allowing me to create the second service bus with the same name?

**Comment by SeanFeldman** [comment]
@KeishaW are you running the snippet above concurrently when running into this issue?

**Comment by KeishaW** [comment]
@SeanFeldman no I am not. I run the snippet the first time, to the get the first service bus. And after it is created and I see it in the Azure portal, I run it again without error.

**Comment by SeanFeldman** [comment]
Sounds like a bug.
If only issues were triaged here in a timely mannor...

**Comment by SeanFeldman** [comment]
Maybe @shahabhijeet @hovsepm @cormacpayne can help here.

**Comment by hovsepm** [comment]
@KeishaW please reopen the issue in the Fluent SDK repo here https://github.com/Azure/azure-libraries-for-net/
