### ISSUE TITLE
[QUERY] workload identity through Azure ADO pipeline service connection

### ISSUE THREAD

**Issue by yanggaome** [Azure/azure-sdk-for-net#46622]
### Library name and version

azure.identity 1.11.4

### Query/Question

Hello,

we are using **AzureCLI2** ADO task and pass in a service connection through **azureSubscription** parameter.

In this AzureCLI2 task, we are using **dotnet test** command for unit testing.

In our C# unit tests, we are using DefaultAzureCredential.

We tried
`var credential = new DefaultAzureCredential(new DefaultAzureCredentialOptions { WorkloadIdentityClientId = "xxx", TenantId = "xxx"});`

or

`var credential = new DefaultAzureCredential(new DefaultAzureCredentialOptions { ManagedIdentityClientId = "xxx" });`

But neither seems working. What is the correct way to use workload identity in C# code? 

Thanks

**Comment by christothes** [comment]
Hi @yanggaome - Can you describe a bit more about your scenario? 

If you are intending to utilize the service connection to interact with Azure resources, you may want to consider using the `DotNetCoreCLI@2` task along with the [AzurePipelinesCredential](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.azurepipelinescredential?view=azure-dotnet).
