### ISSUE TITLE
[FEATURE REQ] Add support filtering of resource group (azure api supports it)

### ISSUE THREAD

**Issue by shellby1** [Azure/azure-sdk-for-net#46631]
### Library name

Azure.ResourceManager.dll

### Please describe the feature.

Azure api supports resource group filtering due to documentation [Resource Groups - List](https://learn.microsoft.com/en-us/rest/api/resources/resource-groups/list?view=rest-resources-2021-04-01) 

`GET https://management.azure.com/subscriptions/{subscriptionId}/resourcegroups?$filter={$filter}&$top={$top}&api-version=2021-04-01`

But [GetResourceGroupAsync(resourceGroupName, cancellationToken)](https://github.com/Azure/azure-sdk-for-net/blob/7e36a3b42dd24dd1e6399ba57d0cd3e40c2cbef6/sdk/resourcemanager/Azure.ResourceManager/src/Resources/Generated/SubscriptionResource.cs#L347) supports only filtering by name.

Could you please add filtering resource groups like it did for [GetGenericResourcesAsync(string filter, expand, top, cancellationToken)](https://github.com/Azure/azure-sdk-for-net/blob/7e36a3b42dd24dd1e6399ba57d0cd3e40c2cbef6/sdk/resourcemanager/Azure.ResourceManager/src/Resources/Custom/SubscriptionResource.cs#L29)

**Comment by HarveyLink** [comment]
Hi @shellby1 , the feature you are looking for is: https://github.com/Azure/azure-sdk-for-net/blob/f5a45365f5560f5c6b1a542f740bd2e8ccaae584/sdk/resourcemanager/Azure.ResourceManager/src/Resources/Generated/ResourceGroupCollection.cs#L271

**Comment by shellby1** [comment]
unfortunately it doesn't support for multiple tags filtering as REST api declares https://learn.microsoft.com/en-us/rest/api/resources/resource-groups/list?view=rest-resources-2021-04-01#uri-parameters

**Comment by HarveyLink** [comment]
> unfortunately it doesn't support for multiple tags filtering as REST api declares https://learn.microsoft.com/en-us/rest/api/resources/resource-groups/list?view=rest-resources-2021-04-01#uri-parameters

If the rest api doesn't support it, neither will the SDK. The SDK is auto generated based on RestAPI.
