### ISSUE TITLE
[BUG] Cannot create private DNS zone using SDK

### ISSUE THREAD

**Issue by youn123** [Azure/azure-sdk-for-net#46646]
### Library name and version

Azure.ResourceManager.Dns 1.2.0-beta.1

### Describe the bug

Getting 

```
 Creation of private DNS zones using this API is no longer allowed. Please use privatednszones resource instead of dnszones resource.
```

when trying to create private DNS zone with following codes:

```cs
var dnsZones = resourceGroupResource.GetDnsZones();
var dnsZoneData = new DnsZoneData("Global")
{
    ZoneType = DnsZoneType.Private
};

await dnsZones.CreateOrUpdateAsync(WaitUntil.Completed, "privatelink.redisenterprise.cache.azure.net", dnsZoneData);
```

### Expected behavior

Expect DNS Zone to be created successfully

### Actual behavior

DNS Zone does not create successfully

### Reproduction Steps

See bug description

**Comment by ArthurMa1978** [comment]
Hey @youn123 , thank you for reaching out to us about the Azure SDK for .Net, for your issue please try the [Azure.ResourceManager.PrivateDns](https://www.nuget.org/packages/Azure.ResourceManager.PrivateDns) lib.
