### ISSUE TITLE
[BUG][Web PubSub]Web PubSub Cilent fail to authenticate with token credential in China Cloud

### ISSUE THREAD

**Issue by abramsz** [Azure/azure-sdk-for-net#46661]
We are running live Tests in Azure China Cloud. The goal is to check whether new azure sdk package could work with Azure China Cloud or not.
In https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/webpubsub/Azure.Messaging.WebPubSub/src/WebPubSubServiceClient_extensions.cs#L117 as follow.

![Image](https://github.com/user-attachments/assets/069a056b-d734-448a-a8a0-68a9634d7d3c)

The scope is hard code as 'https://webpubsub.azure.com/.default' leading to only work well in the public cloud.

The value of the scope in different clouds is follow:
Azure public cloud: https://webpubsub.azure.com/.default
China cloud: https://webpubsub.azure.cn/.default

AZURE_AUTHORITY_HOST setting:
Public Cloud : https://login.microsoftonline.com/
China Cloud: https://login.partner.microsoftonline.cn/

This bug is similar to the BUG from Text Analytics sdk:
https://github.com/Azure/azure-sdk-for-net/issues/18520

**Comment by vicancy** [comment]
Adding @chuongnguyen to take a look.

**Comment by cqnguy23** [comment]
For this issue, I think we can add another field like `AuthenticationScope` in the `WebPubSubServiceClientOptions` to let users decide which scope they could use when creating client, similar to what the Text Analytics team did [here](https://github.com/Azure/azure-sdk-for-net/pull/26583/files). What do you think @vicancy ?

**Comment by vicancy** [comment]
> For this issue, I think we can add another field like `AuthenticationScope` in the `WebPubSubServiceClientOptions` to let users decide which scope they could use when creating client, similar to what the Text Analytics team did [here](https://github.com/Azure/azure-sdk-for-net/pull/26583/files). What do you think [@vicancy](https://github.com/vicancy) ?

Sounds good to me. Hi @jsquire , how do you feel about it? Is there a general effort/guidance/pattern in the SDK side for this different cloud scope issue?

**Comment by jsquire** [comment]
That's generally the pattern that we've seen.   You'll want to get thoughts from @KrzysztofCwalina and @tg-msft as the language architects.

**Comment by cqnguy23** [comment]
> For this issue, I think we can add another field like `AuthenticationScope` in the `WebPubSubServiceClientOptions` to let users decide which scope they could use when creating client, similar to what the Text Analytics team did [here](https://github.com/Azure/azure-sdk-for-net/pull/26583/files). What do you think [@vicancy](https://github.com/vicancy) ?

Hi @tg-msft and @KrzysztofCwalina, please let me know if you have any concerns with this approach, if not I'll go ahead and start with the implementation

**Comment by cqnguy23** [comment]
Actually just did some further investigation and it seems that our service uses the same scope for all clouds. @abramsz could you tell us what error you might be experiencing? It's possible that AAD Credential might not be configured correctly when initiating the service client

**Comment by cqnguy23** [comment]
I used this code snippet to invoke a method in a resource in Mooncake and it seems to work alright. Please make sure your AAD credentials are not overridden by other configs (such as Visual Studio/Visual Studio Code config)
```c#
var option = new DefaultAzureCredentialOptions
{
    AuthorityHost = AzureAuthorityHosts.AzureChina,
};
var credential = new DefaultAzureCredential(option);
var serviceClient = new WebPubSubServiceClient(new Uri("https://testresource.webpubsub.azure.cn"), "chat", credential);
var token = await serviceClient.GetClientAccessUriAsync();
```

**Comment by abramsz** [comment]
> I used this code snippet to invoke a method in a resource in Mooncake and it seems to work alright. Please make sure your AAD credentials are not overridden by other configs (such as Visual Studio/Visual Studio Code config)
> 
> var option = new DefaultAzureCredentialOptions
> {
>     AuthorityHost = AzureAuthorityHosts.AzureChina,
> };
> var credential = new DefaultAzureCredential(option);
> var serviceClient = new WebPubSubServiceClient(new Uri("https://testresource.webpubsub.azure.cn"), "chat", credential);
> var token = await serviceClient.GetClientAccessUriAsync();

Let me clarify our scenario, we have a app service as client, and azure webpub service, both shared with a MSI , the credential should be MSI creadential.

**Comment by abramsz** [comment]
> I used this code snippet to invoke a method in a resource in Mooncake and it seems to work alright. Please make sure your AAD credentials are not overridden by other configs (such as Visual Studio/Visual Studio Code config)
> 
> var option = new DefaultAzureCredentialOptions
> {
>     AuthorityHost = AzureAuthorityHosts.AzureChina,
> };
> var credential = new DefaultAzureCredential(option);
> var serviceClient = new WebPubSubServiceClient(new Uri("https://testresource.webpubsub.azure.cn"), "chat", credential);
> var token = await serviceClient.GetClientAccessUriAsync();

We have use DefaultAzureCredential to replace ManagedIdentityCredential, it works now. 
Thanks 

@cqnguy23 
Is there any need to do this fix now?
