### ISSUE TITLE
Either wrong comment or BUG

### ISSUE THREAD

**Issue by edsonschmitt** [Azure/azure-sdk-for-net#46692]
While I was searching the code base for reasons why my tests would break under Azure.Identity 1.13 I came across the linked piece of code ... 

I do not believe this is the reason for the change in behavior I'm experiencing but the discrepancy between the comment and the code jumped at me.

https://github.com/Azure/azure-sdk-for-net/blob/d0aadf70031d8bb14d62a2c81e9ce1de8e967e53/sdk/identity/Azure.Identity/src/AppServiceManagedIdentitySource.cs#L25C1-L30C14

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
This code is actually deprecated in 1.13.0, so it shouldn't be relevant.
