### ISSUE TITLE
[FEATURE REQ] Additional methods for schema management on SchemaRegistryClient

### ISSUE THREAD

**Issue by Georgi-Ivanov-Fourth** [Azure/azure-sdk-for-net#46708]
### Library name

Azure.Data.SchemaRegistry

### Please describe the feature.

There are 2 things, which I am missing right now:
- there is no method to get schema versions, so that I know which is the latest one and how many are there (especially if you are limited to 25)
- it is not possible to "probe" a schema, before registering it - this make it quite tedious to plug this a step in the CI/CD pipeline. Schemas can't be validated, can't be checked against the schema group compatibility mode - the only way is to try, register it and check for errors

**Comment by jsquire** [comment]
Hi @Georgi-Ivanov-Fourth.  Thank you for reaching out and we regret that you're experiencing difficulties.  Unfortunately, the maintainers of the Azure SDK packages are unable to assist with this feature request.

The additional operations that you're asking for are not currently supported by the Schema Registry service.   To ensure that the Schema Registry service team has visibility and can help with your request, your best path forward for would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) or inquire on the [Azure Feedback site](https://feedback.azure.com/d365community).

I'm going to close this out; if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.
