### ISSUE TITLE
[BUG] Azure.Monitor.OpenTelemetry SDK incorrectly reports HTTPS `url` as HTTP in Application Insights request logs

### ISSUE THREAD

**Issue by DrEsteban** [Azure/azure-sdk-for-net#46726]
### Library name and version

Azure.Monitor.OpenTelemetry.AspNetCore 1.3.0-beta.2

### Describe the bug

I have an ASP.NET app hosted in Azure WebApps for Linux. When using the OpenTelemetry SDK to log telemetry for my app to Application Insights, if I look at the `requests` table I see the `url` column being reported as `**http://**my.webapp.com`. Even though clients are definitely connecting using HTTPS, and I'm using Forwarded Headers middleware to ensure the HttpContext values are populated correctly. (Due to running in WebApps)

Interestingly, if I use the native AppInsights SDK, _it_ correctly reports the URL w/ `https://`. It's just the OpenTelemetry SDK that seems to get it wrong.

Here's an example screenshot:
![Image](https://github.com/user-attachments/assets/f82fd083-3617-42eb-9608-3511b0666019)
I've added both the OpenTelemetry and AppInsights SDKs to my app, so requests are being double-logged. Note these 2 requests, each logged twice, but the slightly different `url` fields in each. The ones correctly reporting as `https://` is the AppInsights-generated log, and the ones reporting as `http://` are the OpenTelemetry ones.

### Expected behavior

I expect the behavior to match the native `Microsoft.ApplicationInsights.AspNetCore` SDK and correctly report the `url` field based on the client's connection to the web app.

### Actual behavior

Whether clients connect with HTTP or HTTPS, the `url` field always reports `http://`

### Reproduction Steps

Create an ASP.NET app with `Azure.Monitor.OpenTelemetry.AspNetCore` configured using the recommended defaults. For comparison, also include the latest `Microsoft.ApplicationInsights.AspNetCore` SDK and configure as well.

E.g.
```csharp
builder.Services.AddOpenTelemetry().UseAzureMonitor();
builder.Services.AddApplicationInsightsTelemetry();
```

### Environment

.NET 8.0, running on Azure WebApps for Linux. Logging to a standard Application Insights instance.

### Related

This is related to #42850 and the spun off #44687 

UPDATE: I just logged an issue on the underlying SDK `OpenTelemetry.Instrumentation.AspNetCore`: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/2231. Hopefully between the 2 of you we can get this issue resolved :)

**Comment by DrEsteban** [comment]
I believe this might be a defect/faulty assumption in the underlying `OpenTelemetry.Instrumentation.AspNetCore` SDK. I've logged an issue there as well: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/2231

**Comment by TimothyMothra** [comment]
> Hopefully between the 2 of you we can get this issue resolved :)

Actually, it's me in both places :D
One of my roles is to make sure issues are opened against the correct component.

THIS repo (Azure-sdk) is only for the AzureMonitor components.
As we discussed in https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/2231, I don't think the bug is with the AzureMonitor library. I'm going to close THIS issue and continue the conversation in the OTel repo.

If you think I've misunderstood something and you want to continue discussing this issue as it pertains to Azure Monitor, please feel free to comment here and we can reopen the issue.
