### ISSUE TITLE
Proxy in TokenCredentialOptions.Transport not being used

### ISSUE THREAD

**Issue by ssteiner** [Azure/azure-sdk-for-net#46731]
### Describe the bug

I recently ran into [this issue with Token requests not going through the proxy](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2032). I was using the same code, with one exception: Instead of providing an instance of ` ClientSecretCredentialOptions` to the `ClientSecretCredential`, I had a `TokenCredentialOptions` instance. 

I was then getting a timeout every time I was trying to access any API method on a machine that only allowed internet access through a proxy - it was the login that was timing out. `Netstat -a` showed that a connection was attempted directly to login.microsoftonline.com, instead of through the proxy.

Because the code at first glance looked just like the code in the linked issue, I didn't even register that I was doing something different. It seems weird to me that `TokenCredentialOptions` has the same Transport property, but in that case, the proxy config is not heeded.

### Expected behavior

I would have expected the request to get the token to also pass through the proxy I provided.

### How to reproduce

Instantiate the GraphServiceClient as follows:

```
var proxy = GetWebProxy();
var handler = new HttpClientHandler
{
    Proxy = proxy,
    UseProxy = proxy != null
};
var options = new TokenCredentialOptions 
{
  AuthorityHost = AzureAuthorityHosts.AzurePublicCloud,
  Transport = new HttpClientTransport(handler)
};
var credential = new ClientSecretCredential(config.TenantId, config.ClientId, config.ClientSecret, options);
var httpClient = GraphClientFactory.Create(proxy: proxy);
graphServiceClient = new GraphServiceClient(httpClient, new Microsoft.Kiota.Authentication.Azure.AzureIdentityAuthenticationProvider(credential));
```

### SDK Version

MS Graph SDK 5.60.0
Azure.Identity 1.13.0

### Known Workarounds

if I define `options` in the code above as follows, things work out just fine

```
var options = new ClientSecretCredentialOptions
{
    Transport = new HttpClientTransport(handler)
};
```

### Configuration

OS: Win11 Pro 23H2 64bit on .NET 8.0.10

P.S. I initially opened this in the MS Graph SDK repo but was told to file here since the affected classes are part of not part of the MS Graph SDK but rather fit here.

**Comment by christothes** [comment]
Hi @ssteiner - 
I tried to reproduce this but the Proxy is used in both cases for me. 

```c#
public async Task VerifyCustomProxy()
{
    using AzureEventSourceListener listener = AzureEventSourceListener.CreateConsoleLogger();
    var handler = new HttpClientHandler
    {
        Proxy = new MyProxy(),
        UseProxy = true
    };
    // switch between the two options types by commenting one or the other below
    var options = new TokenCredentialOptions
    // var options = new ClientSecretCredentialOptions
    {
        AuthorityHost = AzureAuthorityHosts.AzurePublicCloud,
        Transport = new HttpClientTransport(handler)
    };
    var credential = new ClientSecretCredential(Guid.NewGuid().ToString(), Guid.NewGuid().ToString(), Guid.NewGuid().ToString(), options);

    await credential.GetTokenAsync(new TokenRequestContext(MockScopes.Default));

    await Task.CompletedTask;
}

public class MyProxy : IWebProxy
{
    // breakpoint set here is always hit.
    public Uri GetProxy(Uri destination) => new Uri("http://localhost:8888");

    public bool IsBypassed(Uri host) => false;

    public ICredentials Credentials { get; set; }
}
```

Can you confirm if this simplified repro also works for you?
