### ISSUE TITLE
ChangeNumber property in ServiceTagsListResult is set as String but in the service tags json it is a Number

### ISSUE THREAD

**Issue by kennyvanle** [Azure/azure-sdk-for-net#46757]
### Type of issue

Typo

### Description

The [ChangeNumber](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.management.network.models.servicetagslistresult.changenumber?view=azure-dotnet#microsoft-azure-management-network-models-servicetagslistresult-changenumber) property is listed as a string

![Image](https://github.com/user-attachments/assets/031097e5-8686-4739-ac5b-6064227defbb)

The service tags json documents listed here has these set as Number: https://learn.microsoft.com/en-us/azure/virtual-network/service-tags-overview

![Image](https://github.com/user-attachments/assets/2978dde6-ca4b-4e79-94ae-5676265ff33a)

example: ![Image](https://github.com/user-attachments/assets/c8d77807-f485-4631-b0d6-3432cafb32af)

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.management.network.models.servicetagslistresult.changenumber?view=azure-dotnet#microsoft-azure-management-network-models-servicetagslistresult-changenumber

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.Network.Models/ServiceTagsListResult.xml

### Document Version Independent Id

79ae2a1c-b47d-92a3-a60e-8e240aeca04b

### Article author

@azure-sdk

### Metadata

* ID: 408737ea-f263-c4b7-f683-6397f240aae9 
* Service: **azure-virtual-network**

**Comment by jsquire** [comment]
Hi @kennyvanle.  Thanks for reaching out and we regret that you're experiencing difficulties.   The `Microsoft.Azure.Management.Network` package reached end of life in September 2023 and is no longer published nor supported by Microsoft.   We strongly recommend not using this package and moving to  the current generation equivalent, `Azure.ResourceManager.Network`.
