### ISSUE TITLE
Add AutoRest modules/Node versions info to SdkInfo_*.cs

### ISSUE THREAD

**Issue by dsgouda** [Azure/azure-sdk-for-net#4676]
We could do with knowing all the AutoRest module versions used to generate code (eg.: modeler, csharp generator, etc) so that we can diagnose problems with code generation quicker

**Comment by jsquire** [comment]
Management pipelines and code generation processes have changed since this issue was filed.   Closing.   

//fyi: @ArthurMa1978 - please feel free to reopen if this is still a desired feature.
