### ISSUE TITLE
[BUG] AnalyzeCustomHostnameAsync improperly parsed from JSON

### ISSUE THREAD

**Issue by infoTrainingym** [Azure/azure-sdk-for-net#46781]
### Library name and version

Azure.ResourceManager.AppService 1.2.0

### Describe the bug

**Type of issue**

Code doesn't work

**Description**

I am trying to use the `AnalyzeCustomHostnameAsync` function to check if a domain is correctly configured. The request is made successfully, and the response is received correctly, but when parsing the response to `CustomHostnameAnalysisResult`, it is not done correctly.

This causes the SDK to return all properties as null.

### Expected behavior

Correctly parse the properties of the model.

### Actual behavior

The request response is:

```json
{
  "isHostnameAlreadyVerified":true,
  "customDomainVerificationTest":"Passed",
  "hasConflictOnScaleUnit":false,
  "hasConflictAcrossSubscription":false,
  "cNameRecords":["xxxxxx.azurewebsites.net"],
  "aRecords":["xx.xx.xx.xx"],
  "domainLevel":"Subdomain",
  "tld":"com"
}
```

However, the method `CustomHostnameAnalysisResult.DeserializeCustomHostnameAnalysisResult` expects a `properties` block, which includes all the properties of the response (`isHostnameAlreadyVerified`, `customDomainVerificationTest`, etc.).

![Image](https://github.com/user-attachments/assets/adb2ef7b-9ac1-42c7-9bfa-cbd675989e32)

### Reproduction Steps

```c#
ArmClient client = new ArmClient(new DefaultAzureCredential());

ResourceIdentifier id = new ResourceIdentifier(this.identifierWebapp);

WebSiteResource websiteResource = client.GetWebSiteResource(id);

CustomHostnameAnalysisResult response = await websiteResource.AnalyzeCustomHostnameAsync(hostname);

// response.IsHostnameAlreadyVerified is null
```

**Comment by jsquire** [comment]
Hi @infoTrainingym.  Thanks for reaching out and we regret that you're experiencing difficulties.   This looks to be a problem with the service not following its published API for the operation, which is not something that the maintainers of the Azure SDK can assist with.  This will require investigation and fixes in the service itself.

Unfortunately, the AppServices service team does not monitor nor respond to issues in this repository, nor can we directly transfer to them.  To ensure that the right team has visibility and can help, your best path forward for would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) or inquire on the [Microsoft Q&A site](https://learn.microsoft.com/answers/questions/).  

I'm going to close this out; if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.

## Analysis

- Version 1.2.0 of Azure.ResourceManager.AppServices is built on service API version 2023-12-01, which defines the `AnalyzeCustomHostName` operation on [L349](https://github.com/Azure/azure-rest-api-specs/blob/928047803788f7377fa003a26ba2bdc2e0fcccc0/specification/web/resource-manager/Microsoft.Web/stable/2023-12-01/WebApps.json#L349).   The result of that operation is defined as `#/definitions/CustomHostnameAnalysisResult`

-`#/definitions/CustomHostnameAnalysisResult` is defined on [L25354](https://github.com/Azure/azure-rest-api-specs/blob/928047803788f7377fa003a26ba2bdc2e0fcccc0/specification/web/resource-manager/Microsoft.Web/stable/2023-12-01/WebApps.json#L25354) and defines those fields as belonging to a `properties` block.   _(see: [L25632](https://github.com/Azure/azure-rest-api-specs/blob/928047803788f7377fa003a26ba2bdc2e0fcccc0/specification/web/resource-manager/Microsoft.Web/stable/2023-12-01/WebApps.json#L25362))_
```json
 "CustomHostnameAnalysisResult": {
      "description": "Custom domain analysis.",
      "type": "object",
      "allOf": [
        {
          "$ref": "./CommonDefinitions.json#/definitions/ProxyOnlyResource"
        }
      ],
      "properties": {
        "properties": {
          "description": "CustomHostnameAnalysisResult resource specific properties",
          "type": "object",
          "properties": {
            "isHostnameAlreadyVerified": {
              "description": "<code>true</code> if hostname is already verified; otherwise, <code>false</code>.",
              "type": "boolean",
              "readOnly": true
            },
            "customDomainVerificationTest": {
              "description": "DNS verification test result.",
              "enum": [
                "Passed",
                "Failed",
                "Skipped"
              ],
              "type": "string",
              "readOnly": true,
              "x-ms-enum": {
                "name": "DnsVerificationTestResult",
                "modelAsString": false
              }
            },
            "customDomainVerificationFailureInfo": {
              "$ref": "./CommonDefinitions.json#/definitions/ErrorEntity",
              "description": "Raw failure information if DNS verification fails.",
              "readOnly": true
            },

            // .. << SNIP FOR BREVITY >>
      }
    },
```

- The specification includes an example [AnalyzeCustomHostName.json](https://github.com/Azure/azure-rest-api-specs/blob/928047803788f7377fa003a26ba2bdc2e0fcccc0/specification/web/resource-manager/Microsoft.Web/stable/2023-12-01/examples/AnalyzeCustomHostName.json) operation, demonstrating the request/response for the call.   That conforms to the spec and returns those fields in a `properties` block.  _(see: [L15](https://github.com/Azure/azure-rest-api-specs/blob/928047803788f7377fa003a26ba2bdc2e0fcccc0/specification/web/resource-manager/Microsoft.Web/stable/2023-12-01/examples/AnalyzeCustomHostName.json#L15))_
```json
"responses": {
    "200": {
      "headers": {},
      "body": {
        "id": "/subscriptions/34adfa4f-cedf-4dc0-ba29-b6d1a69ab345/resourceGroups/testrg123/providers/Microsoft.Web/sites/sitef6141",
        "name": "sitef6141",
        "type": "Microsoft.Web/sites",
        "properties": {
          "isHostnameAlreadyVerified": true,
          "customDomainVerificationTest": "Passed",
          "customDomainVerificationFailureInfo": {
            "code": "07198",
            "message": "Custom domain verification failed on conflicting CNAMEs."
          },
          "hasConflictOnScaleUnit": false,
          "hasConflictAcrossSubscription": true,
          "conflictingAppResourceId": "/subscriptions/34adfa4f-cedf-4dc0-ba29-b6d1a69ab345/resourceGroups/testrg123/providers/Microsoft.Web/sites/siteog",
          "cNameRecords": [
            "siteog.azurewebsites.net"
          ]
        }
      }
```
