### ISSUE TITLE
[BUG] FabricClient.Core.Git.GetConnectionAsync throws null reference exception if connection has never been synced

### ISSUE THREAD

**Issue by mikegoatly** [Azure/azure-sdk-for-net#46788]
### Library name and version

Microsoft.Fabric.Api 1.0.0-beta10

### Describe the bug

If the `gitSyncDetails` property in the response contains `null` for the `lastSyncTime`, then the following exception is thrown:

```
System.ArgumentNullException: 'Value cannot be null. (Parameter 'input')'
This exception was originally thrown at this call stack:
    System.ThrowHelper.ThrowArgumentNullException(System.ExceptionArgument)
    System.DateTimeOffset.Parse(string, System.IFormatProvider, System.Globalization.DateTimeStyles)
    Microsoft.Fabric.Api.Core.ModelSerializationExtensions.TypeFormatters.ParseDateTimeOffset(string, string)
    Microsoft.Fabric.Api.Core.ModelSerializationExtensions.GetDateTimeOffset(System.Text.Json.JsonElement, string)
    Microsoft.Fabric.Api.Core.Models.GitSyncDetails.DeserializeGitSyncDetails(System.Text.Json.JsonElement)
    Microsoft.Fabric.Api.Core.Models.GitConnection.DeserializeGitConnection(System.Text.Json.JsonElement)
    Microsoft.Fabric.Api.Core.GitRestClient.GetConnectionAsync(System.Guid, System.Threading.CancellationToken)
    Microsoft.Fabric.Api.Core.GitClient.GetConnectionAsync(System.Guid, System.Threading.CancellationToken)
```

`null` seems to occur when a workspace has been linked to source control, but both the workspace and source control contained no items, requiring no sync to be performed. 

An example response with this in effect is:

```json
{
    "gitProviderDetails": {
        "organizationName": "XX",
        "projectName": "XX",
        "gitProviderType": "XX",
        "repositoryName": "MGFabric",
        "branchName": "dev",
        "directoryName": "/Fabric"
    },
    "gitSyncDetails": {
        "head": "XX",
        "lastSyncTime": null
    },
    "gitConnectionState": "ConnectedAndInitialized"
}
```

### Expected behavior

No exception should be thrown. `lastSyncTime` should be reported as `null`.

### Actual behavior

An exception is thrown.

### Reproduction Steps

1. Create a new workspace
2. Create a DevOps repo that contains only the folder that will be linked to the workspace. Other than a placeholder readme it should be empty
3. Link the workspace to the repo
4. Call `FabricClient.Core.Git.GetConnectionAsync` - exception is thrown

### Environment

# .NET info

.NET SDK:
 Version:           8.0.403
 Commit:            c64aa40a71
 Workload version:  8.0.400-manifests.e99c892e
 MSBuild version:   17.11.9+a69bbaaf5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.403\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [aspire]
   Installation Source: VS 17.11.35327.3
   Manifest Version:    8.1.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.1.0\WorkloadManifest.json
   Install Type:        FileBased

Host:
  Version:      8.0.10
  Architecture: x64
  Commit:       81cabf2857

.NET SDKs installed:
  6.0.427 [C:\Program Files\dotnet\sdk]
  7.0.410 [C:\Program Files\dotnet\sdk]
  8.0.403 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.35 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.35 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.35 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

# Visual Studio Info

Microsoft Visual Studio Enterprise 2022
Version 17.11.5
VisualStudio.17.Release/17.11.5+35327.3
Microsoft .NET Framework
Version 4.8.09032

Installed Version: Enterprise

**Comment by jsquire** [comment]
Hi @mikegoatly.   Thanks for reaching out and we regret that you're experiencing difficulties.   Microsoft Fabric is not part of the Azure SDK and is not developed nor supported from this repository.  The maintainers of the Azure SDK are unable to assist with your inquiry, and the Fabric team does not respond to issues logged here.  

Based on their NuGet page, it does not appear that the Microsoft Fabric client has an associated GitHub repository nor a public support process.  Unfortunately, this means that we're unable to transfer to the correct ream on your behalf.   To ensure that the right team has visibility and can help, your best path forward for would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) or inquire on the [Microsoft Q&A site](https://learn.microsoft.com/answers/questions/).   

I'm going to close this out; if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.

**Comment by mikegoatly** [comment]
Thanks @jsquire, I'll report it on the partner community forum and take it from there.
