### ISSUE TITLE
Creation of Storage Account yields an invalid JSON error

### ISSUE THREAD

**Issue by borgdylan** [Azure/azure-sdk-for-net#4679]
I am trying to make a new stoeage account using the Fluent API for Azure. This used to work in the past, but today it has failed:

```
CloudException: The request cannot be interpreted as valid Json: {
"sku": {
"name": "Standard_LRS"
},
"kind": "BlobStorage",
"location": "westeurope",
"tags": {},
"properties": {
"accessTier": "Hot"
}
}.
```

The code sequence used was:
```
var sAccount = await azure.StorageAccounts.Define(accountName).WithRegion(GetRegionFromMoniker(_options2.AzureRegion)).WithExistingResourceGroup(_options2.StorageResourceGroup).WithSku(StorageAccountSkuType.Standard_LRS).WithBlobStorageAccountKind().CreateAsync(CancellationToken.None, true);
```

Assue that the ```azure``` object represents an full logged in client.

**Comment by deathly809** [comment]
https://jsonlint.com/ reports as valid JSON, VSCode reports as valid JSON.

I assume the period at the end was not part of the JSON.  Are there special characters?

**Comment by borgdylan** [comment]
This was an issue withing the West Europe data centre itself. A simialr failure had occurred when using the portal UI. Closing this since teh Azure engineers fixed it from their end.
