### ISSUE TITLE
The information on the article is incorrect. You cannot set the AnalyticalStoreTimeToLiveInSeconds to null

### ISSUE THREAD

**Issue by hesperanca** [Azure/azure-sdk-for-net#46814]
### Type of issue

Code doesn't work

### Description

There has been a lot of confusion about how to disable the analytical store on a Cosmos container. I raised a bug about this [some time ago](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/4634) that was dealt with by @ealsur.  Some of the documentation has been amended, but this article still states that we can disable the CosmosDB integration by setting the TTL value to null, which is incorrect.

According to the [updated documentation](https://learn.microsoft.com/en-us/azure/cosmos-db/analytical-store-introduction#analytical-ttl), to disable the analytical store we need to set the ```AnalyticalStoreTimeToLiveInSeconds``` property to ```0``` (not ```null``` as stated in this article).

It would also be great if it could be documented that setting the ```AnalyticalStoreTimeToLiveInSeconds``` property to ```0``` will not work if continuous backup is enabled (which is the default). 

We are an ISV selling a SAAS application that is heavily dependent on CosmosDB. Documentation issues like this one can severely the service we provide to our customers.

Thanks for your help.

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.containerproperties.analyticalstoretimetoliveinseconds?view=azure-dotnet

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/ContainerProperties.xml

### Document Version Independent Id

5d68eda7-bc03-d2b1-8f5b-e55207a4b839

### Article author

@azure-sdk

### Metadata

* ID: cb823c91-7571-cca8-c7b8-e396faa4c1fa 
* Service: **azure-cosmos-db**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.Azure.Cosmos` library is maintained as [#4849](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/4849).
