### ISSUE TITLE
[BUG]Batch operations with retriable errors are not retried

### ISSUE THREAD

**Issue by rlrossiter** [Azure/azure-sdk-for-net#46845]
### Library name and version

Azure.Data.Tables 12.8.3

### Describe the bug

Performing batch operations on tables (and I assume blobs) returns [multipart/mixed responses](https://learn.microsoft.com/en-us/rest/api/storageservices/performing-entity-group-transactions#json-versions-2013-08-15-and-later). Because the OData protocol for these response types is to ALWAYS return a 202, we never fall into the [`ShouldRetry`](https://github.com/Azure/azure-sdk-for-net/blob/730b202eb01c409e439781124a3ea21ea39d01a7/sdk/core/Azure.Core/src/Pipeline/RetryPolicy.cs#L178C1-L187C1) section of RetryPolicy, as `Response.IsError` is always false due to the 202.

Azure.Data.Tables, after receiving the response, [does still parse these multipart responses](https://github.com/Azure/azure-sdk-for-net/blob/a5714d4c1d3f516db2528ac3f000dde20bbd4b49/sdk/tables/Azure.Data.Tables/src/TableRestClient.cs#L72C1-L91C72) and raises an exception when one of the inner responses fail, but if any of those are 429/500-range we have already passed the `HttpPipelinePolicy.SendAsync` that contains the retry logic.

### Expected behavior

When an inner response of the batch response is a retriable response, I would expect a retry to have occurred.

But is this a reasonable expectation? Retrying the entire response would re-upsert the entire batch, so the ones that succeeded would be upserted again.

### Actual behavior

No retries occur, and our services receive the following error from [this section of code](https://github.com/Azure/azure-sdk-for-net/blob/a5714d4c1d3f516db2528ac3f000dde20bbd4b49/sdk/tables/Azure.Data.Tables/src/TableRestClient.cs#L86-L88):

Operation could not be completed within the specified time.
RequestId:<requestId>
Time:<time>
Status: 500 (Internal Server Error)
ErrorCode: OperationTimedOut

### Reproduction Steps

```csharp
private const int TableChunkSize = 100;

// Provide a large number of entities to result in a large number of calls to Storage
// Larger table entities (bringing the batch closer to the 4MB limit) has been found
// to result in more 500s from storage. Smaller entities typically results in 429.
public Task UpsertEntitiesAsync(List<MyTableEntity> entities, string storageUri, string tableName)
{
    var tableServiceClient = new TableServiceClient(storageUri, new DefaultAzureCredential());
    var tableClient = tableServiceClient.GetTableClient(tableName);
    string partitionKey = entities.First().PartitionKey;

    // Parallel.ForEachAsync to hit it much harder
    foreach (var chunk in entities.Chunk(TableChunkSize))
    {
        var transactions = chunk.Select(e => new TableTransactionAction(TableTransactionActionType.UpsertMerge, e));
        await tableClient.SubmitTransactionAsync(transactions).ConfigureAwait(false);
    }
}
```

### Environment

.NET SDK:
 Version:           8.0.403
 Commit:            c64aa40a71
 Workload version:  8.0.400-manifests.e99c892e
 MSBuild version:   17.11.9+a69bbaaf5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.26100
 OS Platform: Windows
 RID:         win-x64

**Comment by rlrossiter** [comment]
It should also be noted that attempting to build a custom RetryPolicy to parse multipart responses was incredibly difficult. Because ShouldRetryAsync is only called on IsError, I found myself having to completely copy-paste the RetryPolicy implementation because I cannot properly call ProcessNextAsync and inject myself deeper into the retry logic to make more nuanced determinations into whether or not the response was an error.

Possibly a separate issue to open for feature request?

**Comment by JonathanCrd** [comment]
Hi @rlrossiter, thank you for bringing this to our attention.

You are right, retrying the entire batch could lead to re-upserting already successful operations, which is not ideal. This behavior might be more of a feature request than a bug, so we will review this issue further to prioritize it accordingly.

**Comment by christothes** [comment]
Hi @rlrossiter - In your repro, could you share an example mix of successful and retriable status codes you are seeing? Batch transactions are guaranteed to be all-or-nothing, so it isn't possible to get partial success. What you are probably seeing is that one or more sub-requests are failing the whole batch. However, it should be possible to devise a custom `RetryPolicy` that retries only if all the failed sub-requests are retriable.

**Comment by rlrossiter** [comment]
> Hi [@rlrossiter](https://github.com/rlrossiter) - In your repro, could you share an example mix of successful and retriable status codes you are seeing? Batch transactions are guaranteed to be all-or-nothing, so it isn't possible to get partial success. What you are probably seeing is that one or more sub-requests are failing the whole batch. However, it should be possible to devise a custom `RetryPolicy` that retries only if all the failed sub-requests are retriable.

So we haven't been able to repro locally, as a single instance of our application hasn't been able to push storage to the point of 429/500. We only see it in our services which doesn't yet have multipart parsing to determine if it's all or nothing. All we receive from the TableRestClient is a 202, and [at least one subrequest failed with 500](https://github.com/Azure/azure-sdk-for-net/blob/7207bbdd636d2775c8d0c41725a4417b2f45ed08/sdk/tables/Azure.Data.Tables/src/TableRestClient.cs#L116C1-L124C34). We're working to add metrics that parse the multipart response to see what the response count internally looks like, I can report back when we have that information.

I tried implementing a custom RetryPolicy, but because the original response is a 202, the response isn't classified as IsError, so we can't simply override ShouldRetryAsync. We also cannot inject into the ProcessNextAsync of RetryPolicy to allow us to determine IsError and then let RetryPolicy handle the retry logic.

It might be possible to put a per-retry HttpPipelinePolicy (not RetryPolicy) where I modify the response message to be the first error subresponse and let RetryPolicy then make its determination on that, but it feels quite hacky.

**Comment by coreymasters-microsoft** [comment]
I'm seeing this behavior for one of our applications. We're using Azure.Data.Tables 12.8.0. 

We've got code sending batched upserts like so:
```csharp
public async Task UpsertBatchAsync(List<T> entities)
{
    var actions = entities.Select(e => new TableTransactionAction(TableTransactionActionType.UpsertReplace, e));
    await this.table.SubmitTransactionAsync(actions);
}
```

Our table client is configured for 3 retires with exponential backoff, but we're seeing the following exception almost immediately after sending the transaction. It doesn't look like any retry is happening. 

```
Azure.Data.Tables.TableTransactionFailedException: Operation could not be completed within the specified time.
RequestId:7a392adf-b002-001c-033d-4d10fa000000
Time:2024-12-13T09:03:20.4504716Z
Status: 500 (Internal Server Error)
ErrorCode: OperationTimedOut

Content:
{"odata.error":{"code":"OperationTimedOut","message":{"lang":"en-US","value":"Operation could not be completed within the specified time.\nRequestId:7a392adf-b002-001c-033d-4d10fa000000\nTime:2024-12-13T09:03:20.4504716Z"}}}

Headers:
X-Content-Type-Options: REDACTED
Cache-Control: no-cache
DataServiceVersion: REDACTED
Content-Type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8
```

**Comment by christothes** [comment]
@coreymasters-microsoft 
There may be something about the entities in the batch or the partition being updated that make this batch too complex to be completed. Try sending fewer entities in the batch collection to see if there is a threshold that succeeds.

**Comment by coreymasters-microsoft** [comment]
@christothes thanks for the reply. 

We submit many of these batches with the same size and similar information and have for a few years. We see this transient server failure rarely, but recently implemented a retry policy on the TableClient. We were surprised to see that a retry did not occur.

**Comment by christothes** [comment]
@coreymasters-microsoft  -
Do you have a link to the custom retry policy? My guess is that you are expecting the API call's response code to be an error code, but most batch operations complete with a 202 status code for the envelope response, and only one or more of the multipart sub responses failed with a failed status code. 

Your retry policy would have to parse the multipart response and inspect the status codes of them to reason about the batch failures as the client does [here](https://github.com/Azure/azure-sdk-for-net/blob/68fcfb6b447660dbc48981dfa17279c2fe968b75/sdk/tables/Azure.Data.Tables/src/TableRestClient.cs#L72-L89). 

But to do this for each operation in a retry policy would be pretty inefficient. In addition, if you needed to re-construct the batch operation, it would be complicated to do in a retry policy. It might be better to wrap batch calls with a try/catch block that re-issues the batch as appropriate after inspecting the sub-responses

**Comment by rlrossiter** [comment]
>It might be better to wrap batch calls with a try/catch block that re-issues the batch as appropriate after inspecting the sub-responses

This is actually what we've done to work around the problem:

```csharp
private readonly AsyncRetryPolicy _retryPolicy = Policy
            .Handle<RequestFailedException>(RequestFailedExceptionsUtils.IsTransientError)
            .WaitAndRetryAsync(settings.Value.NumberOfRetries, retryAttempt => TimeSpan.FromSeconds(Math.Pow(2, retryAttempt) * settings.Value.ExponentialBackoffDelayMultiplierInSeconds));

...

Response<IReadOnlyList<Response>> response = await _retryPolicy.ExecuteAsync(() => tableClient.SubmitTransactionAsync(batchTransactions, cancellationToken)).ConfigureAwait(false);

```

But isn't this doing the same thing as an HTTP-pipeline-internal retry policy should be doing? Assuming we wouldn't try and get smart around which internal batch item was failed.

**Comment by christothes** [comment]
The tricky thing about handling retries for batch transactions is that the whole batch may not be retriable as-is unless it is a very small subset of scenarios. For example, 429 responses or batch intermittent timeouts. For a robust solution, you'd need to inspect all the non-successful sub-response status codes and make a decision about what to do. Sometimes this may involve modifying the batch before retrying. How you decide to correct the error may be dependent on your specific scenario, so there is not a built-in default solution in the SDK.

**Comment by coreymasters-microsoft** [comment]
@rlrossiter thank you for that; much appreciated. Also @christothes TY for the guidance and discussion. I think our scenario is fairly straightforward and allows us to retry the whole batch in this case. 

I'm still with @rlrossiter on this one, It feels odd for the `TableClient` with retries configured to just not do retires in this case. I understand the nuance with batched transactions you've mentioned, however.
