### ISSUE TITLE
[FEATURE REQ] Azure.Monitor.OpenTelemetry.AspNetCore: `AzureVMResourceDetector`, `AppServiceResourceDetector`, etc, should be public

### ISSUE THREAD

**Issue by DrEsteban** [Azure/azure-sdk-for-net#46870]
### Library name

Azure.Monitor.OpenTelemetry.AspNetCore

### Please describe the feature.

The Azure.Monitor.OpenTelemetry.AspNetCore library includes various internal "Detectors" for different Azure compute platforms: ([link](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/src/Vendoring/OpenTelemetry.Resources.Azure))

IMO these detectors should be made public! And/or packaged and distributed as another NuGet package. Not **all** workloads running in Azure use ASP.NET - some just use regular .NET Core or the worker pattern. (No Http exposed or references to ASP.NET SDKs.)  In those cases, it'd be nice if apps could still apply these Detectors to their OpenTelemetry initializers.

As a workaround, I've manually copy/pasted the code from the [`AzureVMResourceDetector`](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/src/Vendoring/OpenTelemetry.Resources.Azure/AzureVMResourceDetector.cs) into my project. (As well as all [internal dependencies](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/src/Vendoring/OpenTelemetry.Resources.Azure/AzureVmMetaDataRequestor.cs) the detector relies on... ~3-4 different internal classes and model objects.)  That way I can call `.AddDetector()` on my `ResourceBuilder` and still benefit from the behavior. But obviously that's very tedious and I don't like knowing I'll need to manually repeat that process if/when Microsoft makes any updates! So it'd be nice if these classes were just publicly consumable from the start.

**Comment by TimothyMothra** [comment]
Hi @DrEsteban, I fully agree and can assure you that this is on our roadmap.

The resource detectors are publicly available now via the `OpenTelemetry.Resources.Azure` package. My team owns this package and we've been collaborating with other internal teams to add additional integrations. I don't have an ETA on when this will get a stable release. But if your company is comfortable with beta packages you can use it now. 
- https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Resources.Azure
- https://www.nuget.org/packages/OpenTelemetry.Resources.Azure

Azure rules mandate that I cannot have beta Nuget dependencies. Until then, we've copied it privately in the `Azure.Monitor.OpenTelemety.AspNetCore`.

**Comment by TimothyMothra** [comment]
I'm going to close this since this is already on our roadmap. 
If you have additional questions or comments, please don't hesitate to reach out!
