### ISSUE TITLE
Building the repo with msbuild on non-windows OS fails

### ISSUE THREAD

**Issue by dsgouda** [Azure/azure-sdk-for-net#4692]
When building the repo on a non windows machine using msbuild (mono implementation), the following error is reported
```
 Updating Tools.....

/Users/deshank/Documents/azure-sdk-for-net/tools/bootstrapTools/bootstrap.targets(5,4): error : Invalid URI: The format of the URI could not be determined. [/Users/deshank/Documents/azure-sdk-for-net/build.proj]

```

**Comment by dpetillo** [comment]
I have the same issue.  Perhaps the build task GetBuildTools (taskBinaries\Microsoft.Azure.Build.BootstrapTasks.dll) isn't cross platform?

**Comment by pakrym** [comment]
The repo is building cross-plat.
