### ISSUE TITLE
[QUERY]Why doesn't Azure Blob Storage support Http 2?

### ISSUE THREAD

**Issue by chassq** [Azure/azure-sdk-for-net#46959]
### Library name and version

Azure.Stoage.Blobs

### Query/Question

We still have yet to hear a valid reason for why after so many years Azure Blob storage REST API or SDK does not support HTTP 2.0. Dont we think it high time to move on from HTTP 1.0/1.1? Of course, we understand we can use FrontDoor to do this but that actually cost a good deal of money just baseline. So, for dev/test environments it is not a good for a budget. This question has been asked many times in threads with no clear answer. The responses are it just does not and there is no plan for it. Can we at least have an answer as to why? It really does nto make sense. For example, one impact is if a website accesses a storage account directly the lighthouse tools ding the site for now using http 2.0.

See: [Http 2.0 support for Azure Blob Storage](https://github.com/Azure/azure-sdk-for-net/issues/42828#top)
#42828

**Comment by jsquire** [comment]
Hi @chassq.  Thanks for reaching out and for your question.  As the issue that you've linked notes, per [the service documentation](https://learn.microsoft.com/en-us/rest/api/storageservices/http-version-support) , the Azure Storage REST API does not support HTTP/2 .  The Azure SDK client library cannot support offer support for a protocol that the service itself does not support.  

While I understand that you're interested in understanding why the service has made this decision, the maintainers of the Azure SDK do not have insight nor influence over the REST API nor the decisions made regarding its design.  Unfortunately, the team responsible for the service does not monitor this repository nor provide support here.  To ensure that the right team has visibility and can help, your best path forward for would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) or inquire on the [Microsoft Q&A site](https://learn.microsoft.com/answers/questions/).   To leave a feature suggestion for HTTP/2 support, you may also want to consider the [Azure Feedback site](https://feedback.azure.com/d365community).

I'm going to close this out; if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.
