### ISSUE TITLE
Microsoft.Azure.Services.AppAuthentication not able to get tokens using SubjectName + Issuer certificate authentication

### ISSUE THREAD

**Issue by nikhilboreddy** [Azure/azure-sdk-for-net#4700]
We usually use this library to get AAD tokens using MSI but there are some cases where we use connection string approach using certificates. 

Connection string: “RunAs=App;AppId={AppId};TenantId={TenantId};CertificateSubjectName={Subject};CertificateStoreLocation= LocalMachine”

It seems like ADAL has introduced a new AcquireTokenAsync overload which takes in a sendX5c flag which allows apps to authenticate using Subject Name + Trusted issuer set by admins. Can the AppAuthentication library to updated to support sending the flag as well when using connection string approach?

https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.clients.activedirectory.authenticationcontext.acquiretokenasync?view=azure-dotnet#Microsoft_IdentityModel_Clients_ActiveDirectory_AuthenticationContext_AcquireTokenAsync_System_String_Microsoft_IdentityModel_Clients_ActiveDirectory_IClientAssertionCertificate_Microsoft_IdentityModel_Clients_ActiveDirectory_UserAssertion_System_Boolean_

**Comment by nonik0** [comment]
Hi Nikhil, this functionality will be covered in the next release of AppAuth which we are working on releasing now.

**Comment by nikhilboreddy** [comment]
> Hi Nikhil, this functionality will be covered in the next release of AppAuth which we are working on releasing now.

Thanks Nick. Can you please let me know the package number?

**Comment by nonik0** [comment]
We have now released AppAuth 1.2.0-preview, which includes setting the new sendX5c flag/argument when using certificate-based authentication. You can find the new release here:
https://www.nuget.org/packages/Microsoft.Azure.Services.AppAuthentication/1.2.0-preview

**Comment by varunsh-msft** [comment]
@shahabhijeet , can you please close this issue?

**Comment by varunsh-msft** [comment]
Closing, this is done.
