### ISSUE TITLE
[BUG] HttpMessage RetryNumber Internal

### ISSUE THREAD

**Issue by Leibowk** [Azure/azure-sdk-for-net#47019]
### Library name and version

Azure.Core 1.44.1 (Current Version)

### Describe the bug

Right now the HttpMessage RetryNumber is Internal. When going to override ShouldRetry on a RetryPolicy we found that it internally used the RetryNumber - Hence to override ShouldRetry we were expecting to be able to get RetryNumber as well.

### Expected behavior

The HttpMessage RetryNumber should be public readonly int instead of internal int.

### Actual behavior

Retry number is an internal int.

### Reproduction Steps

.

**Comment by Leibowk** [comment]
(also sorry if I messed up the format of this somehow/if this isn't technically a bug but a feature request - first time opening an issue here)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by annelo-msft** [comment]
Hi @Leibowk, would it be possible to share the specific scenario you are working with?  Depending on what your target scenario is, there may be alternative approaches to accomplishing the outcome you're looking for, and I'm happy to help you find the best approach here.  Thanks!

**Comment by Leibowk** [comment]
Sure. I was hoping to override 

ShouldRetry on the [RetryPolicy](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Pipeline/RetryPolicy.cs)

We needed to Retry when we encountered a 409 connecting to the FileShare because of a situation with files still being written to when a get comes in and being locked.

I was hoping to create a simple override method like this:

`public class CustomRetryPolicy : RetryPolicy
{
    public const int _maxRetries = 5;

    public CustomRetryPolicy()
        : base(_maxRetries)
    {
    }

    public bool ShouldRetry(HttpMessage message, Exception? exception)
    {
        if (message.RetryNumber < _maxRetries && message.Response.Status == 409)
        {
            return true;
        }

        return base.ShouldRetry(message, exception);
    }
}`

However "RetryNumber" is currently internal and not accessible. Due to this we had to just make our own retry logic at our repo layer. Alternatively one other thing would be to bring the max retry logic out into the ProcessAsync vs having that in the ShouldRetryInternal.

**Comment by Leibowk** [comment]
An alternative then could be in RetryPolicy

```
...

  bool shouldRetry = false;

  // We only invoke ShouldRetry for errors. If a user needs full control they can either override HttpPipelinePolicy directly
  // or modify the ResponseClassifier.

  if (lastException != null || (message.HasResponse && message.Response.IsError))
  {
      var belowMax = message.RetryNumber < _maxRetries;
      shouldRetry = async ? belowMax && (await ShouldRetryAsync(message, lastException).ConfigureAwait(false)) : belowMax && ShouldRetry(message, lastException);
  }

...


        //Calls now only to determine if error type is a valid error
        private bool ShouldRetryInternal(HttpMessage message, Exception? exception)
        {
                if (exception != null)
                {
                    return message.ResponseClassifier.IsRetriable(message, exception);
                }

                // Response.IsError is true if we get here
                return message.ResponseClassifier.IsRetriableResponse(message);
        }
```


That way I could have my override simply be

```
    public bool ShouldRetry(HttpMessage message, Exception? exception)
    {
        if (message.Response.Status == 409)
        {
            return true;
        }

        return base.ShouldRetry(message, exception);
    }
```

**Comment by annelo-msft** [comment]
Hi @Leibowk, thank you for the additional information!

If you are looking to add an HTTP status code to the set of defaults the retry policy considers "retriable," the best approach to achieving that is to customize the response classifier for the method you are calling.

I provided a sample illustrating one way to implement that here: https://github.com/Azure/azure-sdk-for-net/issues/46426#issuecomment-2397728041.  This sample is specific to our clients based on the `System.ClientModel` Core library, but a similar approach will work with clients based on Azure.Core.  If you can share which client you are using, I can help you find whether the linked approach is recommended, or whether it would be better to use an approach adapted to a client with an Azure.Core pipeline.

Thanks!

**Comment by Leibowk** [comment]
We're working with the FileShare so the ShareClient

**Comment by annelo-msft** [comment]
Can you confirm that you mean the `Azure.Storage.Files.Shares` client?  If so, I will work to provide a concrete a recommendation in the next few days.  Thanks!

**Comment by Leibowk** [comment]
@annelo-msft correct! From your comment, thing I got it figured out.

```

public class CustomRetryPolicy : RetryPolicy
{
    private readonly int _retryStatusCode;

    public CustomRetryPolicy(int customRetryStatusCode)
    {
        _retryStatusCode = customRetryStatusCode;
    }

    protected override void OnSendingRequest(HttpMessage message)
    {
        if (message.ResponseClassifier is not CustomRetryClassifier)
        {
            message.ResponseClassifier = new CustomRetryClassifier(message.ResponseClassifier, _retryStatusCode);
        }
    }
}

public class CustomRetryClassifier : ResponseClassifier
{
    private readonly ResponseClassifier _defaultClassifier;
    private readonly int _specialRetriableStatusCode;

    public CustomRetryClassifier(ResponseClassifier defaultClassifier, int specialRetriableStatusCode)
    {
        _defaultClassifier = defaultClassifier;
        _specialRetriableStatusCode = specialRetriableStatusCode;
    }

    public override bool IsRetriableResponse(HttpMessage message)
    {
        //// if it's the special HTTP code, classify it;
        //// otherwise, let the default classifier classify it.
        if (message.Response!.Status == _specialRetriableStatusCode)
        {
            return true;
        }

        return _defaultClassifier.IsRetriableResponse(message);
    }
}

```

**Comment by annelo-msft** [comment]
> From your comment, thing I got it figured out.

I am so glad to hear that!

It looks like the simplified approach I was considering suggesting is not currently available in the client library you are using.  But -- thank you so much for sharing your scenario, because it helps us understand ways we can improve our APIs to make them better for use cases that our users need.  This once specifically gives me some ideas for ways we might make this much easier for you to achieve what you're trying to accomplish in the future -- thank you for giving us the information we need to see opportunities like this.


Given the solution you were able to find, would it be OK with you if we close this issue?  If there is anything outstanding here that I can help with before closing, please let me know.

**Comment by Leibowk** [comment]
All good to close it! Thanks for the help. :)

**Comment by annelo-msft** [comment]
Closed per above comment.  Thanks again, @Leibowk!
