### ISSUE TITLE
Microsoft.Azure.Management.DataLake.Store FileStatusProperties.PathSuffix Empty On File

### ISSUE THREAD

**Issue by g-hamers** [Azure/azure-sdk-for-net#4702]
```
var adlsClient = new DataLakeStoreFileSystemManagementClient(auth);
var directoryInfo= adlsClient.FileSystem.ListFileStatus(_adlsAccountName, "/local/temp/ghamers");
```
![image](https://user-images.githubusercontent.com/42684912/44611432-efdda680-a7b5-11e8-8937-51214c953b15.png)

Within directoryInfo, I can see the file / directory names within the directory using the .PathSuffix field.  This isn't working when I get the FileStatusProperties of a file diectly.  The PathSuffix is empty for the file.

`var fileInfo= adlsClient.FileSystem.GetFileStatus(_adlsAccountName, "/local/temp/ghamers/origin.tsv");`

![image](https://user-images.githubusercontent.com/42684912/44611445-07b52a80-a7b6-11e8-90d4-6a4c2e771411.png)

This is the case for both the Microsoft.Azure.Management.DataLake.Store 2.2.1 and 2.4.1-preview.

**Comment by g-hamers** [comment]
Have you started looking in this issue yet?  I am still waiting for this problem to be fixed.

**Comment by markcowl** [comment]
@g-hamers Closing this as there have been several iterations of the data lake client since3 this report.  Please file a new issue if you are still seeing this problem.
