### ISSUE TITLE
Unable to creating Bot Channels Registration for BotService

### ISSUE THREAD

**Issue by mehtanilay10** [Azure/azure-sdk-for-net#4703]
Hi, I am trying to create Bot Channel Registration using Azure SDK for .Net.
For this, I have used **Microsoft.Azure.Management.BotService** package with below method.

```
// Create Bot
Bot createdBot = await botServiceClient.Bots.CreateRegistrationBotAsync(resourceGroupName, botServiceName, bot);
```

**This method currently creating Web App Bot instead of Bot Channel Registration.**

### Issue-2
As well as In this package 2 external packages used but Its version was written as exactly equal (=), It should be greater than equal (>=) .
```
    <PackageReference Include="Microsoft.IdentityModel.Clients.ActiveDirectory" Version="[3.14.1]" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="[5.1.4]" />
```

**Comment by mehtanilay10** [comment]
I have also tried with API Version: **2018-07-12**, but this time got 
```
The Resource 'Microsoft.BotService/botServices/dev-bot-123-c' under resource group 'dev-bot-123' was not found.
```
Here request URL is
```
https://management.azure.com/subscriptions/996b68f4-6fff-41a7-b5df-9ec7e3b8dc63/resourceGroups/dev-bot-123/providers/Microsoft.BotService/botServices/dev-bot-123-c?api-version=2018-07-12
```
Looks like **/** in Resource type name creates an issue. Here Resource type is **Microsoft.BotService/botServices**

**Comment by jsquire** [comment]
Closing this out as there has been no recent engagement.  Please feel free to reopen or file a new issue if this remains a problem with the current version of the library.
