### ISSUE TITLE
Integration Account SKU name enumeration does not accept Basic SKU

### ISSUE THREAD

**Issue by ohawari** [Azure/azure-sdk-for-net#4704]
Hi all,
I've been trying to create an Integration Account with Basic Tier, but it is always returning a deserialization error.
Reviewing the code I've detected a bug related to the SKU name enumeration.
This is the class enum:

[JsonConverter(typeof(StringEnumConverter))]
    public enum IntegrationAccountSkuName
    {
        [EnumMember(Value = "NotSpecified")]
        NotSpecified,
        [EnumMember(Value = "Free")]
        Free,
        [EnumMember(Value = "Standard")]
        Standard
    }

As you can see, no Basic Sku name is supported.
Please, can you fix it?

Many thanks.

**Comment by shahabhijeet** [comment]
@ohawari what version of SDK are you referencing?
Give the full name of the SDK and it's version you are using.

**Comment by ohawari** [comment]
Hi, good morning.
I'm using Microsoft Azure Libraries for .NET version 2.9.
It's not working event in the Host VS2017 generic build agent in VSTS online.
In my first post of this thread, is the specific lines that are not correct because no EnumMember Basic is supported in the enumeration.
Many thanks,
Best regards.
