### ISSUE TITLE
[BUG] RunCommandInputParameter Parameter values all strings

### ISSUE THREAD

**Issue by shareonline** [Azure/azure-sdk-for-net#47046]
### Library name and version

Azure.ResourceManager.Compute v1.6.0

### Describe the bug

This goes for both Azure.ResourceManager.Compute v1.6.0 and the new hybrid preview of the same.

When sending a script as a run command we are forced by the SDK to send name and value as strings.
When you then have a powershell script with bool, int og other type, the script fails to convert the parameter to the correct type.
In some situations we are forced to change the script parameters to all strings, and then inside the script parse these to the correct types.
This is a major limitation to run scripts inside both Azure VM's and Arc VM's.

This is the error for a bool parameter
 Cannot proc
ess argument transformation on parameter 'HideFromAddressList'. Cannot convert value "System.String" to type "System.Bo
olean". Boolean parameters accept only Boolean values and numbers, such as $True, $False, 1 or 0.

### Expected behavior

The expected behavior would be for the api to convert the values sent into the correct types and then use them as script arguments. 

### Actual behavior

Everything is being forced to strings, which local powershell scripts can't convert

### Reproduction Steps

    param (
        [Parameter(Mandatory=$false, ValueFromPipelineByPropertyName)]
        [string]$testString,
        
        [Parameter(Mandatory=$true, ValueFromPipelineByPropertyName)]
        [int]$testNumber,

        [Parameter(Mandatory)]
        [bool]$testBool
    )
Write-Output $testBool

When sending this script to the VM i have tried the following as parameter values:
testBool = $true
testBool = 1
testBool = $True
testBool = true
testBool = True

The powershell script inside the VM always returns:
 Cannot proc
ess argument transformation on parameter 'testBool'. Cannot convert value "System.String" to type "System.Bo
olean". Boolean parameters accept only Boolean values and numbers, such as $True, $False, 1 or 0.

**Comment by jsquire** [comment]
Hi @shareonline.  Thank you for reaching out and we regret that you're experiencing difficulties.  The Azure SDK packages have no insight nor influence over the format used by Azure services to exchange data; they must conform to the published REST API specification for the service.   In this case, the Compute resource provider defines the set of parameters for the "Run Command" operation as a string-based name and value set.    This can be seen in the [RunCommandInputParameter definition](https://github.com/Azure/azure-rest-api-specs/blob/4f68529971f845e8757c2b2a746d78ceb91854cd/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2024-07-01/runCommand.json#L927) of the API spec, as well as the associated [example payload](https://github.com/Azure/azure-rest-api-specs/blob/4f68529971f845e8757c2b2a746d78ceb91854cd/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2024-07-01/examples/runCommandExamples/VirtualMachineRunCommand_CreateOrUpdate.json#L14).

In your scenario, it seems that the service is not translating these as you'd expect.  The maintainers of the Azure SDK are unable to assist as we do not have insight into the service implementation.   Unfortunately, the Azure services teams do not monitor our repository, do not offer support here, nor provide a way for us to transfer an inquiry to them directly.   To ensure that the right team has visibility and can help, your best path forward for would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) or inquire on the [Microsoft Q&A site](https://learn.microsoft.com/answers/questions/).

I'm going to close this out; if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.
