### ISSUE TITLE
[FEATURE REQ] Azure.Identity - improve visibility, add logging

### ISSUE THREAD

**Issue by lkurzyniec** [Azure/azure-sdk-for-net#47045]
### Library name

Azure.Identity

### Please describe the feature.

It's a common practice to use `DefaultAzureCredential()`, which under the hood have several different credential providers, which runs one after another.
It would be nice to have an option, a switch, to enable logging what's happening - log entries about through which providers code went, which provider had a hit.

**Comment by jsquire** [comment]
Hi @lkurzyniec.   Thank you for reaching out and for your suggestion.   The Azure SDK, including Azure.Identity, has logging built in which you can subscribe to and publish to your preferred sink.   This is discussed in the article [Logging with the Azure SDK for .NET](https://learn.microsoft.com/dotnet/azure/sdk/logging).   Azure.Identity also provides additional context and discussion about the logging specific to credentials in the [Enable and configure logging](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/TROUBLESHOOTING.md#enable-and-configure-logging) section of its Troubleshooting Guide.
