### ISSUE TITLE
[BUG] Cannot assign zones using ManagedClusterAgentPoolProfile or ContainerServiceAgentPoolData

### ISSUE THREAD

**Issue by cwash05** [Azure/azure-sdk-for-net#47063]
### Library name and version

Azure.ResourceManager.ContainerService 1.2.2

### Describe the bug

When configuring ContainerServiceAgentPoolData or ManagedClusterAgentPoolProfile you can not use any kind of variable substitution with the AvailabilityZones property.  I will only take a hard coded list of zones. 

```
AvailabilityZones = { "1", "2", "3" }
```

### Expected behavior

I expect to be able to use variable substitution to assign to the property based on user input. 

```
List<string> zones;
zones =  new List<string> { "1" };

AvailabilityZones = zones
```

### Actual behavior

trying to use a variable gives CS0200 error

### Reproduction Steps

try to create any node pool where the zones are not hard coded

```
List<string> zones;
zones =  new List<string> { "1" };

new ManagedClusterAgentPoolProfile(systemNodePoolName)
{
    Count = sysNodeCount,
    VmSize = buildData.linuxVmSku,
    Mode = AgentPoolMode.System,
    //VnetSubnetId = (buildData.networkPlugin == "Kubenet")? null : new ResourceIdentifier(sysNodeSubnetId.Id),
    //PodSubnetId = (buildData.networkPluginMode == "Dynamic") ? new ResourceIdentifier(sysNodePodSubnetId.Id) : null,
    //OSDiskType = osDiskType.Managed,
    OSType = osType.Linux,
    OSSku = (buildData.customVnet) ? systemNodePoolOs : buildData.linuxOs,
    MaxPods = maxPods,
    AgentPoolType = "VirtualMachineScaleSets",
    EnableNodePublicIP = false,
    //NodeTaints = buildData.customVnet ? { "CriticalAddonsOnly=true:NoSchedule" } : new ResourceIdentifier(sysNodeSubnetId.Id) ,
    AvailabilityZones = zones

}

```

**Comment by jsquire** [comment]
Hi @cwash05.  Thank you for reaching out and we regret that you're experiencing difficulties.  As a convention across libraries in the Azure SDK, collection types for models are intentionally read-only.   Their value can be set by mutating the existing collection.  This can be done by either adding members after the object has been constructed or using C#'s initializer syntax as part of construction.   

In your scenario, it sounds like what you'll want to do is manipulate the existing collection to seed with the values that you've collected.

```csharp
// Example: populating from another collection.
var profile = new ManagedClusterAgentPoolProfile(systemNodePoolName);
profile.AvailabilityZones.AddRange(myZoneList);

// Example: adding items after construction.
var profile = new ManagedClusterAgentPoolProfile(systemNodePoolName);
profile.AvailabilityZones.Add("1");
profile.AvailabilityZones.Add("2");
profile.AvailabilityZones.Add("2");

// Example: initializer syntax
var profile = new ManagedClusterAgentPoolProfile(systemNodePoolName);
{
    AvailabilityZones = { "1", "2", "3" }
}
```
