### ISSUE TITLE
[BUG] ManagedIdentityCredential authentication failed. "No connection could be made"

### ISSUE THREAD

**Issue by lipalath-ms** [Azure/azure-sdk-for-net#47064]
### Library name and version

Azure.Messaging.ServiceBus 7.18.1

### Describe the bug

Exception encountered:

ManagedIdentityCredential authentication failed: Retry failed after 6 tries. Retry settings can be adjusted in ClientOptions.Retry or by configuring a custom retry policy in ClientOptions.RetryPolicy. (No connection could be made because the target machine actively refused it.

### Expected behavior

Authentication should succeed

### Actual behavior

Authentication failing after multiple attempts

### Environment

.NET 8 Isolated

Package:
Microsoft.Azure.Functions.Worker.Extensions.ServiceBus 5.21.0

**Comment by christothes** [comment]
Hi @lipalath-ms  -
It would be helpful to know more information about what you are doing, what changed before you had this issue, and to get some logging of the issue. 

For console output, you would just need to add the following line to your program. 

```c#
using AzureEventSourceListener listener = AzureEventSourceListener.CreateTraceLogger();
```

If you need to log the output somewhere other than the console, such as through the ILogger provider, this can be done as described in [these docs](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Diagnostics.md#custom-logging-callback).
