### ISSUE TITLE
[BUG] MaxTextRecallSize property of SearchOptions.HybridSearch object is not working as expected

### ISSUE THREAD

**Issue by ayushgorya** [Azure/azure-sdk-for-net#47122]
### Library name and version

Azure.Search.Documents 11.7.0-beta.1

### Describe the bug

When we search the index from azure portal using json view , with MaxTextRecallSize = 100 as shown below.

```
{
  "search": "india",
  "answers": "extractive|count-3",
  "captions": "extractive",
  "queryLanguage": "en-us",
  "semanticConfiguration": "MySemanticConfigurations",
  "count": true,
  "queryType": "semantic",
  "vectorQueries": [
    {
      "kind": "text",
      "text": "india",
      "fields": "VectorField1,VectorField2"
    }
  ],
  "hybridSearch": {
    "maxTextRecallSize": 100,
    "countAndFacetMode": "countRetrievableResults"
  }
}
```
The results are reduced from ~2000 to around 200. This is expected.
But when we try this from c# search sdk (Azure.Search.Documents 11.7.0-beta.1), the results are around 2000 only.

### Expected behavior

Expected behaviour is to get the same number of records (around 200) which we get from azure search explorer using below json.
Expected record count : ~200

```
{
  "search": "india",
  "answers": "extractive|count-3",
  "captions": "extractive",
  "queryLanguage": "en-us",
  "semanticConfiguration": "MySemanticConfigurations",
  "count": true,
  "queryType": "semantic",
  "vectorQueries": [
    {
      "kind": "text",
      "text": "india",
      "fields": "VectorField1,VectorField2"
    }
  ],
  "hybridSearch": {
    "maxTextRecallSize": 100,
    "countAndFacetMode": "countRetrievableResults"
  }
}
```

### Actual behavior

In actual when we use azure search sdk, we get around ~2000 records as opposed to ~200 records which we get from azure search explorer. 

### Reproduction Steps

Working code : when we use rest api from azure search explorer.

```
{
  "search": "india",
  "answers": "extractive|count-3",
  "captions": "extractive",
  "queryLanguage": "en-us",
  "semanticConfiguration": "MySemanticConfigurations",
  "count": true,
  "queryType": "semantic",
  "vectorQueries": [
    {
      "kind": "text",
      "text": "india",
      "fields": "VectorField1,VectorField2"
    }
  ],
  "hybridSearch": {
    "maxTextRecallSize": 100,
    "countAndFacetMode": "countRetrievableResults"
  }
}
```

Not working : when we use azure sdk from c#.

![Image](https://github.com/user-attachments/assets/fb3de500-4500-4794-ad26-fa4b46c4af48)

### Environment

Azure AppService
.Net 8

**Comment by ayushgorya** [comment]
Hi @ShivangiReja , any updates on this issue?

**Comment by ShivangiReja** [comment]
@ayushgorya We’ve recently released Azure.Search.Documents version [11.7.0-beta.2](https://www.nuget.org/packages/Azure.Search.Documents/11.7.0-beta.2). Could you please test with this version?  

I couldn’t reproduce the behavior as we don’t have similar data to test with. Based on my review of the C# SDK, it appears that we’re sending the `HybridSearch` object to the service, and the results you’re seeing are being returned directly by the search service.  

Have you tried testing with other SDKs, such as Java, TypeScript, or Python, or using the REST API via Postman or a similar tool? This will help us determine whether the issue lies with the SDK or the service itself.

**Comment by ShivangiReja** [comment]
@ayushgorya Thank you for the confirmation!
