### ISSUE TITLE
[FEATURE REQ] Obfuscating ResponseError Details is breaking for consumers and unnecessary

### ISSUE THREAD

**Issue by pateljay-37** [Azure/azure-sdk-for-net#47173]
### Library name

Azure.Core 1.42.0.0

### Please describe the feature.

As previously discussed in this issue https://github.com/Azure/azure-sdk-for-net/issues/38890, Details, Target, and InnerError are all internal properties on the AzureDeploymentOperation.Properties.StatusMessage.ResponseError class. I understand the expectation is for resource providers (RPs) to ensure all information needed to diagnose an error are in the top-level error code and message, but it's not possible to actually enforce that or guarantee it. My RP, Azure Batch, currently inspects the error Details to inform both our internal error handling and what we return back to our customers. Removing visibility to these Details is effectively a breaking change for us.
 
I understand that a workaround is to call ToString() and to inspect the Details from there, but given you're making the Details available there, why not just make them accessible on the ResponseError object directly? This obfuscation is unnecessary, and forces consumers to add new logic on their side to avoid the breaking change.

**Comment by jsquire** [comment]
@pateljay-37:  Please refer to the issue that you linked.  Your scenario and request align with the one made there, and the discussion thread with rationale and the decision remain salient.  I'm going to close this out, as there is no change to the outcome from the existing issue.
