### ISSUE TITLE
[SECURITY] new version of Azure.Extensions.AspNetCore.DataProtection.Blobs to combat dependency security vulnerability please

### ISSUE THREAD

**Issue by robrich** [Azure/azure-sdk-for-net#47176]
### Library name and version

Azure.Extensions.AspNetCore.DataProtection.Blobs  1.3.4

### Describe the bug

Azure.Extensions.AspNetCore.DataProtection.Blobs depends on ... depends on System.Drawing.Common 4.7.0 which has a critical vulnerability, causing a build warning. Can we get a new build of Azure.Extensions.AspNetCore.DataProtection.Blobs that depends on the recently released version of Microsoft.AspNetCore.DataProtection that doesn't have this vulnerability?

### Expected behavior

Build succeeds without warnings.

### Actual behavior

Build fails when "Treat warnings as Errors" is enabled, and NuGet package restore fails.

### Reproduction Steps

1. Add Azure.Extensions.AspNetCore.DataProtection.Blobs NuGet package
2. See NuGet security error
3. Cry

### Environment

ASP.NET 9, VS 2022

**Comment by jsquire** [comment]
Hi @robrich.  Thanks for reaching out and we regret that you're experiencing difficulties.   This traces back to `System.Security.Permissions` v4.7.0, which has a dependency on `System.Windows.Extensions` only for its `netcoreapp3.0` target.  Neither its `netstandard2.0` or `net461` targets hold that dependency.  This has been discussed this with the Azure SDK and .NET security teams and they confirmed that this is considered a false positive by the scanner rather than an active security risk, as the issue being flagged exists only for an unsupported platform.   If you have a need to mitigate the false positive, the recommendation is to take a direct dependency on a version of `Microsoft.AspNetCore.DataProtection` in your application that is not flagged by the scanner. 

 Unfortunately, we're out of minor versions of `Microsoft.AspNetCore.DataProtection` to move to and moving to a new major version requires additional validation and testing.  We're tracking this work in #35707, but I don't currently have an estimate on when we'll have bandwidth to schedule work on it.

#### Related:
  - [#35693](https://github.com/Azure/azure-sdk-for-net/issues/35693)
  - [#42102](https://github.com/Azure/azure-sdk-for-net/issues/42102)

**Comment by robrich** [comment]
Is there a way to store DataProtection keys in Azure Storage without this library?

Can we update the docs at https://learn.microsoft.com/en-us/dotnet/api/overview/azure/extensions.aspnetcore.dataprotection.blobs-readme and https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-storage-providers to note the additional dependency to avoid the security error?

**Comment by jsquire** [comment]
> Is there a way to store DataProtection keys in Azure Storage without this library?

I can't speak authoritatively to the Data Protection system in general, but I believe the answer is yes.   Anyone can write a provider similar to the extension package and implement the persistence contract to store keys in Azure Storage.

 
> Can we update the docs at https://learn.microsoft.com/en-us/dotnet/api/overview/azure/extensions.aspnetcore.dataprotection.blobs-readme and https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-storage-providers to note the additional dependency to avoid the security error?

We appreciate the suggestion, but this would cause more confusion than help.  There is no need for direct references in your application when hosted on any supported version of .NET.  The only time there's a potential vulnerability that needs to be mitigated is if you're running on `netcoreapp3.0` specifically - which is an unsupported framework.  The correct mitigation in that case is to upgrade to a supported runtime, not redeploy with updated references.

**Comment by SoftwareJourney** [comment]
@jsquire "With respect to the security error that you're seeing, its a known false positive returned by several third-party scanners."
=> I don't think it is only related to third-party scanners. It also affects Visual Studio (without third-party extension).

In Visual Studio v17.12.1, when I add the nuget package "Azure.Extensions.AspNetCore.DataProtection.Keys" v1.2.4 to an empty class library project (dotnet v8), I almost instantly get the following compilation warning:
"Package 'System.Drawing.Common' 4.7.0 has a known critical severity vulnerability, https://github.com/advisories/GHSA-rxg9-xrhp-64gj"

![Image](https://github.com/user-attachments/assets/66e757df-1664-4db8-8fc4-619d78709b41)

**Comment by robrich** [comment]
This is my exact scenario as well. Visual Studio 2022 with no extensions
and an ASP.NET 9 app. Taking a dependency on the intermediate library
solved the symptom.

**Comment by jsquire** [comment]
Thanks for the additional context, folks.  If this is being flagged by Microsoft tools, then there's follow-up discussion needed here with the .NET security team to understand why the tooling is not in alignment with their internal guidance.    We'll look into local repro and follow-up.

**Comment by benrhere** [comment]
> If this is being flagged by Microsoft tools, then there's follow-up discussion needed here with the .NET security team to understand why the tooling is not in alignment with their internal guidance. We'll look into local repro and follow-up.

Just wanted to echo what others are saying: VS 17.12.1 (and the past few versions) show this alert if I don't take an explicit dependency on System.Drawing.Common later version.

![Image](https://github.com/user-attachments/assets/d1ce91d4-c2d9-475b-b093-871edbc6a0f0)

**Comment by jsquire** [comment]
Hi folks.   Thanks for your patience as we looked more deeply into this.  Confirming that we're now able to reproduce the behavior using Microsoft tooling.   I followed up with the .NET security team and they confirmed that the approach to scanning changed with the .NET 9 release and was also updated in the latest .NET 8 SDK.   The short version is that the scanner no longer filters retired platforms.   They reiterated that there is no active risk, as the vulnerability is only present when running specifically on `netcoreapp3.0` in this case.

We agree this is a poor experience and do not want Microsoft tooling flagging Azure packages by default.  As a result, we've prioritized bumping the data protection dependencies to align with the 8.x targets and are currently validating the impact of these changes.   Work can be tracked in #47286.   

Once validation is complete, we'll release the updates.   Our hope is to do so this week or next.

**Comment by JonathanCrd** [comment]
This issue got closed when the related PR got merged. 
I’m reopening it and will close it again once the updated version of `Azure.Extensions.AspNetCore.DataProtection.Blobs` is released and available in NuGet.

**Comment by JonathanCrd** [comment]
Hi everyone,
Version 1.4.0 for [AspNetCore.DataProtection.Blobs](https://www.nuget.org/packages/Azure.Extensions.AspNetCore.DataProtection.Blobs) is now available. This update addresses the vulnerability in the previous dependency on `System.Drawing.Common 4.7.0` and no longer triggers build warnings in Visual Studio.

Thanks for your patience and for highlighting this issue.

**Comment by SoftwareJourney** [comment]
@JonathanCrd Thank you very much!
I confirm the error message "Package 'System.Drawing.Common' 4.7.0 has a known critical severity vulnerability, GHSA-rxg9-xrhp-64gj" disappeared for my use case (after I upgraded the nuget package "Azure.Extensions.AspNetCore.DataProtection.Keys" from v1.2.4 to v1.3.0):

![Image](https://github.com/user-attachments/assets/68cc7710-5f0d-49fb-9b80-b12f6997fd12)
 
The confirmation box explains correctly and clearly that the nuget package "System.Drawing.Common" v4.7.0 will be uninstalled as the result of the parent nuget package update:
![Image](https://github.com/user-attachments/assets/43c9cf7d-a79b-4129-af4c-ac2542edb11f)
