### ISSUE TITLE
WebSiteUpdateParameters.WebSiteHostNameSslState is missing name property

### ISSUE THREAD

**Issue by niklaslundberg** [Azure/azure-sdk-for-net#472]
I cannot set SSL host name bindings in Azure Websites with the .NET SDK since there is no &quot;name&quot; property in class WebSiteUpdateParameters.WebSiteHostNameSslState.

A workaround is to manually make a PUT JSON request.<p><a href="https://github.com/Azure/azure-sdk-for-net/issues/472">https://github.com/Azure/azure-sdk-for-net/issues/472</a></p>

**Comment by matt-gibbs** [comment]
It is there now
https://github.com/Azure/azure-sdk-for-net/blob/master/src/WebSiteManagement/Generated/Models/WebSiteUpdateParameters.cs#L99
