### ISSUE TITLE
Getting the FQDN (or public ip) of a load balancer is not fluent

### ISSUE THREAD

**Issue by Ofekw** [Azure/azure-sdk-for-net#4720]
To get the public facing ip of a load balancer, we can get the IP id in a fluent manner, but then we have to call the base azure object to get the corresponding IP for the IP id provided. 

`var ipList = azure.VirtualMachineScaleSets.GetByResourceGroup("xxxxx","xxxxx").GetPrimaryInternetFacingLoadBalancer().PublicIPAddressIds `

`azure.PublicIPAddresses.GetById(ipList.First()).Dump()`

This isn't too fluent. It would be ideal if `PublicIPAddressIds` would return a list of IP objects with .PublicIpAddress property on it. 

Thoughts?

I could be fetching the IP address wrong, how should I go about it so it's fluent?

Cheers,
Ofek

**Comment by shahabhijeet** [comment]
@Ofekw can you give us more details, what version of SDK you are referencing to.
Also is this .NET Fluent library?

**Comment by shahabhijeet** [comment]
@Ofekw can you open an issue in the Fluent repo
https://github.com/Azure/azure-libraries-for-net/

Closing...
