### ISSUE TITLE
BingVisualSearch parameters missing

### ISSUE THREAD

**Issue by MCKRUZ** [Azure/azure-sdk-for-net#4722]
Here https://docs.microsoft.com/en-us/rest/api/cognitiveservices/bingvisualsearch/images/visualsearch

It indicates that there are three uri parameters that can be attached to the visual search API string
Mkt, safeSearch, setLang.

Right now there is no way with this DLL to put those parameters in.  Will you be creating a way?

**Comment by shakao** [comment]
Yes, these parameters will be exposed in the next version of the SDK, and you will be able to pass values into your call to VisualSearchMethodAsync, similar to how URI parameters are currently set in the [Web Search SDK](https://github.com/Azure-Samples/cognitive-services-dotnet-sdk-samples/blob/master/BingSearchv7/BingWebSearch/WebSearchSamples.cs#L203).

**Comment by ChrisHMSFT** [comment]
Hi @MCKRUZ ,

The latest version of the SDK supports these input parameters: https://www.nuget.org/packages/Microsoft.Azure.CognitiveServices.Search.VisualSearch/

Thanks,
Chris
