### ISSUE TITLE
[BUG] AppService GetConnectionStringsAsync Exception

### ISSUE THREAD

**Issue by wchigit** [Azure/azure-sdk-for-net#47234]
### Library name and version

Azure.ResourceManager.AppService version 1.0.2

### Describe the bug

Run into same issue as [#46683](https://github.com/Azure/azure-sdk-for-net/issues/38950) and [#389](https://github.com/Azure/azure-sdk-for-net/issues/38950)

error message: Execution failed. The requested operation requires an element of type 'Object', but the target element has type 'Array'.. Exception: System.InvalidOperationException: The requested operation requires an element of type 'Object', but the target element has type 'Array'.
at System.Text.Json.ThrowHelper.ThrowJsonElementWrongTypeException(JsonTokenType expectedType, JsonTokenType actualType)
at Azure.ResourceManager.AppService.Models.ConnectionStringDictionary.DeserializeConnectionStringDictionary(JsonElement element)
at Azure.ResourceManager.AppService.WebAppsRestOperations.ListConnectionStringsAsync(String subscriptionId, String resourceGroupName, String name, CancellationToken cancellationToken)
at Azure.ResourceManager.AppService.WebSiteResource.GetConnectionStringsAsync(CancellationToken cancellationToken)

### Expected behavior

Successfully get and deserialize connection string dictionary.

### Actual behavior

The requested operation requires an element of type 'Object', but the target element has type 'Array'.

### Reproduction Steps

Error from production log. Correlation ID: afdf60e2-2a37-4df2-bf0c-2e29c82eb0b5
Request:
"message": {"requestMethod":"POST","requestUri":"https://management.azure.com/subscriptions/3b84045b-7604-4c84-adc7-c57db640b71b/resourceGroups/rg-rat-we-test-kronos/providers/Microsoft.Web/sites/func-rat-we-test-kronos-argus/config/connectionstrings/list?api-version=2021-02-01","duration":1254.7295,"correlationId":"afdf60e2-2a37-4df2-bf0c-2e29c82eb0b5","requestHeaderLengths":{"Accept":16,"x-ms-arm-signed-obo-token":2262,"x-ms-correlation-request-id":36,"x-ms-client-request-id":36,"x-ms-return-client-request-id":4,"User-Agent":115,"Authorization":1327},"requestContentLength":0,"responseCode":200,"contentLength":482}

**Comment by HarveyLink** [comment]
Hi @wchigit , please try the latest version of Azure.ResourceManager.AppService.
