### ISSUE TITLE
Inconsistent information about default request timeout

### ISSUE THREAD

**Issue by mic-hnk** [Azure/azure-sdk-for-net#47240]
### Type of issue

Outdated article

### Description

Hi,

This [comment](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/5e6232d25f84074d5008e97670d3e0dc07891f0e/Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs#L380)  says default RequestTimeout is 60 seconds.

Actual default value seems to come from this [line](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/5e6232d25f84074d5008e97670d3e0dc07891f0e/Microsoft.Azure.Cosmos/src/ConnectionPolicy.cs#L21) and it's 6 seconds.

Which makes this [comment](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/5e6232d25f84074d5008e97670d3e0dc07891f0e/Microsoft.Azure.Cosmos/src/ConnectionPolicy.cs#L130) inaccurate too.

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.fluent.cosmosclientbuilder.withrequesttimeout?view=azure-dotnet

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos.Fluent/CosmosClientBuilder.xml

### Document Version Independent Id

50c6f556-cb99-7c2d-877f-67b8cbd548ea

### Article author

@azure-sdk

### Metadata

* ID: 0646ee69-5f80-49d9-924f-d2574afa9fa7 
* Service: **azure-cosmos-db**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the Cosmos SDK packages are maintained as [#4898](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/4898).
