### ISSUE TITLE
[BUG]  Additional messages cannot be added when using CreateRunStreamingAsync or CreateRunAsync

### ISSUE THREAD

**Issue by sandrohanea** [Azure/azure-sdk-for-net#47244]
### Library name and version

Azure.AI.Projects 1.0.0-alpha.20241114.1

### Describe the bug

When trying to run an assistant turn, and add additional user messages in a single call, the SDK is not allowing it.

The reason is that `additionalMessages` property is of type `IEnumerable<ThreadMessage> additionalMessages = null` for both `CreateRunStreamingAsync` and `CreateRunAsync`

As an SDK user, I'm not able to construct that object (which requires Id, ThreadId, assistantId, etc) in order to store additional messages before running the thread run,

CreateMessageAsync is using less properties and can be called without these properties (Id, createddate, etc):
![Image](https://github.com/user-attachments/assets/ed790077-58e4-4c85-ae97-df2a597eb500)

Alternative, call the CreateMessageAsync before calling the CreateRunAsync():
![Image](https://github.com/user-attachments/assets/5fe7db21-04cb-46cb-9b1f-80f9db9b1c7b)

But this will result in unnecessary calls the Agent API.

Please, change the additionalMessages to a property similar with `CreateMessageRequest` (that is currently internal) in order to be able to send additional messages when running the agent response.

### Expected behavior

It is expected to be able to add additional messages when creating the thread run.

### Actual behavior

It is not possible to add the additional messages

### Reproduction Steps

See above

### Environment

Host:
Version: 9.0.0
Architecture: x64
Commit: 9d5a6a9aa4

**Comment by ShivangiReja** [comment]
Hi @sandrohanea,  Thank you for reporting this issue and sharing detailed reproduction steps.  

The issue appears to be related to how the `additionalMessages` property is defined in the underlying TypeSpec. We haven’t manually created a type for this property, and it follows the schema defined in the TypeSpec file. You can review the spec for `additionalMessages` here:  
[TypeSpec Reference](https://github.com/Azure/azure-rest-api-specs/blob/17ab26e678f06460cd154e2c0cb187aae158f4bf/specification/ai/Azure.AI.Projects/agents/runs/models.tsp#L202).

cc: @jhakulin @dargilco

**Comment by ShivangiReja** [comment]
Here’s an alternate approach you can use to make it work:

In the C# SDK, we provide both convenience methods and protocol methods. The issue lies in the convenience method, where we use input and output models. However, you can still use the protocol method without any issues. Protocol methods allow you pass the raw request and retrieve the raw response directly.

You can call this protocol method:
```csharp
Task<Response> CreateRunAsync(string threadId, RequestContent content, RequestContext context = null)
```

**Comment by ShivangiReja** [comment]
Fixed: https://github.com/Azure/azure-sdk-for-net/pull/47272
