### ISSUE TITLE
[BUG] ErrorMessage not returned when CreateThreadAsync method fails

### ISSUE THREAD

**Issue by sandrohanea** [Azure/azure-sdk-for-net#47242]
### Library name and version

Azure.AI.Projects 1.0.0-alpha.20241114.1

### Describe the bug

Use the following code with the dotnet sdk:

var clientOptions = new AIProjectClientOptions();

// just adding `x-ms-enable-preview` header
clientOptions.AddPolicy(new CustomHeadersPolicy(), HttpPipelinePosition.PerCall);

var projectClient = new AIProjectClient(
   "not-trusted-AIProject-Subscription",
   new DefaultAzureCredential(),
   clientOptions);

var agentClient = projectClient.GetAgentsClient();
var thread = await agentClient.CreateThreadAsync();

Make sure you use some subscription that is not allowed yet to access Agents.

### Expected behavior

 A clear error is shown

### Actual behavior

Simple 400 is returned, without correlation IDs not error message:
Service request failed.
Status: 400 (Bad Request)

Headers:
Date: Mon, 18 Nov 2024 17:22:44 GMT
Transfer-Encoding: chunked
Connection: keep-alive
Request-Context: REDACTED

### Reproduction Steps

Executing the CreateThreadAsync method for a subscription that was not allowed yet to use the agents will result in 400

### Environment

Host:
  Version:      9.0.0
  Architecture: x64
  Commit:       9d5a6a9aa4

**Comment by ShivangiReja** [comment]
To clarify, the SDK does not manipulate or remove error messages provided by the service. The `RequestFailedException` is thrown based on the response received from the Azure service. In this case, the service returned a 400 (Bad Request) status code without additional error details in the response body.
