### ISSUE TITLE
[BUG] Can't disassociate NATGateway from Subnet

### ISSUE THREAD

**Issue by lissdy** [Azure/azure-sdk-for-net#47261]
### Library name and version

Azure.ResourceManager.Network 1.9.0

### Describe the bug

I need to disassociate NATGateway from Subnet with SDK, while set ` subnetData.NatGatewayId = null`, hit below error

>Content:
{"error":{"code":"InvalidRequestFormat","message":"Cannot parse the request.","details":[{"code":"MissingJsonReferenceId","message":"Value for reference id is missing. Path properties.natGateway."}]}}

```
            // get the SubnetResource
            ResourceIdentifier subnetResourceId = SubnetResource.CreateResourceIdentifier(subscriptionId, resourceGroupName, virtualNetworkName, subnetName);
            SubnetResource subnet = client.GetSubnetResource(subnetResourceId);
            SubnetResource result = await subnet.GetAsync();
            var subnetData = result.Data;
            subnetData.NatGatewayId = null;
            var subnetCollection = client.GetVirtualNetworkResource(VirtualNetworkResource.CreateResourceIdentifier(subscriptionId, resourceGroupName, virtualNetworkName)).GetSubnets();
            // hit bad request exception
            var operation = await subnetCollection.CreateOrUpdateAsync(WaitUntil.Started, subnetName, subnetData, default);
```

### Expected behavior

The SDK supports NAT Gateway disassociation

### Actual behavior

Hit exception while set `NatGatewayId` to null

### Reproduction Steps

```
            SubnetResource subnet = client.GetSubnetResource(subnetResourceId);
            SubnetResource result = await subnet.GetAsync();
            var subnetData = result.Data;
            subnetData.NatGatewayId = null;
            await subnet.UpdateAsync(WaitUntil.Started, subnetData);
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Thank you @lissdy for your feedback, @HarveyLink please look into this issue.

**Comment by mcgallan** [comment]
@lissdy  Thank you for your feedback. I have written code that works correctly and meets your expected requirements. You can refer to it to modify your code to achieve your needs. Here is the relevant code snippet for you:
```
var subnetResource = (await networkResource.GetSubnets().CreateOrUpdateAsync(WaitUntil.Completed, subnet2Name, subnet)).Value;

var updatedata = subnetResource.Data;

Assert.AreEqual(gatewayId, updatedata.NatGatewayId);

updatedata.NatGatewayId = null;

updatedata.NatGateway = null;

var updateResponse = await subnetResource.UpdateAsync(WaitUntil.Completed, updatedata);

Assert.AreEqual(null, updateResponse.Value.Data.NatGatewayId);
```
