### ISSUE TITLE
[BUG] Not able to get all apps that use a Hybrid Connection in an App Service Plan

### ISSUE THREAD

**Issue by JagodaMika** [Azure/azure-sdk-for-net#47267]
### Library name and version

Azure.ResourceManager.AppService

### Describe the bug

Get all apps that use a Hybrid Connection in an App Service Plan.

Request:
GET /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Web/serverfarms/{name}/hybridConnectionNamespaces/{namespaceName}/relays/{relayName}/sites<>?api-version=2024-04-01
Response:
The requested operation requires an element of type 'String', but the target element has type 'Object'.

### Expected behavior

Correctly get all apps that use a Hybrid Connection in an App Service Plan 

### Actual behavior

Not able to parse request response to expected type (string)

### Reproduction Steps

var appServicePlan = await _azureResourceGroup.GetAppServicePlanAsync("someAppServicePlanName");
var appServicePlanResource = await appServicePlan.Value.GetAsync();
var relays = appServicePlanResource.Value.GetHybridConnectionRelaysAsync();
await foreach (var relayOverview in relays)
{
      var relay = await appServicePlanResource.Value.GetAppServicePlanHybridConnectionNamespaceRelayAsync(relayOverview.ServiceBusNamespace, 
                        relayOverview.Name);
      var listOfAppServicesWhichAreUsingHybridConnection = relay.Value.GetWebAppsByHybridConnectionAsync();
}

**Comment by JagodaMika** [comment]
The same problem for sync method GetWebAppsByHybridConnection()

**Comment by ArthurMa1978** [comment]
Thank you @JagodaMika for your feedback, @HarveyLink please look into this issue.

**Comment by mcgallan** [comment]
@JagodaMika Thank you for your feedback. I tried to reproduce the issue using the code you provided, but I did not encounter the problem you mentioned. Here is the code I used for reproduction: 
```
AppServicePlanResource plan = client.GetAppServicePlanResource(new ResourceIdentifier("myResourceId"));
var relays = plan.GetHybridConnectionRelaysAsync();
await foreach (var relayOverview in relays)
{
    var relay = await plan.GetAppServicePlanHybridConnectionNamespaceRelayAsync(relayOverview.ServiceBusNamespace, relayOverview.Name);
    var listOfAppServicesWhichAreUsingHybridConnection = relay.Value.GetWebAppsByHybridConnectionAsync();
}
```
(I used an AppService plan resource that contains a web app, and the web app is configured with two HybridConnections). Based on the tests conducted with version 1.3.0 of AppService, I did not find this issue. If possible, please provide more information so that we can better assist you in resolving the problem.

**Comment by JagodaMika** [comment]
Hi @mcgallan The code you wrote works, but when you try to iterate through 'listOfAppServicesWhichAreUsingHybridConnection' to get actual values from it, then you will receive an exception which I mentioned:

System.InvalidOperationException: 'The requested operation requires an element of type 'String', but the target element has type 'Object'.'

Sorry I didn't clear that out.
