### ISSUE TITLE
[BUG] Can't connect to AppInsights with Azure.Monitor.Query with ManagedIdentity.

### ISSUE THREAD

**Issue by vpetit-reimagine** [Azure/azure-sdk-for-net#47295]
### Library name and version

Azure.Monitor.Query 1.5.0

### Describe the bug

Following the example, it is impossible for an Azure Function to actually connect to the AppInsights through the package with

```cs
var client = new MetricsQueryClient(new DefaultAzureCredential(options)); // Where options holds the managed identity ID with `ManagedIdentityClientId` property
```

### Expected behavior

The Azure Function should be able to read the Azure AppInsights it is trying to access to.

### Actual behavior

Depending on what I am trying to test, I get either:
- `DefaultAzureCredential failed to retrieve a token from the included credentials. `
- if using `new MetricsQueryClient(new ManagedIdentityCredential(id))` I get `ManagedIdentityCredential authentication failed: User-assigned managed identity is not supported by the detected managed identity environment.` (there is nothing in the documentation explaining what

### Reproduction Steps

1. Create an App Service on Azure
2. Create an Application Insights resource on Azure linked to the App Service
3. Create an Azure function (timer or http based) using the `Azure.Monitor.Query` and `Azure.Identity` packages, specifying the previous app resource as the one to query (in the form of `/subscriptions/{id}/resourceGroups/{rg-name}/providers/microsoft.insights/components/{app-insights-name}`).
4. Assign either a system or user-defined managed identity to the Azure Function
5. Run the Azure Function

**Comment by christothes** [comment]
Hi @vpetit-reimagine - 
In your repro steps you mention running the Azure Function - are you running it locally or deployed to Azure?

If deployed to Azure, can you get logging of the error while using the `ManagedIdentityCredential`?

For console output, you would just need to add the following line to your program. 

```c#
using AzureEventSourceListener listener = AzureEventSourceListener.CreateTraceLogger();
```

If you need to log the output somewhere other than the console, this can be done as described in [these docs](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Diagnostics.md#custom-logging-callback). 

for example: 

```c#
using AzureEventSourceListener listener = new AzureEventSourceListener(
    (args, message) => myLogger.Log("[{0:HH:mm:ss:fff}][{1}] {2}", DateTimeOffset.Now, args.Level, message),
    level: EventLevel.Verbose);
```

**Comment by HAKIMBIBI67A** [comment]
/::01

**Comment by HAKIMBIBI67A** [comment]
/::01

**Comment by christothes** [comment]
> Do you see anything else I could investigate further just in case my intuition is false?

No, this seems like the most promising route to pursue.

**Comment by vpetit-reimagine** [comment]
Alright, I didn't have time to fully come back to this, but I have to say that so far, I am still unsuccessful with this.

First of all, it is still impossible to debug anything locally because of this `ManagedIdentity` restriction that is impossible to get rid of, and secondly, it seems that `availabilityResults/availabilityPercentage` is not working anymore and I can't find anything in the whole documentation about how we are even supposed to actually use this package.

The full documentation examples are so basic that they are useful for any real use case.
