### ISSUE TITLE
Unable to update Bot Channel Property using SDK

### ISSUE THREAD

**Issue by mehtanilay10** [Azure/azure-sdk-for-net#4731]
Hey guys,
I need to Create/Update/Delete Channel connections dynamically, for this, I am using `Microsoft.Azure.Management.BotService` package.
I have faced some **issues while updating any channel configurations**, however, Create/Delete operation working proper.

```
TelegramChannel channel = new TelegramChannel()
{
    Properties = new TelegramChannelProperties
    {
        IsEnabled = isEnabled
    }
};
BotChannel botChannel = new BotChannel { Location = "global", Properties = channel };

BotChannel updatedChannelDetails = null;
AzureBotServiceClient botServiceClient = GetBotServiceClient();
updatedChannelDetails = await botServiceClient.Channels.UpdateAsync(resourceGroupName, botServiceName, channelName, properties: channel);
return updatedChannelDetails;
```
I have checked for Facebook/Skype/Slack/Telegram. Then I have downloaded Its source code and debugged it. And found that its **Rest API generates 500!**

### Request URL
[PUT] https://management.azure.com/subscriptions/●●●/resourceGroups/●●●/providers/Microsoft.BotService/botServices/●●●/channels/TelegramChannel?api-version=2017-12-01

### Request Body
```

{
    "properties": {
        "channelName": "TelegramChannel",
        "properties": {
            "isEnabled": true
        }
    }
}
```
### Response
```
{
    "error": {
        "code": "InternalServerError",
        "message": "Encountered internal server error. Please try again."
    }
}
```
Please resolve this as soon as possible I am sticke due to this issue.

**Comment by jsquire** [comment]
Closing this out as there has been no recent engagement.  Please feel free to reopen or file a new issue if this remains a problem with the current version of the library.
