### ISSUE TITLE
Adding app settings to existing Function App creates a new storage account 

### ISSUE THREAD

**Issue by david-jarman** [Azure/azure-sdk-for-net#4733]
Creating a new storage account is an unintended consequence of calling

```CSharp
functionApp.Update()
.WithAppSetting("key", "value")
.Apply();
```
This also causes the currently deployed functions to be lost since the function app is now pointing at a new storage account.

The offending code is in [FunctionAppImpl.cs](https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/AppService/FunctionAppImpl.cs) Line 163-166

**Comment by hovsepm** [comment]
@david-jarman please open this issue in the Fluent SDK repo here - https://github.com/Azure/azure-libraries-for-net/

**Comment by david-jarman** [comment]
Done

https://github.com/Azure/azure-libraries-for-net/issues/457
