### ISSUE TITLE
[QUERY] AuthenticateAsync() causes error invalid_client AADSTS650057

### ISSUE THREAD

**Issue by DanielHWe** [Azure/azure-sdk-for-net#47358]
### Library name and version

Azure.Identity 1.13.1

### Query/Question

I tryed to persist a [AuthenticationRecord](https://learn.microsoft.com/dotnet/api/azure.identity.authenticationrecord?view=azure-dotnet) like described in section "Silently authenticate a user with AuthenticationRecord and TokenCachePersistenceOptions" of [TokenCache](
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/samples/TokenCache.md)

But I always ending in getting the error ```Error details: error invalid_client error_description: AADSTS650057: Invalid resource. The client has requested access to a resource which is not listed in the requested permissions in the client's application registration.```

Eroor shown in Browser by calling AuthenticationRecord authRecord = await credential.AuthenticateAsync();

I tryed to change the scope and the API Permissions in entry, currently I have File.ReadWrite.All, Application.ReadWrite.All, Directory.ReadWrite.All, AuthenticationContext.Read.All, offline_access, openid, profile, User.read.

But that did not help.

I have a WPF Desktop App and how may I able to Silently authenticate a user, so he must not login within the browser each time the application is restarted. (Currently I'm using InteractiveBrowserCredentialOptions)

### Environment

Windows 11, .Net 8, WPF Desktop App

**Comment by christothes** [comment]
Hi @DanielHWe - 
Are you able to get a token interactively without persisting the AuthenticationRecord or does this error only occur when trying the silent auth flow? If the error occurs both ways, this sounds like an Entra ID configuration issue. If interactive authentication works but silent doesn't, can you provide a minimal code snippet that reproduces the problem including any relevant details about your app registration configuration?

**Comment by DanielHWe** [comment]
It happens on call `` await interactiveCredential.AuthenticateAsync(); ```

```private readonly string[] _scopes = new[] { "https://graph.microsoft.com/.default" };
private const string AUTH_RECORD_PATH = "./tokencache.bin";

_options = new InteractiveBrowserCredentialOptions
{
    TenantId = tenantId,
    ClientId = clientId,
    AuthorityHost = AzureAuthorityHosts.AzurePublicCloud,
    RedirectUri = new Uri("http://localhost:8080/secret"),
    TokenCachePersistenceOptions = new TokenCachePersistenceOptions
    {
        Name = "OneDriveService",
        UnsafeAllowUnencryptedStorage = true
    }
};
//...

AuthenticationRecord authRecord = await interactiveCredential.AuthenticateAsync(); //Here it crashes

 using (var authRecordStream = new FileStream(AUTH_RECORD_PATH, FileMode.Create, FileAccess.Write))
 {
     await authRecord.SerializeAsync(authRecordStream);
 }
```

**Comment by christothes** [comment]
Hi @DanielHWe - 
Can you describe exactly what your scenario is? Are you authenticating to an App Registration? If so, how is it configured and what scope are you using for the [AuthenticateAsync](https://github.com/Azure/azure-sdk-for-net/blob/f9343631ac651cc8fcd089bcf492a764661544a3/sdk/identity/Azure.Identity/src/Credentials/InteractiveBrowserCredential.cs#L146)?

**Comment by DanielHWe** [comment]
I have a WPF Dektop App in with I up and download files from oneDrive via MS Graph. This works but each time I restart the app it is needed to login in the browser. I want to reduce this and store the informations for a temporary time.

> Are you authenticating to an App Registration?
Yes to access the oneDrive of the user.

Scopes are:
```private readonly string[] _scopes = new[] { "https://graph.microsoft.com/.default" };```

**Comment by christothes** [comment]
> I have a WPF Dektop App in with I up and download files from oneDrive via MS Graph. This works but each time I restart the app it is needed to login in the browser. I want to reduce this and store the informations for a temporary time.

How are you using the credential when it works?

> AuthenticationRecord authRecord = await interactiveCredential.AuthenticateAsync(); //Here it crashes

In your code above you are calling `AuthenticateAsync` with no parameters. Does the problem occur when you call it with a `TokenRequestContext` containing the scope mentioned above?

**Comment by DanielHWe** [comment]
I used the documentation here: [TokenCache.md](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/samples/TokenCache.md)

So in case the AuthenticationRecord was allready stored, I would use:
```var credential = new InteractiveBrowserCredential(
    new InteractiveBrowserCredentialOptions
    {
        TokenCachePersistenceOptions = new TokenCachePersistenceOptions(),
        AuthenticationRecord = authRecord
    });```

TokenRequestContext is working.
