### ISSUE TITLE
Azure.Storage.DataMovement.Blobs Samples Issue

### ISSUE THREAD

**Issue by jianingwang123** [Azure/azure-sdk-for-net#47377]
1.
Section [link1](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.DataMovement.Blobs/samples/Sample01b_HelloWorldAsync.cs#L936):

![Image](https://github.com/user-attachments/assets/89191da0-c57e-4f81-93d5-00e14bde7fae)

 [link2](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.DataMovement.Blobs/samples/Sample01b_HelloWorldAsync.cs#L870):

![Image](https://github.com/user-attachments/assets/ee095fb7-a0e0-4861-9030-9a9e17ba0dc0)

**Reason:**
The link for test is invalid.

**Suggestion:**
Change to a valid test link.

2.
Section [link3](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.DataMovement.Blobs/samples/Sample01b_HelloWorldAsync.cs#L60):

![Image](https://github.com/user-attachments/assets/97d524ab-083f-490b-86d3-3dccba37d090)

**Reason:**
System.ArgumentException : Cannot use TokenCredential without HTTPS.

**Suggestion:**
Change the links to https.

@scottaddie , @jsquire ,@rohit-ganguly and @amnguye for notification.

**Comment by amnguye** [comment]
Let's fix this similar to how I fixed this for the regular Blobs Package samples
https://github.com/Azure/azure-sdk-for-net/pull/45083/files

**Comment by jianingwang123** [comment]
@nickliu-msft According to the updated code, a new issue is encountered：
**Section**[ link](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.DataMovement.Blobs/samples/Sample01b_HelloWorldAsync.cs#L940):
![Image](https://github.com/user-attachments/assets/b44f586f-9c36-4a39-833c-c81ed6cf1171)
**Reason:**
System.ArgumentException : Unable to find resource provider for transfer source with provider id: blob. Please ensure you have registered the required resource provider with TransferManagerOptions.ResumeProviders.
