### ISSUE TITLE
Fh

### ISSUE THREAD

**Issue by lfputnam** [Azure/azure-sdk-for-net#47383]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/microsoft.applicationinsights.telemetryclient.trackpageview?view=azure-dotnet#microsoft-applicationinsights-telemetryclient-trackpageview(microsoft-applicationinsights-datacontracts-pageviewtelemetry)

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.ApplicationInsights/TelemetryClient.xml

### Document Version Independent Id

03a23c8e-e7ea-2e9d-b285-b74935e99cb2

### Article author

@azure-sdk

### Metadata

* ID: 54fc335f-c066-35a8-e81e-f1b90f9025fd 
* Service: **azure-monitor**
* Sub-service: **application-insights**

**Comment by jsquire** [comment]
Issue is not actionable.   Closing as spam.
