### ISSUE TITLE
[QUERY] The issue is that when an exception occurs in SessionInitializingAsync, messages still continue to be processed in the ProcessMessageAsync method

### ISSUE THREAD

**Issue by solonkooi** [Azure/azure-sdk-for-net#47408]
### Library name and version

Azure.Messaging.ServiceBus 7.18.1

### Query/Question

We use **ServiceBusSessionProcessor** in our project
We encountered a problem that when an exception occurs in **SessionInitializingAsync**, messages still continue to be processed in the **ProcessMessageAsync** method
We tried calling the **ReleaseSession** method in case of an exception in **SessionInitializingAsync**, but in this case, messages with this session stop being processed at all

- Is there any way to cancel / postpone session processing in case of an error in **SessionInitializingAsync**?

- How can we track current sessions in processing? Maybe some utilities?

### Environment

dotnet 8

**Comment by solonkooi** [comment]
I'll add a code snippet to make it easier to understand what I mean.

```   
    private async Task SessionInitializingAsync(ProcessSessionEventArgs args)
    {
        var userId = int.Parse(args.SessionId);
        await using var scope = serviceScopeFactory.CreateAsyncScope();
        try
        {
            var sessionState = await PrepareSessionStateAsync(args, scope, userId);
            await args.SetSessionStateAsync(sessionState);
        }
        catch (Exception ex)
        {
            args.ReleaseSession();
            logger.LogError(ex, "State preparation failed for user {UserId}", userId);
            throw;
        }
    }
```

**Comment by solonkooi** [comment]
@JoshLove-msft Yes, I also expected this to help in my case, but in fact, after calling ReleaseSession, processing for messages in this session no longer begins even after a while. I added logs to the above code.
Perhaps there is some kind of waiting for new messages for the session?
 It would be extremely useful to be able to track which sessions are currently open, is this possible?

**Comment by JoshLove-msft** [comment]
It's possible that the processor is just busy processing other sessions for a while so it doesn't get to the session you just released, but it should still eventually process it. There is not currently a way to track which sessions are open. See https://github.com/Azure/azure-sdk-for-net/issues/20569.

**Comment by solonkooi** [comment]
@JoshLove-msft  I was able to figure out that the behavior I described was caused by the throw exception in the code I provided
I removed that line and now it works as expected
