### ISSUE TITLE
HttpRecorder uses obsolete Newtsonsoft features

### ISSUE THREAD

**Issue by chrimc62** [Azure/azure-sdk-for-net#4744]
HttpRecorder uses TypeNameAssemblyFormat which is obsolete as of Newtonsoft v11.0.  This means that clients are forced to use either Newtonsoft 9 or 10 and cannot use the latest.

[ObsoleteAttribute("TypeNameAssemblyFormat is obsolete. Use TypeNameAssemblyFormatHandling instead.")]
public FormatterAssemblyStyle TypeNameAssemblyFormat { get; set; }

**Comment by shahabhijeet** [comment]
@chrimc62 this has been fixed in the latest version of [httprecorder](https://www.nuget.org/packages/Microsoft.Azure.Test.HttpRecorder/1.13.3)
