### ISSUE TITLE
[BUG] ApiManagementUserResource.GenerateSsoUriAsync   method returns  incorrect hotsname

### ISSUE THREAD

**Issue by tranepura** [Azure/azure-sdk-for-net#47459]
### Library name and version

Azure.ResourceManager.ApiManagement 1.2.0.0

### Describe the bug

 ApiManagementUserResource.GenerateSsoUriAsync   method returns APIM portal  hostname instead of APIM developer portal hostname.          

As a workaround for this issue , I  replace the correct developer portal  host name  for SSO uri for the solution .

```
var ssoUriObject = new Uri(generatedSsoUri);

string ssoDevPortalUrl = $"{devPortalUrl}{ssoUriObject.PathAndQuery}";

return ssoDevPortalUrl; 
```

Actual returned  SSO Uri screenshot         
 ![Image](https://github.com/user-attachments/assets/9a77c794-7b3f-4ae4-bc03-6235fd6e1833)

### Expected behavior

 ApiManagementUserResource.GenerateSsoUriAsync   should return  APIM  Developer portal  hostname/domain name 

i.e   https://**apim-name.developer.azure-api.net**/signin-sso?token=token

### Actual behavior

 ApiManagementUserResource.GenerateSsoUriAsync   returns  APIM  portal  hostname/domain name 

i.e   https://**apim-name.portal.azure-api.net**/signin-sso?token=token

![Image](https://github.com/user-attachments/assets/9769163f-0a58-40f0-bc33-a63279ae85d6)

### Reproduction Steps

 ```
ResourceIdentifier serviceIdentifier = ApiManagementServiceResource.CreateResourceIdentifier(subscriptionId, rg, apimName);
 ApiManagementServiceResource apiManagementService = client.GetApiManagementServiceResource(serviceIdentifier);

 // List all users and filter by email 
 AsyncPageable<ApiManagementUserResource> pageableUsers = apiManagementService.GetApiManagementUsers().GetAllAsync();

 //Get the traget user by  user property email 
 ApiManagementUserResource targetUser = null;

 await foreach (ApiManagementUserResource user in pageableUsers)
 {
     if (user.Data.Email.Equals(userEmail, StringComparison.OrdinalIgnoreCase))
     {
         targetUser = user;
         break;
     }
 }


//Get SSO dev portal URI of that user 

 var ssoUri = await targetUser.GenerateSsoUriAsync();

var generatedSsoUri = ssoUri.Value.Value;
```

### Environment

.NET SDK:
 Version:           8.0.404
 Commit:            7b190310f2
 Workload version:  8.0.400-manifests.1c2a2fce
 MSBuild version:   17.11.9+a69bbaaf5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.404\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [aspire]
   Installation Source: VS 17.10.35122.118
   Manifest Version:    8.2.2/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.2.2\WorkloadManifest.json
   Install Type:        FileBased

Host:
  Version:      9.0.0
  Architecture: x64
  Commit:       9d5a6a9aa4

.NET SDKs installed:
  8.0.303 [C:\Program Files\dotnet\sdk]
  8.0.307 [C:\Program Files\dotnet\sdk]
  8.0.404 [C:\Program Files\dotnet\sdk]
  9.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Thank you @tranepura for your feedback, @HarveyLink please look into this issue.

**Comment by HarveyLink** [comment]
Hi @tranepura , Thank you for reaching out to us. This matter does not fall under the responsibilities of Azure SDK team. We kindly recommend that you could [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request), as they would be best equipped to assist you with your inquiry. Please let us know if you need further guidance on how to reach them!
