### ISSUE TITLE
[BUG] InteractiveBrowserCredential does not cache persistently with TokenCachePersistenceOptions

### ISSUE THREAD

**Issue by user-45-20** [Azure/azure-sdk-for-net#47457]
### Library name and version

Azure.Identity 1.13.1

### Describe the bug

The docs at https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/samples/TokenCache.md describe how token caching works in Azure.Identity: in-memory caching is offered out-of-the-box, while persistent caching to disk can be activated by passing `TokenCachePersistenceOptions = new TokenCachePersistenceOptions()` to credentials. However, in my case this option appears to have no effect.

Full code:
```
using Azure.Core;
using Azure.Identity;

namespace MyApp
{
    internal class Program
    {
        static async Task Main(string[] args)
        {
            var credential = new InteractiveBrowserCredential(
                new InteractiveBrowserCredentialOptions()
                {
                    ClientId = "my_clientid",
                    TenantId = "my_tenantid",
                    TokenCachePersistenceOptions = new TokenCachePersistenceOptions(),
                });

            var context = new TokenRequestContext(["user.read"]);
            Console.WriteLine((await credential.GetTokenAsync(context)).Token);
        }
    }
}
```

According to the section "Credentials supporting token caching", `InteractiveBrowserCredential` supports persistent disk caching.
Note that the second described approach - manually caching the `AuthenticationRecord` - does indeed work, but according to the docs, so should the code I provided above.

[Here's](https://old.reddit.com/r/dotnet/comments/1c5aybt/token_caching_for_graphserviceclient/) another user running into this behavior a few months ago.

### Expected behavior

upon first program run the user authenticates in a browser; subsequent program runs require no interaction and just print the cached token

### Actual behavior

every program run starts the browser to authenticate

### Reproduction Steps

1. register an app on Entra
2. add "http://localhost" to its redirect URIs
3. replace the client and tenant ID, then build and run the program provided in the description

**Comment by christothes** [comment]
Hi @user-45-20 ,
Setting `TokenCachePersistenceOptions` alone only makes the cache serialize to disk rather than staying in memory. If you're intent is to get silent authentication in subsequent logins, you must persist and supply an `AuthenticationRecord` as described [in this sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/samples/TokenCache.md#silently-authenticate-a-user-with-authenticationrecord-and-tokencachepersistenceoptions)

**Comment by user-45-20** [comment]
> Hi [@user-45-20](https://github.com/user-45-20) , Setting `TokenCachePersistenceOptions` alone only makes the cache serialize to disk rather than staying in memory. If you're intent is to get silent authentication in subsequent logins, you must persist and supply an `AuthenticationRecord` as described [in this sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/samples/TokenCache.md#silently-authenticate-a-user-with-authenticationrecord-and-tokencachepersistenceoptions)

OK, thanks for the information. I'm wondering: what is the cache on disk used for if it's not used to recover the token after the process restarts?

**Comment by christothes** [comment]
> OK, thanks for the information. I'm wondering: what is the cache on disk used for if it's not used to recover the token after the process restarts?

The cache alone is not enough information. The `AccountRecord` indicates which account to lookup in the cache.

**Comment by user-45-20** [comment]
So is there a scenario where using `TokenCachePersistenceOptions` without `AuthenticationRecord` makes sense or provides some functionality over just standard in-memory token caching?

**Comment by christothes** [comment]
> So is there a scenario where using `TokenCachePersistenceOptions` without `AuthenticationRecord` makes sense or provides some functionality over just standard in-memory token caching?

Not really, unless you just want your cache serialized to disk for some reason.
