### ISSUE TITLE
001

### ISSUE THREAD

**Issue by thekingq20** [Azure/azure-sdk-for-net#47455]
### Type of issue

Other (describe below)

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.client.deviceclient.createfromconnectionstring?view=azure-dotnet#microsoft-azure-devices-client-deviceclient-createfromconnectionstring(system-string)

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Devices.Client/DeviceClient.xml

### Document Version Independent Id

7d284e10-a359-df7e-1452-797812fc2b0e

### Article author

@azure-sdk

### Metadata

* ID: 488a4cba-d957-de87-8afb-4b563433f128 
* Service: **azure-iot-hub**

**Comment by jsquire** [comment]
Closing as spam
