### ISSUE TITLE
[QUERY] New version for Azure.ResourceManager.DevTestLabs

### ISSUE THREAD

**Issue by zhiweiv** [Azure/azure-sdk-for-net#47461]
### Library name and version

Azure.ResourceManager.DevTestLabs 1.1.0

### Query/Question

Can you release a new version for Azure.ResourceManager.DevTestLabs? The feature https://github.com/Azure/azure-sdk-for-net/pull/41206 is need by us which is not available in current version.

BTW, Azure.ResourceManager.DevTestLabs 1.1.0 was released one year ago.

**Comment by HarveyLink** [comment]
Released new version [Azure.ResourceManager.DevTestLabs](https://www.nuget.org/packages/Azure.ResourceManager.DevTestLabs)
