### ISSUE TITLE
How do you set the NIC

### ISSUE THREAD

**Issue by rob011235** [Azure/azure-sdk-for-net#47499]
### Type of issue

Typo

### Description

[Enter feedback here]
How do you set the NIC when you are crating a virtual machine. It is read only.

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.connectedvmwarevsphere.virtualmachinedata.networkinterfaces?view=azure-dotnet-preview#azure-resourcemanager-connectedvmwarevsphere-virtualmachinedata-networkinterfaces

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.ResourceManager.ConnectedVMwarevSphere/VirtualMachineData.xml

### Document Version Independent Id

8752da48-cab5-c171-6852-4ef7d39c3ecb

### Article author

@azure-sdk

### Metadata

* ID: 9dfd1b45-c86f-b232-3ffe-6e34aebbfc57 
* Service: **azure**

**Comment by jsquire** [comment]
Hi @rob011235i.  Thank you for reaching out and we regret that you're experiencing difficulties.  As a convention across libraries in the Azure SDK, collection types for models are intentionally read-only.   Their value can be set by mutating the existing collection.  This can be done by either adding members after the object has been constructed or using C#'s initializer syntax as part of construction.   

```csharp
// Example: adding items after construction.
var data = new VirtualMachineData(AzureLocation.EastUS);
data.NetworkInterfaces.Add(new NetworkInterface { Label = "One" });
data.NetworkInterfaces.Add(new NetworkInterface { Label = "Two" });

// Example: initializer syntax
var data = new VirtualMachineData(AzureLocation.EastUS);
{
    NetworkInterfaces = 
    {
        new NetworkInterface { Label = "One" },
        new NetworkInterface { Label = "Two" }
    }
};
```
