### ISSUE TITLE
Mr Peter kardashein

### ISSUE THREAD

**Issue by Sirkingpedro112818** [Azure/azure-sdk-for-net#47502]
### Type of issue

Typo

### Description

[Enter feedback here]trancver funds

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cognitiveservices.knowledge.qnamaker.ioperations?view=azure-dotnet-legacy

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CognitiveServices.Knowledge.QnAMaker/IOperations.xml

### Document Version Independent Id

a292984b-7873-c6db-738d-52fd30f58283

### Article author

@azure-sdk

### Metadata

* ID: 941f4ee9-a595-523d-6794-cf645bc6b341 
* Service: **azure-ai-services**

**Comment by jsquire** [comment]
Closing as spam
