### ISSUE TITLE
[BUG]OpenAI中的chatClient.CompleteChatAsync(..)方法在触发TPM的Token数限制后，会导致一直处于等待中。

### ISSUE THREAD

**Issue by qideqian** [Azure/azure-sdk-for-net#47569]
### Library name and version

Azure.AI.OpenAI 2.1.0

### Describe the bug

`  ClientResult<ChatCompletion> completion = await chatClient.CompleteChatAsync(
                chatMessages
                , new ChatCompletionOptions()
                {
                }, cancellationTokenSource.Token);
`
会处于一直等待中，不抛异常，得不到结果。

### Expected behavior

提示触发TPM的异常，不会一直处于等待，不抛异常，不出结果。

### Actual behavior

一直处于等待，不抛异常，不出结果。

### Reproduction Steps

ClientResult<ChatCompletion> completion = await chatClient.CompleteChatAsync(
                chatMessages
                , new ChatCompletionOptions()
                {
                }, cancellationTokenSource.Token);

**Comment by jsquire** [comment]
Hi @qideqian.   Thank you for opening this issue and we regret that you're experiencing difficulties.  Unfortunately, this repository is English-based and we're unable to assist with issues in other languages.   I'm going to close this out, but I'd encourage you to open a new issue in English for assistance.
