### ISSUE TITLE
[BUG] COSMOS: container vector policy and vector indexing policies are not supported

### ISSUE THREAD

**Issue by repne** [Azure/azure-sdk-for-net#47563]
Vector indexing policies are not supported: [Documentation](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/how-to-manage-indexing-policy?tabs=dotnetv3%2Cpythonv3#vector-indexing-policy-examples) [Source code](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cosmosdb/Azure.ResourceManager.CosmosDB/src/Generated/Models/CosmosDBIndexingPolicy.cs)

Container vector policy is also not supported: [Documentation](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/vector-search#container-vector-policies)

**Library name and version**
Azure.ResourceManager.CosmosDB 1.3.2

**Workaround**
Using the cosmos client library:

```cs
// this only works with connection string, no other credentials
var connectionStrings = CosmosAccount.GetConnectionStrings(ConsoleApp.CancellationToken);
var ConnectionString = connectionStrings.First().ConnectionString;
var cosmosClient = new CosmosClient(ConnectionString);

await cosmosClient
.GetDatabase(CosmosDatabase.Data.Name)
.CreateContainerIfNotExistsAsync(new ContainerProperties("actors-storage", "/partitionKey")
{
    VectorEmbeddingPolicy = new
    ([
        new()
        {
            Path = "/state/vector1",
            DataType = VectorDataType.Float32,
            DistanceFunction = DistanceFunction.Cosine,
            Dimensions = 2048,
        },
        new()
        {
            Path = "/state/vector2",
            DataType = VectorDataType.Float32,
            DistanceFunction = DistanceFunction.Cosine,
            Dimensions = 2048,
        }
    ]),
    IndexingPolicy = new()
    {
        IndexingMode = IndexingMode.Consistent,
        Automatic = true,
        IncludedPaths =
        {
            new IncludedPath { Path = "/*" }
        },
        ExcludedPaths =
        {
            new ExcludedPath { Path = "/\"_etag\"/?" },
            new ExcludedPath { Path = "/state/vector1/*" },
            new ExcludedPath { Path = "/state/vector2/*" }
        },
        VectorIndexes =
        {
            new VectorIndexPath()
            {
                Path = "/state/vector1",
                Type = VectorIndexType.QuantizedFlat,
            },
            new VectorIndexPath()
            {
                Path = "/state/vector2",
                Type = VectorIndexType.DiskANN,
            }
        }
    }
},
cancellationToken: ConsoleApp.CancellationToken);
```

**Comment by ArthurMa1978** [comment]
Hey @repne , thank you for reaching out to us about the Azure SDK for .NET.
The Cosmos SDK is generated from the [swagger spec](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/cosmos-db/resource-manager) which is owned by service side and not the SDK side, so for your feedback please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) to ask service team to update the swagger spec and then upgrade the SDK.

Therefore, we are closing this issue for now, if you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.
