### ISSUE TITLE
[QUERY] Get patchAssessmentResults/latest of HybridCompute Resource

### ISSUE THREAD

**Issue by TheToor** [Azure/azure-sdk-for-net#47579]
### Library name and version

Azure.ResourceManager.HybridCompute 1.0.0 / Azure.ResourceManager.Compute 1.6.0

### Query/Question

You should be able to call "patchAssessmentResults/latest" and "patchAssessmentResults/latest/softwarePatches/{id}" on a HybridComputeMachineResource or ComputeMachineResource to get the lastest assesment result.
But the ARM client only seems to expose a way to run a new assesment and get the result with the AssessPatches() method.
This would always invoke a new assessment instead of getting the latest.
How can I get the latest update details without invoking a new assessment?
Or how can I use the ArmClient to manually call "/subscriptions/<Subscription>/resourceGroups/<ResourceGroup>/providers/Microsoft.HybridCompute/machines/<Machine>/patchAssessmentResults/latest" for me without having to deal with authentication and authorization?

### Environment

.NET 9.0 on Windows with Visual Studio 2022

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Thank you for your feedback @TheToor , @HarveyLink please look into this issue.

**Comment by mcgallan** [comment]
@TheToor Thank you for reaching out to us. Regarding the issue you mentioned, we currently do not have a viable solution. 
On one hand, the methods provided by the SDK only support running a new assessment and obtaining results through the AssessPatches() method. There is no other way to retrieve the VirtualMachineAssessPatchesResult at this time. 
On the other hand, the Swagger we are using does not include a request path similar to `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachines/{vmName}/assessPatches/latest`. This results in the server being unable to process such requests, making this approach practically infeasible.
This matter does not fall under the responsibilities of Azure SDK team. We kindly recommend that you could [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request), as they would be best equipped to assist you with your inquiry. Please let us know if you need further guidance on how to reach them!

**Comment by TheToor** [comment]
Thanks for the info. I stole that path from the network debugging tool while using the Azure Portal.
Either way I found that you can use the Azure.ResourceManager and query for patchassessmentresources.
That will include the updates. Not sure if that is what Azure Portal is doing in the background.
Leaving this here for others to find.
I think you can close this then.
