### ISSUE TITLE
[BUG][DocumentIntelligence] Not able to set features on the AnalyzeDocumentOptions

### ISSUE THREAD

**Issue by ruudjanssenlyanthe** [Azure/azure-sdk-for-net#47588]
### Library name and version

[Azure.AI.DocumentIntelligence1.0.0]

### Describe the bug

Hi All,

I'm not able to set the features i want, the property has only a get, new code:

```
DocumentIntelligenceClient client = new DocumentIntelligenceClient(new Uri(Endpoint), credential);

List<DocumentAnalysisFeature> features = new List<DocumentAnalysisFeature>();
var keyValuePairFeature = new DocumentAnalysisFeature("KeyValuePairs");
features.Add(keyValuePairFeature);

AnalyzeDocumentOptions analyzeDocumentOptions = new AnalyzeDocumentOptions("prebuilt-invoice", BinaryData.FromBytes(file))
{	
				Pages = "1-3",
				Features = "error when trying to set this"
};
							
var operation = client.AnalyzeDocument(WaitUntil.Completed, analyzeDocumentOptions);
```

The overload on the AnalyzeDocument method call has a features parameter, but than i can't pass the options with the binaryData anymore compared to the code on the 1.0.0.beta3 package:

```
DocumentIntelligenceClient client = new DocumentIntelligenceClient(new Uri(Endpoint), credential);

AnalyzeDocumentContent analyzeDocumentContent = new AnalyzeDocumentContent();
analyzeDocumentContent.Base64Source = BinaryData.FromBytes(file);

List<DocumentAnalysisFeature> features = new List<DocumentAnalysisFeature>();
var keyValuePairFeature = new DocumentAnalysisFeature("KeyValuePairs");
features.Add(keyValuePairFeature);

var operation = client.AnalyzeDocument(WaitUntil.Completed, "prebuilt-invoice", analyzeDocumentContent, pages: "1-3", features: features);
```

### Expected behavior

Be able to set the features or get another option that works.

### Actual behavior

Build error when trying to set the features

### Reproduction Steps

See code above

### Environment

Latest Visual Studio running on .net 6, .net8 and net framework 4.8

**Comment by ruudjanssenlyanthe** [comment]
Ticket can be closed, found the way to set this. Perhaps a good idea to put it in the documentation.

```
DocumentIntelligenceClient client = new DocumentIntelligenceClient(new Uri(Endpoint), credential);
							
AnalyzeDocumentOptions analyzeDocumentOptions = new AnalyzeDocumentOptions("prebuilt-invoice", BinaryData.FromBytes(file))
{	
	Pages = "1-3",
        Features = { DocumentAnalysisFeature.KeyValuePairs }
};

var operation = client.AnalyzeDocument(WaitUntil.Completed, analyzeDocumentOptions);
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by kinelski** [comment]
The usage of features is illustrated in our samples: [Key-value pairs extraction](https://github.com/Azure/azure-sdk-for-net/tree/60684220695c49d3512811c7d26d86064f7b05f0/sdk/documentintelligence/Azure.AI.DocumentIntelligence/samples/Sample_AddOnCapabilities.md#key-value-pairs-extraction).

To check other common scenarios, see our [samples README](https://github.com/Azure/azure-sdk-for-net/tree/60684220695c49d3512811c7d26d86064f7b05f0/sdk/documentintelligence/Azure.AI.DocumentIntelligence/samples).
