### ISSUE TITLE
Event notification for KeyVault secret change

### ISSUE THREAD

**Issue by kolauy** [Azure/azure-sdk-for-net#4759]
My project has a requirement to apply new secret automatically when it's changed in KeyVault. Is there a way to receive a notification from KeyVaultClient object when the KeyVault secret is changed?

**Comment by shahabhijeet** [comment]
@kolauy is this a native app you are running or is this a azure deployed web app that you want to be notified when resources change in azure key vault?
Have you tried using Alerts that are exposed in Azure KeyVault, it gives you couple of options like azure functions or logic apps that you can integrate with?

Their isn't anything in the client SDK to notify you, so any support you need for notification will have to be from the service side.
