### ISSUE TITLE
[QUERY] EventHub tracing is missing

### ISSUE THREAD

**Issue by adeliab** [Azure/azure-sdk-for-net#47590]
### Library name and version

Azure.Monitor.OpenTelemetry.AspNetCore 1.2.0

### Query/Question

EventHub's EventProcessor.Process tracing is missing since using OpenTelemetry.

![Image](https://github.com/user-attachments/assets/8460030f-9707-4ad4-a539-13628118a514)

Documentation says to include the "Azure.*" or "Azure.Messaging.*" sources but since .UseAzureMonitor() method already has .AddSource("Azure.*"), I assume I don't need to add additional customization?

This is the setup
```
builder.Services.AddOpenTelemetry()
    .UseAzureMonitor(options =>
    {
        options.SamplingRatio = openTelemetrySettings.SamplingRatio;
    })
    .ConfigureResource(builder => builder.AddService(Constants.Logging.RoleName));
```

Is there something I'm missing here?

**Comment by gastonmuijtjens** [comment]
@adeliab The Azure Event Hub SDK still considers `ActivitySource` support as experimental: https://github.com/Azure/azure-sdk/blob/main/docs/tracing/distributed-tracing-conventions.md#messaging-libraries. Therefore, you might have to add the `AZURE_EXPERIMENTAL_ENABLE_ACTIVITY_SOURCE` environment variable in order for Event Hub spans to show up: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Diagnostics.md#enabling-experimental-tracing-features

**Comment by adeliab** [comment]
thanks @gastonmuijtjens . the traces are back after enabling that env variable
