### ISSUE TITLE
[QUERY] - How does one analyze a document with Features and QueryFields in Azure Document Intelligence 1.0.0?

### ISSUE THREAD

**Issue by VladDerptastic** [Azure/azure-sdk-for-net#47630]
### Library name and version

Azure.AI.DocumentIntelligence 1.0.0

### Query/Question

In Azure.AI.DocumentIntelligence.1.0.0-beta3, one could pass in _features_ (such as keyValueParis for layout scan) and _queryFields_ through the `AnalyzeDocumentAsync()` method, which still accepted an `AnalyzeDocumentContent` object.

However, in the official 1.0.0 release, `AnalyzeDocumentContent` has been replaced by [AnalyzeDocumentOptions](https://github.com/Azure/azure-sdk-for-net/blob/Azure.AI.DocumentIntelligence_1.0.0/sdk/documentintelligence/Azure.AI.DocumentIntelligence/CHANGELOG.md#breaking-changes), and `AnalyzeDocumentAsync()` no longer accepts features and queryFields in the signatures that expect an `AnalyzeDocumentOptions` object.
```cs
public virtual async Task<Operation<AnalyzeResult>> AnalyzeDocumentAsync(WaitUntil waitUntil, AnalyzeDocumentOptions options, CancellationToken cancellationToken = default)
```

`AnalyzeDocumentOptions` itself has `Features` and `QueryFields` properties, but they are **read-only** ([source](https://github.com/Azure/azure-sdk-for-net/blob/Azure.AI.DocumentIntelligence_1.0.0/sdk/documentintelligence/Azure.AI.DocumentIntelligence/src/AnalyzeDocumentOptions.cs)), so setting them in there is apparently not supported.

The other option to pass them on in `AnalyzeDocumentAsync()` is by passing in a `RequestContent` object instead. However, that signature only returns a `BinaryData` object, whereas I was hoping for the original `AnalyzeResult`, and the one that is returned when passing in `AnalyzeDocumentOptions` over `RequestContent`. 
```cs
public virtual async Task<Operation<BinaryData>> AnalyzeDocumentAsync(WaitUntil waitUntil, string modelId, RequestContent content, string pages = null, string locale = null, string stringIndexType = null, IEnumerable<DocumentAnalysisFeature> features = null, IEnumerable<string> queryFields = null, string outputContentFormat = null, IEnumerable<AnalyzeOutputOption> output = null, RequestContext context = null)
```

In `DocumentIntelligenceClient.cs` I can see that, to return an `AnalyzeResult`, some internal conversion from `BinaryData` is taking place:

```cs
public virtual async Task<Operation<AnalyzeResult>> AnalyzeDocumentAsync(WaitUntil waitUntil, AnalyzeDocumentOptions options, CancellationToken cancellationToken = default)
{
    Argument.AssertNotNull(options, nameof(options));

    using RequestContent content = options.ToRequestContent();
    RequestContext context = FromCancellationToken(cancellationToken);
    Operation<BinaryData> response = await AnalyzeDocumentAsync(waitUntil, options.ModelId, content, options.Pages, options.Locale, DefaultStringIndexType, options.Features, options.QueryFields, options.OutputContentFormat?.ToString(), options.Output, context).ConfigureAwait(false);
    return ProtocolOperationHelpers.Convert(response, FetchAnalyzeResultFromAnalyzeOperation, ClientDiagnostics, "DocumentIntelligenceClient.AnalyzeDocument");
}
```

The simple question is - **What's the intended way for a user to specify `Features` and `QueryFields` for a document analysis request?** Is de-serializing BinaryData into AnalyseResult just an additional one liner? If so, why does the internal deserialization implementation seem to have so many arguments/steps? Was setting the `Features` and `QueryFields` properties to _read-only_ in `AnalyzeDocumentOptions` a mistake that slipped QA? What's the expectation here?

### Environment

.NET SDK:  8.0.300
Microsoft Visual Studio Community 2022 (64-bit) - Current, Version 17.10.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by kinelski** [comment]
@VladDerptastic,

The `Features` and `QueryFields` collections have no setters, as you mentioned, but the collections can still be modified. For example:
```cs
var options = new AnalyzeDocumentOptions("prebuilt-layout", uriSource)
{
    Features = { DocumentAnalysisFeature.FontStyling }
};
```

Feel free to take a look at our [Analyze a document with add-on capabilities](https://github.com/Azure/azure-sdk-for-net/tree/a491c5696ca9a18c790ac42a78db84c72af1c1cc/sdk/documentintelligence/Azure.AI.DocumentIntelligence/samples/Sample_AddOnCapabilities.md) sample for more details.
