### ISSUE TITLE
[QUERY] How to get all possible AppServicePlan configurations from an Azure subscription?

### ISSUE THREAD

**Issue by wbarisch** [Azure/azure-sdk-for-net#47644]
### Library name and version

Azure.ResourceManager.AppService 1.3.0

### Query/Question

**I want to get a List with all possible AppService Hosting Plan configuration settings of my Azure subscription(Location, Tier, Size,...). Possibly through skus.**
 - It should be done using Azure SDK for .NET.
 - I already have a SubscriptionResource object to work with. Every sample and code here will assume "subscription" variable to be that object.
Essentially, I want to get the app service hosting plan pricing options, like in the portal: ![Image](https://github.com/user-attachments/assets/3a1afc46-1afd-4bd0-afa0-c76081dd381c)

**What have I tried?**

- Using GetSkusAsync() returns null every-time. I've tried with different subscriptions and result is the same.
```
var skus = await AppServiceExtensions.GetSkusAsync(subscription);
foreach (var sku in skus.Value.Skus)
{
        Console.WriteLine($"- Tier: {sku.Tier}, Size: {sku.Size}, Name: {sku.Name}");
}
```

- I thought maybe was that the SubscriptionResource could not just get the hosting plan configuration plans like in Azure portal because the SubscriptionResource is used to create,store,modify already the resources. So I looked to try with MockableAppServiceSubscriptionResource. But I could't get an object out of it that would make me be able to call the function in the first try(GetSkusAsync).

If you know how to get possible hosting plan configuration. Please do share your knowledge. And if it not currently possible with Azure sdk for .net, I would also appreciate the info.

Thank you and best regards,
Wesley

### Environment

.Net 8.0 Console Application

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Thank you for your feedback @wbarisch , @HarveyLink please look into this issue.

**Comment by welovej** [comment]
hi @wbarisch   I tried to reproduce  and got the same condition as below. There may have some troubles in the service end.
<img width="865" alt="Image" src="https://github.com/user-attachments/assets/e7de5fa3-a286-4473-9a55-10905353ed7f" />

But we can achieve the global  in another way like this:
```
            var client = new ArmClient(new DefaultAzureCredential());
            ResourceIdentifier subId = SubscriptionResource.CreateResourceIdentifier(subscriptionId);
            SubscriptionResource subResource = client.GetSubscriptionResource(subId);

            await foreach (var appServicePlan in subResource.GetAppServicePlansAsync())
            {
                Console.WriteLine($"App Service Plan ID: {appServicePlan.Id}");
                Console.WriteLine($"SKU Name: {appServicePlan.Data.Sku.Name}");
                Console.WriteLine($"SKU Tier: {appServicePlan.Data.Sku.Tier}");
            }
```

**Comment by wbarisch** [comment]
@welovej Thank you for the answer. What I was trying to achiev is to get a princing plan listing to print in order to make the user of my program choose between the possible hosting plan princings to create a new hosting plan for an web app. It seems like what your code does is to get
all the created service app hosting plans inside a subscription.
Forgive me for not being clear in my question. I'll edit it to

**Comment by welovej** [comment]
> hi [@wbarisch](https://github.com/wbarisch) I tried to reproduce and got the same situation as below. There may have some troubles in the service end. <img alt="Image" width="869" src="https://private-user-images.githubusercontent.com/26237688/398646670-a7b371ae-f45a-4188-8be6-5231869ceb60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyNjUwMzUsIm5iZiI6MTczNTI2NDczNSwicGF0aCI6Ii8yNjIzNzY4OC8zOTg2NDY2NzAtYTdiMzcxYWUtZjQ1YS00MTg4LThiZTYtNTIzMTg2OWNlYjYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDAxNTg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyMGMzNWE1MjA1ZWM1MTY0N2Q2MDkzOGE1Zjg5ZGRiZGM3NDcwMzY1MmQ2MjM5ZjBjZDQyOGE1ZjI2ODFhNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-1CzVODIzjaIvg3LR3BgRazrGZumSZzi6WlfSzxxypM">
> 
> But we can achieve the global in another way like this:
> 
> ```
>             var client = new ArmClient(new DefaultAzureCredential());
>             ResourceIdentifier subId = SubscriptionResource.CreateResourceIdentifier(subscriptionId);
>             SubscriptionResource subResource = client.GetSubscriptionResource(subId);
> 
>             await foreach (var appServicePlan in subResource.GetAppServicePlansAsync())
>             {
>                 Console.WriteLine($"App Service Plan ID: {appServicePlan.Id}");
>                 Console.WriteLine($"SKU Name: {appServicePlan.Data.Sku.Name}");
>                 Console.WriteLine($"SKU Tier: {appServicePlan.Data.Sku.Tier}");
>             }
> ```

Hey @wbarisch ,  thank you for reaching out to us about the Azure SDK for .NET. Unfortunately, this issue is related to the service side and not the SDK side, so we are not able to help you with it. Therefore, we are closing this issue for now. If you need more assistance, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). We apologize for any inconvenience this may cause you.
We value your feedback and we want to make sure that your problem is solved. If you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.

**Comment by wbarisch** [comment]
@welovej I already contacted them, they said this is an Azure SDK issue. I just want to get the pricing list like in Azure Portal, but from Azure SDK. Is this not possible? If it is not possible just say so!

**Comment by welovej** [comment]
> [@welovej](https://github.com/welovej) I already contacted them, they said this is an Azure SDK issue. I just want to get the pricing list like in Azure Portal, but from Azure SDK. Is this not possible? If it is not possible just say so!

hi @wbarisch , I have posted the http request screenshot above.  And The service end just reponsed null. How could be it's an issue of SDK?

**Comment by wbarisch** [comment]
@welovej Okay, makes sense now. Thank You! I thought your request was the same query you did in your sdk-.net code. I will contact Azure support again then.
