### ISSUE TITLE
Packages failing BinSkim analysis

### ISSUE THREAD

**Issue by barborico** [Azure/azure-sdk-for-net#4764]
Hi,

I am working on a Microsoft service and our deployment pipeline (CDPx) runs [BinSkim](https://github.com/Microsoft/binskim) analysis as part of official builds. I have had to create an exception because our dependency on Azure Key Vault and Azure app authentication libraries is causing this analysis to break the build. Specifically, the following packages yield BadSigningAlgorithm (BA2022) errors with the message: "Cryptographically weak signatures: [digest algorithm: 'sha1NoSign' + digest encryption algorithm: 'RSA']".

- Microsoft.Azure.KeyVault.dll
    - Microsoft.Rest.ClientRuntime.dll
    - Microsoft.Rest.ClientRuntime.Azure.dll
- Microsoft.Azure.KeyVault.WebKey.dll
- Microsoft.Azure.Services.AppAuthentication.dll

Given that BinSkim is a part of Azure SDL, the Azure SDK should pass its muster. Is there a plan to use an approved signing process for these packages? And if not, can one be formed?

Thank you!

**Comment by djj0809** [comment]
Hi, any update on this?

**Comment by dsgouda** [comment]
@djj0809 @cofitz1 Could you specify the versions of the dll with which you face this issue? Are you able to see the issue with latest version of the dlls?

**Comment by pakrym** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Comment by mj1856** [comment]
FYI - I was able to reproduce this on older versions of these dlls.

To resolve ensure you have
- `Microsoft.Azure.Services.AppAuthentication` >= 1.2.1
- `Microsoft.Azure.KeyVault` >= 3.0.1

If, like me, you were getting these as dependencies of some other package, you can add them directly to the project to override the ones specified by the dependency.  (Ex. `Microsoft.Extensions.Configuration.AzureKeyVault`)
