### ISSUE TITLE
New-AzureRmVmss : Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by WellorZhang** [Azure/azure-sdk-for-net#4767]
Hi All,
I encountered the "Object reference not set to an instance of an object." failure when using the command "New-AzureRmVmss", any idea on this?
•	New-AzureRmVmss -ResourceGroupName $rgname -VMScaleSetName $vmssname -VirtualMachineScaleSet $vmssConfig

New-AzureRmVmss : Object reference not set to an instance of an object.
At **.ps1:138 char:1
+ New-AzureRmVmss -ResourceGroupName $rgname -VMScaleSetName $vmssname  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmVmss], NullReferenceException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.Automation.NewAzureRmVmss

<img width="1211" alt="t1" src="https://user-images.githubusercontent.com/41512705/45613586-6d38c600-ba99-11e8-8d4a-69d4eb25fbd4.png">

Thanks,
Wellor

**Comment by shahabhijeet** [comment]
@WellorZhang please open this issue in the [azure powershell repository](https://github.com/azure/azure-powershell)
