### ISSUE TITLE
Microsoft.Threading.Tasks Version=1.0.12.0 is required at runtime for Microsoft.Azure.Management.ApiManagement nuget package

### ISSUE THREAD

**Issue by mcphersonwhite** [Azure/azure-sdk-for-net#4769]
We have run into an issue at runtime, the absolute best time to have an issue, where it seems that the Microsoft.Azure.Management.ApiManagement.UsersOperations.ListAsync(String resourceGroupName, String serviceName, QueryParameters query, CancellationToken cancellationToken) operation requires the presence of Microsoft.Threading.Tasks. 

Closer inspection of the Microsoft.Azure.Management.ApiManagement, shows that the runtime dependency is not listed as a dependency of the nuget package. 

Could you please make this a dependency? or perhaps drop the dependency and rely on System.Threading.Tasks?

**Comment by mcphersonwhite** [comment]
Seems that this is fixed in the pre-release version of the nuget package.
What is the expected eta on the next stable version release for the Microsoft.Azure.Management.ApiManagement nuget package?

**Comment by jsquire** [comment]
Closing this out as there has been no recent engagement.  Please feel free to reopen or file a new issue if this remains a problem with the current version of the library.
