### ISSUE TITLE
.net core 2.2 in Azure

### ISSUE THREAD

**Issue by MSAppsDev** [Azure/azure-sdk-for-net#4778]
Hi,

When can we expect .net core 2.2 in Azure?

**Comment by shahabhijeet** [comment]
@MSAppsDev we are in process of understanding the scenarios that needs .NET Core 2.2 support.
Could you list few scenarios that require .NET Core 2.2

**Comment by MSAppsDev** [comment]
Hi,

we need for Azure MSI functionality.

**Comment by racheldelman** [comment]
@shahabhijeet Any idea when .net core 2.2 will be available in Azure?

**Comment by pakrym** [comment]
.NET Core 2.2 is availible
