### ISSUE TITLE
Provide MsiAccessTokenProvider implemenation without ADAL dependency

### ISSUE THREAD

**Issue by CBaud** [Azure/azure-sdk-for-net#4780]
We'd like to use the MsiAccessTokenProvider implemenation in order to address AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1023. Unfortunately, consuming the current AppAuthentication library creates an implicit dependency on Microsoft.IdentityModel.Clients.ActiveDirectory that @brentschmaltz would like to avoid. Are there any options available, other than creating a private fork of the current implementation?

**Comment by brentschmaltz** [comment]
@CBaud we should be able to sort this out in a couple of days to sort this out.
Possibilities are
1. to layer on top, pull the KeyVault extensions into m.im.tokens, put this code into m.im.tokens.extensions.
2. add internal 'GetToken' code to m.im.tokens.

**Comment by nonik0** [comment]
Feel free use your own private fork to make these changes. We can't remove the ADAL dependency without losing half of our token providers that depend on ADAL. For instance, anyone developing on Service Fabric will need to use cert-based auth for their local development scenarios. It should be simple enough to remove the ADAL dependencies, but feel free to ping me if you need assistance if you choose to go down this path.

**Comment by brentschmaltz** [comment]
@nonik0 when we added support in IdentityModel for MSI, we ended up creating two assemblies.
The one with the ADAL dependency layers on top of the other.

This should simplify MSI usage and remove the dependency on ADAL.

**Comment by varunsh-msft** [comment]
This approach will duplicate the samples and guidance for using MSI for customers, which may get confusing, e.g. when to use one library vs. the other. If you have implemented a workaround for your project, can you please close this issue? Thanks!

**Comment by brentschmaltz** [comment]
@varunkch what samples are you referring to?

**Comment by varunsh-msft** [comment]
If you look at the [documentation](https://docs.microsoft.com/en-us/azure/key-vault/service-to-service-authentication#samples), there are 3 key samples listed. For each of them, customers can use Azure AD secret/ cert based auth for local development. This is common for [service fabric scenarios ](https://stackoverflow.com/questions/49859477/access-key-vault-from-local-service-fabric-cluster-with-msi)where local development cannot use developer identity. If a separate library is created that does not allow Azure AD secret/ cert based auth for local development, it will create confusion for customers.

**Comment by varunsh-msft** [comment]
Closing this issue as we cannot do this without ADAL. We need to support non-MSI scenarios in the library as well.
