### ISSUE TITLE
Microsoft.Rest.Clientruntime RetryAfterDelegatingHandler.SendAsync() is missing ConfigureAwait(false)

### ISSUE THREAD

**Issue by dbrink** [Azure/azure-sdk-for-net#4784]
I'm not entirely sure this is the correct repo for the Autorest C# client runtime.  Please point me in the right direction as it doesn't appear the source in this repo is up to date.   Version 2.3.13 adds RetryAfterDelegatingHandler, but the SendAsync method is missing ConfigureAwait(false) on both async calls it makes.  Version 2.3.12 fixed this in other places so it's unfortunate it was missed in the next release.

**Comment by ChrisRobbers** [comment]
I am getting a lot of random hangs after upgrading to this version, so that makes sense!

**Comment by shahabhijeet** [comment]
@dbrink we have identified this issue and have already fixed it. The current bits are under test and would be released end of this week.

**Comment by ChrisRobbers** [comment]
@shahabhijeet is this fixed with the 2.3.14 release?

**Comment by shahabhijeet** [comment]
Yes this is fixed in
https://www.nuget.org/packages/Microsoft.Rest.ClientRuntime/2.3.14
