### ISSUE TITLE
Exception while executing function: CreateRedboxResourcegroup. Microsoft.Rest.ClientRuntime.Azure.Authentication: Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.14.0.8, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

### ISSUE THREAD

**Issue by AmudhaPalani** [Azure/azure-sdk-for-net#4789]
The library Microsoft.Azure.Services.AppAuthentication has a dependency on Microsoft.IdentityModel.Clients.ActiveDirectory, Version>=3.14.2. But the SDK library Microsoft.Azure.Management.Graph.RBAC.Fluent has a dependency on same library for version=3.14.0.8

Please let me know how to resolve this dependency?

**Comment by shahabhijeet** [comment]
@AmudhaPalani please open the same issue in the below repo
https://github.com/Azure/azure-libraries-for-net/

Closing
