### ISSUE TITLE
Parameterize Prerelease tag for github releases

### ISSUE THREAD

**Issue by dsgouda** [Azure/azure-sdk-for-net#4807]
Following up from [here](https://github.com/Azure/azure-sdk-for-net/issues/4761), we need to parameterize a prerelease tag flag so that the github releases are posted correctly.

**Comment by jsquire** [comment]
Management pipelines have changed since this issue was filed.   Closing.   

//fyi: @ArthurMa1978 - please feel free to reopen if this is still needed.
