### ISSUE TITLE
[Suggestion] Document Service Configuration parameter is not base64

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-sdk-for-net#481]
To specify .cscfg contents, [REST API says](http://msdn.microsoft.com/en-us/library/windowsazure/ee460813.aspx):

&gt; **Configuration:** Required. Specifies the base-64 encoded service configuration file for the deployment.

However the library does conversion from string to base64 under the hood but this is not clear. This took me a while to figure it out. It is a good feature indeed but an explicitly stating that it does not require b64 encoded string on `DeploymentCreateParameters.Configuration` field would be nice. Currently it is:

        // Summary:
        //     Required. The service configuration file for the deployment.
        public string Configuration { get; set; }<p><a href="https://github.com/Azure/azure-sdk-for-net/issues/481">https://github.com/Azure/azure-sdk-for-net/issues/481</a></p>

**Comment by markcowl** [comment]
Should be fixed in the latest update.  Please open a new issue if not.
