### ISSUE TITLE
Consider delisting Microsoft.Azure.Services.AppAuthentication 1.1.0-preview

### ISSUE THREAD

**Issue by tjrobinson** [Azure/azure-sdk-for-net#4826]
Since the [nuget package for Microsoft.Azure.Services.AppAuthentication 1.1.0-preview](https://www.nuget.org/packages/Microsoft.Azure.Services.AppAuthentication/1.1.0-preview) is much older than `1.0.0`, `1.0.2` and `1.0.3` and appears to offer no functionality that isn't available in the `1.0.x` versions, should it be de-listed from the NuGet Gallery to avoid confusion?

It can cause problems (assembly binding redirects) when used in a project that uses `Microsoft.Extensions.Configuration.AzureKeyVault`.

See also my comment on this blog post (if it's been approved yet): https://blogs.msdn.microsoft.com/cloud_solution_architect/2017/12/22/using-managed-service-identities-in-functions-to-access-key-vault/

**Comment by nonik0** [comment]
Delisting the package could cause a lot of builds to break for customers who already have that package in their solutions. We will be releasing 1.2.0-preview soon which should resolve this concern, as it will be the most recent release and well as highest version of AppAuth.

**Comment by tjrobinson** [comment]
@nonik0 Thanks for getting back to me on this. Good to hear that 1.2.0-preview will be available soon.

Regarding unlisting the package, it shouldn't cause anyone using that package any problems:

> nuget.org does not support permanent deletion of packages. Doing so would break every project depending on the availability of the package, especially with build workflows that involve package restore.
> 
> nuget.org does supports *unlisting* a package, which can be done in the package management page on the web site. Unlisted packages don't appear on nuget.org or in the Visual Studio UI, and do not appear in search results. Unlisted packages, however, can still be downloaded and installed by using an exact version number, which supports package restore. In addition, unlisted packages may still be discovered in the following specific scenarios:
> 
> - Package restore using floating versions (for example, `1.0.0-*`), if the latest available package matching the version or dependency constraints is an unlisted package.
> - Replication of packages through the catalog (as the catalog also contains unlisted packages).
>
> https://docs.microsoft.com/en-us/nuget/policies/deleting-packages

**Comment by nonik0** [comment]
@tjrobinson Thanks for that information; we were not aware. We will take a look and consider delisting the package. We have also released AppAuth 1.2.0-preview, which you can find here:
https://www.nuget.org/packages/Microsoft.Azure.Services.AppAuthentication/1.2.0-preview

**Comment by varunsh-msft** [comment]
Given that we have newer versions are available now, I do not see value in unlisting the older package. If there are samples/ code referring it, they will still download it. If someone is creating a new project, they are unlikely to use an older preview version. Let me know if you see a good reason for unlisting it now, else we can go ahead and close the issue. Thanks!
