### ISSUE TITLE
Enable WarningsAsErrors globally for all tests

### ISSUE THREAD

**Issue by dsgouda** [Azure/azure-sdk-for-net#4827]
Coming from https://github.com/Azure/azure-sdk-for-net/issues/4670 , we have enable WarningsAsErrors for most RPs. However some RPs have tests that need some additional fixes when enabling this flag.
Below is the list of RPs:
```
BatchAI
DataFactory
KeyVault
SqlManagement
Storage
StorSimple8000Series
Websites
```

We need to get these individual RPs to fix the warnings in their tests

**Comment by shahabhijeet** [comment]
@dsgouda let's start monitoring PRs from the above RPs and start asking them to fix their warnings.
