### ISSUE TITLE
Storage Account Count for subscription

### ISSUE THREAD

**Issue by lucasmaj** [Azure/azure-sdk-for-net#4830]
azure.StorageAccounts.Manager.Usages.List().First().CurrentValue appears to be counting only classic storage accounts. Is there a better way to get just count of all storage account in a subscription without listing them (zure.StorageAccounts.List().Count()) ?

**Comment by shahabhijeet** [comment]
@lucasmaj can you provide the full name of the package you are using, also provide the version number you are using.
Any information to reproduce this error will be helpful.

**Comment by lucasmaj** [comment]
using Microsoft.Azure.Management.Fluent;
using Microsoft.Azure.Management.ResourceManager.Fluent;

Microsoft.Azure.Management.Fluent 1.16.0
Microsoft.Azure.Management.Storage.Fluent 1.16.0

**Comment by lucasmaj** [comment]
Thank you for explaining. I see now. That is because the limit for storage accounts is per Subscription-Location?

**Comment by lucasmaj** [comment]
It appears that to get ListByLocation method we need to use Microsoft.Azure.Management.Storage package 9.0.0-preview?
Also what is the simplest way of getting ServiceClientCredentials from service principal creds? Currently getting exception:
Microsoft.Rest.Azure.CloudException: Response from service 'Microsoft.Storage' does not contain sufficient information to enforce access control policy.

**Comment by blueww** [comment]
9.0.0-preview Support ListByLocation , but 8.0.0-preview also support it.
You can look at the doc for how to use the SDK: https://azure.microsoft.com/da-dk/resources/samples/storage-dotnet-resource-provider-getting-started/

**Comment by blueww** [comment]
@lucasmaj 
We plan to close the issue as not hear from you for a long itme.
Feel free to let us know if you need any futher assistant.

@shahabhijeet 
Would you please help to close the issue, or give the permission to close the issue.

**Comment by dsgouda** [comment]
Closing per @blueww 's comments
