### ISSUE TITLE
Github: Maintain parity between swagger PR and .NET SDK PR

### ISSUE THREAD

**Issue by shahabhijeet** [Azure/azure-sdk-for-net#4843]
Ability to detect and create a mapping between Swagger PR and .NET SDK PR
Ability to update both PR with the mapping
 - Swagger PR should have .NET SDK PR info and vice versa.

**Comment by jsquire** [comment]
Given the age of this issue and the amount of automation changes since it was created, I'm closing this as stale.  Please feel free to reopen if this is still needed.
