### ISSUE TITLE
Add remaining resources to profile configs

### ISSUE THREAD

**Issue by dsgouda** [Azure/azure-sdk-for-net#4844]
There are a few resources for which we need to create profile tags in the spec repo

Resouce | Spec path | 2018-03-01-hybrid   spec version | 2017-03-09-profile   spec version
-- | -- | -- | --
dnsZones | dns/resourcemanager | 2016-04-01 | 2016-04-01
locks | resources/resourcemanager | 2016-09-01 | 2015-01-01
policyAssignments | resources/resourcemanager | 2016-12-01 | 2015-10-01-preview
policyDefinitions | resources/resourcemanager | 2016-12-01 | 2015-10-01-preview

Once this is done, we need to regenerate the code for multi profile SDKs (also involves fixing code generation scripts)

**Comment by jsquire** [comment]
Given the age of this and shift to track two management libraries, closing this out as stale.  Please feel free to reopen if this is still needed.
