### ISSUE TITLE
[Suggestion] Document difference of IHostedServiceOperations.Delete & .DeleteAll

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-sdk-for-net#487]
I guess one of them deletes deployments with disks (uses `comp=media` as documented in http://msdn.microsoft.com/en-us/library/windowsazure/gg441305.aspx) however both method signatures <nobr>(`Delete`, `DeleteAll`</nobr> &amp; their asyncs) have the same description on xmldocs:

```csharp
        // Summary:
        //     The Delete Hosted Service operation deletes the specified cloud service from
        //     Windows Azure. (see http://msdn.microsoft.com/en-us/library/windowsazure/gg441305.aspx
        //     for more information)
```<p><a href="https://github.com/Azure/azure-sdk-for-net/issues/487">https://github.com/Azure/azure-sdk-for-net/issues/487</a></p>
<!---@tfsbridge:{"tfsId":2060256}-->

**Comment by markcowl** [comment]
Closing as obsolete.  Please open a new issue if this is still a problem.

**Comment by ahmetalpbalkan** [comment]
@markcowl why am I opening a new issue if this is not fixed? Please reopen.
