### ISSUE TITLE
Setting default values for model properties are not being set

### ISSUE THREAD

**Issue by r-delgadillo** [Azure/azure-sdk-for-net#4877]
I have the following model defined in my swagger file but the generated C# SDK does not reflect setting the default value for this model when calling the constructor. Shouldn't the default value bet se to `IoTApps` as defined in the swagger file.

### Swagger Model
![image](https://user-images.githubusercontent.com/35089121/47032591-947dc400-d127-11e8-98a7-4321d108e6b2.png)

### Generated C# SDK
![image](https://user-images.githubusercontent.com/35089121/47032824-25ed3600-d128-11e8-808f-e2a3fa0038fa.png)

**Comment by shahabhijeet** [comment]
@r-delgadillo there are two way we can solve this problem:
1) have a default value generated and send it over wire
or
2) Let the service handle default values, this way no data is sent over wire.

We chose not to send default values over wire and increase the payload, currently services should be able to handle default values.
One good thing that comes out of this is, if there are any changes in the default values (which does not affect the datatypes, you don't need to regenerate the SDK.
Hope this addresses your concern.
