### ISSUE TITLE
Polling behavior is undocumented in asynchronous service operations

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-sdk-for-net#488]
I was expecting asynchronous (operation-id returning) calls like `IDeploymentOperations.CreateAsync` and `IStorageAccountOperations.CreateAsync` to return me the `OperationResponse` immediately after one call and allow me to call `GetOperationStatus(id)` to poll the service for completion. 

However I just realized all those methods internally retry until service operation is no longer in `InProgress` state. Adding such internal loop by default is limiting control of operations but making them more useful. Thanks, this is very nice of you. However this behavior is not documented properly. See Create Deployment method xmldocs:

&gt; 
&gt; Summary:
&gt;     The Create Deployment operation uploads a new service package and creates
&gt;     a new deployment in the staging or production environments. The Create Deployment
&gt;     operation is an asynchronous operation. **To determine whether the management
&gt;     service has finished processing the request, call Get Operation Status.** For
&gt;     more information on asynchronous operations, see Tracking Asynchronous Service
&gt;     Management Requests. (see http://msdn.microsoft.com/en-us/library/windowsazure/ee460813.aspx
&gt;     for more information)
&gt; 
&gt; Parameters:
&gt;     ...

(see the highlighted part above) It tells user to call GetOperationStatus method, however operation is already finished. I guess this comment is from MSDN for the REST call, however the client library exposes a different behavior and this should be noted in documentation.<p><a href="https://github.com/Azure/azure-sdk-for-net/issues/488">https://github.com/Azure/azure-sdk-for-net/issues/488</a></p>

**Comment by markcowl** [comment]
This is actually the function of the 'Begin.. functions.  The Create... functions will do polling

**Comment by ahmetalpbalkan** [comment]
@markcowl if so the comments on the method should be fixed. See my issue description above. Problem is with xmldocs.
