### ISSUE TITLE
ComputerVisionClient: Inconsistent exception handling (v3.2.0)

### ISSUE THREAD

**Issue by wahyuen** [Azure/azure-sdk-for-net#4905]
Currently, for some endpoints in the ComputerVisionClient, it appears to throw the following exception, ComputerVisionErrorException. eg. ListModelsWithHttpMessagesAsync, AnalyzeImageWithHttpMessagesAsync

However, it then appears that for some other endpoints, the client returns HttpOperationException. eg GenerateThumbnailWithHttpMessagesAsync

It would be great to make the exception handling consistent, given that as a consumer, we rely on them to facilitate things such as rate limit retries.

**Comment by navba-MSFT** [comment]
@ryogok, @TFR258, @tburns10. Could you please look into this once you get a chance ?

**Comment by JimSuplizio** [comment]
Hi @wahyuen, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
