### ISSUE TITLE
Microsoft.Azure.Services.AppAuthentication: Using AppKey/ ClientSecret in Authentication requires escaping "=" and ";" parameters

### ISSUE THREAD

**Issue by rohan3usturge** [Azure/azure-sdk-for-net#4908]
Hi Team,

When using the connection string for client secret. The library does not accept if client secret has any of the following characters. We need an ability to escape these characters while sending the client secret.

Both AAD1 and AAD2 versions are creating secrets containing either "=" or ";". 

`RunAs=App;AppId={appId};TenantId={tenantId};AppKey=asdasdsd;asdasdasd`

The following code breaks.

`Dictionary<string, string> connectionString1 = AzureServiceTokenProviderFactory.ParseConnectionString(connectionString);`

![image](https://user-images.githubusercontent.com/33190464/47293433-c27f6e80-d627-11e8-9e5d-b877d34437ef.png)

**Comment by rohan3usturge** [comment]
Hi Team,

Is anyone looking into this repo ?

**Comment by nonik0** [comment]
Hi Rohan, sorry for the delay in responding here. We will be fixing this for the next AppAuth release.

**Comment by Patrick-Braunstorfer** [comment]
This bug is still present in the current version. Is there an ETA on fixing this? Or adding a way to escape characters? Currently we are regenarating Client Secrets until we get one without = or ; which is not a proper solution.

**Comment by nonik0** [comment]
Hi @Patrick-Braunstorfer, thanks for your question! I am working on the next release now, which includes this fix. The next release should be out within the next couple of weeks and I will update this issue when it is released.

**Comment by nonik0** [comment]
Hi @rohan3usturge  and @Patrick-Braunstorfer,

Thanks for originally bringing this issue to our attention. We have [a new preview release](https://www.nuget.org/packages/Microsoft.Azure.Services.AppAuthentication/1.2.0-preview3) that implements quote escaping. You can use single or double quotes to escape your secret value, as below:

`RunAs=App;AppId=<AppId>;AppKey="secret=with;specialchars";TenantId=<TenantId>`

Please try this out and let us know if you have any issues or feedback!
