### ISSUE TITLE
.Net SDK Samples for Querying Azure RGs Which are not in use

### ISSUE THREAD

**Issue by mvvsubbu** [Azure/azure-sdk-for-net#4915]
How can I query azure resource groups which are not in use for last 24 hours using .net SDK?

**Comment by shahabhijeet** [comment]
@mvvsubbu how would you defined "not in use"?
Does that mean the resources deployed in the RG are not in use? If yes how would you classify the state of your RG if a VM has been in a shutdown state in a RG for last 7 days?

**Comment by pakrym** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
