### ISSUE TITLE
Get access token using Microsoft.Azure.Services.AppAuthentication in a container

### ISSUE THREAD

**Issue by Zenuka** [Azure/azure-sdk-for-net#4933]
I've got a docker container using the `AzureServiceTokenProvider` to get an access token to access key vault but it's not working. I'm getting the following exception message:
```
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/{GUID}. Exception Message: Tried the following 3 methods to get an access token, but none of them worked.
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/{GUID}. Exception Message: Tried to get token using Managed Service Identity. Unable to connect to the Managed Service Identity (MSI) endpoint. Please check that you are running on an Azure resource that has MSI setup.
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/{GUID}. Exception Message: Tried to get token using Visual Studio. Access token could not be acquired. Environment variable LOCALAPPDATA not set.
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/{GUID}. Exception Message: Tried to get token using Azure CLI. Access token could not be acquired. 
```
I'm not sure if the nuget package should be working inside a docker container I start up using Visual Studio (docker-compose).

**Comment by Zenuka** [comment]
Anyone have an idea if this should be working or if this is not supported currently?

**Comment by kdcllc** [comment]
@Zenuka please give a test drive for this cli tool https://www.nuget.org/packages/appauthnetication/#

**Comment by varunsh-msft** [comment]
To use the app auth library in a container on local machine, you will need to set env variables to use an explicit service principal credential. https://docs.microsoft.com/en-us/azure/key-vault/service-to-service-authentication#running-the-application-using-a-service-principal
