### ISSUE TITLE
How to authenticate via MSI locally

### ISSUE THREAD

**Issue by LockTar** [Azure/azure-sdk-for-net#4968]
I want to login with MSI when I develop locally.
The [documentation](https://docs.microsoft.com/en-us/dotnet/azure/dotnet-sdk-azure-authenticate?view=azure-dotnet#mgmt-auth) isn't update because I see nothing about the method: 
```C#
SdkContext.AzureCredentialsFactory.FromMSI(new MSILoginInformation(MSIResourceType.AppService), AzureEnvironment.AzureGlobalCloud)
```

How can I develop locally with MSI so it will use the user selected from the Visual Studio 2017 (latest version) option "Azure Service Authentication".

You can use this in example for getting values out of a keyvault via a `KeyVaultClient`.
```C#
var azureServiceTokenProvider = new AzureServiceTokenProvider();
var keyVaultClient = new KeyVaultClient(new KeyVaultClient.AuthenticationCallback(azureServiceTokenProvider.KeyVaultTokenCallback));
```
You could also generate accesstokens in this way:
```C#
var azureServiceTokenProvider = new AzureServiceTokenProvider();
string token await azureServiceTokenProvider.GetAccessTokenAsync(RESOURCE HERE, TENANTID HERE);
```
After that, you could use the token to call a rest api. But I don't want that, I want to use this library with MSI.

Thanks

**Comment by MaxWilson** [comment]
MSIs aren't supported locally, but there's something just as good: AzureServiceTokenProvider from the Microsoft.Azure.Services.AppAuthentication Nuget package will auto-detect if MSIs are available (if you're running in the cloud) and will log in as the MSI if it's available, and it will log in using your personal credentials otherwise (i.e. if you're running on your dev machine)--as long as both the MSI and your personal identity have access to the Azure resource that should cover most scenarios. See https://docs.microsoft.com/en-us/azure/app-service/app-service-managed-service-identity?context=azure/active-directory/context/msi-context#asal for details.

The exception is if you're developing a service on ServiceFabric because that it will be running under Network Service account, not your personal credentials, so it won't be possible to grant permissions to your Network Service account. I don't know a good solution for that scenario currently.

**Comment by LockTar** [comment]
Hi @MaxWilson,

This:

> MSIs aren't supported locally. In the cloud, AzureServiceTokenProvider will find the MSI endpoint at a non-routable address (http://169.254.169.254/metadata/identity/oauth2/token) and so will use it; on a dev box, AzureTokenProvider won't find any such endpoint and will attempt to use 'az login' if available before falling back to your domain identity.

is exactly the behavior that I want. The first part (MSI) works with this package in Azure. But when I develop locally from Visual Studio I can't get the fallback to the `domain identity`. 
I think you mean with the domain idenity the identity selected in the settings right?
![image](https://user-images.githubusercontent.com/1568453/47813553-be500100-dd4b-11e8-8e30-55199de31a0f.png)

I have this working with the library "Microsoft.Azure.Services.AppAuthentication" via:
```C#
var azureServiceTokenProvider = new AzureServiceTokenProvider();
string token await azureServiceTokenProvider.GetAccessTokenAsync(RESOURCE HERE, TENANTID HERE);
```

but not with this fluent library. I have to login with a app registration for local development and can use MSI in the cloud to bypass the problem:
```C#
private static IAzure GetAzureConnection()
{
    AzureCredentials credentials;
    string localDevelopment = Environment.GetEnvironmentVariable("LocalDevelopment", EnvironmentVariableTarget.Process);

    if (!string.IsNullOrEmpty(localDevelopment) &&
        string.Equals(localDevelopment, "true", StringComparison.InvariantCultureIgnoreCase))
    {
        _log.LogDebug($"Get the local service principal for local login");                
        var localDevSp = new Principal
        {
            UserPrincipalName = "LocalLogin",
            AppId = Environment.GetEnvironmentVariable("ClientId", EnvironmentVariableTarget.Process),
            TenantId = Environment.GetEnvironmentVariable("TenantId", EnvironmentVariableTarget.Process)
        };
        string clientSecret = Environment.GetEnvironmentVariable("ClientSecret", EnvironmentVariableTarget.Process);

        _log.LogDebug($"Get the local sp credentials");
        credentials = SdkContext
            .AzureCredentialsFactory
            .FromServicePrincipal(localDevSp.AppId, clientSecret, localDevSp.TenantId, AzureEnvironment.AzureGlobalCloud);
    }
    else
    {
        _log.LogDebug($"Get the MSI credentials");
        credentials = SdkContext
                .AzureCredentialsFactory
                .FromMSI(new MSILoginInformation(MSIResourceType.AppService), AzureEnvironment.AzureGlobalCloud);
    }
            
    _log.LogDebug($"Construct the Azure object");
    var azure = Azure
        .Configure()
        .WithLogLevel(HttpLoggingDelegatingHandler.Level.Basic)
        .Authenticate(credentials)
        .WithDefaultSubscription();

    return azure;
}
```

**Comment by MaxWilson** [comment]
[Disclaimer for clarity's sake: I'm a consumer of MSIs and AppAuthentication, not a representative of the respective dev teams.]

I do NOT mean the Azure Service Authentication dropdown--I mean the actual domain account your user identity is running under. If I'm logged into my computer as maxw@microsoft.com, but I set the VS dropdown to wilson.max@gmail.com, AFAICT AppAuthentication ignores the VS dropdown (and any identity from az login) completely and just authenticates as maxw@microsoft.com. I think this may be a bug and I filed an issue here: https://github.com/Azure/azure-libraries-for-net/issues/510

Error messages I've seen from AppAuthentication lead me to believe it tries four strategies before giving up: (1) Check for MSI endpoint; (2) Check for VS login identity, (3) Check for az login identity; (4) Check for domain identity. So a possible workaround for your issue might be to use "az login".

In any case, I think the real ask here is not to support MSIs locally but for AppAuthentication to work correctly. Would you agree?

**Comment by LockTar** [comment]
> But it looks to me as if the core ASK here is a way to get AzureCredentials locally without an explicit login step
I agree.

> I mean the actual domain account your user identity is running under. I think this may be a bug and I filed an issue here: Azure/azure-libraries-for-net#510
Hmmm I need to test this. If this is the case, than I agree with you that it is a bug...

**Comment by LockTar** [comment]
Is there someone of the team that has a good suggestion (to test)?

**Comment by shahabhijeet** [comment]
@LockTar it seems you are trying to get a solution for this in your fluent code, if so please open a bug in the correct repository
https://github.com/azure/azure-libraries-for-net/issues

But just for my sake of clarity, can your ask be summed up as below as mentioned by @MaxWilson 
> But it looks to me as if the core ASK here is a way to get AzureCredentials locally without an explicit login step, even if it's via AppAuthentication instead of MSI. Would you agree with that characterization?

If yes, could you clarify if your apps intention is to get authenticated against MSI (when deployed, is that using "user assigned identity" or "Service assigned identity") but during development phase you want to get authenticated using "user assigned identity" or your cached in user logged identity?

**Comment by LockTar** [comment]
Created a new issue in the other repo. Strange that I created a ticket here....
BTW, I don't really understand what you mean with:

> during development phase you want to get authenticated using "user assigned identity" or your cached in user logged identity?

In Azure, I'm using a  "Service assigned identity". Maybe we need to continue in the other #585 issue and close this one.

**Comment by shahabhijeet** [comment]
Closing
