### ISSUE TITLE
Question/Suggestion for Windows/VS providers

### ISSUE THREAD

**Issue by BryanLa** [Azure/azure-sdk-for-net#4987]
1. The `WindowsAuthenticationAzureServiceTokenProvider` type uses a hard-coded app/client ID of `d7813711-9094-4ad3-a062-cac3ec74ebe8`. Is this a multi-tenant app registration for Windows clients?

2. For the `VisualStudioAccessTokenProvider` type, could we get the last sentence of the following exception changed in Microsoft.Asal.Token.Service.exe ?

   "Exception for Visual Studio token provider Microsoft.Asal.TokenService.exe : TS003: Error, TS005: No accounts found.  Please go to Tools->Azure Services Authentication, and add an account to be to authenticate to Azure services during development."

   **SUGGESTION**: "Please ensure you are signed-in to a valid account in Visual Studio, and a valid account is selected in Tools->Options->Azure Service Authentication."

3. For the `VisualStudioAccessTokenProvider` type, could we get the last sentence of the following exception changed in Microsoft.Asal.Token.Service.exe ?

   "Exception Message: Tried to get token using Visual Studio. Access token could not be acquired.
Exception for Visual Studio token provider Microsoft.Asal.TokenService.exe : TS003: Error, TS001: This account 'name@domain.com' needs re-authentication. Please go to Tools->Azure Services Authentication, and re-authenticate the account you want to use."

   **SUGGESTION**: "Please go to Tools->Options->Azure Service Authentication, and re-authenticate the account you want to use."

**Comment by BryanLa** [comment]
Label: AppAuthentication

**Comment by varunsh-msft** [comment]
Extremely sorry for the delay in responding. For the first question, yes, it is a multi-tenant app registration. For the other two, I will discuss that with the VS team and get back.

**Comment by BryanLa** [comment]
Thanks @varunsh-msft !

**Comment by varunsh-msft** [comment]
The error messages should get updated in a future version of Visual Studio. This is being tracked by the Visual Studio team internally.
