### ISSUE TITLE
Allow AppAuthentication to use all accounts connected to Visual Studio

### ISSUE THREAD

**Issue by paulhickman-a365** [Azure/azure-sdk-for-net#4992]
I have three accounts added to my profile in Visual Studio, and cloud explorer allows me to use all three when connecting to Azure Resources. However, Microsoft.Azure.Services.AppAuthentication only uses the one shown as the "Personalization Account" in the account settings page.

There should either be a means to indicate which account is the active one for App Authentication within visual studio, either globally or better still, in solution options for a particular solution. Alternatively, the library should try all accounts that are listed under the profile rather than just the Personalization Account..

**Comment by LukeKolodziej** [comment]
Paul,
You can set the account globally within Visual Studio: Tools -> Options -> Azure Service Authentication -> Account Selection

**Comment by paulhickman-a365** [comment]
Thanks, that helps a lot. 

It would still be useful to be able to set it per-solution though.

**Comment by varunsh-msft** [comment]
Discussed with Visual Studio team and there are no plans at the moment to try all accounts as the account needs to be global since it is accessed from a separate process and it does not know what solution is current.
