### ISSUE TITLE
How to set StoredProcedureParameter value to be as treated as Null using C#

### ISSUE THREAD

**Issue by iamnarendhar** [Azure/azure-sdk-for-net#5004]
There is an option "Treat as Null" for StoredProcedureParameter in ADF
How do we set it using C# ?

![image](https://user-images.githubusercontent.com/24953203/48197063-7b5ce180-e37a-11e8-8787-ca95e220b6f2.png)

Even If we send the value as null to the StoredProcedureParameter constructor, it is taking as empty string in the deployed pipeline

[https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.datafactory.models.storedprocedureparameter?view=azure-dotnet#constructors](url)

**Comment by lmy269** [comment]
@iamnarednhar, can you share your code? Does **new StoredProcedureParameter(null, "String")** not work for you?

**Comment by brobinson88** [comment]
I've found the same problem setting the value to None in the python SDK. I've tried StoredProcedureParammeter(None, 'String') and it doesn't set the treat as null checkbox. Is there an update on this issue??

**Comment by lmy269** [comment]
@shawnxzq , can you take a look?

**Comment by shawnxzq** [comment]
This is a known issue, we already have work item to track this.

**Comment by jsquire** [comment]
@shawnxzq: Would you please be so kind as to link the existing work item and close this out as a duplicate?
