### ISSUE TITLE
Azure Search SDK: Cannot select search text against columns

### ISSUE THREAD

**Issue by bunceg** [Azure/azure-sdk-for-net#5019]
The Lucene query syntax allows something like this:

`search=contributors:jk rowling AND title:potter&$select=title,contributors&searchmode=all&querytype=full&api-version=2017-11-11`

i.e. I only want to search for terms that match "jk", "rowling" in the contributors column and "potter" in the title column.

The SDK does not enable this; it only allows us to select the search fields (Title, contributors) and the search terms (jk, rowling, potter). It then returns results that include potter in the contributors field and rowling in the title field. It does not allow us to scope certain search terms to specific columns.

This is obviously insufficient for fine-grained searching.

The SDK needs to fully support the Lucene syntax for restricting columns

**Comment by brjohnstmsft** [comment]
@bunceg While the SDK doesn't provide any kind of functionality for building full Lucene queries, you can pass such queries as a string to the SDK. Just make sure to set `QueryType` to `Full`:

```csharp
var params = new SearchParameters()
{
    QueryType = QueryType.Full,
    Select = new[] { "title", "contributor" },
    SearchMode = SearchMode.All
};

string searchText = "contributors:(jk rowling) AND title:potter";
var result = client.Documents.Search(searchText, params);
```

Note the parentheses around "jk rowling", which ensures that the term "rowling" is also scoped to the "contributors" field.

**Comment by bunceg** [comment]
@brjohnstmsft Two things:

1) Thanks for replying so quickly
2) This "feature" isn't explained anywhere that I can see (and I've asked before in various Microsoft blogs about this). If it isn't explained, it really should be as it's not obvious that you can do this

**Comment by brjohnstmsft** [comment]
@bunceg Thanks for the feedback. I agree that this should be more easily discoverable. I can think of two changes we could make to improve this; Please let me know if these would have helped you find this, or if there's something else we can do:

  1. Add an example to [this article](https://docs.microsoft.com/azure/search/search-query-lucene-examples) showing how to pass a Lucene query to the `Search` method of the .NET SDK.
  1. Add a reference to the [aforementioned article](https://docs.microsoft.com/azure/search/search-query-lucene-examples) to the [reference page for the Search method in the SDK](https://docs.microsoft.com/dotnet/api/microsoft.azure.search.documentsoperationsextensions.search?view=azure-dotnet#Microsoft_Azure_Search_DocumentsOperationsExtensions_Search_Microsoft_Azure_Search_IDocumentsOperations_System_String_Microsoft_Azure_Search_Models_SearchParameters_Microsoft_Azure_Search_Models_SearchRequestOptions_) (and its relevant overloads).

**Comment by brjohnstmsft** [comment]
@bunceg These are great suggestions, thanks! I'll make sure our documentation is updated as you've recommended.
