### ISSUE TITLE
Batch Management SDK should support authentication like Batch SDK

### ISSUE THREAD

**Issue by chrisalexander** [Azure/azure-sdk-for-net#5022]
The batch SDK supports an authentication callback:

    var client = await BatchClient.OpenAsync(new BatchTokenCredentials(batchUri, authCallback));

However the batch management SDK only supports an ITokenProvider or a token:

    var batchManagementClient = new BatchManagementClient(new TokenCredentials(accessToken))

This means if you have a batchManagementClient that lasts > 1 hr (the default token expiry), subsequent API calls fail because the token has expired.

Our workaround is to re-create the client periodically but ideally it would support refreshable authentication using the same signature as the main batch client.

**Comment by shahabhijeet** [comment]
@chrisalexander did you explicitly set Null for token cache when trying to get AuthContext, because ADAL offers a default token cache out of the box that will allow you not to worry about expiring tokens.

**Comment by chrisalexander** [comment]
I don't think so, what do you mean by this?

**Comment by jsquire** [comment]
Closing this out as there has been no recent engagement.  Please feel free to reopen or file a new issue if this remains a problem with the current version of the library.
