### ISSUE TITLE
CloudEvent schema only accepts JObject; nuget uses JArray

### ISSUE THREAD

**Issue by mmulhearn** [Azure/azure-sdk-for-net#5025]
This stackoverflow topic is still relevant [https://stackoverflow.com/questions/52233053/posting-custom-message-to-event-grid-via-logicapps](https://stackoverflow.com/questions/52233053/posting-custom-message-to-event-grid-via-logicapps)

If you are using the CloudEvent schema, you get a JSON error about sending an array.  The nuget does not handle that schema.  It should.  It does not allow you to send a single object; it only allows an IList.

**Comment by shahabhijeet** [comment]
@mmulhearn can you be more specific and provide more information.
A way to reproduce the behaviour.
Nuget Package name/version.

**Comment by pakrym** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
