### ISSUE TITLE
Misleading output for AAD app ARM authentication

### ISSUE THREAD

**Issue by davidobrien1985** [Azure/azure-sdk-for-net#5026]
Hello,

I just had to troubleshoot a customer's C# app that authenticates to ARM via a service principal (AAD app).
Problem was the log output from the SDK is not very helpful:

```
The client 'fdc050fd-5ca7-42b0-bccf-6b6df0b455db' with object id 'fdc050fd-5ca7-42b0-bccf-6b6df0b455db' does not have authorization to perform action 'Microsoft.KeyVault/vaults/read' over scope '/subscriptions/<subscriptionId>/resourceGroups/rg/providers/Microsoft.KeyVault/vaults/kv-aus'
```

It turns out that the application in question was the AAD app with ApplicationId as can be seen in this attachment.
![2018-11-16_15-14-21](https://user-images.githubusercontent.com/8554521/48597551-76b7af00-e9b2-11e8-87ee-fed2f273cdd8.png)

The log output made me assume that `the client` was the `ApplicationId` and `object id` was the `objectId`, but in the AAD app portal there is no way to search by objectId neither is the objectId visible in the portal.

Am I just looking at the wrong thing or is this log output from the SDK not very helpful?

**Comment by shahabhijeet** [comment]
@davidobrien1985 can you please descibe what you are trying to do and what SDKs and their respective versions you are using.
The provided information is not sufficient to reproduce the issue.

**Comment by pakrym** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
