### ISSUE TITLE
Cannot provision AppInsights using API 2015-05-01

### ISSUE THREAD

**Issue by padillah** [Azure/azure-sdk-for-net#5034]
I am trying to provision an Application Insights resource but if I use the 2015-05-01 api the instance I end up with always reports "Error reading data" in the Search pane.
{
"$schema" : "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
"contentVersion" : "1.0.0.0",
"parameters" : {
"appInsights-name" : {
"type" : "String"
}
},
"resources" : [
{
"name" : "[parameters('appInsights-name')]",
"type" : "microsoft.insights/components",
"apiVersion" : "2015-05-01",
"location" : "[resourceGroup().location]",
"kind" : "other",
"properties" : {
"Application_Type": "other",
"Flow_Type": "Bluefield",
"Request_Source": "rest"
},
"dependsOn" : []
}
]
}

But, if I use the template from 2014-04-01 I get a usable AppInsights instance.
{
"$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
"contentVersion": "1.0.0.0",
"parameters": {
"appInsights-name": {
"type": "String"
}
},
"resources": [
{
"type": "microsoft.insights/components",
"kind": "other",
"name": "[parameters('appInsights-name')]",
"apiVersion": "2014-04-01",
"location": "[resourceGroup().location]",
"properties": {
"ApplicationId": "[parameters('appInsights-name')]"
}
}
]
}

Does the 2015 api work? What am I doing wrong?

**Comment by morgangrobin** [comment]
I believe this was fixed in https://github.com/Azure/azure-rest-api-specs/pull/5505
