### ISSUE TITLE
LuisRuntimeAPI is not accesible

### ISSUE THREAD

**Issue by mirsaeedi** [Azure/azure-sdk-for-net#5036]
I've downloaded the latest version of[ Luis.Runtime v2](https://www.nuget.org/packages/Microsoft.Azure.CognitiveServices.Language.LUIS.Runtime/2.0.0) into my UWP project targeting Windows 10 v1809. But I cannot instantiate the _LuisRuntimeAPI_  class because compiler complains that the class does not exist. 
Could you please help me with that?

![image](https://user-images.githubusercontent.com/2342405/48745009-b17e4900-ec37-11e8-9ec3-e08981ddb111.png)

**Comment by mirsaeedi** [comment]
I found that I should use LUISRuntimeClient instead.

This sample should get updated although. 

https://github.com/Azure-Samples/Cognitive-Services-LUIS-Console-Application

**Comment by jsquire** [comment]
Closing this out as there has been no recent engagement.  Please feel free to reopen or file a new issue if this remains a problem with the current version of the library.
