### ISSUE TITLE
The format of value xxx is invalid

### ISSUE THREAD

**Issue by amir734jj** [Azure/azure-sdk-for-net#5046]
I get the following exception when I run the code (I use Mac):
> The format of value 'Darwin17.7.0DarwinKernelVersion17.7.0WedOct10230614PDT2018rootxnu-4570.71.131/RELEASE_X86_64' is invalid.

Code that throws an exception
```
var serviceClientCredentials = new AzureApiKeyServiceClientCredentials("<key>");
// Throw an exception here
var client = new TextAnalyticsClient(_serviceClientCredentials);
```
```
ServiceClientCredentials class:
 
    public class AzureApiKeyServiceClientCredentials : ServiceClientCredentials
    {
        private readonly string _subscriptionKey;

        public AzureApiKeyServiceClientCredentials(string subscriptionKey)
        {
            _subscriptionKey = subscriptionKey;
        }
        
        public override Task ProcessHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            request.Headers.Add("Ocp-Apim-Subscription-Key", _subscriptionKey);
            
            return base.ProcessHttpRequestAsync(request, cancellationToken);
        }
    }
```

**Update 1**
I think `TextAnalyticsClient` tries to set a header key/value and header value is not valid. 

**Update 2**
I see the source of the problem. Its setting OsVersion on header of `HttpClient` and it's not url friendly or something and `HttpClient` is throwing an exception:

```
 this.UpdateDefaultUserAgentList("OSVersion", this.OsVersion);
```
So all you need to do it to fix it is to always call `CleanUserAgentInfoEntry(_osVersion)`.

**Comment by shahabhijeet** [comment]
@amir734jj @bastisk can you tell me what version of ClientRuntime are you using in your app?
If you upgrade your app to the latest ClientRuntime, you should not see this issue.
https://www.nuget.org/packages/Microsoft.Rest.ClientRuntime/2.3.18

**Comment by amir734jj** [comment]
@shahabhijeet Thanks for the help. I just installed the latest version of `Microsoft.Rest.ClientRuntime` and it solved the problem.

**Comment by shahabhijeet** [comment]
@amir734jj closing the issue as well as the PR.

**Comment by hanssens** [comment]
I had the same on macOS with the Microsoft.Azure.EventGrid SDK ([v3.0.0](https://www.nuget.org/packages/Microsoft.Azure.EventGrid/3.0.0)). It crashed on initialising the client:

```
var client = new EventGridClient(topicCredentials);
```

Adding the latest Microsoft.Rest.ClientRuntime (v2.3.19) fixed it as well for me. Perhaps it's useful info for others in the future.

**Comment by santifdezmunoz** [comment]
I got the same issue working with Microsoft.Azure.Batch on MacOS Mojave and crashed on the same scenario:

BatchClient batchClient = BatchClient.Open(batchCredentials)

Adding latest Microsoft.Rest.ClientRuntime also fixed the issue for me.
