### ISSUE TITLE
Constant for Ocp-Apim-Subscription-Key

### ISSUE THREAD

**Issue by vanillajonathan** [Azure/azure-sdk-for-net#5052]
For the `Microsoft.Azure.Management.ApiManagement` namespace.

Consider adding a constant for `Ocp-Apim-Subscription-Key`.

Or an `AddOcpApimSubscriptionKey` extension method.

**Comment by solankisamir** [comment]
This is the `management` API nuget and not the `runtime` (Gateway/Proxy) API nuget. The header `Ocp-Apim-Subscription-Key` does not make any sense in `Management` nuget.

We don't have any nuget for `runtime` (Gateway/Proxy).

**Comment by vanillajonathan** [comment]
Fair enough.
