### ISSUE TITLE
Azure Search SDK: Missing CosmosDb data source creation methods

### ISSUE THREAD

**Issue by mgottein** [Azure/azure-sdk-for-net#5060]
See https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SDKs/Search/DataPlane/Microsoft.Azure.Search.Service/Customizations/DataSources/Models/DataSource.Customization.cs

We are missing a  cosmos db method to match document db

**Comment by arv100kri** [comment]
Being addressed in the preview SDK PR #5223

**Comment by brjohnstmsft** [comment]
This has been fixed in the new [Azure Search preview SDK](https://www.nuget.org/packages/Microsoft.Azure.Search/8.0.0-preview). A stable release that includes this fix will be available within a week.
