### ISSUE TITLE
Azure Batch Operations hang when invalid credentials provided

### ISSUE THREAD

**Issue by pielegacy** [Azure/azure-sdk-for-net#5067]
Trying to validate Azure Batch SDK credentials in an application and the way I'm doing this is by creating a Client and then trying to list entities like Pools, for example:

```cs
public override async Task TestConnectionAsync()
{
    using (var client = BatchClient.Open(Credentials))
    {
        await client.PoolOperations.ListPools().ToListAsync();
    }
}
```

This method works fine when the provided credentials are valid, however testing for invalid credentials results in the method never completing its executions or throwing an exception.

**Comment by paterasMSFT** [comment]
Thank you for reporting this. Seems like this was fixed along the way, as I can't reproduce. It can take a minute or two for the exception to be thrown, but it is throwing. Feel free to re-open with additional info if you can still reproduce.
