### ISSUE TITLE
DataManagement.DataFactory packages not in Sync with the latest feature releases

### ISSUE THREAD

**Issue by mrsanjaysharma2** [Azure/azure-sdk-for-net#5109]
We have been using the latest version of the package (Microsoft.Azure.Management.DataFactory v2.3.1) for one of our application responsible for authoring and monitoring Azure Data Factory pipelines. 
But now we wanted to use the AzureFunction Activity and sadly the activity and linked service components for azure functions are not present because the packages have not been updated or other reasons.

Last release was around Oct 2018, this could be a blocker for us as we will not be able to use the latest features into our application. can somebody from the ADF team please help?

**Comment by jsquire** [comment]
Closing this out as there has been no recent engagement.  Please feel free to reopen or file a new issue if this remains a problem with the current version of the library.
