### ISSUE TITLE
AI Component List GET returns invalid response for subscription with no AI instance

### ISSUE THREAD

**Issue by VaclavK** [Azure/azure-sdk-for-net#5123]
Hi,

using https://www.nuget.org/packages/Microsoft.Azure.Management.ApplicationInsights/0.2.0-preview we ran into the issue of listing (GET https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.Insights/components?api-version=2015-05-01) when subscription does not contain any AI instance

according to doco , this should return https://docs.microsoft.com/en-us/rest/api/application-insights/components/list#applicationinsightscomponentlistresult but actually returns [] - 

the nuget client ApplicationInsightsManagementClient  tries to deserialize and throws an exception

according to doco, one would expect the response to be an instance of the type with empty array and no next link

**Comment by jsquire** [comment]
Closing this out, as there has been no recent engagement.  Please feel free to reopen or file a new issue if this behavior is still occurring.
