### ISSUE TITLE
Getting authentication issue while calling azure api for resource utilization

### ISSUE THREAD

**Issue by Basantit** [Azure/azure-sdk-for-net#5124]
Hi,
I am trying to call Azure API for resource utilization of Virtual machine but getting 401 authentication error.
I am successfully generating an access token but while calling metric definitions API using the token, I am getting 401 error.
I am following this http://devchat.live/en/2017/02/27/access-metrics-using-azure-monitor-rest-api/
URL for my code (using C#).

Please find below screenshots.

![token](https://user-images.githubusercontent.com/16048013/50896443-04ea6780-142f-11e9-91e6-ebb25cbf8812.PNG)
![azure](https://user-images.githubusercontent.com/16048013/50896444-04ea6780-142f-11e9-8424-d303ea3b9fed.PNG)

**Comment by shahabhijeet** [comment]
@Basantit can you describe what you are trying to do? The code you have pasted is fine, but what really helps is describing the SDKs it's version you are tyring to do use and describing a scenairo, once you provide that information, then we can request for code if things are still not clar.

**Comment by pakrym** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
