### ISSUE TITLE
Resources.CheckExistenceByIdAsync() issue

### ISSUE THREAD

**Issue by rajbos** [Azure/azure-sdk-for-net#5132]
I noticed 'Bad request' errors while calling `Resources.CheckExistenceByIdAsync(resourceId, apiVersion)`. 

Digging through the actual request using Postman I see it does a HEAD request to `https://management.azure.com//subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Storage/storageAccounts/{resourceName}?api-version=2018-07-01` and that returns after >40 seconds with '503 - service unavailable'.

**Comment by shahabhijeet** [comment]
Please provide more information on the SDK that you are using and the version of the SDK that gives you this error.

**Comment by blueww** [comment]
@rajbos 
SDK just report the error we get from server. From the scenarios of you, it look more like a temperate server throttling than SDK issue. 

Does the error happen repeatedly even after several hours/days?
If so, could you share the whole responds which include request ID and time, they are very important for investigation. (hide any credential)

**Comment by rajbos** [comment]
I am using version `1.18.0` of the `Microsoft.Azure.Management.Fluent` NuGet package.

**Comment by rajbos** [comment]
During testing today, I get a 404 result for a resource ID that doesn't exist and a `400 Bad Request` for a valid resource id!

Response for the latter:
```
HTTP/1.1 400 Bad Request
Cache-Control: no-cache
Pragma: no-cache
Content-Length: 712
Content-Type: application/json; charset=utf-8
Expires: -1
x-ms-failure-cause: gateway
x-ms-request-id: a39e399d-0385-48bb-b48d-9f1b61adebcf
x-ms-correlation-request-id: a39e399d-0385-48bb-b48d-9f1b61adebcf
x-ms-routing-request-id: CANADACENTRAL:20190211T095734Z:a39e399d-0385-48bb-b48d-9f1b61adebcf
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
Date: Mon, 11 Feb 2019 09:57:33 GMT
```

**Comment by blueww** [comment]
@shahabhijeet 
The code for this API is not in storage SDK, but in resource SDK, would you please ask the resource SDK owner for help?
https://github.com/Azure/azure-sdk-for-net/blob/40248f466aa063bd90f16dae10d06b9b7317e2d0/src/SDKs/Resource/Management.ResourceManager/Generated/ResourcesOperationsExtensions.cs

**Comment by TheMonnster** [comment]
Any updates on this issue? I am also facing this. For me a resource that does not exist is properly resolving as false, but for resources that are in place I consistently get 400 Bad Request as well. :(

**Comment by yungezz** [comment]
hi @xccc-msft could you pls help to have a look? thanks

**Comment by xccc-msft** [comment]
This is the same issue as [Azure/azure-sdk-for-java#8860](https://github.com/Azure/azure-sdk-for-java/issues/8860) reported.
It's a known issue found in [Azure/azure-rest-api-specs#2856](https://github.com/Azure/azure-rest-api-specs/issues/2856).
Pending discussion post by [Azure/azure-rest-api-specs#8092](https://github.com/Azure/azure-rest-api-specs/issues/8092).

It's a service issue rather than SDK issue. Add `Service Attention` so ARM team would help look into it.

**Comment by DeepakMohanSingh** [comment]
Hi. I still face the same issue. Any update on this? 

Thanks.

**Comment by weidongxu-microsoft** [comment]
@DeepakMohanSingh 
Many service does not support this `HEAD` http method. Hence it fails. It would require fix from service.

**Comment by abatishchev** [comment]
@ifeoluwaokunoren for the question about supporting `HEAD`.

**Comment by snaheth** [comment]
Most Resource Providers (RPs) do not support the HEAD response when it is sent to ARM. As of the date this comment was published, only 4 RPs support this operation, which means it's not suitable to viably assess whether a resource exists.

At a 1:1 comparison of something that effectively works across all Resource Providers, you're better off using the [GET /resource operation](https://docs.microsoft.com/en-us/rest/api/resources/resources/get) where a successful response (200) confirms a resource exists.

If you're looking to do this at scale, across your multiple subscriptions, management groups, or tenant - you should use [Azure Resource Graph](https://docs.microsoft.com/en-us/azure/governance/resource-graph/concepts/explore-resources).

You may also use the [GET /resources operation](https://docs.microsoft.com/en-us/rest/api/resources/resources/list) to retrieve all the resource in your subscription.

**Comment by abatishchev** [comment]
+ @ifeoluwaokunoren 

Hi @snaheth,
I don't think the fact that out of a hundred or two RPs only 4 support HEAD is a good argument not to support it. More practically speaking - make them to support it.

Also your words directly contradict the public documentation at https://docs.microsoft.com/en-us/rest/api/resources/resources/check-existence

However, it's not you. It's the documentation that must be fixed asap.
