### ISSUE TITLE
Sync AZConfig changes into main repo

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk-for-net#5135]

**Comment by Petermarcu** [comment]
Didn't this happen already? I think this being done should close out the epic for shipping the AZConfig Preview.

**Comment by AlexGhiondea** [comment]
Yes. We can close this.

**Comment by bsiegel** [comment]
This task was started a while back to migrate the service team's code into our repo. Since then we decided to instead integrate our own track 2 libraries instead of the service team's, so this can be closed.
