### ISSUE TITLE
Cosmos DB RequestOptions PartitionKey will not serialize with JsonConvert, Always NULL

### ISSUE THREAD

**Issue by laultman** [Azure/azure-sdk-for-net#5138]
Trying to serialize RequestOptions to send to Azure Functions but the JsonConvert.SerializeObject always produces a null on the PartitionKey object. That seems to be a bug. RequestOptions is sealed so my only work around is to manually construct my own class. That seems extreme when it is needed for just about everything in Cosmos. The only way to pass parameters to Azure Functions is by serialization.

`		public static void Main(string[] args)
		{
			var partitionKeyValue = "39393939";	// Some partition key in Cosmos DB collection
			var requestOptions = new RequestOptions
			{
				PartitionKey = new PartitionKey(partitionKeyValue)
			};

			var data = JsonConvert.SerializeObject(requestOptions);

			// send data to Azure Functions
			var requestOptions1 = JsonConvert.DeserializeObject<RequestOptions>(data);
		}
`

**Comment by j82w** [comment]
@laultman try using the new [v3 sdk](https://github.com/Azure/azure-cosmos-dotnet-v3).

**Comment by kirankumarkolli** [comment]
Resolving the incident with V3 SDk as work-around.
