### ISSUE TITLE
ComputerVision SDK not support Cognitive Service that hosted on Mooncake

### ISSUE THREAD

**Issue by micli** [Azure/azure-sdk-for-net#5148]

**Comment by micli** [comment]
Recently I found that Microsoft.Azure.CognitiveServices.Vision.ComputerVison that can be downloaded from nuget cannot access computer vision service that hosted on mooncake. I investigated root cause is that version number v2.0 has been hard code in [ComputerVisionClient.cs](https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SDKs/CognitiveServices/dataPlane/Vision/ComputerVision/ComputerVision/Generated/ComputerVisionClient.cs#L189) file.

It looks weird that Chinese customers cannot easily access cognitive service. It just because mooncake has a gap with global azure. This is not like abandon the v1.0 service, but more like abandon customers in China.

**Comment by navba-MSFT** [comment]
@ryogok, @TFR258, @tburns10 Could you please look into this issue ?

**Comment by JimSuplizio** [comment]
Hi @micli, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
