### ISSUE TITLE
Add support for  ADAL.NET 4.x

### ISSUE THREAD

**Issue by qub1n** [Azure/azure-sdk-for-net#5163]
I would like to install and use ADAL.NET Version 4.4.0 in my project, because a login to Azure sometimes crashing and these bugs seems to be already resolved in Adal 4.x

 Install-Package Microsoft.IdentityModel.Clients.ActiveDirectory -Version 4.5.0

Install-Package : NU1608: Detected package version outside of dependency constraint: Microsoft.Rest.ClientRuntime.Azure.Authentication 2.3.6 requires Microsoft.IdentityModel.Clients.Ac
tiveDirectory (>= 3.14.0 && < 4.0.0) but version Microsoft.IdentityModel.Clients.ActiveDirectory 4.5.0 was resolved.

Please remove constrain < 4.0.0 and add support for  ADAL.NET 4.x

**Comment by shahabhijeet** [comment]
@qub1n I hear you and I understand the frustration.
But we have been hit hard in the past with breaking changes in ADAL.
But we are working towards a better solution and should be able to release a package that will honor latest version of ADAL when needed.
I am sorry we do not have a quick fix for now, but please let me know what is their in ADAL 4.x that you don't get in Adal 3.x

**Comment by qub1n** [comment]
Actually I have been struggling with some random and rare race conditions in Adal 3. The in which is Adal3 crashing file has been completely rewritten in Adal 4 so I hoped it could be fixed. Or I have a bug in my code, I just wanted tried the latest.

Furthermore Adal 3 TokenCache is binary and Adal 4 TokenCache also support JSON format.

https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Changes-adalnet-4.0

**Comment by jonmill** [comment]
@shahabhijeet - any updates on this? This is still causing issues

**Comment by vludax** [comment]
We'd also love to see the dependency version of `Microsoft.Rest.ClientRuntime.Azure.Authentication` updated updated.

**Comment by jonmill** [comment]
@varunsh-msft @shahabhijeet - this is becoming more and more of a problem...could you please provide an update on when we can expect this to be fixed?

**Comment by jonmill** [comment]
@maririos - if you know of anyone who could help get some traction here, that would be great :)

**Comment by shahabhijeet** [comment]
@qub1n @jonmill can you use the latest version of the auth library 2.3.8

**Comment by jonmill** [comment]
@shahabhijeet - does that mean that there's a different auth library for the management package than for the rest of the azure packages? Everything else seems to use `Microsoft.IdentityModel.Clients.ActiveDirectory` not `Microsoft.Rest.ClientRuntime.Azure.Authentication`. Just trying to understand since I have a different dependency on `Microsoft.IdentityModel.Clients.ActiveDirectory` due to KeyVault

**Comment by shahabhijeet** [comment]
2.3.8 is the new version of Azure.Authentication library.
This just allows you to get latest ADAL pacakges, we had a upper limit on our Auth library, but now it has been extended, so you can upgrade ADAL pacakges to 4.x

**Comment by jonmill** [comment]
Awesome, this looks to build for me without any warnings. Thank you for the update!
