### ISSUE TITLE
AzureServiceTokenProvider.GetAuthenticationResultAsync should accept a cancellation token

### ISSUE THREAD

**Issue by binderjoe** [Azure/azure-sdk-for-net#5172]
Per Azure Design guidelines, GetAuthenticationResultAsync() should accept and honor a cancellation token--both for API consistency and for better resiliency.

@varunsh-msft and @nonik0 should probably have a look.

**Comment by nonik0** [comment]
Hi @binderjoe, we've released support for cancellation tokens in [the latest preview release](https://www.nuget.org/packages/Microsoft.Azure.Services.AppAuthentication/1.2.0-preview3) we just released. Please try it out and let us know if you have any feedback.
