### ISSUE TITLE
Clean up permissions on net repos

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk-for-net#5178]
Once azure-sdk-admin, azure-sdk-write, azure-sdk-push, and azure-members teams have permissions lined up on this repo, we need to go through and remove all of the other teams.  This will need to be done with care to ensure there is no interruption in service for those working in the repos.

- [ ] azure-sdk-for-net
- [ ] azure-sdk-for-net-pr

**Comment by brjohnstmsft** [comment]
Hi @kurtzeborn -- We (Azure Search) have a team called NetSdkSearchMergeAdmins set up to allow us to merge our own PRs to the search-preview branch (long story), although that doesn't seem to be working anymore.

Can you provide more background on this change and what's motivating it?

FYI @shahabhijeet

**Comment by kurtzeborn** [comment]
@brjohnstmsft Access to the various azure-sdk repos has grown organically over time and we're trying to clean that up and standardize it across the repos.  In particular there has been a proliferation of folks with full "Admin" access to the repos that we want to rein in and in the process organize better the whole permission structure so that it's not only clear who has what access, but why they have that access.  

So far, all of the changes made as part of this effort have been additive.  No access has been removed yet.  So I'm not sure why it's not working anymore for you.  I see the NetSdkSearchMergeAdmins team in the list with "Write" access to the repo.  That will continue to be true as we make these changes (though the team name may change to conform with the final naming system).

**Comment by kurtzeborn** [comment]
@brjohnstmsft To further clarify... the azure-sdk-write team I mentioned in the issue will have write access to the repo and NetSdkSearchMergeAdmins (likely renamed to azure-sdk-write-search) will be parented to that team (and have the same access as a result).  This way it will be clear that the team contains members of the Azure Search team who have write access to the repo (answering the "who" and "why" questions I alluded to above).  This will also align us better to GitHub's guidance around [nested teams](https://help.github.com/articles/about-teams/#nested-teams).
