### ISSUE TITLE
FormatException when using AzureSearch 5.0.3 on MacOs Sierra

### ISSUE THREAD

**Issue by imjustjoekingex** [Azure/azure-sdk-for-net#5184]
On MacOS Sierra, the following exception is thrown while initializing Application Insights, the cause seems to be the inclusion of AzureSearch 5.0.3
![screen shot 2019-01-27 at 3 46 18 pm](https://user-images.githubusercontent.com/16024841/51882683-bc4b0d80-234d-11e9-96b1-08da39b1c0e3.png)

**Comment by knnithyanand** [comment]
I also face the same error below is my code to initialize `SearchServiceClient`

``` cs
var cred = new SearchCredentials(apiKey);
_client = new SearchServiceClient(serviceName, cred);
```

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/3396079/52728000-66cf5b80-2ff1-11e9-85fa-5699f9d808bb.png">

**Comment by brjohnstmsft** [comment]
@shahabhijeet Per the stack trace above, this looks like an issue in `ClientRuntime`, not `Microsoft.Azure.Search`. It looks like a bug in how `ServiceClient` is handling the user agent string. Can you please take a look?

**Comment by brjohnstmsft** [comment]
@imjustjoekingex @knnithyanand Are you able to repro this with Azure .NET libraries other than `Microsoft.Azure.Search`?

**Comment by imjustjoekingex** [comment]
not so far, its only this specific version too

**Comment by shahabhijeet** [comment]
@imjustjoekingex can you provide the Microsoft.Rest.ClientRuntime version that you are using.
And if you can upgrade to the latest version and then let me know if you still encounter the issue.

**Comment by brjohnstmsft** [comment]
@imjustjoekingex @knnithyanand A new [Azure Search preview SDK](https://www.nuget.org/packages/Microsoft.Azure.Search/8.0.0-preview) is now available on NuGet that uses the latest version of the ClientRuntime library. A stable release that includes this change will be available within a week.

I'm going to close this issue for now. If you get a chance to use this new version, please re-open this issue if it doesn't solve the problem.
