### ISSUE TITLE
Managed Identity: Configurable timeout based on time

### ISSUE THREAD

**Issue by ArLucaID** [Azure/azure-sdk-for-net#5191]
Currently, the retry logic in the Azure SDKs for Managed Identity token generation supports a configurable time out based on counts. For response time sensitive services this has not been enough. Per customer feedback, they would like to have timeout configuration based on time (i.e. milliseconds) 
This will allow for quicker fail after certain.
Can we make the retry max configurable based on time?

**Comment by arluca** [comment]
@binderjoe FYI

**Comment by shahabhijeet** [comment]
@arluca can you specify the SDK name/version that you are using.
Provide the nuget version link to avoid any confustion.
