### ISSUE TITLE
API Management Service : Import Service Fabric Cluster APIs

### ISSUE THREAD

**Issue by MilindThakkar** [Azure/azure-sdk-for-net#5201]
We have created two APIs and deployed them to Service Fabric Cluster which exposes it as https://[SomeClusterUrl]:8100 and https://[SomeClusterUrl]:8101

Now, we want to expose these APIs via API Management Service and we couldn't find any easier way. There is one article at https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-tutorial-deploy-api-management but it's really very vague to understand and relate it with this SDK

We managed to create API Management Service instance and also create blank API (or import throgh Swagger) using SDK. But don't know how to import Service Fabric API.

And also could create API Management BackEnd pointing to Service Fabric App, But then we couldn't find any way to bind this BackEnd to any API created in the API Management Service.

Any help, sample and/or pointing to right direction is greatly appreciated.

**Comment by solankisamir** [comment]
@MilindThakkar please refer to this [Create or update Service Fabric Backend](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/apimanagement/Microsoft.Azure.Management.ApiManagement/tests/ManagementApiTests/BackendTests.cs#L145)

**Comment by jsquire** [comment]
Closing this out, as there has been no recent engagement.  Please feel free to reopen if you feel that further discussion is needed.
