### ISSUE TITLE
Bing spell check not working in LUIS and no error message!

### ISSUE THREAD

**Issue by gleek13** [Azure/azure-sdk-for-net#5210]
I'm trying to use Bing Spell Check in LUIS (online - luis.ai) but it is not working, and LUIS does not show an error message.  I can call the spell check API directly and it works fine with our subscription key.  It does not work when called from the LUIS testing panel. I have tried valid and invalid keys but nothing is shown in LUIS.  How do I see the error(s)? Where does LUIS post those error messages?

**Comment by lilyjma** [comment]
@gleek13 is this still a problem for you?

**Comment by jsquire** [comment]
Closing this out, as there has been no recent engagement.  Please feel free to reopen if you feel that further discussion is needed.
