### ISSUE TITLE
Ensure that we check the request version 

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#5237]
In method `VerifyRequestLine` we used to validate the Version of the request message.

However due to some infrastructure issues I have disabled that code for now (on Linux and Windows the defaults seemed to be different) -- possible because the code was running on different versions of .NET Core.

```csharp
        void VerifyRequestLine(HttpRequestMessage request)
        {
            Assert.AreEqual(_expectedMethod, request.Method);
            _expectedUri.Verify(request.RequestUri.ToString());

            // Uncomment this!
            //Assert.AreEqual(new Version(2, 0), request.Version);
        }
```

**Comment by weshaggard** [comment]
Closed with https://github.com/Azure/azure-sdk-for-net/pull/5254.
