### ISSUE TITLE
InvalidRequestContent - Deploy Vnet with 2 Subnets JSON template

### ISSUE THREAD

**Issue by Rossco88** [Azure/azure-sdk-for-net#5255]
Hi Guys

We have VM labs that are deployed via JSON templates for students, recently a requirement to deploy multiple VM's for a student in separate subnets under the same Vnet is required. 

We are getting the following error

Error code
InvalidRequestContent
Message
The request content was invalid and could not be deserialized: 'Invalid property identifier character: {. Path 'Properties.template.resources[4].properties.addressSpace', line 181, position 8.'.

the part of the JSON template it is referring to is below starting with Line 181. 

{
          "apiVersion": "2018-11-01",
          "dependsOn": [
            "[Variables('vnet')]"
          ],
          "location": "australiaeast",
          "name": "subnet1",
          "properties": {
            "addressPrefix": "10.1.0.0/26"
          },
          "type": "subnets"
        },
        {
          "apiVersion": "2018-11-01",
          "dependsOn": [
            "[Variables('vnet')]"
          ],
          "location": "australiaeast",
          "name": "subnet2",
          "properties": {
            "addressPrefix": "10.1.0.64/26"
          },
          "type": "subnets"
        },

As far as Visual Studio is concerned this template file is fine

Thanks

**Comment by isra-fel** [comment]
Hi @Rossco88 sorry for late response. This looks like valid JSON to me. Could you share the whole template, or the upper level? Thanks
