### ISSUE TITLE
The Link in all PRs to the Breaking Changes definition is a 404

### ISSUE THREAD

**Issue by cleemullins** [Azure/azure-sdk-for-net#5257]
Every PR has this text:

"The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md)."

Unfortunately, the link is a 404. 

Once my laughing from the irony wore off, I figured I would let you know. :)

**Comment by AlexGhiondea** [comment]
Thank you for pointing that out!

**Comment by AlexGhiondea** [comment]
I'm not seeing that anymore -- if you see it again, please let me know!
