### ISSUE TITLE
[QUERY] What is the 'Key' field in DeploymentImpl

### ISSUE THREAD

**Issue by fashaikh** [Azure/azure-sdk-for-net#5263]
**Query/Question**
I see this in the debug view. but cant find documentation for it or how I can use it in my code
![image](https://user-images.githubusercontent.com/2650941/53125319-97902300-3512-11e9-8ddd-fcd7c2308c75.png)

***Why is this not a Bug or a feature Request?***
Not sure yet.  I need to get a guid for a deployment via fluent, and this seems to be it but I cant seem to use it directly in the code
i.e
'deploymentId.Key'

errors during build  which is confusing

**Setup (please complete the following information if applicable):**
 - OS: windows
 - IDE : VS2017
 - Version of the Library used: 1.0.24
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Query Added
- [ x] Setup information Added

**Comment by kurtzeborn** [comment]
Thank you for opening this issue!  We are routing it to the appropriate team for follow up.

**Comment by isra-fel** [comment]
Sorry for late response. @weidongxu-microsoft could you help with this issue? Thank you!

**Comment by weidongxu-microsoft** [comment]
1.0.24 is a too early SDK version.

Please refer to doc or spec for details of properties. https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Resources/stable/2019-08-01/resources.json#L4518

If it not included in doc or spec, it probably not meanful.

**Comment by weidongxu-microsoft** [comment]
Please reopen if you have question.
