### ISSUE TITLE
[Feature Request] Update dependencies of Microsoft.Rest.ClientRuntime.Azure.TestFramework & Microsoft.Rest.ClientRuntime.Azure.Authentication

### ISSUE THREAD

**Issue by gasper-az** [Azure/azure-sdk-for-net#5271]
**Is your feature request related to a problem? Please describe.**
When trying to update the **Microsoft.Rest.ClientRuntime.Azure.TestFramework** to the latest version ([1.7.6](https://www.nuget.org/packages/Microsoft.Rest.ClientRuntime.Azure.TestFramework/)), which will be used along the **Microsoft.Bot.Connector** [4.1.5](https://www.nuget.org/packages/Microsoft.Bot.Connector/4.1.5), we are having the next dependencies errors:

| Project                                                | Microsoft.Rest.ClientRuntime.Azure.TestFramework 1.7.6  | Microsoft.Bot.Connector 4.1.5 |
| ---------------------------------------  |  --------------------------------- | ------------------------ |
| Version   of Microsoft.IdentityModel.Clients.ActiveDirectory    required | >= 3.14.0 && < 4.0.0 | >= 4.5.0
| Version   of Microsoft.IdentityModel.Tokens required | = 5.1.2 | >= 5.2.1

Also, we noticed that the **Microsoft.Rest.ClientRuntime.Azure.Authentication** [v2.3.7](https://www.nuget.org/packages/Microsoft.Rest.ClientRuntime.Azure.Authentication/) requires the usage of **Microsoft.IdentityModel.Clients.ActiveDirectory** greater or equal than **v3.14.0** and minor to **4.0.0**.

**Describe the solution you'd like**
It's necessary to update the next required versions:

- **Microsoft.IdentityModel.Clients.ActiveDirectory** to [4.5.1](https://www.nuget.org/packages/Microsoft.IdentityModel.Clients.ActiveDirectory/4.5.1), because the latest version allowed by both **Microsoft.Rest.ClientRuntime.Azure.TestFramework** and **Microsoft.Rest.ClientRuntime.Azure.Authentication** is the **3.19.8** (should be minor to _4.0.0_), which was released 8 months ago ([link](https://www.nuget.org/packages/Microsoft.IdentityModel.Clients.ActiveDirectory/3.19.8))

- **Microsoft.IdentityModel.Tokens** to [5.4.0](https://www.nuget.org/packages/Microsoft.IdentityModel.Tokens/5.4.0), because the latest version allowed by **Microsoft.Rest.ClientRuntime.Azure.TestFramework** should be **5.2.1**, which was released 6 months ago ([link](https://www.nuget.org/packages/Microsoft.IdentityModel.Tokens/5.2.1))

**Steps to reproduce**
As we are currently working on the [BotBuilder-Dotnet](https://github.com/Microsoft/botbuilder-dotnet) repository, the steps to reproduce the ISSUE mentioned above are:

- Clone the [BotBuilder-Dotnet](https://github.com/Microsoft/botbuilder-dotnet) repository
- Open the _Microsoft.Bot.Builder.sln_ solution in Visual Studio 2017
- Build _Microsoft.Bot.Connector.Tests_ project under the Tests folder
- You will see the next Warning:
```warning NU1608: Detected package version outside of dependency constraint: Microsoft.Azure.Test.HttpRecorder 1.7.0 requires Newtonsoft.Json (>= 9.0.1 && < 10.0.0) but version Newtonsoft.Json 10.0.3 was resolved.```

This is because we are using _[Microsoft.Rest.ClientRuntime.Azure.TestFramework v1.6.0](https://www.nuget.org/packages/Microsoft.Rest.ClientRuntime.Azure.TestFramework/1.6.0)_, which one of its dependencies is _[Microsoft.Azure.Test.HttpRecorder 1.7.0](https://www.nuget.org/packages/Microsoft.Azure.Test.HttpRecorder/1.7.0)_, which also has the next constraint on the _Newtonsoft.Json_ package:

![image](https://user-images.githubusercontent.com/43762887/53199310-853ee380-35fd-11e9-8223-4bf410e7bae5.png)

Here is a screenshot of the .csproj file:
![image](https://user-images.githubusercontent.com/43762887/53199323-8e2fb500-35fd-11e9-9fc6-eb6d6da5fa33.png)

Also, is important to highlight that we have a reference to another project of this solution, which is _Microsoft.Bot.Connector_ [v4.1.5](https://www.nuget.org/packages/Microsoft.Bot.Connector/4.1.5) :

![image](https://user-images.githubusercontent.com/43762887/53199339-9851b380-35fd-11e9-90a6-5414359a1367.png)

![image](https://user-images.githubusercontent.com/43762887/53199345-9c7dd100-35fd-11e9-8a80-dff8b45f5feb.png)

* Trying to solve the previous ISSUE, update the _Microsoft.Rest.ClientRuntime.Azure.TestFramework_ to its latest version [v1.7.6](https://www.nuget.org/packages/Microsoft.Rest.ClientRuntime.Azure.TestFramework/1.7.6)
* After trying updating this dependency, the next error (which correspond to the first dependency issue we mentioned above) will be shown:

![image](https://user-images.githubusercontent.com/43762887/53199359-a8699300-35fd-11e9-8a8f-c3a3c94252df.png)

_Note_
These are the current NuGet packages we are using on _Microsoft.Bot.Connector.Test_ project:
![image](https://user-images.githubusercontent.com/43762887/53199371-b0293780-35fd-11e9-88c2-e7e38b83815f.png)

**Comment by kurtzeborn** [comment]
Thank you for opening this issue!  We are routing it to the appropriate team for follow up.

**Comment by EricDahlvang** [comment]
I think this can be closed.  It appears to have been addressed with https://www.nuget.org/packages/Microsoft.Rest.ClientRuntime.Azure.TestFramework/1.7.7
