### ISSUE TITLE
[FEATURE REQ] Allow to create LUIS Dispatch app in Microsoft.Azure.CognitiveServices.Language.LUIS.Authoring

### ISSUE THREAD

**Issue by hansmbakker** [Azure/azure-sdk-for-net#5278]
**Is your feature request related to a problem? Please describe.**
I want to create a LUIS Dispatch app from a .net core app. I'm using the `Microsoft.Azure.CognitiveServices.Language.LUIS.Authoring` NuGet package.

**Describe the solution you'd like**
Methods in the `Microsoft.Azure.CognitiveServices.Language.LUIS.Authoring` NuGet package to create a Dispatch app based on other LUIS apps and QnA KBs

**Describe alternatives you've considered**
- Create a separate Dispatch nuget package
- Use `Process.Start` to use the `dispatch` CLI tool (feels unclean).

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [*] Description Added
- [*] Expected solution specified

**Comment by kurtzeborn** [comment]
Thank you for opening this issue!  We are routing it to the appropriate team for follow up.

It appears to be data-plan code, so routing this to our client libraries team.

**Comment by hansmbakker** [comment]
@kurtzeborn @AlexGhiondea @tsuwandy do you have any update for this?

**Comment by cahann** [comment]
Dispatch is a tool on top of LUIS but it is not integrate yet in the service so the operations are not natively support through luis authoring APIs

**Comment by AlexGhiondea** [comment]
@hansmbakker does this answer your question?

**Comment by hansmbakker** [comment]
Well that answer is from 7 months ago, was hoping for some new insights / roadmap, but  if that is still the same then “it is what it is”

**Comment by cahann** [comment]
Dispatch is not owned by the LUIS team so we dont have plans for native support as part of the LUIS SDKs

**Comment by hansmbakker** [comment]
Ok, thank you for your response. In that case this issue can be closed.

**Comment by AlexGhiondea** [comment]
Thank you @hansmbakker.
