### ISSUE TITLE
Resource Group should be returned in API Management service response ApiManagementServiceResource

### ISSUE THREAD

**Issue by MilindThakkar** [Azure/azure-sdk-for-net#5285]
API Management List or any other function response doesn't contain Resource Group. However it always asks for Resource Group of the service when you try to add /import API or any other operation. This is little strange as I have to go back portal to get the exact resource group 

A property should be added to ApiManagementServiceResource model 

As the only other alternate is to do string manipulation to find the group on ID property, which is not right IMHO

**Comment by kurtzeborn** [comment]
Thank you for opening this issue!  We are routing it to the appropriate team for follow up.

**Comment by isra-fel** [comment]
This issue was also assigned to the wrong person.  @solankisamir could you help loop in the correct people? Thanks.

**Comment by solankisamir** [comment]
The `Id` property of the response contains the `ResourceGroup`
