### ISSUE TITLE
[FEATURE REQ] Need a Microsoft.Azure.Management.EventHub pkg for .net 4.5.

### ISSUE THREAD

**Issue by lifhu** [Azure/azure-sdk-for-net#5307]
**Is your feature request related to a problem? Please describe.**
We have projects built against .net framework 4.5 and no Microsoft.Azure.Management.EventHub pkgs were able to built for it, except for 1.1.0, which is very old without management API we need.

**Describe the solution you'd like**
Need a Microsoft.Azure.Management.EventHub pkg for .net 4.5.

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by kurtzeborn** [comment]
Thank you for opening this issue!  We are routing it to the appropriate team for follow up.

**Comment by Petermarcu** [comment]
Thanks for the feedback. The Azure SDK minimum supported .NET Framework version is currently at .NET Framework 4.7.2. We strongly encourage you to update your target framework to either that or .NET Standard 2.0 if its a library project. .NET 4.7.2 is an update available on all supported OS's and broadly distributed via Windows Update. Hopefully by now, everywhere you need to run has at least 4.7.2 if not 4.8. I'm going to close this issue now.
