### ISSUE TITLE
[QUERY] TokenCredential and periodicTokenRenewer

### ISSUE THREAD

**Issue by yokode** [Azure/azure-sdk-for-net#5309]
**Query/Question**
I'm looking into using TokenCredential's periodicTokenRenewer functionality however I could not find any best practices on which cases should it be used, the minimal frequency which should be set or any sample code that actually uses this.
We are currently using TokenCredential to populate StorageCredentials that are being used by a CloudStorageAccount to access Azure Blob Storage.
For short lived access the renewer is obviously unnecessary but we have some use cases which would require long lived access as well.

***Why is this not a Bug or a feature Request?***
This might later escalate into a feature request for documentation but currently I would just like to inquire about this.

**Setup (please complete the following information if applicable):**
Not relevant
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Query Added
- [X] Setup information Added

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

CC: @shahabhijeet

**Comment by yokode** [comment]
@kurtzeborn - any news regarding this?

**Comment by jongio** [comment]
@yokode - Please see the new Token Refresh policies and reopen this issue if it doesn't solve what you are after.  Thanks, Jon
https://devblogs.microsoft.com/azure-sdk/azure-identity-august-2020-ga/#proactive-token-refresh
