### ISSUE TITLE
[BUG] No SdkBuildTools before step 4

### ISSUE THREAD

**Issue by dashesy** [Azure/azure-sdk-for-net#5347]
**Describe the bug**
The documentation asks

Sn -Vr tools\SdkBuildTools\tasks\net46\Microsoft.Azure.Sdk.Build.Tasks.dll

But there is no SdkBuildTools in tools yet, it appears after the next instruction, i.e. after

MsBuild.exe build.proj

***Exception or Stack Trace***
Failed to open metadata scope on tools\SdkBuildTools\tasks\net46\Microsoft.Azure.Sdk.Build.Tasks.dll -- The system cannot find the path specified.

**To Reproduce**
clone
follow instructions
Sn -Vr tools\SdkBuildTools\tasks\net46\Microsoft.Azure.Sdk.Build.Tasks.dll

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

CC: @shahabhijeet

**Comment by dashesy** [comment]
Thanks, just to clarify the documentation is the Readme in this repo

**Comment by AlexGhiondea** [comment]
@kurtzeborn can you take a look at this?

**Comment by kurtzeborn** [comment]
Docs have been updated and sn.exe exceptions are no longer needed in order to build.
