### ISSUE TITLE
[BUG] No SDKs directory must be src/SDKs

### ISSUE THREAD

**Issue by dashesy** [Azure/azure-sdk-for-net#5348]
**Describe the bug**
Documentation mentions 

Open any solution, eg "SDKs\Compute\Compute.sln"

And later

msbuild build.proj /t:CreateNugetPackage /p:scope=SDKs\Compute

But there is no SDKs directory, it must be src\SDKs

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

CC: @shahabhijeet @weshaggard

**Comment by AlexGhiondea** [comment]
@kurtzeborn now that we have changed the structure of the repo we should make sure the docs are calling out the new structure.

**Comment by weshaggard** [comment]
The docs have been updated. this should not be any issue any longer.
