### ISSUE TITLE
Enable client test runs against .NET Framework

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-for-net#5367]
Currently our test for data plane/client libraries only run against .NET Core we should enable get them running on .NET Framework as well.

**Comment by maririos** [comment]
@chidozieononiwu do you know when we will this be done?

**Comment by chidozieononiwu** [comment]
> @chidozieononiwu do you know when we will this be done?

I am almost done with this. I have it all working on my dev machine but I have to sort out some errors that occur when run on the devOps pipeline. Hopefully I should be done today.

**Comment by maririos** [comment]
Cool. Not that we are blocked on that, but wanted to see the ETA :)
