### ISSUE TITLE
Is ImportCertificateWithHttpMessagesAsync idempotent?

### ISSUE THREAD

**Issue by sarajang** [Azure/azure-sdk-for-net#5371]
I am trying to figure out whether the operation ImportCertificateWithHttpMessagesAsync on KeyVaultClient is idempotent or not. The documentation is a bit unclear on this one.

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

CC: @schaabs

**Comment by schaabs** [comment]
@sarajang thanks for your feedback on the documentation.  Adding @prashanthyv who can help with updating the documentation.

To answer your question, yes ImportCertificateWithHttpMessagesAsync is idempotent.  Importing a certificate will result in a new certificate being created in the case that a certificate with the specified name doesn't already exist in the vault.  In the case that a certificate with the specified name already exists in the vault, a new version of the certificate is created.  All versions of the certificate can be accessed via GetCertificateAsync or GetCertificateWithHttpMessagesAsync by specifying the specific version, if no version is speicired the latest version of that certificate will be returned.  Please let me know if you have more questions.

**Comment by prashanthyv** [comment]
Thanks @schaabs

**Comment by sarajang** [comment]
Thank you, would appreciate an update to the documentation as well.

**Comment by prashanthyv** [comment]
@sarajang - We need to do a code update for the same. Will work on it. 

Thanks
