### ISSUE TITLE
Introduce the package reference to Azure.Base

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#5378]
@maririos commented on [Thu Feb 28 2019](https://github.com/Azure/azure-sdk-for-net-lab/issues/126)

**Comment by maririos** [comment]
@AlexGhiondea  what is the work that needs to happen here? I can't remember

**Comment by AlexGhiondea** [comment]
I think this is done now -- this was to have a dependency from AzConfig to Base as a Nuget package
