### ISSUE TITLE
Support Correlation IDs

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#5381]
@KrzysztofCwalina commented on [Fri Jan 18 2019](https://github.com/Azure/azure-sdk-for-net-lab/issues/30)

We need the ability to correlate multiple requests that are part of a larger logical operation. For example, all Get requests that are part of a single polling interval in the ConfigurationWatcher

---

@maririos commented on [Fri Feb 01 2019](https://github.com/Azure/azure-sdk-for-net-lab/issues/30#issuecomment-459908127)

Per our conversation, moving the issue out of Preview 1

---

@maririos commented on [Mon Feb 04 2019](https://github.com/Azure/azure-sdk-for-net-lab/issues/30#issuecomment-460354807)

Notes from meeting with service team:
-	Can flow into the service (as the service is a middleware) 
-	Correlation ID is cross service

**Comment by AlexGhiondea** [comment]
Is this still relevant?

**Comment by maririos** [comment]
Yes. correlation id is something we need to support. @pakrym  did some work on Azure.Base to include it.
I don't think we are using it on AzConfig yet, but I have to double check.
At least add a test or something

**Comment by pakrym** [comment]
I added support for RequestId only, we don't have anything for CorrelationId but it's still relevant.

**Comment by maririos** [comment]
Thanks for the clarification!

**Comment by pakrym** [comment]
Moved to Azure.Core label and this should be done in a central way.

**Comment by pakrym** [comment]
Moved to Azure.Core label and this should be done in a central way.

**Comment by AlexGhiondea** [comment]
I believe we have a story here. Please confirm and then close.
