### ISSUE TITLE
Ensure that we have XML doc comments for public APIs

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#5382]
@AlexGhiondea commented on [Thu Jan 24 2019](https://github.com/Azure/azure-sdk-for-net-lab/issues/76)

---

@maririos commented on [Wed Feb 27 2019](https://github.com/Azure/azure-sdk-for-net-lab/issues/76#issuecomment-468098712)

@AlexGhiondea could you clarify what you mean with XML doc comments?

**Comment by AlexGhiondea** [comment]
This means that public APIs have documentation (using the `\\\` syntax)
