### ISSUE TITLE
SettingBatchFilter should allow specifying max items to retrieve

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#5389]
@KrzysztofCwalina commented on [Fri Jan 18 2019](https://github.com/Azure/azure-sdk-for-net-lab/issues/47)

The range header accepts upper bound. For the spec:

Range: items=0-2

**Comment by maririos** [comment]
According to conversations with the other languages, for Preview 2, Range is not going to be supported.
Once there is a more clear need, we will go ahead and implement it.

**Comment by annelo-msft** [comment]
Functionality is not currently required.  We may revisit in a later release.
