### ISSUE TITLE
ConfigurationWatcher Should Take EqualityComparer  Parameter

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#5392]
@KrzysztofCwalina commented on [Fri Jan 18 2019](https://github.com/Azure/azure-sdk-for-net-lab/issues/51)

**Comment by AlexGhiondea** [comment]
Is this still relevant?

**Comment by maririos** [comment]
> Is this still relevant?

What do you mean?
As part for the work done for Preview 2, we haven't touched the watcher.

**Comment by pakrym** [comment]
Configuration watcher is not shipping.
