### ISSUE TITLE
Azure.ApplicationModel.Configuration Cleanup

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#5395]
@KrzysztofCwalina commented on [Fri Jan 18 2019](https://github.com/Azure/azure-sdk-for-net-lab/issues/39)

- [x] remove all NotImplementedException
- [x] remove all TODOs
- [x] move types into their own files names appropriately

**Comment by annelo-msft** [comment]
Moved TODOs into issues.
