### ISSUE TITLE
Add samples for the configuration service

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#5397]
@maririos commented on [Mon Mar 11 2019](https://github.com/Azure/azure-sdk-for-net-lab/issues/127)

The samples should leave in the root of the project directory, next to the Readme.
Links in the Readme are an option. 
Adding the samples to a C# Playground is something to look into.

More information about Readme guidelines: https://github.com/Azure/azure-sdk/blob/master/docs/README-TEMPLATE.md

**Comment by AlexGhiondea** [comment]
Is there anything left to do here?

**Comment by maririos** [comment]
Yeah. Improve the samples

**Comment by maririos** [comment]
PR: https://github.com/Azure/azure-sdk-for-net/pull/5789
