### ISSUE TITLE
Async ienumerable for GetBatch

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#5410]

**Comment by AlexGhiondea** [comment]
Can this be implemented or do we need help from the compiler/runtime? /cc @KrzysztofCwalina

**Comment by maririos** [comment]
After talking to .NET team, the NuGet package for Async ienumerable will be available for preview 6, so around June. To not block the release of AppConfig Preview 2, we are going to work on issue #5993 for now so we can consume it in the future, and I will move this issue to vNext epic.

**Comment by maririos** [comment]
This was done by @pakrym

**Comment by pakrym** [comment]
This would have to be redone with new AsyncCollection pattern.
