### ISSUE TITLE
Review visibility of property ETag

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#5412]
Per .NET guideline, this should be readonly if visible at all.

"DO ensure model public properties are get-only if they aren’t intended to be changed by the user."

**Comment by maririos** [comment]
Meeting scheduled for Wednesday 3/12

**Comment by maririos** [comment]
The conclusion of the meeting is that for now we are going to leave it visible for the customer, but we need to look into what other services need/scenarios they have.
One example will be the storage service.

We did expand in the API surface across languages. More information about it could be found in onenote:https://microsoft.sharepoint.com/teams/AzureDeveloperExperience/Shared%20Documents/Service%20-%20Azconfig/Azure%20SDK%20-%20Service%20-%20Azconfig/Azconfig.one#Standarization%20across%20languages%20&section-id=%7B50856656-5D71-2640-B240-11758DB2FB6E%7D&page-id=%7B79180E7A-F7B4-4221-8398-D440467E3782%7D&object-id=%7BAD444C44-9B38-0225-20E9-23FDAB509498%7D&22

**Comment by AlexGhiondea** [comment]
Can we close this?

**Comment by maririos** [comment]
The visibility itself hasn't been decided, so I would prefer to leave open until we reach a decision

**Comment by annelo-msft** [comment]
If ETag is available on raw response, do we need it to be publicly visible?  It seems like an advanced scenario that could warrant advanced usage like digging into a response object.

Per guideline: DO allow a consumer to access the complete response, including the status line, headers and body. The client library must follow the language specific guidance for accomplishing this.

**Comment by annelo-msft** [comment]
Issue raised with arch board: https://github.com/Azure/azure-sdk/issues/638

**Comment by annelo-msft** [comment]
Readonly.  Implemented in #7717
