### ISSUE TITLE
Get behavior when Configuration Setting doesn't exists

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#5416]
- Should it throw or return null?
- Implement `TryGetSetting`?

**Comment by AlexGhiondea** [comment]
I think this should throw when the setting doesn't exist.

**Comment by maririos** [comment]
After a conversation with other .NET team members, we are going to go with Throw. Once we have customer feedback or more clarity on customer scenarios, then we'll revisit
