### ISSUE TITLE
Testing on .NET Framework

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#5417]
Currently our CI only runs tests for .NET Core. We need to add testing coverage for .NET Framework before GA

**Comment by maririos** [comment]
@bsiegel Do you know if there is something special we need to do in the .yml file in order to set the test to run for a specific framework?

**Comment by bsiegel** [comment]
@maririos I believe everything is driven by the csproj files - there's nothing special that should need to be done to make it work for netfx vs netcore. Just make sure that the project file has configurations for both frameworks and we can use a build matrix to run tests via msbuild with both frameworks.

**Comment by maririos** [comment]
Closing as dup of https://github.com/Azure/azure-sdk-for-net/issues/5367
