### ISSUE TITLE
[Service Bus] Improve live test reliability

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-net#5426]
The Service Bus live tests appear to have some flaky tests.  The tests were run in a loop for many hours to collect reliability data.  Results are here:

https://dev.azure.com/azure-sdk/playground/_test/analytics?buildDefinitionId=142

**Comment by jsquire** [comment]
Closing this issue as a duplicate of:  
    [[Service Bus Client] Stabilize Live Tests (#5446)](https://app.zenhub.com/workspace/o/azure/azure-sdk-for-net/issues/5446)
