### ISSUE TITLE
[Service Bus Client] Stabilize Live Tests 

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#5446]
The tests adopted from the [standalone repository](https://github.com/Azure/azure-service-bus-dotnet), which were designated as Live are not fully self-contained nor resilient, which has resulted in some unpredictable failures when run as part of the nightly runs. 

In order to ensure that the nightly run is reliable, the Service Bus results should be investigated and tests that are not reliable should be analyzed. 

  - If the test is not current and is not needed to verify functionality of the service, it should be deleted.  

  - If the test can be improved in a reasonable amount of time and effort, it should be.  

 - If the test is needed and requires more than a reasonable effort, it should be flagged to be skipped and a separate issue opened to cover the work required to fix the test.  

The tests were run in a loop for many hours to collect reliability data. Results are here: 
https://dev.azure.com/azure-sdk/playground/_test/analytics?buildDefinitionId=142

#### Related Issues 
  - [[Service Bus] Improve live test reliability](https://github.com/Azure/azure-sdk-for-net/issues/5426) (#5426) _[closed as duplicate]_

**Comment by mikeharder** [comment]
The .NET live tests have failed every day for the past 7, so I think we need to either fix or disable these tests in the next few days.  Here are the test analytics for the nightly builds (filter to last 7 days):

https://dev.azure.com/azure-sdk/internal/_test/analytics?buildDefinitionId=37

The following tests are failing every build:

![image](https://user-images.githubusercontent.com/9459391/54855221-c84eae00-4cb2-11e9-8a31-17107198d677.png)

Plus more tests are flaky.

**Comment by jsquire** [comment]
@mikeharder: These are actively being worked on.  The entire infrastructure is being overhauled and the changes will come in two phases: the first is adding isolation to each test case to run in its own queue/topic.  A side-effect of this is that we are likely to be able to parallelize the runs.

The next phase will start the whack-a-mole of trying to tweak some of the brittle timing issues.  I have the feeling that this will be more insidious and will need to be an ongoing effort.

I expect that the first phase of changes should hit PR early next week, and there are some related things that I’ll be asking to bounce off of you.

**Comment by jsquire** [comment]
After the last set of changes, we've had 5+ days with no Service Bus failures or flaky behavior.   I'm going to consider the stabilization verified at this point; we can pursue any future flaky behavior under a new issue, should there be a need.
