### ISSUE TITLE
How do I select a FIPS compatible cryptographic algorithm for a key vault managed storage account

### ISSUE THREAD

**Issue by glennsills** [Azure/azure-sdk-for-net#5450]
When access a StorageAccount blob storage via a CloudBlobClient I get the following exception

Microsoft.WindowsAzure.Storage.StorageException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.

I do not see a way for a client select the V1MD5 algorithm (StorageAccount.V1MD5) from a key vault managed storage account, since the StorageAccounts are not directly accessible - instead there are StorageAccountBundles. Any suggestions.

I'm using Microsoft.Azure.KeyVault 3.0.3

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

CC: @schaabs

**Comment by schaabs** [comment]
@prashanthyv could you take a look at this?

**Comment by glennsills** [comment]
Any thoughts on this?

**Comment by AlexGhiondea** [comment]
@RandalliLama could you please look into this?

**Comment by glennsills** [comment]
Anyone? Anyone?

**Comment by heaths** [comment]
Using MD5 on the client will cause Windows crypto APIs (Crypto and CNG) to err. FIPS compliance would have to be disabled on the host, which is not recommended. So if selecting MD5, which is expected. But I am a bit confused if you're trying to select MD5 (not FIPS-compliant), saying there's no way to select anything else. If this is still a problem, could you clarify?

Are you trying to manage rotation keys via storage, or encrypt blobs for storate? Our newer libraries (Azure.*) are recommended and we have a feature launching today that would be easier and better to use (documentation coming soon).

**Comment by heaths** [comment]
If you're doing this to work around Storage not supporting AAD, Storage does now support AAD and it's recommended you use AAD and Managed Identity. This is much simpler in Azure.* packages, and service documentation is available at https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad. Please review this and let us know if this works better for you.

**Comment by heaths** [comment]
Closing with no response from the customer. If we get the information requested, we can reopen for further investigation.

**Comment by glennsills** [comment]
> Closing with no response from the customer. If we get the information requested, we can reopen for further investigation.

Sorry, by the time you had looked at this I had moved to another job :-)
