### ISSUE TITLE
[Event Hubs Client] Stabilize Live Tests

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#5451]
The tests adopted from the [standalone repository](https://github.com/azure/azure-event-hubs-dotnet), which were designated as Live are not fully self-contained nor resilient, which has resulted in some unpredictable failures when run as part of the nightly runs. 

In order to ensure that the nightly run is reliable, the Event Hubs results should be investigated and tests that are not reliable should be analyzed. 

  - If the test is not current and is not needed to verify functionality of the service, it should be deleted.  

  - If the test can be improved in a reasonable amount of time and effort, it should be.  

 - If the test is needed and requires more than a reasonable effort, it should be flagged to be skipped and a separate issue opened to cover the work required to fix the test.

**Comment by JamesBirdsall** [comment]
For ServiceFabricProcessor, most of these were fixed by #7446. EventException test has a separate issue with the error count being off by one.
