### ISSUE TITLE
InternalServerError when calling AuthorizationServer.CreateOrUpdate[BUG]

### ISSUE THREAD

**Issue by richardjharding** [Azure/azure-sdk-for-net#5468]
**Describe the bug**
I'm attempting to create (or update) an AuthorizationServer entry in a API Management service using the sdk

***Exception or Stack Trace***
I've traced the response from the server in fiddler:
```
HTTP/1.1 500 Internal Server Error
Content-Type: application/json; charset=utf-8
Strict-Transport-Security: max-age=31536000; includeSubDomains
Date: Fri, 15 Mar 2019 11:55:40 GMT
Content-Length: 116

{"error":{"code":"InternalServerError","message":"Request processing failed due to internal error.","details":null}}
```

this results in an exception raised by the sdk with no more information

**To Reproduce**
Attempt to create a new authorization server using the [docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.apimanagement.authorizationserveroperationsextensions.createorupdate?view=azure-dotnet) 

***Code Snippet***
Here is an example of code (note in F#) I've redacted some urls and secrets
```
let serverContract = AuthorizationServerContract("rjh-test-auth","<redacted>",
                                                    "<redacted>",[|"authorizationCode";"implicit"|],
                                                    "APIManagementClient","rjh-test-auth")
    
    serverContract.DisplayName <- "rjh-test-auth"
    serverContract.Description <- "Identity Server Dev"
    serverContract.AuthorizationEndpoint <- "<redacted>"
    serverContract.ClientRegistrationEndpoint <- "<redacted>"
    serverContract.ClientId <- "APIManagementClient"
    serverContract.ClientSecret <- "<redacted>"
    serverContract.GrantTypes <- [|"authorizationCode";"implicit"|]
    serverContract.SupportState <- Nullable<bool> true
    serverContract.TokenEndpoint <- "<redacted>"
    serverContract.AuthorizationMethods <- [|(Nullable<AuthorizationMethod> AuthorizationMethod.GET)|]
    serverContract.ClientAuthenticationMethod <- [|"Body"|]
    
    serverContract.Validate()

    client.AuthorizationServer.CreateOrUpdate(args.resourceGroupName, args.serviceName, "rjh-test-auth",serverContract, null) |> ignore
```

and here is the body that was sent in the PUT request

```
{
  "properties": {
    "description": "Identity Server Dev",
    "authorizationMethods": [
      "GET"
    ],
    "clientAuthenticationMethod": [
      "Body"
    ],
    "tokenEndpoint": "https://identity-dev.dev.digitalsse.cloud/connect/token",
    "supportState": true,
    "clientSecret": "<redacted>",
    "displayName": "rjh-test-auth",
    "clientRegistrationEndpoint": "<redacted>",
    "authorizationEndpoint": "<redacted>",
    "grantTypes": [
      "authorizationCode",
      "implicit"
    ],
    "clientId": "APIManagementClient"
  }
}
```

**Expected behavior**
The new authorization service is created in the api management instance

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used - 4.0.6 preview

**Additional context**
I should add that I am able to query existing authorization servers via the sdk ok so I'm confident authentication is working
I should also add that the api management instance is set up with custom domains and I've set the client.BaseUri to suit

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by isra-fel** [comment]
Sorry for late response. Hi Michael could you share some insights on this? Thanks

**Comment by solankisamir** [comment]
This looks like a server side issue. @richardjharding is this still reproducible? We don’t have logs going back 1 year. 
- Can you provide the correlationid / api management service name + datetime with the most recent repro?

**Comment by richardjharding** [comment]
I don't think this is still reproducible - we are call the API without errors now
