### ISSUE TITLE
Exceptions in long running operations are not localized

### ISSUE THREAD

**Issue by anponnet** [Azure/azure-sdk-for-net#5506]
**Describe the bug**
When I make any call which returns a 202 (Accepted) and put the location header as the link to OperationResults API, SDK polls the OperationResults API continuously till it receives a 200 (or an error). In our case it throws an error. The expectation in this error is not localized. When I tried to debug this, I found when SDK calls the OperationResults API, it is not adding the “accept-language” header. Ie, Client.AcceptLanguage is not honored.

**To Reproduce**
This is how I tested it. When creating the SDK client, we set the property AcceptLanguage as shown below. Our service honors this header, and localizes any message based on this.

this.Client = this.Context.GetServiceClient<DataBoxEdgeManagementClient>();
       this.Client.AcceptLanguage = "fr";

a.	Scenario 1: When I make any synchronous call and there is any message/ exception thrown, it is localized as client SDK adds “accept-language” header to http request before sending it. No Issue here

b.	Scenario 2. When I make any call which returns a 202 (Accepted) and put the location header as the link to OperationResults API, SDK polls the OperationResults API continuously till it receives a 200 (or an error). In our case it throws an error. The expectation in this error is not localized. When I tried to debug this, I found when SDK calls the OperationResults API, it is not adding the “accept-language” header. Ie, Client.AcceptLanguage is not honored.

Here, we have 2 issues. One, the exception message thrown by SDK is not localized. Second the inner  details thrown by service is not localized

i.	Exception details: This is the root level exception, this is thrown by SDK, I think. Localizing this based on language header is SDK,s responsibility. 
         {
                                "ClassName": "Microsoft.Rest.Azure.CloudException",
                                "Message": "Long running operation failed with status 'BadRequest'.",
                                .......       
         }

ii.	Exception Body: When you open the exception to see the details of it, the Body property contains the actual exception thrown by the service. It is responsibility of service to localize it based on language header. We have localized it, but since SDK is not passing the accept-language header, it is default to English.

                                         {
                                                       "Code": "GatewayJobsPutDeviceAdminPasswordFailed",
                                                        "Message": "Could not update device admin password on 'ga-ar-testpass03'.\r\nAn error occurred with the error code {NO_PARAM}. \r\nFor more information, refer to the error code details (http://aka.ms/dbe-error-codes). If the error persists, contact Microsoft Support.",
                                                       .....
} 

***Code Snippet***
NA

**Expected behavior**
Long running operation messages/exceptions are localized based on AcceptLanguage header set.

**Screenshots**

**Setup (please complete the following information):**
 - OS: [e.g. iOS]    :  Windows 10
 - IDE : [e.g. IntelliJ]   : Visual Studio
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [Y] Bug Description Added
- [Y] Repro Steps Added
- [Y] Setup information Added

**Comment by markcowl** [comment]
Two parts to this issue.  First is the header not being propagated to the service for asynchronous operations.  This is a bug that should be fixed.

The second is for the library to select a localized version of the base exception string based on the accept-language header setting. In .Net, localization occurs through localized versions of the dll resources, and is selected by the CurrentCulture setting (https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.currentculture?view=netcore-3.1).  However, consumers want to have a consistent experience when selecting for  a particular language The proper way to handle this is likely to *set* a the accept-language setting based on the CurrentCulture setting, so that the application can set the default culture once (or it can be set from default machine settings).
