### ISSUE TITLE
Define code-style guide and add .editorconfig to the repo

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#5515]
I don't think there is a defined set of code-style rules. We should add one and start enforcing it on the new code especially considering that we are productizing Azure.Base.

We might want to copy https://github.com/dotnet/corefx/blob/master/.editorconfig or some other established repo style.

cc @mikeharder @weshaggard

**Comment by weshaggard** [comment]
Thanks for opening @pakrym we have this on our backlog at https://github.com/Azure/azure-sdk/issues/220 but it is good to have one in the individual language repos as well.

**Comment by pakrym** [comment]
Whoops, didn't know that repo exists.
