### ISSUE TITLE
Nightly LiveTest Failures - Microsoft.Azure.ServiceBus.UnitTest

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-net#5526]
[Example Build with Test Failure List](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=10131&view=ms.vss-test-web.build-test-results-tab)

Clicking on the link above should take you directly to a list of the 5 failing tests.

**Comment by AlexGhiondea** [comment]
Closing this for now as the SB tests should be in a good state at this time. Please reactivate if you are still seeing this.
