### ISSUE TITLE
[FEATURE REQ] Add an extension method to return the emotion ranked list with name and respective score

### ISSUE THREAD

**Issue by andreluizsecco** [Azure/azure-sdk-for-net#5560]
**Is your feature request related to a problem? Please describe.**
Using the package **Microsoft.Azure.CognitiveServices.Vision.Face**, if I wanted to check which emotion with the highest score was detected on the face, I need to check all the fields. I have no method or property that will bring this information to me in an easy way.

**Describe the solution you'd like**
Get the emotion list in the detected faces by an extension method to return the emotion ranked list with name and respective score.

**Additional context**
Emotion class does not contain any method or field so I can easily get the name and score.
This causes me to have to implement an additional method to check all the fields to determine the emotion with the highest score identified on the face.

The image below shows the lack of structures in the class that support a rapid use of the identified emotion:
![emotionClass](https://user-images.githubusercontent.com/7199850/54857924-b08e1e80-4ce0-11e9-8f59-235807d19e9c.PNG)

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by andreluizsecco** [comment]
Hello! Would it be better to create a separate package to add functionality and extensions to Azure SDKs? I do not think we're evolving much here: #5561.

**Comment by cthrash** [comment]
FWIW - The older SDK had this [feature](https://github.com/microsoft/Cognitive-Common-Windows/blob/master/ClientLibrary/Contract/EmotionScores.cs#L86), but this namespace and types have deviated.  Could be used as a starting point if the team is interested.

**Comment by andreluizsecco** [comment]
Yes @cthrash, for now I have already sent a PR: #5561

**Comment by jsquire** [comment]
Closing this out, as the referenced PR has been merged.   Please feel free to reopen if you believe that further discussion is needed.
