### ISSUE TITLE
'authority' should be in Uri format Parameter name: authority

### ISSUE THREAD

**Issue by Neue-Ziel** [Azure/azure-sdk-for-net#5563]
**Describe the bug**
When I try

                azureCredentials = SdkContext
                    .AzureCredentialsFactory
                    .FromServicePrincipal(_clientId, _clientSecret, _tenantId, _azureEnvironment);

                currentSubscription = Azure
                    .Configure()
                    .WithLogLevel(HttpLoggingDelegatingHandler.Level.None)
                    .Authenticate(azureCredentials)
                    .WithDefaultSubscription()
                    .GetCurrentSubscription();

everything worked perfect.

But when I get the the AzureCredential elsewhere (in a static method in a static class)

I got the 

**authority should be in uri format**

Exception

The problem seems to be with the **.WithDefaultSubscription()**
I have tried bypass use another thread which suggested in
https://github.com/Azure/azure-sdk-for-net/issues/3238
but had no luck.

***Code Snippet***

This piece of code worked

                azureCredentials = SdkContext
                    .AzureCredentialsFactory
                    .FromServicePrincipal(_clientId, _clientSecret, _tenantId, _azureEnvironment);

                currentSubscription = Azure
                    .Configure()
                    .WithLogLevel(HttpLoggingDelegatingHandler.Level.None)
                    .Authenticate(azureCredentials)
                    .WithDefaultSubscription()
                    .GetCurrentSubscription();

And this snippet throws exception
**authority should be in uri format
Parameter name: authoriy**

                azureCredentials = SdkContext
                    .AzureCredentialsFactory
                    .FromServicePrincipal(clientId, clientSecret, tenantId, azureEnvironment);
(separated in another class)

                currentSubscription = Azure
                    .Configure()
                    .WithLogLevel(HttpLoggingDelegatingHandler.Level.None)
                    .Authenticate(_azureCredentials)
                    .WithDefaultSubscription()
                    .GetCurrentSubscription();

**Setup (please complete the following information):**
 - OS: Windows 10 1809
 - IDE : vs2017
 - Version of the Library used
.NET Framework 4.6
nuget
Microsoft.Azure.Management.ResourceManager.Fluent.Authentication 1.19.0 -> 1.20.0

According to
https://github.com/Azure/azure-sdk-for-net/issues/3238
the deadlock issue was supposed to be solved in Release 1.2

Any help would be appreciated.

**Comment by Neue-Ziel** [comment]
Update:

**Works**
```
azureCredentials = SdkContext
    .AzureCredentialsFactory
    .FromServicePrincipal("GUID", "SECRET", "GUID", AzureEnvironment.AzureChinaCloud);

currentSubscription = Azure
    .Configure()
    .WithLogLevel(HttpLoggingDelegatingHandler.Level.None)
    .Authenticate(azureCredentials)
    .WithDefaultSubscription()
    .GetCurrentSubscription();

```

**Throws same exception**
```
azureCredentials = SdkContext
    .AzureCredentialsFactory
    .FromServicePrincipal(clientId, clientSecret, tenantId, azureEnvironment); // the only different line

currentSubscription = Azure
    .Configure()
    .WithLogLevel(HttpLoggingDelegatingHandler.Level.None)
    .Authenticate(azureCredentials)
    .WithDefaultSubscription()
    .GetCurrentSubscription();
```
where _clientId, clientSecret, tenantId, azureEnvironment_ are member variables.

**Comment by Neue-Ziel** [comment]
Seems to be a problem with
**Microsoft.IdentityModel.Clients.ActiveDirectory.Authenticator**

  | Name | Value | Type
-- | -- | -- | --
◢ | DeclaringMethod | '((System.RuntimeType)((System.Reflection.RuntimeMethodInfo)($exception)._exceptionMethod).DeclaringType).DeclaringMethod' threw an exception of type 'System.InvalidOperationException' | System.Reflection.MethodBase {System.InvalidOperationException}
  | ▶ Data | {System.Collections.ListDictionaryInternal} | System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
  | HResult | -2146233079 | int
  | HelpLink | null | string
  | ▶ IPForWatsonBuckets | 0x72b73ba4 | System.UIntPtr
  | ▶ InnerException | null | System.Exception
  | IsTransient | false | bool
  | Message | "Method may only be called on a Type for which Type.IsGenericParameter is true." | string
  | RemoteStackTrace | null | string
  | Source | "mscorlib" | string
  | StackTrace | "   at System.RuntimeType.get_DeclaringMethod()" | string
  | ▶ TargetSite | {System.Reflection.MethodBase get_DeclaringMethod()} | System.Reflection.MethodBase {System.Reflection.RuntimeMethodInfo}
  | WatsonBuckets | null | object
  | _HResult | -2146233079 | int
  | _className | null | string
  | ▶ _data | {System.Collections.ListDictionaryInternal} | System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
  | _dynamicMethods | null | object
  | ▶ _exceptionMethod | {System.Reflection.MethodBase get_DeclaringMethod()} | System.Reflection.MethodBase {System.Reflection.RuntimeMethodInfo}
  | _exceptionMethodString | null | string
  | _helpURL | null | string
  | ▶ _innerException | null | System.Exception
  | ▶ _ipForWatsonBuckets | 0x72b73ba4 | System.UIntPtr
  | _message | "Method may only be called on a Type for which Type.IsGenericParameter is true." | string
  | _remoteStackIndex | 0 | int
  | _remoteStackTraceString | null | string
  | ▶ _safeSerializationManager | {System.Runtime.Serialization.SafeSerializationManager} | System.Runtime.Serialization.SafeSerializationManager
  | _source | "mscorlib" | string
  | ▶ _stackTrace | {sbyte[24]} | object {sbyte[]}
  | _stackTraceString | null | string
  | _watsonBuckets | null | object
  | _xcode | -532462766 | int
  | ▶ _xptrs | 0x00000000 | System.IntPtr
  | ▶ Static members |   |  
▶ | DeclaringType | null | System.Type
  | DomainInitialized | false | bool
  | ForwardCallBinder | {System.OleAutBinder} | System.OleAutBinder
  | FullName | "Microsoft.IdentityModel.Clients.ActiveDirectory.Authenticator" | string
▶ | GUID | {5fe6a163-fbcf-388e-a7a6-b6c98ae29e7d} | System.Guid
  | GenericCache | null | object
▶ | GenericParameterAttributes | '((System.RuntimeType)((System.Reflection.RuntimeMethodInfo)($exception)._exceptionMethod).DeclaringType).GenericParameterAttributes' threw an exception of type 'System.InvalidOperationException' | System.Reflection.GenericParameterAttributes {System.InvalidOperationException}
▶ | GenericParameterPosition | '((System.RuntimeType)((System.Reflection.RuntimeMethodInfo)($exception)._exceptionMethod).DeclaringType).GenericParameterPosition' threw an exception of type 'System.InvalidOperationException' | int {System.InvalidOperationException}

**Comment by kurtzeborn** [comment]
Issue moved to [Azure/azure-libraries-for-net #627](https://github.com/Azure/azure-libraries-for-net/issues/627) via [**ZenHub**](https://www.zenhub.com/)
