### ISSUE TITLE
[FEATURE REQ] Allow specifying endpoint URL instead of hostname in EventGridClient

### ISSUE THREAD

**Issue by josh-endries** [Azure/azure-sdk-for-net#5566]
**Is your feature request related to a problem? Please describe.**

It seems to be impossible to change the transport, port, path or other parts of event grid submission via EventGridClient. I was attempting to use a local event grid emulator service but can only specify a hostname to the client, so I couldn't change the port number (or path).

**Describe the solution you'd like**

var topicEndpoint = "http://localhost:5000/myTopic"; // or Uri
await egc.PublishEventsAsync(topicEndpoint, eventGridEvents);

**Additional context**

If I want to dev/test an application that uses Event Grid, currently there is no easy way to do so.

This project seems like it would work, which was easy to get up and running:

https://github.com/ravinsp/eventgrid-emulator

However there is no way to specify anything other than hostname to the client, that I've found, so I haven't been able to get it to work, and I don't really want to run something locally as admin with SSL or whatever else might be required by the library...

I was receiving "server refused the connection" errors when trying to use Event Grid recently, both locally and then with a real Azure EG service. The cause was that the app setting contained a URL, not just a hostname (I copied it from the portal). I had forgotten that, unlike most other services, you must supply _only_ the hostname to EventGridClient, not the full endpoint URL. This seems like a strange limitation/abstraction.

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by ahamad-MS** [comment]
@josh-endries Thanks for reporting this issue. It seems you are trying to use EventGrid-Emulator from https://github.com/ravinsp/eventgrid-emulator which is a tool that is not authored, or owned by Azure Event Grid Service team. Please contact the tool author directly for any suggestion on the tool.

Regarding the official usage of .NET SDK for publishing to Azure Event Grid Service in the Cloud, please refer to our publisher sample code here: https://github.com/Azure-Samples/event-grid-dotnet-publish-consume-events/tree/master/EventGridPublisher 

Please let us know if you have specific question about the Azure Event Service official usage. thanks

**Comment by jfggdl** [comment]
@josh-endries, we are going to close this issue, but feel free to reopen it if you have any additional questions. Thanks for reporting this issue.
