### ISSUE TITLE
[FEATURE REQ] API Management: Allow API Revision creation from source 

### ISSUE THREAD

**Issue by alex-zyl** [Azure/azure-sdk-for-net#5568]
Azure portal allows creating new API Revision that copies all settings and operations from the latest available revision by sending SourceApiId
```
PUT https://management.azure.com/subscriptions/SUB_IDresourceGroups/RG_NAME/providers/Microsoft.ApiManagement/service/APIM_SERVICE/apis/API_NAME;rev=5?api-version=2018-06-01-preview
Body:
{"sourceApiId":"/subscriptions/SUB_ID/resourceGroups/RG_NAME/providers/Microsoft.ApiManagement/service/APIM_SERVICE/apis/API_NAME;rev=4"}
```

It would be nice to have similar capability in APIM SDK

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by alex-zyl** [comment]
@kurtzeborn 
Thanks!
It seems that this is the only way to create valid api revision. Revisions created from New-AzureRmApiManagementApiRevision cmd-let messup entire api set.

**Comment by lilyjma** [comment]
hi @alex-zyl, are you still experiencing problem with this?

**Comment by alex-zyl** [comment]
@lilyjma 
I'm good now. 
But, tbh, I don't remember already either this issue was fixed on APIM/sdk side or I'd found a workaround :)
But I think we can close the issue.
