### ISSUE TITLE
Add Static Analysis to CI

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk-for-net#5569]
We need to add static analysis to our build/CI.
Ultimately, this would verify compliance to numerous guidelines, but short term we must ensure that we never ship a client with a constructor that does not take service API version (defaulted to a constant). This is so that API version called does not change when a new version of the client library is used.

**Comment by pakrym** [comment]
Just in case, I've written Roslyn analyzers in the past. This one is easy to implement.

**Comment by pakrym** [comment]
We might want to start the "best client SDK" practices analyzer kit.

**Comment by AlexGhiondea** [comment]
@pakrym I talked with the engineering team and they recommend we create a project in this repo https://github.com/Azure/azure-sdk-tools inside a folder like: `packages\net-packages\<some cool name>`

I was planning to start a small project there to write a very simple analyzer and hook it up to the build -- let me know if you have space cycles and want to start it :).

**Comment by pakrym** [comment]
@AlexGhiondea, unfortunately, that repo is not set up to build/tests .net projects, is it something engineering can help us out with?

**Comment by weshaggard** [comment]
> is it something engineering can help us out with?

Yes we will definitely help set that up as we put stuff into that repo.

**Comment by AlexGhiondea** [comment]
@pakrym we can talk to @weshaggard to see how he would like us to setup the project -- but I hope that hooking up the project to build in that repo won't be very complicated.

**Comment by pakrym** [comment]
Talked to @mikeharder, I'll start with a copy of azure-sdk-for-net pipeline and trim it as required

**Comment by weshaggard** [comment]
@pakrym please include me on the reviews and I'll help guide the pipeline stuff.

**Comment by pakrym** [comment]
I think this is issue can be closed, we'll track adding individual analyzers separately.
