### ISSUE TITLE
ComputerVisionErrorException: Resource not found

### ISSUE THREAD

**Issue by kritdikoon** [Azure/azure-sdk-for-net#5588]
**Query/Question**
I am testing Computer Vision from 7 days free account for trial.
After I put my endpoint +credentils and run describe_image,
I got "Resource not found".

Could anyone advice how to solve this issue? 

python(1)=======================
from azure.cognitiveservices.vision.computervision import ComputerVisionClient
from azure.cognitiveservices.vision.computervision.models import VisualFeatureTypes
from msrest.authentication import CognitiveServicesCredentials

endpoint = "https://westcentralus.api.cognitive.microsoft.com/vision/v1.0"      
key = "XXXXXXXXXXXXXXX"
credentials = CognitiveServicesCredentials(key)
ComputerVisionClient(endpoint, credentials)
output(1)-----------------------------------------
<azure.cognitiveservices.vision.computervision.computer_vision_client.ComputerVisionClient at 0x1a867cbf0f0>

python(2)========================
domain = "landmarks"
url = "http://www.public-domain-photos.com/free-stock-photos-4/travel/san-francisco/golden-gate-bridge-in-san-francisco.jpg"
language = "en"
max_descriptions = 3

analysis = client.describe_image(url, max_descriptions, language)

Output(2)----------------------------------------------------
ComputerVisionErrorException              Traceback (most recent call last)
<ipython-input-67-76270683b1f2> in <module>()
      4 max_descriptions = 3
      5 
----> 6 analysis = client.describe_image(url, max_descriptions, language)
      7 
      8 # for caption in analysis.captions:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\azure\cognitiveservices\vision\computervision\computer_vision_client.py in describe_image(self, url, max_candidates, language, custom_headers, raw, **operation_config)
    243 
    244         if response.status_code not in [200]:
--> 245             raise models.ComputerVisionErrorException(self._deserialize, response)
    246 
    247         deserialized = None

ComputerVisionErrorException: Resource not found

===============================
**Setup :**
 - OS: Windows
 - IDE : Jupyter Notebook
 - Library: azure-cognitiveservices-vision-computervision==0.3.0

**Comment by kritdikoon** [comment]
I found out my mistake.

client = ComputerVisionClient(endpoint, credentials)

**Comment by kurtzeborn** [comment]
Thanks for reaching out on this issue.  Based on your comments it appears this issue should be closed.  Please reopen if I've misunderstood.
