### ISSUE TITLE
Nuget packages not released

### ISSUE THREAD

**Issue by dmaterowski** [Azure/azure-sdk-for-net#5592]
**Describe the bug**
This pull request which fixes broken bot service management has been merged to main branch over 100 days ago:
https://github.com/Azure/azure-sdk-for-net/pull/5056
Since that time Microsoft.Azure.Management.BotService was not released, in fact, the last version is dated to July 2018

Can you do the nuget release for this package?
**To Reproduce**
See https://www.nuget.org/packages/Microsoft.Azure.Management.BotService/

**Setup (please complete the following information):**
n/a

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

CC: @shahabhijeet

**Comment by dmaterowski** [comment]
@kurtzeborn any update on this?

**Comment by cosmaioan** [comment]
Any update on this ? The version from nuget fails from time to time. Reporting an Internal server Error

**Comment by dmaterowski** [comment]
@Kuhnsta  @shahabhijeet @dsgouda 
is it impossible to run a cicd pipeline for a fix coming from community within half of a year?

**Comment by carlosscastro** [comment]
Hi @dmaterowski I'll solve this within the next couple of days.

**Comment by isra-fel** [comment]
0.9.3-preview was published on 5/22/2019
