### ISSUE TITLE
Simplify Pipeline Configuration

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk-for-net#5632]
I would like to consider the following pipeline configuration simplifications:

- [x] Clients should inherit from HttpPipelineOptions and take custom options to their ctors, e.g. ConfigurationClientOptions would be the subclass ConfigurationClient takes. This way when the options type is instantiated, it can be pre-initialized for a specific client without the need to call a factory on the client to pre-initialize the instance. 
- [x] Make DisableTelemetry and ApplicationId to be static (decided not to do)
- [x] Collapse HttpPipelineOptions .AddPolicy methods into one method taking and enum specifying where the policy is added - replaces with lists.
- [x] Move HttpPipelineOptions.Build methods to HttpPipeline. The options type is something people will interact with more than with the pipeline, and people should not be building pipelines often.
- [x] HttpPipelineTransport should not inherit from HttpPipelinePolicy. Currently it allows users to add a transport in the wrong place in the policy chain. Then they will get an exception at runtime, but it would be better to simply avoid this issue altogether.
- [ ] I think we should move all pipeline related APIs that we expect SDK users to use (e.g. policies  they create) to Azure.Base.Pipeline.Policies, all APIs that we expect SDK developers to use to Azure.Base.Pipeline
- [ ] I think we should make concrete policies public

**Comment by pakrym** [comment]
> Make DisableTelemetry and ApplicationId to be static

Should we also add some way to override them in non static way too?

> HttpPipelineTransport should not inherit from HttpPipelinePolicy. Currently it allows users to add a transport in the wrong place in the policy chain. Then they will get an exception at runtime, but it would be better to simply avoid this issue altogether.

How do you call into transport from the last policy then? Do we pass pass transport as an argument of ProcessAsync?

Do we allow modifying options after the pipeline was built?

**Comment by KrzysztofCwalina** [comment]
> Should we also add some way to override them in non static way too?

I am not sure. It seems not super useful to do this on per pipeline. Maybe we should have a concept of process-wide policies.

>How do you call into transport from the last policy then? Do we pass pass transport as an argument of ProcessAsync?

One way to do it is to have a type for the policy chain, instead of using raw ReadOnlyMemory. 

> Do we allow modifying options after the pipeline was built?
This is a hard problem. Since policies can be mutable, it seems like we already cannot prevent some mutations. But it might be worth thinking how to make it less surprising to the users.
