### ISSUE TITLE
Update Unit test to run on .Net461 (Sample4_Logging.cs)

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-for-net#5654]
**Description**
Enabling unit test for data plane/client libraries to run against .Net461 caused various test to break.
Tests have been ignored for net461 to get the repo to build.
The tests involved need to be updated to pass with correct result in net461.

**To Reproduce**
Add net461 to the list of target frameworks in (RepoRoot)/eng/Directory.Build.Data.targets then run unit tests.

```<RequiredTargetFrameworks>netcoreapp2.0;net461</RequiredTargetFrameworks>```

**Expected behavior**
Test will fail or throw an exception (affected code lines has been ignored with #if preprocessor directive) e.g.
```
#if FullNetFx
            Assert.AreEqual(new Version(2, 0), request.Version);
#endif
```
- src/SDKs/Azure.ApplicationModel.Configuration/data-plane/Azure.ApplicationModel.Configuration.Tests/samples/Sample4_Logging.cs

**SetUp**
 - OS: Windows

**Comment by AlexGhiondea** [comment]
This is happening because on .NET Core 2.1 the HttpRequest version was updated to 2.0. In .NET 4.6.1 the version is still 1.1. We should update the code to account for this difference.

@maririos can you take a look?

**Comment by maririos** [comment]
Surge thing
