### ISSUE TITLE
[BUG] Connection And Memory of Azure Function don't down.

### ISSUE THREAD

**Issue by mankyyou** [Azure/azure-sdk-for-net#5686]
After my function run over.My connection and memory always stands still.When I turn off my functions it must be down.

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! Assigning this to @praries880 who has some follow up questions on this bug.

**Comment by isra-fel** [comment]
Hi @mankyyou sorry for late response, Could you provide us more info about your issue? Thank you.

### Used libraries and versions
### Sample code
