### ISSUE TITLE
Azure Search SDK AnalyzerName.AsString.StandardAsciiFoldingLucene not const

### ISSUE THREAD

**Issue by samcook** [Azure/azure-sdk-for-net#5705]
**Query/Question**
In the Azure Search SDK, is there a reason why `AnalyzerName.AsString.StandardAsciiFoldingLucene` is a static readonly string rather than a const string like all the others?

Because it isn't a compile time constant, it can't be used as the name of an analyzer in an `Analyzer` attribute (`[Analyzer(AnalyzerName.AsString.StandardAsciiFoldingLucene)]`)

**Setup (please complete the following information if applicable):**
 - OS: Windows 10
 - IDE : Visual Studio 2019
 - Version of the Library used: `5.0.3`, `7.0.0-preview`
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

CC: @brjohnstmsft @AlexGhiondea

**Comment by brjohnstmsft** [comment]
This is a bug and it will be fixed in the next set of SDK releases, which are expected later in April and early May.

**Comment by brjohnstmsft** [comment]
This has been fixed in the new [Azure Search preview SDK](https://www.nuget.org/packages/Microsoft.Azure.Search/8.0.0-preview). A stable release that includes this fix will be available within a week.
