### ISSUE TITLE
Event grid - Event DomainTopics - allow filter by OData functions

### ISSUE THREAD

**Issue by steverash** [Azure/azure-sdk-for-net#5731]
**Description**
Using Event grid DomainTopics, when calling ListByDomainAsync, I'd like to use the filter parameter to fetch DomainTopics whose Name ends with a certain string.   

Given it seems to be an OData filter, I've used a filter string of "endswith(Name, 'blah')".  However this then fails with :

> Invalid query options: Function 'endswith' is not allowed. To allow it, set the 'AllowedFunctions' property on EnableQueryAttribute or QueryValidationSettings.

**Expected Solution**

I'd like to use the above filter.   

The other option would be to fetch all and filter afterwards in code.  However this seems inefficient. 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Description Added
- [X] Expected solution specified

**Comment by praries880** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by AlexGhiondea** [comment]
@binzywu can you help direct this to the right person who can take a look?

**Comment by ahamad-MS** [comment]
@steverash  Filtering is currently allowed on the Name property only. The supported operations include: CONTAINS, eq (for equal), ne (for not equal), AND, OR and NOT." 

We are marking this as a feature request and will evaluate accordingly. In the meantime, you can use Contains and then filter the remaining ones separately.

**Comment by steverash** [comment]
Thanks, I think the contains will do what we need for now.
