### ISSUE TITLE
[FEATURE REQ] ApiManagement need support for running tests on older Nugets

### ISSUE THREAD

**Issue by solankisamir** [Azure/azure-sdk-for-net#5749]
**Is your feature request related to a problem? Please describe.**
We are from API Management service and we every few months we release a new SDK. We need a hook in the `azure-sdk-for-net` repository for running live tests on older nugets.

**Describe the solution you'd like**
- A job which given our ConnectionString runs all tests on all major nuget releases we have made.
- The job can run each night and provide us with trx files to investigate the issue.

**Describe alternatives you've considered**
Currently, we are doing this by checking out commits of the major release and running tests in them.

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by solankisamir** [comment]
@shahabhijeet  as discussed.

**Comment by allenjzhang** [comment]
Hi, Solankisamir, our team is taking over .NET SDK support and cleaning up older issues. I apologize that your issue has not been responded to as team was going thru transition. Back to your feature request, I suggest you create your own pipeline in OneAzure. You would be able to have flexibility to verify multiple existing nuget packages. If you need any help or questions on setting up the pipelines, feel free to engage our team. Thx
