### ISSUE TITLE
Investigate using C#8 compiler features

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#5752]
There are multiple features we might be interested in:
- Async Enumerable
- Async Disposable
- Nullable reference types

This requires VS2019 and 3.0-x SDK

cc @mikeharder @weshaggard

**Comment by weshaggard** [comment]
I'm supportive of trying to enable this but we need to be sure that we can still run our code/tests on our supported target frameworks which is currently .NET Core 2.1 and .NET Framework 4.6.1.

**Comment by jaredpar** [comment]
C# 8.0 is only officially supported on .NET Core. That being said when the supporting types are available though the features will work on any framework.

**Comment by weshaggard** [comment]
@jaredpar is that only .NET Core 3.0+? Or will they work on .NET Core 2.1 as well?

**Comment by cartermp** [comment]
@weshaggard .NET Core 3.0+. If you have the correct type shapes then code will compile and run, but that would be considered unsupported/use-at-you-own-risk.

**Comment by pakrym** [comment]
@jaredpar what about nullability annotations in netstandard libraries?

**Comment by weshaggard** [comment]
I will be moving the .NET Core toolset to 3.0 preview 5 after that then we can start using the bridget pack for the new features.

**Comment by jaredpar** [comment]
Awesome

**Comment by weshaggard** [comment]
The toolset update has been merged with https://github.com/Azure/azure-sdk-for-net/pull/6130. @pakrym  please feel free to try out the new C# 8 features.
