### ISSUE TITLE
Azure C# API to fetch EA billing usage?

### ISSUE THREAD

**Issue by indumathymk** [Azure/azure-sdk-for-net#5765]
Is there any API SDK available in **C#  to fetch EA account cost and usage.**

_Am tried in Python using below namespace,
from azure.mgmt.commerce import UsageManagementClient
from azure.mgmt.consumption import ConsumptionManagementClient
from azure.mgmt.commerce.models import MeterInfo,ResourceRateCardInfo_

similar to that tried in c# is  not avail.

Please do some  favour?

**Comment by praries880** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

CC: @shahabhijeet

**Comment by isra-fel** [comment]
Sorry for late response. Billing team could you help share some insights, thank you!

**Comment by anand-rengasamy** [comment]
Usage is owned by cost management team. Looping the right owners.

**Comment by isra-fel** [comment]
Thank you @anand-rengasamy :)

**Comment by ms-premp** [comment]
@indumathymk  please check these links

https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.consumption?view=azure-dotnet

https://github.com/Azure-Samples/billing-dotnet-ratecard-api/tree/master/ConsoleApp-Billing-RateCard

https://github.com/Azure-Samples/billing-dotnet-usage-api/tree/master/ConsoleApp-Billing-Usage

**Comment by ramaganesan-rg** [comment]
Closing as per comments from Prem
