### ISSUE TITLE
Update Unit test to run on .Net461 (MessageInteropEnd2EndTests.cs)

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-for-net#5774]
**Description**
Enabling unit test for data plane/client libraries to run against .Net461 causes ```MessageInteropEnd2EndTests``` test to break due to ```WithQueueAsync``` not being implemented.
File has been removed from build at ```Microsoft.Azure.ServiceBus.Tests.csproj```.
```WithQueueAsync``` should be implemented.

**To Reproduce**
Add net461 to the list of target frameworks in (RepoRoot)/eng/Directory.Build.Data.targets then run unit tests.

```<RequiredTargetFrameworks>netcoreapp2.0;net461</RequiredTargetFrameworks>```

**Expected behavior**
Test will fail or throw an exception, (Cannot find the Method ```WithQueueAsync```)

-  src\SDKs\ServiceBus\data-plane\tests\Microsoft.Azure.ServiceBus.Tests\MessageInterop\MessageInteropEnd2EndTests.cs (Removed From Build)

**SetUp**
 - OS: Windows

**Comment by jsquire** [comment]
@chidozieononiwu:  I think there is something larger going on here;  `WithQueueAsync` exists and was not recently added (most other tests depend on it as well, on the .NET Core and Full Net FX builds.    In addition, the set of tests that were removed compiles and passes running under the full framework from within Visual Studio.     

Happy to chat, if it's helpful.

(see:  [ServiceBusScope](https://github.com/Azure/azure-sdk-for-net/blob/master/src/SDKs/ServiceBus/data-plane/tests/Microsoft.Azure.ServiceBus.Tests/Infrastructure/ServiceBusScope.cs))
