### ISSUE TITLE
Seperate test reporting of .Net Framework from that of .Net Core

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-for-net#5776]
**Description.**
We need to be able to differentiate test results for .Net framework from that of .Net Core on the DevOps Pipeline

**Solution**
Update the test result reporting so that we can see the test results for .NET Core separate from those of .Net Framework

**Comment by weshaggard** [comment]
On top of the reporting concerns we should also split this to help runtime performance by enabling parallel test runs for .NET Core and .NET Framework.

**Comment by chidozieononiwu** [comment]
Fixed by #6842
