### ISSUE TITLE
Please enable "soft delete" parameter in Azure key vault by default

### ISSUE THREAD

**Issue by gesada** [Azure/azure-sdk-for-net#5797]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [ ] Expected solution specified

**Comment by gesada** [comment]
Hello,
Currently, Azure has soft-delete is not enabled by default
https://docs.microsoft.com/en-gb/azure/key-vault/key-vault-ovw-soft-delete
I would like to please request for this to be enabled globally and to be default.
Many thanks,
George Sadathian
Microsoft PFE
v-gesada@microsoft.com

**Comment by praries880** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by AlexGhiondea** [comment]
@RandalliLama can you take a look a this?

**Comment by heaths** [comment]
Programmatically and in the portal, this is now the default. The Az CLI and PowerShell module changes are coming soon.
