### ISSUE TITLE
Update Storage tests to prep for repo move

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#5799]
Make it possible to inject testing configuration from the environment, prevent tests without access to a live service from failing, make the build work on a fresh sync, and stabilize flaky tests

**Comment by blueww** [comment]
@tg-msft

I owns the SRP .net SDK. I see you have filed 9 issues with "Storage" label and assigned to yourself.
Are they for SRP .net SDK? I think the test for SRP .net SDK already can run without access to live service now, and the build (include test) should can pass on a fresh sync.

Feel free to contact me if you need any support from me.

**Comment by tg-msft** [comment]
Thanks for checking in @blueww.  These issues are all for the next version of the data-plane .NET client libraries.

**Comment by tg-msft** [comment]
Merged in other repo
