### ISSUE TITLE
[QUERY] Project setup questions for new RP

### ISSUE THREAD

**Issue by feiyushi** [Azure/azure-sdk-for-net#5821]
**Query/Question**
I'm setting up a new SDK for ImageBuilder RP. Swagger: [link](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/imagebuilder/resource-manager)
I'm following README to set up a new SDK folder and generate c# code, however I'm hitting two problems. My fork and branch: [link](https://github.com/feiyushi/azure-sdk-for-net/tree/image-builder-sdk-for-net). Please help. Thanks.

1. Unable to generate code using ./generate.ps1. I run the command for other RP (like Compute) and no problem with that, but with out RP, I got this error (see below). Later I found out this error is thrown by autorest, confirmed by running `cmd.exe /c autorest.cmd https://github.com/Azure/azure-rest-api-specs/blob/master/specification/imagebuilder/resource-manager/readme.md --csharp --version=latest --reflect-api-versions --csharp-sdks-folder=F:\azure-sdk-for-net\src\SDKs` alone. I had to circumvent this issue by cloning the swagger to local and serve it to autorest.

"
AutoRest installed successfully.
Commencing code generation
Generating CSharp code
Executing AutoRest command
cmd.exe /c autorest.cmd https://github.com/Azure/azure-rest-api-specs/blob/master/specification/imagebuilder/resource-manager/readme.md --csharp --version=latest --reflect-api-versions --csharp-sdks-folder=F:\azure-sdk-for-net\src\SDKs
AutoRest code generation utility [version: 2.0.4283; node: v10.15.3]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\user\.autorest\@microsoft.azure_autorest-core@2.0.4302\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4302)
   Loading AutoRest extension '@microsoft.azure/autorest.csharp' (~2.3.79->2.3.82)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.55->2.3.55)

Write-ErrorLog :   **Error: Cannot write data to 'https://github.com/Azure/azure-rest-api-specs/blob/master/specification/imagebuilder/resource-manager/generated/ImageBuilderClient.cs'. Protocol 'https:' not supported for writing. Make sure to specify a local, absolute
path as target file/folder.**
At C:\Users\user\Documents\WindowsPowerShell\Modules\CodeGenerationModules\AutoRestCodeGenerationModule\AutoRestCodeGenerationModule.psm1:96 char:5
"

2. After I have the proj file ready I cannot build it. Similar to this issue #5038. Sadly I don't see any solution there. Error:

"
F:\azure-sdk-for-net\tools\SdkBuildTools\targets\ideCmd.targets(20,3): error MSB4018: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Azure.Management.ImageBuilder, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf385
6ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A) [F:\azure-sdk-for-net\src\SDKs\ImageBuilder\Management.ImageBuilder\Microsoft.Azure.Management.ImageBuilder.csproj]
F:\azure-sdk-for-net\tools\SdkBuildTools\targets\ideCmd.targets(20,3): error MSB4018: File name: 'Microsoft.Azure.Management.ImageBuilder, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' ---> **System.Security.SecurityException:
 Strong name validation failed.** (Exception from HRESULT: 0x8013141A) [F:\azure-sdk-for-net\src\SDKs\ImageBuilder\Management.ImageBuilder\Microsoft.Azure.Management.ImageBuilder.csproj]
"

***Why is this not a Bug or a feature Request?***
I think I need help with the setup. If anything not documented discovered later, we could update README.

**Setup (please complete the following information if applicable):**
 - OS: Windows
 - IDE : VS2017
 - Version of the Library used: AutoRest code generation utility [version: 2.0.4283; node: v10.15.3]
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by kurtzeborn** [comment]
CC: @shahabhijeet

**Comment by isra-fel** [comment]
Hi Feiyu, we are sorry for late response. As for the autorest issue, please add `-SdkGenerationDirectory "$PSScriptRoot\Generated"` in your generate.ps1; or equivently, specify a `--csharp.output-folder=C:\sdk` option to autorest.cmd.

If you have other questions concerning C# management plane SDK, please contact azdevxdotnet "at" microsoft.com . Thank you :)

**Comment by feiyushi** [comment]
thank you! it worked.
