### ISSUE TITLE
Default Setting Selector

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#5826]
Do we really need it? => https://github.com/Azure/azure-sdk-for-net/blob/master/src/SDKs/Azure.ApplicationModel.Configuration/data-plane/Azure.ApplicationModel.Configuration/SettingSelector.cs#L34

**Comment by maririos** [comment]
Currently we have:
```c#
        public SettingSelector() : this(Any, Any) { }

        public SettingSelector(string key, string label = default)
        {
            Keys = new List<string>();
            Keys.Add(key ?? Any);

            Labels = new List<string>();
            if (label != null) Labels.Add(label);
        }
```

The purpose of the `SettingSelector` is to bring a set of settings that will match what the user is looking for. It will be rare when a user wants to query the whole Configuration Store.
In that case, a key and or label will always be required. It could be one or more.

So what about changing it to something like this?

```c#
        public SettingSelector(string key, string label)
        {
            Keys = new List<string>();
            Keys.Add(key ?? Any);

            Labels = new List<string>();
            Labels.Add(label ?? Any);
        }

        public SettingSelector(List<string> keys, List<string> labels)
        {
            Keys = new List<string>(Keys);
            Labels = new List<string>(Labels);
        }
```

**Comment by maririos** [comment]
@pakrym @KrzysztofCwalina

**Comment by pakrym** [comment]
Does it benefit us to remove the default ctor? Only things it does is make it harder for customers to call `GetBatch` especially when they don't care about key/label filtering.

**Comment by maririos** [comment]
I am speaking hypothetically here as we don't have backing data... but if 
> they don't care about key/label filtering.

then the idea is to bring everything that is the Configuration Store. How often will that happen? Will this be the API to do that?

When I think about `GetBatch` it is more like I want to query something specific and therefore I need to specify either key or label.

Again, all of this is hypothetical. I am good either way.

**Comment by maririos** [comment]
There isn't much traction on whether to change this or not so closing for now
