### ISSUE TITLE
[BUG] Invalid API version when deleting snapshots

### ISSUE THREAD

**Issue by bmunsen** [Azure/azure-sdk-for-net#5827]
Using the latest version of the Microsoft.Azure.Management.Compute SDK (v25.0.0) I am running into an API version error when attempting to delete a managed disk snapshot using any of the delete methods on the SnapshotOperations and SnapshotOperationsExtensions classes.

When attempting to use these methods, a REST call is made that resembles the following:

DELETE /subscriptions/.../providers/Microsoft.Compute/snapshots/<snapshotname>?api-version=2018-09-30 HTTP/1.1

That REST call results in the following error being returned:

The api-version '2018-09-30' is invalid. The supported versions are '2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.

From what I can see in the source code, it is hard-coded to specify this API version, yet the API backend is rejecting this version string.  I am in need of the ability to create and delete snapshots in an automated fashion, so I would appreciate a fix on this ASAP.

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

CC: @shahabhijeet

**Comment by isra-fel** [comment]
Sorry for late response! The latest compute SDK is using `2019-11-01` for snapshot operations. Could you try it? Thank you!
