### ISSUE TITLE
AzureServiceTokenProvider and MsiAccessTokenProvider supporting AAD Pod Identity in AKS

### ISSUE THREAD

**Issue by tehho** [Azure/azure-sdk-for-net#5841]
**Is your feature request related to a problem? Please describe.**
Yes.
The native tutorial on https://github.com/Azure/aad-pod-identity does not work out of the box with 
AzureServiceTokenProvider and MsiAccessTokenProvider.
curl http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://management.azure.com -H "podname: nginx-flex-kv-int" -H "podns: default" does work

**Describe the solution you'd like**
Add support for Pod name and Pod namespace headers in the MsiAccessTokenProvider.
Ether with environmentvariables or some other smart solutions.
This would be the same as 

`
if (isAppServicesMsiAvailable)
{
    request.Headers.Add("Secret", msiSecret);
}
else
{
    request.Headers.Add("Metadata", "true");
}
`
on lines 65 to 72

**Describe alternatives you've considered**
Fix MSI for pods running in AKS without the AAD-pod-identity just work nativeli :D

**Additional context**
Running on AKS 1.12.6 with nmi daemonset and mic deployment (1 pod). 
Can see the request come in and not work.
Works flawlessly with above curl

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Description Added
- [X] Expected solution specified

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by TomGeske** [comment]
Is this one still active? It should work by now ...

cc: @aramase
