### ISSUE TITLE
[BUG] Azure Key Vault References feature doesn't appear to work with Configuration.GetConnectionString(stringName)

### ISSUE THREAD

**Issue by AlphaCreative** [Azure/azure-sdk-for-net#5847]
**Describe the bug**

We are testing out the new Azure Key Vault references feature and the promise of no code changes required to host our configuration/secrets in Key Vault.  Looks like Configuration.GetSection("SectionName").Bind(bindObj) is working fine with key vault references but our existing code that makes a call to Configuration.GetConnectionString("connectionStringName") to get the connection string out of appsettings.json is now returning null when using key vault references.  If we make a call to Configuration.GetSection("ConnectionStrings").Value we get only the reference to the key vault not the value so "@Microsoft.KeyVault(SecretUri=https://my-key-vault.vault.azure.net/secrets/ConnectionStrings/5f59dcbc017049f1b949f4a5b3cfe2f2)"  is returned.

How is this feature supposed to work with ConnectionString settings?  Since that is one of the most obvious things you would want to store in Key Vault it seems like this should work, happy to find out we just aren't doing something correctly.  We have verified the URL and version number of the key in keyvault so we know that is valid.  All other key vault references are working fine.

**To Reproduce**
1.  Set up Azure Web Site using Key Vault References and system managed identity per [https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references](url)
2.  Add a ConnectionStrings setting to your appsettings.json and a key vault reference that points to an azure secret that contains the body of the connectionstrings section that has a couple of connection strings in it as follows:
`{ "ConnString1": "Server=mydb.database.windows.net;Database=mydb;User ID=myuser;Password=password;MultipleActiveResultSets=true", 
"ConnString2": "Server=mydb.database.windows.net;Database=mydb2;User ID=myuser2;Password=password;MultipleActiveResultSets=true", 
"ConnString3": "Server=mydb.database.windows.net;Database=mydb3;User ID=myuser3;Password=password!;MultipleActiveResultSets=true" }`
3.  In Startup.cs make a call to Configuration.GetConnectionString("ConnString1") and verify that it returns null

***Code Snippet***
`string connString = Configuration.GetConnectionString("ConnectionStringName");
//connString is always null when using Azure Key Vault References

string connSection = Configuration.GetSection("ConnectionStrings").Value;
//connSection just contains the key vault reference not the actual value of the secret
`

**Expected behavior**
connection string to be returned from Configuration.GetConnectionString("ConnectionStringName") when using Azure Key Vault References just like it is when stored in appsettings.json

**Setup (please complete the following information):**
 - OS: Azure Key Vault and Azure App Service (web site)
 - IDE : Visual Studio 2017

**Comment by AlphaCreative** [comment]
Discovered the issue was larger than just GetConnectionString.  Closing for now will reopen once I have more details

**Comment by adetayorabiu** [comment]
@AlphaCreativeDev Did you figure this out? I'm currently having the same issue in my app. I retrieving the secret using IConfiguration.GetConnectionString and it returns the raw key vault secret url instead of the secret value
