### ISSUE TITLE
ConnectionString ...  is not valid. Must contain 'RunAs' attribute and it must not be empty.

### ISSUE THREAD

**Issue by parthsha** [Azure/azure-sdk-for-net#5866]
**Query/Question**
I am trying out AzureServiceTokenProvider to fetch access token in a simple .NET console app. I built my project in Visual Studio and then opened command prompt where I created an environment variable via the following command:
set AzureServicesAuthConnectionString="RunAs=App;AppId={AppId};TenantId={TenantId};AppKey={ClientSecret}" with the correct values for AppId, TenantId and ClientSecret substituted. 

When I run the console app, I get the following error but I am not sure why. (I have hidden AppId, TenantId, and ClientSecret from the exception stack trace below.) Clearly, it can read the value of my environment variable. The environment variable does contain RunAs attribute, so why is it complaining that this attribute is missing? What am I doing wrong?

Unhandled Exception: System.ArgumentException: Connection string "RunAs=App;AppId=(my App Id);TenantId=(my Tenant Id);AppKey=(my Client Secret)" is not valid. Must contain 'RunAs' attribute and it must not be empty.
   at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderFactory.ValidateAttribute(Dictionary`2 connectionSettings, String attribute, String connectionString)
   at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderFactory.Create(String connectionString, String azureAdInstance)
   at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider..ctor(String connectionString, String azureAdInstance)
   at FetchToken.Program.Main(String[] args) in (path)\Program.cs:line 14

***Why is this not a Bug or a feature Request?***
I am trying this library out for the first time, so I am not sure if there is something missing in my code?

**Setup (please complete the following information if applicable):**
 - OS: Windows 10
 - IDE : Visual Studio 2017
 - Version of the Library used: 1.0.3

**Comment by varunsh-msft** [comment]
Can you please remove the double quotes from the connection string? thanks!

**Comment by parthsha** [comment]
Yikes, that's what I was doing wrong. I thought without the quotes, bash might break on ; or = operators, but they didn't. Thank you for your help!
