### ISSUE TITLE
Migrate tests to netcoreapp2.1

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#5886]
.net core 2.0 is out-of-support and we should run tests on .net core 2.1 that's LTS

@weshaggard

**Comment by weshaggard** [comment]
Agreed. See https://github.com/dotnet/core/blob/master/microsoft-support.md for the support matrix.

**Comment by weshaggard** [comment]
Fixed with https://github.com/Azure/azure-sdk-for-net/pull/6247
