### ISSUE TITLE
[Engineering System] Support for UWP Builds

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#5908]
# Summary

Due to the technique used by its dependencies to mask platform differences, the Event Hubs client library makes use of the `uap10.0` target framework.   Despite attempts to revise the approach during migration to the central SDK repository, it has been determined that the need for `uap10.0` continues to exist.

# Scope of Work

- Design an approach to allow .NET client library builds to target `uap10.0` while continuing to support the current set of target frameworks (`net641`, `netstandard2.0`, `netstandard1.4`) used by Event Hubs and other client libraries.

- Integrate support into the central engineering pipeline for `uap10.0` support.

- Update the engineers working on Event Hubs .NET client library migration on the design and how to leverage it, using Jesse Squire and Alex Ghiondea as the points of contact.

# Out of Scope

- Adding support for other target platforms.

- Integrating the new pipeline support into interested client library projects; this remains the responsibility of engineers working on the individual client libraries.

# Success Criteria

The .NET client library build system contains support for the `uap1.0` target continuing to support the existing set of target frameworks centered on .NET Standard and the full .NET Framework.

**Comment by weshaggard** [comment]
I want to take a look and see if we can get away with using the NS1.4 binary in the uap10 folder instead of enabling uap builds in our engineering system.
