### ISSUE TITLE
Bringing Service Bus code base WITH history

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-sdk-for-net#5921]
**Query/Question**

The original repository for the Service Bus .NET Standard client was copied w/o git history, eliminating any ability to go back in history to review changes.

Example:
History for the [`ClientEntity`](https://github.com/Azure/azure-sdk-for-net/commits/master/src/SDKs/ServiceBus/data-plane/src/Microsoft.Azure.ServiceBus/ClientEntity.cs) vs the original [file](https://github.com/Azure/azure-service-bus-dotnet/commits/dev/src/Microsoft.Azure.ServiceBus/ClientEntity.cs).

There are [ways](https://stackoverflow.com/a/17373088/59563) to merge histories and it would be appreciated if the history of the original repository would not be eliminated. 

Related issues: #5872

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by SeanFeldman** [comment]
Closed via https://github.com/Azure/azure-sdk-for-net/issues/5872#issuecomment-486667922
