### ISSUE TITLE
Azure.Core API Cleanup

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk-for-net#5922]
I took a look at the most recent Azure.Core and here are some API cleanup suggestions:

- [x] HttpPipelineUrlBuilder shoiuld be moved to Azure.Core namespace. The root namespace should contain types that are used by SDK users. Azure.Core is for people implementing SDK clients. The exception to the rule is probably Request, as it needs to be in the same namespace as response (for parity).
- [ ]  HttpPipelineUrlBuilder: would the two append methods be better as extensions on UriBuilder?
- [ ] Why is UriBuilder a property of the Request? If we want it to simply be a mutable URL, maybe we should just call it Url (the type and property)
- [ ] Might be better to move AzureSdkClientLibraryAttribute to Azure.Core namespace. I don't think it's worth having a namespace for one type.
- [ ] I think HttpHeader should be in Azure.Core namespace. Some APIs there use it.
- [ ] Why do we need HttpPipelineMethodConverter to be public?

**Comment by pakrym** [comment]
> HttpPipelineUrlBuilder shoiuld be moved to Azure.Core namespace. The root namespace should contain types that are used by SDK users. Azure.Core is for people implementing SDK clients. The exception to the rule is probably Request, as it needs to be in the same namespace as response (for parity).

Will do.

> HttpPipelineUrlBuilder: would the two append methods be better as extensions on UriBuilder?

No, having a type allows us to optimize string allocations a lot, extension methods do not allow us to do the same.

> Why is UriBuilder a property of the Request? If we want it to simply be a mutable URL, maybe we should just call it Url (the type and property)

I don't have a strong opinion about this but Url feels like a very generic type name to take especially considering almost no one has to instantiate it.

> Might be better to move AzureSdkClientLibraryAttribute to Azure.Core namespace. I don't think it's worth having a namespace for one type.

Will do

> I think HttpHeader should be in Azure.Core namespace. Some APIs there use it.

SDK users might use it too, it's very similar to Request/Response.

> Why do we need HttpPipelineMethodConverter to be public?

Used in AppConfig auth policy.

**Comment by pakrym** [comment]
@KrzysztofCwalina ping
