### ISSUE TITLE
[BUG] Updating NotificationHub GCM/FCM Credentials

### ISSUE THREAD

**Issue by iganderson** [Azure/azure-sdk-for-net#5925]
**Describe the bug**
When using NotificationHubsManagementClient.NotificationHubs.CreateOrUpdate() to change the GCM/FCM credentials for a Notification Hub, the credentials do not change.

**To Reproduce**

1. Create a new notification hub, assigning it a GCM/FCM key.
2. Use NotificationHubsManagementClient.NotificationHubs.CreateOrUpdate() to update the hub with a new GCM/FCM key.

***Code Snippet***

    using Microsoft.Azure.Management.NotificationHubs;
    using Microsoft.Azure.Management.NotificationHubs.Models;
    using Microsoft.IdentityModel.Clients.ActiveDirectory;
    using Microsoft.Rest;

    namespace AzureTesting
    {
      internal class NotificationHubtTest
      {
        const string SUBSCRIPTION_ID = "My Subscription ID";

        const string RESOURCE_GROUP = "Default-NotificationHubs-CentralUS";
        const string HUB_NAME = "DefaultHub";
        const string HUB_LOCATION = "Central US";

        // These constants are required for authenticating my app in the Azure AD.
        const string TENANT_ID = "My Tenant ID";
        const string CLIENT_ID = "My Client ID";
        const string CLIENT_SECRET = "My Client Secret";

        public void Test()
        {
          string namespaceName = "MyNotificationHubNamespace";

          // Create a new notification hub for my notification hub namespace.
          CreateOrUpdateHub(namespaceName, "My First Key");

          // Wait a little bit to ensure the hub is created.
          // (Not normally how I would do this, but this is for demonstration purposes.)
          System.Threading.Thread.Sleep(10000);

          // If I look at the new hub on portal.azure.com, it has the correct GCM/FCM key assigned.

          // Now update the hub with a new GCM/FCM key.
          CreateOrUpdateHub(namespaceName, "My Second Key");

          // When check on the hub at this point on portal.azure.com, it still has
          // the old GCM/FCM key ("My First Key") and not the new one ("My Second Key").
        }

        private NotificationHubResource CreateOrUpdateHub(string namespaceName, string gcmKey)
        {
          var parameters = new NotificationHubCreateOrUpdateParameters()
          {
            NotificationHubCreateOrUpdateParametersName = HUB_NAME,
            Location = HUB_LOCATION,
            GcmCredential = new GcmCredential(null, gcmKey)
          };

          using (var client = CreateClient())
          {
            var hub = client.NotificationHubs.CreateOrUpdate(RESOURCE_GROUP, namespaceName, HUB_NAME, parameters);
            return hub;
          }
        }

        private NotificationHubsManagementClient CreateClient()
        {
          var credentials = GetClientCredentials(TENANT_ID, CLIENT_ID, CLIENT_SECRET);
          var client = new NotificationHubsManagementClient(credentials);
          client.SubscriptionId = SUBSCRIPTION_ID;
          return client;
        }

        private TokenCredentials GetClientCredentials(string tenantID, string clientID, string clientSecret)
        {
          var context = new AuthenticationContext($"https://login.microsoftonline.com/{tenantID}");
          var result = context.AcquireTokenAsync("https://management.core.windows.net/", new ClientCredential(clientID, clientSecret)).Result;
          var credentials = new TokenCredentials(result.AccessToken);

          return credentials;
        }
      }
    }

**Expected behavior**
The GCM/FCM credentials should change to reflect what was set in the NotificationHubCreateOrUpdateParameters class.

**Setup (please complete the following information):**
 - OS: Windows 10 Pro (Build 17763)
 - IDE : Visual Studio Professional 2017 
 - Microsoft.Azure.Management.NotificationHubs v2.3.2 (preview)
 - .NET Framework: 4.7.2
 - Language: C#

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by isra-fel** [comment]
Sorry for late response; Thejaswini could you share some insights on this, thanks?

**Comment by stankovski** [comment]
Closing due to no repro
