### ISSUE TITLE
[FEATURE REQ]AppAuthentication should be able to refresh tokens independently of retrieving tokens

### ISSUE THREAD

**Issue by chrisamert** [Azure/azure-sdk-for-net#5930]
**Is your feature request related to a problem? Please describe.**
We are planning to use the Managed Identity to access things like SQL and Storage from our web application, and we’d like to prevent user requests having to pay the tax of acquiring a new token. We'd like the ability to ensure the value in the cache is valid when we retrieve it

**Describe the solution you'd like**
A couple options that I've thought about

* Have a method we can call to force refresh all the values in the cache.  We can then call this from a background task in our code on some set schedule
* The AppAuthentication library itself has a background task running to retrieve new tokens on some configurable schedule

**Describe alternatives you've considered**
No alternatives at the moment

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Description Added
- [X] Expected solution specified

**Comment by Petermarcu** [comment]
@henrik-me is this an MSAL feature request? cc/ @schaabs

**Comment by henrik-me** [comment]
Disclaimer: Functionality like this should be used with careful consideration to protect from calling the STS too frequently. Ideally the optimal user experience should be taken into account but measures should also be taken to not make calls that are not needed (telemetry on application usage should be able to find the optimal balance).

@chrisamert : I'm assuming we are talking Confidential Client scenarios, thus scenarios where you use a secret or a certificate to authenticate?

@chrisamert : Can you pls. point me to the what you mean by AppAuthentication library? I believe I know however in my mind we have a few things which are regularly referenced as AppAuthentication.

@Petermarcu @schaabs : For ConfidentialClient, MSAL can do something to help more than what it does today. MSAL doesn't have access to the secret/certificate and thus can't perform this operation with-out being handed this information and as a consequence this functionality has to be triggered by the one in possession of the secret/certificate. MSAL will renew the token if there are 5 minutes or less to the expiry when called. This functionality can be triggered on a background process by the hosting application.

Aside: For scenarios where there is a refresh token available in the cache recommendation on a similar scenario is described under [Pro-Active Token renewal](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/High-availability#pro-active-token-renewal). 
We don't expose a method to do this for everything in the cache, however we leave it to the applications and background processes to do this renewal based on their criteria's (we know some services does this). 

Disclaimers aside, I would like to explore if we can provide a similar to what AppAuthentication does, some parts of the functionality might live in the Azure SDK's and other parts in MSAL.

Opened https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1763 for tracking.

**Comment by Petermarcu** [comment]
Thanks @henrik-me . Lets use your issue to track progress on this. I'll close this issue here...

**Comment by henrik-me** [comment]
@Petermarcu : more than likely there will be work on consumers for this and this has to be exposed in the Azure SDK's as well. I think those items goes hand in hand. Also ATM, this is not something we are prioritizing, however there are workarounds if using MSAL directly, not sure if it makes sense for Azure SDK's to expose some of that functionality.
