### ISSUE TITLE
[Service Bus Client] Rename test environment variable

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-net#5949]
For consistency, @jsquire and I agreed to use the environment variable `SERVICE_BUS_CONNECTION_STRING` for all Service Bus tests in all languages.  In this repo, the variable should be renamed from `AZ_SERVICE_BUS_CONNECTION` to `SERVICE_BUS_CONNECTION_STRING`.

Related: https://github.com/Azure/azure-sdk-for-js/issues/2471

**Comment by AlexGhiondea** [comment]
@jsquire is there still work to be done here?

**Comment by jsquire** [comment]
Apologies; I didn't realize that this was here.   I made this change under  [#2471](https://github.com/Azure/azure-sdk-for-net/issues/2471) and it was included in [PR #5954](https://github.com/Azure/azure-sdk-for-net/pull/5954).    

Closing this out.
