### ISSUE TITLE
[Service Bus Client] Perf test should dynamically create queue

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-net#5950]
The Service Bus perf test (added in https://github.com/Azure/azure-sdk-for-net/pull/5932) should be updated to dynamically create and delete the queue used for testing, similar to the functional tests.

@jsquire 

Related: https://github.com/Azure/azure-sdk-for-js/issues/2472

**Comment by JoshLove-msft** [comment]
The perf tests and live tests dynamically create resources.
