### ISSUE TITLE
[QUERY] repositories in container registries

### ISSUE THREAD

**Issue by PejmanNik** [Azure/azure-sdk-for-net#5964]
**Query/Question**
How I can get repositories in container registries with images data like tags and manifests?

***Why is this not a Bug or a feature Request?***
It can be done by PowerShell and API but can't do in SDK

**Setup (please complete the following information if applicable):**
 - OS: Win 10
 - IDE : VS
 - Version of the Library used: latest
 
 **Information Checklist**
 I can get IRegistry but there no way to get repositories  from there

**Comment by sajayantony** [comment]
@estebanreyl could you please update this issue with the pointer to your PR which would enable this in the SDK.

**Comment by estebanreyl** [comment]
We are currently working to get through all of those issues and have an ongoing PR in the Azure rest api spec repository from where the acr sdk is autogenerated. You can find that here: https://github.com/Azure/azure-rest-api-specs/pull/6629 . Once that PR goes through we can generate the a new fully functioning api that supports tag and manifest acquisition among other things.

**Comment by xiadu94** [comment]
@PejmanNik, just check in. Seems @estebanreyl 's PR is merged, can you verify has your issue been resolved yet?

**Comment by PejmanNik** [comment]
Yes, @xiadu94 . Thank you
