### ISSUE TITLE
[BUG]Code in MemoryApplicationAuthenticationProvider.cs to fetch the token does not use ConfigureAwait(false) to avoid deadlock

### ISSUE THREAD

**Issue by rahuldutta90** [Azure/azure-sdk-for-net#5967]
**Describe the bug**
Code in MemoryApplicationAuthenticationProvider.cs to fetch the token does not use ConfigureAwait(false)
https://github.com/Azure/azure-sdk-for-net/blob/750900fc1150ec03d33b42e9e2591c892d87a694/src/SdkCommon/Auth/Az.Auth/Az.Authentication/MemoryApplicationAuthenticationProvider.cs#L60 

Customer was using ADLS SDK from IIS web api. They were calling non-async methods of ADLS SDK. Internal to the ADLS SDK we call the api on ServiceClientCredential to get token and it was getting stuck there. It was not retruning from there. And the reason is probably because the continuation and the waiting due to "GetAwaiter().GEtResult()" is trying to be executed by the same thread.

This type of deadlock is special to web apis/UI not console type apps.

***Exception or Stack Trace***
It is a deadlock issue. 

**To Reproduce**
This issue can be reproduced if ServiceClientCredential.ProcessHttpRequestAsync().GetAwaiter().GetResult() is called from IIS webapi or UI. 
https://danielwertheim.se/do-i-need-to-use-configureawait-false-all-the-way/ 
https://medium.com/bynder-tech/c-why-you-should-use-configureawait-false-in-your-library-code-d7837dce3d7f

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
Deadlock should not be caused

**Screenshots**

**Setup (please complete the following information):**
 - Customer used their iis project
 - Version of the Library used - Current

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by kurtzeborn** [comment]
CC: @shahabhijeet
