### ISSUE TITLE
[BUG] Calls to AzureServiceTokenProvider.GetAccessTokenAsync fail when the thread culture is not en-US

### ISSUE THREAD

**Issue by SaltyDH** [Azure/azure-sdk-for-net#5976]
**Describe the bug**
When attempting to call AzureServiceTokenProvider.GetAccessTokenAsync() an AzureServiceTokenProviderException is thrown because: Tried to get token using Managed Service Identity. Access token could not be acquired. String '4/29/2019 9:55:41 AM +00:00' was not recognized as a valid DateTime.

Whilst the underlying exception is lost because the exception is caught and thrown as a AzureServiceTokenProviderException, I believe the underlying cause is that the call to DateTimeOffset.Parse (line 59 of Azure.Services.AppAuthentication/AppAuthenticationResult.cs) is using the current thread culture however the dates in the TokenResponse are always in en-US format.

In my specific case, the current thread culture is set to en-AU when the call to AzureServiceTokenProvider.GetAccessTokenAsync() is made. The call is made from an Azure App Service configured with a User Managed Identity.

***Exception or Stack Trace***
Parameters: Connection String: RunAs=App;AppId=<appIdRemoved>, Resource: https://management.azure.com/, Authority: . Exception Message: Tried to get token using Managed Service Identity. Access token could not be acquired. String '4/29/2019 9:55:41 AM +00:00' was not recognized as a valid DateTime.
StackTrace:   at async Task<AppAuthenticationResult> Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider.GetAuthResultAsyncImpl(string authority, string resource, string scope)
   at async Task<AppAuthenticationResult> Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider.GetAuthenticationResultAsync(string resource, string tenantId)
   at async Task<string> Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider.GetAccessTokenAsync(string resource, string tenantId)

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added

**Comment by praries880** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by adibraniste** [comment]
Hi,

I am having the same issue - received token field "expires_on":"6/25/2019 2:18:56 PM +00:00" with the calling assembly using en-GB is failing.
Is this an SDK/library issue or an Azure platform issues? I think that the response should be ISO standard not culture specific.

**Comment by nonik0** [comment]
@SaltyDH @adibraniste This looks like an issue with App Service MSI endpoint and well as the AppAuth library (as the library is not accounting for the current behavior of the API). I was also able to repro this issue, and we will be releasing a fix with the next release of AppAuth (slated for this week).

I will also talk with the App Service MSI team regarding updating their API to use a more appropriate datetime format.

**Comment by nonik0** [comment]
@SaltyDH @adibraniste [AppAuth 1.2.1](https://www.nuget.org/packages/Microsoft.Azure.Services.AppAuthentication/1.2.1) was just released that should fix this culture issue (on the client side). Please try out the new release and let me know if you have any issues.

**Comment by adibraniste** [comment]
@nonik0 We have just updated to version 1.3.0 and now it works as expected (removed the temporary workaround we had in place).
Thanks for the support.
