### ISSUE TITLE
[BUG] ServiceClient does not dispose the root HttpClientHandler, causing TCP connection leak

### ISSUE THREAD

**Issue by allxiao** [Azure/azure-sdk-for-net#5977]
**Describe the bug**
Reference issue: #3712 

The `ServiceClient` creates a `HttpClientHandler` when no `HttpClient` is provided. This handler is not disposed in `ServiceClient#Dispose()`. This keeps a connection open in the background but no code path is able to use it.

We periodically create a ServiceClient (Kubernetes from KubernetesClient/csharp) and query the service endpoint. In .NET Core 2.1, this is guarded by a timeout (as said in #3712) and the connections may be recycled after timeout.

After upgrading to .NET Core 2.2, it seems there's some change to the timeout mechanism, and we can see the ghost connections keep growing and finally no local ports can be allocated and it affects all the services in the VM.

***Exception or Stack Trace***
N/A

**To Reproduce**

1. Create a `Kubernetes` instance using config file, and query any service API.
2. Dispose the instance
3. Repeat step 1~2

***Code Snippet***
Add the code snippet that causes the issue.
```
var kubeConfig = KubernetesClientConfiguration.BuildConfigFromConfigFile("/path/to/kubeconfig");
while (true)
{
    using (var client = new Kubernetes(kubeConfig))
    {
        await client.ListNamespacedDeployment1Async("default");
    }
    await Task.Delay(TimeSpan.FromSeconds(5));
}
```

**Expected behavior**
When the `ServiceClient` is disposed, all the resource created by itself and not exposed should be disposed.

**Screenshots**
```
$ sudo netstat -ap \| grep $(pgrep K8s)
tcp        0      0 10.4.255.128:40855      x.x.x.x:https      ESTABLISHED 14872/K8sChecker
tcp        0      0 10.4.255.128:40991      x.x.x.x:https      ESTABLISHED 14872/K8sChecker
tcp        0      0 10.4.255.128:38547      x.x.x.x:https      ESTABLISHED 14872/K8sChecker
tcp        0      0 10.4.255.128:38915      x.x.x.x:https      ESTABLISHED 14872/K8sChecker
...
```

**Setup (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - IDE : VS
 - Version of the Library used
    * KubernetesClient 1.5.18 which depends on Microsoft.Rest.ClientRuntime 2.3.10 (which does not even dispose the HttpClient, fixed in 2.3.12)
    * Microsoft.Rest.ClientRuntime 2.3.20

**Additional context**
.NET Core 2.1 seems to clean up the connections with timeout, while .NET Core 2.2 just leaves them open and use up system resource.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [*] Bug Description Added
- [*] Repro Steps Added
- [*] Setup information Added

**Comment by praries880** [comment]
cc: @shahabhijeet

**Comment by jongio** [comment]
@AlexGhiondea - Who should this one go to?
