### ISSUE TITLE
[Azure Search][BUG] Exclude attributes using IContractResolvers throws exception when loading data

### ISSUE THREAD

**Issue by pergerch** [Azure/azure-sdk-for-net#5979]
**Describe the bug**
Similar to #1259 I was trying to ignore certain attributes from being added to the index.
I created my own ContractResolver based on the CamelCasePropertyNamesContractResolver.

I could successfully create an index model without the excluded fields.

However when building the index using IndexBatch as shown in the documentation there is an exception complaining that a resource without a type name was found.

***Exception or Stack Trace***
```
Microsoft.Rest.Azure.CloudException: The request is invalid. Details: parameters : A resource without a type name was found, but no expected type was specified. To allow entries without type information, the expected type must also be specified when the model is specified.

   at Microsoft.Azure.Search.DocumentsOperations.DoIndexWithHttpMessagesAsync(String payload, SearchRequestOptions searchRequestOptions, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Search.DocumentsOperationsExtensions.IndexAsync[T](IDocumentsOperations operations, IndexBatch`1 batch, SearchRequestOptions searchRequestOptions, CancellationToken cancellationToken)
   at gDoc.Integration.AzureSearchService.InsertOrUpdate[T](IEnumerable`1 records) in C:\<project folder>\AzureSearchService.cs:line 116
```

**To Reproduce**

1) Define an index of a class using a custom ContractResolver
2) Load data into the index using IndexBatch and define the same ContractResolver in the serialization and deserializiation of the search client.
3) Try to load data. Above exception appears.

***Code Snippet***
```C#
public class SearchServiceContractResolver : CamelCasePropertyNamesContractResolver
{
    protected override IList<JsonProperty> CreateProperties(Type type, MemberSerialization memberSerialization)
    {
        var ignoredProperties = type.GetProperties().Where(p => Attribute.IsDefined(p, typeof(SearchServiceIndexIgnoredAttribute), false))
            .ToList();

        var properties = base.CreateProperties(type, memberSerialization);

        // Exclude ignored Properties
        properties = properties.Where(p => ignoredProperties.All(x => x.Name.ToLowerInvariant() != p.PropertyName.ToLowerInvariant())).ToList();

        return properties;
    }
}
```

```C#
var indexDefinition = new Index()
{
    Name = indexName,
    Fields = FieldBuilder.BuildForType<T>(new SearchServiceContractResolver()),
};

// Index model creation works well
await this.GetServiceClient().Indexes.CreateAsync(indexDefinition);
```

```C#
private SearchIndexClient GetIndexClient<T>()
{
    var indexName = this.GetIndexName<T>();
    var client = new SearchIndexClient(this.serviceName, indexName, new SearchCredentials(this.serviceApiKey));
    client.SerializationSettings.ContractResolver = new SearchServiceContractResolver();
    client.DeserializationSettings.ContractResolver = new SearchServiceContractResolver();

    return client;
}

// Insert data doesn't work and throws exception (in try):
var actions = records.Select(r => IndexAction.MergeOrUpload(r));

var batch = IndexBatch.New(actions);

await this.CreateIndexIfNotExists<T>();

var indexClient = this.GetIndexClient<T>();

try
{
    await indexClient.Documents.IndexAsync(batch);
}
// Exception...
```

**Expected behavior**
When importing data to the index, the custom ContractResolver should be used and the excluded properties should not be transmitted. So the import should be successful.

**Setup (please complete the following information):**
 - OS: Win 10 x64
 - IDE : VS 2019
 - Version of the Library used: 5.0.3

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by praries880** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up

CC: @shahabhijeet

**Comment by brjohnstmsft** [comment]
@pergerch Thanks for reporting this. It arrived just a little too late for us to address in our [latest release](https://www.nuget.org/packages/Microsoft.Azure.Search/8.0.0-preview), but we will investigate.

**Comment by pergerch** [comment]
Too bad, but congrats to the new release and thank you for looking into it. 

In the meantime I found a simple workaround. I manually map my custom type records into `Documents` before inserting, using this method (that is based on a comment on some other issue here):

```C#
private List<Document> GetDocuments<T>(IEnumerable<T> records)
{
    var documents = new List<Document>();
    var properties = typeof(T)
        .GetProperties(System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance)
        .Where(prop => !Attribute.IsDefined(prop, typeof(SearchServiceIndexIgnoredAttribute))).ToList();

    foreach (var record in records)
    {
        var doc = new Document();

        foreach (var m in properties)
        {
            doc.Add(m.Name, m.GetValue(record, null));
        }

        documents.Add(doc);
    }

    return documents;
}
```

**Comment by brjohnstmsft** [comment]
@pergerch I'm unable to repro this problem with version 9.0 of the SDK. Can you confirm whether upgrading solves the issue? If it doesn't, can you please share one of the model types for which it's failing? Here's the one I used in my test:

```csharp
class Record
{
    [Key]
    public string Id { get; set; }

    [IsFilterable, IsSearchable]
    public string Name { get; set; }

    [SearchServiceIndexIgnored]
    public TimeSpan Ignore { get; set; }
}
```

If you could also share the definition of `SearchServiceIndexIgnored`, that might also help. Here's the one I came up with for my test:

```csharp
[AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = true)]
class SearchServiceIndexIgnoredAttribute : Attribute
{
}
```

It would also help if you provide a minimal example of test data (instances of your model class) that cause `IndexAsync` to throw `CloudException`. Thanks!

**Comment by brjohnstmsft** [comment]
@pergerch Can you confirm whether upgrading to version 9 solved your issue?

**Comment by pergerch** [comment]
@brjohnstmsft I haven't had time to test it yet. Will give you feedback later this week. Thanks for your update.

**Comment by brjohnstmsft** [comment]
@pergerch Any update?

**Comment by pergerch** [comment]
@brjohnstmsft Yes, I can confirm. Upgrading to version 9 has solved the issue. Thanks a lot for your time!

**Comment by brjohnstmsft** [comment]
@pergerch Thanks for confirming.
