### ISSUE TITLE
[FEATURE REQ] Support ACI User Assigned Identites via SDK

### ISSUE THREAD

**Issue by CoenraadS** [Azure/azure-sdk-for-net#5980]
When creating an ACI container via a C# function app using the Fluent SDK, I am unable to assign it an User Assigned Identity.

The documentation here: https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/services-support-managed-identities shows that it is supported via CLI, Resource Manager template or YAML. But SDK is unsupported.

As a solution I would like to use the Fluent API when instantiating an ACI to assign an User Assigned Identity (so that the python code in the container can authenticate with other Azure services via MSI).

**Comment by praries880** [comment]
Issue moved to [Azure/azure-libraries-for-net #649](https://github.com/Azure/azure-libraries-for-net/issues/649) via [**ZenHub**](https://www.zenhub.com/)
