### ISSUE TITLE
[QUERY] src vs sdk folders

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-sdk-for-net#6018]
**Query/Question**

Vast majority of the code is found under `src` as a convention.
Some code is under `sdk`. What's the reason for that?

**Comment by kurtzeborn** [comment]
Wes should be able to answer this one.

CC: @shahabhijeet

**Comment by weshaggard** [comment]
Thanks for the query @seanfelman but this is a temporary inconsistency as we are in the process of transitioning the a new convention with the source under the sdk folder, see issue https://github.com/Azure/azure-sdk-for-net/issues/5213.
