### ISSUE TITLE
[Service Bus] [Transferred issue] Allow clients to report if they own or share the underlying connection string

### ISSUE THREAD

**Issue by axisc** [Azure/azure-sdk-for-net#6032]
@SeanFeldman  please add details.

**Comment by SeanFeldman** [comment]
Follow up for original PR https://github.com/Azure/azure-service-bus-dotnet/pull/485 which fixed issue https://github.com/Azure/azure-service-bus-dotnet/issues/482 

- Extract `OwnsConnection` into `IClientEntity` contract

[The fix](https://github.com/Azure/azure-service-bus-dotnet/pull/485) was backwards compliant w/o need in a breaking change/major release. It was determined that the next major release should contain this change. PR for the **next major** in the "old" ASB client repo: https://github.com/Azure/azure-service-bus-dotnet/pull/486. This PR should be opened against this library.

**Comment by mscrivo** [comment]
I don't understand the implications of this new `OwnsConnection` prop.  Can you explain it a bit more? 
We recently upgraded to 4.0 and are having issues with our workers suddenly losing connections and being unable to get queue counts.  Would this be related?

We are seeing messages like this:

> Microsoft.Azure.ServiceBus.ServiceBusException: The connection was inactive for more than the allowed 240000 milliseconds and is closed by container 'ccc6060e076640199da57f39b7762509_G0'.

**Comment by SeanFeldman** [comment]
@mscrivo this property should not affect anything as it's a read-only flag to indicate wherever a client owns the connection (created it) or not (was given an existing connection).
