### ISSUE TITLE
Obsolete property in JsonSerializerSettings

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-for-net#6040]
**Bud Description**
ReferenceResolver property in JsonSerializerSettings is obsolete.

***Exception or Stack Trace***
`Customization\JsonSerializerExtensions.cs(34,17): warning CS0618: 'JsonSerializerSettings.ReferenceResolver' is obsolete: 'ReferenceResolver property is obsolete. Use the ReferenceResolverProvider property to set the IReferenceResolver: settings.ReferenceResolverProvider = () => resolver' [C:\git\azure-sdk-for-net\src\sdks\eventgrid\DataPlane\Microsoft.Azure.EventGrid\Microsoft.Azure.EventGrid.csproj]`
NB: sdk folder has changed

**To Reproduce**
Remove  `<NoWarn>$(NoWarn);CS0618</NoWarn>` from `Microsoft.Azure.EventGrid.csproj` then build the project.

**Expected behavior**
Warning is thrown. Warning is treated as error on the CI pipeline.

**Comment by AlexGhiondea** [comment]
@chidozieononiwu do we need to remove that warning? It looks like the owners of that library are aware that the property is obsolete and chose to use it anyway. Unless we have a reason to remove that error, I would leave the project as-is.

**Comment by chidozieononiwu** [comment]
> @chidozieononiwu do we need to remove that warning? It looks like the owners of that library are aware that the property is obsolete and chose to use it anyway. Unless we have a reason to remove that error, I would leave the project as-is.

I was the one who suppressed the warning during the repo restructure. That library wasn't being pulled into the build previously so the warning wasn't showing up.

**Comment by AlexGhiondea** [comment]
Why are we pulling it into the build now?

I think we can try and fix it using the suggestion provided in the error message but I want to understand a bit more about why we are doing it first.

**Comment by chidozieononiwu** [comment]
> Why are we pulling it into the build now?
> I think we can try and fix it using the suggestion provided in the error message but I want to understand a bit more about why we are doing it first.

So, the build was using the folder name 'data-plane' to include dataplane libraries. For EventGrid that folder was named 'DataPlane' so it has not been building for a while which is why the warning seems new. I had to add it t0 <NoWarn> to get it to build in CI since warnings are reported as errors.

**Comment by AlexGhiondea** [comment]
Do you know if we shipped this at all? It looks like a version was released just last month. If we didn’t build it, any idea how it got built?

**Comment by chidozieononiwu** [comment]
> Do you know if we shipped this at all? It looks like a version was released just last month. If we didn’t build it, any idea how it got built?

As far as I can tell since this change [#5133](https://github.com/Azure/azure-sdk-for-net/commit/9d2b41e33674db73d8cee01b0018b8d98e9de984#diff-290679e463588a1e5c4da291beb89083) some of the client libraries have not been building in the CI and batch is one of them. cc @weshaggard

**Comment by weshaggard** [comment]
>Do you know if we shipped this at all? It looks like a version was released just last month. If we didn’t build it, any idea how it got built?

It was built from the management plane jenkins jobs. It didn't ship through our pipelines yet.

**Comment by AlexGhiondea** [comment]
Ok. And is there a way to see why this warning wasn’t send there? I am hesitant to make a change to this code until we understand why we are seeing this error.

I will reach out to the service owners to see if they have more insight.

**Comment by weshaggard** [comment]
I suspect they just ignored the warning before, whereas we are a little more strict about treating warnings as errors. It is also possible that we have updated the version of Json.Net which now has the obsolete warning whereas the older version didn't.

**Comment by Petermarcu** [comment]
I propose that we just don't do anything here. In our next wave of updates there will be no JSON.NET dependency and this code will just go away. Agree?
