### ISSUE TITLE
README in the Documentation folder is not super useful

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk-for-net#6094]
https://github.com/Azure/azure-sdk-for-net/blob/master/Documentation/README.md

It just has a table and no links to docs.

**Comment by kurtzeborn** [comment]
@scbedd, I think your work to generate packages.md makes this obsolete.  If I'm right, we can just delete this readme.

**Comment by danieljurek** [comment]
This looks like an old bug. We have a list of released packages with links to source, packages, and reference documentation at https://aka.ms/azsdk
