### ISSUE TITLE
KeyVault README does not follow our readme/sample guidelines

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk-for-net#6095]
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Microsoft.Azure.KeyVault/README.md

The readme does not have hello world sample inline
Also, there is no "samples" folder with samples. 
See how Configuration service package does it.

**Comment by kaerm** [comment]
Correct me if I am wrong but this is track 1 not track 2, right?

**Comment by AlexGhiondea** [comment]
This is about the Track 1.
