### ISSUE TITLE
[QUERY] Individual component SemVer vs repo milestones

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-sdk-for-net#6096]
**Query/Question**

Individual libraries, such as Azure Service Bus are SemVer versioned. When a component used to be in a standalone repo, milestones where used to represent SemVer versions to be released. One of the milestone would, for example, be the next major where breaking changes would be introduced. Issues/PRs with breaking changes would be assigned that milestone.

In the current monolithic repository, milestones are used as well, but they represent [sprints](https://github.com/Azure/azure-sdk-for-net/milestones). Could you please point me to the documentation (sorry if it's there and I just failed to locate it) or elaborate on the methodology used to express SemVer versions in regard to milestones? Thank you.

**Comment by SeanFeldman** [comment]
Related: https://github.com/Azure/azure-sdk-for-net/issues/6031#issuecomment-425551043

**Comment by kurtzeborn** [comment]
Good question Sean!  There deserves to be more clarity here.

**Comment by maggiepint** [comment]
Hi Sean,

You have correctly caught that we are re-working how we do things a bit around here, and that includes milestones. I'm curious - are milestones a critical path to this, or are you mostly looking to understand 'What features will be in the next major and minor releases?'

If we were to provide a roadmap with what we are planning on working on next, would that cover it?

Thanks for the clarification.

**Comment by SeanFeldman** [comment]
Before I touch on the milestones part, let me elaborate on SemVer first.

[Semantic Versioning](https://semver.org/) (SemVer) is very clear about versioning of packages. It helps customers and providers [clearly communicate](https://semver.org/#summary) changes and manage expectations, eliminating surprises and streamlining software updates.

Looking at the [releases page](https://github.com/Azure/azure-sdk-for-net/releases), there are two problems:
1. There's no way to know what version of what component is being released.
1. Release doesn't point to the changes made (fixed bugs, added improvements, new features added, breaking changes, etc).

Anyone monitoring this repository for releases (GitHub feature) is notified almost on a daily basis but the information is a fire-hose of packages released w/o version. This could be argued as a GitHub issue. 
![image](https://user-images.githubusercontent.com/1309622/57198280-29160b00-6f2e-11e9-8428-f393d2b812ca.png)
Saying that, having a version in the release notes would save the exploration of NuGet to identify what the latest version that got shipped was. Also, the NuGet cannot provide the information about changed made in the latest release.

**Example**: latest release of `Microsoft.Azure.CognitiveServices.FormRecognizer`.
GitHub release notes [link](https://github.com/Azure/azure-sdk-for-net/releases/tag/2019-05-03T18-15).
NuGet [feed](https://www.nuget.org/packages/Microsoft.Azure.CognitiveServices.FormRecognizer) shows 0.8.0-preview version as the latest. Is it thought? Neither from the GitHub release nor from the NuGet feed it is possible to find out what changes have been released in that version.

### Milestones

Milestones are extremely helpful to set expectations and identify when things will be delivered. With milestones aligned with releases, those that dependent on features or bugs can at least have an idea what to expect. For example, a breaking change would need to go into the next major version. Therefore an issue for a bug that would required a breaking change would be assigned to the next major milestone. Additional work planned for the next major would be addressed in the similar way.

Hotfixes and new features. Depending on how those categorized based on SemVer, hotfix might be released in a milestone different from a feature that was planned. Or, if possible, they'd be packaged together under the same milestone. As a 3rd party library developer it helps to see this information to know how to plan work on my end, rather than wondering what will happen.

An example of how milestones worked for Service Bus client: [link](https://github.com/Azure/azure-service-bus-dotnet/milestones?state=closed&direction=desc)

**Comment by SeanFeldman** [comment]
@kurtsung @maggiepint hope this information helps.
Here's how we leverage milestones ([past](https://github.com/Particular/NServiceBus.AzureServiceBus/milestones?state=closed&direction=desc) and  [future](https://github.com/Particular/NServiceBus.AzureServiceBus/milestones)) and [releases](https://github.com/Particular/NServiceBus.AzureServiceBus/releases).

**Comment by maggiepint** [comment]
Hey Sean,

I think on the releases side you are asking for work that is already in-flight. As you noticed, we are making quite a few changes to how SDKs are versioned. If you were to look at [this release](https://github.com/Azure/azure-sdk-for-net/releases/tag/Azure.Core_1.0.0-preview.5), it uses our new release format, which will soon be the format for all GitHub releases going forward. This follows our [SemVer guidelines](https://github.com/Azure/azure-sdk/blob/master/docs/engineering-system/releases.md#package-versioning) which over time will be enforced for all packages in this repo, including any future releases of the Service Bus client.

I realize the notes are sparse on the release I linked - I'm currently working with our dev teams to make sure we get as complete of notes as possible on our releases in the future.

Does that answer your release question?

On the milestone side - right now it's up to each service team to determine how they want to publish roadmaps/timelines/expectations. I can definitely talk to service bus about how they want to handle roadmap in this new repo format. @jsquire might be a good starting point for this.

**Comment by SeanFeldman** [comment]
@maggiepint the new release format is good. With some improvements to the release notes it will be exactly what I'm asking for 🙂

👍 for sorting out milestones.

**Comment by SeanFeldman** [comment]
> any issues filed or pull requests made will continue to be actively triaged collaboratively between the Service Bus and Developer Platform teams.

👍

**Comment by maggiepint** [comment]
I think if we are happy with the new release format, then I can close this with a note that I am working on a proposal for how our service teams can track milestones and upcoming changes a bit more transparently.

Let me know if I need to re-open.
