### ISSUE TITLE
BeginSwapingSlots Typo

### ISSUE THREAD

**Issue by pnewhook** [Azure/azure-sdk-for-net#610]
Swapping should have two p's in [BeginSwapingSlots](https://github.com/Azure/azure-sdk-for-net/blob/2a427d6c73d2291114f20b5b44edf9679e0138b2/src/WebSiteManagement/Generated/WebSiteOperationsExtensions.cs#L70) and [BeginSwapingSlotsAsync](https://github.com/Azure/azure-sdk-for-net/blob/2a427d6c73d2291114f20b5b44edf9679e0138b2/src/WebSiteManagement/Generated/WebSiteOperationsExtensions.cs#L107) The comments spell it right. I understand this would be a breaking change, but it's better to change early before the library gains broad usage.<p><a href="https://github.com/Azure/azure-sdk-for-net/issues/610">https://github.com/Azure/azure-sdk-for-net/issues/610</a></p>

**Comment by shahabhijeet** [comment]
please reopen if this is an issue.
