### ISSUE TITLE
[Suggestion] Helper to create Virtual Network Configuration Schemas

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-sdk-for-net#611]
Users are supposed to pass XML data to the APIs like Create Virtual Network in [a certain format](http://msdn.microsoft.com/en-us/library/jj157100.aspx).

It could be helpful if we can prepare an object model to create such an XML. I know some of the objects required are already in the code under `VirtualNetworks.Models.NetworkListResponse` class but we are missing the list-wrapper members like:

`` for `NetworkListResponse.LocalNetworkSite`
`` and `` for `NetworkListResponse.DnsServer`
...
and the main element ``. And the existing model cannot be used with DataContractSerializer or XmlSerializer since it's missing the required attributes on fields of those types.

Since VNet configs can be updated programmatically, maybe we should even provide overloads that take the VirtualNetworkConfiguration object model besides XML and do the serialization ourselves?<p><a href="https://github.com/Azure/azure-sdk-for-net/issues/611">https://github.com/Azure/azure-sdk-for-net/issues/611</a></p>

**Comment by singhkay** [comment]
this should be owned by the networking team at this point. Adding Ed Munoz @dud5

**Comment by ahmetalpbalkan** [comment]
apparently there is no interest + this was ASM so closing.
