### ISSUE TITLE
[FEATURE REQ] Missing CreateOrUpdate method in IDscNodeOperations

### ISSUE THREAD

**Issue by PAV41** [Azure/azure-sdk-for-net#6127]
There is no way to create Dsc Node via Azure SDK. At this moment IDscNodeOperations interface doesn't have CreateOrUpdate() method. You can only list existing nodes or delete them. Could you pls implement missing method?

As a workaround now we are creating on the fly Powershell script which is calling function Register-AzureRmAutomationDscNode. This works fine but is dirty solution and we want avoid it.

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by nc-mlo** [comment]
vote +

**Comment by andyw248** [comment]
Please file feature request at: https://feedback.azure.com/forums/246290-automation?filter=top&page=1.
