### ISSUE TITLE
[BUG] ClientSecret with semicolon or equals causes exception in AzureServiceTokenProvider

### ISSUE THREAD

**Issue by Kurtaclan** [Azure/azure-sdk-for-net#6138]
**Describe the bug**

Any password with a semicolon or equal sign causes AzureServiceTokenProvider to fail.

***Exception or Stack Trace***
Add the exception log and stack trace if available
Connection string is not in a proper format. Expected format is Key1=Value1;Key2=Value=2;

**To Reproduce**

Try creating a AzureServiceTokenProvider with a client secret that contains a semicolon or equals sign

***Code Snippet***
Add the code snippet that causes the issue.
new AzureServiceTokenProvider($"RunAs=App;AppId={appSettings["ClientId"]};TenantId={appSettings["enantId"]};AppKey={appSettings["ClientSecret"]}");

**Expected behavior**

Common escapes should allow the string to not be split, ie double quotes or curly braces.

**Setup (please complete the following information):**
 - OS: Windows
 - IDE : Visual Studio 2017 Professional
 - Version of the Library used: 1.0.1

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by shahabhijeet** [comment]
@Kurtaclan what library is this bug regard to?
Can you provide the source of this library if from nuget.org, provide the URL for the library.

**Comment by Kurtaclan** [comment]
https://www.nuget.org/packages/Microsoft.Azure.Services.AppAuthentication/1.0.1

**Comment by nonik0** [comment]
@Kurtaclan This issue is fixed in the latest GA release, [AppAuth 1.2.0](https://www.nuget.org/packages/Microsoft.Azure.Services.AppAuthentication/1.2.0).
