### ISSUE TITLE
We need a "pipeline.proj" file 

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk-for-net#6167]
We should look at introducing a ```pipeline.proj``` MSBuild file for each logical service which sits within its ```/sdk/[service]``` folder. At the moment the PR validation pipelines reference a single "project file" which is actually a solution file and we use ```dotnet pack``` and ```dotnet test``` on this file, however not all data plane libraries have a solution file.

We can either add solution files where they are missing or we could add a pipeline.proj file which services the same purpose and might work better. This pipeline.proj file would also be capable of building and testing the management libraries as well (maybe?).

This might allow us to simplify the PR pipeline creation approach where we automatically scan the ```/sdk``` folder for directories that contain ```pipeline.proj``` and then create a ci.yml file which maps to it.

**Comment by kurtzeborn** [comment]
@weshaggard and I believe we have this covered already with our service.proj files.  Closing this.  Please reopen if you feel like there's more to do here.
