### ISSUE TITLE
[BUG] Multiple calls to RegisterSessionHandler hangs web app

### ISSUE THREAD

**Issue by travismartinjones** [Azure/azure-sdk-for-net#6187]
**Describe the bug**
When registering session handlers for multiple queues, a web app may become unresponsive.

***Exception or Stack Trace***
No exception thrown to the client, but multiple exceptions are logged by the MessagingEventSource. Those exceptions are:

- Exception thrown: 'System.TimeoutException' in System.Private.CoreLib.dll
- Exception thrown: 'Microsoft.Azure.ServiceBus.ServiceBusTimeoutException' in System.Private.CoreLib.dll

**To Reproduce**
Load the attached project that reproduces the error. The first call to api/test will respond once the web app is loaded. Wait 1-2 minutes until you see the exceptions listed above being logged in the debug output. Try loading the same api/test url and it will no longer load.

***Code Snippet***
Please see the [attached project](https://github.com/Azure/azure-sdk-for-net/files/3157125/Repro.zip)

**Expected behavior**
The application should always respond to requests to api/test in a timely manner and be unaffected by any service bus internal operations.

**Screenshots**
Not applicable.

**Setup (please complete the following information):**
 - OS: Windows 10 Pro (Other window platforms likely)
 - IDE : Visual Studio 2017
 - 3.4.0

**Additional context**
If you comment out Startup.cs:64 where RegisterSessionHandler is called, the hang will not occur.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by travismartinjones** [comment]
@kurtzeborn On issue https://github.com/Azure/azure-sdk-for-net/issues/6252 you tagged it with Service Bus and Client. I think these two issues stem from the same problem and this card should also be tagged similarly.

**Comment by travismartinjones** [comment]
@kurtzeborn I haven't seen any activity on this bug in over a month. Has it been assigned to a team for follow up?

**Comment by jfggdl** [comment]
@kurtzeborn we bumped into this one, but it was not visible to us on the dashboard because it did not have the Service Bus label. I have added it.

**Comment by nemakam** [comment]
@travismartinjones - Are you also sending messages to the queue during your repro?
I am unable to get the repro that you are mentioning. My `GET` call to `https://localhost:44320/api/test` succeeds everytime

**Comment by nemakam** [comment]
@travismartinjones - Could you enable ETL traces and share it with us so that we can see which part is causing issues?

**Comment by travismartinjones** [comment]
@nemakam No messages are being sent in the reproduction test case. Only the calls to CreateQueueAsync and RegisterSessionHandler. I just downloaded the Repro.zip test case, ran the solution, waited two minutes, refreshed the web api endpoint at https://localhost:44320/api/test and it was not responsive. 

I'll work on enabling ETL traces and get that information added to this issue.

**Comment by nemakam** [comment]
Interesting.. It works pretty well on my machine. My guess would be that it has to do with mixing sync and async calls.

**Comment by travismartinjones** [comment]
@nemakam I've generated an ETL trace, but unable to attach due to the size. Is there something particular in the TL that you'd like me to pull via PerfView?

Also, I'm working on creating a new reproduce-able case that uses the AMQP source instead of the nuget package in order to provide more verbose logging.

**Comment by travismartinjones** [comment]
@nemakam The ETL I've generated doesn't have the Event Source traces that I would expect. What are the appropriate settings needed to capture service bus & amqp trace information from PerfView?

**Comment by nemakam** [comment]
@travismartinjones 
Download PerfView
Run PerfView.exe /OnlyProviders=*Microsoft-Azure-ServiceBus Collect
Stop the collection of traces once you have successful repro.

This however, doesn't collect the AMQP level info. I'll have to check the AMQP library for its tracing

**Comment by travismartinjones** [comment]
@nemakam The PerfView data didn't seem to capture useful information for you, so I've gone ahead and made a fork that better illustrates the issue. 

https://github.com/travismartinjones/azure-sdk-for-net/tree/feature/issue-6187

I've added a line of diagnostics output in the AmqpLinkCreator.cs:82. If you launch the reproduction solution from /samples/TimeoutReproduction/ServiceBusStandardWebTest/ you'll see the following output:

```
Queue Queue1 already created 
...
Queue Queue100 already created
Registering session handler for Queue1
...
Registering session handler for Queue100
```

You can hit https://localhost:44320/api/test and it should load just fine. After 1-2 minutes, you'll see the exceptions from the AmqpLinkCreator being logged. At this point, the test url https://localhost:44320/api/test will no longer respond. I'm not sure how await AmqpObject.OpenAsync is supposed to work, but it appears to be timing out and causing this issue.

The errors logged will look like the following:

```
The operation did not complete within the allocated time 00:00:58.4436083 for object receiver987.
The operation did not complete within the allocated time 00:00:58.5540593 for object receiver923.
The operation did not complete within the allocated time 00:00:58.5550841 for object receiver925.
The operation did not complete within the allocated time 00:00:58.5561959 for object receiver927.
The operation did not complete within the allocated time 00:00:58.5521067 for object receiver924.
The operation did not complete within the allocated time 00:00:58.5555955 for object receiver926.
The operation did not complete within the allocated time 00:00:58.8998396 for object receiver414.
The operation did not complete within the allocated time 00:00:58.5526369 for object receiver919.
The operation did not complete within the allocated time 00:00:58.5550457 for object receiver922.
```

**Comment by axisc** [comment]
@travismartinjones

Thanks for sharing the details. We will need more information to debug this.

could you take a memory dump when you repro this error locally, and use Wireshark to capture the network trace?

**Comment by nemakam** [comment]
@travismartinjones ,
https://docs.microsoft.com/en-us/dotnet/api/system.net.servicepointmanager.defaultconnectionlimit?redirectedfrom=MSDN&view=netframework-4.8#System_Net_ServicePointManager_DefaultConnectionLimit 

Could you ensure that the service is able to create 100s of outbound connection from your app?

**Comment by jfggdl** [comment]
@travismartinjones, would you please share any status on where your problem stands? Were you be able to ensure that the service is able to create 100s of outbound connections form your app? Are you able to provide a memory dump?

**Comment by jfggdl** [comment]
@travismartinjones, I am going to close this issue, but please feel free to open another issue and refer to this one if you still have questions/need additional support. If you open a new issue, please help us with the questions that both axisc  and nemakan asked.
