### ISSUE TITLE
Implement Track 2 APIs for Keys

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#6203]
Things to do:
- [x] Refactor internal code into reusable components
- [ ] Implement the Keys APIs

**Comment by maririos** [comment]
I divided this issue in 3 to facilitate PRs and feedback:
- Create, update, delete: https://github.com/Azure/azure-sdk-for-net/issues/6432
- Restore, backup, purge, import: https://github.com/Azure/azure-sdk-for-net/issues/6433
- List methods: https://github.com/Azure/azure-sdk-for-net/issues/6434
