### ISSUE TITLE
[BUG]Tests fail in Microsoft.Azure.CognitiveServices.Language.LUIS.Authoring.Tests

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-for-net#6211]
**Bug Description**
Various tests are failing in Microsoft.Azure.CognitiveServices.Language.LUIS.Authoring.Tests

**To Reproduce**
Remove Skip property from the Test Attibute on the specific test.

**Expected behavior**
Test Fails

**Comment by jsquire** [comment]
Given the age of this issue and the deprecation of most of the track one libraries, closing this as stale.  If tests are still failing, please file a new issue.
