### ISSUE TITLE
Azure.Configuration should be renamed to Azure.ApplicationModel.Configuration

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-for-net#6236]
The library has been renamed but there are still a number of project files with the older name:

Example:
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/appconfiguration/Azure.ApplicationModel.Configuration/src/Azure.Configuration.csproj
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/appconfiguration/Azure.ApplicationModel.Configuration/tests/Azure.Configuration.Tests.csproj

Those should be renamed to match the assembly/package name.

**Comment by maririos** [comment]
Pr merged
