### ISSUE TITLE
Enable SourceLink for .NET projects

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-for-net#6239]
See https://github.com/dotnet/SourceLink for how to enable SourceLink. This will give us the ability to debug through the source code of our libraries as well as it will add some additional metadata to the information version that points to the sha of the source when it was built.

**Comment by weshaggard** [comment]
@tmat Do we still need to reference the SourceLink package or is the support if we are using the .NET Core 3 SDK? Has support been added to the SDK?

**Comment by tmat** [comment]
Yes, there is no plan to include SourceLink in the SDK.

**Comment by weshaggard** [comment]
@chidozieononiwu looks like there are some projects that already reference SourceLink (https://github.com/Azure/azure-sdk-for-net/search?q=sourcelink&unscoped_q=sourcelink) which is why @mitchdenny said it worked for some he tried already. Please move that package reference to the common targets file and update the version to the latest published on nuget.org.

**Comment by SeanFeldman** [comment]
It was extremely convenient to step into the code w/o the need to set up symbols server.
I'd like to ask what was the reason SourceLink was disqualified?

**Comment by weshaggard** [comment]
We have enabled SourceLink for all our data-plane packages by default, see PR https://github.com/Azure/azure-sdk-for-net/pull/6867. If you are seeing something not working please let us know.
