### ISSUE TITLE
Publishing to Azure Service Bus using AmqpWebSockets doesn't work from .Net Core app

### ISSUE THREAD

**Issue by djrhodes** [Azure/azure-sdk-for-net#6242]
**Query/Question**
Attempting to publish to an Azure service bus fails with 'Unable to connect to remote server' error from a .Net core 2.2 console app. I am in an enterprise environment so am using the AmqpWebSockets transport type. I can publish fine from a .Net framework 4.7.2 app using exactly the same nuget package, code and connection string.

From the diagnostic output it logs a Timeout exception from Microsoft.Azure.Amqp.dll, and then a HttpRequestException - "A connection attempt failed because the connected party did not properly respond.....".

I'm thinking it can't be environmental as it works from .Net Framework.

***Why is this not a Bug or a feature Request?***
I'm not sure this is a bug as there may be some setting or config that I am missing.

**Setup (please complete the following information if applicable):**
 - OS: Windows 10 Enterprise 10.0.17134 
 - IDE : Visual Studio 2017 15.9.11
 - Version of the Library used : Microsoft.Azure.ServiceBus v3.4.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added
Attached below is my sample test client code
[AzurePublishTest.zip](https://github.com/Azure/azure-sdk-for-net/files/3167499/AzurePublishTest.zip)
]

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by ErikMogensen** [comment]
@djrhodes , I cannot find any reference to a proxy in the solution you attached. You need to specify connection information to the proxy. Therefore it is surprising that the .Net Framework application worked. I assume you set it in the app.config file.

The following code, as mentioned in [https://github.com/Azure/azure-service-bus-dotnet/issues/436](url) should work for both of your applications once you have adapted the parameters to your proxy connection:

```
WebProxy proxyObject = new WebProxy(
    "http://<proxyserver>:<proxyport>", 
    true, 
    new string[] { "somemachine" }, 
    new NetworkCredential("<user>", "<password>"));
WebRequest.DefaultWebProxy = proxyObject;
```

**Comment by djrhodes** [comment]
@ErikMogensen Thanks for your response. I thought the same but there were no proxy settings in machine.config.  However, setting the proxy explicitly in the .Net core code worked, so thank you 👍

**Comment by alcidesfmelof** [comment]
> to specify connection information

How to to specify connection information in code? 
Just opened a new thread, I am not understanding hot to specify in code. 


```
queueClient = new QueueClient(ServiceBusConnectionString, QueueName);
queueClient.ServiceBusConnection.TransportType = TransportType.AmqpWebSockets;

```

Where it goes the WebProxy /WebRequest. 

Thank you.
