### ISSUE TITLE
Deployment Label should NOTbe Base64 Encoded

### ISSUE THREAD

**Issue by vijayshinvabk** [Azure/azure-sdk-for-net#625]
BUG in VirtualMachineOperations.BeginCreatingDeploymentAsync

As per the REST documentation at http://msdn.microsoft.com/en-us/library/azure/jj157194.aspx while creating a new VirtualMachine Deployment we should pass the Deployment Label as plain string. The SDK function VirtualMachineOperations.BeginCreatingDeploymentAsync Base64 encodes the Deployment Label. 

This causes the deployment label to show up as a Base64 encoded string in the Azure portal.

![azure sdk bug](https://cloud.githubusercontent.com/assets/6523821/2875881/a9002d9c-d428-11e3-86c8-005e9497ee77.png)<p><a href="https://github.com/Azure/azure-sdk-for-net/issues/625">https://github.com/Azure/azure-sdk-for-net/issues/625</a></p>

**Comment by markcowl** [comment]
This iss ue should be fixed.  Please open a new issue if you see a recurrence

**Comment by ahmetalpbalkan** [comment]
@markcowl are you just closing old issues or are you sure this is fixed?
