### ISSUE TITLE
Test reporting warning for Azure.ApplicationModel.Configuration

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-for-net#6264]
For some reason on Linux and Mac we get this warning when publishing test results which makes me wonder if all the tests are correctly getting reported. 

See last nights build https://dev.azure.com/azure-sdk/internal/_build/results?buildId=30798
```
##[warning]Invalid results file. Make sure the result format of the file '/home/vsts/work/1/s/sdk/appconfiguration/Azure.ApplicationModel.Configuration/samples/TestResults/_fv-az578_2019-05-14_12_05_16.trx' matches 'VSTest' test results format.
##[section]Async Command Start: Publish test results
```

**Comment by weshaggard** [comment]
Based on some other instances of this I believe the issue is likely that there are no tests run for this project in this configuration for the sample projects. We should figure out if that is intended and if so then figure out if we want to disable these test result somehow when there are not tests run.

**Comment by AlexGhiondea** [comment]
I believe we have tests now for this library. Is there a way to check that this is no longer an issue?

**Comment by weshaggard** [comment]
The latest test runs on the pipeline https://dev.azure.com/azure-sdk/internal/_build?definitionId=237 no longer show this warning so we can close this.
