### ISSUE TITLE
RoleInstance.InstanceStatus and RoleInstanceStatus

### ISSUE THREAD

**Issue by KiranDommaraju** [Azure/azure-sdk-for-net#627]
The property InstanceStatus in Microsoft.WindowsAzure.Management.Compute.Models.RoleInstance class enumerated from the PropertyValues in Microsoft.WindowsAzure.Management.Compute.Models.RoleInstanceStatus class 

One of the value for the RoleInstance.InstanceStatus is “Provisioning” which I do not find in RoleInstanceStatus class.<p><a href="https://github.com/Azure/azure-sdk-for-net/issues/627">https://github.com/Azure/azure-sdk-for-net/issues/627</a></p>

**Comment by markcowl** [comment]
Ths instance status enumeration is a guide and not an exhaustive list of values.  Please reopen if this is still an issue.
