### ISSUE TITLE
HttpPipeline should be disposable and support disposable policies

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#6288]
We need to be able to dispose of HttpClient or any other resources created inside policies.

cc @KrzysztofCwalina

**Comment by KrzysztofCwalina** [comment]
Really? The client is shared (between many pipelines).

**Comment by pakrym** [comment]
We already have per-client policies that conceivably can cache disposable resources (encryption related stuff in auth policies comes to mind). I don't want to find ourselves in the world where we're unable to manage resources on client-lifetime basis.

Other example is non-http transports like AMQP that might manage clients internaly.
