### ISSUE TITLE
Ship vNext version of Service Bus

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#6302]
This will track the work for the next release of Service Bus.

**Comment by SeanFeldman** [comment]
@AlexGhiondea is this epic supposed to have links to the issues that will be released in a minor or major?

**Comment by SeanFeldman** [comment]
Would be nice to provide a reason not give a wrong impression to subscribers 🙂

**Comment by AlexGhiondea** [comment]
There was not more work associated with this epic, so I closed it. Thanks for the feedback -- I'll make sure to add more context on issues when they are closed.
