### ISSUE TITLE
[BUG] SharedAccessSignatureProvider.tokenTimeToLive default throws opaque exception

### ISSUE THREAD

**Issue by jasonholloway** [Azure/azure-sdk-for-net#6312]
When using the ASB client to publish to a topic:

The `SharedAccessSignatureProvider.tokenTimeToLive` field, if left at its default value (as is incredibly simple to do when configuring via MassTransit), causes an obscure exception to be thrown by the framework Timer class on first received message - this is because of a lack of validation in the Microsoft code, leading to negative numbers in the wrong places.

`ActiveClientLinkManager` is the place to look for the offending code, and the best explanation can be found attached to the end of this closed issue in the archived repo: https://github.com/Azure/azure-service-bus-dotnet/issues/399#issuecomment-460070046

This is likely to be affecting a large proportion of people using Azure Service Bus via MassTransit - sensible default behaviour is needed!

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

CC: @shahabhijeet

**Comment by jfggdl** [comment]
@jasonholloway, Thank you. We are already looking at the suggested approach in the link provided.
