### ISSUE TITLE
[BUG] [Azure Table storage] Query filter containing exclamation mark not working correctly.

### ISSUE THREAD

**Issue by Dethras** [Azure/azure-sdk-for-net#6350]
While testing I have noticed an issue with filters containing the ! where when you include it in the query, the sdk will automatically convert it to not.

Example:

PartitionKey eq 't!est' = PartitionKey eq 'tnotest'

I tried to search for an escape character of something of that sort but it was fruitless.
I also don't know if there are other characters with the same issue.

**Comment by brjohnstmsft** [comment]
@Dethras Which Azure service are you referring to? Is it Azure Search, or something else? Also, can you provide details on how exactly you diagnosed the problem?

**Comment by Dethras** [comment]
@brjohnstmsft Apologies for the lack of detail. I am referring to the Azure Table storage. And if you would like, you can replicate the issue yourself. Just Create a table and add a record with the partitionkey containing an exclamation mark, then query that table and try to retrieve that record (Most preferably with an equals).

**Comment by brjohnstmsft** [comment]
@Dethras Thanks for clarifying. I'm on the Azure Search team, and Azure Search also supports the OData syntax for filtering, which is why I wasn't sure which service you meant. I've renamed and tagged your issue so that it gets routed to the right people.

**Comment by Dethras** [comment]
@brjohnstmsft Thanks, I do appreciate it :)

**Comment by blueww** [comment]
@Dethras 
Which SDK are you using? (and version)
For this repo, it currently only for storage SDK on  management plane, but table is data plane.
 
If you are using "WindowsAzure.Storage", please file issue in https://github.com/Azure/azure-storage-net

**Comment by Dethras** [comment]
@blueww You are absolutely right, I should have filed the issue on the azure-storage-net. I will close this issue and open another one on https://github.com/Azure/azure-storage-net. Thanks :)
