### ISSUE TITLE
[BUG] System.TypeLoadException

### ISSUE THREAD

**Issue by ddobric** [Azure/azure-sdk-for-net#6381]
Tried to set running newest bits. When started, application fails with System.TypeLoadException.

### Error
> ***Exception or Stack Trace***
> System.TypeLoadException
>   HResult=0x80131522
>   Message=Method 'get_EventBehaviourForContinueAsNew' in type 'DurableTask.ServiceBus.ServiceBusOrchestrationService' from assembly 'DurableTask.ServiceBus, Version=2.0.10.0, Culture=neutral, PublicKeyToken=d53979610a6e89dd' does not have an implementation.
>   Source=<Cannot evaluate the exception source>
>   StackTrace:
> <Cannot evaluate the exception stack trace>

### Project file
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.DurableTask.AzureStorage" Version="1.6.0" />
    <PackageReference Include="Microsoft.Azure.DurableTask.Core" Version="2.1.1" />
    <PackageReference Include="Microsoft.Azure.DurableTask.ServiceBus" Version="2.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharedLib.NetCore\SharedLib.NetCore.csproj" />
  </ItemGroup>

</Project>
```

### Sample
 ```
static void Main(string[] args)
        {
    
            string hubName = "DtfSampleHub2";
            IOrchestrationServiceInstanceStore instanceStore = new AzureTableInstanceStore(hubName, m_StorageConnStr);

            var orchestrationServiceAndClient = new ServiceBusOrchestrationService(m_ConnStr, hubName, instanceStore, null, null);

            orchestrationServiceAndClient.CreateIfNotExistsAsync().Wait();

            m_TaskHubWorker = new TaskHubWorker(orchestrationServiceAndClient);
          
            m_TaskHubWorker.AddTaskOrchestrations(typeof(TimerOrchestration));
            m_TaskHubWorker.AddTaskOrchestrations(typeof(HelloOrchestration));
            m_TaskHubWorker.AddTaskActivities(typeof(SchedulerTask), typeof(UserInputTask), typeof(PlayFileTask));

            
            m_TaskHubWorker.StartAsync().Wait();

            Thread.Sleep(int.MaxValue);
        }
```

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by SeanFeldman** [comment]
@ddobric Microsoft.Azure.DurableTask.ServiceBus is referencing the old client, WindowsAzure.ServiceBus. Which is not related to this client here.

**Comment by shankarsama** [comment]
This issue should be assigned to DurableTask framework (https://github.com/Azure/durabletask)

**Comment by simonporter** [comment]
Microsoft.Azure.DurableTask.ServiceBus prior to version 2.1.3 did not support DotNetCore. Version 2.0.10 of Microsoft.Azure.DurableTask.ServiceBus has Microsoft.Azure.DurableTask.Core version 2.0.10 as a dependency, the project it set to reference a newer version explictly.
Recommend using Microsoft.Azure.DurableTask.ServiceBus 2.1.3 and not explicitly calling in a different version of Microsoft.Azure.DurableTask.Core.
