### ISSUE TITLE
WebSiteUpdateConfigurationParameters should not create empty collections

### ISSUE THREAD

**Issue by markrendle** [Azure/azure-sdk-for-net#639]
In the `WebSiteUpdateConfigurationParameters` [constructor](https://github.com/Azure/azure-sdk-for-net/blob/master/src/WebSiteManagement/Generated/Models/WebSiteUpdateConfigurationParameters.cs#L298-L305), the `AppSettings`, `ConnectionStrings`, `DefaultDocuments`, `HandlerMappings` and `Metadata` properties are set to empty collections instead of null. The REST API interprets an empty collection as **Delete any existing settings**. These properties should be null, which the REST API interprets as **No change**.<p><a href="https://github.com/Azure/azure-sdk-for-net/issues/639">https://github.com/Azure/azure-sdk-for-net/issues/639</a></p>

**Comment by shahabhijeet** [comment]
please reopen if this is still an issue.
