### ISSUE TITLE
[ServiceFabricProcessor] ServiceFabricProcessor should accept IFabricPartitionLister as extensibility point

### ISSUE THREAD

**Issue by pwlodek** [Azure/azure-sdk-for-net#6399]
**Problem statement**
Currently, ServiceFabricProcessor assumes default partition lister, which is not possible to override, and is internal. I have a specific case where I want to control which SF partition reads which Event Hub partition. With current implementation, it is impossible to achieve without forking the library.

**Solution**
Please accept IFabricPartitionLister instance in ServiceFabricProcessor constructor to allow more extensibility (Open/Close principle)

**My Case explanation**
I have an event hub with X partitions , and IoT solution where devices ingest messages on the EV, the EV is partitioned by device id. I have a SF stateful service with a matching number of partitions. Each stateful partition also has per device data, so it is partitioned by the same device id. Now I need to make sure that the SF partition which has data for device say with id A happens to be the partition which accepts traffic from an EH partition which has events from device A. This is required because I have other stateless service which injects device specific data to SF stateful partition. So that stateless service needs to know which SF stateful partition will be processing data for each device. And to do that, I need to control have SF partitions are assigned to EH partitions.

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by jsquire** [comment]
@JamesBirdsall, @serkantkaraca, would one of you be kind enough to offer your thoughts?

**Comment by JamesBirdsall** [comment]
Thank you for providing such a detailed explanation of your scenario! This sort of feedback -- learning how customers are using Service Fabric and how they want to consume Event Hubs within that -- is exactly what we hoped for with this preview.

For the moment, you can do what you want right now via ServiceFabricProcessor.MockMode. To make it formally public, I could add it to the ServiceFabricProcessor constructor as an optional argument that defaults to null (use ServiceFabricPartitionLister). Does that sound reasonable?

**Comment by pwlodek** [comment]
Yes, this is exactly what I would like to see.

**Comment by jfggdl** [comment]
@jamesbirdall, do you have in mind a release date?

**Comment by JamesBirdsall** [comment]
We have received a number of good suggestions for API changes. I hope to get 0.6 with those changes out by the end of the month.

**Comment by samuelkoppes** [comment]
We are verifying the state of this issue, and will report back with a status update by 11/4/2020.

**Comment by kasun04** [comment]
The Microsoft.Azure.EventHubs.ServiceFabricProcessor package is in preview and there are no plans for a stable release. This package will soon be deprecated and therefore we won't be taking any changes.
