### ISSUE TITLE
Can't import existing app service certificate into new resource group

### ISSUE THREAD

**Issue by Patafoin** [Azure/azure-sdk-for-net#6409]
**Describing the problem** 

Using SDK I create a new resource group and a web app. I wan't to reuse a wildcard SSL app service certificate that already exists and which is stored into another resource group within its keyvault.
When creating the ssl binding through the certificate thumbprint, it says that the certificate is not found.
I need to import existing app certificate into my newly resource group and don't know how to do this.

**Step to reproduce the problem**
From the azure portal, manually create a resource group called "xxx-backup-RG" and buy a wildcard ssl certificate and store it into this new RG. It will prompt you to create a keyvault to store the secret, go through the procedure.
Then, using Azure SDK, create a new resource group called "xxx-web-RG", create an app plan, a web app, create the webapp hostname and then try to bind your ssl certificate.

````
var resourceGroup = azure.ResourceGroups
                        .Define("xxx-web-RG")
                        .WithRegion(ResourcesHelper.Location)
                        .Create();

var servicePlan = azure.AppServices.AppServicePlans.Define($"xxx-web-appplan")
                                             .WithRegion(ResourcesHelper.Location)
                                             .WithExistingResourceGroup(resourceGroup)
                                             .WithPricingTier(ResourcesHelper.AppServicePricing)
                                             .WithOperatingSystem(OperatingSystem.Windows)
                                             .WithCapacity(1)
                                             .WithPerSiteScaling(false)
                                             .Create();
var app = azure.WebApps
                        .Define($"xxx-myapp-webapp")
                        .WithExistingWindowsPlan(servicePlan)
                        .WithExistingResourceGroup(resourceGroup)
                        .Create();

webApp = webApp.Update()
                  .DefineHostnameBinding()
                  .WithThirdPartyDomain("myhost.com")
                  .WithSubDomain("webapp")
                  .WithDnsRecordType(CustomHostNameDnsRecordType.CName)
                  .Attach()
                  .Apply();

webApp.Update()
      .DefineSslBinding()
      .ForHostname("myhost.com")
      .WithExistingCertificate(ResourcesHelper.CertificateThumbPrint)
      .WithSniBasedSsl()
      .Attach()
      .Apply();
````

**How can you see where the problem really is**
Create the webapp resource group as describe with code above but remove the last call.
Go to Azure portal, open your webapp custom domain parameters.
You will see your custom domain flagged not secure and a "add ssl binding" link.
Click on this link and then you will see a blade that asks for importing the app service certificate with two options : 
- with PFX file
- By finding it from subscription resources
If you choose the second option, you will find your certificate and by choosing it, you will be able to create your binding through a second blade.

If you try now to create a new resource group fully manually through azure portal with exactly the same resources and go to add ssl binding, you won't have the first blade which asks to import the certificate, you will have the second one directly as if your certificate was already available.

**Alternate solution**
Before using Azure SDK to create our environments, we used ARM templates.
The step to import our certificate before creating ssl bindings is done with this chunk of code : 

```
{
      "type": "Microsoft.Web/certificates",
      "name": "MyCertificateName",
      "apiVersion": "2016-03-01",
      "location": "[variables('Location')]",
      "properties": {
        "keyVaultId": "[parameters('keyvaultId')]",
        "keyVaultSecretName": "[parameters('KeyvaultSecretName')]",
        "thumbprint": "[parameters('certThumbprint')]"
      },
      "dependsOn": [
        "[concat('Microsoft.Web/serverfarms/', variables('WebAppAppPlanName'))]"
      ]
    },
```

**What I want to do**
All I want is being able to create my ssl bindings by making my certificate available into my newly resource group.
Thanks

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! It looks like this is an issue with our fluent libraries for .Net, so I'm going to transfer the issue to the appropriate repo.

**Comment by Patafoin** [comment]
Thank you. Do you know a workaround using web API for example to do this ?

**Comment by Patafoin** [comment]
Same problem was solved for the java library.
https://github.com/Azure/azure-libraries-for-java/issues/182

**Comment by jamesholwell** [comment]
If I'm understanding your issue correctly, we had this issue too - and initially managed to work around it by "recreating" the certificate in the new resource group and then referencing it by thumbprint. This stopped working at some point recently and I think it's because Azure doesn't want you to have the same thumbprint in the same location twice for a single subscription (irrespective of which resource group it is in).

So our new workaround was to:
-  assign the certificate to an app service in the 'first' resource group, which creates the hidden `microsoft.web/certificates` resource in the 'first' resource group
- get this certificate using the Fluent interface on the 'first' resource group `Azure.AppServices.AppServiceCertificates.GetByResourceGroupAsync()`
- get the binding for the app service in the 'second' resource group using `appService.GetHostNameBindingsAsync()`, set the Thumbprint and SslType directly on the Inner, then use the lower level `Azure.WebApps.Inner.CreateOrUpdateHostNameBindingAsync` interface to apply the updated Inner back into the app service

I think the root cause is that the Fluent interface doesn't expect you to supply a certificate from a different resource group. It would be ace to add an `WithExistingCertificate(IAppServiceCertificate certificate)` overload to the builder that doesn't try to be clever and just passes the certificate along without trying to "re-find" it in the resource group.

**Comment by isra-fel** [comment]
Sorry for late response. @weidongxu-microsoft could you help with this issue? Thank you!

**Comment by weidongxu-microsoft** [comment]
@Patafoin
@jamesholwell

The bug was fixed a few versions before (now it try find the Thumbprint from all app certificates across resource groups). Please try latest 1.33.0

**Comment by steeve49** [comment]
@weidongxu-microsoft I tried with the last version (1.33.0) but it doesn't work.
Can you please check my code in my first post please ? 
I would like to know if I missed one step.

Context : I already have a resourcegroup (lets say I named it "MyCertRg") with my wildcard ssl certificate

1. I create a new resourcegroup (I name it "MyNewEnvRg")
2. I create an App Plan
3. I create a webApp
4. I try to update my webapp using DefineHostnameBinding, DefineSslBinding and MyCertRg's certificate thumbprint

The fact that it works when I execute my arm template with the following code let me think I missed a SDK step to make it work without ARM 

`{
      "type": "Microsoft.Web/certificates",
      "name": "MyCertificateName",
      "apiVersion": "2016-03-01",
      "location": "[variables('Location')]",
      "properties": {
        "keyVaultId": "[parameters('keyvaultId')]",
        "keyVaultSecretName": "[parameters('KeyvaultSecretName')]",
        "thumbprint": "[parameters('certThumbprint')]"
      },
      "dependsOn": [
        "[concat('Microsoft.Web/serverfarms/', variables('WebAppAppPlanName'))]"
      ]
    },`

Do you think so ?

**Comment by weidongxu-microsoft** [comment]
Let's track it in azure-libraries-for-net https://github.com/Azure/azure-libraries-for-net/issues/961

**Comment by ltkvien** [comment]
> * get this certificate using the Fluent interface on the 'first' resource group `Azure.AppServices.AppServiceCertificates.GetByResourceGroupAsync()`
Maybe I have the same issue with PowerShell and the error is: **New-AzWebAppSSLBinding : Operation returned an invalid status code 'NotFound'** .

**Comment by ltkvien** [comment]
> If I'm understanding your issue correctly, we had this issue too - and initially managed to work around it by "recreating" the certificate in the new resource group and then referencing it by thumbprint. This stopped working at some point recently and I think it's because Azure doesn't want you to have the same thumbprint in the same location twice for a single subscription (irrespective of which resource group it is in).
> 
> So our new workaround was to:
> 
> * assign the certificate to an app service in the 'first' resource group, which creates the hidden `microsoft.web/certificates` resource in the 'first' resource group
> * get this certificate using the Fluent interface on the 'first' resource group `Azure.AppServices.AppServiceCertificates.GetByResourceGroupAsync()`
> * get the binding for the app service in the 'second' resource group using `appService.GetHostNameBindingsAsync()`, set the Thumbprint and SslType directly on the Inner, then use the lower level `Azure.WebApps.Inner.CreateOrUpdateHostNameBindingAsync` interface to apply the updated Inner back into the app service
> 
> I think the root cause is that the Fluent interface doesn't expect you to supply a certificate from a different resource group. It would be ace to add an `WithExistingCertificate(IAppServiceCertificate certificate)` overload to the builder that doesn't try to be clever and just passes the certificate along without trying to "re-find" it in the resource group.
Maybe I have the same issue with PowerShell and the error is: **New-AzWebAppSSLBinding : Operation returned an invalid status code 'NotFound'** .
