### ISSUE TITLE
[BUG] Computer Vision OCR sample bug

### ISSUE THREAD

**Issue by LukeBayler** [Azure/azure-sdk-for-net#6424]
**Describe the bug**
Text not properly recognized in attached image. This happens with sample in the repo listed below (also here: https://github.com/Azure-Samples/cognitive-services-dotnet-sdk-samples/blob/master/samples/ComputerVision/OCR/Program.cs), and happens when I use the Computer Vision SDK for Go. This image is in the image repo. Other images with cursive/handwritten text are recognized accurately.
![handwritten_text](https://user-images.githubusercontent.com/34659252/58517701-31deb300-8161-11e9-9280-4019b8affced.jpg)

***Exception or Stack Trace***
Recognizing text in a local image with OCR ...
Text:
Language: en
Text angle: 0
Orientation: Up
Text regions:
        Region bounding box: 102,27,384,87
        Line bounding box 102,27,58,27
                Word bounding box: 102,27,58,27
                Text: musAv
        Line bounding box 312,84,174,30
                Word bounding box: 312,92,17,21
                Text: in
                Word bounding box: 406,84,80,30
                Text: woacl

**To Reproduce**
Run this sample: https://github.com/Azure-Samples/cognitive-services-dotnet-sdk-samples/blob/master/samples/ComputerVision/OCR/Program.cs

**Expected behavior**
Text output should be:
You must be the change
you want to see in the world!

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : command-line
 - Version of the Java Library used: "Microsoft.Azure.CognitiveServices.Vision.ComputerVision" Version="4.0.0"
- Version of the Go Library used: 2.0

**Additional context**
None.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by toothache** [comment]
@LukeBayler, the sample code is using wrong API for calling OCR service. It's recommend to use `BatchReadFile` instead of `RecognizePrintedText`.

**Comment by LukeBayler** [comment]
Got it. Thanks. I'm working with the SDKs and don't see support for BatchReadFile in the Java SDK. Is that correct?

**Comment by toothache** [comment]
Yes. The Java SDK hasn't been updated for quite a long time. I submitted an issue for that.

https://github.com/Azure/azure-sdk-for-java/issues/3785

**Comment by TFR258** [comment]
Hi Luke,

The latest iteration of the Computer vision APIs has a new async operation called [Read ](https://westcentralus.dev.cognitive.microsoft.com/docs/services/computer-vision-v3-ga/operations/5d986960601faab4bf452005)which should perform well with handwritten text.

You can refer to this guide to get started in Java: https://docs.microsoft.com/en-us/azure/cognitive-services/computer-vision/quickstarts-sdk/client-library?pivots=programming-language-java

I hope this helps.
Thanks,
Tom
