### ISSUE TITLE
Infinite loop in DeleteRoleInstanceByDeploymentSlotAsync

### ISSUE THREAD

**Issue by BrandonBrowning** [Azure/azure-sdk-for-net#645]
Whenever I call this function, I'm getting a stackoverflow.  It seems to be caused by https://github.com/Azure/azure-sdk-for-net/blob/master/src/ComputeManagement/Generated/DeploymentOperations.cs#L4330<p><a href="https://github.com/Azure/azure-sdk-for-net/issues/645">https://github.com/Azure/azure-sdk-for-net/issues/645</a></p>

**Comment by markcowl** [comment]
This should be fixed.  Please reopen or open a new issue if yoiu see a recurrence
