### ISSUE TITLE
[FEATURE REQ] Support Managed Identity for ServiceBus management client

### ISSUE THREAD

**Issue by markgould** [Azure/azure-sdk-for-net#6462]
Re-creating this issue - https://github.com/Azure/azure-service-bus-dotnet/issues/603

Are there any updates/ETA on this?

**Comment by kurtzeborn** [comment]
Thank you for migrating this issue! We are routing it to the appropriate team for follow up.

This appears to be an ask for a new feature on the service itself (MSI in Service Bus), so tagging it "Service Attention".

**Comment by jfggdl** [comment]
Thanks for creating this issue. Would you please clarity which Management client you are referring to? This would help us with understanding the issue and any potential gaps in MI support. Thanks.

**Comment by markgould** [comment]
This is referring to the ManagementClient in the Azure Service Bus .NET Standard client library.

**Comment by markgould** [comment]
Here is the code sample from the original issue that reproduces the error:

```
        static void Main(string[] args)
        {
            var token = TokenProvider.CreateManagedServiceIdentityTokenProvider();           
            var client = new ManagementClient("sb://namespace.servicebus.windows.net/",  token);
            var desc = client.GetQueueAsync("QueueName").Result;
        }
```

If you use fiddler or some other method of looking at the raw request/response, you'll see the following error:

```
<Error><Code>401</Code><Detail>MalformedToken: Invalid authorization header: The request is missing WRAP authorization credentials. TrackingId:0910eebc-76b3-414a-b45d-fabca4df9477_G33, SystemTracker:[namespace].servicebus.windows.net:[queue], Timestamp:11/9/2018 4:36:45 PM</Detail></Error>
```

**Comment by jfggdl** [comment]
@markgould, Would you please provide the namespace name?

**Comment by markgould** [comment]
Are you asking for my ServiceBus namespace? If so, it's smidevmark.servicebus.windows.net

This is the exact code I'm trying to run from Visual Studio (which should pick up my Azure credentials)

```
var token = TokenProvider.CreateManagedServiceIdentityTokenProvider();
var client = new ManagementClient("sb://smidevmark.servicebus.windows.net/", token);
var desc = client.GetQueueAsync("QueueName").Result;
```

Error:

```
UnauthorizedException: MalformedToken: Invalid authorization header: The request is missing WRAP authorization credentials. TrackingId:7292e51b-081c-4e90-9abd-f06f63cc9e49_G0, SystemTracker:smidevmark.servicebus.windows.net:QueueName, Timestamp:2019-06-06T18:30:10
```

**Comment by ShubhaVijayasarathy** [comment]
This is coming end of June.

**Comment by fabiomilheiro** [comment]
@ShubhaVijayasarathy, thank you for letting us know that the fix for this was coming but I'm still hitting this error now with the latest version of Microsoft.Azure.ServiceBus (v3.4.0).

Could you confirm if there was a delay? And also a rough estimate please?

Thanks

**Comment by engenb** [comment]
I hope this issue doesn't go unnoticed because it was closed.  I am also seeing this same issue with Microsoft.Azure.ServiceBus 3.4.0

if this is helpful, here is a request I captured from ManagementClient.TopicExistsAsync

```
GET https://leasecrunchpreprod.servicebus.windows.net/Development_IntegrationEvent?api-version=2017-04&enrich=False HTTP/1.1
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IkN0ZlFDOExlLThOc0M3b0MyelFrWnBjcmZPYyIsImtpZCI6IkN0ZlFDOExlLThOc0M3b0MyelFrWnBjcmZPYyJ9.eyJhdWQiOiJodHRwczovL3NlcnZpY2VidXMuYXp1cmUubmV0LyIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0L2U4NTEzODU5LWZkMjctNGI4NS1iMjc1LWIyZjYxYWRhOGFjNC8iLCJpYXQiOjE1NjI1NDE5NjUsIm5iZiI6MTU2MjU0MTk2NSwiZXhwIjoxNTYyNTQ1ODY1LCJhY3IiOiIxIiwiYWlvIjoiNDJaZ1lLZ3cwcmd1THU5eSthZmQxbmZyWTdKZWl0MWszV04rOEZGVjk1eWlsN1hoajcwQSIsImFtciI6WyJwd2QiXSwiYXBwaWQiOiI4NzJjZDlmYS1kMzFmLTQ1ZTAtOWVhYi02ZTQ2MGEwMmQxZjEiLCJhcHBpZGFjciI6IjAiLCJmYW1pbHlfbmFtZSI6IkVuZ2VuIiwiZ2l2ZW5fbmFtZSI6IkJyaWFuIiwiZ3JvdXBzIjpbIjUzZmJiM2E0LWEzZWEtNDk2NC1iOGEyLTE5ZmNlMTAxM2Q3YSIsImYwOGMyY2FlLWFkNTItNDAwMy1hZWQ1LTk3MGEwYWFiZWIzOSJdLCJpcGFkZHIiOiI5OS4zNi45LjI0MSIsIm5hbWUiOiJCcmlhbiBFbmdlbiIsIm9pZCI6IjVkNmJiZDcxLTc3MzUtNDk3Yy05NzExLTNkNmU2MTYxOTNiZCIsInB1aWQiOiIxMDAzMjAwMDREQjdBRDhEIiwic2NwIjoidXNlcl9pbXBlcnNvbmF0aW9uIiwic3ViIjoiTS1jUGpFU1BCODNWeW9EaHVfRFB6bEw0S2FWTEMta2Ixb1E5OXltMGltUSIsInRpZCI6ImU4NTEzODU5LWZkMjctNGI4NS1iMjc1LWIyZjYxYWRhOGFjNCIsInVuaXF1ZV9uYW1lIjoiYnJpYW5AbGVhc2VjcnVuY2guY29tIiwidXBuIjoiYnJpYW5AbGVhc2VjcnVuY2guY29tIiwidXRpIjoiNWJFS2oxZzY2MFdVYldmMTBISmdBQSIsInZlciI6IjEuMCIsIndpZHMiOlsiNjJlOTAzOTQtNjlmNS00MjM3LTkxOTAtMDEyMTc3MTQ1ZTEwIl19.ZyXPZqJUMKGFQx0JZp-oTKSSgy66DjGyy4nbQ2_ZzPhgjNUpoeMOOXofWVld2t3acXJZAkp2UUj68qezSHCPDE6CkwSgeDOhjSfGsHuWsFaPZvT1iDw9ElwGpjwgpx9COfsV-AVrszfAooDmaVu2rJdi2w8q2zHR2pNgMGx5j85BrZys-H2w_XWN2qhW8Cv_OQKcaxjxboYHy3yHj58u2j4Kp3YSR8SdGwPBTbnMJr5A3zcr0pIAUtmnCiIwDw8pc9nyLvKg0A3gAxBfcTBqFJyt9Qzx8kAR5GZrDH4yHuaSQbDISrWYMReI7FuGCAVjAtqmAndI6gYHFqGSSC_Olg
UserAgent: SERVICEBUS/2017-04(api-origin=.NETStandard,Version=v2.0;os=Microsoft Windows 10.0.17763 ;version=3.4.0.0;product=Microsoft.Azure.ServiceBus)
Host: leasecrunchpreprod.servicebus.windows.net
```

It looks like ManagementClient is getting a good token, using my Azure Service Authentication account set in Visual Studio.  However, ServiceBus seems to be expecting a different form of authorization.  I really need/want to take advantage of this feature, so if there's anything I can do to help please let me know @ShubhaVijayasarathy .

**Comment by markgould** [comment]
@kurtzeborn @jfggdl can this issue be re-opened or can we get some clarification please?

**Comment by jfggdl** [comment]
@markgould, Yes. I could reopen it, but I will do something better. I want to make sure that you are able to reopen it without a problem. Please confirm to me you are not able to reopen it. By asking me to reopen it, it seems that you cannot re-open the issue.

**Comment by markgould** [comment]
I'm pretty sure on github if someone else closes an issue, I can't reopen it. I don't see any option to reopen the issue anywhere.

**Comment by jfggdl** [comment]
@markgould, thank you for that feedback. We were under the impression that the community, especially the user who created the issue could reopen it once it was closed. I am working to understand how we can fix this.

**Comment by engenb** [comment]
I think the last we heard from @ShubhaVijayasarathy, a June release was being targeted to resolve this.  Assuming that means this is nearly released, could we get an updated timeline, please?  I don't need anything specific.  I just need to know if I can afford to wait for this or if I need to start wiring up KeyVault for ServiceBus credentials.  Thanks!

**Comment by engenb** [comment]
this appears to have been resolved with the recent [4.0.0 release](https://github.com/Azure/azure-sdk-for-net/releases/tag/Microsoft.Azure.ServiceBus_4.0.0)

**Comment by markgould** [comment]
Have you had chance to try it? I'm getting the following error:

> 'InvalidIssuer: Token issuer is invalid. TrackingId:d5018c6c-9c15-4f56-a218-daa562744f82, SystemTracker:NoSystemTracker, Timestamp:2019-08-12T19:50:17'

**Comment by serkantkaraca** [comment]
Can you provide sample code causing this failure? You may hide your namespace and secure identity.

**Comment by markgould** [comment]
@serkantkaraca turns out this was simply due to Visual Studio changing my active Azure account to my personal instead of work. Changed it back and confirmed all is good with both 4.0.0 and 3.4.0.

We can consider this resolved!
