### ISSUE TITLE
NUnit tests do not fail on exceptions in one-time teardown

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#6467]
https://github.com/nunit/nunit/issues/2466#issuecomment-401202218

**Comment by kurtzeborn** [comment]
CC: @weshaggard, @chidozieononiwu

**Comment by kurtzeborn** [comment]
@pakrym, not sure what's wanted here.  If there's an ask of the engineering system team please provide more context.  Otherwise, we're going to assume you're using this to track your own work.

**Comment by pakrym** [comment]
Not sure anything can be done here. Problem is that when you throw in `[OneTimeTeardown]` method of the test class the test won't fail and would just produce a warning. This might hide test issues in the long run. 

One possible thing is to look at test trx reports after the run and fail the build if any warnings are found.

**Comment by pakrym** [comment]
Non-actionable without a fix in NUnit that is not likely to happen.
