### ISSUE TITLE
[QUERY] EventHubs ServiceFabricProcessor Checkpointing

### ISSUE THREAD

**Issue by fredxfred** [Azure/azure-sdk-for-net#6471]
**Query/Question**

How is the checkpointing with ServiceFabricProcessor (.NET) achieved? Does it work at all?

I recently restarted a SFP cluster (and changed the consuming key) and noticed that the egress spike after restart was much more than the accumulated backlog from the few minutes the cluster was down. I'm guessing this means that events are getting consumed again? I know that checkpointing with EPH is done using Azure storage but since I didn't provide any azure storage credentials, and I haven't been able to find the right location for checkpointing in the source code, I'm worried there isn't any checkpointing at all, or that it is tied to the receiving key (as opposed to the consumer group).

***Why is this not a Bug or a feature Request?***
It is a feature request *if* the checkpointing is unimplemented.

 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Query Added
- [ N/A] Setup information Added

**Comment by jsquire** [comment]
@JamesBirdsall and @serkantkaraca, would you be so kind as to offer your thoughts?

**Comment by JamesBirdsall** [comment]
Checkpointing is implemented using ReliableDictionary provided by Service Fabric. Take a look at the CheckpointAsync methods on PartitionContext -- just call one of those from inside your implementation of IEventProcessor.ProcessEventsAsync to set a checkpoint.
