### ISSUE TITLE
Improve how we handle encode for Base64URL to string on KeyVault API

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#6476]
See more information in discussion: https://github.com/Azure/azure-sdk-for-net/pull/6457#discussion_r290083103

**Comment by AlexGhiondea** [comment]
Does this make sense to be in the Json package?

**Comment by heaths** [comment]
There are more efficient ways of doing base64 encoding that including building our own singleton table, in which we could have the right characters already and eliminate padding in the first place. But we should probably do this in core, so punting to post-preview 5 and moving to Core.

**Comment by pakrym** [comment]
I don't think the usage is performance-critical, we can reopen if it is.

**Comment by heaths** [comment]
@tg-msft, doesn't Storage use base64url encoding quite a bit for blogs or something?

**Comment by tg-msft** [comment]
We do it in a couple of places, but I don't think any of them are performance critical for Storage scenarios.
