### ISSUE TITLE
Issues with Websites.Create API

### ISSUE THREAD

**Issue by shashankshrivastava** [Azure/azure-sdk-for-net#648]
&gt;&gt;Bug in WebSites.Create API allowing Invalid characters in website name. Only hyphens and alphanumeric characters should be allowed. As a result, the created Website is in unstable state in the system and always throws 500. 
&gt;&gt;It also creates the website in &quot;free&quot; mode by default even if we set the compute mode as &quot;dedicated&quot;
&gt;&gt;SiteMode has only 2 options - Basic and Limited. &quot;Standard&quot; is missing.<p><a href="https://github.com/Azure/azure-sdk-for-net/issues/648">https://github.com/Azure/azure-sdk-for-net/issues/648</a></p>

**Comment by shahabhijeet** [comment]
please reopen if this is still an issue.
