### ISSUE TITLE
Could not load file or assembly Microsoft.Azure.EventHubs.ServiceFabricProcessor. SecurityException: Strong name validation failed.

### ISSUE THREAD

**Issue by AlexZbn** [Azure/azure-sdk-for-net#6484]
We are trying to use Microsoft.Azure.EventHubs.ServiceFabricProcessor, Version=0.5.2.0 in our Azure service fabric stateful service ( .NET Framework 4.7.2) and receiving the error: 
Could not load file or assembly 'Microsoft.Azure.EventHubs.ServiceFabricProcessor, Version=0.5.2.0, Culture=neutral, PublicKeyToken=7e34167dcc6d6d8c' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)'

***Exception or Stack Trace***
Exception: System.IO.FileLoadException|
Message: 'Could not load file or assembly 'Microsoft.Azure.EventHubs.ServiceFabricProcessor, Version=0.5.2.0, Culture=neutral, PublicKeyToken=7e34167dcc6d6d8c' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)'
Stack trace: 
   at WebHooksProcessor.WebHooksProcessor.<RunAsync>d__3.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at WebHooksProcessor.WebHooksProcessor.RunAsync(CancellationToken cancellationToken)

**To Reproduce**
Try to use ServiceFabricProcessor in a .NET Framework stateful service

***Code Snippet***

        internal sealed class WebHooksProcessor : StatefulService
	{
		private bool _keepGoing = true;

		public WebHooksProcessor(StatefulServiceContext context)
			: base(context)
		{
		}

		protected override async Task RunAsync(CancellationToken cancellationToken)
		{
			try
			{
				EventProcessorOptions options = new EventProcessorOptions();
				options.OnShutdown = OnShutdown;
				ServiceFabricProcessor processorService = new ServiceFabricProcessor(Context.ServiceName, Context.PartitionId, StateManager, Partition,
					new HookEventsProcessor(), "Connection string", "$Default", options);

				Task processingTask = processorService.RunAsync(cancellationToken);

				while (_keepGoing)
				{
					Thread.Sleep(1000);
				}

				await processingTask;
			}
			catch (Exception ex)
			{
				ServiceEventSource.Current.Message("WebHooksProcessor.RunAsync() error: {0}", ex);
			}
		}

		private void OnShutdown(Exception e)
		{
			_keepGoing = false;
		}
	}

**Expected behavior**
Provides events from EventHub for IEventProcessor implementation without errors

**Screenshots**
![image](https://user-images.githubusercontent.com/51408618/58962254-a1d9e280-87cc-11e9-9e36-e8117cca7e14.png)

**Setup (please complete the following information):**
 - OS: Windows 10 v. 1809
 - IDE : Visual Studio Enterprise 2017
 - Version of the Library used: Microsoft.Azure.EventHubs.ServiceFabricProcessor, Version=0.5.2.0

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by weshaggard** [comment]
I just confirmed that the 5.2.0 version of the library on nuget https://www.nuget.org/packages/Microsoft.Azure.EventHubs.ServiceFabricProcessor/0.5.2 is delay signed and not fully signed. 

@jsquire do you know who would be the correct person to produce a new build to fix this issue?

**Comment by jsquire** [comment]
@AlexGhiondea:  This should be a small change with minor version bump.   Any objections to me doing this as a one-off?

@serkantkaraca: Are there any concerns around doing a release of ServiceFabricProcessor with bump to `0.5.3` just to push it through the central engineering system with a new signature?

**Comment by AlexZbn** [comment]
Hello, is there any progress?

**Comment by jsquire** [comment]
Hi @AlexZbn.  Apologies for the delay;  we've cut a new build and validated the signature.  The package is queued to be published, so it should be available in the next couple of days.  Once I've got confirmation, I'll ping this issue to let you know.

**Comment by jsquire** [comment]
@AlexZbn:  The new package has been published, and can be found here:  https://www.nuget.org/packages/Microsoft.Azure.EventHubs.ServiceFabricProcessor/0.5.3.    Please let us know if you run into any further difficulties.

**Comment by AlexZbn** [comment]
Thank you!
