### ISSUE TITLE
Small documentation typo in DeploymentGetResponse

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-sdk-for-net#649]
In Microsoft.WindowsAzure.Management.Compute.Models.DeploymentGetResponse
```
        //
        // Summary:
        //     The virtual IP addresses that are specified for thedeployment.
        public IList VirtualIPAddresses { get; set; }
```

'thedeployment' part above.<p><a href="https://github.com/Azure/azure-sdk-for-net/issues/649">https://github.com/Azure/azure-sdk-for-net/issues/649</a></p>

**Comment by markcowl** [comment]
Please reopen if you're still seeing this issue.
