### ISSUE TITLE
Make sure we have READMEs in service folders

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk-for-net#6502]
We should have service specific README files in folders corresponding to services, e.g.
https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage

**Comment by pallavit** [comment]
@KrzysztofCwalina This is a really old bug but I do see readme in each folder now. Can this be resolved now?

**Comment by pallavit** [comment]
Closing this issue since we have readme's available. Let feel free to reopen if I misinterpreted the question here.
