### ISSUE TITLE
Contributing.md has outdated build instructions

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk-for-net#6503]

**Comment by weshaggard** [comment]
@chidozieononiwu is working on updating the docs in https://github.com/Azure/azure-sdk-for-net/pull/6368. It is currently on pause as he is finishing up the directory restructuring work.

**Comment by weshaggard** [comment]
Updated with https://github.com/Azure/azure-sdk-for-net/pull/6368.
