### ISSUE TITLE
[BUG] Property Body on CloudException is null

### ISSUE THREAD

**Issue by leagallino** [Azure/azure-sdk-for-net#6512]
**Describe the bug**
The property Body is null on CloudException when the exception is created from a bad request to https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.Network/locations/{location}/usages?{api_version}

I found that the error is happening because the response is an scaped string and not a Json, so the Deserialize throw a JsonException and the Body is never set for that reason.

***Exception or Stack Trace***

**To Reproduce**
Send a proper request to the endpoint mentioned above with a not supported location in order to get a Bad Request response.
Try to parse the Response Content to a CloudError Object
Catch the JsonException.

***Code Snippet***
From https://github.com/Azure/azure-sdk-for-net/commit/149dd1b6b4889f5c3b730aa86eaa3e41ec451604 Operation.cs

`var ex = new CloudException(string.Format("Operation returned an invalid status code '{0}'", _statusCode));
                try
                {
                    _responseContent = await _httpResponse.Content.ReadAsStringAsync().ConfigureAwait(false);
                    CloudError _errorBody =  Rest.Serialization.SafeJsonConvert.DeserializeObject<CloudError>(_responseContent, Client.DeserializationSettings);
                    if (_errorBody != null)
                    {
                        ex = new CloudException(_errorBody.Message);
                        ex.Body = _errorBody;
                    }
                }
                catch (JsonException)
                {
                    // Ignore the exception
                }`

**Expected behavior**
Get a well formated Json
Parse the Json
Map to CloudError properly

**Screenshots**
![image](https://user-images.githubusercontent.com/22958280/59115069-db226780-891e-11e9-8c98-dc0c7365fa19.png)

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : Visual Studio Professional 2017
 - Version of the Library used

**Additional context**

**Information Checklist**
- [ X ] Bug Description Added
- [ X ] Repro Steps Added
- [ X ] Setup information Added

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by erich-wang** [comment]
@leagallino , somehow I got well format json when using postman. Could you share your code snippet to repro the error? Please also provide package info, thanks.

**Comment by leagallino** [comment]
Hello, I lost what I've done, but doing something like this I get into the catch because the json came malformed with the extra quotes at the beginning and the end. (I was using the last version of the package)

```
using (var httpClient = new HttpClient())
            {
                var response = httpClient.SendAsync(request).Result;
                try
                {
                    var result = JsonConvert.DeserializeObject<CloudError>(response.Content.ReadAsStringAsync().Result);
                }
                catch (JsonException ex)
                {
                    // Ignore the exception
                }
            }
```

Let me know if this is useful.

**Comment by erich-wang** [comment]
With version 19.12.0-preview of Management.Network, CloudError is deserialized properly as below:
![image](https://user-images.githubusercontent.com/20198527/61360935-08651c80-a8b2-11e9-9c35-727aeaf01651.png)

Please let  me know if any other concern, thanks.

**Comment by erich-wang** [comment]
@leagallino , the issue could not be reproduced and don't get response for 10 days, so close it. Please feel free to reopen it if you could reproduce it, thanks.
