### ISSUE TITLE
Add code coverage reporting 

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#6513]
Something, like we have in corefx, would've been perfect.

**Comment by chidozieononiwu** [comment]
PR https://github.com/Azure/azure-sdk-for-net/pull/14185 is out for this, with sample publish [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=493604&view=codecoverage-tab)
A side not is that the [html site](https://azuresdkartifacts.blob.core.windows.net/azure-sdk-for-net/Code%20Coverage/index.html) looks better that when its embedder in the code coverage tab.
