### ISSUE TITLE
Unable to restore purged secret in soft-delete vault

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#6514]
Tracking disabled test.

Repro:

```
$keyname = "TestKey3"
$keyvault = "pakrym-keyvault"

az keyvault secret set --vault-name $keyvault --name $keyname --value Nice
az keyvault secret backup --vault-name $keyvault --name $keyname --file-path bu-$keyname
az keyvault secret delete --vault-name $keyvault --name $keyname
az keyvault secret purge --vault-name $keyvault --name $keyname

# retry purge untill succeeds
while ($LASTEXITCODE -ne 0)
{
    az keyvault secret purge --vault-name $keyvault --name $keyname
}

# make sure secret got purged

az keyvault secret show-deleted --vault-name $keyvault --name $keyname

while ($LASTEXITCODE -eq 0)
{
    az keyvault secret show-deleted --vault-name $keyvault --name $keyname
}

az keyvault secret restore --vault-name $keyvault --file-path bu-$keyname

```

**Comment by pakrym** [comment]
cc @schaabs

**Comment by maririos** [comment]
I might be missing something here, but once you purge, there is no way to recover the secrets, so show-deleted will fail.
show-deleted will show you the secrets that are marked for delete (https://docs.microsoft.com/en-us/rest/api/keyvault/getdeletedsecret/getdeletedsecret) and only those are the ones you can recover

**Comment by pakrym** [comment]
I expect show-deleted to fail but restore operation that uses a local copy of the key should succeed https://docs.microsoft.com/en-us/rest/api/keyvault/restoresecret/restoresecret

**Comment by heaths** [comment]
We've implemented delete and purge as LROs.

**Comment by pakrym** [comment]
How does having an lro fix the issue I've described?

**Comment by heaths** [comment]
I misunderstood. Un-ignoring those tests, I see the issue still repros and have contact the service team directly. Unfortunately, we have no effective way of monitoring a purge operation like we did for delete and recover, which we turned into LROs for GA.

**Comment by heaths** [comment]
Ping @RandalliLama

**Comment by RandalliLama** [comment]
@pakrym is the issue that there is no way to determine when the purge has actually completed?

**Comment by heaths** [comment]
He's OOF, but, yes, the issue is there is no way to know when the purge actually completed such that you could create a new one or restore an existing one from backup. Though, I suppose you could just try until either of those operations succeeds, but seems like a hacky workaround.

**Comment by pakrym** [comment]
Especially considering purge is a long-running operation. LRO being completed should signify that the secret was fully purged.

**Comment by sebansal** [comment]
We do not have a command to review the pending state.
Recommendation is that the customer should retry after few minutes.
