### ISSUE TITLE
Service Bus RBAC:  Revisit Naming and Discoverability of Public API Changes

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#6548]
# Summary

The recent set of changes to the Service Bus client library made for the RBAC feature made a set of changes to the API surface, garnering some feedback with respect to its discoverability and naming.  Due to sensitivity around timing, the changes were merged to facilitate internal testing of the feature.  Before public release, another review pass for naming would be helpful to ensure a good user experience for the API.

# Scope of Work

- Revisit feedback from the [RBAC pull request](https://github.com/Azure/azure-sdk-for-net/pull/6393) (#6393) and continue discussion and evaluation of the feedback.

- As an outcome of review and discussion, adopt or defer/decline feedback around the API surface, naming, types, and other constructs.

- Refactor, as needed, to incorporate the agreed upon set of changes.

# Out of Scope

- Large changes to implementation that would alter the tested feature set or functionality.

- A full review of the API surface; the discussion will be scoped to the changes made for RBAC in order to limit the impact on existing consumers.

# Success Criteria

- Feedback on the API naming and discoverability has been vetted and explicitly accepted, deferred, or declined.

- Accepted changes have been made and submitted via pull request.

# References

- [ServiceBus SDK: Rbac support](https://github.com/Azure/azure-sdk-for-net/pull/6393) (#6393)

**Comment by bainian12345** [comment]
Please see [this PR](https://github.com/Azure/azure-sdk-for-net/pull/6578) for addressing this issue.
