### ISSUE TITLE
Create premium KeyVault to test EC and RSA HSM keys

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#6551]
When trying to create an EC or RSA key with `hsm=true`, the current KV we use fails with: 
`Hardware key operation not allowed on standard vault`.
Looks like if we create and run tests against a Premium KV, the problem will be fixed

**Comment by heaths** [comment]
This is "now" (a few months ago, but I missed this bug) done in our sdk\keyvault\test-resources.json and we have some tests using it.
