### ISSUE TITLE
Track 2 live tests do not run in nigtly builds

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#6555]
Because we have two solutions and only Track 1 solution is used for testing.
cc @weshaggard @AlexGhiondea

**Comment by weshaggard** [comment]
@pakrym do you know what secrets are needed to run these live tests?

**Comment by pakrym** [comment]
No, unfortunately I don't 

cc @maririos

**Comment by maririos** [comment]
Is this related to KeyVault? This was done already thanks to @danieljurek change. 
KV is running nightly live tests

**Comment by pakrym** [comment]
Live tests runs are still failing https://dev.azure.com/azure-sdk/internal/_build?definitionId=234&_a=summary

**Comment by maririos** [comment]
Track1 are yes. They've always failed. We have a thread on email about it.
Looks like @schaabs is going to disable those tests for now

**Comment by maririos** [comment]
For what this issue addresses, everything was done, so we should close it
