### ISSUE TITLE
Unable to connect to DocumentDB (CosmoDB)

### ISSUE THREAD

**Issue by csreddyennam** [Azure/azure-sdk-for-net#6561]
**Describe the bug**
When we connect o DocumentDB, unable to open connection to cosmoDB.
The same work when we have .Net Core 2.0
Below are the version we are using:
.Net Core 2.2
Package used: <PackageReference Include="Microsoft.Azure.DocumentDB.Core" Version="2.4.0" />
Visual studion: 2017 (15.9.12)

***Exception or Stack Trace***
InnerException = {System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Http.Connec...

["One or more errors occurred. (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond)","   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)\r\n   at System.Threading.Tasks.Task.Wait()\r\n   at webapi.Controllers.ValuesController.Get() in C:\\XXXi\\ConsoleApp1\\webapi\\Controllers\\ValuesController.cs:line 42 System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond\r\n   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)\r\n   at System.Threading.Tasks.ValueTask`1.get_Result()\r\n   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n   at System.Threading.Tasks.ValueTask`1.get_Result()\r\n   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)\r\n   at System.Threading.Tasks.ValueTask`1.get_Result()\r\n   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)\r\n   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n   at Microsoft.Azure.Documents.Client.DocumentClient.HttpRequestMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)\r\n   at Microsoft.Azure.Documents.Client.GatewayServiceConfigurationReader.GetDatabaseAccountAsync(Uri serviceEndpoint)\r\n   at Microsoft.Azure.Documents.Routing.GlobalEndpointManager.GetDatabaseAccountFromAnyLocationsAsync(Uri defaultEndpoint, IList`1 locations, Func`2 getDatabaseAccountFn)\r\n   at Microsoft.Azure.Documents.Client.GatewayServiceConfigurationReader.InitializeReaderAsync()\r\n   at Microsoft.Azure.Documents.Client.DocumentClient.InitializeGatewayConfigurationReader()\r\n   at Microsoft.Azure.Documents.Client.DocumentClient.GetInitializationTask(IStoreClientFactory storeClientFactory)\r\n   at Microsoft.Azure.Documents.Client.DocumentClient.EnsureValidClientAsync()\r\n   at Microsoft.Azure.Documents.Client.DocumentClient.OpenPrivateInlineAsync(CancellationToken cancellationToken)"]

**To Reproduce**
Open a console application of .Net Core 2.2 with package: <PackageReference Include="Microsoft.Azure.DocumentDB.Core" Version="2.4.0" />

***Code Snippet***
try
                {
                    
                    WebProxy proxyObject = new WebProxy("XXXX");
                    WebRequest.DefaultWebProxy = proxyObject;

                    HttpClientHandler handler = new HttpClientHandler()
                    {
                        Proxy = proxyObject,
                        UseProxy = true,
                    };

                    var accountKey = "XXX";

                    var databaseAccountName = "XXX";
                    var databaseEndPoint = new Uri(string.Format("https://{0}.documents.azure.com", databaseAccountName));
                    var databaseAccountKey = accountKey;
                    var connectionPolicy = new ConnectionPolicy
                    {
                        ConnectionMode = ConnectionMode.Gateway, //ConnectionMode.Gateway
                        ConnectionProtocol = Protocol.Https,
                        RetryOptions = new RetryOptions()
                        {
                            MaxRetryAttemptsOnThrottledRequests = 6,
                            MaxRetryWaitTimeInSeconds = 5
                        }
                    };

                    // var client = new DocumentClient(databaseEndPoint, databaseAccountKey, handler, connectionPolicy);
                    var client = new DocumentClient(databaseEndPoint, databaseAccountKey, connectionPolicy);
                    client.OpenAsync().Wait();

                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }

**Expected behavior**
Connection to DocumentDB (CosmoDB) should open with out error.

**Setup (please complete the following information):**
 - OS: Windows
 - IDE : Visual studion 2017 (15.9.12) 
 - Version of the Library Microsoft.Azure.DocumentDB.Core=> Version="2.4.0"

**Additional context**
Its working with .Net Core 2.0

**Comment by brjohnstmsft** [comment]
FYI @weshaggard @shahabhijeet We'll probably need help routing this to the right place. This issue affects multiple SDKs including Azure Search and Azure table storage, but only on .NET Core 2.2. Any ideas who this should be assigned to? Is it a more general issue with .NET Core?

**Comment by wmengmsft** [comment]
@csreddyennam, we will take a look.

Can you please kindly file this issue at https://github.com/Azure/azure-cosmos-table-dotnet/issues which is where issues related to Cosmos DB Table SDK are tracked and triaged? Thanks.

**Comment by csreddyennam** [comment]
Thanks, I have logged the issue @ https://github.com/Azure/azure-cosmos-table-dotnet/issues/6

**Comment by AlexGhiondea** [comment]
I will go ahead and close this issue since this is being tracked in the right repo now. Please reactivate if I missed anything
