### ISSUE TITLE
[BUG]Build Failure in Microsoft.Azure.Management.OperationalInsights.Test

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-for-net#6565]
**Describe the bug**
Build Broken due to missing type

***Exception or Stack Trace***
```
Helpers\TestHelper.cs(161,53): error CS0246: The type or namespace name 'StorageInsight' could not be found (are you missing a using directive or an assembly reference?) [C:\Git\azure-sdk-for-net\sdk\o
perationalinsights\Microsoft.Azure.Management.OperationalInsights\tests\Microsoft.Azure.Management.OperationalInsights.Test.csproj]
Helpers\TestHelper.cs(161,78): error CS0246: The type or namespace name 'StorageInsight' could not be found (are you missing a using directive or an assembly reference?) [C:\Git\azure-sdk-for-net\sdk\o
perationalinsights\Microsoft.Azure.Management.OperationalInsights\tests\Microsoft.Azure.Management.OperationalInsights.Test.csproj]
```

**To Reproduce**
Remove `<ExcludeFromBuild>true</ExcludeFromBuild>` and
`<ExcludeFromTest>true</ExcludeFromTest>` from `Microsoft.Azure.Management.OperationalInsights.Test`
Attempt build using `msbuild build.proj /t:Runtests /p:Scope=operationalinsights -v:m`

**Expected behavior**
Build Fails

**Comment by chidozieononiwu** [comment]
Build was failing before repo restructure.

**Comment by jsquire** [comment]
Given the age of this issue and the deprecation of most of the track one libraries, closing this as stale.  If the build is still failing, please file a new issue.
