### ISSUE TITLE
[BUG]Build Failure in Microsoft.Azure.Management.Monitor.Tests

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-for-net#6566]
**Describe the bug**
`useCommonAlertSchema` not specified in `EmailReceiver` constructor.

***Exception or Stack Trace***
```
Scenarios\ActionGroupsTests.cs(122,29): error CS7036: There is no argument given that corresponds to the required formal parameter 'useCommonAlertSchema' of 'EmailReceiver.EmailReceiver(string, string,
 bool, ReceiverStatus?)' [C:\Git\azure-sdk-for-net\sdk\monitor\Microsoft.Azure.Management.Monitor\tests\Microsoft.Azure.Management.Monitor.Tests.csproj]
```

**To Reproduce**
Remove `<ExcludeFromBuild>true</ExcludeFromBuild>` and
`<ExcludeFromTest>true</ExcludeFromTest>` from `Microsoft.Azure.Management.monitor.Tests`
Attempt build using `msbuild build.proj /t:Runtests /p:Scope=monitor -v:m`

**Expected behavior**
Build Fails

**Comment by chidozieononiwu** [comment]
Build was failing before repo restructure.

**Comment by isra-fel** [comment]
Fixed: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/monitor/Microsoft.Azure.Management.Monitor/tests/Microsoft.Azure.Management.Monitor.Tests.csproj#L12
