### ISSUE TITLE
System.Net.Http dependency should update to a newer version

### ISSUE THREAD

**Issue by brianholley** [Azure/azure-sdk-for-net#6579]
**Describe the bug**
Azure Sdk depends on an old version of System.Net.Http (4.3.0) with an active CVE: https://github.com/aspnet/Announcements/issues/239. This was previously discussed in 2017 with https://github.com/Azure/azure-sdk-for-net/issues/3176.

In the meantime, netstandard has updated to 2.0 which includes System.Net.Http 4.3.2, so it should be safe to bump the Azure sdk to reference that version. This itself should not be considered a security issue (more code hygiene) due to the standard library forcing use of the newer secure version.

***Exception or Stack Trace***
N/A

**To Reproduce**
1. Create a new netstandard or netcore class library
2. Reference any latest Azure sdk package (e.g. Microsoft.Azure.KeyVault 3.0.3)
3. Class library references insecure System.Net.Http library version 4.3.0

***Code Snippet***
N/A

**Expected behavior**
Expected that the latest versions of the Azure sdk reference secure dependencies

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: WIndows 10 1903 (build 18362.175)
 - IDE: Visual Studio Enterprise 2019 (16.1.3)
 - Version of the Library used: any latest (e.g. Microsoft.Azure.KeyVault 3.0.3)

**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by praries880** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

@shahabhijeet can you kindly take a look at this?

**Comment by AlexGhiondea** [comment]
It looks like the latest version of KV does have the updated version.

**Comment by weshaggard** [comment]
We have updated the version of this in the repo https://github.com/Azure/azure-sdk-for-net/blob/master/eng/Packages.Data.props#L80 so the next time we release any of the packages they will be referencing the higher version.
