### ISSUE TITLE
[BUG] Unable to use API KeyVaultClient.SignAsync() with RS256 algorithm

### ISSUE THREAD

**Issue by sharathppss** [Azure/azure-sdk-for-net#6602]
**Describe the bug**
Unable to use API KeyVaultClient.SignAsync() with RS256 algorithm.
Trying to generate a signature for a string using a key present on Azure key service.
https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.keyvault.keyvaultclientextensions.signasync?view=azure-dotnet

***Exception or Stack Trace***
- Operation returned an invalid status code 'BadRequest'(-2146233088)    at Microsoft.Azure.KeyVault.KeyVaultClient.<SignWithHttpMessagesAsync>d__54.MoveNext()--- End of stack trace from previous location where exception was thrown ---at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at Microsoft.Azure.KeyVault.KeyVaultClientExtensions.<SignAsync>d__2.MoveNext()--- End of stack trace from previous location where exception was thrown ---at 

**To Reproduce**
Not sure applicable. 

***Code Snippet***
Authentication Done:
```
private AzureKeyManager()
        {
            if (!string.IsNullOrEmpty(KeyVaultEndpoint))
            {
                var azureServiceTokenProvider = new AzureServiceTokenProvider();
                AzureKeyVaultClient = new KeyVaultClient(
                    new KeyVaultClient.AuthenticationCallback(
                        azureServiceTokenProvider.KeyVaultTokenCallback));
            }
        }
```
Below data generated as input for SignData. JsonWebKeySignatureAlgorithm.RS256 used as parameter.
```
var fileParamBytes = System.Text.Encoding.UTF8.GetBytes(fileParamJson);
```
```
 public async Task<string> SignData(string keyID, byte[] Data, string algo)
        {
            var operationResult = await AzureKeyVaultClient.SignAsync(keyID, algo, Data);

            var signature = Convert.ToBase64String(operationResult.Result);
            return signature;
        }
```

**Expected behavior**
Able to perform signing with UTF-8 encoded string. 

**Screenshots**

**Setup (please complete the following information):**
 - OS: NA
 - IDE : NA
 - Nuget Microsoft.Azure.KeyVault 3.0.3

**Additional context**
I have a web app deployed on Azure which talks to key service. The key service has appropriate access policy enabled. Encryption and Decryption APIs are working from the same setup.
**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [] Repro Steps Added
- [x] Setup information Added

**Comment by praries880** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by MikeNicholls** [comment]
Hi @sharathppss, are you passing `fileParamBytes` directly into `SignData`?  The documentation isn't very clear, but you actually need to hash the data yourself and pass the _digest_ into the `SignAsync` function.

If you're not already, try something like this:
```csharp
byte[] digestBytes = SHA256.Create().ComputeHash(fileParamBytes); // RS256 operates against an SHA-256 digest
var operationResult = await SignData(keyID, digestBytes, JsonWebKeySignatureAlgorithm.RS256);
```

**Comment by sharathppss** [comment]
Sorry of the last response, was not quite able to get back to this issue earlier.

The above suggestion worked. Thank you for the help.
