### ISSUE TITLE
Azuer Function + KeyVault + User Assigned Managed Identity inside a single resource group.

### ISSUE THREAD

**Issue by UMANGAWASTHY** [Azure/azure-sdk-for-net#6611]
Azuer Function + KeyVault + User Assigned Managed Identity inside a single resource group.
I am using Keyvault secrect to store sql server creditional and i am access this secrect inside azuer function v2(.net core) using User Assigned Managed Identity. 
While development on Visual Studio 2019 it is working . After publish to azuer it's not working.
It's throwing error like this :
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/****************. Exception Message: Tried the following 3 methods to get an access token, but none of them worked.
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/*******************. Exception Message: Tried to get token using Managed Service Identity. Access token could not be acquired. MSI ResponseCode: BadRequest, Response: 
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/******************. Exception Message: Tried to get token using Visual Studio. Access token could not be acquired. Visual Studio Token provider file not found at "D:\local\LocalAppData\.IdentityService\AzureServiceAuth\tokenprovider.json"
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/*************************. Exception Message: Tried to get token using Azure CLI. Access token could not be acquired. 'az' is not recognized as an internal or external command,
operable program or batch file.

This Is my code :
string connectionstring = "";
var provider = new AzureServiceTokenProvider();
var kv = new KeyVaultClient(new KeyVaultClient.AuthenticationCallback(provider.KeyVaultTokenCallback));
try
{
var secret = await kv.GetSecretAsync("https://abcdefgh.vault.azure.net/secrets/mysecrect/123456789012345678901234567890").ConfigureAwait(false);;
connectionstring  = secret.Value;
}
Catch(Exception ex)
{
throw ex;
}
Nuget dlls
Microsoft.Azure.Services.AppAuthentication 1.0.3 And 1.2.0-preview2
Microsoft.Azure.KeyVault 3.0.0

**Comment by praries880** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by nonik0** [comment]
@UMANGAWASTHY You are trying to use a user-assigned managed identity, correct? Could you try setting an AppAuth connection string to specify using the user-assigned managed identity, as below:

`RunAs=App;AppId={ClientId of user-assigned identity}`

**Comment by nonik0** [comment]
@UMANGAWASTHY You are trying to use a user-assigned managed identity, correct? Could you try using an [AppAuth connection string](https://docs.microsoft.com/en-us/azure/key-vault/service-to-service-authentication#connection-string-support) to tell AppAuth to specifically use the user-assigned managed identity? You can do this by passing the following connection string directly to the ASTP constructor, or setting the AzureServicesAuthConnectionString environment variable:

`RunAs=App;AppId={ClientId of user-assigned identity}`

Also, do you also have the system managed identity enabled for your Azure Function, or is it disabled?

**Comment by UMANGAWASTHY** [comment]
@nonik0 
RunAs=App;AppId={ClientId of user-assigned identity}

Thanks it's working.

**Comment by countchivas** [comment]
Thanks @nonik0 !
