### ISSUE TITLE
Is azure's open source project dotnetty still under maintenance?

### ISSUE THREAD

**Issue by fanliang11** [Azure/azure-sdk-for-net#6612]
Hello,azure community
           Please forgive me for submitting a issue here, I can't think of a better solution for [dotnetty](https://github.com/Azure/DotNetty) Author to answer our issues. [Dotnetty](https://github.com/Azure/DotNetty) is not maintained, no one has merged the request, reply to the issue, based on the dotnetty ecosystem has been established, Do not want dotnetty to die like this, my open source project surging is also based on dotnetty, wait for your reply, please do not give up after open source, so Will make us cool heart

**Comment by praries880** [comment]
@nayato @mikelchai  Can either of you take a look at this issue and redirect it appropriately?

Not marking this as a Cliwnt/Mgmt issue as it is neither.

**Comment by pakrym** [comment]
We're sorry but this repo is only tracking Azure SDK work.
