### ISSUE TITLE
Verify the Azure.Core TestFramework's Recording.Random seed between recording and playback

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#6615]
We need to make the same number of Random generator usage calls when recording and playing back tests for everything to line up.  We should see if there's a way to enforce that automatically (even if it's just saving and verifying the final Seed via reflection).

**Comment by christothes** [comment]
This one is pretty old and I'm not sure if it is still relevant. Currently we do save the seed in recordings, and the number and ordering of calls to generate random Ids is important to validating correctness of the recoding/playback. If I am missing something here, please re-open and clarify.
