### ISSUE TITLE
EventHubsSharedKeyCredential should allow the shared key to be updated

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#6618]
# Summary

The first preview of the track two Event Hubs client library exposed a credential type for using the shared key without a connection string; this type was based on the generic `TokenCredential` and accepted by the `EventHubClient` as a generic credential. 

There is no current means to allow for the key to be rotated after the credential was created; each refresh of the token will make use of the same shared key.   A means should be provided, ia method call, to provide a new shared key that will update the internal state and be used for generation of the next access token.

# Success Criteria

- The shared key held by the credential may be updated in-place without the need to stop processing or create a new token.

- The tests necessary for its validation have been created and pass reliably.

- The existing test suite continues to produce deterministic results and pass reliably.

**Comment by albertodenatale** [comment]
> to provide a new shared key that will update the internal state and be used for generation of the next access token

Hello 😁 

May I ask for a clarification?

Would that have the same effect of what would happen by clicking either of the following?

![image](https://user-images.githubusercontent.com/11591862/68942910-05b7fc80-07aa-11ea-8d16-6518252df970.png)

Or the method should be called by the developer after generating the new keys?

**Comment by jsquire** [comment]
The design in my head looks something like this, at the moment:

```csharp
public sealed class EventHubSharedKeyCredential : TokenCredential 
{
    public string SharedAccessKeyName { get; }
    
    public EventHubSharedKeyCredential(string sharedAccessKeyName, string sharedAccessKey);
    
    public override AccessToken GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken);
    public override ValueTask<AccessToken> GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken);
    
    // Planned enhancement (#6618)
    public void UpdateSharedAccessKey(string sharedAccessKeyName, string sharedAccessKey);
}
```

With the basic idea being that developers can call the `UpdateSharedAccessKey` method with a new name/value if they rotate credentials - like moving from primary to secondary or regenerating like you're showing.  The behavior would be that the internal state of the credential gets updated  and the next time `GetTokenAsync` is invoked, it uses the new `key.`

The bit trick is that we'll need to make some tweaks to `ConvertToSharedAccessSignatureCredential` and change that to something like `AsSharedAccessTokenCredential`, where we generate a `[SharedAccessSignatureCredential](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/src/Authorization/SharedAccessSignatureCredential.cs)` for the `EventHubsSharedKeyCredential` instance instead of cloning it into a new one.   (Each all to that method would get the same SharedAccessSignatureCredential back instead of a new credential)

We could then generate a new key and inject it into the `SharedAccessSignatureCredential` to force the update.   We'll need to add an internal `UpdateSignature` method to it as well.   I think that would make it appear a more important operation than just exposing the property/setter, since updating the signature has significance to it and side-effects in the wider system.

That's my brain dump.... but it's largely high level.   I welcome feedback, thoughts, or other ideas that you may have to improve on that.


https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/src/Authorization/SharedAccessSignatureCredential.cs

**Comment by jsquire** [comment]
> Hope you are well. I really enjoyed my previous contributions and I would love to challenge myself with this task if you are happy to?
> 
Absolutely.  You were wonderful to work with!   We'd love to have you continue being involved.

> In this regard, I would have some questions to ask you do not mind?
> 
Always.   It may take me a day or two when busy to loop back around, but please always feel free to reach out.

**Comment by albertodenatale** [comment]
> That's my brain dump.... but it's largely high level. I welcome feedback, thoughts, or other ideas that you may have to improve on that.

I think is very clear thank you. 

I will try to go on with that as much as I can, I will then come back to you.

Sitting at a high level, do you think it could be a valid idea having the ```EventHubsSharedKeyCredential``` constructor taking all the keys and passing them to ```SharedAccessSignatureCredential```?

Looking at ```SharedAccessSignatureCredential:::GetToken()``` the keys could then be automatically rotated when the ```SignatureExpiration``` has passed? 

That would offer an alternative to calling ```UpdateSharedAccessKey``` and arguably would tie nicely with what is already in place?

> Absolutely. You were wonderful to work with! We'd love to have you continue being involved.

Thank you this means a lot to me

**Comment by jsquire** [comment]
Closing, as the associated PR has been merged.   Thanks to @albertodenatale for contributing this feature!
