### ISSUE TITLE
[Devops] - Azure devops doesn't deploy on linux using dotnet 2.2 but shows succesfull 

### ISSUE THREAD

**Issue by Joseluismantilla** [Azure/azure-sdk-for-net#6622]
**Describe the bug**
The Pipeline release doesn't deploy anything when the App Service is linux!!! --Obviously on windows it works.

***Exception or Stack Trace***
Try to do a CD using linux dotnet 2.2 version, the release pipeline shows succesfull but the url doesn't change and I can't see any error.

**To Reproduce**
Pipeline release using linux for deplying code in the new app service.

***Code Snippet***
Empty

**Expected behavior**
The web app deployed

**Screenshots**

**Setup (please complete the following information):**
 - OS: Linux
 - IDE : All by Azure web
 - Version of the Library used
Dotnet 2.2

**Additional context**

**Comment by praries880** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by btardif** [comment]
@praries880 this is not an app service issue, this is an issue with azure pipelines, please triage this issue to that team.

CC: @pulkitaggarwl

**Comment by AlexGhiondea** [comment]
@Joseluismantilla I am not sure if the issue you are seeing is related to an SDK. If it is, please let me know.
