### ISSUE TITLE
[BUG] GetAccessTokenAsync is very slow when running locally

### ISSUE THREAD

**Issue by omerlh** [Azure/azure-sdk-for-net#6651]
**Describe the bug**
I used `GetAccessTokenAsync` code to test MSI locally. The code was running for more than 1 minute before it returned a valid token. I tested it multiple times, the behavior was consistent. 

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
Try running the code locally.

***Code Snippet***
```
namespace test
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var stopwatch = new Stopwatch();
            stopwatch.Start();

            var azureServiceTokenProvider = new AzureServiceTokenProvider();
            var token = await azureServiceTokenProvider.GetAccessTokenAsync("https://management.azure.com/");

            stopwatch.Stop();
            Console.WriteLine(stopwatch.Elapsed);
        }
    }
}
```
**Expected behavior**
The method returns code in a reasonable time (e.g. a few seconds).

**Screenshots**

**Setup (please complete the following information):**
 - OS: [e.g. iOS] Mac OS 10.13.6
 - IDE : [e.g. IntelliJ] VS code, tested locally using `dotnet run`.
 - Version of the Library used: `Microsoft.Azure.Services.AppAuthentication`, 1.0.3
 - Dotnet version: 2.2.103
 - Azure CLI version: `2.0.58`

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by praries880** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

cc: @shahabhijeet

**Comment by nonik0** [comment]
@omerlh Can you elaborate more on your repro steps/scenario? You said you are running locally, but MSI is only possible when deployed to an Azure VM or App Service with MSI enabled.

Can you confirm you are seeing this issue on a local machine? If that's the case, the cause of the delay is not the MSI token retrieval logic, but possibly another of AppAuth's authentication methods (Azure CLI, Visual Studio, or Windows integrated auth).

**Comment by omerlh** [comment]
Yes, this is when running locally. I guess it's trying to use Azure CLI credentials.

**Comment by jnyrup** [comment]
Have you tried providing a `connectionString` to `AzureServiceTokenProvider`?
```C#
new AzureServiceTokenProvider("RunAs=Developer; DeveloperTool=VisualStudio")
```

We experienced long delays as well when running locally.
If I remember correct `AzureServiceTokenProvider` will first try authenticating using `AzureCLI` and `MSI` before trying `VisualStudio`.

**Comment by omerlh** [comment]
I don't think this will work on Mac:
```
Unhandled Exception: Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderException: Parameters: Connection String: RunAs=Developer; DeveloperTool=VisualStudio, Resource: https://management.azure.com/, Authority: . Exception Message: Tried to get token using Visual Studio. Access token could not be acquired. Environment variable LOCALAPPDATA not set.
   at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider.GetAccessTokenAsyncImpl(String authority, String resource, String scope)
   at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider.GetAccessTokenAsync(String resource, String tenantId)
   at test.Program.Main(String[] args) in /Users/omerl/dev/test/Program.cs:line 40
   at test.Program.<Main>(String[] args)
```
Do you know what is the connection string for Azure CLI?

**Comment by jnyrup** [comment]
> Do you know what is the connection string for Azure CLI?

`"RunAs=Developer; DeveloperTool=AzureCli"`
https://docs.microsoft.com/en-us/azure/key-vault/service-to-service-authentication#connection-string-support

**Comment by omerlh** [comment]
Thank you, this indeed solved the issue - may be worth documenting it?

**Comment by erich-wang** [comment]
@omerlh , is the issue resolved? If yes I'll close it, thanks.

**Comment by omerlh** [comment]
Yes please.
