### ISSUE TITLE
[FEATURE REQ] Cancellation support for client.ReceiveAsync()

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-sdk-for-net#6653]
**Is your feature request related to a problem? Please describe.**

Azure Service Bus is using long-polling to retrieve messages. That means user code has to wait for command execution before an endpoint can shut down. With asynchronous libraries, it's a common theme and a recommended practice to pass a `CancellationToken` to invoke earlier termination of work.

**Describe the solution you'd like**

1. Add support for `CancellationToken` to `ReceiveAsync()`
1. Consider a review of the client to support cancellation pattern throughout various APIs (`ReceiveAsync()`, `SendAsync()`, `AcceptMessageSessionAsync()`, etc).

**Describe alternatives you've considered**

For the context, here's the original issue from the client's previous repository: https://github.com/Azure/azure-service-bus-dotnet/issues/439#issuecomment-423770087

**Comment by praries880** [comment]
https://github.com/Azure/autorest-clientruntime-for-java/pull/622

**Comment by SeanFeldman** [comment]
@praries880 the issue you've linked to seems to refer to something completely different than this issue is about. Was this a typo?

**Comment by jfggdl** [comment]
@axisc, would you please create an internal work item in our backlog to address Sean's concerns/feature request?

**Comment by axisc** [comment]
added this to the internal team backlog
https://msazure.visualstudio.com/One/_workitems/edit/5038388

**Comment by SeanFeldman** [comment]
@axisc closing public issues in favour of an internal backlog is not a good idea.
Please keep public issues open and close when the internal issues are completed.

![image](https://user-images.githubusercontent.com/1309622/62409012-d9e98000-b5d9-11e9-9674-fc9293f88dee.png)

**Comment by goenning** [comment]
I'm with @SeanFeldman on this one, I subscribe to notifications on feature requests that I need so I known when it's implemented. Ideally it should be done as Sean suggested, if not, at least post an update on this thread when it's implemented.

**Comment by danielmarbach** [comment]
@jfggdl @axisc Given the popularity of https://github.com/Azure/azure-service-bus-dotnet/issues/439#issuecomment-423770087 why isn't this reopened? 

// cc @nemakam

**Comment by jfggdl** [comment]
Thanks for your feedback. We will keep this issue open and will update it once we have any news about the candidate feature to implement token cancellation support.

**Comment by jsquire** [comment]
Moving this to the backlog milestone, as the associated sprint has passed.

@axisc:  Would you be so kind as to confirm that this is still an active item and help route to the appropriate individual?

**Comment by SebastianAchatz** [comment]
Is there any timeline for cancellation support in the client sdk?

**Comment by ramya-rao-a** [comment]
Hello all,

Thanks for your patience

Please note that a newer package `Azure.Messaging.ServiceBus` is available as of November 2020. While the older `Microsoft.Azure.ServiceBus` package for which this issue was logged will continue to receive critical bug fixes, we strongly encourage you to upgrade. Read the [migration guide](https://aka.ms/azsdk/net/migrate/sb) for more details.

@JoshLove-msft, Can you provide details on the cancellation support in the new package?

@shankarsama, Can you share if you have plans to add cancellation support to the older `Microsoft.Azure.ServiceBus`? If not, we can close this issue after @JoshLove-msft provides details for the new package

**Comment by ramya-rao-a** [comment]
_Update_: 

Post discussions with @shankarsama, there are no plans to add this feature to the `Microsoft.Azure.ServiceBus` package.
Please do try out the newer package `Azure.Messaging.ServiceBus` which does have the cancellation support like @JoshLove-msft mentioned above.
