### ISSUE TITLE
Azure.Core should have an adapters for HttpContent types in System.Net.Http

### ISSUE THREAD

**Issue by schaabs** [Azure/azure-sdk-for-net#6680]
Client libraries should be able to use the build in HttpContent types to construct content in Azure.Core.  For some content types which are trivial, such as ByteArrayContent, this is not much of an issue, but other content types which more involved such as, FormUrlEncodedContent or MultipartFormDataContent, it would be very useful.

**Comment by pakrym** [comment]
We ended up having our own implementations for special content types.
