### ISSUE TITLE
[BUG] Microsoft.Azure.Services.AppAuthentication 1.2.0 breaks compatibility

### ISSUE THREAD

**Issue by markgould** [Azure/azure-sdk-for-net#6683]
Microsoft.Azure.Services.AppAuthentication 1.2.0 breaks compatibility with apps that depend on a previous version. For example, I'm using Microsoft.Extensions.Configuration.AzureAppConfiguration which specifics >= 1.0.3.

A CancellationToken was added to AzureServiceTokenProvider.GetAccessTokenAsync. The existing method signature was modified with an optional parameter, instead of adding a new method. If breaking changes like this are added, shouldn't the version bump to 2, or was this a mistake?

The following exception is thrown:

```
Method not found: 'System.Threading.Tasks.Task`1<System.String> Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider.GetAccessTokenAsync(System.String, System.String)
```

To repro:

Follow steps here and update to Microsoft.Azure.Services.AppAuthentication 1.2.0: https://docs.microsoft.com/en-us/azure/azure-app-configuration/howto-integrate-azure-managed-service-identity

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by nonik0** [comment]
@markgould Thank you very much for bringing this to our attention! We will be fixing this ASAP, targeting early next week.

**Comment by erich-wang** [comment]
@nonik0, any update for the issue?

**Comment by nonik0** [comment]
@markgould Thank you for providing the repro steps. [AppAuth 1.2.1](https://www.nuget.org/packages/Microsoft.Azure.Services.AppAuthentication/1.2.1) was just released that has the fix for this issue.

@erich-wang FYI.

**Comment by Petermarcu** [comment]
This looks like it was addressed and never closed. I'm going to close it now.
