### ISSUE TITLE
Storage Files does not have Hello World sample

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk-for-net#6696]
The following file is linked from storage files readme and promises to be a hello world sample:
sdk/storage/Azure.Storage.Files/tests/Samples/Sample1_HelloWorld.cs

But there is not hello world sample in the file.

**Comment by kaerm** [comment]
What needs to change? @tg-msft

**Comment by tg-msft** [comment]
...  a lot.  😃   Assigning to myself.

**Comment by tg-msft** [comment]
Resolved with last release.
