### ISSUE TITLE
[BUG] Cannot connect to KeyVault on Mac OS X

### ISSUE THREAD

**Issue by aheintz** [Azure/azure-sdk-for-net#6709]
**Describe the bug**
I'm running a .NET Framework project on Mac under mono and trying to use KeyVault but cannot get get access token due to Windows CLI command is used instead of Bash command. According to the output, "cmd.exe" is used, although the source for tag "1.2.0" indicates the Bash command should be used is OS is not Windows.

***Exception or Stack Trace***
````
[ERROR] FATAL UNHANDLED EXCEPTION: Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderException: Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/05392f7e-58e6-4648-9ee2-95041f83c964. Exception Message: Tried the following 4 methods to get an access token, but none of them worked.
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/05392f7e-58e6-4648-9ee2-95041f83c964. Exception Message: Tried to get token using Managed Service Identity. Unable to connect to the Managed Service Identity (MSI) endpoint. Please check that you are running on an Azure resource that has MSI setup.
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/05392f7e-58e6-4648-9ee2-95041f83c964. Exception Message: Tried to get token using Visual Studio. Access token could not be acquired. Environment variable LOCALAPPDATA not set.
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/05392f7e-58e6-4648-9ee2-95041f83c964. Exception Message: Tried to get token using Azure CLI. Access token could not be acquired. ApplicationName='cmd.exe', CommandLine='/c az account get-access-token -o json --resource https://vault.azure.net', CurrentDirectory='', Native error= Cannot find the specified file
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/05392f7e-58e6-4648-9ee2-95041f83c964. Exception Message: Tried to get token using Active Directory Integrated Authentication. Access token could not be acquired. secur32.dll
````

**To Reproduce**
Run a .NET Framework 4.6.1 project and try to connect to KeyVault on Mac OS X

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
The expected behaviour would be that the `AzureCliAccessTokenProvider` would use the Bash command.

**Setup (please complete the following information):**
 - OS: Mac OS X (Output from Runtime OSDescription: Unix 18.6.0.0)
 - IDE : Jetbrains Rider
 - Microsoft.Azure.Services.AppAuthentication 1.2.0
 - Mono 5.18.1.3

**Comment by loarabia** [comment]
Thank you for the issue. I think there may be two things here. One is the root issue that may have caused the fallback logic to kick in and the other is that in one fallback path the logic was trying to run cmd.exe on a MacOS device.

Management team, can you take a look?

**Comment by erich-wang** [comment]
I'm looking into it.

**Comment by aveuud** [comment]
I have the same problem trying to login in to Azure with managed identity in Visual Studio Code. 
Error message:
Parameters: Connection String: [No connection string specified], Resource: https://management.azure.com, Authority: . Exception Message: Tried the following 3 methods to get an access token, but none of them worked.
Parameters: Connection String: [No connection string specified], Resource: https://management.azure.com, Authority: . Exception Message: Tried to get token using Managed Service Identity. Unable to connect to the Managed Service Identity (MSI) endpoint. Please check that you are running on an Azure resource that has MSI setup.
Parameters: Connection String: [No connection string specified], Resource: https://management.azure.com, Authority: . Exception Message: Tried to get token using Visual Studio. Access token could not be acquired. Environment variable LOCALAPPDATA not set.
Parameters: Connection String: [No connection string specified], Resource: https://management.azure.com, Authority: . Exception Message: Tried to get token using Azure CLI. Access token could not be acquired.

**Comment by JiriKovar** [comment]
Same here. Trying to run Selenium UI tests on hosted Azure DevOps MacOs agents. First we run an "az login" for service principal & set the subscription with the KeyVault, then we run UI tests which are reading from the KeyVault and are depending on the AZ CLI authentication. 

On Windows, it works fine, but on MacOs, we are running into that issue. 

What is the ETA for this issue? 

Thanks.

**Comment by loarabia** [comment]
@erich-wang Have you had a chance to look into the issue any deeper?

**Comment by erich-wang** [comment]
I'm asking AppAuthentication team to look deeper

**Comment by nonik0** [comment]
Hi all, thank you for reporting this issue. I was able to repro the issue on both OSX and Ubuntu using Mono. This issue should be fixed in the [latest AppAuth 1.3.1 release](https://www.nuget.org/packages/Microsoft.Azure.Services.AppAuthentication/1.3.1), please try it out and let us know if you have any issues!

**Comment by erich-wang** [comment]
@aheintz, please close the issue after verification, thanks.

**Comment by varunsh-msft** [comment]
Closing issue since fix was released in Aug.

**Comment by soydachi** [comment]
Please reopen this issue because in the latest AppAuth is no more working, but in the AppAuth 1.3.1 yes.

**Comment by soydachi** [comment]
> Please reopen this issue because in the latest AppAuth is no more working, but in the AppAuth 1.3.1 yes.

This issue only occurs in MacOS, the latest version in Windows is working well

**Comment by Rorschachly** [comment]
I am having the same issue as @soydachi does (MacOS). Please help us!

**Comment by anaismiller** [comment]
@soydachi, @Rorschachly, two asks:
- Can you please check and see if it also happens on AppAuth 1.6.0, just released?
- What .NET targets are you using?

**Comment by Rorschachly** [comment]
> @soydachi, @Rorschachly, two asks:
> 
> * Can you please check and see if it also happens on AppAuth 1.6.0, just released?
> * What .NET targets are you using?

Reply to @anaismiller 
1. I started to use AppAuth 1.6.0. The problem still happens every time I first start the program. But after maybe several minutes, it could work, still non-deternimistic. 
2. ASP .Net Core 3.1 (Same problem when using ASP .Net Core 2.2)

Thanks.

**Comment by Rorschachly** [comment]
@anaismiller 
My latest solution to this issue is to run `dotnet run` in my native terminal, then shut down the process. Then click `run debug` on Visual Studio. And it works. But I don't think this is a long time solution, either.

Thanks.

**Comment by akshitaagarwa11a** [comment]
> @soydachi, @Rorschachly, two asks:
> 
> * Can you please check and see if it also happens on AppAuth 1.6.0, just released?
> * What .NET targets are you using?

@anaismiller Is there a solution to this problem? I am facing the same issue with MacOS. I'm currently using the latest version of AppAuth i.e. 1.6.1.

**Comment by jpecman** [comment]
I had the same problem on my mac and after some digging in [source](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/mgmtcommon/AppAuthentication/Azure.Services.AppAuthentication/TokenProviders/AzureCliAccessTokenProvider.cs) I found that AzureCLIPath was not set on my machine.

I installed Azure CLI through homebrew so my path to it was '/opt/homebrew/bin/az'

I put this line into `˜/.zshrc `(I use zsh, if you use bash then it should go into `˜/.bash_profile` )

`export AzureCLIPath=/opt/homebrew/bin`

restarted related apps and now it works :-)

**Comment by anaim3** [comment]
Hi, I am really struggling here, how did you guys fix this problem?
I still can't connect to key vault, failing to get the access token from visual studio for Mac 2022(preview)..

**Comment by Rorschachly** [comment]
> Hi, I am really struggling here, how did you guys fix this problem? I still can't connect to key vault, failing to get the access token from visual studio for Mac 2022(preview)..

I would recommend trying VS Code, and using Terminal command line to run it.

**Comment by anaim3** [comment]
Hi, thanks for your reply its working on viscose although I had to change the target framework from 3.1 to 6.0.1

now how can I make it work on Visual studio ?
