### ISSUE TITLE
Add ManagedIdentityClient options class to Azure.Identity

### ISSUE THREAD

**Issue by schaabs** [Azure/azure-sdk-for-net#6711]
ManagedIdentityClient should have it's own ClientOptions type now that it is a separate client from AadIdentityClient.  ManagedIdentityClientOptions could possibly expose:

- ImdsAvailableTimeoutMs
- ImdsEndpoint
- ImdsApiVersion
- AppServiceMsiApiVersion

Also the ClientOptions classes should be configured use ResponseClassifier to handle retry behavior and failure conditions by default.

**Comment by AlexanderSher** [comment]
Not needed right now.
