### ISSUE TITLE
Release version requirements for services that use Core

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-net#6722]
We need to use binary composition for packages that depend on Core and lock to a specific future release version. 

Procedure: 
- [x] Open a PR to update the targeted version of Core (PR: https://github.com/Azure/azure-sdk-for-net/pull/6720) 
- [ ] Release the updated version of Core
- [ ] Verify CI pipelines and live tests succeed for affected packages

**Comment by danieljurek** [comment]
We have a solution today for .NET where a developer can switch between binary and source composition for Core. We're using binary composition by default today. 

To finish this: We should have a strategy for auditing source vs. binary composition before releasing to ensure that a package will not be published without first having published its dependencies. This should happen for all languages.

**Comment by danieljurek** [comment]
Updated docs: https://github.com/Azure/azure-sdk/blob/master/docs/policies/releases.md#consistent-dependency-versions

> Avoid source dependencies in projects and only use binary/package dependencies. If a package under development needs to incorporate changes from a package upon which it depends then it should use the nightly dev version of that package. That is, if Project B incorporates changes to Project A then Project B should consume the Package from Project A that is released in the nightly feed.

We don't presently have a tool for auditing source vs binary/package composition

**Comment by weshaggard** [comment]
We have setup testing modes that ensure we test against both package and source versions of Core so we should always be in a good state for both.
