### ISSUE TITLE
Upgrade reference Microsoft.IdentityModel.Clients.ActiveDirectory to 5.xx

### ISSUE THREAD

**Issue by romanpolunin** [Azure/azure-sdk-for-net#6742]
We need ServiceBus package to support Microsoft.IdentityModel.Clients.ActiveDirectory of versions 5.xx. Current version (3.4) locks the reference between 3.17.2 and < 5.0.0

**Comment by loarabia** [comment]
Thanks @romanpolunin  I've tagged this so the Service Bus team should take a look.

/cc @axisc

**Comment by jfggdl** [comment]
@romanpolunin , thanks for raising this request. Would you please provide us more information as to the specific requirements that you have for which you need Microsoft Identity's 5.xx?

**Comment by rythos42** [comment]
I can't speak for the OP, but in my office people keep trying to blindly update to the latest packages in a shared project. This will end up working fine in whatever solution they're working on, but breaks another solution they hadn't thought to check.

**Comment by romanpolunin** [comment]
> @romanpolunin , thanks for raising this request. Would you please provide us more information as to the specific requirements that you have for which you need Microsoft Identity's 5.xx?

There's another project (referenced from the same assembly) which uses Azure KeyVault. The code is new, so it's using most recent Microsoft.IdentityModel.Clients.ActiveDirectory (5.xx). Also, we noticed them somehow this version conflict does not affect us at run time, so it's only a build warning for now.

**Comment by jfggdl** [comment]
Thanks for the clarity. We are looking into the activities that would require Service Bus to support Microsoft.IdentityModel.Clients.ActiveDirectory  version 5.XX.

**Comment by nemakam** [comment]
The latest code doesn't take dependency on `Microsoft.IdentityModel.Clients.ActiveDirectory` anymore. The next release should resolve this.
