### ISSUE TITLE
[BUG] Management Service Bus Solution file has incorrect project references

### ISSUE THREAD

**Issue by OwenDF** [Azure/azure-sdk-for-net#6744]
The solution file at sdk\servicebus\Microsoft.Azure.Management.ServiceBus/Microsoft.Azure.Management.ServiceBus.sln has references to projects that do not exist (they appear to have had their names simplified at some point.

To reproduce: open the solution file in Visual Studio and observe that the projects fail to load.

**Comment by loarabia** [comment]
Hi @OwenDF thanks for reporting this issue. I've tagged it to have the team take a look.

/cc @shahabhijeet
