### ISSUE TITLE
Do not copy the TTL when forwarding messages

### ISSUE THREAD

**Issue by sanjaysingh** [Azure/azure-sdk-for-net#6748]
I have following setup of my Topics and Susbcriptions to implement a server side retry of messages.
**Topic1** (all default settings)
   **Subscription1** (all default settings)

**Topic1.Retry**
    **Subscription1** (Enable Deadletterring on Message expiration, Forward dead lettered messages to: Topic1)

I published the failed messages from code to the Retry topic above. The message has some TTL set that is based on some logic of how business events should be retried.
```C#
var message = new Message(Encoding.UTF8.GetBytes(messageBody));
                message.TimeToLive = DeriveMessageRetryInterval(message);
                await topicClient.SendAsync(message);
```
I notice that when the message is forwarded after expiration from the Error subscription, it also has the same TTL in the main subscription (Topic1.Subscription1). This causes the messages to get lost if we do not process them in time from Topic1.Susbcription1.

Is there anyway to disable copying of TTL when the message is forwarded? We are migrating from RabbitMQ which does not copy the expiration when forwarding the messages so we did not face this issue. If there is any other pattern to implement this message TTL based server side retry, I would appreciate any pointer on that as well.

I understand that i can have expiration on the subscription level and not set the TTL from the code but then i will not have the flexibility to set different expiration for messages. This also does not necessarily seem to be an issue with the SDK but i am not sure where else to ask.

**Comment by loarabia** [comment]
@sanjaysingh Thanks for reporting this. I've tagged this for the team to take a look

/cc @ShubhaVijayasarathy

**Comment by axisc** [comment]
@sanjaysingh

not copying the TTL will break the contract that the sender is setting for the receivers who consume the message.

As a solution, you may have to adapt the contract that the sender and receiver are maintaining. 
I recommend either keeping a larger TTL value, or relying on the dead letter queue to recover from the situation where your messages are expiring.

hope this helps. 
please let me know if there are any other questions.
