### ISSUE TITLE
Test sync-over-async code in more environments

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#6759]
.NET is currently providing sync APIs that eventually call into an async transport layer.  We should do a lot of stress testing in different environments.  The Storage team has suggested ASP.NET, desktop, WPF, WinForms, WebForms, and anything that might play with SynchronizationContext.

**Comment by kurtzeborn** [comment]
This is a general purpose issue to track running our tests in more environments (in particular different/common synchronization contexts).

**Comment by kurtzeborn** [comment]
This may be something we could consider as part of our perf/stress push going on.

**Comment by pallavit** [comment]
@tg-msft is this still a concern? Now that the engsys team is looking at stress testing - do you have any particular scenarios you would want us to consider?

**Comment by JimSuplizio** [comment]
Hi @tg-msft, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
