### ISSUE TITLE
[FEATURE REQ] CreateOrUpdate method for Custom Roles

### ISSUE THREAD

**Issue by countchivas** [Azure/azure-sdk-for-net#6772]
https://docs.microsoft.com/en-us/azure/role-based-access-control/custom-roles-rest

**Comment by maggiepint** [comment]
Thanks for sending this feedback. We are routing to the appropriate team for follow-up.

**Comment by lilyjma** [comment]
@rthorn17 any updates on this?

**Comment by rthorn17** [comment]
> @rthorn17 any updates on this?

This is not with the ARM team.  The Identity team would need to make the changes to their RP to add the feature request. 

@jsquire > I see you updated the issue in Jun. Are you tracking this in a backlog for feature requests?

**Comment by jsquire** [comment]
@rthorn17 - I am not; this was moved to allow it to pass automated issue validation.  The repository standards require that anything tagged `feature-request` be assigned to a milestone.   `Backlog` is the default which comes with no assumed timeline.

**Comment by jsquire** [comment]
@AlexGhiondea:  Would you be so kind as to help route this to the appropriate team.  I'm not sure which tag/group is appropriate for the management plane Identity area.

**Comment by lilyjma** [comment]
@nickzhums : would you happen to know who might be able to help with management plane Identity?

**Comment by nickzhums** [comment]
@jianghaolu Could you please see if this is related to Azure Identity?

**Comment by jianghaolu** [comment]
This is not owned by the Identity team. The API is owned by the Azure management SDK team. 

And I can see this test already in place: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/authorization/Microsoft.Azure.Management.Authorization/tests/Tests/BasicTests.cs#L1160. Is this what you are looking for?
