### ISSUE TITLE
[BUG] WebSeachAPI: Microsoft.Azure.CognitiveServices.Search.WebSearch.Models.SearchResult "entities" results are missing

### ISSUE THREAD

**Issue by jan-ai** [Azure/azure-sdk-for-net#6774]
**Describe the bug**
While documentation (https://docs.microsoft.com/en-us/rest/api/cognitiveservices-bingsearch/bing-web-api-v7-reference#searchresponse) and online demo (https://azure.microsoft.com/en-us/services/cognitive-services/bing-web-search-api/) showing an "entities" property in the search response of the webserach REST-API, the SDK does not have an "entities" Property.

**Expected behavior**
SDK should match documentation of Version 7 of bing search API. "entities" property should be added.

**Setup (please complete the following information):**
Version of the Library used: v2.0.0 of Microsoft.Azure.CognitiveServices.Search.WebsSearch

**Comment by maggiepint** [comment]
Thanks for the feedback. We have routed this to the appropriate team for follow-up.

**Comment by jan-ai** [comment]
Also it looks like several properties of Microsoft.Azure.CognitiveServices.Search.VideoSearch.Models are missing. See the following list

- creator
- datePublished
- **duration**
- encodingFormat
- hostPageDisplayUrl
- isAccessibleForFree
- mainEntity
- publisher

Should I open a new bug report for those as well or does the appropriate team care about all missing properties in the several ...Search...Models?

Also what is the best guess on the time frame to solve this issue? I understand it might be difficult to answer this, but will it be days, weeks oder months? We didn't expect that several properties are missing. If it takes longer we might have to use the REST-API, which obviously should be decided as soon as possible.

Thanks

**Comment by mjparinas** [comment]
This seems to be a fairly significant omission in the Node.js SDK. I'm currently using this library and it is NOT feature complete at all. I'm commenting to add visibility to this bug.

**Comment by dmitryfd** [comment]
Is there any update on adding this functionality to the library?

**Comment by craigeddy** [comment]
Could really use the `datePublished` property here, please! Thanks.

**Comment by SaurabhSharma-MSFT** [comment]
@jaggerbodas-ms, @arwong Can you please look into this.

**Comment by SaurabhSharma-MSFT** [comment]
@elizabeth @eleni Did you get a chance to look into this.

**Comment by jaggerbodas-ms** [comment]
Hi Saurabh,

Our Cognitive API's are on a path to deprecation by the end of 2023 so we are not making any updates to the SDK's.  Partners should use the REST API's.

Thanks,

Elizabeth

From: Eleni Romano ***@***.***>
Sent: Wednesday, March 9, 2022 9:33 AM
To: Jagger Bodas ***@***.***>; Azure/azure-sdk-for-net ***@***.***>; Azure/azure-sdk-for-net ***@***.***>; Elizabeth Westphal ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [Azure/azure-sdk-for-net] [BUG] WebSeachAPI: Microsoft.Azure.CognitiveServices.Search.WebSearch.Models.SearchResult "entities" results are missing (#6774)

Hi,

So this is for Cognitive services? If so you should contact someone from the Cognitive services team. Thanks!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: Jagger ***@***.***>
Sent: Wednesday, March 9, 2022 7:05 AM
To: ***@***.***>; ***@***.***>; Elizabeth ***@***.***>; Eleni ***@***.***>
Cc: ***@***.***>
Subject: RE: [Azure/azure-sdk-for-net] [BUG] WebSeachAPI: Microsoft.Azure.CognitiveServices.Search.WebSearch.Models.SearchResult "entities" results are missing (#6774)

+ @Elizabeth ***@***.***>, @Eleni ***@***.***>

**Comment by jaggerbodas-ms** [comment]
Sure, got it.  Thanks for the details.

Thanks
Saurabh
From: Elizabeth Westphal ***@***.***>
Sent: Friday, April 1, 2022 2:20 PM
To: Eleni Romano ***@***.***>; Jagger Bodas ***@***.***>; Azure/azure-sdk-for-net ***@***.***>; Azure/azure-sdk-for-net ***@***.***>; Saurabh Sharma ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [Azure/azure-sdk-for-net] [BUG] WebSeachAPI: Microsoft.Azure.CognitiveServices.Search.WebSearch.Models.SearchResult "entities" results are missing (#6774)

Hi Saurabh,

Our Cognitive API's are on a path to deprecation by the end of 2023 so we are not making any updates to the SDK's.  Partners should use the REST API's.

Thanks,

Elizabeth

From: Eleni Romano ***@***.******@***.***>>
Sent: Wednesday, March 9, 2022 9:33 AM
To: Jagger Bodas ***@***.******@***.***>>; Azure/azure-sdk-for-net ***@***.******@***.***>>; Azure/azure-sdk-for-net ***@***.******@***.***>>; Elizabeth Westphal ***@***.******@***.***>>
Cc: Mention ***@***.******@***.***>>
Subject: RE: [Azure/azure-sdk-for-net] [BUG] WebSeachAPI: Microsoft.Azure.CognitiveServices.Search.WebSearch.Models.SearchResult "entities" results are missing (#6774)

Hi,

So this is for Cognitive services? If so you should contact someone from the Cognitive services team. Thanks!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: Jagger ***@***.***>
Sent: Wednesday, March 9, 2022 7:05 AM
To: ***@***.***>; ***@***.***>; Elizabeth ***@***.***>; Eleni ***@***.***>
Cc: ***@***.***>
Subject: RE: [Azure/azure-sdk-for-net] [BUG] WebSeachAPI: Microsoft.Azure.CognitiveServices.Search.WebSearch.Models.SearchResult "entities" results are missing (#6774)

+ @Elizabeth ***@***.***>, @Eleni ***@***.***>

**Comment by SaurabhSharma-MSFT** [comment]
@jan-ai Please let us know if you have any questions else we will proceed further with the closure of this case. Thanks

**Comment by SaurabhSharma-MSFT** [comment]
@jan-ai We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.

**Comment by craigeddy** [comment]
> Our Cognitive API's are on a path to deprecation by the end of 2023 so we are not making any updates to the SDK's. Partners should use the REST API's.

Is there some documentation link I can look at for the migration path? Thanks!

**Comment by SaurabhSharma-MSFT** [comment]
@craigeddy It’s the same schema, just a different endpoint.  You can read some about the move as well as find links to documentation over here - [Bing Search APIs are Transitioning](https://blogs.bing.com/search-quality-insights/october-2020/Bing-Search-APIS-are-Transitioning)

**Comment by jaggerbodas-ms** [comment]
Hi,

So this is for Cognitive services? If so you should contact someone from the Cognitive services team. Thanks!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: Jagger ***@***.***>
Sent: Wednesday, March 9, 2022 7:05 AM
To: ***@***.***>; ***@***.***>; Elizabeth ***@***.***>; Eleni ***@***.***>
Cc: ***@***.***>
Subject: RE: [Azure/azure-sdk-for-net] [BUG] WebSeachAPI: Microsoft.Azure.CognitiveServices.Search.WebSearch.Models.SearchResult "entities" results are missing (#6774)

+ @Elizabeth ***@***.***>, @Eleni ***@***.***>
