### ISSUE TITLE
Add hooks for Recorded test Request/Response Body manipulation

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#6781]
Most of the Storage tests upload random data and we don't want to add 1GB of noise in the recordings that everyone has to sync.  It would be great if we could selectively exclude/generate/etc. the request/response bodies of those recordings.

**Comment by JimSuplizio** [comment]
Hi @tg-msft, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
