### ISSUE TITLE
Add helpers in Azure.Core to map between ServiceVersion enums and REST API versions

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#6801]
Investigate if there's anything we can do to mitigate pain of keeping version numbers in sync with our ServiceVersion enums.

**Comment by kurtzeborn** [comment]
I think this was a concern raised by Keith...

@seanmcc-msft does something need to happen here?  If so what would you like to see?  Otherwise, will you please close this.
