### ISSUE TITLE
[BUG] The KeyVault dotnet SDK's Unwrap method doesn't complement the REST Wrap method

### ISSUE THREAD

**Issue by rajdhandus** [Azure/azure-sdk-for-net#6803]
**Describe the bug**
I get a BadRequest error when trying to call the UnwrapKeyAsync method in .net SDK.

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
1. Wrap using REST Service (https://$keyVaultName.vault.azure.net/keys/$keyName/$keyVersion/wrapkey?api-version=7.0)

2. Unwrap using the SDK.

***Code Snippet***
`function Wrap-Key
(
  [string]$accessToken,
  [string]$keyVaultName,
  [string]$keyName,
  [string]$keyVersion,	# Optional
  [string]$plainText
)
{
 
  $queryUrl = "https://$keyVaultName.vault.azure.net/keys/$keyName/$keyVersion/wrapkey?api-version=7.0"
    
  $headers = @{ 'Authorization' = "Bearer $accessToken"; "Content-Type" = "application/json" }
 
  $bodyObject = @{ "alg" = "RSA-OAEP-256"; "value" = $plainText }
  $bodyJson = ConvertTo-Json -InputObject $bodyObject
 
  $response = Invoke-RestMethod -Method POST -Ur $queryUrl -Headers $headers -Body $bodyJson
 
  return $response.value
}`

```
private async Task<byte[]> UnwrapKeyAsync(string keyId, byte[] dataToDecrypt)
        {
            var decryptOperation = await this.keyVaultClient.UnwrapKeyAsync(keyId, JsonWebKeyEncryptionAlgorithm.RSAOAEP256, dataToDecrypt).ConfigureAwait(false);
            return decryptOperation.Result;
        }
```

**Expected behavior**
Unwrapping a Wrapped key should be working irrespective of whether or not the Wrapping happened in .net SDK or over REST. 

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows
 - IDE : VS 2019
 - Latest Libraries

**Additional context**
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Microsoft.Azure.KeyVault/src/Generated/Models/KeyOperationsParameters.cs#L57

The SDK is covering the payload with Base64 one last time before sending the REST request. This is causing the difference. 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Bug Description Added
- [x ] Repro Steps Added
- [x ] Setup information Added

**Comment by maggiepint** [comment]
Thanks for the feedback. We are routing to the appropriate team for follow-up. cc: @schaabs

**Comment by schaabs** [comment]
Hi @rajdhandus, thanks for reporting the issue.  In you example code where you're calling the REST API directly what is the value you're passing in for $plaintext?

~~~
$bodyObject = @{ "alg" = "RSA-OAEP-256"; "value" = $plainText }
~~~

This should be a base64url encoded value.  This is what the service expects.  Unfortunately the REST API docs [here](https://docs.microsoft.com/en-us/rest/api/keyvault/unwrapkey/unwrapkey), and [here](https://docs.microsoft.com/en-us/rest/api/keyvault/wrapkey/wrapkey).  Just say that value is type `string` which is not very helpful.

But if you look at the swagger definition for wrap and unwrap it does say that the format is base64url
https://github.com/Azure/azure-rest-api-specs/blob/d6d5aca27ed6252cfeab510b8abd2a935b468e04/specification/keyvault/data-plane/Microsoft.KeyVault/stable/7.0/keyvault.json#L695
~~~
    "/keys/{key-name}/{key-version}/wrapkey": {
      ...
          {
            "name": "parameters",
            "in": "body",
            "required": true,
            "x-ms-client-flatten": true,
            "schema": {
              "$ref": "#/definitions/KeyOperationsParameters"
            },
          ...
~~~ 
https://github.com/Azure/azure-rest-api-specs/blob/d6d5aca27ed6252cfeab510b8abd2a935b468e04/specification/keyvault/data-plane/Microsoft.KeyVault/stable/7.0/keyvault.json#L4861
~~~
    "KeyOperationsParameters": {
      "properties": {
        ...
        "value": {
          "type": "string",
          "format": "base64url"
        }
~~~

I'm not sure why the generated REST API specs don't mention the format.  I'll file an issue on the documentation to address this, but in your example $plainText should be base64url encoded before sending it to the service, and you should get the same result as through the SDK.

**Comment by rajdhandus** [comment]
hi @schaabs - we tried using both base64 encoded string and planText string as input for the Wrap Method.. both time the Unwrap method failed with Bad Request..

Given below is the powershell function that Wraps..

```
#region Wrap The SymmetricKey
function Wrap-Key
(
  [string]$accessToken,
  [string]$keyVaultName,
  [string]$keyName,
  [string]$keyVersion,	# Optional
  [string]$plainText
)
{
    [byte[]]$plainArray = [System.Text.Encoding]::Unicode.GetBytes($plainText)
    $base64String = [Convert]::ToBase64String($plainArray)
 
  $queryUrl = "https://$keyVaultName.vault.azure.net/keys/$keyName/$keyVersion/wrapkey?api-version=7.0"
    
  $headers = @{ 'Authorization' = "Bearer $accessToken"; "Content-Type" = "application/json" }
 
  $bodyObject = @{ "alg" = "RSA-OAEP-256"; "value" = $base64String }
  $bodyJson = ConvertTo-Json -InputObject $bodyObject
 
  $response = Invoke-RestMethod -Method POST -Ur $queryUrl -Headers $headers -Body $bodyJson
 
  return $response.value
}
#endregion
```

Should Wrapkey REST method's output/response be base64 encoded before calling Unwrap via the SDK? 

Are you suggesting that the Wrapkey's request be base64 encoded? If that is the case the response from Wrapkey REST call should be mappable as-is to the Unwrap SDK method correct?

**Comment by heaths** [comment]
Issue moved to [Azure/azure-sdk-for-js #5497](https://github.com/Azure/azure-sdk-for-js/issues/5497) via [**ZenHub**](https://www.zenhub.com/)
