### ISSUE TITLE
Storage models should implement IEquatable

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#6808]

**Comment by tg-msft** [comment]
@JoshLove-msft  - can you verify we do this for all of our structs and close the issue if so?

**Comment by JoshLove-msft** [comment]
Is this a requirement only for value-type models?

**Comment by JoshLove-msft** [comment]
The following structs don't implement IEquatable. Note these are all internal:

From Blobs.Batching csproj:
- HashCodeCombiner
- InplaceStringBuilder
- KeyValueAccumulator
- StringTokenizer
- StringTokenizer.Enumerator
- StringValues.Enumerator

From Common csproj:
- ReliabilityConfiguration
- Volatile
