### ISSUE TITLE
[BUG] Most of links  in package.md are broken after folder refactoring

### ISSUE THREAD

**Issue by erich-wang** [Azure/azure-sdk-for-net#6812]
[BUG] Most of links  in [package.md](https://github.com/Azure/azure-sdk-for-net/blob/master/packages.md) are broken after folder refactoring

**Comment by kurtzeborn** [comment]
@scbedd, I'm pretty sure this just means we need to run the generation tool again if it's not already running automatically.

**Comment by scbedd** [comment]
Happy to say I already pre-empted this! 

#6848

**Comment by scbedd** [comment]
Closing as it's already taken care of.
