### ISSUE TITLE
[FEATURE REQ] AzureSqlDatabaseLinkedService - support client certificate authentication against service principal

### ISSUE THREAD

**Issue by ohadschn** [Azure/azure-sdk-for-net#6814]
**Is your feature request related to a problem? Please describe.**
I can't use client certificates to authenticate against my AAD app's service principal for SQL authentication in Data Factory. This makes my auto-rotation story harder.

**Describe the solution you'd like**
Add a property such as `ServicePrincipalCertificate` which you'd then use for AAD authentication against the specified `ServicePrincipalId`.

**Comment by maggiepint** [comment]
Thanks for this feedback. I have routed to the appropriate team for follow-up.

**Comment by moralt** [comment]
May I suggest to also apply the "Data Factory" lable? The ask is actually on their team.

**Comment by maggiepint** [comment]
Thanks! Sometimes I can't quite tell.

**Comment by oliverbean** [comment]
This feature requeset is accepted by Azure Data Factory team, and would be included into next two months' plan. Customers store their client certificate in Azure Key Vault, and refer it inside AzureSQL linked service, to authenticate and access AzureSQL database.

**Comment by ohadschn** [comment]
@oliverbean any news by chance?

**Comment by oliverbean** [comment]
@ohadschn, this feature is supported now in ADF. Feel free to try and share feedback.

**Comment by arolshan** [comment]
@oliverbean can you please share a link to relevant documentation\sdk reference?

**Comment by jsquire** [comment]
Per Oliver's comment that the feature, closing this item out.

**Comment by arolshan** [comment]
is there a link to documentation or sdk on how to achieve this?

**Comment by arolshan** [comment]
@oliverbean i was trying to search this everywher, REST, .NET SDK, and it doesn't exist in any reference. can you provide a link?
