### ISSUE TITLE
Azure.Core should wrap all transport layer exceptions

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#6817]
If your network connection drops during the middle of a request, we should throw a `RequestFailedException` rather than an `HttpRequestException` that [`HttpClient` throws.](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.sendasync?view=netframework-4.8)

Ideally customers won't have to know or care about which transport layer they're using.

**Comment by pakrym** [comment]
Include clientRequestId in messages.
