### ISSUE TITLE
[FEATURE REQ] Make BatchFlushInterval configurable in ServiceBus SDK

### ISSUE THREAD

**Issue by LeroyK** [Azure/azure-sdk-for-net#6859]
**Is your feature request related to a problem? Please describe.**
The Service Bus SDK uses a [static readonly value of 20ms](https://github.com/Azure/azure-sdk-for-net/blob/52f9222058b5ae6716c8b088af20485dc0d4d1bc/sdk/servicebus/Microsoft.Azure.ServiceBus/src/Core/MessageReceiver.cs#L46) for batch flush interval when receiving messages. This could delay message processing speed.

**Describe the solution you'd like**
This value should be configurable, like in the old SDK.

**Comment by praries880** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by jfggdl** [comment]
@LeroyK, we are adding this feature request to our backlog. That said, there is no defined date on which we will start working on this feature yet. We invite you to contribute by implementing this issue. We will work with you reviewing your PR and releasing it.  Please let us know.

**Comment by axisc** [comment]
Added this to our internal team backlog.
https://msazure.visualstudio.com/One/_workitems/edit/5038154

**Comment by SeanFeldman** [comment]
@axisc closing public issues in favour of an internal backlog is not a good idea.
Please keep public issues open and close when the internal issues are completed.

![image](https://user-images.githubusercontent.com/1309622/62409012-d9e98000-b5d9-11e9-9674-fc9293f88dee.png)
