### ISSUE TITLE
[QUERY] Preview 1 - Will there be a Azure.Storage.Tables? What should we use instead?

### ISSUE THREAD

**Issue by tjrobinson** [Azure/azure-sdk-for-net#6860]
**Query/Question**
Will there be a `Azure.Storage.Tables` package for table storage? What should we use instead if not?

***Why is this not a Bug or a feature Request?***
It is a question, though it may lead to a feature request.

**Setup (please complete the following information if applicable):**
 - OS: N/A
 - IDE : N/A
 - 12.0 Preview 1
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by praries880** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by Sudheer-Dhulipalla** [comment]
Please refer to the links below - there is a supported SDK available here:  
- https://docs.microsoft.com/en-us/azure/cosmos-db/table-introduction
- https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table

**Comment by tjrobinson** [comment]
@Sudheer-Dhulipalla And just to confirm, that nuget package is suitable, and recommended, for "legacy" (i.e. non Cosmos DB backed) Table Storage as well? If so it's a kind of confusing namespace.

**Comment by jongio** [comment]
We shipped Azure Tables Beta 1 - you can find it here: https://aka.ms/azsdk/releases
