### ISSUE TITLE
Fix xml doc comments in Azure.Core

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-for-net#6870]
As part of https://github.com/Azure/azure-sdk-for-net/pull/6869 I had to disable warning 1591 because there are a bunch of missing doc comments. This issue is to track fixing those warnings and removing that suppression.

**Comment by weshaggard** [comment]
Note that this also include Azure.Core.Extensions which has also disabled 1591.

**Comment by pakrym** [comment]
Dup: https://github.com/Azure/azure-sdk-for-net/issues/6229
