### ISSUE TITLE
Fix xml doc comments for ApplicationModel Configuration 

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-for-net#6873]
As part of https://github.com/Azure/azure-sdk-for-net/pull/6869 I had to disable warning 1591 because there are a bunch of missing doc comments. This issue is to track fixing those warnings and removing that suppression.

**Comment by maririos** [comment]
PR #6880 added most of the missing xmldocs.
Remaining metods are for the [AppConfigurationAzureClientBuilderExtensions](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/appconfiguration/Azure.ApplicationModel.Configuration/src/AppConfigurationAzureClientBuilderExtensions.cs#L11).
