### ISSUE TITLE
[Up For Grabs] Storage: Remove snapshot from most APIs

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#6887]
Rather than take a `snapshot` parameter on most of our APIs, we'll expect users to call `WithSnapshot` to get a `BlobClient` that make requests for a particular snapshot.

**Comment by seanmcc-msft** [comment]
@tg-msft, it looks like we have the snapshot parameter for our APIs in swagger, I think it would be best to leave it to reduce the ambiguity for customers attempting to generate off it.  If we chose to leave the snapshot parameter in swagger, I believe we can just set snapshot to default in the BlobClients.  What do you think?

**Comment by tg-msft** [comment]
I think we should leave it in the swagger as well and stop taking it as an input parameter on all of the high level `*Client`'s methods.  By not passing it to the generated protocol layer from the high level methods, it just won't add anything to the URI.

If customers want to operate on a snapshot, they'll call `*Client.WithSnapshot(...)` to give them a client with the snapshot already added to the URI and automatically lighting up any APIs that operate specifically on snapshots.

We just need to make sure the query parameter name is consistent for all snapshot APIs, remove the snapshot parameters in all our handwritten code, and update the tests to use `WithSnapshot`.

**Comment by seanmcc-msft** [comment]
Ok, I'm going to take this task then, as it isn't swagger-dependent.

**Comment by seanmcc-msft** [comment]
@tg-msft, what about APIs such as GetPageRangesDiff, that currently take parameters snapshot and previousSnapshot?

**Comment by seanmcc-msft** [comment]
On second thought, most the APIs with the snapshot parameter are on PageBlobClient, and it seems more intuitive to me to just leave them as-is.  What is the impetus for this issue?

**Comment by tg-msft** [comment]
I think it makes sense to leave both on `GetPageRangesDiff`.

I recall this being a change your team requested during one of the API reviews.  I could go either way here -- mind syncing with Keith and then the two of you can make the call?

**Comment by kurtzeborn** [comment]
@seanmcc-msft can you close this issue if you agree we no longer want to do anything here.

**Comment by amishra-dev** [comment]
Since there has been no user complaints about this and this has not been flagged by arch board, lets consider this cut. We can reactivate if this comes back as feedback from the users.
