### ISSUE TITLE
Have RetriableStream take an HttpPipeline instead of a ResponseClassifier

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#6889]
Our clients typically only hang on to the `HttpPipeline` after building it from our `ClientOptions` as it's all we need to make requests.  Unfortunately `RetriableStream` only takes a `ResponseClassifier` and the number of retries.

This means we'll need to pull certain values off the `ClientOptions` and thread them through the service hierarchy to use `RetriableStream` correctly (i.e., calling `new BlobServiceClient(..., new BlobClientOptions() { ..., ResponseClassifier = new CustomClassifier() }) .GetBlobContainerClient(...) .GetBlobClient(...) .Download()` would require threading the `ResponseClassifier` all the way down that chain).

It would be easier to implement if we could pass an `HttpPipeline` to the `RetriableStream` which then internally checked `HttpPipeline._responseClassifier`.

**Comment by pakrym** [comment]
HttpPipeline now exposes the ResponseClassifier so you don't have to carry it around. I don't want to require HttpPipeline to construct `RetriableStream` because it doesn't strictly require it.

**Comment by tg-msft** [comment]
Opening back and assigning to me to properly use this in Storage
