### ISSUE TITLE
Storage: Add convenience for File Upload

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#6893]
Add a convenience method to automatically upload an entire as a series of ranges

**Comment by seanmcc-msft** [comment]
@amnguye, It might be good to ask @tg-msft what he has in mind for this.

I'm thinking maybe we add overloads for the following methods, swapping Stream content for File file:
- BlobClient.Upload(Stream content)
- BlobClient.UploadAsync(Stream content)
- FileClient.UploadRange()
- FileClient.UploadRangeAsync()

I'm thinking users using AppendBlobClient and PageBlobClient will know how to convert a File to a FileStream.  @tg-msft, what do you think?

**Comment by tg-msft** [comment]
@seanmcc-msft - I think you're looking at a different type of convenience method that we don't currently have a work item (or plan) for yet.

This bug is specifically about making it possible to upload a 1GB file to File Storage without having to manually split it into 4mb chunks that you individually pass to `UploadRangeAsync`.  We did this for the simple `BlobClient` at https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/BlobClient.cs#L472 and need something similar for `FileClient`.

I think the names `FileClient.Upload`/`FileClient.UploadAsync` would fit pretty naturally next to `FileClient.UploadRange`/`FileClient.UploadRangeAsync`.

**Comment by seanmcc-msft** [comment]
Oh never mind, I didn't understand what this issue was.  Please disregard.
