### ISSUE TITLE
Storage: API feedback - change small IEnumerable<T>s to T[]s

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#6894]
Update the Queue response types to return arrays instead of `IEnumerable<T>`s

We should do this for QueueClient's PeekMessages and DequeueMessages

**Comment by tg-msft** [comment]
We could do this change in the generator, but this will actually be easier in the code.

**Comment by ShivangiReja** [comment]
Closed with https://github.com/Azure/azure-sdk-for-net/pull/7750
