### ISSUE TITLE
Storage: Make the CORS rules nullable

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#6895]
In our (Blob/Queue/File)ServiceClient.SetPropertiesAsync method, we need to allow the list of Cors rules to be null to indicate they should be ignored instead of cleared (per https://docs.microsoft.com/en-us/rest/api/storageservices/set-blob-service-properties).

**Comment by tg-msft** [comment]
I think we'll want to do this with a new swagger attribute that we specify on these models and then allow null to prevent them from showing up in the generated code.

**Comment by tg-msft** [comment]
If we call the new swagger attribute something like `x-az-nullable-array`, we could add one via Azure.Storage.Blobs/swagger/readme.md changes like:

```
    ### Make CORS allow null values
    It should be possible to pass null for CORS to update service properties without
    changing existing rules.
    ``` yaml
    directive:
    - from: swagger-document
      where: $.definitions.StorageServiceProperties
      transform: >
        $.properties.Cors["x-az-nullable-array"] = true;
    ```
```

Then we'd use the [serviceModel.ts](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Common/swagger/Generator/src/serviceModel.ts#L398) to mark the property as read/write and update [generator.ts](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Common/swagger/Generator/src/generator.ts#L862) to respect it and [not initialize by default.](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Common/swagger/Generator/src/generator.ts#L905)

**Comment by ShivangiReja** [comment]
Closed with https://github.com/Azure/azure-sdk-for-net/pull/7766
