### ISSUE TITLE
[P0] Storage: Use structs for our model types where appropriate

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#6897]
Change the code generation to use structs for model types identified in the API review

**Comment by tg-msft** [comment]
We've got support for this in the generator and now we just need to enable it for types we want to make structs.

**Comment by pakrym** [comment]
We might need fewer structs rather than more. For example I think all *Info types should be consistent in whether they are classes or structs and some of them are too large to be structs so I think they all should be classes.

**Comment by pakrym** [comment]
There are also structs like FileSmbProperties that are large and mutable.

**Comment by pakrym** [comment]
I propose the following rules for making things structs:
- Not *Info\*Headers\*Properties types - they might grow and only one is created per client call so perf doesn't matter.
- Not mutable, especially not types used as mutable model properties
- Fewer than 5 members

**Comment by tg-msft** [comment]
Assigning to @pakrym to close if he thinks we're good here.  (Thanks for the help!)

**Comment by tg-msft** [comment]
Looking at the latest APIs and pending PRs, we're down to just a handful of structs that meet Pavel's recommendations above.  Closing the issue.
