### ISSUE TITLE
[P1] Storage: Use flags enums for various options types

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#6902]
A lot of our options types should be Flags enums instead of structs full of bools.  We can just add `To***`/`Parse` extension methods on `BlobExtensions` to serialize/deserialize as appropriate.  We'll probably need to wait for the API review to get the full list of types we should convert into enums.

Look at [`BlobSasPermissions` as an example](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/Sas/BlobSasPermissions.cs).  I think we make that a `[Flags] public enum BlobSasPermissions { /* ...  */ }` and add `string ToPermissionsString(this BlobSasPermissions permissions)` and `BlobSasPermissions ParsePermissionsString(string permissions)` on `BlobExtensions`, but the API review should make that clear.

**Comment by amishra-dev** [comment]
Feel a little too late atm, if it gets flagged by arch board we will reconsider, for now lets consider this cut.

**Comment by tg-msft** [comment]
I disagree - I think this is a big usability problem with our APIs and want to keep it open.
