### ISSUE TITLE
Add "content hydration hooks" to recorded tests

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#6903]
Storage has a couple of tests where we'd like to upload large (>=1GB) files without bloating the size of the recordings that everyone has to sync in their repo.  We should devise a system where we can simply store a seed/size in the content on disk and have the recording turn back into that same random series of bytes when we play back the recording.

**Comment by pallavit** [comment]
@tg-msft given recordings are going to move out of the repo, do you still see value in supporting this scenario?

**Comment by tg-msft** [comment]
There's definitely value in the scenario, but I also don't think we'll ever get around to implementing so closing for now.
