### ISSUE TITLE
Testing Proposal: Simplify test recording serialization

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#6906]
It would be great to either:

1. Add customizable `ExcludedRequestHeaders`/`ExcludedResponseHeaders` that we skip on comparison/serialization.
2. Check whether an existing recording matches the current recording before we serialize and skip it if they're the same.

Either option allows us to just xcopy the recordings back into our src directory to see what's been updated.  Option 1 has the benefit of cleaner diffs at the cost of a little more service specific work.

Thoughts?

**Comment by pakrym** [comment]
What's the goal here?

**Comment by tg-msft** [comment]
I have about one thousand Storage tests and it's kind of a pain to update recordings when I make a change.  I generally:

- implement the feature,
- see which tests fail during playback,
- turn on recording,
- tell nUnit to run just the failed tests from the previous run,
- then copy only the test recordings with recently updated timestamps (across `n` different directories)

The nUnit test runner in VS is very flaky and this process can be error prone.

I'd much rather only write out test recordings when there's a meaningful change so I can xcopy the recordings back into my source directory.

**Comment by pakrym** [comment]
I see, so the goal is to avoid re-recodings. Last time I thought about it response content was a hard thing to handle as it often contains things like creation timestamps.

**Comment by tg-msft** [comment]
I'd be perfectly happy to opt into this by authoring a custom `RecordingComparer` or similar that handled Storage specific content parsing.

**Comment by tg-msft** [comment]
\+ @maririos @schaabs @AlexGhiondea for their thoughts here too

_(Anyone else spend a lot of time recording tests?)_

**Comment by pakrym** [comment]
> I'd be perfectly happy to opt into this by authoring a custom RecordingComparer or similar that handled Storage specific content parsing.

Sounds good, I'll prototype something.
