### ISSUE TITLE
[BUG] ServiceBus Session Closes if no messages after MessageWaitTimeout even if it was Renewed

### ISSUE THREAD

**Issue by corneliutusnea** [Azure/azure-sdk-for-net#6922]
**Describe the bug**
The ServiceBus session automatically closes if there are no messages received in the MessageWaitTimeout time even if I continuously triggered the RenewSessionLockAsync.

***Code***
The issue seems to be this line:
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Microsoft.Azure.ServiceBus/src/SessionReceivePump.cs#L214
It assumes that if MessageWaitTimeout passed with no messages it should automatically close the session.

**To Reproduce**
1. Open a ServiceBus Session and Send a Message
2. Register a session handler with a `MessageWaitTimeout`=1m
3. Every 20seconds renew the session using `RenewSessionLockAsync`
4. Wait for 1m after the last message was received and notice the session just dropped out

***Code Snippet***
-

**Expected behavior**
`RenewSessionLockAsync` should take priority over MessageWaitTimeout. `MessageWaitTimeout` The first is a value I control only when the session is started. But application control and decisions can make me want to explicitly prolong the session that I hold longer than the initial `MessageWaitTimeout` by calling `RenewSessionLockAsync`. 
Because `MessageWaitTimeout` takes priority in closing the session also the value of `LockedUntilUtc` is meaningless. Even if `LockedUntilUtc` gives me a value 10m in the future, if the `MessageWaitTimout` is 2 minutes, I will loose the session after 2 minutes with no way to stop that.

If this is not desired (which means as a developer I loose control of how long the session should be held) then the documentation for the `MessageWaitTimeout` (https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.sessionhandleroptions.messagewaittimeout?view=azure-dotnet) should be updated to explicitly say that this will instantly close the session when it timesout with no way of recovery.

**Comment by kurtzeborn** [comment]
Thanks for opening this issue and even suggesting the fix!  I've routed this to the appropriate team for follow up.

**Comment by nemakam** [comment]
@corneliutusnea , Its a good ask, I understand the current implementation isn't really geared at your use-case. But I worry it would become a breaking change for most of the users of SessionPump as this isn't a bug, but a completly different design itself. 
This is something that cannot be changed as of now. If needed, new pump options / new pump needs to be created.
Alternatively, do you think something like https://github.com/Azure/azure-service-bus-dotnet/pull/624, where you can register a message handler on a given session would work for you?

**Comment by corneliutusnea** [comment]
@nemakam I'm not sure if that other design will work. We are using the normal `RegisterSessionHandler` to pickup any new session available but once we pick it up we want to control how long it stays alive.
I understand now wanting to change the behavior of `MessageWaitTimeout` as it might break existing code expecting the pump to timeout.
My guess is that people that manually renew via `RenewSessionLockAsync` would understand that calling this overrides the `MessageWaitTimeout`. 
So maybe this approach would work: in the pump, once the timeout is hit and if the `RenewSessionLockAsync` was called and the locktime is not done, instead of dropping the session just continue with the session and go back in the pump.

Thoughts?

**Comment by nemakam** [comment]
There is no way to distinguish between user calling `RenewSessionLockAsync` and the pump itself calling it. The pump already ensures using a background task that the session is always renewed till renew timeout. If we go ahead with this change, then it would mean that no matter how many messages exist, the session pump will not close a given session till it has reached the auto-renew-lock timeout

**Comment by axisc** [comment]
@corneliutusnea, thanks for raising this issue. I was curious about your use-case and wanted to check if there was another pattern you could utilize. Controlling a session lifecycle from the receiver side feels like an anti-pattern.

Ideally, the receiver should know only about where the messages should be received from and what can/should be done once those are available. 

Having the receiver actually control the session by querying it fits a 'database'-esque setup where you can query the data at that point in time. Given that keeping the session open on the receiver requires computation, I'd recommend against it. If there are messages in that session, the receiver can pick up the next time it calls receive.

**Comment by corneliutusnea** [comment]
@axics You already give me control over the session lifecycle as the receiver. That's the whole point of being the receiver and accepting a session, I get full control over that session while I have it don't I?
The only issue I have is that control seems to be oddly limited to "you have control _while_ you receive messages or for how long _you don't get_ messages".  There is no in between. If I have the session I should be able to choose how I handle it. The cost of maintaining a session sticky is less (for me) than the warm-up/cool-down I pay when I start/finish a session on a receiver.

This is a limitation of the SDK not of the ServiceBus which feels like a very random limitation.

Lastly, from my testing, the scenario of re-picking up a session does not work very well, as by the time I get to re-pick the session it might have been picked by another consumer thus I re-pay the cost to wam-up & cool-down another receiver.

**Comment by axisc** [comment]
@corneliutusnea  thanks for the context.

Your expectations are correct, and the only reason I recommended against it was the fact that keeping a session open on the service bus broker requires computation (and provides no benefit when there are no messages in the given timeframe). 

The SessionHandler is meant to mimic push semantics in a pull setup, but there are some optimizations that need to be done and abstracted away from the client application. This is done in an attempt to keep the client code simple.

Alternatively, you may consider using [SessionClient](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Microsoft.Azure.ServiceBus/src/SessionClient.cs) to explicitly manage the session.

Do let me know if there are any other questions.

**Comment by axisc** [comment]
@corneliutusnea 

I'll close the issue for now. Please feel free to reopen if you have any further questions.
