### ISSUE TITLE
Is it intended that if a Subscription does not exist a ServiceBusCommunicationEx is thrown instead of a MessagingEntityNotFoundEx?

### ISSUE THREAD

**Issue by TheReaLee** [Azure/azure-sdk-for-net#6943]
**Query/Question**
Is it intended that if a Subscription does not exist a ServiceBusCommunicationEx is thrown rather than a MessagingEntityNotFoundException?

***Why is this not a Bug or a feature Request?***
Our team is currently building a wrapper around the Microsoft.Azure.ServiceBus project and have noticed that when a Topic or Queue does not exist a **MessagingEntityNotFoundException** is thrown whereas when a Subscription does not exists a **ServiceBusCommunicationException** is thrown. 

Is this intended and if yes why so?... Doesn't a Topic + Subscription make up a Messaging Entity?

**Setup**
 - OS: Windows 10 version 1809
 - IDE : Visual Studio Enterprise 2019
 - Version of the Library used: 3.4.0
 
```
protected override void SubscribeInternal()
{
	RetryExponential retryExponential = new RetryExponential(TimeSpan.FromSeconds(5), TimeSpan.FromSeconds(20), 3);

	string topicName = "TestTopic";
	//This subscription has not been created
	string subscriptionName = "Sub1";

        _azureSubscriptionClient = new SubscriptionClient(this._getConnectionString(), topicName, subscriptionName, ReceiveMode.PeekLock, retryExponential);
	MessageHandlerOptions messageHandlerOptions = new MessageHandlerOptions(_onExceptionThrownHandler)
	{                   
	    MaxConcurrentCalls = _topicSubscriptionConnectionOptions.MaxConcurrentMessages,                   
	    AutoComplete = false
	};
	_azureSubscriptionClient.RegisterMessageHandler(_onMessageReceivedHandler, messageHandlerOptions);
}

private Task _onExceptionThrownHandler(ExceptionReceivedEventArgs exceptionReceivedEventArgs)
{
    Exception exception = exceptionReceivedEventArgs.Exception;
    //exception.GetType() == 'ServiceBusCommunicationException'
    ...
}

private async Task _onMessageReceivedHandler(Message message, CancellationToken token)
{
    ...
}
```

**Comment by kurtzeborn** [comment]
Thanks for opening this issue.  I've attempted to route this to the appropriate team who should be able to get you an answer on what's going on here.

**Comment by TheReaLee** [comment]
@kurtzeborn any news about this?

**Comment by jsquire** [comment]
@nemakam, @binzywu : Would one of you be so kind as to offer your thoughts?

**Comment by SeanFeldman** [comment]
I think the issue is more general. It's not just about subscriptions. It's about any entity. Currently, `MessagingEntityNotFoundException` is only thrown on `NamespaceManager` operations, but not `MessageSender`/`MessageReceiver`. I can send a PR.

**Comment by SeanFeldman** [comment]
I've run through a scenario where a connection is established, the subscription is removed, and an operation to send/receive a message is attempted. The issue is that `AmqpLinkCreator.CreateAndOpenAmqpLinkAsync()` will throw. When it does, it will convert the exception using `AmqpExceptionHelper.GetClientException(connectionError)`, where `connectionError` is a boolean determined by ` session.IsClosing()`. This will always be true given that a line above `session.SafeClose(exception);` is called. As a result of that `AmqpExceptionHelper.ToMessagingContractException()` will return `ServiceBusCommunicationException` rather than `MessagingEntityNotFoundException`.

@nemakam does this sound right to you?

**Comment by SeanFeldman** [comment]
BTW, a simpler way to repro this would be:
```c#
var receiver = new MessageReceiver(connectionString, "topic/sub"); // let `topic` exist, but not `sub`
await receiver.ReceiveAsync();
```

**Comment by axisc** [comment]
@TheReaLee  - thanks for raising this. 

I think this is definitely a MessagingEntityNotFoundException. 
Adding it to the backlog and assigning the January milestone to it.
