### ISSUE TITLE
[EventHubs] Refactor Diagnostics Live Tests 

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#6970]
The current implementation of the Diagnostics Live Tests was directly extracted from Track One and properly adapted into Track Two.

However, the tests we have now are too long and they don't follow the "test one and only one thing" principle, making it harder to accurately pinpoint future failures.

It's necessary to refactor these into small unit tests that test only one thing each.

**Comment by jsquire** [comment]
This task is now obviated by the work done for diagnostics in Track Two.   The approach changed and relies on work from `Azure.Core`, and is covered by its own suite of tests.
