### ISSUE TITLE
Upgrade the references Microsoft.Rest.ClientRuntime.Azure.TestFramework

### ISSUE THREAD

**Issue by yaohaizh** [Azure/azure-sdk-for-net#6987]
Need update ActiveDirectory here: 
https://github.com/Azure/azure-sdk-for-net/blob/f4c8a9e67d3fd323fcc72270b92871128ae5c288/sdk/mgmtcommon/TestFramework/ClientRuntime.Azure.TestFramework/Microsoft.Rest.ClientRuntime.Azure.TestFramework.csproj#L43

https://github.com/Azure/azure-sdk-for-net/issues/6458 depends on this fix. Thanks.

**Comment by erich-wang** [comment]
it is similar to https://github.com/Azure/azure-sdk-for-net/issues/7006.

**Comment by jsquire** [comment]
Given the age of this issue and the deprecation of most of the track one libraries, closing this as stale.  Please feel free to reopen if this is still needed.
