### ISSUE TITLE
Rebuild Role Instance is not implemented for Compute's IDeploymentOperations

### ISSUE THREAD

**Issue by jessey-git** [Azure/azure-sdk-for-net#701]
We have a need to automate operations against role instances and Rebuild seems to be missing: http://msdn.microsoft.com/en-US/library/azure/dn627518.aspx<p><a href="https://github.com/Azure/azure-sdk-for-net/issues/701">https://github.com/Azure/azure-sdk-for-net/issues/701</a></p>

**Comment by markcowl** [comment]
Closing as obsolete.  Please reopen if this issue recurs
