### ISSUE TITLE
Asp .net app hangs(deadlocks) when using SqlAppAuthenticationProvider. Microsoft.Azure.Services.AppAuthentication 1.3.0

### ISSUE THREAD

**Issue by mllab-nl** [Azure/azure-sdk-for-net#7013]
**Describe the bug**
Asp .net app hangs(deadlocks) when using SqlAppAuthenticationProvider

**To Reproduce**
1. Have an application running using LegacyAspNetSynchronizationContext ( Asp.net apps )  
2. Register SqlAppAuthenticationProvider
SqlAuthenticationProvider.SetProvider(SqlAuthenticationMethod.ActiveDirectoryInteractive, new SqlAppAuthenticationProvider());
3. When web requests comes open SQL connection 

Reason:
missing .ConfigureAwait(false) in AzureServiceTokenProvider.GetAccessTokenAsync

IMHO this as a blocking issue that needs to be fixed/shipped ASAP

**Comment by mllab-nl** [comment]
https://github.com/Azure/azure-sdk-for-net/pull/7014

**Comment by maggiepint** [comment]
Thanks so much for this. I have routed to the appropriate team for follow-up.

**Comment by nonik0** [comment]
@mllab-nl Thank you for reporting this, this has been fixed in the [AppAuth 1.3.1 release](https://www.nuget.org/packages/Microsoft.Azure.Services.AppAuthentication/1.3.1). Please let us know if you have any further issues.
