### ISSUE TITLE
[How to add custom authorization ]

### ISSUE THREAD

**Issue by ashishkaushik123** [Azure/azure-sdk-for-net#7015]
**Query/Question**
A clear and concise ask/query.
i have generated a C# client using autorest using swagger.yaml , but now i  need to add a custom authorization to my request .
***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?
N/A
**Setup (please complete the following information if applicable):**
 - OS: [e.g.windows]
 - IDE : [e.g. Visual studio code]
 - Version of the Library used -- autorest latest
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [ ] Setup information Added

**Comment by maggiepint** [comment]
Issue moved to [Azure/autorest #3291](https://github.com/Azure/autorest/issues/3291) via [**ZenHub**](https://www.zenhub.com/)

**Comment by maggiepint** [comment]
Hi,

I think what you are asking is how to add custom authentication in an autorest generated client. I am moving this to the AutoRest repo as the appropriate location.
