### ISSUE TITLE
net - mgmt build pipelines should switch to unified pipelines

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-for-net#7020]
Currently there are instructions for publishing mgmt libraries at https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#signing-and-publishing-nuget-packges, that process currently has a build pipeline and a release pipeline that gets auto triggered. However with the new unified pipelines we can put those into the same pipeline which will make finding the artifacts easier in the instructions. Currently the instructions say to find the deployments under the summary of the build however when the DevOps UI changes for unified pipelines those don't currently show up on the build summary page, I"m not sure if that is a DevOps bug or a design change but in either case I think switching to a unified pipeline will make this process much simpler. 

I would do that for both "net - mgmt" and "net - mgmt - pr". 

cc @erich-wang @shahabhijeet @mitchdenny

**Comment by erich-wang** [comment]
I'll address it when I have time

**Comment by jsquire** [comment]
From a quick look at the pipeline, it looks like this was done so I'm going to close this out as stale.   Please feel free to reopen if this is still needed.
