### ISSUE TITLE
500 - The request timed out. The web server failed to respond within the specified time.[BUG]

### ISSUE THREAD

**Issue by VidyaSalimath** [Azure/azure-sdk-for-net#7023]
Hello Team,

Am getting the 500 request timeout issue while hosting SharePoint Provider hosted app.Is there a way to increase the timeout settings of App service plan?

Regards,
Vidya

**Comment by loarabia** [comment]
Thanks for reporting this. I've tagged it to route to the right team.

**Comment by lilyjma** [comment]
@VidyaSalimath is this still a problem for you?

**Comment by Mohankade09** [comment]
I am facing similar issue for azure function v3

**Comment by AlexGhiondea** [comment]
Thank you for reporting this. The issue does not contain enough information to be actionable. Please file a new issue with additional details so we can better help you.
