### ISSUE TITLE
[FEATURE REQ] Support for AMQP v1.0.0 standard: "ContentEncoding" (OASIS + RFC 2616)

### ISSUE THREAD

**Issue by motmot80** [Azure/azure-sdk-for-net#7027]
The `Microsoft.Azure.ServiceBus.Message` class does not provide the AMQP v1 property "**content-encoding**" which is described in the official standard (field 7):

http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-messaging-v1.0-os.html#type-properties

On the other hand the `Microsoft.Azure.Amqp.AmqpMessage` does provide the property and f.e. other libraries like **amqpnetlite** are offering it, too.

It should be trivial to extend `Microsoft.Azure.ServiceBus.Message`  and `Microsoft.Azure.ServiceBus.Amqp.AmqpMessageConverter` to support this property. Just like `Message.ContentType`. 

Right now we are using an expensive application property in a none standard way to tell the consumer the content encoding is "deflate", "gzip" etc.

Thanks and best regards,
T.

**Comment by jfggdl** [comment]
@motmot80, We are adding this feature request to our backlog. Please note that do not have a date on when this feature might hgbe implemented as there is some investigation that has to happen on the implications to support this feature across all SDKs (languages).

**Comment by axisc** [comment]
@motmot80  
Thanks for reporting this, I've added this to the internal engineering backlog. Closing it here.

https://msazure.visualstudio.com/One/_workitems/edit/5044415
