### ISSUE TITLE
[BUG] Azure.Storage *ClientOptions classes have ServiceVersion specified but not used.

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#7040]
**Describe the bug**
In Azure.Storage.sln, StorageClientOptions.cs, BlobClientOptions.cs, and QueueClientOptions.cs all specify the service version, establishing the pattern to do so for the .NET design guidelines.  These values are not used in the project, though -- the versions used to communicate with the backend services appear to be hard-coded, as shown in [BlobRestClient.cs](https://github.com/Azure/azure-sdk-for-net/blob/91c376a50b30ba9b407e00e25bab61acaf6c976a/sdk/storage/Azure.Storage.Blobs/src/Generated/BlobRestClient.cs#L95).

***Exception or Stack Trace***
N/A

**To Reproduce**
N/A

**Comment by tg-msft** [comment]
This is blocked on #6283 and will be fixed automatically as part of that change.
