### ISSUE TITLE
[FEATURE REQ] Consider adding Azure.Security.KeyVault.Common project to Azure.Security.KeyVault

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#7041]
**Is your feature request related to a problem? Please describe.**
Common functionality was duplicated across projects when adding version-to-string logic in [PR 6915](https://github.com/Azure/azure-sdk-for-net/pull/6915), specifically the GetVersionString method in [KeyClientOptions.cs](sdk/keyvault/Azure.Security.KeyVault.Keys/src/KeyClientOptions.cs) and [SecretClientOptions.cs](sdk/keyvault/Azure.Security.KeyVault.Secrets/src/SecretClientOptions.cs).

**Describe the solution you'd like**
Consider adding an Azure.Security.KeyValue.Common project to house code that's common across products.

**Describe alternatives you've considered**
For now, the code was copied across files.

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ X] Description Added
- [ X] Expected solution specified

**Comment by AlexGhiondea** [comment]
We are sharing code via a shared code project. While having a common libraries might help, in this case they introduce another layer of dependency that we should try to avoid.
