### ISSUE TITLE
Storage: Move Auth policy to PerRetryPolicies so users could theoretically use their own retry policy

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#7051]
There's not a _good_ way for users to implement their own retry policy, but it should at least be _possible_.   We need to change the code in StorageClientOptions that builds the pipeline to move the auth policy from the params "client policies" into the PerRetryPolicies collection.  Then users could at least change the RetryOptions to 0 retries and use their own.

**Comment by tg-msft** [comment]
@pakrym - What are your thoughts on this?  Is it okay to add policies to the user's `BlobClientOptions`?   Or should we really be sticking with the `clientPolicies`?

**Comment by pakrym** [comment]
I'm not sure I understand the connection between the location of auth policy and being able to replace retry policy.

**Comment by pakrym** [comment]
>  Is it okay to add policies to the user's BlobClientOptions

Nope, it's not, we shouldn't mutate passed in objects.

> Or should we really be sticking with the clientPolicies?

Why not use 
```C#

        public static HttpPipeline Build(ClientOptions options, HttpPipelinePolicy[] perCallClientPolicies, HttpPipelinePolicy[] perRetryClientPolicies, ResponseClassifier responseClassifier)
```
overload?

**Comment by tg-msft** [comment]
If the user wants to fake their own retry policy, they could set MaxRetries to 1 and add their custom retry policy as the first PerRetry policy.  If we added the auth as a PerRetry policy, then it all works.  The reason to not use the `perRetryClientPolicies` on build is they'd happen before the user's PerRetry policies.

But it sounds like the correct answer is to ignore this until you make it possible to customize retry policies.  Thanks!
