### ISSUE TITLE
[BUG] Higher number of Outgoing Messages when using Batch Receive

### ISSUE THREAD

**Issue by goenning** [Azure/azure-sdk-for-net#7057]
**Describe the bug**
When using Batch ReceiveAsync, I'm seeing a higher number of outgoing messages on Azure Service Bus compared to when ReceiveAsync(1) is used.

***Exception or Stack Trace***
N/A

**To Reproduce**
- Create a console app that sends a message every 100~300 ms
- Create a console app that consumes 10 messages every second using MessageReceiver

***Code Snippet***
https://gist.github.com/goenning/80ff763b4cc47a338bfae5d3de42bb17

**Expected behavior**
The red metrics shown below happens when using **ReceiveAsync(10)**. The number of Outgoing Messages is higher than the Incoming. During green metrics I was using **ReceiveAsync(1)**, in which case the total Outgoing Messages matched the Incoming Messages.

I'd expect the number of Outgoing Messages to match Incoming Messages regardless of using batch receive or not. I have confirmed that in this scenario there was no Re-delivery, every message was delivered exactly once (at least from the Consumer app perspective).

**Screenshots**
![image](https://user-images.githubusercontent.com/94755/62226087-8d236080-b3b1-11e9-94ec-007d54da481d.png)

**Setup (please complete the following information):**
 - OS: Windows
 - IDE : VS2019
 - Version of the Library used: Microsoft.Azure.ServiceBus@3.4.0

**Additional context**
This might not be a bug and possible working as designed, but in this case, why is this happening?

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by nemakam** [comment]
@goenning, thanks for the detailed description, but this looks like a support investigation and opening this issue through "support ticket" on the Azure portal would be the better route for this. They can take a look a service side logs for your namespace and guide further.
