### ISSUE TITLE
[Storage] Cannot build .NET Storage SDK with default installation of Visual Studio 2019

### ISSUE THREAD

**Issue by seanmcc-msft** [Azure/azure-sdk-for-net#7064]
**Describe the bug**
I cannot build the .NET Azure Storage SDK with the default installation of Visual Studio 2019 (Community and Enterprise)

***Exception or Stack Trace***
None.

**To Reproduce**

* Create a new Azure VM
  * [https://ms.portal.azure.com/](https://ms.portal.azure.com/)
  * Virtual Machines tab on the left
  * "+ Add"
  * On the "Create a virtual machine" page
    * Image: Windows 10 Pro, Version 1809
    * Size: Standard D3 v2
    * Wait for your VM to deploy
* Connect to the new VM
  * Click the "Virtual machines" tab on the left
  * Search for your new VM by name
  * Select the VM, click the "Connect" button at the top
* Download and install Git
  * [https://git-scm.com/downloads](https://git-scm.com/downloads)
  * Install Git with default settings
* Download Visual Studio Community 2019
  * [https://visualstudio.microsoft.com/downloads/](https://visualstudio.microsoft.com/downloads/)
  * Install Visual Studio Community 2019 **without any workloads.**  Note that there are no workloads listed in [https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/CONTRIBUTING.md) or [https://github.com/Azure/azure-sdk-for-net/blob/master/CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/master/CONTRIBUTING.md)
* Clone the repository
```
C:\>git clone https://github.com/Azure/azure-sdk-for-net.git
```
* Attempt to open the repository in Visual Studio
  * Open the solution file in Visual Studio
```
C:\azure-sdk-for-net\sdk\storage\Azure.Storage.sln
```

***Code Snippet***
None.

**Expected behavior**
I expect to be able to build the solution in Visual Studio 2019.

**Screenshots**
![error](https://user-images.githubusercontent.com/44180881/62252075-95c26980-b3a6-11e9-9662-5b77dec8d62a.png)

**Setup (please complete the following information):**
 - OS: Windows 10 version 1809
 - IDE : Visual Studio 2019 Community
 - Version of the Library used: latest commit in master

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by tg-msft** [comment]
Someone on the Engineering Systems side should run through this, capture all of our implicit requirements, and update CONTRIBUTING.md to enable new folks getting started with our project.

**Comment by chidozieononiwu** [comment]
I have updated contributing guidelines for this. I still cannot repro the source link error. It might be best to file a separate issue to track that, and include more details about the system and environment where it occurs.
