### ISSUE TITLE
Azure.Core README.md Response sample does not dispose the response objects

### ISSUE THREAD

**Issue by j82w** [Azure/azure-sdk-for-net#7082]
**Describe the bug**
None of the Disposable objects are disposed of in the Azure.Core [README.md](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/core/Azure.Core#accessing-http-response-details-using-responset). Both the `Response` [here](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/Response.cs), `Response<T>` [here](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/ResponseOfT.cs), and Stream implement IDisposable.

**Expected behavior**
Dispose of all Disposable objects.  This will prevent any memory leaks.

**Screenshots**
![image](https://user-images.githubusercontent.com/8868107/62325532-b51dcd00-b460-11e9-9020-90bec4aae16c.png)

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by pakrym** [comment]
This sample is correct, while the types do implement IDisposable none of the usages you've highlighted strictly require disposal in the current implementation.
