### ISSUE TITLE
Azure.Identity update InteractiveBrowserCredential to enable use of alternative ports

### ISSUE THREAD

**Issue by schaabs** [Azure/azure-sdk-for-net#7086]
InteractiveBrowserCredential currently defaults to listening on port 80 for the authentication code redirect.  This should be updated to be configurable, and pick a random available port by default.

**Comment by pallavit** [comment]
@christothes , @schaabs is this still a concern?

**Comment by christothes** [comment]
I'm going to close since this has been unaddressed for so long. We can re-open if necessary,
