### ISSUE TITLE
Why does the SDK guideline define the necessity for sync methods?

### ISSUE THREAD

**Issue by danielmarbach** [Azure/azure-sdk-for-net#7092]
**Query/Question**

![image](https://user-images.githubusercontent.com/174258/62359529-451e4e00-b517-11e9-889a-152517b308aa.png)

https://azuresdkspecs.z5.web.core.windows.net/DotNetSpec.html

Why does the SDK guideline define the necessity of providing sync method overloads? How are you planning to implement those? I hope you are not going to use `GetAwaiter().GetResult()` but have a clear dedicated synchronous HttpPipeline? But still why is this required at this day of age when Task returning APIs for IO bound domains is the defacto standard?

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by christopheranderson** [comment]
Agree that this seems like an aggressive requirement for the initial releases. Is it common for our existing SDKs to have Sync and Async? Is this a big blocker that we need to prioritize? I'd hope that the scope of Track 2 is focused mostly on alignment and P0 gaps.

**Comment by loarabia** [comment]
Assigning to Krzysztof and Adrian to take a look from the guidelines POV.

**Comment by adrianhall** [comment]
The short version is that, during user studies, developers were confused by the async methods.  As much as we would love for the entire world of developers to be "async aware", we aren't there yet, and may never get there.  Adding synchronous methods provides for an easier introduction to the SDK.

**Comment by SeanFeldman** [comment]
@adrianhall thank you for clarifying the reason behind the guideline.

Would you mind to share the technical expectation of how the synchronous overloads will be implemented? @danielmarbach has brought a concern that would be good to address. Thank you.

**Comment by KrzysztofCwalina** [comment]
I will try to add a justification to the guidelines, but quickly: we are getting feedback that many developers want to start using Azure SDK in existing apps with deep synchronous callstacks. Rewriting the callstack to async is not an option. In such case, the developers are forced to do sync over async. Today the pipeline is doing sync over async also, but in the future we will provide first class synchronous implementation.

**Comment by j82w** [comment]
If the only reason to support synchronous call stacks is to support older existing application would it be better to try to build a library or some other solution as an additional package to convert asynchronous SDK to synchronous? This seems like unnecessary bloat for most users since modern applications are asynchronous. Also by supporting synchronous APIs directly in the SDK users might start building new applications with the sync API. The user will eventually hit scaling/performance issues and have to convert to async. This would also avoid every SDK team from needing to duplicate their entire call stack to support the synchronous calls.
