### ISSUE TITLE
[Query] Service Bus - Does AmqpTransactionManager tx management need to be atomic?

### ISSUE THREAD

**Issue by danielmarbach** [Azure/azure-sdk-for-net#7093]
**Query/Question**

Currently `AmqpTransactionManager` [acquires a lock around a simple dictionary](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Microsoft.Azure.ServiceBus/src/Amqp/AmqpTransactionManager.cs#L30-L42). If the operations in the [case a current enlistment is not present](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Microsoft.Azure.ServiceBus/src/Amqp/AmqpTransactionManager.cs#L34-L41) don't have to be atomic the implementation could be switched to a concurrent dictionary which would boost performance in concurrent scenarios. 

Thoughts @nemakam @jsquire 

Happy to provide a PR.

**Comment by jsquire** [comment]
Thank you for reaching out, Daniel, and your willingness to submit a pull request.  Those are always appreciated.

In this case, I don't have enough familiarity with some of the transaction context to be an authoritative source.  I'll need to defer to @binzywu and @nemakam as the experts in this area, if they'd be kind enough to offer their thoughts.

**Comment by nemakam** [comment]
@danielmarbach, we can definitely consider improving the performance in that area. If only one thread is trying to enlist, then keeping it atomic is easier. But if things are happening concurrently, one thing we need to make sure is that the enlistment should go through, and if it doesn't, we should throw exception. 
If you have a good implementation, we'd love to have the PR.

**Comment by danielmarbach** [comment]
So I was chewing on this a bit and I have mixed feelings. I compared [slightly twisted current AMQP TX Manager](https://github.com/danielmarbach/Benchmark.TxManager/blob/master/Program.cs#L138) towards [one that uses `ConcurrentDictionary`](https://github.com/danielmarbach/Benchmark.TxManager/blob/master/Program.cs#L183). It definitely improves the lock contention overhead by almost a third though it is super hard to create a reliable and stable test harness from which actual meaningful data can be derived.

![image](https://user-images.githubusercontent.com/174258/62492274-678dc100-b7ce-11e9-9559-cfb3176d1f70.png)

Left current version with lock, right version that uses concurrent dictionary

**Comment by danielmarbach** [comment]
I have some micro benchmark results I could publish tomorrow but the problem is the micro benchmarks seem to be even less meaningful

**Comment by nemakam** [comment]
@danielmarbach , I took a quick look on the code that was present in the screenshot. It doesn't take care of the whole thing. If two operations are concurrently trying to call this, and one of them throws after adding and removing from dictionary, but the other operation does a successful `dictionary.get` (due to race condition), how do you make sure that that operation fails? 
The more I think of it, the more I feel there's no easy way to get rid of the lock.

**Comment by danielmarbach** [comment]
Yeah hence my initial question whether the operation needs to be atomic. Based on the conversation above I understood it doesn't have to be but it seem I misunderstood. Yeah then there is no way around the lock to have atomicity around the dictionary modifications. Maybe this should be documented as an inline comment in the code?

**Comment by nemakam** [comment]
Sorry this didn't work out. Thanks for the effort! (y)
