### ISSUE TITLE
Storage: Use nameof for operation IDs instead of constant strings

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#7105]
Per the discussion in #7102, let's switch to expressions like `$"{nameof(Azure)}.{nameof(Storage)}.{nameof(Blobs)}.{nameof(Specialized)}.{nameof(LeaseClient)}.{nameof(Acquire)}"` for our operation IDs instead of constant strings.

**Comment by seanmcc-msft** [comment]
We've already implemented this one.
