### ISSUE TITLE
Sample for adls gen2

### ISSUE THREAD

**Issue by sagarkul** [Azure/azure-sdk-for-net#7115]
Any Sample or documentation to How to access ADLS Gen2 Files.

**Comment by sumantmehtams** [comment]
Attaching a doc that shows how you can use the REST APIs to interact with ADLS Gen2.

[Use-the-REST-API-to-manage-data-in-Azure-Data-Lake-Storage Gen.docx](https://github.com/Azure/azure-sdk-for-net/files/3753351/Use-the-REST-API-to-manage-data-in-Azure-Data-Lake-Storage.Gen.docx)

**Comment by sumantmehtams** [comment]
Feel free to reopen if you need more info. Thanks!
