### ISSUE TITLE
Update .NET Guidelines for Sample file naming

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#7137]
The [.NET Guidelines for Samples](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-samples) specify naming files with a **S\<number\>_**
 prefix.  The AppConfiguration, KeyVault, and Storage libraries have named sample files with a **Sample\<number\>_** prefix instead.  We'll use the **Sample\<number\>_** prefix, and update the guidelines to reflect this.  It would be good to also specify whether the number should have leading zeros and/or lettered sub-cases like Sample1a and Sample1b.

**Comment by KrzysztofCwalina** [comment]
@kaerm, what convention do we want to use? Let's agree on something and I will update the guidelines.

**Comment by kaerm** [comment]
I think sample does sound clearer but wouldn't that make the names of all the samples become long and therefore unreadable?

**Comment by annelo-msft** [comment]
Are there guidelines regarding file name length for client SDK files?

**Comment by kaerm** [comment]
I do not think so @KrzysztofCwalina ?

**Comment by annelo-msft** [comment]
Per separate thread, it sounds like the max path length from repo root is roughly 200, subject to finalization but in that ballpark.  The difference between S\<num\> and Sample\<num\> is five characters.  Given this, I'd vote for clarity.  What do others think @kaerm , @KrzysztofCwalina ?

Per numbering, a leading 0 will help sort them in the IDE/filter in numerical order, but breaks when we exceed 99 samples (which I expect would break a simplicity principle).  So, include the leading 0?

Any thoughts on adding the a, b, etc to numbers?  I'm seeing "Extended" and reusing the same number for Sync/Async in other libraries.  It would be good to standardize on a convention here, too.  My preference would be tersely spelling out differences so the user can see what's in each at a glance, but open to alternatives.

**Comment by jsquire** [comment]
The guidelines appear to have been updated, though the length and leading zero questions from Anne have not been included.    

I'm going to close this out as stale, but please feel free to reopen _(potentially moving to the main Azure SDK repository)_ if further discussion/action is needed here.
