### ISSUE TITLE
Competing Consumers Causing High Number of Epoch Errors

### ISSUE THREAD

**Issue by keggster101020** [Azure/azure-sdk-for-net#7154]
## Actual Behavior
When creating a named consumer as such:
```csharp
new EventProcessorHost(
                Environment.MachineName,
                _configData.EventHubName,
                _configData.EventHubConsumerGroup,
                _eventHubConnectionString,
                _storageConnectionString,
                _configData.EventHubLeaseContainerName
                );
```
And deploying that consumer to different webjobs in different regions, the consumers will consistently throw epoch exceptions multiple times (2-10x) an hour per machine
>New receiver with higher epoch of '20' is created hence current receiver with epoch '19' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:2549e0a3000104e50000f47b5d3adcbd_G6S3_B2S3

## Expected Behavior
Each named consumer will coordinate with the others attaching to 1 or more partitions and coordinating.

## Versions  
- OS platform and version: Windows Server
- .NET Version: .NET Framework 4.6.2
- NuGet package version or commit ID: 3.0.0

**Comment by serkantkaraca** [comment]
Couple questions:
- How many partitions are there?
- How many VMs are there?
- Can you make sure there is no duplicate hostname across regions?

**Comment by axisc** [comment]
@keggster101020

I'm closing this issue for now. If you still experience issues on your end, please feel free to reopen the issue.
