### ISSUE TITLE
Incorrect use of SemaphoreSlim in AsyncLock.cs

### ISSUE THREAD

**Issue by Dirtmigurt** [Azure/azure-sdk-for-net#7155]
## Actual Behavior
1. Calling LockAsync twice on the same AsyncLock object follows the non-contention code path both times

## Expected Behavior
1. The second call to LockAsync should not enter the if statement at AsyncLock.cs:46

You are using the wrong SemaphoreSlim constructor, new SemaphoreSlim(1) creates a semaphore that allows unlimited concurrency. new SemaphoreSlim(1,1) limits max concurrency to 1.

## Versions  
- OS platform and version: Windows 10 Version 10.0.18362
- .NET Version: 4.6.2
- NuGet package version or commit ID: master

**Comment by serkantkaraca** [comment]
Thanks for pointing this. PR is out - https://github.com/Azure/azure-sdk-for-net/pull/7203
