### ISSUE TITLE
EventHubProcessorHost does not support specifying an ITokenProvider, an ICheckpointManger, and an ILeaseManager in one constructor

### ISSUE THREAD

**Issue by sahildesai308** [Azure/azure-sdk-for-net#7156]
## Actual Behavior
1. EventProcessorHost has a constructor that takes an ITokenProvider and a CloudStorageAccount, and a constructor that takes an ICheckpointManager and an ILeaseManager but uses a connection string.

## Expected Behavior
1. EventProcessorHost should have a constructor that takes an ITokenProvider and an ICheckPointManager and ILeaseManager so that MSI can be used while still being able to modify how checkpoints and leases are stored.

## Versions  
- .NET Version: 3.0.0.0
- NuGet package version or commit ID: 3.0.0

**Comment by serkantkaraca** [comment]
Created a PR - https://github.com/Azure/azure-sdk-for-net/pull/7201
