### ISSUE TITLE
Lease failures with v3.0.0 when using blob storage and frequent checkpoints

### ISSUE THREAD

**Issue by Plasma** [Azure/azure-sdk-for-net#7158]
## Actual Behavior
1. When upgrading from `2.2.1` to `3.0.0`, we observed in our environment frequent `ListBlobs` API calls that were taking ~5 seconds consistently towards the blob folder containing the lease files. We had 10 partitions/files.

This seemed to be happening consistently/frequently, only after between 10 mins and 50 minutes did this resolve itself.

We suspect this code was stuck in a loop: https://github.com/Azure/azure-event-hubs-dotnet/blob/257834dfebfe655c2d47e17b5e03bea110a14ca5/src/Microsoft.Azure.EventHubs.Processor/AzureStorageCheckpointLeaseManager.cs#L239-L263

1. The side effect of this method loop never returning was no leases were acquired, or were acquired after a long time (10-50 minutes).

## Our investigation
1. We noted in v3.0.0 is the first time ListBlobs is used
1. We noted for this event hub, we checkpoint very frequently (multiple times per second)
1. We suspect because of this constant checkpointing, Azure Blob Storage, when told to ListBlobs, timed out internally in 5 seconds (see https://docs.microsoft.com/en-us/azure/storage/common/storage-c-plus-plus-enumeration _One reason might be that the query could not complete in five seconds_) and returned zero or more items, and a continuation token.

These ListBlobs API calls were repeated constantly with no delay between invocation, leaving ListBlobsSegmented in the above loop to never be able to complete, as a continuation token was always returned after Azure gave up after 5s to return from ListBlobs, but I assume provided a token to say "try again please".

I suspect because of our frequent writes, perhaps Azure was having trouble returning a complete ListBlobs response when requested within 5 seconds (it was waiting for writes to stop?) and so instead gave up but returned a continuation token.

This caused the loop to take 10-50 mins to return, causing leases not to be taken or any work done.

## Mitigation
We are revising our code to reduce checkpointing frequency in the efforts this solves the problem. We have reverted using v3.0.0 and it went back to normal.

## Expected Behavior
1. This problem not to occur, and leases to be taken as usual

## Versions  
- OS platform and version: 3.0.0
- .NET Version: .NET 4.6x
- NuGet package version or commit ID: 3.0.0

**Comment by serkantkaraca** [comment]
This sounds like a Storage SDK issue. We have moved to up to date Blob SDK in 4.0.0 release. Can you please try and see if issue still reproduces on 4.0.0 ?

**Comment by Plasma** [comment]
Hi @serkantkaraca thank you for taking a look at this issue.

Since I posted this issue we performed further investigation and believe we found the root cause. This is still caused by the event hubs SDK logic, please read on for more.

1. Previously, the SDK did direct reads/writes to known checkpoint files. Now, it does a ListBlobs to find what files are available. The ListBlobs is important, and the cause of this issue.

1. We have Soft Deletes enabled on the storage account that holds the checkpoint files.
1. Because of the frequent writes/updates to the checkpoint files, this causes Azure storage to create snapshots of those files whenever their content changes. This is happening frequently.
1. When you perform ListBlobs() as per https://github.com/Azure/azure-event-hubs-dotnet/blob/257834dfebfe655c2d47e17b5e03bea110a14ca5/src/Microsoft.Azure.EventHubs.Processor/AzureStorageCheckpointLeaseManager.cs#L239-L263 you are (correctly) only wanting to see non-deleted blobs.

However, Azure storage must still "page through" internally beyond the historical snapshot versions.

What this means is, calling ListBlobs() in the directory is looking for (in our case, 10 partitions worth) of blobs, but must first page through 10 partitions with of snapshot revision history (100s of thousands) of blobs for the Storage server to return the active blobs.

This was confirmed by also inspecting Azure storage logs and noticing the ListBlobs API calls were all taking 5 seconds, which is the internal timeout for a continuation token that is returned by Storage when there are no results yet (call again with the next continuation token) as per:

"storage may return no records, or fewer records than the value of the max_results parameter that you specified, even if the continuation token is not empty. One reason might be that the query could not complete in five seconds. " (https://docs.microsoft.com/en-us/azure/storage/common/storage-c-plus-plus-enumeration )

* The end result of the above logic change is that now `GetAllLeasesAsync` is taking 1 hour+ to return instead of a second.

We are not able to upgrade to the latest Event Hubs SDK until this is resolved, or we have to look to move to a separate storage account with soft-deletes OFF just to avoid this issue, but that's a bit frustrating.

I am also worried for others using this system where the performance will begin to degrade and then fail, if they have many updates and soft deletes enabled.

**Comment by serkantkaraca** [comment]
Thanks for your time investigating this. I have 2 questions:

1. I would like to know why you have turned soft-delete ON for lease account? Are you using the same storage account for some other services as well?

2. Were you able to get a confirmation from Storage for this statement "Azure storage must still "page through" internally beyond the historical snapshot versions."?

**Comment by Plasma** [comment]
Hi @serkantkaraca ,

1. We have a few storage accounts for our system, and saw no reason to create a specific storage account for event hubs use. The account itself has had soft deletes enabled since launch.

2. Yes, I can confirm. If you have access to Azure support, its ticket 119053025000495
Below is the latency graph for storage operations on our account the events hubs share, and you can see the ListBlobs latency spikes up to 5000ms.

![unnamed](https://user-images.githubusercontent.com/229209/62743768-11977280-ba87-11e9-979e-619d911ee347.png)

In my support discussion, the support person included a response from the backend team:

> Kindly understand due to the plain blobs design of Azure Blob Storage, the folders are actually virtual folders. When you tried to load the content of folder “xxx”, it actually will enumerate all blobs in folder “aaa”, “bbb” and “ccc” as we by default store the blobs in alphabet order like below

[...]

> Now add to this, there is possibility that you have deleted blobs as well in the directory list that we have to enumerate but we don’t return because they are waiting for GC.

[...]

> We will enumerate everything but return what is asked for. So yes, snapshots also would be enumerated but not returned.

So I believe this to be the issue because:

1. The above latency graph for ListBlobs taking 5 seconds, and the five second note written in https://docs.microsoft.com/en-us/azure/storage/common/storage-c-plus-plus-enumeration about empty enumeration results

1. Azure storage is throwing away list results of snapshots (100s of thousands if not more in our account for the checkpoint files) when trying to find the active blobs

1. Both azure portal and azure storage explorer show very long load times for results when browsing to the checkpoint folder in storage. When I look at Azure portals XHR requests in Chrome debugger, I see a continuation token returned for the next result set, but the result set remains empty, this repeats itself for 30+ minutes at least.

1. Prior to this SDK upgrade, ListBlobs was not used.

Hope that helps.

**Comment by serkantkaraca** [comment]
Unfortunately there is not much we can do to address this issue. ListBlobs is supposed to return list of active blobs, we are not supposed to know internal implementation or design issues at the Storage side. It is very obvious this is a pitfall for any storage account with hot updates and soft-delete. 

We recommend customers to use dedicated storage accounts for Event Hubs Processor Host. Can you move your leases to a dedicated account and turn of the soft-delete? I will consider adding a warning or error during host startup on soft-delete enabled storage accounts so that customers can avoid this in the future.

**Comment by axisc** [comment]
@Plasma

I'm closing this issue for now. Please feel free to reopen if there are further questions.
