### ISSUE TITLE
Question - IEventProcessor :  Is there any/best way to check how many messages left to process on each partition?

### ISSUE THREAD

**Issue by PanClifton** [Azure/azure-sdk-for-net#7159]
Hello 

i was wondering if you can help me.

Is there any/best way to retrieve information from blob container(where the info about state of each partition being kept), how many messages left to process by event processor for each partition?

Kind Regards,
Bartek

**Comment by serkantkaraca** [comment]
You can enable runtime metrics in processor options. Turning it on will start providing end of stream position as part of context that you can use to calculate the backlog.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.eventprocessoroptions.enablereceiverruntimemetric?view=azure-dotnet#Microsoft_ServiceBus_Messaging_EventProcessorOptions_EnableReceiverRuntimeMetric

**Comment by PanClifton** [comment]
thank you
