### ISSUE TITLE
[Feature]AzureStorageCheckpointLeaseManager does not support lease duration more than 60 seconds.

### ISSUE THREAD

**Issue by vishwas-neo** [Azure/azure-sdk-for-net#7160]
Currently lease duration can be at max 60 seconds because of limitation of AzureLeaseBlobs. 
If processing time is more than 60 seconds and we are checkpointing after the processing is complete then it throws LeaseLostException. If we checkpoint before than there is a chance of data loss.

We can take infinite lease on azureblobs and change the expiry logic for partition balancing.
Lease will be considered as expired if it is not modified for time more than lease duration.

**Comment by serkantkaraca** [comment]
Track 2 SDK is dropping direct Storage dependency. This issue won't apply any more so closing.

https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/eventhub/Azure.Messaging.EventHubs
