### ISSUE TITLE
Clarifying event hub errors related to: Renewing Lease, Closing Event Processor, Checking Leases, Stealing Lease

### ISSUE THREAD

**Issue by Plasma** [Azure/azure-sdk-for-net#7162]
## Actual Behavior
We set `options.SetExceptionHandler` and see a few exceptions each day related to:

Renewing Lease, Closing Event Processor, Checking Leases, Stealing Lease

We are wondering if these are potential problems (eg, our leases are incorrectly expiring, or there is an issue somewhere), or whether these are harmless and we can stop logging them.

Thank you

## Versions  
- OS platform and version: .NET Framework
- .NET Version: 4.6.2
- NuGet package version or commit ID: NuGet 2.2.1

**Comment by serkantkaraca** [comment]
With 3.0.0 release we have made some number of improvements to reduce Storage IO calls in turn which reduces chance of hitting Storage exceptions. Please open a dedicated issue for each type of lease failure you are observing.

**Comment by Plasma** [comment]
Hi @serkantkaraca 

Do you mind sharing some insights into the specifics about what happens when a lease is stolen, or fails to be renewed?

For example, assuming we have Worker 1 & 2, and for simplicity one partition/lease in total between them, and the lease is owned by Worker 1.

If we have a Lease Duration of 60s, and Renwal Interval of 45s, can you share what happens.

1. How does Worker 2 steal the lease from Worker 1. Does Worker 1 just skip renewing the lease, and hope someone else picks it up?

2. Is there a chance that Worker 1 and Worker 2 both think they own the Lease, and are processing the partition at the same time?

It's not clear from the documentation and errors mentioned in logging what's actually happening.

Thank you

**Comment by serkantkaraca** [comment]
1. In such a scenario Worker-2 wouldn't even attempt to steal the lease since that action wouldn't provide an improved load balancing state. Stealing only happens for a host when only it finds out some other host owns 2 or more partitions than her.

2. There might be a small window of time where both hosts think they own the lease, however not so long after one will fail to renew the lease and close the partition pump.

Let me know if you have any other question.

**Comment by Plasma** [comment]
Thanks for that. What if we had 3 workers instead, or whatever configuration is needed to allow for leases to be stolen.

I'm trying to understand why event hubs would have multiple processors processing the same partition, when it feels like you could steal leases but also do so carefully so that each partition is not regularly processed more than once concurrently.

This seems to be an unnecessary complexity overhead for us to handle?

**Comment by larslarsson** [comment]
Hijjack comment

> With 3.0.0 release 

13 days ago 4.0.0 was released & commen is 12 days ago, is this the one you mean? Had the issue on 3.0.0
No release notes for 4.0.0 in https://github.com/Azure/azure-event-hubs-dotnet/releases

**Comment by serkantkaraca** [comment]
3.0.0 already has lease management the improvements. However, better if you stay in the latest release which is 4.0.0.

**Comment by serkantkaraca** [comment]
> Thanks for that. What if we had 3 workers instead, or whatever configuration is needed to allow for leases to be stolen.
> 
> I'm trying to understand why event hubs would have multiple processors processing the same partition, when it feels like you could steal leases but also do so carefully so that each partition is not regularly processed more than once concurrently.
> 
> This seems to be an unnecessary complexity overhead for us to handle?

Once the hosts settle down, you should not see any partition moves thus no duplicate processing. Duplicate processing will always happen when a host joins or leaves. Please remember, Azure Event Hubs provides at-least-once delivery guarantee and hence you should be prepared to process duplicate messages regardless of partition ownership on the receiver side.

**Comment by Plasma** [comment]
Thanks; is it possible to reduce this though using lease management, for the regular case?

For example, if an event hub can instead of processing concurrently will just pause processing until its "safe" for only one processor to be associated with one partition, that would be great.

Side bonus question: With respect to partition counts and throughput units, does it make any sense to ever have more throughput units than partition counts?

I always thought the most throughput units you can use is bounded by the count of the partitions you have, but a colleague noted even with one partition limit, more throughput units seemed to get throughput higher, which was confusing.

Thank you

**Comment by serkantkaraca** [comment]
> For example, if an event hub can instead of processing concurrently will just pause processing until its "safe" for only one processor to be associated with one partition, that would be great.

You can implement processors in a way that it can skip processing rest of the batch when ReceiverDisconnectedException or LeaseLostException is observed. It is really up to developer.

> Side bonus question: With respect to partition counts and throughput units, does it make any sense to ever have more throughput units than partition counts?
> I always thought the most throughput units you can use is bounded by the count of the partitions you have, but a colleague noted even with one partition limit, more throughput units seemed to get throughput higher, which was confusing.

We recommend maximum 1MB sender traffic per partition however this is not a limit we enforce at the broker side. One can easily achieve 10MB per partition as an example. Basically 1MB per partition recommendation comes from scaling design, not from some sort of throughput limit. You should always bump up your TU as you need to process more events, regardless of the partition count.
