### ISSUE TITLE
TryAdd to EventDataBatch has a wrong calculation

### ISSUE THREAD

**Issue by DanYaari** [Azure/azure-sdk-for-net#7165]
When trying to add an EventData to EventDataBatch, there is the following check:
```
if (this.currentSize + eventSizeForBatch > this.maxSize)
        return false;
```
this.maxSize is taken from the link when it is opened.
This calculation checks for the additional headers of the AMQP messages, but it does not take into account the headers of the AMQP message that will encapsulate the entire batch.

Therefore, we might be able to add an EventData almost to the limit of maxSize, and when we try sending the batch, the message is created using
`AmqpMessage amqpMessage = AmqpMessageConverter.EventDatasToAmqpMessage(eventDatas, partitionKey)
`

However, the amqpMessage.SerializedMessageSize is different from the final currentSize of the EventDataBatch due to the headers of the AMQP message. This causes the send to fail even though we succeeded in adding the EventData to the batch.

This happens with version 2.2.1 and 3.0, and I believe there needs to be a buffer given to the maxSize in EventDataBatch to take the AMQP header into account.

Thanks,
Dan Yaari,
Microsoft AATP

**Comment by serkantkaraca** [comment]
SendAsync(batch.ToEnumerable(), partitionKey) with a key different than the one used during batching would be an implementation error. Please reactivate the issue if you have a different repro.

**Comment by Plasma** [comment]
Hi @serkantkaraca we have more information on this bug at https://github.com/Azure/azure-sdk-for-net/issues/11987
