### ISSUE TITLE
PartitionContext.CheckpointAsync throws StorageException on transient errors

### ISSUE THREAD

**Issue by dmytro-gokun** [Azure/azure-sdk-for-net#7170]
I'm using the latest version of the lib (Microsoft.Azure.EventHubs.Processor, 2.2.1) on .NET Core 2.2. Mostly it works just fine, but sometimes calls to CheckpointAsync throw StorageException with message "The server is busy". From what I can gather (https://docs.microsoft.com/en-us/azure/storage/common/storage-performance-checklist): "In some cases, the storage service may throttle your application or may simply be unable to serve the request due to some transient condition and return a "503 Server busy" message or "500 Timeout". This can happen if your application is approaching any of the scalability targets, or if the system is rebalancing your partitioned data to allow for higher throughput. " Our app is not approaching any limits, so it looks like a transient exception which can be safely retried. Now, from what I can see, there is no way to customize RetryPolicy used by the library (and it does not use any internally). So, it looks like the only way to handle this is to have a higher-level retry code, retrying CheckpointAsync on transient exceptions. But would not it be really nice if the lib: 1) used a sensible retry policy by default; 2) provided a way to redefine that if needed ?

**Comment by serkantkaraca** [comment]
Closing the issue since Track 2 SDK is removing storage dependency from Processor Host.

**Comment by dmytro-gokun** [comment]
@serkantkaraca What is "Track 2 SDK"? Where can I read about it? Is it available for download?

**Comment by serkantkaraca** [comment]
https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/eventhub/Azure.Messaging.EventHubs

**Comment by dmytro-gokun** [comment]
Thanks
