### ISSUE TITLE
InitialOffsetProvider Ingored if Host did Checkpoint 

### ISSUE THREAD

**Issue by davidrevoledo** [Azure/azure-sdk-for-net#7171]
A guy in slack was having this issue, I looked in a related issue that if you return Task.FromResult(0) and you don't checkpoint the stream you can start again to re process event, however the host cannot track where and what it has been processed.

It'd be good no matter if the host did checkpoint with some mechanism reset the record `Streaming` to start at some point.

Is that possible currently ? @serkantkaraca 

Thanks.

## Actual Behavior
`InitialOffsetProvider` seems not be used if a client did CheckPoint

## Expected Behavior
Once processed an stream of events and checkpointed, some one want to start again to re process the stream and at that point `InitialOffsetProvider` is ignored.

Related Issue : https://github.com/Azure/azure-event-hubs-dotnet/issues/233

## Versions  
- OS platform and version:
- .NET Version:
- NuGet package version or commit ID:

**Comment by serkantkaraca** [comment]
I am closing the feature request which didn't gain a traction. Besides Track 2 client development is picking up. This can be discussed under Track 2 if needed.
