### ISSUE TITLE
EventHub Emulator

### ISSUE THREAD

**Issue by jonmill** [Azure/azure-sdk-for-net#7172]
## Actual Behavior
1. EventHub has a locally-installable emulator for local testing

## Expected Behavior
1. No emulator exists

## Versions  
- OS platform and version: All
- .NET Version: All
- NuGet package version or commit ID: N/A

It's painful (and requires money) to require a connection to an EventHub in order to develop locally. Please follow in the steps of the Storage team and provide an emulator that can be used locally for development

**Comment by serkantkaraca** [comment]
There is no progress on this yet. I will keep this open to track the request.

**Comment by jonmill** [comment]
@evgenisokolov - we couldn't wait on this any longer and switched over to [Redis Stream](https://redis.io/topics/streams-intro) inside our Kubernetes Cluster instead. It made local development super east

**Comment by jfggdl** [comment]
@jonmill. Thank you for requesting this feature. We acknowledge the need for an emulator and it is actually in our minds to provide such support, but at this time it has not been scheduled. Our apologies.

**Comment by jcvandan** [comment]
@jfggdl I really think this should be a priority for the team, most modern dev teams need to be able to be able to run their application infrastructure on their machines so they can have a fast feedback loop, write local integration tests, and work from anywhere. A lack of an emulator means teams have to start provisioning dev environments for every developer, which is a time consuming headache a lot of teams can't take on!

**Comment by Smurf-IV** [comment]
@jfggdl Why is this closed ? All because it's not scheduled foes not mean it should be closed so that it "Disappears" from you open items view !
Especially when there is a comment like:
`There is no progress on this yet. I will keep this open to track the request.`

**Comment by AmirSasson** [comment]
What about Kafka as a local alternative?  @jonmill 
as far as i know, Azure EventHub Sdk works seamlessly with Apache Kafka

**Comment by leonids2005** [comment]
Just curiosity - why this ticket is closed?

**Comment by galvesribeiro** [comment]
@AmirSasson just FYI, it is not that EventHub SDK works with Kafka, it is the other way around. EventHub Service works if you use Kafka SDK. So no, it is not an alternative for testing in CI/CD pipelines...

**Comment by akshitgupta29** [comment]
4.5 years later, this functionality is still missing, and most of the developers are waiting for this. 

Is there any workaround, if anyone please can suggest?
