### ISSUE TITLE
EventHubsDiagnosticSource does not follow corefx DiagnosticSource recommendations

### ISSUE THREAD

**Issue by gambrose** [Azure/azure-sdk-for-net#7173]
`EventHubsDiagnosticSource` exposes events named like `Microsoft.Azure.EventHubs.Receive.Stop` which goes against [recommendations](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/DiagnosticSourceUsersGuide.md#event-names) to not include the Listener name in the event name.

**Comment by serkantkaraca** [comment]
PR - https://github.com/Azure/azure-sdk-for-net/pull/7186

**Comment by jfggdl** [comment]
The PR has been merged. We are expecting its imminent release in September.
