### ISSUE TITLE
Determine EventData message size

### ISSUE THREAD

**Issue by samneirinck** [Azure/azure-sdk-for-net#7174]
## Actual Behavior
Unable to determine the message size of a serialized `EventData` instance. I noticed this missing property while looking at [the following StackOverflow question](https://stackoverflow.com/questions/27263189/how-can-the-serialized-size-of-eventdata-be-determined-for-batching). There was a change related to batch sizes on Azure/azure-event-hubs-dotnet#79, but this issue is about a single `EventData` instance. 

## Expected Behavior
The old SDK has the property `SerializedSizeInBytes` ([MSDN](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.eventdata.serializedsizeinbytes?view=azure-dotnet#Microsoft_ServiceBus_Messaging_EventData_SerializedSizeInBytes)). Would like to have the same property available here.

## Versions  
- OS platform and version: Windows
- .NET Version: 4.7
- NuGet package version or commit ID: 1.1.0

If you're open for contributions I'd love to take a look.

**Comment by serkantkaraca** [comment]
Please reconsider creating a feature request for Track 2 SDK - https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/eventhub/Azure.Messaging.EventHubs
