### ISSUE TITLE
Any plans for supporting IoT Hub connection strings?

### ISSUE THREAD

**Issue by dominicbetts** [Azure/azure-sdk-for-net#7175]
Are you planning to add support for IoT Hub connection strings in the way that is supported in Microsft.ServiceBus.Messaging library?

It's much more convenient to use the IoT Hub connection string directly rather than assembling a Event Hub connection string from IoT Hub's Event Hub-compatible settings.

**Comment by serkantkaraca** [comment]
We are moving ITOHub support to Track 2 SDK therefore closing the feature request here.

**Comment by felipepessoto** [comment]
Hi @serkantkaraca where did the issue was moved for? I couldn't find it.
Thanks

**Comment by serkantkaraca** [comment]
Azure.Messaging.EventHubs addressed the ask with a sample. Please open new issues if you have any issues or questions regarding the sample. You can find sample here - https://github.com/Azure/azure-sdk-for-net/tree/master/samples/iothub-connect-to-eventhubs
