### ISSUE TITLE
[Track One Event Hubs Tests] Randomize partition picked

### ISSUE THREAD

**Issue by tzhanl** [Azure/azure-sdk-for-net#7178]
sdk/eventhub/Microsoft.Azure.EventHubs/tests/Client/DataBatchTests.cs.
thinking of Randomize partition picked in Test SendingPartitionKeyBatchOnPartitionSenderShouldFail.
 replace "0" with random Partition key for follow code:
var partitionSender = ehClient.CreatePartitionSender("0");

**Comment by soo-toance** [comment]
hello does it look good? 
i found that in ReceiverTests - CreateReceiverWithEndOfStream use like this : ) ([source code](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Microsoft.Azure.EventHubs/tests/Client/ReceiverTests.cs#L62))

before : 
```
var ehClient = EventHubClient.CreateFromConnectionString(connectionString);
var partitionSender = ehClient.CreatePartitionSender("0");
```

after: 
```
var partitions = await this.GetPartitionsAsync(ehClient);
var partitionId = partitions[new Random().Next(partitions.Length)];
var partitionSender = ehClient.CreatePartitionSender(partitionId);
```
