### ISSUE TITLE
Event Processor Tests

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#7182]
# Summary

Due to time constraints and the desire to release a preview of `EventProcessor` to gather feedback, the associated test suite for both unit and live tests were not a priority for the second preview.  In order to ensure that we maintain a high quality bar and are able to validate enhancements, bug fixes, and changes to the implementation, a comprehensive suite of tests is needed.

# Scope of Work

- Analyze `EventProcessor` and determine the surface area of tests needed to fully validate the implementation and API surface.

- Prioritize the test needs such that the API surface and areas with greater risk or impact are given more importance.

- Implement those tests which the time box for this issue allows; working from highest priority to lowest.

- Open issues to capture any test needs that remain, including their relative importance and any other necessary context.

# Out of Scope

- Tests for areas outside of the scope of the `EventProcessor` and associated types.

- Enhancements, fixes, or changes to the `EventProcessor` and associated types; the scope of this work is limited to test implementations.

# Success Criteria

- The highest priority tests for the `EventPocessor` feature area have been implemented and pass consistently with reliable and deterministic results.

- Any outstanding test needs have been captured in a dedicated issue for tracking and to be addressed at a later time.

**Comment by kinelski** [comment]
The main goal of this issue has been achieved in #7366. A few tests still need to be done, and some changes must be performed in the existing ones, but the remaining work has been separated in multiple issues:  #7375, #7463 and #7464, so this one is being closed.
