### ISSUE TITLE
[BUG] the NuGet project URL for Azure.Security.KeyVault.Secrets points to an invalid URL

### ISSUE THREAD

**Issue by KSchlobohm** [Azure/azure-sdk-for-net#7184]
**Describe the bug**
The project url on https://www.nuget.org/packages/Azure.Security.KeyVault.Secrets/ points to [Page not found](https://github.com/Azure/azure-sdk-for-net/blob/6756d9a222b93698c410b2efa0f915709a1a14b6/sdk/keyvault/Azure.Security.KeyVault.Secrets/README.md).

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
Follow the link from the NuGet Gallery site or use the project link from the Visual Studio IDE for package management.

***Code Snippet***
N/A

**Expected behavior**
The link should point to https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Secrets/Readme.md

**Screenshots**
N/A

**Setup (please complete the following information):**
 - N/A

**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by KSchlobohm** [comment]
Looks like the link to the KeyVault Readme is [changing](https://github.com/Azure/azure-sdk-for-net/pull/7205) with regard to the link for Steps to Reproduce.

**Comment by KSchlobohm** [comment]
Looks like the link to the KeyVault Readme is [changing](https://github.com/Azure/azure-sdk-for-net/pull/7205) with regard to the expected behavior.

**Comment by AlexGhiondea** [comment]
@KSchlobohm thanks for pointing it out! I believe that is fixed now. Please let me know if that is not the case.
