### ISSUE TITLE
[BUG] Azure.Security.KeyVault.Secrets preview2 - GetSecrets() should return type Secret instead of SecretBase

### ISSUE THREAD

**Issue by KSchlobohm** [Azure/azure-sdk-for-net#7193]
**Describe the bug**
In the documentation to enumerate secrets the list of returned secrets is of type Secret. The actual type returned in preview2 of Azure.Security.KeyVault.Secrets is SecretBase which does not include the property "Value".

***Exception or Stack Trace***
- System.InvalidCastException: 'Unable to cast object of type 'Azure.Security.KeyVault.Secrets.SecretBase' to type 'Azure.Security.KeyVault.Secrets.Secret'.'

**To Reproduce**
1. [List secrets](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Secrets/Readme.md#list-secrets)

***Code Snippet***
```cs
IEnumerable<Response<SecretBase>> allSecrets = client.GetSecrets();

  foreach (Secret secret in allSecrets)
  {
    Console.WriteLine(secret.Name);
  }
```

**Expected behavior**
Expected the "client.GetSecrets()" in the above code to return a type of IEnumerable<Response<Secret>> so that the details of the secrets can be used without having to make n-many calls the API to get these values.

**Setup (please complete the following information):**
 - OS: [Windows 10]
 - IDE : [Visual Studio]
 - Version of the Library used: Azure.Security.KeyVault.Secrets -Version 4.0.0-preview.2

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by KSchlobohm** [comment]
Looks like the link to the KeyVault Readme is [changing](https://github.com/Azure/azure-sdk-for-net/pull/7205) with regard to the link for Steps to Reproduce.

**Comment by AlexGhiondea** [comment]
@KSchlobohm thanks for pointing this out! We'll take a look at this!
