### ISSUE TITLE
[BUG] Azure.Security.KeyVault.Secrets preview2 uses 1970 to populate the Created and Updated properties

### ISSUE THREAD

**Issue by KSchlobohm** [Azure/azure-sdk-for-net#7197]
**Describe the bug**
When creating a new Secret the new value is stored as 1/19/1970 rather than current DateTime and the properties for Created and Updated on the Secret object are read-only.

***Exception or Stack Trace***
N\A

**To Reproduce**
1. [Create a Secret](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Secrets/Readme.md#create-a-secret)

***Code Snippet***
```cs
            SecretClient client = new SecretClient(
                vaultUri: new Uri("https://ux-bash-keyvault.vault.azure.net/"),
                credential: new DefaultAzureCredential());

            Secret newSecret = new Secret("newSecret", "createdToday");
            Secret newSecretResponse = client.Set(newSecret);
            Console.WriteLine("newSecret Created: " + newSecretResponse.Created);
            Console.WriteLine("newSecret Updated: " + newSecretResponse.Updated);
```

**Expected behavior**
- Expected to be able to set these values or have the values set during the life-cycle of saving the data when they're set to read-only.

**Screenshots**
![Created and Updated dates not set](https://user-images.githubusercontent.com/23503973/62653668-a84b1e80-b923-11e9-979c-445cdbb74cdc.png)

**Setup (please complete the following information):**
 - OS: [Windows 10]
 - IDE : [Visual Studio 2019]
 - Version of the Library used - Azure.Security.KeyVault.Secrets -Version 4.0.0-preview.2

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by KSchlobohm** [comment]
Looks like the link to the KeyVault Readme is [changing](https://github.com/Azure/azure-sdk-for-net/pull/7205) with regard to the link for Steps to Reproduce.

**Comment by AlexGhiondea** [comment]
@KSchlobohm thanks for pointing this out! We'll take a look at this!
