### ISSUE TITLE
[BUG] the SecurityClient.PurgeDeleted method is not behaving Synchronously

### ISSUE THREAD

**Issue by KSchlobohm** [Azure/azure-sdk-for-net#7199]
**Describe the bug**

***Exception or Stack Trace***
Azure.RequestFailedException: 'Service request failed.
Status: 409 (Conflict)

Content:
{"error":{"code":"Conflict","message":"Secret is currently being deleted.","innererror":{"code":"ObjectIsBeingDeleted"}}}

Headers:
Cache-Control: no-cache
Pragma: no-cache
Server: Microsoft-IIS/10.0
x-ms-keyvault-region: eastus2
x-ms-request-id: 029e790c-d967-41a7-a1f8-cb9a8875668b
x-ms-keyvault-service-version: 1.1.0.875
x-ms-keyvault-network-info: addr=68.203.133.33;act_addr_fam=InterNetwork;
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Strict-Transport-Security: max-age=31536000;includeSubDomains
X-Content-Type-Options: nosniff
Date: Wed, 07 Aug 2019 21:12:05 GMT
Content-Length: 121
Content-Type: application/json; charset=utf-8
Expires: -1

**To Reproduce**
Follow the docs to setup a KeyVault and credentials for testing - https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Secrets/Readme.md
Follow the docs to enable soft-delete mode using cli - https://docs.microsoft.com/en-us/azure/key-vault/key-vault-soft-delete-cli
Run the following code to purge a deleted key
The last line in the code snippet fails because the PurgeDeleted method is still pending.

***Code Snippet***
```cs
            // Create a new secret client using the default credential from Azure.Identity
            SecretClient client = new SecretClient(
                vaultUri: new Uri("https://ux-bash-keyvault.vault.azure.net/"),
                credential: new DefaultAzureCredential());


            Secret value = client.Set("my-soft-delete-test", "keyValue");
            client.Delete("my-soft-delete-test");
            client.PurgeDeleted("my-soft-delete-test");
            client.Set("my-soft-delete-test", "keyValue"); //operation fails because PurgeDeleted is not synchronous
```

**Expected behavior**
Expecting to be able to reuse a key name when PurgeDeleted is complete.

**Setup (please complete the following information):**
 - OS: [Windows 10]
 - IDE : [Visual Studio 2019]
 - Version of the Library used - Azure.Security.KeyVault.Secrets -Version 4.0.0-preview.2

**Additional context**
An async method for PurgeDeleted also exists. This behavior was observed on PurgeDeleted which is expected to perform synchronously.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by KSchlobohm** [comment]
Looks like the link to the KeyVault Readme is [changing](https://github.com/Azure/azure-sdk-for-net/pull/7205).

**Comment by AlexGhiondea** [comment]
@KSchlobohm thanks for pointing this out! We'll take a look at this!

**Comment by heaths** [comment]
Thank you for the feedback! Unfortunately, deleting keys or secrets in a soft delete-enabled vault is not immediate, and purging requires subsequently trying to get the delete object repeatedly until it no longer exists. Generally, we try to avoid multiple operations in the client library to avoid performance issues by default in client applications. While we decide how to address this issue, you can use a retry loop like we do in our [test infrastructure](https://github.com/Azure/azure-sdk-for-net/blob/f5d3bc84f0c104bcd196db8613766bd6f051e9e9/sdk/keyvault/Azure.Security.KeyVault.Secrets/tests/KeyVaultTestBase.cs#L108-L119).

**Comment by heaths** [comment]
Unfortunately, the service does not provide a way to efficiently pull using, for example, a long-running operation like with [Create Certificate](https://docs.microsoft.com/en-us/rest/api/keyvault/createcertificate/createcertificate). We will document that users can poll in a loop similar to how we do in tests if needed.

**Comment by KSchlobohm** [comment]
Can we change the name of the method to be async and alter the method so that it returns control flow to the application when the operation is completed?

**Comment by schaabs** [comment]
As of the release 1.0.0 we have updated this method to return a DeletedSecretOperation which is an LRO poller you can use to determine when the delete operation is complete.

**Comment by heaths** [comment]
The method itself is async, but the server returns right away before a secret it purged. There's nothing the client can poll on. The only way to know that we can create a new secret is to actually try to create a secret, but in most practical cases if a customer was purging a secret they wouldn't want it created again. At least, we can't do that on behalf of customers for that reason.

Instead, if you have a practical scenario in which you're trying to create a key after purging, you'd have to do so in a loop as explained above until it works. However, you can always create a new secret with the same name and a new version is created. This works for secrets, keys, and certificates.
