### ISSUE TITLE
[BUG] Latest Storage SDK does not work with Azure Storage Emulator 5.9

### ISSUE THREAD

**Issue by Plasma** [Azure/azure-sdk-for-net#7208]
**Describe the bug**
Recently installed `Microsoft.Azure.Storage.Blob` NuGet `11.0.0` https://www.nuget.org/packages/Microsoft.Azure.Storage.Blob/

The Storage Emulator locally version 5.9 (latest, have even re-installed).

```
C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator>AzureStorageEmulator.exe status
Windows Azure Storage Emulator 5.9.0.0 command line tool
IsRunning: True
BlobEndpoint: http://127.0.0.1:10000/
QueueEndpoint: http://127.0.0.1:10001/
TableEndpoint: http://127.0.0.1:10002/
```

***Exception or Stack Trace***
```
Microsoft.Azure.Storage.StorageException: Storage Exception (Request Id: 117143b0-1cef-400f-8e9c-2c9470c989e6): {"ErrorCode":"VersionNotSupportedByEmulator","ErrorMessage":"The REST version of this request is not supported by this release of the Storage Emulator. Please upgrade the storage emulator to the latest version. Refer to the following URL for more information: http://go.microsoft.com/fwlink/?LinkId=392237\nRequestId:117143b0-1cef-400f-8e9c-2c9470c989e6\nTime:2019-08-08T06:52:00.3785996Z","AdditionalDetails":{"VersionAttempted":"2019-02-02"}} ---> Microsoft.Azure.Storage.StorageException: The REST version of this request is not supported by this release of the Storage Emulator. Please upgrade the storage emulator to the latest version. Refer to the following URL for more information: http://go.microsoft.com/fwlink/?LinkId=392237
```

**To Reproduce**
Try using Storage Emulator with latest SDK.

**Comment by longzheng** [comment]
Looks like the latest version of the SDK is now targeting `2019-02-02` which is not supported by either the Azure Storage Emulator or Azurite

https://github.com/Azure/azure-storage-net/blame/bbb7da62bc49ee79e07cf607d2202c9778b83d56/Lib/Common/Shared/Protocol/Constants.cs#L1493

**Comment by amishra-dev** [comment]
Hi @Plasma @longzheng 
10.0.* was the last supported version of the SDK for Azure Storage emulator. We will not be extending Azure Storage Emulator to support SDK version 11. I will update the readme to reflect this status.

I will follow up with the Azurite team and post the response here for the support of 02-02-2019 REST API.

**Comment by BrianVallelunga** [comment]
@amishra-dev, Is the storage emulator being discontinued? If so, that's a pity as it's a very useful tool. Personally, I'd like to see some of the core services (blob, Cosmos, Service Bus) integrated into a single Docker image that I could download. It would really ease development work.

**Comment by amishra-dev** [comment]
@BrianVallelunga that is correct. Development of Storage Emulator is being discontinued, Azurite is the way foward for us. 
Filed the feature request in Azurite. https://github.com/Azure/Azurite/issues/249

**Comment by riverar** [comment]
@amishra-dev I'm confused, isn't Storage Emulator part of Visual Studio lifecycle? You can't just kill it with no notice right?

**Comment by nlysaght** [comment]
Azurite just supports blob storage only, so we still need the Storage Emulator for Table and Queue storage. So is it only the Blob portion of Azure Storage Emulator that is being retired or the whole emulator? Is there an official announcement that you folks in MS are going to be making around this issue, because this is going to causing a lot of trouble for a lot of people.

**Comment by amishra-dev** [comment]
Its not killed, we will continue to support Azure Storage Emulator. We believe Azurite is a better solution for our customer for future releases of the service and we will add support for future versions only in Azurite.

**Comment by Plasma** [comment]
Hey @amishra-dev ; to be clear, .NET Storage SDK 11+ will not be supported by Azure Storage Emulator now or in the future?

We've been using the emulator since it was released, so just want to know if we now delete it from our stack and replace it with something else.

Thanks

**Comment by XiaoningLiu** [comment]
Hi,

Azurite will update and catch up latest storage features and API versions covering blob & queue. Now, we are working on Azurite Queue implementation, and planning to have a release for queue within several weeks. After that, we will start working on blob feature parity catch up. During meantime, contribution are welcome.

For Table Storage would recommend using the emualtor from Cosmos team.
https://docs.microsoft.com/en-us/azure/cosmos-db/local-emulator

**Comment by pemari-msft** [comment]
Hi all, thanks for your feedback. We are still supporting the older, Windows-only Storage Emulator, but new features won't be able to be added to it. We'll release a new version in the coming days that will fix the latest api-versions to ensure you are unblocked ASAP and we apologize for the confusion. 

The Azurite emulator is an open-source, cross-platform emulator that we've chosen to invest in in response to customer feedback. Azurite will support Blobs and Queues, and the CosmosDB emulator is the way forward for Table emulation. Azurite is our officially recommended solution, and as such, all new Storage Service releases will also have a corresponding Azurite release on day 1. 

Please let me know if you have any questions regarding the above -- we are working on some official documentation that outlines the above and we'll be posting it shortly.

**Comment by longzheng** [comment]
@pemari-msft thanks and when you do release the emulator update, it would be very helpful if you could please update the release notes as well (which are quite out of date) to document the API version for future reference.

https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator

**Comment by macux** [comment]
So basically the solution for now is to downgrade the SDK to 10.0.3, I've confirmed this works for queues on 5.9 of the emulator. Is there a specific version or issue(s) we should watch to know when Azurite is ready to support all services for the v11 SDK? I don't want to upgrade until I can test in dev and CI end to end, thanks.

**Comment by clawrenceks** [comment]
@pemari-msft I see you have suggested here that the CosmosDB emulator is the way forward for Table Emulation. This is worrying. The Table Emulation support in the Cosmos DB Emulator is not even close to the capability offered by the Azure Storage Emulator coupled with the Storage Explorer.

Added to this, the Docker support for the Cosmos DB Emulator is woefully inadequate and the GitHub repo for it has issues that are over two years old. This doesn't sound like something that we should be looking to as a way forward at present.

**Comment by kfarmer-msft** [comment]
I'm updating the fwlinks for the storage emulator to point to the v5.10 release today.

**Comment by kfarmer-msft** [comment]
> https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator

Updated notes for 5.8, .9, and .10 have been merged with the docs and should appear in the next day or so.

**Comment by BadgerCode** [comment]
I currently use storage emulator when running Azure functions locally, or when running the tests in Azure Devops.

Are there any guides for running Azurite in a Devops build pipeline?
When can we expect the fix for storage emulator to be available on Devops?

**Comment by HarlowBurgess** [comment]
> Hi,
> Azurite will update and catch up latest storage features and API versions covering blob & queue. Now, we are working on Azurite Queue implementation, and planning to have a release for queue within several weeks. After that, we will start working on blob feature parity catch up. In the meantime, Azurite is an open source project, contribution are welcome.
> For Table Storage would recommend using the emualtor from Cosmos team. They are also working on cross platform support.
> https://docs.microsoft.com/en-us/azure/cosmos-db/local-emulator

I don't know, call me crazy, but maybe next time don't drop support for the current, working solution until you have actually finished implementing its replacement. Just a thought.
