### ISSUE TITLE
[FEATURE REQ] BlobContainerClient.CreateIfNotExistsAsync

### ISSUE THREAD

**Issue by mjrousos** [Azure/azure-sdk-for-net#7211]
**Is your feature request related to a problem? Please describe.**
Moving from the Microsoft.Azure.Storage.Blob NuGet package to Azure.Storage.Blobs package, a number of 'convenience' methods are missing that degrade the developer experience. One example of this that shows up early in the development process is the lack of a `CreateIfNotExistsAsync` API on `BlobContainerClient`.

I understand that the new SDK is meant to closely reflect the RESTful API, but without helper methods like this, developers need to write more code than they did with the old API and the end result is a loss in productivity.

Getting a container client pointed at a container which may already exist with the old SDK was this easy:

```CSharp
var container = blobClient.GetContainerReference("my-container");
await container.CreateIfNotExistsAsync();
```

With the new SDK, those same two lines are replaced with:

```CSharp
var containerClient = new BlobContainerClient(ConnectionString, "my-container");
try
{
    await containerClient.CreateAsync();
}
catch (StorageRequestFailedException exc)
{
    if (exc.Status != 409)
    {
        throw;
    }
}
```

The newer SDK more closely matches the RESTful API, but is a poorer developer experience.

**Describe the solution you'd like**
Helper methods (like `CreateIfNotExistsAsync`) similar to those available in Microsoft.Azure.Storage.Blob to increase productivity.

**Describe alternatives you've considered**
As mentioned above, this can be easily worked around, but makes the SDK feel less complete than the old one.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by tg-msft** [comment]
Putting this up for grabs, @amnguye and @JoshLove-msft.

**Comment by tg-msft** [comment]
Also - can we we try to do this with an [IfNoneMatch](https://docs.microsoft.com/en-us/rest/api/storageservices/specifying-conditional-headers-for-blob-service-operations) access condition?  One of the complaints I've heard about previous iterations of this API is it added a lot of unpleasant 400 error messages to customer logs.

**Comment by amnguye** [comment]
Opened two separate issues to implement this feature for Files(#7878) and Queues(#7879)
