### ISSUE TITLE
DbContext.Database.Migrate() fails when using access token?

### ISSUE THREAD

**Issue by jbelaire** [Azure/azure-sdk-for-net#7212]
**Query/Question**
I’m building an identity service using Identity Server 4 EF scaffolding.  The database server is an empty Azure SQL PaaS resource with only the master database.  I'm trying to use Managed Identity to authenticate my application to the Azure SQL PaaS resource.

I granted my Azure login the “Active Directory admin” role for the Azure SQL PaaS resource in the Azure portal, and I’m running this service locally using VS2019, which is also logged in with my Azure login.

When my service starts up and attempts to run the IS4 EF migration, I’m getting a System.Data.SqlClient.SqlException: 'Login failed for user 'NT AUTHORITY\ANONYMOUS LOGON'.' exception.

If I create an empty database in the Azure SQL PaaS resource, the migration runs successfully.  The migration appears to have an issue creating the database when using an access token.  I confirmed the access token is set on the database connection prior to calling .Migrate().

Should the migration be able to create a database object using managed identity?

Here are the relevant snippets of code:

Program.cs
```cs
public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
    WebHost.CreateDefaultBuilder(args)
        .UseStartup<Startup>()
        .ConfigureAppConfiguration((ctx, builder) =>
        {
            var config = builder.Build();
            var tokenProvider = new AzureServiceTokenProvider();
            var keyVaultClient = new KeyVaultClient((authority, resource, scope) => tokenProvider.KeyVaultTokenCallback(authority, resource, scope));
            builder.AddAzureKeyVault(config["KeyVault:BaseUrl"], keyVaultClient, new DefaultKeyVaultSecretManager());
        })
        .UseApplicationInsights()
        .UseSerilog((context, configuration) =>
        {
            configuration.ReadFrom.Configuration(context.Configuration);
        });
```
Startup.cs
```cs
public void Configure(IApplicationBuilder app)
{
    ...
    app.UseIdentityServer();
    app.InitializeDatabase();
}

public void ConfigureServices(IServiceCollection services)
{
    ...
    IIdentityServerBuilder identityServerBuilder = services
        .AddIdentityServer(...)
        .AddConfigurationStore(options =>
        {
            options.ConfigureDbContext = builder =>
            {
                var connection = new SqlConnection(identityConnectionString)
                {
                    AccessToken = new AzureServiceTokenProvider().GetAccessTokenAsync("https://database.windows.net/").Result
                };

                builder.UseSqlServer(connection, sql =>
                {
                    sql.MigrationsAssembly(migrationsAssembly);
                    sql.EnableRetryOnFailure(maxRetryCount: 15, maxRetryDelay: TimeSpan.FromSeconds(30), errorNumbersToAdd: null);
                });
            };
        });
    ...
}
```
IApplicationBuilderExtensions.cs
```cs
public static class IApplicationBuilderExtensions
{
    public static IApplicationBuilder InitializeDatabase(this IApplicationBuilder app)
    {
        using (var scope = app.ApplicationServices.GetService<IServiceScopeFactory>().CreateScope())
        {
            // Exception occurs here if the database does not already exist...
            // I confirmed the AccessToken is set on the Database connection.
            scope.ServiceProvider.GetRequiredService<PersistedGrantDbContext>().Database.Migrate();
            scope.ServiceProvider.GetRequiredService<ConfigurationDbContext>().Database.Migrate();
        }
        return app;
    }
}
```
web.config
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <section name="SqlAuthenticationProviders" type="System.Data.SqlClient.SqlAuthenticationProviderConfigurationSection, System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
  </configSections>
  <SqlAuthenticationProviders>
    <providers>
      <add name="Active Directory Interactive" type="Microsoft.Azure.Services.AppAuthentication.SqlAppAuthenticationProvider, Microsoft.Azure.Services.AppAuthentication" />
    </providers>
  </SqlAuthenticationProviders>
</configuration>
```
***Why is this not a Bug or a feature Request?***
At this point I'm not sure if this is a bug, feature request, or configuration issue on my part.

**Setup (please complete the following information if applicable):**
 - OS: Windows 10 (1903)
 - IDE : Visual Studio 2019 Professional 16.3 Preview 1
 - Microsoft.Azure.Services.AppAuthentication 1.3.0

**Comment by loarabia** [comment]
Hi @jbelaire , I've labeled this issue so that the right teams should be able to find it.

**Comment by amolagar5** [comment]
First step will be to check what is the token you are getting, if its valid. 
you can print your token in the program and check here for more details. https://jwt.ms/
If you can share the server\db names, I can also lookup on what login errors you are getting. 
Here is our troubleshooting guide. 
https://techcommunity.microsoft.com/t5/Azure-SQL-Database/Troubleshooting-problems-related-to-Azure-AD-authentication-with/ba-p/1062991

**Comment by jeroenterheerdt** [comment]
@jbelaire please respond by 1/31 if you have any more questions, otherwise we will proceed to close this issue.
