### ISSUE TITLE
Test the developer experience when invalid service parameters are passed in.

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#7223]
Per Guideline:

 DO test the developer experience when invalid service parameters are passed in. Ensure clear error messages are generated by the client. If the developer experience is inadequate, work with the service team to correct the problem.

**Comment by jsquire** [comment]
@nisha-bhatia :  While you're working in AppConfig, would you be so kind as to confirm this?


//cc @ShivangiReja

**Comment by jsquire** [comment]
Closing this out, as changes to the experience now would be breaking.

**Comment by annelo-msft** [comment]
I'm not arguing that this shouldn't be closed, but changes to error message text are non-breaking.  We can address this case-by-case based on customer feedback if needed.

**Comment by jsquire** [comment]
> changes to error message text are non-breaking. 

Even if our guidelines do not categorize as breaking changes, they do run the risk of breaking customer application logic.  Whether we officially discourage doing so or not, there are real-world applications sniffing and applying logic based on error message text to disambiguate error scenarios.  

I don't know how likely it is that those would apply to the "bad parameters scenario", but I would be opposed to making changes here without strong evidence of a usability issue.
