### ISSUE TITLE
Complete Documentation

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#7225]
- [ ] Quickstart - Article on docs.microsoft.com that is similar to but expands on the README content
- [ ] Conceptual - Long-form documentation like Quickstarts, Tutorials, How-to guides, and other content on docs.microsoft.com

**Comment by annelo-msft** [comment]
@kaerm 

Closing as this belongs to PM team.

**Comment by annelo-msft** [comment]
Reassigning per conversation with @kaerm

**Comment by AlexGhiondea** [comment]
Closing this. If this is still required, let's file a new issue.
