### ISSUE TITLE
[BUG] Azure App Configuration client library for .NET Doc error

### ISSUE THREAD

**Issue by x9xu** [Azure/azure-sdk-for-net#7233]
In Azure App Configuration client library for .NET document, example about how to delete a key value is described as following, 
"
string connectionString = <connection_string>;
var client = new ConfigurationClient(connectionString);
var setting = new ConfigurationSetting("some_key", "some_value");
client.Set(setting);
ConfigurationSetting setting = client.Delete("some_key");
"

(https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/appconfiguration/Azure.ApplicationModel.Configuration#delete-a-configuration-setting)

But in code, the client delete action will return a Azure Response instead of ConfigurationSetting.
(https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/appconfiguration/Azure.ApplicationModel.Configuration/src/ConfigurationClient.cs#L455)

**Comment by annelo-msft** [comment]
Fixed.
