### ISSUE TITLE
Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.14.2.11

### ISSUE THREAD

**Issue by Muthukumar230195** [Azure/azure-sdk-for-net#7239]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified

**Comment by loarabia** [comment]
Hi @Muthukumar230195  I've labeled this bug so that the right team should be able to find it. I was curious if you could offer any more details about what you ran into? Were you using a tool and this popped out as an error, was this a case where you pulled in the AAD nuget directly and saw this, or did this perhaps come from pulling in another nuget for a different service but this appeared?

Thanks for any additional details.

**Comment by Muthukumar230195** [comment]
hi @loarabia 
this error occurs while fetching the password from key-vault in azure. moreover, we don't use the ActiveDirectory version 3.14.2 dll in our azure function but wondering from where this version takes it up. Exception message shows the source of the error is Microsoft.Azure.Services.AppAuthentication but there also we using ver:3.19.8 ActiveDirectory.
(note:Microsoft.Azure.Services.AppAuthentication depentent on Microsoft.identitymodle.Clients.ActiveDirectory Dll) 

thank you.

**Comment by DerAlbertCom** [comment]
This is still a problem, is it not possible to use a ServicePrincipal with a Certificate in ASP.NET Core 3.1. Only Managed Identity (which is not Available in AzureGermany) and ClientSecret is possible.

**Comment by MarkLFT** [comment]
I have this exact same problem.  Does anyone have a workaround for this issue?  It has now been over a year since this was first reported.

**Comment by AlexGhiondea** [comment]
@DerAlbertCom, @MarkLFT could you please file a new issue if you still need help?

**Comment by DerAlbertCom** [comment]
After two Years ignoring the Bug on your Side the world moved on, AzureGermany is killed, we moved to Global, and .NET Core 3.1 is nearing End of Life. Maybe we need a ServicePrincipal with a Certificate in the  future then I will see if the problem still exists. In the meantime I will put the same effort in reproducing the bug as you working on this issue.
