### ISSUE TITLE
Investigate pooling of HashAlgorithm instances in KeyVault CryptographyClients.

### ISSUE THREAD

**Issue by schaabs** [Azure/azure-sdk-for-net#7240]
Internally the CryptographyClient creates HashAlgorithm instances to compute hashes.  We should investigate if these could be reused to reduce allocations.

**Comment by heaths** [comment]
According to https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.hashalgorithm.canreusetransform?view=netstandard-2.0#property-value this property always returns `true`, though it is virtual. No algorithm we support based on their Windows implementation currently overrides that; however, this is not thread-safe. As such, we should create new instances with each use.
