### ISSUE TITLE
[QUERY] Are there breaking changes in v4.0.0?

### ISSUE THREAD

**Issue by Zenuka** [Azure/azure-sdk-for-net#7241]
Is there maybe a readme or release notes to see if there are breaking changes in Microsoft.Azure.ServiceBus v4.0.0? And of course what they are?

**Comment by jfggdl** [comment]
@zenuka, Thank you for letting us know about this issue. Here you could find the release notes:

https://github.com/Azure/azure-sdk-for-net/releases/tag/Microsoft.Azure.ServiceBus_4.0.0


I will close this item for now, but please let me know if you have additional questions and we can reopen this issue for you.
