### ISSUE TITLE
Event Hub Client should allow the Event Hubs namespace name (alone) as the host

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#7242]
# Summary

The `EventHubClient` has a constructor which takes a `host` in the form of a string.  Presently, this value is expected to follow the format historically used to represent the endpoint concept  `{your-namespace-name}.servicebus.windows.net` or  `{protocol}://{your-namespace-name}.servicebus.windows.net`.  

The first value is not displayed anywhere within the portal that developers can reference and the second appears only as the `Endpoint` token within the connection string, making understanding the expected parameter a burden.   Further, this value is never used in the form that it was passed in; it is transformed and combined with other metadata, such as the Event Hub name and artifacts of the selected transport to create the actual URI for communicating with the service.  

In order to make the developer experience better, the `EventHubClient` constructor should accept just the Event Hub namespace for the `host` parameter, in addition to the two patterns previously described.  The chosen transport layer should understand the form needed to communicate with the server and responsibility for validating and assisting to form the full host can be delegated to it.

This would provide a friendlier and more robust developer experience, while removing the need for developers to hunt through the connection string or read a "magic suffix" value from documentation.  It would also allow easier support for additional transports to use with the service.

# Scope of Work

- Add the ability for the transport client to inspect an Event Hub client `host` parameter, validate it and, if needed, transform an Event Hubs namespace name into a valid `host` for the transport.

- Update the `EventHubClient` to delegate `host` validation to the active transport client.   This is likely to require some refactoring in the order of operations in order to ensure that support for the requested transport has been created prior to considering the `host`.

- Update documentation to remove language that calls out the need to apply the specific suffix to the Event Hubs namespace value.

- Update samples and "Getting Started" examples to use the simpler form of the host.

- Implement any additional tests that are needed to cover the enhancements.

# Out of Scope

- Removal of the current set of `host` patterns; these should remain valid.

# Success Criteria

- The `EventHubClient` constructors that accept a `host` parameter are able to handle the  patterns of:  `{your-namespace-name}.servicebus.windows.net`, `{protocol}://{your-namespace-name}.servicebus.windows.net`, and `{your-namespace-name}`.

- The transport client holds delegated responsibility for validating and helping to form the valid `host` from the parameters provided to the `EventHubClient`.

- Documentation and samples have been updated to reflect the change and to illustrate usage with the simplest form, specifically using the raw Event Hubs namespace as `host`.

**Comment by ramya-rao-a** [comment]
> The first value is not displayed anywhere within the portal that developers can reference and the second appears only as the Endpoint token within the connection string, making understanding the expected parameter a burden. 

We have communicated this to the service team and they will be working with their UI team to find a good place for the fully qualified domain name in the portal

> Further, this value is never used in the form that it was passed in; it is transformed and combined with other metadata, such as the Event Hub name and artifacts of the selected transport to create the actual URI for communicating with the service.

This is not entirely true. The AMQP connection requires to know the entire full `your-namespace-name.servicebus.windows.net` and not just the name of the namespace we want to connect to. The AMQP connection itself doesn't need to know the event hub name.

 Its the individual AMQP links (sender, receiver) that use the Event Hub name in conjunction with the `your-namespace-name.servicebus.windows.net`.


> The EventHubClient constructors that accept a host parameter are able to handle the patterns of: {your-namespace-name}.servicebus.windows.net, {protocol}://{your-namespace-name}.servicebus.windows.net, and {your-namespace-name}

Another point to note is that the suffix `servicebus.windows.net` is not the same for all clouds.
For example, the China cloud would have the suffix `servicebus.chinacloudapi.cn`.
See https://docs.microsoft.com/en-us/azure/china/resources-developer-guide.

Therefore, it is actually important for the EventHubClient to know the full namespace along with the right suffix.

**Comment by jsquire** [comment]
> This is not entirely true. The AMQP connection requires to know the entire full your-namespace-name.servicebus.windows.net and not just the name of the namespace we want to connect to. The AMQP connection itself doesn't need to know the event hub name.

The point wasn't to be fully detail-accurate, as I haven't dug into the AMQP level in depth yet.  The point was that the `sb://` protocol used in the portal is thrown away.

**Comment by jsquire** [comment]
> Another point to note is that the suffix servicebus.windows.net is not the same for all clouds.  For example, the China cloud would have the suffix servicebus.chinacloudapi.cn.

Yes, therein lies the rub.  That's the challenge to design around.  If it was as straight-forward as a simple append, it would have taken less time to just do the implementation than it would to have written up an issue.  :)

**Comment by ramya-rao-a** [comment]
As far as I understand, the suffix problem is not something that we can design around in the client side though. It is entirely a service side construct.

**Comment by jsquire** [comment]
> As far as I understand, the suffix problem is not something that we can design around in the client side though. It is entirely a service side construct.

You may very well turn out to be correct, but I think it's worth looking into and potentially having a conversation with the service team about.  They may have some thoughts on a way to query it.   If nothing else, hopefully, it'll accentuate the need to expose the value in a prominent location in the portal.

**Comment by jsquire** [comment]
After discussion, the Azure Messaging service team has agreed to make the fully qualified Event Hubs namespace a member of the properties that appear in the Azure portal, and to elevate it to the overview in a prominent location.

This proposal will not move forward.
