### ISSUE TITLE
Address ConnectionString parsing in AppConfiguration

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#7248]
Per TODOs in ConfigurationClient_private.cs:

- // TODO (pri 2): this allows elements in the connection string to be in varied order. Should we disallow it?
- // TODO (pri 2): this parser will succeed even if one of the elements is missing (e.g. if cs == "a;b;c". We should fix that.
- // TODO (pri 2): this might throw an obscure exception. Should we throw a consistent exception when the parser fails?

Finalize and implement.  
- Is varied order allowed by connection string format?  
- Fix the second issue.
- Wrap exception and include original exception as inner exception.  Vet with API folks.

Initial research on connection string:
https://azure.microsoft.com/en-in/blog/windows-azure-web-sites-how-application-strings-and-connection-strings-work/
https://blogs.msdn.microsoft.com/kaushal/2017/05/04/azure-app-service-how-to-read-parse-connection-strings-via-php/

**Comment by zhenlan** [comment]
Varied order should be allowed as long as all required elements are present.
