### ISSUE TITLE
Suggested .NET Guidelines Updates

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#7250]
The following is a list of suggested updates based on making sure AppConfig complies with the .NET guidelines:

- [ ] Does this need to be updated with AsyncCollection?
**DO** return IEnumerable<Response<T>> or ``IAsyncEnumerable<Response>` from service methods that return a collection of items.
- [ ] We no longer have ConfigurationModelFactory.SettingBatch(), which is referenced under guideline: 
 **DO** provide factory or builder for constructing model graphs returned from virtual service methods.
- [ ] Guideline containing \<TargetFramework\>netstandard2.0\<\/TargetFramework\>is overly prescriptive.
- [ ] HttpPipelineOptions has been renamed ClientOptions, should be updated in guideline:
**DO** name subclasses of HttpPipelineOptions by adding Client suffix to the name of the client type the options subclass is configuring.
- [ ] Method implementation is out of sync with code in guidelines - as discussed, update guidelines so they don't imply it's exact code, specifically in HttpPipeline section, possibly elsewhere.
- [ ] We call something Azure.ETag in the guidelines, but this isn't the precise namespace:
 **DO** use Azure.ETag to represent ETags.
- [ ] As discussed, move engineering systems guidelines (with link to them) possibly to the intro, as a reference similar to the general guidelines.
**DO** follow Azure SDK engineering systems guidelines for working in the azure/azure-sdk-for-net GitHub repository.

**Comment by heaths** [comment]
I ran across this while looking for something else. Is this still relevant? I believe this is all in our guidelines now.

**Comment by jsquire** [comment]
After a quick at-a-glance validation, it appears that these are all included in gudelines.  Given the age of this issue, I'm going to close this out as stale.   Please feel free to reopen if further action  is needed.
