### ISSUE TITLE
How to fetch encrypted blob using rest api?

### ISSUE THREAD

**Issue by sdbhattacharya** [Azure/azure-sdk-for-net#7255]
**Query/Question**
I need to know how to extract blob content from azure which is encrypted using a BYOK stored in keyvault over Rest API?
I'm using storage (general purpose v1) type resource.

***Why is this not a Bug or a feature Request?***
This information might be readily available which I am not able to locate using the docs.

**Setup (please complete the following information if applicable):**
 - OS: Windows 10
 - IDE : VS 2017 Enterprise
 - Version of the Library used
Microsoft.Azure.KeyVault.Extensions - 3.0.4
WindowsAzure.Storage - 9.3.3
 
sample code used
----------------------
private static async Task GetContent(string token)
        {
            HttpClient client = new HttpClient();            

            string sasToken = "?sv=Some-Token";
            string url = "https://abcd.blob.core.windows.net/Container1/0156b3d3-8923-407e-b80c-c7ty0498edcu"          
               
           

            string finalUrl = url + sasToken;
            string _algorithm = string.Empty;
            try
            {
                using (HttpResponseMessage response = await client.GetAsync(finalUrl, HttpCompletionOption.ResponseHeadersRead))
                {
                    if (response.StatusCode == HttpStatusCode.OK)
                    {
                        /*
                         Retrieve information for encryption from response header
                         */
                        var headers = response.Headers;
                        if (headers != null)
                        {
                            string jsonText = string.Empty;
                            foreach (var header in headers)
                            {
                                if (header.Key.ToLower().Equals("x-ms-meta-encryptiondata"))
                                {
                                    jsonText = header.Value.First();
                                    dynamic encryptionData = JsonConvert.DeserializeObject<ExpandoObject>(jsonText, new ExpandoObjectConverter());
                                    dynamic encryptionAgent = encryptionData.EncryptionAgent;
                                    _algorithm = Convert.ToString((dynamic)encryptionAgent.EncryptionAlgorithm);

                                    _rsaKey = await GetRSAFromKeyVault(jsonText);
                                    break;
                                }
                            }
                        }
                    }
                }

                client.DefaultRequestHeaders.Add("x-ms-encryption-key", Base64Encode(_rsaKey.Kid));
                client.DefaultRequestHeaders.Add("x-ms-encryption-algorithm", _rsaKey.DefaultEncryptionAlgorithm);//"AES256"
                client.DefaultRequestHeaders.Add("x-ms-version", "2018-03-28");

                using (HttpResponseMessage res = await client.GetAsync(finalUrl, HttpCompletionOption.ResponseHeadersRead))
                {
                    if (res.StatusCode == HttpStatusCode.OK)
                    {
                        using (Stream streamToReadFrom = await res.Content.ReadAsStreamAsync())
                        {
                            Microsoft.Azure.KeyVault.KeyVaultClient kv = new Microsoft.Azure.KeyVault.KeyVaultClient(new Microsoft.Azure.KeyVault.KeyVaultClient.AuthenticationCallback(GetToken));
                            var keyIdentifier = "https://keyvault1.vault.azure.net/keys/EncryptionKey/g8c8e3af1d9j41629605e808c8a7gcc0";
                            KeyVaultCrypto obj = new KeyVaultCrypto(kv, keyIdentifier);
                            
                            var temp = obj.DecryptAsync(ReadFully(streamToReadFrom)).GetAwaiter().GetResult();
                            
                            using (System.IO.FileStream output = new System.IO.FileStream(@"C:\somefile.pdf", FileMode.Create))
                            {
                                streamToReadFrom.CopyTo(output);                                
                            }
                        }
                    }
                }
            }
            catch (Exception)
            {
                throw;
            }
            finally {
                _rsaKey.Dispose();
            }            
        }

**Comment by amishra-dev** [comment]
We added support for this in our .NET SDK release 11.0, I would encourage you to use that. If you want to look at the change please look at [this](https://github.com/Azure/azure-storage-net/commit/e8af68b1cb10296dbd1e9211734dfe82cbd59c6f).

If you just want to use the Rest API, here is a simplified example from our [python sdk](https://github.com/Azure/azure-storage-python/blob/54e60c8c029f41d2573233a70021c4abf77ce67c/azure-storage-blob/azure/storage/blob/_serialization.py#L55)
