### ISSUE TITLE
AcceptMessageSession to takes more than few minutes without Timeout exception

### ISSUE THREAD

**Issue by basavarajb** [Azure/azure-sdk-for-net#7256]
**Actual Behavior**
AcceptMessageSession takes from 5ms to more than minutes - timeout was set to 5ms and to default one.

**Expected Behavior**
We're trying to read messages from Servicebus in Azure environment. Our process is run inside Continuous Webjob and it sometimes fails with TimeoutException.

We find out that there is a problem with AcceptMessageSession.
Our workflow:

receive all messages for specific session 
Do business logic 
Post message to another queue 
Then save data into database
complete all messages from session at once and go to other session
From time to time AcceptMessageSession takes a lot of time (in minutes): AcceptMessageSession invocation which takes from 1 to 3 minutes 

We thought that Servicebus will throw exception when methods is taking more than expected.

**Versions**
OS platform and version: Azure, azureWebjobs: Latest version
.NET Version: .NET Core 2.1
NuGet package version or commit ID: Microsoft.Azure.ServiceBus 3.4.0

**Code**
`sessionClient.OperationTimeout = new TimeSpan(0, 0, 5); session = await sessionClient.AcceptMessageSessionAsync();  `

**Comment by basavarajb** [comment]
> **Actual Behavior**
> AcceptMessageSession takes from 5ms to more than minutes - timeout was set to 5ms and to default one.
> 
> **Expected Behavior**
> We're trying to read messages from Servicebus in Azure environment. Our process is run inside Continuous Webjob and it sometimes fails with TimeoutException.
> 
> We find out that there is a problem with AcceptMessageSession.
> Our workflow:
> 
> receive all messages for specific session
> Do business logic
> Post message to another queue
> Then save data into database
> complete all messages from session at once and go to other session
> From time to time AcceptMessageSession takes a lot of time (in minutes): AcceptMessageSession invocation which takes from 1 to 3 minutes
> 
> We thought that Servicebus will throw exception when methods is taking more than expected.
> 
> **Versions**
> OS platform and version: Azure, azureWebjobs: 3.0.2
> .NET Version: .NET Core 2.1
> NuGet package version or commit ID: Microsoft.Azure.ServiceBus 3.4.0

**Comment by axisc** [comment]
@basavarajb

Thanks for reporting this issue.

Could you provide the below details. These will help with triaging the issue - 
  - Where is the namespace hosted?
  - Where is the client application hosted?
  - Is the namespace on the Standard or Premium tier?
  - Does the Service Bus queue have active sessions when the program is calling AcceptMessageSesionAsync()?

**Comment by axisc** [comment]
hi @basavarajb,

Do you still see this issue? If so, please consider opening a support ticket with the relevant information so that we can track this appropriately.

I'll close this issue for now.

Thanks
