### ISSUE TITLE
[FEATURE REQ] Azure KeyVault Secret - Add local development support

### ISSUE THREAD

**Issue by sujayvsarma** [Azure/azure-sdk-for-net#7269]
Microsoft's recent official guidance dictates that developers use the KeyVault to store application secrets and non-Git-table configuration. Of course, one could store them in environment variables and strange places like that -- but none of those options are **deployment** friendly.

So this is a feature request to have some sort of support for local development, at least at the SDK level. For example, the Storage system uses the Emulator service (though it is not a 100% replica of the Azure Storage system, it is reasonable enough to do some debugging aboard an aircraft on your laptop).

How do I envision this working:

- The project's app.Development.config provides the Vault URI as localhost (let's say "https://localhost:9000/vault"). This is a magic string as far as the SDK is concerned. 

- When it runs, if the URI matches the magic string, the SDK will not connect to Azure at all. Instead, it will use local disk storage.

The local storage for the vault can be a json file named "vault.json" in the project's directory tree (this will make it editable to the developer).

**Comment by maggiepint** [comment]
@schaabs

**Comment by pakrym** [comment]
What kind of application model are you using? ASP.NET or ASP.NET Core?

This feature request seems like something that needs to be handled on the higher level of abstration and sounds similar to what user secrets feature does (https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-2.2&tabs=windows).

**Comment by sujayvsarma** [comment]
ASP .net Core.

Yes, I have a similar conversation going about App Configuration with someone else. I think it should be handled there as well.

**Comment by pakrym** [comment]
Yes, I think for ASP.NET Core the most appropriate place to handle development scenario is at the Configuration system layer because it can be done once instead of adding support to every configuration provider.
