### ISSUE TITLE
Consider Nullable Reference Types for Client and Options in AppConfig

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#7271]
More details: https://devblogs.microsoft.com/dotnet/try-out-nullable-reference-types/ 
Example PR: https://github.com/Azure/azure-sdk-for-net/pull/7263

**Comment by jsquire** [comment]
Moving this to the backlog milestone, as the associated milestone date has passed.

@AlexanderSher:  Since you're the assigned engineer, would you be so kind as to help route this to the correct milestone and epic?

**Comment by AlexanderSher** [comment]
Closing because .Net team has decided to use reference types directly. FYI @pakrym
