### ISSUE TITLE
[BUG] Azure.Core.ResponseOfT contains disposable Response

### ISSUE THREAD

**Issue by j82w** [Azure/azure-sdk-for-net#7286]
**Describe the bug**
[`Response<T>`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/ResponseOfT.cs) contains a disposable [Response](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/Response.cs) property. There is no way to dispose of the inner Response object. This is a memory leak and will cause additional overhead for garbage collection. 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by j82w** [comment]
@pakrym this is related to the recent [PR](https://github.com/Azure/azure-sdk-for-net/pull/7273)

**Comment by pakrym** [comment]
Not disposing a reference doesn't cause a memory leak as long as it doesn't hold any common/unmanaged resources without having a finalizer. 

In the case of the Response the only part that holds onto shared resource is the content stream. It also depends if response buffering is enabled:
1. In the case where buffering is enabled the process of buffering itself would dispose the underlying stream and avoid resource leak, buffered stream is just a memory stream and can be collected.
2. In the case where buffering is disabled, it's clients responsibility to either dispose Response it got from the pipeline or return Response<T> where T is IDisposable and consumer of the client SDK has to dispose the value.

In addition not disposing something doesn't add any GC overhead because no matter if an object is disposed GC still has to walk the graph and collect it.

**Comment by j82w** [comment]
1. Response ContentStream is a Stream. There is no guarantee that it is a MemoryStream. Does Response need to be updated to be MemoryStream instead of Stream?
2.  How will users know that there is inner property that needs to be disposed of?
3. Would a better solution be to use Memory<byte> or Span<byte> instead of Stream? It would remove all the dispose logic and it would give better performance.

**Comment by pakrym** [comment]
The response should be able to handle both buffered and streamed responses, Memory or MemoryStream would only work for buffered responses.

We know that Response.ContentStream would be MemoryStream for buffered responses because we control the buffering logic and create the stream.

**Comment by pakrym** [comment]
Any reason not to make ChannelEnumerableSubscription itself IAsyncEnumerator ?

**Comment by j82w** [comment]
My issues with this is it is dependent on a implementation detail, and not the contract. If someone changes that implementation in the future then this will be broken. There is also no way for users to know if they need to dispose of the inner stream or not to dispose of it. 

What scenario requires supporting stream? Would users actually get better use out of always having a buffered Memory object?

**Comment by pakrym** [comment]
> My issues with this is it is dependent on a implementation detail, and not the contract. If someone changes that implementation in the future then this will be broken. There is also no way for users to know if they need to dispose of the inner stream or not to dispose of it.

Users never have to dispose the inner stream. Users only need to dispose something when the return type is Response<Stream> then they have to dispose the response.Value.

>What scenario requires supporting stream? Would users actually get better use out of always having a buffered Memory object?

Downloading large files from blob storage, for example.

**Comment by j82w** [comment]
> Users never have to dispose the inner stream. Users only need to dispose something when the return type is Response then they have to dispose the response.Value.

I'm a little confused here. `Response<T>`  has an inner `Response `object that is disposable. If `Response ` contains a network or some other Stream type that needs to be disposed of how is it getting disposed of?

**Comment by pakrym** [comment]
> I'm a little confused here. Response<T> has an inner Response object that is disposable. If Response contains a network stream or some other stream type that needs to be disposed of how is it getting disposed of?

We are controlling the clients and the pipeline and wouldn't return Response<T> that has a network stream in it.
