### ISSUE TITLE
No EventListener on Xamarin (Mono) Implementations

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-sdk-for-net#7292]
**Describe the bug**
The Azure.Core logging uses EventSource to log diagnostic messages.  This relies on an implementation of EventListener to get the logging into something you can read.  However, there is no EventListener in Mono.  Hence I can't log.

See https://github.com/mono/mono/blob/master/mcs/class/corlib/System.Diagnostics.Tracing/EventListener.cs 

**Setup (please complete the following information):**
 - OS: iOS / Android
 - IDE : Visual Studio 2019
 - Version of the Library used: Storage preview-2

**Comment by KrzysztofCwalina** [comment]
This is a feature request on the Xamarin team. I communicated the request to them.
