### ISSUE TITLE
Storage tests failing sometimes on MacOS

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-for-net#7296]
I've been seeing this storage test failing intermittently on MacOS.

```
X UploadRangeAsync_WithUnreliableConnection [1s 634ms] |  
-- | --
  | Error Message: |  
  | Final progress has unexpected value |  
  | Expected: 1048576 |  
  | But was:  131072 |  
  |   |  
  | Stack Trace: |  
  | at Azure.Storage.Files.Test.FileClientTests.UploadRangeAsync_WithUnreliableConnection() in /Users/vsts/agent/2.155.1/work/1/s/sdk/storage/Azure.Storage.Files/tests/FileClientTests.cs:line 675
```
Couple example runs:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=88791&view=logs&j=e44bd064-d8d9-5feb-6343-09b8c49ab1a8
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=86776&view=logs&j=e44bd064-d8d9-5feb-6343-09b8c49ab1a8

**Comment by weshaggard** [comment]
Another instance:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=88871&view=logs&j=e44bd064-d8d9-5feb-6343-09b8c49ab1a8

If we keep hitting this I will disable this test until it can be fixed.

**Comment by pemari-msft** [comment]
This is a dup, so clsoing and linking to the other.
