### ISSUE TITLE
[FEATURE REQ] - New SDKs - Add "Export as Template" function

### ISSUE THREAD

**Issue by sujayvsarma** [Azure/azure-sdk-for-net#7304]
In the new SDKs, please consider adding an "Export as Template" function. This would export the configuration as an ARM template. 

**Pathways**

Mode |Description
-------|---------------
Create|Instantiate a new resource object of the type (say `Compute`), configure all the elements for that resource, and call `Export()`. This would export whatever has been configured (and other essentials with default values) to the ARM template for that resource type.
Current|Fetch current resource from Azure, call `Export()`. This would export the currently deployed resource as an ARM template.
Load and Deploy|Load a previously configured ARM template directly (deserialize), and then proceed to deploy it with `DeployFromTemplate()` or whatever.

**Comment by sujayvsarma** [comment]
Currently the ExportTemplate function is available only for `ResourceGroups`:

[ResourceGroup Export Template API Doc](https://docs.microsoft.com/en-us/rest/api/resources/resourcegroups/exporttemplate).

My request is to extend this to other resources. Presumably, the generic `Resource` class implements it, with overloaded specific implementations in other resource types.

**Comment by isra-fel** [comment]
Sorry for late response. @armleads-azure could you please share some insights? Thank you.

**Comment by snaheth** [comment]
Adding @apclouds to capture this feature request

**Comment by apclouds** [comment]
Hi @sujayvsarma, you can achieve this today by passing in a list of the resource ID(s) you want to export: https://docs.microsoft.com/en-us/rest/api/resources/resourcegroups/exporttemplate#exporttemplaterequest

**Comment by sujayvsarma** [comment]
> Hi @sujayvsarma, you can achieve this today by passing in a list of the resource ID(s) you want to export: https://docs.microsoft.com/en-us/rest/api/resources/resourcegroups/exporttemplate#exporttemplaterequest

This requires all resources requested to be in the same resource group. That is not how we create resources.

**Comment by apclouds** [comment]
@sujayvsarma to confirm, your feature request is for Export Template to work across distinct Resource Groups, and produce a single template with the specified resources from each of those?

**Comment by sujayvsarma** [comment]
@apclouds  - Yes. I am also okay with the result being multiple json files. Consider something like this:

```csharp
VirtualMachine vm = new VirtualMachine() 
{
  // do a bunch of VM property config here
};

vm.Deploy();

// Now this is what I envisage!
vm.ExportTemplate();

```

Also:

```csharp
ResourceGroup rg = new ResourceGroup("Test");
VirtualMachine vm = new VirtualMachine() 
{
   vm.ResourceGroup = rg,

  // do a bunch of VM property config here
};

rg.Deploy();

rg.ExportTemplate();
```

Stuff like that. you get the idea.

**Comment by apclouds** [comment]
@sujayvsarma I will capture this feature request on my end. Can you also share the scenario for which you want this capability? Can you elaborate on why you want to export from different RGs into a single template?

**Comment by sujayvsarma** [comment]
What do you mean why? This is how people use the clouds.

**Comment by apclouds** [comment]
@sujayvsarma sorry for the confusion. The ask was to see if there were any other details you wanted to share around why export from a single resource group was not enough. The feature request for export template across different RGs has been captured.
