### ISSUE TITLE
ServiceBus Track 2 work items

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#7306]
- [ ] Management client
  - [ ] Recorded tests
  - [ ] Constructors
  - [ ] Sync methods
  - [ ] Remove polly from existing tests
- [ ] NUnit test
- [ ] Cancellation tokens

**Comment by SeanFeldman** [comment]
As an external colaborator I have no visibility into the planning of work items. To be able to contribute meaningfully, @pakrym would it be possible to provide a minimal context in the issue description? Quite possible that won't be able to contribute at all, but perhaps others will.
Thank you.

**Comment by AlexGhiondea** [comment]
I am closing this for now. We will create separate work items going forward as needed.
