### ISSUE TITLE
Add AppConfiguration client that takes endpoint only.

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#7310]
AppConfiguration client SDK should support the scenario where, if the user has logged in to Azure, they only need to specify the endpoint of the service in a Client constructor, not a full connection string.

**Comment by pakrym** [comment]
FYI. With the way we do clients in track 2 it would also need to have TokenCredential parameter

**Comment by annelo-msft** [comment]
This approach goes counter to Architecture Board guidelines.  It has been replaced by: https://github.com/Azure/azure-sdk-for-net/issues/7571
