### ISSUE TITLE
[QUERY] Response<T> ergonomics 

### ISSUE THREAD

**Issue by loic-sharma** [Azure/azure-sdk-for-net#7315]
**Query/Question**
I'm a little concerned that returning `Response<T>` from all service methods "pollutes" customers' code. For this example:

```csharp
var client = new BlobContainerClient(connectionString, "container");
ContainerItem containerItem = await client.GetPropertiesAsync();

Console.WriteLine(containerItem.Name);
```

I almost always want to access the `ContainerItem` instead of the raw `Response`. Considering my team uses `var` pervasively, the wrapper `Response` object makes this a little less convenient:

```csharp
var client = new BlobContainerClient(connectionString, "container");
var response = await client.GetPropertiesAsync();

Console.WriteLine(response.Value.Name);
```

It seems like we'll need to add `.Value` wherever we use the Azure SDK. Is it really that useful to expose the raw response everywhere? What customer scenarios need the raw response? Would it be better to have separate "high level" APIs that hide the response object from "low level" APIs that expose it?

***Why is this not a Bug or a feature Request?***
This is a question so that I can understand a design choice better.

**Setup (please complete the following information if applicable):**
N/A
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Query Added
- [X] Setup information Added

**Comment by loarabia** [comment]
Tagging for some of the architects to respond to.

**Comment by loic-sharma** [comment]
>  But we explored many alternatives, and felt the current design is the best trade off.

Be that as

**Comment by loic-sharma** [comment]
Thank you for the response!

> We could have added separate APIs from these scenarios (as you mentioned), but this results in more complexity (more types/members).

I agree that adding separate APIs for these scenarios adds more complexity. However, wrapping values in `Response<T>` also adds a complexity:

1. My code won't compile if I copy the samples but replace the type declarations with `var`. This seems like a poor first experience.
1. I'll need to add `.Value` calls everywhere

> But we explored many alternatives, and felt the current design is the best trade off.

Could you describe how the trade offs were evaluated?

**Comment by loic-sharma** [comment]
> My code won't compile if I copy the samples but replace the type declarations with var. This seems like a poor first experience.

This seems was addressed by https://github.com/Azure/azure-sdk-for-net/pull/7769. Feel free to close off this issue
