### ISSUE TITLE
Storage: Disabling tests that don't accept Now for x-ms-file-creation-time

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#7318]
I've disabled a handful of tests that fail with a default value of `Now` for `x-ms-file-creation-time` to unblock moving to 2019-02-02 for Files

**Comment by seanmcc-msft** [comment]
This is because the default value for the times on those APIs is "Preserve", not "Now".

**Comment by tg-msft** [comment]
Great - I made a best guess based on what's documented in https://docs.microsoft.com/en-us/rest/api/storageservices/create-file until the tests started passing.  😄
