### ISSUE TITLE
[BUG] Migrating from EventSender to PartitionSender - how to tell if sender is closed?

### ISSUE THREAD

**Issue by amirxnz** [Azure/azure-sdk-for-net#7322]
I am trying to migrate code that used the old EventHubSender from the Microsoft.ServiceBus (.Net Framework) to the new PartitionSender in the Microsoft.Azure.EventHubs package. In the old package I could run OnClosed on the sender and recreate it if needed. However, I can't find any way to do it here.

I have a "sender pool" that I am maintaining so I want to make sure that no one closed the sender before I pass it to some other call.

Any direction in this matter will be greatly appreciated, thanks!

**Comment by serkantkaraca** [comment]
Unfortunately clients don't have a way to tell whether close called or not on them. There is a flag for this hidden for internal use only. I will send a PR to make it available publicly.

**Comment by serkantkaraca** [comment]
PR here https://github.com/Azure/azure-sdk-for-net/pull/7365

**Comment by serkantkaraca** [comment]
Fix is merged to master.
