### ISSUE TITLE
EnumerateChannelRespectsTheMaximumWaitTime test flaky

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#7330]
https://dev.azure.com/azure-sdk/public/_build/results?buildId=91413&view=ms.vss-test-web.build-test-results-tab&runId=3694460&resultId=102087&paneView=debug

```
  The elapsed time should be close to the duration set for the cancel timeout.

  Expected: 00:00:01 +/- 00:00:02

  But was:  00:00:03.3003010

```

**Comment by jsquire** [comment]
Fixed by:  https://github.com/Azure/azure-sdk-for-net/pull/7332

**Comment by pakrym** [comment]
Still fails
```
There should have been default items returned due to the wait time expiring.

  Expected: greater than 2

  But was:  2
```

**Comment by pakrym** [comment]
`EnumerateChannelRespectsWhenThereIsNoMaximumWaitTime` is flaky too:

```
  The elapsed time should be close to the duration set for the cancel timeout.

  Expected: 00:00:00.2800000 +/- 00:00:02

  But was:  00:00:02.7934437

```

**Comment by jsquire** [comment]
I'll restructure both with the next set of changes that I push through.

**Comment by jsquire** [comment]
Both tests were restructured to reduce the dependency on timing elements.  This should be resolved with the merging of the linked PR.    Closing and will continue to monitor nightly runs.
