### ISSUE TITLE
[FEATURE REQ] Client SDK Show error messages

### ISSUE THREAD

**Issue by brendanburkhart** [Azure/azure-sdk-for-net#7333]
Using the C# TextAnalyticsClient I was getting seemingly random `Unhandled Exception: Microsoft.Azure.CognitiveServices.Language.TextAnalytics.Models.ErrorResponseException: Operation returned an invalid status code 'Forbidden`. It wasn't till I used Fiddler to watch the actual network requests that I saw the attached error message - `Out of call volume quota. Quota will be replenished in`. I believe this SDK would be better if the HTTP error message was included in the exception message.

It would also be nice if CognitiveServices with the more helpful 429 Too Many Requests rather than 403 Forbidden when the call volume quota is exceed, but at least it returns a useful message.

**Comment by assafi** [comment]
Resolved in new SDKs. 
https://docs.microsoft.com/en-us/azure/cognitive-services/text-analytics/quickstarts/text-analytics-sdk?tabs=version-3&pivots=programming-language-csharp
