### ISSUE TITLE
[FEATURE REQ] Check if App Service exists globally

### ISSUE THREAD

**Issue by rfabro** [Azure/azure-sdk-for-net#7341]
**Is your feature request related to a problem? Please describe.**
I'm trying to automate the app service deployment to Azure via the SDK and it's a pain to create an app service that already exists globally.

**Describe the solution you'd like**
A function in the SDK that checks if an app service exists globally.

**Describe alternatives you've considered**
I can check via Azure portal if the app service exists but I want to do things in an automated approach. I can curl the possible app service URL but a method built right into the SDK would be a better solution.

**Comment by panchagnula** [comment]
@naveedaz FYI

**Comment by rfabro** [comment]
After some time exploring the Azure SDK, I've learned that the `CheckNameAvailabilityAsync` method under the `WebSiteManagementClientExtensions` class does check if the App service exists globally. Will  now be closing this request.
