### ISSUE TITLE
[BUG] Inconsistant property types in generated types

### ISSUE THREAD

**Issue by seanmcc-msft** [Azure/azure-sdk-for-net#7346]
FlattenedStorageFileProperties.ContentLanguage and .ContentEncoding are strings, but RawStorageFileProperties.ContentLanguage and .ContentEncoding are IEnumerable<string>.  

These properties are all listed as strings in the Files swagger.  Why is the generator generating different types for the same swagger types?

This is causing FileClientTests.DownloadAsync() to fail.

**Comment by tg-msft** [comment]
> Why is the generator generating different types for the same swagger types?

Probably because one is being changed by a transform but the other isn't: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Files/swagger/readme.md#sharenamedirectoryfilename

**Comment by tg-msft** [comment]
This is just a swagger change so assigning back to @seanmcc-msft to update the swagger to match what the service is expecting for this API.
