### ISSUE TITLE
[BUG] DirectoryClient.SetDirectoryProperties should return a RawStorageDirectoryInfo instead of a DirectorySetPropertiesResult

### ISSUE THREAD

**Issue by seanmcc-msft** [Azure/azure-sdk-for-net#7349]
These two classes are identical, so we don't need DirectorySetPropertiesResult.

**Comment by tg-msft** [comment]
You're probably missing an `x-ms-client-name` (soon to be `x-az-response-name`) on `SetDirectoryProperties`'s response.  If you give two responses the same name `x-ms-client-name`, they'll merge into a single class like you want.

**Comment by tg-msft** [comment]
Assign back @seanmcc-msft  as this is an issue with swagger you haven't checked in yet.
