### ISSUE TITLE
[BUG] ManagementClient.GetQueuesAsync()

### ISSUE THREAD

**Issue by Ubel** [Azure/azure-sdk-for-net#7353]
Hello,

Until the 8 august, i receive this error "Requested value 'ManageNotificationHub' was not found" when i call the methode GetQueuesAsync() of ManagementClient but I doesn't release new app since the 3 july.
Was there a change on the azure service bus?

i use the packahe Microsoft.Azure.ServiceBus 3.3.0

Sample for reproduce
`client = new ManagementClient(AliasConnectionString);
            {
                try
                {
                    var queues = await client.GetQueuesAsync();
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }
            }`

Thanks for your answers.
Ubel

**Comment by axisc** [comment]
@Ubel 

Thanks for raising this issue. Are you utilizing Notification Hub as well?

Could you also provide the namespace you are using? Please be sure to *not* include the sas tokens.

**Comment by Ubel** [comment]
Hi @axisc !

We don't use notification hub.
The namespace use for ManagementClient is Micorsoft.Azure.ServiceBus.Management.

The list of used namespaces: 

using Microsoft.ApplicationInsights;
using Microsoft.Azure.ServiceBus;
using Microsoft.Azure.ServiceBus.Management;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reactive.Concurrency;
using System.Reactive.Linq;
using System.Reactive.Subjects;
using System.Threading.Tasks;

**Comment by nemakam** [comment]
@Ubel , yes, there was a service deployment that I see that happened on 8th August. 
But `Requested value 'ManageNotificationHub' was not found` seems weird. 
What kind of access rights are you requesting from?
I'm curious as to what does your connection string look like? **without the secrets**

And after august 8, are things working as expected or are you seeing any errors?

**Comment by Ubel** [comment]
@nemakam ,
I request the 'manage' right to know the list of queues and topics in the namespace.
Then i request the information of each, to know the number of active and dead-letter messages for each.

My connection string without the secret : Endpoint=sb://alarmhub-infra-int-sbn.servicebus.windows.net/

After the 8 august, i always receive the error "Requested value 'ManageNotificationHub' was not found" when i call the method GetQueuesAsync().

**Comment by Ubel** [comment]
I found the problem by downloading the service bus template.
One queue have bad right : 

`{
            "type": "Microsoft.ServiceBus/namespaces/queues/authorizationRules",
            "apiVersion": "2017-04-01",
            "name": "[concat(parameters('namespaces_alarmhub_infra_int_sbn_name'), '/datahistory-queue/RootManageQueuePolicy')]",
            "location": "France Central",
            "dependsOn": [
                "[resourceId('Microsoft.ServiceBus/namespaces/queues', parameters('namespaces_alarmhub_infra_int_sbn_name'), 'datahistory-queue')]",
                "[resourceId('Microsoft.ServiceBus/namespaces', parameters('namespaces_alarmhub_infra_int_sbn_name'))]"
            ],
            "properties": {
                "rights": [
                    "ManageNotificationHub"
                ]
            }
        }`

it's weird that this value can be applied but with the good rights : [ "Manage", "Send", "Listen" ],
the method GetQueuesAsync() works.
