### ISSUE TITLE
Cannot access AMQP annotations (eg for iothub-* values)

### ISSUE THREAD

**Issue by nrandell** [Azure/azure-sdk-for-net#7356]
**Describe the bug**
The AMQP annotations aren't exposed as SystemProperties in EventData, so you cannot access the iothub-* properties (eg iothub-message-source)

***Exception or Stack Trace***

**To Reproduce**
Connect to an iothub end point.
Read a message.
Look at the event data in a debugger and only see 4 system properties (x-opt-sequence-number, x-opt-enqueued-time, x-opt-offset and x-opt-partition-key)
Compare to using 'az hub monitor-events --properties all' tat includes 'iothub-connection-message-source', 'iothub-connection-enqueuedtime' and various other 'iothub-' properties

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
The ability to access the iothub-* properties, or any annotations attached to the AMQP message. The previous library allowed this.
e.g. `receivedEvent.SystemProperties.TryGetValue(MessageSystemPropertyNames.ConnectionDeviceId, out var deviceId)`

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : Visual Studio 2019 
 - Version of the Library used: Azure.Messaging.EventHubs 5.0.0-preview.1

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by jsquire** [comment]
Rerouting this to Ramya for consideration, as the use of System Properties is under discussion for the new client library.

**Comment by ramya-rao-a** [comment]
@nrandell Apart from the message body, what else can be set on an IotHub message?

@sjkwak, @serkantkaraca,

As per one of our discussions, we concluded that the SystemProperties need not be exposed to the user. If IotHub allows users to set all properties on the AMQP message, then our library should expose these properties as well.

As per AMQP spec, below are things that can be set on an AMQP message
- message properties like `message_id`, `reply_to`, `to`, `correlation_id`, `content_type`, `content_encoding` etc.
- `message_annotations`
- `application_properties`
- `body`

**Comment by serkantkaraca** [comment]
Instead of considering individual message properties, better if you can provide those in a dictionary as in track-1 client. https://github.com/Azure/azure-sdk-for-net/blob/9c1795bad971d74a35069971570a5f7804fa5c81/sdk/eventhub/Microsoft.Azure.EventHubs/src/Amqp/AmqpMessageConverter.cs#L147

**Comment by xitia** [comment]
Hello, I am from stream analytics team. We need to get access to SystemProperties as well. We currently have a GAed feature to let people query system property metadata from eventhub events/ iothub events. Customers use it a lot to get info such as iothub device id etc. We could provide more customer scenarios if needed. Please do considering add these properties back. Thanks!

**Comment by nrandell** [comment]
@ramya-rao-a - my scenario is not that I set any properties from my iot client, it's that when I consume a message, I read some of the annotations to work out where the message came from. It reduces repetition as I don't need to include the origin in my message.

Have a look at https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messages-construct for some more details.

**Comment by ramya-rao-a** [comment]
Thanks all!

We will be bringing back the `SystemProperties` on the `EventData` back in the upcoming release of this library which will have the version 5.0.0-preview.3

Please note, that the name `SystemProperties` may or may not change in the preview that comes after i.e 5.0.0-preview.4 based on the api reviews we will be going through internally.

**Comment by jsquire** [comment]
The full set of system properties, including the untyped dictionary, has been reintroduced with PR #7461 and will be part of the third preview upon its release.
