### ISSUE TITLE
Microsoft.Azure.EventHubs.Processor library can not load Microsoft.WindowsAzure types from the Microsoft.Azure.Storage.Blob library with version >= 10.0.0

### ISSUE THREAD

**Issue by CapitalistHippie** [Azure/azure-sdk-for-net#7369]
**Describe the bug**
When Microsoft.Azure.Storage.Blob with a version higher than 9.4.2 is referenced the application fails on load with the below exception.

This is probably because of a namespace change in the Microsoft.Azure.Storage.Blob library since version 10.0.0

***Exception or Stack Trace***
```
System.Reflection.ReflectionTypeLoadException
  HResult=0x80131602
  Message=Unable to load one or more of the requested types.
Could not load type 'Microsoft.WindowsAzure.Storage.Blob.BlobResultSegment' from assembly 'Microsoft.Azure.Storage.Blob, Version=11.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
Could not load type 'Microsoft.WindowsAzure.Storage.Blob.BlobResultSegment' from assembly 'Microsoft.Azure.Storage.Blob, Version=11.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
``` 

**To Reproduce**
Have the processor library and the Microsoft.Azure.Storage.Blob library version 10.0.0 or higher referenced in the same console app and start it.

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
I expect it to not crash the application

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : Visual Studio 2019
 - Version of the Library used: 4.0.0

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by serkantkaraca** [comment]
Fix merged - https://github.com/Azure/azure-sdk-for-net/pull/7372
