### ISSUE TITLE
NetworkListResponse.VirtualNetworkSite needs a Location property

### ISSUE THREAD

**Issue by GarrettDavis** [Azure/azure-sdk-for-net#737]
During TechEd (May 12-15) or before, the concept of Regional Virtual Networks was announced.  When a new Virtual Network is created in the Portal, we don't even have the option of specifying an Affinity Group for the location, only a Region.  Unfortunately, the INetworkOperations.ListAsync() method's response ([NetworkListResponse](https://github.com/Azure/azure-sdk-for-net/blob/master/src/NetworkManagement/Generated/Models/NetworkListResponse.cs)) does not provide the region (VirtualNetworkSite.Location) of the Virtual Network, only a null AffinityGroup.  To work around this and obtain the region, I need to also make a call to INetworkOperations.GetConfigurationAsync() and parse the configuration XML.  I know that the [REST API](http://msdn.microsoft.com/en-us/library/azure/jj157185.aspx) response has VirtualNetworkSite.Location so the code for NetworkListResponse simply needs to be regenerated with the new schema.

BTW, where are the specifications for the generated files so when I make these requests in the future, I can simply fork a file and add a pull request?<p><a href="https://github.com/Azure/azure-sdk-for-net/issues/737">https://github.com/Azure/azure-sdk-for-net/issues/737</a></p>

**Comment by markcowl** [comment]
Closing as obsolete.  Please reopen if this issue recurs
