### ISSUE TITLE
Why do IQueueClient and ISubscriptionClient have identical but unrelated session handlers?

### ISSUE THREAD

**Issue by jholovacs** [Azure/azure-sdk-for-net#7371]
**Query/Question**
ISubscriptionClient:
```csharp
void RegisterSessionHandler(Func<IMessageSession, Message, CancellationToken, Task> handler, Func<ExceptionReceivedEventArgs, Task> exceptionReceivedHandler);
void RegisterSessionHandler(Func<IMessageSession, Message, CancellationToken, Task> handler, SessionHandlerOptions sessionHandlerOptions);
```
IQueueClient:
```csharp
void RegisterSessionHandler(Func<IMessageSession, Message, CancellationToken, Task> handler, Func<ExceptionReceivedEventArgs, Task> exceptionReceivedHandler);
void RegisterSessionHandler(Func<IMessageSession, Message, CancellationToken, Task> handler, SessionHandlerOptions sessionHandlerOptions);
```
I was trying to build a message handler on the client side for handling both queues and topics, since it's _literally exactly the same code once the message is consumed_ ... but this completely shut me down.

Why is there not an interface along the lines of:
```csharp
public interface IContinuousMessageClient
{
    void RegisterSessionHandler(Func<IMessageSession, Message, CancellationToken, Task> handler, SessionHandlerOptions sessionHandlerOptions);
    void RegisterSessionHandler(Func<IMessageSession, Message, CancellationToken, Task> handler, Func<ExceptionReceivedEventArgs, Task> exceptionReceivedHandler);
}

public interface ISubscriptionClient : IContinuousMessageClient, IReceiverClient, IClientEntity
{
    string TopicPath { get; }
    string SubscriptionName { get; }
    Task AddRuleAsync(string ruleName, Filter filter);
    Task AddRuleAsync(RuleDescription description);
    Task<IEnumerable<RuleDescription>> GetRulesAsync();
    Task RemoveRuleAsync(string ruleName);
}

public interface IQueueClient : IContinuousMessageClient, IReceiverClient, IClientEntity, ISenderClient
{
    string QueueName { get; }
}
```

I have to think this is deliberate, since it seems so obvious, but I cannot understand why.

**Comment by jholovacs** [comment]
OK, it looks like these methods are also on `IReceiver`, which both `IQueueClient` and `ISubscriptionClient` inherit from, so I can use that instead.

But since I've already asked, why are those methods on all three interfaces?  Doesn't this violate the DRY principle?

**Comment by axisc** [comment]
@jholovacs,

Thanks for reporting this issue. 

There is merit in what you are suggesting and we think it will help clean up the design. We will add this to the backlog.

**Comment by nemakam** [comment]
> But since I've already asked, why are those methods on all three interfaces? Doesn't this violate the DRY principle?

@jholovacs, the one which is in `IReceiverClient` is the `RegisterMessageHandler` which is for regular messages and not sessions. We would probably need a separate interface for sessions as we didnt want to have session related functionality in that `IReceiverClient`.

**Comment by jholovacs** [comment]
Should it matter?  At the end of the day, the implementation of the
interface is just consuming messages, correct?  The mechanism by which it
gets the message seems out of scope.

**Comment by nemakam** [comment]
Its slightly different.
When you say `RegisterSessionHandler`, it accepts new sessions, and passes you the session object. That session object is the actual "Receiver". So it doesn't really make sense to have a `RegisterSessionHandler` on the receiver object itself. 
We need a separate interface which does the job of `RegisterSessionHandler`. 

Essentially how this was designed is that, 
for most mainstream scenarios, you just want to use the handlers which will be part of `QueueClient` and `TopicClient`. If you need anything more than what the handler can do, then you can use the core pieces and build the whole thing yourself. Core pieces would include `MessageSender`, `MessageReceiver` and `SessionClient`.

**Comment by nemakam** [comment]
And btw, feel free to raise a PR...

**Comment by jholovacs** [comment]
I'll look at a PR next week, but it seems strange that the
RegisterSessionHandler exists on all three interfaces with the same
signature, especially considering that 2 inherit from the third already.
The intent is definitely not clear there.

**Comment by jholovacs** [comment]
Has it been removed since the latest Nuget package?  Last week I pulled in
the latest and those two methods were on all three.

**Comment by jsquire** [comment]
Moving this to the backlog milestone to match the associated tags; the assigned milestone has passed.

**Comment by ramya-rao-a** [comment]
Please note that a newer package `Azure.Messaging.ServiceBus` is available as of November 2020. While the older `Microsoft.Azure.ServiceBus` package for which this issue was logged will continue to receive critical bug fixes, we strongly encourage you to upgrade. Read the [migration guide](https://aka.ms/azsdk/net/migrate/sb) for more details.

The new package has a new client hierarchy which should not have the issues described here.
