### ISSUE TITLE
[QUERY] How can I instantiate a ServiceClient<T> such that it takes care of refreshing access tokens?

### ISSUE THREAD

**Issue by sandeepiiit** [Azure/azure-sdk-for-net#7379]
**Query/Question**
How can I instantiate a `ServiceClient<T>` such that it takes care of refreshing access tokens?

`KeyVaultClient` inherits from `ServiceClient`, and provides a constructor that takes a `AuthenticationCallback`. This allows `KeyVaultClient` to delegate the task of fetching access token to a delegate, for example to `AzureServiceTokenProvider.KeyVaultTokenCallback`. This delegate takes care of refreshing tokens.

However, I am unable to see similar capabilities in other classes that inherit from `ServiceClient`. For example, `DevTestLabsClient` doesn't have a ctor that takes an `AuthenticationCallback`. Is there a way to achieve a similar functionality for `DevTestLabsClient` ?

Below is my current code, and I am worried that my web app will start failing once the token expires, unless I recreate an instance of `DevTestLabsClient` on every request.

```cs
AzureServiceTokenProvider azureServiceTokenProvider = new AzureServiceTokenProvider();
string accessToken = await azureServiceTokenProvider.GetAccessTokenAsync(@"https://management.azure.com/");
TokenCredentials tokenCredentials = new TokenCredentials(accessToken);
IDevTestLabsClient dtlClient = new DevTestLabsClient(tokenCredentials, httpClient, disposeHttpClient: false);
// Will the dtlClient instance created above stop working when the access token expires?
// Is it recommended to create this client afresh before each use? (I would like to avoid that).

```

***Why is this not a Bug or a feature Request?***
I think this is my lack of knowledge rather than a bug or feature request.

**Setup (please complete the following information if applicable):**
 - OS: Windows 10
 - IDE : Visual Studio 2019
 - Version of the Library used:
     - Microsoft.Azure.Management.DevTestLabs 3.0.0
     - Microsoft.Azure.Services.AppAuthentication 1.0.3
     - Microsoft.IdentityModel.Protocols.OpenIdConnet 5.4.0
     - System.IdentityModel.Tokens.Jwt 5.4.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by kaerm** [comment]
Hi @sandeepiiit, thanks for reaching out, I'm tagging relevant teams

**Comment by joerage** [comment]
@sandeepiiit, sorry for the late response. You have probably figure things out since you asked, but here is a solution for anyone stumbling on this question.

Here is some code that shows how to only get a new token when necessary.

```
private static AppAuthenticationResult _authResult;
    private static TokenCredentials _credentials;
    private static DevTestLabsClient _dtlClient;

    public static async Task Main()
    {
        DateTime endTime = DateTime.Now.AddHours(2);
        while (DateTime.Now < endTime)
        {
            await EnsureDtlClientAsync();
            var lab = _dtlClient.Lab.GetResource("<rgName>", "<labName>");
            Console.WriteLine($"{DateTime.Now.ToShortTimeString()}: {lab.Name}");
            Thread.Sleep(1000 * 60 * 3);
        }
    }

    private static async Task EnsureDtlClientAsync()
    {
        if (_authResult != null)
        {
            TimeSpan tokenTimeRemaining = _authResult.ExpiresOn - DateTimeOffset.UtcNow;
            if (tokenTimeRemaining.TotalMinutes > 5)
            {
                return;
            }
        }
       
        _authResult = await new AzureServiceTokenProvider()
            .GetAuthenticationResultAsync(@"https://management.azure.com/", "<tenantId>");
        _credentials = new TokenCredentials(_authResult.AccessToken);
        _dtlClient = new DevTestLabsClient(_credentials)
        {
            SubscriptionId = "<subId>"
        };
    }
```

**Comment by razvansalajan** [comment]
Any update on this ? 
The alternative that I am thinking of is to have a custom implementation of [ITokenProvider ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.rest.tokencredentials.-ctor?view=azure-dotnet#Microsoft_Rest_TokenCredentials__ctor_Microsoft_Rest_ITokenProvider_ ) that takes an AzureServiceTokenProvider. 
Is there an alternative without a custom implementation ? 
If no, is there a plan to do one ?
