### ISSUE TITLE
Samples for Mocking Client Types

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#7382]
# Summary

The Event Hubs client library aims to be mockable and fully support testability.  To help illustrate usage of the new API for the testing scenarios, a set of samples  mocking the various Event Hubs client types and illustrating use of the model factory  is needed.

# Scope of Work

- Implement a sample or set of samples demonstrating a basic approach for mocking the high level client types for their core scenarios.  Included should be:<br />
  - `EventHubProducerClient`
  - `EventHubConsumerClient`
  - `EventProcessorClient`
  - `PartitionReceiver`
  - `EventProcessor<TPartition>` <br /><br />

- Ensure that the use of the model factory is demonstrated for key types, including:<br />
  - `EventData`
  - `EventDataBatch`
  - `EventHubProperties`
  - `PartitionProperties`
  - `PartitionPublishingProperties`
  - `LastEnqueuedEventProperties`
  - `PartitionContext`

# Success Criteria

- The sample(s) have been created, with a clear and simple approach and detailed discussion to support the goal of helping those unfamiliar with Event Hubs to get started testing its types.

- The sample(s) adhere to the coding conventions and standards defined for track two libraries.

- All projects in the solution compile; any warnings that exist have either been fixed or additional work items filed to address them if they were deemed non-critical.

- The sample(s) follow the pattern within the Event Hubs library, are compiled and executed as part of the Live test suite.

# Related

The following are promising pull requests begun by a community member before they were unable to complete due to time constraints.  These would serve as a great starting point.

- [Samples for Mocking Client Types (EventProcessor)](https://github.com/Azure/azure-sdk-for-net/pull/23677)
- [Samples for Mocking Client Types (EventHubProducerClient)](https://github.com/Azure/azure-sdk-for-net/pull/23867)

# References

- [.NET Guidelines (Mocking)](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-mocking)
- [Updating Sample Snippets (Contributing Guide)](https://github.com/Azure/azure-sdk-for-net/blob/master/CONTRIBUTING.md#updating-sample-snippets)
- [Event Hubs Hello World Sample](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample01_HelloWorld.md)
- [Hello World Snippets (1/2)](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/tests/Snippets/SamplesCommonTests.cs)
- [Hello World Snippets (2/2)](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/tests/Snippets/Sample01_HelloWorldLiveTests.cs)

**Comment by ACHYUT001** [comment]
Hi @jsquire,
If this is still open, I'd like to take this up.

**Comment by jsquire** [comment]
Hi @ACHYUT001.  Apologies for missing the notification on this earlier.  Your contribution would be greatly appreciated.   Our goal here would be to demonstrate the types mentioned in the scope, and I think the best way to do that would be to try and mirror some of the core scenarios that we demonstrate in our publishing, consuming, and processing samples.  

As you may already be aware, our samples are markdown-based and with the code driven from snippets defined in our test suite.  I added a few more references to the issue description that may help you get started.  Since this work is based around unit testing, we can probably avoid Live tests and just stick with unit tests - like the first set of snippets above.

I'm happy to help you along as best I can;  please feel free to use a draft PR to share ideas and start discussion,  just mention me when you'd like my thoughts.   Thank you for helping to make the Azure SDK experience better!

**Comment by ACHYUT001** [comment]
Hi @jsquire ,

Sorry, been a little away past few days.
I'll pick this up and have a draft PR done by EoW.

Thanks

**Comment by ACHYUT001** [comment]
@jsquire ,

I've started out writing the mocks.
Here are a few for Publishing, requesting your thoughts : [PR21630](https://github.com/Azure/azure-sdk-for-net/pull/21630)
Should I cover all the scenarios as done in the [publishing sample](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample04_PublishingEvents.md)? 

I also needed your thoughts in understanding the points to cover in the markdown file of the sample.

Thanks

**Comment by jsquire** [comment]
Yes, this work has not been completed.   There have been some contributions that formed a good foundation for the samples, but there is still some work needed to complete the sample.
