### ISSUE TITLE
The data contract for Computer Vision API OCR bounding boxes could use improvement

### ISSUE THREAD

**Issue by jakingmsft** [Azure/azure-sdk-for-net#7383]
After updating my **Microsoft.Azure.CognitiveServices.Vision.ComputerVision** Nuget package to version 5.0.0, the data contract for bounding boxes switched from `List<int>` to `List<double>`. 

1. [The documentation](https://westus.dev.cognitive.microsoft.com/docs/services/5adf991815e1060e6355ad44/operations/587f2cf1154055056008f201) still says "the eight integers." 
2. A pixel coordinate must be a whole number. So it is unclear how to convert `double` value to  a real pixel coordinate (round down or up?). I just guess by casting `(int)`. 
3. It would probably be better to have an object model like

```
{
    rectangle: { x: 202, y: 618, width: 2047, height: 840 },
    angle: 128.314 }
}
```

so that consumers of the service don't have to parse a length-8 array.

**Comment by kaerm** [comment]
Hi @jakingmsft thanks for reporting this, tagging the right teams to have a look at this

**Comment by cthrash** [comment]
- The documentation should get updated.
- OCR now handles PDFs in addition to images as input.  For images, the units are pixels but for PDFs the units are inch.  For a given response, you can see the units in the [TextRecognitionResultDimensionUnit field](https://github.com/Azure/azure-sdk-for-net/blob/4ac320b7bb143145d67d396cd33cf9cc1dc21a2f/sdk/cognitiveservices/Vision.ComputerVision/src/Generated/Models/TextRecognitionResult.cs#L95).
- While the existing data type is not great, what you're proposing doesn't take in to account the rotation of the rectangle.  The eight values represent the four coordinates of the rectangle.

**Comment by JimSuplizio** [comment]
Hi @jakingmsft, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
