### ISSUE TITLE
[BUG] CI should not run 'net - client - ci' for mgmt related PR

### ISSUE THREAD

**Issue by erich-wang** [Azure/azure-sdk-for-net#7388]
It seems that CI runs 'net - client - ci' although the change is mgmt related only, for example:
https://github.com/Azure/azure-sdk-for-net/pull/7363/.

**Comment by isra-fel** [comment]
Hello @kaerm , is there an ETA for this issue? It is breaking several management plain PRs.

Thanks

**Comment by chidozieononiwu** [comment]
Fixed with net - client - ci triggers. 
Changes in eng/mgmt, eng/mgmt.proj, eng/pipelines/mgmt.yml, eng/pipelines/templates/jobs/archetype-sdk-mgmt.yml will no longer trigger net - client -ci
