### ISSUE TITLE
Provide functionality to stop all role instances for a cloud service

### ISSUE THREAD

**Issue by rboorgapally** [Azure/azure-sdk-for-net#742]
Currently, I can reboot all role instances by slot using the SDK. Can we also have STOP?

One use case this will serve is that, I want to stop my staging which is on a old build. I will delete it after a few hours if I find my new build in production good enough. Other wise I will revert. I do not want staging to be running during this time.

This functionality is available on the portal but not in SDK.<p><a href="https://github.com/Azure/azure-sdk-for-net/issues/742">https://github.com/Azure/azure-sdk-for-net/issues/742</a></p>

**Comment by markcowl** [comment]
@rboorgapally Closing per the owner's request.  Please open a new issue if this behavior recurs.
