### ISSUE TITLE
[QUERY] Should CancelAutoRenewLock also cancel pumpCancellationToken?

### ISSUE THREAD

**Issue by Homulvas** [Azure/azure-sdk-for-net#7433]
Can someone explain why CancelAutoRenewLock in MessageReceivePump only cancels renewLockCancellationToken? It stops renewing the message and it is released but the cancellation token in onMessageCallback is never triggered so the message handler never knows that the message has been effectively cancelled.
Should the message handler essentially track it's own lifetime and cancel on it's own or are there ways to work around this?

**Comment by kaerm** [comment]
@Homulvas thanks for letting us know - we are going to have a look at this

**Comment by nemakam** [comment]
@Homulvas, this is by design. The token is cancelled only when the client is closed. 
There's another issue which is tracking the same feature request - https://github.com/Azure/azure-sdk-for-net/issues/12461. 
Kindly use that for tracking purposes.
