### ISSUE TITLE
[Track One] Tests for closing the Event Hub client are unstable during nightly runs

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#7435]
# Summary

A recent change introduced new tests to verify the behavior that when an `EventHubClient` is closed, any senders and receivers that were created by that client are also marked as closed.  These tests have proven to be non-deterministic during nightly test runs, failing intermittently but frequently.  

An example failure can be found in the [nightly results from August 30](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=99215&view=ms.vss-test-web.build-test-results-tab).   The failure looks like:

![image](https://user-images.githubusercontent.com/913445/64031165-dcc28c80-cb15-11e9-91fa-d27d46bf8fcf.png)

# Scope of Work

- Analyze the tests to understand the point of non-determinism and decide on an approach to stabilize for nightly runs.

- Refactor the tests as needed to ensure that the results are deterministic and consistently pass.

# Out of Scope

- Changes or refactoring in other areas.

# Success Criteria

- The tests `ClosingEventHubClientClosesSenderEntities` and `ClosingEventHubClientClosesReceiverEntities` have been refactored or removed and no longer causes intermittent, but frequent, failures during nightly runs.

- The changes did not cause regressions elsewhere; nightly test runs pass consistently and reliably with deterministic results.

**Comment by serkantkaraca** [comment]
This is fixed now.
