### ISSUE TITLE
msc: not found error

### ISSUE THREAD

**Issue by SalmaMamdouhSalem** [Azure/azure-sdk-for-net#7449]
After I install .Net library and clone the .Net device sample, there is an error is appeared which says that:
< /bin/sh: 1: mcs : not found >

So please anyone knows what is the problem?

In addition to I wanna to ask about an error appeared on command line terminal when i write dotnet --version command ,this error is appeared that "Did you mean to run dotnet SDK commands? Please install dotnet SDK from: http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409"

I couldn't understand why this error is appeared However, I already installed the Prerequisites which are mentioned in this link https://docs.microsoft.com/en-us/azure/iot-hub/quickstart-send-telemetry-dotnet .
By the way I build this sample on raspberry-pi 3 on "Raspbian OS".
Anyone could help me?? ,, thanks in advance :)

**Comment by SalmaMamdouhSalem** [comment]
@msftbot Thank you for your response and I am waiting for the solution of this issue.

**Comment by jlian** [comment]
@iluican can you assign someone to look at this?

**Comment by jlian** [comment]
Looks like it's an issue with the IoT hub client C# SDK. @SalmaMamdouhSalem can you please open your issue at https://github.com/Azure/azure-iot-sdk-csharp?
