### ISSUE TITLE
[QUERY] AzureServiceTokenProvider rewrites the PATH variable when invoking Azure CLI

### ISSUE THREAD

**Issue by mladedav** [Azure/azure-sdk-for-net#7455]
**Query/Question**
Why does the token provider rewrite the PATH? When installed outside of /usr/bin or /usr/local/bin and no path is provided in the AzureCLIPath environment variable, the token is not obtained and the problem is hard to debug. There is a comment stating that "// Default install location for Az CLI is included. If developer has installed to non-default location, the path can be specified using AzureCliPath variable." But I do not see any merit in deleting the PATH that the developer may expect to be present in the process.

The only thing I can come up with is preventing running different executable named az, but this does not protect anyone if the attacker is already able to install an executable inside a directory on the PATH or augment the variable.

Line 83 at [AzureCliAccessTokenProvider.cs](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/mgmtcommon/AppAuthentication/Azure.Services.AppAuthentication/TokenProviders/AzureCliAccessTokenProvider.cs)

***Why is this not a Bug or a feature Request?***
Because I believe there may be some rational decision as to why the current state is this way.

**Setup (please complete the following information if applicable):**
 - OS: Linux (based on source code works the same way on macOS and similar rewrite is also present for Windows)
 - Version of the Library used: 1.3.1
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by varunsh-msft** [comment]
This is just to be overly cautious about not running a malicious program. The existing path environment variable could have various different directory paths in it, and we had made a decision to not trust all of those directory paths. The decision was to favor a white list of known paths or let the developer specify one.
