### ISSUE TITLE
[BUG] BlobClient.UploadAsync calls Read rather than ReadAsync

### ISSUE THREAD

**Issue by srowan** [Azure/azure-sdk-for-net#7456]
**Describe the bug**
In the simple usage scenario for blobClient.UploadAsync:

`await blobClient.UploadAsync(stream);`

The SDK ends up calling `stream.Read` rather than `stream.ReadAsync`.   Shouldn't this be calling `stream.ReadAsync` on the input stream?

**Comment by Tewr** [comment]
Hello, I have a theory after having debugged this (origins in a discussion on https://github.com/Tewr/BlazorFileReader/issues/74 ):

The essence of my theory:

> [NonDisposingStream](
https://github.com/Azure/azure-sdk-for-net/blob/81cb4541c8dceabc339a75eb17be3dfc7a436bfe/sdk/storage/Azure.Storage.Common/src/NonDisposingStream.cs) does not override `ReadAsync`, thus, `Stream.ReadAsync` ends up calling `Read()`.
