### ISSUE TITLE
[FEATURE REQ] Release Microsoft.Azure.Services.AppAuthentication major version supporting Microsoft.IdentityModel.Clients.ActiveDirectory 5.x

### ISSUE THREAD

**Issue by Eldar1205** [Azure/azure-sdk-for-net#7457]
**Is your feature request related to a problem? Please describe.**
The nuget Microsoft.IdentityModel.Clients.ActiveDirectory was upgraded to a major version 5.x with many breaking changes - many other nugets we want to update have dependency on the 5.x major version, but due to Microsoft.Azure.Services.AppAuthentication still having dependency on the major version 4.x we are blocked from updating to 5.x without runtime errors from Microsoft.Azure.Services.AppAuthentication.

**Describe the solution you'd like**
Please release a major version of Microsoft.Azure.Services.AppAuthentication nuget which supports 5.x of Microsoft.IdentityModel.Clients.ActiveDirectory but without any breaking changes by itself, it should keep working exactly the same only with the 5.x dependency which consumers would need to ensure doesn't cause regression in another nuget still depending on a version before 5.x of Microsoft.IdentityModel.Clients.ActiveDirectory.

**Describe alternatives you've considered**
Don't think there are alternatives - we want to update other nugets to new versions that required Microsoft.IdentityModel.Clients.ActiveDirectory version 5.x, and we can't have more than one nuget version in the project without some huge refactors that will probably cause regressions of their own. Many nugets have already released a version supporting Microsoft.IdentityModel.Clients.ActiveDirectory version 5.x, the Microsoft.Azure.Services.AppAuthentication should update as well.

**Comment by EricDahlvang** [comment]
Can we get an update on this?

**Comment by EricDahlvang** [comment]
Hi @loarabia 

Can we get an update on this?

**Comment by varunsh-msft** [comment]
We should be able to release this change in the next couple of weeks.

**Comment by EricDahlvang** [comment]
Thanks @varunsh-msft

**Comment by nonik0** [comment]
@EricDahlvang @Eldar1205 We just released [AppAuth 1.4.0](https://www.nuget.org/packages/Microsoft.Azure.Services.AppAuthentication/1.4.0). In this version the ADAL dependency has been updated to 5.2, so please try it out and let us know if you have any further issues!

**Comment by EricDahlvang** [comment]
@nonik0 Thank you for the update!  Our usage is actually an intermediary dependency.  We now need Microsoft.Extensions.Configuration.AzureKeyVault to pull this new version.  I'll notify them of your release.  Thanks again.

**Comment by varunsh-msft** [comment]
Closing this issue since 1.4.0 fixes this.
