### ISSUE TITLE
Make Event Processor Client Tests more deterministic

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#7458]
# Summary

Event Processors, once initialized, demand some time before stabilizing. This happens because of the internal load balancing, which tries to distribute partition processing responsibility among Event Processors in the most balanced way.

The Event Processor Live Tests currently rely on the `WaitStabilization` method before actually performing assertions, an approach that may result in flaky behavior. This method keeps track of all active Event Processors' owned partitions, and it considers stabilization to be achieved once the partition load distribution hasn't changed after a few cycles. It gives up and throws an error if it takes more than 1 minute.

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/tests/Processor/EventProcessorClientLiveTests.cs#L68-L70

# Out of Scope

- Creation of new tests for additional coverage.

# Success Criteria

- The `EventProcessorClient` tests have been refactored and produce consistent and deterministic results.

- The existing test suite continues to produce deterministic results and pass reliably.

**Comment by jsquire** [comment]
This scope will likely be addressed as part of a community contribution to remove the load balancer and refactor it into a stand-alone offering.   Shifting this back to the backlog until those efforts are complete and will reevaluate then.

**Comment by jsquire** [comment]
Test stability was addressed as part of the recent overhaul of the `EventProcessorClient` (#10843).   This issue is no longer necessary.
