### ISSUE TITLE
[EventHubs] Event Processor exception handling tests

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#7464]
# Summary

The current set of Event Processor unit tests in Track Two does not cover exception handling. The actual expected behavior has not been decided on yet.

# Goal

Implement Event Processor's exception-handling-related tests in Track Two:
- Test `IPartitionProcessor.ProcessError` calls.
- Test proper exception handling in multiple situations (`EventHubConsumer` exceptions, `IPartitionProcessor` exceptions, retriable / non-retrieable exceptions).
- Test exception handling when `PartitionManager` throws.

**Comment by jsquire** [comment]
Closing due to the recent reworking of the design; dedicated work items will be opened for the new design.
