### ISSUE TITLE
EventHubClient.SendAsync() silently dies when running in thread

### ISSUE THREAD

**Issue by jobeland** [Azure/azure-sdk-for-net#7470]
When running `EventHubClient.SendAsync()` inside a for loop, it seems to run fine. However when it is run inside of a `Parallel.For()` loop, it seems to die silently before completing. 

Ex:
```
        static async Task Main(string[] args)
        {
            var random = new Random();
            Parallel.For(0, 1, new ParallelOptions { MaxDegreeOfParallelism = 1 }, async (i) =>
            //for (var i = 0; i < 1; i++) // This approach succeeds
            {
                var eventHubConnectionString = "<connectionString>"
                var eventHubClient = EventHubClient.CreateFromConnectionString(eventHubConnectionString);
                var eb = new EventDataBatch(1046528, "0");
                Console.WriteLine($"Starting Thread {i}");
                try
                {
                    for (var j = 0; j < 10000; j++)
                    {
                        var bytes = new byte[1024];
                        random.NextBytes(bytes);
                        using (var ed = new EventData(bytes))
                        {
                            if (!eb.TryAdd(ed))
                            {
                                await eventHubClient.SendAsync(eb);
                                eb.Dispose();
                                eb = new EventDataBatch(1046528, "0");
                            }
                            eb.TryAdd(ed);
                        }
                        Console.WriteLine($"{j}");
                    }
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                }
                Console.WriteLine($"Stopping Thread {i}");
            });
            Console.WriteLine("Done");
        }
```

"Done" is written but "Stopping Thread" is never written. It seems to fail while attempting to `SendAsync()`, but doesn't seem to throw any exceptions. The entire thread just exits. I've tried this with other `SendAsync()` options and not just EventDataBatch - they all seem to repro the issue. Running version 4.0.0 of the package on .netcore 2.2

**Comment by jsquire** [comment]
@serkantkaraca, would you mind taking a look or rerouting to the appropriate person to do so?

**Comment by serkantkaraca** [comment]
Main function call needs to wait until all parallel threads complete. Can you add Console.Readline() at the end and see if it help?

**Comment by jobeland** [comment]
@serkantkaraca Console.ReadLine() appears to allow the remainder of the thread to finish in the background. The weird behavior I'm seeing appears to be due to behavior of Parallel.For finishing when it encounters an await, and is nothing specific to this sdk. Closing this issue, sorry for the confusion!
