### ISSUE TITLE
TimeSpan in 24h format are not bind to TimeSpan in Azure

### ISSUE THREAD

**Issue by ranouf** [Azure/azure-sdk-for-net#7478]
Here is my AppSettings:
"MyTimeSpans":{
 "MyTimeSpan1":"08:00:00",
 "MyTimeSpan2":"18:00:00"
}

in local, I can read easily both, the TimeSpan format in 24h is allowed.

in Azure WebApp, MyTimeSpan1 has a value but MyTimeSpan is null.

**BUG**: TimeSpan in format 24 is not correctly binded.

**QUESTION**: Is there a workaround to fix the issue?

**Comment by isra-fel** [comment]
Sorry for late response. @AzureAppServiceCLI, @antcp could you please share some insights? Thank you.
