### ISSUE TITLE
Revisit use of `DateTimeOffset.Parse` and replace with `DateTimeOffset.ParseExact`

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#7484]
# Summary

In the Event Hubs library and tests, when interacting with some types not defined in the Event Hubs client library, the `DateTime` type is used instead of the `DateTimeOffset` type used by Event Hubs.  Currently, this is being parsed using `DateTime.Parse` against an ISO-8601 format which is producing a result that still requires `ToUniversalTime` to convert to UTC.

Instead, parsing could be done using `DateTime.ParseExact("2012-03-04T08:42:00Z", "u")` to produce a UTC value using the exact time provided.   The existing use of `Parse` should be replaced, where not associated with track one types, which will be removed before GA.

# Scope of Work

- Investigate the Event Hubs client and test code for use of `DateTime.Parse` against an ISO-8601 format that is intended to be UTC,  replacing instances not associated with track one dependencies with the equivalent `DateTime.ParseExact`. 

# Out of Scope

- Changing referenced used with track one code; this dependency will be removed before GA and does not warrant the effort to replace.

# Success Criteria

-  No instances of `DateTime.Parse` are used within the Event Hubs client or tests to produce a UTC value, outside of when interacting with track one types.

- Tests have been adjusted as needed and continue to produce consistent, deterministic results and pass.

**Comment by Azkel** [comment]
Hey guys,
I wanted to take that task, but while going through EventHub solution I didn't find any instances of `DateTime.Parse` neither in client or related tests. `DateTimeOffset.Parse` didn't return any results as well.

Should this be done within sdk\eventhub\Microsoft.Azure.EventHubs.sln solution? Because I'm not sure at this point ;)

**Comment by jsquire** [comment]
Hi @Azkel.   Thanks for reaching out and your willingness to contribute.   I hope that you'll forgive the slow turn-around, but we're just finishing out a push to our next milestone.  We're just about through that and should be more responsive in a day or so.

The intended scope for this is the `Azure.Messaging.EventHubs` library tests project.   We're currently ussing `DateTimeOffset.Parse` in quite a few places throughout the tests, for example in the [AmqpFilterTests](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/tests/Amqp/AmqpFilterTests.cs).   I'm honestly unsure if moving to `ParseExact` is worth the efforts to do so or whether our current use of `Parse` is reasonable for the level of precision that we actually need.   I'm thinking figuring out a recommendation based on that question would be where I'd start, personally.

**Comment by jsquire** [comment]
This represents a very minor improvement that would impact only test code.   As it has been open for some time and is unlikely to be a priority, going to close this out.
