### ISSUE TITLE
[Proposal] Consider moving EventProcessor to the root namespace

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#7489]
The EventProcessor is the main way for people to interact with Event Hubs. It should be easy to find and putting it in the root namespace might help with that.

**Comment by jsquire** [comment]
I'm not entirely sure that is an accurate statement.  The processor is a popular way that is used, but I'm not certain that our intent is to position it as the preferred way.

Within Track One where it exists as a separate package somewhere between a framework to be built upon and an opinionated implementation of that over blob storage.  The `EventProcessor` within the core Track Two package is intended only as a framework that can be built upon and cannot be used for real-world scenarios out-of-the-box.   There will be companion packages (with concrete implementations) or additional work needed to extend the processor for use.

The decision to put it in a dedicated namespace was to avoid a situation where it could be confused with the `EventHubConsumer`, which does offer a ready-to-use means to consume events and, I believe, a simpler "getting started" experience.

Does the additional context change your thoughts at all?

**Comment by jsquire** [comment]
@ramya-rao-a : Do we have alignment across the Event Hubs feature team on how we'd like to position the processor, with respect to the above?  Should we open that for discussion with the service team and/or the architecture board for preview 4 and beyond?

//cc: @kinelski

**Comment by ramya-rao-a** [comment]
We should open this up for discussion with both service team and the board for Preview 4

**Comment by ramya-rao-a** [comment]
I believe similar issues have been logged for Python & Java as well

**Comment by jsquire** [comment]
This will be covered as part of the latest round of design rework.   Closing this, as it no longer requires separate tracking.
