### ISSUE TITLE
[BUG]Intermittent Failure in .Net CI

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-for-net#7490]
**Describe the bug**
CI sometimes fails with 
`error : Failed to resolve SDK 'Microsoft.Build.CentralPackageVersions/2.0.36'. Package restore was successful but a package with the ID of "Microsoft.Build.CentralPackageVersions" was not installed.`

example [here](https://dev.azure.com/azure-sdk/public/_build/results?buildId=103328&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774), [here](https://dev.azure.com/azure-sdk/public/_build/results?buildId=103332&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774), and [here](https://dev.azure.com/azure-sdk/public/_build/results?buildId=101519&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774)

**To Reproduce**
Steps to reproduce the behavior: Queue a PR build

**Expected behavior**
Pipeline fails at random

**Comment by pakrym** [comment]
This is fairly frequent would be nice if someone could take a look 

cc @weshaggard @mitchdenny

**Comment by weshaggard** [comment]
@jeffkl is this an issue you guys seen reported?

**Comment by jeffkl** [comment]
I have seen this error before but haven't figured out what causes it.

The package was restored and the NuGet API was called to get the path to it which returns null.

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/Microsoft.Build.NuGetSdkResolver/NuGetSdkResolver.cs#L156

@nkolev92 do you know what could cause this?

**Comment by danieljurek** [comment]
Additional example: https://dev.azure.com/azure-sdk/public/_build/results?buildId=109787&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774

**Comment by weshaggard** [comment]
@jeffkl this looks related to https://github.com/NuGet/NuGet.Client/pull/2734 which should have fixed this. We are using the preview 7 of the .NET Core SDK so it should contain that fix, do you know if there are other potential issues?

**Comment by jeffkl** [comment]
Yes it sort of does except that its intermittent.  I would imagine a casing bug would happen 100% of the time.  Did the workaround in #7490 resolve it completely?  If so, then casing would definitely be a problem still.

**Comment by nkolev92** [comment]
I forgot to reply to this, when I dug into it last. 
It's very peculiar, I looked into potential issues with the parsing/the selection, and I didn't see anything obvious :/

**Comment by pakrym** [comment]
@weshaggard @chidozieononiwu do you have thoughts about next steps we can take to try and fix this?

**Comment by weshaggard** [comment]
@pakrym do you know if we have seen this since @chidozieononiwu merged his workaround in #7647? I'd like to see if that helps this problem and if not we will try to figure out other options.

**Comment by chidozieononiwu** [comment]
The workaround did not solve the problem. The bug still exists as it occurred yesterday [here](https://dev.azure.com/azure-sdk/public/_build/results?buildId=112815&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774)

**Comment by weshaggard** [comment]
I'm fixing this issue in https://github.com/Azure/azure-sdk-for-net/pull/7705 by eliminating the nuget resolver from our usage and directly checking in the props/targets file from the central package version nupkg. If the nuget resolver issue gets fixed we can later consider using the sdk import again.
