### ISSUE TITLE
Azure App Configuration SDK: Support data plane API version

### ISSUE THREAD

**Issue by x9xu** [Azure/azure-sdk-for-net#7502]
As required by Azure REST API Guidelines, we are adding **explicit** API Versioning. All requests **MUST** provide explicit API Version as query string parameter,

for example:

     "https://example.azconfig.io/kv?api-version=1.0"

User should be able to specify the Api version in through configuration properties.

**Comment by annelo-msft** [comment]
Duplicate of https://github.com/Azure/azure-sdk-for-net/issues/6944

**Comment by annelo-msft** [comment]
Implemented in #7619
