### ISSUE TITLE
[FEATURE REQ] Enable passing timespan as range for ApplicationInsightsDataClient methods

### ISSUE THREAD

**Issue by AndreMantas** [Azure/azure-sdk-for-net#7506]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to use [ApplicationInsightsDataClient](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.applicationinsights.applicationinsightsdataclient?view=azure-dotnet) methods to get data between a timespan range.

**Describe the solution you'd like**
According to the [API Docs](https://dev.applicationinsights.io/documentation/Using-the-API/Metrics):
> **Specify the timespan**
> The Application Insights APIs specify time using ISO 8601 formats. A timespan, or time range, for a query can be specified as
> 
> 1. the length of time before now (e.g P2D for the last 2 days, PT12H for the last 12 hours, etc.), or
> 2. as a time range specified by a start and end time where each time has the format YYYY-MM-DDThh:mm:ss.sssZ and these are combined to form a time range as 2016-03-01T13:00:00Z/20016-03-03T15:30:00Z, or
> 3. or as a start time and a length of time after that, e.g. 2016-03-01/P1D which specifies the time range covering the entire day March 1 UTC.

Currently only option 1. is possible to use. 
Options 2 and 3 are simply not possible because the SDK methods only receive one TimeSpan parameter. This parameter is encoded it into the query parameter as
`timespan=<iso-format-timespan>`
so there is never a possibility of having the query parameter as
`timespan=<iso-format-timespan-1>/<iso-format-timespan-2>`

Which is possible in the API Explorer:

![image](https://user-images.githubusercontent.com/7627975/64413684-ddb16c00-d089-11e9-813c-84a0320e25dd.png)

**Describe alternatives you've considered**
- Using QueryWithHttpMessagesAsync but it also receives a timespan which is used as query parameter without supporting ranges
- Build the url and executing the GET request manually: defeats the purpose of the SDK

**Additional context**
Using latest SDK version: Microsoft.Azure.ApplicationInsights 0.9.0-preview

Is it possible to issue a PR? I'm not seeing the methods in the master branch (https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/applicationinsights/Microsoft.Azure.ApplicationInsights/src)

**Information Checklist**
- [X] Description Added
- [X] Expected solution specified

**Comment by kaerm** [comment]
Thanks @AndreMantas for reporting this - routing this for the right team to take a look

**Comment by alongafni** [comment]
Hi @AndreMantas ,
Sorry for the late response.
I checked and I am able to provide URL-encoded ranges in the timespan parameter, see [this query](https://api.int.loganalytics.io/v1/workspaces/DEMO_WORKSPACE/query?csl=union%20*%20|%20limit%201&api_key=DEMO_KEY&timespan=2020-03-01T13%3A00%3A00Z%2F2020-03-03T15%3A30%3A00Z) for example.

I didn't use the ApplicationInsightsDataClient class, but seems like it only encodes the timespan parameter, so it should behave the same.

However, I did find 2 typos in the examples you provided, maybe they caused your attempts to fail?
In #2 using fromDate/toDate ranges, your toDate has a typo - 20016 instead of 2016,
and in #3 using fromDate/toPeriod example, the period should be PT1D instead of P1D.

Can you please try again and let me know if you still see the issue?

**Comment by AlexGhiondea** [comment]
@AndreMantas could you take a look at @alongafni's reply?

**Comment by AndreMantas** [comment]
@alongafni the 2 typos you mentioned is when i'm quoting the API Docs: https://dev.applicationinsights.io/documentation/Using-the-API/Metrics

It was either that way when i copied from there or somehow i added the typos.

Either way it doesn't matter because im not using those values...

My issue is specifically with the **ApplicationInsightsDataClient**: https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.applicationinsights.applicationinsightsdataclient?view=azure-dotnet#methods

I could obviously create a raw request in c# and add the query string parameters as i wanted but that is not the point here.

What i am/was reporting is the lack of possibility to pass a timespan range to the methods of this class so that it encodes them. As i said:

> Options 2 and 3 are simply not possible because the SDK methods only receive one TimeSpan parameter. This parameter is encoded it into the query parameter as
> timespan=\<iso-format-timespan>
> so there is never a possibility of having the query parameter as
> timespan=\<iso-format-timespan-1>/\<iso-format-timespan-2>

**Comment by alongafni** [comment]
@AndreMantas Sorry, I understand now what you meant in the original post. I will take it from here and keep you updated with any progress.

**Comment by alongafni** [comment]
@AndreMantas I did some digging, and apparently the package you referenced is Deprecated (even though it is not marked as such, sorry about that) - https://www.nuget.org/packages/Microsoft.Azure.ApplicationInsights/

The package that you should be using is this - https://www.nuget.org/packages/Microsoft.Azure.ApplicationInsights.Query/0.9.0-preview
Docs are here - https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.applicationinsights.query.applicationinsightsdataclient?view=azure-dotnet-preview

In the new package, the timespan parameter is modeled as string which allows providing any of the 3 time ranges you describe, and I verified I can use option #3 with it:

var task = client.Events.GetCustomEventsWithHttpMessagesAsync(appId, "2020-05-01/2020-05-02");
task.Wait();
var results = task.Result;

As you may have noticed, the methods and parameters are organized a bit differently, so you need to do something like this:
client.Events.GetCustomEventsWithHttpMessagesAsync(applicationId, ...);

Please let me know if you have additional questions or concerns.
Alon
