### ISSUE TITLE
[EventHubs] Event Processor's global exception handler

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#7537]
# Summary

The current `EventProcessor` implementation swallows up unhandled exceptions instead of reporting to the user about them.

https://github.com/Azure/azure-sdk-for-net/blob/de8e950ecf5d04e29f2383511f63a096724f2522/sdk/eventhub/Azure.Messaging.EventHubs/src/Processor/EventProcessor.cs#L246-L249

The same issue can be found in `PartitionPump` as well. The pieces of code that need attention are marked with a `TODO` comment, so they can be easily found.

# Goal

Implement an exception callback so users can handle thrown exceptions by themselves.

**Comment by jsquire** [comment]
Closing due to the recent reworking of the design; dedicated work items will be opened for the new design.
