### ISSUE TITLE
Decide on pattern for UriBuilder types and derive custom UriBuilders from RequestUriBuilder

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#7539]
Storage is adding its own BlobUriBuilder/FileUriBuilder/QueueUriBuilder types that have a lot of implementation overlap with Azure.Core's RequestUriBuilder.  We should look at refactoring RequestUriBuilder so we can derive from it and come up with a consistent pattern across client libraries for different services.

**Comment by tg-msft** [comment]
Assigning to @pakrym if we want to do this for Preview 4

**Comment by pakrym** [comment]
I looked at this and it doesn't look feasible. Having both AppendQuery/AppendPath methods and strongly typed properties do not interoperate very well.
