### ISSUE TITLE
[EventHubs] Partition Manager's methods should support Cancellation Token

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#7540]
# Summary

The class `PartitionManager` currently contains 3 `abstract` methods: `ListOwnershipAsync`, `ClaimOwnershipAsync` and `UpdateCheckpointAsync`. None of them support the use of `CancellationToken`.

https://github.com/Azure/azure-sdk-for-net/blob/2bbba0efbd5d19c0742d363d55954bcfa4d68e91/sdk/eventhub/Azure.Messaging.EventHubs/src/Processor/PartitionManager.cs#L30-L31

# Goal

Add a `CancellationToken` parameter in the three aforementioned methods. It's also necessary to:
 - Update `InMemoryPartitionManager` concrete subclass. Since it's a synchronous non-blocking implementation, it's likely that the `CancellationToken` won't be used.
 - Update the blob storage `PartitionManager` concrete subclass. This one accesses the storage Azure service, so it should make proper use of the tokens.

**Comment by jsquire** [comment]
Closing due to the recent reworking of the design; dedicated work items will be opened for the new design.
