### ISSUE TITLE
Event Processor Client Tests: some live tests can be mocked

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#7541]
# Summary

Live tests incur costs to whoever runs them because they make use of Azure resources to work. Some of the live tests we have for `EventProcessor` could be mocked in order to prevent unnecessary costs.

https://github.com/Azure/azure-sdk-for-net/blob/2bbba0efbd5d19c0742d363d55954bcfa4d68e91/sdk/eventhub/Azure.Messaging.EventHubs/tests/Processor/EventProcessorLiveTests.cs#L40-L41

For instance, `StartAsyncCallsPartitionProcessorInitializeAsync` shouldn't need to connect to the service in order to assert the initialize method is being called. We are not testing actual received information.

# Scope of Work

 - Analyze the current live tests and determine which ones could be mocked.

 - Make the necessary changes to the `EventProcessor` infrastructure so we and users can mock stuff.

 - Update the mockable live tests and move them to the `EventProcessorTests` file.

# Success Criteria

- Live tests for the `EventProcessorClient` have been reviewed and any tests without a true need for Azure resources have been reclassified.

- The existing test suite continues to produce deterministic results and pass reliably.

**Comment by jsquire** [comment]
With the overhaul of the `EventProcessorClient`, tests were analyzed and adjusted.  Tests that were able to be converted to unit tests have been; no known work is outstanding.
