### ISSUE TITLE
'SetConfiguration' functionality of 'NetworkManagementClient.Networks'  has stopped working.

### ISSUE THREAD

**Issue by shubhangi-p** [Azure/azure-sdk-for-net#755]
'SetConfiguration' functionality of 'NetworkManagementClient.Networks' (azure-sdk-for-net / src / NetworkManagement / Generated / NetworkOperations.cs) has stopped working.

SetConfiguration functionality was working perfect with 'Microsoft.WindowsAzure.Management.Network version 2.1.2'. New version of dll throwing the following exception.

Exception Occurred :  of type Microsoft.WindowsAzure.CloudException : InvalidContentType: Invalid ContentType header specified for the request.    at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.WindowsAzure.NetworkOperationsExtensions.SetConfiguration(INetworkOperations operations, NetworkSetConfigurationParameters parameters)

Kindly fix this issue as soon as possible.<p><a href="https://github.com/Azure/azure-sdk-for-net/issues/755">https://github.com/Azure/azure-sdk-for-net/issues/755</a></p>

**Comment by matt-deboer** [comment]
Hi All,
It seems that this issue still exists in the current version of the API.

**Comment by matt-deboer** [comment]
Nevermind; just realized that this particular operation wants 'text/plain' for the xml document.

**Comment by shahabhijeet** [comment]
please reopen if this is still an issue.
