### ISSUE TITLE
Is AzureServiceTokenProvider.GetAccessTokenAsync() thread safe?

### ISSUE THREAD

**Issue by SaurabhSharma-MSFT** [Azure/azure-sdk-for-net#7574]
Is AzureServiceTokenProvider.GetAccessTokenAsync() thread safe?

**Comment by Rookian** [comment]
Unfortunately, `Azure.Identity` seems not to be thread safe. Are there attempts to change that?

**Comment by allenjzhang** [comment]
@nonik0 , Nick, can you help answer this question? BTW, this project should not be under mgmtcommon. Do you have your RP folder under SDK?

**Comment by jsquire** [comment]
Since this was filed the AppAuthentication library has been formally retired and is no longer maintained.   Closing this out.
