### ISSUE TITLE
[Event Hubs] Updates to PartitionProcessor post API review

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-net#7579]
Below are the actionable items from the feedback on the PartitionProcessor in the API review

- Move away from current implementation which has a base class that implements all 4 methods that do nothing but log to an abstract class. Customer should be forced to inherit this class and implement the "ProcessEvents" method. Us implementing "ProcessEvents" such that it only logs doesnt help much in the long run.
- Move the method to update checkpoint from partition context to the PartitionProcessor. This should be implemented by the abstract class.
- Consider removing PartitionContext class by setting partitionId, eventHubName & consumer group name as properties on the class either by the constructor or the initialize method.
- CloseReason should have only 2 reasons: Shutdown & OwnershipLost
    - The intention was to allow the user to know whether or not they should bother checkpointing. If anything other that shutdown, there is no way the library can support checkpointing. Keeping this in mind, there isnt any reason why the customer might want to know any 3rd reason. An EventHubException will be passed to "ProcessErrors"
     - There isnt much the user can do knowing that the Event Processor stopped processing a partition because of underlying exception from Event Hub or an error from the PartitionManager

**Comment by jsquire** [comment]
Closing this issue due to the recent reworking of the design; new issues will be opened for the efforts needed.
