### ISSUE TITLE
[Storage] Performance regression in BlobClient.DownloadAsync()

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-net#7597]
PR #7525 caused a significant performance regression in BlobClient.DownloadAsync():

| Build                 | RPS   |
|-----------------------|-------|
| 12.0.0-dev.20190908.1 | 8,300 |
| 12.0.0-dev.20190911.1 | 100   |

CC: @pakrym

**Comment by pakrym** [comment]
The reason the regression happened is that it's more expensive to leave a response stream unread when it's not buffered because HttpClient can't reuse the connection. I leave @tg-msft to decide if it's a big deal.

**Comment by kurtzeborn** [comment]
There's no user scenario for downloading without using the response stream, so we're okay with performance being worse in that case.
