### ISSUE TITLE
Intermittent build failure

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-net#7604]
We've seen build failures crop up a couple times citing an unsuccessful package restore. 

```
D:\a\1\SourceDirWith49CharsLengthTestForLongPaths\eng\Directory.Build.Data.targets : error : Failed to resolve SDK 'Microsoft.Build.CentralPackageVersions/2.0.36'. Package restore was successful but a package with the ID of "Microsoft.Build.CentralPackageVersions" was not installed.
```

https://dev.azure.com/azure-sdk/public/_build/results?buildId=109787&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774

**Comment by pakrym** [comment]
Dup of https://github.com/Azure/azure-sdk-for-net/issues/7490
