### ISSUE TITLE
Add support for retry of server call with retry header using IRetryPolicy

### ISSUE THREAD

**Issue by abhilasharora** [Azure/azure-sdk-for-net#7605]
We plan to update AzconfigClient to support exponential backoff retry for retryable failures encountered by the server based on the retry-after-ms header returned in the response. This issue tracks the work required to port this behavior to the official SDK.

The changes can be found in the following method in class `AzconfigMessageInvoker`.

`public async Task<HttpResponseMessage> SendAsync(Func<HttpRequestMessage> requester, CancellationToken cancellationToken)`

Labels : AzConfig, Client

**Comment by pakrym** [comment]
We have this support implemented. See https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/Pipeline/RetryPolicy.cs#L148

**Comment by abhilasharora** [comment]
> We have this support implemented. See https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/Pipeline/RetryPolicy.cs#L148

This issue is to track the exponential backoff retry support in DotNet SDK for Azure App Configuration. The correct label for it is Azconfig and the code is located under https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/appconfiguration.

**Comment by pakrym** [comment]
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/appconfiguration is using the Azure.Core pipeline where default retry policy implementation already has support for server-based retry.

**Comment by abhilasharora** [comment]
@pakrym Thanks for the clarification. This item is to update the logic of AzconfigClient to use exponential backoff retry strategy with randomized delay. I submitted this change to our Team's private repository today, and the official SDK needs to be updated to use this new approach.

Pull request that needs to be incorporated in official SDK
https://github.com/Azure/Azconfig-DotnetSdk/pull/85

**Comment by pakrym** [comment]
cc @annelo-msft

**Comment by pakrym** [comment]
I think azure core pipeline supports everything described by this issue and is used in AppConfig SDK. Please reopen if I missed something.
