### ISSUE TITLE
[BUG] Links in XML docs are broken on reference documentation

### ISSUE THREAD

**Issue by loic-sharma** [Azure/azure-sdk-for-net#7625]
**Describe the bug**
The SDK uses `<see href=""/>` for links; these are not properly rendered on the reference documentation. For example, `BlobContainerClient.Create`:

* Source code: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/BlobContainerClient.cs#L213
* Generated reference documentation: https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobcontainerclient.create?view=azure-dotnet-preview#Azure_Storage_Blobs_BlobContainerClient_Create_System_Nullable_Azure_Storage_Blobs_Models_PublicAccessType__System_Collections_Generic_IDictionary_System_String_System_String__System_Threading_CancellationToken_

**Screenshots**

![image](https://user-images.githubusercontent.com/737941/64926884-0e934e80-d7b8-11e9-8fd5-6f1694892bed.png)

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by seanmcc-msft** [comment]
Hi @loic-sharma,

Thanks for reporting this, we'll fix this issue before GA.

**Comment by chidozieononiwu** [comment]
Fixed with #8456
