### ISSUE TITLE
Get region of CloudStorageAccount

### ISSUE THREAD

**Issue by qub1n** [Azure/azure-sdk-for-net#7626]
**Is your feature request related to a problem? Please describe.**
I would like to get Region from CloudStorageAccount created from SAS link.

I would like to warn user that some network feed might applied if this storage is in the different region then a client. But there is no API for it.

**Describe the solution you'd like**
Discuss with Azure team and add a region property to the REST API first, then to the SDK. Actually there are already storage properties like SKU and storage type, so why not to list region as well?

I would like to make this code working.

CloudStorageAccount storage = CloudStorageAccount.Parse(
"DefaultEndpointsProtocol=https;AccountName=xyz;AccountKey=1234...");
var client = storage.CreateCloudBlobClient();
AccountProperties props = client.GetAccountProperties();
Console.WriteLine($"Region = {props.Region}");

**Describe alternatives you've considered**
Let user to enter region manually during entering SAS link to our App. (annoying, error prone).

**Comment by yaohaizh** [comment]
This should be data plane API.

**Comment by zhusijia26** [comment]
@amishra-dev please provide comment or feature ETA on the request.

**Comment by seanmcc-msft** [comment]
This would require backend API changes that are not currently on the road map.

**Comment by qub1n** [comment]
Guys, I believe that first we should evaluate if the idea itself is good for user.

And then you can decide to postpone it (because of the roadmap) or reconsider your API roadmap/design if it cannot handle such simple change.

**Comment by amishra-dev** [comment]
Hi @qub1n, 
The question is not about "simple change", its about where do we enable our developers to do more with our given set of resources. 
This information is available in the management plane sdk(https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.storage.models.storageaccount?view=azure-dotnet)

In the ideal world, sure we can add all management functions into the data plane API as well, but given that we already have a way for our developers to get this functionality, i am wondering does it make sense in to do it?

**Comment by qub1n** [comment]
Unfortunately, Management Functions can be called only in a certain context. If you have only an exported Key, you cannot detect the region.

In our App, we would like to add the possibility to Add Storage Account by exported Key. But there is no simple way how to detect region in this case. Then I need to deploy VM to the correct region to be able to do cost-effective operation with the storage account, otherwise, my bill could be quite high.

The only way how to detect region is to ask user which is entering a storage account key or deploy Azure functions/VMs to all regions and measure the shortest ping to CloudStorageAccount which is a quite clunky solution.

**Comment by amishra-dev** [comment]
Thanks for the detailed explanation @qub1n, let me talk to my friends in the management plane sdk team and the service teams and see if we have a solution for your case. I will keep you updated.
