### ISSUE TITLE
Add CloudStorageAccount GetAccountProperties

### ISSUE THREAD

**Issue by qub1n** [Azure/azure-sdk-for-net#7627]
**Is your feature request related to a problem? Please describe.**

GetAccountProperties method of CloudStorageAccount is missing in azure-libraries-for-net (using Microsoft.WindowsAzure.Storage.Blob), but it is included and working in the nuget Microsoft.Azure.Storage.Blob.

**Describe the solution you'd like**
Add this method as well.

I would like to have the same working code like bellow:

using Microsoft.Azure.Storage;
using System;
using Microsoft.WindowsAzure.Storage.Blob;
using System.Threading.Tasks;
using Microsoft.WindowsAzure.Storage.Shared.Protocol;

namespace StorageTest
{
    class Program
    {
        static async Task Main(string[] args)
        {
            CloudStorageAccount storage = CloudStorageAccount.Parse(
                <SNIP>);
            var client = storage.CreateCloudBlobClient();
            AccountProperties props = client.GetAccountProperties();
            Console.WriteLine($"AccountKind = {props.AccountKind}");
            Console.WriteLine($"SkuName = {props.SkuName}");
        }
    }
}

**Describe alternatives you've considered**
reference nuget Microsoft.Azure.Storage.Blob instead and replace namespace Microsoft.WindowsAzure.Storage.Blob by Microsoft.Azure.Storage.Blob

**Comment by loarabia** [comment]
Hi @qub1n thanks for reporting the issue. Note you had a access token in the code snippet you copied. I edited it out but it is likely in the other repo and probably still discoverable. I would recommend double checking and changing the token.

**Comment by seanmcc-msft** [comment]
Hi @qub1n,

We actually already have a GetAccountInfo API on BlobServiceClient in the Azure.Storage.Blobs namespace:

```csharp
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Models;
using System;
using System.Threading.Tasks;

namespace ConsoleApp9
{
    class Program
    {
        private static readonly string connectionString = "Your connection string";

        static async Task Main(string[] args)
        {
            BlobServiceClient blobServiceClient = new BlobServiceClient(connectionString);
            AccountInfo accountInfo = await blobServiceClient.GetAccountInfoAsync();

            Console.WriteLine($"AccountKind = {accountInfo.AccountKind}");
            Console.WriteLine($"SkuName = {accountInfo.SkuName}");
        }
    }
}
```

Let use know if you have any further questions.
