### ISSUE TITLE
VM Scaleset vs Azure Batch

### ISSUE THREAD

**Issue by balukantu** [Azure/azure-sdk-for-net#7628]
VM scale set can be used to create multiple VM's based on the business requirement and, Also, Azure batch is used to execute a job in multiple VM's.

What is the exact difference between Azure Batch and VM Scale set?

**Comment by bgklein** [comment]
Please see Vikas and Fred's response at https://social.msdn.microsoft.com/Forums/en-US/88097470-80aa-4b2d-b24a-c0b747d31f29/vm-scaleset-vs-azure-batch?forum=azurebatch
