### ISSUE TITLE
[BUG] net - core -ci times out on linux test

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#7634]
Linux pipeline checks are timing out:

https://dev.azure.com/azure-sdk/public/_build/results?buildId=111004&view=logs&j=ad07b744-5a1a-5d54-7693-fcb02e666633&t=24c7afb3-2fe1-5e71-64cc-9945982a3981&l=959 #

**Comment by kurtzeborn** [comment]
@chidozieononiwu, you should take a quick look at this, but @weshaggard and I are suspicious that this is because of some long running tests and if that's the case, this should go back to the .Net client team for further investigation.

**Comment by kurtzeborn** [comment]
Assigning this and #8618  to you @jsquire for follow up. If the redesign makes these go away, please close.

**Comment by jsquire** [comment]
Closing this as a duplicate of #8618.  Both appear to reference the same issue with same suspected root cause.
