### ISSUE TITLE
[BUG][Storage][Recordings] x-ms-copy-source request header is being URL-encoded in test recordings

### ISSUE THREAD

**Issue by seanmcc-msft** [Azure/azure-sdk-for-net#7645]
- FileClient.PutRangeFromUrl() has a x-ms-copy-source header to specify the source URL
- This header is sent non-URL-encoded, but it is URL-encoded in the test recordings, causing the recorded test to fail.

**Comment by jsquire** [comment]
Closing; according to the linked PR, this issue was resolved by those changes.
