### ISSUE TITLE
ServiceFabricManagementClient for connecting to Secure Cluster

### ISSUE THREAD

**Issue by javaadpatel** [Azure/azure-sdk-for-net#7650]
How do you use the `ServiceFabricManagementClient` class to connect to a secure service fabric cluster? The only documentation I have found is this:
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-connect-to-secure-cluster
but this documentation is for FabricClient? 

Which class should one use for managing a service fabric cluster?

**Comment by peterpogorski** [comment]
Hi @javaadpatel,

What operations are you trying to perform on the cluster?

To perform cluster operations from an application on the cluster. FabricClient will allow you to manage Service Fabric services and other entities on a cluster. Please see the FabricClient documentation for more details: https://docs.microsoft.com/en-us/dotnet/api/system.fabric.fabricclient?view=azure-dotnet

If you are trying to connect to a cluster to deploy an application or modify a cluster setting, you can use either the PowerShell or CLI modules as seen in https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-connect-to-secure-cluster. This documentation is not for the FabricClient class. 

Please let me know if you need any futher information.

**Comment by javaadpatel** [comment]
hi @peterpogorski ,

I am trying to list all the applications in the cluster, deploy new applications into the cluster and upgrade existing applications in the cluster.

I am currently using the powershell commands to do these actions but when i saw the ServiceFabricManagementClient class i thought that it was a way to do these actions using c#. because the methods on it like ` serviceFabricClient.Applications.ListWithHttpMessagesAsync` seemed like that was its purpose, is that incorrect? 

I would ideally like to move away from the powershell scripting.

**Comment by peterpogorski** [comment]
You can definitely complete those operations outside of PowerShell by using the FabricClient.ApplicationManagementClient class. Find more information here: https://docs.microsoft.com/en-us/dotnet/api/system.fabric.fabricclient.applicationmanagementclient?view=azure-dotnet 

You can also complete these opeartions using the Service Fabric REST APIs which you can read more about here: https://docs.microsoft.com/en-us/rest/api/servicefabric/
