### ISSUE TITLE
Update CryptographyClient to use Memory<byte> instead of byte[]

### ISSUE THREAD

**Issue by schaabs** [Azure/azure-sdk-for-net#7656]
- Investigate the impact of the change
- Update implementation

**Comment by heaths** [comment]
Both `Memory<T>` and `Span<T>` represents a view on existing data. `ICryptoTransform` accepts only a `byte[]` and to get an array from either aforementioned class, they have to allocate a new array. There'd be no benefit to accepting either as input. Returning a `Memory<byte>` would seemingly offer no benefit either as crypto APIs will still allocate a `byte[]` and return it, and we'd simply wrap it. In fact, round-tripping these structures would result in more allocation.

**Comment by heaths** [comment]
We can use [MemoryMarshal.TryGetArray](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.memorymarshal.trygetarray?view=netstandard-2.1#System_Runtime_InteropServices_MemoryMarshal_TryGetArray__1_System_ReadOnlyMemory___0__System_ArraySegment___0___) and fall back to allocating an array as needed, but we will punt this to the backlog.

**Comment by heaths** [comment]
Closing for now with no customer demand. If it comes up, we can add overloads later but the `byte[]` output from the underlying APIs will still be a problem that needs to be solved in an x-plat manner.
