### ISSUE TITLE
Live tests should create a new Key Vault each time if environment variable is unset

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#7663]
Live tests often fail because of deleted, non-purged keys that get left behind. To avoid this problem, we should create a new Key Vault in global test setup each time and delete it when done if the `AZURE_KEYVAULT_URL` environment variable is unset.

This should help live test reliability.

**Comment by heaths** [comment]
Adding KeyVault label back, even though this is cross-service.

**Comment by heaths** [comment]
This is mostly fixed by #9127.

**Comment by heaths** [comment]
@danieljurek should we generalize this as part of our original MQ work? There was some discussion about it, but I'm not finding any open issues in this or azure-sdk repos.

**Comment by pakrym** [comment]
Do we even want to do this?

**Comment by heaths** [comment]
At one point we did. I did find #9062 that is tracking this. Some service teams felt pretty strongly this should "just work" when running tests.

**Comment by heaths** [comment]
This has been resolved with our new test-resources.json solution where live test resources are created and destroyed for each live run.
