### ISSUE TITLE
[EventHubs] PartitionId should be number, not string

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-net#7664]
As per feedback from the Service team, it is guaranteed that partition ids with be numbers starting from 0 until n-1 where n is the number of partitions. With this in mind, below changes would be needed in the Event Hubs library

- The result from `getProperties()` should contain partition count instead of the partition Ids
- The method `getPartitionIds()` no longer needed as users can start from 0 till n-1 on their own
- All samples & Readme to be updated that use `getPartitionIds()`
- All apis that take partitionId to be updated with the type change.

cc @jsquire

**Comment by jsquire** [comment]
This is covered in [#7417](https://github.com/Azure/azure-sdk-for-net/issues/7417).   Closing this as a duplicate and liking it there to capture the additional conext.

**Comment by ramya-rao-a** [comment]
Ah! I didn't see any issues for this topic assigned to the epic, so I created one. Please update #7417 to be under the epic #7562

**Comment by jsquire** [comment]
I'm not comfortable committing to that in the timeline for preview 4; resource time is already allocated over 100%.   I'm happy to prioritize it next up in the queue and make best efforts but, while low effort, there's a large surface area that is impacted by this change.
