### ISSUE TITLE
Consider adding ClientRequestId to exceptions thrown from the pipeline

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#7670]
So when task cancellation exception  gets thrown, we attach some meaningful information to it.

**Comment by JoshLove-msft** [comment]
This is mostly covered by using distributed tracing. The request Id would be added to the HTTP span here - https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Pipeline/Internal/RequestActivityPolicy.cs#L71
