### ISSUE TITLE
Inconsistency between "crv", "curve", and "curveName" in code vs. swagger

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#7684]
Similar to #7683 the swagger states to use "crv" while the x-ms-client-name is "curve", but in code we write "curveName".

**Comment by heaths** [comment]
The service is returning "crv":

```json
      "ResponseBody": {
        "key": {
          "kid": "https:\u002f\u002fheathskv.vault.azure.net\u002fkeys\u002f1930028727\u002fb968cab3e06344088a86c23e01f34bb8",
          "kty": "EC",
          "key_ops": [
            "sign",
            "verify"
          ],
          "crv": "P-256",
          "x": "NVlwYx3dC5c6OiOnj2_FA4P8OdMeyLZlIUMLfeBC9ig",
          "y": "Gg1QouOH6HslHTQ66ho9syd49V_VbTGjv-1a-R_1WI0"
        },
        "attributes": {
          "enabled": true,
          "created": 1568855698,
          "updated": 1568855698,
          "recoveryLevel": "Recoverable\u002bPurgeable"
        }
      }
```

**Comment by Petermarcu** [comment]
What are other languages doing? Might be good to look at a couple others and we can have an even broader conversation.

**Comment by Petermarcu** [comment]
@JonathanGiles @johanste @bterlson

**Comment by johanste** [comment]
For Python:

The parameter is `curve` ([docs](http://azure.github.io/azure-sdk-for-python/ref/azure.keyvault.keys.html#azure.keyvault.keys.client.KeyClient.create_key))

The low-level JsonWebKey uses the attribute name `crv` ([docs](http://azure.github.io/azure-sdk-for-python/ref/azure.keyvault.keys.html#azure.keyvault.keys.models.JsonWebKey))

The "helper"/enum type for curve names is `KeyCurveName` ([docs](http://azure.github.io/azure-sdk-for-python/ref/azure.keyvault.keys.html#azure.keyvault.keys.enums.KeyCurveName))

**Comment by johanste** [comment]
With regards to swagger and `x-ms-client-name`, given that the purpose of `x-ms-client-name` is to give a (strong) hint to code generators (modulo whatever naming conventions apply to the target language - e.g. pascal case, camel case, snake case etc.) as to what the canonical name is supposed to be for the property/type, it would probably be a reasonable thing for us to match it in our libraries. If we feel like the annotation is wrong in swagger, we could change it there (as long as we are mindful of any breaking changes for autogenerated libraries - e.g. Go)

**Comment by heaths** [comment]
I already fixed it in our code, but had opened this to make sure we validate across the languages (was focused on fixing other old-test issues). There may be a problem in the auto-gen code, since at least in .NET it seems the x-ms-client-name was used not only for the member name, but the JSON key as well. A particular method didn't have coverage which is probably why this was missed, and I'll be adding coverage.

**Comment by johanste** [comment]
Yeah, using `x-ms-client-name` for the json key name is not correct...

**Comment by heaths** [comment]
There's a few discrepencies bewteen languages on this we'll have to iron out, e.g. .NET uses `CurveName` for the property (now) but other languages that do expose it (not all do) use `curve` (correct) or `crv` (incorrect).
