### ISSUE TITLE
Consumer EventData does not work if system time isn't UTC

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-net#7708]
Link : https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/README.md#consume-events-using-an-event-processor

Code snippet:
![image](https://user-images.githubusercontent.com/51379715/65345240-a2856180-db8e-11e9-9a4e-f8c14ed28577.png)

Error Details : Will throw an exception while perform this code.
![image](https://user-images.githubusercontent.com/51379715/65345257-a913d900-db8e-11e9-8417-f1dac4f64b18.png)
Consumes Event data failed while system time is not UTC time, it works if set the system time as UTC.

Migrated from: https://github.com/Azure/azure-sdk-for-java/issues/5448

**Comment by jsquire** [comment]
I've completed investigation and was able to reproduce this.   A fix has been made in the linked PR and will be included in the next release.

**Comment by jsquire** [comment]
Closing as resolved, with the associated PR merged.
