### ISSUE TITLE
Method of creating a HttpPipeline based on another instance

### ISSUE THREAD

**Issue by jaschrep-msft** [Azure/azure-sdk-for-net#7713]
**Is your feature request related to a problem? Please describe.**
It is difficult to create a pipeline based on another pipeline. One would have to save a `ClientOptions` instance and keep it alongside the `HttpPipeline`, but even then the `ClientOptions` is only additive in its policy collection. And if you cannot reasonably have access to said `ClientOptions` instance then it is not even possible to know what your starting point is.

**Describe the solution you'd like**
Have `HttpPipeline` implement `IEnumerable<HttpPipelinePolicy>`. This would keep the pipeline structure immutable. So long as individual policies are also immutable (already expected), the pipeline would remain immutable in its entirety.

**Describe alternatives you've considered**
A method of getting a `ClientOptions` instance from a `HttpPipeline`. This would allow the actual observation to be marked `internal` should that be important, but accurately creating a `ClientOptions` instance from a pipeline would likely be difficult without the pipeline maintaining any sort of information about how it was created, and impossible if the pipeline were 100% custom built from scratch.

**Additional context**
This feature would allow specialized clients (e.g. `EncryptedBlockBlobClient`) that require a special policy in their pipeline to be created from a "parent" client (e.g. a `BlobContainerClient`). Currently, these navigation methods pass the pipeline to the new client directly, and so their arbitrary pipeline cannot be replicated with an additional policy tacked on to the front end, like the specialized client requires.

This does not stop these clients from being constructed as desired, but it does stop them from using these client navigation methods that are supported with every other client.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by pakrym** [comment]
I think we've implemented the encrypted storage client without this feature. Please reopen if still needed.
