### ISSUE TITLE
[BUG] Error converting value "ContainerInsights" to type 'LogAnalyticsLogType' (ContainerGroup)

### ISSUE THREAD

**Issue by sabvente** [Azure/azure-sdk-for-net#7714]
**Describe the bug**
The SDK is unable to deserialize the container list response. The last working nuget version is 1.22.2

***Exception or Stack Trace***
One or more errors occurred. (Unable to deserialize the response.)
Unable to deserialize the response.
Error converting value "ContainerInsights" to type 'Microsoft.Azure.Management.ContainerInstance.Fluent.Models.LogAnalyticsLogType'. Path 'properties.diagnostics.logAnalytics.logType', line 1, position 1135.
Could not cast or convert from System.String to Microsoft.Azure.Management.ContainerInstance.Fluent.Models.LogAnalyticsLogType.

Relevant part of the JSON response:
```
{
  "value": [
    {
      "properties": {
        "diagnostics": {
          "logAnalytics": {
            "logType": "ContainerInsights"
          }
        }
      }
    }
  ]
}
```

***Code Snippet***
`var cgs = azure.ContainerGroups.List().ToArray()`

**Expected behavior**
Be able to receive the response.

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : VS2017
 - Version of the Library used: Microsoft.Azure.Management.Fluent 1.26.0
Last lib version without the bug: 1.22.2.

**Comment by isra-fel** [comment]
Sorry for late response. @weidongxu-microsoft could you please share some insights? Thank you.

**Comment by weidongxu-microsoft** [comment]
@sabvente

Could you try later versions?

I've tried 1.33.0 and cannot reproduce. Sample json
```
"diagnostics":{"logAnalytics":{"workspaceId":"...","logType":"ContainerInsights"}}
```

There is an upgrade on container service as 1.27.0, which might have fixed the issue.
https://github.com/Azure/azure-libraries-for-net/releases/tag/Fluent-v1.27.0

**Comment by sabvente** [comment]
@weidongxu-microsoft 
Hi,

Sorry, but I'm unable to test this right now. If 1.33.0 works for you, than I'm sure this will be ok.
Close this issue if you want.

**Comment by weidongxu-microsoft** [comment]
OK. You can reopen it if you see it again.
