### ISSUE TITLE
IVirtualMachineOperations.CreateDeploymentAsync should support deploying multiples roles at once

### ISSUE THREAD

**Issue by oliverw** [Azure/azure-sdk-for-net#772]
Right now if the Roles property of VirtualMachineCreateDeploymentParameters used in a call to IVirtualMachineOperations.CreateDeploymentAsync contains more than one role (why is a collection in the first place?) the call will fail complaining the the collection should contain only one role.

Either support deploying multiple roles at once or convert the property to a scalar.

**Comment by shahabhijeet** [comment]
please reopen if this is still an issue.
