### ISSUE TITLE
[QUERY] GetFilesAndDirectories does not work with spaces

### ISSUE THREAD

**Issue by pgmolloy** [Azure/azure-sdk-for-net#7720]
This is a question for Azure File Storage, specifically the DirectoryClient method "GetFilesAndDirectories". I can upload and view directories in Azure File Explorer and read the Uri property with spaces but the method,  "GetFilesAndDirectories", fails with a message that the resource does not exits. This creates an issue for us when automating file shares between various Azure services that contain spaces within the query string.

Do we need to replace the spaces with typical Uri placeholders for this method to work?

**Comment by tg-msft** [comment]
This is the same issue as #7659.  We need URI encoding across all Storage APIs.

**Comment by amnguye** [comment]
Resolved by #8090
