### ISSUE TITLE
Add more tests for CryptographyClient

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#7725]
With the RSA implementation available for the crypto client in PR #7724, add more tests to make sure #7662 is fully covered.

**Comment by ssimontis** [comment]
Hello @heaths is anyone presently working on this, or may I have a go at it? Thank you!

**Comment by heaths** [comment]
Not currently. If you want to, that would be wonderful! Specifically, we want to validate client operations on the server, and vice versa. E.g. sign a digest on the server and verify on the client, or encrypt on the client and decrypt on the server. I have a couple of examples already in CryptographyClientTests.cs if you want to have a look.

Thank you, and I look forward to reviewing!

**Comment by heaths** [comment]
This was completed.
