### ISSUE TITLE
Storage: Change operator parameter names to left and right

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#7737]
@KrzysztofCwalina pointed out in the ongoing API review that our generated 'extensible enum' structs need to have overloaded operator parameter names of `left` and `right` instead of `a` and `b`.  [Here's an example comment.](https://apiview.azurewebsites.net/Assemblies/Review/c52f059a-6d57-4d40-b7d2-a5816565a660#Azure.Storage.Blobs.Models.ArchiveStatus)

This change should only require editing generator.ts to update the extensible enum operator parameter names at [generator.ts line 825](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Common/swagger/Generator/src/generator.ts#L825) and [generator.ts line 833](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Common/swagger/Generator/src/generator.ts#L833) to `left` and `right`.

After you regenerate, a clean Azure.Storage.sln build should let you know things are good.

**Comment by tg-msft** [comment]
And while we're in there, we should probably change `o` to `value` in the [implicit cast at line 817](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Common/swagger/Generator/src/generator.ts#L817).

**Comment by ShivangiReja** [comment]
Closed with https://github.com/Azure/azure-sdk-for-net/pull/7742
