### ISSUE TITLE
Storage: Add internal constructors for output only model types

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#7738]
@KrzysztofCwalina pointed out in the ongoing API review that model types only ever returned shouldn't have public constructors.  We're not generating those constructors, but C# will add a default public constructor if we don't have any.  [Here's an example comment.](https://apiview.azurewebsites.net/Assemblies/Review/c52f059a-6d57-4d40-b7d2-a5816565a660#Azure.Storage.Blobs.Models.AccountInfo)

We need to add an internal constructor that looks something like:
```
    /// <summary>
    /// Prevent direct instantiation of ${naming.type(type.name)} instances.
    /// You can use ${factoryName}.${naming.type(type.name)} instead.
    /// </summary>
    internal ${naming.type(type.name)}() { }
```

This is a little more involved.  You can see where we generate constructors at [generator.ts line 872](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Common/swagger/Generator/src/generator.ts#L872).  We want to add an `else` that generates the above code.  You can get the factory name for the helpful comment via same code as [line 943](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Common/swagger/Generator/src/generator.ts#L943).  Adding a local variable for `naming.type(type.name)` probably wouldn't hurt either.

When you regenerate, you should see private constructors appear for all the model types without other constructors and a Azure.Storage.sln should rebuild cleanly.

**Comment by ShivangiReja** [comment]
Closed with https://github.com/Azure/azure-sdk-for-net/pull/7744
