### ISSUE TITLE
Discrepancies in REST docs vs. actual responses [KeyVault]

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#7746]
This is a mutable list of discrepancies we're finding in the [REST documentation for Key Vault](https://docs.microsoft.com/en-us/rest/api/keyvault) vs. responses in our recorded tests.

1. [Recover Deleted Secret](https://docs.microsoft.com/en-us/rest/api/keyvault/recoverdeletedsecret/recoverdeletedsecret) returns secret properties - no secret value. There are others I'll dig up later.

**Comment by heaths** [comment]
Ping @RandalliLama

**Comment by RandalliLama** [comment]
Pulling in an appropriate owner.

**Comment by sebansal** [comment]
The documentation doesn't mention recover-delete to be returning actual secret value.

**Comment by heaths** [comment]
@sebansal the [Responses](https://docs.microsoft.com/rest/api/keyvault/recoverdeletedsecret/recoverdeletedsecret#response) section says a `SecretBundle` is returned with ID, value, etc., and the JSON schema in the swagger includes the value as well since it reuses the `SecretBundle` model type.

**Comment by jlichwa** [comment]
#please-close

**Comment by jlichwa** [comment]
@heaths can you take look, if updating documentation is enough.

**Comment by heaths** [comment]
Yes, that's fine. I see the PR didn't close this issue, so doing so now.
