### ISSUE TITLE
Add a method to extract Activity from EventData

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#7749]

**Comment by pakrym** [comment]
cc @JoshLove-msft @jsquire any customers asking for this?

**Comment by JoshLove-msft** [comment]
I haven't heard anything about this for the Service Bus equivalent.

**Comment by jsquire** [comment]
The only one that I know of was from a conversation on #14201; I think that may have been the genesis for you creating this.

**Comment by jsquire** [comment]
Closing for now, as there have not been requests for this functionality.  Will revisit as feedback is received.
