### ISSUE TITLE
Does AzureServiceTokenProvider.GetAccessTokenAsync cache tokens across instances (of the provider)?

### ISSUE THREAD

**Issue by johnkwaters** [Azure/azure-sdk-for-net#7755]
The documentation states:

"The AzureServiceTokenProvider class caches the token in memory and retrieves it from Azure AD just before expiration.So, you no longer have to check the expiration before calling the GetAccessTokenAsync method. Just call the method when you want to use the token."

Is this true even if I use a new instance of AzureServiceTokenProvider each time, or do I need to use the same instance?

```
var tokenProvider = new AzureServiceTokenProvider();
 _accessToken = await tokenProvider.GetAccessTokenAsync(_msiOptions.AppId);
```

**Comment by johnkwaters** [comment]
Got this answer on SO:

Yes. The cache is static so it is shared across instances.

The token provider uses this class as the cache: https://github.com/Azure/azure-sdk-for-net/blob/ddda7cb74b979f03bb03e240c06c924914ee8bdd/src/SdkCommon/AppAuthentication/Azure.Services.AppAuthentication/Cache/AccessTokenCache.cs. 

As you can see, it has a static ConcurrentDictionary.

**Comment by markcowl** [comment]
Question answered

**Comment by OskarKlintrot** [comment]
The caching is done in [AppAuthResultCache](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/mgmtcommon/AppAuthentication/Azure.Services.AppAuthentication/Cache/AppAuthResultCache.cs).
