### ISSUE TITLE
Storage: Update generated extensible enums

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#7780]
We're settling on a [shared pattern for extensible enums](https://gist.github.com/heaths/d105148428fe09a2631322b656f04ebb) and are [adding it to the Guidelines.](https://github.com/Azure/azure-sdk/pull/648/files)

We should follow this official pattern [in the generator.](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Common/swagger/Generator/src/generator.ts#L733)

**Comment by ShivangiReja** [comment]
Closed with https://github.com/Azure/azure-sdk-for-net/pull/8029
