### ISSUE TITLE
Is in Microsoft.Azure.EventHubs a way to create multiple EventHubClient object under the same TCP connection?

### ISSUE THREAD

**Issue by patramp** [Azure/azure-sdk-for-net#7781]
**Query/Question**
Is in Microsoft.Azure.EventHubs a easy way to create multiple EventHubClient object under the same TCP connection?

***Why is this not a Bug or a feature Request?***
In  WindowsAzure.ServiceBus library there is a class "MessagingFactory" that handle multiple eventhubclients reusing the same connection. The problem is that Microsoft.Azure.EventHubs do not have a MessagingFactory class. We would like to create multiple EventHubClient objects at runtime under the same connection following microsoft recommendation: "Always reuse connections, i.e. do not create a connection only for one event. This is valid for both AMQP and HTTP."

**Setup (please complete the following information if applicable):**
 - OS: Windows 10
 - IDE : Visual Studio Professional 2019
 - Version of the Library used: Microsoft.Azure.EventHubs 4.0.0

**Comment by jfggdl** [comment]
@patramp, thank you for raising this issue. We are discussing the best answer and we should be back to you soon.

**Comment by serkantkaraca** [comment]
Why do you need multiple EventHubClient objects using the same connection? Basically you can have single client object and keep using it.

**Comment by patramp** [comment]
I have different event hubs, my event hub sender needs to send messages to a different event hubs depends on the type of message.

**Comment by serkantkaraca** [comment]
I understand your reasoning now however still having dedicated connection per event hub should not be a big concern for you. On a Standard namespace, you get at least 5000 concurrent connections. Besides, how many eventhubs concurrently are you willing to run your clients on at any given time?

**Comment by patramp** [comment]
So your recommendation is to have one connection per eventhub, don't reuse the same connection. We are going to have a event hub sender sending messages to our eventhubs at the moment we do not know how many we are gonna have at the begining no more than 5 but in the future we do not know...

**Comment by serkantkaraca** [comment]
Are you able to do a rough estimation of number of connections needed per namespace? Such as 100 clients each sending to 5 eventhubs concurrently will need 500.

**Comment by serkantkaraca** [comment]
Please reactivate the thread if needed.
