### ISSUE TITLE
Storage: Add ToString methods to clients

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#7782]
People kept trying to `Console.WriteLine` the clients in the last UX Study.  It's not a critical scenario, but it might help folks when getting started.  And we might similarly want to use `DebuggerVisualizer` attributes to help out in the Watch window.

**Comment by JimSuplizio** [comment]
Hi @tg-msft, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
