### ISSUE TITLE
[BUG] nuget install package error

### ISSUE THREAD

**Issue by TommixYuan** [Azure/azure-sdk-for-net#7802]
my project is on .net 4.5.2,get this error  when install package by nuget.

Failed to add reference. The package 'Microsoft.Rest.ClientRuntime' tried to add a framework reference to 'System.Runtime' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.			0

**Comment by markcowl** [comment]
@TommixYuan Is your project targeted at .Net452, or at netstandard or a different framework?  Also, what kind of component is your product building (WebApp, DLL, executable, something else)?System.Runtime is a standard package in .Net 4.5.2 Framework, so this would seem to be an error in .Net452 on your machine, or the targeting pack in your IDE.

If none of these sound like your issue, can you please share your OS, Installed Frameworks, and a small repro project ?

**Comment by markcowl** [comment]
@TommixYuan Is your project targeted at .Net452, or at netstandard or a different framework?  Also, what kind of component is your product building (WebApp, DLL, executable, something else)?System.Runtime is a standard package in .Net 4.5.2 Framework, so this would seem to be an error in .Net452 on your machine, or the targeting pack in your IDE.

If none of these sound like your issue, can you please share your OS, Installed Frameworks, and a small repro project ?
