### ISSUE TITLE
Error while trying to Fetch Channel Information using Bot Service API

### ISSUE THREAD

**Issue by fazal60** [Azure/azure-sdk-for-net#7805]
Hey Guys, 
We are working on an application as part of which one of the requirements is to fetch the Secret Key value for a DirectLine Channel created within our Bot Channel Registration.
I am using the ListWithKeysAsyn POST API as it supposedly returns the Secret key values in the response:
![image](https://user-images.githubusercontent.com/7508202/65824139-803bb580-e218-11e9-9520-995ab5d443ad.png)

But I get a Bad Request Error despite supplying valid values to it.

Here is how I am making that request:
![image](https://user-images.githubusercontent.com/7508202/65824151-eb858780-e218-11e9-9f49-89b23894cd5d.png)

You can see in the above screenshot 2 highlighted lines. One for making a Post call to the List API, which fails. The other one is calling the Get API with the exact same parameters passed to it (only difference being, it takes the channelName as a string). The Get API succeeds and returns the BotChannel information, but it returns blanks for secret keys.

Here is the full log:

`{"Request":{"Method":{"Method":"POST"},"RequestUri":"https://management.azure.com/subscriptions/7da41661-fb51-45ba-b8f2-b4c136cb904b/resourceGroups/b5089623-4ae5-4f4c-b70d-76af795c421b/providers/Microsoft.BotService/botServices/85f216fd-94ef-457b-8a5e-8da14f9b118e/channels/DirectLineChannel/listChannelWithKeys?api-version=2017-12-01","Properties":{},"Content":null,"Headers":{"x-ms-client-request-id":["0e348881-6910-4381-b914-9ad6c387055a"],"accept-language":["en-US"],"Authorization":["Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImFQY3R3X29kdlJPb0VOZzNWb09sSWgydGlFcyIsImtpZCI6ImFQY3R3X29kdlJPb0VOZzNWb09sSWgydGlFcyJ9.eyJhdWQiOiJodHRwczovL21hbmFnZW1lbnQuYXp1cmUuY29tLyIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzcyZjk4OGJmLTg2ZjEtNDFhZi05MWFiLTJkN2NkMDExZGI0Ny8iLCJpYXQiOjE1Njk3MTQ5NTgsIm5iZiI6MTU2OTcxNDk1OCwiZXhwIjoxNTY5NzE4ODU4LCJhaW8iOiI0MkZnWUpBNnBxYmJ1ZGIrWHZWbXAxTEhuOHZ0QUE9PSIsImFwcGlkIjoiYWMyMDIyZGItNDlkZC00MTExLWE3MTQtMzNkMjY1ZGUzMzA4IiwiYXBwaWRhY3IiOiIxIiwiaWRwIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvNzJmOTg4YmYtODZmMS00MWFmLTkxYWItMmQ3Y2QwMTFkYjQ3LyIsIm9pZCI6IjYwMzdlNTIyLThmNGQtNDQxYy1hY2U0LTA1OTFkMjYzN2YzZiIsInN1YiI6IjYwMzdlNTIyLThmNGQtNDQxYy1hY2U0LTA1OTFkMjYzN2YzZiIsInRpZCI6IjcyZjk4OGJmLTg2ZjEtNDFhZi05MWFiLTJkN2NkMDExZGI0NyIsInV0aSI6IjAtZGoyUGc1ckVtVV9uX0EwOWhJQUEiLCJ2ZXIiOiIxLjAifQ.pK7zU1_ne1a8rX7KCGwBY_3re_kUM1VOPd1Y_9SlwOhvzPNPD8Xhkx2XQE9TiiOUhzfv9aUMFtRo_YvZ2yfkT_Qb1CtKPfmefSgT-5MhS7eEbsneRn9xA8OjyuDvpcwlt1fOs6kcTkxFoS3gtlNZra70GwHBTAXGBoZcjbotV1qYJa8lXTHLUS3m5UIvqdKXJfCDY93vV7U27TmAQ9iK6h1wnxlUw82Q_gM65oElkTLAam9CFjvw97ahp_IkxDrj8eT0OzM1l5x-uVD0khMULgRpWCRR0pPQJPZne7G7eKgu0_5kibKp1CHdwdtlTJ6R96pr7B-1CbVAxT764zVYyA"],"User-Agent":["FxVersion/4.7.3416.0","OSName/Windows","OSVersion/6.2.9200.0","Microsoft.Azure.Management.BotService.AzureBotServiceClient/0.9.3.preview"]}},"Response":{"StatusCode":400,"ReasonPhrase":"Bad Request","Content":"<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>Runtime Error</title>\r\n        <meta name=\"viewport\" content=\"width=device-width\" />\r\n        <style>\r\n         body {font-family:\"Verdana\";font-weight:normal;font-size: .7em;color:black;} \r\n         p {font-family:\"Verdana\";font-weight:normal;color:black;margin-top: -5px}\r\n         b {font-family:\"Verdana\";font-weight:bold;color:black;margin-top: -5px}\r\n         H1 { font-family:\"Verdana\";font-weight:normal;font-size:18pt;color:red }\r\n         H2 { font-family:\"Verdana\";font-weight:normal;font-size:14pt;color:maroon }\r\n         pre {font-family:\"Consolas\",\"Lucida Console\",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}\r\n         .marker {font-weight: bold; color: black;text-decoration: none;}\r\n         .version {color: gray;}\r\n         .error {margin-bottom: 10px;}\r\n         .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:hand; }\r\n         @media screen and (max-width: 639px) {\r\n          pre { width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; }\r\n         }\r\n         @media screen and (max-width: 479px) {\r\n          pre { width: 280px; }\r\n         }\r\n        </style>\r\n    </head>\r\n\r\n    <body bgcolor=\"white\">\r\n\r\n            <span><H1>Server Error in '/' Application.<hr width=100% size=1 color=silver></H1>\r\n\r\n            <h2> <i>Runtime Error</i> </h2></span>\r\n\r\n            <font face=\"Arial, Helvetica, Geneva, SunSans-Regular, sans-serif \">\r\n\r\n            <b> Description: </b>An application error occurred on the server. The current custom error settings for this application prevent the details of the application error from being viewed remotely (for security reasons). It could, however, be viewed by browsers running on the local server machine.\r\n            <br><br>\r\n\r\n            <b>Details:</b> To enable the details of this specific error message to be viewable on remote machines, please create a &lt;customErrors&gt; tag within a &quot;web.config&quot; configuration file located in the root directory of the current web application. This &lt;customErrors&gt; tag should then have its &quot;mode&quot; attribute set to &quot;Off&quot;.<br><br>\r\n\r\n            <table width=100% bgcolor=\"#ffffcc\">\r\n               <tr>\r\n                  <td>\r\n                      <code><pre>\r\n\r\n&lt;!-- Web.Config Configuration File --&gt;\r\n\r\n&lt;configuration&gt;\r\n    &lt;system.web&gt;\r\n        &lt;customErrors mode=&quot;Off&quot;/&gt;\r\n    &lt;/system.web&gt;\r\n&lt;/configuration&gt;</pre></code>\r\n\r\n                  </td>\r\n               </tr>\r\n            </table>\r\n\r\n            <br>\r\n\r\n            <b>Notes:</b> The current error page you are seeing can be replaced by a custom error page by modifying the &quot;defaultRedirect&quot; attribute of the application&#39;s &lt;customErrors&gt; configuration tag to point to a custom error page URL.<br><br>\r\n\r\n            <table width=100% bgcolor=\"#ffffcc\">\r\n               <tr>\r\n                  <td>\r\n                      <code><pre>\r\n\r\n&lt;!-- Web.Config Configuration File --&gt;\r\n\r\n&lt;configuration&gt;\r\n    &lt;system.web&gt;\r\n        &lt;customErrors mode=&quot;RemoteOnly&quot; defaultRedirect=&quot;mycustompage.htm&quot;/&gt;\r\n    &lt;/system.web&gt;\r\n&lt;/configuration&gt;</pre></code>\r\n\r\n                  </td>\r\n               </tr>\r\n            </table>\r\n\r\n            <br>\r\n\r\n    </body>\r\n</html>\r\n","Headers":{"Strict-Transport-Security":["max-age=31536000; includeSubDomains"],"x-ms-ratelimit-remaining-subscription-writes":["1198"],"x-ms-request-id":["91a3b02e-857e-4ff7-9daf-3e57e5f95ab0"],"x-ms-correlation-request-id":["91a3b02e-857e-4ff7-9daf-3e57e5f95ab0"],"x-ms-routing-request-id":["EASTUS:20190929T000102Z:91a3b02e-857e-4ff7-9daf-3e57e5f95ab0"],"X-Content-Type-Options":["nosniff"],"Cache-Control":["private"],"Date":["Sun, 29 Sep 2019 00:01:02 GMT"],"Server":["Microsoft-IIS/10.0"],"Content-Length":["3420"],"Content-Type":["text/html; charset=utf-8"]}},"Body":null,"Message":"Operation returned an invalid status code 'BadRequest'","Data":{},"InnerException":null,"StackTrace":"
   at Microsoft.Azure.Management.BotService.ChannelsOperations.<ListWithKeysWithHttpMessagesAsync>d__9.MoveNext()\r\n
--- End of stack trace from previous location where exception was thrown ---\r\n
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n
   at Microsoft.Azure.Management.BotService.ChannelsOperationsExtensions.<ListWithKeysAsync>d__9.MoveNext()\r\n
--- End of stack trace from previous location where exception was thrown ---\r\n
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()\r\n
   at Microsoft.Omnichannel.ChannelProvisioning.Client.AzureBotClient.<RetrieveDirectChannel>d__18.MoveNext() in C:\\D365Dev14\\ChannelConnector\\src\\AsyncConnectors\\ChannelProvisioningService\\Client\\AzureBotClient.cs:line 286","HelpLink":null,"Source":"Microsoft.Azure.Management.BotService","HResult":-2146233088}`

**Comment by maggiepint** [comment]
Thanks for the feedback. We have routed to the appropriate team for follow up.
