### ISSUE TITLE
Note that Event Hub samples require .NET Core 3

### ISSUE THREAD

**Issue by sebader** [Azure/azure-sdk-for-net#7809]
The Readme.md for the new Event Hubs SDK should note at least somewhere, that all the samples that are shown there do require .NET Core 3.0.

https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/eventhub/Azure.Messaging.EventHubs

**Comment by jsquire** [comment]
Include as part of #7587.


//cc: @kinelski

**Comment by jsquire** [comment]
Thank you for the feedback, Sebastian.   

The samples do require using C# 8, either as part of .NET Core 3 or by enabling the preview language version and including the compatibility references.   You're absolutely right that we do a poor job of documenting that.   We'll get those updated for the next release.

**Comment by sebader** [comment]
oh of course you're right, I meant C# 8 (which equals to .NET Core 3 in this case) :)

**Comment by jsquire** [comment]
Details for this went in with the Preview 4 README updates [#7587]

Thank you, again, Sebastian for calling this out.
