### ISSUE TITLE
Update Swagger to remove XMS from XMSContentCR64

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#7821]
https://github.com/Azure/azure-rest-api-specs/tree/storage-dataplane-preview/specification/storage/data-plane

**Comment by JoshLove-msft** [comment]
This was specifically for updating the swagger as opposed to the transform so that it would apply to all platforms and we could remove transform.

**Comment by tg-msft** [comment]
Ah, reopening

**Comment by JimSuplizio** [comment]
Hi @JoshLove-msft, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
