### ISSUE TITLE
[Azure Search] CS1061: 'IIndexesOperations' does not contain a definition for 'GetClient'

### ISSUE THREAD

**Issue by DrJuriko** [Azure/azure-sdk-for-net#7833]
Just migrated from Microsoft.Azure.Search Version="5.0.2". Everything is fine except this string:

ISearchIndexClient indexClient = ServiceClient.Indexes.GetClient("IndexName");

CS1061	'IIndexesOperations' does not contain a definition for 'GetClient' and no accessible extension method 'GetClient' accepting a first argument of type 'IIndexesOperations' could be found (are you missing a using directive or an assembly reference?)

**Setup (please complete the following information):**
-  Microsoft.Azure.Search Version="10.0.0"

**Comment by brjohnstmsft** [comment]
@DrJuriko How did you upgrade? Did you use NuGet, or did you change version numbers manually? Have you tried a full clean & rebuild?

**Comment by DrJuriko** [comment]
Yes, exactly, what I did: upgraded project from nuget, save it to git, delete old project folder from local and theg get all sources again with clone repository from git. This is my project file items:

`  <ItemGroup>
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="5.0.0" />
    <PackageReference Include="AutoMapper" Version="9.0.0" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="7.0.0" />
    <PackageReference Include="Microsoft.ApplicationInsights" Version="2.11.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.8.0" />
    <PackageReference Include="Microsoft.Azure.Search.Data" Version="10.0.0" />
    <PackageReference Include="Microsoft.Azure.Search.Service" Version="10.0.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="2.9.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="2.9.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="3.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.9.5" />
  </ItemGroup>
`

Are you sure that GetClient method is still here?

**Comment by brjohnstmsft** [comment]
`GetClient` still exists, but it's defined in an assembly that you're not referencing. I see `Microsoft.Azure.Search.Data` and `Microsoft.Azure.Search.Service`, but not `Microsoft.Azure.Search` itself. It's recommended that you just reference `Microsoft.Azure.Search` as this should automatically bring in all the dependencies.

Try that and let me know if it works.

**Comment by DrJuriko** [comment]
Yes, thank your time, after Microsoft.Azure.Search install all were fine...

**Comment by brjohnstmsft** [comment]
@drjuriko Glad it’s working for you. Thanks for confirming.
