### ISSUE TITLE
Storage: Add higher level permission helpers

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#7834]
It was suggested in the API review that we should have additional permission helpers so it's easy to see if the current permissions are the subset of another, etc.

**Comment by JimSuplizio** [comment]
Hi @tg-msft, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
