### ISSUE TITLE
Storage: Change AccessTierInferred to `bool` instead of `bool?`

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#7837]
[From the API review](https://apiview.azurewebsites.net/Assemblies/Review/c52f059a-6d57-4d40-b7d2-a5816565a660#Azure.Storage.Blobs.Models.BlobItemProperties) - we can default `null` to `false`.

**Comment by tg-msft** [comment]
I think this is just making AccessTierInferred a required value

**Comment by ShivangiReja** [comment]
Closed with https://github.com/Azure/azure-sdk-for-net/pull/7912
