### ISSUE TITLE
Storage: Change `SkuName` acronym capitalization

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#7852]
[Per the API Review](https://apiview.azurewebsites.net/Assemblies/Review/c52f059a-6d57-4d40-b7d2-a5816565a660#Azure.Storage.Blobs.Models.SkuName), the acronyms in `SkuName`'s values [should be PascalCased.](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions#capitalization-rules-for-identifiers)

**Comment by ShivangiReja** [comment]
Closed with https://github.com/Azure/azure-sdk-for-net/pull/7998
