### ISSUE TITLE
Storage: Make constants instance properties

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#7853]
Since our constants will need to version, we should make them instance properties on the clients.  See https://apiview.azurewebsites.net/Assemblies/Review/c52f059a-6d57-4d40-b7d2-a5816565a660#Azure.Storage.Blobs.Specialized.BlockBlobClient for more.

**Comment by JoshLove-msft** [comment]
Should these also be made internal as per comments on the APIReview?

**Comment by JoshLove-msft** [comment]
Also, rather than instance properties, can they be static readonly?
