### ISSUE TITLE
[QUERY] How do I enable the static website feature for azure storage blob containers via the sdk?

### ISSUE THREAD

**Issue by Spaceman1861** [Azure/azure-sdk-for-net#7875]
**Query/Question**
How do I enable the static website feature for azure storage blob containers via the sdk?

***Why is this not a Bug or a feature Request?***
It may be a feature request im not sure if you can do it via the sdk or not.

**Setup (please complete the following information if applicable):**
I have made a new storage account using.

***
var resourceGroup = await azure.ResourceGroups.Define($"{uniqueId}")
    .WithRegion(region)
    .CreateAsync();

var newstorage = await azure.StorageAccounts.Define($"{uniqueId}")
    .WithRegion(region)
    .WithExistingResourceGroup(resourceGroup)
    .CreateAsync();
***

I want to toggle on the static website feature but I can only find doco on how to do it with the CLI / Powershell modules. Can it be done with the .net sdk?

Powershell doco:
https://docs.microsoft.com/en-us/powershell/module/az.storage/enable-azstoragestaticwebsite?view=azps-2.7.0&viewFallbackFrom=azps-1.3.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [/] Query Added
- [/] Setup information Added

**Comment by Spaceman1861** [comment]
Im struggling to get the powershell one to work correctly :( any help here would be amazing.

**Comment by zezha-msft** [comment]
@zhusijia26 could you please help refer this issue to the corresponding PM?

**Comment by zhusijia26** [comment]
angshuman.nayak@ can help. Emailed him about this issue.
