### ISSUE TITLE
[FEATURE REQ] CreateIfNotExists/DeleteIfExists/Exists for File

### ISSUE THREAD

**Issue by amnguye** [Azure/azure-sdk-for-net#7878]
**Is your feature request related to a problem? Please describe.**
Related to issue #7211 
In the old API there are 'convenience' methods like CreateIfNotExists/DeleteIfExists for File and FileShare

**Describe the solution you'd like**
Helper methods (like CreateIfNotExists/DeleteIfExists) for Files

**Describe alternatives you've considered**
Can easily be worked around. Refer to #7211.

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by seanmcc-msft** [comment]
In track 1, we have:

- [CloudFileShare.CreateIfExists()](https://github.com/Azure/azure-storage-net/blob/master/Lib/ClassLibraryCommon/File/CloudFileShare.cs#L173), [.DeleteIfExists()](https://github.com/Azure/azure-storage-net/blob/master/Lib/ClassLibraryCommon/File/CloudFileShare.cs#L705), and [.Exists()](https://github.com/Azure/azure-storage-net/blob/master/Lib/ClassLibraryCommon/File/CloudFileShare.cs#L878)
- [CloudDirectoryClient.CreateIfExists()](https://github.com/Azure/azure-storage-net/blob/master/Lib/ClassLibraryCommon/File/CloudFileDirectory.cs#L239), [.DeleteIfExists()](https://github.com/Azure/azure-storage-net/blob/master/Lib/ClassLibraryCommon/File/CloudFileDirectory.cs#L514), and [.Exists()](https://github.com/Azure/azure-storage-net/blob/master/Lib/ClassLibraryCommon/File/CloudFileDirectory.cs#L649)
- [CloudFileClient.DeleteIfExists()](https://github.com/Azure/azure-storage-net/blob/master/Lib/ClassLibraryCommon/File/CloudFile.cs#L2674), [.Exists()](https://github.com/Azure/azure-storage-net/blob/master/Lib/ClassLibraryCommon/File/CloudFile.cs#L2322).  I think we should also add CreateIfNoExists()

**Comment by seanmcc-msft** [comment]
Resolved with https://github.com/Azure/azure-sdk-for-net/pull/10074
