### ISSUE TITLE
[FEATURE REQ] CreateIfNotExists/DeleteIfExists/Exists for Queue

### ISSUE THREAD

**Issue by amnguye** [Azure/azure-sdk-for-net#7879]
**Is your feature request related to a problem? Please describe.**
Related to issue #7211 
In the old API there are 'convenience' methods like CreateIfNotExists/DeleteIfExists for File and FileShare

**Describe the solution you'd like**
Helper methods (like CreateIfNotExists/DeleteIfExists) for Files

**Describe alternatives you've considered**
Can easily be worked around. Refer to #7211.

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by seanmcc-msft** [comment]
In track 1, we have [QueueClient.CreateIfNotExists()](https://github.com/Azure/azure-storage-net/blob/master/Lib/ClassLibraryCommon/Queue/CloudQueue.cs#L159),[ .DeleteIfExists()](https://github.com/Azure/azure-storage-net/blob/master/Lib/ClassLibraryCommon/Queue/CloudQueue.cs#L318), and [.Exists()](https://github.com/Azure/azure-storage-net/blob/master/Lib/ClassLibraryCommon/Queue/CloudQueue.cs#L916)
