### ISSUE TITLE
Address exception hierarchy and more specific exception types

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#7897]
https://github.com/Azure/azure-sdk-for-net/pull/7803#discussion_r329399198

Comment from @KrzysztofCwalina:
I think .NET should be throwing more specific exception types for errors that should be grammatically handled. For example, you want to handle conflicts buy reacquiring the resource, modifying it again, and retrying.

**Comment by pakrym** [comment]
I close this until we find a specific case we want to discuss.
