### ISSUE TITLE
[QUESTION] How to use .WithWinRM() ?

### ISSUE THREAD

**Issue by Mishu** [Azure/azure-sdk-for-net#7898]
**Question**
I have a question about the `WithWinRM` method for the VirtualMachine creation using the .NET Azure SDK.
I'm using this call to create a VM: 

```
var vm = await azure.VirtualMachines.Define("testVM")
                       .WithRegion("East US")
                       .WithExistingResourceGroup("TestRg")
                       .WithExistingPrimaryNetworkInterface("testVM_nic")
                       .WithWindowsCustomImage(customImage.Id)
                       .WithAdminUsername("Testuser")
                       .WithAdminPassword("Test12345678")
                       .WithWinRM(new WinRMListener(ProtocolTypes.Https, certificateUrl))
                       .WithComputerName("testVM")                       
                       .WithSize(VirtualMachineSizeTypes.StandardDS3V2)
                       .CreateAsync();
```
After running this I get an error:
```
Certificate https://xxx.vault.azure.net/secrets/xxx/db1baf0c860f456ks4nckh06d86e1ec8594 specified in WinRM configuration is not defined in the VM model secrets.
```
How can I specify the `OsProfile.Secrets` option with the fluent API?

***Why is this not a Bug or a feature Request?***
Not sure if I'm using it correctly, even though I found nothing in the documentation about this.

**Setup (please complete the following information if applicable):**
 - OS: Windows
 - IDE : Visual Studio 2019
 - Microsoft.Azure.Management.Fluent 1.26.1
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Query Added
- [x ] Setup information Added

**Comment by isra-fel** [comment]
Sorry for late response. @weidongxu-microsoft could you please share some insights? Thank you.

**Comment by weidongxu-microsoft** [comment]
@Mishu 

Would please upgrade to 1.30.0 or later? Latest is 1.33.0.
Related PR https://github.com/Azure/azure-libraries-for-net/pull/926
Related doc https://docs.microsoft.com/en-us/azure/virtual-machines/windows/winrm

It would have an additional API `WithVaultSecret` to set up keyvault setting.

**Comment by Drewm3** [comment]
AlexGhiondea, this looks to be an issue with the Fluent SDK, not the backend API. So I am removing the Service Attention label.

**Comment by weidongxu-microsoft** [comment]
I assume upgrading to 1.30.0+ would solve the problem (as in PR mentioned).

Reopen it if you still find issue.
