### ISSUE TITLE
Make Delete consistent with conditional Get

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#7915]
Investigate:
- AppConfig returns a ConfigurationSetting on Delete when a 200 response is returned?
(See swagger: https://github.com/Azure/azure-rest-api-specs-pr/pull/887)

If yes, have Delete return Reponse<T>, and return a NoBodyResponse for a 204.

**Comment by AlexanderSher** [comment]
By design. Should return Response for unconditional operations
