### ISSUE TITLE
ServiceDefinition:NamedElementNameString doesn't allow ':' (colon) in name

### ISSUE THREAD

**Issue by abatishchev** [Azure/azure-sdk-for-net#792]
cscfg scheme doesn't allow a colon `:` inside settings name, e.g.:
```
<?xml version="1.0" encoding="utf-8"?>
<ServiceDefinition name="OrangeJuice.Server.Azure" xmlns="http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition" schemaVersion="2014-06.2.4">
  <WebRole name="MyService" vmsize="Small">
    <ConfigurationSettings>
      <Setting name="test:a" />
    </ConfigurationSettings>
  </WebRole>
</ServiceDefinition>
```
Causing compiler error:

>The XML specification is not valid: The 'name' attribute is invalid - The value 'test:a' is invalid according to its datatype 'http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition:NamedElementNameString' - The Pattern constraint failed.

**Comment by singhkay** [comment]
@abatishchev This repo is actually for the MAML client libraries but I'll forward this thread to the Azure SDK team responsible for the cscfg schema internally.

**Comment by johnkattenhorn** [comment]
+1 for this, it's a major pain as Serilog uses colon, I've currently having to build a special addition to use another character.

Be good to know the reason or if there was a way to protect the colon.

**Comment by abatishchev** [comment]
Any update on this, please?

**Comment by 99abhilash99** [comment]
This shouldn't be a blocking issue.  Just remove that colon from your setting, for eg.,<Setting name="testa" /> ,you can simply use yourConfigmanager.AppSettings["testa"]

**Comment by abatishchev** [comment]
This is the blocking issue if I want to use `ns:test` and there is no reason me to be disallowed to do so, should be I?

**Comment by abatishchev** [comment]
Any response, please?

**Comment by abatishchev** [comment]
Any update on this, please?

**Comment by abatishchev** [comment]
Any update on this, please?

**Comment by singhkays** [comment]
@abatishchev Please file a support ticket for resolution on this. This repo is not manned by folks implementing the cscfg schema.

**Comment by abatishchev** [comment]
@singhkays hi Kay, is there a repo where this issue can be discussed, and maybe addressed?

**Comment by singhkays** [comment]
@abatishchev Don't think the PaaS SDK is open sourced so there currently isn't a repo. Other than support, uservoice is probable a better venue for this feedback so that folks can vote on it and it gives the team a prioritization signal. https://feedback.azure.com/forums/169386-cloud-services-web-and-worker-role
