### ISSUE TITLE
[FEATURE REQ] Service Bus: Support batching for operations other than Send

### ISSUE THREAD

**Issue by ankrause** [Azure/azure-sdk-for-net#7921]
**Is your feature request related to a problem? Please describe.**
It should be easy to work with multiple messages using the Service Bus .NET Client. Currently, the client supports batch sending new messages to a queue/topic using the SendAsync method with an overload for IList<Message>. No other operations support this.

**Describe the solution you'd like**
Ideally, all core operations accept a collection/batched operation.

The easiest example here is scheduled messages which can currently only be sent one at a time. At the very least, scheduled send seems like it should support the same level of batching as normal send, just with a delayed delivery date.

Other operations could also support batching:

- Given a handful of lock tokens, complete those locked messages.*
- Given a handful of lock tokens, abandon those locked messages.
- Given a handful of lock tokens, move those messages to deadletter.
- Given a handful of sequence numbers, cancel all scheduled messages.

\* As a note on complete, IMessageReceiver supports batch completion with lock tokens, but IQueueClient and ISubscriptionClient do not.

**Describe alternatives you've considered**
Of course you could achieve this by using parallel tasks, but that's not the same as making a single network request.

**Additional context**
The underlying implementation of both the old .NET Client and the new one appear to support some of this. For example, CancelScheduledMessageAsync ultimately has an array of sequence IDs in the underlying operation, that array is just 1 element.

**Comment by jfggdl** [comment]
@ankrause, thank you for requesting this feature. We are going to be adding this feature request to our internal backlog and we will communicate whether we are going to  implement it and if so, the approximate date for release.

**Comment by axisc** [comment]
Added this to our internal backlog.

**Comment by jsquire** [comment]
Shifting to the backlog milestone, as the previously assigned sprint has passed.

**Comment by dtovey-gdi** [comment]
Upvote on this feature request.

Azure.Messaging.ServiceBus.ServiceBusReceiver needs the ability to Complete a batch of messages (CompleteMessagesAsync).
We have had to switch our development back to the Microsoft.Azure.ServiceBus API simply to have the ability to batch complete.
Consuming a batch of 100 messages with PeekLock/Complete runs an order of magnitude faster when using the batch complete vs serial complete.

**Comment by SeanFeldman** [comment]
@jsquire this was a feature available in track 1 (`Microsoft.Azure.ServiceBus`) and is a blocker for those that need to complete messages in a batched manner. The comment provided by @dtovey-gdi is exactly what customers are going through and revert their adoption of track 3 SDK. /cc @JoshLove-msft

**Comment by SeanFeldman** [comment]
Thank you @JoshLove-msft. Was this the same for Track 0 or because of SBMP it worked differently?

**Comment by JoshLove-msft** [comment]
I'm not sure about that. @axisc do you know if SBMP had batch settlement support? Or was it implemented by sending simultaneous settlements via the client?

**Comment by dtovey-gdi** [comment]
Thank you @JoshLove-msft . That helped a lot; speed is much improved when using that approach. Track 2 and Track 1 are giving near identical times for peek-lock receive & completion. Tested several times with 20k x 512 byte messages receive/complete on both APIs with prefetching enabled.

**Comment by ramya-rao-a** [comment]
Closing this issue as there are no plans to add this feature to the older `Microsoft.Azure.ServiceBus`. Please do try the newer `Azure.Messaging.ServiceBus` package as mentioned in the previous comment and share any feedback you have.
