### ISSUE TITLE
EventHubTrigger - PartitionContext.RuntimeInformation properties are all null or default

### ISSUE THREAD

**Issue by manums** [Azure/azure-sdk-for-net#7936]
## Actual Behavior
In EventhubTrigger function, we are trying to use PartitionContext.RuntimeInformation to log Lag per partition in terms of Sequence Number and last enqueued time for that partition. 

However I always see PartitionContext.RuntimeInformation properties are all null or contain default values.

![image](https://user-images.githubusercontent.com/3592179/65829054-2a85fe00-e256-11e9-810e-382e4477240a.png)

```cs
[FunctionName("EventProcessorFunction")]
 public async Task EventsProcessorFunction([EventHubTrigger("events", Connection = "EventHubConnectionString", ConsumerGroup = "%EventHubConsumerGroup%")] EventData[] events, [EventHub("failed-events", Connection = "EventHubConnectionString")]IAsyncCollector<EventData> outputEvents, ExecutionContext executionContext, PartitionContext partitionContext)
```

## Expected Behavior
RuntimeInformation contains information about receiver (event group listener) for current partition for which function was invoked.

## Versions  
- OS platform and version: Win 10
- .NET Version: .Net Core 2.1
- NuGet package version or commit ID: EventHubs Extensions 3.0.6

![image](https://user-images.githubusercontent.com/3592179/65829118-a2ecbf00-e256-11e9-9f97-08f8725cd6a7.png)

**Comment by serkantkaraca** [comment]
Have you enable receiver run-time metrics in processor options?

**Comment by manums** [comment]
Thanks @serkantkaraca.

Adding enableReceiverRuntimeMetric worked! That said , this information can't be found easily on any docs. 

```json
"extensions": {
    "eventHubs": {
      "batchCheckpointFrequency": 1,
      "eventProcessorOptions": {
        "maxBatchSize": 64,
        "prefetchCount": 128,
        "enableReceiverRuntimeMetric": true
      }
    }
  }
```
