### ISSUE TITLE
[QUERY] How to use a NetTCPRelay (.net core 3.0)

### ISSUE THREAD

**Issue by Dispersia** [Azure/azure-sdk-for-net#7960]
**Query/Question**
 How do you implement a NetTCPRelay endpoint with this new library? I also need to add a TokenProvider.

 How we used to do it was like this:

```
var binding = new NetTcpRelayBinding();
var cf = new ChannelFactory<T>(binding, new EndpointAddress("sb://address..."));
cf.EndPoint.Behaviors.Add(new TransportClientEndpointBehavior
{
    TokenProvider = TokenProvider.CreateSharedAccessSignatureTokenProvider()
});
```
 I have found most of what I needed, but I'm not sure exactly what the 'sb' part of the address was even for. Based on: https://github.com/Azure/azure-relay-dotnet/issues/90 I also tried to change it to a BasicHttpBinding, and added the (OperationContextScope) to try and add the token that it did, but the service returns a 400 (which, it gives no information about, unfortunately).

 With that, do I need the TokenProvider from Microsoft.Azure.Relay, or the Primitive? I don't know what the difference is and they look the exact same to me.

***Why is this not a Bug or a feature Request?***
 Not sure if this is even where this would be implemented, but the token providers, and old clients were in WindowsAzure.ServiceBus

**Setup (please complete the following information if applicable):**
 - OS: Windows 10
 - IDE : Visual Studio 2019 Enterprise
 - 4.0.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by jfggdl** [comment]
@Dispersia, thanks for creating this issue. I am working on providing the answers to your questions.

**Comment by dlstucki** [comment]
For WCF Relays, such as NetTcpRelayBinding, [WindowsAzure.ServiceBus](https://www.nuget.org/packages/WindowsAzure.ServiceBus/) is the only supported API. There is no .NET Core support for WCF Relays. [Microsoft.Azure.Relay](https://www.nuget.org/packages/Microsoft.Azure.Relay/) supports Hybrid Connections only.

**Comment by jfggdl** [comment]
@Dispersia, I will be closing this issue, but feel free to request to be opened again if you still have a question.

**Comment by dlstucki** [comment]
For example, this WebHttpRelayBinding sample would work with the relay sender running in .NET Core if you generated a token in .NET Core (I'd personally use TokenProvider from Microsoft.Azure.Relay.dll to do this):
https://github.com/Azure/azure-relay/tree/master/samples/wcf-relay/RelayHttp

Alternatively you could not require Client Auth on the WCF Relay, but that's recommended.

**Comment by Dispersia** [comment]
Thank you, we ended up moving it off of servicebus and just to an `http://` route, and used an azure function proxy to point to it. Thank you for the help
