### ISSUE TITLE
Storage: Provide sync Multipart reader

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#7972]
The implementation we took from ASP.NET only supports async operations.  If we want a fully sync option, we may need to modify it.

**Comment by JimSuplizio** [comment]
Hi @tg-msft, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
