### ISSUE TITLE
Remove unnecessary nullable parameters in Storage API

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#7974]
For instance, in DeleteBlob (both in BlobBatch and BlobBaseClient) DeleteSnapshotsOptions and BlobAccessConditions params are nullable for no apparent reason. We can go through the API and remove nullability to make the API more straightforward and more maintainable.

**Comment by tg-msft** [comment]
While the reasons may not be apparent, there are reasons.  The access conditions will be fixed as part of #7896 and there's another PR looking at DeleteSnapshotOptions.  I think this is a duplicate.
