### ISSUE TITLE
Microsoft.Azure.* needs to archive PDBs to the symbol server

### ISSUE THREAD

**Issue by leculver** [Azure/azure-sdk-for-net#7976]
Hello!

I am getting reports that PDBs are missing for certain Azure SDK dlls.  Specifically we are seeing reports that these are missing, but I assume this is a general problem all of the DLLs that are being built:

    microsoft.azure.management.resourcemanager.dll
    Microsoft.Azure.KeyVault.Core.dll

The symbols policy for DevDiv is that all frameworks need to archive their PE image and **Windows** PDBs (that is, non-portable pdbs) to the internal Microsoft symbol server.  We require non-portable PDBs because the entire ecosystem around Watson does not yet support portable pdbs.  Work has begun to support this, but in the meantime we need to have teams archive windows PDBs to the symbol server.

This not only impacts Watson and WinDbg users, but also any VS component that takes a dependency on Microsoft.Azure.* DLLS will get automatic bugs filed against them when trying to insert builds without properly archived PE Images or PDBs.

Usually resolving this is as simple as adding an extra build step to convert Portable PDBs into regular PDBs and archiving them.  I can provide more details offline.

Please let me know if you have any questions or concerns!

**Comment by kurtzeborn** [comment]
@chidozieononiwu, Wes believes the work is done here, just need you to verify that PDBs are indeed being archived.

**Comment by leculver** [comment]
@kurtzeborn if you can point me to some binaries/pdbs that you believe are indexed properly I can verify that it all works end-to-end.

**Comment by chidozieononiwu** [comment]
@kurtzeborn We still need to publish a package to actually test this. I will get Azure.Template published today then we can test.

**Comment by chidozieononiwu** [comment]
@leculver I have published https://www.nuget.org/packages/Azure.Template/1.0.2-preview.1 and it should be have pdbs published.

**Comment by leculver** [comment]
@chidozieononiwu Thank you!  I will test this Monday if I can, Tuesday afternoon if not.

**Comment by weshaggard** [comment]
For context this issue was addressed with 2 changes:
https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-build-tools/pullrequest/63 which enabled our symbol publishing steps to convert from portable pdb to windows pdb for symbol archiving.

https://github.com/Azure/azure-sdk-for-net/pull/8748 was a follow-up we need because the portable pdb conversion needed both the pdb and dll in the same package to be able to do the conversion. Which is why we need to use symbols.nupkg instead of snupkg.
