### ISSUE TITLE
[BUG] RetryPolicy does not seem to have any impact on subscriptions

### ISSUE THREAD

**Issue by sanjaysingh** [Azure/azure-sdk-for-net#7978]
**Describe the bug**
When I susbscribe to a Topic with a retry policy that basically says 'keep trying for maximum of 100 times with maximum delta of 30 sec and then give up', I see that the retry continues whatever settings i do for the RetryPolicy. In short RetryPolicy does not seem to play any role in this.
Following is sample code to create the client and susbcribe
```C#
var client = new SubscriptionClient(
                    "<<>ConnectionString>",
                    "<<topic>>",
                    "<<subscription>>",
                    ReceiveMode.PeekLock,
                    new RetryExponential(TimeSpan.Zero, TimeSpan.FromSeconds(1), 5));
var messageHandlerOptions = new MessageHandlerOptions(this.OnExceptionReceived)
            {
                AutoComplete = false
            };
client.RegisterMessageHandler(async (message, token) => { await ProcessMessage(message, token); }, messageHandlerOptions);

When i introduce a network issue and bring it back, things keep working automatically which is nice. However, in cases where the network connectivity issue has spanned more than specific retry limit, i expect this to stop retrying. It does not however do so and seems to infinitely retry.

The question is -  what is then the use of RetryPolicy for subscription scenario? How do i achieve this behavior of stopping to retry after it as exhausted the configured value. 

```

***Exception or Stack Trace***
Not applicable

**To Reproduce**
As given in the description above

***Code Snippet***
Given in the description

**Expected behavior**
RetryPolicy should be honored for subscription use cases or please point me to a documentation for how it works for mainly subscription use case. 

**Screenshots**
Not applicable

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : Visual Studio 2019, .Net 4.6.2
 - Version of the Library used: Microsoft.Azure.ServiceBus 3.4.0

**Comment by jfggdl** [comment]
@sanjaysingh, thanks for creating this issue. We are going to try to reproduce your scenario and we will get back to you with our findings.

**Comment by nemakam** [comment]
@sanjaysingh , the given description is by-design. 
So the `RetryPolicy` that you provide is applicable at an operation level. For example `CompleteMessageAsync()` or `MessageReceiver.ReceiveAsync()`. Given an individual operation, it is wrapped under the `RetryPolicy` to ensure it gets its fair share of retries.
But the pumps (i.e., `RegisterMessageHandler`) works differently where-in it is expected to recover automatically and remove lot of complications of error handling etc from the end-user. It internally calls `ReceiveAsync()` with the right `RetryPolicy` but the pump itself continues infinitely until you close the client.
If for any reason the default behavior does not suit you, feel free to use the individual pieces on which the pump is built (for e.g., `MessageReceiver`) to get what you want.
