### ISSUE TITLE
[FEATURE REQ] Azure Storage Clients should support un-authenticated access and using a preexisting HttpPipeline

### ISSUE THREAD

**Issue by alexperovich** [Azure/azure-sdk-for-net#7986]
**Is your feature request related to a problem? Please describe.**
I have a storage account container with public anonymous read/list access. I wanted to use the storage SDK to read and list blobs in the container. That isn't possible without abusing the protected constructor to create a sub class that creates the HttpPipeline manually.

**Describe the solution you'd like**
This should be completely valid csharp
```csharp
var container = new BlobContainerClient("https://<account>.blob.core.windows.net/<container>"); // <-- anonymously accessible container, but this should also work with a SAS token in the url
container.GetBlobs(); // This should return successfully if the container has public read/list access enabled
```

**Describe alternatives you've considered**
I currently have the following functioning hack:
```csharp
private class AnonContainerClient : BlobContainerClient
{
  public override Uri Uri { get; }
  protected override HttpPipeline Pipeline { get; }

  public AnonContainerClient(string uri)
  {
    Uri = new Uri(uri);
    Pipeline = HttpPipelineBuilder.Build(new BlobClientOptions());
  }
}
```
Unfortunately this causes `GetBlobClient` to return an invalid `BlobClient` instance because it passes a null `HttpPipeline` to it. I can't just override `GetBlobClient` because the constructor that accepts an HttpPipeline is internal.

**Additional context**
No additional context

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issue as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by maggiepint** [comment]
@tg-msft what do you think?

**Comment by tg-msft** [comment]
Thanks for filing this.

We've fixed the missing .ctor with #7836 and that'll show up in the next release.  The other (maybe slightly less annoying) workaround in the meantime is:

```C#
private BlobContainerClient GetAnonymousContainerClient(Uri containerUri)
{
    BlobUriBuilder builder = new BlobUriBuilder(containerUri);
    string containerName = builder.ContainerName;
    builder.ContainerName = null;
    return new BlobServiceClient(builder.Uri).GetBlobContainerClient(containerName);
}  
```

We've also made the Pipeline internal with #7843, per feedback from @KrzysztofCwalina.  We're planning to keep these hidden until we've collected more customer feedback and scenarios to make sure we've got the API right.

**Comment by amnguye** [comment]
Hi,

Is this still an issue for you, or does the release with the fix resolve this issue?

**Comment by alexperovich** [comment]
This issue is fixed. Thanks.
