### ISSUE TITLE
Rename structs with too generic names

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#8022]
Based on API feedback, we should rename this type:

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Certificates/src/Action.cs#L12

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Certificates/src/Certificate.cs#L12

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Certificates/src/Contact.cs#L11

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Certificates/src/ContactList.cs

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Certificates/src/Error.cs#L11

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Certificates/src/Issuer.cs#L14

**Comment by heaths** [comment]
I'm tracking this internally with all our other edits. This is tracked as one large issue #8035.
