### ISSUE TITLE
BatchClient through exception when trying to use api to list pools

### ISSUE THREAD

**Issue by OBSchoolQ** [Azure/azure-sdk-for-net#8026]
Hello,

I am trying to create a WPF/C# application to access Batch and perform different tasks.

I am using Miscrosoft.Identity.Client.dll (MSAL) the Microsoft Identity Platform to get authentication token and setup my clientid and Azure Batch permission following the steps for "Use integrated authentication" given here https://docs.microsoft.com/en-us/azure/batch/batch-aad-auth.

I am trying to use the BatchClient object and I get the following error whenever I try to use its api such as listing pools (I am using Microsoft.Azure.Batch.dll version 12.0.0).

Error Code = AuthenticationFailed, Lang=en-US, Message = Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly.
RequestId:c2f995b5-6d67-48f5-933e-8eaa18057d59
Time:2019-10-09T23:22:39.8087667Z
Additional Values:
Error Details key=AuthenticationErrorDetail value=The access token has been obtained from wrong audience or resource 'https://batch.core.windows.net'. It should exactly match (including forward slash) with one of the allowed audiences 'https://batch.core.windows.net/'

It issue seems to be related to the parsing of scopes.

There was a similar bug reported and fixed but with management.core.windows.net instead of batch.core.windows.net.
Here is the link https://github.com/Azure/azure-sdk-for-net/issues/4090.

I have used a similar approach with Azure Service Management (ResourceManagementClient) using Microsoft.Azure.Management.ResourceManager.dll with no problem.
However, I noticed that if I try to use the wrong scope when authenticating and then use ResourceManagementClient and call an api I get this error.

The access token has been obtained for wrong audience or resource 'https://batch.core.windows.net'. It should exactly match with one of the allowed audiences 'https://management.core.windows.net/','https://management.core.windows.net','https://management.azure.com/','https://management.azure.com'.

Which is similar to the BatchClient error but with more "allowed audiences".

I tried three approaches to try and make the BatchClient work; (1) using BatchTokenCredentials (2) using BatchServiceClient and (3) using BatchSharedKeyCredentials.
Numbers (1) and (2) do not work but (3) works. However I do not want to use (3) because it requires the use of a batch account key.

Here is my code for the 3 different tries.

            string[] batchScopes = new string[] { "https://batch.core.windows.net/user_impersonation" };

            AuthenticationResult myBatchAuthResults = await GetAuthResultAsync(batchScopes);

            string BatchAccountUrl = "https://mybatchaccount.westus2.batch.azure.com";
            string BatchAccountName = "mybatchaccount";
            string BatchAccountKey = "mybatchaccountkey==WJ9MSilP58ZeR";

            // OPTION 1
            BatchTokenCredentials batchTokenCredentials = new BatchTokenCredentials(BatchAccountUrl, myBatchAuthResults.AccessToken);

            // OPTION 2
            ServiceClientCredentials myBatchServiceClientCred = new TokenCredentials(myBatchAuthResults.AccessToken);

            BatchServiceClient batchServiceClient = new BatchServiceClient(myBatchServiceClientCred);
            batchServiceClient.BatchUrl = BatchAccountUrl;

            using (BatchClient batchClient = BatchClient.Open(batchServiceClient))
            {
                try
                {
                    IPagedEnumerable<CloudPool> temppools = batchClient.PoolOperations.ListPools();
                    foreach (CloudPool pol in temppools)
                    {

                    }
                }
                catch (Exception exp)
                {
                    Console.WriteLine(exp.ToString());
                    Message = exp.ToString();
                }
            }

            // OPTION 3

            BatchSharedKeyCredentials cred = new BatchSharedKeyCredentials(BatchAccountUrl, BatchAccountName, BatchAccountKey);

            using (BatchClient batchClient = BatchClient.Open(cred))
            {
                try
                {
                    IPagedEnumerable<CloudPool> cloudPools = batchClient.PoolOperations.ListPools();
                    foreach (CloudPool cloudPool in cloudPools)
                    {

                    }
                }
                catch (Exception exp)
                {
                    Console.WriteLine(exp.ToString());
                    Message = exp.ToString();
                }

            }

        private async Task<AuthenticationResult> GetAuthResultAsync(string[] newScopes)
        {
            AuthenticationResult newAuthResult = null;

            IPublicClientApplication app = App.PublicClientApp;

            IEnumerable<IAccount> accounts = await app.GetAccountsAsync();

            IAccount firstAccount = accounts.FirstOrDefault();

            try
            {
                newAuthResult = await app.AcquireTokenSilent(newScopes, firstAccount)
                                      .ExecuteAsync();
            }
            catch (MsalUiRequiredException ex)
            {
                // A MsalUiRequiredException happened on AcquireTokenSilent.
                // This indicates you need to call AcquireTokenInteractive to acquire a token
                // System.Diagnostics.Debug.WriteLine($"MsalUiRequiredException: {ex.Message}");

                try
                {
                    newAuthResult = await app.AcquireTokenInteractive(newScopes)
                        .WithAccount(accounts.FirstOrDefault())
                        .WithPrompt(Prompt.SelectAccount)
                        .ExecuteAsync();
                }
                catch (MsalException msalex)
                {
                    string msg = $"Error Acquiring Token:{System.Environment.NewLine}{msalex}";
                    Message = msg;
                }
            }
            catch (Exception ex)
            {
                string msg = $"Error Acquiring Token Silently:{System.Environment.NewLine}{ex}";
                Message = msg;
                return null;
            }

            return newAuthResult;
        }

I would like to know what I'm missing and make this work.
Thank you

**Comment by schaabs** [comment]
@OBSchoolQ Thanks for filing this issue, sorry you're running into trouble here. From looking at the error message it seems like you're missing a '/' in the scope you're specifying. Can you try adding another '/' to your scope in the first line of your snippet like this:

~~~
 string[] batchScopes = new string[] { "https://batch.core.windows.net//user_impersonation" };
~~~

Or if that still doesn't solve the problem could you also try the following scope:

~~~
 string[] batchScopes = new string[] { "https://batch.core.windows.net//.default" };
~~~

**Comment by OBSchoolQ** [comment]
Thank you. Both these scopes work.

The reason I used the string without the extra '/' is because I have been able to use scopes for storage and graph successfully without having to put the extra '/'. Including adding containers, making resources,... But when I moved to Batch the same approach didn't work.

string[] storageScopes = new string[] { "https://storage.azure.com/user_impersonation" };

string[] graphScopes = new string[] { "https://graph.microsoft.com/User.Read" };

I was confused by the error message since it showed  'https://batch.core.windows.net' and 'https://batch.core.windows.net/' with one part showing "//" and the end just showing "/". I did not clue in that I needed the extra slash.

Thanks again for your help.

**Comment by bgklein** [comment]
@OBSchoolQ I am closing the issue as it seems your issue is mitgated. Feel free to reach out if you experience other issues!
