### ISSUE TITLE
Storage: Rename Lease to BlobLease

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#8037]
[Per the API review](https://apiview.azurewebsites.net/Assemblies/Review/c52f059a-6d57-4d40-b7d2-a5816565a660#Azure.Storage.Blobs.Models.Lease), we want to rename `Lease` to `BlobLease`.

**Comment by ShivangiReja** [comment]
Closed with https://github.com/Azure/azure-sdk-for-net/pull/8071
