### ISSUE TITLE
Storage: Remove `Blob` suffix in BlobType enum values

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#8038]
[Per the API review](https://apiview.azurewebsites.net/Assemblies/Review/c52f059a-6d57-4d40-b7d2-a5816565a660#Azure.Storage.Blobs.Models.BlobType), we should remove the `Blob` suffix from our the enum values in `BlobType`.  It should become:

```C#
public enum BlobType
{
    Block,
    Page,
    Append
}
```

**Comment by ShivangiReja** [comment]
Closed with https://github.com/Azure/azure-sdk-for-net/pull/8105
