### ISSUE TITLE
Storage: Change first ServiceVersion value to 1 and throw for everything else

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#8039]
https://apiview.azurewebsites.net/Assemblies/Review/c52f059a-6d57-4d40-b7d2-a5816565a660#Azure.Storage.Blobs.BlobClientOptions.ServiceVersion

**Comment by tg-msft** [comment]
For Blobs, Queues, and Files

**Comment by ShivangiReja** [comment]
closed with https://github.com/Azure/azure-sdk-for-net/pull/8128
