### ISSUE TITLE
Storage: Add convenience to turn a BlobItem into a BlobClient

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#8046]
Per the API review and UX studies, make it easy to create a BlobClient from a BlobItem.

**Comment by amnguye** [comment]
Closing for now as a sufficient workaround to use.
```
containerClient.GetBlobBaseClient(blobItem.Name);
```

If you are looking for a feature like this, please open a new github issue with your scenario / code workaround that would benefit from a feature like this.
