### ISSUE TITLE
Exception Message: Tried to get token using Azure CLI. Access token could not be acquired. after `az login

### ISSUE THREAD

**Issue by cescoferraro** [Azure/azure-sdk-for-net#8053]
**Describe the bug**
I cannot connect to my dev vault even after running az login

***Exception or Stack Trace***Parameters: Connectionstring: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/b8495907-4bdc-4878-a828-a90219cad36f. Exception Message: Tried to get token using Azure CLI. Access token could not be acquired. 

***Code Snippet***
```
                .ConfigureAppConfiguration((context, config) =>
                {
                    var name = $"{Environment.GetEnvironmentVariable("KEYVAULT_NAME")}";

                    Console.WriteLine(name);
                    var keyVaultEndpoint = $"https://{name}.vault.azure.net/";
                    var azureServiceTokenProvider = new AzureServiceTokenProvider();
                    Console.WriteLine(keyVaultEndpoint);
                    var keyVaultClient = new KeyVaultClient(
                        new KeyVaultClient.AuthenticationCallback(
                            azureServiceTokenProvider.KeyVaultTokenCallback));

                    config.AddAzureKeyVault(
                        keyVaultEndpoint, keyVaultClient, new DefaultKeyVaultSecretManager());
                })
```

**Expected behavior**
To  read the vault, it works on other machines

**Setup (please complete the following information):**
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 18.2 Sonya
Release:	18.2
Codename:	sonya
cescoferraro@desktop:

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [ ] Repro Steps Added
- [x] Setup information Added

**Comment by varunsh-msft** [comment]
Can you please follow the steps listed here, and let me know what error you get? Do you get a token returned when you run _az account get-access-token_ on the command line?
https://docs.microsoft.com/en-us/azure/key-vault/service-to-service-authentication#appauthentication-troubleshooting

**Comment by varunsh-msft** [comment]
Closing this issue as there has been no response to the question.

**Comment by felipevianas** [comment]
Hello there, anyone else facing this problem in Visual Studio for Mac ?

When I run "az account get-access-token --resource https://vault.azure.net" in the terminal it works and gives me the token, however when I try to debug the application from visual studio for mac I get the following error:

**Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderException has been thrown**

"Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/563b1b43-df0e-4083-b1a3-a25195382d70. Exception Message: Tried the following 3 methods to get an access token, but none of them worked.\nParameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/563b1b43-df0e-4083-b1a3-a25195382d70. Exception Message: Tried to get token using Managed Service Identity. Unable to connect to the Instance Metadata Service (IMDS). Skipping request to the Managed Service Identity (MSI) token endpoint.\nParameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/563b1b43-df0e-4083-b1a3-a25195382d70. Exception Message: Tried to get token using Visual Studio. Access token could not be acquired. Environment variable LOCALAPPDATA not set.\nParameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/563b1b43-df0e-4083-b1a3-a25195382d70. Exception Message: Tried to get token using Azure CLI. Access token could not be acquired. \n"

**Comment by seanarmstrong87** [comment]
@felipevianas Did you get any solution to your problem? I am having the same issue running on Mac (M1) debugging in Rider

**Comment by felipevianas** [comment]
Not yet, everything I have tried so far has not worked, I even tried Rider as well and no luck, as soon as I find the solution I will post it here.

**Comment by felipevianas** [comment]
@seanarmstrong87 I just tried using AzureServiceTokenProvider( "RunAs=Developer;DeveloperTool=AzureCLI" ) on Rider and it worked.

However still doesn't work on Visual Studio for MAC.

@varunsh-coder can you help us?

**Comment by varunsh-coder** [comment]
I no longer work at Microsoft. From what I can remember the integration was between AzureServiceTokenProvider and Visual Studio, not VS for MAC. You can use Azure CLI's token on a MAC. Moreover, the recommendation is to migrate to the Azure.Identity library: https://docs.microsoft.com/en-us/dotnet/api/overview/azure/app-auth-migration

**Comment by seanarmstrong87** [comment]
I got it working. I had installed homebrew and azure-cli on my Mac (M1) and
the Arm64 version has a different install location. The azure
authentication library couldn't find the CLI. Not sure why as there was a
symlink for it on the path. So I uninstalled homebrew and installed the 64
bit version then installed the 64 bit version of the azure-cli. Then it
worked.

**Comment by felipevianas** [comment]
@seanarmstrong87 thanks for the update, however I am not sure how to specify the 64 bit version during homebrew and azure cli installation.

Can you please let me know how you did it?

**Comment by seanarmstrong87** [comment]
I followed this article which shows how to setup both versions of homebrew
on your mac.

https://medium.com/mkdir-awesome/how-to-install-x86-64-homebrew-packages-on-apple-m1-macbook-54ba295230f

Good luck

**Comment by felipevianas** [comment]
Great, thanks :)

**Comment by tlo-johnson** [comment]
In the Arm64 camp. An alternative is to specify the location of the Azure-CLI via the AzureCLIPath environment variable. 

`AzureCLIPath="/opt/homebrew/bin" dotnet run`

**Comment by anaim3** [comment]
hi, did you manage to fix this problem? I am really struggling here? is it working or not ?

**Comment by felipevianas** [comment]
Yes, I was able to make it work using this option for installing node and azure-cli:

arch -x86_64 brew install "here goes your package name"

Hope it works for you.

**Comment by anaim3** [comment]
I tried the steps you shared by executing every command there..

at the end I just installed Azure-CLI by axbrew instead of brew.. 

I didn't change any config in VS tho.. is that correct ?

**Comment by neonids** [comment]
Hey guys, I am seeing the same issue. I tried installing the 64 bit versions but same issue. I think Azure auth library is not able to find the az cli. Any ideas?
