### ISSUE TITLE
EventHubClient.SendAsync(IEnumerable<EventData>, string) enumerates input sequence more than once

### ISSUE THREAD

**Issue by pasviridov** [Azure/azure-sdk-for-net#8060]
## Actual Behavior
1. Call the EventHubClient.SendAsync with single-pass sequence, e.g. created using yield method.
2. Some or all messages aren't being sent.

## Expected Behavior
1. All messages should be sent to Event Hub.

## Versions  
- OS platform and version: N/A
- .NET Version: .net core 3.0, .net standard 2.1
- NuGet package version or commit ID: Microsoft.Azure.EventHubs 4.1.0

Code example that reproduces the error: [Program.zip](https://github.com/Azure/azure-event-hubs-dotnet/files/3716238/Program.zip)

**Comment by serkantkaraca** [comment]
You are logging 20 items as 'sent' however only sending 7 of them actually. All 7 sent is received at each iteration. Am I reading this wrong?

**Comment by serkantkaraca** [comment]
The issues doesn't seem to be AEH SDK related. Basically remove the SDK from the sample code and check Count() on the returned enumerator as in the below code snippet. Count will return different values on the same batch. I am not sure whether this is CLR bug or the behavior is by design.

```
                var batches = LimitBatchSize(items);
                foreach (var batch in batches)
                {
                    Console.WriteLine($"Count: {batch.Count()}");
                    Console.WriteLine($"Count: {batch.Count()}");
                }
```

**Comment by pasviridov** [comment]
> Count will return different values on the same batch

Yes, you're right. Your code snippet demonstrates the same behavior because it contains the same error as the SendAsync method of AEH SDK does. In a common case, the IEnumerable contract doesn't suppose scanning more than one time. You cannot call Count() and then call it again or rescan the sequence in some other way and be sure that you'll get the same sequence of items. E.g. the next example will also lead you to the same problem where its cause is more obvious, i.e. it produces different values of Count() samely as your example does:

```
IEnumerable<string> ReadLinesFromConsole()
{
    string line;
    while ("stop" != (line = Console.ReadLine()))
    {
        yield return line;
    }
}

IEnumerable<string> lines = ReadLinesFromConsole();
Console.WriteLine(lines.Count());
Console.WriteLine(lines.Count());
```

The problem with the SendAsync method of AEH SDK is that it defines its contract using the IEnumerable type of parameter but uses the parameter as a re-scannable collection. Such a contract gives an illusion that you can provide this parameter as a single-pass sequence, e.g. use a method like ReadLinesFromConsole() shown above. But SDK uses this parameter in a wrong way i.e. scans it several times (at least twice, the first time on validation, then on sending the events). So, until you don't use permanent collections (e.g. List<> or Array) you may get a wrong behavior. There are several ways to fix the issue:
* Explicitly define the method's contract as expecting a re-scannable collection, e.g. use IReadOnlyCollection<EventData> or IReadOnlyList<EventData>.
* Preserve the existing contract but explicitly convert the sequence to a re-scannable collection inside the SendAsync method implementation, e.g. use ToList() or ToArray(), and then use it.
* At least, explicitly describe the expectations of the method in its documentation. We've discovered the problem in our production environment and it wasn't obvious that some implicit requirements of the SendAsync method weren't satisfied.

**Comment by serkantkaraca** [comment]
Thanks for detailed explanation of the root cause of the issue. I will start working on the fix ASAP. First, need to find out if other SDKs we own are also susceptible to this contract and fix them all the same way.

**Comment by serkantkaraca** [comment]
Fix under review at https://github.com/Azure/azure-sdk-for-net/pull/14053
