### ISSUE TITLE
Fix tests so they delete any settings they add.

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#8068]
Currently the AZConfig library has tests that add some settings but does not clean them up after execution. Need to clean up settings added by tests.

**Comment by Prince269090** [comment]
@annelo-msft , Can you please provide more details on files which requires this to be fixed?

**Comment by annelo-msft** [comment]
@Prince269090, thanks for helping out with this!

Have a look at https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/appconfiguration/Azure.Data.AppConfiguration/tests/ConfigurationLiveTests.cs.

We want everything to be deleted that isn't created by the https://github.com/Azure/azure-sdk-for-net/blob/0420109e4f665b540b82d5a5aa6de6c290847d03/sdk/appconfiguration/Azure.Data.AppConfiguration/tests/ConfigurationLiveTests.cs#L68 function.

**Comment by annelo-msft** [comment]
Specifically, the ConfigurationSetting with (key: "abcde-<id>", value: "Starts with abc") is not getting deleted.
