### ISSUE TITLE
Require Explicit Proxy Instance

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#8069]
# Summary

Currently, the track one version of the Service Bus client library for .NET does not require callers to explicitly provide an `IWebProxy` instance when they would like to use a proxy as part of the transport.  Instead, an attempt is made to implicitly discover the system-wide proxy and make use of it.  It does not appear to be possible today for a caller to override that behavior and provide an explicit proxy.

Because the track one code delegates proxy discovery to `WebRequest.DefaultWebProxy`, it currently is unavailable when using .NET Core or other platforms where the `WebRequest` type has been deprecated.

# Scope of Work

- Investigate the potential for removing implicit proxy discovery in favor of requiring an explicit proxy.

- If possible, remove the implicit proxy discovery.  Otherwise, update the approach to make use of the `HtppClient`, as described in the related issue below.

- Allow for callers to specify an explicit proxy instance which takes precedence over any implicitly discovered default.

# Success Criteria

- The Service Bus client library is usable on .NET Core 3 and with the common targets for the Azure .NET SDKs.

- Callers are able to pass an explicit `IWebProxy` instance that takes precedence over any defaults.

# Related Issues

- [[BUG] System.Net.Sockets.SocketException in netcoreapp TargetFramework](https://github.com/Azure/azure-sdk-for-net/issues/7899) (#7899)

**Comment by JoshLove-msft** [comment]
This is supported here - https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/src/ServiceBusClientOptions.cs#L32

We currently don't have a default Proxy. @jsquire  does EH allow for default Proxy?

**Comment by jsquire** [comment]
No; Event Hubs does not allow for an implicit default proxy.   It requires an explicit proxy be set in the options.   If I recall, this was opened by request when Pavel was first investigating based on an issue with Track One where it used an out of date method for sniffing the system default an implicitly trying to use it.

I think Track Two is using the same underlying approach that Event Hubs was, this is a non-issue and can be ignored.
