### ISSUE TITLE
Azure Insights Preview - Authentication failed. The 'Authorization' header is not present or provided in an invalid format.

### ISSUE THREAD

**Issue by sporty81** [Azure/azure-sdk-for-net#807]
Trying to use the new Azure Insights EventOperations and getting authorization failures.

            SubscriptionCloudCredentials credentials = new CertificateCloudCredentials(subscriptionID, cert);
            Microsoft.Azure.Insights.InsightsClient client = new InsightsClient(credentials);

            var test2 = client.EventOperations.GetCountSummaryAsync("");
            test2.Wait();

            var response = client.EventOperations.ListEventsAsync("", "");
            response.Wait();

**Comment by matt-gibbs** [comment]
There are two types of client libraries. They are divided by namespace. The "WindowsAzure" libraries can user CertificateCloudCredentials. They access Azure through the original access points. They correspond to features configured via https://manage.windowsazure.com . The "Azure" libraries correspond to the new Azure Resource Manager controls, and https://portal.azure.com and use AAD.
