### ISSUE TITLE
[P1] Storage: Make sure ListSharesIncludeType is hidden in Files

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#8078]
https://apiview.azurewebsites.net/Assemblies/Review/47c9ebbff8c0458fa2e7904eae34656f#0ab7be88f79f4198ac525c2e8f0751fe

**Comment by ShivangiReja** [comment]
Closed with https://github.com/Azure/azure-sdk-for-net/pull/8164
