### ISSUE TITLE
[P0] Storage: Update Files and Queues enumerators to match GetBlobs

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#8084]
Remove the `Get*Options` types, turn bool params into flags enums, raise everything up to params,etc.

https://apiview.azurewebsites.net/Assemblies/Review/47c9ebbff8c0458fa2e7904eae34656f#Azure.Storage.Files.Models.GetFilesAndDirectoriesOptions

**Comment by JoshLove-msft** [comment]
GetFilesAndDirectoriesOptions has two properties - Prefix and ShareSnapshot - both of which are strings. As such, this wouldn't make sense to change to an Enum. Should we leave as is?

GetQueueOptions can be made a Flags Enum.

**Comment by tg-msft** [comment]
Don't make them enums, but remove the Options class and put the values directly on the method.
