### ISSUE TITLE
Question: Using Microsoft.Azure.Services.AppAuthentication library with SDK

### ISSUE THREAD

**Issue by ghost** [Azure/azure-sdk-for-net#8089]
Hi guys,

If we look at the Managed Service Identity documentation [here](https://docs.microsoft.com/en-us/azure/app-service/app-service-managed-service-identity?context=azure/active-directory/context/msi-context#asal), it recommends to use the Microsoft.Azure.Services.AppAuthentication library to get an access token. I know then I can create a `TokenCredential` with the access token string and pass it to `SqlManagementClient`. 

However, the access token life cycle is now completely not managed by Azure SDK. Which means I have to catch exception and get a new access token. My questions are:

1. Why we have two ways of doing authentication? One built in SDK, one through another library.
2. How can we manage the access token life cycle in SDK now? Should we find someone to integrate these libraries together?
3. If the answer is to create new SQL management client every time, then how you an re-use a single instance of HTTP Client to avoid hitting Azure function sandbox connection limit?

Thanks

**Comment by yaohaizh** [comment]
C# Non fluent lib issue.

**Comment by jongio** [comment]
@ghost Please see this temporary adapter that we created here: https://github.com/jongio/azidext

It only supports DefaultAzureCredential for now.  Please let me know if you have other requirements.

This is only a stopgap until Mgmt Plane supports the new Azure Identity classes.

```
using JonGallant.Azure.Identity.Extensions;

var appInsightsClient = new SqlManagementClient(new DefaultAzureMgmtCredential());
```

**Comment by jongio** [comment]
Closing as the user account used to open this issue has been deleted and it was opened in 2018.
