### ISSUE TITLE
Reenable ListBlobsFlatSegmentAsync_PreservesWhitespace test

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#8113]
While implementing https://github.com/Azure/azure-sdk-for-net/pull/8090 I think I've hit a side effect of https://github.com/Azure/azure-sdk-for-net/pull/8090 with double encoding. When the issue gets fixed the test should be re-enabled.

cc @tg-msft

**Comment by tg-msft** [comment]
Not marking this `blocking-release` yet, but it'll probably get fixed as part of #7659
