### ISSUE TITLE
Add test for CertificateClient.GetDeletedCertificates to cover the includePending parameter

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#8130]
Now that we've added support to `CertificateClient.GetDeletedCertificates` for the `includePending` parameter documented at https://docs.microsoft.com/en-us/rest/api/keyvault/getdeletedcertificates/getdeletedcertificates we should add test coverage for this.

**Comment by pallavit** [comment]
@heaths is this still valid?

**Comment by heaths** [comment]
Valid? Yes. Worthwhile? No. I echo some SDK architects that we shouldn't be testing every little facet of service behavior. Please reopen if you disagree.
