### ISSUE TITLE
Allow customers to parse certificate, key, and secret IDs from URLs

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#8142]
We had an internal customer request to allow customers to pass a URI to methods instead of just a name, since, for example, customers can copy the URI from the portal and wouldn't otherwise have to parse the name out themselves.

Things to consider,

* Do we provide method overloads to take a Uri, or just expose (through abstraction, perhaps) our existing internal APIs that parse it for them?
* If the methods to take a full Uri, do we assert that it has the same base Uri for which the client class was instantiated?

**Comment by schaabs** [comment]
@heaths, perhaps this could be solved by making KeyVaultIdentitifier public to allow people to parse the Id? I agree it's a bit more awkward than just having the method take a uri.

The other possibility is we could create classes similar to the KeyResolver, which is vault agnostic, for Secrets and Certificates.

**Comment by heaths** [comment]
+1 on the idea of a `KeyResolve`-like helper.

**Comment by g2vinay** [comment]
Yeah, the resolver helper can work.
But its implementation details are not quite straight, 
as with Key Resolver we have the Crypto client tied to a Key.

In Secret, Key and Certificate cases clients are tied to vault.
We will need to validate that key vault identifers are of the vault to which client is configured for too.

**Comment by heaths** [comment]
Note: based on [guidelines](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/exceptions-and-performance#try-parse-pattern), we should also provide a throwing variant of the `TryParse` method.
