### ISSUE TITLE
[P1] Storage: Remove StorageProgress type

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#8145]
https://apiview.azurewebsites.net/Assemblies/Review/b48340c11dab4e88b3b2bd269bc03661#Azure.Storage.Common.StorageProgress

Per the comments, we're going to remove the type entirely and update our code to use `Progress<long>` instead of `IProgress<StorageProgress>`.

**Comment by pakrym** [comment]
@KrzysztofCwalina why should we use the implementation type `Progress<>` instead of the `IProgress<>` interface?

**Comment by KrzysztofCwalina** [comment]
So people can new up the type they see in the signature.

**Comment by pakrym** [comment]
Isn't this a pretty advanced scenario and a very easy implementation to find? What if they don't want the behavior it provides?
