### ISSUE TITLE
[P2] Storage: Rename *Metrics.IncludeAPIs to IncludeApis

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#8156]
https://apiview.azurewebsites.net/Assemblies/Review/231f6f1802d44c8e9f7c1bfe0819a413#Azure.Storage.Queues.Models.QueueMetrics

We have one for Blobs/Files/Queues

**Comment by ShivangiReja** [comment]
Closed with https://github.com/Azure/azure-sdk-for-net/pull/8204
