### ISSUE TITLE
[P1] Storage: Make GeoReplicationStatus a regular enum

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#8158]
https://apiview.azurewebsites.net/Assemblies/Review/231f6f1802d44c8e9f7c1bfe0819a413#Azure.Storage.Queues.Models.GeoReplicationStatus

We have one for Blobs/Files/Queues.  Note that it will get renamed by #8148.

**Comment by ShivangiReja** [comment]
Files: We don't have `GeoReplicationStatus` in Files.
Blobs: It is already a regular enum for Blobs.
Queues: [PR ](https://github.com/Azure/azure-sdk-for-net/pull/8197) is out to make this a regular enum for Queues.

**Comment by ShivangiReja** [comment]
Closed with https://github.com/Azure/azure-sdk-for-net/pull/8197#event-2723097278
