### ISSUE TITLE
[BUG] Azure.Storage.Blobs namespace is not recognized, when some other Azure NuGets added to the project.

### ISSUE THREAD

**Issue by pavolkov** [Azure/azure-sdk-for-net#8169]
**Describe the bug**
Looks like some incompatibility issue of NuGet
               PackageReference Include="Azure.Storage.Blobs" Version="12.0.0-preview.3" 
with some other Azure NuGets. For example adding the NuGet below to the same project  
               PackageReference Include="Microsoft.Azure.KeyVault" Version="3.0.4" 
makes the VS not recognizing "using Azure.Storage.Blobs;"
and the Build throwing Error	"CS0234	The type or namespace name 'Storage' does not exist in the namespace 'Microsoft.Azure' (are you missing an assembly reference?)"	 

There are other packages, which are causing the same issue.

***Exception or Stack Trace***
1. "CS0234	The type or namespace name 'Storage' does not exist in the namespace 'Microsoft.Azure' (are you missing an assembly reference?)"	

2. "using Azure.Storage.Blobs;" line of code is underscored by Visual Studio. 

**To Reproduce**
1. Add the following packages into the project:
       "Azure.Storage.Blobs" Version="12.0.0-preview.3"
       "Microsoft.Azure.KeyVault" Version="3.0.4"
2.  Create new CS file and add "using Azure.Storage.Blobs;" with some sample API call.
3.  Build the project. The build should fail with "CS0234	The type or namespace name 'Storage' does not exist in the namespace 'Microsoft.Azure' (are you missing an assembly reference?)"	

***Code Snippet***
Add the code snippet that causes the issue.
using Azure.Storage.Blobs.Models;
...
UserDelegationKey key = await blobClient.GetUserDelegationKeyAsync(
                    now,
                    now.AddDays(this.UserDelegationPeriodDays));

**Expected behavior**
UserDelegationKey is recognized as a member of Azure.Storage.Blobs.Models.

**Screenshots**
![image](https://user-images.githubusercontent.com/41705481/66962559-231c6e00-f026-11e9-842a-25c3b4d98b0b.png)

**Setup (please complete the following information):**
 - OS: Windows 10 Entrprise
 - IDE : VS2019 16.3.1
 - Version of the Library used
     "Azure.Storage.Blobs" Version="12.0.0-preview.3"

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by sunildixit** [comment]
@loarabia Any update on this one?

**Comment by loarabia** [comment]
@pavolkov My guess of the issue is that the older KeyVault package (v3) has an internal dependency on an earlier storage package version. My belief would be to update KeyVault to V4 which we are previewing alongside the Storage V12 library. Below are pointers to the libraries.

$> dotnet add package Azure.Storage.Blobs --version 12.0.0-preview.4
$> dotnet add package Azure.Storage.Blobs.Batching --version 12.0.0-preview.4
$> dotnet add package Azure.Storage.Queues --version 12.0.0-preview.4
$> dotnet add package Azure.Storage.Files --version 12.0.0-preview.4

$> dotnet add package Azure.Security.KeyVault.Secrets --version 4.0.0-preview.5
$> dotnet add package Azure.Security.KeyVault.Keys --version 4.0.0-preview.5
$> dotnet add package Azure.Security.KeyVault.Certificates --version 4.0.0-preview.5

Assuming that guess of the issue is right (@AlexGhiondea  and @kurtzeborn can you confirm)? I'm wondering if we severed that dependency so that we could roll these libraries forward independently.

**Comment by sergiosolorzano** [comment]
Happening to me too. I'm working on an Azure Function App. Is there another way to use blob? I'm currently using: using System;
using System.IO;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.Build.Framework;
using Newtonsoft.Json;

These fail. I tried adding Microsoft at the front to no avail.
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Models;

**Comment by seanmcc-msft** [comment]
What does your csproj file for your project look like?

**Comment by sergiosolorzano** [comment]
Thank you @seanmcc-msft , yes I had added Azure.Storage.Blobs. I then started with a new fresh project and reinstalled all packages and it worked fine, possibly an extra package i added that messed things

**Comment by mayank1495** [comment]
@seanmcc-msft 
Probably the issue persists or may be am missing something out.
If I install **Azure.Storage.Blobs**  along with **Microsoft.Azure.KeyVault** or **Microsoft.Azure.Services.AppAuthentication** , it gives the same namespace error as originally mentioned in this thread.
Please help.

**Comment by ShubhamRane** [comment]
+1 @mayank1495

**Comment by gazabhi** [comment]
Do we have a solution for this? I am also facing a similar issue. Despite the package reference for azure.storage.blobs is present, I am getting build errors saying it's not recognized.

**Comment by chpence** [comment]
Here's a solution that may help. Add the `global::` qualifier to the namespaces which have the issue:

```csharp
using global::Azure.Storage.Blobs;
```

**Explanation**: From the error message, we can tell the `Azure.*` namespaces are being mistakenly resolved as `Microsoft.Azure.*` namespaces. This can happen if your own namespace looks like `Microsoft.*` and you have references to both Azure namespaces in your project.

So when you write something like:

```csharp
namespace Microsoft.Foo.Bar.Baz
{
    using Azure.Storage.Blobs; // Becomes `using Microsoft.Azure.Storage.Blobs;`
}
```

there is an implicit `Microsoft.` that is prepended to the namespace, causing the error above if that namespace does not exist in your project.  The `global::` qualifier prevents this implicit interpretation of the namespace.
