### ISSUE TITLE
[P1] Storage: Rename ParallelTransferOptions to StorageTransferOptions

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#8179]
https://apiview.azurewebsites.net/Assemblies/Review/b48340c11dab4e88b3b2bd269bc03661#Azure.Storage.Common.ParallelTransferOptions

**Comment by ShivangiReja** [comment]
Closed with https://github.com/Azure/azure-sdk-for-net/pull/8201
