### ISSUE TITLE
Adjustments to the .Net daily dev builds

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk-for-net#8181]
- [x] Versioning - we need to update all of the the `VersionPrefix` properties in the repo to include the prerelease preview tag always.
- [ ] ~Update the [guidance](https://github.com/Azure/azure-sdk/blob/master/docs/policies/releases.md) for daily dev build version to be the following format: `X.Y.Z-preview.x.YYYYMMDD.r`~
- [x] We need to change the build to add the daily dev prefix to our scheduled nightly builds only.
- [x] Integrate the above into publishing in the unified pipelines.  Clean up the old versioning properties in the pipelines as well.
- [x] Update the [versioning doc](https://github.com/Azure/azure-sdk-for-net/blob/master/Documentation/Versioning.md) in the .Net repo (and add a link/blurb into the contributing.md)
  - [x] Update the links in the DevOps wiki if we decide to merge versioning.md into contributing.md
- [ ] [Stretch] Decide whether to move to a DevOps feed instead of the blobs based feed

**Comment by mitchdenny** [comment]
> * daily dev prefix

@kurtzeborn just to clarify - do you mean "add the daily dev suffix" ?

**Comment by weshaggard** [comment]
We have done everything here except moving from blob feed to DevOps feed. At least for now we will stick with the blob feed to prevent folks that are currently consuming it to be broken and require updating. The switch the DevOps feed doesn't seem worth the extra effort at this point.
