### ISSUE TITLE
Add Azure.Core.Testing Package

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk-for-net#8195]
We need a package with implementations of our pipeline abstractions to make Mocking scenarios easy. For example, in many mocking scenarios and instance of Azure.Response needs to be created in the mock, but we don't provide any public way to create such instances.

[corrected spelling]

**Comment by gliljas** [comment]
One year later, any progress on this? I was first happy to see that so many methods on e.g BlobServiceClient were virtual and therefore mockable, only to realize that very much is implemented using internal methods wrapped in extension methods.

**Comment by JoshLove-msft** [comment]
Related to https://github.com/Azure/azure-sdk-for-net/issues/28462

**Comment by KrzysztofCwalina** [comment]
@annelo-msft, FYI

**Comment by annelo-msft** [comment]
Related to moving TestFramework types into a public library.

It would be good to reconcile vs what's recommended in https://devblogs.microsoft.com/azure-sdk/unit-testing-and-mocking/#response.

**Comment by JimSuplizio** [comment]
Hi @KrzysztofCwalina, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
