### ISSUE TITLE
LoggingPolicy does not check if tracing is enabled before doing more expensive formatting

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#8208]
In LoggingPolicy.cs:
```c#
s_eventSource.Request(request.ClientRequestId, request.Method.ToString(), FormatUri(request.Uri), FormatHeaders(request.Headers));
```
This does not follow guidance from azure/azure-sdk#645 to check EventSource.IsEnabled() first before expensive formatting. There may be other places as well.

**Comment by pakrym** [comment]
The entire policy is skipped if the event source is disabled.
