### ISSUE TITLE
Re-enable Get() that takes an acceptDateTime

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#8211]
Begun in https://github.com/Azure/azure-sdk-for-net/pull/8209

**Comment by AlexGhiondea** [comment]
Is this additive? If so, it can come in next week.

**Comment by annelo-msft** [comment]
Yes, it is -- removing blocking release tag.

**Comment by AlexanderSher** [comment]
Add the third overload with `ConfigurationSetting setting, DateTimeOffset acceptDateTime)`
