### ISSUE TITLE
Parse and make Error object available on RequestFailedException

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#8215]
It came up from an internal customer that .NET is not exposing the Error object from failed requests. Other languages are doing this. We could, when requested, parse out [common Error object](https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#7102-error-condition-responses) properties (like "error" - might be a couple other ones we could check for) from the response we already have to make this available. This parsing could also be virtual so Storage (/cc @tg-msft) could proffer errors from their response headers.

Seems this was also discussed based on #8143, but seemed storage specific. We might want to consider this more generally.

**Comment by pakrym** [comment]
We expose message, error code, and data (inherited from base exception). We don't currently expose target.

**Comment by AlexGhiondea** [comment]
It doesn't look like this is something we want to do. In that case, @pakrym please close this.

**Comment by tg-msft** [comment]
Azure.Core has enough hooks that we're able to do this [on top of them for Storage](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/StorageRequestFailedException.cs#L50).  Probably won't be supported by the new generator in the same way or for some time.

**Comment by pakrym** [comment]
cc @annelo-msft FYI, now that we have `AzureError` type and the new `RequestFailedException(Response)` ctor it might be time to add AzureError as a property to RequestFailedException

**Comment by pakrym** [comment]
I'm not sure whether it's worth exposing at all as the only two properties it has are already on the exception itself.
