### ISSUE TITLE
Operation<T>.WaitForCompletion should trace an activity for the entire duration

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#8226]
Though we have `DiagnosticScope` for REST calls, it would be advantageous to trace, measure, and adjust total polling times for `Operation<T>` by starting and stopping an activity for the entire duration of `WaitForCompletionAsync`.

```c#
public static async ValueTask<Response<TResult>> DefaultWaitForCompletionAsync<TResult>(this Operation<TResult> operation, TimeSpan pollingInterval, CancellationToken cancellationToken)
    where TResult : notnull
{
    EventSource.SetCurrentThreadActivityId(Guid.NewGuid(), out Guid oldActivityId);
    try
    {
        while (true)
        {
            await operation.UpdateStatusAsync(cancellationToken).ConfigureAwait(false);
            if (operation.HasCompleted)
            {
                return Response.FromValue(operation.Value, operation.GetRawResponse());
            }

            await Task.Delay(pollingInterval, cancellationToken).ConfigureAwait(false);
        }
    }
    finally
    {
        Eventsource.SetCurrentThreadActivityId(oldActivityId);
    }
}
```

**Comment by pakrym** [comment]
cc @kinelski

**Comment by jsquire** [comment]
@lmolkova :  Your thoughts on whether this fits our OTel strategy would be appreciated.

**Comment by lmolkova** [comment]
yes, this aligns with out distributed tracing policy https://azure.github.io/azure-sdk/general_implementation.html#distributed-tracing

We should create one span for public methods that result in 1+ server calls which includes `WaitForCompletion`. We'd end up with nested `UpdateStatusAsync` spans under `WaitForCompletion`, but we have means to suppress them.

**Comment by pallavit** [comment]
@jsquire I am moving this to Azure.Core project? Are you tagging OTel issues with anything special?

**Comment by JimSuplizio** [comment]
Hi @heaths, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
