### ISSUE TITLE
[P0] Storage: Rename Batching -> Batch

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#8229]
Since batching went out at the very last minute during Preview 4 in both .NET and Java, we missed that our names weren’t aligned.
- Java: azure-storage-blob-batch
- .NET: Azure.Storage.Blobs.Batching

The architects briefly huddled and decided to make .NET match Java.  We’ll change the namespace, assembly, and package to Azure.Storage.Blobs.Batch.

**Comment by tg-msft** [comment]
Also, update the artifact names in the ci.yml as part of the rename

**Comment by ShivangiReja** [comment]
Closed with https://github.com/Azure/azure-sdk-for-net/pull/8350
