### ISSUE TITLE
Microsoft.WindowsAzure.Management.Monitoring.Alerts CreateOrUpdateAsync Error

### ISSUE THREAD

**Issue by cmonney** [Azure/azure-sdk-for-net#823]
I am trying to create an Azure alert using the AlertsClient

My resourceid looks like the following:

```
        var resourceId = ResourceIdBuilder.BuildCloudServiceResourceId(
            "<cloud service name>", 
            "<deployment name>",
            "<role name>");
```

My create method is as follows:

 private static Task<OperationResponse> CreateAzureAlert(string resourceId, AlertsClient alertsClient)
        {
            var rule = new Rule
            {
                Name = "CPU Alert",
                Id = Guid.NewGuid().ToString(),
                Description = "If CPU usage is greater than twenty percent then alert",
                IsEnabled = true,
                Condition = new ThresholdRuleCondition
                {
                    Operator = ConditionOperator.GreaterThan,
                    Threshold = 10,
                    WindowSize = TimeSpan.FromMinutes(15), //new TimeSpan(0,0,5,0),
                    DataSource = new RuleMetricDataSource
                    {
                        MetricName = "Percentage CPU",
                        ResourceId = resourceId,
                        MetricNamespace = "WindowsAzure.Availability"
                    }
                }
            };

```
        RuleAction action = new RuleEmailAction
        {
            SendToServiceOwners = true
        };

        ((RuleEmailAction) action).CustomEmails.Add("email@address.com");
        rule.Actions.Add(action);
        rule.LastUpdatedTime = DateTime.UtcNow;

        var response = alertsClient.Rules.CreateOrUpdateAsync(new RuleCreateOrUpdateParameters
        {
            Rule = rule
        }, CancellationToken.None);

        return response;
    }
```

The error message I am getting is:
{"<string xmlns=\"http://schemas.microsoft.com/2003/10/Serialization/\">{\"Code\":\"InvalidRequest\",\"Message\":\"Could not find any metric definitions.\"}</string>"}

Please check and let me know if I am doing something wrong. Many thanks

**Comment by shahabhijeet** [comment]
please reopen if this is still an issue.
