### ISSUE TITLE
PlaybackTransport is not using the AsyncValidatingStream

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#8232]
I noticed that `ClientTestBase` is not using the `AsyncValidatingStream`, so live tests are not fully validating whether sync or async code was used. We might want to fix that, though there will be a bug tail we'll have to fix (I'm opening a separate such bug against Key Vault after this).

**Comment by JoshLove-msft** [comment]
This is obsolete with the move to Test Proxy.
