### ISSUE TITLE
[BUG] ServiceFabricProcessor throws an unexpected OperationCanceledException exception

### ISSUE THREAD

**Issue by dmytro-gokun** [Azure/azure-sdk-for-net#8280]
This bug is similar to https://github.com/Azure/azure-sdk-for-net/issues/7933
The difference is the type of the exception thrown (+ I have some more details now).

1. ProcessErrorAsync is called with the following exception:

```
System.OperationCanceledException: The operation was canceled.
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.ReceivingAmqpLink.EndReceiveMessages(IAsyncResult result, IEnumerable`1& messages)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.EventHubs.Amqp.AmqpPartitionReceiver.OnReceiveAsync(Int32 maxMessageCount, TimeSpan waitTime)
   at Microsoft.Azure.EventHubs.Amqp.AmqpPartitionReceiver.OnReceiveAsync(Int32 maxMessageCount, TimeSpan waitTime)
   at Microsoft.Azure.EventHubs.PartitionReceiver.ReceiveAsync(Int32 maxMessageCount, TimeSpan waitTime)
   at Microsoft.Azure.EventHubs.Amqp.AmqpPartitionReceiver.ReceivePumpAsync(CancellationToken cancellationToken, Boolean invokeWhenNoEvents)
{"Type":"System.OperationCanceledException", "CancellationToken":{"IsCancellationRequested":false, "CanBeCanceled":false, "WaitHandle":{"Handle":"2244", "SafeWaitHandle":{"IsInvalid":false, "IsClosed":false}​}}, "TargetSite":"Void Throw()", "StackTrace":"   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.Azure.Amqp.ReceivingAmqpLink.EndReceiveMessages(IAsyncResult result, IEnumerable`1& messages)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.Azure.EventHubs.Amqp.AmqpPartitionReceiver.OnReceiveAsync(Int32 maxMessageCount, TimeSpan waitTime)\r\n   at Microsoft.Azure.EventHubs.Amqp.AmqpPartitionReceiver.OnReceiveAsync(Int32 maxMessageCount, TimeSpan waitTime)\r\n   at Microsoft.Azure.EventHubs.PartitionReceiver.ReceiveAsync(Int32 maxMessageCount, TimeSpan waitTime)\r\n   at Microsoft.Azure.EventHubs.Amqp.AmqpPartitionReceiver.ReceivePumpAsync(CancellationToken cancellationToken, Boolean invokeWhenNoEvents)", "Message":"The operation was canceled.", "Data":{}, "Source":"System.Private.CoreLib", "HResult":-2146233029}
```

2. CloseAsync is called with Reason = Cancelled

3. ServiceFabricProcessor.RunAsync throws

```
System.OperationCanceledException: The operation was canceled.
   at Microsoft.Azure.EventHubs.ServiceFabricProcessor.ServiceFabricProcessor.RunAsync(CancellationToken fabricCancellationToken)
   at MyClass.RunAsync(CancellationToken cancellationToken)
```

The important thing here is that the CancellationToken passed to ServiceFabricProcessor.RunAsync() is NOT cancelled.

@JamesBirdsall Does this information help in any way?

**Comment by adrianhall** [comment]
@dmytro-gokun Can you please provide information on what NuGet package you are using please?

**Comment by dmytro-gokun** [comment]
@adrianhill Okay, now i see something interesting. I'm referencing Microsoft.Azure.EventHubs.ServiceFabricProcessor version 0.5.5. But. That version is not even listed at https://www.nuget.org/packages/Microsoft.Azure.EventHubs.ServiceFabricProcessor/

Have it been somehow revoked?

**Comment by adrianhall** [comment]
I'd have to check with the service team to be sure.  However, that does happen if we know of a major issue.  To get you going, I'd downgrade to 0.5.4 (the latest version listed on NuGet), and see if you still experience the problem.

**Comment by dmytro-gokun** [comment]
@adrianhall Thanks. I'll try downgrading, give it a spin for a week or so and let you know if I see this again.

**Comment by adrianhall** [comment]
Thanks - will close on 11/15/2019 unless we hear something.

**Comment by peterpogorski** [comment]
@dmytro-gokkun please confirm that this is working for you. @sjkwak @JamesBirdsall FYI.

**Comment by dmytro-gokun** [comment]
@peterpogorski So far, I have not seen this exact scenario with 0.5.4. However, this kinds of situations happen rarely in general, so i want to give it some more time to run before closing the issue.

**Comment by dmytro-gokun** [comment]
I can now confirm that this exact issue exists with 0.5.4. I've seen it happening several times over this last weekend.

**Comment by adrianhall** [comment]
Thanks for the update and validation.
