### ISSUE TITLE
Remove InMemoryPartitionManager for Event Processor

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#8286]
# Summary

The current version of the `EventProcessorClient` includes an `InMemoryPartitionManager` instance as part of the core package.  This was intended to assist with the onboarding experience, but has been determined to be potentially confusing to developers new to the Event Hubs client library, and could establish anti-patterns as an implied way of using the processor in production.   It should be removed and used as a simple example, in order to better clarify the scope of its intended use.

# Scope of Work

- Remove the `InMemoryPartitionManager` from the core Event Hubs client library.

- Reconsider its use in samples, to provide the intended example of an approachable on-boarding experience for new developers.

- Adjust implementation details as needed to keep existing functionality and work within the new sample context.

- Add, remove, or adjust tests to cover the new API and ensure its functionality.

# Out of Scope

- Updates or changes to the other core types which are not related to removing the `InMemoryPartitionManager`.

# Success Criteria

- The `InMemoryPartitionManager` is no longer available as part of the core Event Hubs client library.

- Samples have been updated to continue to illustrate an approachable on-onboarding for new developers, containing a local version of the `InMemoryPartitionManager` should it be deemed appropriate for the sample.

- The existing test suite continues to produce deterministic results and pass reliably.

**Comment by ShivangiReja** [comment]
Closed with https://github.com/Azure/azure-sdk-for-net/pull/8773
