### ISSUE TITLE
[BUG] API version mismatch using AppAuthentication with managed identities and Service Fabric

### ISSUE THREAD

**Issue by MarcWils** [Azure/azure-sdk-for-net#8298]
**Description**
We're trying to get AppAuthentication to work with managed identities on a service fabric cluster. We use the SqlAuthenticationProvider to get authenticate against an Azure SQL database. There's a mismatch between the API version used by the [MsiAccessTokenProvider](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/mgmtcommon/AppAuthentication/Azure.Services.AppAuthentication/TokenProviders/MsiAccessTokenProvider.cs#L104) and the API version supported by the [Service Fabric Managed Identity Token Service] (https://docs.microsoft.com/en-us/azure/service-fabric/how-to-managed-identity-service-fabric-app-code#acquiring-an-access-token-using-rest-api).

MsiAccessTokenProvider uses either `2017-09-01` or `2018-02-01`. The Service Fabric MITS accepts only `2019-07-01-preview`.

***Exception***
Exception Message: Tried to get token using Managed Service Identity. Access token could not be acquired. Received a non-retryable error. MSI ResponseCode: BadRequest, Response: {"error":{"correlationId":"9ff07b76-2fda-4c87-8194-48ef8de0c47f","code":"InvalidApiVersion","message":"The api-version '2017-09-01' is not supported. Supported version is '2019-07-01-preview'."}}

**Comment by amenarde** [comment]
AppAuthentication does not support service fabric managed identities today. [Here AppAuthentication lists the two types of identities it supports](https://docs.microsoft.com/en-us/azure/key-vault/service-to-service-authentication#running-the-application-using-managed-identity-or-user-assigned-identity) as well as in [the code you linked to](https://github.com/Azure/azure-sdk-for-net/blob/6cf81ccbb614029fbeca89b6665fd32a75f714f3/sdk/mgmtcommon/AppAuthentication/Azure.Services.AppAuthentication/TokenProviders/MsiAccessTokenProvider.cs#L12-L15), which is AppService identities and VMSS identities.

There is no plan to integrate with AzureServiceTokenProvider during SF MI's preview period, but it is targeted to be integrated during GA. In the meantime, [the link you gave is the current way to leverage service fabric identities](https://docs.microsoft.com/en-us/azure/service-fabric/how-to-managed-identity-service-fabric-app-code).

**Comment by dragav** [comment]
Please also see [Supported Scenarios for SF Managed Identity](https://docs.microsoft.com/en-us/azure/service-fabric/concepts-managed-identity#supported-scenarios-for-service-fabric-applications): "SF support for managed identities is not integrated at this time into the AzureServiceTokenProvider".
