### ISSUE TITLE
New version of Microsoft.Azure.ServiceBus NuGet that works with System.IdentityModel.Tokens.Jwt 6.1.0

### ISSUE THREAD

**Issue by zoltanromocsa** [Azure/azure-sdk-for-net#8308]
**Query/Question**
A clear and concise ask/query.

Is there a timeline to release a version of the Microsoft.Azure.ServiceBus NuGet package that works with System.IdentityModel.Tokens.Jwt 6.1.0?
The current version (4.0.0) requires System.IdentityModel.Tokens.Jwt (>= 5.4.0 && < 6.0.0).

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?
This is not a report of an actual issue. I am just curious when a new version of the Microsoft.Azure.ServiceBus NuGet package will become available.

**Setup (please complete the following information if applicable):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by jfggdl** [comment]
@zoltanromocsa, Thank you for raising this issue. We have started working on how we can package support for JWT 6.1.0 in our SDKs.

@ramya-rao-a, it looks like the dependency in any given version of JWT is shared among all the SDKs per the new packaging scheme. Would you be able to help us with this issue?

**Comment by jsquire** [comment]
> @zoltanromocsa, Thank you for raising this issue. We have started working on how we can package support for JWT 6.1.0 in our SDKs.
> 
> @ramya-rao-a, it looks like the dependency in any given version of JWT is shared among all the SDKs per the new packaging scheme. Would you be able to help us with this issue?

I can;  the version can be overridden on an individual project basis for those with a need to drift from the centralized dependency.  The trade-off, of course, is having package conflicts if the version that Service Bus takes a dependency on isn't compatible with another library used by the same consumer.

@nemakam:  Feel free to reach out as needed.

**Comment by nemakam** [comment]
@jsquire, are you suggesting ServiceBus to override this version support in its package? How do we go about deciding whether this needs to be changed across all the SDKs (at repo level)?

**Comment by jsquire** [comment]
> @jsquire, are you suggesting ServiceBus to override this version support in its package? How do we go about deciding whether this needs to be changed across all the SDKs (at repo level)?

Generally speaking, there is a [dependency report](https://azuresdkartifacts.blob.core.windows.net/azure-sdk-for-net/dependencies/dependencies.html) which you can reference to see what dependencies are referenced by which libraries in the repository.   In this case, the JWT library has a few different consumers that I know of and is know to have some challenges with backwards compatibility.   

In the particular case of Service Bus, I'd say that the safer path would be to override the global version.   The alternative would be to upgrade globally and take responsibility for ensuring that the other libraries don't experience regressions or incompatibilities - which seems like it may be a non-trivial effort.

In the event that you decide to go with the override, the syntax would be local to your project files and look something like:
`<PackageReference Include="Some.Package.Name" VersionOverride="1.0.4" />`,  where the standard version range syntax for references is valid.

**Comment by nemakam** [comment]
The latest public version of that library is 5.6.0. 
https://www.nuget.org/packages/System.IdentityModel.Tokens.Jwt/
