### ISSUE TITLE
[P0] Storage: Rename LeaseClient to BlobLeaseClient

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#8323]
We want to change the type name to `BlobLeaseClient` and the `GetLeaseClient()` methods to `GetBlobLeaseClient()`.  All the other methods, properties, test names, etc., should stay the same to minimize churn.

**Comment by ShivangiReja** [comment]
Closed with https://github.com/Azure/azure-sdk-for-net/pull/8328
