### ISSUE TITLE
[Storage][DataLake] Clean up generated code for DataLake

### ISSUE THREAD

**Issue by amnguye** [Azure/azure-sdk-for-net#8346]
In reference to pull request #8235 , clean up needs to be done for the swagger to ensure it matches the REST API for Azure Data Lake. There are some parameters are are unused and not required and there are some parameters that are required but are marked nullable/optional in the generated code.

For example,
For Append in FileClient, the exposed api is correct that we require the "position" parameter but in the generated code it is nullable.

**Comment by JimSuplizio** [comment]
Hi @amnguye, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
