### ISSUE TITLE
How can I create a VM in MS Azure along with Chef Client through Microsoft Azure Management Libraries?

### ISSUE THREAD

**Issue by Robin2009** [Azure/azure-sdk-for-net#838]
Hi all,
    My question is nothing about any issue but it's quite important to me. Right now I was asked to develop a client(WinForm or Mvc) to create virtual machines along with Chef client. In azure management portal page this stuff seems easy enough because we're able to choose to install VM agent and then choose to install Chef Client or other trustable extensions in the last step of "Create Virtual Machine". But how could it be done through this api (not rest api)?  I googled a lot of resource but didn't find anything helpful, no demo, no sample code at all. So anyone here please give me any suggestion? Any idea will be appreciated. Thanks.

**Comment by singhkay** [comment]
@Robin2009 Are you trying to do this PowerShell? or the Azure Compute .NET Client library?

**Comment by singhkay** [comment]
Closing as haven't heard back from OP in 6 months. Please reopen if still an issue
