### ISSUE TITLE
Feature Request - Azure ServiceRuntime - Add Fields

### ISSUE THREAD

**Issue by sporty81** [Azure/azure-sdk-for-net#839]
Please enhance the Azure ServiceRuntime so there is a way to get these fields from cloud services.

Slot - Staging/Production
Service Name - Can get the instance name, but we want to know the name of the deployment itself.
SubscriptionId

Thank you!!

**Comment by singhkay** [comment]
@sporty81 - Is this a feature request for the Compute client library or the REST API?

**Comment by sporty81** [comment]
@singhkay Would be nice if these fields were on the cloud service machine themselves in the registry, environment keys, or available from the ServiceRuntime.dll. Not talking about REST. Talking about just what you can get from the on the machine.

**Comment by singhkay** [comment]
@sporty81 Got it, let me forward this feedback to the right team

**Comment by shahabhijeet** [comment]
please reopen if this is still an issue.
