### ISSUE TITLE
[Storage][DataLake] Look into finding a way to auto-gen the Blob models -> DataLake models transformations

### ISSUE THREAD

**Issue by seanmcc-msft** [Azure/azure-sdk-for-net#8393]
https://github.com/Azure/azure-sdk-for-net/pull/8235

**Comment by JimSuplizio** [comment]
Hi @seanmcc-msft, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
