### ISSUE TITLE
[P1] Storage: Use null instead of empty dictionary when metadata wasn't requested

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#8397]
Per the [discussion in the API review](https://apiview.azurewebsites.net/Assemblies/Review/c52f059a-6d57-4d40-b7d2-a5816565a660#Azure.Storage.Blobs.Models.BlobItem), we're going to go with `null` instead of an empty dictionary when you call GetBlobs() but don't request any metadata to be returned.

This should happen for Blobs, Files, and Queues.

**Comment by ShivangiReja** [comment]
Closed with https://github.com/Azure/azure-sdk-for-net/pull/8457
