### ISSUE TITLE
Storage: Update XML doc comments

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#8400]
Update our doc comments per https://aka.ms/sdkdocsoverview and ensure they reflect all our latest changes and have helpful conceptual content.

**Comment by JimSuplizio** [comment]
Hi @tg-msft, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
