### ISSUE TITLE
readme.md issues in Identity

### ISSUE THREAD

**Issue by AlexanderSher** [Azure/azure-sdk-for-net#8432]
- [ ] [Introduction](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/identity/Azure.Identity#azure-identity-client-library-for-net): missing "Samples" link
- [ ] [Key concepts](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/identity/Azure.Identity#credentials): subsection headers (Credentials, DefaultAzureCredential and Environment variables) should be L3
- [ ] [Examples](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/identity/Azure.Identity#credentials): it would be useful to have a list of all examples at the beginning of the section
- [ ] [Examples](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/identity/Azure.Identity#credentials): subsection headers should be L3
- [ ] Update readme to not refer to Azure.Identity as prerelease

**Comment by schaabs** [comment]
Fixed via https://github.com/Azure/azure-sdk-for-net/pull/8887
