### ISSUE TITLE
Expose `MessageCount` values in paged namespace queries

### ISSUE THREAD

**Issue by tmasternak** [Azure/azure-sdk-for-net#8434]
**Query/Question**

It looks that the `MessageCount` values are [available](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Microsoft.Azure.ServiceBus/src/Management/QueueDescriptionExtensions.cs#L144) at the client-side when `GetQueueAsync()` is executed via Azure ServiceBus client. 

***Why is this not a Bug or a feature Request?***
This is a performance improvement. Currently `MessageCount` value for a queue is accessible via property on [QueueRuntimeInfo](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Microsoft.Azure.ServiceBus/src/Management/QueueRuntimeInfo.cs#L26) class. 

When querying for multiple `MessageCount` values in the namespace at once there are 1+n requests needed. 

First, one to get a list of available queues in the namespace via

>  managementClient.GetQueuesAsync()    

and later, n calls for each queue to get the QueueRuntimeInfo:

> managementClient.GetQueueRuntimeInfoAsync()

**Setup (please complete the following information if applicable):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by jfggdl** [comment]
@tmasternak, thank you for creating this issue. We had a conversation with our engineering team. We are adding to our backlog and we will be considering to implement this feature.

**Comment by tmasternak** [comment]
@jfggdl thank you for the information. Would it be helpful if I created for this PR? 

My initial thought was to add `MessageCount` property to the `QueueDescription`?

**Comment by nemakam** [comment]
The plan was to separate runtime properties like `MessageCount` which might have to be aggregated over multiple partitions and nodes at runtime before returning it, and the static content which are part of `QueueDescription` which can be fetched easily from anywhere. Initially they were bundled together as one giant method. The aim was to separate them out so that we optimize resource usage.
Adding `MessageCount` back to `QueueDescription` doesn't help with this. An alternate would be to allow fetching `QueueRuntimeInformation` for all the queues at once instead of one-by-one.

**Comment by nemakam** [comment]
@tmasternak , sorry, but this needs further discussion internally and I'd like you to hold off on a new PR creation for this for now.

**Comment by tmasternak** [comment]
@nemakam thank you for sharing the context. I think that splitting configuration and runtime data at the API level makes perfect sense.

That said, it would be great if there was a way to get runtime data without 1+n access pattern. This obviously assumes that ASB internals enables to gathering data about multiple entities in one request. Otherwise, I would question exposing paged runtime data at the API level as well.

**Comment by jsquire** [comment]
Moving this to the backlog milestone, as the associated sprint has passed.

@axisc:  I removed the outdated assignment.  Would you be so kind as to help route to the appropriate individual?

**Comment by tmasternak** [comment]
If I can help in any e.g. opening a PR just let me know.

**Comment by nemakam** [comment]
@tmasternak , we had an internal discussion, and we are okay with this change.
Feel free to raise a PR for this. Take a look at existing `GetQueues` and `GetQueueRuntimeInfo` implementation and you should be able to figure it out.

**Comment by tmasternak** [comment]
@nemakam I've opened a PR which proposes adding a new method to `ManagementClient`. I started off adding the `MessageCount` to the `QueueDescription` but realized that it's designed with library client modifications in mind i.e. all property setters are public. Adding a new `MessageCount` property could lead to confusion as it's a read-only value contrary to all the other values.

As a result, I've added a dedicated method similar to `GetQueuesAsync` that returns queue runtime information in pages. Please have a look.
