### ISSUE TITLE
[QUERY] SignAsync from the Azure app service

### ISSUE THREAD

**Issue by oleksabor** [Azure/azure-sdk-for-net#8437]
**Query/Question**
Dears

Please help me to connect to the Azure KeyVault from the Azure app service and query the service for signature. The question is that I can't determine ClientID for the app service instance.

I can connect to the Azure KeyVault using the code below:

```CSharp
var clientCred = new ClientCredential(cfg.ClientID, cfg.Secret);
var client = new KeyVaultClient(new KeyVaultClient.AuthenticationCallback(
	   (authority, resource, scope) => GetAccessToken(authority, resource, scope, clientCred)));

async Task<string> GetAccessToken(string authority, string resource, string scope, ClientCredential cred)
{
	var context = new AuthenticationContext(authority, TokenCache.DefaultShared);
	var result = await context.AcquireTokenAsync(resource, cred).ConfigureAwait(false);

	return result.AccessToken;
}
```
However it requires the clientid and secret to be specified. It works if clientId and secret for existing App Registration instance. 

Is it possible to change `GetAccessToken` to use app service identity somehow? Probably, I will need the `context.AcquireTokenAsync` call to be replaced with `AcquireTokenSilentAsync` but it requires client id too.

***Why is this not a Bug or a feature Request?***
It should be possible to connect to the Vault using the Azure app service. I can add one more app registration, store client id and secret for the app service and use it. But I suppose it looks surplus, since there is a possibility to grant Vault access for the app service directly

**Setup (please complete the following information if applicable):**
 - OS: Windows
 - IDE : VisualStudio 2017
 - Version of the Library used "Microsoft.Azure.KeyVault" Version="3.0.4"
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Query Added
- [ ] Setup information Added

**Comment by AlexGhiondea** [comment]
Hi!

Thanks for filling this issues. Could you add additional information about it?

Thank you!

**Comment by AlexGhiondea** [comment]
@heaths could you take a look?

**Comment by heaths** [comment]
This would be the client ID and secret output by the Azure CLI or the Azure Portal when you register your tenant. Did you follow instructions like those in the [README](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/keyvault/Azure.Security.KeyVault.Keys#createget-credentials), or something similar? You can set those up as environment variables shown in the above link.

You could also use the `DefualtAzureCredential` which supports a chain of common, different credential types that works great for hosting as a service or in a development environment (e.g. service credentials take precedent). In that case, the default credentials in a development environment can be specified as environment variables named as shown in the link above, or even a device login should work. In a service, Managed Service Identities are supported and preferred.

**Comment by oleksabor** [comment]
@heaths Thank you for a hint
I can set clientid and secret using the environment variables. However it requires new app service registration to be created (and manage the app secrets)


Seems that I need something like [AzureServiceTokenProvider](https://docs.microsoft.com/en-us/azure/key-vault/service-to-service-authentication) 
The AzureServiceTokenProvider allows app service to authenticate using the `RunAs=App` [connection string](https://docs.microsoft.com/en-us/azure/key-vault/service-to-service-authentication#connection-string-support) and sign data using the key vault client:

````CSharp
var azureServiceTokenProvider1 = new AzureServiceTokenProvider(connectionString: cfg.ConnectionString); // RunAs=App
using(var client = new KeyVaultClient(new KeyVaultClient.AuthenticationCallback(azureServiceTokenProvider1.KeyVaultTokenCallback)))
{
var signedResult = client.SignAsync(cfg.KeyName, algorithm, digest).Result; 
// keyName = https://{vaultname}.vault.azure.net/keys/{keyname}
// algorithm = JsonWebKeySignatureAlgorithm.RS512
// digest is 512 hash
}
````

Also the connection string can be set to `$"RunAs=App;AppId={config.ClientID};TenantId={config.Tenant};AppKey={config.Secret}"` for the development environment if application is started as console on dev machine for example.
