### ISSUE TITLE
readme.md issues in Storage Blobs

### ISSUE THREAD

**Issue by AlexanderSher** [Azure/azure-sdk-for-net#8444]
- [ ] [Introduction](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage/Azure.Storage.Blobs#azure-storage-blobs-client-library-for-net): What is server version for?
- [ ] [Introduction](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage/Azure.Storage.Blobs#azure-storage-blobs-client-library-for-net): missing "Samples" link. Also, do we need to have REST API reference here?
- [ ] [Prerequisites](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage/Azure.Storage.Blobs#prerequisites): Is authentication required? 
- [ ] [Prerequisites](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage/Azure.Storage.Blobs#prerequisites): Need to have list-formatted prerequisites (see [KeyVault.Keys](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/keyvault/Azure.Security.KeyVault.Keys#prerequisites))
- [ ] [Examples](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage/Azure.Storage.Blobs#examples): it would be useful to have a list of all examples at the beginning of the section

**Comment by seanmcc-msft** [comment]
This has been fixed.  https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/README.md
