### ISSUE TITLE
readme.md issues in Storage Queues

### ISSUE THREAD

**Issue by AlexanderSher** [Azure/azure-sdk-for-net#8445]
- [ ] [Introduction](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage/Azure.Storage.Queues#azure-storage-queues-client-library-for-net): Do we need server version?
- [ ] [Introduction](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage/Azure.Storage.Queues#azure-storage-queues-client-library-for-net): missing "Samples" link. Also, do we need to have REST API reference here?
- [ ] [Prerequisites](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage/Azure.Storage.Queues#prerequisites): Is authentication required? 
- [ ] [Prerequisites](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage/Azure.Storage.Queues#prerequisites): Need to have list-formatted prerequisites (see [KeyVault.Keys](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/keyvault/Azure.Security.KeyVault.Keys#prerequisites))
- [ ] [Key concepts](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage/Azure.Storage.Queues#key-concepts): can we have this section to be more descriptive?
- [ ] [Examples](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage/Azure.Storage.Queues#examples): it would be useful to have a list of all examples at the beginning of the section

**Comment by seanmcc-msft** [comment]
This has been fixed https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Queues/README.md
