### ISSUE TITLE
Doc generation CleanUp

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-for-net#8461]
- [x] Clean up `eng\pipelines\templates\steps\archetype-sdk-docs.yml` to get all the steps into single powershell script so to can easily be reproduced locally. 
- [x] Track exit codes to ensure runs are correct.
- [x] Convert management and client steps into a single step
- [x] Map service names to a friendly name on doc index
- [ ] ~~Figure our how to build doc index without losing docs for renamed packages~~
- [x] I also like the doc generation stuff under the doc\ root folder similar to python.

**Comment by kurtzeborn** [comment]
The renamed package item was tracked by a different issue (https://github.com/azure/azure-sdk/issues/761) and is cut.
