### ISSUE TITLE
Storage: Rename Files to Files.Shares

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#8477]

**Comment by tg-msft** [comment]
- package/assembly/namespace: `Azure.Storage.Files` => `Azure.Storage.Files.Shares`
- `FileServiceClient` => `ShareServiceClient`
- `ShareClient` => (same)
- `DirectoryClient` => `ShareDirectoryClient`
- `FileClient` => `ShareFileClient`

We are not changing the `GetFooClient(name)` methods.

**Comment by JoshLove-msft** [comment]
Also, rename test projects, but not individual tests.

**Comment by JoshLove-msft** [comment]
What about these:
- FileClientBuilderExtensions
- FileClientOptions
- FileUriBuilder

**Comment by tg-msft** [comment]
Good catch.  I would vote for:
- `FileClientBuilderExtensions` => `ShareClientBuilderExtensions`
- `FileClientOptions` => `ShareClientOptions`
- `FileUriBuilder` => `ShareUriBuilder`
- `FileSmbProperties` doesn't change
- `NtfsFileAttributes` doesn't change

And the models are easier:
- `StorageFileInfo` => `ShareFileInfo`
- `StorageFileItem` => `ShareFileItem`
- `StorageFileProperties` => `ShareFileProperties`
- `StorageFileDownloadDetails` => `ShareFileDownloadDetails`
- `StorageFileDownloadInfo` => `ShareFileDownloadInfo`
- `StorageDirectoryInfo` => `ShareDirectoryInfo`
- `StorageDirectoryProperties` => `ShareDirectoryProperties`
- `FileServiceProperties` => `ShareServiceProperties`

And the SAS types are:
- `FileAccountSasPermissions` => `FileAccountSasPermissions`
- `FileSasBuilder` => `ShareSasBuilder`
- `FileSasPermissions` => `ShareFileSasPermissions`
- `ShareSasPermissions` => doesn't change

@KrzysztofCwalina?

**Comment by JoshLove-msft** [comment]
For FileAccountSasPermissions, did you mean it should change to ShareAccountSasPermissions?

**Comment by tg-msft** [comment]
I did...  edited in place.

**Comment by JoshLove-msft** [comment]
FileHttpHeaders => ShareFileHttpHeaders?

**Comment by tg-msft** [comment]
Yes, `FileHttpHeaders` => `ShareFileHttpHeaders`

**Comment by JoshLove-msft** [comment]
From generated file:
FileAccessPolicy => ShareFileAccessPolicy
FileCorsRule => ShareFileCorsRule
FileErrorCode => ShareFileErrorCode
FileMetrics => ShareFileMetrics
FileRangeWriteType => ShareFileRangeWriteType
FileRetentionPolicy => ShareFileRetentionPolicy
FileServiceProperties => ShareFileServiceProperties
FileSignedIdentifier => ShareFileSignedIdentifier
FilesModelFactory => ShareFilesModelFactory
StorageFileCopyInfo => ShareFileCopyInfo
StorageFileHandle => ShareFileHandle
StorageFileRangeInfo => ShareFileRangeInfo
StorageFileUploadInfo => ShareFileUploadInfo

**Comment by tg-msft** [comment]
`FileAccessPolicy` => `ShareAccessPolicy`
`FileCorsRule` => `ShareCorsRule`
`FileErrorCode` => `ShareErrorCode`
`FileMetrics` => `ShareMetrics`
`FileRangeWriteType` => `ShareFileRangeWriteType`
`FileRetentionPolicy` => `ShareRetentionPolicy`
`FileServiceProperties` => `ShareServiceProperties`
`FileSignedIdentifier` => `ShareSignedIdentifier`
`FilesModelFactory` => `ShareModelFactory`
`StorageFileCopyInfo` => `ShareFileCopyInfo`
`StorageFileHandle` => `ShareFileHandle`
`StorageFileRangeInfo` => `ShareFileRangeInfo`
`StorageFileUploadInfo` => `ShareFileUploadInfo`
