### ISSUE TITLE
Storage: Normalize Content-Language/Encoding

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#8478]
https://apiview.azurewebsites.net/Assemblies/Review/c52f059a-6d57-4d40-b7d2-a5816565a660#Azure.Storage.Blobs.Models.BlobItemProperties

**Comment by JoshLove-msft** [comment]
For this, what about just using string everywhere for content-language/encoding? Does IEnumerable add much value?
