### ISSUE TITLE
Azure.Identity Conceptual Docs (with language-specific code samples)

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-net#8488]
This is a tracking item to finish writing Conceptual Documentation for Identity before the November SDK update.

This is something @ellismg began last week, but it needs to be expanded with language-specific code samples as well.

Per offline discussion, this conceptual docs will be PR'd to all 4 repos and each language-specific package owner will fill-in the language-specific portion in the markdown / docs

Related: https://github.com/Azure/azure-sdk-for-java/issues/6062

**Comment by jsquire** [comment]
Since this looks to have had the milestone moved forward by the triage team, I'm sliding it to the backlog until it is ready to be worked on.

**Comment by christothes** [comment]
@joshfree Is this issue still relevant?

**Comment by joshfree** [comment]
This can be closed now
