### ISSUE TITLE
[BUG] SessionHandlerOptions.MessageWaitTimeout allows zero value, but throws on ReceiveAsync

### ISSUE THREAD

**Issue by ankrause** [Azure/azure-sdk-for-net#8490]
**Describe the bug**
SessionHandlerOptions.MessageWaitTimeout allows me to set the timeout to 0, using TimeSpan.FromSeconds(0) as an example. At runtime, the session receiver throws an ArgumentOutOfRangeException continuously during the ReceiveAsync operation.

***Exception or Stack Trace***
Message:
> Argument operationTimeout must be a positive non-zero timeout value. The provided value was 00:00:00. (Parameter 'operationTimeout')
Actual value was 00:00:00.

Trace:

>   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<ReceiveAsync>d__64.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<ReceiveAsync>d__62.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Azure.ServiceBus.SessionReceivePump.<MessagePumpTaskAsync>d__21.MoveNext()

**To Reproduce**
Set the SessionHandlerOptions.MessageWaitTimeout property to 0 and register a session handler against a queue/subscription with messages.

***Code Snippet***
```
    public static class Program
    {
        public static async Task Main(string[] args)
        {
            var sessionHandlerOptions = new SessionHandlerOptions(ExceptionReceivedHandler)
            {
                AutoComplete = false,
                MaxAutoRenewDuration = TimeSpan.FromSeconds(60),
                MaxConcurrentSessions = 1,
                MessageWaitTimeout = TimeSpan.FromSeconds(0)
            };

            var queueClient = new QueueClient(<connection args>);

            queueClient.RegisterSessionHandler(HandleSession, sessionHandlerOptions);

            await Task.Delay(TimeSpan.FromHours(1));
        }

        private static Task ExceptionReceivedHandler(ExceptionReceivedEventArgs arg)
        {
            return Task.CompletedTask;
        }

        private static Task HandleSession(
            IMessageSession session,
            Message message,
            CancellationToken ctx)
        {
            Console.WriteLine(session);
            Console.WriteLine(message);
            Console.WriteLine(ctx);

            return Task.CompletedTask;
        }
    }
```

**Expected behavior**
- Other properties in SessionHandlerOptions have guards in the setters against negative arguments, including the MessageWaitTimeout. MaxConcurrentSessions also guards against a zero value as it must be 1 or more. I would expect this property to have a similar guard if 0 is not valid.
- The implementation of "OperationTimeout" is confusing as compared to the full framework library. Using an explicit .Receive operation with TimeSpan.Zero historically meant "no wait", as I recall. In the case of sessions, "MaxWaitTimeout" to me means "how long to wait for another message before closing the session". Offhandedly, I would expect to be able to set this to 0 meaning "as soon as I'm done processing the message, if there are no more messages, close the session and get a new one".

Additionally, the current version of the package does not provide a documentation file, so none of these properties have details explaining their usage or limitations.

**Setup (please complete the following information):**
 - OS: Windows
 - IDE : VS2019 Enterprise
 - Version of the Library used: 4.1.0

**Comment by jfggdl** [comment]
@ankrause, thanks for creating this issue. We are reviewing our SDK and will provide some guidance.

**Comment by nemakam** [comment]
@ankrause. 
> I would expect this property to have a similar guard if 0 is not valid.

Yes, we will add a guard here. Thanks for pointing that out.

>The implementation of "OperationTimeout" is confusing as compared to the full framework library. Using an explicit .Receive operation with TimeSpan.Zero historically meant "no wait", as I recall. In the case of sessions, "MaxWaitTimeout" to me means "how long to wait for another message before closing the session". Offhandedly, I would expect to be able to set this to 0 meaning "as soon as I'm done processing the message, if there are no more messages, close the session and get a new one".

I agree this is confusing especially when comparing it with the full framework client. With the current implementation using `AMQP` transport/protocol (which is also true with full framework client), it is not possible to provide a 0 second timeout for Receive operation. Unlike the `NetMessaging` protocol which is present only in the full framework client, where the parameter represented `serverWaitTime`, in `AMQP` transport, this timeout is implemented as client side timeout and not service side timeout. 
AMQP is a streaming protocol and doesn't let you specify timeout for each `credit` that is requested from service. The `ReceiveAsync()` starts its own client side timeout for cancelling the request and doesn't rely on the service in this particular case. 
This is the whole reason behind disparity. It is less about full-framework client and this client. It has to do with `NetMessaging` protocol and `AMQP`. Unfortunately, there isn't any easy way using this client to provide a zero timeout value. You could experiment with giving a very small `TimeSpan`. But that's at your own risk.

> Additionally, the current version of the package does not provide a documentation file, so none of these properties have details explaining their usage or limitations.

Oh. Didn't realize there's an issue with documentation. We will try to fix that. Meanwhile, you could take a look at the xml docs in the library itself or check out the source code - https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Microsoft.Azure.ServiceBus/src/SessionHandlerOptions.cs

**Comment by jsquire** [comment]
Moving this to the backlog milestone, as the associated sprint has passed.

**Comment by ramya-rao-a** [comment]
Regarding the issue with documentation, the fix is already in and the documentation will be showing up after the next update to Microsoft.Azure.ServiceBus
