### ISSUE TITLE
<inheritdoc> breaks docfx 

### ISSUE THREAD

**Issue by AlexanderSher** [Azure/azure-sdk-for-net#8503]
Master branch contains all the doc strings:  https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Secrets/src/DeleteSecretOperation.cs
But corresponding page on azure.github.io had only type description:
https://azuresdkdocs.blob.core.windows.net/$web/dotnet/Azure.Security.KeyVault.Secrets/4.0.0-preview.6/api/Azure.Security.KeyVault.Secrets/Azure.Security.KeyVault.Secrets.DeleteSecretOperation.html

**Comment by scbedd** [comment]
Just checked 3/27, InhericDoc not showing up appropriately..

**Comment by pakrym** [comment]
What's the plan here?

**Comment by chidozieononiwu** [comment]
DocFx does not yet have full support for InheritDoc. I will investigate further to see if some of these can be taking care of by updating docfx to the latest version.

**Comment by chidozieononiwu** [comment]
Doc Strings are now being published https://azuresdkdocs.blob.core.windows.net/$web/dotnet/Azure.Security.KeyVault.Secrets/4.2.0/api/Azure.Security.KeyVault.Secrets/Azure.Security.KeyVault.Secrets.DeleteSecretOperation.html
