### ISSUE TITLE
WebSiteUpdateParameters and WebSites.Update deprecated? have gone away to where? Replaced by what?

### ISSUE THREAD

**Issue by drewid** [Azure/azure-sdk-for-net#851]
Have WebSiteUpdateParameters and WebSites.Update deprecated / gone away without even the slightest bit of mention?

When things shifted to Microsoft.Azure.Management those items went away and I cannot figure out what their comparable commands now are - nothing seems to fit.

Trying to add a sub-domain binding to Azure WebSite Programmatically.

Per earlier sample code this "used" to work.  Now it doesn't without the equivalent being present or at least I can't figure it out. WebSiteGetParameters still exists but WebSiteUpdateParameters doesn't.

```
          WebSiteManagementClient client = new WebSiteManagementClient(getCredentials()); 

          var website = client.WebSites.Get(webspaceName, websiteName, new Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetParameters()); 
            website.WebSite.HostNames.Add(subDomainName); 

            var parm = new WebSiteUpdateParameters(); 
            parm.HostNames = website.WebSite.HostNames; 
            client.WebSites.Update(webspaceName, websiteName, parm); 
            Console.WriteLine("Add CName: {0} to {1} successfully!",subDomainName,websiteName); 
```

HELP!! Please.  Right now there doesn't seem to be a way to programmatically fully work with Azure websites anymore.

**Comment by shahabhijeet** [comment]
please reopen if this is still an issue.
