### ISSUE TITLE
GetCertificateOperation should be removed 

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#8515]
And replaced with an operation constructor.

**Comment by heaths** [comment]
We've decided to cut this. There are other operations like canceling and deleting an LRO that the service supports that we feel are better exposed by the `CertificateClient`.

**Comment by pakrym** [comment]
We need to adjust the guidelines for this.

**Comment by heaths** [comment]
I'll open a dependency issue then, but it wasn't just a matter of cancel and delete. I talked about this with @KrzysztofCwalina and @schaabs as well. Them passing the right `CertificateClient` in is problematic, and our other pseudo-LROs for delete and recover can't be recreated from some dedicated URI, thus making the experience inconsistent.

**Comment by heaths** [comment]
After offline discussion, moving back in for now. Still some things to discuss.

**Comment by heaths** [comment]
Talking offline with @pakrym, @KrzysztofCwalina, and @schaabs, instead we will:

* Keep `GetCertificateOperation` on `CertificateClient`
* Move `CancelCertificateOperation` and `DeleteCertificateOperation` to `CertificateOperation` as `Cancel` and `Delete`, respectively.

This makes getting existing certificate operations more discoverable based on our UX studies. This is predicated on whether it's possible for other languages, however.
