### ISSUE TITLE
[BUG] EventHub connection using Sas token, SendAsync throws Time-out interval must be less than 2^32-2.

### ISSUE THREAD

**Issue by stefando** [Azure/azure-sdk-for-net#8530]
**Describe the bug**
I am connecting to EventHub via SaS token valid for two months. 
(Validity longer than ``` TimeSpan.FromMilliseconds(System.Threading.Timer.MAX_SUPPORTED_TIMEOUT)```).

Sending message throws:

> System.ArgumentOutOfRangeException: Time-out interval must be less than 2^32-2.

***Exception or Stack Trace***

> System.ArgumentOutOfRangeException: Time-out interval must be less than 2^32-2. (Parameter 'dueTime')
>    at System.Threading.Timer.Change(Int64 dueTime, Int64 period)
>    at System.Threading.Timer.Change(TimeSpan dueTime, TimeSpan period)
>    at Microsoft.Azure.EventHubs.Amqp.ActiveClientLinkManager.ScheduleValidityTimer()
>    at Microsoft.Azure.EventHubs.Amqp.ActiveClientLinkManager.SetActiveLink(ActiveClientLinkObject activeClientLink)
>    at Microsoft.Azure.EventHubs.Amqp.AmqpEventDataSender.CreateLinkAsync(TimeSpan timeout)
>    at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
>    at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
>    at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
>    at Microsoft.Azure.EventHubs.Amqp.AmqpEventDataSender.OnSendAsync(IEnumerable`1 eventDatas, String partitionKey)
>    at Microsoft.Azure.EventHubs.Amqp.AmqpEventDataSender.OnSendAsync(IEnumerable`1 eventDatas, String partitionKey)
>    at Microsoft.Azure.EventHubs.EventDataSender.SendAsync(IEnumerable`1 eventDatas, String partitionKey)
>    at Microsoft.Azure.EventHubs.EventHubClient.SendAsync(IEnumerable`1 eventDatas, String partitionKey)
>    at Utils.Generate.EhSas.Program.Main(String[] args) in Program.cs:line 29
> 

**To Reproduce**
1. Create an Event Hub key for shared access policy with send access.
2. Using the key, create the SAS token as described [here](https://docs.microsoft.com/en-us/azure/event-hubs/authenticate-shared-access-signature)
3. Create EventHubClient
4. Try to send data.

***Code Snippet***
```csharp
static async Task Main()
{
    const string ehurl = "amqps://<<nsName>>.servicebus.windows.net/";
    const string entityPath = "<<ehName>>";

    var token = CreateToken(
        ehurl,
        "SampleVendor",
        "<<my_key>>",
        DateTime.UtcNow + TimeSpan.FromDays(60));
    
    var client = EventHubClient.Create(
        new EventHubsConnectionStringBuilder(
            new Uri(ehurl), 
            entityPath, 
            token, 
            TimeSpan.FromSeconds(10)));
            
    var m = new EventData(Encoding.UTF8.GetBytes("Test message!"));
    await client.SendAsync(m);
}

private static string CreateToken(string resourceUri, string keyName, string key, DateTime expiration)
{
    TimeSpan sinceEpoch = expiration - new DateTime(1970, 1, 1);
    var expiry = Convert.ToString((uint)sinceEpoch.TotalSeconds);
    string stringToSign = HttpUtility.UrlEncode(resourceUri) + "\n" + expiry;
    HMACSHA256 hmac = new HMACSHA256(Encoding.UTF8.GetBytes(key));
    var signature = Convert.ToBase64String(hmac.ComputeHash(Encoding.UTF8.GetBytes(stringToSign)));
    var sasToken = string.Format(CultureInfo.InvariantCulture, "SharedAccessSignature sr={0}&sig={1}&se={2}&skn={3}", HttpUtility.UrlEncode(resourceUri), HttpUtility.UrlEncode(signature), expiry, keyName);
    return sasToken;
}
```

**Expected behavior**
No exception, message sent to EventHub

**Setup (please complete the following information):**
 - Windows 10
 - .net core 3.0
 - Microsoft.Azure.EventHubs 4.1.0
 - Microsoft.Azure.Amqp 2.4.3

**Comment by jfggdl** [comment]
@stefando, thanks for letting us know about this issue. @serkantkaraca is working on this issue and he should be sharing his findings soon.

**Comment by serkantkaraca** [comment]
Thanks for reporting the issue. I am currently working on a fix.

**Comment by serkantkaraca** [comment]
PR here https://github.com/Azure/azure-sdk-for-net/pull/8541

**Comment by serkantkaraca** [comment]
Fix is merged to master branch.
