### ISSUE TITLE
SqlManagementClient authentication issue

### ISSUE THREAD

**Issue by Rowdster** [Azure/azure-sdk-for-net#854]
With API 2014-10-01 and code like below:

`_subscriptionCloudCredentials =  new CertificateCloudCredentials(subscriptionId, _azureCertificate);
SqlManagementClient smc = new SqlManagementClient(_subscriptionCloudCredentials);
smc.Servers.List("rgn");`

For "smc.Servers.List("rgn");" I am getting "AuthenticationFailed: Authentication failed. The 'Authorization' header is not present or provided in an invalid format."

Very similar code works great for ComputeManagementClient.

I have the same issue with ResourceManagementClient.

**Comment by pecke01** [comment]
@markcowl Is there a reason that you cant use a certificate for working with ResourceManagementClient? Limits what you can automate a lot when you need to do some manual auth.

**Comment by markcowl** [comment]
@pecke01 It shouldn't prevent automation.  As long as you have orgid or service credentials, youcan acquire a token for management without user interaction.
Not allowing certificate authentication is a service-side requirement.

**Comment by abramz** [comment]
Sorry to comment on an old issue. 

I am currently working with the Data Factory preview, and while I have been able to authorize a user, I have their credentials in plain text in a config file. While I have some ideas on how to secure the credentials, I was wondering if you guys have guidance on the best way to do it?
