### ISSUE TITLE
[Identity] Support cross-tenant authentication

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-net#8544]
Support the scenario described in https://docs.microsoft.com/azure/azure-resource-manager/management/authenticate-multi-tenant. 

To test it, the shared image gallery scenario takes advantage of this type of authentication header: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/share-images-across-tenants

A previous issue which users were able to workaround: https://github.com/Azure/azure-sdk-for-java/issues/3819. We need to provide a more elegant way.

**Related https://github.com/Azure/azure-sdk-for-java/issues/6040**

**Comment by schaabs** [comment]
Customers who have a need to make requests which utilize the `x-ms-authorization-auxiliary` header to do multi-tenant authorization of service calls before support is added to the Azure SDK directly can use a custom pipeline policy to add the auxiliary headers. Below is a simplified example of such a policy, but a robust solution would also need to handle token expiry.

``` c#
public class AuxiliaryAuthenticateHeaderPolicy : HttpPipelineSynchronousPolicy
{
    // ...

    public override void OnSendingRequest(HttpMessage message)
    {
        message.Request.AddHeader("x-ms-authorization-auxiliary", _accessToken);

        base.OnSendingRequest(message);
    }
}
```

The custom policy can then be added to any Azure SDK service client using `ClientOptions.AddPolicy`

**Comment by Jazaret** [comment]
@schaabs 
I believe I found a similar way using the scenario described in the Java thread by adding the auxiliary token in the base http client passed into the SDK Client.

```cs
var mainTokenCredentials = new TokenCredentials(accessToken);
var baseClient = new HttpClient();
baseClient.DefaultRequestHeaders.Add("x-ms-authorization-auxiliary", $"Bearer {auxAccessToken}");
return new ResourceManagementClient(mainTokenCredentials , baseClient, true)
{
    BaseUri = new Uri(baseUri),
    SubscriptionId = subscriptionId
};
```

**Comment by pallavit** [comment]
@christothes, @schaabs is this still valid?

**Comment by JimSuplizio** [comment]
Hi @joshfree, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
