### ISSUE TITLE
Remove partition affinity from Event Hub Producer Client

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#8555]
# Summary

In its current form, an instance of the `EventHubProducerClient` must be bound to a specific Event Hub partition in order to publish events explicitly to that partition.  The client should be able to work dynamically across all partitions, allowing a partition to be specified when publishing an event batch, similar to how a partition key is accepted.  One client instance should be able to communicate with any partition of the associated Event Hub on demand or publish to the gateway for automatic routing or partition key hashing.

# Scope of Work

- The `EventProducerClient` does not accept an option specific to a partition when it is constructed.  

- The notion of instance-level state for partition association has been removed.

- The `SendOptions` allows for a `PartitionId` to be specified, allowing `null` but not empty strings.

- When an event batch is sent, validation should be performed to ensure that the send options contain either a partition identifier or a partition key, but not both.   Having neither is also acceptable.

- Tests have been added or adjusted to cover the updated API and ensure its functionality.

# Out of Scope

- Updates or changes to samples beyond ensuring that the project can be compiled; these will be covered under a separate work item.

- Updates or changes to documentation; these will be covered under a separate work item.

- Background cleanup of internal transport clients for partitions addressed by the client instance; this will be an enhancement covered under a separate work item.

# Success Criteria

- The refactoring and enhancements  detailed by the scope have been completed.

- The tests necessary for its validation have been created or adjusted and pass reliably.

- The existing test suite continues to produce deterministic results and pass reliably.

# References

- [Event Hubs Client Library Strawman](https://gist.github.com/jsquire/36c0198e0898f203168e70bc15816d2c)
- [Event Hubs Client Library Skeleton](https://gist.github.com/jsquire/3fadc1ea57594c31f1c39366c0d7b530)

**Comment by ramya-rao-a** [comment]
> The SendOptions allows for a PartitionId to be specified, allowing null but not empty strings.

Did we consider having an overload that takes the partitionId instead of having it in the `SendOptions`?

**Comment by jsquire** [comment]
> > The SendOptions allows for a PartitionId to be specified, allowing null but not empty strings.
> 
> Did we consider having an overload that takes the partitionId instead of having it in the `SendOptions`?

It was considered, but remains an obscure corner case expected to be used less frequently than the partition key, which is in the options.
