### ISSUE TITLE
Validate and add unit tests for retry for failed requests in Azure.Data.AppConfiguration

### ISSUE THREAD

**Issue by abhilasharora** [Azure/azure-sdk-for-net#8560]
1. Ensure that the retry logic for failed requests works as expected
2. Add unit tests for automated validation of retry logic for pull requests and as a part of build

Tags : AzConfig, Client

**Comment by AlexGhiondea** [comment]
@abhilasharora can you add some more details around the expected behavior?

We have tests that run during PR validation — our tests will run there and during Nightly CI. Was there anything you wanted with #2?

**Comment by abhilasharora** [comment]
In an App Configuration SDK method like `GetConfigurationSettingAsync`, when the HTTP call to the server fails, the request needs to be retried. However, I don't see any test that verifies this behavior. If such a test exists, could you point me to it? If not, could we add it?

**Comment by annelo-msft** [comment]
Please see these tests:
[AuthorizationHeadersAddedOnceWithRetries](
https://github.com/Azure/azure-sdk-for-net/blob/31a937aa9b5b669c2e72b08ea9c646a7feea3dbd/sdk/appconfiguration/Azure.Data.AppConfiguration/tests/ConfigurationMockTests.cs#L825)
[ConfiguringTheClient, which validates retries](https://github.com/Azure/azure-sdk-for-net/blob/31a937aa9b5b669c2e72b08ea9c646a7feea3dbd/sdk/appconfiguration/Azure.Data.AppConfiguration/tests/ConfigurationMockTests.cs#L574)
