### ISSUE TITLE
[Service Bus] Detect connection status

### ISSUE THREAD

**Issue by giggio** [Azure/azure-sdk-for-net#8561]
Right now it does not seem possible to detect the connection state with Azure Service Bus. There is no property that indicates if we are connected or if there is some connectivity issue (or other issue, like subscription deleted etc).

**Describe the solution you'd like**
I want a boolean property on the `SubscriptionClient` that tells me if it is connected. And I want an event on connection changes, i.e. `Connected` and `Disconnected`.

**Describe alternatives you've considered**
The alternative I'm using now uses Reflection, which is fragile. It does a little bit like this:

````csharp
var subscriptionClient = new SubscriptionClient(connStr, topic, subscription, ReceiveMode.PeekLock);
var conn = subscriptionClient.ServiceBusConnection;
FaultTolerantAmqpObject<AmqpConnection> connectionManager = (FaultTolerantAmqpObject<AmqpConnection>)typeof(ServiceBusConnection).GetProperty("ConnectionManager", BindingFlags.Instance | BindingFlags.NonPublic).GetMethod.Invoke(conn, null);
var amqpConnection = await connectionManager.GetOrCreateAsync(TimeSpan.FromSeconds(2));
var amqpSessionSettings = new AmqpSessionSettings { Properties = new Fields() };
while (true)
{
    var session = amqpConnection.CreateSession(amqpSessionSettings);
    var connected = false;
    try
    {
        await session.OpenAsync(TimeSpan.FromSeconds(2));
        await session.CloseAsync(TimeSpan.FromSeconds(2));
        connected = true;
    }
    catch (TimeoutException)
    {
    }
    Console.WriteLine(connected);
    Thread.Sleep(2000);
}
````

**Additional context**
I'll use this to inform the healthcheck of a container on a Kubernetes environment.

We shouldn't need to have to use reflection. And I get that the library is resilient and will reconnect. But I need to setup scaling, alerts and other infrastructure based on the fact that there is a worker doing what it is supposed to be doing. If for some reason a container gets disconnected from Service Bus, I need to know, I might setup infrastructure that will recreate it, setup alarms, etc. My queues/topics might be filling up, and I don't get to react to it.

**Comment by AlexGhiondea** [comment]
/cc @binzywu.

Also, @jsquire to see how this feedback applies to our Track 2 libraries.

**Comment by jfggdl** [comment]
@giggio, thanks for opening this issue. 
@axisc  or @makam: Is there a way we can expose the connection status from the service to the SDKs, if that is not currently the case?

**Comment by axisc** [comment]
We'll investigate this and add to the backlog.

**Comment by SeanFeldman** [comment]
> I want a boolean property on the SubscriptionClient that tells me if it is connected. 

That property exists on all clients, including `SubscriptionClient` - `IsClosedOrClosing`[](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.cliententity.isclosedorclosing?view=azure-dotnet#Microsoft_Azure_ServiceBus_ClientEntity_IsClosedOrClosing).

**Comment by giggio** [comment]
> That property exists on all clients, including SubscriptionClient - IsClosedOrClosing.

If we pull the network cable and put the computer on airplane mode, so cutting all network communication, that property still shows as false. So we cannot rely on it.

**Comment by SeanFeldman** [comment]
I did not claim you can rely on it, just pointed out there there is a property that is supposed to indicate what's the state of the connectivity. The fact that it doesn't work as it supposed to is a bug that should be looked into (@axisc might already know about it).

For the scenario you've described, you really need not a property, but an event. Which you've also mentioned. That would be a feature as today it doesn't exist AFAIK.

**Comment by tomkerkhove** [comment]
This is a great feature request - We'd like to use this as well so that we can use it as part of our health probe approach.

THis is important as Kubernetes requires this to kill dead pods and recreate them.

**Comment by giggio** [comment]
@tomkerkhove This is exactly what I need to do and the reason I opened this issue.

**Comment by tomkerkhove** [comment]
Any feedback/timeline on this one @axisc?

**Comment by tomkerkhove** [comment]
While we're asking, would be good if there's a built-in .NET Core Health Check that works with this feature

**Comment by giggio** [comment]
Everyone interested in this issue, please add your 👍 up there so they can prioritize it.

**Comment by jsquire** [comment]
Moving this to the backlog milestone, as the associated sprint was outdated.

**Comment by tomkerkhove** [comment]
Is there an update on this @jsquire @axisc we **really** need this, certainly for container workloads.

**Comment by JWilh** [comment]
Really would like to see that, as it's crucial for us to have a proper health check for our services.

**Comment by filipw** [comment]
it's pretty unfortunate that a property `IsClosedOrClosing` on the connection object and the client object just keeps returning `false` when you go completely offline 😄 

It would be great to have this work properly to allow quick and easy health monitoring

**Comment by tomkerkhove** [comment]
Jup, in the same boat here and need this super urgently..

**Comment by tomkerkhove** [comment]
Any update on this @jsquire?

**Comment by jsquire** [comment]
Unfortunately, I'm only acting as issue triage and don't have insight.   I'll have to defer to @axisc and @shankarsama, as the Service Bus team owns this version of the library.

**Comment by tomkerkhove** [comment]
This is still a pain,any update on this?

**Comment by ramya-rao-a** [comment]
Thanks for your patience everyone and apologies for the delay in response.

Please note that a newer package Azure.Messaging.ServiceBus is available as of November 2020. While the older `Microsoft.Azure.ServiceBus` package for which this issue was logged will continue to receive critical bug fixes, we strongly encourage you to upgrade. Read the [migration guide](https://aka.ms/azsdk/net/migrate/sb) for more details.

Meanwhile, this feature request applies to both the older `Microsoft.Azure.ServiceBus` and the newer `Azure.Messaging.ServiceBus` packages.

@JoshLove-msft Can you share what the best practice is when using the new `Azure.Messaging.ServiceBus` package in this regard and is there any feature request we can take for the new package from here?

@shankarsama Same question for you from the perspective of `Microsoft.Azure.ServiceBus` 

Others,
Can you share how you would use this property if it was available? The Service Bus clients are designed in such a way that they recover from all retriable connection errors. Is monitoring errors caught from either your send or receive operations suffice to monitor the health of your application?

**Comment by tomkerkhove** [comment]
Thank you for the update!

> Others,
> Can you share how you would use this property if it was available? The Service Bus clients are designed in such a way that they recover from all retriable connection errors. Is monitoring errors caught from either your send or receive operations suffice to monitor the health of your application?

I think we have enough examples mentioned above but the most obvious one is health probing to see if the message processor is still processing messages. If not, instance needs to be killed and recreated

**Comment by SkNuwanTissera** [comment]
I am using Java SDK 3.5.1.
I cannot use any property available out there to detect an open/closed connection.
`IsClosedOrClosing` is not accessible via QueueClient, TopicClient or SubscriptionClient.  
It has a function `getIsClosedOrClosing`. But that method is protected. So cannot use outside the package.
Could you please help with this concern.

**Comment by JoshLove-msft** [comment]
Related Java issue - https://github.com/Azure/azure-sdk-for-java/issues/24075

**Comment by JoshLove-msft** [comment]
> Thank you for the update!
> 
> > Others,
> > Can you share how you would use this property if it was available? The Service Bus clients are designed in such a way that they recover from all retriable connection errors. Is monitoring errors caught from either your send or receive operations suffice to monitor the health of your application?
> 
> I think we have enough examples mentioned above but the most obvious one is health probing to see if the message processor is still processing messages. If not, instance needs to be killed and recreated

Can you clarify what the instance would need to be killed and recreated? Since the clients are all inherently resilient, even if the connection or link goes down, it should automatically reconnect on the next iteration of the receive loop. If there are errors occurring, these would be raised to the error handler (so they should be observable already).

**Comment by tomkerkhove** [comment]
But what if it doesn't? We've had idle processors in the past where that was not the case. You could argue that was a bug, but having health probes to identify these, kill them and start new instances is going to save you instead of assuming they are up while you have a backorder of thousands of orders, for example.

Health probing is essential for live site management, but we need to be able to get the info from the SDK.

**Comment by JoshLove-msft** [comment]
That makes sense. Since the connection is meant to be resilient, and the snapshot of the connection state may not be that relevant to the overall system health, what if we had some sort of metric/metrics that would allow you to detect the health? We are thinking of something like a "LastReceiveAttemptedTime" property that you could check.

**Comment by tomkerkhove** [comment]
Would that metric be in the SDK or in Azure Monitor?

**Comment by JoshLove-msft** [comment]
Good question 😄 
I was thinking the SDK itself. We are already logging a lot of events that could be picked up by Azure Monitor. My understanding is that many customers don't enable logging/diagnostic tracing at the Verbose level due to the volume of logs/events.

**Comment by tomkerkhove** [comment]
Agreed, SDK is what I'd prefer as well!

**Comment by JWilh** [comment]
I would like to include this in a health check, that is called from appinsights, so we get better insights about the availability of our environment. A LastReceiveAttemptedTime property could help to achieve this.
Only problem I can think of: what if a worker already executes the max number of queue items of MaxConcurrentCalls?
LastReceiveAttemptedTime  wouldn't be updated, as the worker wouldn't get new queue items, right?

We have workers, that executes work that normally finishes within 10 sec, but also workers where executing the item takes up to 10min or in case of retriable transient errors even up to 30 min for an individual queue item.

**Comment by JoshLove-msft** [comment]
That's a good point - I think we could also have a property that indicates how many messages are currently being processed.

**Comment by JoshLove-msft** [comment]
@giggio since the issue description refers to types other than the pump/processor, I'm wondering if the solution I proposed would be helpful for you. Can you speak more to why you would need status information for the lower level types that you have complete control over?

**Comment by giggio** [comment]
I don't believe a property that indicates how many messages are currently being processed would help me, as I need to know if the worker is connected, even if it is not processing messages (because there aren't any).

**Comment by JoshLove-msft** [comment]
Well there would be the number of messages being processed, in addition to the last receive attempted time. The combination of both of these should give insight into what the processor is doing. Would that meet your needs?

**Comment by giggio** [comment]
Is the last receive attempted time the last time the worker connected to the bus? If yes, and we have a time span where that should happen, then yes, it would be enough.
For example, if the worker tries to receive a message every 5 seconds, but the last receive attempted time is 1 minute, could I assume there is a problem? Would that mean it is disconnected?

I believe that even if this works, we are passing lower abstraction concepts to the api. Why not abstract all of this and add a `Connected` property (and `Disconnected` and `Connected` events)?

**Comment by JoshLove-msft** [comment]
> I believe that even if this works, we are passing lower abstraction concepts to the api. Why not abstract all of this and add a Connected property (and Disconnected and Connected events)?

The issue is that this Connected property could be misleading. It would only tell you if you are connected at that instant - it wouldn't really give insight into whether you need to restart your container. In general, there shouldn't be a problem if Connected was false, as the library would recreate the connection lazily.

**Comment by firephantomassasin** [comment]
+1! Please develop this feature for azure service bus SDK C# library as well. We badly need this for health monitoring like alerting us if the connection is not connected (due to failed internet connection)

**Comment by csiakgyula** [comment]
+1 vote! We would also need this feature to check connection status without Exception to be raised or Message to sent over.

**Comment by sohanlal311** [comment]
We need this feature a big time. Could you please prioritize it if possible? Or please help us with an ETA?

**Comment by firephantomassasin** [comment]
> We've added the concept of TransportMetrics in #27663
> 
> This type contains the following three properties:
> 
> ```cs
>         public System.DateTimeOffset? LastConnectionClose { get { throw null; } }
>         public System.DateTimeOffset? LastConnectionOpen { get { throw null; } }
>         public System.DateTimeOffset? LastHeartBeat { get { throw null; } }
> ```
> 
> In order to populate these properties, you would need to set EnableTransportMetrics to true in the ServiceBusClientOptions.
> 
> We will plan to release a beta with this update in April. Please let us know if these help your use cases.

For the LastHeartBeat, how frequently will this be updated? Like how can we know if the connection has been drop or disconnected? Which one should we use?

**Comment by JoshLove-msft** [comment]
> For the LastHeartBeat, how frequently will this be updated? Like how can we know if the connection has been drop or disconnected? Which one should we use?

The heartbeat is sent approximately every 30 seconds.

**Comment by JoshLove-msft** [comment]
The ServiceBusTransportMetrics are available in beta in https://www.nuget.org/packages/Azure.Messaging.ServiceBus/7.8.0-beta.2.

In order to populate these properties, you would need to set EnableTransportMetrics to true in the ServiceBusClientOptions.
Please try it out and let us know what you think!

**Comment by jsquire** [comment]
With the release of the transport metrics, I'm going to mark this addressed and close it out.   If you'd like to offer feedback the new metrics, please feel free to open a new issue for that discussion.

**Comment by SeanFeldman** [comment]
@jsquire or @JoshLove-msft, is this API documented anywhere?

**Comment by jsquire** [comment]
@SeanFeldman:   Documentation can currently be found on MS Docs:

- [ServiceBusClientOptions.EnableTransportMetrics](https://docs.microsoft.com/dotnet/api/azure.messaging.servicebus.servicebusclientoptions.enabletransportmetrics?view=azure-dotnet-preview#azure-messaging-servicebus-servicebusclientoptions-enabletransportmetrics)
- [ServiceBusClient.GetTransportMetrics](https://docs.microsoft.com/dotnet/api/azure.messaging.servicebus.servicebusclient.gettransportmetrics?view=azure-dotnet-preview)
- [ServiceBusTransportMetrics](https://docs.microsoft.com/dotnet/api/azure.messaging.servicebus.servicebustransportmetrics?view=azure-dotnet-preview)

I'll defer to @JoshLove-msft for any additional sources and future plans.

**Comment by SeanFeldman** [comment]
Based on what I’ve seen in the past, XML docs don’t provide as much help to the teams that don’t use ASB extensively as elaborate documentation. Just in the links above, I can see that two steps are required to get the metrics.

Adding it to [Diagnostics section](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/README.md#logging-and-diagnostics) could be a good start.

**Comment by sohanlal311** [comment]
@JoshLove-msft Could you please point me out to the Java API for the same?

**Comment by sohanlal311** [comment]
@JoshLove-msft Could you please point me out to the Java API for the same?

**Comment by JoshLove-msft** [comment]
Hi @sohanlal311 this feature is not yet available in the Java library.
/cc @ki1729

**Comment by sohanlal311** [comment]
@JoshLove-msft Could you please let me know if we need to open another issue for Java version?

**Comment by JoshLove-msft** [comment]
Reopening so that we can collect feedback on the beta feature before GA.

**Comment by sohanlal311** [comment]
@ki1729 Could you please let me know if there is already a Java version of this issue?

**Comment by sohanlal311** [comment]
@ki1729 Could you please provide an update on this one?

**Comment by sohanlal311** [comment]
@JoshLove-msft Could you please let me know if there is already a Java version of this issue?

**Comment by joshfree** [comment]
@stliu let's open a new issue in https://github.com/azure/azure-sdk-for-java/ repo for the Java SDK specific ask, and we can link that back to here; rather than adding Java noise to the .NET repo. :)

**Comment by stliu** [comment]
ah, my mistake didn't check the repo :)

**Comment by ki1729** [comment]
@stliu I have created a new issue in the Java repo to track this feature request : https://github.com/Azure/azure-sdk-for-java/issues/30507

**Comment by ki1729** [comment]
@sohanlal311 : The corresponding issue for Java is here: https://github.com/Azure/azure-sdk-for-java/issues/30507

**Comment by scgbear** [comment]
@jsquire or @joshfree, there an ETA on when ServiceBusTransportMetrics will make it's way out of the https://www.nuget.org/packages/Azure.Messaging.ServiceBus/7.8.0-beta.2 package ? 

All of the links to documentation you provided above resolve to a 404. 

This feature die on the vine?

Are there alternative approaches we should be taking to solve the problem of determining connection status?

**Comment by JoshLove-msft** [comment]
@scgbear, yes we are planning on taking a different approach here. @lmolkova do you have any timelines for when the metrics work will begin for .NET?

**Comment by bar10dr** [comment]
How on earth does it take more than three years to implement two simple events that informs of a connection state change?

This is such a low level basic feature.

Is the plan to bind this functionality into some sort of premium tier or additional paid service?
