### ISSUE TITLE
Implement a wait backoff for Key Vault LROs

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#8575]
Consider implementing a backoff on the polling interval for some or all Key Vault LROs. This might be most helpful for `CertificateClient.StartCreateCertificate` that can take a long time - even days while waiting for human intervention.

**Comment by christothes** [comment]
Should we consider adding an additional method to `OperationHelpers` similar to 
https://github.com/Azure/azure-sdk-for-net/blob/66de0fc0f20a3a888716df5e1075d8893b2e1899/sdk/core/Azure.Core/src/Shared/OperationHelpers.cs#L42

For example
```c#
public static async ValueTask<Response<TResult>> PolicyWaitForCompletionAsync<TResult>(this Operation<TResult> operation, WaitPolicy policy, CancellationToken cancellationToken)
```

where `WaitPolicy` is similar to [RetryOptions](https://github.com/Azure/azure-sdk-for-net/blob/66de0fc0f20a3a888716df5e1075d8893b2e1899/sdk/core/Azure.Core/src/RetryOptions.cs)?

**Comment by heaths** [comment]
Probably a better question for @pakrym, but with the second, why not just use `RetryOptions`, which means we could take whatever the user specified or use the defaults if none. Most of it is relevant.

**Comment by christothes** [comment]
Agreed about `RetryOptions` with the exception of maybe `NetworkTimeout`

**Comment by pakrym** [comment]
I would start by using RetryOptions directly. I know it has some extra members but considering the usage is fully internal it shouldn't be a problem.

`public static async ValueTask<Response<TResult>> WaitForCompletionAsync<TResult>(this Operation<TResult> operation, RetryOptions options, CancellationToken cancellationToken)`

We also need to make sure reties do not escalate to very large values too quickly.

**Comment by heaths** [comment]
This is still an issue. If I force a 429, I don't get a `Retry-After` header, though, so we'd need to artifically implement a wait back-off. @jlichwa it would be nice if the service did that, which is generally a good idea when sending a 429 (too many requests):
```
Status: 429
Content:
{"error":{"code":"Throttled","message":"Request was not processed because too many requests were received. Reason: VaultRequestTypeLimitReached"}}

Headers:
Cache-Control: no-cache
Pragma: no-cache
x-ms-keyvault-region: westus2
x-ms-client-request-id: dd86cbb5-58fe-49fd-a04a-d9eb358a18c1
x-ms-request-id: 1ee55031-971a-4396-a66a-06d394dba343
x-ms-keyvault-service-version: 1.9.576.1
x-ms-keyvault-network-info: conn_type=Ipv4;addr=24.16.19.131;act_addr_fam=InterNetwork;
X-Content-Type-Options: REDACTED
Strict-Transport-Security: REDACTED
Date: Tue, 01 Nov 2022 21:49:18 GMT
Content-Length: 146
Content-Type: application/json; charset=utf-8
Expires: -1
```

**Comment by pallavit** [comment]
@heaths is this still valid?

**Comment by heaths** [comment]
Valid, yes, but whether we should do anything about it in the SDK, I still think not. I think the service team should implement Retry-After so that it works with any REST client that respects it. /cc @jackrichins

**Comment by pallavit** [comment]
Given this is something we would want the service team to implement - should we open a feature request with the KV team and close this issue? I don't think there is any action item that we want to take on the SDK side for this and I suspect KV team would not be looking at the GH repo for prioritization/asks.

**Comment by heaths** [comment]
It is labeled as `Service Attention` that used to work, but maybe a tracking issue in their AzDO instance would be best, yes.
