### ISSUE TITLE
Add README.md for KeyVault.Certificates/samples directory

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#8579]

**Comment by heaths** [comment]
@pakrym I opened this based on something you said, but not sure if it's to track converting services' samples to markdown, or have a README as a sort of index in the directory. If the former, this is done and I can close this; otherwise, if the latter, IMO that seems superfluous since there's only a few sample files and they have descriptions at the top already.

**Comment by pakrym** [comment]
I think we can close this in favor of question 1 in https://github.com/Azure/azure-sdk/issues/769
