### ISSUE TITLE
Use dotnet add package in our `Installing` readme sections

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#8582]
Currently, we are using `Install-Package` powershell snippet that's not cross plat and available only in VS:
```

` ``PowerShell
Install-Package Azure.Data.AppConfiguration -Version 1.0.0-preview.2
` ``

```

We should either use `dotnet install package` that's available in more places.

cc @AlexGhiondea @heaths

**Comment by heaths** [comment]
+1 on this, but I can't tell why it was closed. Did a PR occur that just didn't link the issue and close it when merged? IIRC, some READMEs were already starting to do this.

**Comment by pakrym** [comment]
related https://github.com/Azure/azure-sdk-for-net/issues/15876

**Comment by jsquire** [comment]
This work was done.   Closing.
