### ISSUE TITLE
Re-enable storage generated code check

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#8584]
See https://github.com/Azure/azure-sdk-for-net/pull/8557/files#diff-e393debd7f57cca40fe083227f50bc35R66

**Comment by jsquire** [comment]
Given the age and that the files present in the referenced diff are no longer in the repo, I'm going to close this out as stale.   Please feel free to reopen if this is still needed.

//fyi:  @tg-msft,  just in case I'm overlooking something

**Comment by tg-msft** [comment]
No, I believe this was already fixed without closing the bug.
