### ISSUE TITLE
Event Hubs test scopes should detect environment variables

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#8588]
# Summary

The live tests within the Event Hubs client library will dynamically manage their Azure resource needs for a run, creating and removing items to fulfill test needs.  This includes the Event Hubs namespace that the tests use, as well as the individual Event Hub and consumer group instances beneath them.

For quicker developer iteration in limited scenarios that do not require a full run, it is desirable to allow an existing set of Azure resources to be specified.

# Scope of Work

- If the `EventHubScope` detects an environment variable `EVENT_HUBS_NAMESPACE_CONNECTION_STRING`, then it should not create a new namespace and should return that connection string as the instance for the test run.  In this scenario, the scope should remove any entity reference to an Event Hub and scope the connection string to the namespace only.

- If the `EventHubScope` detects an environment variable `EVENT_HUBS_EVENT_HUB_NAME`, then it should not create a new event hub for each test scope and should, instead, return the specified Event Hub name.   In this scenario, the scope should use the management library to query the available consumer groups for the specified Event Hub and return those as part of the scope.

- If the `StorageScope` (EventProcessorStore.Blobs package) detects an environment variable `EVENT_HUBS_BLOBS_CONNECTION_STRING`, then it should not create a new storage account and, instead, that connection string as the instance for the test run.  

- Tests have been added or adjusted to cover the enhancements and ensure their functionality.

# Out of Scope

- Handling of any other environment variables.

- Attempting to notify or influence tests that they're using an existing and potentially shared resource; it is responsibility of the developer providing the environment variables to ensure the test(s) being run against it are tolerant of a "used" and shared resource.

# Success Criteria

- The refactoring and enhancements detailed by the scope have been completed.

- The tests necessary for its validation have been created or adjusted and pass reliably.

- The existing test suite continues to produce deterministic results and pass reliably.

**Comment by albertodenatale** [comment]
@jsquire I know I have already some pulls open, however I think I might help with this? :)

**Comment by albertodenatale** [comment]
> * If the `EventHubScope` detects an environment variable `EVENT_HUBS_NAMESPACE_CONNECTION_STRING`, then it should not create a new namespace and should return that connection string as the instance for the test run.  In this scenario, the scope should remove any entity reference to an Event Hub and scope the connection string to the namespace only.

I wonder if you had any plans on how to take the namespace name out from the FQDN? Shall we just split the "EndpointToken" and remove the ".servicebus.windows.net" from it?

**Comment by jsquire** [comment]
> @jsquire I know I have already some pulls open, however I think I might help with this? :)

Always happy for help.   Please feel free to jump on in.   You've got a bit of exposure to the test infrastructure already, so it shouldn't be good rough.   That said, I will warn you that, once gain, I have a basic idea of things but haven't really spent time thinking all the way through this.    :)

**Comment by jsquire** [comment]
> > * If the `EventHubScope` detects an environment variable `EVENT_HUBS_NAMESPACE_CONNECTION_STRING`, then it should not create a new namespace and should return that connection string as the instance for the test run.  In this scenario, the scope should remove any entity reference to an Event Hub and scope the connection string to the namespace only.
> 
> I wonder if you had any plans on how to take the namespace name out from the FQDN? Shall we just split the "EndpointToken" and remove the ".servicebus.windows.net" from it?

Don't think that we'll need to do that; the quoted line was referring to stripping out the `;EntityPath=` token from the connection string so that we don't get conflicts between the connection string and any Event Hub name specified as an environment variable or which has been generated (if there wasn't an environment variable).    Off the top of my head, we could either do that by just manipulating the string or by using the [`ConnectionStringParser`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/src/Core/ConnectionStringParser.cs) to break it down and then reassemble.   Since we're setting up the test run, either way should be fine.   We don't have any performance critical sections.

**Comment by albertodenatale** [comment]
> the quoted line was referring to stripping out the `;EntityPath=` token from the connection string

Thank you for the clarification, you read my mind, it would have actually been my next question.

What about the ```TestEnvironment.EventHubsNamespace``` property? 

It is coming too from the created namespace:

```csharp
public static string EventHubsNamespace => s_activeEventHubsNamespace.Value.Name;
```

And we ultimately take it in ```EventHubScope::CreateNamespaceAsync``` :

```csharp
string CreateName() => $"net-eventhubs-{ Guid.NewGuid().ToString("D") }";
```

Should we put another environment variable for it or should we parse it out from the FQDN?

I could find no way to retrieve this piece of information from the management SDK but I did not actually search too much?

**Comment by albertodenatale** [comment]
There are a number of tests that are reliant on the number of partitions created in an Event Hub. 

Listing them to keep track:

- ProducerDoesNotSendToSpecificPartitionWhenPartitionIdIsNotSpecified
- ProducerSendsEventsInTheSameSetToTheSamePartition
- ProducerSendsEventsWithTheSamePartitionHashKeyToTheSamePartition
- PartitionProcessorCanCreateACheckpoint
- StopAsyncDoesNothingWhenEventProcessorIsNotRunning
- StartAsyncDoesNothingWhenEventProcessorIsRunning

**Comment by jsquire** [comment]
Not sure that I'm entirely following;  I have a feeling there may be a slight disconnect on what we're trying to accomplish.   That said, I'll do my best to hit these point-by-point and see where we end up.

> What about the `TestEnvironment.EventHubsNamespace` property?
> 
> It is coming too from the created namespace
> Should we put another environment variable for it or should we parse it out from the FQDN?

I'm thinking of basically this flow:  

```
if (connection string environment variable was found)
{
    Use [ConnectionStringParser](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/src/Core/ConnectionStringParser.cs) to pull it apart
    Use the host name of the endpoint from the [ConnectionStringProperties](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/src/Metadata/ConnectionStringProperties.cs) as the namespace
    TestEnvironment.EventHubsNamespace = extracted hostname
}
else
{
    Create new namespace
    TestEnvironment.EventHubsNamespace = new namespace name
}
```

> This property `TestEnvironment.EventHubsNamespace` is broadly used in the tests. For instance, it is used to tearing down a namespace when tests end.
There's an important point that I had forgotten and, honestly, haven't thought through end-to-end.   The `EventHubScope` will need to track whether it created the namespace/hub or not so that it only removes things it was responsible for creating.  
 
> I could find no way to retrieve this piece of information from the management SDK but I did not actually search too much?
> I think I found a method that might actually work to retrieve the namespace name starting from the FQDN:

Clever; I didn't know that you could do that.  Maybe I'm overlooking something, but we've made the assumption in many places that the namespace name is always the host for the FQDN;  using the management approach may be the safer option, but I think it's potentially overkill here.  If the norms for how the bits of information are related don't match up, we probably have larger problems due to assumptions.  Likewise, this is a non-critical path (tests) and a scenario that is probably a 10% or less use case.   I'm in favor of the straightforward,  `I have a URI and I'm taking the host name` approach, personally.

> Really looking forward to knowing your thinking

That's all this is;  my thoughts  which are probably not fully fleshed out for some areas of this.   Please feel free to push back and change my mind.  :)

**Comment by jsquire** [comment]
> There are a number of tests that rely on the number of partitions created in an Event Hub in order to succeed.
> 
> Listing them to keep track (these are all those that fail with a hub having 4 partitions):
> 
> * PartitionProcessorCanCreateACheckpoint
> * StopAsyncDoesNothingWhenEventProcessorIsNotRunning
> * StartAsyncDoesNothingWhenEventProcessorIsRunning
> 
> These fail because they need a high number of partitions (10):
> 
> * ProducerDoesNotSendToSpecificPartitionWhenPartitionIdIsNotSpecified
> * ProducerSendsEventsInTheSameSetToTheSamePartition
> * ProducerSendsEventsWithTheSamePartitionHashKeyToTheSamePartition

I wouldn't worry about this, honestly.   If a developer is overriding the default behavior and asking the tests to use an existing Event Hub, then the developer is assuming the responsibility of ensuring that the resource is appropriate.   To reinforce, this is a 10% scenario for developers with a specific (and short-term) need;  it isn't the recommended way to run tests and isn't something that I plan on calling out in documentation.

**Comment by jsquire** [comment]
> I wonder if you had any plans on how to take the namespace name out from the FQDN? Shall we just split the "EndpointToken" and remove the ".servicebus.windows.net" from it?

I'd throw it into a `System.Uri` and just extract the host name.

**Comment by albertodenatale** [comment]
Thank you very much for the heads.

While on the code I noticed that if we want to use ```ConnectionStringParser``` (that is an internal class) and at the same time build the code inside ```SharedSource``` of ```Azure.Messaging.EventHubs.CheckpointStore.Blobs.Tests``` we will need to declare it friendly assembly from ```Azure.Messaging.EventHubs``` as it currently happens for ```Azure.Messaging.EventHubs.Tests```?

I will send you soon a draft pull that might be easier to navigate?

**Comment by jsquire** [comment]
> While on the code I noticed that if we want to use `ConnectionStringParser` (that is an internal class) and at the same time build the code inside `SharedSource` of `Azure.Messaging.EventHubs.CheckpointStore.Blobs.Tests` we will need to declare it friendly assembly from `Azure.Messaging.EventHubs` as it currently happens for `Azure.Messaging.EventHubs.Tests`?

Yeah.... so that would seem to be a detail that I didn't think through;  unfortunately, the project reference will cause issues because we also reference that as a package transiently through the `CheckpointStore.Blobs` reference.... which causes some really unhappy situations during builds.

Thanks for illustrating in the draft PR;  you're right, that was helpful to visualize things.   I left some thoughts, but it looks like we're thinking pretty similarly for the most part.

**Comment by albertodenatale** [comment]
> the project reference will cause issues because we also reference that as a package transiently through the `CheckpointStore.Blobs` reference

That would prompt me to ask you if we should not check-in the ```InternalsVisibleTo``` now, in order to have it ready for when ```Azure.Messaging.EventHubs (5.0.0-preview.6)``` will be out?

**Comment by jsquire** [comment]
> > the project reference will cause issues because we also reference that as a package transiently through the `CheckpointStore.Blobs` reference
> 
> That would prompt me to ask you if we should not check-in the `InternalsVisibleTo` now, in order to have it ready for when `Azure.Messaging.EventHubs (5.0.0-preview.6)` will be out?
> 
I'm thinking we probably should strongly consider just writing a simple parser and accept a bit of code duplication to avoid the additional complexity in the referencing.   It feels like quite a bit of heavy changes to avoid duplicating a very small and specialized bit of code.    Thoughts?    Am I overlooking some additional benefits?

**Comment by albertodenatale** [comment]
> Thoughts? Am I overlooking some additional benefits?

That's what I call critical thinking!

I love how you broke down the problem, complexity vs duplication.

The only major issue I could see is if there was a bug fix and we forgot to take it in the copied version, but it would become visible quite quickly being this a testing environment.

The ```Shared``` folder limits the number of copies to two.

If we added in future a copy of something else, we might still be in time to add a reference.

I absolutely love it, let's go for it.

**Comment by albertodenatale** [comment]
To be honest I am not sure if you thought to all these things or if it just me that I am overthinking it? It might be just me actually :smile:
