### ISSUE TITLE
Flaky build: attribute 'EventProcessorClient' that could not be resolved 

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#8590]
Some builds fail with the following error:

```
BlobPartitionManager.cs(283,91): error CS1574: XML comment has cref attribute 'EventProcessorClient' that could not be resolved [D:\a\1\SourceDirWith49CharsLengthTestForLongPaths\sdk\eventhub\Azure.Messaging.EventHubs.CheckpointStore.Blobs\src\Azure.Messaging.EventHubs.CheckpointStore.Blobs.csproj]
```

Restart makes the failure go away.

Example: https://dev.azure.com/azure-sdk/public/_build/results?buildId=177551&view=logs&j=96d7b680-dcef-5cfd-cab1-6c247ea8b6c3&t=6fa7484a-d027-52bc-0b8f-217fe61fafa9&l=162

cc @weshaggard @danieljurek @chidozieononiwu @jsquire

**Comment by pakrym** [comment]
This now fails a lot more: https://dev.azure.com/azure-sdk/public/_build/results?buildId=177647&view=logs&j=1e00682f-6081-5348-8da2-7d601664b2e3

**Comment by jsquire** [comment]
**Context:**  This type was renamed in the latest release; this appears to be a transient (but sometimes difficult to clear) exception related to resolving the NuGet package dependency for Event Hubs 5.0.0-preview.5; this issue began after moving to a package reference (from project reference) this morning.

**Comment by weshaggard** [comment]
I believe I have fixed this by overwriting some invalid packages on our blob feed with the versions we GA'ed this week. I'm going to close this issue now but please do re-open if you see any other similar failures.
