### ISSUE TITLE
Consider removing ReliableOperation helpers from Storage SDKs

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#8608]
All HTTP related retries should be handled as part of the pipeline.

Using ReliableOperation causes things to be retried more times than expected.

cc @tg-msft

**Comment by JimSuplizio** [comment]
Hi @pakrym, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
