### ISSUE TITLE
[BUG] Code generation script is not working for EventGrid Management.

### ISSUE THREAD

**Issue by ahamad-MS** [Azure/azure-sdk-for-net#8619]
**Describe the bug**
We are trying to generate the .NET SDK for Event Grid management using the provided generate.ps1 script under sdk\eventgrid\Microsoft.Azure.Management.EventGrid\src . The script keeps failing with message: 
Start-AutoRestCodeGeneration : Could not find root for output directory since script is not run from SDK repo, please provide this using the -SdkRepoPath parameter!

Trying to provide the SDK repro info with -SdkReproPath fails that the parameter SdkReproPath is invalid. The error is: 
Start-AutoRestCodeGeneration : A parameter cannot be found that matches parameter name 'SdkRepoPath'.

I uninstalled node.js and reinstalled it again and went through the installation steps for autorest and I still hit the issue. 

I found another similar [open] issue (https://github.com/Azure/azure-sdk-for-net/issues/6309 ) that indicates that things started to fail due to folder structure change. I don't find a solution for this issue though.

***Exception or Stack Trace***
Add the exception log and stack trace if available

PS E:\SDK2020-0101P\net2\azure-sdk-for-net\sdk\eventgrid\Microsoft.Azure.Management.EventGrid\src> E:\SDK2020-0101P\net2\azure-sdk-for-net\sdk\eventgrid\Microsoft.Azure.Management.EventGrid\src\generate.ps1
Start-AutoRestCodeGeneration : Could not find root for output directory since script is not run from SDK repo, please provide this using the -SdkRepoPath parameter!
At E:\SDK2020-0101P\net2\azure-sdk-for-net\sdk\eventgrid\Microsoft.Azure.Management.EventGrid\src\generate.ps1:1 char:1
+ Start-AutoRestCodeGeneration -ResourceProvider "eventgrid/resource-ma ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Start-AutoRestCodeGeneration

**To Reproduce**
1. Start developer command prompt for VS 2017 in elevated mode.
2. cd to E:\SDK2020-0101P\net2\azure-sdk-for-net\sdk\eventgrid\Microsoft.Azure.Management.EventGrid\src
3. run powershell
4. run generated.ps1

Also also happen from running the scrip in Powershell ISE

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
Generated code for management API to be auto generated.

**Screenshots**

**Setup (please complete the following information):**
 - OS: [e.g. iOS] Windows Build 18362.418
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by isra-fel** [comment]
@ahamad-MS I believe you need to [update your build tools](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#updating-build-tools).
Let me know if it works for you, thanks.

**Comment by ahamad-MS** [comment]
Thanks @isra-fel  ! that seems to fix it. Issue resolved for me for now. thanks.
