### ISSUE TITLE
[FEATURE REQ] SecretClient should support existing MSAL authenticated Sessions

### ISSUE THREAD

**Issue by KSchlobohm** [Azure/azure-sdk-for-net#8621]
**Is your feature request related to a problem? Please describe.**
Documentation currently describes there are several Credential classes used to provide authorization to the `SecretClient` as shown [here](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/identity/Azure.Identity#credentials).

None of these solutions allows me to use a user principal that I have already established.

**Describe the solution you'd like**
After authenticating a user with the MSAL library I want to be able to reuse the existing context to access other resources (like Azure Key Vault). I do not want my users to be prompted multiple times during their session in my client application.

```cs
           var publicClientApp = PublicClientApplicationBuilder.Create(AzureAppRegistrationConfig.ClientId)
                        .WithAuthority(AzureCloudInstance.AzurePublic, AzureAppRegistrationConfig.TenantId)
                        .WithRedirectUri("http://localhost")
                        .Build();

           var authResult = publicClientApp.AcquireTokenInteractive(_scopes)
                        .WithAccount(accounts.FirstOrDefault())
                        .WithPrompt(Prompt.SelectAccount)
                        .WithUseEmbeddedWebView(false) //without this line the new window prompt can sometimes fail to open and the method will hang/do-nothing
                        .WithSystemWebViewOptions(options)
                        .ExecuteAsync(cancellationToken).Result;
```

Now that I have an `authResult` (and token) I'd like to give this context to the `SecretClient` object so that I can access Key Vault Secrets.

**Describe alternatives you've considered**
I have switched to using the `InteractiveBrowserCredential` object instead of using the above `PublicClientApplicationBuilder`.

**Additional context**
The documentation does not show whether or not this is a feature that already exists.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Description Added
- [x ] Expected solution specified

**Comment by AlexGhiondea** [comment]
@schaabs can you take a look?

**Comment by schaabs** [comment]
@KSchlobohm Thank you for the feedback. As you have already discovered the `InteractiveBrowserCredential` credential provides the interactive authentication flow. If this serves your purposes I'm glad to hear it. If not we welcome any feedback on how it might better fit your scenario.

The `InteractiveBrowserCredential` is actually built on top of the MSAL `PublicClientApplication`, but it doesn't expose the MSAL client through it's API. In the case you're application requires more control over authentication, or you need to share the `PublicClientApplication` instance with other portions of your program which authenticate clients outside of the Azure SDK, it is possible to provide your own `TokenCredential` implementation to use with the `SecretClient` or any other client which supports authenticating with a `TokenCredential`.  

Here is an example of an implementation which would perform interactive authentication when first called, and then silently authenticate any subsequent calls. It is modeled after the `InteractiveBrowserCredential` implementation.

~~~c#
    public class MyPublicApplicationCredential : TokenCredential
    {
        private readonly IPublicClientApplication _publicClientApp;
        private readonly IAccount _account;
        private SystemWebViewOptions _options;

        public MyPublicApplicationCredential(IPublicClientApplication publicClientApp, SystemWebViewOptions options)
        {
            _publicClientApp = publicClientApp;
            _options = options;
        }

        public override AccessToken GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken)
        {
            return GetTokenAsync(requestContext, cancellationToken).GetAwaiter().GetResult();
        }

        public override async ValueTask<AccessToken> GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
        {
            if (_account != null)
            {
                try
                {
                    AuthenticationResult result = await _publicClientApp.AcquireTokenSilent(requestContext.Scopes, _account).ExecuteAsync(cancellationToken).ConfigureAwait(false);

                    return new AccessToken(result.AccessToken, result.ExpiresOn));
                }
                catch (MsalUiRequiredException)
                {
                    return await GetTokenInteractiveAsync(requestContext.Scopes, cancellationToken).ConfigureAwait(false);
                }
            }
            else
            {
                return  await GetTokenInteractiveAsync(requestContext.Scopes, cancellationToken).ConfigureAwait(false);
            }
        }

        private async Task<AccessToken> GetTokenInteractiveAsync(string[] scopes, CancellationToken cancellationToken)
        {
            var authResult = await _publicClientApp.AcquireTokenInteractive(scopes)
                         .WithPrompt(Prompt.SelectAccount)
                         .WithUseEmbeddedWebView(false)
                         .WithSystemWebViewOptions(_options)
                         .ExecuteAsync(cancellationToken);

            _account = authResult.Account;
            return new AccessToken(authResult.AccessToken, authResult.ExpiresOn);
        }
~~~

Your application could then use your custom credential type to instantiate Azure SDK clients such as the `SecretClient`.

~~~ c#
    var publicClientApp = PublicClientApplicationBuilder.Create(AzureAppRegistrationConfig.ClientId)
                        .WithAuthority(AzureCloudInstance.AzurePublic, AzureAppRegistrationConfig.TenantId)
                        .WithRedirectUri("http://localhost")
                        .Build();

    var myCred = new MyPublicApplicationCredential(publicClientApp, options);
    
    var secretClient = new SecretClient("https://myvault.vaults.azure.net", myCred);
~~~

**Comment by KSchlobohm** [comment]
Thanks @schaabs, the `MyPublicApplicationCredential` example you provided is the class I was expecting the framework to provide.

In my situation, the `InteractiveBrowserCredential` class is even easier to work with but in other situations where I would want to use the authResult to access the authenticated user's information this `MyPublicApplicationCredential` class demonstrates a more flexible approach.

Is this a class that can be added to the documentation and/or Azure.Identity NuGet package?

**Comment by schaabs** [comment]
@KSchlobohm we probably won't add this class to Azure.Identity at least at this time as we are using the MSAL client more as an implementation detail and we have consciously avoided exposing it's API through Azure.Identity to give us flexibility in the future. However I do agree that we should have a sample which demonstrates creating and using such a credential type. I've created issue https://github.com/Azure/azure-sdk-for-net/issues/8694 to track this.

**Comment by KSchlobohm** [comment]
Thanks @schaabs that makes sense!
