### ISSUE TITLE
Unable to delete the key when test completed [AzConfig]

### ISSUE THREAD

**Issue by Prince269090** [Azure/azure-sdk-for-net#8624]
After test completion, below key and values are still available in the configuration explorer which should be deleted once test execution completes. 

```
Key= ~`!@#$^&()_+=[]{}|;"'<>./--1114869967
Value= value-~`!@#$^&()_+=[]{}|;"'<>./-
```

**Comment by AlexGhiondea** [comment]
@Prince269090 do you have a repro that we can look at? Does the SDK throw an error?

**Comment by annelo-msft** [comment]
This is an issue on the service side that they're planning to fix: https://github.com/Azure/AppConfiguration/issues/181

Once it is fixed, we should update our live tests to make sure they delete the special character settings at the end of the tests.

Thanks for finding this issue, @Prince269090, and for filing issues to track it!

**Comment by jsquire** [comment]
Moving this to the backlog milestone, as the associated milestone date has passed.

@AlexanderSher:  Since you're the assigned engineer, would you be so kind as to help route this to the correct milestone and epic?

**Comment by AlexGhiondea** [comment]
@AlexanderSher it looks like the associated issue on the service is resolved. Can we close this?

**Comment by AlexanderSher** [comment]
I've created the following test which I've run on existing AzConfig with several hundreds of previously created settings:
```cs
var connectionString = Recording.RequireVariableFromEnvironment("APPCONFIGURATION_CONNECTION_STRING");
var service = new ConfigurationClient(connectionString);
var selector = new SettingSelector {KeyFilter = "~`*"};

var settings = (await service.GetConfigurationSettingsAsync(selector).ToEnumerableAsync()).ToArray();

foreach (var setting in settings)
{
    await service.DeleteConfigurationSettingAsync(setting.Key);
}

var settingsAfterDelete = (await service.GetConfigurationSettingsAsync(selector).ToEnumerableAsync()).ToArray();

Assert.AreEqual(0, settingsAfterDelete.Length);
```

It has failed on the assert, but not on the `DeleteConfigurationSettingAsync`.

**Comment by AlexanderSher** [comment]
Found the error, it should be
```cs
await service.DeleteConfigurationSettingAsync(setting.Key, setting.Label);
```
@zhenlan, is it mandatory to provide `label` for the setting to be deleted?

**Comment by zhenlan** [comment]
I'm not sure about the API, but the service will only delete the key-value without a label if the label is not provided.

https://github.com/Azure/AppConfiguration/blob/master/docs/REST/kv.md#delete

**Comment by AlexanderSher** [comment]
Ok, that would require some changes in tests. @annelo-msft , why we don't raise an exception for the `204` status code?

**Comment by annelo-msft** [comment]
Short answer: 204 is a success code.

Longer answer: There are considerations around concurrency here.  It's possible one client will delete the key and get a 200, and then another will try to delete it, but since it's already deleted, get a 204. This is a success condition, since the intention was that the key would be deleted and it already is.  The same could happen with a single client due to retries.

**Comment by AlexanderSher** [comment]
Ok, so then I just need to change the tests so that they validate the code. No product change needed.
