### ISSUE TITLE
AsyncPageable should not contain a AsPages API

### ISSUE THREAD

**Issue by j82w** [Azure/azure-sdk-for-net#8628]
The current AsyncPageable as the following issues:

1. Item iterator having the ability to get a page iterator is not intuitive and is difficult to discover.
2. Page iterator should be preferred method for performance reasons.
3. AsyncPageable based on the name should be iterating over pages not items.
4. What happens if the user iterates over a few items then calls AsPages? Even if there is a guideline users will have to learn it. It would be a better user experience to avoid this complexity.

This is an example of number 4. Does AsPages return the first page, the rest of the existing page, new query that start from the beginning, or does it cause an exception?
```
AsyncPageable<SecretProperties> pageable = client.GetPropertiesOfSecretsAsync();
await foreach (SecretProperties secretProperties in pageable )
{
     IAsyncEnumerable<Page<T>> page = pageable.AsPages();
 }
```

Solutions:
1. AsyncPageable only does by page, and the user simply has to do 2 for loops
2. Have separate APIs for by page vs by item on the client.

**Comment by pakrym** [comment]
> Page iterator should be preferred method for performance 

This is a very controversial statement.

The current design was made with the idea that customers want items and paging is an advanced scenario leading to "Item iterator having the ability to get a page iterator is not intuitive and is difficult to discover.".

> AsyncPageable based on the name should be iterating over pages not items.

Again, it depends on the interpretation. I would agree with you if it was called AsyncPages but Pageable just conveys that paging is possible but not required.

> What happens if the user iterates over a few items then calls AsPages? Even if there is a guideline users will have to learn it. It would be a better user experience to avoid this complexity.

In current implementations pages are returned starting from the beginning. But I would argue this is a very advanced scenario that customers would rarely hit.

This API has shipped in GA version of Azure.Core and other libraries so proposed changes would be extremely breaking.

**Comment by j82w** [comment]
@pakrym I agree this is not worth a major version bump, but is there a place to store a list of backlog items of proposals that are breaking changes? That way in the future when a new major version is being worked on this can be reviewed again.

**Comment by pakrym** [comment]
The current plan is that we would not have a new major version because of a breaking changes ever. Libraries we ship should stay forever compatible.
