### ISSUE TITLE
Review ASP.NET Core extension methods before the next release

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#8635]
Figure out if we need one for processor.
And maybe merge AddEventHubConsumerClientWithNamespace into AddEventHubConsumerClient

**Comment by jsquire** [comment]
I reviewed and confirmed that what we have remains valid.   I added an extension for the processor client prior to GA.   I didn't merge anything at this point, leaving the extensions to match the available major constructors.
