### ISSUE TITLE
Deployment.Get() fails if Script Extension outputs Unicode logs

### ISSUE THREAD

**Issue by grant-d** [Azure/azure-sdk-for-net#864]
**Summary**
The output of the Azure Script Extension can break the parsing of the CloudService payload.
The specific break in this case was caused by a simple mis-spelling of a .msi installer.
MsiExec returns a Unicode error message which MAML is unable to handle.

**Impact**
High. The only workaround is to logon to the machine and delete the latest .status file.
This is not a contrived scenario - installing a .msi is common.
You can run another script to reset the status, since running a script requires a Deployment.Get first.

**Workaround**
See 5) below
(And in this case, fix spelling of .msi)

**Repro 1**
1) Run a script using the Azure Script Extension: &MSIEXEC.EXE /i "MisSpelt.msi" /qn /L*v Log.log
2) Give it enough time to start executing (a couple of mins)
3) Try do a Deployment.GetBySlot(Slot.Production)
4) The call fails with ".', hexadecimal value 0x00, is an invalid character. Line 1, position 5301."
5) RDP onto the VM, delete the latest .status file for the script extension, goto 3). Now it succeeds

**Repro 2**
Copy & paste the output below into the latest script .status file on a VM that has previously run a script successfully.
Goto 3) above

**Detail**
Here’s the (client) stack trace. As you can see this is bad XML returning from REST and/or bad parsing on the MAML stack:

**[XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 1, position 5301.]**
    Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task):49
    Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task):29
    **Microsoft.WindowsAzure.DeploymentOperationsExtensions.GetBySlot**(IDeploymentOperations operations, String serviceName, DeploymentSlot deploymentSlot):65

The .status file in this example has the following content:
*[{"status":{"code":0,"formattedMessage":{"lang":"en-US","message":"Finished executing command"},"name":"CustomScriptHandler","operation":"Command Execution Finished","status":"success","substatus":[{"code":0,"formattedMessage":{"lang":"en-US","message":"-Message Set PowerShell Context\\n\\nMajor  Minor  Build  Revision\\n-----  -----  -----  --------\\n4      0      -1     -1      \\n-Message Ensure well-known folders\\nVERBOSE: Performing the operation \"Create Directory\" on target \"Destination: \\nC:\\temp\".\\n\\nPSPath            : Microsoft.PowerShell.Core\\FileSystem::C:\\temp\\nPSParentPath      : Microsoft.PowerShell.Core\\FileSystem::C:\\\\nPSChildName       : temp\\nPSDrive           : C\\nPSProvider        : Microsoft.PowerShell.Core\\FileSystem\\nPSIsContainer     : True\\nName              : temp\\nParent            : \\nExists            : True\\nRoot              : C:\\\\nFullName          : C:\\temp\\nExtension         : \\nCreationTime      : 9\/26\/2014 3:36:21 AM\\nCreationTimeUtc   : 9\/26\/2014 3:36:21 AM\\nLastAccessTime    : 9\/26\/2014 3:36:21 AM\\nLastAccessTimeUtc : 9\/26\/2014 3:36:21 AM\\nLastWriteTime     : 9\/26\/2014 3:36:21 AM\\nLastWriteTimeUtc  : 9\/26\/2014 3:36:21 AM\\nAttributes        : Directory\\nBaseName          : temp\\nMode              : d----\\n\\n-Message Installing MisSpelt.msi\\n\\n\\nT\u0000h\u0000i\u0000s\u0000 \u0000i\u0000n\u0000s\u0000t\u0000a\u0000l\u0000l\u0000a\u0000t\u0000i\u0000o\u0000n\u0000 \u0000p\u0000a\u0000c\u0000k\u0000a\u0000g\u0000e\u0000 \u0000c\u0000o\u0000u\u0000l\u0000d\u0000 \u0000n\u0000o\u0000t\u0000 \u0000b\u0000e\u0000 \u0000o\u0000p\u0000e\u0000n\u0000e\u0000d\u0000.\u0000 \u0000 \u0000V\u0000e\u0000r\u0000i\u0000f\u0000y\u0000 \u0000t\u0000h\u0000a\u0000t\u0000 \u0000t\u0000h\u0000e\u0000 \u0000p\u0000a\u0000c\u0000k\u0000a\u0000g\u0000e\u0000 \u0000e\u0000x\u0000i\u0000s\u0000t\u0000s\u0000 \u0000a\u0000n\u0000d\u0000 \u0000t\u0000h\u0000a\u0000t\u0000 \u0000y\u0000o\u0000u\u0000 \u0000c\u0000a\u0000n\u0000 \u0000a\u0000c\u0000c\u0000e\u0000s\u0000s\u0000 \u0000i\u0000t\u0000,\u0000 \u0000o\u0000r\u0000 \u0000c\u0000o\u0000n\u0000t\u0000a\u0000c\u0000t\u0000 \u0000t\u0000h\u0000e\u0000 \u0000a\u0000p\u0000p\u0000l\u0000i\u0000c\u0000a\u0000t\u0000i\u0000o\u0000n\u0000 \u0000v\u0000e\u0000n\u0000d\u0000o\u0000r\u0000 \u0000t\u0000o\u0000 \u0000v\u0000e\u0000r\u0000i\u0000f\u0000y\u0000 \u0000t\u0000h\u0000a\u0000t\u0000 \u0000t\u0000h\u0000i\u0000s\u0000 \u0000i\u0000s\u0000 \u0000a\u0000 \u0000v\u0000a\u0000l\u0000i\u0000d\u0000 \u0000W\u0000i\u0000n\u0000d\u0000o\u0000w\u0000s\u0000 \u0000I\u0000n\u0000s\u0000t\u0000a\u0000l\u0000l\u0000e\u0000r\u0000 \u0000p\u0000a\u0000c\u0000k\u0000a\u0000g\u0000e\u0000.\u0000\\n\u0000\\n\u0000"},"name":"StdOut","status":"success"},{"code":0,"formattedMessage":{"lang":"en-US","message":""},"name":"StdErr","status":"success"}]},"timestampUTC":"\/Date(1411802311744)\/","version":"1"}]*

If you remove the noise, this translates to:
*This installation package could not be opened.  Verify that the package exists and that you can access it, or contact the application vendor to verify that this is a valid Windows Installer package.*

**Comment by singhkay** [comment]
This was fixed by a recent code change. Closing
