### ISSUE TITLE
[BUG] ProcessExceptionAsync fires with MaximumReceiveWaitTime set to null

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#8641]
With the following code 

``` C#

 _processor = new EventProcessorClient(
                EventHubConsumerClient.DefaultConsumerGroupName, new InMemoryPartitionManager(), configuration["Uploads:connectionString"],
                configuration["Uploads:eventHubName"]);
    
            _processor.ProcessEventsAsync = ProcessEvents;
            _processor.ProcessExceptionAsync = (context, exception) => {
                _logger.LogError(exception, "Error in " + context);
                return Task.CompletedTask;
            };
            await _processor.StartAsync();
```

I get callbacks with 0 events with some interval ~30sec.

**Comment by jsquire** [comment]
This one is on the odd side, but looks like a bug.     `PartitionPump` currently does a receive on line 259 using the wait time from the default options, which should be null.   Either that call is returning when it should not and triggering the conditional on 278,  liekly logic in the AmqpConsumer on line 162.   If that behavior doesn't match the track one code, we'll need to adjust there, otherwise, we'll need to adjust the logic in the pump to add a check for non-null on the wait time.

**Comment by jsquire** [comment]
Confirming that the AmqpConsumer behavior is consistent with the track one code and the associated comments;  Receive on the consumer does not wait indefinitely and will emit an empty set when the wait time (defaulted to the per-try timeout specified by the retry options) has elapsed.

- [Track One default](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Microsoft.Azure.EventHubs/src/PartitionReceiver.cs#L159) is the default operation timeout from the client.

- [Track Two default](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/src/Amqp/AmqpConsumer.cs#L162) is the try timeout.   This behavior will be preserved on the low-level receiver in the new design.

Going forward, this should not be an issue, as the iterator will wait indefinitely unless explicitly canceled or a wait time is specified.  Once the processor is converted over, there shouldn't be further need to filter that out.   Tracked by [#7409](https://github.com/Azure/azure-sdk-for-net/issues/7409), in scope for GA release.

**Comment by jsquire** [comment]
@kinelski:  Would you be so kind as include a test for this with the refactoring?

**Comment by jsquire** [comment]
Processor has been refactored and is no longer responsible for managing the wait time.   The consumer has a set of tests validating the wait time behavior.   Closing this out, as it is expected to behave as advertised in the next release.
