### ISSUE TITLE
EventHubs:  Need ContentType from underlying AMQP message exposed on EventData

### ISSUE THREAD

**Issue by clemensv** [Azure/azure-sdk-for-net#8653]
For mapping [CloudEvents](https://github.com/cloudevents/spec) correctly onto EventHubs, we will need the ContentType property mapped to the EventData structure from and to the underlying AMQP message.

**Comment by AlexGhiondea** [comment]
/cc @serkantkaraca 

Also /cc @jsquire for Track 2.

**Comment by jfggdl** [comment]
@clemensv, Thanks for creating this issue Clemens. When would you like this feature implemented.

@serkantkaraca - please let us know if this should be added to our backlog (if its effort is beyond a couple of hours/days, for example).

**Comment by serkantkaraca** [comment]
ContentType is already provided in SystemProperties of EventData. Is the ask different here? @clemensv, can you provide more details?

https://github.com/Azure/azure-sdk-for-net/blob/0be76a78b6e8cb86f1316d158fa63b3595763f64/sdk/eventhub/Microsoft.Azure.EventHubs/src/Amqp/AmqpMessageConverter.cs#L227

**Comment by clemensv** [comment]
I need a strongly typed representation of that. It's apparently so obscure that I missed it, and ContentType should be first-class. Indeed, it should be a top-level property right on EventData, because otherwise you have no way to declare what your binary content contains. The same must apply to the new APIs. 

=> EventData.ContentType

**Comment by serkantkaraca** [comment]
Sent PR for feature request - https://github.com/Azure/azure-sdk-for-net/pull/14047

**Comment by serkantkaraca** [comment]
Merged

**Comment by pherbel** [comment]
EventData.ContentType property also should be in the Azure.Messaging.EventHubs package.

As I know that Azure.Messaging.EventHubs is the latest and Microsoft.Azure.EventHubs is considered as a legacy. Right?

@serkantkaraca Why is #14047 fix only in the legacy package?

Thanks

**Comment by jsquire** [comment]
Hi @pherbel: `Azure.Messaging.EventHubs` has a different development cadence and is not intended to evolve in parallel to `Microsoft.Azure.EventHubs`.    The addition of content type for `Azure.Messaging.EventHubs` is part of a larger effort to better expose the entire AMQP information model, which is still in the design phase.   I[#8656](https://github.com/Azure/azure-sdk-for-net/issues/8656) can be used to track content type, specifically, in the new library.
