### ISSUE TITLE
Automation prevents packages that aren't preview or GA from shipping to nuget

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-net#8654]
In the event that a UP build is manually initiated with a version number that should not be released, some validation should prevent release of packages with non-releasable version numbers.

**Comment by chidozieononiwu** [comment]
DocWarden currently indexes all packages during which it also pulls out the current versions. We could easily check during the iteration to make sure the versions are correct and break the build if its a release build. @scbedd  what do you think about including this feature in DocWarden.

**Comment by weshaggard** [comment]
We already have some protection against not publishing the same version in our git tagging step and nuget will also block if we try to publish the same version twice. We also have some automation going into place that will help normalize the versioning format I don't think we need any other version validation at this time, so I"m closing this issue.
