### ISSUE TITLE
Expose ContentType from underlying AMQP message via SystemProperties

### ISSUE THREAD

**Issue by clemensv** [Azure/azure-sdk-for-net#8656]
I need the ContentType property from the underlying AMQP message exposed for mapping CloudEvents correctly.

**Comment by jsquire** [comment]
This is pending the outcome of the discussion between Serkant and Clemens in #[8653](https://github.com/Azure/azure-sdk-for-net/issues/8653).  Once Serkant and the Event Hubs team lock on a design, we'll pick this up and adapt that design for inclusion in the track two client.

For now, returning to the backlog.

**Comment by jsquire** [comment]
Closing this in favor of moving the scope into #20105, all-up issue to expose the full AMQP message model.
