### ISSUE TITLE
Microsoft.WindowsAzure.Management.MediaServices.CreateAsync fails with error "The server encountered an internal error. Please retry the request."

### ISSUE THREAD

**Issue by mottagare** [Azure/azure-sdk-for-net#866]
I am trying to create a media services account using the Media Services management library. Whilst calling CreateAsync I get an error back with the non helpful message "The server encountered an internal error. Please retry the request.".

I use Azure Active Directory for authentication. I can successfully get a list of media services account using the library and also calling the Get-method to get individual accounts, so my credentials should be valid.

Exampel of a call made:
RequestId
3509d9be42055e9e8dedcf61c9ff1f32

**Comment by shahabhijeet** [comment]
please reopen if this is still an issue.
