### ISSUE TITLE
Broken API reference links in azure-sdk repo under releases/2019-11

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/azure-sdk-for-net#8661]
All the [API reference links](https://github.com/Azure/azure-sdk/blob/master/releases/2019-11/2019-11-dotnet.md#quick-links) are broken except storage in [azure-sdk](https://github.com/Azure/azure-sdk) repo.

**Comment by pakrym** [comment]
cc @chidozieononiwu

**Comment by chidozieononiwu** [comment]
Fixed with https://github.com/Azure/azure-sdk/pull/772
