### ISSUE TITLE
SubscribeToEvents method is hard to find

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#8672]
I've tried the EH preview.5 libraries and one thing that took me longer than expected was the SubscribeToEvents method. `ReceiveAsync` was an obvious one I've tried  but it returned `IEnumerable<EventData>` forcing me to write my own outer loop.

What about renaming `ReceiveAsync` to `ReceiveBatchAsync`? And `SubscribeToEvents` to `ReceiveAsync`?

**Comment by jsquire** [comment]
We're in the midst of an overhaul to the client hierarchy and design.    I'm going to close this out, as there are new names and new locations for the concepts that are under discussion here.    Pending final board review, the design skeleton can be found in the following gist, if you'd like a preview:

[Event Hubs October Design Skeleton](https://gist.github.com/jsquire/3fadc1ea57594c31f1c39366c0d7b530)
