### ISSUE TITLE
Add samples demonstrating implementing TokenCredential directly with ADAL / MSAL

### ISSUE THREAD

**Issue by schaabs** [Azure/azure-sdk-for-net#8694]
There is a common scenario that Apps which already are using ADAL or MSAL to authenticate to services such as O365 also want to use the same instance of `AuthenticationContext` or `PublicApplicationClient` to authenticate to azure services. We should provide samples which demonstrate how to wrap an ADAL or MSAL client in a custom TokenCredential implementation to accomplish this.

I have a start to a such sample in response to the user issue https://github.com/Azure/azure-sdk-for-net/issues/8621

**Comment by christothes** [comment]
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/samples/DefiningCustomCredentialTypes.md#authenticating-with-msal-directly
