### ISSUE TITLE
AppAuthentication allowed using clientId and certificate without the tenantId, Idenitity doesn't

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#8698]
This is the snippet I've used:

![image](https://user-images.githubusercontent.com/1697911/68519825-5084c200-0248-11ea-852b-968b70283300.png)

cc @schaabs

**Comment by schaabs** [comment]
We don't currently have plans to fix this. If there is a specific scenario that this blocks please feel free to reopen.
