### ISSUE TITLE
[BUG] Xamarin Gives Invalid Image Error On ComputerVisionClient.AnalyzeImageAsync Call

### ISSUE THREAD

**Issue by corykroll** [Azure/azure-sdk-for-net#8700]
**Describe the bug**
ComputerVisionClient.AnalyzeImageAsync returns the error
System.IO.FileNotFoundException: 'Invalid Image'
This is running in a Xamarin.Forms app.
The same call from a .NET Core 3 app works properly.

***Exception or Stack Trace***
System.IO.FileNotFoundException
  Message=Invalid Image

**To Reproduce**
Create a new Xamarin.Forms project
Add Microsoft.Azure.CognitiveServices.Vision.ComputerVision NuGet v5.0.0
Call ComputerVisionClient.AnalyzeImageAsync with an authenticated client, passing in a valid URL for a PNG image

***Code Snippet***
// Example from C# quickstart
// https://docs.microsoft.com/en-us/azure/cognitive-services/computer-vision/quickstarts-sdk/csharp-sdk

            // Creating a list that defines the features to be extracted from the image. 
            List<VisualFeatureTypes> features = new List<VisualFeatureTypes>()
            {
                VisualFeatureTypes.Categories, VisualFeatureTypes.Description,
                VisualFeatureTypes.Faces, VisualFeatureTypes.ImageType,
                VisualFeatureTypes.Tags, VisualFeatureTypes.Adult,
                VisualFeatureTypes.Color, VisualFeatureTypes.Brands,
                VisualFeatureTypes.Objects
            };

            // Analyze the URL image 
            ImageAnalysis results = await client.AnalyzeImageAsync("https://moderatorsampleimages.blob.core.windows.net/samples/sample16.png", features);

**Expected behavior**
An ImageAnalysis object to be returned, like it does when using the same NuGet library and calls with a .NET Core 3 console project.

**Screenshots**
Not applicable

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : Visual Studio Community 2019 16.3.8
 - Version of the Library used v5.0.0

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x ] Bug Description Added
- [ x ] Repro Steps Added
- [ x ] Setup information Added

**Comment by AlexGhiondea** [comment]
@corykroll can you share the full exception message? What assembly is it failing to load?

**Comment by corykroll** [comment]
The exception didn't give me any details when referencing it via the NuGet.
I brought in the library, built it, and now I get a bit more information:

  at (wrapper managed-to-native) System.Reflection.Assembly.LoadFrom(string,bool,System.Threading.StackCrawlMark&)
  at System.Reflection.Assembly.InternalGetSatelliteAssembly (System.String name, System.Globalization.CultureInfo culture, System.Version version, System.Boolean throwOnFileNotFound, System.Threading.StackCrawlMark& stackMark) [0x000af] in <6de48997d0c0445dbea8d4d83492d8c6>:0 

This triggersd in ComputerVisionClientExtensions.cs line 80, which is this call:
using (var _result = await operations.AnalyzeImageWithHttpMessagesAsync(url, visualFeatures, details, language, descriptionExclude, null, cancellationToken).ConfigureAwait(false))

within this method:
public static async Task<ImageAnalysis> AnalyzeImageAsync(this IComputerVisionClient operations, string url, IList<VisualFeatureTypes> visualFeatures = default(IList<VisualFeatureTypes>), IList<Details> details = default(IList<Details>), string language = default(string), IList<DescriptionExclude> descriptionExclude = default(IList<DescriptionExclude>), CancellationToken cancellationToken = default(CancellationToken))

**Comment by corykroll** [comment]
Anything I can try?  NuGet packages I can take a look at?
I've tried preview builds for ComputerVision (v6.0.0-dev.20190919.3) and Xamarin.Forms (v4.4.0.991210-pre2) but the error continues to occur.

**Comment by corykroll** [comment]
```
{System.IO.FileNotFoundException: Invalid Image
File name: '/storage/emulated/0/Android/data/com.companyname.krollware.snapnsend/files/.__override__/en-US/Microsoft.Rest.ClientRuntime.resources.dll'
  at (wrapper managed-to-native) System.Reflection.Assembly.LoadFrom(string,bool,System.Threading.StackCrawlMark&)
  at System.Reflection.Assembly.InternalGetSatelliteAssembly (System.String name, System.Globalization.CultureInfo culture, System.Version version, System.Boolean throwOnFileNotFound, System.Threading.StackCrawlMark& stackMark) [0x000af] in <46c2fa109b574c7ea6739f9fe2350976>:0 }
```

**Comment by corykroll** [comment]
Got a little more debug info on this one.  Anything that can be done here?

**Comment by corykroll** [comment]
This issue no longer occurs in Visual Studio Community 16.4.0 Preview 6 (it came up in 16.3.10).  This also doesn't come up in Visual Studio for Mac 8.3.10).  Same code.  Best I can come up with is the issue is in Visual Studio itself.
