### ISSUE TITLE
[BUG] EventDataBatch disables diagnostic properties and plugins

### ISSUE THREAD

**Issue by gyuwon** [Azure/azure-sdk-for-net#8701]
`EventDataBatch` creates AMQP messages before the event sending process so when using it results the loss of `Diagnostic-Id`, `Correlation-Context` and any other properties set through plugins without any feedback.

I understand why `EventDataBatch` generates AMQP message when `TryAdd` is called but it would be better to give some warning at such situation.

**Comment by AlexGhiondea** [comment]
@gyuwon can you share more information about this? 
What library are you using?
What code are you writing for this?

**Comment by jsquire** [comment]
The mention of plugins identifies this as the track one library.   I'd like to ask @serkantkaraca, @sjkwak, or @JamesBirdsall to offer their thoughts.

**Comment by gyuwon** [comment]
The following code calculates the size of the event data but also generates AMQP message.

https://github.com/Azure/azure-sdk-for-net/blob/1264615ef858e1c368e1ba2b89771fdb1be69428/sdk/eventhub/Microsoft.Azure.EventHubs/src/EventDataBatch.cs#L84-L86

And `BeforeEventSend` method of `EventHubsPlugin` allows us to modify `EventData`.

https://github.com/Azure/azure-sdk-for-net/blob/1264615ef858e1c368e1ba2b89771fdb1be69428/sdk/eventhub/Microsoft.Azure.EventHubs/src/Core/EventHubsPlugin.cs#L29

But in the case of batch sending scenario, AMQP message was already created before run plugins so modifications from plugins are just ignored.

**Comment by serkantkaraca** [comment]
Thanks for reporting this. Let me check the code and provide you my findings.

**Comment by serkantkaraca** [comment]
We are going to have a fix in the next release.

**Comment by serkantkaraca** [comment]
Keeping the issue active. This will be fixed as part of 4.3 release. Thx.

**Comment by jsquire** [comment]
There should be no immediate action needed, per Serkant's comment.   Trimming up some tags to discourage the bot from interfering with the tracking and release process.

**Comment by serkantkaraca** [comment]
Fix is merged. This will be available by 4.3.0 release.
