### ISSUE TITLE
Add Performance project to TextAnalytics solution

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#8704]
- [ ] Figure out the infrastructure required to run the tests
- [ ] Figure out the scenarios we want to test
- [ ] Implement the scenarios
- [ ] Run the scenarios and analyze the results

**Comment by mayurid** [comment]
Related to test debt issue being looked at

**Comment by heaths** [comment]
Note: see https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/textanalytics/azure-ai-textanalytics/tests/perfstress_tests for what scenarios Python covered to make sure we're all on equal footing.

**Comment by maririos** [comment]
FR https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/formrecognizer/Azure.AI.FormRecognizer/perf/Azure.AI.FormRecognizer.Perf 
If you have questions, ping: Mohit-Chakraborty
