### ISSUE TITLE
Implement ClientBuilderExtensions

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#8709]

**Comment by maririos** [comment]
@annelo-msft could you provide more info about what the purpose of the issue is?

**Comment by AlexGhiondea** [comment]
This is related to the way Dependency Injection works in ASP.NET Core.

https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/core/Microsoft.Extensions.Azure

**Comment by maririos** [comment]
@AlexGhiondea is this required for each service? Does it has to happen for GA or could it be after?

**Comment by maririos** [comment]
@pakrym could you explain to me the work needed here? I see the document Alex shared, but it isn't clear where I need to make the changes. 
All we need to do is to register the client? or what else? Also, how do we test this?
What else am I missing?

**Comment by xantari** [comment]
Question, what is the recommended way to register a SearchIndexClient in asp .net core? It seems there are no dependency injection samples for Azure Cognitive Search out there!

**Comment by pakrym** [comment]
@xantari because the library is in preview there is no extension method yet, I'm sure that would change in later previews or GA (cc @tg-msft @heaths).

For now you can use `services.AddSingleton(new SearchIndexClient(...))`;

**Comment by tg-msft** [comment]
Yes - filed https://github.com/Azure/azure-sdk-for-net/issues/10848 to track.
