### ISSUE TITLE
Implement TextAnalyticsModelFactory

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#8710]

**Comment by maririos** [comment]
@annelo-msft could you provide more info about what the purpose of the issue is?

**Comment by maririos** [comment]
Do we need mocking tests?

**Comment by AlexGhiondea** [comment]
@annelo-msft is this still required?

**Comment by maririos** [comment]
My understanding is that this applies for mocking, but we already have something set up. 
What will be the remaining work here?

**Comment by annelo-msft** [comment]
The guidelines imply this is required: https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-mocking  Could we raise this up to Krzysztof to find out if other approaches are acceptable?

✅ DO provide factory or builder for constructing model graphs returned from virtual service methods.

Model types shouldn’t have public constructors. Instances of the model are typically returned from the client library, and are not constructed by the consumer of the library. Mock implementations need to create instances of model types. Implement a static class called <service>ModelFactory in the same namespace as the model types.

**Comment by KrzysztofCwalina** [comment]
> My understanding is that this applies for mocking, but we already have something set up.

What do we have setup? If you mean we have our recorded mocks, then the guideline is not about them. The guideline is to ensure that our customers (not us) can use mocking framework, like Moq, to unit test their code that uses our libraries.

**Comment by maririos** [comment]
An example: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/appconfiguration/Azure.Data.AppConfiguration/src/ConfigurationModelFactory.cs
