### ISSUE TITLE
Refactor TextAnalyticsClient to remove duplication

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#8711]
There is a great deal of code duplication across methods in TextAnalyticsClient.  KeyVault has some nice patterns around making each of the client calls just a few lines long.  Look into adopting these patterns.

https://github.com/Azure/azure-sdk-for-net/pull/8677#discussion_r345396211
https://github.com/Azure/azure-sdk-for-net/pull/8677#discussion_r345399295

https://github.com/Azure/azure-sdk-for-net/pull/8677#discussion_r345555438

**Comment by maririos** [comment]
Because of the work in https://github.com/Azure/azure-sdk-for-net/issues/12951 this is no longer needed
