### ISSUE TITLE
Investigate the use of CultureInfo

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#8712]
CultureInfo could be used to represent CountryHint and Language instead of strings.  Consider using this.  Understand what standards it represents, and if we were to adopt it in .NET, what the implications would be for APIs in other languages.

**Comment by mayurid** [comment]
@annelo-msft to investigate and discuss with @KrzysztofCwalina

**Comment by maririos** [comment]
The service team is actually using `CultureInfo.GetCultures(CultureTypes.SpecificCultures)`, they don't have a list of available country hints or languages, which makes me think that we shouldn't maintain a list either.
Still looking how to take advantage of CultureInfo...

**Comment by maririos** [comment]
Decision was to leave input parameters as is, and not create enum for country or language. User can always use other .NET libraries as helpers like RegionInfo, CultureInfo
