### ISSUE TITLE
Automate breaking large batches into smaller groups

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#8713]
For lage batches of input, provide the capability to break these into batches that respect the service's request size limitations.  

Provide knobs for users to tune throughput vs. response time.  Add to ClientOptions?

**Comment by mayurid** [comment]
Needs investigation with the Arch boarch. @kristapratico will be investigating.

**Comment by maririos** [comment]
Just curious, @kristapratico were you looking into this?

**Comment by mayurid** [comment]
I dont believe we will be looking into this in library side.
