### ISSUE TITLE
[FEATURE REQ] [Azure Cognitive Search] Add method to escape Lucene queries

### ISSUE THREAD

**Issue by brjohnstmsft** [Azure/azure-sdk-for-net#8719]
(This issue was created to track [this User Voice feedback](https://feedback.azure.com/forums/263029-azure-search/suggestions/32114773-provide-method-for-escaping-characters-in-the-sear)).

Special characters must be escaped to be used as part of the search text. You can escape them by prefixing them with backslash (`\`). Special characters that need to be escaped include the following: 
`+ - && || ! ( ) { } [ ] ^ " ~ * ? : \ / `

Currently there is no built-in method in the SDK, basically the equivalent of `UrlEscape`, which can do this, so every developer has to create their own implementation.

Note that this is a separate concern from the URL-encoding of search text when sent in the URL query string, or JSON encoding of the search text when sent in the request body. The SDK already handles both of those cases.

**Comment by xdansmith** [comment]
This issue has been idle for two years. Is this still a planned feature?
