### ISSUE TITLE
Single/multi-instance of EventGridClient

### ISSUE THREAD

**Issue by M0ns1gn0r** [Azure/azure-sdk-for-net#8722]
**Query/Question**
Should one re-use `EventGridClient` instances like it's recommended for `HttpClient` or create them on a per-request basis ?

**Comment by banisadr** [comment]
@ahamad-MS feel free to fact check me if you disagree, but in general you should re-use the instances because it is more efficient.

**Comment by ahamad-MS** [comment]
While it is all application dependent, but as @Banisadr indicated, reusing the EventGridClient instance is more efficient.
