### ISSUE TITLE
Create mechanism for building metapackage

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#8728]
We need to have a mechanism for producing metapackages (packages that only reference other packages).

For now, we want to create one for Azure.Storage which will pull in the Azure.Storage.Blobs package

**Comment by pakrym** [comment]
Do we want something more than just a project referencing other projects?

**Comment by kurtzeborn** [comment]
It was decided to remove the meta package for .Net instead of keeping it around and constantly updating it.
