### ISSUE TITLE
Creating a StorageService using ResourceManagementClient fails with "Accepted"

### ISSUE THREAD

**Issue by grant-d** [Azure/azure-sdk-for-net#873]
When creating a StorageService using the following code, it throws with CloudException.Message == "Accepted". The reason is likely due to line 404 of ResourceOperations.cs:

// ... Submit request...
if (statusCode != HttpStatusCode.OK && statusCode != HttpStatusCode.Created)
{ // ... throw... }

This line should probably include Accepted (202) as a valid result.

Repro code:
                    var armClient = new ResourceManagementClient(azureCreds);

                    var id = new ResourceIdentity()
                    {
                        ResourceProviderApiVersion = "2014-06-01",
                        ResourceProviderNamespace = "Microsoft.ClassicStorage",
                        ResourceName = "<storage service name>",
                        ResourceType = "storageAccounts"
                    };

                    var properties = @"{""accountType"": """ + "Standard-LRS" + @"""}";

                    var rsc = new BasicResource()
                    {
                        Location = this.Location,
                        Properties = properties
                    };

                    rsp = armClient.Resources.CreateOrUpdate(this.ResourceGroup, id, rsc);

// throws "Accepted" error

**Comment by matt-gibbs** [comment]
This is expected at this time. Once Storage is generally available in ARM, this will light up.
