### ISSUE TITLE
[BUG] PowerShell Core fails to load Azure.Core because of version dependency

### ISSUE THREAD

**Issue by erich-wang** [Azure/azure-sdk-for-net#8739]
**Describe the bug**
Azure.Core should depend on System.Diagnostics.DiagnosticSource nuget package 4.5.1 instead of 4.6 to make it work in PowerShell Core.

PowerShell Core 6.2.2 (released this July) has dependency on version 4.0.3.1 of System.Diagnostics.DiagnosticSource, however Azure.Core depends on higher version 4.0.4.0. PowerShell Core will automatically load 4.0.3.1 of System.Diagnostics.DiagnosticSource when starting, later when loading modules depending on Azure.Core, PowerShell Core will report failure because it need higher version 4.0.4.0 of System.Diagnostics.DiagnosticSource.

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by pakrym** [comment]
Downgrading the dependency is a breaking change and we need 4.6 to function properly.

This would be fixed by PowerShell core 7 shipping with updated dependencies: https://github.com/PowerShell/PowerShell/releases/tag/v7.0.0-preview.5

**Comment by pakrym** [comment]
There is also `System.Runtime.CompilerServices.Unsafe` pinned by powershell that Azure libraries use and they can't not be lowered or removed.
