### ISSUE TITLE
Provide helper method to parse a query string into SearchParameters

### ISSUE THREAD

**Issue by hugobarona** [Azure/azure-sdk-for-net#8740]
**Query/Question**
Before i can classify this as a bug or feature request, i would like to understand if there is a way to achieve my need. So, i followed the documentation with examples of OData queries. I used one of the examples using the $orderby parameter in the Azure portal, running the query in the Search explorer. When i tried to map the exact same query to the Search Index Client, setting the query in the query field ($orderby=BaseRate asc), i was not getting the same results. Then looking to the documentation, i saw some examples using the SearchParameters object and the OrderBy property. So then i tried to create an instance of the SearchParameters and pass it in the search, and it worked. So, now my question is if it would be possible to use the query parameter, as it is in the Search explorer in the portal (for the query string), instead of being required to build a SearchParameters object. So if i have the following query:

"$orderby=BaseRate asc, LastModifiedDate desc, ItemID asc, Location desc"

Instead of parsing the $orderby parameters and create the collection for the Orderby property of the SearchParameters, i could just forward the query to the search query and run the search.

So, instead of having this code:

`var results = searchIndexClient.Documents.Search<Items>("*", new SearchParameters {
    OrderBy = new string[] {  "BaseRate asc", "LastModifiedDate desc", "ItemID asc", "Location desc"}
 });`

i could have the following, without the need to parse the query coming from the client

`var results = searchIndexClient.Documents.Search<Items>("$orderby=BaseRate asc, LastModifiedDate desc, ItemID asc, Location desc");`

If the SearchParameters object is required in these scenarios when we have orderby or filter parameters, then the SDK could be able behind the scenes to parse the query and fill the parameters.

***Why is this not a Bug or a feature Request?***
For now i am trying to understand if this is already available somehow, and i just missed it.

**Comment by brjohnstmsft** [comment]
Hi @hugobarona,

The functionality you're looking for is not exposed by the SDK today, so we'll treat this as a feature request. I've updated the issue title accordingly and will make sure we're tracking this for a future SDK release. Thanks for reporting it!

**Comment by brjohnstmsft** [comment]
FYI @AlexGhiondea 

The justification for this feature is that it would make it easier for users to transition from using Search Explorer in the Portal to using the SDK. Perhaps another approach we could take is have the Portal generate SDK code in various languages for initializing `SearchParameters` (to be called `SearchOptions` or `SearchQuery` in the Track 2 SDK I believe)?

**Comment by AlexGhiondea** [comment]
This is a good suggestion but this isn't something we are ready to pursue in the client library right now.
