### ISSUE TITLE
EventProcessor is getting slow on big traffic

### ISSUE THREAD

**Issue by bilalmalik777** [Azure/azure-sdk-for-net#8743]
It was working perfectly in dot net core 2.1. Recently i updated my app to dot net 2.2, so every environment start to show memory consumption 99%.

I am keeping all code in using block, like getting service from dependency injection and calling and consuming DB, etc. I am also calling context.CheckpointAsync(); at ten end of ProcessEventsAsync method. Please help to solve this performance issue owing to which lag is coming. I add a code below which is doing problem

> 
      public async Task ProcessEventsAsync(PartitionContext context, IEnumerable<EventData> messages)
        {
            using (var serviceScope = Program.ServiceProvider.GetRequiredService<IServiceScope>().CreateScope())
            using (var IMessagingService = serviceScope.ServiceProvider.GetService<IMessagingService>())
            {
                var sw = Stopwatch.StartNew();
                //// create service references.
                logger = serviceScope.ServiceProvider.GetService<ILogger<EventProcessor>>();
                var memorycache = serviceScope.ServiceProvider.GetService<IMemoryCache>();
                memorycache.Set<string>(CacheKeyConstants.CustomerEnvironment, Program.CustomerEnvironment);
                var service = serviceScope.ServiceProvider.GetService<IOutPutService>();
                var consumptionService = serviceScope.ServiceProvider.GetService<IMCService>();
                var tempService = serviceScope.ServiceProvider.GetService<ITempService>();
                var popupService = serviceScope.ServiceProvider.GetService<IPopUpService>();
                EquipmentMessageModel equipmentMessage;
                string messageData = string.Empty;

                foreach (var message in messages)
                {
                    sw.Start();
                    messageData = Encoding.UTF8.GetString(message.Body.Array);
                    equipmentMessage = JsonConvert.DeserializeObject<EquipmentMessageModel>(messageData);
                    if (equipmentMessage.Kind == MessageTypes.1 || equipmentMessage.Kind == MessageTypes.2)
                    {
                        sw.Stop();
                        sw.Reset();
                        messageData = string.Empty;
                        equipmentMessage = null;
                        return;
                    }

                    logger.LogInformation("Message web job started.");

                    await IMessagingService.SaveMessageToDb(messageData, equipmentMessage);
                    await this.ProcessMessageData(sw, messageData, service, consumptionService, tempService, popupService);
                    messageData = string.Empty;
                    equipmentMessage = null;
                    sw.Stop();
                    sw.Reset();
                    logger = null;
                }

                consumptionService = null;
                auxiliaryService = null;
                service = null;
                equipmentAlertService = null;
                memorycache = null;
                sw = null;
            }
            await context.CheckpointAsync();
        }

## Versions  
- OS platform and version: Microsoft azure app service
- .NET Version: 2.2 core
- NuGet package version :4.1.0

**Comment by serkantkaraca** [comment]
I think you should identify what is really causing high memory consumption with 2.2. Please take a process dump and check the heap.

**Comment by serkantkaraca** [comment]
No comm for a while. Please reactivate the issue if needed.

**Comment by bilalmalik777** [comment]
my apologies for not commenting regarding issue status. Actually the issue was in something else not in   EventProcessor. :)

**Comment by serkantkaraca** [comment]
Glad to hear issue is solved.
