### ISSUE TITLE
Package shared sources for Azure.Core

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-sdk-for-net#8751]
@pakrym 

**Is your feature request related to a problem? Please describe.**
To create a client, there are a certain set of shared sources from Azure.Core that are needed. However, these sources are nested into this repo. For external (not in the repo) consumers, it is difficult to access these sources. 

**Describe the solution you'd like**
Create a package with these sources that can be easily accessed, aka `Azure.Core.Shared`. This package does not contain the compiled DLL, but only the shared sources.

**Describe alternatives you've considered**
- Having Azure.Core in a separate repo, and then using Git sub-module to access them.
- Exposing the internal types as public.
- Including the sources as part of the current Azure.Core package.
- Creating a separate project for shared sources and having all clients reference that project. That project references the Azure.Core DLL, which only has public interfaces.

**Additional context**
This would be for use by the autorest.csharp generator, or any other clients external to this repository.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by pakrym** [comment]
We've packaged the generator along with Azure.Core shared sources into it's own package. I don't think we should be packing all of them wholesale just yet.
