### ISSUE TITLE
Fix the TOC on docs.microsoft.com

### ISSUE THREAD

**Issue by kaerm** [Azure/azure-sdk-for-net#8753]
All of our packages are linked under Core https://docs.microsoft.com/en-us/dotnet/api/overview/azure/core/client?view=azure-dotnet

**Comment by scbedd** [comment]
[Review Link](https://review.docs.microsoft.com/en-us/dotnet/api/overview/azure/?view=azure-dotnet&branch=smoke-test)
[PR Submitted](https://github.com/Azure/azure-docs-sdk-dotnet/pull/1090)

I have validated that:

`Azure.Storage.File`
`Azure.Storage.Blob`
`Azure.Identity`
`Azure.Core` 

Are all where we expect them to be located in the ToC. Evidence:

![image](https://user-images.githubusercontent.com/45376673/68909229-815e6e80-0702-11ea-9220-3e1e8f547a0f.png)
![image](https://user-images.githubusercontent.com/45376673/68909243-8ae7d680-0702-11ea-8dcc-2344193ea689.png)
![image](https://user-images.githubusercontent.com/45376673/68909253-94713e80-0702-11ea-8162-83027f79d113.png)
![image](https://user-images.githubusercontent.com/45376673/68909300-bc60a200-0702-11ea-84de-5813d3e10186.png)
