### ISSUE TITLE
Onboard Nov previews on docs.microsoft.com using public feeds

### ISSUE THREAD

**Issue by kaerm** [Azure/azure-sdk-for-net#8754]
https://www.nuget.org/packages/Azure.Data.AppConfiguration/1.0.0-preview.4
https://www.nuget.org/packages/Azure.Messaging.EventHubs/5.0.0-preview.5
https://www.nuget.org/packages/Azure.Security.KeyVault.Certificates/4.0.0-preview.6
https://www.nuget.org/packages/Azure.Storage.Files.DataLake/12.0.0-preview.6
https://www.nuget.org/packages/Azure.Storage.Files.Shares/12.0.0-preview.5

**Comment by kaerm** [comment]
Also adding Storage Datalake as preview  .Net Package: https://www.nuget.org/packages/Azure.Storage.Files.DataLake/12.0.0-preview.6

**Comment by scbedd** [comment]
Onboarded, but wrinkle here. I don't see a CI job for either preview or legacy.
