### ISSUE TITLE
How to obtain TokenCloudCredentials inside a webapi?

### ISSUE THREAD

**Issue by riccardobecker** [Azure/azure-sdk-for-net#876]
I have a portal where a user logs in using WAAD. After logging he/she can call some webapi's (inside the same MVC project). Inside that webapi I need to call some functions from the Azure Management Libraries. The question is: how can I obtain TokenCloudCredentails inside that webapi for the current user? (who logged in with valid credentials).

Obviously, I don't want people to login again calling AcquireToken since they already are logged in with valid WAAD credentials.

**Comment by bradygaster** [comment]
Though I don't have a specific code example handy to demonstrate this functionality, I showed off how to do multi-tenant auth from within a web application for this specific purpose - knowing how to pull the token out and re-use it - during my MAML presentation at TechEd Europe last year. 

The talk is recorded an available on Channel 9 here: http://channel9.msdn.com/Events/TechEd/Europe/2014/DEV-B316

The Multi-tenant demo begins at around 55:00, so just jump to that part of the talk and you'll see a walk-through, with code, on doing precisely what you're after. 

Hope this helps! For now I'm going to close this issue. If you need any further guidance please reach out to me directly via twitter (@bradygaster) and we'll work it out from there.
