### ISSUE TITLE
Distributed Tracing:  Move message spans outside of Send spans

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#8760]
Send scope and message scopes should be siblings not parent-children.

**Comment by jsquire** [comment]
From conversations, it is believed that this should be just moving the [instrumentation call](https://github.com/Azure/azure-sdk-for-net/blob/029ea4a756ceed7c24a8b35cf2e25d00dd26fa22/sdk/eventhub/Azure.Messaging.EventHubs/src/Producer/EventHubProducerClient.cs#L428) before the scope creation that follows.

**Comment by jsquire** [comment]
To test, https://github.com/Azure/azure-sdk-for-net/tree/master/samples/linecounter with AppInsights configured
