### ISSUE TITLE
[BUG] Wrong priority range in network configuration

### ISSUE THREAD

**Issue by microbecode** [Azure/azure-sdk-for-net#8775]
**Describe the bug**
When adding a NetworkSecurityGroupRule for an Batch Pool's network configuration the priority has to be between 150 and 3500 (inclusive). According to my tests this is correct and also documented correctly: https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.batch.protocol.models.networksecuritygrouprule.priority?view=azure-dotnet#Microsoft_Azure_Batch_Protocol_Models_NetworkSecurityGroupRule_Priority .

However in the API documentation for virtual networks the range is 100-4096 (https://docs.microsoft.com/en-us/rest/api/virtualnetwork/networksecuritygroups/createorupdate#securityrule). Shouldn't these ranges be the same?

***Code Snippet***
```
CloudPool pool = Client.PoolOperations.CreatePool(
	poolId: poolId,
	targetDedicatedComputeNodes: PoolNodeCount,
	virtualMachineSize: vmSize,
	virtualMachineConfiguration: CreateVirtualMachineConfiguration(CreateImageReference()));

pool.NetworkConfiguration = new NetworkConfiguration
{
	EndpointConfiguration = new PoolEndpointConfiguration(new InboundNatPool[]
	{
		new InboundNatPool("RDP", InboundEndpointProtocol.Tcp, 3389, 7500, 8000, new NetworkSecurityGroupRule[]
		{
			new NetworkSecurityGroupRule(120, NetworkSecurityGroupRuleAccess.Allow, "*")
		})
	})
};

try
{
	pool.Commit();
}
catch (Exception ex)
{
	if (ex.InnerException is Microsoft.Azure.Batch.Protocol.Models.BatchErrorException bex)
	{
		var myex = bex.Body.Values[2].Value;
		 Console.WriteLine(myex);
	}
	throw ex;
}

Here "myex" contains the error.
```

**Expected behavior**
I expect the priority ranges to be the same in both repos.

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : Visual Studio
 - Microsoft.Azure.Batch, Version=12.0.0.0,

**Additional context**
I got forwarded to this repo from: https://github.com/MicrosoftDocs/azure-docs/issues/42798

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Bug Description Added
- [x ] Repro Steps Added
- [x ] Setup information Added

**Comment by bgklein** [comment]
@microbecode The priority levels of 100-149 are reserved for Batch usage hence the different lower-bound. We believe the upper-bound is simply out-of-date and that the true upper bound is 4096. We will look to have this updated for the next release of the SDK.
