### ISSUE TITLE
Make countryHint an extensible enum

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#8780]
Make defaults strongly typed.

https://github.com/Azure/azure-sdk-for-net/pull/8677#discussion_r345395540

**Comment by annelo-msft** [comment]
We may move this to March, @mayurid

**Comment by maririos** [comment]
Related #8712

**Comment by maririos** [comment]
Close per https://github.com/Azure/azure-sdk-for-net/issues/8712
