### ISSUE TITLE
Expose internal constructor of RetryExponential policy to configure DeltaBackoff parameter

### ISSUE THREAD

**Issue by darjanbogdan** [Azure/azure-sdk-for-net#8785]
### Description
At the moment, there is no way to configure `DeltaBackoff` parameter when instantiating `RetryExponential` policy. Although, the former _Windows.Azure.ServiceBus_ client has that possibility, this one doesn't have it since contructor is marked as [internal](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Microsoft.Azure.ServiceBus/src/RetryExponential.cs#L26).

### Current Solution
In order to circumvent the issue, I had to instantiate class using its internal constructor via reflection, which I definitely want to avoid:
```
var internalCtor = typeof(RetryExponential)
    .GetConstructors(BindingFlags.NonPublic | BindingFlags.Instance)
    .Single();

var instance = (RetryExponential)internalCtor.Invoke(
    new object[] { TimeSpan.FromMinutes(2), TimeSpan.FromMinutes(8), TimeSpan.FromMinutes(2), 3 }
    );

Console.WriteLine(instance.DeltaBackoff); // 00:02:00
```

~Please note, I saw it is possible to override `OnShouldRetry` method, but it feels a bit strange to do it. I'm afraid copy-pasting the whole (existing) implementation and using other property as a "DeltaBackoff" could lead to issues when package version upgrades (e.g. change of algortihm), not to mention maintenance nightmare.~ I realized class is sealed, so this can be disregarded. 

### Potential Solution
So, if there is no valid reason to _hide_ possibility to configure `DeltaBackoff` would you consider making that constructor public as well? 

**Information Checklist**
- [x] Description Added
- [x] Expected solution specified

**Comment by darjanbogdan** [comment]
If the answer is affirmative, I'll be glad to make a PR :)

**Comment by axisc** [comment]
@darjanbogdan, 

sounds like a good idea. Please feel free to raise a PR :)

**Comment by ramya-rao-a** [comment]
Closing as the related PR #12256 is merged
