### ISSUE TITLE
[FEATURE REQ] App role assignment

### ISSUE THREAD

**Issue by et1975** [Azure/azure-sdk-for-net#8794]
**Is your feature request related to a problem? Please describe.**
I'm automating applications setup and role assignments.
Currently I can do most of it via `az`, but there's no .NET or the CLI alternative to PowerShell's [App Role Assignment](https://docs.microsoft.com/en-us/powershell/module/azuread/new-azureaduserapproleassignment?view=azureadps-2.0).

**Describe the solution you'd like**
I'd like to be able to create app role assignments w/o introducing PowerShell into the mix, preferrably via `IAuthorizationManagementClient` or similar interface.

**Describe alternatives you've considered**
`az` CLI feature request for this already exists, but not addressed: https://github.com/MicrosoftDocs/azure-docs/issues/33494
PowerShell is not an option, given this is a small new part of a large infrastruture setup that's already being managed from Linux w/o it. 
I considered importing PowerShell's AzureAD DLLs for this, but it looks too complicated for a single task. 

**Additional context**
N/A

**Information Checklist**
- [x] Description Added
- [x] Expected solution specified

**Comment by krispenner** [comment]
Similarly I would like to create service principal app role assignments. This is nearly identical to the user flow requested, please add this at the same time. [New-AzureADServiceAppRoleAssignment](https://docs.microsoft.com/en-us/powershell/module/azuread/new-azureadserviceapproleassignment?view=azureadps-2.0)

For completeness, you could also support groups as well, but this is not required for me yet.
[New-AzureADGroupAppRoleAssignment](https://docs.microsoft.com/en-us/powershell/module/azuread/new-azureadgroupapproleassignment?view=azureadps-2.0)

Example powershell script for background:
```ps
function Add-ManagedIdentityToApplicationRole($ApplicationName, $RoleName, $IdentityName)
{    
    Write-Host "Ensuring managed identity $IdentityName is assigned the role $RoleName in application $ApplicationName."

    # Get the object ID of the managed identity's service principal
    Write-Host "Retrieving the service principal's object ID for the managed identity $IdentityName..."
    $msi = Get-AzureADServicePrincipal -Filter "DisplayName eq '$IdentityName'"
    $msiId = $msi.ObjectId
    Write-Host "Retrieved the service principal's object ID $msiId for the managed identity $IdentityName."

    # Get the object ID of the application's service principal (enterprise application)
    Write-Host "Retrieving the service principal's object ID for the enterprise application $ApplicationName..."
    $app = Get-AzureADServicePrincipal -Filter "DisplayName eq '$ApplicationName'"
    $appId = $app.ObjectId
    Write-Host "Retrieved the service principal's object ID $appId for the enterprise application $ApplicationName."

    # Get the role ID of the application's role to be assigned
    Write-Host "Retrieving the role ID for the role $RoleName in application $ApplicationName..."
    $app = Get-AzureADApplication -Filter "DisplayName eq '$ApplicationName'"
    $roleId = ($app.AppRoles | Where-Object { $_.Value -eq $RoleName } | Select -First 1).Id
    Write-Host "Retrieved the role ID $roleId for the role $RoleName in application $ApplicationName."

    # Check if the managed identity has already been assigned the app role in the enterprise application
    Write-Host "Checking if managed identity $IdentityName is already assigned the role $RoleName in application $ApplicationName..."
    if ((Get-AzureADServiceAppRoleAssignment -ObjectId $appId -All $true | Where-Object { $_.PrincipalId -eq $msiId -and $_.Id -eq $roleId }).Count -ge 1)
    {
        # Role is already assigned
        Write-Host "Managed identity $IdentityName is already assigned the role $RoleName in application $ApplicationName."
    }
    else
    {
        # Role is not already assigned, so assign the app role of the application to the web app's managed identity
        Write-Host "Managed identity $IdentityName is not already assigned the role $RoleName in application $ApplicationName."
        Write-Host "Assigning managed identity $IdentityName the role $RoleName in application $ApplicationName..."
        New-AzureADServiceAppRoleAssignment -ObjectId $msiId -Id $roleId -PrincipalId $msiId -ResourceId $appId
        Write-Host "Assigned managed identity $IdentityName the role $RoleName in application $ApplicationName."
    }
}

```

**Comment by navba-MSFT** [comment]
@et1975 Apologies for the late reply. Could you please refer the sample .NET code available [here](https://github.com/Azure-Samples/aad-dotnet-manage-users-groups-and-roles) which explains how to manage AAD user and Group and the role assignments ? Please let us know if you have any further questions on this. Awaiting your reply.

**Comment by et1975** [comment]
Classic case of "if you wait long enough the problem goes away on its own" :)

I should have posted here, but I've found the solution long ago. What you are referring to there is *Azure subscription roles*, not *application roles*. The confusion is understandable as the functionality I was looking for is not actually in azure SDK purview ever since MS Graph displaced Azure Graph - it's in [MS Graph SDK](https://docs.microsoft.com/en-us/graph/sdks/create-client?tabs=CS) now.

I had to reverse engineer the solution, as there was no documentation at the time, but here's the outline:
1. Create the client, passing the token acquisition method of your preference. The token scope requested should be "https://graph.microsoft.com/.default"
2. Use `client.Applications.Request().Filter()` to list roles
3. Use `client.ServicePrincipals[objectId].AppRoleAssignments.Request().AddAsync()` to add assignments
4. Use `client.ServicePrincipals[objectId].AppRoleAssignments[id].Request().DeleteAsync()` to remove assignments

Now, depending on the identity executing this it may require [certain permissions](https://docs.microsoft.com/en-us/graph/permissions-reference) on your AAD tenant's Graph. 
If you want a service principal to carry out these actions, it's even trickier (and outright impossible in our AAD tenant, for example due to governance). If you need this as part of user's workflow (ie. using user's identity via Auth Code/device code flow) the bar is lower - clientId of the application that's going to make these calls on your behalf needs to be allowed to impersonate you to access the graph api.

I don't know if there's a single document describing all this, but good luck to all the 50+ people who udooted.

**Comment by djsly** [comment]
Thanks @et1975 , I guess the question that remains, can your solution be used by AZ CLI ...

**Comment by et1975** [comment]
`az ad` CLI would indeed be good place for this functionality and since it has special relationship with AAD avoid the headache of setting up the correct permissions. This is SDK repo, so not really suitable for `az` cli discussions, but here's the workaround you could use: `az rest` to make calls to [graph APIs](https://docs.microsoft.com/en-us/graph/use-the-api).
For example:
```
BODY="{\"id\":\"$ROLE_ID\",\"principalId\":\"$PRINCIPAL_ID\",\"resourceId\":\"$APP_OBJ_ID\"}"
az rest --method post --uri "https://graph.windows.net/$TENANT_ID/servicePrincipals/$PRINCIPAL_ID/appRoleAssignments?api-version=1.6" --body "$BODY" --headers "Content-type=application/json"
```
