### ISSUE TITLE
Live tests use configurable /p:IncludeSamples

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-net#8808]
Live tests should include the ability to opt into samples (disabled by default, can be overridden in tests.yml)

**Comment by weshaggard** [comment]
@danieljurek is the goal here to enable running the samples with the live test runs and against live services?

**Comment by jsquire** [comment]
Given the age of this issue and the approach of live test snippets as samples, closing this as stale.  Please feel free to reopen if this is still needed.
