### ISSUE TITLE
[Storage] We need to check if user is attempting to use Bearer Token Auth with HTTP

### ISSUE THREAD

**Issue by seanmcc-msft** [Azure/azure-sdk-for-net#8810]
Currently, if a user attempts to use bearer token auth with HTTP, we actually send the request to the service and get a 403.  This is a security venerability because the bearer token is exposed in the non-encrypted request.

We should add a check either in Storage or Core, which will throw if the user attempts to do this.  It could potentially be configurable, so if the user doesn't want this check, it can be disabled.

**Comment by seanmcc-msft** [comment]
This definitely an issue in Blobs and Queues.

**Comment by schaabs** [comment]
I've added an explicit check for this in `BearerTokenAuthenticationPolicy` in PR https://github.com/Azure/azure-sdk-for-net/pull/8874

**Comment by schaabs** [comment]
Reopening this issue as you might also add an initial check when constructing storage clients so the user immediately gets an exception.
