### ISSUE TITLE
Response<T> is not disposable causing leaked TCP connections.

### ISSUE THREAD

**Issue by alexperovich** [Azure/azure-sdk-for-net#8819]
**Describe the bug**
`Response<T>` contains a disposable field but is not itself disposable. This is a huge problem because the object indirectly contains a HttpResponseMessage. HttpResponseMessage objects are one of the most important types to dispose because they hold on to TCP connections.

***Exception or Stack Trace***
N/A

**To Reproduce**
Try to put a `Response<T>` in a using.

***Code Snippet***
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/Response%7BT%7D.cs#L14

**Expected behavior**
`Response<T>` should be disposable so that HttpResponseMessage objects can be properly disposed.

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: all
 - IDE : any
 - 1.0.1

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by pakrym** [comment]
The `HttpResponseMessage` contained in Response<T> is guaranteed to be already disposed.

**Comment by alexperovich** [comment]
The it should not be accessible at all. If the message has been disposed then I shouldn't be able to read it.

**Comment by pakrym** [comment]
What shouldn't be accessible?

**Comment by alexperovich** [comment]
The `Response`, from a `Response<T>` I should not be able to access the `Response` object, because it contains the HttpResponseMessage and the content stream, both of which are useless if the HttpResponseMessage has been disposed.

**Comment by pakrym** [comment]
They are not useless, most of the time Response contains a buffered memory stream that is fully functional.

**Comment by alexperovich** [comment]
It still contains the HttpResponseMessage, and none of the code I saw to create a `Response<T>` guarantees that anything is disposed. An incorrectly written method that returns a `Response<T>` can very easily leak the responses. Normally you shouldn't dispose things that you return from a method, but you have to wrap the `Response` in a using despite returning it from the method to not write code that will cause problems running on a server.

**Comment by pakrym** [comment]
> An incorrectly written method that returns a Response<T> can very easily leak the responses.

Agreed, but making Response<T> disposable wouldn't fix this issue. Customers are even more likely to not dispose things.

That's exactly why we made a decision to keep Response<T> non-disposable and handle complexity in clients instead.

**Comment by alexperovich** [comment]
> Customers are even more likely to not dispose things.

If the type is disposable static analysis produces a warning/error for failing to dispose it. I think that is (sadly) ReSharper specific though. If the onus is on users of HttpPipeline to do the correct thing with Response objects then I guess its fine. It is just a very alarming experience as a dev when I put a `Response<T>` in a using and it doesn't work. I knew it was associated with a http response so it should be disposable to control the lifetime of the response.

Then I F12 to the implementation and see this `Response` field and see that it is disposable, but the parent class isn't. I then F12 on `Response` and see the `HttpResponseMessage` field and no way to dispose it from a `Response<T>` object. That raises a big red flag because the `HttpResponseMessage` is unavoidably leaked unless an already disposed instance was passed in. If the object was already disposed it should not be saved, that's just useless memory overhead and misleading when looking at the code.

**Comment by AlexandreArpin** [comment]
@pakrym 
> That's exactly why we made a decision to keep Response<T> non-disposable and handle complexity in clients instead.

Currently reviewing our dispose patterns and `using` in our applications since we _sometimes_ have DisposedExceptions.

We have a pretty big throughput of blobs in our applications, does your comment means the Client ensure the response's stream are correctly disposed?

Currently, we're doing the following

```
var response = await blob.DownloadAsync(cancellationToken);
using (response.Value)
{
    return steamDownloader.GetValue(response.Value.Content);
}
```

Is this not advised?

**Comment by pakrym** [comment]
@AlexandreArpin, you are doing the right thing here. `DownloadAsync` is one of the few client methods that return "live" network stream that has to be either read to the end or disposed.
