### ISSUE TITLE
Produce a dependency graph during CI

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk-for-net#8838]
Anywhere that we currently generate a dependency report we should also publish a dependency graph. #8597 and Azure/azure-sdk-tools#278 will be needed for the implementation.

**Comment by heaths** [comment]
Was there an exact audience for this large graph? With both track 1 and track 2 assemblies, there's so much in the graph it's difficult to navigate. Could we limit it to track 2 assemblies?

Also, we do have a need for the data (non-visual), but would need to generate dependencies for track 2 assemblies on an intersection of assemblies in PowerShell Core - or just their target assemblies in general (whether they ship them or not). Currently, in 7.0-preview.rc2, they are [using the 3.1.101 SDK](https://github.com/PowerShell/PowerShell/blob/master/global.json) and [targeting netcoreapp3.1](https://github.com/PowerShell/PowerShell/blob/master/PowerShell.Common.props#L98).

/cc @chidozieononiwu @AlexGhiondea

**Comment by bsiegel** [comment]
@heaths Just wanted to make sure you saw Azure/azure-sdk-tools#278 which documents many features which help you navigate the graph. Agreed that the fully expanded graph is pretty tough to grok.

**Comment by heaths** [comment]
Thanks. I must've glazed over that second issue link (looked at #8597 originally). Is there a way to filter this data, both in the UI but - more importantly - harvest some (for track 2 only) to make it easy for PowerShell to consume? Just a post-processing step after net.js is generated, I assume?

**Comment by bsiegel** [comment]
The data is exported in JSONP format, and for .NET the tool is actually written as a PowerShell script. It could definitely be tweaked/adjusted to make things easier for analysis with PowerShell.

**Comment by chidozieononiwu** [comment]
https://github.com/Azure/azure-sdk-for-net/pull/9964
