### ISSUE TITLE
[Storage][DataLake] Consider creating internal methods for DataLake APIs that call into blobs

### ISSUE THREAD

**Issue by seanmcc-msft** [Azure/azure-sdk-for-net#8843]
"The main thing that it would help with is avoiding the duplicate exception handling and scope stuff, but I would agree it is not high priority." - @JoshLove-msft

**Comment by JimSuplizio** [comment]
Hi @seanmcc-msft, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
