### ISSUE TITLE
EventProcessorHost not working behind corporate proxy

### ISSUE THREAD

**Issue by mathavanmani** [Azure/azure-sdk-for-net#8849]
Hi,

This issue has been originally reported part of https://github.com/Azure/azure-event-hubs-dotnet/issues/210 and @serkantkaraca has fixed it. But the fix has been applied only for **full framework**. Could you please this fix this for **.Net Core** as well ?

https://github.com/Azure/azure-sdk-for-net/blob/166356f5367ef208f27a096652148b886019a053/sdk/eventhub/Microsoft.Azure.EventHubs.Processor/src/AzureStorageCheckpointLeaseManager.cs,

`
#if FullNetFx
            // Proxy enabled?
            if (this.host.EventProcessorOptions != null && this.host.EventProcessorOptions.WebProxy != null)
            {
                this.operationContext = new OperationContext
                {
                    Proxy = this.host.EventProcessorOptions.WebProxy
                };
            }
#endif`

**Comment by serkantkaraca** [comment]
This is a limitation in Storage library. I have just checked and .Net Standard library still doesn't support proxy configuration.

**Comment by mathavanmani** [comment]
Hi @serkantkaraca , We have tested the EventHub using nuget library Azure.Messaging.EventHubs and Azure.Messaging.EventHubs.CheckpointStore.Blobs. It works as fine if we set the proxy in EventHubProducerClientOptions/EventProcessorClientOptions. 

This library is in preview at the moment , is this the library we should be using ? Other library Microsoft.Azure.EventHubs and Microsoft.Azure.EventHubs.Processor are going to maintained as well? 

Thanks

**Comment by jfggdl** [comment]
@mathavanmani, Are you referring to https://www.nuget.org/packages/Azure.Messaging.EventHubs/?

If so, that should be released early next year. If it is working for you, then that should be the package that you should use. Please just test all your scenarios (it is a preview) and if you have any feedback, please create another GitHub issue specific to the issue.

**Comment by mathavanmani** [comment]
Hi @jfggdl. Yes, I'm referring to https://www.nuget.org/packages/Azure.Messaging.EventHubs/. 

May I know the difference between the packages https://www.nuget.org/packages/Azure.Messaging.EventHubs/ and https://www.nuget.org/packages/Microsoft.Azure.EventHubs/.  

And also Whats the plan for future in terms of which one is going to be upgraded frequently ?

**Comment by jsquire** [comment]
Hi @mathavanmani.  Thank you for your feedback.

I'm glad to hear that the new version of the library is supporting your proxy scenario.  Unfortunately, I am not able to offer more insight around the potential release date for the new library but we do feel that the current version, preview.6, is in a good and stable place.   That said, it is still a preview, so I would caution against using it for critical production workloads until it does officially release.

There have been quite a few changes between v4 and the previews and also between preview.5 and preview.6.  If you're interested in exploring it further, you may find our [Migration Guide](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/MIGRATIONGUIDE.md) helpful in navigating the changes from the Event Processor Host in the v4 library.   We also have a fairly extensive set of [samples](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/eventhub/Azure.Messaging.EventHubs.Processor/samples) that illustrate some common scenarios.

We'd appreciate any feedback that you'd like to share about your experiences.  If you run into difficulties, please feel free to reach out here or on [Twitter](https://www.twitter.com/Jesse_Squire).

**Comment by jsquire** [comment]
With respect to your question around ongoing support and future enhancements for the `Microsoft.Azure.EventHubs` packages, I'll need to defer to @jfggdl.

**Comment by jfggdl** [comment]
Thanks for the question. The standard policy from Microsoft with respect to the period of support and deprecation of products/services is 3 years. This means that once the new Azure.Messaging.EventHubs SDK/package is released for General Availability (GA), we will still support Azure.Microsoft.EventHubs (v4) for 3 more years. However, priority for new features will be given to the new version.  
Please let me know if you have any more questions.

**Comment by jfggdl** [comment]
By the way, we are planning to close this issue. It looks like you have a viable path forward with the proxy support of Azure.Messaging.EventHubs albeit you will need to wait for its GA for production use.

**Comment by Protheon** [comment]
hi @mathavanmani . when you mentioned it worked, were you trying via websockets or tcp? from the documentation i see you cannot set proxy when attempting tcp. rgs
