### ISSUE TITLE
Build fails when switching package references to project references 

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/azure-sdk-for-net#8856]
When using `UseProjectReferenceToAzureClients`  to switch package references to project references for [Azure.Messaging.EventHubs.Processor ](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/eventhub/Azure.Messaging.EventHubs.Processor) library, It gives the below error-

![image](https://user-images.githubusercontent.com/45216704/69282147-72fad180-0b9e-11ea-98a8-17410bbe0837.png)

If we remove the above highlighted area, it works fine.

For more details refer  https://github.com/Azure/azure-sdk-for-net/pull/8821

**Comment by ShivangiReja** [comment]
cc: @weshaggard @Azure/azure-sdk-eng

**Comment by weshaggard** [comment]
This switch is intended to be used for the entire graph and not just part of the graph so this error is sort of expected as it is checking to verify that every Azure.* reference is a project reference.

**Comment by weshaggard** [comment]
Closing this issue let me know if there is a scenario we really need to support here.

**Comment by weshaggard** [comment]
#8872 should help make this a little clearer from the error it gives.
