### ISSUE TITLE
Azure Blob Storage: Connection String SAS

### ISSUE THREAD

**Issue by slipdef** [Azure/azure-sdk-for-net#8859]
Trying to upload blob to Azure Blob Storage using SAS based connection string. Crashed with the exception below. When using Access Key based connection string all works fine.

The specified resource does not exist.
RequestId:4affd386-201e-00d6-02f2-9f6b28000000
Time:2019-11-20T22:32:27.5499019Z
Status: 404 (The specified resource does not exist.)

ErrorCode: ResourceNotFound

Headers:
Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id: 4affd386-201e-00d6-02f2-9f6b28000000
x-ms-client-request-id: a73be4bc-348c-480d-8474-45ef2c806a57
x-ms-version: 2019-02-02
x-ms-error-code: ResourceNotFound
Date: Wed, 20 Nov 2019 22:32:26 GMT
Content-Length: 223
Content-Type: application/xml

Connecting string is copied from Azure portal, looks smth like this:
"BlobEndpoint=https://xxx.blob.core.windows.net/;SharedAccessSignature=sv=2019-02-02&ss=b&srt=sco&sp=rwdlac&se=2029-11-21T04:57:39Z&st=2019-11-19T20:57:39Z&spr=https&sig=<sig>"

***Exception or Stack Trace***
 at Azure.Storage.Blobs.BlobRestClient.BlockBlob.UploadAsync_CreateResponse(Response response)
   at Azure.Storage.Blobs.BlobRestClient.BlockBlob.<UploadAsync>d__0.MoveNext()

***Code Snippet***
client.GetBlobClient(blob.BlobName).UploadAsync(stream, allowOverwrite, cancellationToken);

 - Version of the Library used: 12.0.0.0

**Comment by amnguye** [comment]
Hello @slipdef !

Thank you for bringing this issue to our attention.

This is definitely a bug, we will definitely look into it and hope to have a fix for it in the January Release.

**Comment by amnguye** [comment]
Looks like when the url is constructed, it looks like we parse the SAS connection string fine, but when we go to construct it and make any request, it doesn't append on the SAS token to the url. That's what causes the authentication to fail, because it doesn't have the proper SAS token appended.

**Comment by kemmis** [comment]
does this work in previous versions of the sdk? I'm having the same issue as well.

**Comment by jongio** [comment]
@slipdef and @kemmis 

I wasn't able to repro with the following code.  Can you please tell me how your code differs from this code, so I can get a repro?  Thanks, Jon

```csharp
using Azure.Storage.Blobs;
using System;
using System.IO;
using System.Text;

namespace azure_blob_storage_test
{
    class Program
    {
        static void Main(string[] args)
        {
            var blobSasUri = new Uri("blob sas uri");
            var blobContainerSasUri = new Uri("blob container sas uri");
            
            var blobUriBuilder = new BlobUriBuilder(blobSasUri);
            var blobContainerClient = new BlobContainerClient(blobContainerSasUri);
            
            var contents = "Hello Blob 3";

            using (var stream = new MemoryStream(Encoding.ASCII.GetBytes(contents))) {
                var response = blobContainerClient.GetBlobClient(blobUriBuilder.BlobName).UploadAsync(stream, overwrite: true, cancellationToken: default(System.Threading.CancellationToken));
                var result = response.Result;
                Console.Write(result);
                Console.ReadKey();
            }
        }
    }
}
```

**Comment by slipdef** [comment]
Reproduced with the sample code below:

```
using System;
using System.IO;
using System.Text;
using Azure.Storage.Blobs;

namespace TestSAS
{
    class Program
    {
        static void Main(string[] args)
        {
            var connString = "BlobEndpoint= xxx";
            var blobContainerClient = new BlobContainerClient(connString, "testsas");
            
            var contents = "Hello Blob 3";

            using (var stream = new MemoryStream(Encoding.ASCII.GetBytes(contents))) {
                var response = blobContainerClient.GetBlobClient("testsas").UploadAsync(stream, overwrite: true, cancellationToken: default(System.Threading.CancellationToken));
                var result = response.Result;
                Console.Write(result);
                Console.ReadKey();
            }
        }
    }
}
```
Connection string:

![image](https://user-images.githubusercontent.com/4365327/69678555-7b8c6400-10d8-11ea-9cc9-0bc083c99d9a.png)

**Comment by kemmis** [comment]
@jongio, I think I might be a bit off with my approach to access the blob storage. I've been trying to utilize the Managed Identity of our App Services, and so I was trying the following, hoping that this would magically happen as long as the current execution context is running with an Azure Identity that has permission to access the storage account with read/write access. Is this approach feasible? Or do we **must** store the full connection string (with the SAS) somewhere like a key vault, retrieve that first, and then pass it to the client constructor?

```
var blobServiceClient = new BlobServiceClient(new Uri("https://mystorageaccountXXX.blob.core.windows.net/"));

var containerClient = blobServiceClient.GetBlobContainerClient("my-container-name");

BlobClient blobClient = containerClient.GetBlobClient("new-blob-name.csv");

using (var sourceFileStream = File.OpenRead("some local path"))
{
    await blobClient.UploadAsync(sourceFileStream);
}
```
Attempting this approach, I did get that 404 error at that ` Azure.Storage.Blobs.BlobRestClient.BlockBlob.UploadAsync_CreateResponse(Response response)` method at the top of the stack trace. Any tips or guidance you can point me to would be awesome. Thanks Jon!

**Comment by jongio** [comment]
@slipdef 

I'm not sure why that connection string doesn't work, but at least now we have code that @amnguye can use to debug it.

In the meantime, you can use the SAS that is generated by [Azure Storage Explorer](https://azure.microsoft.com/en-us/features/storage-explorer/)

![image](https://user-images.githubusercontent.com/2163001/69689168-0fc8dd80-107d-11ea-8226-24422d6777ad.png)

![image](https://user-images.githubusercontent.com/2163001/69689181-1a837280-107d-11ea-83c9-a4ebf5c2210d.png)

![image](https://user-images.githubusercontent.com/2163001/69689203-240cda80-107d-11ea-93e6-f009a85f75be.png)

```csharp
            var blobContainerSasUri = new Uri("sas uri from storage explorer);
            var blobContainerClient = new BlobContainerClient(blobContainerSasUri);
            
            var contents = "Hello Blob 6";

            using (var stream = new MemoryStream(Encoding.ASCII.GetBytes(contents))) {
                var response = blobContainerClient.GetBlobClient("blob.txt").UploadAsync(stream, overwrite: true, cancellationToken: default(System.Threading.CancellationToken));
                var result = response.Result;
                Console.Write(result);
                Console.ReadKey();
            }
```

**Comment by jongio** [comment]
@kemmis - This article should help you with Managed Identities and blob storage.  The magic is in DefaultAzureCredential(), which will check for service principal environment variables locally (for your local dev expereince) and if not found it will instantiate use ManagedIdentities under the covers.  It's great for having the same code in dev as you do in prod and you don't have to manage the sp for prod yourself.

https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-msi?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json#net-code-example-create-a-block-blob

**Comment by jongio** [comment]
@slipdef - Here's how you'd implement this with dynamic Sas based on your account name and key.  Please put those values in env vars not code (of course)

```csharp
            var storageAccountName = "jongstorage";
            var storageAccountKey = "+NmQtcJQ5q5cWEfXBM5tN1SxXer4FA==";
            var storageAccountUri = $"https://{storageAccountName}.blob.core.windows.net/";

            // Create a service level SAS that only allows reading from service
            // level APIs
            AccountSasBuilder sas = new AccountSasBuilder
            {
                // Allow access to blobs
                Services = AccountSasServices.Blobs,

                // Allow access to the service level APIs
                ResourceTypes = AccountSasResourceTypes.All,

                // Access expires in 1 hour!
                ExpiresOn = DateTimeOffset.UtcNow.AddHours(1)
            };

            // Allow read access
            sas.SetPermissions(AccountSasPermissions.All);

            // Create a SharedKeyCredential that we can use to sign the SAS token
            StorageSharedKeyCredential credential = new StorageSharedKeyCredential(storageAccountName, storageAccountKey);

            // Build a SAS URI
            UriBuilder sasUri = new UriBuilder(storageAccountUri);
            sasUri.Query = sas.ToSasQueryParameters(credential).ToString();

            // Create a client that can authenticate with the SAS URI
            var blobServiceClient = new BlobServiceClient(sasUri.Uri);

            // Create a container client
            var blobContainerClient = blobServiceClient.GetBlobContainerClient("blobs");

            var contents = "Hello Blob 10";

            using (var stream = new MemoryStream(Encoding.ASCII.GetBytes(contents)))
            {
                var response = blobContainerClient.GetBlobClient("blob.txt").UploadAsync(stream, overwrite: true, cancellationToken: default(System.Threading.CancellationToken));
                var result = response.Result;
                Console.Write(result);
                Console.ReadKey();
            }
```

**Comment by kemmis** [comment]
Thanks @jongio. I found that guide and was still getting the same issues. Everything I tried basically caused the dev environment fail to find my visual studio signed in azure account. Turns out one of the azure sdk packages wasn't playing nice with my version of VS (I was probably 4 months behind). After updating visual studio, it was able to pick up my identity, and now I only have a permissions issue (403 response). I think I just need to add myself to the blob data contributor role. I hear that it's not enough to be just a normal contributor role. So I'll give that shot. 

Thanks for your time. Over-and-out.

**Comment by slipdef** [comment]
@jongio thanks for the workaround. I would prefer to use connection string based on SAS token tho to don't refactor external code to make it working with URI based approach. Any ETA how soon the fix can go live? Like do we need to wait next Azure SDK release or you provide a hotfix version?

**Comment by jongio** [comment]
@slipdef - I will follow up on that and get back to you.

@amnguye - I was able to repro with the following code:

```csharp
            var connString = "BlobEndpoint=https://jongstorage.blob.core.windows.net/;....N6SLGlUB98NwSmduhtk%3D";
            var blobContainerClient = new BlobContainerClient(connString, "testsas1");
            blobContainerClient.Create();
```
```
The specified resource does not exist.
RequestId:ebabc17d-b01e-0017-3e30-a56357000000
Time:2019-11-27T14:41:53.8176082Z
Status: 404 (The specified resource does not exist.)

ErrorCode: ResourceNotFound

Headers:
Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id: ebabc17d-b01e-0017-3e30-a56357000000
x-ms-client-request-id: 4a342aae-4281-40a8-8621-527b05705c8b
x-ms-version: 2019-02-02
x-ms-error-code: ResourceNotFound
Date: Wed, 27 Nov 2019 14:41:53 GMT
Content-Length: 223
Content-Type: application/xml

```
and verified that this works in the python SDK
```python
from azure.storage.blob import ContainerClient

container = ContainerClient.from_connection_string("BlobEndpoint=https://jongstorage.blob.cPWX2PfxN6SLGlUB98NwSmduhtk%3D", "testsas2")
container.create_container()

```

**Comment by seanmcc-msft** [comment]
@jongio, in your example above, is "testsas1" the name of the container you are trying to create, or your SAS string?  Our BlobContainerClient constructors that take a connection string have the container name as the second parameter, not a sas string.

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/BlobContainerClient.cs#L141

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/BlobContainerClient.cs#L165

**Comment by seanmcc-msft** [comment]
For now, I'd recommend using the following work-around:

```
BlobContainerClient containerClient = new BlobContainerClient(new Uri("your SAS url here"));
```

This is working correctly for me with a container SAS URL from the Storage Explorer.

**Comment by jongio** [comment]
@seanmcc-msft - testsas1 and testsas2 are containers.

I recommended that workaround as well (above), but they want to use the connection string, not the container sas url.

**Comment by JoshLove-msft** [comment]
In the conn string constructor, we have:
`var builder = new BlobUriBuilder(conn.BlobEndpoint) { BlobContainerName = blobContainerName };`

BlobEndPoint property does not have the sas token included. We should probably update the StorageConnectionString parsing code to include sas token if present in the Endpoint properties.

**Comment by jongio** [comment]
@kemmis - You need to assign the ["Storage Blob Data Contributor"](https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#storage-blob-data-contributor) role to the service principal and you MUST provide a scope.  I'm not sure of the depth of the scope yet, but here's what worked for me.

```
az role assignment create --role ba92f5b4-2d11-453d-a403-e96b0029c9fe --assignee [sp-id] --scopes "/subscriptions/[sub id]/resourceGroups/[rg name]/providers/Microsoft.Storage/storageAccounts/[storage account name]"
```

**Comment by kemmis** [comment]
Yep. Thanks Jon. That’s what I figured out last week. It’s funny... I first
got the code up and running writing to blobs via linqpad in all but 30
minutes. But when I went to complete the feature in my app, I realized I
needed to scrap that code and make it use managed identity credentials as
to not have to pass connection strings with keys in them all over the
place. Took me about 2 days to finally get that working.

**Comment by jongio** [comment]
Reactivating due to #9110

**Comment by jongio** [comment]
Please see workaround description here: https://github.com/Azure/azure-sdk-for-net/issues/9110#issuecomment-565174631

**Comment by seanmcc-msft** [comment]
I believe this issue has been resolved, we have unit tests covering these cases:
- https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/tests/ContainerClientTests.cs#L59
- https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/tests/ContainerClientTests.cs#L115
- https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/tests/ContainerClientTests.cs#L150
- https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/tests/ContainerClientTests.cs#L169
- https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/tests/ContainerClientTests.cs#L192
