### ISSUE TITLE
docs.ms has obsolete types from old preview libraries

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#8866]
For Azure.Core and maybe other track 2 libraries:

For example https://docs.microsoft.com/en-us/dotnet/api/azure.core.retriablestream?view=azure-dotnet doesn't exist in GA package.

And all types miss xml docs.

**Comment by pakrym** [comment]
cc @scbedd @kaerm

**Comment by kaerm** [comment]
@pakrym you mean that this class was a part of the previews but not of the release? 

For xml docs: can you show me an example of the page where it doesn't exist and link to where it is described in the library

**Comment by pakrym** [comment]
> @pakrym you mean that this class was a part of the previews but not of the release?

Yep

> For xml docs: can you show me an example of the page where it doesn't exist and link to where it is described in the library

https://docs.microsoft.com/en-us/dotnet/api/azure.core.pipeline.clientoptions?view=azure-dotnet vs https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/ClientOptions.cs

**Comment by kaerm** [comment]
@scbedd can you make sure GA versions get pulled in the docs system and not preview? 

I will file an issue on the XML

**Comment by scbedd** [comment]
I didn't actually update the source of these GA docs, just the location in ToC. I will check the CI definition of this.

**Comment by pakrym** [comment]
https://docs.microsoft.com/en-us/dotnet/api/azure.core.retriablestream?view=azure-dotnet still there.

**Comment by scbedd** [comment]
@pakrym This is a doc rendering issue, not any issue with the configuration.

I have completely removed the `Azure.Core` folder from the `smoke-test` branch, and re-run the CI to ensure that we're not keeping around any old files. I got the _exact same_ file set generated.

(Screenshot of CI Config for Azure.Core):
![image](https://user-images.githubusercontent.com/45376673/71195855-9c615880-2243-11ea-9747-7c8eac6682ab.png)


I have reached out to the documentation with a bunch of this information. This issue will be re-titled to better fit the situation.

**Comment by pakrym** [comment]
> Also, for the RetriableStream that doesn't exist anymore, it does, but it may be rendering in the wrong place. In repo 

It's internal now, so from docs perspective it doesn't exist.

Is there any updates about this issue?

**Comment by scbedd** [comment]
Not at this time.

**Comment by scbedd** [comment]
Latest discussion on this item present here: [https://ceapex.visualstudio.com/Engineering/_queries/edit/213531/?triage=true].

Have a lock on what the issue is, but no response so far on what I can do to resolve this.
