### ISSUE TITLE
[BUG] AzureServiceTokenProvider does not support UserAssignedIdentities

### ISSUE THREAD

**Issue by lukas-gmuer** [Azure/azure-sdk-for-net#8877]
User Assigned Identities are not supported for AzureServiceTokenProvider as documented. https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/key-vault/service-to-service-authentication.md
https://docs.microsoft.com/de-ch/azure/key-vault/service-to-service-authentication

From the documentation the AzureServiceTokenProvider should be called with connection string: RunAs=App;AppId={AppId}

The AzureServiceTokenProviderFactory however requires tenantId and secret/certificate to be specified as well in this case.

I could not find any implementation of a TokenProvider for the case of a User Assigned identity.

**To Reproduce**
var azureServiceTokenProvider = new AzureServiceTokenProvider("RunAs=App;AppId={AppId}");

**Comment by heaths** [comment]
Our newer libraries like Azure.Identity can actually alleviate a lot of this hassle. Using `DefaultAzureCredential` chains multiple authentication models in a way that is optimized for services but allows for development work that should work in your case. Are you able to upgrade to those newer libraries?

**Comment by lukas-gmuer** [comment]
Thanks for the quick reply. Azure Identity does seem to support user managed identity.

I will report back once i tried to integrate it with the configuration provider

**Comment by varunsh-msft** [comment]
While it is good to move to the new Azure.Identity libraries, this is supported in App authentication, so do want to close on the original question. @nonik0 , can you please look into this? thanks!

**Comment by nonik0** [comment]
@lukas-gmuer could you provide more information about your scenario, including the specifics of your environment, the error you are seeing, etc.? Using the connection string "RunAs=App;AppId={AppId}" with AzureServiceTokenProvider will enable you to use a user-assigned managed identity. This specifically will use the [MsiAccessTokenProvider](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/mgmtcommon/AppAuthentication/Azure.Services.AppAuthentication/TokenProviders/MsiAccessTokenProvider.cs) to get a token for a user-assigned managed identity (however this is technically an implementation detail as you should be using the AzureServiceTokenProvider).

**Comment by lukas-gmuer** [comment]
When executing this:
`var azureServiceTokenProvider = new AzureServiceTokenProvider("RunAs=App;AppId=XXXXXX-XXXX-XXXX-XXXX-XXXXXXX");`

It trhows
System.ArgumentException
  HResult=0x80070057
  Message=Connection string RunAs=App;AppId=XXXXXX-XXXX-XXXX-XXXX-XXXXXXX is not valid. Must contain 'TenantId' attribute and it must not be empty.
  Source=Microsoft.Azure.Services.AppAuthentication
  StackTrace:
   at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderFactory.ValidateAttribute(Dictionary`2 connectionSettings, String attribute, String connectionString)
   at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderFactory.Create(String connectionString, String azureAdInstance)
   at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider..ctor(String connectionString, String azureAdInstance)
   at Zurich.FrontLayer.Web.Program.<>c.<Main>b__3_0(HostBuilderContext hostingContext, IConfigurationBuilder config) in

**Comment by nonik0** [comment]
@lukas-gmuer What version of AppAuthentication are you using? Support for user-assigned identities was first added in [1.2.0-preview](https://www.nuget.org/packages/Microsoft.Azure.Services.AppAuthentication/1.2.0-preview). Based off the error message shown, it looks like you are using an older version of AppAuthentication.

**Comment by heaths** [comment]
Closing due to lack of response. If you are still having issues, please reopen this issue with more details and we can investigate.
