### ISSUE TITLE
Packages.html 404s

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-net#8888]
All links here (except the package link) 404
https://azure.github.io/azure-sdk-for-net/packages.html

![image](https://user-images.githubusercontent.com/2163001/69502716-49f07e80-0ec7-11ea-9564-2fb226954e7b.png)

**Comment by chidozieononiwu** [comment]
packages.md has been removed in https://github.com/Azure/azure-sdk-for-net/pull/9015
