### ISSUE TITLE
[Track One] Tests for runtime metrics on the client are consistently failing nightly runs

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#8892]
# Summary

A recent change appears to have caused two of the client tests for runtime metrics to begin failing consistently during nightly runs.   The behavior seems to have begun starting with the nightly run for Monday, November 18th, where the following two tests have been failing:

- Microsoft.Azure.EventHubs.Tests.Client.ReceiverRuntimeMetricsTests.DisableWithReceiverOptions
- Microsoft.Azure.EventHubs.Tests.Client.ReceiverRuntimeMetricsTests.DefaultBehaviorDisabled

The failures have remained consistent since, and a good example for inspection was the run for [Sunday, November 24](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=196134&view=ms.vss-test-web.build-test-results-tab).  The failure details look something like:

![image](https://user-images.githubusercontent.com/913445/69551410-a35db980-0f6a-11ea-9f54-86c7eaf8b596.png)

# Scope of Work

- Analyze the tests to understand the point of non-determinism and decide on an approach to stabilize for nightly runs.

- Refactor the tests as needed to ensure that the results are deterministic and consistently pass.

# Out of Scope

- Changes or refactoring in other areas.

# Success Criteria

- The tests `DisableWithReceiverOptions` and `DefaultBehaviorDisabled` have been refactored or removed and no cause consistent failures during nightly runs.

- The changes did not cause regressions elsewhere; nightly test runs pass consistently and reliably with deterministic results.

**Comment by jsquire** [comment]
@serkantkaraca, @JamesBirdsall:  If you would be so kind as to offer your thoughts, it would be greatly appreciated.

**Comment by serkantkaraca** [comment]
Let me check. It is probably due to a recent change I merged.

**Comment by serkantkaraca** [comment]
Fixed by https://github.com/Azure/azure-sdk-for-net/commit/74764e44ea817b9de73eea3a637ccf295c01da6c#diff-1e0ecb0f40c280481e60fafad9e32799
