### ISSUE TITLE
Consider naming for NamedEntity, LinkedEntity, and KeyPhrases

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#8894]
The names NamedEntity, LinkedEntity, and KeyPhrases relate more to the algorithms that identify them than what they actually represent.  

Ideally, these would be more descriptive names, that indicate to users when to use which.

Key phrases are just the strings deemed important in the input text.  It can be a noun or a verb, unlike entities in other cases.  Given the algorithm, we may not be able to recognize the type.  If we don't have key phrases, some entities ("important phrases") could be missed -- i.e. we'd overlook things that aren't in the type system used to train the NER model.  People should use key phrases over the others when they want the full set of important words and they don't care about the type of the extracted phrase.  

Named Entities are extracted based on the type system the NER model is trained with.  This is currently people, organizations, and locations.

Linked Entities are used for disambiguation.  They link to a knowledge base such as Wikipedia, and can tell you e.g. whether "bank" in "I'm going to the bank" is a river bank or a financial institution.

**Comment by mayurid** [comment]
Waiting for UX study

**Comment by maririos** [comment]
NamedEntity changes to => `CategorizedEntity`

**Comment by maririos** [comment]
Documentation should include literature naming

**Comment by maririos** [comment]
`Key phrases` should include an i.e. in the documentation so people know when to use it

**Comment by maririos** [comment]
For `Linked Entities` look #8781

**Comment by maririos** [comment]
For KeyPhrases see #9691
