### ISSUE TITLE
Decide how to name method for PII entities

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#8895]
This is currently a method on TextAnalyticsClient that takes the same input type and returns the same output type as GetEntities.  We don't like that Pii is abbrevated in the name.

One proposal was to have just GetEntities and take an enum to specify which entities to return - General, Pii, Healthcare, etc.

Healthcare entities will have a different shape, so the return type will be different, which means we can't use this approach for all different entity types.

We should look at customer scenarios and think about what groups of functionality make sense to expose on the same client as part of this.

**Comment by annelo-msft** [comment]
We can handle this as part of the UX work.  User in the study seemed to be fine with the current naming.

**Comment by maririos** [comment]
closing per:
> User in the study seemed to be fine with the current naming.
