### ISSUE TITLE
Consider renaming verbs for consistency

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#8896]
We currently have a different verb for each endpoint.  Would it be better to use the same verb across endpoints?  Possibly "infer" ?

Consider this in the context of potentially breaking the client into multiple clients/packages, per https://github.com/Azure/azure-sdk-for-net/issues/8895

**Comment by mayurid** [comment]
Waiting for UX study feedback

**Comment by maririos** [comment]
Per UX, current naming works, no need to unify
