### ISSUE TITLE
Design warning representation for DocumentSentiment

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#8898]
Warnings currently exist only on SentenceSentiment.  If a sentence has a warning, though, then the document containing the sentence should have a warning as well.  Consider the design of TextSentiment to accomodate warnings at both levels.

**Comment by maririos** [comment]
When there is a warning, service returns something like:
```
{ 
   "documents":[ 
      { 
         "id":"0",
         "sentiment":"negative",
         "documentScores":{ 
            "positive":0.09,
            "neutral":0.11,
            "negative":0.8
         },
         "sentences":[ 
            { 
               "sentiment":"negative",
               "sentenceScores":{ 
                  "positive":0.15,
                  "neutral":0.04,
                  "negative":0.81
               },
               "offset":199,
               "length":585,
               "warnings":[ 
                  "Sentence was truncated because it exceeded the maximum token count."
               ]
            }
         ]
      }
   ],
   "errors":[ 

   ],
   "modelVersion":"2019-10-01"
}
```

we completely ignore warnings, so definitely need to fix it

**Comment by maririos** [comment]
Service team is working on moving warnings to the same level as errors, but including an ID.
This change will be proposed after the release date for P3 so moving this issue to next iteration

**Comment by maririos** [comment]
Conversation on Teams Channel: https://teams.microsoft.com/l/message/19:7b87fb348f224b37b6206fa9d89a105b@thread.skype/1587764652237?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1587764652237&teamName=Azure%20SDK&channelName=Language%20-%20DotNet&createdTime=1587764652237

Python and JS are more inclined to follow option 3.
From conversations, looks like .NET might follow.

**Comment by maririos** [comment]
Implementation of the design is in PR https://github.com/Azure/azure-sdk-for-net/pull/11827
