### ISSUE TITLE
Consider null sentiment

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#8899]
Currently, in SentimentClass, Neutral is the same as Unspecified.  However a neutral sentiment in a sentence is different from no sentiment being able to be identified.  Consider how to design this.

**Comment by mayurid** [comment]
Need to discuss with Assaf

**Comment by maririos** [comment]
Question added to #9722

**Comment by maririos** [comment]
>However a neutral sentiment in a sentence is different from no sentiment being able to be identified.

A sentence will always return a sentiment as the service returns the arg-max across the label scores., so no need to have "null sentiment"
