### ISSUE TITLE
Consider naming around "Documents" and "Text"

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#8900]
In some places we have "inputText" and in others we have "document".

Get clarity on what is which, when to use which one, and how document potentially relates to other documents in the Cognitive Services set of services.

Note:
The text analytics service seems to refer to a "document" as the object which holds the "text" along with other metadata like id and language/countryHint. Many of the v3 docs on docs.microsoft use this terminology (see [here](https://docs.microsoft.com/en-us/azure/cognitive-services/text-analytics/how-tos/text-analytics-how-to-sentiment-analysis#sentiment-analysis-v3-public-preview) for example). We want to make sure we don't confuse our users by using other terminology in the client libraries, but also want to ensure we are using the most accurate language in all places (APIs, docs, SDKs).

**Comment by mayurid** [comment]
Looking for UX study feedback

**Comment by maririos** [comment]
Definitely something we need to improve on. 
We are moving this to P3 as it involves looking for consistency through all the API, documentation, and service team
