### ISSUE TITLE
Decide on library version numbers and how/whether these correspond to service versions

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#8901]
There are considerations with Track 1 packages already having version numbers we may not want to change.

- Python is 0.2.0
- JS is 4.0.0: https://www.npmjs.com/package/@azure/cognitiveservices-textanalytics
- Java is 1.0.2-beta https://mvnrepository.com/artifact/com.microsoft.azure.cognitiveservices/azure-cognitiveservices-textanalytics
- .NET, the Track 1 library is Microsoft.Azure.CognitiveServices.Language.TextAnalytics 4.0.0.  We will be using the namespace Azure.AI.TextAnalytics, and could start numbering at 1.0.0 if needed.

We'll need to decide if we want different SDK languages to be in sync on version number
We'll need to decide if we want SDKs to be in sync with service version.

**Comment by assafi** [comment]
Please note that if we change the namespace it will be the second time we do so. In that since we have never heard customers complain about the SDK versions before, is that something you're hearing on your side?

**Comment by annelo-msft** [comment]
The updated namespace is required by our guidelines:  https://azure.github.io/azure-sdk/general_design.html#namespaces

To my knowledge, we don't have prescriptive guidelines about versioning, which is why this is open to discussion.

**Comment by annelo-msft** [comment]
@kaerm @mayurid

**Comment by kaerm** [comment]
and @ChrisHMSFT

**Comment by annelo-msft** [comment]
We have decided that libraries will version independently from the service.  We will start with 1.0.0-preview.1 for libraries in all languages.

@mayurid @assafi
