### ISSUE TITLE
Onboard december releases on docs.microsoft.com

### ISSUE THREAD

**Issue by kaerm** [Azure/azure-sdk-for-net#8914]
- [ ] Onboard the following packages on docs.microsoft.com
**Latest:**
Azure.Core 1.0.1
Azure.Identity 1.1.0
Azure.Storage.Files.Shares 12.0.0
Azure.Storage.Common 12.0.0
Azure.Storage.Blobs.Batch 12.0.0
Azure.Storage.Blobs 12.0.0
Azure.Storage.Queues 12.0.0
Azure.Security.KeyVault.Keys 4.0.0
Azure.Security.KeyVault.Secrets 4.0.0
**Preview:**
Azure.Security.KeyVault.Certificates P 4.0.0-preview.7
Azure.Storage.Files.DataLake 12.0.0-preview.6
Azure.Messaging.EventHubs 5.0.0-preview.6
Azure.Messaging.EventHubs.CheckpointStore.Blobs 1.0.0-preview.4
Azure.Data.AppConfiguration 1.0.0-preview.6
**Legacy:**
Microsoft.Azure.Storage.File 11.1.1

- [ ] Remove following packages from preview:
Azure.Storage.Files.Shares 12.0.0-preview.5
Azure.Storage.Files  12.0.0-preview.4

@AlexGhiondea to confirm version numbers

**Comment by scbedd** [comment]
Latest
- [x] Updated latest packages. For latest versions, I leveraged this [site.](https://azure.github.io/azure-sdk/releases/latest/dotnet.html) as the current stuff wasn't up to date.

Preview
- [x] Updated for current previews
- [x] I did NOT remove `Azure.Storage.Files` from the preview moniker as it is still preview.

Legacy
- [x] Added Microsoft.Azure.Storage.File 11.1.1

[Associated PR](https://apidrop.visualstudio.com/binaries/_git/mrefconfig/pullrequest/747?_a=overview)

**Comment by kaerm** [comment]
Also here Files have also been replaced by files.shares

**Comment by scbedd** [comment]
Everything looks good that I can tell between Latest, Legacy, Preview. Submitted PR to merge to master.

**Comment by scbedd** [comment]
Blocking issue discovered on last validation. Latest updates for `Azure.Storage.Files` is causing a conflict when determining what assembly owns the type `ShareSasPermissions.xml`. At least one of these succeeded (given that we can see Files.Shares in the ToC), but the interplay of the new Azure.Storage.* are building are causing artifacts that are not recognized by the build system.

**Comment by kaerm** [comment]
Wait - let me understand it better - Azure.Storage.Files should not be used at this point. The GA package is Azure.Storage.Files.Shares. Is that causing the problem or other Storage packages?

**Comment by scbedd** [comment]
I edited the comment, but I believe it's all of them in general. Why? I tried _completely removing_ Azure.Storage.Files.Shares and the problem still occurred. I'm writing a mail to Robert now.

**Comment by scbedd** [comment]
Heard back from Robert.

>the issue actually seems to stem from the fact that this type is changing from a struct to an enum in the preview moniker. You can see that here in the EcmaXml:

``` 
<Base>
 <BaseTypeName>System.ValueType</BaseTypeName>
 <BaseTypeName FrameworkAlternate="azure-dotnet-preview">System.Enum</BaseTypeName>
</Base>
```

> That is causing the entity type determination to fail in Ecma2Yaml here.
 
>This is a pretty dramatic breaking change for that type from one version to another ... one that the system is obviously ill-equipped to handle at this point. As it's changing in the preview, any chance that we can petition the engineering team to use another type name for this particular type, rather than changing from a struct to an enum?

Short term: I am removing the preview version of `Azure.Storage.Files` to mitigate and unblock doc publishing.

**Comment by scbedd** [comment]
`Azure.Storage.Files` and `Azure.Storage.Files.Shares` previews will be excluded until the `latest` packages and `preview` packages will have the same BaseType. 

Limitation of the docs pipeline.

Review documentation is available here: https://review.docs.microsoft.com/en-us/dotnet/api/overview/azure/?view=azure-dotnet&branch=master

**Comment by kaerm** [comment]
let's share that with the .net team for review
