### ISSUE TITLE
Ensure client request id and other headers are added only once on retries.

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#8920]
Per Partner request:

Can you please confirm that the client request id won’t be repeated on retry too? Because client request id is not involved in HMAC signing, I am not sure if it’s fixed as part of the signing issue.

This is the real log of the response that the customer reported.

 
![clientReqId](https://user-images.githubusercontent.com/21269347/69653124-8dfa9500-1027-11ea-9472-c4f0bb94fe3e.png)

So looks like this is what happened
1.	The SDK sent the initial request with x-ms-client-request-id: 0453ca94-5026-4fa0-aeee-ea38de69cfd5
2.	The request is throttled and the server responded 429 (this is the first log I shared earlier)
3.	The SDK retry for 429 and sent a request with x-ms-client-request-id: 0453ca94-5026-4fa0-aeee-ea38de69cfd5, 0453ca94-5026-4fa0-aeee-ea38de69cfd5
4.	The server responded 401 likely due to the SDK HMAC signing  issue you mentioned
5.	The SDK won’t retry for 401 and the exception bubbled up.

Looks like when SDK retries, it doubles the client request id string. Is this fixed already?

**Comment by annelo-msft** [comment]
Action here is to add test to verify this doesn't happen in the current release.

**Comment by AlexanderSher** [comment]
Closed by #8986
