### ISSUE TITLE
Ignore some attributes when generating API listing

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#8931]
@heaths 

> Here’s a couple of attributes we could probably hide in the generated API:
> 
> •	System.Runtime.CompilerServices.CompilerGeneratedAttribute
> •	System.ComponentModel.EditorBrowsableAttribute
> 
> At least, those are the only ones I see besides StructLayoutAttribute in Key Vault.

**Comment by pakrym** [comment]
I don't think the issue was fixed in linked PR. This one is about API listing files and PR changes the API doc generation

**Comment by chidozieononiwu** [comment]
Resolved by https://github.com/Azure/azure-sdk-for-net/pull/10515
