### ISSUE TITLE
[BUG] Microsoft.Azure.CognitiveServices.Language.LUIS.Authoring.LUISAuthoringClient.Apps.DownloadQueryLogsAsync does not provide an includeResponse parameter even though the API does.

### ISSUE THREAD

**Issue by v-kydela** [Azure/azure-sdk-for-net#8937]
**Describe the bug**
[`DownloadQueryLogsAsync`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/cognitiveservices/Language.LUIS.Authoring/src/Generated/AppsExtensions.cs#L167-L184) does not provide an `includeResponse` parameter even though the [API](https://westus2.dev.cognitive.microsoft.com/docs/services/luis-programmatic-apis-v3-0-preview/operations/5890b47c39e2bb052c5b9c36) does ([even in v2](https://westus.dev.cognitive.microsoft.com/docs/services/5890b47c39e2bb17b84a55ff/operations/5890b47c39e2bb052c5b9c36/console)).

***Code Snippet***
```c#
public static async Task<Stream> DownloadQueryLogsAsync(this IApps operations, System.Guid appId, CancellationToken cancellationToken = default(CancellationToken))
```

**Expected behavior**
The SDK should provide all the functionality that the REST API does.

**Additional context**
For the sake of completeness, a model or helper method should also be included to help consume the CSV result of this call.

**Information Checklist**
- [X] Bug Description Added
- ~~Repro Steps Added~~ (N/A)
- ~~Setup information Added~~ (N/A)

**Comment by JimSuplizio** [comment]
Hi @v-kydela, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
