### ISSUE TITLE
OpenWriteAsync equivalent in v12 Azure.Storage.Blobs?

### ISSUE THREAD

**Issue by christophwille** [Azure/azure-sdk-for-net#8942]
**Query/Question**
We used https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.blob.cloudappendblob.openwriteasync?view=azure-dotnet-legacy#Microsoft_Azure_Storage_Blob_CloudAppendBlob_OpenWriteAsync_System_Boolean_System_Threading_CancellationToken_ with the "old" SDK. Is there an equivalent in the new SDK?

***Why is this not a Bug or a feature Request?***
We are migrating an existing application, but moving to a different pattern is an option for us.

**Setup (please complete the following information if applicable):**
 - Version of the Library used 12.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by tg-msft** [comment]
We don't have an equivalent of `CloudBlobStream` in Azure.Storage.Blobs.  The preferred approach will be calling [`AppendBlobClient.AppendBlockAsync`](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.specialized.appendblobclient.appendblockasync?view=azure-dotnet#Azure_Storage_Blobs_Specialized_AppendBlobClient_AppendBlockAsync_System_IO_Stream_System_Byte___Azure_Storage_Blobs_Models_AppendBlobRequestConditions_System_IProgress_System_Int64__System_Threading_CancellationToken_).

**Comment by christophwille** [comment]
Thanks. We opted to go with the following approach: temp file on disk, then upload in one operation instead of the previous approach of "streaming" the file to blob storage (two stage instead of one).

**Comment by tg-msft** [comment]
Would a `MemoryStream` that you periodically flush to `AppendBlockAsync` do the job without writing to disk?  Ideally you shouldn't have to touch the file system because that can end up being tricky if you're deploying to varied environments.

While we don't have anything like this today, I think it's a good idea as a higher level convenience and filed #8993.  Thanks for bringing this up @christophwille.

**Comment by rarpal** [comment]
Using AppendBlock with a MemoryStream proved to be extremely slow when compared with the previous versions CloudBlobStream over a StreamWriter
