### ISSUE TITLE
[BUG] BatchReadFileAsync Deserialization Error

### ISSUE THREAD

**Issue by czitelli** [Azure/azure-sdk-for-net#8943]
Hi guys, I am testing Cognitive Services TextAnalytics and found a deserialize error (RecognitionResult = null) using BatchReadFileWithHttpMessagesAsync and GetTextOperationResultWithHttpMessagesAsync, the cause of this is that the object TextOperationResult has an invalidad json property (PropertyName = "recognitionResult") but the response is "recognitionResults". To fix it, I need deserialize the response with another object model (ReadOperationResult) this has correct [JsonProperty(PropertyName = "recognitionResults")].

Please, let me know if it's fixed.

Regards, Cris

**Comment by maririos** [comment]
Hi @czitelli . 
Which library and version are you using?

**Comment by czitelli** [comment]
Hi @maririos, how it's going? 
Details
Library: Microsoft.Azure.CognitiveServices.Vision.ComputerVision
Version: 5.0.0
Please, let me know if the issue is fixed.
Regards.

**Comment by maririos** [comment]
Thanks!
@annelo-msft could you help pointing here to someone from ComputerVision?

**Comment by maririos** [comment]
@ChrisHMSFT could you please help route to the Computer Vision team?

**Comment by TFR258** [comment]
Thank you for the Feedback @maririos , we are looking into it.

Thanks,
Tom

**Comment by JimSuplizio** [comment]
Hi @czitelli, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
