### ISSUE TITLE
Expose Credential type for DefaultAzureCredential and ChainedTokenCredential

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-net#8948]
When using DefaultAzureCredential or ChainedTokenCredential I find it useful to know which credential type is being used.  Right now I have to resort to reflection or EventSource:

```csharp
using var listener = new AzureEventSourceListener((eventArgs, text) => AzureEventSourceHandler(eventArgs, text), EventLevel.Informational);

        static void AzureEventSourceHandler(EventWrittenEventArgs eventArgs, string text)
        {
            if (text.Contains("Credential") && text.Contains("succeeded"))
            {
                Console.WriteLine(text);
            }
        }
```

I would rather do something like this:

```csharp
var credential = new DefaultAzureCredential();
credentail.GetToken();
credential.GetType();  // and this return the type used

or

credential.GetCredentialType(); // if overriding GetType() is a problem due to composition model

```
I understand that GetToken isn't called until a network call is needed, but a user could call GetToken() first if they really need to know the Credential type.

**Comment by jongio** [comment]
Related: https://github.com/Azure/azure-sdk-for-java/issues/6591

**Comment by JimSuplizio** [comment]
Hi @jongio, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
