### ISSUE TITLE
QueueClient: Support CreateIfNotExistsAsync + DeleteIfExistsAsync

### ISSUE THREAD

**Issue by christophwille** [Azure/azure-sdk-for-net#8950]
**Is your feature request related to a problem? Please describe.**
We were migrating old code - Microsoft.WindowsAzure.Storage.Queue had those two methods (and as an aside, Azure.Storage.Blobs does have the equivalents for containers, so here is an API difference)

**Describe the solution you'd like**
Implement those two methods on QueueClient.

**Describe alternatives you've considered**
We implemented the methods as extensions catching RequestFailedException for QueueErrorCode.QueueAlreadyExists and QueueErrorCode.QueueNotFound for Create and Delete respectively.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Description Added
- [X] Expected solution specified

**Comment by tg-msft** [comment]
Thanks for reporting this!  We've got #7879 filed to address this in a future release _(and #7878 for Files.Shares)_ so I'm going to close this bug as a duplicate.
