### ISSUE TITLE
[FEATURE] [storage] Implement a low performance cost Exists() method on the blobclient class

### ISSUE THREAD

**Issue by NickBosworth** [Azure/azure-sdk-for-net#8952]
There is a very common use case to test if a blob exists before attempting to download it. This feature was supported in previous official Dotnet client libraries.  

e.g. CloudBlobClient.GetContainerReference(containerName).GetBlockBlobReference(key).Exists();

It is currently frustrating that the only solution is to drive logic flow with a try-catch which is bad practise and doesn't explicitly answer the question about whether the blob exists or not, just that it couldn't be fetched. We can look at status codes etc but the added complication increases branching logic and bug risk in the calling application. There is also the option of looking at the blob's properties but this has similar drawbacks to the above.   

Ideally, I would love an Exists() method on the BlobClient class, similar to previous versions of client libraries.  This should naturally be a low impact on performance and network traffic as is possible.

**Comment by amnguye** [comment]
Hi,

Thanks for your input. We will definitely look into making a helper method for Exists for blobs.

I've added the feature request label onto this.

**Comment by EdiWang** [comment]
I have the same issue when upgrading my old code to the new SDK. Now I have to use low-performance try-catch code to check 404 blobs. I would like the ```Exists()``` method for ```BlobClient```
to be implemented.

```csharp
public async Task<Response<ImageInfo>> GetAsync(string fileName)
{
    var blobClient = _container.GetBlobClient(fileName);
    await using var memoryStream = new MemoryStream();
    var extension = Path.GetExtension(fileName);
    if (string.IsNullOrWhiteSpace(extension))
    {
        return new FailedResponse<ImageInfo>((int)ResponseFailureCode.ExtensionNameIsNull);
    }

    // This needs to try-catch 404 status now :(

    //var exists = await blobClient.ExistsAsync();
    //if (!exists)
    //{
    //    _logger.LogWarning($"Blob {fileName} not exist.");
    //    return new FailedResponse<ImageInfo>((int)ResponseFailureCode.ImageNotExistInAzureBlob);
    //}

    await blobClient.DownloadToAsync(memoryStream);
    var arr = memoryStream.ToArray();

    var fileType = extension.Replace(".", string.Empty);
    var imageInfo = new ImageInfo
    {
        ImageBytes = arr,
        ImageExtensionName = fileType
    };

    return new SuccessResponse<ImageInfo>(imageInfo);
}
```

**Comment by stap123** [comment]
Something similar on a container would be useful as well
