### ISSUE TITLE
Design approach for setting Id to default in TextDocumentInput

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#8954]
The business need here is to allow users to set the ID field when they have a need to do this, and hide it from them in all other cases, so we don't expose this complexity to them unless they want to opt-in to this feature.

Roughly speaking, we'll need to default the ID the same way we do in the batch string overloads.
Some questions around the design are:
- Should we have ID on TextDocumentInput at all?
- Should we provide a special overload for the "advanced" scenario of setting the ID?
- Does this have implications for the way we're using associative arrays currently?

**Original APIView Comment:**
KrzysztofCwalina1 week ago
I know we discussed it, but I don't remember the conclusion: can we get rid of the id and just match the input to output by index?

annelo-msft0 seconds ago
The service team needs to allow users to set Id, so they can potentially correlate them to GUIDs or some other DB id. We can look into providing a default setting if the user does not specify it.

**Comment by maririos** [comment]
FYI @mssfang

**Comment by maririos** [comment]
Now that TA has GAd, we haven't heard customers asking about this or implying that current implementation is confusing. 
Closing issue.
