### ISSUE TITLE
[BUG] Only the home tenant is considered for multi-tenant users when using SharedTokenCacheCredential

### ISSUE THREAD

**Issue by b10-dslappendel** [Azure/azure-sdk-for-net#8957]
**Describe the bug**
As reported in Azure/AppConfiguration#201, it seems that using `SharedTokenCacheCredential` (which extends to `DefaultAzureCredential`) doesn't work when the user is part of multiple tenants.

Last week AzureAppConfiguration was updated to version 3, and it started using Azure.Identity. Version 2 seems to have used a self-implemented way of connecting with `.ConnectWithManagedIdentity` that has a fallback to local credentials if managed identity is not available. This worked just fine. Version 3 however, fails.

If I don't set `SharedTokenCacheTenantId`, it fails with a 500 (which is a bug apparently and should return 401). If I do set `SharedTokenCacheTenantId`, it fails with the message that no accounts have been found matching the tenant id. However, I am part of the tenant that I'm trying to connect to.

***Exception or Stack Trace***
```
SharedTokenCacheCredential is unavailable
No account matching the specified tenantId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx was found in the cache.
To authenticate with the SharedTokenCacheCredential, login an account through developer tooling supporting Azure single sign on.
[ {username: ****** tenantId: yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy} ].
```

**To Reproduce**
In my case, I have a home tenant A and I am a guest in tenant B.
The App Configuration instance that I want to connect to from my application resides in tenant B.
Executing the code fails with the above mentioned message.

***Code Snippet***
```cs
var builder = new ConfigurationBuilder();
builder.AddAzureAppConfiguration(x =>
{
    x.Connect(new Uri("https://xxxx.azconfig.io"), new DefaultAzureCredential(new DefaultAzureCredentialOptions
    {
        SharedTokenCacheTenantId = "xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx",
    }));
});
var config = builder.Build();
```

**Expected behavior**
I'm expecting this not to fail. Additionally, I expect it to succeed even without having to manually set the tenant id as it does with version 2 of AppConfiguration.

**Setup (please complete the following information):**
 - OS: Windows 10 1903
 - IDE: Visual Studio 2019 16.3.9
 - Version of the Library used: Azure.Identity 1.1.0

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by pakrym** [comment]
cc @schaabs

**Comment by AlexGhiondea** [comment]
@b10-dslappendel thanks for reporting this. We are aware of this issue and are working on a fix for it and we will release it early next year.

**Comment by brandonh-msft** [comment]
@AlexGhiondea any update here? I'm trying to use `DefaultAzureCredential` to fall back to `SharedTokenCacheCredential` but I am logged in to multiple tenants/subscriptions. I have specified `AZURE_USERNAME` in the environment variables but still get the error message that my username is not found in the tenant.

**Comment by logiclabs** [comment]
Just as something else to try.. make sure your username is exact case as
what is shown in VS.

I had a similar problem with multiple accounts and account not being found,
and it was down to the username check in Shared Token Cache being case
sensitive.

**Comment by arkiaconsulting** [comment]
@brandonh-msft And if you're using an aliased Microsoft Account, this could also be a problem.

**Comment by sopelt** [comment]
@arkiaconsulting just the fact that an aliased microsoft account/AAD account combination exists or having them both logged in?

**Comment by brandonh-msft** [comment]
We ended up solving the problem by setting the `includeInteractive` boolean on the DefaultAzureCredential ctor to `true`. This pops a browser when we hit the code in either VS or VSCode, but does not work in VSCode DevContainers - I'm working on opening a thread w/ that team now.

**Comment by a99cl208** [comment]
The problem is :
In file **https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/identity/Azure.Identity/src/SharedTokenCacheCredential.cs**, line136, you have this line that is used to find your account :

```
List<IAccount> filteredAccounts = accounts.Where(a => (string.IsNullOrEmpty(_username) || a.Username == _username) && (string.IsNullOrEmpty(_tenantId) || a.HomeAccountId?.TenantId == _tenantId)).ToList();
```

So the filtering is done using the HomeAccountId. However, this ID is always the tenant ID of the main tenant of a user. If you want to log on a tenant you are guest into, it won't work. I have checked the MSAL token cache file "%HOMEPATH%\AppData\Local\.IdentityService\AccountStore.json", and in my case the ID of the tenant I want to log on is in the JSON property `IdentityServiceTenants`, which is a serialized json array. But I noticed that the `IAccount` interface that is used by `SharedTokenCacheCredential` does not expose this property.

So I don't think this can work with the actual design.

As @brandonh-msft said, an actual workaround is to use the interactive browser and specifying the tenant id. We use this workaround on my projet since 3 month now. But it's a clearly a workaround and not solution since you need to relog on the interactive browser each time you launch your application which is really annoying.

**Comment by arkiaconsulting** [comment]
@sopelt I experienced the issue with a external developer having an Microsoft Account having a main `hotmail` email, and an `outlook` alias. We invited him in our tenant with his alias, and so he's not able to use `SharedTokenCacheCredential`.
As a workaround, I think we will use a service principal locally, and fall back to `EnvironmentCredential`.

**Comment by brandonh-msft** [comment]
> The problem is :
> In file **https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/identity/Azure.Identity/src/SharedTokenCacheCredential.cs**, line136, you have this code that is used to find your account :
> 
> ```
> List<IAccount> filteredAccounts = accounts.Where(a => (string.IsNullOrEmpty(_username) || a.Username == _username) && (string.IsNullOrEmpty(_tenantId) || a.HomeAccountId?.TenantId == _tenantId)).ToList();
> ```

Thanks for finding & calling this out. I pulled down the source and poked around; it doesn't look like there's a list of **all** tenants that we could even filter on at the point where we're filtering the accounts :/ I went up in to the MsalPublicClient and still no _list_ of tenant IDs for us to look for.

This is going to require some more significant work; cc'ing @schaabs as he's the one whose name's on the last commits to the area :)

**Comment by schaabs** [comment]
Thank you all for you're contributions to this issue. As @a99cl208 and @brandonh-msft pointed out the MSAL APIs don't expose guest tenant information when we list accounts, so at this time the `SharedTokenCacheCredential` is limited in it's functionality because of this. We are working on broader changes to address this, which should be coming in our next preview release in May.

Also, in our last preview release, [1.2.0-preview.2](https://www.nuget.org/packages/Azure.Identity/1.2.0-preview.2), we added the `VisualStudioCredential` to the `DefaultAzureCredential` authentication flow, which I believe will unblock this scenario of signing into a guest tenant when authenticating in VS. If you log into VS with the desired account, and then specify the tenant you wish to authenticate in either via the AZURE_TENANT_ID environment variable or the `VisualStudioTenantId` property on `DefaultAzureCredentialOptions` this will authenticate the account to the desired tenant.

**Comment by jabbera** [comment]
@bradrich-msft  where can I follow progress on using an interactive login from a devcontainer?

**Comment by bradrich-msft** [comment]
> @bradrich-msft  where can I follow progress on using an interactive login from a devcontainer?

I think you may have the wrong person.  I have no idea what you are referring to.

**Comment by jabbera** [comment]
@bradrich-msft sorry. you are right:

@brandonh-msft where can I follow progress on using an interactive login from a devcontainer?

**Comment by brandonh-msft** [comment]
@jabbera honestly this is the best place I've found. Have you tried the prerelease nupkg @schaabs highlighted?

**Comment by jabbera** [comment]
@brandonh-msft selfishly I’m looking for the python sdk but considering this required a collaboration with the remote dev team I was hoping the solution would be the same. 🤷‍♂️

**Comment by brandonh-msft** [comment]
Created https://github.com/Azure/azure-sdk-for-net/issues/11509

**Comment by b10-dslappendel** [comment]
> 
> 
> Thank you all for you're contributions to this issue. As @a99cl208 and @brandonh-msft pointed out the MSAL APIs don't expose guest tenant information when we list accounts, so at this time the `SharedTokenCacheCredential` is limited in it's functionality because of this. We are working on broader changes to address this, which should be coming in our next preview release in May.
> 
> Also, in our last preview release, [1.2.0-preview.2](https://www.nuget.org/packages/Azure.Identity/1.2.0-preview.2), we added the `VisualStudioCredential` to the `DefaultAzureCredential` authentication flow, which I believe will unblock this scenario of signing into a guest tenant when authenticating in VS. If you log into VS with the desired account, and then specify the tenant you wish to authenticate in either via the AZURE_TENANT_ID environment variable or the `VisualStudioTenantId` property on `DefaultAzureCredentialOptions` this will authenticate the account to the desired tenant.

@schaabs what's the progress on this?
I see that there have been some updates, and testing the latest changes in preview 5 I am able to authenticate with `VisualStudioCredential` as long as I specify `TenantId`. If I use `DefaultAzureCredential` with `VisualStudioTenantId` however, it gives me a 401. And using it without specifying any tenant id results in the same 401.

While I can make it working now regarding my issue in https://github.com/Azure/AppConfiguration/issues/201, it's still a regression that I have to specify a tenant id.

**Comment by christothes** [comment]
@b10-dslappendel Does this work if you set `ExcludeSharedTokenCacheCredential` to true in the `DefaultAzureCredentialOptions`?

**Comment by b10-dslappendel** [comment]
@christothes No, sadly it does not. I still get the same 401 error.

I included the response that I got from my latest try below:
```
WWW-Authenticate: HMAC-SHA256,Bearer error="invalid_token", error_description="The access token is from the wrong issuer. It must match the AD tenant associated with the subscription, to which the configuration store belongs. If you just transferred your subscription and see this error message, please try back later."
x-ms-request-id: 486c0ef8-c242-447e-bb93-75e792e7fb32
x-ms-client-request-id: 9e54a690-810c-4d6e-a277-4e9654fc674e
x-ms-correlation-request-id: 486c0ef8-c242-447e-bb93-75e792e7fb32
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: DNT, X-CustomHeader, Keep-Alive, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Authorization, x-ms-client-request-id, x-ms-useragent, x-ms-content-sha256, x-ms-date, host, Accept, Accept-Datetime, Date, If-Match, If-None-Match, Sync-Token, x-ms-return-client-request-id, ETag, Last-Modified, Link, Memento-Datetime, retry-after-ms, x-ms-request-id, x-ms-client-session-id, x-ms-effective-locale, WWW-Authenticate
Strict-Transport-Security: max-age=15724800; includeSubDomains
Content-Length: 0
```

I did manage to get it working by using the AzureCliCredential (or by excluding everything except AzureCli in the DefaultAzureCredentialOptions). But I guess that's only because I made sure to run `az account set` with the subscription I wanted it to connect to.

**Comment by christothes** [comment]
Thanks for the update. Does it work for you if the `AZURE-TENANT_ID` environment variable is set to your preferred tenant? This should be the same as providing it via the DefaultAzureCredentialOptions, but generically for any of the configurable credential types.

https://github.com/Azure/azure-sdk-for-net/blob/72d4c479d82a7f71fd5b40dccf736ce96d9ec6a4/sdk/identity/Azure.Identity/src/DefaultAzureCredentialOptions.cs#L13-L42

https://github.com/Azure/azure-sdk-for-net/blob/5af6e7328701b71aec8f948b8054692083412b97/sdk/identity/Azure.Identity/src/EnvironmentVariables.cs#L12

**Comment by sschutten** [comment]
Ik was running into the exact same issue and can confirm that setting the tenant ID in the `AZURE_TENANT_ID` environment variable makes me able to authenticate to the tenant I'm guest of. Like @b10-dslappendel mentions, it doesn't work when setting the tenant ID using the `VisualStudioTenantId` in the `AzureDefaultCredentialOptions` of the `AzureDefaultCredential`. That said, I like this option better than setting it in code.

**Comment by b10-dslappendel** [comment]
Ah yes, setting `AZURE_TENANT_ID` does work. However, I feel like I should clarify my issue here to make sure that there's no confusion, since I noticed that something has changed since last year.

[I mentioned last year](#issuecomment-643289924) that 
1) `DefaultAzureCredential` doesn't pick up `VisualStudioTenantId` properly, and fails with a 401
2) specifying no tenant id results in the same 401

I seem to get the first case to work now. But the second one still doesn't work, whereas it did work with the earlier AppConfiguration preview libraries back in 2019. This is only the case when running locally with with our own account credentials.

Over the last few months, we have updated to the latest AppConfiguration library, moving away from the preview version in 2019, otherwise we were lacking behind with the changes.
However, currently we are forced to set the tenant id for every project we have in order to make it connect properly (or I guess setting the environment variable `AZURE_TENANT_ID` should also work, but that's also not very user friendly for debugging purposes). There's no automatic detection which tenant the AppConfiguration instance should be loaded from (whereas it did work that way with the earlier preview versions, as I mentioned before).

This is technically a regression from (a preview version in) 2019, but I'm not sure whether this is something you would want to add back (or even if it's feasible to do so).
Maybe another solution to explore would be to select the correct tenant in Visual Studio itself, so that VS sets `AZURE_TENANT_ID` upon running the project? Because currently, even though you can choose which account you would want to use in the Azure Service Authentication settings panel, you can't select the tenant here.

Hopefully I've provided some more context, let me know which direction you want to take.

**Comment by christothes** [comment]
Hi @b10-dslappendel  - You are correct that the Azure.Identity client works a bit differently than AppConfiguration. There is not enough context available to guess the correct tenant if multiple credentials are available to Visual Studio. Specifying the tenant Id is the only way to disambiguate the tenant currently.

Alternatively, you could also login to the desired tenant with Azure CLI and rely on that rather than the Visual Studio credential.

**Comment by b10-dslappendel** [comment]
@christothes Thanks for the confirmation. Are there any plans to support it in the future? Or at least supporting a choose tenant option in VS?

**Comment by christothes** [comment]
@b10-dslappendel - It is possible that we'll support the ability to determine the required tenant as part of future enhancements. 

I'll close out this issue for now.

**Comment by b10-dslappendel** [comment]
@christothes Alright, thanks for the communication 😀
