### ISSUE TITLE
KeyVaultErrorException incorrectly reports a http status code of 500

### ISSUE THREAD

**Issue by schaabs** [Azure/azure-sdk-for-net#8969]
A customer reported an issue of a `KeyVaultErrorException` being raised from `KeyVaultClient.PurgeSecret` with the following details pulled from their logging.

~~~
innerExceptionData":[{"code":"InternalError","subCode":0,"message":"Secret is currently being deleted.","timeStamp":"2019-12-02T21:34:05.2100705Z","httpStatusCodeInternal":500,"exceptionType":"Microsoft.Azure.KeyVault.Models.KeyVaultErrorException","details":[{"code":"RootActivityId","message":"65de34ee-df59-41fa-ac6f-de6035c0ac2b"},
~~~

However from looking at the logs it appears that the service returned a 409 in this case not a 500.

This issue was first encounted in Microsoft.Azure.KeyVault v2.3.2.

This issue was originally raised as an internal IcM issue, https://icm.ad.msft.net/imp/v3/incidents/details/161290635/home.

**Comment by heaths** [comment]
We investigated this and found that the request IDs for the 409 and 500 status codes were actually different, and there was no code path that would allow overriding the status code. The IcM ticket has been resolved.
