### ISSUE TITLE
Microsoft.Azure.Management.IotHub should respect "IoT" casing

### ISSUE THREAD

**Issue by rido-min** [Azure/azure-sdk-for-net#8979]
Although the [Capitalization convention](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions?redirectedfrom=MSDN)  suggest to use `Iot`, in this case the package Id, assembly name and namespace should respect the product name casing: `IoTHub`.

**Comment by jlian** [comment]
This is true, but the namespace that was chosen was `Microsft.Devices/IotHubs` unfortunately. .NET SDKs are generated off of the swagger based on that namespace, but maybe we could override it? @iluican thoughts?

**Comment by iluican** [comment]
@jlian It would also be a breaking change. Pretty sure it's not worth the trouble.

**Comment by jlian** [comment]
Don't think we will be able to accommodate this request, sorry
