### ISSUE TITLE
Create testing infrastructure to simulate retry requests.

### ISSUE THREAD

**Issue by AlexanderSher** [Azure/azure-sdk-for-net#8984]

**Comment by kurtzeborn** [comment]
Hey @AlexanderSher, can you be more specific on what you're looking for here?  Was this something you're investigating, or asking that someone else investigate?  Can you provide an example scenario you'd like to see covered with this?

**Comment by jsquire** [comment]
Given the age of this issue and the independent efforts working on Azure chaos, I'm going to close this out as stale.   Please feel free to reopen with some additional details if you believe this is still needed.
