### ISSUE TITLE
Improve documentation for permissions on various credential types

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#8992]
Based on feedback, we should improve the documentation cross-language about the different credential types that can be configured for Key Vault and how permissions need to be configured for, say, enumerating or using keys, getting secrets, etc.

**Comment by heaths** [comment]
All but the `CryptographyClient` have been updated to list required permission(s) for methods.

**Comment by pallavit** [comment]
When you say documentation do you mean on the methods\referral docs or readme's? Also where did we get this feedback from? This feels like a good item to pick-up in the v-team.

**Comment by heaths** [comment]
It was just a thought I had. The REST API docs have the required permissions, and I added them to .NET, but I also was thinking it would be nice if we (the v-team including the service teams) document how to manage Key Vault permissions anyway. There are some docs already out there as well. Maybe we just link to them from our READMEs.

**Comment by pallavit** [comment]
@heaths do you have any particular docs in mind you would want to put in readme's? I think this will be a perfect issue to address as MQ if you think it would be valuable to our customers.

**Comment by heaths** [comment]
E.g.:

* https://learn.microsoft.com/azure/key-vault/general/rbac-guide (recommended)
* https://learn.microsoft.com/azure/key-vault/general/assign-access-policy (legacy)

I still think it's worth making sure all languages update their API docs (maybe even REST, since many are auto-generated) to list the keys. That said, we may also want to mention the Data Action permissions for RBAC; however, I wonder if we should discuss a more holistic approach across SDKs or even REST with @KrzysztofCwalina and @tg-msft. I'm willing to prototype it in the Key Vault SDK for .NET.

**Comment by pallavit** [comment]
> I still think it's worth making sure all languages update their API docs (maybe even REST, since many are auto-generated) to list the keys.

If you think there is value here we should absolutely do this. Mind creating an issue for this across languages? We can take it in January and make sure all KV SDKs have this. 

> That said, we may also want to mention the Data Action permissions for RBAC; however, I wonder if we should discuss a more holistic approach across SDKs

Can you help me understand the scenario here? who would it benefit? I am wondering if we should do this in code or perhaps common documentation is all that is needed at this pointl

**Comment by heaths** [comment]
> Can you help me understand the scenario here? who would it benefit? I am wondering if we should do this in code or perhaps common documentation is all that is needed at this pointl

To which part?

* RBAC: KV recommends RBAC over legacy permissions, so listing the legacy permissions (perhaps last) and data actions would be necessary.
* In general, I think this may be in line with work @tg-msft has also been helping drive re: security attributes: REST APIs should document what permissions they require (if relevant) and we generate code from it. E.g., a `@critical` decorator would generate the new internal attribute we introduced for static analysis, but we could have a `@permissions` decorator that took a string list of what permissions are required to otherwise successfully call (i.e. no 403 or 404) an API. /cc @johanste @bterlson

**Comment by heaths** [comment]
I checked all the languages for Key Vault using `backupSecret` as a litmus and they all, somewhere, already list the legacy permission, which I think is good enough. I've opened Azure/typespec-azure#76 to track and will resolve this one.
