### ISSUE TITLE
[MQ] Parameterize ClientOptions for testing

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#8994]
We've got a number of dimensions that we want to parameterize our tests against including:

- validating the SDK against all supported service versions
- validating the SDK against federated clouds
- injecting certain classes of faults to verify the tests work in both the happy path

This would ideally include the infrastructure to:

- mark individual tests as ignored for certain combinations of parameters _(i.e., don't test recent service features with old versions)_
- mark certain parameters/parameter groups as only running in specific contexts _(i.e., only run against the latest version when testing locally but all of them nightly)_
- potentially allow different test recordings for each parameter/group

**Comment by AlexGhiondea** [comment]
I believe some of this has already been done.

**Comment by tg-msft** [comment]
Yes - we got the critical pieces with https://github.com/Azure/azure-sdk-for-net/pull/9582.  Closing the issue and we'll re-open if we need anything else.
