### ISSUE TITLE
Publish dialog for VS2015 dialog doesn't display errors

### ISSUE THREAD

**Issue by BillWagner** [Azure/azure-sdk-for-net#902]
The Publish dialog in VS 2015 doesn't provide hints when you create a new DB and the database password doesn't meet the requirements.

To repo:
Make a website project.
Publish to Azure
Select a new database
Enter a simple password ('test') for example.

You'll get an error message saying that you need to fix the errors in the dialog, but there is no indication as to what fields need to be corrected.

**Comment by matt-gibbs** [comment]
I have forwarded this issue on to the team that does VS tooling for Azure.
