### ISSUE TITLE
How to retrieve latest record from Azure table storage using C#?

### ISSUE THREAD

**Issue by rkmasternet** [Azure/azure-sdk-for-net#9020]
Hello All,
             I'm Facing an issue with azure table storage. I have lac's of data into the storage table. I need to query the data as per the Requirement. 
1.First approach is to retrieve all the data and then queried as per the requirement but its taking too much time.   
2. Second approach is what if i get filtered data from table storage directly using query

So as per my understanding second approach is best but i am not able queried appropriately.
*How can i retrieve the last entry from Azure table storage, in this i am also trying to MAX and order by function but its not work for me.
**Not running code: -** 
`var query2 = new TableQuery<TherapyEvent>().Where(
               TableQuery.CombineFilters(
                   TableQuery.GenerateFilterCondition("PartitionKey", QueryComparisons.Equal, patientId.ToString()),
                   TableOperators.And,
                   TableQuery.GenerateFilterConditionForGuid("DeviceID", QueryComparisons.Equal, deviceId))
                  
                   ).OrderByDescending(x=>x.EventDate).Take(1).Select(x=>x.EventDate).ToList();`

**Running code which taking too much time.**
`var query = new TableQuery<TherapyEvent>().Where(
              TableQuery.CombineFilters(
                  TableQuery.GenerateFilterCondition("PartitionKey", QueryComparisons.Equal, patientId.ToString()),
                  TableOperators.And,
                  TableQuery.GenerateFilterConditionForGuid("DeviceID", QueryComparisons.Equal, deviceId))
                  );
            var resp= _table.ExecuteQuery(query).OrderByDescending(x=>x.EventDate).Take(1).Select(x=>x.EventDate).ToList()`

**Comment by daniel-refahi** [comment]
we have been waiting for this feature for 5 years now

**Comment by AlexGhiondea** [comment]
@rkmasternet we have released a new version of the Tables library. Can you give it a try and see if it addresses your issue?
