### ISSUE TITLE
Improve HttpClient timeout handling in Azure Core

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#9031]
HttpClient throws a TaskCanceledException for timeouts. See https://github.com/dotnet/corefx/issues/20296 for additional context. This makes it so we won't actually retry in the Azure SDK, in general, for things like IOExceptions and TimeoutExceptions, because they would be wrapped in TaskCanceledExceptions. We should consider adding an HttpClientHandler as described [here](https://thomaslevesque.com/2018/02/25/better-timeout-handling-with-httpclient/) so that we can throw the correct exception so client libraries can correctly retry for exceptions that really shouldn't be thrown as TaskCanceledExceptions.

**Comment by JoshLove-msft** [comment]
Another idea that @tg-msft mentioned would be to have ResponseClassifier.IsRetriableException inspect the InnerException and retry if the inner exception is a Timeout or IOException.

**Comment by mikeharder** [comment]
@tg-msft, @pakrym: Can we prioritize fixing this issue?  It's hurting the reliability of the Storage Live Tests.  Here's a recent failure:

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=223861&view=ms.vss-test-web.build-test-results-tab&runId=7726628&resultId=100597&paneView=debug

In general, I think clients should treat "error from server" and "no response from server after timeout" the same way.  So I don't think this should be a controversial change.

**Comment by pakrym** [comment]
This issue is on my shortlist.
