### ISSUE TITLE
(Web sites mgmt.) GetUsageMetricsAsync throws FormatException on TZ > UTC+0000

### ISSUE THREAD

**Issue by bcrosnier** [Azure/azure-sdk-for-net#904]
## Issue

While calling `GetUsageMetricsAsync` on a `WebSite` element when living in a timezone above UTC (here, CET = UTC+0100), an exception is thrown.

```
System.FormatException
The DateTime represented by the string is out of range.
```
## Expected result

A `WebSiteGetUsageMetricsResponse` instance given with no exceptions.
## Steps to reproduce
1. Create a website on Windows Azure
2. Set your system to Romance Standard Time (or UTC+0100, CET, Europe/Paris, etc.)
3. In a project, retrieve the website you created using the `WebSiteManagementClient`.
4. On the `WebSite` instance, call the `GetUsageMetricsAsync()` method.

Simple demo code using the synchronous wrappers is available [on this gist](https://gist.github.com/bcrosnier/f7dd07d59c0be2d90bfe).
## Details

This issue does not happen when the system date is set on a zero or negative UTC index.

Debugging this shows a parsing attempt on the XML received from the server on the following line, in [`WebSiteOperations.cs#L5131`](https://github.com/Azure/azure-sdk-for-net/blob/master/src/WebSiteManagement/Generated/WebSiteOperations.cs#L5131):

```
DateTime nextResetTimeInstance = DateTime.Parse(nextResetTimeElement.Value, CultureInfo.InvariantCulture);
```

The XML element in question (`nextResetTimeElement`) here is a string representation of `DateTime.MaxValue` is structured like so:

```
<NextResetTime>9999-12-31T23:59:59.9999999Z</NextResetTime>
```

I suspect the issue is related to the trailing `Z` given by the server. A [similar issue](https://connect.microsoft.com/VisualStudio/feedback/details/605679/string-represetation-of-datetime-maxvalue-cant-be-parsed-by-datetime-parseexact) was reported and explained by Greg of the .NET BCL team. That or the value returned by the server is simply not correct.

**Comment by shahabhijeet** [comment]
please reopen if this is still an issue.
