### ISSUE TITLE
Unable to serialize message for legacy SB client when using modern SB client

### ISSUE THREAD

**Issue by josh-endries** [Azure/azure-sdk-for-net#9043]
Hello,

I have several services in production that use the "old" WindowsAzure.ServiceBus package and send/receive messages to/from queues. I would like to use the "new" Microsoft.Azure.ServiceBus package in new projects, such as the one I'm working on currently, but I haven't been able to coerce the new package to serialize and send messages in a format that the old package expects (the Base64 WCF XML binary stuff).

I have tried a few different approaches or snippets that I've found online but haven't gotten them to work. Maybe my search-fu isn't up to the task. I have gotten the opposite working (new package reading old package's messages).

Are there any _complete_ examples (with using statements, etc.) of doing this?

Again, or in other words, I am trying to use the Microsoft.Azure.ServiceBus library to send messages to a SB queue such that they will be successfully deserialized by an application that is using the WindowsAzure.ServiceBus library.

**Comment by josh-endries** [comment]
I think I figured out where I went wrong.

The service I am sending to is a webjob with a ServiceBusTrigger:

    public static async Task foo([ServiceBusTrigger(queueName)] BrokeredMessage message)

`ServiceBusTrigger` is from Microsoft.Azure.WebJobs.ServiceBus, 2.2 and `BrokeredMessage` is from Microsoft.ServiceBus 3.0. I'm not sure how it got set up this way but that's what it is.

The exception I see in the log is:

> Exception: SerializationException -- Message: There was an error deserializing the object of type System.Byte[]. The input source is not correctly formatted.

This happens when using this sending code in LinqPad with Microsoft.Azure.ServiceBus 4.1:

	var messageSender = new MessageSender(serviceBusConnectionString, queueName);

	var message = new Message(Encoding.UTF8.GetBytes(serializedJobMessage))
	{
		MessageId = messageId,
		CorrelationId = correlationId
	};

	await messageSender.SendAsync(message);

If I use `BrokeredMessage` from Microsoft.ServiceBus 3.0, it works fine, though:

	var message = new Microsoft.ServiceBus.Messaging.BrokeredMessage(Encoding.UTF8.GetBytes(serializedJobMessage))
	{
		MessageId = messageId,
		CorrelationId = correlationId
	};

	var queueClient = Microsoft.ServiceBus.Messaging.QueueClient.CreateFromConnectionString(serviceBusConnectionString, queueName);
	await queueClient.SendAsync(message);

I guess the two message classes aren't interchangeable (for some reason I got the impression that they are), at least not serialization wise. I suppose that if I used `Message` in the trigger, it might work.

I still can't send a Message that uses the BrokeredMessage body, which is what I was originally trying to do. I essentially just abandoned the new stuff and have both in my app now, but this workaround is okay for my current use case, until I can update the other end. It would be nice to not need references/code to both libraries in this situation.

**Comment by nemakam** [comment]
@josh-endries 
Copied from this - https://github.com/Azure/azure-service-bus-dotnet/issues/239#issuecomment-320820562 

1. send via full .net client and receive via .netstd client


type sent via .netfull | receive via .netstd
-- | --
stream | bytes (which is literally bytes from stream)
object (including string, bytes[]), the object is serialized with DataContract | GetBody<T> (the extension method we provided)

2. send via .netstd client and receive via full .net client

type sent via via .netstd | receive via .netfull
-- | --
bytes | GetBody<Stream> then get all bytes from streams
bytes (the bytes from the XmlObjectSerializer serialization e.g. DataContractBinarySerializer (we will make the class public) | GetBody<T>(XmlObjectSerializer) with default DataContractBinarySerializer or any customized other XmlObjectSerializer


If the systems are running with old client, you will be likely stuck with XmlObjectSerializer (data contract serializer) like our .netfull client. But things will not be broken. Sample code is like below which is exactly what happens underneath in the .netfull client.
```csharp
var bytes = your bytes;
var serializer = DataContractBinarySerializer<byte[]>.Instance;
using (MemoryStream stream = new MemoryStream())
{
    serializer.WriteObject(stream, bytes);
    var msg = new Message(stream.ToArray());
    var client = new Microsoft.Azure.ServiceBus.QueueClient(ConnectionString, Queue);
    await client.SendAsync(msg);
    await client.CloseAsync();
}
```

Supporting different body section types for AMQP is another important goal for us. We will later introduce support sending and receiving different AMQP body section types.

**Comment by nemakam** [comment]
@josh-endries , Let me know if the above explanation doesn't answer your question.
