### ISSUE TITLE
Extract Load Balancing from the Event Processor

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#9051]
# Summary

The current design for the `EventProcessorClient` introduced a new paradigm in which an `EventProcessorClient` is strongly bound to a given storage dependency and exposed in a separate package to ensure dependencies are isolated.  As a result, each storage offering will need to expose its own processor client and provide a set of functionality consistent across each of the Event Processor client implementations.

Additionally, there is a desire to introduce a base class for Event Processor client implementations to allow for developers with unique or advanced needs to customize a client for their needs while being able to leverage core processor functionality, such as load balancing.   At present, this will be difficult, as the load balancing functionality is embedded directly into the initial `EventProcessorClient` implementation.

In order to meet future goals and also to allow for a more deterministic testing experience though mocking, the load balancing functionality should be extracted into a stand-alone instance that can be shared among the processor implementations and can be injected for better testability.

# Scope of Work

- Determine the API shape needed to support a stand-alone load balancer, aimed at an `internal` visibility and packages within the Event Hubs client family of solutions.

- Prepare a proposed design skeleton and share with the .NET Event Hubs team, incorporating team feedback.

- Implement the stand-alone load balancer within the `Shared` area of Event Hubs, including a set of dedicated unit tests that offers comprehensive coverage of the functionality.

- Update the `EventProcessorClient` within the `Azure.Messaging.EventHubs.Processor` package to consume the new load balancer.

- Revise the tests for the `EventProcessorClient` within the `Azure.Messaging.EventHubs.Processor` package to be more reliable and deterministic by mocking load balancing rather than delegating to the `Manager` type that currently works around it.

# Out of Scope

- Updates or changes to samples beyond ensuring that the project can be compiled; these will be covered under a separate work item.

- Updates or changes to documentation; these will be covered under a separate work item.

# Success Criteria

- The refactoring and enhancements detailed by the scope have been completed.

- The tests necessary for its validation have been created or adjusted and pass reliably.

- The existing test suite continues to produce deterministic results and pass reliably.

# References

- [Event Hubs Client Library Strawman](https://gist.github.com/jsquire/36c0198e0898f203168e70bc15816d2c)
- [Event Hubs Client Library Skeleton](https://gist.github.com/jsquire/3fadc1ea57594c31f1c39366c0d7b530)

**Comment by jsquire** [comment]
Picking up the assignment on behalf of @christothes, as he had expressed interest but I'm unable to directly assign.

**Comment by christothes** [comment]
@jsquire I've created https://github.com/christothes/azure-sdk-for-net/pull/1 for discussion of the approach.

**Comment by jsquire** [comment]
> @jsquire I've created [christothes#1](https://github.com/christothes/azure-sdk-for-net/pull/1) for discussion of the approach

Much appreciated.   I left a few thoughts there; in a nutshell, I like the approach and think there are just a few details that we'll want to kick around to lock down.

**Comment by kinelski** [comment]
Issue solved by #9198.
