### ISSUE TITLE
[Flaky build] OSX "Use .NET Core sdk 3.0.100" fails 

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#9057]
```
/usr/bin/tar xzC /Users/runner/runners/2.160.1/work/_temp/67dc5e2a-a6cb-40bb-8c5f-07049de230e7 -f /Users/runner/runners/2.160.1/work/_temp/4bc95f2a-731c-4e59-9da7-158124aa3570
./sdk/3.0.100/FSharp/FSharp.Compiler.Private.dll: (Empty error message)
tar: Error exit delayed from previous errors.
##[error]Failed while installing version: 3.0.100 at path: /Users/runner/hostedtoolcache/dotnet with error: Failed while extracting downloaded package with error: Error: The process '/usr/bin/tar' failed with exit code 1

```

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=207600&view=logs&j=e44bd064-d8d9-5feb-6343-09b8c49ab1a8&t=dd9426be-7617-5dce-9eaf-97862ae512e5

**Comment by kurtzeborn** [comment]
@chidozieononiwu, we'll have to look at how often this is happening.  There may be an issue here that the .Net team is aware of already, so it's worth following up with them if this is happening more often than we'd like.

**Comment by chidozieononiwu** [comment]
Closing this issue as its the same as https://github.com/Azure/azure-sdk-for-net/issues/12120
