### ISSUE TITLE
Persist tokens and other outputs securely for test execution

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#9061]
Output tokens from test-sources.json need to be stored securely so we can remember them across sessions. We're opting to use this instead of environment variables, since changing environment variables requires restarting IDEs like VS (which spawns many child processes, most of which don't respond to broadcast messages asking them to update their environment variables).

* On Windows, we'll use DPAPI to encrypt files under %AppData%\azuresdk.
* On linux and MacOS, we'll chmod 700 ~/.local/azuresdk.

On both systems, the subdirectory will be a hash of the repo root (case-sensitive on linux/MacOS; tolower'd in Windows).

**Comment by heaths** [comment]
@pakrym did this for Windows, but we don't yet do this for linux and should consider it.

**Comment by heaths** [comment]
@schaabs given your work on Identity, will chmod'ing a file on linux be sufficient for storing secrets? We use DPAPI on Windows. It would be nice to be able to do this on *nix. If not, I'll close this.

/cc @pallavit @jsquire @JoshLove-msft

**Comment by heaths** [comment]
Talking offline, `chmod`'ing might be okay for test resource secrets, but if anyone uses persistent SP credentials that could be disastrous. No one has really asked for this on non-Windows, and given the effort required for a DPAPI-like implementation - the likes that `az` uses - I'm just going to close this. We can revisit later if needed.

**Comment by schaabs** [comment]
In Identity persisted token caches are protected on Mac and Linux as well using Keyring and Keychain. This does have some drawbacks. Keyring isn't installed by default on Linux distros, and Keychain isn't accessible on Mac in SSH sessions. In the cases where it's not available we have an option to allow storing the file unencrypted with only chmod protection, but this will error by default.

I would say the need to encrypt the file would depend on the information being stored in it. If it only contains details of test resources which are short lived it's chmod is probably sufficient. If on the other hand it contains account credentials or longer lived azure resources we should consider adding more protection.
