### ISSUE TITLE
Investigate Storage small blob download perf

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#9063]
Compare throughput for 10K blob downloads between Track 1 and Track 2 and investigate any meaningful deltas.  Reach out to @mikeharder or @tg-msft if you want info on the perf analysis tools we've been using thus far.

**Comment by JimSuplizio** [comment]
Hi @tg-msft, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
