### ISSUE TITLE
[BUG] Unexpected Result for AnalyzeImageByDomainAsync

### ISSUE THREAD

**Issue by wiazur** [Azure/azure-sdk-for-net#9068]
Computer Vision API v5.0.0 and v6.0.0-dev.20190919.3.

Testing through Visual Studio, Windows 10.

## Issue Description
The `AnalyzeImageByDomainAsync()` function returns a `DomainModelResults.Results`, but it is raw JSON response, meaning the user does not know what it can get from this response, until they print the whole response as a JSON dump. SDKs are supposed to prevent having to dig through JSON for results.

The other API calls do not have this, they have properties that represent the keys.
Requesting a fix so the user is not confused and this function is consistent with the other API calls.

Suggestion: return the properties of the results similar to the following examples:

`results.Result.name` - the name of the landmark or celebrity
`results.Result.confidence` - confidence of the correct name or face rectangle
`results.Result.faceRectangle.width` - gets the dimensions of the found face of a celebrity

[The function in the Computer Vision SDK](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cognitiveservices.vision.computervision.computervisionclientextensions.analyzeimagebydomainasync?view=azure-dotnet#Microsoft_Azure_CognitiveServices_Vision_ComputerVision_ComputerVisionClientExtensions_AnalyzeImageByDomainAsync_Microsoft_Azure_CognitiveServices_Vision_ComputerVision_IComputerVisionClient_System_String_System_String_System_String_System_Threading_CancellationToken-).

To reproduce, run this sample in a console application in Visual Studio:
https://github.com/Azure-Samples/cognitive-services-dotnet-sdk-samples/blob/master/documentation-samples/quickstarts/ComputerVision/Program.cs

**Comment by kaerm** [comment]
@anrothMSFT @tburns I am not sure if this is addressed in the new API version but would be good if you could take a look

**Comment by JimSuplizio** [comment]
Hi @wiazur, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
