### ISSUE TITLE
Distributed tracing: Add links on Send

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-net#9073]
**Is your feature request related to a problem? Please describe.**

EventHubs Track2 SDK creates 
- span per each message (when message is added to batch or sent).
- span for sending message/batch.

We assume that users, knowing their code, in most cases can figure out relationships between messages/send operations (they are most likely siblings).

The problem happens when we try to use automated tools and visualizations for the following cases

**Scenario 1**
- message was created at timestamp1
- sent at timestamp2
- processed at timestamp3

**Issue**: How to calculate heuristic like 'Time in queue' for the message (we can't say for sure when it was sent) for arbitrary case (not relying on operation names specific for event hub)

**Scenario 2**
- message was created at timestamp1
- sent at timestamp2 - send failed
- send retried at timestamp3 - succeed
- processed at timestamp4

Same issue.

**Scenario 3**
- message1 was created
- message1 sent 
- message2 was created
- message2 sent 

How do users/tools could find out which message was sent in which operation?

**Describe the solution you'd like**
Send span should have links to tracing contexts of all messages being sent.

**Describe alternatives you've considered**

**Additional context**

e.g. with following code

```csharp
EventDataBatch batch1 = await eventHubProducerClient1.CreateBatchAsync();
EventDataBatch batch2 = await eventHubProducerClient2.CreateBatchAsync();

batch1.TryAdd(new EventData(Encoding.UTF8.GetBytes("1")));
batch2.TryAdd(new EventData(Encoding.UTF8.GetBytes("2")));

batch1.TryAdd(new EventData(Encoding.UTF8.GetBytes("3")));
batch2.TryAdd(new EventData(Encoding.UTF8.GetBytes("4")));

await eventHubProducerClient1.SendAsync(batch1);
await eventHubProducerClient2.SendAsync(batch2);
```

![image](https://user-images.githubusercontent.com/2347409/70584026-7289a100-1b74-11ea-895e-79987e6cce18.png)

Try to figure out when which message was sent and to which event hub :)

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by jsquire** [comment]
Note:  See [this snippet](https://github.com/Azure/azure-sdk-for-net/blob/05648342092362d134c862af97f752d14fef7685/sdk/eventhub/Azure.Messaging.EventHubs.Processor/src/EventProcessorClient.cs#L840) for reference.
