### ISSUE TITLE
[BUG] GetToken(string[] scopes) in docs, not in code.

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-net#9077]
Docs has string[] scopes overrides:
![image](https://user-images.githubusercontent.com/2163001/70588947-33168100-1b83-11ea-8763-2605e3b4d120.png)

https://docs.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet

Code does not:

![image](https://user-images.githubusercontent.com/2163001/70589020-707b0e80-1b83-11ea-9ff0-2413fcc0c917.png)

**Comment by christothes** [comment]
This appears to have been resolved.
