### ISSUE TITLE
Consider breaking TextAnalyticsClient into multiple clients.

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#9079]
Do UX research on what functionality is used together and if/whether it would make sense to break different clients into different packages, such as Pii or other entity endpoints.

Related to this: https://github.com/Azure/azure-sdk-for-net/issues/8895

**Comment by mayurid** [comment]
This is something we will need to look for all libraries  We should also discuss this with Service team

**Comment by maririos** [comment]
UX study showed that library as is, is good and there isn't a necessity to break functionality in multiple clients.
For now I am going to close it.
Feel free to re-open in case there is more investigation/work to be done here
