### ISSUE TITLE
Investigate: Improve the performance of success and error responses

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#9089]
Per Heath's comment: https://github.com/Azure/azure-sdk-for-net/pull/9080#discussion_r356843416

- work with service team to document result sort order, if possible
- reimplement merge algorithm

**Comment by annelo-msft** [comment]
We may move this to March @mayurid

**Comment by annelo-msft** [comment]
Investigate the impact of this to decide when it should happen.

**Comment by maririos** [comment]
FYI @mssfang

**Comment by maririos** [comment]
Hopefully with the work on https://github.com/Azure/azure-sdk-for-net/issues/8704 we might be able to see if this is a concern or not

**Comment by maririos** [comment]
I believe that we are good for now. We have added performance tests. If we see a regression we will start looking here.
I will close this issue and will reopen when needed
