### ISSUE TITLE
Improve test coverage of TA library

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#9091]
Consider for mock types:
https://github.com/Azure/azure-sdk-for-net/pull/9080#discussion_r356744102

**Comment by annelo-msft** [comment]
https://github.com/Azure/azure-sdk-for-net/pull/9335#issuecomment-571659277

**Comment by maririos** [comment]
#9335 (comment) addressed here https://github.com/Azure/azure-sdk-for-net/pull/9523/files#diff-96979e4bd9871a78178e9e1d28c133b6R145

**Comment by maririos** [comment]
Move Authentication tests to LiveTests => https://github.com/Azure/azure-sdk-for-net/pull/9433#discussion_r370474741

**Comment by maririos** [comment]
>Move Authentication tests to LiveTests => #9433 (comment)

Done

**Comment by maririos** [comment]
Last remaining tests are in PR https://github.com/Azure/azure-sdk-for-net/pull/9849

**Comment by maririos** [comment]
PR #9849 will be merged after today's release. so moving to P3

**Comment by maririos** [comment]
PR merged
