### ISSUE TITLE
[BUG] [storage] [files] UploadRangeAsync takes in a stream when set to Clear Range 

### ISSUE THREAD

**Issue by amnguye** [Azure/azure-sdk-for-net#9093]
**Describe the bug**
To clear ranges for a Azure File the mehtod UploadRange needs to be called, using the parameter writeType to be set to "ShareFileRangeWriteType.Clear". However when calling this method, with this parameter it still requires to pass a stream object for the content parameter. This is unnecessary for the user to have to create a stream that's not used.

Currently the SDK uses that stream to determine the content-length, which is set to 0 when performing a clear range. When using clear, we should automatically set the content-length header to 0

***Code Snippet***
`sourceFile.UploadRangeAsync(ShareFileRangeWriteType.Clear, new HttpRange(0, 1024), new MemoryStream());`
(This is currently the workaround for this behavior if you just hand the method a blank stream)
**Expected behavior**
`sourceFile.UploadRangeAsync(ShareFileRangeWriteType.Clear, new HttpRange(0, 1024)));`

**Comment by seanmcc-msft** [comment]
I think we should split UploadRangeAsync into
```
UploadRangeAsync(HttpRange range, Stream content, byte[] transactionalContentHash, IProgess<long> progressHandler, CancellationToken cancellationToken)
ClearRangeAsync(HttpRange range, CancellationToken cancellationToken)
```
@tg-msft, what do you think?

**Comment by tg-msft** [comment]
I think that's a good idea.  We just need to leave the original overload for compat (hidden behind `[EditorBrowsable(...)]`, etc., is fine though).
