### ISSUE TITLE
ServiceBusManagement not working anymore?

### ISSUE THREAD

**Issue by riccardobecker** [Azure/azure-sdk-for-net#910]
The latest drop of the ServiceBusManagement library seems to be broken?

            ServiceBusManagementClient sbClient = new ServiceBusManagementClient(credentials);

used to work before but now gives me a: "

The best overloaded method match for 'Microsoft.WindowsAzure.Management.ServiceBus.ServiceBusManagementClient.ServiceBusManagementClient(System.Net.Http.HttpClient)' has some invalid arguments	

This used to work before?

Am I missing something?

I installed the "ordinary" management tools for storage and so on.

regards

**Comment by riccardobecker** [comment]
Getting the latest drops of the Management libraries combined with preview version 0.14

Install-Package Microsoft.WindowsAzure.Management.ServiceBus -Version 0.14.0-preview -Pre

Seems to work.

**Comment by markcowl** [comment]
Closing as no repro.  Please reopen this issue if you see a recurrence.
