### ISSUE TITLE
[BUG] System.FormatException: 'No valid combination of account information found.' when using SAS Connection String

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-net#9110]
This code, which uses the SAS connection string from the Azure Portal
![image](https://user-images.githubusercontent.com/2163001/70736188-a1af2800-1cc4-11ea-8a6c-cac35feaffe7.png)

```
var connString = "BlobEndpoint=https://jongstorage.blob.core.windows.net/;QueueEndpoint=https://jongstorage.queue.core.windows.net/;FileEndpoint=https://jongstorage.file.core.windows.net/;TableEndpoint=https://jongstorage.table.core.windows.net/;SharedAccessSignature=sv=2019-02-02&ss=b&srt=sco&sp=rwdlac&se=2019-12-13T01:29:16Z&st=2019-12-12T17:29:16Z&spr=https&sig=...";
var blobContainerClient = new BlobContainerClient(connString, "containerjong123");
blobContainerClient.CreateIfNotExists();
```

Now throws this exception:
```
  | Message | "No valid combination of account information found." | string

```

**Comment by JoshLove-msft** [comment]
The issue is that our SDK doesn't support table storage. We can make it so we don't fail validation if table storage endpoint and SAS permissions are included in connection string.

**Comment by JoshLove-msft** [comment]
The workaround is to remove the table endpoint from the connection string.

**Comment by jongio** [comment]
Thanks Josh.

I have confirmed that workaround works, here are more detaills.

The TableEndpoint URL cannot exist in the connection string, so remove it.

![image](https://user-images.githubusercontent.com/2163001/70746441-ab438a80-1cda-11ea-9e33-016113b15535.png)

Do not check the Table checkbox in the Portal
![image](https://user-images.githubusercontent.com/2163001/70746817-69ffaa80-1cdb-11ea-8622-2b6a32e313c4.png)


If you have a "t" in the "ss" parameter, then you need to re-generate the SAS connection string without the Table option selected, you cannot simply remove the "t" from the parameter, because the SAS generation takes that parameter into account.

![image](https://user-images.githubusercontent.com/2163001/70746527-d62dde80-1cda-11ea-8813-b9403a4b5867.png)
