### ISSUE TITLE
return cloudblockblob size

### ISSUE THREAD

**Issue by thdotnet** [Azure/azure-sdk-for-net#9112]
using the following:

`CloudBlockBlob blob = container.GetBlockBlobReference(blobName);
`
blob.Properties and blob.Properties.Length are not being populated. Why is this happening? What is the approach to get cloudblockblob size?

**Comment by zezha-msft** [comment]
Hi @thdotnet, you probably need to invoke the get properties call before looking at the length.

**Comment by seanmcc-msft** [comment]
Response<BlobProperties> response = await blob.GetPropertiesAsync();
long length = response.Value.ContentLength;

**Comment by thdotnet** [comment]
Thanks, but I was expecting this to be automatically populated because I do need the blob and it's properties, don't want to do two calls for it.

**Comment by thdotnet** [comment]
@seanmcc-msft there's no such method on assembly Microsoft.Azure.Storage.Blob (11.1.0.0).

**Comment by zezha-msft** [comment]
@thdotnet `GetBlockBlobReference` is not making any actual HTTP call, it's just giving you a reference (pointer) to the blob.

**Comment by thdotnet** [comment]
@zezha-msft anyway, there's no GetPropertiesAsync on CloudBlockBlob / CloudBlob classes

**Comment by seanmcc-msft** [comment]
Microsoft.Azure.Storage.Blob 11.x is the old Azure Storage SDK.

To get the properties of a blob using the old SDK:
```
// This is not making a network call, it is simply creating the CloudBlockBlob object.
CloudBlockBlob blob = container.GetBlockBlobReference(blobName);

// This is making a network call to get the blob's properties.
await blob.FetchAttributes();

long length = blob.Properties.Length;
```

Azure.Storage.Blobs 12.x is the new SDK.

To get blob properties using the new SDK:
```
// This is not making a network call, it is simply creating the BlockBlobClient object.
BlockBlobClient blob = container.GetBlockBlobClient(blobName);

// This is making a network call to get the blob's properties.
Response response = await blob.GetPropertiesAsync();

long length = response.Value.ContentLength;
```

**Comment by thdotnet** [comment]
Can you flash in the description that Microsoft.Azure.Storage.Blob is the old sdk? there's a confusion about it. There are WindowsAzure.Storage, Microsoft.Azure.Storage, Azure.Storage.Blobs and maybe more. Please also update docs.microsoft.com saying which one is the official / most recent SDK

**Comment by CoderKooke** [comment]
I would really appreciate some clarity on it too.  In a .Net Core 3.1 app using Azure.Storage.Blob 11.1.4 the FindAttributes() method errors stating the blob does not exist despite being able to return the parent path, name and other properties.

FindAttributesAsync doesn't error but returns -1 for length and other properties are null but no doubt that is a version issue.

Feel like I'm stuck in a gap between the two.
