### ISSUE TITLE
[BUG] Trying to use generated SAS token in SDK v12

### ISSUE THREAD

**Issue by SiobhanBaynes** [Azure/azure-sdk-for-net#9139]
**Describe the bug**
A SAS token created for a blob appears to generate successfully but fails validation on download

***Exception or Stack Trace***
When trying to hit the URL in the browser the following message is given:
`<Error>
<Code>AuthenticationFailed</Code>
<Message>
Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:xxxTime:2019-12-13T19:36:46.4526282Z
</Message>
<AuthenticationErrorDetail>
Signature did not match. String to sign used was r 2020-12-13T19:36:29Z /blob/eutranscriptiondemo/audiofiles/Input.wav https,http 2019-02-02 b
</AuthenticationErrorDetail>
</Error>`

**To Reproduce**
Create a console app, add Azure.Storage.Blobs v12.1.0, create a container and blob file and add the code snippet. 

***Code Snippet***
Example here uses the emulator, but it fails in the same way with real credentials.
```
static void Main(string[] args)
{
	var blobUrl = "http://127.0.0.1:10000/devstoreaccount1/audiofiles/Input.wav";
	var url = new Program().GetAccessKey(blobUrl);
}
public string GetAccessKey(string blobName)
{
	var blobSasBuilder = new BlobSasBuilder()
	{
		BlobName = blobName,
		ExpiresOn = DateTime.UtcNow.AddYears(1),
		Protocol = SasProtocol.HttpsAndHttp,
	};
	blobSasBuilder.SetPermissions(BlobSasPermissions.Read);
	var sasQueryParameters = blobSasBuilder.ToSasQueryParameters(
		new StorageSharedKeyCredential("devstoreaccount1", "Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=="));
	var sasUri = new UriBuilder(blobName);
	sasUri.Query = sasQueryParameters.ToString();
	return sasUri.ToString();
}
```

**Expected behavior**
The browser should be able to download the file.

**Setup (please complete the following information):**
 - OS: W10
 - IDE : VS 16.4
 - Azure.Storage.Blobs v12.1.0,

**Comment by JoshLove-msft** [comment]
It looks like in the snippet, we are setting the BlobSasBuilder.BlobName = BlobUrl rather than the BlobName itself.

I believe it should work if we set BlobName to the actual blob name, and set BlobContainerName to the container name in the BlobSasBuilder.

**Comment by SiobhanBaynes** [comment]
Awesome thanks!..I tried a bunch of parameters in there but didn't spot the BlobContainerName property.  Are there any docs for this?  If not, do you have a stub I can contribute to?

**Comment by tg-msft** [comment]
We're still working on getting more comprehensive [samples](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/samples/Sample02_Auth.cs#L125) out that will walk through a number of these scenarios in more depth.  Please check back soon.

We also generate [reference docs](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.sas.blobsasbuilder?view=azure-dotnet) from our [doc comments](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/Sas/BlobSasBuilder.cs#L14).
