### ISSUE TITLE
Onboard January releases on docs.microsoft.com

### ISSUE THREAD

**Issue by kaerm** [Azure/azure-sdk-for-net#9146]
- [ ] Onboard the following packages on docs.microsoft.com
**Latest:**
Azure.Messaging.EventHubs 5.0.0
Azure.Messaging.EventHubs.Processor 5.0.0
Azure.Messaging.EventHubs.CheckpointStore.Blobs 1.0.0
Azure.Data.AppConfiguration 1.0.0
Azure.Security.KeyVault.Certificates 4.0.0
Azure.Storage.Files.DataLake 12.0.0
**Preview:**
Azure.AI.TextAnalytics 1.0.0-preview1
Azure.Cosmos 4.0.0
**Legacy:**
Microsoft.Azure.EventHubs.Processor 4.1.0
Microsoft.Azure.EventHubs 4.1.0

- [ ] Remove following packages from preview:
Azure.Security.KeyVault.Certificates P 4.0.0-preview.7
Azure.Messaging.EventHubs 5.0.0-preview.6
Azure.Messaging.EventHubs.CheckpointStore.Blobs 1.0.0-preview.4
Azure.Data.AppConfiguration 1.0.0-preview.6
Azure.Storage.Files.DataLake 12.0.0-preview.6

- [ ] Update GA versions if they are not pulling from latest for:
Azure.Core 1.0.1
Azure.Identity 1.1.0
Azure.Storage.Files.Shares 12.0.0
Azure.Storage.Common 12.0.0
Azure.Storage.Blobs.Batch 12.0.0
Azure.Storage.Blobs 12.0.0
Azure.Storage.Queues 12.0.0
Azure.Security.KeyVault.Keys 4.0.0
Azure.Security.KeyVault.Secrets 4.0.0

@AlexGhiondea to confirm version numbers

**Comment by ThisWillDoIt** [comment]
I'm a little bit confused by the status of this ticket.

The January 2020 [Docs](https://azure.github.io/azure-sdk/releases/2020-01/dotnet.html) say Azure.Messaging.EventHubs is GA and the install instruction say it is version 5 (without preview version).

The 'latest releases' section on the same docs page says it's still Preview 6 and the [NuGet package](https://www.nuget.org/packages/Azure.Messaging.EventHubs) is also still on Preview 6.

**Comment by kaerm** [comment]
@ThisWillDoIt sorry for the confusion, we are updating our docs in preparation for the January release but the actual package hasn't been published yet. It should be out very soon though.
