### ISSUE TITLE
[BUG] Run pipeline fails for targeting .net core 3.1

### ISSUE THREAD

**Issue by arman-g** [Azure/azure-sdk-for-net#9154]
**Describe the bug**
 Run pipeline fails for targeting .net core 3.1.

***Exception or Stack Trace***

```
 "/home/vsts/work/1/s/lasc.web.jurybot/lasc.web.jurybot.csproj" (Restore target) (1) ->

       "/home/vsts/work/1/s/lasc.web.jurybot/lasc.web.jurybot.csproj" (_GenerateRestoreGraphProjectEntry target) (1:5) ->

       (_CheckForUnsupportedNETCoreVersion target) -> 

         /usr/share/dotnet/sdk/3.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(127,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.1.  Either target .NET Core 3.0 or lower, or use a version of the .NET SDK that supports .NET Core 3.1
```

**To Reproduce**
1. Setpup azure pipeline for a project targeting .net core 3.1
2. Run pipeline.

**Expected behavior**
Should run the pipeline and build the application without errors.

**Setup (please complete the following information):**
- Azure DevOps Pipeline
 - .net core 3.1

**Comment by pakrym** [comment]
Hello, thank you for your report but this repository contains Azure Client SDK libraries. Azure DevOps issues should be filed using developercommunity.visualstudio.com.


Please take a look at https://developercommunity.visualstudio.com/content/problem/844809/azure-pipelines-wapproj-build-fails-using-windows.html
