### ISSUE TITLE
Give clients access to exceptions/failed responses from retries

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#9157]
If a request is retried and the final retry results in an exception, an AggregateException is thrown which includes the previous exceptions. However, if the final retry results in a failure response, clients have no way to access the previous exceptions or previous failure responses. This information is very useful in debugging failures. For instance, the default ResponseClassifier will retry on IOExceptions or RequestFailedExceptions with a response status of 0. In Storage, when creating a new container, if the connection is dropped after the request goes out, the retried request would get back a ContainerAlreadyExists response from the service, but without including the previous failures in the exception thrown by Storage, it is unclear why the Container would already exist.

**Comment by pakrym** [comment]
We've added logging of these exceptions.
