### ISSUE TITLE
[BUG] BlobClient.DownloadAsync() doesn't return ContentHash even though docs suggest it should

### ISSUE THREAD

**Issue by danwkennedy** [Azure/azure-sdk-for-net#9165]
**Describe the bug**
Calls to `BlobClient.DownloadAsync()` and `BlobClient.DownloadAsnyc(CancellationToken)` don't return the `BlobDownloadInfo.ContentHash` field.

**To Reproduce**
- Set up a blob with the content hash set
- Download using either `DownloadAsync()` or `DownloadAsync(CancellationToken)`
- Look at the contents of the `ContentHash` property

***Code Snippet***

```C#
var blob = (await BlobClient.DownloadAsync(cancellationToken)).Value;
var properties = (await BlobClient.GetPropertiesAsync(cancellationToken: cancellationToken)).Value;

Console.WriteLine(blob.ContentHash); // Outputs nothing, is null
Console.WriteLine(properties.ContentHash); // Outputs "System.Byte[]"

Console.WriteLine(properties.ContentHash.Length); // Outputs a value greater than 0
Console.WriteLine(blob.ContentHash); // Throws, can't read property of null

```

**Expected behavior**
Since the [docs](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.models.blobdownloadinfo.contenthash?view=azure-dotnet#Azure_Storage_Blobs_Models_BlobDownloadInfo_ContentHash) for `BlobDownloadInfo` state:

>If the blob has an MD5 hash and this operation is to read the full blob, this response header is returned so that the client can check for message content integrity.

I would expect `DownloadAsync()` and `DownloadAsync(CancellationToken)` calls to return the `ContentHash` as they satisfy both of those conditions.

**Setup (please complete the following information):**
 - OS: .net Core so N/A
 - Version: 12.1.0

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by jsquire** [comment]
//cc: @tg-msft

**Comment by seanmcc-msft** [comment]
I can repo the issue, DownloadReponse.ContentHash is null, but DownloadResponse.Details.BlobContentHash is populated.

This may be by design, since BlobClient.Download() may have to preform multiple get requests to download the entire blob. 

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/BlobBaseClient.cs#L601

**Comment by danwkennedy** [comment]
Yeah, I found a workaround with the following code:

```C#
var blob = (await BlobClient.DownloadAsync(cancellationToken)).Value;

Console.WriteLine(blob.Details.BlobContentHash); // Outputs "System.Byte[]"
```

It doesn't change the fact that the docs and returned object are confusing. At least I can do what I need to in a single request instead of two 😄

**Comment by tudort-iquest** [comment]
This bug still appears on v12.4.1, but when BlobClient.DownloadToAsync(Stream destination) is called for an 0-byte blob..

**Comment by seanmcc-msft** [comment]
Unfortunately, I can't reproduce this issue.  In [this](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/tests/BlobBaseClientTests.cs#L183) unit test, `response.Value.ContentHash` is populated.  I also tried with a 0-byte blob with the same result.
