### ISSUE TITLE
[FEATURE REQ] Exists/CreateIfNotExists/DeleteIfExists for DataLake

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#9173]
Is your feature request related to a problem? Please describe.
Related to issue #7211
BlobContainerClient has CreateIfNotExists/DeleteIfExists methods. We should add similar methods for DataLakeFileSystemClient

Describe the solution you'd like
Helper methods (like CreateIfNotExists/DeleteIfExists) for DataLakeFileSystemClient and possibly other DataLake clients where it makes sense.

Describe alternatives you've considered
Can easily be worked around. Refer to #7211.

Additional context

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by seanmcc-msft** [comment]
I think we should add CreateIfNotExists(), Exists(), DeleteIfExists() to FileSystemClient and PathClient.

**Comment by seanmcc-msft** [comment]
Related https://github.com/Azure/azure-sdk-for-net/issues/9509
