### ISSUE TITLE
[BUG] TaskCanceledException with PublishEventsAsync function

### ISSUE THREAD

**Issue by MattHartz** [Azure/azure-sdk-for-net#9175]
**Describe the bug**
Occasionally in production, receiving Task Cancelled at the "PublishEventsAsync" function. 
Once this happens, i have to redeploy my application for it to stop breaking particular functions.

I have a wrapper class that contains an EventGridClient, and this class is stored in a DI container using Unity, so if there are any HttpClients that EventGridClient is creating, it should only be one.  Unfortunately not able to batch events without a large code overhaul.

System.Threading.Tasks.TaskCanceledException

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Microsoft.Azure.EventGrid.EventGridClient.<PublishEventsWithHttpMessagesAsync>d__38.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Microsoft.Azure.EventGrid.EventGridClientExtensions.<PublishEventsAsync>d__0.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**To Reproduce**
I am unfortunately not able to reproduce this in anyway, but it appears to be an issue in some posts. Haven't found any help from said posts.

https://github.com/Azure/azure-sdk-for-net/issues/4575
https://github.com/Azure/azure-functions-host/issues/3160
https://social.msdn.microsoft.com/Forums/windows/en-US/8cb7640e-d108-4820-93f4-75743487f8ad/publish-to-event-grid-failing-with-a-task-was-canceled?forum=servbus
https://stackoverflow.com/questions/29179848/httpclient-a-task-was-cancelled

**Expected behavior**
Don't do this ;)

**Setup (please complete the following information):**
Service Fabric 6.4.641
Framework 4.6.1

Thanks!!!

**Comment by jfggdl** [comment]
Thanks for creating this issue. Would you please share, if possible without sharing any sensitive information, the code snippet that you are using?

**Comment by MattHartz** [comment]
```C#

**Comment by MattHartz** [comment]
Potentially more information...

"Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request" inner exception.

**Comment by ahamad-MS** [comment]
Thanks @MattHartz  for reporting this issue. EventGridClient is autogenerated for us using AutoRest. It is not clear to me from your description what might cause this. I did not spot anything wrong from your code snippet too. It is not EventGrid service related issue but I will try to loop more teams to take a closer look into this issue. thanks.

**Comment by ahamad-MS** [comment]
Hello @isra-fel .. Any idea who might be able to help investigating this issue from auto-rest generated code perspective?

I added AutoRest Runtime tag but not sure if they will be the right team to help. 

kindly advise.

thanks

**Comment by MattHartz** [comment]
@ahamad-MS Thanks for attempting to aggregate the teams around this. I will be grabbing the EventGridClient's version shortly.

**Comment by MattHartz** [comment]
EventGridClient "1.4.0"

**Comment by MattHartz** [comment]
Any updates?

**Comment by gdodd1977** [comment]
We are getting this error from time to time as well when calling PublishEventsAsync. We register EventGridClient as singleton, so I assume it should be handling the HttpClient creation so as to not create too many clients. Or do I have that assumption incorrect?

**Comment by lilyjma** [comment]
@MiYanni, do we have any updates on this issue?

**Comment by MiYanni** [comment]
@lilyjma Unfortunately, our team currently doesn't work on the AutoRest.CSharp v2 generator. We're only working on AutoRest.CSharp v3 which will replace v2 at some point. Since this is generated, I'm assuming it is EventGrid management plane, since we didn't have any generated data plane clients (AFAIK). @erich-wang Do you know who to contact for management plane C# EventGrid SDK assistance?

**Comment by rhan1161** [comment]
@MiYanni @lilyjma @erich-wang @ahamad-MS Any updates on this issue?  We are seeing this issue in our Prod environment.  Is there another channel where I can escalate this issue up the chain?

**Comment by lilyjma** [comment]
@nickzhums do you know who might be able to help with this?

**Comment by nickzhums** [comment]
@dingmeng-xue could you let someone have a look to see if this is indeed AutoRest issue or something can be done on the SDK side ? This is generated mgmt SDK and the customer is having issues.

**Comment by cravecode** [comment]
I have been getting this error as well.
In my situation (perhaps others' as well?) I believe it is caused by too large of a payload in the POST to the EventGrid API (`https://******.****.eventgrid.azure.net/api/events?api-version=2018-01-01`).
When I change the call to a synchronous call so that i can actually see the process run to completion, I get a `413` response code.
```
StatusCode: 413, ReasonPhrase: 'Request Entity Too Large', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Transfer-Encoding: chunked
  Server: Microsoft-HTTPAPI/2.0
  Strict-Transport-Security: max-age=31536000; includeSubDomains
  x-ms-request-id: e309ef43-6b64-4236-86f1-d53de4f8e7ad
  Date: Tue, 21 Apr 2020 15:27:18 GMT
  Content-Length: 279
}
Example of the temporary code change I made to make the post synchronous so I could see the completed response. 
```
<img width="813" alt="event-grid-sdk" src="https://user-images.githubusercontent.com/169682/79915797-a06dd480-83f5-11ea-89c2-2fd9dbf37a12.png">

**Comment by isra-fel** [comment]
@ahamad-MS hello, could you confirm what @cravecode posted about size limitation? Thank you both 😄 

(And just to clarify some misunderstanding: as the label suggests, this is data-plane SDK.)

**Comment by MattHartz** [comment]
Turns out for us a lot of the issue was just OOM exceptions that trickled task cancelled. Not 100% sure why it ultimately would happen roughly at the same spot, but heh.

**Comment by cravecode** [comment]
IMO, this issue can be closed.
