### ISSUE TITLE
[BUG] BlobClient.UploadAsync doesn't report progress correctly on large files

### ISSUE THREAD

**Issue by gdignard** [Azure/azure-sdk-for-net#9180]
**Describe the bug**
For large files (not sure what the cutoff is, but certainly for 400G+ files) the IProgress<long> returns a value which appears to be the upload progress of one upload thread rather than a global value.

***Exception or Stack Trace***
Not applicable

**To Reproduce**
Use the public virtual Task<Response<BlobContentInfo>> UploadAsync(string path, BlobHttpHeaders httpHeaders = null, IDictionary<string, string> metadata = null, BlobRequestConditions conditions = null, IProgress<long> progressHandler = null, AccessTier? accessTier = null, StorageTransferOptions transferOptions = default, CancellationToken cancellationToken = default) call for a large file and observe the value passed back by the progressHandler.

***Code Snippet***
Not applicable

**Expected behavior**
Each invocation of the Progress<long> would be the total number of bytes successfully uploaded so far.

**Screenshots**
Output for an upload of file size 327,653,166 bytes:
Progress[0] 0
Progress[1] 131,072
Progress[2] 131,072
Progress[3] 0
Progress[4] 0
Progress[5] 131,072
Progress[6] 0
Progress[7] 131,072
Progress[8] 131,072
Progress[9] 0
Progress[10] 262,144
Progress[11] 262,144
Progress[12] 262,144
Progress[13] 262,144
Progress[14] 262,144
Progress[15] 393,216
Progress[16] 393,216
Progress[17] 524,288

etc...
NOTE: Eventually the numbers reset to zero once they hit a little over 8,000,000; the progress for the file in question -- again 327,653,166 bytes -- ends with the sequence

Progress[2570] 8,257,536
Progress[2571] 8,388,608
Progress[2572] 7,733,248
Progress[2573] 7,864,320
Progress[2574] 8,388,608
Progress[2575] 7,995,392
Progress[2576] 8,126,464
Progress[2577] 8,257,536
Progress[2578] 8,388,608
Progress[2579] 8,388,608
Upload Complete

**Setup (please complete the following information):**
 - OS: Windows
 - IDE : VisualStudio Pro
 - Version of the Library used
Assembly Azure.Storage.Blobs, Version=12.1.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8

**Additional context**
Not applicable

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by gdignard** [comment]
Additional context; this was also a Xamarin situation and the upload was taking place on an iOS device.

**Comment by zezha-msft** [comment]
@tg-msft I see that you removed the Service Attention label, are you handling this one?

**Comment by tg-msft** [comment]
@zezha-msft I added it as an oversight and immediately removed it _(we're only using Service Attention for Track 1 libraries, per my understanding)_.  I'm not planning on investigating this bug -- but I'll be sure to assign things to myself when I am to help make that clear.

**Comment by sam-piper** [comment]
Just to add, I'm seeing exactly the same issue with 12.1 in a standard .NET Core 3.1 Console app.

**Comment by gdignard** [comment]
I had a quick look around; I would say the prime suspect is 

azure-sdk-for-net/sdk/storage/Azure.Storage.Blobs/src/PartitionedUploader.cs

Where, at line 212 in the lastest revision there's an 
private async Task<Response<BlobContentInfo>> UploadInParallelAsync (
            Stream content,
            int blockSize,
            BlobHttpHeaders blobHttpHeaders,
            IDictionary<string, string> metadata,
            BlobRequestConditions conditions,
            IProgress<long> progressHandler,
            AccessTier? accessTier,
            CancellationToken cancellationToken)

Which is invoked when the file size is larger than a target value and which includes an await foreach where each task is passed the same IProgress<long> reference.
