### ISSUE TITLE
Cannot delete a message after dequeue

### ISSUE THREAD

**Issue by takaz-ams** [Azure/azure-sdk-for-net#9183]
I am using azure storage queues to push messages then i ma running an aspnet core worker app to process the queue. After successfully getting a message and logging it to the db, i can delete the message. The app then hangs at that line and never returns. This like is the main issue:

 await _queueViews.DeleteMessageAsync(msgClick);
here is the rest of the code

  CloudQueueClient queueClient = storageAccount.CreateCloudQueueClient();
            _queueClicks = queueClient.GetQueueReference(ClicksQueue);
            _queueViews = queueClient.GetQueueReference(ItemViewsQueue);
            _queueClicks.CreateIfNotExistsAsync();
            _queueViews.CreateIfNotExistsAsync();

....
....
..
   var msgClick = await _queueClicks.GetMessageAsync();
                if (!(msgClick is null))
                {
                    var content = JsonConvert.DeserializeObject<MessageClickWrapper>(msgClick.AsString);
                    if (content != null && content.ItemClickLog != null)
                    {
                        if (!await _context.ShopItemClickLogs.AnyAsync(a => a.Id == content.ItemClickLog.Id))
                        {
                            await _context.ShopItemClickLogs.AddAsync(content.ItemClickLog);
                            await _context.SaveChangesAsync(stoppingToken).ConfigureAwait(false);
                        }
                        try
                        {
                            await _queueViews.DeleteMessageAsync(msgClick);
                        }
                        catch (AggregateException axp)
                        {
                            _logger.LogError(axp.Message);
                        }
                    }
                }

**Comment by amnguye** [comment]
Hi @takaz-ams 

What version of the SDK are you using?

Also when you say the app hangs, do you mean the aspnet app or the .NET sdk hangs?

**Comment by takaz-ams** [comment]
Hi
I am using 2.9

By hanging i mean that when i debug the app, and step through the lines, when i get to that particular line it does not go beyond that line. The call to .DeleteMessageAsync(msg); never returns.

If i comment out that line, it goes through and reads the next message.
I did notice that when the queue only have one message, it seems to works fine. It reads the message, logs to db then deletes.

**Comment by kartikshah9** [comment]
@amnguye can you provide an update on the above

**Comment by wantedfast** [comment]
@takaz-ams 
We note that you get message from **ClicksQueue**, but try to delete this message in **ItemViewQueue**. This is wired.
The De-queue operation required get message and delete message from same queue.
Why do you de-queue in this way ?

**Comment by wantedfast** [comment]
@jongio

**Comment by takaz-ams** [comment]
> @takaz-ams
> We note that you get message from **ClicksQueue**, but try to delete this message in **ItemViewQueue**. This is wired.
> The De-queue operation required get message and delete message from same queue.
> Why do you de-queue in this way ?

@wantedfast you were right. Even though i have both queues, the first delete was attempting to delete from a different queue from which the message was read.

I wish it throw an exception or some sort of message when that happens

Thanks
