### ISSUE TITLE
[Storage][STG71] Rename BlobContainerProperties.DenyEncryptionScopeOverride 

### ISSUE THREAD

**Issue by seanmcc-msft** [Azure/azure-sdk-for-net#9192]
https://github.com/Azure/azure-sdk-for-net/pull/9190

Pending email discussion.

**Comment by blueww** [comment]
@seanmcc-msft 
Please add "Client" label for dataplane SDK. (As agreement before, we use "Client" label to differ dataplane SDK issue and SRP SDK issue)
We have a system to collect SRP SDK issues, the issues without "Client" label will be collect as SRP SDK issues.
Thanks!

**Comment by seanmcc-msft** [comment]
@blueww, sorry about that!
