### ISSUE TITLE
[BUG] Computer Vision: DomainModelResults.results is raw response

### ISSUE THREAD

**Issue by wiazur** [Azure/azure-sdk-for-net#9193]
**Describe the bug**
The DomainModelResults.results from the `AnalyzeImageByDomain()` API call returns raw results instead of object properties. The issue has been spelled out[ here](https://github.com/Azure-Samples/cognitive-services-dotnet-sdk-samples/issues/133). This is confusing for users who expect an SDK, not a REST model.

Suggestion: create a model for [DomainModelResults](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cognitiveservices.vision.computervision.models.domainmodelresults.result?view=azure-dotnet).

**To Reproduce**
Run the AnalyzeImageByDomain() API call, for instance in [this sample](https://github.com/Azure-Samples/cognitive-services-dotnet-sdk-samples/blob/master/samples/ComputerVision/RecognizeDomainSpecificContent/Program.cs).

**Expected behavior**
For `DomainModelResults.results` to return an object with properties such as:

```
results.Result.name - the name of the landmark or celebrity
results.Result.confidence - confidence of the correct name or face rectangle
results.Result.faceRectangle.width - gets the dimensions of the found face of a celebrity
```

**Setup**
 - OS: Windows 10
 - IDE : Visual Studio
 - Version of the Library used: both 5.0.0 and 6.0.0-dev.20190919.3

**Comment by JimSuplizio** [comment]
Hi @wiazur, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
