### ISSUE TITLE
Add editorconfig or stylecop rule to disallow multiple blank lines

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#9194]
We shouldn't have multiple blank lines between methods.

It would also be great if we can avoid having any blank lines between consecutive braces of the same direction (open or close), e.g., this shouldn't be allowed:
```
            }

        }
```

**Comment by weshaggard** [comment]
I don't have a problem with this rule.

**Comment by chidozieononiwu** [comment]
We have this rule enabled already. If you find an instance where this is not being applied feel free to open this issue again https://github.com/Azure/azure-sdk-for-net/blob/c4a711e96b17b4dc8743e69c8e34bdff3fa4d712/eng/CodeAnalysis.ruleset#L269
