### ISSUE TITLE
Add Blobs.ErrorCodes, Queues.ErrorCodes, DataLake.ErrorCodes, File.ErrorCodes to Constants.cs

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#9199]
We have Constants.ErrorCodes that contains cross-library error codes like InternalError/OperationTimedOut. We should look into standardizing this pattern so that we have Constants.Blobs.ErrorCodes/Constants.DataLake.ErrorCodes/etc.
Then we can go through and update any uses of hardcoded strings to use the constants, such as
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Files.DataLake/tests/FileClientTests.cs#L381

**Comment by tg-msft** [comment]
We should just remove the duplicate values in Constants.cs and rely on the public *ErrorCode classes.  Those get autogenerated with the latest values automatically and we won't have to patch up Constants.cs all the time by hand.

**Comment by JimSuplizio** [comment]
Hi @JoshLove-msft, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
