### ISSUE TITLE
Performance on Service Bus

### ISSUE THREAD

**Issue by masonyc** [Azure/azure-sdk-for-net#9200]
**Query/Question**
Hi, we are using Premium Service bus with 1 message unit and 80Gb data. 

In our logs, we found out Topic client’s SendAsync method takes about 1-2seconds to send out the message and Session Client’s ReceiveAsync method also takes about 1-2seconds to pull it down from Topic subscriber.

My question is, are there any way to reduce the time in these calls to milliseconds? The project I am working on requires real time performance. 

***Why is this not a Bug or a feature Request?***
Not sure if it is standard performance or I did some thing wrong in my code.

**Setup (please complete the following information if applicable):**
 - OS: Windows
 - IDE : VS 2019
 - Version of the Library used
 Microsoft.Azure.ServiceBus 4.1.1
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by jfggdl** [comment]
Thanks for your question. Would you please share the code snippet you are using for sending and receiving?

**Comment by nemakam** [comment]
@masonyc,
To start with, take a look at - https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-performance-improvements 

On the service side it should not take 1-2 seconds for a message. It generally is in the order of tens of ms. If you are facing long time, its either client-network round trip time, or time for other operations that are happening behind the scenes. The very first send/receive creates a new connection, and then a link on top of it to send. That might take its time. 
See if this time you are measuring is anomaly or is a general trend for every message. 
For receive(), one of the biggest boost is generally by enabling prefetch on the receiver.
Also, make sure the namespace is in the same region as the client machine which is calling in.

**Comment by masonyc** [comment]
@nemakam Thanks for the reply. The server side does not have much latency. I think the latency we are facing is getting the response from SendAsync Call. The first send call normally takes like 2 second, the followed calls are taking 1 second. We switched to session client for receiving message and now Receive Call is taking like 500ms.
![image](https://user-images.githubusercontent.com/18006944/71327747-35a8ab80-2571-11ea-9d10-a4dbf76a7561.png)

![image](https://user-images.githubusercontent.com/18006944/71327751-3f321380-2571-11ea-9ee4-60e6e15c0ec9.png)

First Call:
![image](https://user-images.githubusercontent.com/18006944/71327758-51ac4d00-2571-11ea-85ac-940e747a2e23.png)

Followed Call:
![image](https://user-images.githubusercontent.com/18006944/71327763-6092ff80-2571-11ea-9142-fed79b0c5494.png)

**Comment by masonyc** [comment]
Hi all, sorry it is me again. I have a .net core web API project that is calling Service Bus SDK to send messages in the middle of the API call.  I have a static class that initialize a Topic client at Startup. In my Integration Tests, first SendAsync call is a bit slow (1-2 seconds) but followed call are fast(within 100ms). This is ok as you mentioned above. But when I call the API manually via Postman, SendAsync method in every API call are taking (1-2 seconds). It seems like the topic client is not getting reused. Any ideas?

**Comment by nemakam** [comment]
@masonyc , unfortunately, there isn't a way in the client to do that. The first send() is when we create a connection and then create an AMQP link and then send the message. And these things take its time. 
You can hack and try and see if you can per-create the connection itself by reusing the connection for a different client and maybe calling a faux method which talks to service, but doesn't really harm you. Creating a link is something that you might not be able to avoid, but atleast, get the connection going.
I'm going to close this for now. Reopen if you need something else.
