### ISSUE TITLE
Add Application permission support for user_impersonation in Azure Service Management

### ISSUE THREAD

**Issue by lxf310** [Azure/azure-sdk-for-net#9203]
**Question**
To take use of Azure SDK via Azure App Registrations, only delegated permissions for user_impersonation is supported which means that a sign-in user is needed when taking use of those APIs and it reduces the capabilities to build up an automation application on it.

**Requirement**
It is obviously that the Application permission can provide the possibility to make related actions more automatically and support more meaningful and realistic use-cases. For example, in my case, I need to take use of this Azure SDK to create a register Bot automatically by a custom application.

**Comment by lxf310** [comment]
Hi team,

Is there any update?

Thanks

**Comment by shareonline** [comment]
I would also like to know of an update to this?

**Comment by lilyjma** [comment]
@antcp, @AzureAppServiceCLI, do we have any updates on this?
