### ISSUE TITLE
[BUG] BlobServiceClient with Blob level SAS Token Not Working

### ISSUE THREAD

**Issue by haresh93** [Azure/azure-sdk-for-net#9204]
**Describe the bug**
I am generating a Blob Level SAS token using user delegation with Azure Service Principal Credentials, and trying to upload a blob using SAS Token generated. I have followed exactly this code sample - https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/samples/Sample02_Auth.cs#L137 to generate the SAS Token.

The SAS Token is created and the Get Blob is working perfectly fine if i keep it in browser but using the BlobServiceClient if i am trying to upload the file or perform any action it is now working. To check if it is authenticated or not i have written this line await service.GetPropertiesAsync(); which is throwing the following error:

***Exception or Stack Trace***
```Unhandled exception. Azure.RequestFailedException: The resource doesn't support specified Http Verb.
RequestId:e87bd73d-201e-0050-2585-b5bd0f000000
Time:2019-12-18T09:29:07.8417147Z
Status: 405 (The resource doesn't support specified Http Verb.)

ErrorCode: UnsupportedHttpVerb

Headers:
Server: Microsoft-HTTPAPI/2.0
x-ms-request-id: e87bd73d-201e-0050-2585-b5bd0f000000
x-ms-client-request-id: 45789838-336b-4d66-8703-88b748b8e932
x-ms-error-code: UnsupportedHttpVerb
Date: Wed, 18 Dec 2019 09:29:06 GMT
Allow: PUT
Content-Length: 237
Content-Type: application/xml

   at Azure.Storage.Blobs.BlobRestClient.Service.GetPropertiesAsync_CreateResponse(Response response)
   at Azure.Storage.Blobs.BlobRestClient.Service.GetPropertiesAsync(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Uri resourceUri, Nullable`1 timeout, String requestId, Boolean async, String operationName, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobServiceClient.GetPropertiesInternal(Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobServiceClient.GetPropertiesAsync(CancellationToken cancellationToken)
   at StorageProvider.Storage.ObjectStorageProvider.GetTemporaryUploadCredentials(Settings storageProviderSettings, String containerName, String blobName, String requestorId, Int32 expirySeconds, Boolean withDownloadAccess, Boolean withDeleteAccess, CancellationToken cancellationToken) in /home/hanu/home/hanu/Development/dotnet/AzureStorageProvider/Storage/ObjectStorageProvider.cs:line 151
   at StorageProvider.Program.Main(String[] args) in /home/hanu/home/hanu/Development/dotnet/AzureStorageProvider/Program.cs:line 45
   at StorageProvider.Program.<Main>(String[] args)
```

**To Reproduce**

***Code Snippet***
```
string blobEndpoint = string.Format("https://{0}.blob.core.windows.net", storageProviderSettings.AccountName);

            TokenCredential credential =
                new ClientSecretCredential(
                    storageProviderSettings.TenantId,
                    storageProviderSettings.ClientId,
                    storageProviderSettings.ClientSecret,
                    new TokenCredentialOptions());

            BlobServiceClient blobServiceClient = new BlobServiceClient(new Uri(blobEndpoint),
                                                                credential);
            
            BlobContainerClient containerClient = blobServiceClient.GetBlobContainerClient(containerName);
            BlobClient blobClient = containerClient.GetBlobClient(blobName);

            var delegationKey = await blobServiceClient.GetUserDelegationKeyAsync(DateTimeOffset.UtcNow, DateTimeOffset.UtcNow.AddDays(7));
            BlobSasBuilder sasBuilder = new BlobSasBuilder()
            {
                BlobContainerName = containerName,
                BlobName = blobName,
                Resource = "b",
                StartsOn = DateTimeOffset.UtcNow,
                ExpiresOn = DateTimeOffset.UtcNow.AddSeconds(expirySeconds)
            };
            sasBuilder.SetPermissions(BlobSasPermissions.All);
            // if (withDownloadAccess) {
            //     sasBuilder.SetPermissions(BlobSasPermissions.Read);
            // }
            // if (withDeleteAccess) {
            //     sasBuilder.SetPermissions(BlobSasPermissions.Delete);
            // }
            Console.WriteLine(sasBuilder.Permissions);
            var sasQueryParams = sasBuilder.ToSasQueryParameters(delegationKey, storageProviderSettings.AccountName).ToString();
            UriBuilder sasUri = new UriBuilder()
            {
                Scheme = "https",
                Host = string.Format("{0}.blob.core.windows.net", storageProviderSettings.AccountName),
                Path = string.Format("{0}/{1}", containerName, blobName),
                Query = sasQueryParams
            };
            Console.WriteLine(sasUri.Uri.AbsoluteUri);

            BlobServiceClient service = new BlobServiceClient(sasUri.Uri);

            await service.GetPropertiesAsync();

            Settings tmpUploadCredentials = CreateTemporaryAzureStorageProviderSettings(sasUri, storageProviderSettings);

            Console.WriteLine(tmpUploadCredentials.ConnectionString);
            return tmpUploadCredentials;
```

**Setup (please complete the following information):**
 - Ubuntu 18.04
 - .NET Core 3
 - Azure.Storage.Blobs 12.1.0

**Comment by tg-msft** [comment]
That shouldn't work by design because you're creating a SAS scoped to a single blob (by setting `ContainerName`/`BlobName` of the `BlobSasBuilder`) and then trying to perform a service level operation.

Could you try creating a `new BlobClient` and call `GetPropertiesAsync` on that instead of the `BlobServiceClient` to see if you're able to successfully authenticate?

**Comment by haresh93** [comment]
Yes on `BlobClient` it worked, then the example shown in sample is wrong it may misguide many people, it has to be changed. 

And another thing can a SAS token be made on a folder so that files can be uploaded to the folder using the SAS token???

**Comment by tg-msft** [comment]
The sample you linked creates an account level SAS so it can perform service level operations like `BlobServiceClient.GetPropertiesAsync`.  You changed it to a single blob SAS and that's why the rest of the sample code was no longer relevant.  We'll work on adding more examples that walk through different SAS combinations and scenarios.

It depends what you mean by folders.  You can create a Container level SAS (using `BlobSasBuilder` and setting `BlobContainerName` while leaving `BlobName` empty) with permissions specific to the resources in that container.  Folders as you see in the Portal or via tools like AzCopy are just a blob naming convention and don't correspond to an actual service feature that you can target with a SAS.

**Comment by haresh93** [comment]
Basically we are using Azure data lake Storage Gen 2, our use case is to generate temporary credentials which grants access only to a folder as ADLS Gen 2 has manage access of a folder, we thought we could generate SAS token for it. 

Pl confirm if it is possible to do with SAS or can you suggest something to serve this use case??

**Comment by tg-msft** [comment]
+@seanmcc-msft for questions about DataLake

**Comment by haresh93** [comment]
@tg-msft Can you confirm if i can generate a short lived service principal like for a fixed time which expires after that time ??

**Comment by haresh93** [comment]
HI @seanmcc-msft, can you help me in this??

**Comment by amnguye** [comment]
If you are trying to access an Azure DataLake Directory(folder), shouldn't you be using a DataLakeDirectoryClient instead of a BlobClient?

**Comment by haresh93** [comment]
@amnguye Actually BlobClient is also creating folders automatically if there is a  `/` in the name of the blob, that is not a problem. Are you saying that If i use DataLakeDirectoryClient then can i grant access only to that directory somehow???

**Comment by tg-msft** [comment]
There's a [`DataLakeSasBuilder.Path`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Files.DataLake/src/Sas/DataLakeSasBuilder.cs#L84) property that looks like it would, but I'll let @seanmcc-msft and @amnguye give you advice on the correct pattern to use here.

**Comment by haresh93** [comment]
@tg-msft I have created a SAS token for a directory with path as `folder1/` and tried to upload a file to it using `az storage blob upload -f <fileName> -c <containerName> -n folder1/file1.png --account-name <accountName> --sas-token <sasToken>`, it is giving the following error `You do not have the required permissions needed to perform this operation.`. Same thing is working if it is a blob.

**Comment by seanmcc-msft** [comment]
Hi @haresh93,  I don't think SAS authentication understands the concept of hierarchical namespace, so generating as SAS token for ```folder1/``` won't allow you to create files within it.

I recommend you remove the ```BlobName``` property from your BlobSasBuilder, and generate a SAS for the entire container.

**Comment by haresh93** [comment]
@seanmcc-msft If not SAS, is there any other method available in Azure which gives folder level access and can expire in 24 Hrs or something, the usecase is that we would be giving the credentials to the user hence giving a container level access doesn't work. 

The point here is the credentials that we are giving to the user should be temporary (for 24 hrs) and scope should be only for a particular folder. Is there any way in Azure??

**Comment by seanmcc-msft** [comment]
@haresh93, one option would be to set the the ACLs on directory to allow a user's access, and then remove the user's access after 24 hours.  You can programmatically set a directory's ACL using the [.NET DataLake SDK](https://www.nuget.org/packages/Azure.Storage.Files.DataLake/12.0.0-preview.7) that we have in preview.  DataLakeDirectoryClient or DataLakePathClient.SetAccessControlList().
