### ISSUE TITLE
[FEATURE REQ] Support progress handler for BlobClient.DownloadTo API

### ISSUE THREAD

**Issue by sam-piper** [Azure/azure-sdk-for-net#9216]
**Is your feature request related to a problem? Please describe.**
BlobClient supports specifying a progress handler when uploading, although this is currently unusable for multi-part uploads on large blobs because the progress value is not normalized for the entire blob (see #9180). However, there is currently no progress handler support for downloading at all.

**Describe the solution you'd like**
Working with large files for both upload and download in a typical UI requires symmetric feature support, of which progress reporting is one. It would be great if we could just pass an `IProgress<T>` implementation directly to `BlobClient.DownloadToAsync()`, and know that it would behave in the same manner as uploading, with a single line of code, for both single-part and multi-part uploads. 

**Describe alternatives you've considered**
We could implement this manually using the previous SDK version, which has a lot more guidance available on the web, but it looks like a lot more work as well and there is much more potential for usage errors on our side.

**Comment by tg-msft** [comment]
Thanks for reporting this!  It's a known issue being tracked by #8506.
