### ISSUE TITLE
When will the HDInsight 3.0 be released?

### ISSUE THREAD

**Issue by mikeblakeuk** [Azure/azure-sdk-for-net#9219]
**Query/Question**
When will latest Microsoft Azure HDInsight Job Library be on NuGet?

***Why is this not a Bug or a feature Request?***
I assume someone need to publish the NuGet package. Preview is fine.

**Setup (please complete the following information if applicable):**
 - OS: Windows
 - IDE : Visual Studio 2019
 - Version of the Library used
We are currently looking to remove our **Hyak.Common** dependencies.
We are using Microsoft.Azure.Management.HDInsight 2.0.6 
and Microsoft.Azure.Management.HDInsight.Job 2.0.7
 
 **Information Checklist**
- [x] Query Added
- [x] Setup information Added

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/hdinsight/Microsoft.Azure.HDInsight.Job/src/Microsoft.Azure.HDInsight.Job.csproj#L8

**Comment by aim-for-better** [comment]
The  ETA is the end of July.
