### ISSUE TITLE
[QUERY] Not clear on how to create Application Insights using the SDK

### ISSUE THREAD

**Issue by carsontwilson** [Azure/azure-sdk-for-net#9226]
**Query/Question**
I have many web applications I need to enable app insights for and am trying to script it out. I see examples for this on az / powershell but not for the SDK. I'm assuming this is possible but it's still not clear.

When I access the Azure interface I don't see any references to application insights that I can use. Is this possible, and if so how?

***Why is this not a Bug or a feature Request?***
It's a how to question - but I'm not sure if it's possible. If not, then it's a feature request :)

**Setup (please complete the following information if applicable):**
 - OS: Windows 10 Pro
 - IDE : VS 2019
 - 1.29 Fluent
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by yaohaizh** [comment]
Duplicate with #https://github.com/Azure/azure-libraries-for-net/issues/27. Please track the issue on the dependency one. Thanks.

**Comment by jongio** [comment]
@carsontwilson 

You can use this SDK: https://www.nuget.org/packages/Microsoft.Azure.Management.ApplicationInsights/0.2.0-preview

The code is here: https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/applicationinsights

The management plane SDKs are mostly generated by AutoREST.

That version doesn't (yet) support the new Azure Identity SDK, so I created a bridge for you here: 

https://github.com/jongio/azidext

This test: https://github.com/jongio/azidext/blob/master/net/JonGallant.Azure.Identity.Extensions.Tests/AppInsightsTests.cs shows you how to create an app insights resource

Please have a look and let me know if this solves your problem. 

Thanks,
Jon

**Comment by jongio** [comment]
@yaohaizh - I reopened this because it isn't really a dupe.  This one is about using the SDK and the other one is about the Fluent SDK in a differnet repo so it is two different efforts.  Let's use this thread to help Carson figure out how to use the existing API.

**Comment by wantedfast** [comment]
@carsontwilson 
How is this issue going? Feel free to let us know if further help is needed.

**Comment by carsontwilson** [comment]
Hi there,

Thank you _so_ much for the assistance on this, I really appreciate it! I'm in the middle of week long company wide meetings and another project - but my plan is to get back to this next week, will update then. Thanks again :)

**Comment by ZenoArrow** [comment]
@jongio Thank you for that information, it should be useful to cover for the missing Application Insights functionality in the Fluent SDK library. Just FYI, the link to the test didn't work for me, though I still found your code by searching for it. This link works for me: https://github.com/jongio/azidext/blob/01fd83ad7da2a6f82101ae0fd856b9a7b672f756/net/JonGallant.Azure.Identity.Extensions.Tests/Mgmt/AppInsightsTests.cs

**Comment by jongio** [comment]
Thanks for letting me know.  I put the tests in a subfolder after I made the comment.  I corrected the link above too.

Please let me know if you run into any issues.

**Comment by jongio** [comment]
@carsontwilson - Did you get this working?

**Comment by tzhanl** [comment]
@carsontwilson  We are going to close this issue because we haven’t heard from you in a few days, but please re-open it if the issue still persists.
