### ISSUE TITLE
Address gaps in Event Processor test coverage

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#9227]
## Issue

The `Azure.Messaging.EventHubs.Processor` package is lacking in test coverage. There are already multiple tests, but they are not enough to ensure proper behavior.

## Goal

Tests for the following scenarios need to be added:
- [x] A `CancellationToken` that has already been cancelled makes `StartProcessingAsync` and `StopProcessingAsync` throw a `TaskCanceledException` (include tests for synchronous methods as well).
- [x] `StartProcessing` and `StopProcessing` synchronous implementations should still start and stop the processor successfully (it should be enough to assert they delegate to the asynchronous implementations. Useful for the previous item as well).
- [x] `StartProcessingAsync` should take no action when processor has already started and hasn't been explicitly stopped. `StopProcessingAsync` should take no action when processor hasn't been started / has already stopped (however, `StopProcessingAsync` resets state when load balancing task is not running because of a failure).
- [x] Processor should allow starting / stopping / starting again.
- [x] ~Processor should be able to recover from a disconnection~ Simulating a disconnection would be difficult without injecting at the AMQP level. It's not worth it given that the processor would deal with it like any other consumer exception.
- [x] `StopProcessingAsync` should surface any load balancing exceptions.
- [x] `StopProcessingAsync` should stop processing for every partition the processor owns and invoke the close handler for each one of them (with reason = `Shutdown`). We need to somehow verify that processing is not taking place anymore. Simply checking the stop handler wouldn't be enough.
- [x] `ToString` should return a string that contains the processor's identifier.
- [x] The processor should renew its ownership every cycle.
- [x] Error handler should be triggered when ownership renewal has failed (make sure there is no partition id).
- [x] The processor should stop processing partitions it doesn't own anymore. Ensure the close handler is called with `OwnershipLost` reason as well.
- [x] The processor should restart processing partitions whose processing tasks have failed (except when the failure has been triggered by user code: #9228). Ensure the close handler is called with `OwnershipLost` reason and the init handler has been called for this same partition. Error handler should be called with the appropriate partition id as well.
- [x] The error handler should be triggered with no partition id when ownership list retrieval from the `StorageManager` fails.
- [x] The error handler should be triggered with no partition id when partitions list retrieval fails.
- [x] The init handler should be triggered with the correct partition id when a new ownership is claimed.
- [x] The error handler should be triggered with the correct partition id when a call to `ListCheckpointAsync` in the `StorageManager` fails. This happens only when starting the processing of a partition.
- [x] Even in case a shutdown has been requested, stopping the processing of a partition should trigger the stop handler with reason = `OwnershipLost` if the processing task has coincidentally failed (properly coordinating the timing is important in this test). We are basically testing this piece of code:
https://github.com/Azure/azure-sdk-for-net/blob/f234423f8615ea1934e5af042589799a82fd6e49/sdk/eventhub/Azure.Messaging.EventHubs.Processor/src/EventProcessorClient.cs#L1294-L1296
- [x] The error handler should be triggered with the correct partition id when a new ownership claim has failed. This test will fail because the current code mistakenly passes a null partition id:
https://github.com/Azure/azure-sdk-for-net/blob/f234423f8615ea1934e5af042589799a82fd6e49/sdk/eventhub/Azure.Messaging.EventHubs.Processor/src/EventProcessorClient.cs#L1358
- [x] An exception thrown by `StorageManager.ClaimOwnershipAsync` while relinquishing ownership should not trigger the error handler and be surfaced to the user.
- [x] When processing a partition, the process handler should be called once for every received event.
- [x] When a maximum wait time is not specified in the options, the process handler should not be triggered while events are not being received. It should be periodically triggered with a `null` partition context otherwise. Edit: partially solved by `ProcessEventAsyncReceivesAnEmptyPartitionContextForNoData`. A new test will be included.
- [x] When triggered with no data, `ProcessEventArgs.UpdateCheckpointAsync` throws an `InvalidOperationException`.
- [x] Calling `ProcessEventArgs.UpdateCheckpointAsync` with a canceled token should throw a `TaskCanceledException`.
- [x] `ProcessEventArgs.UpdateCheckpointAsync` surfaces the exception when `StorageManager.UpdateCheckpointAsync` throws. It would be nice to assert it does not call the error handler as well.
- [x] Throwing from ~any handler~ initialize or process handler should bubble the exception up and make the processor stop working. ~We should include tests for every possible error handler call, even though it's a bit overwhelming~. Currently this will fail for the process handler (tracked by #9228).
- [x] When processing is requested to stop, every handler still in execution should have its `CancellationToken` canceled.
- [x] Constructor test (include tests for both constructors): `RetryPolicy` should be passed to the `BlobsCheckpointStore` constructor.
- [x] `BlobsCheckpointStore` methods should throw a `TaskCanceledException` when cancellation has been requested before calling them.
- [x] `BlobsCheckpointStore` calls to the Storage SDK should delegate the `RetryPolicy` and the `CancellationToken`.
- [x] Publish a set of events and then process them, creating a checkpoint for the last event.   Create a new processor and begin processing.  No exception should occur.  Publish a set of events and verify that only these new events are seen by the second processor.

**Comment by jsquire** [comment]
Added an additional scenario for resuming from a checkpoint that corresponds to the last event in a stream.
