### ISSUE TITLE
[EventHubs] Event Processor Client should surface exceptions thrown by the Process Event handler

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#9228]
## Summary

By design, the `EventProcessorClient` expects code provided by the user to not throw. In case this situation arises, the thrown exception should not be captured by the processor and should be bubbled up to the user, completely stopping the client.

User code is present in 4 handlers: `PartitionInitializingAsync`, `PartitionClosingAsync`, `ProcessEventAsync` and `ProcessErrorAsync`, which are called via the `On<handler-name>` methods in the `EventProcessorClient` class. For instance:
https://github.com/Azure/azure-sdk-for-net/blob/f234423f8615ea1934e5af042589799a82fd6e49/sdk/eventhub/Azure.Messaging.EventHubs.Processor/src/EventProcessorClient.cs#L902-L908

## Issue

The only call to `OnProcessEventAsync` in the processor happens in the `RunPartitionProcessingAsync` method.

https://github.com/Azure/azure-sdk-for-net/blob/f234423f8615ea1934e5af042589799a82fd6e49/sdk/eventhub/Azure.Messaging.EventHubs.Processor/src/EventProcessorClient.cs#L860

Multiple calls to this method run in parallel, one for each owned partition. We hold a `Dictionary` to keep track of the partition processing tasks.

https://github.com/Azure/azure-sdk-for-net/blob/f234423f8615ea1934e5af042589799a82fd6e49/sdk/eventhub/Azure.Messaging.EventHubs.Processor/src/EventProcessorClient.cs#L1250-L1253

However, when one of these tasks fail, we forcefully await them, catch the thrown exception and delegate it to the `ProcessErrorAsync` handler.

https://github.com/Azure/azure-sdk-for-net/blob/f234423f8615ea1934e5af042589799a82fd6e49/sdk/eventhub/Azure.Messaging.EventHubs.Processor/src/EventProcessorClient.cs#L1273-L1292

## Goal

We should be able to differentiate between exceptions thrown by user code and errors thrown by the client code in the scope of the `RunPartitionProcessingAsync` method. When catching these, anything thrown by the user should **not** trigger the `ProcessErrorAsync` handler and bubble up to stop the load balancing task. This exception should be retrieved when calling `EventProcessorClient.StopProcessingAsync`.

Tests are being tracked by the following issue: #9227. For this reason, they are not mandatory to close this one.

**Comment by jsquire** [comment]
This item is no longer valid, with the transition of the client as a subtype of `EventProcessor<T>`
