### ISSUE TITLE
ConnectWithManagedIdentity is not working after upgrading to 3.0

### ISSUE THREAD

**Issue by klogan12** [Azure/azure-sdk-for-net#9229]
**Describe the bug**
ConnectWithManagedIdentity is not working after upgrading to 3.0

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
Follow below doc , but looks like ConnectWithManagedIdentity  got removed.
https://docs.microsoft.com/en-us/azure/azure-app-configuration/howto-integrate-azure-managed-service-identity

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by wantedfast** [comment]
According the [release notes,](https://github.com/Azure/AppConfiguration/blob/master/releaseNotes/MicrosoftExtensionsConfigurationAzureAppConfiguration.md#300-preview-010550001-251---november-22-2019) **ConnectWithManagedIdentity()** method was removed in 3.0.0 to connect the App Configuration store using system-assigned managed identity currently. And it replaced as **Connect()** method.

Before:
`IConfigurationBuilder configBuilder = new ConfigurationBuilder();
IConfiguration configuration = configBuilder.AddAzureAppConfiguration(options => {
   options.ConnectWithManagedIdentity(endpoint);
}).Build();`

After
`IConfigurationBuilder configBuilder = new ConfigurationBuilder();
IConfiguration configuration = configBuilder.AddAzureAppConfiguration(options => {
   options.Connect(endpoint, new ManagedIdentityCredential());
}).Build();`

**Comment by wantedfast** [comment]
@jongio

**Comment by klogan12** [comment]
worked!
