### ISSUE TITLE
[Text Analytics] Inconsistent Input Error Handling (v1.0.0-preview.1)

### ISSUE THREAD

**Issue by assafi** [Azure/azure-sdk-for-net#9240]
It's possible this issue will be addressed in #8864 which is rather generic, so opening a dedicated issue for this.

Seems some invalid inputs are inconsistent in their error handling.

For example:

```csharp
var response = client.AnalyzeSentiment(" "); // Will issue a request to the service and will throw a RequestFailedException with a 200 status code and "Invalid document in request." message.
```

however, 

```csharp
var response = client.AnalyzeSentiment(""); // Will throw immediately with ArgumentException
```

This can be problematic if inputs are coming from an external source for example, requiring different error handling.

**Comment by assafi** [comment]
@annelo-msft

**Comment by assafi** [comment]
FWIW, I think it's fine to do error validation on the client, but it should throw the same error as the service. So perhaps it would be easier to just not do it.

**Comment by maririos** [comment]
Reading the [.NET guidelines](https://azure.github.io/azure-sdk/dotnet_introduction.html#parameter-validation) seems like we shouldn't do the validation for `client.AnalyzeSentiment("")`.

@KrzysztofCwalina I see this happening in other services, like KV, which already GA so not sure what to choose for TA. Could you provide some guidance here?

**Comment by KrzysztofCwalina** [comment]
The guidance is a bit unclear here, but the way I understand it:
1. We should not be validating ranges of values on the client.
2. We should make sure that the document we send is formed correctly.

In this particular case, I think we could go either way, but I do agree with @assafi that we should be consistent.

cc: @johanste

**Comment by johanste** [comment]
I agree with @KrzysztofCwalina on the understanding of the guidance. For this particular method, I would probably lean towards letting the service do the validation.

- I would generally expect the caller to be able to test the inputs to avoid the exception. The more complicated we make the logic to validate the inputs, the less likely that is (and while stripping out whitespace is not that complicated in most languages, it more than doubles the complexity compared to just a non-zero-length check)
- There are still scenarios where the input is invalid and the client cannot verify it. Which means that I now have two different error paths on the client; one for things the client can verify and a second for anything that slipped through all the way to the service.

**Comment by maririos** [comment]
Thanks @KrzysztofCwalina and @johanste for the input.
For TA case, then I will work on consistency between server and client by letting the service do the validation, unless the client requires/modifies the parameter.

**Comment by maririos** [comment]
PR with changes and tests: https://github.com/Azure/azure-sdk-for-net/pull/9486
