### ISSUE TITLE
[Text Analytics] TextSentiment contains Offset and Length (v1.0.0-preview.1)

### ISSUE THREAD

**Issue by assafi** [Azure/azure-sdk-for-net#9241]
`TextSentiment` type contains Offset and Length properties that are not being used and are not supported by the service API. These properties are relevant only for `SentenceSentiment` scope, but not for the document scope.

![image](https://user-images.githubusercontent.com/1440860/71385285-5ab21400-259b-11ea-9767-a6507e5b5da3.png)

**Comment by assafi** [comment]
@annelo-msft

**Comment by assafi** [comment]
FWIW, while it's possible to just sum up all of the document lengths for example, there are some edge cases (e.g. "blah.   " -> will contain only one sentence of length 5) where the sum of sentences is not equal to the document length. Also, I can't think of a case where the offset will not be set to 0.

**Comment by maririos** [comment]
Thanks @assafi . This has been fixed in Preview 2
