### ISSUE TITLE
[Text Analytics] RequestFailedException makes AnalyzeSentimentResult.ErrorMessage obsolete

### ISSUE THREAD

**Issue by assafi** [Azure/azure-sdk-for-net#9242]
Might be addressed in #8864 

In the case of a single input an input error results in a `RequestFailedException` so the `AnalyzeSentimentResult.ErrorMessage` is never actually used. 

```csharp
            var client = new TextAnalyticsClient(new Uri(endpoint), key);
            try
            {
                var response = client.AnalyzeSentiment("  I had the best day of my life. I wish you were there with me. ");
                if (response.Value.ErrorMessage != default)
                {
                    // This will never happen, because the RequestFailedException will be thrown
                }
                
                // Handle successful response
            }
            catch (RequestFailedException rfe)
            {
                Console.Error.WriteLine(rfe.ErrorCode);
            }
```

**Comment by assafi** [comment]
@annelo-msft

**Comment by annelo-msft** [comment]
@assafi, that is correct.  ErrorMessage (which we'll be changing to a strongly typed error class) is still useful when it comes back in a batch result.  The exception in the case of a single result will still have all the information from the TextAnalyticsError type and inner errors.  So in your sample, you'd remove the block that checks the error code.

>                 if (response.Value.ErrorMessage != default)
>                 {
>                     // This will never happen, because the RequestFailedException will be thrown
>                 }

Is there a concern about this that I'm missing?

**Comment by maririos** [comment]
We implemented what @annelo-msft is mentioning in P2. 
@assafi please let us know if there are still concerns in this area

**Comment by maririos** [comment]
Closing for now. 
@assafi please re-open if there are concerns with our approach
