### ISSUE TITLE
[Text Analytics] Singular response types missing request level property ModelVersion (v1.0.0-preview.1)

### ISSUE THREAD

**Issue by assafi** [Azure/azure-sdk-for-net#9243]
The singular (i.e. non-batch) response types appear to be missing the request level property `ModelVersion`. 

For example, `AnalyzeSentimentResult` returned by `TextAnalyticsClient.AnalyzeSentiment(string inputText, string language = null, CancellationToken cancellationToken = default)` does not contain a `ModelVersion` property. This is true for other singular response types like `DetectLanguageResult`.

**Comment by assafi** [comment]
@annelo-msft

**Comment by maririos** [comment]
As we were thinking on leaving the singular methods as simple as possible, we don't have that possibility. For batch methods though, we do allow it.

Do you think we should revisit this decision?

**Comment by assafi** [comment]
I do, depending on the cost of course. Unfortunately, a very common pattern we see is customers start with the simple calls, and never optimize with batch. So I would say we still need that level of detail. Having said that, if it's too much work or makes other things uglier it's probably not worth it.

**Comment by maririos** [comment]
Thanks! I will look into it

**Comment by maririos** [comment]
@assafi so I took a look and because for single document input we are returning atomic types, we don't have the ability to return statistics.
i.e. `Response<IReadOnlyCollection<LinkedEntity>> response = client.RecognizeLinkedEntities(input);`

**Comment by maririos** [comment]
Currently our single document method looks like this:
`RecognizeLinkedEntities(string inputText, string language = default)`

If we add model version, it will be another `default` parameter:
`RecognizeLinkedEntities(string inputText, string language = default, string modelVersion)`
Although it will work in .NET, for Java it implies that we need to create a method overload:
```
`RecognizeLinkedEntities(string inputText, string language = default, string modelVersion)`

**Comment by assafi** [comment]
@maririos we expect very few customers will use modelVersion. In addition, most likely this will be a client-wide setting and not something that will change for each call. 
I think it's safe to move it to the requests options and/or client options type.

**Comment by maririos** [comment]
>I think it's safe to move it to the requests options and/or client options type.

We currently have it in the request options, which is only available for the batch methods for .NET and Java.

>and/or client options type.

Interesting! I wonder what/if it was decided to leave it in the request options instead of client options. I created issue https://github.com/Azure/azure-sdk-for-net/issues/10493 to follow up on that

**Comment by annelo-msft** [comment]
Is it possible different model versions would be specified for different models? (i.e. one version for language detection, one for entity extraction, etc.)  IIRC, this is why we allowed it to be specified per call, and not on client options.  I agree it probably only needs to be set once per client instantiation (I defer to @assafi on the business requirement from customers).  If it was on client options, would we need a model version for each different type?

**Comment by maririos** [comment]
Thanks for the context Anne!

**Comment by assafi** [comment]
Good suggestion. Safe answer is "we don't know". I think it's always possible for customers to instantiate a new client for these advance scenarios. 
If I had to choose, I would opt for simplicity (e.g having it as a single setting in client/request options) and wait to hear users feedback before making the change.

**Comment by maririos** [comment]
Will leave as it is for now. 
If we receive feedback from users that suggest they need model version on the client level, then we will adjust.
