### ISSUE TITLE
Mark recordings as generated in git

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#9253]
To improve PR experience.
See https://github.com/Azure/azure-sdk-for-js/pull/6701/files

**Comment by kurtzeborn** [comment]
@pakrym what's the goal that would be accomplished by using `linguist-generated=true`?  Would it be to hide these files from PR diffs or something else?

**Comment by pakrym** [comment]
You can see the effect here: https://github.com/Azure/autorest.csharp/pull/408/files

![image](https://user-images.githubusercontent.com/1697911/72567414-b609b600-386a-11ea-9e50-0b900fe5d0b5.png)

**Comment by pakrym** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-net/pull/9511
