### ISSUE TITLE
CloudContext.Clients.CreateManagementClient(credentials) Not Found

### ISSUE THREAD

**Issue by davihar** [Azure/azure-sdk-for-net#927]
After upgrading to 2.0 calls like CloudContext.Clients.CreateManagementClient(credentials) are not compiling.  Did it move?  Thanks.

**Comment by matt-gibbs** [comment]
This was removed in the major version update.
Please use the constructor of the specific management client, i.e. var client = new ManagementClient(credentials)...

**Comment by pjirsa** [comment]
using the constructor gives invalid parameter errors
