### ISSUE TITLE
singleUploadThreshold parameter not publicly exposed

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#9277]
Internal method BlobClient.StagedUploadAsync has a parameter called singleUploadThreshold that can be set to determine the max size stream that can be uploaded as a single block. This parameter is currently only used by test code that calls directly into StagedUploadAsync. 

If we want to expose this option, we should add it to the relevant public APIs. If not, we should consider whether it is worth keeping in product code at all. Also, this seems very similar to the already exposed StorageTransferOptions.MaximumTransferLength property, so I wonder if we could just use this property in our implementation rather than singleUploadThreshold. Currently, MaximumTransferLength is only used for parallel uploads, and whether or not the upload will be in parallel is determined by whether the size is less than 256MB.

**Comment by tg-msft** [comment]
`singleUploadThreshold` (the cutoff for staging vs. uploading in one shot) and `MaximumTransferLength` (the size of staged blocks) need different values tuned for perf.  We can consider exposing it if there are customer scenarios.

**Comment by JoshLove-msft** [comment]
Is it misleading that `MaximumTransferLength` would be ignored if the file size is less than 256MB?

**Comment by tg-msft** [comment]
Maybe, but I feel like anybody who plays around with `StorageTransferOptions` will have figured out that uploads are staged in blocks so it's not an insurmountably bad name.

**Comment by amnguye** [comment]
`StorageTransferOptions.InitialTransferSize` has already been added.
