### ISSUE TITLE
[BUG] Service Bus - ManagementClient GetRulesAsync not returning expected rules

### ISSUE THREAD

**Issue by danielcirket** [Azure/azure-sdk-for-net#9279]
**Describe the bug**
Service Bus Mangement Client. `GetRulesAsync(topicName, subscriptionName, count: pageSize);` does not return more than 25 items, despite supplying a count of 50 or the default of 100.

***Exception or Stack Trace***
N/A

**To Reproduce**
1. Create a topic
2. Add a subscription
3. In a loop, add 50 rules to the subscription
4. Call `GetRulesAsync`, only 25 are returned.

***Code Snippet***
```c#
var ruleCount = 50;
var client = new ManagementClient(...);

Func<Task> setup = async () =>
{
    await client.CreateTopicAsync(_topicName);
    await client.CreateSubscriptionAsync(_topicName, _subscriptionName);
    await client.RemoveRuleAsync(_topicName, _subscriptionName, RuleDescription.DefaultRuleName);

    for (var i = 0; i < ruleCount; i++)
    {
        await client.CreateRuleAsync($"{nameof(SampleEvent)}_{i}", _subscriptionName, _topicName);
    }
};

setup.Should().NotThrow();

Func<Task> verify = async () =>
{ 
    var rules = await client.GetRulesAsync(_topicName, _subscriptionName);

    rules.Should().HaveCount(ruleCount);
    rules.Should().OnlyContain(r => r.Rule.StartsWith($"{nameof(SampleEvent)}_"));
};

verify.Should().NotThrow();
```

**Expected behavior**
For rule counts of 100 or less then all rules should be returned rather than be truncated at 25.

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: WIndows 10 / Ubuntu
 - IDE : VS 2019 16.5 
 - Version of the Library used **4.1.1**

**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by SeanFeldman** [comment]
This is a server-side issue and was already raised earlier [here](https://github.com/Azure/azure-service-bus-dotnet/issues/581).

Raised an issue with the server-side repo: https://github.com/Azure/azure-service-bus/issues/330

**Comment by nemakam** [comment]
@danielcirket , this issue is in the backlog. We will take a look at it.

**Comment by 3437CasaVerde** [comment]
@danielcirket Hi Dan, we rolled out a deployment to fix this issue recently. Could you verify if it's fixed on your end? Default count should be 100.

**Comment by danielcirket** [comment]
Appears to be fixed @3437CasaVerde, thanks
