### ISSUE TITLE
StorageAccountCreateParameters GeoReplicationEnabled Missing

### ISSUE THREAD

**Issue by davihar** [Azure/azure-sdk-for-net#928]
After upgrading to 2.0 the GeoReplicationEnabled property is missing.  How is replication now specified for storage accounts?  Thanks

**Comment by markcowl** [comment]
This is by design.  The new storage management API now has different levels of storage account redundancy for different account types.  See: https://msdn.microsoft.com/en-us/library/azure/dn727290.aspx
