### ISSUE TITLE
[QUERY] Missing App Insights dependency Telemetry with netcore3 console app plus Microsoft.Azure.EventHubs client

### ISSUE THREAD

**Issue by bengimblett** [Azure/azure-sdk-for-net#9280]
**Query/Question**
Why when using a netcore console app (netcoreapp3.0) to send events to eventhub
"Microsoft.Azure.EventHubs" Version="4.1.0"  using instance of EventHubClient->SendAsync()
And using App Insights to track the event
"Microsoft.ApplicationInsights.DependencyCollector" Version="2.11.2"  initialised in code on console app start 
Do i not see AEH dependency item generated for the event send to the EventHub.

This is expected. If i deploy a simple Az function (pointed to App Insights) to do the same, it does generate the correct App insights dependency telemetry item for the [AEH] event send.

Is the development team aware of any issues with generating AI dependency events from the AEH netcore compat. SDK in this scenario (netcore v3 console app)?

***Why is this not a Bug or a feature Request?***
I may have mis-configured AI SDK. Therefore this may not be a bug.
It is not a feature request because the functionality should work.

**Setup (please complete the following information if applicable):**
 - OS: W10
 - IDE :\ Visual Studio Code latest
 - netcoreapp3 console app with "Microsoft.Azure.EventHubs" Version="4.1.0" 
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Query Added
- [ x] Setup information Added

**Comment by bengimblett** [comment]
The exception event from perfview was stripped
Event MSec=  "2381.5616" PID="14516" PName="egconsole" TID="11260" EventName="EventWriteString" ProviderName="Microsoft-Azure-EventHubs" FormattedMessage="ERROR: Exception in Command Processing for EventSource Microsoft-Azure-EventHubs: Unsupported type Exception in event source." message="ERROR: Exception in Command Processing for EventSource Microsoft-Azure-EventHubs: Unsupported type Exception in event source."

**Comment by bengimblett** [comment]
I am getting confused with exactly the mechanisms used here
AI Dependency module doc (https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-dependencies) says 3 methods are used 
(1) the instrumentation profiler 
(2) tracesource 
(3) diagnosticsource. (For sharing rich events in context)

And it's the last I should be looking at

I can see EventHubs SDK does write out events through a diagnosticsource named "Microsoft.Azure.EventHubs"
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Microsoft.Azure.EventHubs/src/EventHubsDiagnosticSource.cs

And AI should be consuming those events
https://github.com/microsoft/ApplicationInsights-dotnet/blob/20cf6bbf7224345934c71d9d703558df32463a85/WEB/Src/DependencyCollector/Shared/Implementation/EventHandlers/EventHubsDiagnosticsEventHandler.cs
Writing out a dependency through TelemetryClient

The question stands - i have now tested a couple more netcoreapp scenarios using the AEH SDK
Summary:
Console App  ---  no AEH dependency items
Web API --- no AEH dependency items
Web API hosted as Az WebApp ---- no AEH dependency items
Az Function (EventHub event send -> output binding) ----AEH dependency is observed

**Comment by lmolkova** [comment]
I believe you've hit https://github.com/microsoft/ApplicationInsights-dotnet/issues/1317. Please try updating ApplicationInsigths packages to 2.12 everywhere except Function apps.

**Comment by jsquire** [comment]
//cc: @serkantkaraca, @JamesBirdsall

**Comment by serkantkaraca** [comment]
AI 2.12 SDK handles shorted activity names as @lmolkova pointed. Let us know if you still hit the issue.

**Comment by bengimblett** [comment]
perfect v latest solved issue.
