### ISSUE TITLE
How to mock value returned by BlobClient.UploadAsync

### ISSUE THREAD

**Issue by Jericho** [Azure/azure-sdk-for-net#9283]
**Query/Question**
I wrote as class that is injected a `BlobClient` dependency and I am writing unit tests to ensure my class behaves as it should. In one instance, my class invokes the `UploadAsync` and therefore I want to mock the invocation of this method in order to test several scenarios (such as: upload successful, upload failed due to missing blob, etc.).

The `UploadAsync` method returns an object of type `Response<BlobContentInfo>` but the properties on the `BlobContentInfo` class are read-only and furthermore, the class does not have a parameter-less constructor. This means that I can't see a way to mock the value returned by this method.

**Code sample**
Here's a simplified version of my class:
```csharp
public class Foo
    private readonly BlobClient _blobClient;

    public Foo(BlobClient blobClient)
    {
        _blobClient = blobClient;
    }

    public async Task Bar(CancellationToken cancellationToken)
    {
        var response = await _blobClient.Upload(...).ConfigureAwait(false);
        ... snip ...
    }
}
```

Here's an example of a unit test:
```csharp
[Fact]
public async Task MyUnitTest()
{
    // Arrange
    var cancellationToken = CancellationToken.None;

    var mockBlob = new Mock<BlobClient>(MockBehavior.Strict, new Uri(BLOB_ITEM_URL), (BlobClientOptions)null);
    mockBlob
        .Setup(c => c.UploadAsync(It.IsAny<Stream>(), It.IsAny<BlobHttpHeaders>(), It.IsAny<IDictionary<string, string>>(), It.IsAny<BlobRequestConditions>(), It.IsAny<IProgress<long>>(), It.IsAny<AccessTier>(), It.IsAny<StorageTransferOptions>(), cancellationToken))
        .ReturnsAsync(Response.FromValue(new BlobContentInfo()))
        .Verifiable();

    var foo = new Foo(mockBlob.Object);

    // Act
    await foo.Bar(cancellationToken).ConfigureAwait(false);

    // Assert
    mockBlob.Verify();
}
```

This unit test does not compile. Visual Studio complains that `CS1729 'BlobContentInfo' does not contain a constructor that takes 0 arguments`.

***Why is this not a Bug or a feature Request?***
Maybe there is an alternative that I am not aware of?

**Setup (please complete the following information if applicable):**
 - OS: Windows 10
 - IDE : Visual Studio 2019
 - Version of the Library used: 12.1
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by pakrym** [comment]
There is a factory method available for mocking purposes: https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.models.blobsmodelfactory.blobcontentinfo?view=azure-dotnet

**Comment by Jericho** [comment]
Exactly what I needed! Thanks for the tip.

**Comment by mobenn** [comment]
Any news about Mocking BlobServiceClient?
Thanks
