### ISSUE TITLE
Make client timeout configurable via ClientOptions

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#9289]
**Is your feature request related to a problem? Please describe.**
Currently, in order for the client timeout to be changed, customers need to set the Transport Options with their own Transport containing their own HttpClient. This seems like a heavy-handed approach to simply change the timeout. Also, it is possible that by doing this, customers would not benefit from all of the features of the Core HttpTransport.

**Describe the solution you'd like**
Add a property to ClientOptions called ClientTimeout.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by seanmcc-msft** [comment]
Should we also make the service timeout configurable via ClientOptions?

**Comment by JoshLove-msft** [comment]
> Should we also make the service timeout configurable via ClientOptions?

I don't think we would want to put the service configuration in the ClientOptions. Some services might not even have a service level timeout.

**Comment by JoshLove-msft** [comment]
I wonder if this should be prioritized given that in Storage, we may want to change our default timeout to accomodate service operations that could take longer than 100s:
https://docs.microsoft.com/en-us/rest/api/storageservices/setting-timeouts-for-blob-service-operations
