### ISSUE TITLE
[FEATURE REQ] Cognitive Search SDK should switch to System.Text.Json, or allow using it instead of Newtonsoft.Json

### ISSUE THREAD

**Issue by ylibrach** [Azure/azure-sdk-for-net#9295]
**Is your feature request related to a problem? Please describe.**
Currently, `ISearchIndexClient` and `ISearchServiceClient`, along with their respective implementations, are hardcoded to accept a `Newtonsoft.Json.JsonSerializerSettings`. With .NET Core now at 3.1 and System.Text.Json having added the final few pieces for widespread use (such as converters), the SDK should be updated to either switch over to STJ or allow switching between STJ and Newtonsoft.

**Describe the solution you'd like**
* Switch these types to accept a `JsonSerializerOptions` instead of a `JsonSerializerSettings`.
* Or, abstract the serializer into another type (eg, `SearchSerializer`) and allow this type to be passed in, thereby removing the tight coupling to a specific library. Cosmos DB's SDK uses a similar approach to this.

**Describe alternatives you've considered**
From what I can tell, there is currently no way to have the Cognitive Search SDK use System.Text.Json.

**Comment by AlexGhiondea** [comment]
@ylibrach thanks for filling this issue. We are aware of this issue and we are working on possible solutions. One option is to change the way the code generator behaves and use a different serializer.

**Comment by brjohnstmsft** [comment]
@AlexGhiondea It's my understanding that the new generation of Azure .NET SDKs are built using `System.Text.Json`, so when we move the Search SDK to Track 2, we'll get this "for free" -- is that correct?

**Comment by AlexGhiondea** [comment]
Yes, we are using `System.Text.Json` in our new library. @ylibrach can you share a bit more about the scenario in which you need to control the serialization?

**Comment by Petermarcu** [comment]
This is resolved in the new release of Search: https://www.nuget.org/packages/Azure.Search.Documents/11.0.0

**Comment by Petermarcu** [comment]
BTW, @ylibrach if you migrate to the new version, we'd love your feedback both on the experience and any perf improvements you see now that its on the faster serializer!
