### ISSUE TITLE
[BUG] NullReferenceException when creating an empty blob

### ISSUE THREAD

**Issue by Jericho** [Azure/azure-sdk-for-net#9304]
**Describe the bug**
When attempting to create an empty blob by invoking the `UploadAsync` method with content set to `null` we get a `NullReferenceException` exception. I tested with `BlockBlobClient` but I suspect the same is true with other types of blobs. 

If `null` is not a valid value, I would expect a guard to throw a `ArgumentNullException` which would be more informative.

If `null` is a valid value, I would expect an empty blob to be created. This would mean replacing code such as `contentLength: content.Length,` [here](https://github.com/Azure/azure-sdk-for-net/blob/323aa8266fbf649f157929c5d460ef0825c74dbc/sdk/storage/Azure.Storage.Blobs/src/BlockBlobClient.cs#L538) with something like `contentLength: content?.Length ?? 0,`.

The workaround is to use `new MemoryStream()` instead of a null value.

***Exception or Stack Trace***
```csharp
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Azure.Storage.NonDisposingStream.get_Length()
   at Azure.Storage.Blobs.Specialized.BlockBlobClient.UploadInternal(Stream content, BlobHttpHeaders blobHttpHeaders, IDictionary`2 metadata, BlobRequestConditions conditions, Nullable`1 accessTier, IProgress`1 progressHandler, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlockBlobClient.UploadAsync(Stream content, BlobHttpHeaders httpHeaders, IDictionary`2 metadata, BlobRequestConditions conditions, Nullable`1 accessTier, IProgress`1 progressHandler, CancellationToken cancellationToken)
```

***Code Snippet***
```csharp
var content = (Stream)null;
await blob.UploadAsync(content, headers, metadata, requestConditions, null, null, cancellationToken).ConfigureAwait(false);
```

**Expected behavior**
I expect an empty blob to be created.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added

**Comment by jsquire** [comment]
@tg-msft: Would you be so kind as to help route this?

**Comment by amnguye** [comment]
Hi @Jericho,

Thanks for bringing this issue to our attention. The plan for now is to make sure that it throws the correct exception ("ArgumentNullException") for not just block blob, but for the regular blob client, page blob and append blob as well.

I made a new issue to investigate whether or not we should make a new API for block blob to create an empty blob, like how page and append blob has it.

#9390
