### ISSUE TITLE
Consider Containers for TA client design

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#9317]
From Chris Hoder

Quick question on the design – did we look at how the SDKs will function when a user uses the containers and not our cloud service? (or at least our guidance between the two) 

We have been containerizing operations within the service and not the complete service. For example, Key phrases and sentiment are separate containers. The functionality is the same, but this would mean that each operation could either not exist or would be a different endpoint.

**Comment by annelo-msft** [comment]
Related to #9079

**Comment by maririos** [comment]
If the endpoint is not present in the container, returning a 404 is ok. 
Closing for now
