### ISSUE TITLE
[BUG] RetryExponential in EventHub can return invalid values

### ISSUE THREAD

**Issue by diogorolo** [Azure/azure-sdk-for-net#9322]
**Describe the bug**
EventHub RetryExponential logic returns values smaller than 0 which throws exceptions when trying to send data through the EventHub

***Exception or Stack Trace***
One or more errors occurred. (The value needs to translate in milliseconds to -1 (signifying an infinite timeout), 0 or a positive integer less than or equal to Int32.MaxValue. (Parameter 'delay'));   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)

**To Reproduce**
Define a RetryPolicy with the following parameters: 

***Code Snippet***
```
       var client = EventHubClient.CreateFromConnectionString(connectionString);
        client.RetryPolicy =new RetryExponential(new TimeSpan(0,0,0,0,10),new TimeSpan(0,0,0,0,500),10  );

// If the Send fails, the error occurs due to the retry,
         client.SendAsync(new EventData(new byte[]{}));

 ```
[The exception happens because we're doing a Task.Delay of a negative value here.](https://github.com/Azure/azure-sdk-for-net/blob/3db8feaa87d7e44eb91baf7812edb70fbc8042ad/sdk/eventhub/Microsoft.Azure.EventHubs/src/Amqp/AmqpEventDataSender.cs#L91)

You can also use this test to check that the value returned by the retry policy in smaller than 0.

```
        [Fact]
        [DisplayTestMethodName]
        public void RetryPolicySmallerThanZeroRetryInterval()
        {
            int retryCount = 0;
            RetryPolicy retry = new RetryExponential(new TimeSpan(0, 0, 0, 0, 10), new TimeSpan(0, 0, 0, 0, 500), 10);

            TimeSpan? firstRetryInterval =
                retry.GetNextRetryInterval(new SocketException(), TimeSpan.FromSeconds(60), ++retryCount);
            TestUtility.Log("firstRetryInterval: " + firstRetryInterval);
            Assert.True(firstRetryInterval != null);
            Assert.InRange(firstRetryInterval.Value.TotalMilliseconds,0,TimeSpan.MaxValue.TotalMilliseconds);
        }
```
**Expected behavior**
Retry policy should always have positive retry intervals

**Setup (please complete the following information):**
 - OS: Windows
 - IDE : Visual Studio 2019
 - Version of the Library used:
 Built from master

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by jsquire** [comment]
@serkantkaraca and @JamesBirdsall:  Would you be kind enough to share your thoughts, please?

**Comment by christothes** [comment]
Just looked into this one out of curiosity and created this quick PR #9370 for discussion. Still needs minor cleanup if this fix makes sense.

**Comment by serkantkaraca** [comment]
PR approved. Thx for the fix!

**Comment by jsquire** [comment]
Closing this out, since the fix has been merged.
