### ISSUE TITLE
[MQ] new resource script should enable specifying directories outside of sdk/

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-net#9325]
This is not part of the MQ priorities, it is a nice to have. 

Smoke tests can also make use of dynamically allocated resources. They live in the `common/` folder in the root of the repo today (https://github.com/Azure/azure-sdk-for-net/tree/master/common/SmokeTests)... except for Java which will be moving up to `common/` in the next check in. 

If we can specify a value like `../common/SmokeTests` to the `ServiceDirectory` parameter then this issue is a noop.

**Comment by heaths** [comment]
Will change from using `Join-Path` to `[Path]::Combine()` which, if the last element is an absolute path, will use that as the sole path. `Join-Path` doesn't do that, and has fairly inconsistent results based on provider and whether elements have a trailing backslash.
