### ISSUE TITLE
[BUG] ASPNET Core 3.1 Not Compatible 

### ISSUE THREAD

**Issue by Hantse** [Azure/azure-sdk-for-net#9333]
**Describe the bug**
Hello,

I use Azure.Storage.Blobs in project, i update from 2.2 to ASPNET Core 3.1.
Before, not issue. Now i have a incompatible issue on build.

I can build / launch in Visual Studio in local.
I cannot build in Azure Dev Ops.

***Exception or Stack Trace***
Package Azure.Storage.Blobs 12.1.0 is not compatible with netcoreapp3.1.

**To Reproduce**
Create a project in ASPNET Core 3.1, and try to simple package restore in Azure Dev Ops Pipeline.

**Comment by JoshLove-msft** [comment]
I've verified that it works locally as well after installing ASPNET Core 3.1

@Hantse It looks like Core 3.1 is not installed by default yet on dev ops. Have you added a task to your pipeline to install 3.1?

**Comment by mikeharder** [comment]
Here's the issue for adding .NET Core 3.1 to pipelines agents:

https://github.com/microsoft/azure-pipelines-image-generation/issues/1435

Here's a sample showing how to install .NET Core 3.1 via the [Use .NET Core task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops).

https://github.com/microsoft/azure-pipelines-image-generation/issues/1438#issuecomment-563920634

**Comment by Hantse** [comment]
Hello,

I've add task, to install .Net Core SDK 3.1.100.
I have another issue, i cannot confirm, it's resolve.

I work on other issue and give feedback,

If it is only this error, sorry to have opened a ticket for so little.

Kind regards,

**Comment by jsquire** [comment]
Closing this out, as .NET Core 3.1 has been added into the pipelines.   Please feel free to reopen if you feel that further discussion is needed.
