### ISSUE TITLE
Management.Sql has inconsistent MaxSizeBytes type

### ISSUE THREAD

**Issue by natelaff** [Azure/azure-sdk-for-net#9337]
Not high priority by any means, but this seemed inconsistent.

string Microsoft.Azure.Management.Sql.Models.ImportRequest.MaxSizeBytes
long Microsoft.Azure.Management.Sql.Models.Database.MaxSizeBytes

**Comment by isra-fel** [comment]
Sorry for late response. SQL team might have some insights to share. Thanks.

**Comment by ArthurMa1978** [comment]
In the latest [swagger](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/sql/resource-manager/Microsoft.Sql/preview/2022-02-01-preview/Servers.json#L580) it's still `string` type.

**Comment by fengzhou-msft** [comment]
Need to verify the type with live traffic.
