### ISSUE TITLE
[Bug] Respect client timeout even after response headers are returned

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#9340]
Since we use the [HttpCompletionOption.ResponseHeadersRead](https://docs.microsoft.com/en-us/uwp/api/windows.web.http.httpcompletionoption) option in [HttpClientTransport](https://github.com/Azure/azure-sdk-for-net/blob/965869fd80da2487ad08389a8cc6172f6d63d68d/sdk/core/Azure.Core/src/Pipeline/HttpClientTransport.cs#L64), the HttpClient timeout will not apply after the response headers are returned. 
This means that if the body of the response never returns for some reason, the client will block indefinitely. 

**Describe the solution you'd like**
Issue https://github.com/Azure/azure-sdk-for-net/issues/9289 requested a ClientTimeout property in ClientOptions. Once we add this, one idea would be to respect the property even after the header is returned. Specifically, [RetriableStream](https://github.com/Azure/azure-sdk-for-net/blob/965869fd80da2487ad08389a8cc6172f6d63d68d/sdk/core/Azure.Core/src/Shared/RetriableStream.cs) could respect this timeout and throw a TimeoutException if we pass the timeout. A problem with this approach would be that large files would likely timeout, so a better approach would be to either use the same timeout (or a different timeout value) to mean how long to wait before throwing when data has stopped returning, or go by the rate that the data is being read and throw if we fall under a certain threshold. The service has a 2MB/minute minimum threshold before throwing: https://docs.microsoft.com/en-us/rest/api/storageservices/setting-timeouts-for-blob-service-operations
 
I'm not sure if there are other scenarios not involving RetriableStream where this indefinite blocking can occur, but if there are we should address those to.

**Comment by mikeharder** [comment]
@JoshLove-msft: Should this be fixed by #10128?  If so, can we try to re-enable the tests?

**Comment by JoshLove-msft** [comment]
I think so, we should give it a try.

**Comment by AlexGhiondea** [comment]
@JoshLove-msft is this still applicable? If not, please close this.

**Comment by JoshLove-msft** [comment]
This was fixed in https://github.com/Azure/azure-sdk-for-net/pull/10169
Closing
