### ISSUE TITLE
Adding webhook receiver to Action Group

### ISSUE THREAD

**Issue by krishnajaju** [Azure/azure-sdk-for-net#9350]
**Query/Question**
I am trying to add a webhook receiver to an Action Group using [Azure Monitor APIs](https://github.com/Azure/azure-sdk-for-net/blob/7f58c79d92866264c65a776fb6fdee4751b4223e/sdk/monitor/Microsoft.Azure.Management.Monitor/src/Generated/ActionGroupsOperations.cs). It exposes a function `CreateOrUpdateWithHttpMessagesAsync` where we need to pass complete action group resource object and this object overwrites the action group completely. To add a webhook receiver, I plan to first fetch action group, add a webhook receiver to that action group and then call update method with this updated action group; does this way of adding webhook sound right?

Would there be a scenario where fetching and updating an action group result in data loss when `fetch api` gives a different data contract?

***Why is this not a Bug or a feature Request?***
Want to understand right way of consuming API.

**Setup (please complete the following information if applicable):**
 - OS: NA
 - IDE : NA
 - Version of the Library used: NA
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by isra-fel** [comment]
Sorry for late response. @AzmonActionG could you please share some insights? Thank you

**Comment by ritwik8119** [comment]
Yes, the specified approach should work. Calling update method with the modified action group will succeed, as long as the newly added receiver (the webhook receiver in the above example) matches the data contract for that receiver.
