### ISSUE TITLE
IncludeStatistics only available for batch operations

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#9378]
`TextAnalyticsResult` provides the option to `Gets statistics about the input document and how it was processed by the service`. This information is misleading as for .NET we only provide the option to get the statistics if there is a batch operation (i.e. [here](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/textanalytics/Azure.AI.TextAnalytics/tests/samples/Sample1_DetectLanguageBatch.cs#L44)).

We should either remove the `Statistics` property from `TextAnalyticsResult` to avoid confusion, or provide an option for the customer to be able to ask for that information in single document analysis like [Python](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/textanalytics/azure-ai-textanalytics/samples/sample_single_detect_language.py#L54) does.

FYI the Detect Language API:
```
Request URL
https://{endpoint}/text/analytics/v2.1/languages[?showStats]
Request parameters
showStats (optional)boolean
(optional) if set to true, response will contain input and document level statistics.
```

FYI @annelo-msft

**Comment by maririos** [comment]
In theory it is enabled for batch operations, but not for convenience methods where the customer can send a list of strings. i.e. https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/textanalytics/Azure.AI.TextAnalytics/src/TextAnalyticsClient.cs#L248

**Comment by annelo-msft** [comment]
The proposed design change in the user study branch would resolve this issue.  Let's see if we can convince the architects to accept that change.

**Comment by maririos** [comment]
See PR https://github.com/Azure/azure-sdk-for-net/pull/9772

**Comment by maririos** [comment]
PR merged
