### ISSUE TITLE
[FEATURE REQ] [ServiceBus] Allow to configure AzureTokenServiceProvider with connectionstring

### ISSUE THREAD

**Issue by MPapst** [Azure/azure-sdk-for-net#9380]
**Is your feature request related to a problem? Please describe.**
I am using different services that are not yet or will maybe never be capable of leveraging from an assigned identity in azure (e.g. not azure hosted compute) and want to use the same code to access a service bus.
For other services (e.g. KeyVault) it was a good solution to just pass a connection string to the ```AzureServiceTokenProvider``` and put it into the DI.
This does not work with Service Bus and Event Hub, because those are hiding the use inside other classes.
To achieve a solution I added an own implementation of ```ITokenProvider``` interface that allows to inject an ```AzureServiceTokenProvider``` instance

**Describe the solution you'd like**
Provide a static method or an ```ITokenProvider``` implementation that takes an ```AzureServiceTokenProvider``` Instance through the constructor

(This also applies to EventHub)

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

I can provider an PR if you are interested.

**Comment by serkantkaraca** [comment]
Why did you need to implement a new token provider? You can easily provide a call back to TokenProvider below where you can manage your own customized AzureServiceTokenProvider. 

https://github.com/Azure/azure-sdk-for-net/blob/50ebe1c6b1b4c76954e7dd94f443d4ffa4df215a/sdk/servicebus/Microsoft.Azure.ServiceBus/src/Primitives/TokenProvider.cs#L80

**Comment by MPapst** [comment]
Because I wanted to provide it to a service using DI without resolving the dependencies on my own.
The only change that would be necessary for that is an constructor receiving an instance of ```AzureServiceTokenProvider``` from DI for the class ```ManagedIdentityTokenProvider```. As I did not want to modify the library I created a new one for my projects, behaving similar to the ```ManagedIdentityTokenProvider``` with the constructor change.

**Comment by serkantkaraca** [comment]
I see, then you did the right thing. Custom token provider is there for that kind of needs anyway.

Unfortunately we are not adding any new features to this library anymore. A new library is being developed by SDK Team from scratch which will have similar paradigms as Event Hubs library which is here - https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/eventhub/Azure.Messaging.EventHubs

@nemakam, can you point the branch for Service Bus track-2 library if development has already started?

**Comment by nemakam** [comment]
@serkantkaraca , the development hasnt started yet, and should start pretty soon. But yes, the current library is adding only important necessary features as of now.

**Comment by SHARMA8** [comment]
@MPapst I am also working on a similar thing. Can you please share the changes you made?  

@nemakam - Can you please share any update you may have on this? I would like to know how we are progressing on the new library. 

Thanks

**Comment by MPapst** [comment]
@SHARMA8, I am sorry, I am currently away on vacation without access to the actual code. But you can take a look on the implementation of ManagedIdentityTokenProvider as mentioned earlier. The necessary change is to cremte an own implementation of the same functionality an replace the static field of the AzureServiceTokenProvider with an instance you are injecting through the ctor.

@serkantkaraca: Shall I close the Issing?

**Comment by serkantkaraca** [comment]
@MPapst yes please, we can close.
