### ISSUE TITLE
[BUG]ClientRuntime 2.3.18 is not compatible with Newtonsoft.Json 12.0.3

### ISSUE THREAD

**Issue by batrived** [Azure/azure-sdk-for-net#9381]
**Describe the bug**
Hi. We recently upgraded Newtonsoft.Json to 12.0.3 from 11.0.2 and started getting this error:

Error invoking operation: Exception has been thrown by the target of an invocation.System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeLoadException: Method 'get_SerializationSettings' in type 'Microsoft.Azure.Management.EventGrid.EventGridManagementClient' from assembly 'Microsoft.Azure.Management.EventGrid, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

***Exception or Stack Trace***

Error invoking operation: Exception has been thrown by the target of an invocation.System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeLoadException: Method 'get_SerializationSettings' in type 'Microsoft.Azure.Management.EventGrid.EventGridManagementClient' from assembly 'Microsoft.Azure.Management.EventGrid, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

***Code Snippet***
Here is a sample implementation of my TestClient:

```
public class EventGridManagementClient:  ServiceClient<TestClient>, IAzureClient {
    public JsonSerializerSettings SerializationSettings { get; private set; }
    public EventGridManagementClient() {
        SerializationSettings = new JsonSerializerSettings();
    }

}
```

**Expected behavior**
It shouldn't crash.

**Screenshots**

**Setup (please complete the following information):**
.Net Framework 4.6.1
- I am using these AutoRest packages:
Microsoft.Rest.ClientRuntime - 2.3.18
Microsoft.Rest.ClientRuntime.Azure - 3.3.18
Microsoft.Rest.ClientRuntime.Azure.Authentication - 2.3.6

**Comment by ahamad-MS** [comment]
Thanks for reporting this issue. EventGridManagementClient is auto-generated for us using auto-rest. Adding appropriate labels (Client, CodeGen, AutoRest RunTime) to request help from appropriate team to help triage/investigate this issue.

**Comment by ahamad-MS** [comment]
Hello @batrived, 

Per discussion with @Petermarcu, it seems this is a well known compatability issue with Newtonsoft.json. The CodeGen team is aware of this issue and have a plan to address it soon. 

The current recommendation is to stay in the previous Newtonsoft.json if possible until this compatability issue is resolved.

@AlexGhiondea , please provide any additional info if needed here.

**Comment by lilyjma** [comment]
Hi @batrived, hopefully your problem was addressed. I was wondering if you'd be willing to share with us your experience working with this library so far. We're committed to improving our SDK, GitHub support process, and documentation. Your feedback is extremely helpful to us, so please let us know if we can hop on a quick call to discuss it. Thanks!
