### ISSUE TITLE
[storage] [FEATURE REQ] Create method for block blob to create empty blobs

### ISSUE THREAD

**Issue by amnguye** [Azure/azure-sdk-for-net#9390]
**Is your feature request related to a problem? Please describe.**
Referencing issue #9304 .

A customer tried to create an empty block blob by using the upload method and its inconvenient to create a block blob by creating an empty stream every time.

For our append and page blob methods we have create methods for empty blobs.

**Describe the solution you'd like**
The proposal and open to discussion since this would be a new API, is to create a "Create" method for the block blob method

**Describe alternatives you've considered**
We were also considering having a check for the upload method to check if they pass a null stream and create the block blob.
Or the user can keep manually creating an empty stream to do so as well.

**Additional context**
Empty blobs are a regular scenario done by customers.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by JimSuplizio** [comment]
Hi @amnguye, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
