### ISSUE TITLE
Improve README instructions for auth

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#9407]
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/textanalytics/Azure.AI.TextAnalytics/README.md

Go through these and make sure step-by-step makes sense.  Python has done a good job here.

Also, how would the guidance be different for production?  Provide a separate sample for this?  (Service team may also be working on this so check with them first before doing this part)

**Comment by maririos** [comment]
Also, mention that the endpoint and API Key cna be found in the Azure Portal first, and then the CLI option
