### ISSUE TITLE
Azure.Core should document how to manually enable ETW logging

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#9419]
During a review, it came up for improved troubleshooting docs that we document (rather, all service have a link back to azure.core) how to manually enable ETW logging, e.g. on a Windows client application.

**Comment by pallavit** [comment]
@heaths which documentation link are we talking about here?

**Comment by heaths** [comment]
That section should actually link back to Azure.Core's diagnostics.md file and not duplicate. That's what we had decided a couple years ago - to link back to authoritative sources.

But, no, that is a console logger. We need to show an E2E ETW trace on Windows, from using logman.exe (or whatever - there's many tools) to setting up an ETW listener: basically, [this](https://learn.microsoft.com/dotnet/azure/sdk/logging#log-to-diagnostic-traces) + [this](https://learn.microsoft.com/dotnet/core/diagnostics/logging-tracing#eventsource).

It was originally supposed to be a short-lived task for Pavel, but I can take a crack at it. I've got a lot of experience with ETW.

**Comment by jsquire** [comment]
This seems like something that should be a Learn article rather than Azure SDK sample so that we have better discovery and can deep-dive.   @heaths, @scottaddie :  Thoughts?

**Comment by heaths** [comment]
Sure, and some exist, but this was more specifically about what provider namespaces we have e.g., Azure.Core. I figured having a sample that is there mainly to talk about how to discover what providers we have would logically talk about - even briefly, with a link out to existing resources on Learn - enabling logging.

I say "sample" here because Azure.Core's samples under _samples/_ are not samples as they are with our other track 2 SDKs - they are effectively troubleshooting docs / howtos.

**Comment by pallavit** [comment]
@scottaddie since you mentioned you are looking at moving some of Azure.Core samples to learn sections - this may be of interest as well.

**Comment by pallavit** [comment]
@heaths I agree with @jsquire here. We are trying to move general purpose and things that will be useful for all SDKs to move to Learn pages and this is a perfect fit there too.

**Comment by heaths** [comment]
Agreed, and we should keep this open to track, IMO.

**Comment by JimSuplizio** [comment]
Hi @heaths, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
