### ISSUE TITLE
[BUG] ComputeManagementClient.ResourceSkus.ListAsync's filter parameter does not work for anything other than filtering by location parameter

### ISSUE THREAD

**Issue by sandeepiiit** [Azure/azure-sdk-for-net#9428]
**Describe the bug**
`Microsoft.Azure.Management.Compute`'s `ComputeManagementClient.ResourceSkus.ListAsync(filter)` does NOT filter for anything other than a filter that uses `location` parameter. This is also discussed https://github.com/Azure/azure-sdk-for-go/issues/6393#issuecomment-559312686.

***Code Snippet***
```
ComputeManagementClient computeManagementClient = new ComputeManagementClient(credentials);
computeManagementClient.SubscriptionId = "**********";
string filter = "resourceType eq 'virtualMachines'";  // Doesn't work. All results are returned.
// string filter = "$filter=resourceType eq 'virtualMachines'";  // Doesn't work. All results are returned.
// string filter = "resourceType eq virtualMachines";  // Doesn't work. All results are returned.
// string filter = "resourceType eq 'Microsoft.Compute/virtualMachines'";  // Doesn't work. All results are returned.
// string filter = "resourceType = 'virtualMachines'";  // Doesn't work. All results are returned.
// string filter = "resourceType='virtualMachines'";  // Doesn't work. All results are returned.
IPage<ResourceSku> resourceSkus = await computeManagementClient.ResourceSkus.ListAsync(filter: filter);
```

**Expected behavior**
I expect the returned results to only contain resource whose resourceType = 'virtualMachines'.

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : Visual Studio
 - Version of the Library used: Microsoft.Azure.Management.Compute 30.2.0

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by Drewm3** [comment]
This is the expected behavior of the API today. The only supported filter is location. So this is really a feature request. 

To track the feature request I have opened the following suggestion in the Azure User Voice system. Please up vote this item: https://feedback.azure.com/forums/216843-virtual-machines/suggestions/39435124-add-additional-filter-options-to-compute-resource

**Comment by sandeepiiit** [comment]
Thanks for creating the feature.

Just a thought: Would it make sense to rename the `filter` param to `location` like some of the other Azure APIs (e.g [Usage ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.compute.usageoperationsextensions.listasync?view=azure-dotnet)API) ? Or perhaps a summary comment on the method mentioning that the only supported filter is location. Hoping that other users of the API don't spend a lot of time trying to debug why filter is not working as they expect :)
