### ISSUE TITLE
Include whether a test is being run in sync or async mode for live tests

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#9434]
This would be helpful in debugging for cases where the stack trace is not included for a failed test, e.g. in case of an NUnit timeout. When the stack trace is included, the trace should point to whether it is sync or async by looking at the initial call, but this feature would still add some convenience.

This should probably be added in `ClientTestBase` so it will work for all libraries. Whether we are in async or not can be determined from the `IsAsync` property.

**Comment by pallavit** [comment]
Given we have not seen many asks for this, I will go ahead and close this one. We can reopen\reprioritize as needed.
