### ISSUE TITLE
Two missing properties from StorageAccountProperties

### ISSUE THREAD

**Issue by veena-udayabhanu** [Azure/azure-sdk-for-net#945]
[Moved from azure-storage-net]
According to the MS Wiki for List Storage Accounts - https://msdn.microsoft.com/en-us/library/azure/ee460787.aspx#bk_extendedproperties - there should be two properties, one for Account Type, and one for Custom Domains - these both appear to be missing from the WindowsAzure.Storage 4.3.2-preview package on nuget.

**Comment by markcowl** [comment]
These properties are in the latest storage manageemnt library.  Please download Microsoft.WindowsAzure.Storage.Manageent from nuget.
