### ISSUE TITLE
[QUERY] How to limit calls to Blob Storage from EventProcessorHost?

### ISSUE THREAD

**Issue by GeeWee** [Azure/azure-sdk-for-net#9450]
**Query/Question**
I have two Azure Eventhubs, each with 32 partitions. Around 700 events pass through the eventhubs every second, first through one, then through the other. One EventHub has 3 concurrent readers, and the other only has one.

My issue is, that the C# EventProcessorHost seems to make a pretty wild amount of calls to the blob storage, for things like lease management and checkpointing. We're talking on average, 800 calls every second.

We register the EventProcessorHost like this
```csharp
            _eventProcessorHost = new EventProcessorHost(
                _eventHubOptions.CurrentValue.EventHubName,
                _eventHubOptions.CurrentValue.ConsumerGroupName ?? PartitionReceiver.DefaultConsumerGroupName,
                _eventHubOptions.CurrentValue.EventHubConnectionString,
                _eventHubOptions.CurrentValue.StorageConnectionString,
                _eventHubOptions.CurrentValue.StorageName);

            // Reduce lease renewal throughput for storage accounts to save price
            _eventProcessorHost.PartitionManagerOptions = new PartitionManagerOptions()
            {
                LeaseDuration = TimeSpan.FromSeconds(60),
                RenewInterval = TimeSpan.FromSeconds(50)
            };

            var eventProcessorOptions = new EventProcessorOptions
            {
                InitialOffsetProvider = partitionId =>
                    EventPosition.FromEnd(),
                EnableReceiverRuntimeMetric = true,
                MaxBatchSize = 400,
                PrefetchCount = 400,
            };

            await _eventProcessorHost.RegisterEventProcessorFactoryAsync(_eventProcessorFactory, eventProcessorOptions);
```
We're looking to limit the amount of calls made to storage. As you can see above, we've also extended the lease duration, from the default of 30 seconds, to the maximum of 60.

We've implemented it, so that checkpointing happens every 2000 messages, which means that, on average, checkpointing happens no more than every 15 seconds per partition.

Is this a normal amount of storage calls to coordinate the EventProcessorHosts? Is there any other dials or knobs I can turn, e.g. adjusting partitions to limit the amount of storage calls?

This is potentially related to https://github.com/Azure/azure-event-hubs-dotnet/issues/331

***Why is this not a Bug or a feature Request?***
This could potentially be a feature request for further documentation in regards to how checkpointing and lease management works - primarily in regards to cost of storage transactions.

**Setup (please complete the following information if applicable):**
 - OS: Linux
 - IDE : Rider
 - Version of the Library used. `Microsoft.Azure.EventHubs.Processor 4.1.0`
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Query Added
- [X] Setup information Added

**Comment by jsquire** [comment]
@serkantkaraca, @sjkwak, and @JamesBirdsall - would you be so kind as to offer your thoughts?

**Comment by serkantkaraca** [comment]
Same question on stackoverflow.com and I am following up there. https://stackoverflow.com/questions/59713513/how-to-limit-calls-to-blob-storage-from-eventprocessorhost

**Comment by GeeWee** [comment]
Just to post additional information here as well.
I have tried running the exact same code, but reducing partitions on each EventHub from 32 to 6. The throughput remains the same (we were running well below capacity, but expected to scale up).

The storage calls have dropped from 500/sec~, to 1.5~/sec.
This seems like a pretty wild exponential increase in storage calls.

**Comment by serkantkaraca** [comment]
I am working on couple improvements in PartitionManager to reduce the storage I/O further more. This will be in release 4.2.

**Comment by GeeWee** [comment]
That's awesome to hear.
Can you confirm this is a normal amount of requests though? I'd like to know whether or not we're misconfiguring our application, or if the amount of storage requests scales exponentially with the amount of partitions?

**Comment by serkantkaraca** [comment]
I cannot confirm w/o knowing how much of the I/O is originated from checkpointing. Can you run with 32 partitions with and w/o checkpointing under regular test load and tell me the difference?

**Comment by GeeWee** [comment]
With a sufficiently high checkpointing threshold, it seems that the IO is reduced to manageable amounts.

Closing.
