### ISSUE TITLE
[QUERY] EventHub batch-processing API future

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-net#9455]
**Query/Question**
Starting Azure.Messaging.EventHub preview6, EventHubProcessor allows to process single messages only (before it allow to process batches only). 

going forward, what is the recommendation to process events with batches? I.e. is EventHubProcessor going to provide any API like this?

Some context: I'm working on distributed tracing from Azure Monitor side and want to understand usage patterns for the new SDK to plan instrumentation for the SDK and Azure services that use it (such as Azure Functions).  

***Why is this not a Bug or a feature Request?***
I'm interested in plans for the EventHub SDK and don't have a scenario that breaks/not working. You could also consider it as a documentation concern.

**Setup (please complete the following information if applicable):**
 - OS: [e.g. iOS] N/A
 - IDE : [e.g. IntelliJ] N/A
 - Version of the Library used: EventHub 5.0.0 preview6
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by jsquire** [comment]
The current Event Processor has no existing plans to move away from the "1-per-handler" pattern, as it is intended to provide a natural step-up from the iterator pattern offered by the consumer client.   Batching is a trivial thing to implement within the handler, if desired, and is illustrated in a [sample](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs.Processor/samples/Sample09_ProcessEventsByBatch.cs).

That said, we are aware that there is a need to support a means of native batching for more advanced scenarios and those that require greater throughput.  We do plan on offering an extensible base Event Processor within the client library that offers fewer abstractions and is closer "to the metal" - which will be based on a batched approach.  Similarly, we also would like to introduce an additional consumer for the same audience that supports the pull-based receiving in batches that the track one client does today.   These offerings are currently in design and are expected to be something that we include in a near-term release.

**Comment by lmolkova** [comment]
thanks for the info!
