### ISSUE TITLE
Correct User Agent string

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#9459]
TextAnalytics User Agent string is:
User-Agent: azsdk-net-AI.TextAnalytics/1.0.0-preview.1+d0778896223c571c825761133d79b9d68c0842d6 (.NET Core 3.1.0; Microsoft Windows 10.0.18363)

It should just have preview.1, not the hash afterward.

**Comment by maririos** [comment]
Is the UA still generated by Core? @pakrym Is this expected?

**Comment by pakrym** [comment]
It's a bug, dotnet build embeds the source sha into the informational version but we should be stripping it out.
