### ISSUE TITLE
CloudContext.Clients.CreateComputeManagementClient gone?

### ISSUE THREAD

**Issue by olaj** [Azure/azure-sdk-for-net#946]
I have some code based on this sample and after i made some nuget upgrades it doesn't work anymore. Is this a bug or some breaking changes that (seems to) not be documented somewhere?

The error is that CreateComputeManagementClient cannot be found. 

var cloudServiceName = "MyCloudService";

using (ComputeManagementClient client =
    CloudContext.Clients.CreateComputeManagementClient(Credentials))
{
    await client.HostedServices.CreateAsync(
        new HostedServiceCreateParameters
        {
            ServiceName = cloudServiceName,
            Location = LocationNames.WestUS
        });
}

**Comment by davihar** [comment]
See https://github.com/Azure/azure-sdk-for-net/issues/927

**Comment by markcowl** [comment]
This was removed in the major version update.
Please use the constructor of the specific management client, i.e. var client = new ManagementClient(credentials)...
