### ISSUE TITLE
Updates to README

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#9461]
a. The install package command < Install-Package Azure.AI.TextAnalytics > did not work without specifying the package version, here is the command that worked : `Install-Package Azure.AI.TextAnalytics -Version 1.0.0-preview.1`
b. We can use cloud shell (https://shell.azure.com/bash) link which will allow user to run the resource creation commands without installing the CLI

For example, as in https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/keyvault/keyvault-keys 

c. Parameters to the cloud shell command need could be explained to simplify the auth:
`az cognitiveservices account create --kind TextAnalytics --resource-group <your-resource-group-name> --name <your-resource-name> --location <location> --sku <sku>`
You can list available locations or skus by running the following commands
>az account list-locations 
>az account list-skus
d. Authenticating to the service:  “subscription key” term in the readme is a little ambiguous, at the portal it is referred as “ API key” or “Access Key” at the overview page or quick start page, suggest to clarify

**Comment by annelo-msft** [comment]
@elraikhm for user study

**Comment by maririos** [comment]
>did not work without specifying the package version, here is the command that worked : Install-Package Azure.AI.TextAnalytics -Version 1.0.0-preview.1

I remember that when working with App config, we added that and eventually the preview version was deleted from the Readmes but I don't remember the reason why. @kaerm is this still a thing?

**Comment by kaerm** [comment]
Shouldn't have changed - commands should be listed in a way that it just works for people in current state

**Comment by maririos** [comment]
Thanks @kaerm !

**Comment by maririos** [comment]
a. and c. addressed in PR #9887 
b. Using Cloud Shell might cause billing issues, so removing the option for now.
d. Addressed when we did changes from subscription key to API Key
