### ISSUE TITLE
[FEATURE REQ] Service Bus abandon message with custom delay

### ISSUE THREAD

**Issue by Bnjmn83** [Azure/azure-sdk-for-net#9473]
Taken from [here](https://github.com/Azure/azure-service-bus-dotnet/issues/52).

This is still a desired feature and totally makes sense in many scenarios. Is there any effort to implement this in the future?

> Sometimes business logic decides that it would be good to retry a message at some latter time.
> For this reason it would be very helpful, if Abandon(IDictionary<>) or similar, would be able to set ScheduledEnqueueTimeUtc.
> 
> msg.Abandon(new Dictionary<string, object>()
> {
>   { "ScheduledEnqueueTimeUtc", DateTime.Now.ToUniversalTime().AddMinutes(2) }
> });
> Right now, this does not work, because only custom properties can be manipulated this way.
> I’m also happy to hear if this kind of retry can be achieved on some other easier way?
> Right now, I typically set LockDuration on some reasonable retry time and avoid invoking of abandon in PeekLock mode. Another way is Deferring, but I don’t like it, because it requires me
> track deferred message, which makes things more complicate then necessary.
> 
> To recap all, wouldn’t be good to have something between Deferr() and Abandon()?
> For example Defer(TimeSpan) or Defer(ScheduleteTimeUtc) or Abandon(TimeSpan) or Abandn(TimeSpan)?!
> Only difference would be, that in a case of Defer, property DeliveryCount wouldn’t be incremented

.

**Comment by jsquire** [comment]
@nemakam and @binzywu:  Woudl you be so kind as to offer your thoughts?

**Comment by nemakam** [comment]
@Bnjmn83, 
This is a feature ask that we could work in the future, but we don't have an ETA right now.
As an alternate solution, you can implement this yourself on the client using the transaction feature. Essentially, complete() the message and send a new message with appropriate "scheduleTime" within the same transaction. That should behave similarly.

**Comment by axisc** [comment]
I think @nemakam's recommendation of completing the message and sending a scheduled message is a better approach.

Service Bus (or any message/command broker) is a server/sender side cursor. When a receiver/client wants to control when the message is visible again (i.e. custom delay/retry) it must take over the cursor from the sender. This can be achieved with the below options - 
  * Completing the message and then resending with a scheduled message.
  * Deferring message and receiving explicitly.

Do let me know if this approach is too cumbersome and we can revisit. If not, I can close this issue.

**Comment by mack0196** [comment]
If the subscription\queue has messages in there, will the scheduled message 'jump to the front of the line' at its scheduled time?

**Comment by ramya-rao-a** [comment]
@shankarsama Please consider moving this issue to https://github.com/Azure/azure-service-bus/issues where you track feature requests for the service

**Comment by jsquire** [comment]
Issue moved to [Azure/azure-service-bus #454](https://github.com/Azure/azure-service-bus/issues/454) via [**ZenHub**](https://www.zenhub.com/)
