### ISSUE TITLE
[FEATURE REQ] Storage - Support automatic resource creation for live tests when run locally

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#9479]
Our CI is now using ARM to create and tear down resources.
The next step would be to add support to do this locally.
This issue will track the requirements for running locally.

**Comment by JimSuplizio** [comment]
Hi @JoshLove-msft, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
