### ISSUE TITLE
[QUERY] why is there no abstract class on top of service client

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-sdk-for-net#9480]
**Is your feature request related to a problem? Please describe.**
Can service client have common abstract class? 

**Describe the solution you'd like**
According to [guideline of service client design] (https://azure.github.io/azure-sdk/dotnet_introduction.html), there are many common or similar methods or pattern, why not add an abstract class as their super class? When service team creates client, it can be extended from this super class directly. 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by KrzysztofCwalina** [comment]
Clients don't actually share any/many methods. They do share a common pattern. The abstract class would not be able to have many/any useful methods. If you still feel we should have a base class. Please suggest what API would it have and how the base APIs would be used.
