### ISSUE TITLE
[BUG]Live test failures in UploadAsync_LargeFile test

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#9487]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=234450&view=ms.vss-test-web.build-test-results-tab&runId=8047326&paneView=debug&resultId=100508

Will need to either decrease the size of the file being uploaded or use the LimitedMemoryStream being added in https://github.com/Azure/azure-sdk-for-net/pull/9464

Introduced: #9260
Disabled: #9499

**Comment by mikeharder** [comment]
Introduced: #9260
Disabled: #9499

**Comment by jsquire** [comment]
Given the age of this issue, I'm going to close it as stale.  If tests continue to fail, please file a new issue.
