### ISSUE TITLE
DataLakeRestClient AppendData exception for zero-length files

### ISSUE THREAD

**Issue by Tornhoof** [Azure/azure-sdk-for-net#9489]
**Describe the bug**
AppendData using a zero length stream throws an exception.

***Exception or Stack Trace***
```ini
Azure.RequestFailedException: The value for one of the HTTP headers is not in the correct format.
RequestId:d3d0ae4c-501f-00e4-3f92-cbcbec000000
Time:2020-01-15T10:58:39.2410781Z
 ---> System.Exception: Exception of type 'System.Exception' was thrown.
   --- End of inner exception stack trace ---
   at Azure.Storage.Files.DataLake.DataLakeRestClient.Path.AppendDataAsync_CreateResponse(Response response)
   at Azure.Storage.Files.DataLake.DataLakeRestClient.Path.AppendDataAsync(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Uri resourceUri, Stream body, String version, Nullable`1 position, Nullable`1 timeout, Nullable`1 contentLength, Byte[] transactionalContentHash, String leaseId, String requestId, Boolean async, String operationName, CancellationToken cancellationToken)
   at Azure.Storage.Files.DataLake.DataLakeFileClient.AppendInternal(Stream content, Nullable`1 offset, Byte[] contentHash, String leaseId, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Files.DataLake.DataLakeFileClient.AppendAsync(Stream content, Int64 offset, Byte[] contentHash, String leaseId, CancellationToken cancellationToken)
```

**To Reproduce**
```csharp
using System;
using System.IO;
using System.Threading.Tasks;
using Azure.Storage;
using Azure.Storage.Files.DataLake;

namespace ZeroLengthRepro
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var storageAccountName = "<Account>";

            string storageAccountKey = "<Key>";
            StorageSharedKeyCredential sharedKeyCredential = new StorageSharedKeyCredential(storageAccountName, storageAccountKey);
            // Create DataLakeServiceClient using StorageSharedKeyCredentials
            Uri serviceUri = new Uri("<URL>");
            DataLakeServiceClient serviceClient = new DataLakeServiceClient(serviceUri, sharedKeyCredential);
            // Create a DataLake Filesystem
            DataLakeFileSystemClient filesystem = serviceClient.GetFileSystemClient(Guid.NewGuid().ToString().ToLowerInvariant());
            await filesystem.CreateAsync().ConfigureAwait(false);
            var response = await filesystem.CreateFileAsync("test.dat").ConfigureAwait(false);
            var fileClient = response.Value;
            await using var fs = new MemoryStream();
            var length = fs.Length;
            await fileClient.AppendAsync(fs, 0).ConfigureAwait(false);
            await fileClient.FlushAsync(length).ConfigureAwait(false);
        }
    }
}

```

***Code Snippet***
```csharp
await fileClient.AppendAsync(fs, 0).ConfigureAwait(false);
```

**Expected behavior**
No exception or an error message with a useful error message.

Workaround: Check for length > 0 prior to Append.

**Screenshots**

**Setup (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - IDE : [e.g. IntelliJ] Visual Studio 16.4
 - Version of the Library used 12.0.0-preview.8

**Additional context**

I noticed that AppendAsync closes the stream, you might want to put that into the intellisense comments as it's a bit unusual (some don't close it if you pass it in, some provide a ``close`` bool etc.).

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by seanmcc-msft** [comment]
@tg-msft, I think the stream is being closed in the Core logic.  Also, we will probably need a change in the generator to support checking body?.length != 0.  If we do the check in the convenience layer, we will get the DiagnosticScope error.

**Comment by amishra-dev** [comment]
@tg-msft can you please assign this to someone on the core side?

**Comment by tg-msft** [comment]
Sorry, I'm not really clear on the ask here.
- Is this about letting folks pass empty streams or streams being closed somewhere?
- What is `await using var fs = new MemoryStream();` in the repro doing?
- Do you want validation added to the code generator to throw for empty streams?  What's the error you want thrown?
- Are you asking us to no-op for empty streams in Azure.Core?  Or the generator?
- Are you asking for a change in the way Azure.Core deals with the Content-Length header?

**Comment by Tornhoof** [comment]
My two (three)  cents:
>     * Is this about letting folks pass empty streams or streams being closed somewhere?
Empty Streams
>     * What is `await using var fs = new MemoryStream();` in the repro doing?
Easiest way to create an empty stream with zero length, in reality instead of  ``new MemoryStream();``, you'd have e.g. ``File.OpenRead(...);``
>     * Do you want validation added to the code generator to throw for empty streams?  What's the error you want thrown?
>     * Are you asking us to no-op for empty streams in Azure.Core?  Or the generator?
>     * Are you asking for a change in the way Azure.Core deals with the Content-Length header?
All three possibilities are valid solutions from my pov:
1. The first is a bit harsh to the user, you'd still need the >0 check in user code
2. Depending on where you put that check it might pose problems, checking it directly on the stream requires seekable streams with a valid Length, checking it while writing into the request pipeline might be better. Admittingly I don't know what part is Core and what part is the generator, but I guess the request pipeline is in Core.
3. Depending on where that exception message comes from you might want to look into that code regardless of any other solution, as either the header is formatted wrongly, then the exception message would be correct (like Content-Length: ``<no value here>``) or if the header is really Content-Length: 0 then the exception message is wrong, because it's not about the format of the value of the header.

**Comment by seanmcc-msft** [comment]
@Tornhoof, in uploading a file with a 0 length stream, is your goal to achieve the functionality of  `file.OpenWrite()`?

**Comment by Tornhoof** [comment]
> is your goal to achieve the functionality of file.OpenWrite()?

I'm not sure that I follow. Do you mean that I want to create a remote file which then returns a stream I can use for writing to azdl? Then the answer is no.

I simply have a 0 byte length file on my filesystem (marker file for example) and this needs to be uploaded to azdl too (and exists there as a 0 byte length file).

It's just a bug which is not very visible, occurs only with specific files, making it hard to debug, because who tests their upload logic with zero length files. I certainly did not, a customer noticed the problem, he had an empty "New Text document.txt" in a directory. It took me awhile to find out that the file was empty.

From my POV just short-circuit the append operation if the stream is empty.

**Comment by seanmcc-msft** [comment]
@tg-msft, would you be ok if we checked the stream length in `DataLakeFileClient.Append()`, and not perform the request if content.Length == 0?  I don't think we currently support non-seekable streams, and I'm not sure if we could/plan to.

**Comment by seanmcc-msft** [comment]
I don't know if we should just return if the stream length == 0, that may introduce some ambiguity - the Data Lake service doesn't accept Appends of length 0.

We could manually check the stream length (assuming it is seekable) and throw an ArgumentException with a more specific message.  In this case, the customer would need to check the file length before Append, but it would be more clear what is happening.

**Comment by amnguye** [comment]
Did we still want to go through with a manual check of the stream length that @seanmcc-msft suggested?

@tg-msft would you be okay with that?

**Comment by amnguye** [comment]
We're currently looking into resolving this offline and seeing if the service can produce a more helpful error.

**Comment by amishra-dev** [comment]
@amnguye any updates?

**Comment by navba-MSFT** [comment]
@Tornhoof Apologies for the late reply. We will update this thread once we have more details.

@amnguye @seanmcc-msft Could you please provide an update on this github thread once you get a chance ? Awaiting your reply.
