### ISSUE TITLE
[EventHubs] Rename PartitionManager class to StorageManager

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#9497]
## Summary

In the last couple of months, the Event Hubs client SDK has gone through a lot of changes, and it has been decided that the name `PartitionManager` does not properly suits its type anymore. For this reason, it will be renamed to `StorageManager`.

The type is `internal` and, therefore, this change is not a breaking one.

It's important to note that currently the `PartitionManager` type dwells in the `Azure.Messaging.EventHubs.Processor` project but, when #9198 is merged, it will be moved to `Azure.Messaging.EventHubs.Shared`.

## Goal

Make sure that the type has been renamed and any mention to a "partition manager" has been updated as well, be it in code or in comments. This should apply to all three projects: `Azure.Messaging.EventHubs`, `Azure.Messaging.EventHubs.Processor` and `Azure.Messaging.EventHubs.Shared`, if applicable.

Tests should still pass constantly.

**Comment by Marusyk** [comment]
I would prepare a PR for this. Could you please assign it to me?

**Comment by kinelski** [comment]
@Marusyk I have assigned it to you. Thank you for being interested in contributing!

**Comment by Marusyk** [comment]
I'll start after merge https://github.com/Azure/azure-sdk-for-net/pull/9198
