### ISSUE TITLE
What is the best way to get the region of storage account with connection string

### ISSUE THREAD

**Issue by klogan12** [Azure/azure-sdk-for-net#9500]
**Query/Question**
What is the best way to get the region of storage account with connection string

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by jongio** [comment]
I could not find a way to get region/location with connection string - because that property is exposed at the service level via the management APIs, which authenticate at the service level with service credentials, not connection string.

Are you able to use service credentials or shared key instead of connection string?  If so, then I can help you with that.

**Comment by amishra-dev** [comment]
Thanks for reaching out to us. This feature is not currently supported by the service in the data plane. Management APIs is the right way to figure this out.

**Comment by jongio** [comment]
@klogan12 While you can't access location from connection string, you can use the management plane SDKs with one of the many new authentication mechanisms provided by Azure.Identity.

I created a bridge between the new Azure.Identity objects and the Management plane SDKs called `DefaultAzureMgmtCredential`.

You can see how to use it with the Storage Mgmt plane SDK here: 

https://github.com/jongio/azidext/blob/master/net/JonGallant.Azure.Identity.Extensions.Tests/Mgmt/StorageTests.cs#L16

Please give it a try and LMK if you have any questions.
