### ISSUE TITLE
Bringing back the container permission retrieval using Azure Storage SDK in v11 or future version

### ISSUE THREAD

**Issue by vick-git** [Azure/azure-sdk-for-net#9503]
**Is your feature request related to a problem? Please describe.**
Unable to retrieve container permission using Azure Storage SDK.

**Describe the solution you'd like**
Please bring back the container permission retrieval using Azure Storage SDK in v11 or future version.

**Describe alternatives you've considered**
Moving to user delegate SAS which is a considerably longer route.

**Additional context**
I understand this is a known [case ](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Frest%2Fapi%2Fstorageservices%2Fcreate-user-delegation-sas%23specify-permissions&data=02%7C01%7Cv-vibala%40microsoft.com%7C926c96b07fe74b5e2ccb08d798a83412%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637145720518973177&sdata=GOpTTmOpRgHtdAoNQuXu%2BOAxhKgo02wKlODLNmSn%2B98%3D&reserved=0) but it's causing a lot of longer routes unneccesarily.

**Comment by seanmcc-msft** [comment]
Hi @vick-git, you can retrieve and set container permissions on v12:
```
using Azure.Storage;
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Models;
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;

namespace SignedPermissions
{
    class Program
    {
        private static readonly string accountName = "";
        private static readonly string accountKey = "";
        private static readonly string accountUrl = "";
        private static readonly string containerName = "mycontainer43";

        static async Task Main(string[] args)
        {
            StorageSharedKeyCredential sharedKeyCredential = new StorageSharedKeyCredential(accountName, accountKey);
            BlobServiceClient blobServiceClient = new BlobServiceClient(new Uri(accountUrl), sharedKeyCredential);
            BlobContainerClient containerClient = blobServiceClient.GetBlobContainerClient(containerName);
            try
            {
                // Create Container
                await containerClient.CreateAsync();

                // Get Blob Access Policy, including signed permissions
                BlobContainerAccessPolicy accessPolicy = await containerClient.GetAccessPolicyAsync();

                // Create Signed Permission
                string signedIdentifierId = ToBase64("signedIdentifierId");
                BlobSignedIdentifier signedIdentifier = new BlobSignedIdentifier
                {
                    Id = signedIdentifierId,
                    AccessPolicy = new BlobAccessPolicy
                    {
                        StartsOn = DateTimeOffset.UtcNow,
                        ExpiresOn = DateTimeOffset.UtcNow.AddDays(1),
                        Permissions = "rw"
                    }
                };

                // Set Signed Permission on the Container.
                await containerClient.SetAccessPolicyAsync(permissions: new List<BlobSignedIdentifier>() { signedIdentifier });
            }
            finally
            {
                await containerClient.DeleteAsync();
            }
        }

        private static string ToBase64(string s)
        {
            var bytes = Encoding.UTF8.GetBytes(s);
            return Convert.ToBase64String(bytes);
        }
    }
}

```

**Comment by nzacca** [comment]
@seanmcc-msft I think this might have been opened on my behalf as part of a Microsoft Azure Support ticket. The OP should have read:

`Unable to retrieve container permission using Azure Storage SDK when connecting with Certificate-based Service Principal`

We have been using the StorageSharedKeyCredential just fine but have been unable to use a Certificate to read/change permissions on a container. This used to work but, based on feedback we received from Support, support for this feature was removed around September 2019.

Just curious if that ability will ever resurface itself in the SDK; and if not, is there a brief explanation for why it was removed?

**Comment by nrandell** [comment]
I think I've seen the same thing. Using a connection string to create a blob service client, everything works ok. However using a ClientSecretCredential and giving the client ownership over the storage account I get a 404 trying to read or write the access policy.
