### ISSUE TITLE
ContentLength of Azure.Storage.Files.DataLake.DataLakeFileClient.GetProperties() is zero for existing file

### ISSUE THREAD

**Issue by SamVanhoutte** [Azure/azure-sdk-for-net#9509]
**When executing GetProperties on DataLakeFileClient, the ContentLength is zero**
I have the following piece of code that I want to use to append data to the END of an existing file in Data Lake Gen2 storage account:

```csharp
DataLakeDirectoryClient directory = await CreateDirectoryIfNotExists();
var fileClient = (await directory.CreateFileAsync(fileName)).Value;
var recordContent = "record_line_to_add"
long recordSize = recordContent.Length;

var recordStream = new MemoryStream(Encoding.UTF8.GetBytes(recordContent));
var fileProperties = await fileClient.GetPropertiesAsync();
var fileLength = fileProperties.Value.ContentLength; // This is 0 for an existing file
await fileClient.AppendAsync(recordStream, offset: fileLength);
await fileClient.FlushAsync(position: recordSize);
```

**To Reproduce**
Execute the above code twice for the same file name and you will see there's no data added, but it just got overwritten.  

**Expected behavior**
I would expect to have the length of the existing data file returned.  As I need to length to indicate where I need to start appending the data.  I might be missing something, but then it would be cool to have better guidance on how to append to existing files, as that is quite common for time series data in Data Lake.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by seanmcc-msft** [comment]
Hi @SamVanhoutte, in your code sample, you are actually overriding your existing file when you call 
```await directory.CreateFileAsync()```.  In addition, the position parameter for ```fileClient.FlushAsync()``` should be [previous file size] + [length of the stream] you appended.

I recommend you change the sample to:
```
var fileClient = directoryClient.GetFileClient(fileName);
var recordStream = new MemoryStream(Encoding.UTF8.GetBytes(recordContent));
var fileProperties = await fileClient.GetPropertiesAsync();
var fileLength = fileProperties.Value.ContentLength; // Won't be 0 if the file already exists.
await fileClient.AppendAsync(recordStream, offset: fileLength);
await fileClient.FlushAsync(position: fileLength + recordStream.Length);
```

We're looking into potentially simplifying the FileClient.Append() and .Flush() logic.

**Comment by SamVanhoutte** [comment]
Thanks, @seanmcc-msft 
That works indeed
I agree the Append logic is a bit clumsy and could be better.  I am also looking to find the best way/pattern to CreateIfNotExist directories or files.

**Comment by seanmcc-msft** [comment]
Hi @SamVanhoutte, we have an issue open to add CreateIfNotExists(), Exists(), and DeleteIfExists() to FileSystemClient, DirectoryClient, and FileClient.  https://github.com/Azure/azure-sdk-for-net/issues/9173.  We'll address this soon.
