### ISSUE TITLE
Microsoft.Azure.Management.ResourceManager nuget: only preview releases available?

### ISSUE THREAD

**Issue by srs81** [Azure/azure-sdk-for-net#9517]
**Query/Question**
The Microsoft.Azure.Management.ResourceManager nuget package only has "preview" versions available. The latest available package at this time appears to be 3.0.0-preview, and all the previous releases show "preview" as well. Can we ever expect a non-preview / production release?

***Why is this not a Bug or a feature Request?***
I'm expecting this is by design. Would just like to get clarification that we can go ahead with using the preview releases in production code.

**Setup (please complete the following information if applicable):**
 - OS: Windows 10
 - IDE : Visual Studio 2019
 - Currently using 2.2.0-preview but would like to upgrade to production release when available
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [Yes] Query Added
- [Yes] Setup information Added

**Comment by nickzhums** [comment]
@srs81 We are working with ResourceManager to publish a release. We'll keep you updated

**Comment by AlexGhiondea** [comment]
@nickzhums any update on this?

**Comment by nickzhums** [comment]
@AlexGhiondea still working with the team on this, there was talk to GA the package but it was not finalized

**Comment by MisinformedDNA** [comment]
@nickzhums Yes, but 6 years without a GA?! That just blows my mind.

**Comment by nickzhums** [comment]
@MisinformedDNA i agree, let me circle back to the team

**Comment by abatishchev** [comment]
@TianoMS, @ravbhatnagar ping

**Comment by srs81** [comment]
@SaurabhSharma-MSFT thanks for the clarification. Ironically, I see that the [new Azure.ResourceManager.Resources package](https://www.nuget.org/packages/Azure.ResourceManager.Resources/) they point to is also still only in beta and two months old at this point 😅 But glad to know of the new direction, will keep an eye on the newer nuget package for future updates, thanks for the information, I'll close this issue accordingly.
