### ISSUE TITLE
Log Diagnostic Scope Start/Stop/Fail

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#9519]
We've got great operation names for diagnostic scopes that would be nice to associate with our HTTP logs.  We should add additional events to our AzureCoreEventSource to expose this info.

See #9274 for additional discussion.

**Comment by pakrym** [comment]
Moving to backlog for now.

**Comment by pakrym** [comment]
We didn't have many customer asks for this and distributed tracing provides similar functionality.
