### ISSUE TITLE
How to enable client side log for Azure Storage sdk in .net core

### ISSUE THREAD

**Issue by HengzheLi** [Azure/azure-sdk-for-net#9538]
I found this link https://docs.microsoft.com/en-us/rest/api/storageservices/client-side-logging-with-the-.net-storage-client-library that describs how to enable client-side log for storage sdk under .net framework.
Is there a way to enable it in .net core?
I tried to enable it using code as the configuration file could not used in .net core and found that the "sharedListeners" is not impletemented in current .net core framework.
Any suggestion?

**Comment by jsquire** [comment]
//cc: @JoshLove-msft, @tg-msft

**Comment by amishra-dev** [comment]
Josh is looking into this.

**Comment by JoshLove-msft** [comment]
Hi @HengzheLi,
Can you take a look at https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/core/Azure.Core#setting-up-console-logging? This would be how to get logging set up assuming you are using the Version 12 storage library.

**Comment by HengzheLi** [comment]
> Hi @HengzheLi,
> Can you take a look at https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/core/Azure.Core#setting-up-console-logging? This would be how to get logging set up assuming you are using the Version 12 storage library.

Oh, I forgot to tell I am using version 11. Because the Client-Side encrytion feature still is not released in version 12 yet. So I think I can't upgrade to 12 for now.

**Comment by JoshLove-msft** [comment]
I found a similar issue in the storage sdk repo - https://github.com/Azure/azure-storage-net/issues/870
where it is indicated that this is a known issue. 
@seanmcc-msft is the latest comment from that issue still accurate - that logging won't work with .NET Core using the V11 library and there is no way to address it?

**Comment by JoshLove-msft** [comment]
Assigning back to @amishra-dev as this appears to be a known issue with the Pre-V12 libraries. See https://github.com/Azure/azure-storage-net/issues/870

**Comment by HengzheLi** [comment]
@JoshLove-msft  Thanks for the link. I check https://github.com/Azure/azure-storage-net/issues/870. But it seems that there is no conclusion and solution at all.
I leave a message asking if it works using DiagnosticSource

**Comment by kasobol-msft** [comment]
@HengzheLi Adding DiagnosticSource as debug events/logs destination would be a new feature request. There's no support for that now.
I can see that your upgrade to V12 was blocked by lack of client side encryption support. Recently we added encryption support and it's available in Azure.Strorage.Blobs 12.5.0-preview.5 .

**Comment by HengzheLi** [comment]
> @HengzheLi Adding DiagnosticSource as debug events/logs destination would be a new feature request. There's no support for that now.
> I can see that your upgrade to V12 was blocked by lack of client side encryption support. Recently we added encryption support and it's available in Azure.Strorage.Blobs 12.5.0-preview.5 .

@kasobol-msft Thanks for the news. Has the estimated date to release a final offical version as it is in preview version and it will be used in our production envrionment?

**Comment by kasobol-msft** [comment]
@HengzheLi Some time in August.

**Comment by HengzheLi** [comment]
Hi @kasobol-msft, I found 12.5.0 was released. But it seems it was not included the Client-Side encryption in this version. https://github.com/Azure/azure-sdk-for-net/blob/Azure.Storage.Blobs_12.5.0/sdk/storage/Azure.Storage.Blobs/CHANGELOG.md

So does the Client-Side encryption feature still need to be waited for another release?

**Comment by jsquire** [comment]
As 12.6.0 is now GA,  I'm going to close this out.  Please feel free to reopen if you feel that further discussion is needed.
