### ISSUE TITLE
[BUG] 500ms timeout on IMDS available probe is too aggressive 

### ISSUE THREAD

**Issue by neilrees** [Azure/azure-sdk-for-net#9550]
**Describe the bug**
When using `ManagedIdentityCredential` to run in the context of a Managed Identity in Azure, a probe is made to `http://169.254.169.254/metadata/identity/oauth2/token` to test whether a managed identity is available or not.  The timeout on this request is 500ms and the response (or lack of) is cached and cannot be cleared/refreshed.  The 500ms timeout cannot be configured.
https://github.com/Azure/azure-sdk-for-net/blob/b0ff97d220ec1e83d43767d693b17a3b6245314e/sdk/identity/Azure.Identity/src/ManagedIdentityClient.cs#L22

On a weak or busy instance, this causes the Msi to be marked as unavailable and it cannot be cleared without relaunching the process.

***Exception or Stack Trace***
https://github.com/Azure/azure-sdk-for-net/blob/b0ff97d220ec1e83d43767d693b17a3b6245314e/sdk/identity/Azure.Identity/src/ManagedIdentityClient.cs#L122

**To Reproduce**
Attempt to use managed identities on a stressed server, or use a proxy to intercept the probe to ensure the response is not received in 500ms.

***Code Snippet***
```
                var accountUri = new Uri("https://storageaccountname.blob.core.windows.net/");
                var client = new BlobServiceClient(accountUri, new ManagedIdentityCredential());
                var containerClient = client.GetBlobContainerClient("container");
                var blobClient = containerClient.GetBlobClient("blob");

                await blobClient.DownloadToAsync(new MemoryStream());
```

**Expected behavior**
* `blobClient` should use the Managed Identity that is available to it.
* It should be possible to configure the 500ms timeout.
* It should be possible to refresh/reset the Msi status in the case of an error without having to restart the process

**Setup (please complete the following information):**
 - Docker Image: mcr.microsoft.com/windows/servercore:ltsc2019
 - Azure.Identity: 1.1.0

**Comment by schaabs** [comment]
@neilrees Thanks for filing this issue. There are a couple of changes in merged in PR #9025 which should address your issue. First of all the IMDS instance discovery timeout has been increased from 500ms to 1000ms. Also, the discovery is no longer cached statically. So if the original discovery fails you can retry by creating a new instance of the `ManagedIdentityCredential`.

This fix will be included in the next release of Azure.Identity which is currently scheduled for mid February. Please feel free to reopen this issue if you still have problems with this fix in place.
