### ISSUE TITLE
Review use of `await using` and ensure that it is synchronization context agnostic

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#9564]
# Summary

In order to ensure that the library is as performant and well-behaved as possible for those using it, the library must ensure that it is following best practices and is  agnostic to the synchronization context.   To this end, all instances where an asynchronous operation is awaited should make use of `ConfigureAwait(false)`.   

Within the codebase, there are some instances which consume an `IAsyncDisposable` making use of the `await using` syntax introduced in C# 8.   In order to ensure that these instances are configured to ignore the synchronization context, it is not possible to just append `ConfigureAwait(false)` to the statement.   Instead, one of the following patterns should be applied:

```csharp
var instance = new SomeDisposableType();
await using var instanceAwaitable = instance.ConfigureAwait(false);

instance.DoThings();
```

```csharp
var instance = new SomeDisposableType();

await using (instance.ConfigureAwait(false))
{
      instance.Dothings();
}
```

# Scope of Work

- Identify areas within the codebase that make use if `IAsyncDisposable` types which do not adhere to one of the patterns which allows `ConfigureAwait(false)` to be applied.

- Adjust those occurrences identified to ensure that `ConfigureAwait(false)` is properly invoked.

# Success Criteria

- The refactoring and enhancements detailed by the scope have been completed; all uses of `IAsyncDisposable` types properly ignore the synchronization context.

- The tests necessary for its validation have been created or adjusted and pass reliably.

- The existing test suite continues to produce deterministic results and pass reliably.

# References

- [Using ConfigureAwait in "await using" declaration ](https://github.com/dotnet/csharplang/issues/2661)

**Comment by maririos** [comment]
Thanks for the documentation and the links to additional resources!

**Comment by AlexanderSher** [comment]
Btw, this is handled by our analyzers ([with braces](https://github.com/Azure/azure-sdk-tools/blob/2f629a4a460525a28edf80361e1b7ef257d21736/src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0012Tests.cs#L314) or [without](https://github.com/Azure/azure-sdk-tools/blob/2f629a4a460525a28edf80361e1b7ef257d21736/src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0012Tests.cs#L377))
