### ISSUE TITLE
UX Study feedback

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#9574]

**Comment by annelo-msft** [comment]
This includes:
https://github.com/azure/azure-sdk-for-net/issues/8900
https://github.com/azure/azure-sdk-for-net/issues/8896
https://github.com/azure/azure-sdk-for-net/issues/8894
https://github.com/azure/azure-sdk-for-net/issues/8781

**Comment by maririos** [comment]
PRs created after today's studies:
- https://github.com/Azure/azure-sdk-for-net/pull/9594
- https://github.com/Azure/azure-sdk-for-net/pull/9592
- https://github.com/Azure/azure-sdk-for-net/pull/9593

**Comment by maririos** [comment]
More issues:
- https://github.com/Azure/azure-sdk-for-net/issues/9688

**Comment by maririos** [comment]
Questions for service team: https://github.com/Azure/azure-sdk-for-net/issues/9722

**Comment by maririos** [comment]
All questions/concerns/changes raised during the UX study have been documented as an issue. Also, most of them have been addressed for P2.
I'm going to close this issue and keep updating the individual ones.
