### ISSUE TITLE
[BUG] [Storage] BlobServiceClient.SetProperties fails with default values

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#9583]
### Bug
Attempting to call `BlobServiceClient.SetPropertiesAsync` with just `Cors` will fail:

```C#
BlobServiceClient blobClient = GetBlobClientFromSomewhere();
await blobClient.SetPropertiesAsync(
    new BlobServiceProperties
    {
        Cors = new[] { new BlobCorsRule { AllowedOrigins = "*", AllowedMethods = "GET,HEAD" } },
    });
```

with a response like:

```HTTP
HTTP/1.1 400 XML specified is not syntactically valid.
Content-Length: 331
Content-Type: application/xml
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 6b21a621-c01e-0087-626f-d1de6b000000
x-ms-client-request-id: 14cf7a3f-a116-44ac-8e0b-8768019ffbf1
x-ms-version: 2019-02-02
x-ms-error-code: InvalidXmlDocument
Date: Wed, 22 Jan 2020 22:02:55 GMT

<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidXmlDocument</Code><Message>XML specified is not syntactically valid.
RequestId:6b21a621-c01e-0087-626f-d1de6b000000
Time:2020-01-22T22:02:56.4989894Z</Message><LineNumber>1</LineNumber><LinePosition>48</LinePosition><Reason>Unexpected value for Version.</Reason></Error>
```

because some of the default values of `BlobServiceProperties` are considered invalid by the service.

### Work Arounds
You can work around this issue by either getting an existing `BlobServiceProperties` instance from `BlobServiceClient.GetPropertiesAsync` _(which is safer because then you'll leave existing properties unchanged)_:

```C#
BlobServiceClient blobClient = GetBlobClientFromSomewhere();
BlobServiceProperties properties = await blobClient.GetPropertiesAsync();
properties.Cors = new[] { new BlobCorsRule { AllowedOrigins = "*", AllowedMethods = "GET,HEAD" } };
await blobClient.SetPropertiesAsync(properties);
```

Or if you don't want to make an extra service call, you can null out a few problematic fields:

```C#
BlobServiceClient blobClient = GetBlobClientFromSomewhere();
await blobClient.SetPropertiesAsync(
    new BlobServiceProperties
    {
        Cors = new[] { new BlobCorsRule { AllowedOrigins = "*", AllowedMethods = "GET,HEAD" } },
        Logging = null,
        HourMetrics = null,
        MinuteMetrics = null
    });
```

### Proposed Fix
We should set reasonable defaults for the problematic fields in `BlobAnalyticsLogging` and `BlobMetrics` that are causing this to fail.  This fix should also apply to the properties of Queues and Files as well.

**Comment by tg-msft** [comment]
`BlobServiceProperties.StaticWebsite` is also problematic, depending on the account type.

**Comment by ChrisFulstow** [comment]
@tg-msft This is also the case if you call `BlobServiceClient.SetPropertiesAsync` with just `Logging` set, the defaults for `MinuteMetrics` and `HourMetrics` don't include a `Version` which causes the request to fail.

Also, there's an issue if you get the existing `BlobServiceProperties` and there're no CORS rules. The default of an empty list doesn't serialize back into the request correctly, you need to null it out so it's omitted.

```
var properties = (await client.GetPropertiesAsync()).Value;
if (!properties.Cors.Any()) { properties.Cors = null; }
await client.SetPropertiesAsync(properties);
```

**Comment by kasobol-msft** [comment]
I have a customer reporting the following:

A few things I was surprised about here:
1)	Default construction of BlobServiceProperties will result in HTTP 400
2)	So much work required to get it working
3)	We default to initializing everything, which will overwrite all properties on the account (the API works like PATCH, even if it isn’t PATCH)
4)	No enum or anything for the 1.0?

```
            BlobServiceClient serviceClient = new BlobServiceClient(connectionString);

            // This fails with HTTP body saying "Unexpected value for Version.", which is talking about the Version element underneath Logging.
            {
                try
                {
                    BlobServiceProperties properties = new BlobServiceProperties();
                    serviceClient.SetProperties(properties);
                }
                catch
                {
                }
            }

            // This fails with HTTP body saying "Element is missing: Version.".
            {
                try
                {
                    BlobServiceProperties properties = new BlobServiceProperties();

                    properties.Logging.Version = "1.0";

                    serviceClient.SetProperties(properties);
                }
                catch
                {
                }
            }

            // This works!!
            {
                BlobServiceProperties properties = new BlobServiceProperties();

                properties.Logging.Version = "1.0";
                properties.HourMetrics.Version = "1.0";
                properties.MinuteMetrics.Version = "1.0";

                serviceClient.SetProperties(properties);
            }
```

**Comment by JimSuplizio** [comment]
Hi @tg-msft, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
