### ISSUE TITLE
Include Blobs.Cryptography in ApiCompat.csproj once it is GA'ed

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#9586]
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/126/API-Compatibility-Verification-.NET

Steps to include Blobs.Cryptography:

Update eng/ApiCompat/ApiCompat.csproj to include package references for the Blobs.Cryptography library.
Update eng/Packages.Data.props to include the current versions of the packages.
Remove EnableApiCompat param (or set to true) from Blobs.Cryptography csproj file.

**Comment by seanmcc-msft** [comment]
We chose to not release Blobs.Cryptography, and instead include crypto in the main Blobs package.
