### ISSUE TITLE
[BUG] Consider updating CopyTo usage in sync download to respect CancellationToken

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#9589]
In PartitionedDownloader, we have a private [CopyTo ](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/PartitionedDownloader.cs#L277 )method that is called to copy the download result into our output stream. In this method we check the cancellation token, and then call CopyTo on the download result.  There is no CopyTo overload for streams that accepts a cancellationToken, so depending on the size of the stream we are attempting to copy, we might get into a situation where the cancellationToken should have timed out but we aren't actually checking for it. 
This is mitigated by the fact that unless this is the last block of the blob, the token would get cancelled while attempting to download the next block.

We should abstract out the code that is used by Core in [RequestContent ](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/RequestContent.cs#L100)to have a CopyTo method that respects cancellationTokens.

**Comment by JoshLove-msft** [comment]
Similar to https://github.com/Azure/azure-sdk-for-net/issues/8847

**Comment by JimSuplizio** [comment]
Hi @JoshLove-msft, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
