### ISSUE TITLE
[BUG] README.md for repository contains information from November

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-sdk-for-net#9597]
**Describe the bug**
The root README.md provides information from the November 2019 release rather than the latest releases.

**To Reproduce**

1. Go to https://github.com/azure/azure-sdk-for-net
2. Read the README.md file
3. Compare to the latest release notes on https://azure.github.io/azure-sdk

**Setup (please complete the following information):**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by AlexGhiondea** [comment]
This has been addressed.
