### ISSUE TITLE
[BUG] Serializing and Deserializing an Index throws Requested value 'ScoringFunction' was not found. error

### ISSUE THREAD

**Issue by larryeby** [Azure/azure-sdk-for-net#9602]
**Describe the bug**
When serializing and deserializing an index using the Microsoft.Azure.Search.Services package, it fails to update when Indexes.CreateOrUpdateAsync is called.
Edit: This seems to only be an issue with indexes with scoring profiles.

***Exception or Stack Trace***
Exception message:
"The request is invalid. Details: index : Requested value 'ScoringFunction' was not found.\r\n"
```
"   at Microsoft.Azure.Search.IndexesOperations.<CreateOrUpdateWithHttpMessagesAsync>d__9.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()\r\n   at Microsoft.Azure.Search.IndexesOperationsExtensions.<CreateOrUpdateAsync>d__1.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at [REDACTED].<UpdateIndexes>d__2.MoveNext() in [REDACTED] 85\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at [REDACTED].<UpdateOrCreateSearchIndex>d__1.MoveNext() in [REDACTED]"
```

**To Reproduce**
1) Get the index using the SearchServiceClient class
2) Serialize the index.
3) Deserialize the index.
4) Change the etag.
5) Update the index.

***Code Snippet***
```
var index = await serviceClient.Indexes.GetAsync("[INDEX_NAME]");
var jsonIndex = JsonConvert.SerializeObject(index);
var rebuiltIndex = JsonConvert.DeserializeObject<Index>(jsonIndex);
rebuiltIndex.ETag = "*";
await serviceClient.Indexes.CreateOrUpdateAsync(rebuiltIndex);
```

**Expected behavior**
The index is updated.

**Screenshots**
n/a

**Setup (please complete the following information):**
 - OS: Windows
 - IDE : Visual Studio 2019
 - Version of the Library used: Happens in 9.1.0 and 10.1.0

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by brjohnstmsft** [comment]
@larryeby In the repro you shared, it looks like you're not using any `JsonSerializerSettings`. There's no guarantee that the index is going to round-trip through JSON correctly such that it will still be well-formed when you pass it back to the API. That's outside of the SDK's control.

Model classes like `Index` are designed to be used with the SDK's own serializer settings, for the sole purpose of serializing JSON requests and deserializing responses from the REST API. You can certainly try to serialize them yourself, but getting the details right is up to you. I'm happy to help troubleshoot, but I just want to make it clear that this is not a scenario that the SDK supports out of the box.

**Comment by larryeby** [comment]
Thanks for the response. I'm currently looking into the right way to serialize/deserialize this. It's something that has to be done on our end due to the use of Azure functions / durable tasks.

I've also just generated a new instance of Index and supplied all the fields with the same values with the same issue:

```
              var newIndex = new Index(
                    rebuiltIndex.Name,
                    rebuiltIndex.Fields,
                    rebuiltIndex.ScoringProfiles.Select(x => new ScoringProfile(
                        x.Name,
                        x.TextWeights,
                        x.Functions.Select(y => new ScoringFunction(y.FieldName, y.Boost, y.Interpolation)).ToList(),
                        x.FunctionAggregation)).ToList(),
                    rebuiltIndex.DefaultScoringProfile,
                    rebuiltIndex.CorsOptions,
                    rebuiltIndex.Suggesters,
                    rebuiltIndex.Analyzers,
                    rebuiltIndex.Tokenizers,
                    rebuiltIndex.TokenFilters,
                    rebuiltIndex.CharFilters);
```
These fields look to be populated properly in the debugger, so unsure where the disconnect could be. 

If I remove the scoring profiles, this works fine. The issues seems to be specifically in the scoring profile. This also doesn't reproduce on DataSources, Indexers, or Skillsets. The serialization is fine.

My scenario is that I'm using an Azure Function to read a JSON string that is the index. I need to do it this way, since I'm updating a ton of environments from blob storage.

My workaround currently is to avoid the SDK and just make calls to the API, but I'm really hoping to continue using the SDK.

**Comment by brjohnstmsft** [comment]
I think I know what the problem is. `ScoringFunction` is not an abstract class, but it actually should be. You need to ensure that when serializing, the type of the function is captured as a property in the JSON, and when deserializing, that type is used to instantiate the right derived class.

**Comment by larryeby** [comment]
Ah, I see. That makes a lot of sense. Thanks for taking a look at this. Is ScoringFunction going to be converted to an abstract class? Is that something I can put up a PR for? If not, I can close this issue out.

**Comment by brjohnstmsft** [comment]
@larryeby We're working on a brand new .NET SDK for Azure Cognitive Search based on the new [Azure API guidelines](https://azure.github.io/azure-sdk/dotnet_introduction.html), so there isn't much point in fixing it in the current SDK since we don't have any future releases planned.

I'll create a new issue to track this for the new SDK and close out this one.

**Comment by AFDevMike** [comment]
I am getting this error
`"The request is invalid. Details: index : Requested value 'ScoringFunction' was not found.\r\n"`

 using `Microsoft.Azure.Search` Version 10.1.0 specifically after adding Scoring Profiles(functionality / property) to our `Index`.  I am using strongly typed classes and no `json` literals.  Would this be the same issue or shall I make another?

**Comment by brjohnstmsft** [comment]
@AFDevMike That sounds like a different problem. Please create a new issue and include a minimal repro if possible.
