### ISSUE TITLE
[FEATURE REQ] IProgress<long> support in ShareFileClient Download

### ISSUE THREAD

**Issue by DouglasIsaksson** [Azure/azure-sdk-for-net#9605]
**Is your feature request related to a problem? Please describe.**
Having support for IProgress in Upload, it feels kinda wonky to need to write a custom solutions for download.

**Describe the solution you'd like**
IProgress<long> support in ShareFileClient Download/DownloadAsync

**Additional context**
This has been submitted for BlobClient already but I feel it's just as important for ShareFileClient.

**Comment by seanmcc-msft** [comment]
Related https://github.com/Azure/azure-sdk-for-net/issues/8506

**Comment by amishra-dev** [comment]
Closing this is a duplicate of https://github.com/Azure/azure-sdk-for-net/issues/8506
