### ISSUE TITLE
[FEATURE REQ] Support for Exists in ShareFileClient

### ISSUE THREAD

**Issue by DouglasIsaksson** [Azure/azure-sdk-for-net#9606]
**Is your feature request related to a problem? Please describe.**
I Kinda wish traversing Files was more like the BlobClient instead of having to traverse from Share to Directory and then to File.
It would be nice if I could use a hierarchical path directly to build a ShareFileClient off a ShareClient, like _shareClient.GetFileClient("myDirectory/myOtherDirectory/file.txt") then use Exists() directly on the ShareFileClient created. 

**Describe the solution you'd like**
Exists() method equivalent to what BlobClient has.

**Describe alternatives you've considered**
The alternative is to use GetFilesAndDirectoriesAsync() and verify if your Uri is in the results returned but that's a bit wonky and inconsistent with BlobClient. Being able to build the ShareFileClient based on a Uri and then just check Exists is preferable.

**Comment by amnguye** [comment]
Hi,

We actually have an issue open to implement this feature request.

#7878 

Please track the progress there. I will close this issue for now and any comments feel free to leave on the existing one.
