### ISSUE TITLE
[FEATURE REQ] Upload/Download consistency across Blobs and Files.Shares clients

### ISSUE THREAD

**Issue by DouglasIsaksson** [Azure/azure-sdk-for-net#9608]
**Is your feature request related to a problem? Please describe.**
BlobClient has a DownloadTo method for Parallel download. No parallel UploadFrom() method though. 
ShareFileClient has neither a UploadFrom or DownloadTo method. 

**Describe the solution you'd like**
Support for UploadFrom/DownloadTo in ShareFileClient
Support for UploadFrom in BlobClient

**Comment by seanmcc-msft** [comment]
Hi, thanks for the feature suggestions.  @tg-msft and @KrzysztofCwalina, what do you think?

**Comment by blueww** [comment]
Please support parallel download/upload for all kinds of blob and Azure File. include progress handler.

**Comment by navba-MSFT** [comment]
@DouglasIsaksson Apologies for the late reply.

@seanmcc-msft Could you please update this github thread once you get a chance ? Awaiting your reply.

**Comment by JimSuplizio** [comment]
Hi @DouglasIsaksson, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
