### ISSUE TITLE
[FEATURE REQ] Bring back NameValidator

### ISSUE THREAD

**Issue by MattGal** [Azure/azure-sdk-for-net#9611]
**Is your feature request related to a problem? Please describe.**
There's no easy way to validate a given string is going to be a valid container name.  Regex's are tough to get right and some of the rules are not obvious (e.g. " no --") A simple call like NameValidator.ValidateContainerName(...) is way easier, but is not provided by any of the new storage libraries.

**Describe the solution you'd like**
Clone the previous NameValidator into a common, shared modern storage library so users don't have to reference both old and new packages to get this functionality. 

**Describe alternatives you've considered**
We're currently referencing the old and new packages already.  If we stopped doing this, it'd either be a regex or trying anyways and trying to differentiate from the exception thrown.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by jsquire** [comment]
//cc: @tg-msft, @JoshLove-msft

**Comment by tg-msft** [comment]
We shied away from anything that validated service behavior in our first couple of releases, but I think the need here is obvious and would be fine as long as we didn't use it to guard service calls (i.e., you can check if it thinks a name is valid and decide how to proceed, but we won't check anything when making `Create` calls).

We should loop in the Arch Board to figure out the right pattern when the Storage team decides to implement because a lot of other services could use something like this as well.

**Comment by amishra-dev** [comment]
@seanmcc-msft please triage tomorrow.

**Comment by mithunshanbhag** [comment]
Anyone know what's the latest status on this? Any alternatives or workaround while using SDK 12?

**Comment by zmarty** [comment]
Folks, why don't we still have a name validator? Every big project needs to write their own, it's a waste of resources. Also, the old library had it, so it's not like this is a new ask. Please, just be at parity.

**Comment by juliusl** [comment]
Made a self-contained port that you can drop into your namespace,

https://gist.github.com/juliusl/5f4a3ade5440be1f71ffd531fb7dc401

**Comment by boiled-water-tsar** [comment]
Came here from a StackOverflow issue. Would love some validator especially since the Blob client at least has a bad habit of not throwing when an invalid name is hit !

**Comment by JimSuplizio** [comment]
Hi @MattGal, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
