### ISSUE TITLE
[BUG] DefaultAzureCredential fails when using Managed Identity from Function to Blob

### ISSUE THREAD

**Issue by CKHere** [Azure/azure-sdk-for-net#9616]
**Describe the bug**
I am trying to write a Blob from a function using a Managed Identity, through the DefaultAzureCredential. However, I get an exception, which I don't understand, as it references Environment variables.

***Exception or Stack Trace***
Error: Azure.Identity.AuthenticationFailedException: The DefaultAzureCredential failed due to an unhandled exception:  ManagedIdentityCredential failed with unhandled exception The authentication request failed due to an unhandled exception.  See inner exception for details..
  EnvironmentCredential is unavailable Environment variables not fully configured. AZURE_TENANT_ID and AZURE_CLIENT_ID must be set, along with either AZURE_CLIENT_SECRET or AZURE_USERNAME and AZURE_PASSWORD. Currently set variables [  ].
  ManagedIdentityCredential failed with The authentication request failed due to an unhandled exception.  See inner exception for details..
See inner exception for more detail. ---> System.AggregateException: The DefaultAzureCredential failed due to an unhandled exception:  ManagedIdentityCredential failed with unhandled exception The authentication request failed due to an unhandled exception.  See inner exception for details.. (Environment variables not fully configured. AZURE_TENANT_ID and AZURE_CLIENT_ID must be set, along with either AZURE_CLIENT_SECRET or AZURE_USERNAME and AZURE_PASSWORD. Currently set variables [  ]) (The authentication request failed due to an unhandled exception.  See inner exception for details.) ---> Azure.Identity.CredentialUnavailableException: Environment variables not fully configured. AZURE_TENANT_ID and AZURE_CLIENT_ID must be set, along with either AZURE_CLIENT_SECRET or AZURE_USERNAME and AZURE_PASSWORD. Currently set variables [  ]
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at SearchEnginesAPI.Services.AzTest.Test() in C:\DIMA_WORK\DIMA-CG-GraphicsInsight\src\Azure-GraphicsInsight\SearchEnginesAPI\Services\AzTest.cs:line 66
   at SearchEnginesAPI.Controllers.AzureTest.Run(HttpRequest req, ILogger log) in C:\DIMA_WORK\DIMA-CG-GraphicsInsight\src\Azure-GraphicsInsight\SearchEnginesAPI\Controllers\AzureTest.cs:line 34

**To Reproduce**
Every time I call a function endpoint, where I call the below test code.

***Code Snippet***
    class AzTest : IAzTest
    {
        public async Task<string> Test()
        {
            string storageEndpoint = string.Format("https://{0}.blob.core.windows.net", "dimacgaztest");
            string containerEndpoint = string.Format("{0}/{1}", storageEndpoint, "aztest");
            string blobName = "azBlobTest.txt";
            string blobEndpoint = string.Format("{0}/{1}", containerEndpoint, blobName);

            //** Access using DefaultAzureCredentials
            // Construct the blob container endpoint from the arguments.
            // Get a credential and create a client object for the blob container.
            BlobContainerClient containerClient = new BlobContainerClient(new Uri(storageEndpoint), new DefaultAzureCredential(true));

            // Create the container if it does not exist.
            // await containerClient.CreateIfNotExistsAsync();

            try
            {

                // Upload text to a new block blob.
                string blobContents = "This is another test block blob.";
                byte[] byteArray = Encoding.ASCII.GetBytes(blobContents);

                using (MemoryStream stream = new MemoryStream(byteArray))
                {
                    await containerClient.UploadBlobAsync(blobName, stream);
                }
            }
            catch (Exception e)
            {
                throw e;
            }
            /**/

            return "OK";
        }

**Expected behavior**
I expect a blob to appear in my container. When I use the following code everything works.

***Code Snippet***
    class AzTest : IAzTest
    {
        public async Task<string> Test()
        {
            string storageEndpoint = string.Format("https://{0}.blob.core.windows.net", "dimacgaztest");
            string containerEndpoint = string.Format("{0}/{1}", storageEndpoint, "aztest");
            string blobName = "azBlobTest.txt";
            string blobEndpoint = string.Format("{0}/{1}", containerEndpoint, blobName);

            //** Access using Managed Credential
            AzureServiceTokenProvider azureServiceTokenProvider = new AzureServiceTokenProvider();
            string accessToken = azureServiceTokenProvider.GetAccessTokenAsync(storageEndpoint).Result;
            var tokenCredential = new TokenCredential(accessToken);
            var storageCredentials = new StorageCredentials(tokenCredential);
            CloudBlockBlob blockBlob = new CloudBlockBlob(new Uri(blobEndpoint), storageCredentials);

            try
            {

                // Upload text to a new block blob.
                string blobContents = "This is a test block blob.";
                blockBlob.UploadText(blobContents);
            }
            catch (Exception e)
            {
                throw e;
            }
            /**/

            return "OK";
        }
    }
 

**Screenshots**

**Setup (please complete the following information):**
 - OS: Linux Function App
 - IDE : Visual Studio Enterprise 2019
 - Version of the Library used: 
.Net Core 3.1
Azure.Identity 1.1.0
Azure.Storage.Blobs 12.2.0
Microsoft.Azure.Services.AppAuthentication 1.3.1
Microsoft.Azure.Storage.Blob 11.1.2
Microsoft.Azure.Storage.Auth  (11.1.2?)

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ X ] Bug Description Added
- [ X ] Repro Steps Added
- [ X ] Setup information Added

**Comment by CKHere** [comment]
In the failing code snippet I have used:

** Snippet **
new BlobContainerClient(new Uri(storageEndpoint), new DefaultAzureCredential(true))

This should have been:

** Snippet **
new BlobContainerClient(new Uri(containerEndpoint), new DefaultAzureCredential(true))

But both fails with the same exception

**Comment by jsquire** [comment]
//cc: @schaabs, @tg-msft

**Comment by schaabs** [comment]
@CKHere  Thanks for filing this issue. Sorry you're running into this trouble. We're currently looking into this issue and from the information you've provided it seems that the ManagdIdentityCredenitial is throwing an exception when attempting to authenticate. Unfortunately the exception details thrown from the DefaultAzureCredential are less than optimal and don't have the information we need to diagnose the issue you're encountering. We're working on reproducing your issue, but if you have a reliable repro you could debug and could provide a bit more info, it would help us out to get this issue fixed.

Can you use visual studio to [remote debug the function](https://markheath.net/post/remote-debugging-azure-functions) and break on all exceptions (https://docs.microsoft.com/en-us/visualstudio/debugger/managing-exceptions-with-the-debugger?view=vs-2019) and copy the exception details for the exception that gets thrown when ManagedIdentityCredential.GetToken is on the stack.

Alternatively, if you modify the catch statement to print the inner exceptions corresponding to the ManagedIdentityCredential as below this would also give us the information needed.

~~~c#
        try
        {

            // Upload text to a new block blob.
            string blobContents = "This is another test block blob.";
            byte[] byteArray = Encoding.ASCII.GetBytes(blobContents);

            using (MemoryStream stream = new MemoryStream(byteArray))
            {
                await containerClient.UploadBlobAsync(blobName, stream);
            }
        }
        catch (Exception e)
        {
            foreach(var inner in ((AggregateException)e.InnerException).InnerExceptions)
            {
                if(inner.Message.Contains("ManagedIdentityCredential"))
                {
                     Console.WriteLine(inner.ToString());

                     Console.WriteLine(inner.InnerException.ToString());
                }
            } 
        }
~~~

**Comment by jongio** [comment]
@CKHere - I was able to successfully use your code in a Linux Azure Function.   

1. Did you assign the Blob Contributor role to the managed identity?

Use this command to get the identity Id:

```
az functionapp identity show --name <func name>--resource-group <rg name>
{
  "principalId": "f29b5b4e-b9bb-493c-a714-7fa2cda85c4b",
  "tenantId": "72f988bf-86f1-41af-91ab-2d7cd011db47",
  "type": "SystemAssigned",
  "userAssignedIdentities": null
}
```

Use this command to assign the role:
```
az role assignment create --assignee <id from above> --role b7e6dc6d-f1e8-4753-8033-0f276bb0955b --scope /subscriptions/<subid>/resourceGroups/<rg>/providers/Microsoft.Storage/storageAccounts/<storage account name>/blobServices/default/containers/<container name>
```

Rerun the code and see if it works.

2. You need to update your code to dynamically generate the file name on each run - it will fail if you try to upload a blob with the same name

3. Have you inspected the logs via the Azure portal to see if you can get a better error message?


Something to note - Managed Identity will not work on your local machine.  To get it to run locally, you need to create a service principal to use on you local machine and add the following to your local.settings.json file

Create sp:
```
az ad sp create-for-rbac
```

Update settings:


```
{
    "IsEncrypted": false,
    "Values": {
        "AzureWebJobsStorage": "UseDevelopmentStorage=true",
        "FUNCTIONS_WORKER_RUNTIME": "dotnet",
        "AZURE_CLIENT_ID": "<id>",
        "AZURE_CLIENT_SECRET": "<secret>",
        "AZURE_TENANT_ID": "<tenant>"
    }
}
```

And use the same `role assignment` command as above with that service principal id.

Let us know if that solves it for you.

**Comment by CKHere** [comment]
@jongio 

I am mainly using the portal, but I am fairly sure I have set the role. However, what puzzled me was when trying to run the az functionapp identity command, I get an error:
`The command failed with an unexpected error. Here is the traceback:

'NoneType' object has no attribute 'identity'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\commands\__init__.py", line 608, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\commands\__init__.py", line 666, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\commands\__init__.py", line 659, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\six\six.py", line 696, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\commands\__init__.py", line 636, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\commands\__init__.py", line 306, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\commands\arm.py", line 749, in handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\commands\arm.py", line 761, in show_exception_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\commands\arm.py", line 747, in handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli\azure\cli\command_modules\appservice\custom.py", line 647, in show_identity
AttributeError: 'NoneType' object has no attribute 'identity'
`
However, if I go to the portal the Identity looks like this:

![image](https://user-images.githubusercontent.com/4884144/73435126-5a4e2b00-4348-11ea-91cb-1efe150d8d48.png).

Maybe I am lacking a setting in the portal?

Furthermore, as I am able to get it working when using the AzureServiceTokenProvider I am fairly confident that the role is set on the container.

@schaabs : I'll try to see if I can create a more detailed response.

**Comment by CKHere** [comment]
@jongio : The above error message was my bad. I am not used to the CLI, so I had the wrong subscription.

**Comment by CKHere** [comment]
@schaabs 
I tried to modify the catch statement. However, as I am not sure how to see the Console in a Azure Function, I changed the Controller endpoint to this:

`            catch (Exception e)
            {
                if (e.InnerException != null && e.InnerException is AggregateException)
                {
                    string exceptionMessage = "";

                    foreach (var inner in ((AggregateException)e.InnerException).InnerExceptions)
                    {
                        Console.WriteLine(inner.ToString());

                        exceptionMessage = exceptionMessage +
                            inner.ToString() + Environment.NewLine;

                        if (inner.InnerException != null)
                        {
                            Console.WriteLine(inner.InnerException.ToString());

                            exceptionMessage = exceptionMessage +
                                inner.InnerException.ToString() + Environment.NewLine
                                ;
                        }

                    }
                    return new BadRequestObjectResult("InnerExceptions: " + Environment.NewLine + exceptionMessage);

                }
                return new BadRequestObjectResult("Error: "+e.ToString());

            }
 `

I had to remove your check whether the inner.Message contained "ManagedIdentityCredential" as it otherwise was blank.  With above code I get the following output:

InnerExceptions: 
Azure.Identity.CredentialUnavailableException: Environment variables not fully configured. AZURE_TENANT_ID and AZURE_CLIENT_ID must be set, along with either AZURE_CLIENT_SECRET or AZURE_USERNAME and AZURE_PASSWORD. Currently set variables [  ]
Azure.Identity.AuthenticationFailedException: The authentication request failed due to an unhandled exception.  See inner exception for details. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Text.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
 ---> System.IO.FileNotFoundException: Could not load the specified file.
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   --- End of inner exception stack trace ---
   at Azure.Identity.ManagedIdentityClient.Deserialize(Stream content)
   at Azure.Identity.ManagedIdentityClient.Authenticate(MsiType msiType, String[] scopes, String clientId, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityCredential.GetTokenImpl(TokenRequestContext requestContext, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
System.IO.FileNotFoundException: Could not load file or assembly 'System.Text.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

File name: 'System.Text.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' ---> System.IO.FileNotFoundException: Could not load the specified file.
File name: 'System.Text.Json'
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at Azure.Identity.ManagedIdentityClient.Deserialize(Stream content)
   at Azure.Identity.ManagedIdentityClient.Authenticate(MsiType msiType, String[] scopes, String clientId, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityCredential.GetTokenImpl(TokenRequestContext requestContext, CancellationToken cancellationToken)

**Comment by jongio** [comment]
- Are you running the Function locally or in Azure?
- Please click the “Show the Azure RBAC roles assigned...” link on the Managed Identity screen in the portal and send what is returned
- The error message says you don’t have Json installed. How did you install the SDK?
- Can you try to create a new blank project with only Azure.Identity and Azure.Storage.Blobs dependencies?
- The CLI install also looks misconfigured. Can you try to reinstall that?

I’m around today so please let me know if you want to hop on a call to figure this out together.

**Comment by CKHere** [comment]
@jongio :
Thanks, for some of the hints. First of all, I'm located in Denmark, thus I wasn't online yesterday. If you're online later today, I might try to give you a call. 

But to return to your questions:

- I'm running the function in Azure

- The Managed Identity was a System assigned Managed Identity, thus it doesn't appear on the Managed identity pane. I tried to create a new User assigned Managed Identity, and add the appropriate role. See attached picture of roles on the container, with comments to the left.

![StorageContainerBlobContributors](https://user-images.githubusercontent.com/4884144/73552542-ba2bfb00-4448-11ea-9aef-a6ceedf73aaa.PNG)

- I think the SDK was installed together with VS2019 (but not quite sure which SDK you are referring to). The Azure.Identity and Azure.Storage.Blobs are NuGet packages.

- I've tried creating a new blank project, and implementing the functionality in that one. This leads to other errors. Currently I'm trying to figure out what happens here. 

- The error from the CLI was my bad. I used a wrong account. It seems to work now.

I'll continue try to debug the newly created function, and see if I can get somewhere with that one.

Thanks.

**Comment by schaabs** [comment]
@CKHere The failure you're running into seems to be an assembly loading issue, when trying to parse the response from the managed identity endpoint:
~~~
Azure.Identity.AuthenticationFailedException: The authentication request failed due to an unhandled exception. See inner exception for details. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Text.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
---> System.IO.FileNotFoundException: Could not load the specified file.
at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
--- End of inner exception stack trace ---
at Azure.Identity.ManagedIdentityClient.Deserialize(Stream content)
at Azure.Identity.ManagedIdentityClient.Authenticate(MsiType msiType, String[] scopes, String clientId, CancellationToken cancellationToken)
at Azure.Identity.ManagedIdentityCredential.GetTokenImpl(TokenRequestContext requestContext, CancellationToken cancellationToken)
--- End of inner exception stack trace ---
System.IO.FileNotFoundException: Could not load file or assembly 'System.Text.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

File name: 'System.Text.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' ---> System.IO.FileNotFoundException: Could not load the specified file.
File name: 'System.Text.Json'
at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
at Azure.Identity.ManagedIdentityClient.Deserialize(Stream content)
at Azure.Identity.ManagedIdentityClient.Authenticate(MsiType msiType, String[] scopes, String clientId, CancellationToken cancellationToken)
at Azure.Identity.ManagedIdentityCredential.GetTokenImpl(TokenRequestContext requestContext, CancellationToken cancellationToken)
~~~
Perhaps there's some conflict in the project dependencies. Could you please add the packages you're including in your project?

**Comment by jongio** [comment]
@CKHere - I was able to repro this.

It seems that we have runtime version mismatches happening.

I was able to get it working by downgrading my Azure function app to netcoreapp2.1, AF v2, and Microsoft.NET.Sdk.Functions=1.0.29

This is not the final solution, but this should unblock you:


Open up your project file and manually set TargetFramework, AzureFunctionsVersion, and update the Microsoft.NET.Sdk.Functions reference to 1.0.29.

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <AzureFunctionsVersion>v2</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.1.0" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.2.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.29" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

**Comment by jongio** [comment]
@CKHere  - I figured out what is happening here.

It looks like the Linux function container host is pinned to dotnet:2.0-appservice, so no matter what code you push to it, it will always run under the context of .NET Core 2.0.

Here's how to fix it to use .NET 3.0 instead.

In the Azure Portal, find your function, click on Platform Features, then Container settings

![image](https://user-images.githubusercontent.com/2163001/73589779-cedfb180-448f-11ea-81c2-fb84aef722e3.png)


In the "Image and optional tag" textbox, change 2.0 to 3.0.



![image](https://user-images.githubusercontent.com/2163001/73589763-9e981300-448f-11ea-9c8a-8961d651448b.png)

![image](https://user-images.githubusercontent.com/2163001/73589772-b5d70080-448f-11ea-9f20-24dd5f7860e8.png)

Click Save

It took about 3 minutes for the image to be pulled.

I will get a simplified repo and follow up with the Functions team.

**Comment by jongio** [comment]
Related https://github.com/Azure/azure-functions-host/issues/5559

**Comment by CKHere** [comment]
@jongio, @schaabs : Thanks for all your help. I can confirm I am now able to get it running from the Azure function. I did try a Windows function at some point of time, which had the same error, thus it might not only be the Linux function that needs an update. 

I am still struggling a bit when running locally, however, I think that is mainly an issue because I'm still an Azure newbie.

**Comment by jongio** [comment]
Glad to hear it.  I would like to hear about your local struggles as well.  Feel free to reach out directly here: https://jong.io/contact

**Comment by jefferson117** [comment]
I too am getting an error when using DefaultAzureCredential to access blob storage. In my case it is a web app which works fine locally (VS2019) but fails when deployed (using system managed identity). I have verified identity has blob contributor permissions for storage account.

The exception stack shows it first tries to obtain environmental credentials (I know I can switch this off with default credentials options but it makes no difference) and fails as expected then attempts to obtain a managed identity token with the following response:

Azure.Identity.AuthenticationFailedException: Invalid response, the authentication response was not in the expected format.
   at Azure.Identity.ManagedIdentityClient.Deserialize(JsonElement json)
   at Azure.Identity.ManagedIdentityClient.DeserializeAsync(Stream content, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityClient.AuthenticateAsync(MsiType msiType, String[] scopes, String clientId, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityCredential.GetTokenImplAsync(TokenRequestContext requestContext, CancellationToken cancellationToken).

I am using latest Azure.Identity 1.1.1. 

I found this link where someone else appears to experience similar problems and having to fall back on cloudblobcontainer https://blog.bitscry.com/2019/12/05/azure-storage-authentication-using-managed-service-identities/ .

Any help appreciated.

**Comment by jongio** [comment]
@jefferson117 Please try to follow along with the steps on this blog and see if you can get it working. 

https://blog.jongallant.com/2020/02/azure-functions-blob-managed-identity-part1/

You can set TENANT with AZURE_TENANT_ID environment variable. But not sure that is related.

**Comment by bradmoulder** [comment]
Can we have some insights to the offline discussion that took place? We are currently encountering the same issue.
