### ISSUE TITLE
RetryPolicy logging should include reason for retry

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-net#9621]
The RetryPolicy logging currently includes only the ClientRequestId and the retry count:

https://github.com/Azure/azure-sdk-for-net/blob/7c2ff45b0f4c60fc9ed2420969b556851e74cd4d/sdk/core/Azure.Core/src/Pipeline/Internal/RetryPolicy.cs#L126

It would be nice to also log information about **why** the retry happened (e.g. the exception that caused the retry).

**Comment by pakrym** [comment]
And possibly the time current try took.

**Comment by ShivangiReja** [comment]
Closed with https://github.com/Azure/azure-sdk-for-net/pull/12003
