### ISSUE TITLE
[Storage][DataLake] Add progress handling.

### ISSUE THREAD

**Issue by seanmcc-msft** [Azure/azure-sdk-for-net#9623]
Add progress handling to Append, and future Upload and Download.

**Comment by JimSuplizio** [comment]
Hi @seanmcc-msft, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
