### ISSUE TITLE
Distributed tracing for Event Hub: do not populate schema in peer.address attribute

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-net#9631]
**Describe the bug**
Azure SDKs for EventHub populate peer.adress (EventHub endpoint) inconsistently using different schemas (or no schemas). 

**Expected behavior**
Assuming schema is an implementation detail and not particularly important for tracing, let's stop populating schema everywhere. I.e. use FQDN instead of endpoint (e.g. azuresdkdemo.servicebus.windows.net)

**Actual behavior (include Exception or Stack Trace)**
Example: 
- .NET: amqps://azuresdkdemo.servicebus.windows.net
- JS: sb://azuresdkdemo.servicebus.windows.net
- Python: azuresdkdemo.servicebus.windows.net
- Java: azuresdkdemo.servicebus.windows.net

**To Reproduce**
1. Send message to EventHub with  EventHubProducerClient.Send
2. enable tracing and capture traces using ApplicationInsights or OpenTelemetry 

**Environment:**
 - Name and version of the Library package used: Azure.Messaging.EventHubs 5.0.0.
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): any
 - IDE and version : any

**Comment by jsquire** [comment]
//cc:  @ramya-rao-a, @chradek, @richardpark-msft - it looks as if this request may also apply to JS/TS.

**Comment by lmolkova** [comment]
I've created a n issue for JS: https://github.com/Azure/azure-sdk-for-js/issues/7109
