### ISSUE TITLE
[FEATURE REQ] - Add the ability to download range to a stream for the azure storage blob and file SDK

### ISSUE THREAD

**Issue by rongduan-zhu** [Azure/azure-sdk-for-net#9667]
**Library or service name.**
What library or service is this request related to?
`Azure.Storage.Blob`
`Azure.Storage.File`
 
**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? 
We would like to have the ability to download a chunk of a file to a stream in the storage blob and storage file SDK. 
What problem is it solving?
We download a file in parallel by breaking it down into chunks and downloading each chunk into a stream which we use to do further processing.

**Comment by tg-msft** [comment]
Does the `range` parameter of `DownloadAsync` for [Blobs](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.specialized.blobbaseclient.downloadasync?view=azure-dotnet#Azure_Storage_Blobs_Specialized_BlobBaseClient_DownloadAsync_Azure_HttpRange_Azure_Storage_Blobs_Models_BlobRequestConditions_System_Boolean_System_Threading_CancellationToken_) and [File Shares](Azure_Storage_Files_Shares_ShareFileClient_DownloadAsync_Azure_HttpRange_System_Boolean_System_Threading_CancellationToken_) do what you're looking for?

**Comment by rongduan-zhu** [comment]
Does DownloadAsync stream the download into the Stream exposed? That is, if I call DownloadAsync on a blob that is bigger than available memory, will it still work? If so then yes, Download/DownloadAsync will work for us, if not, then we will need something to do this. It can either be a new parameter in the existing API or a new API

**Comment by amnguye** [comment]
Hi, so to get another update, did using the `range` parameter in `Download`\`DownloadAsync` work for you to download a chunk of a file or blob?

**Comment by seanmcc-msft** [comment]
Please re-open if this continues to be an issue.
