### ISSUE TITLE
[BUG] Calling Azure Function using ServiceBusTrigger inside Xamarin.Android fails

### ISSUE THREAD

**Issue by bizmonger** [Azure/azure-sdk-for-net#9669]
**Describe the bug**
My Azure function doesn't trigger when called by my Android app.

**Expected behavior**
The following test successfully triggers the Azure function via a ServiceBusTrigger:

    [<Fact>]
    let ``Publish message assigned to servicebus topic``() =
    
        // Setup
        let connectionstring = ConfigurationManager.ConnectionStrings.["servicebus_testEnv"].ConnectionString
    
        // Test
        async {
    
            let client  = TopicClient(connectionstring, "Topic.courier-subscribed")
            let data    = "test_data"
            let message = Message(Encoding.UTF8.GetBytes(data))
    
            do! client.SendAsync(message) |> Async.AwaitTask
            do! client.CloseAsync()       |> Async.AwaitTask
        }

**Actual behavior (include Exception or Stack Trace)**
When I use the same code for my Xamarin Android application, the Azure function never gets triggered.

Instead, I observe the following error:

> System.TimeoutException: 'The operation did not complete within the
> allocated time 00:00:49.9480520 for object session5.'

**To Reproduce**
Here's the code in my Xamarin Android app:

    let subscribe : Subscribe =
        fun request ->

            async {

                let body = {
                    Courier   = request.Courier
                    Location  = request.Location
                    Timestamp = DateTime.Now
                }

                try
                    let connectionstring = QueueTopic.Instance.ConnectionString
                    let client  = TopicClient(connectionstring, "Topic.courier-subscribed")
                    let json    = JsonConvert.SerializeObject(body)
                    let message = Message(Encoding.UTF8.GetBytes(json))

                    do! client.SendAsync(message) |> Async.AwaitTask
                    do! client.CloseAsync()       |> Async.AwaitTask

                    return Ok body
             }

**Workaround**
I had to migrate the publishing of a message from my Android app running on an Emulator to an Azure function that my app now has to call.

**Environment:**
Android - Version 9 (Emulator)
Microsoft.Azure.ServiceBus: 4.1.1
Newtonsoft.Json: 12.0.3

Microsoft Visual Studio Community 2019 Preview (2)
Version 16.5.0 Preview 2.0
VisualStudio.16.Preview/16.5.0-pre.2.0+29721.120
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

ASP.NET and Web Tools 2019   16.5.170.20430
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.5.170.20430
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.5.170.20430
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.5.170.20430
Azure Functions and Web Jobs Tools

C# Tools   3.5.0-beta2-20057-04+f43cfcd2be1b781e0b5a9153776f7e5fecf92b89
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Microsoft Azure HDInsight Azure Node   2.4.5000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.4.5000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.4.5000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.21108.1

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   16.5.509 (d15be8b)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SettingsWindow Extension   1.0
SettingsWindow Visual Studio Extension Detailed Info

Visual F# Tools 10.8.0.0 for F# 4.7   16.5.0-beta.20071.14+c4c09df4d5a68c3e9a51948bab554d11e2c141f2
Microsoft Visual F# Tools 10.8.0.0 for F# 4.7

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

Xamarin   16.5.000.400 (d16-5@4a7a7df)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.5.0.391 (remotes/origin/d16-5@2aeef9a0a)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.5.42 (afa79c5)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.2.0.84 (d16-5/ac3f71f)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: df42020
    Java.Interop: xamarin/java.interop/d16-5@c0cc770
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.28.0@46204c4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b

**Comment by jsquire** [comment]
@nemakam, would you be so kind as to offer your thoughts?

**Comment by nemakam** [comment]
@bizmonger, 
Could you describe the workflow again? Do you have a ServiceBusTrigger that in-turn sends a message to another servicebus? Or do you have a ServiceBusTrigger that should happen when you successfully send this message to the serviceBus? 
I am trying to understand whether the scope of issue is with ServiceBus-send() or AzureFunctions's serviceBusTrigger.

**Comment by bizmonger** [comment]
@nemakam 

The Xamarin.Android scenario is the following:

1. Android app (running in Emulator) publishes a message to a service bus (running on local machine) with appropriate connection string

2. Observe service bus trigger never executes

3. Observe timeout in Android app

NOTE:
This use to work in the last preview build of Visual Studio 2019.
Hence, the service bus trigger would be successfully triggered from an Android emulator client.


A normal automated test (using XUnit) works fine.

**Comment by nemakam** [comment]
We have customers running our code on Xamarin, so I feel this should be something related to your environment.

Also, what do you mean by "This use to work in the last preview build of Visual Studio 2019."? Do you mean that this used to work another build of VS2019, but after you updated your VS2019, this stopped working?
