### ISSUE TITLE
[Face API] SslStream.CheckDisposed () in Xamarin forms >> Android 

### ISSUE THREAD

**Issue by glintpursuit** [Azure/azure-sdk-for-net#9675]
**Describe the bug**
1. System.Threading.Tasks.TaskCanceledException: Cannot access a disposed object. Object name: 'SslStream'.
2. We get this issue while uploading image DetectWithStreamAsync method 

**Actual behavior (include Exception or Stack Trace)**
System.Net.Http
HttpConnection.SendAsyncCore (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken)
System.Net.Http
HttpConnectionPool.SendWithNtConnectionAuthAsync (System.Net.Http.HttpConnection connection, System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken)
System.Net.Http
HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken)
System.Net.Http
RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken)
Microsoft.Rest
RetryAfterDelegatingHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken)
Microsoft.Rest
RetryDelegatingHandler+<>c__DisplayClass15_0.<SendAsync>b__0 ()
Microsoft.Rest
RetryDelegatingHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken)
System.Net.Http
HttpClient.FinishSendAsyncBuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts)
Microsoft.Azure.CognitiveServices.Vision.Face
FaceOperations.DetectWithStreamWithHttpMessagesAsync (System.IO.Stream image, System.Nullable`1[T] returnFaceId, System.Nullable`1[T] returnFaceLandmarks, System.Collections.Generic.IList`1[T] returnFaceAttributes, System.String recognitionModel, System.Nullable`1[T] returnRecognitionModel, System.String detectionModel, System.Collections.Generic.Dictionary`2[TKey,TValue] customHeaders, System.Threading.CancellationToken cancellationToken)
Microsoft.Azure.CognitiveServices.Vision.Face
FaceOperationsExtensions.DetectWithStreamAsync (Microsoft.Azure.CognitiveServices.Vision.Face.IFaceOperations operations, System.IO.Stream image, System.Nullable`1[T] returnFaceId, System.Nullable`1[T] returnFaceLandmarks, System.Collections.Generic.IList`1[T] returnFaceAttributes, System.String recognitionModel, System.Nullable`1[T] returnRecognitionModel, System.String detectionModel, System.Threading.CancellationToken cancellationToken)

**How to reproduce**
1. upload the image stream with less timeout

**Comment by JimSuplizio** [comment]
Hi @glintpursuit, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
