### ISSUE TITLE
Look default value of DocumentSentiment.Sentiment

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#9690]
Is it Positive? None? Negative?

**Comment by maririos** [comment]
It is positive

**Comment by maririos** [comment]
@annelo-msft you ok moving this to P3?

**Comment by annelo-msft** [comment]
Yes, P3 is great.  It would be good to have this default to something like null if it was an error case, but I think throwing an exception when you access the success value on an error result may mean we don't have to worry about it.
