### ISSUE TITLE
[Design] Form Recognizer: Design Clients & Namespaces

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#9699]
Design clients for FormRecognizer service to support hero scenarios in a way that will work for v2.x, to the best of our knowledge, will evolve to support v3.x.

---
Prior details: 

Additional questions from Krzysztof to address as part of this:
1.	Should scenario specific clients be in one namespace or many namespaces?
2.	Should the custom client be in separate namespace from the scenario specific clients?

--

1. Multiple Clients for Custom/CustomModel/Layout/Receipt
Possible approaches, in order of FR team preference:
•	Single client with nested accessors (either properties or methods) for specialized areas
o	PRO: Clear separation of concerns
o	PRO: Reuse code and docstrings
o	CON: Deeply nested accessors
o	CON: sub-clients discouraged and/or not common in Azure SDKs
•	Multiple clients for each specialized area
o	PRO: Clear separation of concerns.
o	PRO: Reuse code and docstrings
o	CON: Duplicate XyzClientOptions for each XyzClient
o	CON: Multiple entry points for user
•	Single “flat” client with all methods available at once
o	PRO: Single entry point for user
o	PRO: Single client options class
o	CON: Verbose method names
o	CON: Duplicated method definitions and docstrings
o	CON: Duplicated method parameter for hierarchical resources (modelId)
Status: Switched from “Single client with nested accessors” to “Multiple clients for each specialized area”. Pending review.
Priority: high
Effort: high

Consider namespaces and whether to split into packages as part of this.

**Comment by annelo-msft** [comment]
We should consider working with the arch board on this to give prescriptive guidance in the guidelines around when to split clients.

**Comment by annelo-msft** [comment]
Regarding AnalyzeClient as a base class: I think the proposed design is a little heavy for what it's trying to do, which is support one boolean parameter difference between these clients. If we land on having multiple clients (and not all functionality exposed through a single client), I agree it would make sense to have a base class that implements common methods, but I don't think AnalyzeOptions and AnalyzeLayoutOptions types are needed, and I would try not to have two AnalyzeClient types.

**Comment by annelo-msft** [comment]
@ctstone

**Comment by annelo-msft** [comment]
Status: proposed design; will discuss with service team and arch board.  @mayurid

**Comment by annelo-msft** [comment]
New feedback from Krzysztof - Custom to go in a Custom namespace, all the prebuilt in the main namespace.  Model types to go in Models, except that Model means something specific in ML and we should consider this.

**Comment by ctstone** [comment]
I left a comment in apiview but it’s worth considering that custom accounts for about 60% of our current traffic. Should we relegate our most used service to a sub namespace?

**Comment by annelo-msft** [comment]
It's a good question.  Do we think that this will be the same pattern for customer who start using the service after GA?

**Comment by annelo-msft** [comment]
Is it ok to not have a FormRecognizerClient in the root namespace.  We’ll UX test this and look at feedback on preview 1, but both Python and .NET will keep the client structure they currently have for preview 1.

**Comment by annelo-msft** [comment]
Updating this issue to reflect current considerations:

o	Option 1: FormRecognizerClient and CustomTrainingClient as in current apiview.  Primary concern is that customer may not know which object to start from and CustomTrainingClient is less discoverable.
o	Option 2: All methods in a single FormRecognizerClient, similar to Sandeep’s suggestion, mirroring the current REST API.
o	Option 3: Since the first step for all use cases is to train/get a model, place the model creation/retrieval/management methods in FormRecognizerClient and have Recognize methods on the returned FormModel classes.  This is more object oriented, but deviates from current undocumented SDK conventions.

**Comment by annelo-msft** [comment]
Addressed in new design - will reopen if architects suggest changes.
