### ISSUE TITLE
Cognitive: Design Error Types

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#9703]
Design common error types for Cognitive, and possibly across the SDK for services that implement the MS REST API Guidelines error types.

These will likely go in Azure.Core.

**Comment by annelo-msft** [comment]
@mayurid

**Comment by annelo-msft** [comment]
@AlexGhiondea why did you remove TextAnalytics from this?

**Comment by AlexGhiondea** [comment]
I assumed this was only tracking the FR work. Feel free to add it back 😀.

**Comment by annelo-msft** [comment]
@maririos, @mayurid , it may be too late to get this into TextAnalytics for the next release, but we were hoping to have a common error type in Azure.Core that all the Cognitive Services and possibly other Azure services could use.

**Comment by maririos** [comment]
Thanks for bringing this to my attention again Anne. I am looking into it

**Comment by annelo-msft** [comment]
Thanks, @maririos !

**Comment by maririos** [comment]
No longer needed as Azure.Core now has `ResponseError` and when appropriate, we are moving our libraries to use that.
