### ISSUE TITLE
Cognitive: Consider naming around models, confidence scores

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#9710]
Work with Cognitive team to investigate and possibly standardize naming around models, confidence scores, or other ML terms that show up across the Cognitive Services

**Comment by annelo-msft** [comment]
@ctstone @mayurid @assafi

**Comment by kinelski** [comment]
The Form Recognizer SDK has shipped on 2020/Aug/20 and naming choices have already been made. This is an old issue.
