### ISSUE TITLE
Cognitive: Design Common Credential Type

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#9711]
I expect this to land in Azure.Core.  It will need to be designed to accomodate additions for new services, without putting in pieces that are unused now.

**Comment by annelo-msft** [comment]
@ctstone @mayurid @assafi

**Comment by annelo-msft** [comment]
KrzysztofCwalina15 hours ago
This type should not be in this package. Could this be in Azure.Core, renamed to simply KeyCredential?


ctstone15 hours ago
Specifically it is an ApimCredential. Header name is always Ocp-Apim-Subscription-Key. If this is not too specific for Core, then yes.

**Comment by maririos** [comment]
PR: https://github.com/Azure/azure-sdk-for-net/pull/10668

**Comment by maririos** [comment]
.NET design is in. Now looking into the other languages

**Comment by maririos** [comment]
Java design merged too.
Python and JS still in PR.

Issue and email with architects to get approval to ship Azure Core is done. Waiting on them to approve

**Comment by maririos** [comment]
Changes in JS have been merged

**Comment by maririos** [comment]
Python changes have been merged and architects have approved 😄 
https://github.com/Azure/azure-sdk/issues/1142
