### ISSUE TITLE
Cognitive: Standardize on Bounding Box type

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#9715]
public float[] BoundingBox { get; }

annelo-msft3 days ago
It would be great to standardize on how a bounding box is represented across the Vision services -- we should look at what Custom Vision, Computer Vision, and Face APIs do as well and see if we can find something that would work for every service.

ctstone2 days ago
Agreed. We have standardized on the OCR bounding box, which uses 8 points. The box angles might not be at right angles.

annelo-msft1 hour ago
When you say you've standardized - how widely is this standardized? (i.e. which services are using the standard?)

ctstone1 hour ago
This format is defined by the OCR Cognitive Service, which we take a dependency on: https://westus.dev.cognitive.microsoft.com/docs/services/5adf991815e1060e6355ad44/operations/5be108e7498a4f9ed20bf96d

Bounding box of a recognized region, line, or word, depending on the parent object. It's an arrary of eight numbers represent the four points (x-coordinate, y-coordinate from the left-top corner of the image) of the detected rectangle from the left-top corner in the clockwise direction. For images, coordinates are in pixels. For PDF, coordinates are in inches.

ctstone1 hour ago
Same service, different API uses a { x: number, y: number, w: number, h: number } for object detection: https://westus.dev.cognitive.microsoft.com/docs/services/5adf991815e1060e6355ad44/operations/5e0cdeda77a84fcd9a6d3d0a

And here's one that uses "x, y, w, h" as a string https://westus.dev.cognitive.microsoft.com/docs/services/5adf991815e1060e6355ad44/operations/56f91f2e778daf14a499e1fc

**Comment by annelo-msft** [comment]
@ctstone

**Comment by annelo-msft** [comment]
Design prototyped for FormRecognizer.  Still need to check whether this will work for all the Vision services.

**Comment by kinelski** [comment]
The Form Recognizer SDK has shipped on 2020/Aug/20 and the `BoundingBox` design has already been decided. This is an old issue.
