### ISSUE TITLE
TA client questions to TA service

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#9722]
- For linked entities, what is the purpose of entity.id? how is entity.name != entity.id?
- RecognizeLikedEntity => what are other name options we could use that will reflect what the service is doing?
  - InferLikedEntities
  - RecognizeLinksEntities
  - ...
- In Analyze sentiment, what are the scores reflecting? confidence level? Do we need to show them? How will a user consume/manage this information?
- Could we expand in the difference between Key Phrase and Entity? What are user scenarios for Key Phrase? What are examples we can provide in our docs?
- When there is an error because the document exceeds the character limit, could the service return the max amount of characters supported to help the user diagnose and adjust?
- Are there plans to have an endpoint that will support multiple calls to the same input? (omnibus)
- [#8946](https://github.com/Azure/azure-sdk-for-python/issues/8946)

**Comment by maririos** [comment]
Where is https://azure.microsoft.com/en-us/services/cognitive-services/text-analytics/ hitting? Return types?

**Comment by maririos** [comment]
Can the sentiment of a `sentence` be mixed? Currently only `document` allows mixed.

**Comment by maririos** [comment]
More questions:
- Default language? Could we enforce it in the SDK?
- Is the readme objective to show single operation? or batch operation

**Comment by maririos** [comment]
When calling AnalyzeSentiment, what happens if the service can't tell the sentiment of the sentence?
`undefined`? error? neutral?

**Comment by maririos** [comment]
WIP

Specific questions:
- For linked entities, what is the purpose of entity.id? how is entity.name != entity.id?
- Could we expand in the difference between Key Phrase and Entity? What are user scenarios for Key Phrase? What are examples we can provide in our docs?
- When there is an error because the document exceeds the character limit, could the service return the max amount of characters supported to help the user diagnose and adjust?
- Can the sentiment of a sentence be mixed? Currently only document allows mixed.
- When calling AnalyzeSentiment, what happens if the service can't tell the sentiment of the sentence?
undefined? error? neutral?

Discussion (might include from section above in we need more detail after the answer):
- RecognizeLikedEntity => what are other name options we could use that will reflect what the service is doing?
  - InferLikedEntities
  - RecognizeLinksEntities
  - ...
- In Analyze sentiment, what are the scores reflecting? confidence level? Do we need to show them? - - How will a user consume/manage this information?
- Default language? Could we enforce it in the SDK?
- Consider using explicit "none" string over empty string for not setting country hint / language
- Is the readme objective to show single operation? or batch operation

**Comment by kristapratico** [comment]
* Should we consider making the user explicitly pass `"none"` instead of the empty string `""` to the service in the case that they do not want to use the default country hint? This can be handled in the SDK, but it might make sense to have the service also adopt this. Issue [here](https://github.com/Azure/azure-sdk-for-python/issues/8946)

**Comment by maririos** [comment]
Email and meeting invite sent
