### ISSUE TITLE
[Feature] Support Emulators such as Azurite and Azure Storage Explorer

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-net#9729]
## Goal: 

Be able to use DefaultAzureCredential with Azurite and/or Storage Explorer

### 1. HTTPS

Storage emulator and Azurite only support HTTP: https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator#authorize-with-shared-key-credentials. TokenCredential does not allow HTTP calls, HTTPS only.

Therefore, an instantiation like this:

`var client = new BlobContainerClient("http://127.0.0.1:10000/devstoreaccount1/{container}", new DefaultAzureCredential());`

Will fail with this error message:

```
Azure.Storage.Blobs: Cannot use TokenCredential without HTTPS.
```

The current workaround looks like this: Use a different Client overload if you want to use emulator:

```csharp
var client = emulator ? 
   new BlobContainerClient(store, container) : 
   new BlobContainerClient(uri, new DefaultAzureCredential());
```

Related Azurite Issue: https://github.com/Azure/Azurite/issues/38

### 2. TokenCredential

Azurite and Storage Explorer do not support Bearer token based credentials. So you will get this exception if you try to call with DefaultAzureCredential

```
[2/4/2020 12:42:47 AM] System.Private.CoreLib: Exception while executing function: func1. Azure.Storage.Blobs: Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature.
```

Related Azurite Issue: https://github.com/Azure/Azurite/issues/389

Although there is no work for the Azure SDK team with this feature, I recommend that we keep this issue open to track the workitems on Azurite.

**Comment by jsquire** [comment]
//cc: @tg-msft

**Comment by tg-msft** [comment]
//cc @schaabs

**Comment by SeanFeldman** [comment]
Azurite v3.7.0 [supports HTTPS](https://github.com/Azure/Azurite/issues/38#issuecomment-619072057). And @jongio has a [blog post](https://blog.jongallant.com/2020/04/local-azure-storage-development-with-azurite-azuresdks-storage-explorer/) about it. Close?
