### ISSUE TITLE
Update Storage tests to no longer use custom transport

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#9734]
Now that https://github.com/Azure/azure-sdk-for-net/issues/9031 is fixed, we can try updating the Storage tests to no longer use the custom Transport which extended the HttpClient timeout. This is because HttpClient timeouts will now be automatically retried due to fix to above issue.

**Comment by JimSuplizio** [comment]
Hi @JoshLove-msft, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
