### ISSUE TITLE
[FEATURE REQ] [STORAGE] Please add an example how to upload a string to blob

### ISSUE THREAD

**Issue by zmarty** [Azure/azure-sdk-for-net#9751]
Please add an example how to upload a string in https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/samples/Sample01a_HelloWorld.cs

Blob Client V9 had a function called UploadTextAsync, the new library does not have that for some reason.

Here is my current attempt:

```csharp
public async Task UploadObjectAsync(
    CancellationToken cancellationToken,
    string containerName,
    string blobPath,
    object obj)
{
    var containerClient = this.Client.GetBlobContainerClient(
        blobContainerName: containerName);

    var blobClient = containerClient.GetBlobClient(
        blobName: blobPath);

    // TODO: Figure out a way to stream this data WHILE serializing
    var json = JsonUtils.SerializeObject(obj);

    using (var memoryStream = new MemoryStream(Encoding.UTF8.GetBytes(json)))
    {
        await blobClient.UploadAsync(memoryStream, overwrite: true);
    }
}
```

**Comment by amnguye** [comment]
Hi,

Yes we will look into adding a sample in for uploading text to a blob. Maybe we will also consider looking into adding back this convenient method to the V12 library depending how large the ask is for this.

**Comment by svengeance** [comment]
Just wanted to hop on this train and say I'm also in this situation. Because all of the `.Upload` methods take a Stream, I was concerned that I was doing things incorrectly by trying to store json in blob storage and I would have to look elsewhere.

**Comment by saviour07** [comment]
I'm in exactly the same situation, trying to use the new v12 library to upload some json to blob storage.
I imagine there will be a fair few that would also like a return of the UploadTextAsync method!

**Comment by kasobol-msft** [comment]
@amnguye We can think about adding overloads that accept https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/core/System.Memory.Data .
@tg-msft what do you think?

**Comment by tg-msft** [comment]
Yes.  I'm very much in favor of adding DownloadData/UploadData methods that return/accept BinaryData so we don't have to add DownloadText, DownloadJson, DownloadAvro, DownloadProtobuf, ..., etc.

**Comment by JimSuplizio** [comment]
Hi @zmarty, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
