### ISSUE TITLE
[FEATURE REQ] Consider adding `ExistsAsync` to `QueueClient`

### ISSUE THREAD

**Issue by ellismg** [Azure/azure-sdk-for-net#9752]
**Library or service name.**
Azure.Storage.Queues
 
**Is your feature request related to a problem? Please describe.**
I'm taking an existing code-base that used the v11 Storage SDK and moving it to use the newer V12 SDK.

The code in question has a long lived processing loop that is pulling from arbitrary containers.  At the start of the loop the the code calls `.ExistsAsync` from the v11 SDK on a `CloudQueue` (which for the v11 SDK would be a `QueueClient`), since if the queue does not exist it can early out of some work.  There are comments in the code mentioning that the Queue could be deleted between the existence check and when actual operations happen, so the code is written to keep that in mind, but even with this caveat, the check provides value.

Looking at the older V11 SDK, it seems like ExistsAsync() tried to fetch the metadata for a queue and if it could it decided the Queue exists.  So it's easy enough for me to add an extension method to the class to do this.  However, there does seem to be some custom logic in translating some responses (for example by my reading of the code if a response with the code PreconditionFailed failed is returned, the older v11 SDK would not throw an exception and instead return true), which means writing method to have the same semantics as the older SDK requires a little care.

It might be nice to add this method back, even though it is possible that by the time you observe the result of ExistsAsync() it is has changed because of some out of band operation.

**Comment by zmarty** [comment]
Also CreateIfNotExistsAsync

**Comment by amnguye** [comment]
Thanks for your suggestions! We actually already have an duplicate issue opened for this, so please follow that issue instead of any updates when that change gets added and merged.

https://github.com/Azure/azure-sdk-for-net/issues/7879
