### ISSUE TITLE
[FEATURE REQ] Samples for Blob Lease

### ISSUE THREAD

**Issue by amnguye** [Azure/azure-sdk-for-net#9756]
**Library or service name.**
[Azure.Storage.Blobs.Samples.Tests] 
 
**Is your feature request related to a problem? Please describe.**
Adding samples for leasing blobs.

**Comment by JimSuplizio** [comment]
Hi @amnguye, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
