### ISSUE TITLE
[FEATURE REQ] Include pdb files with "Azure.Storage.Blobs" nuget package

### ISSUE THREAD

**Issue by zmarty** [Azure/azure-sdk-for-net#9757]
Could you please include pdb files with "Azure.Storage.Blobs" nuget package? I am trying to debug a problem within the library (actually it's inside Azure.Core).

You do that for "WindowsAzure.Storage" as per related item: https://github.com/Azure/azure-storage-net/issues/115

**Comment by pakrym** [comment]
cc @chidozieononiwu @weshaggard

**Comment by weshaggard** [comment]
We intentionally don't include the symbols in the nuget packages to avoid size issues but we do publish them to the microsoft symbol servers so you should be able to load the symbols for debugging. Make sure you have the "Microsoft Symbol Server" option checked in VS symbols options and it should find and download the symbols automatically for you.

**Comment by zmarty** [comment]
I was able to get the pdb for Blobs, but that depends on Azure.Core and I don't see a pdb for that in my local cache. My problem is actually inside Azure.Core, it seems.

**Comment by weshaggard** [comment]
Azure.Core symbols should be present as well. Can you point us to the version of Azure.Core package you are using so we can verify the symbols are present?

**Comment by zmarty** [comment]
1.0.1

**Comment by weshaggard** [comment]
@chidozieononiwu can you please have a look at the Azure.Core 1.0.1 package and ensure the symbols are correctly published?

**Comment by chidozieononiwu** [comment]
We are unable to publish symbols for that version as the original release build has been cleaned up. Best to move to the newer version 1.0.2 which has symbols published.

**Comment by StingyJack** [comment]
@chidozieononiwu  - Is the PDB still working for this?

Visual Studio says its loaded the symbol info for this but is unable to locate the PDB to do debugging. We have the MSFT symbol servers enabled, but get no option for getting the sources to step through. 
![image](https://user-images.githubusercontent.com/15381181/119566853-a01ed600-bd79-11eb-9f59-885b354b7e36.png)

**Comment by weshaggard** [comment]
It looks like the PDBs are loaded already for Azure.Storage.Blobs.

**Comment by StingyJack** [comment]
I didnt get the screenshot but the dialog box  that came up after selecting Symbol Load Information  said it could not locate the PDB's.   It could be a VS issue. @karthik-iyer do you remember the actual message in that dialog?
