### ISSUE TITLE
Azure Function - Host.json file is missing using Terraform Deploy

### ISSUE THREAD

**Issue by masonyc** [Azure/azure-sdk-for-net#9765]
**Query/Question**
Hi All, 

I am using Terraform to deploy Azure Functions infrastructure through Azure DevOps release pipeline. Everything works fine but starting from last Friday. I got an error said Function runtime is unable to start. After some investigation, I found out the host.json file is not generated in the Azure Function and I dont know how to get it fix. Can you please provide some suggestions on this?
(Only change is updated Function version v2 to v3, but even I downgrade back to v2, same problem still exists).

![image](https://user-images.githubusercontent.com/18006944/73603104-dd8aad80-45e2-11ea-962c-0c0690d71742.png)

**Environment:**
Azure Function V2/V3
Resources Created By Terraform using App Service Plan Tier

**Comment by jsquire** [comment]
Hi @masonyc:

I'm sorry that you're running into difficulties and we appreciate you taking the time to reach out and let us know.   Unfortunately, the issue that you're describing does not appear to be related to one of the .NET SDK libraries, so there's not much that we can do to help.   It looks as if you're running into a potential problem with Azure Functions deployment.   

You may want to consider using Twitter to contact @AzureFunctions or @jeffhollan to discuss.   If you're looking for something more formal, you'll likely want to open a support ticket using the Azure portal:

![image](https://user-images.githubusercontent.com/913445/73613259-ce473800-45c1-11ea-8d61-b8612d17adcd.png)

I'm going to close this out; if I've overlooked something and you believe that you're running into a problem with one of the .NET Azure SDK libraries, please reopen and we'd be happy to assist as we're able.
