### ISSUE TITLE
[Sql] DatabasesOperationsExtensions.DeleteAsync() should throw if not exists

### ISSUE THREAD

**Issue by natelaff** [Azure/azure-sdk-for-net#9767]
DatabasesOperationsExtensions.DeleteAsync() should throw an exception when the database does not exist. Currently you can await it and if the database doesn't exist it will simply carry on. This is in contrast to say attempting to delete a Dns record set which will throw if it does not exist.

**Comment by isra-fel** [comment]
Sorry for late response. SQL team might have some insights to share. Thanks.

**Comment by jaredmoo** [comment]
Thank you for reporting this feedback!

The current behaviour is correct according to ARM RPC.

https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/resource-api-reference.md#delete-resource

> The resource provider can return 200 (OK) or 204 (NoContent) to indicate that the operation completed successfully. A 200 (OK) should be returned if the object exists and was deleted successfully; and a 204 (NoContent) should be used if the resource does not exist and the request is well formed.
> 
> 202 (Accepted) can be returned to indicate that the operation will complete asynchronously.
> 
> If the resource group does not exist, 404 (NotFound) will be returned by the proxy layer and will not reach the resource provider. 412 (PreconditionFailed) and other normal REST codes are acceptable as long as they match the REST guidelines.

If deleting dns record set throws when it doesn't exist, then that's a bug in the DNS API ;)
