### ISSUE TITLE
[FEATURE REQ] Add logging during startup for KeyVault

### ISSUE THREAD

**Issue by pekspro** [Azure/azure-sdk-for-net#9771]
**Library or service name.**
Microsoft.Azure.KeyVault 
 
**Is your feature request related to a problem? Please describe.**
**Long story:** I recently had problem with an app service running in Azure with an ASP.NET Core application. It failed to start and give me this error message:

```
HTTP Error 500.37 - ANCM Failed to Start Within Startup Time Limit
Common solutions to this issue:
ANCM failed to start after 120000 milliseconds
Troubleshooting steps:
Check the system event log for error messages
Enable logging the application process' stdout messages
Attach a debugger to the application process and inspect
```

I checked the event log but the only information I got was this:

```
Application '/LM/W3SVC/1617611725/ROOT' with physical root 'D:\home\site\wwwroot\' failed to load coreclr. Exception message:
Managed server didn't initialize after 120000 ms.
```

Then I tried to start the application via the debug console in Kudo. It did start but it took more than three minutes, way more than expected.

Mostly by luck I found that the application had a VNet Integration to get access to some resources on-premise. When I removed this the application was able to start. After some more investigation I found that some DNS servers was configured on the network that wasn’t accessible from Azure. This caused every request to the internet took 10-15 seconds more than normal.

Since my application is connecting to KeyVault on startup and downloads several key-values it could be this that has caused the application start slower than allowed (if I remove KeyVault integration it starts faster). Clearly this is a configuration error, but with better logging this would have been a lot easier to troubleshoot.

**Short story**: Please add some logging so we could easily see when an application starts and stops fetching key-values from KeyVault. This is very valuable if this causes the application to boot slowly for instance due network issues.

**Comment by jsquire** [comment]
//cc: @AlexGhiondea, @heaths

**Comment by heaths** [comment]
Logging is on by default in Azure using the new Azure.Security.KeyVault.* packages, along with a faster, more customizable pipeline, and fewer allocations. We recommend switching to these libraries since they are our primary focus going forward. The older versions will only get critical fixes.

Please let us know if these newer libraries resolve your issue.

**Comment by pekspro** [comment]
Thanks for the advice @heaths. I’ve updated to the new libraries – no code changes were needed which was a nice surprise. Also, when debugging the applications starts a second or two faster now, seems like the KeyVault integration is a bit faster. Well done! 

My original problem was already resolved before I updated the libraries so I couldn’t do any testing on that. However, I have tried to find logs related to KeyVault but couldn’t find any.

**Comment by heaths** [comment]
Glad to hear you found it painless to migrate and saw improvements!

In what environment are you running? If in Azure and using AppInsights, it should be automatic. If not using AppInsights (or other related monitors), you can enable console logging, for example, using: https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/core/Azure.Core#setting-up-console-logging

You can also use `dotnet trace collect` with the "Azure-Core" trace source name. See https://heaths.dev/azure/2020/02/04/trace-azure-sdk-for-net.html for an example.

Let me know if that works for you or not.

**Comment by pekspro** [comment]
Thanks again @heaths  for more great advices :-) I drew a hasty conclusion yesterday. I did remove the old nuget packages and installed the new ones and everything just worked. But the old nuget packages was references by other nuget packges which I didn’t saw until today so I’m still using the old version. I should have learned by now that things are never that easy ;-)  

Either way, I’m configuration KeyVault (and Azure App Configuration too) in the CreateHostBuilder method so that all values are loaded before ConfigureServices is called (like described here: https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-3.1#use-managed-identities-for-azure-resources). I haven’t found a way to that with the new SDK.

In my original problem this caused the application to be stopped before ConfigureServices was called. And as I understand it the new SDK only use logging when it has been configured, and this is normally done in ConfigureServices. So, I guess this wouldn’t have give me any useful logging – or I’m missing something? My application is running as an app service in Azure with AppInsights.

**Comment by heaths** [comment]
You stated,
> when an application starts and stops fetching key-values from KeyVault

The request logging would do just that. A request would be sent but, based on your description, you wouldn't get back a response for a while (or at all, depending). Wouldn't that help? Even logging the method call wouldn't do much more since the client methods are actually pretty lightweight wrappers around the REST APIs in most cases (we put a lot of design work into the SDK - the clients, the models, etc. - but they are designed to be efficient clients). The method would always make a request. Very little exists between the invocation site and the request site, and what code is there would truly be exception if it threw.

@pakrym, do we have any updated documentation or examples on using track 2 with host builders?

**Comment by pakrym** [comment]
There isn't a ton of documentation about it but there is a ASP.NET integration library for new APIs: https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/core/Microsoft.Extensions.Azure#register-clients

If you inject client through DI you should get logs forwarded to ASP.NET core logs.

**Comment by pekspro** [comment]
@pakrym , this page:

https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/core/Microsoft.Extensions.Azure#register-clients

shows how to configure KeyVault in ConfigureServices to be used with DI. But with earlier SDK:s it was possible to configure KeyVault with the host builder, like this:

	// using Microsoft.Azure.KeyVault;
	// using Microsoft.Azure.Services.AppAuthentication;
	// using Microsoft.Extensions.Configuration.AzureKeyVault;
	
	public static IHostBuilder CreateHostBuilder(string[] args) =>
	    Host.CreateDefaultBuilder(args)
	        .ConfigureAppConfiguration((context, config) =>
	        {
	            if (context.HostingEnvironment.IsProduction())
	            {
	                var builtConfig = config.Build();
	
	                var azureServiceTokenProvider = new AzureServiceTokenProvider();
	                var keyVaultClient = new KeyVaultClient(
	                    new KeyVaultClient.AuthenticationCallback(
	                        azureServiceTokenProvider.KeyVaultTokenCallback));
	
	                config.AddAzureKeyVault(
	                    $"https://{builtConfig["KeyVaultName"]}.vault.azure.net/",
	                    keyVaultClient,
	                    new DefaultKeyVaultSecretManager());
	            }
	        })
	        .ConfigureWebHostDefaults(webBuilder =>
	        {
	            webBuilder.UseStartup<Startup>();
	        });
	
Sample copied from: https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-3.1#use-managed-identities-for-azure-resources

Is this possible with the new SDK?

**Comment by pakrym** [comment]
Ah, you want the configuration provider integration.

We are going to ship a version of configuration provider that uses new SDKs around march and it would support all logging features of new SDKs.

**Comment by pekspro** [comment]
Thanks for the answer @pakrym . I’ll wait until it released, I have another look then. The current version works well for me so not a major issue for me.

**Comment by heaths** [comment]
Closing this since it's stale and the new configuration providers have shipped. Please let us know if you are still having problems and we can reopen this issue for further investigation.
