### ISSUE TITLE
Move Analyze step to ubuntu-16.04

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#9776]
The Analyze step was on windows-2019 which starts slower, so it was moved to ubuntu-16.04 and working against track 2. However, when I had to publish track 1 packages that failed with an assembly binding error since linux doesn't have .NET Framework. For now, I moved the analyze step back to windows-2019.

We should consider moving back, though. It seems to have been working up until now, and even then is surprising it happens given services.proj still builds track 1 and 2. The major change with my PR was that sdk\keyvault\ci.yml was changed to build track 1 only (for this release).

**Comment by kurtzeborn** [comment]
As part of the changeover to the 1ES machine pool, we are now using ubuntu-18.04, so I think this is done.
