### ISSUE TITLE
Publishing pipeline fails to increment package versions

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#9780]
During release of track 1 packages, part of the publishing pipeline failed on the "Increment package version" step and subsequent steps, though ultimately succeeded to publish. Given these are track 1 packages, probably not expected that we should update them the same as track 1 packages.

See https://dev.azure.com/azure-sdk/internal/_build/results?buildId=250217&view=logs&j=4eab8ed6-9df1-50e3-aa86-c2ed1708909c&t=12ea21d7-18f8-57e1-47f6-4a2260a12c23 for an example.

**Comment by chidozieononiwu** [comment]
This was fixed yesterday. Tool worked today for Text Analytics https://github.com/Azure/azure-sdk-for-net/pull/9906. Will Close this.
