### ISSUE TITLE
[Event Hubs Client] Intermittent test failures during nightly runs (Track One)

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#9798]
# Summary

The test `ReceiverTests.CreateReceiverWithInclusiveSequenceNumber` has recently begun experiencing intermittent failures during nightly runs, typically constrained to the `net461` platform.  An example failure can be found in the [nightly results from February 4](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=251108&view=ms.vss-test-web.build-test-results-tab&runId=8485358&resultId=101219&paneView=debug).   The failure looks like:

![image](https://user-images.githubusercontent.com/913445/73786005-7269e400-4766-11ea-9366-5f12f88474f1.png)

# Scope of Work

- Analyze the test(s) to understand the point of non-determinism and decide on an approach to stabilize for nightly runs.

- Refactor the tests as needed to ensure that the results are deterministic and consistently pass.

# Out of Scope

- Changes or refactoring in other areas.

# Success Criteria

- The test(s) discussed in the summary have been refactored or removed and no longer cause intermittent, but frequent, failures during nightly runs.

- The changes did not cause regressions elsewhere; nightly test runs pass consistently and reliably with deterministic results.

**Comment by jsquire** [comment]
//cc: @serkantkaraca, @JamesBirdsall

**Comment by serkantkaraca** [comment]
Thx, I will take a look.

**Comment by serkantkaraca** [comment]
PR for fix submitted.
