### ISSUE TITLE
queueClient.SendAsync(message) doesnt send msg consistently 

### ISSUE THREAD

**Issue by anjanchidige** [Azure/azure-sdk-for-net#9815]
# Description

The below program sends the message to the queue, but most of the times not sending. I use the sender method in my class library, which is being called in a Cloud Service(Worker Role). Please help me to correct the code.

`    class Program
    {
        static void Main(string[] args)
        {

            Sender();
            Console.ReadKey();
        }

        private static void Sender()
        {
            var ConnectionString = "<<Connectionstring>>";
            var QueueName = "samplequeue";

            var queueClient = new QueueClient(ConnectionString, QueueName);

            try
            {
                for (var i = 0; i < 5; i++)
                {
                    // Create a new message to send to the queue
                    string messageBody = $"Message {i}";
                    var message = new Message(Encoding.UTF8.GetBytes(messageBody));

                    // Write the body of the message to the console
                    Console.WriteLine($"Sending message: {messageBody}");

                    // Send the message to the queue
                    queueClient.SendAsync(message);
                }

            }
            catch (Exception ex)
            {
                Console.WriteLine("Message queue failed\n" + ex.Message);
            }
            finally
            {
                Console.WriteLine("Message queued");
            }
        }
    }`

**Comment by jsquire** [comment]
Hi @anjanchidige.  Sorry to hear that you're having difficulties and thank you for taking the time to let us know.   Sean's advice is spot-on and should, I believe, resolve your issue.   As this does not appear to be an issue with the client itself, I'm going to close this out.
