### ISSUE TITLE
How to set Blob Content type on the new SDK?

### ISSUE THREAD

**Issue by galvesribeiro** [Azure/azure-sdk-for-net#9823]
Hello folks! on the previous versions of te Blob client SDK, it was easy to set the `Content-Type` of a blob using the blob reference.

Now I see that the new (v12) Azure.Storage.Blobs `BlobClient` can call `GetPropertiesAsync()` to get a `BlobProperties` object but I can't find how to set it.

So, how to properly set the file content type when uploading the blob?

I've found out `await blob.SetHttpHeadersAsync(new BlobHttpHeaders { ContentType = GetContentType(fileType) });` but that requires another call to the the storage... Isn't there a better way for doing that while uploading the file?

Thanks!

**Comment by jsquire** [comment]
//cc: @tg-msft

**Comment by tg-msft** [comment]
[`BlobClient.SetHttpHeadersAsync`](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.specialized.blobbaseclient.sethttpheadersasync?view=azure-dotnet#Azure_Storage_Blobs_Specialized_BlobBaseClient_SetHttpHeadersAsync_Azure_Storage_Blobs_Models_BlobHttpHeaders_Azure_Storage_Blobs_Models_BlobRequestConditions_System_Threading_CancellationToken_) will let you set the Content-Type as you've noticed.  You can also pass that [`BlobHttpHeaders`](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.models.blobhttpheaders?view=azure-dotnet) type as the second parameter of [`BlobClient.UploadAsync`](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobclient.uploadasync?view=azure-dotnet#Azure_Storage_Blobs_BlobClient_UploadAsync_System_IO_Stream_Azure_Storage_Blobs_Models_BlobHttpHeaders_System_Collections_Generic_IDictionary_System_String_System_String__Azure_Storage_Blobs_Models_BlobRequestConditions_System_IProgress_System_Int64__System_Nullable_Azure_Storage_Blobs_Models_AccessTier__Azure_Storage_StorageTransferOptions_System_Threading_CancellationToken_) to set the value when uploading.

**Comment by galvesribeiro** [comment]
Thanks for getting back so fast.

The problem is that when I use that overload that takes a `BlobHttpHeaders`, it doesn't allow me to set `override: true` and if I don't set that, I get the "blob already exist" response if I push a blob to override previous one.

Do we have an alternative way to set both headers and the override options?

Thanks!

**Comment by tg-msft** [comment]
[`overwrite` is just a shortcut for the more powerful `BlobRequestConditions`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/BlobClient.cs#L484)

**Comment by galvesribeiro** [comment]
Hummm... 

```
await blob.UploadAsync(content, new BlobHttpHeaders{ ContentType = GetContentType(fileType)}, conditions: new BlobRequestConditions{ IfMatch = new ETag("*") });
```

Should that be the correct way?

**Comment by tg-msft** [comment]
Almost - if you want `overwrite: true`, that corresponds to `conditions: null` or just:

```C#
await blob.UploadAsync(content, new BlobHttpHeaders { ContentType = GetContentType(fileType) });
```

**Comment by galvesribeiro** [comment]
Yeah, sorry, I forgot to mention that I've ended up with this:

```csharp
               blob = this._container.GetBlobClient(fileName);
                await blob.UploadAsync(
                    content,
                    new BlobHttpHeaders
                    {
                        ContentType = GetContentType(fileType)
                    },
                    conditions: null);
                sw.Stop();
```

Thanks folks! I'm closing the issue.

**Comment by warnov** [comment]
That solution is a little bit obscure. It would be great having an intuitive option like in the last version.

**Comment by jamie-lord** [comment]
The lack of documentation for this common use case is pretty poor.

**Comment by martonx** [comment]
Hello, I have lots of blobs uploaded into blob container with wrong content-type. I don't find edit option on Azure portal. Now, I wrote a small console app to modify content-type, but it seems it is impossible. Is it true?
I have to download all of the blobs, then delete all of them, then upload with the correct content-type?

Is this true, or only a bad joke? There is even no content-type setting possibility on Azure portal when uploading a file. LOL.

**Comment by nmg196** [comment]
Does anyone have an implemenation of GetContentType()?

**Comment by tg-msft** [comment]
You can call [BlobClient.SetHttpHeadersAsync](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.specialized.blobbaseclient.sethttpheadersasync?view=azure-dotnet#Azure_Storage_Blobs_Specialized_BlobBaseClient_SetHttpHeadersAsync_Azure_Storage_Blobs_Models_BlobHttpHeaders_Azure_Storage_Blobs_Models_BlobRequestConditions_System_Threading_CancellationToken_) to update the content type without reuploading.  You can call [BlobClient.GetPropertiesAsync](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.specialized.blobbaseclient.getpropertiesasync?view=azure-dotnet#Azure_Storage_Blobs_Specialized_BlobBaseClient_GetPropertiesAsync_Azure_Storage_Blobs_Models_BlobRequestConditions_System_Threading_CancellationToken_) to get the content type.

**Comment by carlmwright** [comment]
> Does anyone have an implemenation of GetContentType()?

In case anyone else wonders this, I originally had my own dictionary that I grabbed them from, but I now use this instead:

https://github.com/samuelneff/MimeTypeMap
