### ISSUE TITLE
[BUG] Azure Search - Cannot $filter by fields containing special characters, even when escaped

### ISSUE THREAD

**Issue by PrimeHydra** [Azure/azure-sdk-for-net#9828]
**Describe the bug**
When a filter query includes special characters that have been escaped with backslashes, as [described in the SDK docs](https://docs.microsoft.com/en-us/azure/search/query-simple-syntax#escaping-search-operators), it does not match fields containing the same text. (Also, single quote ' is apparently escaped by doubling it: ''.)  In this case, the test document contains a field like: 

` "FirmName": "Crazy Charz Inc. ' + - && ! ( ) { } [ ] ^ \" ~ * ? : \\ /"`

**Expected behavior**
The document above should be returned.

**Actual behavior (include Exception or Stack Trace)**
Instead, zero results are returned.

**To Reproduce**

1. Create an index with the document mentioned in the description.
2. Using the SDK, set `SearchParams.Filter` to `search.in(FirmName, 'Crazy Charz Inc. '' \+ \- \&\& \! \( \) \{ \} \[ \] \^ \" \~ \* \? \: \\ \/', '|')`. (That's how the value looks when I inspect in in VS.)
3. Observe that no results are returned (not an error; see SO link below for details on what happens in the Search Explorer with the same query).

**Environment:**
 - Microsoft.Azure.Search v10.1.0
 - Windows 10
 - Search is performed in a .NET Standard 2.0 library and consumed by a .NET Core 3.1 library.
 - Visual Studio 16.4.3

Also see [this SO post](https://stackoverflow.com/questions/60066616/azure-cognitive-search-how-to-filter-by-fields-containing-special-characters). 

Not to be confused with this [feature request](https://github.com/Azure/azure-sdk-for-net/issues/8719); the issue is that the filter doesn't work _even when escaping the characters_, not the need for a character-escaping method. Unless I'm doing something wrong, in which case, please tell me how to pass this test case. Thanks!

**Comment by brjohnstmsft** [comment]
@PrimeHydra I wrote a console app to repro this behavior, and it's not a bug -- you're using the encoding scheme for a different query syntax (Simple query syntax for full-text search, not the OData syntax for filters). I provided more details in my answer on StackOverflow.

**Comment by PrimeHydra** [comment]
Thanks, @brjohnstmsft . Though this was user error, I feel the SDK docs could have made the filter expression character escaping a bit clearer? Three different syntaxes in one request is a lot for search newbies like myself to keep track of. :) Maybe I missed that page in the docs. Appreciate your response.

**Comment by brjohnstmsft** [comment]
@PrimeHydra I agree it isn’t discoverable enough. It’s probably in a note somewhere. I’ll change the filter docs to make it more obvious. 

We’re currently working on a new generation of client libraries for Azure Cognitive Search, and one of our goals is to provide a mechanism for encoding each syntax so you don’t have to deal with it anymore.

**Comment by brjohnstmsft** [comment]
@PrimeHydra I've updated the documentation. The changes should go live some time later today. I added a note at the top of the "simple" and "full Lucene" syntax pages explaining that they're not the same as the filter syntax, then added a section to [here](https://docs.microsoft.com/azure/search/query-odata-filter-orderby-syntax#constants) explaining how string escaping works in OData.

Thanks for reporting this -- your feedback helps us make our service better!

**Comment by yviouswilliamous** [comment]
Hi, I have the same problem with escaping a single quote in a filter expression.

I applied the solution you proposed on the [SO post](https://stackoverflow.com/questions/60066616/azure-cognitive-search-how-to-filter-by-fields-containing-special-characters). I doubled the single quote. But there is no values in the response.

I use the latest version of the API (2020-06-30).

Here is the request I execute from the Azure search explorer : 
`search=revue&$filter=(tags/any(tag: search.in(tag/value,'services d''investissement')))`

Thank you for your answer.

**Comment by brjohnstmsft** [comment]
@yviouswilliamous What is the tag value that you're expecting to match? Note that the default delimiters for `search.in` are comma and space, so your filter is effectively being executed as if it were written this way:

```
$filter=tags/any(tag: tag/value eq 'services' or tag/value eq 'd''investissement')
```

**Comment by yviouswilliamous** [comment]
> @yviouswilliamous What is the tag value that you're expecting to match? Note that the default delimiters for `search.in` are comma and space, so your filter is effectively being executed as if it were written this way:
> 
> ```
> $filter=tags/any(tag: tag/value eq 'services' or tag/value eq 'd''investissement')
> ```

@brjohnstmsft , the tag value I'm expecting to match is **"services d'investissement"**

If I understand well, I should try changing the default delimiter and do something like this `$filter=tags/any(tag: search.in(tag/value,'services d''investissement', '|')) `?

**Comment by brjohnstmsft** [comment]
Yes, or if you really only want to match against one possible value instead of a list of values, just use `eq` instead of `search.in`:

```
$filter=tags/any(tag: tag/value eq 'services d''investissement')
```

**Comment by yviouswilliamous** [comment]
> Yes, or if you really only want to match against one possible value instead of a list of values, just use `eq` instead of `search.in`:
> 
> ```
> $filter=tags/any(tag: tag/value eq 'services d''investissement')
> ```

Thank you, I know how to solve the problem now. I'll use this notation `$filter=tags/any(tag: tag/value eq 'services d''investissement')` or the moment. I'll try to implement `search.in` another time.
