### ISSUE TITLE
[Event Hubs] Please rename migration guide to MigrationGuide.md

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-net#9841]
The migration guide for Event Hubs at one point was named `MigrationGuide.md`
At some point this got renamed to `migration-guide-from-v4.md`

This now results in a broken link in the [quick start for the old package](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-dotnet-standard-getstarted-send) which gets heavy traffic

The title inside the file talks about migration from what to what, so I would suggest we go back to the simpler name of `MigrationGuide.md`

cc @jsquire, @ShivangiReja

**Comment by jsquire** [comment]
This was a change requested by @maggiepint in our document review prior to launch.     Open to taking the change, but deferring to Maggie as the documentation standard owner.

**Comment by ramya-rao-a** [comment]
@jsquire,

I synced with @maggiepint offline, and she is ok with renaming back to the old name to have the broken link fixed.

If we want to have an aka.ms link for this, then that is a decision for another day.
Let's rename the file and have the link fixed.

**Comment by jsquire** [comment]
Roger that; will do.
