### ISSUE TITLE
Microsoft.Azure.Services.AppAuthentication.GetAccessTokenAsync for Azure AAD App Registration

### ISSUE THREAD

**Issue by gverstraete** [Azure/azure-sdk-for-net#9845]
**Query/Question**
We are currently investigation how we can setup an Azure Function with Managed Identity to connect to an API-M instance secured with OAuth2.0 (following this guide: https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-protect-backend-with-aad).

Nevertheless, on the internet we find a lot of solutions stating this could work by using the App Id / App Id Url. I am unable to create a token based on that. Also not on the backend nor the client app registration.

Because all samples are on two legged applications, and this is actually three legged i have following questions:
- Is this possible?
- And if so; how can we implement this.

**Environment:**
 - Microsoft.Azure.Service.AppAuthentication 1.3.1 (+ tested on 1.2.1)
 - .NET Core 2.2
 - Visual Studio 15.9.16

**Comment by anaismiller** [comment]
@gverstraete I am not sure if the three legged approach is possible; however, getting a token with a Managed Identity is as well as with a Service Principal. I'd recommend looking at the documentation in [here](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/service-to-service-authentication#running-the-application-using-managed-identity-or-user-assigned-identity) for examples.

**Comment by gverstraete** [comment]
I checked with the team, and this topic is no longer applicable if we look at it today.

So I will close this issue.
