### ISSUE TITLE
[Storage] Programmatic Managed Disk Accounts

### ISSUE THREAD

**Issue by seanmcc-msft** [Azure/azure-sdk-for-net#9855]
Figure out if it is possible to programmatically create a Managed Disk account.  If so, updated the Storage Contributing.md with instructions, and un-ignore the Storage Managed Disk tests.

**Comment by JimSuplizio** [comment]
Hi @seanmcc-msft, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
