### ISSUE TITLE
DiagnosticScopeValidatingInterceptor: Allow methods with no client calls

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#9857]
We're adding a protected virtual async method that doesn't make any client calls.  `[ForwardsClientCalls]` lets us say that nothing with its name should ever appear, but since no client calls are ever made the interceptor complains that no scopes were created.  We should add something like a `[NoClientCalls]` for niche scenarios like this.

**Comment by pakrym** [comment]
Please reopen if there is still a need.
