### ISSUE TITLE
Event Hub Processor - IoT Twin Change and Lifecycle Events?

### ISSUE THREAD

**Issue by thnk2wn** [Azure/azure-sdk-for-net#9869]
**Query/Question**
Are IoT hub Device Twin change events and Device Lifecycle events supported with Azure.Messaging.EventHubs?

It appears they are not as I'm only seeing Device Telemetry Message events. However [this documentation](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-event-grid-routing-comparison#differences) states:
>"Event Grid can be used for telemetry data but can also report when devices are created, deleted, connected, and disconnected from IoT Hub".

Is there special setup to get this working or does it only work in certain scenarios? I have a sample app modeled after event hub processor samples but `iothub-message-source` system property is always `Telemetry` after even long runs, despite device twins updating and devices connecting and disconnecting.

**Environment:**
 - Name and version of the Library package used: Azure.Messaging.EventHubs 5.0.1, Azure.Messaging.EventHubs.Processor 5.01.1

 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Hosting currently just on Windows 10 dev box. .Net Runtime info:

<pre>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
</pre>

 - IDE and version : Visual Studio Professional Version 16.4.4

**Comment by jsquire** [comment]
Hi @thnk2wn.   We're sorry that you're experiencing difficulties and appreciate you reaching out to bring them to our attention.   If I understand correctly, you're not seeing an expected set of events appear within the Event Hubs service.   With respect to the new Event Hubs client, there would be nothing different or special that you would need to configure; if the events appear in the service, the client will read them.  That said, the documentation and quote that you're referencing refers to Event Grid, not Event Hubs.  Those are two different services.   Is it possible that the data that you're looking for is published to Event Grid and you're attempting to read it from Event Hubs by mistake?

I believe the best folks to assist would be the IOT Hub team, so I've routed this issue for their visibility.   Hopefully, they'll be able to help get things sorted with you.

**Comment by jlian** [comment]
Are you using message routing or event grid integration? 

AFAIK routing has twin change events, event grid doesn't

If so, can you show a screenshot of your message routing settings page? There is setup needed and you need to enable a route that has the data source you want https://stackoverflow.com/questions/46196423/how-to-implement-routes-functionality-for-twin-change-in-azure-iot-hub

Also, I think this sample might be close to what you want to do https://docs.microsoft.com/en-us/samples/azure-samples/iot-hub-notifications-sync-graphdb/iot-hub-notifications-sync-graphdb/

**Comment by thnk2wn** [comment]
@jlian Today we use message routing and that works fine but I'm looking into event grid integration as a possible future alternative here.

If you refer to the link I posted (https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-event-grid-routing-comparison#differences) it does show event grid can also report when devices are "created, deleted, connected, and disconnected from IoT Hub". I'm not seeing any of that, only telemetry messages. Are the docs wrong there? Or are there there additional steps or it only works in cases?

I do see twin change events are noticeably missing from that page so I assume that's not supported with no plans to? I would think the same data sources you can trigger off of via message routing that you could also tap into through the Hub's event grid integration.

**Comment by jlian** [comment]
Did you set up Event Grid integration with those events checked? Can you show your settings page? 
![image](https://user-images.githubusercontent.com/2320572/74198346-fb28ca00-4c15-11ea-8843-288b9856c2ae.png)

Also I didn't even know that you could consume event grid notifications directly with a event hub client - is that what you're doing? Or do you have an event hub handler set up with your event grid?

In terms of twin change events via event grid roadmap, I'd have to dial in @ash2017

**Comment by thnk2wn** [comment]
@jlian I'm not using a subscription, I'm connecting the `EventProcessorClient` directly to the IoT hub's built-in event hub compatible endpoint (IoT Hub Settings -> Build-in endpoints --> Events).

Perhaps therein lies the problem but telemetry messages at least work that way. The subscription requires me to pick and endpoint though so it's similar to IoT hub message routing at that point, albeit with more options. 

Effectively I'm exploring if the IoT hub itself can be the endpoint, tapping into events there by way of its Event Grid integration. We have some a hybrid shift in progress and some on-premise applications and queues that need to react to various events from the IoT hub. If needed we can keep the IoT hub message routing populating Azure Service Bus queues that we can read from on-premise (in Azure today), but I wanted to explore if the storage needed to remain in Azure and be somewhat duplicated on-premise, or if systems could react to hub events more directly when outside of Azure.

**Comment by jlian** [comment]
I'm not sure if I'm being clear. There's configuration on IoT Hub that you have to do to enable non-telemetry events either via routing or event grid. I can't tell if you ever enabled those configs or not. Yes IoT Hub itself can be the endpoint but you must first set it up. 

Did you ever do something like this? 

![image](https://user-images.githubusercontent.com/2320572/74261431-18aa7200-4cb0-11ea-983b-1cfcb0e5bf53.png)

If so can you please show the screenshot in your "Message routing" tab?

Also, if you want to read from IoT Hub's built-in endpoint, you'll have to use routing (and not event grid which sends all that stuff to an event grid subscription), IIRC

**Comment by thnk2wn** [comment]
As mentioned the existing IoT Hub message routing just routed all event types to Service Bus Queues. I didn't setup routing from the IoT hub to an Event Grid (and when I tried I get "There are no Azure Event Hub resources in subscription '<subscription>'."). That might make sense to me if I was routing to another Event Grid endpoint but not the hubs built-in endpoint.

I don't understand your last comment as I am definitely reading from the IoT hub's built-in Event Hub-compatible endpoint directly (no routing, no event grid subscription), but only for telemetry events.

Either routing or event grid subscription doesn't appear it would satisfy the hybrid model inquiry here with on-premise integration. If the IoT hub events have to go to an Azure resource first and then read by something on-premise, that's okay - I'm just trying to determine if an on-premise app can tap directly into each of the IoT hub event types directly without first passing through a routing layer to another Azure resource.

**Comment by jlian** [comment]
I don't understand. Are your clients reading from the Service Bus Queue or the IoT Hub's Event Hub compatible built-in endpoint? Or are you saying that you're reading from SBQ today and would like to change?

> As mentioned the existing IoT Hub message routing just routed all event types to Service Bus Queues.

and

> I don't understand your last comment as I am definitely reading from the IoT hub's built-in Event Hub-compatible endpoint directly (no routing, no event grid subscription), but only for telemetry events. 

are confusing to me because they're conflicting statements. Are you using the message routing feature in IoT Hub or not? I'm saying you *must* use the routing feature if you want the twin change events.

Let's just forget about Event Grid for a minute. I think it would be much more clear if you could just show the settings are in the "Message routing" tab of the IoT Hub, please. Here's an example of what I'm looking for 

![image](https://user-images.githubusercontent.com/2320572/74265888-2cf26d00-4cb8-11ea-90b6-91185f9b08a5.png)

**Comment by jlian** [comment]
Also, do you want device connect/disconnect events?

**Comment by thnk2wn** [comment]
Again, using IoT hub message routing with Service Bus Queues today, evaluating if Event Grid (or other mechanism) would provide a way to receive the same events more directly in a hybrid model from on-premise.

The existing IoT hub message routing to SB queues works fine and nothing has been modified there for this effort in question.  For twin changed events, there's nothing currently I can route to when I want those on-premise. I can't easily push them there, was evaluating more of a pull model and if event grid functionality allowed for a more direct read of telemetry, twin change, and connection events from in-house applications.

I can take it from here, thanks

**Comment by jlian** [comment]
You can get the twin change events directly via IoT hub's built-in endpoint. Just setup routing like this 

![image](https://user-images.githubusercontent.com/2320572/74269118-da1bb400-4cbd-11ea-8f45-ffbfcd1ad003.png)

No event grid or service bus needed, if you can make your clients work with the built-in endpoint

The only thing missing is device connect/disconnect events, which you will need to setup event grid for.

**Comment by thnk2wn** [comment]
You have an "events" endpoint though in those routes. What is that endpoint pointing to? A custom Event Hub endpoint? I can't pick the IoT hub itself as the event endpoint and I have no Event Hub resource created for that. I can create one if it's required; it wasn't for telemetry but if needed for twin change so be it.

**Comment by jlian** [comment]
The events endpoint is the [built-in endpoint](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messages-read-builtin) , which is essentially IoT Hub itself - doesn't require you to create any other Azure resources

**Comment by thnk2wn** [comment]
Ahh, I was clicking on +Add Endpoint rather than the dropdown. Thanks, that worked. Seeing the twin change events now in the event processor. For connection/disconnection I can probably keep the existing event grid subscription that routes to a Service Bus queue or look into event grid setup later.
