### ISSUE TITLE
[Flaky test] WithTimeoutGenericDoesNotThrowsWhenATimeoutDoesNotOccur

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#9872]
```
[xUnit.net 00:00:06.58]     Microsoft.Azure.ServiceBus.UnitTests.TaskExtensionsTests.WithTimeoutGenericDoesNotThrowsWhenATimeoutDoesNotOccur [FAIL]
  X Microsoft.Azure.ServiceBus.UnitTests.TaskExtensionsTests.WithTimeoutGenericDoesNotThrowsWhenATimeoutDoesNotOccur [5s 338ms]
  Error Message:
   There should not have been a timeout exception thrown.
Expected: False
Actual:   True
  Stack Trace:
     at Microsoft.Azure.ServiceBus.UnitTests.TaskExtensionsTests.WithTimeoutGenericDoesNotThrowsWhenATimeoutDoesNotOccur() in D:\a\1\s\sdk\servicebus\Microsoft.Azure.ServiceBus\tests\Infrastructure.Tests\TaskExtensionTests.cs:line 101
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by JoshLove-msft** [comment]
Closing out as this is now being tracked separately.

**Comment by pakrym** [comment]
Where?

**Comment by JoshLove-msft** [comment]
This will be tracked by the service team. /cc @ramya-rao-a

**Comment by pakrym** [comment]
Can we link to an issue? What do we do when tests keep failing?

**Comment by ramya-rao-a** [comment]
Hey @pakrym 

I suggested @JoshLove-msft to close all the issues around flaky tests for the Microsoft.Azure.ServiceBus package. Most of these are over a year old and the tests that were flaky then may or may not be flaky now.

The service team prefers to use their internal workitem tracking system to track this work. So, we will not be having any GitHub issues to link to

I will be working with them to come up with a system to avoid the case of tests failing over long periods of time.

**Comment by pakrym** [comment]
To clarify my question a bit: When I see a flaky task in SB T1 library, where do I file it?

**Comment by ramya-rao-a** [comment]
> When I see a flaky task in SB T1 library, where do I file it?

You wouldnt be filing it. It is the package owner's responsibility to track the flaky tests and have a plan to fix them. And it is my responsibility to ensure that they are aware of this. We currently have a team that are filing GH issues with the test-reliability label for test failures for the packages that the Azure SDK team owns. If the service team is interested in this model, we will have them onboarded. Otherwise, we leave it to them to find a way to manage their tests.
