### ISSUE TITLE
[BUG] LabServices  solution doesn't build

### ISSUE THREAD

**Issue by daviddowning** [Azure/azure-sdk-for-net#9873]
**Describe the bug**
I'm trying to compile the LabServices solution in the https://github.com/Azure/azure-sdk-for-net repository using Visual Studio 2017/2019.

**Expected behavior**
The solution and all projects should build.

**Actual behavior (include Exception or Stack Trace)**
Getting 7423 errors during compilation.  "The type or namespace 'System' could not be found.

**To Reproduce**
Try to compile using VS 2017 or VS 2019.

**Environment:**
Devlopment laptop.
![LabServicesErrors](https://user-images.githubusercontent.com/8891308/74187200-ed1c7e80-4c00-11ea-81e7-2359ed6e1139.png)

**Comment by wantedfast** [comment]
Hi, @daviddowning 
Thanks for reporting this issue. We create a new issue [#9982](https://github.com/Azure/azure-sdk-for-net/issues/9982) to track this. Thanks!
@jongio
