### ISSUE TITLE
Implement Schedule/CancelScheduled batch

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#9874]
Track 1 .NET doesn't have this, but Typescript Track 2 does.
Figure out if there is a reason this wasn't added for Track 1.
Add to Track 2 if it can be added.

**Comment by SeanFeldman** [comment]
Will it be an atomic operation? Sending/receiving a batch is atomic. If scheduling/cancelling will not be atomic, how will you handle partial failures?

**Comment by JoshLove-msft** [comment]
I believe it is atomic as it is supported by the service itself.

Related https://github.com/Azure/azure-sdk-for-net/issues/7921

**Comment by SeanFeldman** [comment]
I was aware that completing messages using a batch of lock tokens was a supported broker operation.
Was not aware of scheduling/completion was supported. @axisc is that supported now?
