### ISSUE TITLE
Add documentation for all methods related to receiving

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#9877]
ServiceBusReceiverClient
ServiceBusReceiverClientOptions
QueueReceiverClient
QueueReceiverClientOptions
SessionReceiverClient
SessionReceiverClientOptions
SubscriptionClient
SubscriptionClientOptions
TransportConsumer

And all dependencies.

**Comment by SeanFeldman** [comment]
Add major types mapping from Track 1 to Track 2?

**Comment by JoshLove-msft** [comment]
> Add major types mapping from Track 1 to Track 2?

This issue is about the inline XML docs. We will probably want to have a migration guide that would include mapping from Track 1 to Track 2.

**Comment by ShivangiReja** [comment]
Closed with https://github.com/Azure/azure-sdk-for-net/pull/10418
