### ISSUE TITLE
ServiceBusException issues

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#9879]
- eliminate unnecessary constructors
- eliminate anything that is only used for EH
- determine whether ctors can be made internal
  - This would make testing across packages more difficult and also make customer testing more difficult if we only expose the protected ctor. These should be fine to leave as public.
- throw correct exceptions for all features being added in Preview 1
- Integrate necessary features of AmqpExceptionHelper(from Track 1) into AmqpError(from EH Track 2)
https://github.com/Azure/azure-sdk-for-net/pull/10000#discussion_r380706470

**Comment by SeanFeldman** [comment]
> determine whether ctors can be made internal

This will make certain testing scenarios not possible.
