### ISSUE TITLE
ConnectionString parsing cleanup

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#9884]
Potentially remove connectionStringBuilder
https://github.com/Azure/azure-sdk-for-net/pull/9842#discussion_r377127281

Add in Validation that entityName matches conn string entity if present in both:
https://github.com/Azure/azure-sdk-for-net/pull/9842#discussion_r377124341

Ensure parity with Track 1 test cases.

**Comment by ShivangiReja** [comment]
Closed with https://github.com/Azure/azure-sdk-for-net/pull/10664
