### ISSUE TITLE
[BUG] Client timeout can mask service issues

### ISSUE THREAD

**Issue by brjohnstmsft** [Azure/azure-sdk-for-net#9891]
**Describe the bug**
This was reported by a customer of Azure Cognitive Search, who was experiencing high latency involuntarily for 48+ hours. They raised a CSS ticket but the service team didn't investigate deeply because their telemetry didn't show any indication of service unavailability or throttling. Upon deeper investigation after escalation, telemetry showed that their requests were being cancelled on the client side after 100 seconds. The customer maintains they are using default .NET SDK timeout (this is using the Track 1 .NET SDK for Azure Cognitive Search, but the same issue could happen with Track 2 .NET SDKs as well.

In addition to hiding the presence of the customer pain from the service team's alerts, the client timeouts also made it very difficult to assess root cause because the requests terminate before any diagnostically useful error could be produced from the service. This is because the service is itself calling another service internally, and uses the same default HttpClient timeout that the SDK uses.

This seems like a potentially common scenario -- Many Azure services are implemented in .NET, and those that forward requests using HttpClient are likely also using the default timeout. For this reason, Azure Core should use a timeout value greater than the default of 100 seconds.

**Expected behavior**
Requests from client libraries should ideally time out after the service does; Definitely after more than 100 seconds (which is likely the default timeout in many services, as it is in Azure Cognitive Search).

**Actual behavior (include Exception or Stack Trace)**
Requests from client libraries time out after 100 seconds.

**To Reproduce**
Service-specific

**Environment:**
Any library that depends on Azure Core.

**Comment by brjohnstmsft** [comment]
FYI @tg-msft @smaine

**Comment by tg-msft** [comment]
@pakrym @KrzysztofCwalina - What do you think about flipping the default Azure.Core timeout from 100s to 120s?

**Comment by pakrym** [comment]
I see how it would make our lives easier but wonder if this is something the customers would want. The typical request shouldn't take this long and if the response would never arrive I would rather client timeout earlier than later.

**Comment by brjohnstmsft** [comment]
@pakrym This should only happen in atypical cases, but when it does, we'd like to be able to diagnose the issue from our telemetry. Otherwise, we can't improve the service to reduce the likelihood of such issues in the future.

If the decision is not to do this in Azure Core, we will advocate strongly to do it in the Track 2 .NET SDK for Search specifically. So the debate ought to be whether you think this could be a broader issue with libraries for other services (something I can only speculate about).

**Comment by pakrym** [comment]
> This should only happen in atypical cases, but when it does, we'd like to be able to diagnose the issue from our telemetry. Otherwise, we can't improve the service to reduce the likelihood of such issues in the future.

I appreciate the desire to get more telemetry but clients waiting for the service to timeout is not the only way to accomplish it. If the case is atypical can't you get the same information just by logging requests that take longer than 60 secs?

> If the decision is not to do this in Azure Core, we will advocate strongly to do it in the Track 2 .NET SDK for Search specifically

Do we know that the service timeout would always kick in or would we make clients wait longer just to get the same client disconnect timeout?

**Comment by brjohnstmsft** [comment]
@pakrym I've scrubbed some details from my initial description of the issue to avoid disclosing internal details of the service, but to summarize -- The reason we're not getting the telemetry we need in this situation is because the API frontend is canceling the request due to client timeout, but the telemetry we need is from another service that hasn't timed out yet. The API frontend in this case is an intermediary, forwarding the request to another service (I'm oversimplifying, but that is the gist). We do guarantee that the timeout of API frontend requests to that service will always be honored.

**Comment by pakrym** [comment]
Closing this as there is currently no plan to increase the Azure.Core default timeout.
