### ISSUE TITLE
Investigate sharing internal code used by both Event Hubs and Service Bus

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#9895]
Service Bus Track 2 is using a copied version of the Event Hubs AMQP wrapper. We should create a new directory and possible shared project for code that can be shared across messaging libraries. We can then compile in the shared files that are needed for each library. We could use a namespace like Azure.Messaging to keep things generic.

**Comment by jsquire** [comment]
There now exists a Messaging section in Azure.Core as well as the Azure.Core.Amqp package which are used for common items.   I believe the majority of code in the EH and SB libraries has now diverged to the point where any benefits of a dedicated effort here are outweighed by the cost.   Closing.
