### ISSUE TITLE
Unify AsyncPageable/Pageable helper classes

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#9896]
Now we have two versions: used by hand-written and generated SDKs

**Comment by annelo-msft** [comment]
When this is addressed, update Paging tutorial in the Azure SDK Development Training program repo:

common-patterns/paging.md

https://github.com/Azure/azure-sdk-pr/pull/267/files

**Comment by annelo-msft** [comment]
Closing as duplicate of https://github.com/Azure/azure-sdk-for-net/issues/32006
