### ISSUE TITLE
[Question] Newtonsoft.Json version mismatch issue where binding redirect is not applicable

### ISSUE THREAD

**Issue by Lingxi-Li** [Azure/azure-sdk-for-net#9898]
We develop an app extension that references LibA which in turns references Microsoft.Rest.ClientRuntime. LibA and ClientRuntime reference different versions of Newtonsoft.Json. 
Passing Newtonsoft.Json object between LibA and ClientRuntime will cause a type mismatch issue. The original app that references LibA uses app-level binding redirect to resolve the issue. However, we cannot adopt this approach, since the app our extension is developed for is not owned by us.

Do you have any suggestion on resolving this issue? I considered building a private ClientRuntime that references the same Newtonsoft.Json as LibA, but is concerned this will cause type mismatch issue within Azure SDKs itself. And we do use other Azure SDKs.

**Comment by AlexGhiondea** [comment]
Which libraries are you working with?

**Comment by Lingxi-Li** [comment]
Resolved with workaround.
