### ISSUE TITLE
DocumentDB as not a service

### ISSUE THREAD

**Issue by tallesl** [Azure/azure-sdk-for-net#990]
*(probably not the best place to post this but here it goes)*

Dear Microsoft,

I have been a good boy all those years playing around with C#, SQL Server and all your goodies.

Yes, it's true that I only do that from 9 to 5 and I don't give much love for you in my spare time, but there's still some love there.

Specially nowadays that you are trying to be the cool kid on the block haging out with [GitHub](https://microsoft.github.io), [StackOverflow](http://blogs.msdn.com/b/ie/archive/2014/12/04/focusing-community-discussions-for-ie-development-on-stackoverflow.aspx) and playing [foundation](http://www.dotnetfoundation.org) just like Apache.

Then you made this new little thing of yours: [DocumentDB](http://azure.microsoft.com/services/documentdb).

Yay! I've being playing with document databases (in my spare time!) for awhile now and so far so good. Now I'll able to have this option for my actual *work*, right?

Not so much. The *as a service* part broke the deal :cry:

Like many places out there, we are a [*Microshop*](https://www.youtube.com/watch?v=gBkDvqIGSaE&t=0m30s) and we only use *stuff* that are hosted inside. We live in our little island. It's our IIS servers and our SQL Servers instances. This is, good or bad, our culture.

So, if I had one wish, just one, would be this: please mighty Microsoft, father of all our tooling, provide us with DocumentDB *as not a service*.

I know, I know that document databases are not a silver bullet. People that treat it as it just got burnt in the end (just look all the MongoDB hate out there).

But here where I work we do all *flavors* of systems. Having another tool in the toolbox would be great (I have two or three systems here already that would be great with a document database).

Sincerely,
Talles

**Comment by diegovinicius** [comment]
:+1:

**Comment by arthur-fernandes** [comment]
:+1:

**Comment by hermsdorff** [comment]
:+1:

**Comment by paulodamasceno** [comment]
+1:

**Comment by mirandajeff** [comment]
:+1:

**Comment by DouglasHenriquees** [comment]
:+1:

**Comment by ValteirJr** [comment]
:+1:

**Comment by paulodamasceno** [comment]
:+1:

**Comment by tuliopimenta** [comment]
:+1:

**Comment by kowsheek** [comment]
:+1:

**Comment by cristianofran** [comment]
:+1:

**Comment by TheSpiderPig** [comment]
Why use microsoft, you can save yourself and your client money by using a free/open source version. I'm not saying MongoDB is the way to go, but you have MANY more options for your database needs.

**Comment by kowsheek** [comment]
True @TheSpiderPig, but off-topic. Having more options is better for the ecosystem.

Also, some of us host everything on Azure and use DocumentDb, but in case we wanted to have a in-house solution, we should have the option.

**Comment by tallesl** [comment]
@TheSpiderPig

There's a whole culture shared by many companies to use only *Microsoft™ Stack™*, the one I currently work for included.

There are many possible reasons for it: fear of other *stacks*, disbelief of open source, making sure the whole tooling plays well with each other, having to interact to a single company for support, etc...

I dislike this attitude of *putting all your eggs in one basket* but that's the reality I can't change.

**Comment by marck010** [comment]
:+1:

**Comment by ryancrawcour** [comment]
You are correct, this is not the best place for this - Instead go to http://feedback.azure.com/forums/263030-documentdb and vote for the feature there. That way the product team is more likely to see the request.

**Comment by pikoslav** [comment]
:+1:

**Comment by bradygaster** [comment]
Closing as @ryancrawcour's link above is the more appropriate place to file the issue.

**Comment by brumano** [comment]
+1:

**Comment by brumano** [comment]
:+1:

**Comment by iamkoch** [comment]
I'm not sold on DDB as of yet. The preview seemed OK, but we had to rip it out of an app after being forced to apply too many hacks to get it to work how we wanted it.

It's a great idea, but nowhere near fully formed yet. That's just my opinion, of course :)

**Comment by ryancrawcour** [comment]
@iamkoch it would be great to know what hacks you were forced in to applying. we obviously have some work to do in these areas to get rid of these. If you would like to provide this feedback directly to us (via email), that would be most valuable. Thanks!
