### ISSUE TITLE
[QUERY] Service Bus client equivalent for Azure.ServiceBus ConnectivityMode

### ISSUE THREAD

**Issue by RemyaRoseTom** [Azure/azure-sdk-for-net#9900]
**Replacement for ConnectivityMode and ServiceBusEnvironment.SystemConnectivity.Mode  in new Microsoft.Azure.ServiceBus.dll **
Microsoft.ServiceBus.Messaging.dll had an option to set the underlying wire-level protocol used to communicate with ServiceBus endpoint using ConnectivityMode for the current application domain
Example :
  ServiceBusEnvironment.SystemConnectivity.Mode = ConnectivityMode.Https;
Is there any methods in Microsoft.Azure.ServiceBus.dll which achieves the same functionality?

**Comment by SeanFeldman** [comment]
There's no identical option as there was in WindowsAzure.ServiceBus, but there is a `TransportType` (AMQP or WebSockets).  When you create a `MessageSender`/`MessageReceiver` (or other clients) you can either specify transport type or provide it via `ServiceBusConnection`. `ServiceBusConnectionStringBuilder` also supports it.

**Comment by nemakam** [comment]
@RemyaRoseTom what is the scenario that you are looking for?
Like @SeanFeldman mentioned, if you want to use HTTPs port (i.e, websocket), then you can change the `TransportType` on the connection.
Closing this issue. Let me know if you have any other question and I'll reopen.

**Comment by pvreddy37** [comment]
hi People. Just need your help and assistance on the below questions.
Earlier we are using session queues  with Microsoft.ServiceBus.Messaging with below approach
1) creating a queue client and we are registering to RegisterSessionHandlerFactory( with a call back and Session handler)
2)  We are inherting IMessageSessionAsyncHandler and overriding OnMessageAsync,OnCloseSessionAsync to handle messages and closing functionality of sessions.

we mainly depend on these member functions (OnMessageAsync,OnCloseSessionAsync ) to write our logic.

Current Problem : we are planning to migrate to use Microsoft.Azure.ServiceBus. and we didn't find an equivalent class or interface with which we can implement and override  (OnMessageAsync,OnCloseSessionAsync ) and write our functionality

Is there any solution for this . or any other alternative.  Thanks in advance

**Comment by nemakam** [comment]
@pvreddy37 
The equivalent of `OnMessageAsync` is `RegisterSessionHandler`.
`OnCloseSessionAsync` doesn't have an equivalent in this library. Could you explain your use case for this method?

**Comment by nemakam** [comment]
And @pvreddy37 , please raise a new issue for a new question like this. The problem you are describing is different from the issue raised here.

**Comment by pvreddy37** [comment]
ok @nemakam

**Comment by CaroleneP** [comment]
Hi, setting TransportType=AmqpWebsockets on service bus connection string does not work on machines with windows with OS version 7, 2008 and 8.1. What is the way to get it working on these machines with the Microsoft.Azure.ServiceBus nuget?

**Comment by SeanFeldman** [comment]
Is opening TCP port [5671/5672](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-faq#what-ports-do-i-need-to-open-on-the-firewall) and avoiding WebSocket an option?

**Comment by CaroleneP** [comment]
@SeanFeldman Our install base is on different customer machines >1500. Out of which 30% are on either Windows 7 or Windows server 2008 or Windows 8.1. It would be impossible to ask the customers to open these ports on their machines. Hence we would like to handle this with code changes on the application side. Is there a way to do this?

**Comment by SeanFeldman** [comment]
@CaroleneP, understand. I only know of the two options already listed above. Will defer to the product group to try and find an alternative.

**Comment by nemakam** [comment]
@CaroleneP , 
are you particular on using .net core? Or does full .net framework work for you? `Microsoft.ServiceBus.Messaging.dll` is the only library which supports HTTPs and newer libraries will not support it going forward.

**Comment by CaroleneP** [comment]
@nemakam Our application is developed using .NET framework. So what do the newer libraries support and why?

**Comment by nemakam** [comment]
Going forward the newer libraries will support Amqp over TCP (port 5671) and Amqp over Websockets (port 443).  AMQP is the protocol we want to adhere to going forward as a messaging service.
At the same time, there is a significant cost to developing & maintaining features geared towards supporting old systems. And given that we do have another library which does support this, we would not be able to prioritize investing into HTTPs support in the newer libraries.
