### ISSUE TITLE
[BUG]AzureServiceTokenProvider doesn't support the connection string for User Assigned identity

### ISSUE THREAD

**Issue by Max9252** [Azure/azure-sdk-for-net#9917]
User Assigned Identity connection string is not supported for AzureServiceTokenProvider as documented. https://docs.microsoft.com/en-us/azure/key-vault/service-to-service-authentication

From the documentation I setted the connection string as RunAs=App;AppId=<User_Assigned_Identity_Client_Id> in my App Service as an app settings

But its throwing the following error:

Unhandled exception. System.ArgumentException: Connection string RunAs=App;AppId=xxxx-xxxx-xxxx-xxxxx; is not valid. Must contain 'TenantId' attribute and it must not be empty.

To Reproduce:
Set the connection string in the app settings of the app service
var azureServiceTokenProvider = new AzureServiceTokenProvider();

**Environment:**
- .NetCore v3.1
- Microsoft.Azure.Services.AppAuthentication v1.4.0
 - Hosting platform: Azure App Service (dotnetcore stack)

**Comment by schaabs** [comment]
@nonik0 Can you take a look at this please.

**Comment by varunsh-msft** [comment]
@Max9252 , I tried this just now using version 1.4 and it worked fine for me. I deployed it to an App Service and was able to use the user-assigned identity. The error you are getting is from an earlier version of App auth library that did not support user-assigned identity. 

Do you get this error on your local development machine? It would be worth trying it out since the error you are getting is a validation error and that code is run before the library tries to fetch the token.

**Comment by Max9252** [comment]
@varunsh-msft Hello, locally I don't get this error but once I deploy the code in my app service and start it again it's throwing this error.

**Comment by varunsh-msft** [comment]
@Max9252 , can you please check the version of the Microsoft.Azure.Services.AppAuthentication.dll? You can download the dll from your app service using Kudu. 

1. Go to https://[yourappservice].scm.azurewebsites.net/DebugConsole
2. Under site/wwwroot/[your app structure] find the Microsoft.Azure.Services.AppAuthentication.dll
3. Click the down arrow to download it. 
4. Right click on the Microsoft.Azure.Services.AppAuthentication.dll file and then Properties
5. Then click "Details" tab and check the product/ file version. This should be **1.4**. 

My hypothesis is that your app service has older version of the library.

**Comment by varunsh-msft** [comment]
@Max9252 , did you get a chance to check this out?

**Comment by Max9252** [comment]
@varunsh-msft yes I was able to test your hypothesis and you're right the DLL had an older version of the library. I'll close this issue since it's done, thank you for your help!
