### ISSUE TITLE
[Feature Request] Allow to specify resourceUri for GetTokenAsync on TokenCredential

### ISSUE THREAD

**Issue by kwaazaar** [Azure/azure-sdk-for-net#9930]
**Library or service name.**
Azure.Core /  Azure.Identity
 
**Is your feature request related to a problem? Please describe.**
I would like to be able to specify a resource for GetTokenAsync on TokenCredential.cs and its derived implementations, especially DefaultAzureCredential. When I can specify resource, I can use it to get tokens for other resources that are protected with AzureAD than just Azure services.

The only option I now have is to use the AzureServiceTokenProvider (or support a similar WWW-Authenticate response header), but I prefer to use these Azure.Identity libraries instead.

Code file: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/TokenCredential.cs

**Comment by jsquire** [comment]
//cc: @schaabs, @pakrym

**Comment by schaabs** [comment]
@kwaazaar Thank you for filing this issue.  The Azure.Identity library is meant to target the [AAD v2.0](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-overview) which no longer uses the resource claim but rather users scopes instead. There are some places in the Identity library where we have to go back and forth between the two, and generally to turn a resourceUri to a scope you can append "/.default" to it (keeping in mind that might result in multiple '/' characters).  We have an internal utility method we use inside the Identity library for this here: 

https://github.com/Azure/azure-sdk-for-net/blob/05998222350d35cd5d695eeead72a5d8d1706576/sdk/identity/Azure.Identity/src/ScopeUtilities.cs#L37-L40

I believe in order for this to work the resource must be setup properly in AAD. I know this is the case for most Azure services, though I'm not sure it will always work with all Microsoft services.

Once you have converted the resourceUri to a string you can use it when calling GetToken like so:

~~~ c#
var credential = new DefaultAzureCredential();

string[] scopes = new string[] { "https://myresource.com/.default" };

AccessToken accessToken = await credential.GetTokenAsync(new TokenRequestContext(scopes));
~~~
