### ISSUE TITLE
Cognitive: Resolve issue of Guidelines-required Models namespace

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#9954]
For Cognitive, the word Models has a specific meaning - i.e. a machine-learned Model.  Providing a Models namespace that isn't about that is likely to be confusing to customers.

**Comment by annelo-msft** [comment]
@KrzysztofCwalina @ctstone

**Comment by annelo-msft** [comment]
Will discuss this with arch board

**Comment by maririos** [comment]
guidelines: https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-method-return

**Comment by tg-msft** [comment]
[Per the guidelines](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-service-models-namespace), we should keep the main namespaces small.  Using `.Models` has the benefit of consistency, but I'd also be curious what in this API would a data scientist consider to be a pre-built model?  I'm thinking things like `RecognizedForm` and `UsReceipt` make sense there.

**Comment by maririos** [comment]
We are going to follow the guidelines here, so leaving the namespace with `Models`
