### ISSUE TITLE
Importing certificates into Azure KeyVault fails due to bad base64 encoding

### ISSUE THREAD

**Issue by twsouthwick** [Azure/azure-sdk-for-net#9963]
**Describe the bug**
I'm wanting to import a certificate into KeyVault created by LetsEncrypt. When I do, it fails with a 400 BadRequest error.

**Expected behavior**
I expect the certificate to be imported with no exceptions.

**Actual behavior (include Exception or Stack Trace)**
```
Azure.RequestFailedException: Service request failed.
Status: 400 (Bad Request)

Content:
{"error":{"code":"BadParameter","message":"The specified Base64-encoded PKCS#12 X.509 certificate content can not be read. Please check if certificate is valid, and is correctly Base64 encoded."}}

Headers:
Cache-Control: no-cache
Pragma: no-cache
Server: Microsoft-IIS/10.0
x-ms-keyvault-region: eastasia
x-ms-request-id: REDACTED
x-ms-keyvault-service-version: 1.1.0.893
x-ms-keyvault-network-info: addr=131.107.159.246;act_addr_fam=InterNetwork;
X-AspNet-Version: REDACTED
X-Powered-By: REDACTED
Strict-Transport-Security: REDACTED
X-Content-Type-Options: REDACTED
Date: Fri, 14 Feb 2020 01:25:43 GMT
Content-Length: 196
Content-Type: application/json; charset=utf-8
Expires: -1

   at Azure.Security.KeyVault.KeyVaultPipeline.SendRequestAsync(Request request, CancellationToken cancellationToken) in C:\Users\tasou\Projects\Software\azure-sdk-for-net\sdk\keyvault\Azure.Security.KeyVault.Shared\src\KeyVaultPipeline.cs:line 240
   at Azure.Security.KeyVault.KeyVaultPipeline.SendRequestAsync[TContent,TResult](RequestMethod method, TContent content, Func`1 resultFactory, CancellationToken cancellationToken, String[] path) in C:\Users\tasou\Projects\Software\azure-sdk-for-net\sdk\keyvault\Azure.Security.KeyVault.Shared\src\KeyVaultPipeline.cs:line 170
   at Azure.Security.KeyVault.Certificates.CertificateClient.ImportCertificateAsync(ImportCertificateOptions importCertificateOptions, CancellationToken cancellationToken) in C:\Users\tasou\Projects\Software\azure-sdk-for-net\sdk\keyvault\Azure.Security.KeyVault.Certificates\src\CertificateClient.cs:line 713
   at McMaster.AspNetCore.LetsEncrypt.AzureKeyVaultCertificateRepository.SaveAsync(X509Certificate2 certificate, CancellationToken cancellationToken) in C:\Users\tasou\Projects\Software\LetsEncrypt\src\LetsEncrypt.Azure\AzureKeyVaultCertificateRepository.cs:line 101
```

**To Reproduce**

```csharp
public async Task SaveAsync(X509Certificate2 certificate, CancellationToken cancellationToken)
{
    var domainName = certificate.GetNameInfo(X509NameType.DnsName, false);
    var exported = certificate.Export(X509ContentType.Pfx);
    var options = new ImportCertificateOptions(NormalizeHostName(domainName), exported);

    try
    {
        await _client.ImportCertificateAsync(options, cancellationToken);

        _logger.LogInformation("Imported certificate into Azure KeyVault for {Domain}", domainName);
    }
    catch (RequestFailedException ex)
    {
        _logger.LogWarning(ex, "Failed to save {Domain} certificate to Azure KeyVault", domainName);
    }
}

/// <summary>
/// Names must follow the regular expression <c>/^[0-9a-zA-Z-]+$/</c>
/// See https://docs.microsoft.com/en-us/rest/api/keyvault/ImportCertificate/ImportCertificate.
/// </summary>
internal static string NormalizeHostName(string hostName) => hostName.Replace(".", "-");
```

**Environment:**
 - Name and version of the Library package used: Azure.Security.KeyVault.Certificates v4.0.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects):
```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.2.103 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
 - IDE and version : Visual Studio 16.4.4

**Comment by twsouthwick** [comment]
I was able to get it to work by modifying the following lines:

https://github.com/Azure/azure-sdk-for-net/blob/d60d77db6ea287478fdd22c4b13fd1c5900be86f/sdk/keyvault/Azure.Security.KeyVault.Certificates/src/ImportCertificateOptions.cs#L74-L78

to look like the following:

```csharp
if (Certificate != null)
{
    json.WriteBase64String(s_valuePropertyNameBytes, Certificate);
}
```

Not sure why there's the custom base64 processing, but it seems to break certificate import.

**Comment by pakrym** [comment]
cc @heaths

**Comment by heaths** [comment]
Most - but seemingly not all, as you found - byte arrays are base64url-encoded, but the REST API does document base64, yes:
* https://docs.microsoft.com/en-us/rest/api/keyvault/importcertificate/importcertificate#request-body

Good catch! However, MergeCertificate isn't so specific:
* https://docs.microsoft.com/en-us/rest/api/keyvault/mergecertificate/mergecertificate#certificatebundle

CertificateBundle's [x5t](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/keyvault/data-plane/Microsoft.KeyVault/stable/7.0/keyvault.json#L4254) does document format as "base64url". [cer](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/keyvault/data-plane/Microsoft.KeyVault/stable/7.0/keyvault.json#L4263) simply shows "byte".

CertificateImportParameters's [value](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/keyvault/data-plane/Microsoft.KeyVault/stable/7.0/keyvault.json#L5140) also does say base64 in the docs.

But CertificateMergeParameters's [x5c](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/keyvault/data-plane/Microsoft.KeyVault/stable/7.0/keyvault.json#L5199) also shows format as "byte".

@RandalliLama can you enumerate which values are base64-encoded vs. base64url-encoded?

/cc @schaabs @jonathandturner @sadasant @chlowell @g2vinay

**Comment by heaths** [comment]
We checked our generation code and `"format": "byte"` should indeed be base64-encoded, not base64url-encoded (separate value).

**Comment by heaths** [comment]
I'll go ahead and make the change because we'll need to fix recorded tests, if that's okay @twsouthwick. I can talk you through how to do the latter if you really want to contribute a PR since we don't have public docs on it yet (we're working on it).

**Comment by twsouthwick** [comment]
Sounds good to me. I was wondering how the tests worked for this :)
