### ISSUE TITLE
Form Recognizer: Design Training Return Types

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#9971]
Re: TrainingResult and TrainingWithLabelsResult:

1. Would there be some polymorphic relationship between these return types?

Yes, we could have all of TrainingInfo, TrainingInputResults, and TrainingErrors (however we call them) on a base type that these two inherit form.  In TextAnalytics we had this for model output types and called it TextAnalyticsResult.  I’d propose FormRecognizerTrainingResult as the name of the base type to be consistent here … @KrzysztofCwalina, would it be ok to have TrainingResult inherit from a base type with a more verbose name?

2. Land on naming for CreatedOn, LastUpdatedOn, Duration

The original CreatedOn is when the user submitted the training request. CompletionTime is equivilent to CreatedOn + Duration.

3. Land on naming for TrainingInputResults/DocumentResults and properties in this.

Since the TotalTrainedPages property is already part of a "TrainingInput" object, why do we need to include the extra "Trained" qualifier? I think we should use (or not use) name qualifiers consistently. See also TrainingInputErrors

FilePath, TotalPages? (We should make it clear in docstrings that this is the total number of pages in the, not the subset that was used for training)

SuccessStatus makes me think this would be a bool, but we have 3 values for this (succeeded, partiallySucceeded, failed). Perhaps ProcessingStatus would be clearer, if a qualifier is needed.

Outcome ?
DocumentTrainingInfo.Name
DocumentTrainingInfo.TotalPages
DocumentTrainingInfo.Errors
DocumentTrainingInfo.Outcome

Let’s think more about this.

**Comment by annelo-msft** [comment]
@ctstone @mayurid

**Comment by krzysztof** [comment]
Please correct the @ mention to the correct Krzysztof

**Comment by annelo-msft** [comment]
Design prototyped. We can reopen this issue or create new ones from UX feedback. @mayurid
