### ISSUE TITLE
Cognitive: How should we separate training and prediction in Cognitive APIs?

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#9972]
Should we separate them the same way across all the cognitive services?

Have a look at Custom Vision and the other services that have training APIs.  Are there patterns that apply across cognitive?

How entry-level vs. ML-terminology-focused should the training APIs be based on our understanding of customers?

If we explicitly decide that there are two different customer groups we are serving with these two APIs, then we it would be OK to use different names, if we cannot come up with one unified naming scheme.

But, if we do have two different distinct customer groups, should we ship two different libraries?

I’d like to work with the service team to understand how their existing customers are using these two different sets of functionalities.  From conversations we’ve had with Chris and Florian, the scenario for using them together is where the data scientists using the train APIs use the analyze APIs to compute the precision and accuracy of their models.  So the naming should be sufficiently aligned that that doesn’t look strange.  But I still think the analyze APIs should be a little more entry-level because our hypothesis is that they’ll also be used by a customer segment without knowledge of ML concepts independently from the training APIs.

I’m not opposed to two different libraries here, but let’s discuss this with the service team.

**Comment by annelo-msft** [comment]
@ctstone @mayurid

**Comment by kinelski** [comment]
The Form Recognizer SDK has shipped on 2020/Aug/20. Training and prediction APIs were split into two different clients in the same package: `FormTrainingClient` and `FormRecognizerClient`. This is an old issue.
