### ISSUE TITLE
[Design] [Form Recognizer | Table Indexer] Implement indexer on ExtractedTable to index into Cells array

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#9975]
## Summary

Tables cells are available in Form Recognizer output in order to use them in application UI, rather than for data analysis.  Given this, providing a table indexer that allows callers to index into a given cell in the table by `row`, `col`, is a more idiomatic approach than having an array of cells users must iterate through to find a given cell.  

One question that arises is how to handle column span and row span.

We should understand prior approaches in BCL/.NET and design an approach for indexing into table cells consistent with these.

The resulting API will likely look like:

```C#
public class ExtractedTable {
    public ExtractedTableCell[] Cells { get; }
    ...
```

See: https://github.com/Azure/azure-sdk-for-net/blob/ce046949f17fc4ceeab5c87beb4750047b983565/sdk/formrecognizer/Azure.AI.FormRecognizer/src/ExtractedTable.cs#L24

## Goals
- Identify examples of table indexers elsewhere in BCL/.NET to understand precedents
- Design an API for indexing into table cells consistent with other BCL/.NET types
- Review design with feature crew and architects
- Implement design

**Comment by annelo-msft** [comment]
@ctstone @mayurid

**Comment by AlexGhiondea** [comment]
@annelo-msft could you please update the title?

**Comment by annelo-msft** [comment]
https://github.com/azure/azure-sdk-for-net/issues/10537 to be done as part of this work.

**Comment by maririos** [comment]
We will like to get more information about the usage of this feature to help shape the design.
Moving to backlog

**Comment by pallavit** [comment]
Closing this, and will reopen if there is a customer need for this feature.
