### ISSUE TITLE
Update Microsoft.Azure.Management.LabServices.Tests to SDK Type 

### ISSUE THREAD

**Issue by wantedfast** [Azure/azure-sdk-for-net#9982]
[PR#6536](https://github.com/Azure/azure-sdk-for-net/pull/6536) update Mgmt SDK project to SDK type. But Microsoft.Azure.Management.LabServices.Tests was missed. The whole solution not working now. Let's update this project to SDK type.

**Replace**
 _Project("{**FAE04EC0-301F-11D3-BF4B-00C04F79EFBC**}") = "Microsoft.Azure.Management.LabServices.Tests", "tests\Microsoft.Azure.Management.LabServices.Tests.csproj", "{DC1024AF-4E20-4E65-9ED8-09CC26385B8B}"_ 

**To** 
_Project("{**9A19103F-16F7-4668-BE54-9A1E7A4F7556**}") = "Microsoft.Azure.Management.LabServices.Tests", "tests\Microsoft.Azure.Management.LabServices.Tests.csproj", "{DC1024AF-4E20-4E65-9ED8-09CC26385B8B}"_
 **At line 6 in Microsoft.Azure.Management.LabServices.sln** file.

**Comment by nickzhums** [comment]
@dingmeng-xue  could you help take a look a this

**Comment by wantedfast** [comment]
Hi @chidozieononiwu ,

Can we update the project GUID according this PR[#6536](https://github.com/Azure/azure-sdk-for-net/pull/6536)

**Comment by chidozieononiwu** [comment]
I guess you can if that makes it build. But PR#6536 did not update that. It just moved the files from the directory `src` to the directory `sdk`. The test project for Labservices has used `ToolsVersion="15.0"` and that GUID before the PR. See [here](https://github.com/chidozieononiwu/azure-sdk-for-net/blob/69f3e5ed36f93e9887d9715ba811512a361f7058/src/SDKs/LabServices/LabServices.sln#L8). @isra-fel do you know if its Ok to update this?

**Comment by wantedfast** [comment]
Since PR [#10656](https://github.com/Azure/azure-sdk-for-net/pull/10565) merged, would close this one.
