### ISSUE TITLE
[FEATURE REQ] Update Microsoft.Rest.ClientRuntime to use Newtonsoft.Json v11.0.2

### ISSUE THREAD

**Issue by snakefoot** [Azure/azure-sdk-for-net#9990]
**Library or service name.**
- [Microsoft.Rest.ClientRuntime](https://www.nuget.org/packages/Microsoft.Rest.ClientRuntime/)
 
**Is your feature request related to a problem? Please describe.**
- Reduce dependencies for NetStandard2.  Newtonsoft.Json v10.0.3 has no NetStandard2-target so it fallback to NetStandard1 dependencies.

**Solution**
- Update to Newtonsoft.Json v11.0.2, or maybe switch to your own new System.Text.Json

**Comment by AlexGhiondea** [comment]
@snakefoot thanks for your suggestion.

We are in the process of updating the client libraries for data plane to follow the [Azure SDK guidelines](https://azure.github.io/azure-sdk/general_introduction.html) and as part of that, we are moving to use `System.Text.Json`.
