### ISSUE TITLE
Cognitive: Standardization of Batch Operations

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#9992]
Does the pattern we established for TextAnalytics work for other Cognitive services like TranslatorText?  Is batching used in Face, Computer Vision, Custom Vision, or QnA Maker?

**Comment by annelo-msft** [comment]
@mayurid @maririos

**Comment by maririos** [comment]
When we talk about pattern we followed in TA, what are the specific points you mean?
Naming?, having single and batch according to language? adding more capabilities to batch (like ability to set more options?)

**Comment by annelo-msft** [comment]
Things including:
- Naming (single vs. batch)
- Having the single-input method return an atomic type.
- Taking an Enumerable of TextInputDocument and returning a <method-name>ResultCollection type.
- Having a convenience method that takes an Enumerable of strings and lets you set the language for the entire collection.
- Having <method-name>ResultCollection have ModelVersion and some metadata (in TA's case, Statistics)
- Having the inner <method-name>Result inherit from a common type that has HasError and a common error type
- Having a customer-settable ID per text input
- Anything we end up doing to hide the ID from customers
- Anything we develop to make it easier to call the method that takes TextInputDocuments.

**Comment by annelo-msft** [comment]
I know @tg-msft has done a bunch of work on Batch APIs for other services since this issue was filed that would be worth evaluating to see if it's relevant here.  Originally, we were not able to reuse batch patterns from storage because they represented batches of operations/transactions whereas in Cognitive we were dealing with batches of data, so the semantics were a bit different.  I am not sure at this point how the APIs and guidance have evolved, so it is worth understanding that to look for opportunities to be consistent across the SDK.

**Comment by pallavit** [comment]
Closing this, and will reopen if we see a customer need.
